In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import torch
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
def prepare_data(csv, batch_size, test_size=0.2):
    
    train, test = train_test_split(csv, test_size=test_size, random_state=42)
    train_dataset = Dataset(train)
    test_dataset = Dataset(test)
    
    train_dataloader = DataLoader(train_dataset, batch_size=batch_size , shuffle=False)
    test_dataloader = DataLoader(test_dataset, batch_size=batch_size , shuffle=False)

    return train_dataloader, test_dataloader

def train(numepch, train_dataloader, model, lossfn, optimizer):
    
  cmodel.train()
  
  for epoch in range(numepch):
    for i, (embs, labels) in enumerate(train_dataloader):
      ax = embs
      ay = labels
      outputs = cmodel(ax)
      loss = lossfn(outputs, ay)

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
    print(f"Epoch [{epoch+1}/{numepch}], Loss: {loss/len(train_dataloader):.10f}")

def test(testdl):
    
    cmodel.eval()
    
    with torch.no_grad():
        correct = 0
        total = 0
        for images, labels in testdl:
            testoutp = cmodel(images)
            predicy = torch.max(testoutp, 1)[1].data.squeeze()
            correct += (predicy == labels).sum().item()
            total += labels.size(0)
        
        accuracy = 100 * correct  / total 
        print(f'Accuracy on test set: {accuracy:.2f}%')
    return accuracy

In [3]:
class Dataset(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]  
        features = torch.tensor(row.iloc[1:].values, dtype=torch.float32) 
        if row.iloc[0] == -1:
            label = torch.tensor(0, dtype=torch.long)
        else: 
            label = torch.tensor(1, dtype=torch.long)
        return features, label

In [4]:
class ClassificationModel_initial(nn.Module):
    def __init__(self):
        super(ClassificationModel_initial, self).__init__()
        self.inputsize = 300
        self.linear1 = nn.Linear(self.inputsize, 100) 
        self.linear2 = nn.Linear(100, 50)
        self.final = nn.Linear(50, 2) 
        self.relu = nn.ReLU()

    def forward(self, emlement):
        a = self.relu(self.linear1(emlement))
        a = self.relu(self.linear2(a))
        a = self.final(a)
        return a

In [5]:
class ClassificationModel_4layers(nn.Module):
    def __init__(self):
        super(ClassificationModel_4layers, self).__init__()
        self.inputsize = 300
        self.linear1 = nn.Linear(self.inputsize, 400) 
        self.linear2 = nn.Linear(400, 200)
        self.linear3 = nn.Linear(200, 100)
        self.linear4 = nn.Linear(100, 50)
        self.final = nn.Linear(50, 2) 
        self.relu = nn.ReLU()

    def forward(self, emlement):
        a = self.relu(self.linear1(emlement))
        a = self.relu(self.linear2(a))
        a = self.relu(self.linear3(a))
        a = self.relu(self.linear4(a))
        a = self.final(a)
        return a

In [6]:
class ClassificationModel_2layers(nn.Module):
    def __init__(self):
        super(ClassificationModel_2layers, self).__init__()
        self.inputsize = 300
        self.linear1 = nn.Linear(self.inputsize, 100) 
        self.final = nn.Linear(100, 2) 
        self.relu = nn.ReLU()

    def forward(self, emlement):
        a = self.relu(self.linear1(emlement))
        a = self.final(a)
        return a

In [7]:
class ClassificationModel_same_neur(nn.Module):
    def __init__(self):
        super(ClassificationModel_same_neur, self).__init__()
        self.inputsize = 300
        self.linear1 = nn.Linear(self.inputsize, 300) 
        self.final = nn.Linear(300, 2) 
        self.relu = nn.ReLU()

    def forward(self, emlement):
        a = self.relu(self.linear1(emlement))
        a = self.final(a)
        return a

In [8]:
w2v_features = pd.read_csv('/kaggle/input/rutwitcorp-features/w2v.csv')
ft_features = pd.read_csv('/kaggle/input/rutwitcorp-features/fasttext.csv')
nn_features = pd.read_csv('/kaggle/input/rutwitcorp-features/nn.csv')

In [12]:
nn_features = nn_features.fillna(0)

In [13]:
w2v_features

,ttype,0,1,2,3,4,5,6,7,8,...,290,291,292,293,294,295,296,297,298,299
0,-1,0.228001,0.630322,0.092418,0.488103,-0.427244,-0.387843,0.049848,0.766664,-0.049325,...,0.095314,0.544863,0.507484,0.034988,0.205440,0.471022,-0.029837,-0.044492,0.541670,-0.204145
1,-1,-0.125850,0.622281,0.495322,-0.018968,-0.292307,-0.774470,-0.105719,1.295264,-0.146767,...,0.447972,0.474673,0.262007,-0.086386,0.358004,0.390512,0.390860,0.083645,0.320615,-0.429494
2,-1,0.239152,0.414813,0.105717,0.470023,0.010107,-0.646937,0.120351,1.041821,-0.387143,...,0.186304,0.542704,0.073912,0.058061,0.256080,0.587694,0.412817,0.126583,-0.050429,-0.320089
3,-1,-0.014056,0.435147,0.178287,0.428631,-0.460142,-0.289358,-0.054438,0.761833,0.079504,...,0.170809,0.398501,0.479410,-0.028344,0.174230,0.282459,-0.050913,-0.022856,0.525792,-0.216345
4,-1,0.007979,0.445018,0.075810,0.225897,-0.017991,-0.615201,0.306581,0.694993,-0.144563,...,0.140964,0.490480,0.278659,0.162972,0.272915,0.424400,0.259505,-0.145519,0.236413,-0.222581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226827,1,-0.035876,0.878943,0.104296,0.728329,-0.353689,-0.439773,0.182505,0.968023,-0.059025,...,0.109289,0.733567,0.296099,0.380783,0.184791,0.515302,0.239793,0.206848,0.279791,-0.010854
226828,1,0.008653,0.499931,0.090878,0.362201,-0.253571,-0.426833,0.203761,0.873196,-0.006452,...,0.087101,0.597502,0.439356,0.232183,0.277183,0.344883,0.127850,-0.055896,0.375737,-0.166386
226829,1,-0.021434,0.584458,0.024416,0.386957,0.022182,-0.709432,0.116442,1.207348,-0.231081,...,0.420685,0.483189,0.214928,0.059376,0.567150,0.874349,0.090339,-0.085642,0.257404,-0.324138
226830,1,0.088621,0.393809,0.013574,0.052699,0.112996,-0.695551,0.067421,0.812738,0.007545,...,0.352681,0.298130,0.335592,0.171954,0.314941,0.462224,0.068494,-0.380729,0.438056,-0.381946
226831,1,0.045262,0.339868,0.266067,0.032905,0.189740,-0.339034,0.383530,0.686437,-0.292317,...,0.198690,0.220075,0.233279,0.074468,0.361979,0.217769,0.144213,0.211297,0.214757,-0.202562

In [14]:
nn_features

,ttype,0,1,2,3,4,5,6,7,8,...,290,291,292,293,294,295,296,297,298,299
0,-1,0.340753,0.031124,0.739497,-0.375235,-0.499968,0.534548,-0.211684,-0.481999,-0.212726,...,0.245932,0.125007,0.351173,-0.316266,-0.789539,-0.517553,-0.131845,-0.381073,0.120151,0.364907
1,-1,-0.690246,-0.010816,-0.058653,0.250485,0.116885,-0.804791,-0.073004,-0.370281,-0.199786,...,0.160127,0.722541,0.172994,-0.169171,-0.537656,-0.054374,0.274572,1.113440,-0.592531,-0.297490
2,-1,-0.367084,-0.176565,-0.455089,-0.055702,0.154182,-0.394134,0.327970,0.470336,-0.372921,...,0.602136,-0.560159,-0.134150,-0.010681,0.224108,0.595275,0.528483,0.097327,-0.227674,0.127470
3,-1,0.042826,-0.418719,0.475656,-0.164247,0.087457,0.572677,0.093745,0.627141,-0.646445,...,0.666362,0.727376,0.416732,-0.785924,-0.849753,0.026444,1.021675,-0.147616,-0.422992,0.484352
4,-1,0.075019,-0.402984,-0.256866,0.167911,0.585712,-0.375480,0.326802,0.312042,0.556814,...,-0.202742,0.076913,-0.219157,-0.010414,0.098259,-0.562676,-0.032315,-0.036927,-0.219010,0.053680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226827,1,-0.270343,-0.086770,0.158084,-0.514566,-0.201240,0.178223,-0.015166,0.413452,-0.046566,...,-0.107139,0.209878,0.674787,-0.176267,-0.068443,-0.201473,-0.334057,0.192961,-0.004670,0.199159
226828,1,-0.193211,-0.248873,0.181928,-0.056868,0.416001,-0.136873,0.180554,-0.186394,0.415592,...,-0.431308,-0.018564,-0.095939,0.088350,0.645534,-0.182684,0.346034,0.608963,-0.177087,-0.061168
226829,1,-0.173667,0.384337,0.185771,-0.043570,0.553976,0.304256,-0.309631,-0.071551,0.212883,...,0.219473,0.127422,-0.670726,0.045611,-0.165252,-0.033079,0.338751,0.544342,-0.161433,0.624336
226830,1,0.565728,-0.994425,-0.303923,0.087832,0.524057,-0.085213,-0.316078,0.337265,0.268820,...,0.148335,0.134011,0.087010,0.015574,0.255143,-0.178976,0.302288,-0.392583,0.296759,-0.128684
226831,1,0.248403,0.029361,0.271873,0.562345,-0.003421,-0.102169,0.017683,0.626830,-0.848586,...,-0.310578,0.464700,-0.158154,-0.407990,0.511735,0.325501,-0.784116,0.400195,0.424611,-0.130965

In [15]:
batch_size = 64
num_epochs = 3

In [16]:
w2v_train, w2v_test = prepare_data(w2v_features, batch_size)
ft_train, ft_test = prepare_data(ft_features, batch_size)
nn_train, nn_test = prepare_data(nn_features, batch_size)

In [17]:
models = [ClassificationModel_initial, ClassificationModel_4layers, ClassificationModel_2layers, ClassificationModel_same_neur]

results_w2v = []
results_ft = []
results_nn = []

In [18]:
for model in models:
    for lr in [0.1, 0.01, 0.001]:
        print(str(model).split('.')[1].rstrip("'>"))
        
        cmodel = model()
        lossfn = nn.CrossEntropyLoss()
        optimizer = torch.optim.Adam(cmodel.parameters(), lr=lr)

        train(num_epochs, w2v_train, cmodel, lossfn, optimizer)
        acc_w2v = test(w2v_test)

        train(num_epochs, ft_train, cmodel, lossfn, optimizer)
        acc_ft = test(ft_test)

        train(num_epochs, nn_train, cmodel, lossfn, optimizer)
        acc_nn = test(nn_test)
        
        results_w2v.append({'model': str(model).split('.')[1].rstrip("'>") , 'learning_rate': lr, 'accuracy': acc_w2v})
        results_ft.append({'model': str(model).split('.')[1].rstrip("'>"), 'learning_rate': lr, 'accuracy': acc_ft})
        results_nn.append({'model': str(model).split('.')[1].rstrip("'>"), 'learning_rate': lr, 'accuracy': acc_nn})

ClassificationModel_initial
Epoch [1/3], Loss: 0.0002294545
Epoch [2/3], Loss: 0.0002488240
Epoch [3/3], Loss: 0.0002420852
Accuracy on test set: 50.88%
Epoch [1/3], Loss: 0.0002420834
Epoch [2/3], Loss: 0.0002420954
Epoch [3/3], Loss: 0.0002420959
Accuracy on test set: 50.88%
Epoch [1/3], Loss: 0.0002420937
Epoch [2/3], Loss: 0.0002420988
Epoch [3/3], Loss: 0.0002420994
Accuracy on test set: 50.88%
ClassificationModel_initial
Epoch [1/3], Loss: 0.0002394351
Epoch [2/3], Loss: 0.0002330937
Epoch [3/3], Loss: 0.0002212281
Accuracy on test set: 63.22%
Epoch [1/3], Loss: 0.0002437336
Epoch [2/3], Loss: 0.0002437390
Epoch [3/3], Loss: 0.0002437436
Accuracy on test set: 50.90%
Epoch [1/3], Loss: 0.0002437597
Epoch [2/3], Loss: 0.0002437593
Epoch [3/3], Loss: 0.0002437594
Accuracy on test set: 50.88%
ClassificationModel_initial
Epoch [1/3], Loss: 0.0002251464
Epoch [2/3], Loss: 0.0002212664
Epoch [3/3], Loss: 0.0002261312
Accuracy on test set: 64.14%
Epoch [1/3], Loss: 0.0002193640
Epoch [2/3], Loss: 0.0002138308
Epoch [3/3], Loss: 0.0002123482
Accuracy on test set: 65.55%
Epoch [1/3], Loss: 0.0002516226
Epoch [2/3], Loss: 0.0002128081
Epoch [3/3], Loss: 0.0001975968
Accuracy on test set: 65.64%
ClassificationModel_4layers
Epoch [1/3], Loss: 0.0002419883
Epoch [2/3], Loss: 0.0002420907
Epoch [3/3], Loss: 0.0002420957
Accuracy on test set: 50.88%
Epoch [1/3], Loss: 0.0002420900
Epoch [2/3], Loss: 0.0002420956
Epoch [3/3], Loss: 0.0002420959
Accuracy on test set: 50.88%
Epoch [1/3], Loss: 0.0002420959
Epoch [2/3], Loss: 0.0002420959
Epoch [3/3], Loss: 0.0002420959
Accuracy on test set: 50.88%
ClassificationModel_4layers
Epoch [1/3], Loss: 0.0002221208
Epoch [2/3], Loss: 0.0002354168
Epoch [3/3], Loss: 0.0002400620
Accuracy on test set: 63.66%
Epoch [1/3], Loss: 0.0002437560
Epoch [2/3], Loss: 0.0002437592
Epoch [3/3], Loss: 0.0002437594
Accuracy on test set: 50.88%
Epoch [1/3], Loss: 0.0002437595
Epoch [2/3], Loss: 0.0002437595
Epoch [3/3], Loss: 0.0002437595
Accuracy on test set: 50.88%
ClassificationModel_4layers
Epoch [1/3], Loss: 0.0002285225
Epoch [2/3], Loss: 0.0002195725
Epoch [3/3], Loss: 0.0002168208
Accuracy on test set: 64.78%
Epoch [1/3], Loss: 0.0002231211
Epoch [2/3], Loss: 0.0002256597
Epoch [3/3], Loss: 0.0002166820
Accuracy on test set: 65.72%
Epoch [1/3], Loss: 0.0002418403
Epoch [2/3], Loss: 0.0002060621
Epoch [3/3], Loss: 0.0001786150
Accuracy on test set: 66.57%
ClassificationModel_2layers
Epoch [1/3], Loss: 0.0002420875
Epoch [2/3], Loss: 0.0002420956
Epoch [3/3], Loss: 0.0002420959
Accuracy on test set: 50.88%
Epoch [1/3], Loss: 0.0002420863
Epoch [2/3], Loss: 0.0002420934
Epoch [3/3], Loss: 0.0002420937
Accuracy on test set: 50.87%
Epoch [1/3], Loss: 0.0006500058
Epoch [2/3], Loss: 0.0010100931
Epoch [3/3], Loss: 0.0006223658
Accuracy on test set: 51.02%
ClassificationModel_2layers
Epoch [1/3], Loss: 0.0002267616
Epoch [2/3], Loss: 0.0002285699
Epoch [3/3], Loss: 0.0002359024
Accuracy on test set: 61.58%
Epoch [1/3], Loss: 0.0002286210
Epoch [2/3], Loss: 0.0002311445
Epoch [3/3], Loss: 0.0002313915
Accuracy on test set: 63.39%
Epoch [1/3], Loss: 0.0002367331
Epoch [2/3], Loss: 0.0002238355
Epoch [3/3], Loss: 0.0002186588
Accuracy on test set: 62.92%
ClassificationModel_2layers
Epoch [1/3], Loss: 0.0002205729
Epoch [2/3], Loss: 0.0002113361
Epoch [3/3], Loss: 0.0002094040
Accuracy on test set: 63.49%
Epoch [1/3], Loss: 0.0002283696
Epoch [2/3], Loss: 0.0002197127
Epoch [3/3], Loss: 0.0002205483
Accuracy on test set: 65.32%
Epoch [1/3], Loss: 0.0002478530
Epoch [2/3], Loss: 0.0002171106
Epoch [3/3], Loss: 0.0001920535
Accuracy on test set: 66.12%
ClassificationModel_same_neur
Epoch [1/3], Loss: 0.0002420339
Epoch [2/3], Loss: 0.0002420933
Epoch [3/3], Loss: 0.0002420958
Accuracy on test set: 50.88%
Epoch [1/3], Loss: 0.0002420992
Epoch [2/3], Loss: 0.0002420950
Epoch [3/3], Loss: 0.0002420959
Accuracy on test set: 50.87%
Epoch [1/3], Loss: 0.0019247018
Epoch [2/3], Loss: 0.0011905341
Epoch [3/3], Loss: 0.0026983300
Accuracy on test set: 51.27%
ClassificationModel_same_neur
Epoch [1/3], Loss: 0.0002467908
Epoch [2/3], Loss: 0.0002514587
Epoch [3/3], Loss: 0.0002505813
Accuracy on test set: 62.27%
Epoch [1/3], Loss: 0.0002262591
Epoch [2/3], Loss: 0.0002408620
Epoch [3/3], Loss: 0.0002351273
Accuracy on test set: 62.96%
Epoch [1/3], Loss: 0.0002309994
Epoch [2/3], Loss: 0.0002170362
Epoch [3/3], Loss: 0.0002232103
Accuracy on test set: 62.65%
ClassificationModel_same_neur
Epoch [1/3], Loss: 0.0002244994
Epoch [2/3], Loss: 0.0002198132
Epoch [3/3], Loss: 0.0002221927
Accuracy on test set: 63.91%
Epoch [1/3], Loss: 0.0002246992
Epoch [2/3], Loss: 0.0002272612
Epoch [3/3], Loss: 0.0002249277
Accuracy on test set: 65.17%
Epoch [1/3], Loss: 0.0002270212
Epoch [2/3], Loss: 0.0001746371
Epoch [3/3], Loss: 0.0001545872
Accuracy on test set: 66.91%

In [19]:
results_w2v

[{'model': 'ClassificationModel_initial',
  'learning_rate': 0.1,
  'accuracy': 50.87618753719664},
 {'model': 'ClassificationModel_initial',
  'learning_rate': 0.01,
  'accuracy': 63.217757400753854},
 {'model': 'ClassificationModel_initial',
  'learning_rate': 0.001,
  'accuracy': 64.1435404589239},
 {'model': 'ClassificationModel_4layers',
  'learning_rate': 0.1,
  'accuracy': 50.87618753719664},
 {'model': 'ClassificationModel_4layers',
  'learning_rate': 0.01,
  'accuracy': 63.65640223069632},
 {'model': 'ClassificationModel_4layers',
  'learning_rate': 0.001,
  'accuracy': 64.77836312738334},
 {'model': 'ClassificationModel_2layers',
  'learning_rate': 0.1,
  'accuracy': 50.87618753719664},
 {'model': 'ClassificationModel_2layers',
  'learning_rate': 0.01,
  'accuracy': 61.580003085943524},
 {'model': 'ClassificationModel_2layers',
  'learning_rate': 0.001,
  'accuracy': 63.493288072828264},
 {'model': 'ClassificationModel_same_neur',
  'learning_rate': 0.1,
  'accuracy': 50.87618753719664},
 {'model': 'ClassificationModel_same_neur',
  'learning_rate': 0.01,
  'accuracy': 62.269931888817865},
 {'model': 'ClassificationModel_same_neur',
  'learning_rate': 0.001,
  'accuracy': 63.90548195825159}]

In [20]:
results_w2v_df = pd.DataFrame(sorted(results_w2v, key=lambda x: x['accuracy'], reverse=True))
results_w2v_df

                            model  learning_rate   accuracy
0     ClassificationModel_4layers          0.001  64.778363
1     ClassificationModel_initial          0.001  64.143540
2   ClassificationModel_same_neur          0.001  63.905482
3     ClassificationModel_4layers          0.010  63.656402
4     ClassificationModel_2layers          0.001  63.493288
5     ClassificationModel_initial          0.010  63.217757
6   ClassificationModel_same_neur          0.010  62.269932
7     ClassificationModel_2layers          0.010  61.580003
8     ClassificationModel_initial          0.100  50.876188
9     ClassificationModel_4layers          0.100  50.876188
10    ClassificationModel_2layers          0.100  50.876188
11  ClassificationModel_same_neur          0.100  50.876188

In [21]:
results_ft_df = pd.DataFrame(sorted(results_ft, key=lambda x: x['accuracy'], reverse=True))
results_ft_df

                            model  learning_rate   accuracy
0     ClassificationModel_4layers          0.001  65.723984
1     ClassificationModel_initial          0.001  65.547645
2     ClassificationModel_2layers          0.001  65.322812
3   ClassificationModel_same_neur          0.001  65.170719
4     ClassificationModel_2layers          0.010  63.391893
5   ClassificationModel_same_neur          0.010  62.957656
6     ClassificationModel_initial          0.010  50.896026
7     ClassificationModel_initial          0.100  50.876188
8     ClassificationModel_4layers          0.100  50.876188
9     ClassificationModel_4layers          0.010  50.876188
10    ClassificationModel_2layers          0.100  50.873983
11  ClassificationModel_same_neur          0.100  50.871779

In [22]:
results_nn_df = pd.DataFrame(sorted(results_nn, key=lambda x: x['accuracy'], reverse=True))
results_nn_df

                            model  learning_rate   accuracy
0   ClassificationModel_same_neur          0.001  66.909868
1     ClassificationModel_4layers          0.001  66.572619
2     ClassificationModel_2layers          0.001  66.118544
3     ClassificationModel_initial          0.001  65.642427
4     ClassificationModel_2layers          0.010  62.917980
5   ClassificationModel_same_neur          0.010  62.646858
6   ClassificationModel_same_neur          0.100  51.268543
7     ClassificationModel_2layers          0.100  51.019463
8     ClassificationModel_initial          0.100  50.876188
9     ClassificationModel_initial          0.010  50.876188
10    ClassificationModel_4layers          0.100  50.876188
11    ClassificationModel_4layers          0.010  50.876188