## Подготовка

Импортируем всё необходимое:

In [1]:
import os
import re
import gc
from tqdm import tqdm
import pickle
import ast
from dataclasses import dataclass, field
    
import pandas as pd
import torchaudio
import IPython
import torch

In [2]:
tqdm.pandas()

In [3]:
from TTS.api import TTS
from TTS.tts.configs.shared_configs import BaseDatasetConfig, BaseAudioConfig

C:\python_venv\venv1_py12\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
from trainer import Trainer, TrainerArgs
from TTS.tts.configs.tacotron2_config import Tacotron2Config
from TTS.tts.configs.shared_configs import CharactersConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.tacotron2 import Tacotron2
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor

In [5]:
device = "cuda" if torch.cuda.is_available() else "cpu"

Загрузим датасет

In [99]:
df = pd.read_csv("data/metadata_RUSLAN_22200.csv", delimiter='|', header=None)
df.columns = ["wav_name", "word"]
df

            wav_name                                               word
0      000000_RUSLAN             С тревожным чувством берусь я за перо.
1      000001_RUSLAN  Кого интересуют признания литературного неудач...
2      000002_RUSLAN                  Что поучительного в его исповеди?
3      000003_RUSLAN           Да и жизнь моя лишена внешнего трагизма.
4      000004_RUSLAN                                Я абсолютно здоров.
...              ...                                                ...
22195  022195_RUSLAN  Мы жаждем совершенства, а вокруг торжествует п...
22196  022196_RUSLAN  Революционер делает попытки установить мировую...
22197  022197_RUSLAN  Он начинает преобразовывать жизнь, достигая ин...
22198  022198_RUSLAN  Допустим, выводит морковь, совершенно неотличи...
22199  022199_RUSLAN  Известно, чем это кончается… Что в этой ситуац...

[22200 rows x 2 columns]

Преобразуем данные к частоте 16 кГц:

In [100]:
DATA_DIR = "data\\RUSLAN"

TARGET_SR = 16000

In [101]:
for file in tqdm(os.listdir(DATA_DIR)):
    file_path = os.path.join(DATA_DIR, file)
    wav, sr = torchaudio.load(file_path)
    if sr == TARGET_SR:
        continue
        
    wav = torchaudio.functional.resample(wav, sr, TARGET_SR)
    torchaudio.save(file_path, wav, TARGET_SR)

  0%|                                                                                        | 0/22200 [00:00<?, ?it/s]C:\python_venv\venv1_py12\Lib\site-packages\torchaudio\_backend\utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(
100%|██████████████████████████████████████████████████████████████████████████| 22200/22200 [00:13<00:00, 1695.13it/s]

Уберём все записи длиннее 10 секунд из данных:

In [6]:
def check_length(wav_name, max_seconds_length):
    file_path = os.path.join(DATA_DIR, wav_name)
    wav, sr = torchaudio.load(file_path)
    return len(wav.flatten()) / sr < max_seconds_length

In [103]:
df = df[df["wav_name"].progress_apply(lambda x: check_length(x + ".wav", 10))]

100%|██████████████████████████████████████████████████████████████████████████| 22200/22200 [00:12<00:00, 1805.08it/s]

Нормализуем тексты:

In [7]:
def is_normalized_text(text):
    if not isinstance(text, str) or text.strip() == '':
        return False
    
    patterns = [
        # Сокращения с точками
        r'\b[а-я]{1,2}\.[а-я]{1,2}\.',
        
        # Инициалы
        r'\b[А-Я]\.\s*[А-Я]\.',
        r'\b[А-Я]\.[А-Я]\.',
        
        # Аббревиатуры из заглавных букв
        r'\b[А-Я]{2,}\b',
        
        # Числа
        r'\d+[\d,.]*\d*',
        
        # Специальные символы (/, №, # и др.)
        r'[/\\№#@]'
    ]
    
    for pattern in patterns:
        if re.search(pattern, text):
            return False
    
    return True

In [105]:
df = df[df["word"].apply(is_normalized_text)]
df["word"] = df["word"].apply(lambda x: re.sub("[^а-яА-Я,.!?]", " ", x))
df["word"] = df["word"].apply(lambda x: re.sub(" +", " " , x.lower()).split())
len(df)

21374

Отделим слова от знаков препинания:

In [106]:
df = df.explode("word")

In [8]:
def split_letters_and_symbols(word):
    symbols = ""
    for i in range(len(word) - 1, -1, -1):
        if word[i].isalpha():
            return word[0:i + 1], symbols

        symbols = word[i] + symbols

    return "", symbols

In [108]:
df["punctuation"] = df["word"].apply(lambda x: split_letters_and_symbols(x)[1])

In [109]:
df["word"] = df["word"].apply(lambda x: split_letters_and_symbols(x)[0])

Возьмём токенизатор из предыдущей лабораторной работы:

In [9]:
class Characters():
    def __init__(self, num_chars):
        self.num_chars = num_chars

In [10]:
class TokensEncoder():
    def __init__(self):
        self.tokens_count = 4
        self.tokens_to_ids = {"<PAD>": 0, "<BOS>": 1, "<EOS>": 2, "<UNK>": 3}
        self.pad_id = 0
        self.use_phonemes = False
        
    
    def fit(self, df_column):
        for index, row in df_column.items():
            for token in row:
                if token not in self.tokens_to_ids:
                    self.tokens_to_ids[token] = self.tokens_count
                    self.tokens_count += 1

        self.ids_to_tokens = {value: key for key, value in self.tokens_to_ids.items()}
        self.characters = Characters(self.tokens_count)

    def transform(self, df_column):
        return df_column.apply(lambda x: [self.tokens_to_ids[token] if token in self.tokens_to_ids else self.tokens_to_ids["<UNK>"] for token in x])

    def transform_one(self, tokens):
        return [self.tokens_to_ids[token] if token in self.tokens_to_ids else self.tokens_to_ids["<UNK>"] for token in tokens]

    def inverse_transform(self, df_column):
        return df_column.apply(lambda x: [self.ids_to_tokens[id] for id in x])

    def inverse_transform_one(self, ids):
        return [self.ids_to_tokens[id] for id in ids]

    def text_to_ids(self, text, language=None):
        while isinstance(text, str):
            try:
                text = pd.eval(text)
            except:
                print(text)
                raise
                

        return [self.tokens_to_ids[token] for token in text]

    def print_logs(self, log_level):
        pass

Напишем функции, добавляющие и удаляющие BOS, EOS и PAD символы:

In [11]:
def add_bos_eos(df_part, column_name):
    df_part[column_name] = df_part[column_name].apply(lambda x: ["<BOS>"] + x + ["<EOS>"])

In [12]:
def add_bos_eos_to_list(word):
    return ["<BOS>"] + word + ["<EOS>"]

In [13]:
def remove_bos_eos_from_list(word):
    while "<BOS>" in word:
        word.remove("<BOS>")
    
    while "<EOS>" in word:
        word.remove("<EOS>")
    
    return word

In [14]:
def remove_bos_eos(df_part, column_name):
    df_part[column_name] = df_part[column_name].apply(remove_bos_eos_from_list)

In [15]:
def remove_pad_from_list(word):
    while "<PAD>" in word:
        word.remove("<PAD>")
    
    return word

In [16]:
def remove_pad(df_part, column_name):
    df_part[column_name] = df_part[column_name].apply(remove_pad_from_list)

И функцию для применения токенизатора:

In [17]:
def train_and_apply_tokens_encoder(tokens_encoder, train_df, val_df, column):
    tokens_encoder.fit(train_df[column])
    train_df[column] = tokens_encoder.transform(train_df[column])
    val_df[column] = tokens_encoder.transform(val_df[column])

Модифицируем класс датасета из предыдущей лабораторной:

In [18]:
class WordsDataset(torch.utils.data.Dataset):
    def __init__(self, df):
        self.df = df
        self.words = [torch.LongTensor(x).to(device) for x in tqdm(df["word"].values)]
        self.allophones = [torch.LongTensor(x).to(device) for x in tqdm(df["allophones"].values)]

    def __len__(self):
        return len(self.df)

    def __getitem__(self, index):
        return self.words[index], self.allophones[index]

И класс для выравнивания длины тензоров в батче:

In [19]:
class WordsPadder():
    def __init__(self, pad_token):
        self.pad_token = pad_token

    def __call__(self, batch):
        words, allophone_sequences = zip(*batch)
        
        padded_words = torch.nn.utils.rnn.pad_sequence(words, padding_value=self.pad_token)
        words_pad_mask = (padded_words == self.pad_token)
        padded_allophone_sequences = torch.nn.utils.rnn.pad_sequence(allophone_sequences, padding_value=self.pad_token)
        allophones_pad_mask = (padded_allophone_sequences == self.pad_token)
        
        return padded_words, padded_allophone_sequences, words_pad_mask.transpose(-1, -2), allophones_pad_mask.transpose(-1, -2)

Модифицируем также класс модели, переводящей последовательность графем в последовательность аллофонов, из предыдущей лабораторной работы:

In [20]:
class Seq2seq(torch.nn.Module):
    def __init__(self, word_tokens_count, allophone_tokens_count, transformer_dim=512, max_seq_len=100, dropout_prob=0.1):
        super().__init__()
        self.max_seq_len = max_seq_len
        self.words_emb = torch.nn.Embedding(word_tokens_count, transformer_dim)
        self.words_positional_encoding = torch.nn.Embedding(self.max_seq_len, transformer_dim)
        self.allophones_emb = torch.nn.Embedding(allophone_tokens_count, transformer_dim)
        self.allophones_positional_encoding = torch.nn.Embedding(self.max_seq_len, transformer_dim)
        self.dropout = torch.nn.Dropout(dropout_prob)
        self.transformer = torch.nn.Transformer(d_model=transformer_dim, dropout=dropout_prob)
        self.linear = torch.nn.Linear(transformer_dim, allophone_tokens_count)
    
    def forward(self, words, allophones, words_pad_mask, allophones_pad_mask):
        words = self.words_emb(words)
        words += self.words_positional_encoding(torch.arange(words.shape[0]).to(device)).unsqueeze(1)
        words = self.dropout(words)
        
        allophones = self.allophones_emb(allophones)
        allophones += self.allophones_positional_encoding(torch.arange(allophones.shape[0]).to(device)).unsqueeze(1)
        allophones = self.dropout(allophones)
        result = self.transformer(words, allophones, tgt_mask=torch.nn.Transformer.generate_square_subsequent_mask(allophones.shape[0]).to(device), src_key_padding_mask=words_pad_mask, tgt_key_padding_mask=allophones_pad_mask)
        return self.linear(result)
    
    def words_to_allophones(self, word, max_length=None):
        if max_length is None:
            max_length = self.max_seq_len
        
        with torch.no_grad():
            allophones = torch.ones((1, word.size(1)), device=device).long()
            finished = torch.zeros(word.size(1), device=device).bool()

            for i in range(0, max_length):
                if finished.all():
                    break
                
                output = self.forward(word, allophones, None, (allophones == 0).transpose(-1, -2))
                
                next_tokens = output.argmax(dim=-1)[output.shape[0] - 1:]
                
                allophones = torch.cat([allophones, next_tokens], dim=0)
                
                finished = finished | (next_tokens.squeeze(0) == 2)
            
            return allophones
    
    def word_to_allophones(self, word):
        allophones = torch.ones((1, 1)).to(device).long()
        while allophones[-1, 0] != 2 and len(allophones) < self.max_seq_len:
            result = self.forward(word, allophones, None, (allophones == 0).transpose(-1, -2))
            allophones = torch.cat([allophones, result.argmax(dim=-1)[result.shape[0] - 1, :].unsqueeze(1)], dim=0)
    
        return allophones

Загрузим модель и токенизаторы, обученные в предыдущей лабораторной работе:

In [21]:
loaded_model = torch.load("model.pt", weights_only=False)
loaded_model.eval()

with open("word_tokens_encoder.pickle", "rb") as file:
    loaded_word_tokens_encoder = pickle.load(file)

with open("allophones_tokens_encoder.pickle", "rb") as file:
    loaded_allophones_tokens_encoder = pickle.load(file)

In [22]:
loaded_model = loaded_model.to(device)

Преобразуем слова в аллофоны:

In [114]:
df["word"] = df["word"].apply(list)
add_bos_eos(df, "word")
df["word"] = loaded_word_tokens_encoder.transform(df["word"])

In [115]:
df["allophones"] = ""
df["allophones"] = df["allophones"].apply(lambda x: [])

In [22]:
def batch_predict(model, dataloader):
    model.eval()
    all_predictions = []
    
    with torch.no_grad():
        for batch in tqdm(dataloader):
            words, _, words_pad_mask, _ = batch
            predictions = model.words_to_allophones(words, 50)
            
            # Конвертируем в numpy и сохраняем
            for i in range(words.size(1)):
                word_seq = words[:, i].cpu().numpy()
                pred_seq = predictions[:, i].cpu().numpy()
                all_predictions.append((word_seq, pred_seq))

            gc.collect()
            torch.cuda.empty_cache()
    
    return all_predictions

In [117]:
ds = WordsDataset(df)
dl = torch.utils.data.DataLoader(ds, batch_size=256, collate_fn=WordsPadder(loaded_word_tokens_encoder.tokens_to_ids["<PAD>"]), shuffle=False)

100%|███████████████████████████████████████████████████████████████████████| 239400/239400 [00:10<00:00, 23347.79it/s]
100%|███████████████████████████████████████████████████████████████████████| 239400/239400 [00:04<00:00, 58762.46it/s]

In [119]:
pred_list = batch_predict(loaded_model, dl)

pred_df = pd.DataFrame(pred_list, columns=["content", "allophones"])

  0%|                                                                                          | 0/936 [00:00<?, ?it/s]C:\python_venv\venv1_py12\Lib\site-packages\torch\nn\functional.py:6041: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(
100%|████████████████████████████████████████████████████████████████████████████████| 936/936 [31:23<00:00,  2.01s/it]

In [121]:
pred_df["content"] = loaded_word_tokens_encoder.inverse_transform(pred_df["content"])
pred_df["allophones"] = loaded_allophones_tokens_encoder.inverse_transform(pred_df["allophones"])

In [123]:
remove_bos_eos(pred_df, "content")
remove_bos_eos(pred_df, "allophones")

In [124]:
remove_pad(pred_df, "content")
remove_pad(pred_df, "allophones")

In [127]:
df = df.reset_index()

Добавим пунктуацию и паузы:

In [129]:
pred_df["wav_name"] = df["wav_name"]
pred_df["punctuation"] = df["punctuation"]

In [139]:
pred_df["allophones"] += pred_df["punctuation"].apply(list)

In [23]:
def get_pause(punctuation):
    if punctuation == ',':
        return [' ', '-']
    
    if punctuation == '.' or punctuation == '?' or punctuation == '!':
        return [' ', '-', '-']

    return [' ']

In [145]:
pred_df["pause"] = pred_df["punctuation"].apply(get_pause)
pred_df["allophones"] += pred_df["pause"]

In [147]:
pred_df = pred_df.groupby("wav_name").agg({"allophones": "sum"}).reset_index()

И преобразуем полученные тексты в последовательности чисел:

In [157]:
new_allophones_encoder = TokensEncoder()
new_allophones_encoder.fit(pred_df["allophones"])
pred_df["allophones"] = new_allophones_encoder.transform(pred_df["allophones"])

In [156]:
with open("new_allophones_encoder.pickle", "wb") as file:
    pickle.dump(new_allophones_encoder, file)

In [158]:
pred_df.to_csv("data/tokenized_allophones_metadata_RUSLAN_22200.csv", sep='|', index=False, header=False)

## Обучение Tacotron2

Загрузим датасет:

In [24]:
pred_df = pd.read_csv("data/tokenized_allophones_metadata_RUSLAN_22200.csv", delimiter='|', header=None)
pred_df

                   0                                                  1
0      000000_RUSLAN  [4, 5, 5, 5, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...
1      000001_RUSLAN  [33, 29, 34, 27, 8, 9, 12, 35, 36, 12, 11, 12,...
2      000002_RUSLAN  [19, 10, 29, 12, 6, 7, 9, 38, 29, 5, 19, 42, 3...
3      000003_RUSLAN  [40, 29, 5, 5, 33, 29, 11, 9, 12, 29, 26, 5, 3...
4      000004_RUSLAN  [25, 12, 26, 5, 6, 27, 6, 7, 9, 27, 38, 4, 27,...
...              ...                                                ...
21369  022195_RUSLAN  [18, 46, 5, 5, 33, 12, 11, 7, 9, 15, 27, 15, 4...
21370  022196_RUSLAN  [11, 12, 13, 27, 39, 20, 26, 17, 11, 35, 8, 6,...
21371  022197_RUSLAN  [27, 16, 5, 5, 12, 6, 7, 8, 9, 16, 29, 19, 12,...
21372  022198_RUSLAN  [40, 29, 38, 5, 24, 36, 42, 18, 54, 9, 32, 13,...
21373  022199_RUSLAN  [12, 28, 43, 44, 4, 16, 22, 54, 9, 32, 19, 12,...

[21374 rows x 2 columns]

Загрузим модель и токенизаторы:

In [25]:
loaded_model = torch.load("model.pt", weights_only=False)
loaded_model.eval()
loaded_model = loaded_model.to(device)

with open("word_tokens_encoder.pickle", "rb") as file:
    loaded_word_tokens_encoder = pickle.load(file)

with open("allophones_tokens_encoder.pickle", "rb") as file:
    loaded_allophones_tokens_encoder = pickle.load(file)

with open("new_allophones_encoder.pickle", "rb") as file:
    loaded_new_allophones_encoder = pickle.load(file)

Зададим специальный класс, последовательно применяющий токенизаторы и Seq2seq модель:

In [26]:
def transform_word(word, word_tokens_encoder, model, allophones_tokens_encoder, new_allophones_encoder):
    word = word.lower()
    tokenized_word = word_tokens_encoder.transform_one(add_bos_eos_to_list(list(word)))
    tokenized_allophones = model.word_to_allophones(torch.LongTensor(tokenized_word).to(device).unsqueeze(1))
    allophones = remove_bos_eos_from_list(allophones_tokens_encoder.inverse_transform_one(tokenized_allophones.flatten().cpu().tolist()))
    return new_allophones_encoder.transform_one(allophones)

In [27]:
def transform_sentence(sentence, word_tokens_encoder, model, allophones_tokens_encoder, new_allophones_encoder):
    sentence = re.sub("[^а-яА-Я,.!?]", " ", sentence)
    words = re.sub(" +", " " , sentence.lower()).split()
    punctuations = [split_letters_and_symbols(word)[1] for word in words]
    words = [split_letters_and_symbols(word)[0] for word in words]
    
    allophones = [transform_word(word, word_tokens_encoder, model, allophones_tokens_encoder, new_allophones_encoder) for word in words]
    pauses = [new_allophones_encoder.transform_one(get_pause(punctuation)) for punctuation in punctuations]
    punctuations = [new_allophones_encoder.transform_one(punctuation) for punctuation in punctuations]

    sentence = []
    for i in range(len(allophones)):
        sentence += allophones[i]
        sentence += punctuations[i]
        sentence += pauses[i]

    return sentence

In [28]:
class SpecialTokenizer():
    def __init__(self, word_tokens_encoder, model, allophones_tokens_encoder, new_allophones_encoder):
        self.word_tokens_encoder = word_tokens_encoder
        self.model = model
        self.allophones_tokens_encoder = allophones_tokens_encoder
        self.new_allophones_encoder = new_allophones_encoder
        
        self.tokens_count = 4
        self.tokens_to_ids = {0: 0, 1: 1, 2: 2, 3: 3}
        self.pad_id = 0
        self.use_phonemes = False
        
    
    def fit(self, df_column):
        for index, row in df_column.items():
            for token in row:
                if token not in self.tokens_to_ids:
                    self.tokens_to_ids[token] = self.tokens_count
                    self.tokens_count += 1

        self.ids_to_tokens = {value: key for key, value in self.tokens_to_ids.items()}
        self.characters = Characters(self.tokens_count)

    def transform(self, df_column):
        return df_column.apply(lambda x: [self.tokens_to_ids[token] if token in self.tokens_to_ids else self.tokens_to_ids["<UNK>"] for token in x])

    def inverse_transform(self, df_column):
        return df_column.apply(lambda x: [self.ids_to_tokens[id] for id in x])

    def text_to_ids(self, text, language=None):
        if type(text) == list:
            return text
        
        if text[0] == '[':
            return ast.literal_eval(text)

        return transform_sentence(text, self.word_tokens_encoder, self.model, self.allophones_tokens_encoder, self.new_allophones_encoder)
        
    def print_logs(self, log_level):
        pass

Будем обучать модель с помощью библиотеки Coqui-TTS. Зададим конфигурацию датасета для модели:

In [29]:
 dataset_config = BaseDatasetConfig(
        formatter="ruslan", meta_file_train="tokenized_allophones_metadata_RUSLAN_22200.csv", path="./data/"
    )

Передадим информацию о наборе представленных символов специальному токенизатору:

In [30]:
tokenizer = SpecialTokenizer(loaded_word_tokens_encoder, loaded_model, loaded_allophones_tokens_encoder, loaded_new_allophones_encoder)
tokenizer.fit(pred_df[1].progress_apply(pd.eval))

100%|███████████████████████████████████████████████████████████████████████████| 21374/21374 [00:46<00:00, 464.49it/s]

In [31]:
tokenizer.text_to_ids("Привет!")

C:\python_venv\venv1_py12\Lib\site-packages\torch\nn\functional.py:6041: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(

[38, 11, 12, 43, 12, 10, 11, 12, 10, 59, 9, 32, 32]

In [32]:
tokenizer.text_to_ids("Привет!")

C:\python_venv\venv1_py12\Lib\site-packages\torch\nn\functional.py:6041: UserWarning: Support for mismatched key_padding_mask and attn_mask is deprecated. Use same type for both instead.
  warnings.warn(

[38, 11, 12, 43, 12, 10, 11, 12, 10, 59, 9, 32, 32]

Зададим первую конфигурацию. Эта конфигурация использовалась в начале обучения (более недели):

In [32]:
config = Tacotron2Config(
        batch_size=64,
        eval_batch_size=16,
        max_decoder_steps=1000,
        num_loader_workers=0,
        num_eval_loader_workers=0,
        run_eval=False,
        test_delay_epochs=-1,
        epochs=1000,
        print_step=25,
        print_eval=False,
        mixed_precision=True,
        output_path="train_data1",
        datasets=[dataset_config],
         test_sentences=[
                "Мне потребовалось довольно много времени, чтобы развить голос, и теперь я не собираюсь молчать.",
                "Будь голосом, а не эхом.",
                "Мне жаль, Дэйв. Боюсь, я не могу этого сделать.",
                "Этот пирог просто великолепен. Он такой вкусный и сочный.",
                "До ноября года.",
            ]
    )

    # INITIALIZE THE AUDIO PROCESSOR
    # Audio processor is used for feature extraction and audio I/O.
    # It mainly serves to the dataloader and the training loggers.
ap = AudioProcessor.init_from_config(config)

    # LOAD DATA SAMPLES
    # Each sample is a list of ```[text, audio_file_path, speaker_name]```
    # You can define your custom sample loader returning the list of samples.
    # Or define your custom formatter and pass it to the `load_tts_samples`.
    # Check `TTS.tts.datasets.load_tts_samples` for more details.
train_samples, eval_samples = load_tts_samples(
    dataset_config,
    eval_split=True,
    eval_split_size=0.1,
)

    # INITIALIZE THE MODEL
    # Models take a config object and a speaker manager as input
    # Config defines the details of the model like the number of layers, the size of the embedding, etc.
    # Speaker manager is used by multi-speaker models.
model = Tacotron2(config, ap, tokenizer, speaker_manager=None)

    # INITIALIZE THE TRAINER
    # Trainer provides a generic API to train all the 🐸TTS models with all its perks like mixed-precision training,
    # distributed training, etc.

Зададим вторую конфигурацию. Эта конфигурация использовалась для продолжения обучения (неделя):

In [33]:
audio_config = BaseAudioConfig(
    sample_rate=16000,
    do_trim_silence=False,
    trim_db=60.0,
    signal_norm=False,
    mel_fmin=0.0,
    mel_fmax=8000,
    spec_gain=1.0,
    log_func="np.log",
    ref_level_db=20,
    preemphasis=0.0,
)

config = Tacotron2Config(
    audio=audio_config,
    run_eval=True,
    test_delay_epochs=-1,
    ga_alpha=0.0,              # Это веса функций потерь такотрона
    decoder_loss_alpha=0.25,   # Это веса функций потерь такотрона
    postnet_loss_alpha=0.25,   # Это веса функций потерь такотрона
    postnet_diff_spec_alpha=0, # Это веса функций потерь такотрона
    decoder_diff_spec_alpha=0, # Это веса функций потерь такотрона
    decoder_ssim_alpha=0,      # Это веса функций потерь такотрона
    postnet_ssim_alpha=0,      # Это веса функций потерь такотрона
    optimizer='Adam',          
    grad_clip=1.0,
    r=2,                       # Это количество фреймов, предсказываемых за раз; меньше -- быстрее сходится!
    max_decoder_steps=500,     # Вот это нужно понижать, чтобы инференс был быстрее
    attention_type="original", # Вот это минорная вариация в архитектуре Такотрона
    double_decoder_consistency=False,     # Это тоже
    epochs=1000,
    batch_size=128,
    eval_batch_size=32,
    lr=1e-5,                              # LR поменьше, чтобы поглубэе спустилося
    lr_scheduler=None,                    # По умолчанию там странный шедулер, чтобы не экспериментировать, лучше старый добрый конст
    print_step=25,
    print_eval=True,
    mixed_precision=False,
    datasets=[dataset_config],
    max_audio_len=160000,                # Чтобы не падало по памяти,если слишком длинная вавка попадает в бач.
    test_sentences=[
                "Мне потребовалось довольно много времени, чтобы развить голос, и теперь я не собираюсь молчать.",
                "Будь голосом, а не эхом.",
                "Мне жаль, Дэйв. Боюсь, я не могу этого сделать.",
                "Этот пирог просто великолепен. Он такой вкусный и сочный.",
                "До ноября года.",
            ]
)

ap = AudioProcessor.init_from_config(config)

    # LOAD DATA SAMPLES
    # Each sample is a list of ```[text, audio_file_path, speaker_name]```
    # You can define your custom sample loader returning the list of samples.
    # Or define your custom formatter and pass it to the `load_tts_samples`.
    # Check `TTS.tts.datasets.load_tts_samples` for more details.
train_samples, eval_samples = load_tts_samples(
    dataset_config,
    eval_split=True,
    eval_split_size=0.1,
)

    # INITIALIZE THE MODEL
    # Models take a config object and a speaker manager as input
    # Config defines the details of the model like the number of layers, the size of the embedding, etc.
    # Speaker manager is used by multi-speaker models.
model = Tacotron2(config, ap, tokenizer, speaker_manager=None)

Эта строчка необходима для продолжения прерванного обучения (в силу смены конфига или непредвиденного выключения компьютера):

In [35]:
model.load_checkpoint(config, "train_data\\run-December-27-2025_12+35AM-0000000\\best_model.pth")

Обучим модель Tacotron2:

In [ ]:
trainer = Trainer(
    TrainerArgs(), config, "train_data", model=model, train_samples=train_samples, eval_samples=eval_samples
)

trainer.fit()

 > Training Environment:
 | > Backend: Torch
 | > Mixed precision: False
 | > Precision: float32
 | > Current device: 0
 | > Num. of GPUs: 1
 | > Num. of CPUs: 20
 | > Num. of Torch Threads: 20
 | > Torch seed: 54321
 | > Torch CUDNN: True
 | > Torch CUDNN deterministic: False
 | > Torch CUDNN benchmark: False
 | > Torch TF32 MatMul: False
 > Start Tensorboard: tensorboard --logdir=train_data\run-December-27-2025_08+25PM-0000000

 > Model has 28272242 parameters

 > EPOCH: 0/999
 --> train_data\run-December-27-2025_08+25PM-0000000
C:\ИТМО\Магистратура\3-й семестр\Синтез речи\coqui-ai-TTS\TTS\tts\datasets\dataset.py:60: UserWarning: torchaudio._backend.utils.info has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. The decoding and encoding capabilities of PyTorch for both audio and video are being consolidated into TorchCodec. Please see https://github.com/pytorch/audio/issues/3902 for more information. It will be removed from the 2.9 release.
  return torchaudio.info(audiopath).num_frames
C:\python_venv\venv1_py12\Lib\site-packages\torchaudio\_backend\soundfile_backend.py:120: UserWarning: torchaudio._backend.common.AudioMetaData has been deprecated. This deprecation is part of a large refactoring effort to transition TorchAudio into a maintenance phase. The decoding and encoding capabilities of PyTorch for both audio and video are being consolidated into TorchCodec. Please see https://github.com/pytorch/audio/issues/3902 for more information. It will be removed from the 2.9 release.
  return AudioMetaData(

 > TRAINING (2025-12-27 20:25:30)

   --> TIME: 2025-12-27 20:25:33 -- STEP: 0/150 -- GLOBAL_STEP: 0
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.477712482213974  (0.477712482213974)
     | > postnet_loss: 0.4226817786693573  (0.4226817786693573)
     | > stopnet_loss: 0.019298231229186058  (0.019298231229186058)
     | > loss: 0.24439679086208344  (0.24439679086208344)
     | > align_error: 0.7512247860431671  (0.7512247860431671)
     | > grad_norm: tensor(0.4610, device='cuda:0')  (tensor(0.4610, device='cuda:0'))
     | > step_time: 2.2001  (2.2000746726989746)
     | > loader_time: 0.5048  (0.504814624786377)

warning: audio amplitude out of range, auto clipped.

   --> TIME: 2025-12-27 20:26:14 -- STEP: 25/150 -- GLOBAL_STEP: 25
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.5001177787780762  (0.4911201858520508)
     | > postnet_loss: 0.4230765998363495  (0.4218352198600769)
     | > stopnet_loss: 0.006265060044825077  (0.009978792592883107)
     | > loss: 0.23706366121768951  (0.23821764528751374)
     | > align_error: 0.6173176765441895  (0.6714037597179412)
     | > grad_norm: tensor(0.1759, device='cuda:0')  (tensor(0.2391, device='cuda:0'))
     | > step_time: 0.9896  (0.7097829055786132)
     | > loader_time: 0.9862  (0.8513325309753418)


   --> TIME: 2025-12-27 20:27:09 -- STEP: 50/150 -- GLOBAL_STEP: 50
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.514593780040741  (0.4984502530097961)
     | > postnet_loss: 0.42627421021461487  (0.4228312003612518)
     | > stopnet_loss: 0.004554674029350281  (0.007789051383733747)
     | > loss: 0.23977167904376984  (0.2381094166636467)
     | > align_error: 0.6370178163051605  (0.648726009726524)
     | > grad_norm: tensor(0.2512, device='cuda:0')  (tensor(0.2476, device='cuda:0'))
     | > step_time: 1.294  (0.9126772546768188)
     | > loader_time: 1.2022  (0.971101107597351)


   --> TIME: 2025-12-27 20:28:17 -- STEP: 75/150 -- GLOBAL_STEP: 75
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5030765533447266  (0.5010001166661581)
     | > postnet_loss: 0.4245142340660095  (0.4221696400642395)
     | > stopnet_loss: 0.003666367381811142  (0.006644663000479338)
     | > loss: 0.23556406795978546  (0.23743710319201153)
     | > align_error: 0.6153015494346619  (0.6376156508922575)
     | > grad_norm: tensor(0.1392, device='cuda:0')  (tensor(0.2190, device='cuda:0'))
     | > step_time: 1.5732  (1.0797404734293616)
     | > loader_time: 1.3718  (1.08093505859375)


   --> TIME: 2025-12-27 20:29:39 -- STEP: 100/150 -- GLOBAL_STEP: 100
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5022186040878296  (0.5019121038913726)
     | > postnet_loss: 0.41675809025764465  (0.4216070717573166)
     | > stopnet_loss: 0.0036393310874700546  (0.005969265860039739)
     | > loss: 0.23338349163532257  (0.2368490605056286)
     | > align_error: 0.5873724222183228  (0.6329221501946445)
     | > grad_norm: tensor(0.1211, device='cuda:0')  (tensor(0.2075, device='cuda:0'))
     | > step_time: 1.6029  (1.2126986336708072)
     | > loader_time: 1.7403  (1.2189906978607183)


   --> TIME: 2025-12-27 20:31:07 -- STEP: 125/150 -- GLOBAL_STEP: 125
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5016429424285889  (0.5027609076499935)
     | > postnet_loss: 0.4125276207923889  (0.42113658380508423)
     | > stopnet_loss: 0.0033181365579366684  (0.00548541149869561)
     | > loss: 0.23186077177524567  (0.23645978510379792)
     | > align_error: 0.5944308638572693  (0.6291666800975796)
     | > grad_norm: tensor(0.1440, device='cuda:0')  (tensor(0.1951, device='cuda:0'))
     | > step_time: 2.112  (1.33408021736145)
     | > loader_time: 1.7018  (1.3184016513824468)


   --> TIME: 2025-12-27 20:33:00 -- STEP: 150/150 -- GLOBAL_STEP: 150
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5231261253356934  (0.5043211587270097)
     | > postnet_loss: 0.42758217453956604  (0.42089706977208463)
     | > stopnet_loss: 0.002596016274765134  (0.005098462756723162)
     | > loss: 0.24027308821678162  (0.236403020521005)
     | > align_error: 0.5861519575119019  (0.6258060562610623)
     | > grad_norm: tensor(0.1980, device='cuda:0')  (tensor(0.1912, device='cuda:0'))
     | > step_time: 2.8536  (1.5296006870269774)
     | > loader_time: 0.987  (1.4341965405146286)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4808539152145386  (0.4808539152145386)
     | > postnet_loss: 0.3391134738922119  (0.3391134738922119)
     | > stopnet_loss: 0.012532695196568966  (0.012532695196568966)
     | > loss: 0.21752454340457916  (0.21752454340457916)
     | > align_error: 0.719860851764679  (0.719860851764679)

   --> STEP: 1
     | > decoder_loss: 0.4604750871658325  (0.4604750871658325)
     | > postnet_loss: 0.3240489661693573  (0.3240489661693573)
     | > stopnet_loss: 0.009914805181324482  (0.009914805181324482)
     | > loss: 0.20604582130908966  (0.20604582130908966)
     | > align_error: 0.6608159244060516  (0.6608159244060516)

   --> STEP: 2
     | > decoder_loss: 0.4555298984050751  (0.4580024927854538)
     | > postnet_loss: 0.31918591260910034  (0.3216174393892288)
     | > stopnet_loss: 0.011318993754684925  (0.010616899468004704)
     | > loss: 0.2049979418516159  (0.20552188158035278)
     | > align_error: 0.6586473882198334  (0.6597316563129425)

   --> STEP: 3
     | > decoder_loss: 0.45715129375457764  (0.45771875977516174)
     | > postnet_loss: 0.31507667899131775  (0.3194371859232585)
     | > stopnet_loss: 0.008803236298263073  (0.010012345078090826)
     | > loss: 0.2018602341413498  (0.20430133243401846)
     | > align_error: 0.7360178828239441  (0.6851603984832764)

   --> STEP: 4
     | > decoder_loss: 0.46688541769981384  (0.46001042425632477)
     | > postnet_loss: 0.3258504569530487  (0.321040503680706)
     | > stopnet_loss: 0.00850688572973013  (0.009635980241000652)
     | > loss: 0.20669084787368774  (0.20489871129393578)
     | > align_error: 0.6061815023422241  (0.6654156744480133)

   --> STEP: 5
     | > decoder_loss: 0.44708937406539917  (0.45742621421813967)
     | > postnet_loss: 0.30887195467948914  (0.31860679388046265)
     | > stopnet_loss: 0.008461128920316696  (0.00940100997686386)
     | > loss: 0.19745145738124847  (0.20340926051139832)
     | > align_error: 0.6438704133033752  (0.6611066222190857)

   --> STEP: 6
     | > decoder_loss: 0.46337732672691345  (0.4584180663029353)
     | > postnet_loss: 0.31861570477485657  (0.3186082790295283)
     | > stopnet_loss: 0.0074855792336165905  (0.009081771519655982)
     | > loss: 0.20298384130001068  (0.20333835730950037)
     | > align_error: 0.5959289073944092  (0.6502436697483063)

   --> STEP: 7
     | > decoder_loss: 0.46861058473587036  (0.45987414036478313)
     | > postnet_loss: 0.3167620003223419  (0.3183445249285017)
     | > stopnet_loss: 0.006672055926173925  (0.008737526434872831)
     | > loss: 0.20301520824432373  (0.2032921931573323)
     | > align_error: 0.5815878212451935  (0.6404356913907188)

   --> STEP: 8
     | > decoder_loss: 0.4656473398208618  (0.460595790296793)
     | > postnet_loss: 0.3174237012863159  (0.31822942197322845)
     | > stopnet_loss: 0.007624210324138403  (0.008598361921031028)
     | > loss: 0.20339196920394897  (0.20330466516315937)
     | > align_error: 0.5774258673191071  (0.6325594633817673)

   --> STEP: 9
     | > decoder_loss: 0.46438685059547424  (0.4610170192188687)
     | > postnet_loss: 0.31915581226348877  (0.31833235422770184)
     | > stopnet_loss: 0.006894825957715511  (0.008409080147329304)
     | > loss: 0.20278048515319824  (0.20324642293983036)
     | > align_error: 0.594437301158905  (0.628323667579227)

   --> STEP: 10
     | > decoder_loss: 0.4942783713340759  (0.4643431544303894)
     | > postnet_loss: 0.33380892872810364  (0.319880011677742)
     | > stopnet_loss: 0.005691096186637878  (0.008137281751260161)
     | > loss: 0.21271292865276337  (0.20419307351112365)
     | > align_error: 0.5886144042015076  (0.6243527412414551)

   --> STEP: 11
     | > decoder_loss: 0.47762438654899597  (0.4655505391684445)
     | > postnet_loss: 0.325582891702652  (0.3203984553163702)
     | > stopnet_loss: 0.006018307525664568  (0.00794464773075147)
     | > loss: 0.20682013034820557  (0.20443189685994928)
     | > align_error: 0.5960822701454163  (0.6217826984145425)

   --> STEP: 12
     | > decoder_loss: 0.47126007080078125  (0.46602633347113925)
     | > postnet_loss: 0.31705307960510254  (0.3201196740070979)
     | > stopnet_loss: 0.008063598535954952  (0.007954560297851762)
     | > loss: 0.20514188706874847  (0.20449106271068254)
     | > align_error: 0.5898586809635162  (0.6191223636269569)

   --> STEP: 13
     | > decoder_loss: 0.4638053774833679  (0.46585549070284915)
     | > postnet_loss: 0.3183300495147705  (0.3199820105846112)
     | > stopnet_loss: 0.005778574384748936  (0.007787176766074621)
     | > loss: 0.20131243765354156  (0.20424655309090248)
     | > align_error: 0.588547021150589  (0.6167704142056979)

   --> STEP: 14
     | > decoder_loss: 0.4673461616039276  (0.46596196719578337)
     | > postnet_loss: 0.3167957663536072  (0.319754421710968)
     | > stopnet_loss: 0.005200141575187445  (0.007602388538154108)
     | > loss: 0.20123562216758728  (0.20403148659637996)
     | > align_error: 0.555870532989502  (0.6124204226902553)

   --> STEP: 15
     | > decoder_loss: 0.4715341329574585  (0.46633344491322837)
     | > postnet_loss: 0.32371485233306885  (0.3200184504191081)
     | > stopnet_loss: 0.005160565488040447  (0.007439600334813197)
     | > loss: 0.20397281646728516  (0.20402757525444032)
     | > align_error: 0.5897644758224487  (0.6109100262324015)

   --> STEP: 16
     | > decoder_loss: 0.4706827700138092  (0.46660527773201466)
     | > postnet_loss: 0.3149169683456421  (0.31969960778951645)
     | > stopnet_loss: 0.005303708836436272  (0.00730610711616464)
     | > loss: 0.20170363783836365  (0.20388232916593552)
     | > align_error: 0.6080056428909302  (0.6107285022735596)

   --> STEP: 17
     | > decoder_loss: 0.4775329530239105  (0.4672480821609497)
     | > postnet_loss: 0.32522302865982056  (0.3200245148995343)
     | > stopnet_loss: 0.0050504812970757484  (0.0071734232444535286)
     | > loss: 0.20573946833610535  (0.20399157264653375)
     | > align_error: 0.559767097234726  (0.6077307725653929)

   --> STEP: 18
     | > decoder_loss: 0.47450318932533264  (0.4676511436700821)
     | > postnet_loss: 0.3185141384601593  (0.31994060509734684)
     | > stopnet_loss: 0.005559222307056189  (0.00708374541459812)
     | > loss: 0.2038135528564453  (0.2039816826581955)
     | > align_error: 0.6047637760639191  (0.6075659394264221)

   --> STEP: 19
     | > decoder_loss: 0.47361069917678833  (0.4679648044862245)
     | > postnet_loss: 0.3179050385951996  (0.31983347001828644)
     | > stopnet_loss: 0.005090831313282251  (0.00697885519873939)
     | > loss: 0.2029697597026825  (0.20392842355527377)
     | > align_error: 0.6020696759223938  (0.6072766623998943)

   --> STEP: 20
     | > decoder_loss: 0.4679983854293823  (0.46796648353338244)
     | > postnet_loss: 0.3156227767467499  (0.31962293535470965)
     | > stopnet_loss: 0.004718384705483913  (0.006865831674076617)
     | > loss: 0.20062367618083954  (0.20376318618655204)
     | > align_error: 0.6234951317310333  (0.6080875858664513)

   --> STEP: 21
     | > decoder_loss: 0.4648497998714447  (0.4678180700256711)
     | > postnet_loss: 0.31152525544166565  (0.3192373315493266)
     | > stopnet_loss: 0.00419298792257905  (0.006738553400195781)
     | > loss: 0.1982867568731308  (0.2035024038382939)
     | > align_error: 0.5619149208068848  (0.6058888875302815)

   --> STEP: 22
     | > decoder_loss: 0.4676147997379303  (0.46780883046713745)
     | > postnet_loss: 0.3154779076576233  (0.31906644864515826)
     | > stopnet_loss: 0.005071790423244238  (0.006662791446697983)
     | > loss: 0.20084497332572937  (0.20338161154226822)
     | > align_error: 0.6264570951461792  (0.6068238060582768)

   --> STEP: 23
     | > decoder_loss: 0.43834906816482544  (0.4665279712366021)
     | > postnet_loss: 0.3039973974227905  (0.3184112725050553)
     | > stopnet_loss: 0.004764425568282604  (0.006580253799810358)
     | > loss: 0.19035103917121887  (0.20281506491744)
     | > align_error: 0.5672025084495544  (0.6051011409448541)

   --> STEP: 24
     | > decoder_loss: 0.47401976585388184  (0.46684012934565544)
     | > postnet_loss: 0.31984972953796387  (0.3184712082147598)
     | > stopnet_loss: 0.004564277827739716  (0.006496254800974081)
     | > loss: 0.20303165912628174  (0.20282408967614174)
     | > align_error: 0.5805993676185608  (0.6040802337229253)

   --> STEP: 25
     | > decoder_loss: 0.4743531048297882  (0.4671406483650207)
     | > postnet_loss: 0.3169698417186737  (0.3184111535549164)
     | > stopnet_loss: 0.0038827802054584026  (0.0063917158171534535)
     | > loss: 0.20171351730823517  (0.20277966678142548)
     | > align_error: 0.5595558285713196  (0.6022992575168611)

   --> STEP: 26
     | > decoder_loss: 0.4475889503955841  (0.46638865998158086)
     | > postnet_loss: 0.3039036989212036  (0.3178531745305428)
     | > stopnet_loss: 0.004648752976208925  (0.006324678784809434)
     | > loss: 0.19252191483974457  (0.2023851378605916)
     | > align_error: 0.5480841398239136  (0.6002140606825169)

   --> STEP: 27
     | > decoder_loss: 0.4439239501953125  (0.46555663369320055)
     | > postnet_loss: 0.30109572410583496  (0.3172325282185166)
     | > stopnet_loss: 0.004069272428750992  (0.006241145216066528)
     | > loss: 0.19032418727874756  (0.20193843598718997)
     | > align_error: 0.5422501564025879  (0.5980672494128898)

   --> STEP: 28
     | > decoder_loss: 0.4496201276779175  (0.4649874727640833)
     | > postnet_loss: 0.3043396472930908  (0.31677206818546566)
     | > stopnet_loss: 0.004096142947673798  (0.006164537992195359)
     | > loss: 0.19258609414100647  (0.20160442377839768)
     | > align_error: 0.5663546323776245  (0.5969346559473446)

   --> STEP: 29
     | > decoder_loss: 0.44557034969329834  (0.4643179167961252)
     | > postnet_loss: 0.3001132309436798  (0.3161976255219558)
     | > stopnet_loss: 0.0037634032778441906  (0.006081740243424629)
     | > loss: 0.19018429517745972  (0.20121062624043431)
     | > align_error: 0.5413054823875427  (0.5950164085832136)

   --> STEP: 30
     | > decoder_loss: 0.444947212934494  (0.46367222666740415)
     | > postnet_loss: 0.3009204864501953  (0.31568838755289713)
     | > stopnet_loss: 0.003120279870927334  (0.005983024897674719)
     | > loss: 0.18958720564842224  (0.20082317888736725)
     | > align_error: 0.534164696931839  (0.5929880181948344)

   --> STEP: 31
     | > decoder_loss: 0.4446774423122406  (0.46305949168820537)
     | > postnet_loss: 0.3033556342124939  (0.3152905567999809)
     | > stopnet_loss: 0.004145145881921053  (0.005923738477811698)
     | > loss: 0.1911534070968628  (0.2005112507650929)
     | > align_error: 0.559970885515213  (0.5919229493987176)

   --> STEP: 32
     | > decoder_loss: 0.4508660137653351  (0.46267844550311565)
     | > postnet_loss: 0.30569615960121155  (0.31499073188751936)
     | > stopnet_loss: 0.004089114721864462  (0.005866406485438347)
     | > loss: 0.19322966039180756  (0.20028370106592774)
     | > align_error: 0.5315145254135132  (0.5900351861491799)

   --> STEP: 33
     | > decoder_loss: 0.4493637979030609  (0.46227497133341705)
     | > postnet_loss: 0.30486857891082764  (0.31468399997913477)
     | > stopnet_loss: 0.004188545048236847  (0.0058155621994625435)
     | > loss: 0.19274663925170898  (0.20005530525337567)
     | > align_error: 0.5459400415420532  (0.5886989696459337)

   --> STEP: 34
     | > decoder_loss: 0.45528557896614075  (0.4620694009696736)
     | > postnet_loss: 0.30705198645591736  (0.31445952899315777)
     | > stopnet_loss: 0.0035479713696986437  (0.0057488683515283115)
     | > loss: 0.19413235783576965  (0.19988110091756373)
     | > align_error: 0.5636341571807861  (0.5879617692793117)

   --> STEP: 35
     | > decoder_loss: 0.45253777503967285  (0.461797068800245)
     | > postnet_loss: 0.30508431792259216  (0.31419166581971303)
     | > stopnet_loss: 0.0037223617546260357  (0.005690968163045389)
     | > loss: 0.19312788546085358  (0.19968815190451486)
     | > align_error: 0.5342484712600708  (0.5864271036216191)

   --> STEP: 36
     | > decoder_loss: 0.4593341648578644  (0.46172865480184555)
     | > postnet_loss: 0.30957213044166565  (0.31406334539254505)
     | > stopnet_loss: 0.00391763262450695  (0.005641708842530433)
     | > loss: 0.1961442083120346  (0.19958970902694595)
     | > align_error: 0.6342093348503113  (0.5877543878224161)

   --> STEP: 37
     | > decoder_loss: 0.45107612013816833  (0.461440748459584)
     | > postnet_loss: 0.3059843182563782  (0.3138449933077838)
     | > stopnet_loss: 0.0037680661771446466  (0.00559106985157406)
     | > loss: 0.19303317368030548  (0.19941250536892866)
     | > align_error: 0.5192666053771973  (0.585903366675248)

   --> STEP: 38
     | > decoder_loss: 0.44093745946884155  (0.46090118822298554)
     | > postnet_loss: 0.3001050353050232  (0.3134834154656059)
     | > stopnet_loss: 0.0033044784795492887  (0.005530896394415514)
     | > loss: 0.18856510519981384  (0.19912704746974141)
     | > align_error: 0.5510632991790771  (0.5849865227937698)

   --> STEP: 39
     | > decoder_loss: 0.4532587230205536  (0.4607052275767693)
     | > postnet_loss: 0.30789506435394287  (0.3133401244114607)
     | > stopnet_loss: 0.0036425860598683357  (0.005482478180709176)
     | > loss: 0.19393104314804077  (0.1989938165896978)
     | > align_error: 0.5463591814041138  (0.583996078142753)

   --> STEP: 40
     | > decoder_loss: 0.4505672752857208  (0.4604517787694931)
     | > postnet_loss: 0.30656203627586365  (0.31317067220807077)
     | > stopnet_loss: 0.0032160773407667875  (0.005425818159710616)
     | > loss: 0.19249840080738068  (0.19883143119513988)
     | > align_error: 0.5845741331577301  (0.5840105295181275)

   --> STEP: 41
     | > decoder_loss: 0.44132769107818604  (0.4599853376062905)
     | > postnet_loss: 0.29907599091529846  (0.3128268994936129)
     | > stopnet_loss: 0.0038481890223920345  (0.005387339400263821)
     | > loss: 0.1889491081237793  (0.1985903989251067)
     | > align_error: 0.5044807195663452  (0.5820707780558888)

   --> STEP: 42
     | > decoder_loss: 0.446035236120224  (0.4596531923328127)
     | > postnet_loss: 0.3023335039615631  (0.31257705674284986)
     | > stopnet_loss: 0.0034271879121661186  (0.005340669126737686)
     | > loss: 0.19051937758922577  (0.19839823175044285)
     | > align_error: 0.5797181129455566  (0.5820147622199284)

   --> STEP: 43
     | > decoder_loss: 0.4445033073425293  (0.45930086942606196)
     | > postnet_loss: 0.30146166682243347  (0.31231855930284014)
     | > stopnet_loss: 0.0030982967000454664  (0.0052885209307680986)
     | > loss: 0.18958954513072968  (0.19819337857324024)
     | > align_error: 0.5517825186252594  (0.5813116867874942)

   --> STEP: 44
     | > decoder_loss: 0.46258023381233215  (0.4593754004348408)
     | > postnet_loss: 0.31049811840057373  (0.31227718564597046)
     | > stopnet_loss: 0.0028707340825349092  (0.005233571229671889)
     | > loss: 0.196140319108963  (0.1981467181308703)
     | > align_error: 0.5512535870075226  (0.5806285481561312)

   --> STEP: 45
     | > decoder_loss: 0.454586386680603  (0.45926897790696886)
     | > postnet_loss: 0.3090853989124298  (0.3122062570518918)
     | > stopnet_loss: 0.003498212667182088  (0.0051950077060610046)
     | > loss: 0.19441615045070648  (0.19806381662686665)
     | > align_error: 0.5529764294624329  (0.5800140566296045)

   --> STEP: 46
     | > decoder_loss: 0.4462658166885376  (0.4589863004891769)
     | > postnet_loss: 0.30101102590560913  (0.31196288246175524)
     | > stopnet_loss: 0.003358082612976432  (0.005155074551863514)
     | > loss: 0.1901772916316986  (0.19789237043131952)
     | > align_error: 0.532780647277832  (0.5789872433828268)

   --> STEP: 47
     | > decoder_loss: 0.44379907846450806  (0.45866316810567326)
     | > postnet_loss: 0.3031528890132904  (0.311775435792639)
     | > stopnet_loss: 0.004153655841946602  (0.005133767770801452)
     | > loss: 0.19089163839817047  (0.19774341868593337)
     | > align_error: 0.56719571352005  (0.5787363597687252)

   --> STEP: 48
     | > decoder_loss: 0.44608011841773987  (0.4584010212371747)
     | > postnet_loss: 0.30123576521873474  (0.31155585932234936)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.37681374044129345 (+0.0)
     | > avg_decoder_loss: 0.45456383354736096 (+0.0)
     | > avg_postnet_loss: 0.3083062388680199 (+0.0)
     | > avg_stopnet_loss: 0.004569064776384921 (+0.0)
     | > avg_loss: 0.19528658349405636 (+0.0)
     | > avg_align_error: 0.5725436526717561 (+0.0)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_151.pth

 > EPOCH: 1/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 20:35:07)

   --> TIME: 2025-12-27 20:35:45 -- STEP: 24/150 -- GLOBAL_STEP: 175
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.5009249448776245  (0.4933937614162763)
     | > postnet_loss: 0.42490047216415405  (0.4247812206546466)
     | > stopnet_loss: 0.0063040959648787975  (0.01004706604483848)
     | > loss: 0.23776045441627502  (0.2395908087491989)
     | > align_error: 0.6948051452636719  (0.6745311617851257)
     | > grad_norm: tensor(0.1636, device='cuda:0')  (tensor(0.2743, device='cuda:0'))
     | > step_time: 0.8497  (0.6290544768174489)
     | > loader_time: 0.956  (0.9229960838953654)


   --> TIME: 2025-12-27 20:36:37 -- STEP: 49/150 -- GLOBAL_STEP: 200
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5046056509017944  (0.4993721794108955)
     | > postnet_loss: 0.41998836398124695  (0.4241905844941431)
     | > stopnet_loss: 0.00512990215793252  (0.007800040452988174)
     | > loss: 0.23627841472625732  (0.23869072995623764)
     | > align_error: 0.5861732959747314  (0.6496358507749984)
     | > grad_norm: tensor(0.1621, device='cuda:0')  (tensor(0.2623, device='cuda:0'))
     | > step_time: 1.3367  (0.8542422226497104)
     | > loader_time: 1.0498  (0.9606477192470005)


   --> TIME: 2025-12-27 20:37:41 -- STEP: 74/150 -- GLOBAL_STEP: 225
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5076051354408264  (0.5018937426644403)
     | > postnet_loss: 0.43097272515296936  (0.423171793689599)
     | > stopnet_loss: 0.00397219555452466  (0.00664376110669125)
     | > loss: 0.2386166751384735  (0.23791014463514895)
     | > align_error: 0.6050152778625488  (0.6384198838794553)
     | > grad_norm: tensor(0.2318, device='cuda:0')  (tensor(0.2281, device='cuda:0'))
     | > step_time: 1.427  (1.031114236728565)
     | > loader_time: 1.216  (1.044506978344273)


   --> TIME: 2025-12-27 20:39:03 -- STEP: 99/150 -- GLOBAL_STEP: 250
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5105628371238708  (0.5026559170448421)
     | > postnet_loss: 0.4256083369255066  (0.4223818080593842)
     | > stopnet_loss: 0.003448997624218464  (0.005966398512210812)
     | > loss: 0.23749178647994995  (0.23722582965186148)
     | > align_error: 0.6054105162620544  (0.633444558490406)
     | > grad_norm: tensor(0.2196, device='cuda:0')  (tensor(0.2103, device='cuda:0'))
     | > step_time: 1.7045  (1.1650359726915456)
     | > loader_time: 1.6914  (1.2127989446273955)


   --> TIME: 2025-12-27 20:40:31 -- STEP: 124/150 -- GLOBAL_STEP: 275
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5048500895500183  (0.5033135046401335)
     | > postnet_loss: 0.4147064983844757  (0.4217090517763169)
     | > stopnet_loss: 0.003652668558061123  (0.005476528987093199)
     | > loss: 0.2335418164730072  (0.2367321680630407)
     | > align_error: 0.6156564950942993  (0.6293686342335514)
     | > grad_norm: tensor(0.1116, device='cuda:0')  (tensor(0.1940, device='cuda:0'))
     | > step_time: 2.0604  (1.2846475628114515)
     | > loader_time: 1.7377  (1.3224795806792473)


   --> TIME: 2025-12-27 20:42:24 -- STEP: 149/150 -- GLOBAL_STEP: 300
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5351361632347107  (0.5045678515562279)
     | > postnet_loss: 0.4349825978279114  (0.42124393422331574)
     | > stopnet_loss: 0.002517404966056347  (0.0050938930893754415)
     | > loss: 0.24504709243774414  (0.236546839543637)
     | > align_error: 0.6261228322982788  (0.6259962826367189)
     | > grad_norm: tensor(0.1984, device='cuda:0')  (tensor(0.1916, device='cuda:0'))
     | > step_time: 14.581  (1.5090205333376892)
     | > loader_time: 2.2541  (1.4163749057974588)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47735595703125  (0.47735595703125)
     | > postnet_loss: 0.3367807865142822  (0.3367807865142822)
     | > stopnet_loss: 0.012586993165314198  (0.012586993165314198)
     | > loss: 0.21612118184566498  (0.21612118184566498)
     | > align_error: 0.7196906208992004  (0.7196906208992004)

   --> STEP: 1
     | > decoder_loss: 0.4570668637752533  (0.4570668637752533)
     | > postnet_loss: 0.32162851095199585  (0.32162851095199585)
     | > stopnet_loss: 0.009940512478351593  (0.009940512478351593)
     | > loss: 0.20461434125900269  (0.20461434125900269)
     | > align_error: 0.6609934568405151  (0.6609934568405151)

   --> STEP: 2
     | > decoder_loss: 0.45252543687820435  (0.4547961503267288)
     | > postnet_loss: 0.31752505898475647  (0.31957678496837616)
     | > stopnet_loss: 0.01124343927949667  (0.010591975878924131)
     | > loss: 0.20375606417655945  (0.20418520271778107)
     | > align_error: 0.6586401462554932  (0.6598168015480042)

   --> STEP: 3
     | > decoder_loss: 0.4541698694229126  (0.45458739002545673)
     | > postnet_loss: 0.31345808506011963  (0.31753721833229065)
     | > stopnet_loss: 0.008850046433508396  (0.010011332730452219)
     | > loss: 0.20075704157352448  (0.2030424823363622)
     | > align_error: 0.7359859049320221  (0.6852065026760101)

   --> STEP: 4
     | > decoder_loss: 0.4624457061290741  (0.4565519690513611)
     | > postnet_loss: 0.3226523995399475  (0.31881601363420486)
     | > stopnet_loss: 0.008576449938118458  (0.00965261203236878)
     | > loss: 0.204850971698761  (0.2034946046769619)
     | > align_error: 0.6061173677444458  (0.665434218943119)

   --> STEP: 5
     | > decoder_loss: 0.44443565607070923  (0.45412870645523074)
     | > postnet_loss: 0.30746302008628845  (0.31654541492462157)
     | > stopnet_loss: 0.008494396694004536  (0.00942096896469593)
     | > loss: 0.19646905362606049  (0.20208949446678162)
     | > align_error: 0.6439155340194702  (0.6611304819583893)

   --> STEP: 6
     | > decoder_loss: 0.4594489634037018  (0.4550154159466426)
     | > postnet_loss: 0.31608790159225464  (0.3164691627025604)
     | > stopnet_loss: 0.007514617405831814  (0.009103243704885244)
     | > loss: 0.2013988345861435  (0.20197438448667526)
     | > align_error: 0.5958553552627563  (0.6502512941757838)

   --> STEP: 7
     | > decoder_loss: 0.4647437036037445  (0.45640517132622854)
     | > postnet_loss: 0.3149472177028656  (0.3162517419883183)
     | > stopnet_loss: 0.00664230203256011  (0.008751680608838797)
     | > loss: 0.20156502723693848  (0.20191590487957)
     | > align_error: 0.581623911857605  (0.6404473824160439)

   --> STEP: 8
     | > decoder_loss: 0.4627668857574463  (0.45720038563013077)
     | > postnet_loss: 0.3155757486820221  (0.3161672428250313)
     | > stopnet_loss: 0.007715702056884766  (0.008622183289844543)
     | > loss: 0.20230135321617126  (0.20196408592164516)
     | > align_error: 0.5777648985385895  (0.6326120719313622)

   --> STEP: 9
     | > decoder_loss: 0.4598708152770996  (0.45749710003534955)
     | > postnet_loss: 0.3163056969642639  (0.31618262661827934)
     | > stopnet_loss: 0.006856877356767654  (0.008426038186169334)
     | > loss: 0.20090100169181824  (0.2018459654516644)
     | > align_error: 0.594296395778656  (0.6283547745810615)

   --> STEP: 10
     | > decoder_loss: 0.4898127615451813  (0.4607286661863327)
     | > postnet_loss: 0.33114996552467346  (0.31767936050891876)
     | > stopnet_loss: 0.005644937977194786  (0.008147928165271878)
     | > loss: 0.21088561415672302  (0.20274993032217026)
     | > align_error: 0.5882694125175476  (0.62434623837471)

   --> STEP: 11
     | > decoder_loss: 0.4743128716945648  (0.46196359395980835)
     | > postnet_loss: 0.3240645229816437  (0.31825982982462103)
     | > stopnet_loss: 0.006060940213501453  (0.007958201987838203)
     | > loss: 0.2056552916765213  (0.2030140540816567)
     | > align_error: 0.5960074365139008  (0.6217699836600911)

   --> STEP: 12
     | > decoder_loss: 0.46751952171325684  (0.4624265879392624)
     | > postnet_loss: 0.31508582830429077  (0.3179953296979268)
     | > stopnet_loss: 0.008013718761503696  (0.007962828385643661)
     | > loss: 0.20366506278514862  (0.2030683048069477)
     | > align_error: 0.5897204875946045  (0.6190991923213005)

   --> STEP: 13
     | > decoder_loss: 0.4607592821121216  (0.46229833364486694)
     | > postnet_loss: 0.3168724477291107  (0.31790895416186404)
     | > stopnet_loss: 0.0058090295642614365  (0.007797151553229644)
     | > loss: 0.20021696388721466  (0.20284897089004517)
     | > align_error: 0.5886158049106598  (0.6167543163666358)

   --> STEP: 14
     | > decoder_loss: 0.46574118733406067  (0.46254425176552366)
     | > postnet_loss: 0.31595632433891296  (0.31776948060308186)
     | > stopnet_loss: 0.0052156345918774605  (0.007612757484561631)
     | > loss: 0.200640007853508  (0.20269118781600678)
     | > align_error: 0.5562794208526611  (0.6124346809727805)

   --> STEP: 15
     | > decoder_loss: 0.4692961275577545  (0.46299437681833905)
     | > postnet_loss: 0.32289958000183105  (0.31811148722966515)
     | > stopnet_loss: 0.005190123803913593  (0.007451248572518428)
     | > loss: 0.20323903858661652  (0.20272771120071412)
     | > align_error: 0.5900536477565765  (0.6109426120917002)

   --> STEP: 16
     | > decoder_loss: 0.46852004528045654  (0.4633397310972214)
     | > postnet_loss: 0.3139493465423584  (0.31785135343670845)
     | > stopnet_loss: 0.005323495250195265  (0.0073182639898732305)
     | > loss: 0.20094084739685059  (0.20261603221297264)
     | > align_error: 0.6080123782157898  (0.6107594724744558)

   --> STEP: 17
     | > decoder_loss: 0.47633984684944153  (0.46410444378852844)
     | > postnet_loss: 0.32513177394866943  (0.3182796134668238)
     | > stopnet_loss: 0.005028885789215565  (0.0071835946839521915)
     | > loss: 0.20539678633213043  (0.2027796059846878)
     | > align_error: 0.5599685311317444  (0.6077717700425316)

   --> STEP: 18
     | > decoder_loss: 0.4731238782405853  (0.46460552348030937)
     | > postnet_loss: 0.31804680824279785  (0.3182666798432668)
     | > stopnet_loss: 0.005577924661338329  (0.007094390793806977)
     | > loss: 0.203370600938797  (0.20281243903769386)
     | > align_error: 0.6050853729248047  (0.6076225257582135)

   --> STEP: 19
     | > decoder_loss: 0.47164013981819153  (0.46497576644546107)
     | > postnet_loss: 0.3169877827167511  (0.31819936946818705)
     | > stopnet_loss: 0.005124962888658047  (0.00699073669353598)
     | > loss: 0.20228193700313568  (0.20278451787798027)
     | > align_error: 0.6025242507457733  (0.6073541954944008)

   --> STEP: 20
     | > decoder_loss: 0.46638089418411255  (0.46504602283239366)
     | > postnet_loss: 0.31519368290901184  (0.3180490851402283)
     | > stopnet_loss: 0.004718415439128876  (0.006877120630815625)
     | > loss: 0.20011207461357117  (0.20265089571475983)
     | > align_error: 0.6238216459751129  (0.6081775680184365)

   --> STEP: 21
     | > decoder_loss: 0.46400535106658936  (0.46499646703402203)
     | > postnet_loss: 0.31113141775131226  (0.31771967240742277)
     | > stopnet_loss: 0.004206436686217785  (0.006749945204882394)
     | > loss: 0.19799062609672546  (0.20242897811390104)
     | > align_error: 0.5622365474700928  (0.6059899003732772)

   --> STEP: 22
     | > decoder_loss: 0.46638423204421997  (0.4650595472617583)
     | > postnet_loss: 0.3151847720146179  (0.3176044496622953)
     | > stopnet_loss: 0.005081679672002792  (0.006674114953387867)
     | > loss: 0.20047393441200256  (0.2023401124910875)
     | > align_error: 0.6268107295036316  (0.6069363016973841)

   --> STEP: 23
     | > decoder_loss: 0.4377172589302063  (0.4638707521169082)
     | > postnet_loss: 0.3039223849773407  (0.3170095772846886)
     | > stopnet_loss: 0.00477122887969017  (0.0065913807762705764)
     | > loss: 0.19018113613128662  (0.20181146134500919)
     | > align_error: 0.5675623416900635  (0.6052243903927179)

   --> STEP: 24
     | > decoder_loss: 0.4734649062156677  (0.46427050853768986)
     | > postnet_loss: 0.32008257508277893  (0.31713761885960906)
     | > stopnet_loss: 0.0045588635839521885  (0.006506692559923977)
     | > loss: 0.202945739030838  (0.20185872291525206)
     | > align_error: 0.5809448659420013  (0.6042127435406047)

   --> STEP: 25
     | > decoder_loss: 0.4739542305469513  (0.4646578574180603)
     | > postnet_loss: 0.31692400574684143  (0.31712907433509835)
     | > stopnet_loss: 0.0038878461346030235  (0.006401938702911138)
     | > loss: 0.20160740613937378  (0.20184867024421693)
     | > align_error: 0.5599996447563171  (0.6024442195892332)

   --> STEP: 26
     | > decoder_loss: 0.44704771041870117  (0.4639805440719311)
     | > postnet_loss: 0.3039567172527313  (0.31662244521654576)
     | > stopnet_loss: 0.004649080336093903  (0.006334521073418168)
     | > loss: 0.19240018725395203  (0.20148526705228365)
     | > align_error: 0.5484484136104584  (0.6003674578208188)

   --> STEP: 27
     | > decoder_loss: 0.44349780678749084  (0.4632219241725074)
     | > postnet_loss: 0.30110839009284973  (0.3160478505823348)
     | > stopnet_loss: 0.004079817794263363  (0.006251013544560583)
     | > loss: 0.19023136794567108  (0.20106845597426096)
     | > align_error: 0.5427926778793335  (0.5982350585637266)

   --> STEP: 28
     | > decoder_loss: 0.44917404651641846  (0.4627202142562185)
     | > postnet_loss: 0.304476261138916  (0.3156345795307841)
     | > stopnet_loss: 0.004097564611583948  (0.006174104654097131)
     | > loss: 0.19251014292240143  (0.20076280193669455)
     | > align_error: 0.56672403216362  (0.5971096647637228)

   --> STEP: 29
     | > decoder_loss: 0.44433438777923584  (0.4620862202397708)
     | > postnet_loss: 0.2997168004512787  (0.3150856905970081)
     | > stopnet_loss: 0.0037618211936205626  (0.006090922465804836)
     | > loss: 0.18977463245391846  (0.20038389954073677)
     | > align_error: 0.5416207313537598  (0.5951962532668276)

   --> STEP: 30
     | > decoder_loss: 0.44495099782943726  (0.46151504615942635)
     | > postnet_loss: 0.3011336624622345  (0.31462062299251564)
     | > stopnet_loss: 0.003138078609481454  (0.005992494337260723)
     | > loss: 0.1896592527627945  (0.20002641131480534)
     | > align_error: 0.5348054766654968  (0.5931832273801165)

   --> STEP: 31
     | > decoder_loss: 0.44439342617988586  (0.4609627358375057)
     | > postnet_loss: 0.303722620010376  (0.3142690745092208)
     | > stopnet_loss: 0.004128318279981613  (0.005932359625735591)
     | > loss: 0.19115732610225677  (0.19974031179181992)
     | > align_error: 0.5603931546211243  (0.5921254830975684)

   --> STEP: 32
     | > decoder_loss: 0.4509110152721405  (0.46064861956983805)
     | > postnet_loss: 0.3057791292667389  (0.31400376372039324)
     | > stopnet_loss: 0.0040895226411521435  (0.005874770969967358)
     | > loss: 0.19326205551624298  (0.19953786628320813)
     | > align_error: 0.531945675611496  (0.5902448641136286)

   --> STEP: 33
     | > decoder_loss: 0.449203759431839  (0.46030180562626233)
     | > postnet_loss: 0.3050532042980194  (0.31373253464698797)
     | > stopnet_loss: 0.004198734182864428  (0.005823981976418784)
     | > loss: 0.19276297092437744  (0.19933256642384964)
     | > align_error: 0.5464155077934265  (0.5889167018008953)

   --> STEP: 34
     | > decoder_loss: 0.45507603883743286  (0.46014810660306144)
     | > postnet_loss: 0.3073449730873108  (0.3135446651893504)
     | > stopnet_loss: 0.0035465185064822435  (0.005756997756714768)
     | > loss: 0.19415177404880524  (0.19918019017752478)
     | > align_error: 0.5639634132385254  (0.5881827815490608)

   --> STEP: 35
     | > decoder_loss: 0.4518900215625763  (0.45991216131619045)
     | > postnet_loss: 0.30505555868148804  (0.31330211928912577)
     | > stopnet_loss: 0.003712703473865986  (0.005698589348633374)
     | > loss: 0.1929491013288498  (0.19900215906756266)
     | > align_error: 0.5348407924175262  (0.5866587247167313)

   --> STEP: 36
     | > decoder_loss: 0.4591798484325409  (0.45989181929164463)
     | > postnet_loss: 0.30981653928756714  (0.3132052976224158)
     | > stopnet_loss: 0.003908746410161257  (0.005648871489231371)
     | > loss: 0.19615784287452698  (0.19892315028442278)
     | > align_error: 0.6347399055957794  (0.5879943130744826)

   --> STEP: 37
     | > decoder_loss: 0.4503253698348999  (0.4596332666036245)
     | > postnet_loss: 0.3058580160140991  (0.3130067224438126)
     | > stopnet_loss: 0.0037597238551825285  (0.005597813445067889)
     | > loss: 0.19280557334423065  (0.1987578103671203)
     | > align_error: 0.5198548436164856  (0.5861527057918341)

   --> STEP: 38
     | > decoder_loss: 0.4405881464481354  (0.4591320792311116)
     | > postnet_loss: 0.30024072527885437  (0.3126707751499979)
     | > stopnet_loss: 0.003316037356853485  (0.005537766705904352)
     | > loss: 0.18852326273918152  (0.19848848016638507)
     | > align_error: 0.5516381859779358  (0.5852444289546263)

   --> STEP: 39
     | > decoder_loss: 0.45322638750076294  (0.4589806512380258)
     | > postnet_loss: 0.30812910199165344  (0.31255432199209165)
     | > stopnet_loss: 0.003630412742495537  (0.005488860194022074)
     | > loss: 0.19396929442882538  (0.19837260360901174)
     | > align_error: 0.5469202101230621  (0.5842617566768938)

   --> STEP: 40
     | > decoder_loss: 0.4499795138835907  (0.4587556228041649)
     | > postnet_loss: 0.3065248727798462  (0.3124035857617855)
     | > stopnet_loss: 0.0032109194435179234  (0.005431911675259471)
     | > loss: 0.1923370212316513  (0.19822171404957772)
     | > align_error: 0.5849549770355225  (0.5842790871858596)

   --> STEP: 41
     | > decoder_loss: 0.44065794348716736  (0.4583142159915552)
     | > postnet_loss: 0.29909366369247437  (0.3120789535161925)
     | > stopnet_loss: 0.0038484414108097553  (0.005393290449297283)
     | > loss: 0.1887863427400589  (0.19799158304202846)
     | > align_error: 0.5049965381622314  (0.5823453664779663)

   --> STEP: 42
     | > decoder_loss: 0.4463629126548767  (0.4580296611502057)
     | > postnet_loss: 0.3027957081794739  (0.31185792386531824)
     | > stopnet_loss: 0.003427830757573247  (0.00534649378997052)
     | > loss: 0.19071748852729797  (0.19781839031548726)
     | > align_error: 0.5803095996379852  (0.5822968958389192)

   --> STEP: 43
     | > decoder_loss: 0.4443556070327759  (0.45771165989166085)
     | > postnet_loss: 0.301723450422287  (0.31162223843641057)
     | > stopnet_loss: 0.0031070669647306204  (0.005294414096360289)
     | > loss: 0.18962684273719788  (0.19762788920901542)
     | > align_error: 0.5523462891578674  (0.5816003701021506)

   --> STEP: 44
     | > decoder_loss: 0.4625934362411499  (0.4578226093541492)
     | > postnet_loss: 0.31072720885276794  (0.31160189685496414)
     | > stopnet_loss: 0.0028772351797670126  (0.00523947821189226)
     | > loss: 0.19620740413665771  (0.19759560545737093)
     | > align_error: 0.5519920587539673  (0.5809274539351464)

   --> STEP: 45
     | > decoder_loss: 0.4543485939502716  (0.4577454090118408)
     | > postnet_loss: 0.3092765510082245  (0.31155022250281433)
     | > stopnet_loss: 0.0035149171017110348  (0.005201154631666011)
     | > loss: 0.1944212019443512  (0.1975250631570816)
     | > align_error: 0.5534701943397522  (0.5803172926108043)

   --> STEP: 46
     | > decoder_loss: 0.44580620527267456  (0.45748586110446765)
     | > postnet_loss: 0.30093273520469666  (0.3113194075615509)
     | > stopnet_loss: 0.0033686121460050344  (0.005161316751542946)
     | > loss: 0.19005334377288818  (0.19736263447481653)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3467786275979244 (-0.03003511284336907)
     | > avg_decoder_loss: 0.4533551118590615 (-0.0012087216882994412)
     | > avg_postnet_loss: 0.30780844796787604 (-0.0004977909001438463)
     | > avg_stopnet_loss: 0.0045737412398342385 (+4.67646344931745e-06)
     | > avg_loss: 0.19486463137648322 (-0.0004219521175731489)
     | > avg_align_error: 0.5729509181145466 (+0.00040726544279046095)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_302.pth

 > EPOCH: 2/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 20:44:17)

   --> TIME: 2025-12-27 20:44:54 -- STEP: 23/150 -- GLOBAL_STEP: 325
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49350231885910034  (0.49244445044061413)
     | > postnet_loss: 0.42097553610801697  (0.4240266836207846)
     | > stopnet_loss: 0.006776721682399511  (0.010058640299931814)
     | > loss: 0.23539617657661438  (0.2391764249490655)
     | > align_error: 0.6398199498653412  (0.6738820179649021)
     | > grad_norm: tensor(0.1697, device='cuda:0')  (tensor(0.2622, device='cuda:0'))
     | > step_time: 0.8827  (0.6503329795339833)
     | > loader_time: 0.9387  (0.9327941251837689)


   --> TIME: 2025-12-27 20:45:46 -- STEP: 48/150 -- GLOBAL_STEP: 350
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.49739915132522583  (0.49885658857723075)
     | > postnet_loss: 0.41476723551750183  (0.4237504744281371)
     | > stopnet_loss: 0.004607852548360825  (0.007849821413401514)
     | > loss: 0.23264944553375244  (0.2385015875721971)
     | > align_error: 0.6248336732387543  (0.6507056200255948)
     | > grad_norm: tensor(0.1597, device='cuda:0')  (tensor(0.2216, device='cuda:0'))
     | > step_time: 1.2441  (0.8602031717697779)
     | > loader_time: 1.0621  (0.9731643150250117)


   --> TIME: 2025-12-27 20:46:51 -- STEP: 73/150 -- GLOBAL_STEP: 375
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5079965591430664  (0.5013132213729702)
     | > postnet_loss: 0.4178107678890228  (0.4225089031539551)
     | > stopnet_loss: 0.004018181003630161  (0.006705226236316439)
     | > loss: 0.2354700267314911  (0.23766075768699385)
     | > align_error: 0.6491612493991852  (0.63816732331498)
     | > grad_norm: tensor(0.1583, device='cuda:0')  (tensor(0.1989, device='cuda:0'))
     | > step_time: 1.4302  (1.0406439663612679)
     | > loader_time: 1.259  (1.0571807345298871)


   --> TIME: 2025-12-27 20:48:08 -- STEP: 98/150 -- GLOBAL_STEP: 400
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5083526372909546  (0.5020144247278877)
     | > postnet_loss: 0.43032389879226685  (0.421861074104601)
     | > stopnet_loss: 0.004033914301544428  (0.0059957883952717695)
     | > loss: 0.23870304226875305  (0.2369646630725082)
     | > align_error: 0.6093571484088898  (0.6334455274805728)
     | > grad_norm: tensor(0.1501, device='cuda:0')  (tensor(0.1904, device='cuda:0'))
     | > step_time: 1.6345  (1.1725968390094994)
     | > loader_time: 1.4729  (1.1707568630880243)


   --> TIME: 2025-12-27 20:49:35 -- STEP: 123/150 -- GLOBAL_STEP: 425
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5034753084182739  (0.5029302173998299)
     | > postnet_loss: 0.4139748811721802  (0.42142053954000397)
     | > stopnet_loss: 0.00337284617125988  (0.00549802189215836)
     | > loss: 0.23273539543151855  (0.23658571083371233)
     | > align_error: 0.603957861661911  (0.629192725671985)
     | > grad_norm: tensor(0.1196, device='cuda:0')  (tensor(0.1802, device='cuda:0'))
     | > step_time: 1.8309  (1.2910398758523836)
     | > loader_time: 1.8869  (1.2852902625634424)


   --> TIME: 2025-12-27 20:51:18 -- STEP: 148/150 -- GLOBAL_STEP: 450
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.521385908126831  (0.5040674251881807)
     | > postnet_loss: 0.42468568682670593  (0.4208356204467852)
     | > stopnet_loss: 0.0028181057423353195  (0.005116302472841297)
     | > loss: 0.2393360137939453  (0.23634206372741107)
     | > align_error: 0.6153029203414917  (0.6258675735947247)
     | > grad_norm: tensor(0.2314, device='cuda:0')  (tensor(0.1794, device='cuda:0'))
     | > step_time: 2.4643  (1.4188230327657751)
     | > loader_time: 2.0496  (1.4190327927872943)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4792020618915558  (0.4792020618915558)
     | > postnet_loss: 0.33889809250831604  (0.33889809250831604)
     | > stopnet_loss: 0.012532561086118221  (0.012532561086118221)
     | > loss: 0.21705760061740875  (0.21705760061740875)
     | > align_error: 0.7193987965583801  (0.7193987965583801)

   --> STEP: 1
     | > decoder_loss: 0.46058428287506104  (0.46058428287506104)
     | > postnet_loss: 0.3254077136516571  (0.3254077136516571)
     | > stopnet_loss: 0.00988332275301218  (0.00988332275301218)
     | > loss: 0.20638133585453033  (0.20638133585453033)
     | > align_error: 0.6604271829128265  (0.6604271829128265)

   --> STEP: 2
     | > decoder_loss: 0.45296338200569153  (0.4567738324403763)
     | > postnet_loss: 0.3173917531967163  (0.3213997334241867)
     | > stopnet_loss: 0.011231268756091595  (0.010557295754551888)
     | > loss: 0.20382004976272583  (0.20510069280862808)
     | > align_error: 0.6581718921661377  (0.6592995375394821)

   --> STEP: 3
     | > decoder_loss: 0.4550171196460724  (0.45618826150894165)
     | > postnet_loss: 0.314434289932251  (0.3190779189268748)
     | > stopnet_loss: 0.008775806985795498  (0.009963466164966425)
     | > loss: 0.20113864541053772  (0.20378001034259796)
     | > align_error: 0.7355471551418304  (0.6847154100735983)

   --> STEP: 4
     | > decoder_loss: 0.46691417694091797  (0.45886974036693573)
     | > postnet_loss: 0.32631221413612366  (0.320886492729187)
     | > stopnet_loss: 0.00850482378154993  (0.009598805569112301)
     | > loss: 0.20681141316890717  (0.20453786104917526)
     | > align_error: 0.6058193445205688  (0.6649913936853409)

   --> STEP: 5
     | > decoder_loss: 0.44652435183525085  (0.45640066266059875)
     | > postnet_loss: 0.3084138333797455  (0.3183919608592987)
     | > stopnet_loss: 0.008523260243237019  (0.009383696503937245)
     | > loss: 0.19725780189037323  (0.20308184921741484)
     | > align_error: 0.6436969339847565  (0.660732501745224)

   --> STEP: 6
     | > decoder_loss: 0.46290478110313416  (0.4574846824010213)
     | > postnet_loss: 0.3190433979034424  (0.3185005336999893)
     | > stopnet_loss: 0.007465341128408909  (0.009063970608015856)
     | > loss: 0.20295239984989166  (0.20306027432282767)
     | > align_error: 0.595458596944809  (0.6498535176118215)

   --> STEP: 7
     | > decoder_loss: 0.4680916965007782  (0.458999970129558)
     | > postnet_loss: 0.3165074288845062  (0.3182158044406346)
     | > stopnet_loss: 0.006673100870102644  (0.008722417788313968)
     | > loss: 0.20282287895679474  (0.20302636069910868)
     | > align_error: 0.5810103118419647  (0.6400187739304134)

   --> STEP: 8
     | > decoder_loss: 0.46519309282302856  (0.45977411046624184)
     | > postnet_loss: 0.31785914301872253  (0.3181712217628956)
     | > stopnet_loss: 0.007712232414633036  (0.008596144616603851)
     | > loss: 0.20347528159618378  (0.20308247581124306)
     | > align_error: 0.5771098434925079  (0.6321551576256752)

   --> STEP: 9
     | > decoder_loss: 0.46389055252075195  (0.460231492916743)
     | > postnet_loss: 0.31933778524398804  (0.3183008399274614)
     | > stopnet_loss: 0.006859460845589638  (0.008403179753157828)
     | > loss: 0.20266655087471008  (0.20303626192940605)
     | > align_error: 0.5938257277011871  (0.6278963320785098)

   --> STEP: 10
     | > decoder_loss: 0.4951057732105255  (0.4637189209461212)
     | > postnet_loss: 0.3351590633392334  (0.3199866622686386)
     | > stopnet_loss: 0.005684745963662863  (0.00813133637420833)
     | > loss: 0.21325094997882843  (0.2040577307343483)
     | > align_error: 0.5883423686027527  (0.6239409357309341)

   --> STEP: 11
     | > decoder_loss: 0.47738176584243774  (0.46496099775487726)
     | > postnet_loss: 0.32513436675071716  (0.32045463540337304)
     | > stopnet_loss: 0.006046653259545565  (0.007941819727420807)
     | > loss: 0.2066756784915924  (0.20429572598500687)
     | > align_error: 0.595537006855011  (0.6213587603785775)

   --> STEP: 12
     | > decoder_loss: 0.4708174467086792  (0.4654490351676941)
     | > postnet_loss: 0.31728482246398926  (0.32019048432509106)
     | > stopnet_loss: 0.00810086540877819  (0.007955073534200588)
     | > loss: 0.20512643456459045  (0.20436495169997215)
     | > align_error: 0.5892025828361511  (0.6186790789167086)

   --> STEP: 13
     | > decoder_loss: 0.46307191252708435  (0.46526617957995486)
     | > postnet_loss: 0.31783121824264526  (0.32000900231874907)
     | > stopnet_loss: 0.005801924038678408  (0.007789446649929652)
     | > loss: 0.20102770626544952  (0.20410824051270118)
     | > align_error: 0.5881809592247009  (0.6163330697096311)

   --> STEP: 14
     | > decoder_loss: 0.4662055969238281  (0.465333280818803)
     | > postnet_loss: 0.3163135349750519  (0.31974504036562784)
     | > stopnet_loss: 0.0051827989518642426  (0.007603257528639266)
     | > loss: 0.20081257820129395  (0.2038728360618864)
     | > align_error: 0.5557299256324768  (0.6120042737041201)

   --> STEP: 15
     | > decoder_loss: 0.4708786904811859  (0.4657029747962952)
     | > postnet_loss: 0.3227439820766449  (0.31994496981302895)
     | > stopnet_loss: 0.0051756747998297215  (0.007441418680051963)
     | > loss: 0.20358134806156158  (0.2038534035285314)
     | > align_error: 0.5894008278846741  (0.610497377316157)

   --> STEP: 16
     | > decoder_loss: 0.4691760838031769  (0.4659200441092253)
     | > postnet_loss: 0.313312828540802  (0.3195304609835148)
     | > stopnet_loss: 0.005328616127371788  (0.007309368520509452)
     | > loss: 0.20095084607601166  (0.2036719936877489)
     | > align_error: 0.6073315441608429  (0.6102995127439499)

   --> STEP: 17
     | > decoder_loss: 0.4780508875846863  (0.4666336231371936)
     | > postnet_loss: 0.3248242437839508  (0.3198418599717757)
     | > stopnet_loss: 0.005036329384893179  (0.007175660336061436)
     | > loss: 0.2057551145553589  (0.20379453020937302)
     | > align_error: 0.5595632791519165  (0.6073150284150067)

   --> STEP: 18
     | > decoder_loss: 0.47268542647361755  (0.4669698344336616)
     | > postnet_loss: 0.31654831767082214  (0.31965888539950055)
     | > stopnet_loss: 0.005565810948610306  (0.007086224258980817)
     | > loss: 0.20287424325942993  (0.20374340315659842)
     | > align_error: 0.604647159576416  (0.6071668134795295)

   --> STEP: 19
     | > decoder_loss: 0.47290298342704773  (0.46728210543331344)
     | > postnet_loss: 0.31706711649894714  (0.3195224765099977)
     | > stopnet_loss: 0.00511153694242239  (0.0069822933475830054)
     | > loss: 0.20260405540466309  (0.20368343748544393)
     | > align_error: 0.6019461452960968  (0.6068920414698752)

   --> STEP: 20
     | > decoder_loss: 0.46685791015625  (0.4672608956694603)
     | > postnet_loss: 0.31404685974121094  (0.3192486956715584)
     | > stopnet_loss: 0.00473896274343133  (0.0068701268173754215)
     | > loss: 0.19996514916419983  (0.2034975230693817)
     | > align_error: 0.6235944032669067  (0.6077271595597268)

   --> STEP: 21
     | > decoder_loss: 0.46436870098114014  (0.46712317211287363)
     | > postnet_loss: 0.3108420670032501  (0.31884838002068655)
     | > stopnet_loss: 0.004196060821413994  (0.006742790341377258)
     | > loss: 0.1979987472295761  (0.20323567660081954)
     | > align_error: 0.5616989135742188  (0.6055353383223216)

   --> STEP: 22
     | > decoder_loss: 0.46790528297424316  (0.46715872260657226)
     | > postnet_loss: 0.31510376930236816  (0.3186781704425812)
     | > stopnet_loss: 0.005063251592218876  (0.006666447670960968)
     | > loss: 0.20081551373004913  (0.2031256691976027)
     | > align_error: 0.6262719631195068  (0.6064779121767392)

   --> STEP: 23
     | > decoder_loss: 0.4370943605899811  (0.46585157643193786)
     | > postnet_loss: 0.3023712933063507  (0.3179691757844842)
     | > stopnet_loss: 0.004757456947118044  (0.006583448074272145)
     | > loss: 0.1896238774061203  (0.20253863477188608)
     | > align_error: 0.5672030448913574  (0.6047703092512878)

   --> STEP: 24
     | > decoder_loss: 0.47197312116622925  (0.46610664079586667)
     | > postnet_loss: 0.3176444470882416  (0.3179556454221408)
     | > stopnet_loss: 0.004572238307446241  (0.006499647667321066)
     | > loss: 0.20197662711143494  (0.20251521778603396)
     | > align_error: 0.5805725157260895  (0.6037620678544046)

   --> STEP: 25
     | > decoder_loss: 0.4724350571632385  (0.4663597774505615)
     | > postnet_loss: 0.3148030638694763  (0.3178295421600342)
     | > stopnet_loss: 0.0038653940428048372  (0.006394277522340417)
     | > loss: 0.20067492127418518  (0.20244160592556)
     | > align_error: 0.5595655739307404  (0.6019942080974581)

   --> STEP: 26
     | > decoder_loss: 0.446060448884964  (0.4655790340441924)
     | > postnet_loss: 0.3024251461029053  (0.31723706538860613)
     | > stopnet_loss: 0.004620253574103117  (0.006326045832023597)
     | > loss: 0.19174164533615112  (0.20203006897981352)
     | > align_error: 0.5480635762214661  (0.5999199530253045)

   --> STEP: 27
     | > decoder_loss: 0.44350263476371765  (0.464761389626397)
     | > postnet_loss: 0.2997500002384186  (0.3165893963089696)
     | > stopnet_loss: 0.004061773885041475  (0.006242183908061297)
     | > loss: 0.18987493216991425  (0.201579878727595)
     | > align_error: 0.5423809885978699  (0.597788880268733)

   --> STEP: 28
     | > decoder_loss: 0.4490627944469452  (0.4642007255128452)
     | > postnet_loss: 0.3028503656387329  (0.3160987166421754)
     | > stopnet_loss: 0.00409126840531826  (0.006165365497249046)
     | > loss: 0.19206956028938293  (0.20124022449765885)
     | > align_error: 0.5664688348770142  (0.5966703072190287)

   --> STEP: 29
     | > decoder_loss: 0.44489794969558716  (0.4635351125536294)
     | > postnet_loss: 0.29951831698417664  (0.31552697872293406)
     | > stopnet_loss: 0.003771452698856592  (0.006082816780063099)
     | > loss: 0.1898755133152008  (0.20084833790516032)
     | > align_error: 0.5413245558738708  (0.594761833034713)

   --> STEP: 30
     | > decoder_loss: 0.44403937458992004  (0.46288525462150576)
     | > postnet_loss: 0.2997538447380066  (0.31500120759010314)
     | > stopnet_loss: 0.0031058997847139835  (0.005983586213551462)
     | > loss: 0.1890542060136795  (0.2004552001754443)
     | > align_error: 0.534327507019043  (0.5927473555008572)

   --> STEP: 31
     | > decoder_loss: 0.4432789981365204  (0.4622527947348933)
     | > postnet_loss: 0.30159446597099304  (0.3145687320540028)
     | > stopnet_loss: 0.004144256468862295  (0.0059242529959808434)
     | > loss: 0.1903626173734665  (0.2001296329882837)
     | > align_error: 0.5604154467582703  (0.5917043907027093)

   --> STEP: 32
     | > decoder_loss: 0.4501287341117859  (0.4618739178404212)
     | > postnet_loss: 0.3043147623538971  (0.3142482955008745)
     | > stopnet_loss: 0.004077304620295763  (0.005866535859240685)
     | > loss: 0.19268818199634552  (0.19989708764478564)
     | > align_error: 0.5317283868789673  (0.5898301405832174)

   --> STEP: 33
     | > decoder_loss: 0.44825056195259094  (0.4614610888741233)
     | > postnet_loss: 0.30311015248298645  (0.31391077601548395)
     | > stopnet_loss: 0.004183219745755196  (0.005815526280044155)
     | > loss: 0.1920233964920044  (0.19965849094318622)
     | > align_error: 0.5462545156478882  (0.5885096671003286)

   --> STEP: 34
     | > decoder_loss: 0.4542958736419678  (0.46125034724964814)
     | > postnet_loss: 0.3050459921360016  (0.31365004707785216)
     | > stopnet_loss: 0.003557061543688178  (0.00574910084662192)
     | > loss: 0.19339251518249512  (0.19947419753846)
     | > align_error: 0.5637158751487732  (0.5877804379252829)

   --> STEP: 35
     | > decoder_loss: 0.45167091488838196  (0.4609766491821834)
     | > postnet_loss: 0.3037243187427521  (0.31336645483970643)
     | > stopnet_loss: 0.0037073311395943165  (0.005690764569278274)
     | > loss: 0.19255614280700684  (0.19927653883184707)
     | > align_error: 0.534430593252182  (0.5862561566489085)

   --> STEP: 36
     | > decoder_loss: 0.45854514837265015  (0.4609091074930297)
     | > postnet_loss: 0.3083057403564453  (0.3132258794373936)
     | > stopnet_loss: 0.003900982439517975  (0.005641048399007155)
     | > loss: 0.19561371207237244  (0.19917479364408386)
     | > align_error: 0.6344075500965118  (0.5875936953557864)

   --> STEP: 37
     | > decoder_loss: 0.4502798616886139  (0.4606218305793968)
     | > postnet_loss: 0.3047229051589966  (0.31299606932176127)
     | > stopnet_loss: 0.003761705942451954  (0.005590255359640798)
     | > loss: 0.1925123929977417  (0.1989947287617503)
     | > align_error: 0.5195794701576233  (0.5857554730531334)

   --> STEP: 38
     | > decoder_loss: 0.4396485686302185  (0.46006990263336583)
     | > postnet_loss: 0.29852381348609924  (0.31261522048398066)
     | > stopnet_loss: 0.003312270389869809  (0.005530308386752088)
     | > loss: 0.18785537779331207  (0.1987015879467914)
     | > align_error: 0.5513946712017059  (0.5848512414254642)

   --> STEP: 39
     | > decoder_loss: 0.4526297152042389  (0.45987912859672153)
     | > postnet_loss: 0.30704087018966675  (0.3124722884251521)
     | > stopnet_loss: 0.0036304625682532787  (0.005481594391405964)
     | > loss: 0.19354811310768127  (0.1985694475663014)
     | > align_error: 0.5465131998062134  (0.5838682147172783)

   --> STEP: 40
     | > decoder_loss: 0.4503501355648041  (0.4596409037709236)
     | > postnet_loss: 0.3059169054031372  (0.31230840384960173)
     | > stopnet_loss: 0.003213662886992097  (0.005424896103795618)
     | > loss: 0.19228042662143707  (0.19841222204267978)
     | > align_error: 0.5847353637218475  (0.5838898934423926)

   --> STEP: 41
     | > decoder_loss: 0.44037631154060364  (0.4591710356677451)
     | > postnet_loss: 0.29806089401245117  (0.31196090360967127)
     | > stopnet_loss: 0.0038409100379794836  (0.005386262297312297)
     | > loss: 0.18845020234584808  (0.19816924595251317)
     | > align_error: 0.5043944120407104  (0.5819509792618638)

   --> STEP: 42
     | > decoder_loss: 0.44545358419418335  (0.45884442968027933)
     | > postnet_loss: 0.30098626017570496  (0.31169960257552926)
     | > stopnet_loss: 0.0034110199194401503  (0.00533923271688677)
     | > loss: 0.19002097845077515  (0.19797523958342417)
     | > align_error: 0.5800572037696838  (0.5819058893691929)

   --> STEP: 43
     | > decoder_loss: 0.44338852167129517  (0.45848498995914017)
     | > postnet_loss: 0.29984867572784424  (0.3114239996255831)
     | > stopnet_loss: 0.0030956650152802467  (0.005287056723826153)
     | > loss: 0.18890497088432312  (0.1977643031020497)
     | > align_error: 0.5520090758800507  (0.5812106146368872)

   --> STEP: 44
     | > decoder_loss: 0.4616855978965759  (0.45855773104862735)
     | > postnet_loss: 0.3090759515762329  (0.3113706348971888)
     | > stopnet_loss: 0.0028668956365436316  (0.00523205306275155)
     | > loss: 0.19555728137493134  (0.19771414351734248)
     | > align_error: 0.5517287254333496  (0.5805405717004432)

   --> STEP: 45
     | > decoder_loss: 0.45413485169410706  (0.45845944484074913)
     | > postnet_loss: 0.30787089467048645  (0.31129286289215097)
     | > stopnet_loss: 0.003508201101794839  (0.005193745241396957)
     | > loss: 0.19400963187217712  (0.1976318210363388)
     | > align_error: 0.5530992746353149  (0.5799307650989959)

   --> STEP: 46
     | > decoder_loss: 0.4460617005825043  (0.45818992866122205)
     | > postnet_loss: 0.3001507520675659  (0.3110506430916165)
     | > stopnet_loss: 0.0033648491371423006  (0.005153986630434899)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3500558752002138 (+0.0032772476022894237)
     | > avg_decoder_loss: 0.45392566287156305 (+0.0005705510125015301)
     | > avg_postnet_loss: 0.3076583273483046 (-0.00015012061957142553)
     | > avg_stopnet_loss: 0.004567252218045972 (-6.489021788266651e-06)
     | > avg_loss: 0.19496324929324063 (+9.861791675741527e-05)
     | > avg_align_error: 0.5726440110892963 (-0.00030690702525026925)


 > EPOCH: 3/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 20:53:32)

   --> TIME: 2025-12-27 20:54:04 -- STEP: 22/150 -- GLOBAL_STEP: 475
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.5006921887397766  (0.4911060373891484)
     | > postnet_loss: 0.4231713116168976  (0.423049810257825)
     | > stopnet_loss: 0.0067317187786102295  (0.010464683598415419)
     | > loss: 0.23769760131835938  (0.23900364474816757)
     | > align_error: 0.6325793266296387  (0.674554933201183)
     | > grad_norm: tensor(0.1736, device='cuda:0')  (tensor(0.2608, device='cuda:0'))
     | > step_time: 0.7714  (0.6199558323079889)
     | > loader_time: 1.1493  (0.8326548337936401)


   --> TIME: 2025-12-27 20:54:56 -- STEP: 47/150 -- GLOBAL_STEP: 500
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5019997954368591  (0.49807562599790856)
     | > postnet_loss: 0.4199433922767639  (0.4233025331446465)
     | > stopnet_loss: 0.0045019835233688354  (0.007990076880347217)
     | > loss: 0.2349877804517746  (0.23833461676506287)
     | > align_error: 0.6604174971580505  (0.6510684318999026)
     | > grad_norm: tensor(0.1783, device='cuda:0')  (tensor(0.2307, device='cuda:0'))
     | > step_time: 1.2187  (0.8606204631480765)
     | > loader_time: 1.049  (0.9082590316204314)


   --> TIME: 2025-12-27 20:56:00 -- STEP: 72/150 -- GLOBAL_STEP: 525
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5029199719429016  (0.5009177244371839)
     | > postnet_loss: 0.41638967394828796  (0.4223444341785378)
     | > stopnet_loss: 0.003936556167900562  (0.00675965562307586)
     | > loss: 0.23376396298408508  (0.23757519552277195)
     | > align_error: 0.601053774356842  (0.6384577602148054)
     | > grad_norm: tensor(0.1523, device='cuda:0')  (tensor(0.2151, device='cuda:0'))
     | > step_time: 1.5264  (1.0369531677828894)
     | > loader_time: 1.3189  (1.0132370856073165)


   --> TIME: 2025-12-27 20:57:22 -- STEP: 97/150 -- GLOBAL_STEP: 550
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5011577010154724  (0.5018374194803926)
     | > postnet_loss: 0.4149726331233978  (0.4216263137527348)
     | > stopnet_loss: 0.0034795617684721947  (0.006030445162341303)
     | > loss: 0.23251213133335114  (0.23689637832420388)
     | > align_error: 0.5802748501300812  (0.6339800867837726)
     | > grad_norm: tensor(0.1234, device='cuda:0')  (tensor(0.2043, device='cuda:0'))
     | > step_time: 1.8808  (1.18420194350567)
     | > loader_time: 2.0579  (1.1814097030875603)


   --> TIME: 2025-12-27 20:58:50 -- STEP: 122/150 -- GLOBAL_STEP: 575
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5044929385185242  (0.5027294774524502)
     | > postnet_loss: 0.42067259550094604  (0.42125636070478156)
     | > stopnet_loss: 0.0036389892920851707  (0.005524822842848836)
     | > loss: 0.2349303662776947  (0.23652128215695992)
     | > align_error: 0.5984804034233093  (0.6299213720638241)
     | > grad_norm: tensor(0.1145, device='cuda:0')  (tensor(0.1925, device='cuda:0'))
     | > step_time: 1.9278  (1.3101468809315415)
     | > loader_time: 1.5859  (1.2891372168650386)


   --> TIME: 2025-12-27 21:00:29 -- STEP: 147/150 -- GLOBAL_STEP: 600
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5117537975311279  (0.5037434739725932)
     | > postnet_loss: 0.4183611273765564  (0.42058898437590825)
     | > stopnet_loss: 0.0028273581992834806  (0.005136724920994063)
     | > loss: 0.23535609245300293  (0.23621983927528875)
     | > align_error: 0.6302828192710876  (0.6264285299242758)
     | > grad_norm: tensor(0.1361, device='cuda:0')  (tensor(0.1837, device='cuda:0'))
     | > step_time: 2.504  (1.4465845896273244)
     | > loader_time: 2.0394  (1.3872547571350922)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.479130357503891  (0.479130357503891)
     | > postnet_loss: 0.3382038474082947  (0.3382038474082947)
     | > stopnet_loss: 0.012497558258473873  (0.012497558258473873)
     | > loss: 0.21683110296726227  (0.21683110296726227)
     | > align_error: 0.719713568687439  (0.719713568687439)

   --> STEP: 1
     | > decoder_loss: 0.4588873088359833  (0.4588873088359833)
     | > postnet_loss: 0.3233298659324646  (0.3233298659324646)
     | > stopnet_loss: 0.009887625463306904  (0.009887625463306904)
     | > loss: 0.2054419070482254  (0.2054419070482254)
     | > align_error: 0.6608221232891083  (0.6608221232891083)

   --> STEP: 2
     | > decoder_loss: 0.45275992155075073  (0.455823615193367)
     | > postnet_loss: 0.317264586687088  (0.3202972263097763)
     | > stopnet_loss: 0.01119291316717863  (0.010540269315242767)
     | > loss: 0.2036990523338318  (0.2045704796910286)
     | > align_error: 0.6585710048675537  (0.659696564078331)

   --> STEP: 3
     | > decoder_loss: 0.45436733961105347  (0.4553381899992625)
     | > postnet_loss: 0.31379154324531555  (0.31812866528828937)
     | > stopnet_loss: 0.008792582899332047  (0.00995770717660586)
     | > loss: 0.2008323073387146  (0.20332442224025726)
     | > align_error: 0.7360342741012573  (0.6851424674193064)

   --> STEP: 4
     | > decoder_loss: 0.4653855860233307  (0.45785003900527954)
     | > postnet_loss: 0.3248266577720642  (0.3198031634092331)
     | > stopnet_loss: 0.008539809845387936  (0.00960323284380138)
     | > loss: 0.20609287917613983  (0.2040165364742279)
     | > align_error: 0.6062065958976746  (0.6654084995388985)

   --> STEP: 5
     | > decoder_loss: 0.4454135000705719  (0.45536273121833803)
     | > postnet_loss: 0.30777430534362793  (0.31739739179611204)
     | > stopnet_loss: 0.008487226441502571  (0.009380031563341617)
     | > loss: 0.19678416848182678  (0.2025700628757477)
     | > align_error: 0.6440566778182983  (0.6611381351947785)

   --> STEP: 6
     | > decoder_loss: 0.4620480239391327  (0.4564769466718038)
     | > postnet_loss: 0.3178492486476898  (0.317472701271375)
     | > stopnet_loss: 0.00747284758836031  (0.0090621675675114)
     | > loss: 0.20244716107845306  (0.20254957924286524)
     | > align_error: 0.5962547659873962  (0.6503242403268814)

   --> STEP: 7
     | > decoder_loss: 0.46733757853507996  (0.4580284655094147)
     | > postnet_loss: 0.3159140944480896  (0.3172500431537628)
     | > stopnet_loss: 0.006642270367592573  (0.008716467967522996)
     | > loss: 0.20245517790317535  (0.20253609333719527)
     | > align_error: 0.581717312335968  (0.6405232506138938)

   --> STEP: 8
     | > decoder_loss: 0.4636421799659729  (0.45873017981648445)
     | > postnet_loss: 0.3159402012825012  (0.3170863129198551)
     | > stopnet_loss: 0.007414238061755896  (0.008553689229302108)
     | > loss: 0.20230983197689056  (0.20250781066715717)
     | > align_error: 0.5774897933006287  (0.6326440684497356)

   --> STEP: 9
     | > decoder_loss: 0.4631726145744324  (0.45922378367847866)
     | > postnet_loss: 0.3182428181171417  (0.3172148134973314)
     | > stopnet_loss: 0.0068665845319628716  (0.00836623315181997)
     | > loss: 0.20222045481204987  (0.2024758822388119)
     | > align_error: 0.5945717096328735  (0.6284138063589731)

   --> STEP: 10
     | > decoder_loss: 0.49164140224456787  (0.46246554553508756)
     | > postnet_loss: 0.33248162269592285  (0.3187414944171906)
     | > stopnet_loss: 0.005664730444550514  (0.008096082881093026)
     | > loss: 0.21169549226760864  (0.20339784324169158)
     | > align_error: 0.5875542461872101  (0.6243278503417968)

   --> STEP: 11
     | > decoder_loss: 0.4765501916408539  (0.46374596790833905)
     | > postnet_loss: 0.3244287669658661  (0.3192585191943429)
     | > stopnet_loss: 0.006004332099109888  (0.007905923719094559)
     | > loss: 0.20624907314777374  (0.20365704596042633)
     | > align_error: 0.5965005159378052  (0.6217980926687067)

   --> STEP: 12
     | > decoder_loss: 0.47093871235847473  (0.4643453632791837)
     | > postnet_loss: 0.31660228967666626  (0.31903716673453647)
     | > stopnet_loss: 0.008041772060096264  (0.007917244414178034)
     | > loss: 0.20492702722549438  (0.20376287773251534)
     | > align_error: 0.5901321768760681  (0.6191592663526534)

   --> STEP: 13
     | > decoder_loss: 0.4633643627166748  (0.46426990169745225)
     | > postnet_loss: 0.3178332448005676  (0.31894455735500044)
     | > stopnet_loss: 0.005797532387077808  (0.007754189642862632)
     | > loss: 0.20109693706035614  (0.20355780537311846)
     | > align_error: 0.5886949896812439  (0.6168158604548526)

   --> STEP: 14
     | > decoder_loss: 0.4674510359764099  (0.46449712557452066)
     | > postnet_loss: 0.31631553173065186  (0.3187567698104041)
     | > stopnet_loss: 0.005177810788154602  (0.007570162581812058)
     | > loss: 0.20111945271492004  (0.2033836373261043)
     | > align_error: 0.5563976168632507  (0.612500271626881)

   --> STEP: 15
     | > decoder_loss: 0.4709945321083069  (0.4649302860101064)
     | > postnet_loss: 0.32262176275253296  (0.319014436006546)
     | > stopnet_loss: 0.005169606301933527  (0.007410125496486823)
     | > loss: 0.20357367396354675  (0.20339630643526713)
     | > align_error: 0.5901821255683899  (0.6110123952229817)

   --> STEP: 16
     | > decoder_loss: 0.47028809785842896  (0.46526514925062656)
     | > postnet_loss: 0.31399044394493103  (0.3187004365026951)
     | > stopnet_loss: 0.005337447859346867  (0.0072805831441655755)
     | > loss: 0.2014070749282837  (0.20327197946608067)
     | > align_error: 0.608122706413269  (0.6108317896723746)

   --> STEP: 17
     | > decoder_loss: 0.4785107672214508  (0.46604430324891033)
     | > postnet_loss: 0.324863076210022  (0.3190629447207731)
     | > stopnet_loss: 0.005003506317734718  (0.007146637448493172)
     | > loss: 0.20584696531295776  (0.20342344922177932)
     | > align_error: 0.5601328611373901  (0.607849499758552)

   --> STEP: 18
     | > decoder_loss: 0.4743201732635498  (0.4665040738052792)
     | > postnet_loss: 0.3175015449523926  (0.31897620028919643)
     | > stopnet_loss: 0.005561897996813059  (0.007058596367844277)
     | > loss: 0.20351733267307281  (0.20342866496907341)
     | > align_error: 0.6053176820278168  (0.6077088432179556)

   --> STEP: 19
     | > decoder_loss: 0.4729498028755188  (0.46684332270371287)
     | > postnet_loss: 0.3168814778327942  (0.31886595173885945)
     | > stopnet_loss: 0.005084540694952011  (0.006954698700849947)
     | > loss: 0.20254236459732056  (0.2033820175810864)
     | > align_error: 0.6027461290359497  (0.6074476477346922)

   --> STEP: 20
     | > decoder_loss: 0.4677281081676483  (0.4668875619769096)
     | > postnet_loss: 0.3147275447845459  (0.3186590313911438)
     | > stopnet_loss: 0.004743496421724558  (0.006844138586893677)
     | > loss: 0.20035742223262787  (0.2032307878136635)
     | > align_error: 0.6240279674530029  (0.6082766637206077)

   --> STEP: 21
     | > decoder_loss: 0.46464410424232483  (0.4667807306562151)
     | > postnet_loss: 0.3106175363063812  (0.31827610305377413)
     | > stopnet_loss: 0.004196963272988796  (0.006718082619564874)
     | > loss: 0.1980123668909073  (0.20298229157924652)
     | > align_error: 0.5623579621315002  (0.6060900588830312)

   --> STEP: 22
     | > decoder_loss: 0.46682009100914  (0.46678251976316626)
     | > postnet_loss: 0.3143288493156433  (0.3180966824293136)
     | > stopnet_loss: 0.005060626659542322  (0.0066427437122911215)
     | > loss: 0.20034785568714142  (0.20286254449324173)
     | > align_error: 0.6268774569034576  (0.6070349406112324)

   --> STEP: 23
     | > decoder_loss: 0.43818527460098267  (0.46553916127785394)
     | > postnet_loss: 0.3029663562774658  (0.317438842161842)
     | > stopnet_loss: 0.004749984480440617  (0.006560449832645448)
     | > loss: 0.19003789126873016  (0.20230495087478473)
     | > align_error: 0.5678450465202332  (0.6053310321724933)

   --> STEP: 24
     | > decoder_loss: 0.47354212403297424  (0.4658726180593173)
     | > postnet_loss: 0.31849420070648193  (0.3174828154345353)
     | > stopnet_loss: 0.004553098697215319  (0.006476810202002525)
     | > loss: 0.20256216824054718  (0.2023156682650248)
     | > align_error: 0.5811285972595215  (0.6043225973844528)

   --> STEP: 25
     | > decoder_loss: 0.4735127389431  (0.4661782228946686)
     | > postnet_loss: 0.31536152958869934  (0.3173979640007019)
     | > stopnet_loss: 0.0038799832109361887  (0.006372937122359872)
     | > loss: 0.20109854638576508  (0.20226698338985444)
     | > align_error: 0.5601824820041656  (0.6025569927692414)

   --> STEP: 26
     | > decoder_loss: 0.44757282733917236  (0.4654626307579187)
     | > postnet_loss: 0.3031747341156006  (0.31685091669742876)
     | > stopnet_loss: 0.004624630324542522  (0.006305694553213051)
     | > loss: 0.19231152534484863  (0.2018840811573542)
     | > align_error: 0.5489775538444519  (0.6004962451182879)

   --> STEP: 27
     | > decoder_loss: 0.44379496574401855  (0.4646601246462928)
     | > postnet_loss: 0.2997702360153198  (0.3162182988943877)
     | > stopnet_loss: 0.004057135432958603  (0.00622241458579622)
     | > loss: 0.1899484395980835  (0.2014420203588627)
     | > align_error: 0.5429332256317139  (0.5983642814336)

   --> STEP: 28
     | > decoder_loss: 0.44966399669647217  (0.4641245486480849)
     | > postnet_loss: 0.3032872974872589  (0.3157564774155617)
     | > stopnet_loss: 0.004098660312592983  (0.0061465662188961035)
     | > loss: 0.19233646988868713  (0.201116822127785)
     | > align_error: 0.5670101046562195  (0.5972444894058364)

   --> STEP: 29
     | > decoder_loss: 0.44554805755615234  (0.4634839799897424)
     | > postnet_loss: 0.2993849813938141  (0.31519194306998416)
     | > stopnet_loss: 0.0037554404698312283  (0.006064113606859384)
     | > loss: 0.18998868763446808  (0.2007330933521534)
     | > align_error: 0.5420842468738556  (0.5953424120771473)

   --> STEP: 30
     | > decoder_loss: 0.4449930489063263  (0.4628676156202952)
     | > postnet_loss: 0.3001028597354889  (0.314688973625501)
     | > stopnet_loss: 0.0031114774756133556  (0.005965692402484516)
     | > loss: 0.18938545882701874  (0.20035483886798222)
     | > align_error: 0.5349881052970886  (0.5933306018511454)

   --> STEP: 31
     | > decoder_loss: 0.44416725635528564  (0.4622643782246497)
     | > postnet_loss: 0.30216652154922485  (0.31428502355852433)
     | > stopnet_loss: 0.004122487269341946  (0.005906234172383143)
     | > loss: 0.19070592522621155  (0.20004358358921542)
     | > align_error: 0.5609967708587646  (0.5922875750449396)

   --> STEP: 32
     | > decoder_loss: 0.45093944668769836  (0.46191047411412)
     | > postnet_loss: 0.3045993149280548  (0.3139823451638222)
     | > stopnet_loss: 0.00407715979963541  (0.005849075598234776)
     | > loss: 0.19296185672283173  (0.19982227962464094)
     | > align_error: 0.5324982702732086  (0.590419159270823)

   --> STEP: 33
     | > decoder_loss: 0.4491690993309021  (0.4615243718479619)
     | > postnet_loss: 0.30367305874824524  (0.31366994254516833)
     | > stopnet_loss: 0.004148196894675493  (0.005797533819339041)
     | > loss: 0.19235874712467194  (0.19959611197312674)
     | > align_error: 0.5464575886726379  (0.5890869904648174)

   --> STEP: 34
     | > decoder_loss: 0.45540887117385864  (0.4613445041810765)
     | > postnet_loss: 0.3059059977531433  (0.31344159122775583)
     | > stopnet_loss: 0.0035440740175545216  (0.00573125558987479)
     | > loss: 0.19387279450893402  (0.19942777910653284)
     | > align_error: 0.5640978813171387  (0.5883520166663563)

   --> STEP: 35
     | > decoder_loss: 0.4526906907558441  (0.461097252368927)
     | > postnet_loss: 0.30407389998435974  (0.31317394290651596)
     | > stopnet_loss: 0.003720539389178157  (0.005673806555569172)
     | > loss: 0.19291168451309204  (0.19924160497529167)
     | > align_error: 0.5353342294692993  (0.5868372227464403)

   --> STEP: 36
     | > decoder_loss: 0.4597448706626892  (0.46105968621042037)
     | > postnet_loss: 0.30884698033332825  (0.31305374950170517)
     | > stopnet_loss: 0.003902044612914324  (0.005624590946050982)
     | > loss: 0.1960500180721283  (0.19915294978353712)
     | > align_error: 0.634857177734375  (0.588171110384994)

   --> STEP: 37
     | > decoder_loss: 0.45067617297172546  (0.4607790507174827)
     | > postnet_loss: 0.30479979515075684  (0.3128306696543822)
     | > stopnet_loss: 0.003759809536859393  (0.005574191448505263)
     | > loss: 0.19262881577014923  (0.19897662183722933)
     | > align_error: 0.51998370885849  (0.5863282076410345)

   --> STEP: 38
     | > decoder_loss: 0.44047749042510986  (0.4602447991308413)
     | > postnet_loss: 0.2988118827342987  (0.31246175420911687)
     | > stopnet_loss: 0.003303372301161289  (0.005514433049890948)
     | > loss: 0.18812572956085205  (0.19869107204048256)
     | > align_error: 0.5517638325691223  (0.5854186188233527)

   --> STEP: 39
     | > decoder_loss: 0.45280778408050537  (0.4600541064372429)
     | > postnet_loss: 0.30682116746902466  (0.31231712377988374)
     | > stopnet_loss: 0.0036428170278668404  (0.005466442895480073)
     | > loss: 0.19355005025863647  (0.19855925096915317)
     | > align_error: 0.5474467873573303  (0.5844449821190957)

   --> STEP: 40
     | > decoder_loss: 0.450523316860199  (0.45981583669781684)
     | > postnet_loss: 0.30562108755111694  (0.3121497228741646)
     | > stopnet_loss: 0.003205597633495927  (0.00540992176393047)
     | > loss: 0.19224169850349426  (0.1984013121575117)
     | > align_error: 0.5851747095584869  (0.5844632253050805)

   --> STEP: 41
     | > decoder_loss: 0.44066858291625977  (0.4593488305080228)
     | > postnet_loss: 0.29786407947540283  (0.3118012925473655)
     | > stopnet_loss: 0.0038457985501736403  (0.005371772417253474)
     | > loss: 0.1884789615869522  (0.19815930360701026)
     | > align_error: 0.5051029026508331  (0.5825276076793673)

   --> STEP: 42
     | > decoder_loss: 0.44574999809265137  (0.45902504878384726)
     | > postnet_loss: 0.3009403944015503  (0.31154269973436993)
     | > stopnet_loss: 0.0034204807598143816  (0.005325313092076353)
     | > loss: 0.19009308516979218  (0.1979672507870765)
     | > align_error: 0.5804007947444916  (0.582476969276156)

   --> STEP: 43
     | > decoder_loss: 0.44397374987602234  (0.4586750185766885)
     | > postnet_loss: 0.2999955415725708  (0.3112741611724676)
     | > stopnet_loss: 0.0030958950519561768  (0.0052734661609107674)
     | > loss: 0.18908822536468506  (0.19776076182376506)
     | > align_error: 0.5523108243942261  (0.5817754310230878)

   --> STEP: 44
     | > decoder_loss: 0.4618607461452484  (0.45874742147597397)
     | > postnet_loss: 0.30899301171302795  (0.31122231686657126)
     | > stopnet_loss: 0.0028708798345178366  (0.005218861926220019)
     | > loss: 0.19558431208133698  (0.1977112970568917)
     | > align_error: 0.5521931648254395  (0.581103106791323)

   --> STEP: 45
     | > decoder_loss: 0.4545123875141144  (0.4586533096101549)
     | > postnet_loss: 0.3077964186668396  (0.3111461857954661)
     | > stopnet_loss: 0.003503284649923444  (0.005180737986746762)
     | > loss: 0.19408048689365387  (0.19763061238659752)
     | > align_error: 0.5535439252853394  (0.5804906805356345)

   --> STEP: 46
     | > decoder_loss: 0.4458197057247162  (0.458374318221341)
     | > postnet_loss: 0.29976871609687805  (0.3108988494976707)
     | > stopnet_loss: 0.003369081299751997  (0.005141354145725137)
     | > loss: 0.18976618349552155  (0.19745964654113934)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.33890624118573726 (-0.01114963401447655)
     | > avg_decoder_loss: 0.4539145804715879 (-1.1082399975159696e-05)
     | > avg_postnet_loss: 0.3072508131012772 (-0.00040751424702739625)
     | > avg_stopnet_loss: 0.0045578922603674455 (-9.359957678526341e-06)
     | > avg_loss: 0.1948492405089465 (-0.00011400878429412842)
     | > avg_align_error: 0.5731621497508251 (+0.000518138661528833)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_604.pth

 > EPOCH: 4/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 21:02:56)

   --> TIME: 2025-12-27 21:03:30 -- STEP: 21/150 -- GLOBAL_STEP: 625
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49785107374191284  (0.49165553138369605)
     | > postnet_loss: 0.42294740676879883  (0.4238043555191585)
     | > stopnet_loss: 0.0071178306825459  (0.010507873037741297)
     | > loss: 0.23731745779514313  (0.2393728466261001)
     | > align_error: 0.6269808113574982  (0.6769530162924812)
     | > grad_norm: tensor(0.1830, device='cuda:0')  (tensor(0.2786, device='cuda:0'))
     | > step_time: 0.968  (0.6535535539899554)
     | > loader_time: 1.0317  (0.8828510443369547)


   --> TIME: 2025-12-27 21:04:19 -- STEP: 46/150 -- GLOBAL_STEP: 650
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5138750076293945  (0.49821385287720227)
     | > postnet_loss: 0.4265012741088867  (0.4236340399669564)
     | > stopnet_loss: 0.00502888485789299  (0.008024316048249602)
     | > loss: 0.2401229590177536  (0.2384862909498422)
     | > align_error: 0.662123441696167  (0.6509908930115078)
     | > grad_norm: tensor(0.1971, device='cuda:0')  (tensor(0.2439, device='cuda:0'))
     | > step_time: 1.19  (0.8487351718156234)
     | > loader_time: 1.0816  (0.926286096158235)


   --> TIME: 2025-12-27 21:05:22 -- STEP: 71/150 -- GLOBAL_STEP: 675
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5045968890190125  (0.5008648604574338)
     | > postnet_loss: 0.41688230633735657  (0.422342128317121)
     | > stopnet_loss: 0.004206559620797634  (0.006767245983495049)
     | > loss: 0.23457635939121246  (0.23756899464298303)
     | > align_error: 0.6078986525535583  (0.639114154056764)
     | > grad_norm: tensor(0.1652, device='cuda:0')  (tensor(0.2212, device='cuda:0'))
     | > step_time: 1.3782  (1.0169028362757724)
     | > loader_time: 1.2898  (1.0235434417993248)


   --> TIME: 2025-12-27 21:06:37 -- STEP: 96/150 -- GLOBAL_STEP: 700
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5063880681991577  (0.5016045756638051)
     | > postnet_loss: 0.4170312285423279  (0.421433812007308)
     | > stopnet_loss: 0.003646287601441145  (0.006043262976163533)
     | > loss: 0.23450110852718353  (0.23680286093925437)
     | > align_error: 0.6071993112564087  (0.6344503499567508)
     | > grad_norm: tensor(0.1479, device='cuda:0')  (tensor(0.2061, device='cuda:0'))
     | > step_time: 1.592  (1.1482098102569582)
     | > loader_time: 1.5438  (1.1416755691170695)


   --> TIME: 2025-12-27 21:08:03 -- STEP: 121/150 -- GLOBAL_STEP: 725
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5062034130096436  (0.502357774283275)
     | > postnet_loss: 0.4185613691806793  (0.420915006852347)
     | > stopnet_loss: 0.0030737295746803284  (0.005526573023920463)
     | > loss: 0.23426491022109985  (0.23634476873500287)
     | > align_error: 0.651383638381958  (0.629757945448899)
     | > grad_norm: tensor(0.1763, device='cuda:0')  (tensor(0.1938, device='cuda:0'))
     | > step_time: 1.8489  (1.2633395549679594)
     | > loader_time: 1.9005  (1.2603654841746186)


   --> TIME: 2025-12-27 21:09:44 -- STEP: 146/150 -- GLOBAL_STEP: 750
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5121848583221436  (0.503316594925645)
     | > postnet_loss: 0.4189550280570984  (0.42027163056478106)
     | > stopnet_loss: 0.003197894897311926  (0.005147461248370372)
     | > loss: 0.23598286509513855  (0.23604451783307612)
     | > align_error: 0.6275616884231567  (0.6258966630860548)
     | > grad_norm: tensor(0.1392, device='cuda:0')  (tensor(0.1875, device='cuda:0'))
     | > step_time: 2.3933  (1.3981053469932248)
     | > loader_time: 2.0592  (1.3864326003479635)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4786820709705353  (0.4786820709705353)
     | > postnet_loss: 0.3368757367134094  (0.3368757367134094)
     | > stopnet_loss: 0.01250715646892786  (0.01250715646892786)
     | > loss: 0.21639661490917206  (0.21639661490917206)
     | > align_error: 0.719476968050003  (0.719476968050003)

   --> STEP: 1
     | > decoder_loss: 0.4589402675628662  (0.4589402675628662)
     | > postnet_loss: 0.3217097520828247  (0.3217097520828247)
     | > stopnet_loss: 0.009950569830834866  (0.009950569830834866)
     | > loss: 0.20511306822299957  (0.20511306822299957)
     | > align_error: 0.6605626940727234  (0.6605626940727234)

   --> STEP: 2
     | > decoder_loss: 0.45255351066589355  (0.4557468891143799)
     | > postnet_loss: 0.3167981803417206  (0.31925396621227264)
     | > stopnet_loss: 0.011193173006176949  (0.010571871418505907)
     | > loss: 0.20353110134601593  (0.20432208478450775)
     | > align_error: 0.6583556234836578  (0.6594591587781906)

   --> STEP: 3
     | > decoder_loss: 0.4549919664859772  (0.45549524823824566)
     | > postnet_loss: 0.31331390142440796  (0.31727394461631775)
     | > stopnet_loss: 0.00876810122281313  (0.009970614686608315)
     | > loss: 0.20084457099437714  (0.2031629135211309)
     | > align_error: 0.7361833155155182  (0.6850338776906332)

   --> STEP: 4
     | > decoder_loss: 0.4652935862541199  (0.4579448327422142)
     | > postnet_loss: 0.32376840710639954  (0.3188975602388382)
     | > stopnet_loss: 0.00852474756538868  (0.009609147906303406)
     | > loss: 0.20579025149345398  (0.20381974801421165)
     | > align_error: 0.6060365736484528  (0.665284551680088)

   --> STEP: 5
     | > decoder_loss: 0.44557327032089233  (0.4554705202579498)
     | > postnet_loss: 0.3072524070739746  (0.31656852960586546)
     | > stopnet_loss: 0.008457045070827007  (0.009378727339208127)
     | > loss: 0.19666346907615662  (0.20238849222660066)
     | > align_error: 0.6439100205898285  (0.6610096454620361)

   --> STEP: 6
     | > decoder_loss: 0.4618203639984131  (0.45652882754802704)
     | > postnet_loss: 0.316698282957077  (0.31659015516440075)
     | > stopnet_loss: 0.007495782803744078  (0.009064903249964118)
     | > loss: 0.2021254450082779  (0.20234465102354685)
     | > align_error: 0.5959218144416809  (0.6501616736253103)

   --> STEP: 7
     | > decoder_loss: 0.46780019998550415  (0.4581390236105238)
     | > postnet_loss: 0.3156243860721588  (0.31645218815122333)
     | > stopnet_loss: 0.0066458978690207005  (0.008719331052686487)
     | > loss: 0.2025020569562912  (0.20236713758536748)
     | > align_error: 0.5812543034553528  (0.6403177636010307)

   --> STEP: 8
     | > decoder_loss: 0.4639574885368347  (0.45886633172631264)
     | > postnet_loss: 0.3154161274433136  (0.3163226805627346)
     | > stopnet_loss: 0.007519630249589682  (0.008569368452299386)
     | > loss: 0.2023630440235138  (0.20236662589013577)
     | > align_error: 0.5774795711040497  (0.632462989538908)

   --> STEP: 9
     | > decoder_loss: 0.4631251096725464  (0.45933952927589417)
     | > postnet_loss: 0.3176548480987549  (0.316470699177848)
     | > stopnet_loss: 0.006904010660946369  (0.008384328697704606)
     | > loss: 0.2020989954471588  (0.20233688917424944)
     | > align_error: 0.5949099659919739  (0.6282904313670264)

   --> STEP: 10
     | > decoder_loss: 0.4895651638507843  (0.4623620927333832)
     | > postnet_loss: 0.330455482006073  (0.31786917746067045)
     | > stopnet_loss: 0.005734449252486229  (0.008119340753182769)
     | > loss: 0.2107396125793457  (0.20317716151475906)
     | > align_error: 0.5858604311943054  (0.6240474313497544)

   --> STEP: 11
     | > decoder_loss: 0.47675999999046326  (0.46367099339311774)
     | > postnet_loss: 0.3245581090450287  (0.3184772621501576)
     | > stopnet_loss: 0.006019032560288906  (0.007928403644737873)
     | > loss: 0.20634855329990387  (0.20346546985886313)
     | > align_error: 0.5963357985019684  (0.6215281919999556)

   --> STEP: 12
     | > decoder_loss: 0.46943020820617676  (0.46415092796087265)
     | > postnet_loss: 0.31517818570137024  (0.31820233911275864)
     | > stopnet_loss: 0.008060473948717117  (0.00793940950340281)
     | > loss: 0.20421256124973297  (0.20352772747476897)
     | > align_error: 0.5900136232376099  (0.6189019779364268)

   --> STEP: 13
     | > decoder_loss: 0.4623619616031647  (0.46401331516412586)
     | > postnet_loss: 0.31673726439476013  (0.31808964105752796)
     | > stopnet_loss: 0.005813921336084604  (0.007775910413609102)
     | > loss: 0.20058873295783997  (0.20330165097346672)
     | > align_error: 0.5883075594902039  (0.6165485611328712)

   --> STEP: 14
     | > decoder_loss: 0.4657568633556366  (0.46413785432066235)
     | > postnet_loss: 0.31555092334747314  (0.31790830407823834)
     | > stopnet_loss: 0.005164016503840685  (0.0075893465629113584)
     | > loss: 0.20049096643924713  (0.20310088779245103)
     | > align_error: 0.5561398565769196  (0.6122336536645889)

   --> STEP: 15
     | > decoder_loss: 0.46961265802383423  (0.46450284123420715)
     | > postnet_loss: 0.322367399930954  (0.31820557713508607)
     | > stopnet_loss: 0.005173809360712767  (0.007428310749431452)
     | > loss: 0.2031688094139099  (0.2031054159005483)
     | > align_error: 0.589975893497467  (0.6107498029867808)

   --> STEP: 16
     | > decoder_loss: 0.4692610204219818  (0.46480022743344307)
     | > postnet_loss: 0.31391289830207825  (0.31793728470802307)
     | > stopnet_loss: 0.005314490757882595  (0.0072961969999596485)
     | > loss: 0.2011079639196396  (0.2029805751517415)
     | > align_error: 0.6079405546188354  (0.6105742249637842)

   --> STEP: 17
     | > decoder_loss: 0.4765062630176544  (0.4654888177619261)
     | > postnet_loss: 0.32439061999320984  (0.31831689266597524)
     | > stopnet_loss: 0.005021348129957914  (0.007162382360547782)
     | > loss: 0.20524556934833527  (0.20311381010448232)
     | > align_error: 0.5597469806671143  (0.6075843870639801)

   --> STEP: 18
     | > decoder_loss: 0.4735438823699951  (0.4659363213512633)
     | > postnet_loss: 0.3177470862865448  (0.3182852367560069)
     | > stopnet_loss: 0.005589437671005726  (0.007074996544462111)
     | > loss: 0.20341219007968903  (0.20313038676977158)
     | > align_error: 0.6048844456672668  (0.6074343903197182)

   --> STEP: 19
     | > decoder_loss: 0.4728667736053467  (0.466301081996215)
     | > postnet_loss: 0.317074716091156  (0.31822152514206736)
     | > stopnet_loss: 0.00509230000898242  (0.006970644095226338)
     | > loss: 0.20257766544818878  (0.2031012961738988)
     | > align_error: 0.6025723218917847  (0.6071784919814059)

   --> STEP: 20
     | > decoder_loss: 0.46705958247184753  (0.46633900701999664)
     | > postnet_loss: 0.31524932384490967  (0.3180729150772095)
     | > stopnet_loss: 0.004748311825096607  (0.006859527481719851)
     | > loss: 0.20032554864883423  (0.20296250879764557)
     | > align_error: 0.6235568225383759  (0.6079974085092544)

   --> STEP: 21
     | > decoder_loss: 0.463836133480072  (0.46621982256571454)
     | > postnet_loss: 0.3103550970554352  (0.3177053999333155)
     | > stopnet_loss: 0.004190141335129738  (0.0067324138556917506)
     | > loss: 0.19773796200752258  (0.20271372085525877)
     | > align_error: 0.562257319688797  (0.6058193090416136)

   --> STEP: 22
     | > decoder_loss: 0.46610119938850403  (0.466214430603114)
     | > postnet_loss: 0.31455832719802856  (0.3175623511726206)
     | > stopnet_loss: 0.0050750356167554855  (0.006657078481194648)
     | > loss: 0.20023992657661438  (0.20260127566077493)
     | > align_error: 0.6265168488025665  (0.6067601063034751)

   --> STEP: 23
     | > decoder_loss: 0.437262624502182  (0.4649556564248126)
     | > postnet_loss: 0.3030793070793152  (0.31693265360334644)
     | > stopnet_loss: 0.004755609203130007  (0.006574405903887489)
     | > loss: 0.18984109163284302  (0.20204648505086484)
     | > align_error: 0.5674114227294922  (0.6050492939741715)

   --> STEP: 24
     | > decoder_loss: 0.47331511974334717  (0.46530396739641827)
     | > postnet_loss: 0.31952351331710815  (0.3170406060914199)
     | > stopnet_loss: 0.004564268514513969  (0.0064906501793302596)
     | > loss: 0.20277392864227295  (0.20207679520050684)
     | > align_error: 0.5806830525398254  (0.6040340339144071)

   --> STEP: 25
     | > decoder_loss: 0.473055899143219  (0.4656140446662903)
     | > postnet_loss: 0.31596294045448303  (0.31699749946594236)
     | > stopnet_loss: 0.0038913178723305464  (0.006386676887050271)
     | > loss: 0.20114603638648987  (0.20203956484794616)
     | > align_error: 0.5596618950366974  (0.6022591483592987)

   --> STEP: 26
     | > decoder_loss: 0.44675716757774353  (0.46488878016288465)
     | > postnet_loss: 0.3030303418636322  (0.31646030109662276)
     | > stopnet_loss: 0.0046309963800013065  (0.0063191507137022335)
     | > loss: 0.1920778751373291  (0.20165642293599936)
     | > align_error: 0.5485750138759613  (0.6001943739560934)

   --> STEP: 27
     | > decoder_loss: 0.4433937668800354  (0.4640926685598161)
     | > postnet_loss: 0.3005385398864746  (0.31587060623698765)
     | > stopnet_loss: 0.004086930770426989  (0.006236475900988336)
     | > loss: 0.1900700032711029  (0.20122729628174393)
     | > align_error: 0.5425758957862854  (0.5980603562461005)

   --> STEP: 28
     | > decoder_loss: 0.44905543327331543  (0.46355562444244114)
     | > postnet_loss: 0.30377137660980225  (0.3154384908931596)
     | > stopnet_loss: 0.004101561848074198  (0.006160228970527116)
     | > loss: 0.19230826199054718  (0.2009087593427726)
     | > align_error: 0.5666002631187439  (0.596936781491552)

   --> STEP: 29
     | > decoder_loss: 0.44475239515304565  (0.4629072372255654)
     | > postnet_loss: 0.2993072271347046  (0.3148822404187301)
     | > stopnet_loss: 0.0037542737554758787  (0.006077264997594315)
     | > loss: 0.1897691786289215  (0.2005246358698812)
     | > align_error: 0.5416581332683563  (0.5950306212079937)

   --> STEP: 30
     | > decoder_loss: 0.44474005699157715  (0.46230166455109917)
     | > postnet_loss: 0.30057111382484436  (0.3144052028656006)
     | > stopnet_loss: 0.0031103568617254496  (0.00597836805973202)
     | > loss: 0.18943814933300018  (0.20015508631865184)
     | > align_error: 0.5347391366958618  (0.5930209050575892)

   --> STEP: 31
     | > decoder_loss: 0.4435957670211792  (0.4616982485017469)
     | > postnet_loss: 0.30289456248283386  (0.31403389188551134)
     | > stopnet_loss: 0.004128749016672373  (0.005918702929310741)
     | > loss: 0.1907513439655304  (0.1998517397911318)
     | > align_error: 0.5604376196861267  (0.5919698313359292)

   --> STEP: 32
     | > decoder_loss: 0.45057427883148193  (0.4613506244495511)
     | > postnet_loss: 0.3049905300140381  (0.3137512868270278)
     | > stopnet_loss: 0.004074295982718468  (0.005861065212229732)
     | > loss: 0.19296549260616302  (0.19963654456660151)
     | > align_error: 0.5320608615875244  (0.5900976760312915)

   --> STEP: 33
     | > decoder_loss: 0.44856372475624084  (0.4609631426406629)
     | > postnet_loss: 0.30449071526527405  (0.3134706634463686)
     | > stopnet_loss: 0.004175256472080946  (0.0058099800988918905)
     | > loss: 0.19243887066841125  (0.19941843323635333)
     | > align_error: 0.5461268723011017  (0.588765227433407)

   --> STEP: 34
     | > decoder_loss: 0.4547349810600281  (0.46077996141770305)
     | > postnet_loss: 0.3066783547401428  (0.31327088966089134)
     | > stopnet_loss: 0.003556195879355073  (0.005743692327729043)
     | > loss: 0.19390952587127686  (0.1992564065491452)
     | > align_error: 0.5637740790843964  (0.588030193658436)

   --> STEP: 35
     | > decoder_loss: 0.45174869894981384  (0.46052192534719194)
     | > postnet_loss: 0.3042971193790436  (0.31301449622426714)
     | > stopnet_loss: 0.003726577153429389  (0.005686060465606196)
     | > loss: 0.19273802638053894  (0.19907016711575645)
     | > align_error: 0.5347115099430084  (0.5865068026951381)

   --> STEP: 36
     | > decoder_loss: 0.4587979316711426  (0.46047403663396835)
     | > postnet_loss: 0.3092554211616516  (0.3129100774725278)
     | > stopnet_loss: 0.0039029393810778856  (0.005636529324369298)
     | > loss: 0.1959162801504135  (0.19898255914449692)
     | > align_error: 0.6344754695892334  (0.5878392656644186)

   --> STEP: 37
     | > decoder_loss: 0.4502483606338501  (0.46019766701234355)
     | > postnet_loss: 0.30535849928855896  (0.312705980764853)
     | > stopnet_loss: 0.0037689378950744867  (0.005586053880334303)
     | > loss: 0.19267065823078156  (0.19881196722791)
     | > align_error: 0.5195793807506561  (0.5859944039099926)

   --> STEP: 38
     | > decoder_loss: 0.4399697184562683  (0.45966535257665736)
     | > postnet_loss: 0.2994588017463684  (0.3123573707906823)
     | > stopnet_loss: 0.0033053362276405096  (0.005526034994737098)
     | > loss: 0.18816246092319489  (0.19853171706199643)
     | > align_error: 0.551263153553009  (0.5850804236374404)

   --> STEP: 39
     | > decoder_loss: 0.4525323212146759  (0.45948245433660656)
     | > postnet_loss: 0.30739185214042664  (0.31223004979965013)
     | > stopnet_loss: 0.003633504267781973  (0.005477508565840812)
     | > loss: 0.19361454248428345  (0.1984056356625679)
     | > align_error: 0.5468890070915222  (0.5841011565465194)

   --> STEP: 40
     | > decoder_loss: 0.44981855154037476  (0.45924085676670073)
     | > postnet_loss: 0.3061067461967468  (0.31207696720957756)
     | > stopnet_loss: 0.003209615359082818  (0.0054208112356718624)
     | > loss: 0.19219094514846802  (0.19825026839971538)
     | > align_error: 0.5847523212432861  (0.5841174356639385)

   --> STEP: 41
     | > decoder_loss: 0.44000309705734253  (0.458771643115253)
     | > postnet_loss: 0.2983407974243164  (0.31174193867822975)
     | > stopnet_loss: 0.003848297754302621  (0.005382457248321393)
     | > loss: 0.18843427300453186  (0.19801085387788164)
     | > align_error: 0.5046939551830292  (0.5821802776034285)

   --> STEP: 42
     | > decoder_loss: 0.44533979892730713  (0.4584518373012543)
     | > postnet_loss: 0.30181238055229187  (0.31150552062761216)
     | > stopnet_loss: 0.003412823425605893  (0.005335561204923405)
     | > loss: 0.19020088016986847  (0.19782490212292894)
     | > align_error: 0.5800789296627045  (0.5821302455096018)

   --> STEP: 43
     | > decoder_loss: 0.4437870383262634  (0.4581107954646266)
     | > postnet_loss: 0.3009481132030487  (0.31125999952471534)
     | > stopnet_loss: 0.0031101773492991924  (0.005283808092001911)
     | > loss: 0.18929395079612732  (0.19762650790602657)
     | > align_error: 0.5519713759422302  (0.5814288764498955)

   --> STEP: 44
     | > decoder_loss: 0.46166256070137024  (0.4581915174018253)
     | > postnet_loss: 0.3096989393234253  (0.31122452088377695)
     | > stopnet_loss: 0.0028773413505405188  (0.005229115666059607)
     | > loss: 0.1957177072763443  (0.1975831260735338)
     | > align_error: 0.551709771156311  (0.5807534422386776)

   --> STEP: 45
     | > decoder_loss: 0.4535177946090698  (0.4580876568953196)
     | > postnet_loss: 0.30830785632133484  (0.31115970611572263)
     | > stopnet_loss: 0.0034860079176723957  (0.005190379938317669)
     | > loss: 0.19394242763519287  (0.1975022216637929)
     | > align_error: 0.5532726645469666  (0.580142758289973)

   --> STEP: 46
     | > decoder_loss: 0.44555267691612244  (0.45781515733055445)
     | > postnet_loss: 0.3003343939781189  (0.310924373243166)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35578691236900556 (+0.016880671183268303)
     | > avg_decoder_loss: 0.45349777015772735 (-0.00041681031386053835)
     | > avg_postnet_loss: 0.30733067068186676 (+7.98575805895374e-05)
     | > avg_stopnet_loss: 0.0045635822179699035 (+5.689957602457961e-06)
     | > avg_loss: 0.1947706935532165 (-7.85469557300078e-05)
     | > avg_align_error: 0.5727755747961275 (-0.00038657495469762715)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_755.pth

 > EPOCH: 5/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 21:12:14)

   --> TIME: 2025-12-27 21:12:45 -- STEP: 20/150 -- GLOBAL_STEP: 775
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49322256445884705  (0.49078268855810164)
     | > postnet_loss: 0.4170651435852051  (0.4233024388551712)
     | > stopnet_loss: 0.007890691049396992  (0.0106581577565521)
     | > loss: 0.23546262085437775  (0.23917943686246873)
     | > align_error: 0.6318039894104004  (0.6789750799536705)
     | > grad_norm: tensor(0.1982, device='cuda:0')  (tensor(0.2540, device='cuda:0'))
     | > step_time: 0.8413  (0.5936125874519347)
     | > loader_time: 1.1895  (0.8942662835121155)


   --> TIME: 2025-12-27 21:13:34 -- STEP: 45/150 -- GLOBAL_STEP: 800
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5055068135261536  (0.4976645376947191)
     | > postnet_loss: 0.4224224090576172  (0.42314426501592)
     | > stopnet_loss: 0.005084361881017685  (0.008097765408456322)
     | > loss: 0.23706667125225067  (0.23829996552732255)
     | > align_error: 0.634197324514389  (0.6504289997948541)
     | > grad_norm: tensor(0.1408, device='cuda:0')  (tensor(0.2401, device='cuda:0'))
     | > step_time: 1.1755  (0.813081826104058)
     | > loader_time: 1.0341  (0.9407554096645779)


   --> TIME: 2025-12-27 21:14:36 -- STEP: 70/150 -- GLOBAL_STEP: 825
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5035416483879089  (0.5006225883960724)
     | > postnet_loss: 0.4167822301387787  (0.42208069052015035)
     | > stopnet_loss: 0.004298659507185221  (0.006812714472679154)
     | > loss: 0.2343796193599701  (0.2374885339822088)
     | > align_error: 0.5989825129508972  (0.6390146979263851)
     | > grad_norm: tensor(0.2018, device='cuda:0')  (tensor(0.2168, device='cuda:0'))
     | > step_time: 1.4262  (0.9824780327933175)
     | > loader_time: 1.2594  (1.0371461868286134)


   --> TIME: 2025-12-27 21:15:55 -- STEP: 95/150 -- GLOBAL_STEP: 850
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5062483549118042  (0.5016629426102887)
     | > postnet_loss: 0.4170861840248108  (0.4213331263316305)
     | > stopnet_loss: 0.0035806053783744574  (0.0060676631909844115)
     | > loss: 0.2344142347574234  (0.2368166801176573)
     | > align_error: 0.6053246259689331  (0.6344586168464861)
     | > grad_norm: tensor(0.1919, device='cuda:0')  (tensor(0.2181, device='cuda:0'))
     | > step_time: 1.5093  (1.1273829962077895)
     | > loader_time: 1.7739  (1.1824705701125298)


   --> TIME: 2025-12-27 21:17:19 -- STEP: 120/150 -- GLOBAL_STEP: 875
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5050956606864929  (0.5025675142804779)
     | > postnet_loss: 0.41624894738197327  (0.4209000607331594)
     | > stopnet_loss: 0.0033083048183470964  (0.005542853916995227)
     | > loss: 0.23364447057247162  (0.23640974797308445)
     | > align_error: 0.6241711974143982  (0.6295090834299721)
     | > grad_norm: tensor(0.1406, device='cuda:0')  (tensor(0.2085, device='cuda:0'))
     | > step_time: 1.9391  (1.245072849591573)
     | > loader_time: 1.8473  (1.2868510683377588)


   --> TIME: 2025-12-27 21:18:56 -- STEP: 145/150 -- GLOBAL_STEP: 900
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5098716020584106  (0.5034510700867091)
     | > postnet_loss: 0.4168263077735901  (0.420231622251971)
     | > stopnet_loss: 0.002888283459469676  (0.00515485015408746)
     | > loss: 0.23456275463104248  (0.23607552329014087)
     | > align_error: 0.6404821872711182  (0.6259831490187807)
     | > grad_norm: tensor(0.1738, device='cuda:0')  (tensor(0.2041, device='cuda:0'))
     | > step_time: 2.3152  (1.3785867477285452)
     | > loader_time: 1.7951  (1.385912970838876)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47796866297721863  (0.47796866297721863)
     | > postnet_loss: 0.33775144815444946  (0.33775144815444946)
     | > stopnet_loss: 0.01255663763731718  (0.01255663763731718)
     | > loss: 0.21648666262626648  (0.21648666262626648)
     | > align_error: 0.720236748456955  (0.720236748456955)

   --> STEP: 1
     | > decoder_loss: 0.4593058228492737  (0.4593058228492737)
     | > postnet_loss: 0.3238929808139801  (0.3238929808139801)
     | > stopnet_loss: 0.009913806803524494  (0.009913806803524494)
     | > loss: 0.20571351051330566  (0.20571351051330566)
     | > align_error: 0.6615975499153137  (0.6615975499153137)

   --> STEP: 2
     | > decoder_loss: 0.45203107595443726  (0.45566844940185547)
     | > postnet_loss: 0.3169621527194977  (0.3204275667667389)
     | > stopnet_loss: 0.011222895234823227  (0.01056835101917386)
     | > loss: 0.20347121357917786  (0.20459236204624176)
     | > align_error: 0.6593824923038483  (0.660490021109581)

   --> STEP: 3
     | > decoder_loss: 0.4542554020881653  (0.4551974336306254)
     | > postnet_loss: 0.3137877583503723  (0.3182142972946167)
     | > stopnet_loss: 0.008833053521811962  (0.009989918520053228)
     | > loss: 0.20084384083747864  (0.20334285497665405)
     | > align_error: 0.7366126477718353  (0.6858642299969991)

   --> STEP: 4
     | > decoder_loss: 0.4649122953414917  (0.457626149058342)
     | > postnet_loss: 0.3248586654663086  (0.3198753893375397)
     | > stopnet_loss: 0.008562703616917133  (0.009633114794269204)
     | > loss: 0.20600543916225433  (0.20400850102305412)
     | > align_error: 0.6066930294036865  (0.666071429848671)

   --> STEP: 5
     | > decoder_loss: 0.4455367624759674  (0.45520827174186707)
     | > postnet_loss: 0.30796217918395996  (0.31749274730682375)
     | > stopnet_loss: 0.008483369834721088  (0.009403165802359581)
     | > loss: 0.19685809314250946  (0.20257841944694518)
     | > align_error: 0.6449078917503357  (0.6618387222290039)

   --> STEP: 6
     | > decoder_loss: 0.4612383246421814  (0.4562132805585861)
     | > postnet_loss: 0.317514568567276  (0.3174963841835658)
     | > stopnet_loss: 0.00748469540849328  (0.009083420736715198)
     | > loss: 0.2021729201078415  (0.20251083622376123)
     | > align_error: 0.5973521769046783  (0.6510909646749496)

   --> STEP: 7
     | > decoder_loss: 0.4669949412345886  (0.45775351779801504)
     | > postnet_loss: 0.31592023372650146  (0.3172712198325566)
     | > stopnet_loss: 0.006661474704742432  (0.008737428446433373)
     | > loss: 0.20239026844501495  (0.2024936122553689)
     | > align_error: 0.582699179649353  (0.641320709671293)

   --> STEP: 8
     | > decoder_loss: 0.4635990858078003  (0.4584842137992382)
     | > postnet_loss: 0.31625989079475403  (0.31714480370283127)
     | > stopnet_loss: 0.007348432205617428  (0.00856380391633138)
     | > loss: 0.20231316983699799  (0.20247105695307255)
     | > align_error: 0.5782637000083923  (0.6334385834634304)

   --> STEP: 9
     | > decoder_loss: 0.4627781808376312  (0.45896132124794853)
     | > postnet_loss: 0.31801649928092957  (0.3172416587670644)
     | > stopnet_loss: 0.006832615006715059  (0.008371449593040679)
     | > loss: 0.20203128457069397  (0.20242219335503048)
     | > align_error: 0.595680296421051  (0.6292432182364993)

   --> STEP: 10
     | > decoder_loss: 0.49045756459236145  (0.46211094558238985)
     | > postnet_loss: 0.3320860266685486  (0.3187260955572128)
     | > stopnet_loss: 0.005711251869797707  (0.008105429820716381)
     | > loss: 0.21134716272354126  (0.20331469029188157)
     | > align_error: 0.5874688625335693  (0.6250657826662064)

   --> STEP: 11
     | > decoder_loss: 0.476125568151474  (0.4633850021795793)
     | > postnet_loss: 0.3244524896144867  (0.3192466768351468)
     | > stopnet_loss: 0.00605213874951005  (0.00791876699606126)
     | > loss: 0.2061966508626938  (0.20357668670740994)
     | > align_error: 0.5974696278572083  (0.6225570413199338)

   --> STEP: 12
     | > decoder_loss: 0.4695778787136078  (0.4639010752240817)
     | > postnet_loss: 0.31606602668762207  (0.3189816226561864)
     | > stopnet_loss: 0.008095094002783298  (0.007933460913288096)
     | > loss: 0.20450608432292938  (0.20365413650870323)
     | > align_error: 0.5911257863044739  (0.6199377700686455)

   --> STEP: 13
     | > decoder_loss: 0.4630996584892273  (0.463839427782939)
     | > postnet_loss: 0.31775394082069397  (0.31888718559191775)
     | > stopnet_loss: 0.00580581882968545  (0.007769796137626355)
     | > loss: 0.20101922750473022  (0.20345145120070532)
     | > align_error: 0.5898302793502808  (0.6176218092441559)

   --> STEP: 14
     | > decoder_loss: 0.4654093384742737  (0.4639515642608915)
     | > postnet_loss: 0.31549084186553955  (0.3186445896114622)
     | > stopnet_loss: 0.005185707006603479  (0.007585218342553292)
     | > loss: 0.20041075348854065  (0.20323425850697927)
     | > align_error: 0.5577687621116638  (0.613346591591835)

   --> STEP: 15
     | > decoder_loss: 0.4700391888618469  (0.4643574059009552)
     | > postnet_loss: 0.32211512327194214  (0.31887595852216083)
     | > stopnet_loss: 0.005181151907891035  (0.007424947246909142)
     | > loss: 0.2032197266817093  (0.20323328971862792)
     | > align_error: 0.5914153456687927  (0.6118845085302989)

   --> STEP: 16
     | > decoder_loss: 0.4707864820957184  (0.4647592231631279)
     | > postnet_loss: 0.31443315744400024  (0.3185982834547758)
     | > stopnet_loss: 0.00532261049374938  (0.0072935511998366565)
     | > loss: 0.20162752270698547  (0.20313292928040028)
     | > align_error: 0.6100567579269409  (0.611770274117589)

   --> STEP: 17
     | > decoder_loss: 0.4772239029407501  (0.4654924396206351)
     | > postnet_loss: 0.32432547211647034  (0.31893517690546375)
     | > stopnet_loss: 0.005031617823988199  (0.007160496295374983)
     | > loss: 0.20541895925998688  (0.20326740163214066)
     | > align_error: 0.5610578656196594  (0.6087871912647697)

   --> STEP: 18
     | > decoder_loss: 0.4733145534992218  (0.46592700150277877)
     | > postnet_loss: 0.3173281252384186  (0.31884589625729454)
     | > stopnet_loss: 0.005595528054982424  (0.007073553615353174)
     | > loss: 0.20325620472431183  (0.20326677958170572)
     | > align_error: 0.6062101125717163  (0.6086440202262666)

   --> STEP: 19
     | > decoder_loss: 0.47172293066978455  (0.4662320504063054)
     | > postnet_loss: 0.3165775239467621  (0.3187265082409507)
     | > stopnet_loss: 0.0051149846985936165  (0.0069704710407868815)
     | > loss: 0.202190101146698  (0.2032101122956527)
     | > align_error: 0.6038373708724976  (0.6083910386813315)

   --> STEP: 20
     | > decoder_loss: 0.46681296825408936  (0.4662610962986946)
     | > postnet_loss: 0.3144797086715698  (0.3185141682624817)
     | > stopnet_loss: 0.004737360868602991  (0.006858815532177686)
     | > loss: 0.20006053149700165  (0.20305263325572015)
     | > align_error: 0.6249549388885498  (0.6092192336916924)

   --> STEP: 21
     | > decoder_loss: 0.46384119987487793  (0.4661458631356557)
     | > postnet_loss: 0.31035083532333374  (0.31812543812252225)
     | > stopnet_loss: 0.0042172325775027275  (0.006733025867669355)
     | > loss: 0.19776524603366852  (0.2028008529118129)
     | > align_error: 0.5636898875236511  (0.6070511695884523)

   --> STEP: 22
     | > decoder_loss: 0.46617794036865234  (0.46614732119170105)
     | > postnet_loss: 0.31445348262786865  (0.31795853105458344)
     | > stopnet_loss: 0.005077899433672428  (0.0066577928479422226)
     | > loss: 0.2002357542514801  (0.20268425751816144)
     | > align_error: 0.6278455257415771  (0.6079963675954125)

   --> STEP: 23
     | > decoder_loss: 0.43774497509002686  (0.4649124365785848)
     | > postnet_loss: 0.3030291795730591  (0.3173094288162563)
     | > stopnet_loss: 0.00473350053653121  (0.006574127964837396)
     | > loss: 0.18992704153060913  (0.20212959595348523)
     | > align_error: 0.5688320994377136  (0.6062935733276865)

   --> STEP: 24
     | > decoder_loss: 0.4735167920589447  (0.4652709513902664)
     | > postnet_loss: 0.31902045011520386  (0.3173807213703791)
     | > stopnet_loss: 0.004578626714646816  (0.006490982079412788)
     | > loss: 0.20271292328834534  (0.2021539012591044)
     | > align_error: 0.5823616087436676  (0.6052964081366857)

   --> STEP: 25
     | > decoder_loss: 0.47336429357528687  (0.4655946850776672)
     | > postnet_loss: 0.3154695928096771  (0.317304276227951)
     | > stopnet_loss: 0.003890729509294033  (0.006386971976608038)
     | > loss: 0.2010991871356964  (0.20211171269416808)
     | > align_error: 0.5613411366939545  (0.6035381972789764)

   --> STEP: 26
     | > decoder_loss: 0.4461527466773987  (0.46484691821611845)
     | > postnet_loss: 0.30293983221054077  (0.31675179761189676)
     | > stopnet_loss: 0.004623735323548317  (0.0063191551822595875)
     | > loss: 0.19189688563346863  (0.20171883473029503)
     | > align_error: 0.5496047735214233  (0.6014638348267628)

   --> STEP: 27
     | > decoder_loss: 0.4434780478477478  (0.46405547857284546)
     | > postnet_loss: 0.30002304911613464  (0.3161322143342759)
     | > stopnet_loss: 0.004085918422788382  (0.0062364427096865795)
     | > loss: 0.18996118009090424  (0.20128336603994723)
     | > align_error: 0.5438999533653259  (0.59933183921708)

   --> STEP: 28
     | > decoder_loss: 0.44901731610298157  (0.4635184013417789)
     | > postnet_loss: 0.30323168635368347  (0.3156714811921119)
     | > stopnet_loss: 0.004095704760402441  (0.006159987782926432)
     | > loss: 0.19215795397758484  (0.20095745846629143)
     | > align_error: 0.5680551528930664  (0.5982148147055081)

   --> STEP: 29
     | > decoder_loss: 0.44516101479530334  (0.4628853880125901)
     | > postnet_loss: 0.29943469166755676  (0.31511159189816174)
     | > stopnet_loss: 0.0037812059745192528  (0.006077960824015839)
     | > loss: 0.18993012607097626  (0.20057720562507367)
     | > align_error: 0.5430798232555389  (0.596313608103785)

   --> STEP: 30
     | > decoder_loss: 0.4444599747657776  (0.4622712075710297)
     | > postnet_loss: 0.30013570189476013  (0.314612395564715)
     | > stopnet_loss: 0.0031051121186465025  (0.005978865867170195)
     | > loss: 0.189254030585289  (0.20019976645708085)
     | > align_error: 0.5360649824142456  (0.5943053205808003)

   --> STEP: 31
     | > decoder_loss: 0.44436419010162354  (0.46169356184621013)
     | > postnet_loss: 0.30254507064819336  (0.3142231270190208)
     | > stopnet_loss: 0.004091168753802776  (0.005917972411900278)
     | > loss: 0.19081848859786987  (0.1998971445906547)
     | > align_error: 0.5618628263473511  (0.5932587885087536)

   --> STEP: 32
     | > decoder_loss: 0.45088163018226624  (0.46135568898171186)
     | > postnet_loss: 0.3048562705516815  (0.3139304127544164)
     | > stopnet_loss: 0.004073197487741709  (0.005860323195520323)
     | > loss: 0.1930076777935028  (0.19968184875324368)
     | > align_error: 0.5335867404937744  (0.5913940370082855)

   --> STEP: 33
     | > decoder_loss: 0.4487084448337555  (0.4609724391590465)
     | > postnet_loss: 0.3037632703781128  (0.31362231753089204)
     | > stopnet_loss: 0.004171012435108423  (0.005809131960356326)
     | > loss: 0.19228893518447876  (0.1994578210693417)
     | > align_error: 0.5479028224945068  (0.5900761214169589)

   --> STEP: 34
     | > decoder_loss: 0.45468756556510925  (0.4607875899356954)
     | > postnet_loss: 0.3058295249938965  (0.3133931177503922)
     | > stopnet_loss: 0.0035517578944563866  (0.005742738605476916)
     | > loss: 0.1936810314655304  (0.19928791549275904)
     | > align_error: 0.5655252933502197  (0.5893540382385254)

   --> STEP: 35
     | > decoder_loss: 0.45148685574531555  (0.46052185467311313)
     | > postnet_loss: 0.3037717342376709  (0.31311822107860016)
     | > stopnet_loss: 0.003696380415931344  (0.005684271228632756)
     | > loss: 0.19251102209091187  (0.19909428996699197)
     | > align_error: 0.5358930230140686  (0.5878265806606837)

   --> STEP: 36
     | > decoder_loss: 0.4585557281970978  (0.46046724004877937)
     | > postnet_loss: 0.30848532915115356  (0.3129895296361711)
     | > stopnet_loss: 0.003882115939632058  (0.005634211359493848)
     | > loss: 0.1956423819065094  (0.19899840363197857)
     | > align_error: 0.6358421146869659  (0.5891603454947472)

   --> STEP: 37
     | > decoder_loss: 0.44983088970184326  (0.4601797711204838)
     | > postnet_loss: 0.30471131205558777  (0.3127657940258851)
     | > stopnet_loss: 0.0037571315187960863  (0.0055834794719074226)
     | > loss: 0.19239269196987152  (0.19881987088435404)
     | > align_error: 0.5211345255374908  (0.5873218098202267)

   --> STEP: 38
     | > decoder_loss: 0.44011297821998596  (0.45965169762310226)
     | > postnet_loss: 0.298962265253067  (0.31240254326870565)
     | > stopnet_loss: 0.003314501605927944  (0.005523769528065857)
     | > loss: 0.18808330595493317  (0.19853732970200086)
     | > align_error: 0.5532923936843872  (0.5864262988692835)

   --> STEP: 39
     | > decoder_loss: 0.45257407426834106  (0.4594702201011853)
     | > postnet_loss: 0.3070789575576782  (0.31226604107098704)
     | > stopnet_loss: 0.0036424400750547647  (0.005475530311321983)
     | > loss: 0.19355569779872894  (0.19840959555063492)
     | > align_error: 0.5482966303825378  (0.5854486150619311)

   --> STEP: 40
     | > decoder_loss: 0.4499673545360565  (0.45923264846205714)
     | > postnet_loss: 0.30590352416038513  (0.312106978148222)
     | > stopnet_loss: 0.003213941352441907  (0.005418990587349981)
     | > loss: 0.19218166172504425  (0.19825389720499514)
     | > align_error: 0.5861900746822357  (0.5854671515524388)

   --> STEP: 41
     | > decoder_loss: 0.4401589035987854  (0.458767435172709)
     | > postnet_loss: 0.2979862093925476  (0.31176256915418116)
     | > stopnet_loss: 0.003828330896794796  (0.005380194009531562)
     | > loss: 0.18836461007595062  (0.1980126950798965)
     | > align_error: 0.5061125159263611  (0.5835316726347295)

   --> STEP: 42
     | > decoder_loss: 0.44526177644729614  (0.458445871869723)
     | > postnet_loss: 0.30094245076179504  (0.3115049472876958)
     | > stopnet_loss: 0.003420487744733691  (0.005333534336560184)
     | > loss: 0.18997155129909515  (0.19782123927559173)
     | > align_error: 0.5816781520843506  (0.5834875411930538)

   --> STEP: 43
     | > decoder_loss: 0.44394367933273315  (0.4581086115781651)
     | > postnet_loss: 0.30042919516563416  (0.31124737165695016)
     | > stopnet_loss: 0.0030987628269940615  (0.005281562906105158)
     | > loss: 0.18919196724891663  (0.1976205585307853)
     | > align_error: 0.5535353422164917  (0.582790978426157)

   --> STEP: 44
     | > decoder_loss: 0.46127912402153015  (0.4581806686791507)
     | > postnet_loss: 0.3089936077594757  (0.3111961497501894)
     | > stopnet_loss: 0.002865445101633668  (0.005226651137821715)
     | > loss: 0.1954336315393448  (0.1975708556446162)
     | > align_error: 0.5536299347877502  (0.5821282274343751)

   --> STEP: 45
     | > decoder_loss: 0.45402345061302185  (0.4580882860554589)
     | > postnet_loss: 0.3080662190914154  (0.31112659573554996)
     | > stopnet_loss: 0.0034956298768520355  (0.005188183998689056)
     | > loss: 0.19401805102825165  (0.1974919044309192)
     | > align_error: 0.5548627972602844  (0.5815223289860619)

   --> STEP: 46
     | > decoder_loss: 0.4454033374786377  (0.4578125263037889)
     | > postnet_loss: 0.29997119307518005  (0.31088408698206366)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35695881554574677 (+0.001171903176741207)
     | > avg_decoder_loss: 0.4534390758384358 (-5.8694319291563435e-05)
     | > avg_postnet_loss: 0.3073597848415375 (+2.9114159670717843e-05)
     | > avg_stopnet_loss: 0.004563507401723076 (-7.481624682715432e-08)
     | > avg_loss: 0.19476322333017984 (-7.470223036654122e-06)
     | > avg_align_error: 0.5742713411649069 (+0.0014957663687793499)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_906.pth

 > EPOCH: 6/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 21:21:22)

   --> TIME: 2025-12-27 21:21:50 -- STEP: 19/150 -- GLOBAL_STEP: 925
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.5007168650627136  (0.49074585814225047)
     | > postnet_loss: 0.4236597716808319  (0.4234993708761115)
     | > stopnet_loss: 0.008438595570623875  (0.01087182279872267)
     | > loss: 0.23953275382518768  (0.23943312936707548)
     | > align_error: 0.6383077204227448  (0.6820990772623765)
     | > grad_norm: tensor(0.2236, device='cuda:0')  (tensor(0.2702, device='cuda:0'))
     | > step_time: 0.7944  (0.6158401338677657)
     | > loader_time: 0.9876  (0.8312869950344688)


   --> TIME: 2025-12-27 21:22:39 -- STEP: 44/150 -- GLOBAL_STEP: 950
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5016558170318604  (0.4975696375424212)
     | > postnet_loss: 0.41800838708877563  (0.42326552691784775)
     | > stopnet_loss: 0.005005599930882454  (0.008160439489239996)
     | > loss: 0.2349216490983963  (0.23836922882632774)
     | > align_error: 0.5923249125480652  (0.6515999876640058)
     | > grad_norm: tensor(0.1683, device='cuda:0')  (tensor(0.2372, device='cuda:0'))
     | > step_time: 1.1502  (0.8259942856701936)
     | > loader_time: 1.0727  (0.9075946049256758)


   --> TIME: 2025-12-27 21:23:41 -- STEP: 69/150 -- GLOBAL_STEP: 975
     | > current_lr: 1e-05  (1.0000000000000016e-05)
     | > decoder_loss: 0.5097827911376953  (0.5004812250102776)
     | > postnet_loss: 0.424774169921875  (0.42218259927155316)
     | > stopnet_loss: 0.004239195957779884  (0.006845315341311304)
     | > loss: 0.2378784418106079  (0.2375112705040669)
     | > align_error: 0.6130467653274536  (0.6404185869555542)
     | > grad_norm: tensor(0.1329, device='cuda:0')  (tensor(0.2368, device='cuda:0'))
     | > step_time: 1.3165  (0.999287674392479)
     | > loader_time: 1.2432  (1.000550335732059)


   --> TIME: 2025-12-27 21:24:56 -- STEP: 94/150 -- GLOBAL_STEP: 1000
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5029171109199524  (0.5012675102086778)
     | > postnet_loss: 0.41995111107826233  (0.42119700445773756)
     | > stopnet_loss: 0.00399533798918128  (0.006092291090023169)
     | > loss: 0.2347124069929123  (0.2367084191200581)
     | > align_error: 0.6183705031871796  (0.6354830762807361)
     | > grad_norm: tensor(0.1459, device='cuda:0')  (tensor(0.2217, device='cuda:0'))
     | > step_time: 1.588  (1.141107997995742)
     | > loader_time: 1.6184  (1.1222216068430146)


   --> TIME: 2025-12-27 21:26:28 -- STEP: 119/150 -- GLOBAL_STEP: 1025
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.501919150352478  (0.5021255229200637)
     | > postnet_loss: 0.41495686769485474  (0.42069369354167907)
     | > stopnet_loss: 0.0032863758970052004  (0.005562075677899127)
     | > loss: 0.23250538110733032  (0.2362668788483163)
     | > align_error: 0.6178608536720276  (0.6302704242598111)
     | > grad_norm: tensor(0.1465, device='cuda:0')  (tensor(0.2062, device='cuda:0'))
     | > step_time: 1.8  (1.2688376042021428)
     | > loader_time: 2.3258  (1.295805864975232)


   --> TIME: 2025-12-27 21:28:14 -- STEP: 144/150 -- GLOBAL_STEP: 1050
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5089415907859802  (0.5031340602371428)
     | > postnet_loss: 0.4162263870239258  (0.42007747540871293)
     | > stopnet_loss: 0.002855472033843398  (0.005169327585867399)
     | > loss: 0.23414745926856995  (0.23597221128228638)
     | > align_error: 0.5964561998844147  (0.6263094078749419)
     | > grad_norm: tensor(0.1699, device='cuda:0')  (tensor(0.2061, device='cuda:0'))
     | > step_time: 2.205  (1.3977560980452435)
     | > loader_time: 2.0079  (1.4564828938908048)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47829389572143555  (0.47829389572143555)
     | > postnet_loss: 0.336040735244751  (0.336040735244751)
     | > stopnet_loss: 0.012459308840334415  (0.012459308840334415)
     | > loss: 0.21604296565055847  (0.21604296565055847)
     | > align_error: 0.7199566960334778  (0.7199566960334778)

   --> STEP: 1
     | > decoder_loss: 0.45853617787361145  (0.45853617787361145)
     | > postnet_loss: 0.32066601514816284  (0.32066601514816284)
     | > stopnet_loss: 0.009907600469887257  (0.009907600469887257)
     | > loss: 0.20470815896987915  (0.20470815896987915)
     | > align_error: 0.6612443327903748  (0.6612443327903748)

   --> STEP: 2
     | > decoder_loss: 0.4533071517944336  (0.4559216648340225)
     | > postnet_loss: 0.31725481152534485  (0.31896041333675385)
     | > stopnet_loss: 0.011248971335589886  (0.010578285902738571)
     | > loss: 0.20388945937156677  (0.20429880917072296)
     | > align_error: 0.6588845252990723  (0.6600644290447235)

   --> STEP: 3
     | > decoder_loss: 0.45535939931869507  (0.45573424299558)
     | > postnet_loss: 0.3133848309516907  (0.3171018858750661)
     | > stopnet_loss: 0.00871145911514759  (0.00995601030687491)
     | > loss: 0.20089751482009888  (0.2031650443871816)
     | > align_error: 0.7362709641456604  (0.6854666074117025)

   --> STEP: 4
     | > decoder_loss: 0.4645600914955139  (0.4579407051205635)
     | > postnet_loss: 0.3230641186237335  (0.31859244406223297)
     | > stopnet_loss: 0.008495073765516281  (0.009590776171535254)
     | > loss: 0.20540113747119904  (0.20372406765818596)
     | > align_error: 0.6063421964645386  (0.6656855046749115)

   --> STEP: 5
     | > decoder_loss: 0.44605889916419983  (0.4555643439292908)
     | > postnet_loss: 0.3073125183582306  (0.3163364589214325)
     | > stopnet_loss: 0.008483528159558773  (0.009369326569139958)
     | > loss: 0.19682638347148895  (0.20234453082084655)
     | > align_error: 0.6446182131767273  (0.6614720463752747)

   --> STEP: 6
     | > decoder_loss: 0.46130383014678955  (0.4565209249655406)
     | > postnet_loss: 0.31623655557632446  (0.3163198083639145)
     | > stopnet_loss: 0.007455155253410339  (0.009050298016518354)
     | > loss: 0.20184025168418884  (0.20226048429807028)
     | > align_error: 0.5965456366539001  (0.6506509780883789)

   --> STEP: 7
     | > decoder_loss: 0.46786943078041077  (0.4581421400819506)
     | > postnet_loss: 0.31609266996383667  (0.31628736002104624)
     | > stopnet_loss: 0.006609439384192228  (0.00870160392618605)
     | > loss: 0.20259997248649597  (0.20230898261070251)
     | > align_error: 0.5821314752101898  (0.640862477677209)

   --> STEP: 8
     | > decoder_loss: 0.46192026138305664  (0.45861440524458885)
     | > postnet_loss: 0.3140394687652588  (0.3160063736140728)
     | > stopnet_loss: 0.00720618199557066  (0.008514676184859127)
     | > loss: 0.2011961191892624  (0.2021698746830225)
     | > align_error: 0.5768651962280273  (0.6328628174960613)

   --> STEP: 9
     | > decoder_loss: 0.4627199172973633  (0.4590705732504527)
     | > postnet_loss: 0.31759509444236755  (0.31618289815055)
     | > stopnet_loss: 0.006828609388321638  (0.008327335429688295)
     | > loss: 0.20190736651420593  (0.20214070710870954)
     | > align_error: 0.5947173833847046  (0.6286244359281328)

   --> STEP: 10
     | > decoder_loss: 0.490631639957428  (0.4622266799211502)
     | > postnet_loss: 0.3308790326118469  (0.3176525115966797)
     | > stopnet_loss: 0.00572405569255352  (0.008067007455974818)
     | > loss: 0.2111017256975174  (0.20303680896759033)
     | > align_error: 0.5874588489532471  (0.6245078772306443)

   --> STEP: 11
     | > decoder_loss: 0.4757511615753174  (0.46345617825334723)
     | > postnet_loss: 0.32393118739128113  (0.31822330030527984)
     | > stopnet_loss: 0.0059985993430018425  (0.007878970354795456)
     | > loss: 0.20591919124126434  (0.20329884371974252)
     | > align_error: 0.5967381000518799  (0.6219833520325747)

   --> STEP: 12
     | > decoder_loss: 0.47016480565071106  (0.4640152305364609)
     | > postnet_loss: 0.3153516352176666  (0.31798399488131207)
     | > stopnet_loss: 0.008112814277410507  (0.00789845734834671)
     | > loss: 0.20449192821979523  (0.20339826742808023)
     | > align_error: 0.5905107855796814  (0.6193606381615003)

   --> STEP: 13
     | > decoder_loss: 0.4623003900051117  (0.4638833197263571)
     | > postnet_loss: 0.31682097911834717  (0.31789453213031477)
     | > stopnet_loss: 0.0057651204988360405  (0.007734354513768966)
     | > loss: 0.20054547488689423  (0.20317882184798902)
     | > align_error: 0.5888599157333374  (0.6170144287439493)

   --> STEP: 14
     | > decoder_loss: 0.4647122025489807  (0.4639425256422588)
     | > postnet_loss: 0.31455957889556885  (0.3176563211849758)
     | > stopnet_loss: 0.005132186226546764  (0.007548485350395952)
     | > loss: 0.19995012879371643  (0.20294820091554097)
     | > align_error: 0.5568675994873047  (0.612718226654189)

   --> STEP: 15
     | > decoder_loss: 0.47047629952430725  (0.46437811056772865)
     | > postnet_loss: 0.3229779303073883  (0.3180110951264699)
     | > stopnet_loss: 0.005158250220119953  (0.007389136341710885)
     | > loss: 0.20352180302143097  (0.20298644105593364)
     | > align_error: 0.5908887684345245  (0.6112629294395446)

   --> STEP: 16
     | > decoder_loss: 0.4687173664569855  (0.46464931406080723)
     | > postnet_loss: 0.313841849565506  (0.3177505172789097)
     | > stopnet_loss: 0.005313172936439514  (0.007259388628881425)
     | > loss: 0.20095297694206238  (0.20285934954881668)
     | > align_error: 0.6083424091339111  (0.6110803969204426)

   --> STEP: 17
     | > decoder_loss: 0.4770865738391876  (0.46538091757718253)
     | > postnet_loss: 0.32479533553123474  (0.3181649183525759)
     | > stopnet_loss: 0.005050102714449167  (0.007129430633914822)
     | > loss: 0.20552058517932892  (0.20301589282119975)
     | > align_error: 0.5604941844940186  (0.6081047373659471)

   --> STEP: 18
     | > decoder_loss: 0.47213661670684814  (0.4657562341954973)
     | > postnet_loss: 0.3170938789844513  (0.31810541616545784)
     | > stopnet_loss: 0.005561869125813246  (0.007042343883464734)
     | > loss: 0.2028694897890091  (0.2030077593194114)
     | > align_error: 0.6055276393890381  (0.6079615652561188)

   --> STEP: 19
     | > decoder_loss: 0.47122135758399963  (0.46604387226857635)
     | > postnet_loss: 0.3160589635372162  (0.3179977081323925)
     | > stopnet_loss: 0.004958574194461107  (0.006932671794569806)
     | > loss: 0.20177865028381348  (0.2029430693701694)
     | > align_error: 0.6027944386005402  (0.6076896112216147)

   --> STEP: 20
     | > decoder_loss: 0.4658227860927582  (0.46603281795978546)
     | > postnet_loss: 0.3146822154521942  (0.31783193349838257)
     | > stopnet_loss: 0.00471712788566947  (0.006821894599124789)
     | > loss: 0.1998433768749237  (0.2027880847454071)
     | > align_error: 0.6245144009590149  (0.6085308507084848)

   --> STEP: 21
     | > decoder_loss: 0.46358901262283325  (0.46591644627707346)
     | > postnet_loss: 0.31009888648986816  (0.3174636931646438)
     | > stopnet_loss: 0.004182564094662666  (0.006696212194150402)
     | > loss: 0.19760453701019287  (0.20254124913896834)
     | > align_error: 0.5626699328422546  (0.6063469974767596)

   --> STEP: 22
     | > decoder_loss: 0.4656706750392914  (0.46590527485717426)
     | > postnet_loss: 0.3143162131309509  (0.317320625890385)
     | > stopnet_loss: 0.005065763369202614  (0.006622100883925503)
     | > loss: 0.20006248354911804  (0.2024285779757933)
     | > align_error: 0.6272582411766052  (0.6072975085540253)

   --> STEP: 23
     | > decoder_loss: 0.43707820773124695  (0.4646519241125687)
     | > postnet_loss: 0.3031027317047119  (0.3167024565779645)
     | > stopnet_loss: 0.004761368967592716  (0.00654119949625886)
     | > loss: 0.18980661034584045  (0.20187979677449103)
     | > align_error: 0.5681460499763489  (0.6055952712245611)

   --> STEP: 24
     | > decoder_loss: 0.4721885025501251  (0.46496594821413356)
     | > postnet_loss: 0.3187907338142395  (0.31678946812947595)
     | > stopnet_loss: 0.004570404067635536  (0.006459083020066221)
     | > loss: 0.20231522619724274  (0.20189793966710567)
     | > align_error: 0.5816903710365295  (0.6045992337167264)

   --> STEP: 25
     | > decoder_loss: 0.47255608439445496  (0.4652695536613464)
     | > postnet_loss: 0.315487265586853  (0.316737380027771)
     | > stopnet_loss: 0.003863370046019554  (0.0063552545011043545)
     | > loss: 0.2008742094039917  (0.20185699045658112)
     | > align_error: 0.5608088672161102  (0.6028476190567018)

   --> STEP: 26
     | > decoder_loss: 0.44596898555755615  (0.46452722411889297)
     | > postnet_loss: 0.3024645447731018  (0.31618842482566833)
     | > stopnet_loss: 0.004614593926817179  (0.006288306017477925)
     | > loss: 0.19172297418117523  (0.20146722059983474)
     | > align_error: 0.5491421818733215  (0.6007820253188795)

   --> STEP: 27
     | > decoder_loss: 0.442727267742157  (0.463719818327162)
     | > postnet_loss: 0.30042099952697754  (0.315604446110902)
     | > stopnet_loss: 0.004078425467014313  (0.006206458589682977)
     | > loss: 0.18986549973487854  (0.201037527234466)
     | > align_error: 0.5433050394058228  (0.5986532480628404)

   --> STEP: 28
     | > decoder_loss: 0.448504239320755  (0.4631764047912189)
     | > postnet_loss: 0.30328625440597534  (0.31516451069286894)
     | > stopnet_loss: 0.0040843291208148  (0.006130668251509113)
     | > loss: 0.19203196465969086  (0.20071589999965259)
     | > align_error: 0.5676923990249634  (0.5975475034543447)

   --> STEP: 29
     | > decoder_loss: 0.4444917142391205  (0.4625321051170086)
     | > postnet_loss: 0.2988783121109009  (0.31460291763831827)
     | > stopnet_loss: 0.0037682405672967434  (0.006049205227915583)
     | > loss: 0.18961074948310852  (0.20033296377494417)
     | > align_error: 0.5423652529716492  (0.5956446672308036)

   --> STEP: 30
     | > decoder_loss: 0.44431936740875244  (0.46192501386006674)
     | > postnet_loss: 0.2999202013015747  (0.31411349376042685)
     | > stopnet_loss: 0.003100118599832058  (0.005950902340312799)
     | > loss: 0.18916000425815582  (0.19996053179105122)
     | > align_error: 0.5353915393352509  (0.5936362296342851)

   --> STEP: 31
     | > decoder_loss: 0.4433821737766266  (0.46132685772834287)
     | > postnet_loss: 0.3024739623069763  (0.31373802500386394)
     | > stopnet_loss: 0.004122571088373661  (0.005891923912830891)
     | > loss: 0.1905866116285324  (0.19965814726967965)
     | > align_error: 0.5614278316497803  (0.5925972490541398)

   --> STEP: 32
     | > decoder_loss: 0.4500395655632019  (0.4609741298481822)
     | > postnet_loss: 0.3046222925186157  (0.3134531583636999)
     | > stopnet_loss: 0.004058402497321367  (0.0058346263685962185)
     | > loss: 0.19272387027740479  (0.19944145111367106)
     | > align_error: 0.5329069495201111  (0.5907319271937014)

   --> STEP: 33
     | > decoder_loss: 0.447958767414093  (0.4605797249259371)
     | > postnet_loss: 0.30377551913261414  (0.31315989656881854)
     | > stopnet_loss: 0.004168156534433365  (0.005784127282712496)
     | > loss: 0.19210171699523926  (0.19921903492826404)
     | > align_error: 0.5473341643810272  (0.5894168434721052)

   --> STEP: 34
     | > decoder_loss: 0.45372194051742554  (0.4603780253845103)
     | > postnet_loss: 0.3062266707420349  (0.31295597816214843)
     | > stopnet_loss: 0.0035277842544019222  (0.0057177642524680675)
     | > loss: 0.19351494312286377  (0.19905126752222285)
     | > align_error: 0.564913272857666  (0.5886961502187393)

   --> STEP: 35
     | > decoder_loss: 0.4516322910785675  (0.4601281472614833)
     | > postnet_loss: 0.30402904748916626  (0.3127009230000632)
     | > stopnet_loss: 0.003717175917699933  (0.005660604585760406)
     | > loss: 0.1926325112581253  (0.1988678744861058)
     | > align_error: 0.5355290770530701  (0.5871770909854345)

   --> STEP: 36
     | > decoder_loss: 0.45838940143585205  (0.4600798487663269)
     | > postnet_loss: 0.3085339069366455  (0.31258517255385715)
     | > stopnet_loss: 0.0039008180610835552  (0.005611721626741605)
     | > loss: 0.19563163816928864  (0.19877797903286087)
     | > align_error: 0.6354135572910309  (0.5885169928272567)

   --> STEP: 37
     | > decoder_loss: 0.4496508240699768  (0.4597979832339931)
     | > postnet_loss: 0.3045455515384674  (0.31236788549938715)
     | > stopnet_loss: 0.0037616416811943054  (0.0055617194660511375)
     | > loss: 0.19231075048446655  (0.19860318907209346)
     | > align_error: 0.5206125974655151  (0.586681738898561)

   --> STEP: 38
     | > decoder_loss: 0.43929752707481384  (0.45925849754559367)
     | > postnet_loss: 0.298772931098938  (0.3120101235414806)
     | > stopnet_loss: 0.003292256500571966  (0.005501996756433264)
     | > loss: 0.18780988454818726  (0.19831915474251696)
     | > align_error: 0.5523870587348938  (0.5857792473153066)

   --> STEP: 39
     | > decoder_loss: 0.451883465051651  (0.4590693941483131)
     | > postnet_loss: 0.3064291179180145  (0.3118670208331866)
     | > stopnet_loss: 0.0036447911988943815  (0.005454376101111755)
     | > loss: 0.19322293996810913  (0.19818848256881422)
     | > align_error: 0.5476738214492798  (0.5848021851136136)

   --> STEP: 40
     | > decoder_loss: 0.4493347108364105  (0.4588260270655155)
     | > postnet_loss: 0.3051896393299103  (0.3117000862956047)
     | > stopnet_loss: 0.0031852053944021463  (0.005397646833444014)
     | > loss: 0.1918163001537323  (0.19802917800843717)
     | > align_error: 0.585854172706604  (0.5848284848034384)

   --> STEP: 41
     | > decoder_loss: 0.4395436942577362  (0.4583557262653258)
     | > postnet_loss: 0.2976071536540985  (0.31135635623117774)
     | > stopnet_loss: 0.003839422482997179  (0.0053596413614818966)
     | > loss: 0.18812713027000427  (0.1977876646489632)
     | > align_error: 0.5055477023124695  (0.5828948071817074)

   --> STEP: 42
     | > decoder_loss: 0.4449669420719147  (0.4580369456892922)
     | > postnet_loss: 0.30170536041259766  (0.3111265706164496)
     | > stopnet_loss: 0.0034260391257703304  (0.005313603213012573)
     | > loss: 0.19009411334991455  (0.1976044848561287)
     | > align_error: 0.5809568166732788  (0.5828486645505544)

   --> STEP: 43
     | > decoder_loss: 0.44333598017692566  (0.45769506277039995)
     | > postnet_loss: 0.3003762364387512  (0.3108765628448752)
     | > stopnet_loss: 0.003095666877925396  (0.005262023298243104)
     | > loss: 0.1890237182378769  (0.1974049321440763)
     | > align_error: 0.5531941056251526  (0.5821590236453125)

   --> STEP: 44
     | > decoder_loss: 0.46129173040390015  (0.45777680521661585)
     | > postnet_loss: 0.3091782033443451  (0.3108379637653177)
     | > stopnet_loss: 0.0028636856004595757  (0.005207515623293479)
     | > loss: 0.19548116624355316  (0.1973612101917917)
     | > align_error: 0.5528973340988159  (0.5814939852465284)

   --> STEP: 45
     | > decoder_loss: 0.45308247208595276  (0.45767248670260113)
     | > postnet_loss: 0.3075679838657379  (0.31076529754532706)
     | > stopnet_loss: 0.003495978657156229  (0.005169481468490429)
     | > loss: 0.19365859031677246  (0.19727892975012462)
     | > align_error: 0.5541000366210938  (0.5808852308326299)

   --> STEP: 46
     | > decoder_loss: 0.44531694054603577  (0.45740388787311054)
     | > postnet_loss: 0.2996971607208252  (0.3105246858752292)
     | > stopnet_loss: 0.0033623643685132265  (0.005130196314143099)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34538436658454663 (-0.011574448961200134)
     | > avg_decoder_loss: 0.45317041286916443 (-0.00026866296927136046)
     | > avg_postnet_loss: 0.30665511389573413 (-0.0007046709458033429)
     | > avg_stopnet_loss: 0.004549595654349436 (-1.3911747373640537e-05)
     | > avg_loss: 0.19450597871433606 (-0.00025724461584378244)
     | > avg_align_error: 0.5736071237108926 (-0.0006642174540142376)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_1057.pth

 > EPOCH: 7/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 21:30:44)

   --> TIME: 2025-12-27 21:31:12 -- STEP: 18/150 -- GLOBAL_STEP: 1075
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49736782908439636  (0.48958418269952136)
     | > postnet_loss: 0.4224233627319336  (0.4231528987487157)
     | > stopnet_loss: 0.007986905984580517  (0.010969835643966993)
     | > loss: 0.23793470859527588  (0.23915410704082912)
     | > align_error: 0.704639196395874  (0.6850060274203619)
     | > grad_norm: tensor(0.1998, device='cuda:0')  (tensor(0.2530, device='cuda:0'))
     | > step_time: 0.7793  (0.5980808205074735)
     | > loader_time: 1.2103  (0.8510312901602851)


   --> TIME: 2025-12-27 21:32:01 -- STEP: 43/150 -- GLOBAL_STEP: 1100
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5080850124359131  (0.49696804271187894)
     | > postnet_loss: 0.4227169454097748  (0.42296443844950476)
     | > stopnet_loss: 0.005629774183034897  (0.008261754524049371)
     | > loss: 0.23833027482032776  (0.23824487557244856)
     | > align_error: 0.6102393567562103  (0.6530213023340979)
     | > grad_norm: tensor(0.2348, device='cuda:0')  (tensor(0.2511, device='cuda:0'))
     | > step_time: 1.3805  (0.826040040614993)
     | > loader_time: 1.0478  (0.9279300833857337)


   --> TIME: 2025-12-27 21:33:03 -- STEP: 68/150 -- GLOBAL_STEP: 1125
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5101397633552551  (0.5000102524371708)
     | > postnet_loss: 0.4238298535346985  (0.421875940526233)
     | > stopnet_loss: 0.004531713202595711  (0.006903889808146395)
     | > loss: 0.23802411556243896  (0.23737543865161784)
     | > align_error: 0.6160520315170288  (0.6404947454438488)
     | > grad_norm: tensor(0.1203, device='cuda:0')  (tensor(0.2324, device='cuda:0'))
     | > step_time: 1.4689  (0.9985291011193219)
     | > loader_time: 1.2308  (1.0289885086171768)


   --> TIME: 2025-12-27 21:34:19 -- STEP: 93/150 -- GLOBAL_STEP: 1150
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5046671628952026  (0.5011069271513212)
     | > postnet_loss: 0.42815083265304565  (0.42103820975108813)
     | > stopnet_loss: 0.0036731513682752848  (0.006125322690794387)
     | > loss: 0.2368776500225067  (0.23666160641818917)
     | > align_error: 0.6060108542442322  (0.6351359178943018)
     | > grad_norm: tensor(0.1450, device='cuda:0')  (tensor(0.2152, device='cuda:0'))
     | > step_time: 1.6777  (1.1399568024502005)
     | > loader_time: 1.5613  (1.1574192277846798)


   --> TIME: 2025-12-27 21:35:43 -- STEP: 118/150 -- GLOBAL_STEP: 1175
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5173720717430115  (0.5019774664256532)
     | > postnet_loss: 0.42438605427742004  (0.4205789611501209)
     | > stopnet_loss: 0.0032050556037575006  (0.005593629619027727)
     | > loss: 0.23864459991455078  (0.23623273597430375)
     | > align_error: 0.6058825850486755  (0.629829895445856)
     | > grad_norm: tensor(0.1316, device='cuda:0')  (tensor(0.2005, device='cuda:0'))
     | > step_time: 1.7822  (1.2577562594817857)
     | > loader_time: 1.7859  (1.26295162055452)


   --> TIME: 2025-12-27 21:37:19 -- STEP: 143/150 -- GLOBAL_STEP: 1200
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.505084753036499  (0.5027313945176717)
     | > postnet_loss: 0.4134032726287842  (0.41979238515967254)
     | > stopnet_loss: 0.003246275708079338  (0.005197367355735466)
     | > loss: 0.2328682839870453  (0.23582831191849876)
     | > align_error: 0.5766165852546692  (0.6261680345018427)
     | > grad_norm: tensor(0.2376, device='cuda:0')  (tensor(0.1934, device='cuda:0'))
     | > step_time: 2.1378  (1.3861862062574268)
     | > loader_time: 1.9569  (1.365219581377256)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4765603542327881  (0.4765603542327881)
     | > postnet_loss: 0.3354271948337555  (0.3354271948337555)
     | > stopnet_loss: 0.012566403485834599  (0.012566403485834599)
     | > loss: 0.21556328237056732  (0.21556328237056732)
     | > align_error: 0.7188321650028229  (0.7188321650028229)

   --> STEP: 1
     | > decoder_loss: 0.4569389820098877  (0.4569389820098877)
     | > postnet_loss: 0.3200165331363678  (0.3200165331363678)
     | > stopnet_loss: 0.0099810054525733  (0.0099810054525733)
     | > loss: 0.20421987771987915  (0.20421987771987915)
     | > align_error: 0.6597017645835876  (0.6597017645835876)

   --> STEP: 2
     | > decoder_loss: 0.4505425691604614  (0.45374077558517456)
     | > postnet_loss: 0.3161103129386902  (0.318063423037529)
     | > stopnet_loss: 0.011261885985732079  (0.010621445719152689)
     | > loss: 0.20292510092258453  (0.20357248932123184)
     | > align_error: 0.6572979092597961  (0.6584998369216919)

   --> STEP: 3
     | > decoder_loss: 0.45277658104896545  (0.4534193774064382)
     | > postnet_loss: 0.3118612468242645  (0.31599603096644086)
     | > stopnet_loss: 0.008687554858624935  (0.009976815432310104)
     | > loss: 0.199847012758255  (0.20233066380023956)
     | > align_error: 0.7353041768074036  (0.6841012835502625)

   --> STEP: 4
     | > decoder_loss: 0.46341145038604736  (0.4559173956513405)
     | > postnet_loss: 0.32265788316726685  (0.31766149401664734)
     | > stopnet_loss: 0.008508097380399704  (0.009609635919332504)
     | > loss: 0.20502543449401855  (0.2030043564736843)
     | > align_error: 0.6049486398696899  (0.6643131226301193)

   --> STEP: 5
     | > decoder_loss: 0.4443638324737549  (0.45360668301582335)
     | > postnet_loss: 0.3066738545894623  (0.3154639661312103)
     | > stopnet_loss: 0.008476894348859787  (0.00938308760523796)
     | > loss: 0.19623632729053497  (0.20165075063705445)
     | > align_error: 0.6432044506072998  (0.6600913882255555)

   --> STEP: 6
     | > decoder_loss: 0.4595797657966614  (0.4546021968126297)
     | > postnet_loss: 0.3156397044658661  (0.31549325585365295)
     | > stopnet_loss: 0.007475756574422121  (0.009065199100101987)
     | > loss: 0.2012806236743927  (0.20158906280994415)
     | > align_error: 0.595124363899231  (0.6492635508378347)

   --> STEP: 7
     | > decoder_loss: 0.4662380516529083  (0.45626446178981234)
     | > postnet_loss: 0.3153609037399292  (0.31547434840883526)
     | > stopnet_loss: 0.006656582001596689  (0.008721110943172659)
     | > loss: 0.20205631852149963  (0.20165581362588064)
     | > align_error: 0.580378532409668  (0.6394228339195251)

   --> STEP: 8
     | > decoder_loss: 0.4616462290287018  (0.45693718269467354)
     | > postnet_loss: 0.3143036663532257  (0.3153280131518841)
     | > stopnet_loss: 0.007473817560821772  (0.008565199270378798)
     | > loss: 0.2014612853527069  (0.20163149759173393)
     | > align_error: 0.5762535333633423  (0.6315266713500023)

   --> STEP: 9
     | > decoder_loss: 0.461317777633667  (0.4574239154656728)
     | > postnet_loss: 0.3173106610774994  (0.31554830736584133)
     | > stopnet_loss: 0.006838043220341206  (0.008373293042596843)
     | > loss: 0.20149515569210052  (0.20161634849177468)
     | > align_error: 0.5931786298751831  (0.6272657778528001)

   --> STEP: 10
     | > decoder_loss: 0.4919493496417999  (0.46087645888328554)
     | > postnet_loss: 0.3317369520664215  (0.3171671718358994)
     | > stopnet_loss: 0.0059532164596021175  (0.00813128538429737)
     | > loss: 0.2118747979402542  (0.20264219343662263)
     | > align_error: 0.5879039764404297  (0.6233295977115632)

   --> STEP: 11
     | > decoder_loss: 0.47492513060569763  (0.46215361085805023)
     | > postnet_loss: 0.32394376397132874  (0.31778322566639294)
     | > stopnet_loss: 0.006027516908943653  (0.00794003370471976)
     | > loss: 0.20574474334716797  (0.2029242434284904)
     | > align_error: 0.5949808061122894  (0.6207524348389019)

   --> STEP: 12
     | > decoder_loss: 0.4677102565765381  (0.4626166646679242)
     | > postnet_loss: 0.3147122859954834  (0.31752731402715045)
     | > stopnet_loss: 0.008086840622127056  (0.007952267614503702)
     | > loss: 0.2036924809217453  (0.20298826321959496)
     | > align_error: 0.58859983086586  (0.6180730511744817)

   --> STEP: 13
     | > decoder_loss: 0.46010062098503113  (0.4624231228461632)
     | > postnet_loss: 0.3159307539463043  (0.31740450171323925)
     | > stopnet_loss: 0.005780071951448917  (0.007785175640422564)
     | > loss: 0.1997879147529602  (0.20274208256831536)
     | > align_error: 0.5874374806880951  (0.615716468829375)

   --> STEP: 14
     | > decoder_loss: 0.46335387229919434  (0.46248960494995117)
     | > postnet_loss: 0.3144547641277313  (0.31719380617141724)
     | > stopnet_loss: 0.005158605519682169  (0.007597563488941107)
     | > loss: 0.19961076974868774  (0.2025184173669134)
     | > align_error: 0.5547723174095154  (0.611363315156528)

   --> STEP: 15
     | > decoder_loss: 0.46874162554740906  (0.462906406323115)
     | > postnet_loss: 0.32266831398010254  (0.31755877335866295)
     | > stopnet_loss: 0.0051743630319833755  (0.007436016791810592)
     | > loss: 0.20302686095237732  (0.2025523136059443)
     | > align_error: 0.5889213383197784  (0.6098671833674113)

   --> STEP: 16
     | > decoder_loss: 0.46798214316368103  (0.4632236398756504)
     | > postnet_loss: 0.31416380405426025  (0.31734658777713776)
     | > stopnet_loss: 0.0053205788135528564  (0.0073038019181694835)
     | > loss: 0.20085707306861877  (0.20244636107236147)
     | > align_error: 0.6068821847438812  (0.6096806209534407)

   --> STEP: 17
     | > decoder_loss: 0.4751986861228943  (0.4639280543607824)
     | > postnet_loss: 0.32467469573020935  (0.31777765295084787)
     | > stopnet_loss: 0.005025376100093126  (0.007169776870047345)
     | > loss: 0.20499370992183685  (0.20259620512233062)
     | > align_error: 0.5588215887546539  (0.6066889131770414)

   --> STEP: 18
     | > decoder_loss: 0.47055724263191223  (0.4642963425980674)
     | > postnet_loss: 0.31697025895118713  (0.3177327977286445)
     | > stopnet_loss: 0.005559237208217382  (0.007080302444390125)
     | > loss: 0.20244111120700836  (0.2025875887937016)
     | > align_error: 0.6041598320007324  (0.6065484086672465)

   --> STEP: 19
     | > decoder_loss: 0.4705720543861389  (0.46462664321849223)
     | > postnet_loss: 0.3166549801826477  (0.3176760704893815)
     | > stopnet_loss: 0.00500751007348299  (0.006971208109079223)
     | > loss: 0.20181426405906677  (0.2025468874918787)
     | > align_error: 0.6013033986091614  (0.6062723555062947)

   --> STEP: 20
     | > decoder_loss: 0.46526315808296204  (0.4646584689617157)
     | > postnet_loss: 0.31540825963020325  (0.31756267994642257)
     | > stopnet_loss: 0.004729696083813906  (0.006859132507815957)
     | > loss: 0.19989755749702454  (0.202414420992136)
     | > align_error: 0.6230417191982269  (0.6071108236908913)

   --> STEP: 21
     | > decoder_loss: 0.46205517649650574  (0.46453450265384855)
     | > postnet_loss: 0.31013280153274536  (0.31720887621243793)
     | > stopnet_loss: 0.004177629016339779  (0.006731441865364711)
     | > loss: 0.19722461700439453  (0.20216728746891022)
     | > align_error: 0.5612449645996094  (0.604926735162735)

   --> STEP: 22
     | > decoder_loss: 0.4653162360191345  (0.4645700359886343)
     | > postnet_loss: 0.31484323740005493  (0.31710134717551147)
     | > stopnet_loss: 0.005065257661044598  (0.006655706219713797)
     | > loss: 0.20010513067245483  (0.20207355306907135)
     | > align_error: 0.6257188320159912  (0.6058718304742466)

   --> STEP: 23
     | > decoder_loss: 0.43597331643104553  (0.4633267003556956)
     | > postnet_loss: 0.30327269434928894  (0.3165001014004583)
     | > stopnet_loss: 0.004732548724859953  (0.006572090676459281)
     | > loss: 0.18954405188560486  (0.20152879214805106)
     | > align_error: 0.5666474997997284  (0.6041664247927458)

   --> STEP: 24
     | > decoder_loss: 0.4709964990615845  (0.4636462753017743)
     | > postnet_loss: 0.3193553388118744  (0.31661906962593395)
     | > stopnet_loss: 0.004573964048177004  (0.006488835400280853)
     | > loss: 0.20216193795204163  (0.20155517322321734)
     | > align_error: 0.5799481272697449  (0.6031573290626208)

   --> STEP: 25
     | > decoder_loss: 0.47155866026878357  (0.4639627707004547)
     | > postnet_loss: 0.3160450756549835  (0.31659610986709597)
     | > stopnet_loss: 0.0038503892719745636  (0.006383297555148601)
     | > loss: 0.20075131952762604  (0.2015230190753937)
     | > align_error: 0.5591623783111572  (0.6013975310325622)

   --> STEP: 26
     | > decoder_loss: 0.44460928440093994  (0.46321840584278107)
     | > postnet_loss: 0.30267688632011414  (0.31606075511528897)
     | > stopnet_loss: 0.004611996002495289  (0.006315170572354243)
     | > loss: 0.19143354892730713  (0.2011349625312365)
     | > align_error: 0.5476427376270294  (0.5993300389785032)

   --> STEP: 27
     | > decoder_loss: 0.4420051872730255  (0.46243273108093824)
     | > postnet_loss: 0.30104926228523254  (0.31550477389936094)
     | > stopnet_loss: 0.004053110722452402  (0.006231390577913435)
     | > loss: 0.18981672823429108  (0.20071576866838667)
     | > align_error: 0.5414424240589142  (0.5971860532407407)

   --> STEP: 28
     | > decoder_loss: 0.4477354884147644  (0.4619078295571463)
     | > postnet_loss: 0.30381011962890625  (0.31508710767541614)
     | > stopnet_loss: 0.004087795037776232  (0.006154833594337106)
     | > loss: 0.1919741928577423  (0.20040356953229224)
     | > align_error: 0.5660092830657959  (0.5960725971630642)

   --> STEP: 29
     | > decoder_loss: 0.44428402185440063  (0.4613001120501551)
     | > postnet_loss: 0.29993611574172974  (0.3145646596777028)
     | > stopnet_loss: 0.0037632687017321587  (0.006072365839419694)
     | > loss: 0.18981830775737762  (0.20003856050557103)
     | > align_error: 0.5408668518066406  (0.5941689507714634)

   --> STEP: 30
     | > decoder_loss: 0.44303032755851746  (0.4606911192337672)
     | > postnet_loss: 0.30045682191848755  (0.3140943984190623)
     | > stopnet_loss: 0.003097612177953124  (0.005973207384037475)
     | > loss: 0.18896938860416412  (0.19966958810885746)
     | > align_error: 0.5337152779102325  (0.5921538283427557)

   --> STEP: 31
     | > decoder_loss: 0.44239145517349243  (0.46010080748988735)
     | > postnet_loss: 0.30323877930641174  (0.3137442171573639)
     | > stopnet_loss: 0.00410816865041852  (0.005913044844243315)
     | > loss: 0.19051574170589447  (0.19937430274101994)
     | > align_error: 0.5594364404678345  (0.5910984287338872)

   --> STEP: 32
     | > decoder_loss: 0.4493008852005005  (0.459763309918344)
     | > postnet_loss: 0.305316299200058  (0.3134808447211981)
     | > stopnet_loss: 0.0040571060962975025  (0.005855046758370008)
     | > loss: 0.19271141290664673  (0.1991660874336958)
     | > align_error: 0.5310251712799072  (0.5892211394384503)

   --> STEP: 33
     | > decoder_loss: 0.44724810123443604  (0.4593840611703468)
     | > postnet_loss: 0.3049637973308563  (0.3132227523760362)
     | > stopnet_loss: 0.004158409778028727  (0.005803633516541485)
     | > loss: 0.19221138954162598  (0.19895533901272397)
     | > align_error: 0.5457206070423126  (0.5879029414870522)

   --> STEP: 34
     | > decoder_loss: 0.4532940089702606  (0.45920494198799133)
     | > postnet_loss: 0.3070988059043884  (0.31304263630334067)
     | > stopnet_loss: 0.0035304874181747437  (0.0057367762783542275)
     | > loss: 0.1936286836862564  (0.1987986726795926)
     | > align_error: 0.5634651184082031  (0.5871841819847331)

   --> STEP: 35
     | > decoder_loss: 0.4500907361507416  (0.45894453610692704)
     | > postnet_loss: 0.3044656217098236  (0.31279757874352593)
     | > stopnet_loss: 0.003703613532707095  (0.005678685914192881)
     | > loss: 0.19234269857406616  (0.19861421627657755)
     | > align_error: 0.5337880849838257  (0.5856585792132787)

   --> STEP: 36
     | > decoder_loss: 0.4575936198234558  (0.4589070106546084)
     | > postnet_loss: 0.3097529709339142  (0.31271300630437004)
     | > stopnet_loss: 0.003887234255671501  (0.005628923368122842)
     | > loss: 0.19572389125823975  (0.1985339294705126)
     | > align_error: 0.6338863968849182  (0.5869982408152686)

   --> STEP: 37
     | > decoder_loss: 0.4492911398410797  (0.45864712225424276)
     | > postnet_loss: 0.30572736263275146  (0.31252420512405604)
     | > stopnet_loss: 0.003749919356778264  (0.00557813947592434)
     | > loss: 0.19250454008579254  (0.19837097300065532)
     | > align_error: 0.5189138352870941  (0.5851581217469396)

   --> STEP: 38
     | > decoder_loss: 0.43823954463005066  (0.45811008073781667)
     | > postnet_loss: 0.299612432718277  (0.31218442163969345)
     | > stopnet_loss: 0.0032900464721024036  (0.0055179265021395515)
     | > loss: 0.18775303661823273  (0.19809155362217049)
     | > align_error: 0.5507012009620667  (0.5842513606736535)

   --> STEP: 39
     | > decoder_loss: 0.4514666497707367  (0.4579397363540454)
     | > postnet_loss: 0.30758246779441833  (0.31206642282314795)
     | > stopnet_loss: 0.0036315012257546186  (0.005469556623257886)
     | > loss: 0.1933937817811966  (0.19797109793394038)
     | > align_error: 0.5459136366844177  (0.5832683421098269)

   --> STEP: 40
     | > decoder_loss: 0.4490352272987366  (0.45771712362766265)
     | > postnet_loss: 0.3064970076084137  (0.3119271874427796)
     | > stopnet_loss: 0.0031870983075350523  (0.0054124951653648145)
     | > loss: 0.19207017123699188  (0.19782357476651666)
     | > align_error: 0.584191620349884  (0.5832914240658283)

   --> STEP: 41
     | > decoder_loss: 0.4386293292045593  (0.45725156766612357)
     | > postnet_loss: 0.2983788847923279  (0.311596741036671)
     | > stopnet_loss: 0.003835414070636034  (0.005374029772810454)
     | > loss: 0.18808746337890625  (0.19758610863511156)
     | > align_error: 0.5038363933563232  (0.5813534964875477)

   --> STEP: 42
     | > decoder_loss: 0.44461482763290405  (0.4569506929034278)
     | > postnet_loss: 0.3027152419090271  (0.3113852767717271)
     | > stopnet_loss: 0.003408069722354412  (0.005327221200180548)
     | > loss: 0.19024059176445007  (0.19741121537628628)
     | > align_error: 0.5793339610099792  (0.5813054123095104)

   --> STEP: 43
     | > decoder_loss: 0.4426354765892029  (0.4566177808961203)
     | > postnet_loss: 0.3015407621860504  (0.3111563345720602)
     | > stopnet_loss: 0.0030885692685842514  (0.005275159527352727)
     | > loss: 0.18913263082504272  (0.19721869015416435)
     | > align_error: 0.5514768362045288  (0.5806117244931155)

   --> STEP: 44
     | > decoder_loss: 0.46064192056655884  (0.456709238615903)
     | > postnet_loss: 0.31010061502456665  (0.3111323409459808)
     | > stopnet_loss: 0.00285726017318666  (0.005220207269303498)
     | > loss: 0.19554288685321808  (0.19718060371550647)
     | > align_error: 0.5509699583053589  (0.5799380479888483)

   --> STEP: 45
     | > decoder_loss: 0.4530855119228363  (0.45662871135605704)
     | > postnet_loss: 0.309106707572937  (0.31108732687102425)
     | > stopnet_loss: 0.003500119550153613  (0.005181983097766834)
     | > loss: 0.1940481811761856  (0.19711099432574378)
     | > align_error: 0.5524868667125702  (0.5793280217382643)

   --> STEP: 46
     | > decoder_loss: 0.44477301836013794  (0.456370978899624)
     | > postnet_loss: 0.3010019063949585  (0.3108680785998054)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.33290842085173633 (-0.0124759457328103)
     | > avg_decoder_loss: 0.452247628659913 (-0.0009227842092514038)
     | > avg_postnet_loss: 0.3073321206100059 (+0.0006770067142717884)
     | > avg_stopnet_loss: 0.0045565991507222235 (+7.003496372787708e-06)
     | > avg_loss: 0.19445153754768948 (-5.4441166646573835e-05)
     | > avg_align_error: 0.572048542174426 (-0.0015585815364665967)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_1208.pth

 > EPOCH: 8/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 21:39:37)

   --> TIME: 2025-12-27 21:39:58 -- STEP: 17/150 -- GLOBAL_STEP: 1225
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48327505588531494  (0.4891664596164928)
     | > postnet_loss: 0.4136519134044647  (0.4227498226306018)
     | > stopnet_loss: 0.007320736069232225  (0.010986300322281964)
     | > loss: 0.23155248165130615  (0.23896537195233739)
     | > align_error: 0.6948302388191223  (0.6836534142494202)
     | > grad_norm: tensor(0.1993, device='cuda:0')  (tensor(0.2480, device='cuda:0'))
     | > step_time: 0.7122  (0.5245268485125374)
     | > loader_time: 0.7955  (0.6279647630803725)


   --> TIME: 2025-12-27 21:40:47 -- STEP: 42/150 -- GLOBAL_STEP: 1250
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5071442127227783  (0.4964839695464997)
     | > postnet_loss: 0.4244248569011688  (0.4225871896459943)
     | > stopnet_loss: 0.0055932472459971905  (0.008222752295079686)
     | > loss: 0.23848551511764526  (0.23799054076274237)
     | > align_error: 0.6008175611495972  (0.653610727616719)
     | > grad_norm: tensor(0.2768, device='cuda:0')  (tensor(0.2372, device='cuda:0'))
     | > step_time: 1.0094  (0.7660477785837083)
     | > loader_time: 1.5681  (0.8754721255529494)


   --> TIME: 2025-12-27 21:41:52 -- STEP: 67/150 -- GLOBAL_STEP: 1275
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5131855010986328  (0.4999474184726601)
     | > postnet_loss: 0.4240514636039734  (0.4216751878830924)
     | > stopnet_loss: 0.00422480097040534  (0.006882382786151634)
     | > loss: 0.23853404819965363  (0.23728803378432545)
     | > align_error: 0.6156306862831116  (0.640559292551297)
     | > grad_norm: tensor(0.2625, device='cuda:0')  (tensor(0.2277, device='cuda:0'))
     | > step_time: 1.2668  (0.9497793539246516)
     | > loader_time: 1.418  (1.0511485960946154)


   --> TIME: 2025-12-27 21:43:06 -- STEP: 92/150 -- GLOBAL_STEP: 1300
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5003708004951477  (0.5008554474815079)
     | > postnet_loss: 0.4133516848087311  (0.4206925766623538)
     | > stopnet_loss: 0.003829780500382185  (0.006101474464547051)
     | > loss: 0.23226040601730347  (0.23648848028286643)
     | > align_error: 0.6620170176029205  (0.6351788367914118)
     | > grad_norm: tensor(0.1429, device='cuda:0')  (tensor(0.2216, device='cuda:0'))
     | > step_time: 1.5939  (1.0996884833211489)
     | > loader_time: 1.5966  (1.1598952360775159)


   --> TIME: 2025-12-27 21:44:35 -- STEP: 117/150 -- GLOBAL_STEP: 1325
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.505614697933197  (0.5017767250537872)
     | > postnet_loss: 0.41431477665901184  (0.42033754811327684)
     | > stopnet_loss: 0.003417103085666895  (0.00557684666540824)
     | > loss: 0.23339948058128357  (0.23610541466464344)
     | > align_error: 0.6231085360050201  (0.6297146346833971)
     | > grad_norm: tensor(0.1618, device='cuda:0')  (tensor(0.2099, device='cuda:0'))
     | > step_time: 1.8342  (1.2298609721354952)
     | > loader_time: 2.2638  (1.3069307498442821)


   --> TIME: 2025-12-27 21:46:14 -- STEP: 142/150 -- GLOBAL_STEP: 1350
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5137184858322144  (0.5026033602549999)
     | > postnet_loss: 0.4211954176425934  (0.4196137913935621)
     | > stopnet_loss: 0.003095596330240369  (0.0051858025950602665)
     | > loss: 0.23682406544685364  (0.23574009033995616)
     | > align_error: 0.5963005423545837  (0.6262036547274656)
     | > grad_norm: tensor(0.2048, device='cuda:0')  (tensor(0.2016, device='cuda:0'))
     | > step_time: 2.2921  (1.3489315106835167)
     | > loader_time: 1.9333  (1.4375537768216198)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4773198366165161  (0.4773198366165161)
     | > postnet_loss: 0.335798054933548  (0.335798054933548)
     | > stopnet_loss: 0.012603283859789371  (0.012603283859789371)
     | > loss: 0.21588274836540222  (0.21588274836540222)
     | > align_error: 0.7196677625179291  (0.7196677625179291)

   --> STEP: 1
     | > decoder_loss: 0.4573410749435425  (0.4573410749435425)
     | > postnet_loss: 0.32071632146835327  (0.32071632146835327)
     | > stopnet_loss: 0.009946898557245731  (0.009946898557245731)
     | > loss: 0.2044612467288971  (0.2044612467288971)
     | > align_error: 0.6609248518943787  (0.6609248518943787)

   --> STEP: 2
     | > decoder_loss: 0.4506362974643707  (0.4539886862039566)
     | > postnet_loss: 0.3157317340373993  (0.3182240277528763)
     | > stopnet_loss: 0.01117171160876751  (0.01055930508300662)
     | > loss: 0.20276372134685516  (0.20361248403787613)
     | > align_error: 0.65855672955513  (0.6597407907247543)

   --> STEP: 3
     | > decoder_loss: 0.4527268409729004  (0.45356807112693787)
     | > postnet_loss: 0.311941921710968  (0.31612999240557355)
     | > stopnet_loss: 0.008812755346298218  (0.009977121837437153)
     | > loss: 0.19997994601726532  (0.20240163803100586)
     | > align_error: 0.7359879612922668  (0.6851565142472585)

   --> STEP: 4
     | > decoder_loss: 0.46310997009277344  (0.45595354586839676)
     | > postnet_loss: 0.3223658502101898  (0.3176889568567276)
     | > stopnet_loss: 0.00857860129326582  (0.00962749170139432)
     | > loss: 0.2049475610256195  (0.20303811877965927)
     | > align_error: 0.6060601472854614  (0.6653824225068092)

   --> STEP: 5
     | > decoder_loss: 0.44406571984291077  (0.45357598066329957)
     | > postnet_loss: 0.3064786493778229  (0.31544689536094667)
     | > stopnet_loss: 0.008512664586305618  (0.009404526278376579)
     | > loss: 0.19614875316619873  (0.20166024565696716)
     | > align_error: 0.6440626978874207  (0.6611184775829315)

   --> STEP: 6
     | > decoder_loss: 0.4597969055175781  (0.454612801472346)
     | > postnet_loss: 0.31569090485572815  (0.3154875636100769)
     | > stopnet_loss: 0.00752455135807395  (0.009091197124992808)
     | > loss: 0.20139649510383606  (0.2016162872314453)
     | > align_error: 0.5962868630886078  (0.6503132085005442)

   --> STEP: 7
     | > decoder_loss: 0.46596261858940125  (0.4562342039176396)
     | > postnet_loss: 0.3148140013217926  (0.3153913404260363)
     | > stopnet_loss: 0.006631569471210241  (0.008739821745881013)
     | > loss: 0.20182572305202484  (0.20164620663438523)
     | > align_error: 0.5817515850067139  (0.6405186908585685)

   --> STEP: 8
     | > decoder_loss: 0.46295642852783203  (0.45707448199391365)
     | > postnet_loss: 0.31497037410736084  (0.31533871963620186)
     | > stopnet_loss: 0.007770921103656292  (0.008618709165602922)
     | > loss: 0.20225262641906738  (0.2017220091074705)
     | > align_error: 0.5780172348022461  (0.6327060088515282)

   --> STEP: 9
     | > decoder_loss: 0.46033424139022827  (0.45743667748239303)
     | > postnet_loss: 0.3161277174949646  (0.31542638606495327)
     | > stopnet_loss: 0.006822134833782911  (0.0084190897954007)
     | > loss: 0.20093762874603271  (0.20163485573397744)
     | > align_error: 0.5944124162197113  (0.6284511652257707)

   --> STEP: 10
     | > decoder_loss: 0.49062222242355347  (0.4607552319765091)
     | > postnet_loss: 0.33068063855171204  (0.31695181131362915)
     | > stopnet_loss: 0.005753786768764257  (0.008152559492737054)
     | > loss: 0.21107950806617737  (0.2025793209671974)
     | > align_error: 0.5889052748680115  (0.6244965761899948)

   --> STEP: 11
     | > decoder_loss: 0.4741978645324707  (0.4619772894815965)
     | > postnet_loss: 0.3229498267173767  (0.31749708544124255)
     | > stopnet_loss: 0.006066064815968275  (0.007962878158485348)
     | > loss: 0.2053529918193817  (0.20283147286285053)
     | > align_error: 0.5963245630264282  (0.6219354840842161)

   --> STEP: 12
     | > decoder_loss: 0.46755728125572205  (0.462442288796107)
     | > postnet_loss: 0.3142186105251312  (0.3172238791982333)
     | > stopnet_loss: 0.008060503751039505  (0.007971013624531528)
     | > loss: 0.20350447297096252  (0.2028875562051932)
     | > align_error: 0.5901282429695129  (0.6192848806579908)

   --> STEP: 13
     | > decoder_loss: 0.46107956767082214  (0.462337464094162)
     | > postnet_loss: 0.3160612881183624  (0.3171344491151663)
     | > stopnet_loss: 0.005786558147519827  (0.00780297858783832)
     | > loss: 0.2000717669725418  (0.20267095703345078)
     | > align_error: 0.5888365805149078  (0.6169427037239075)

   --> STEP: 14
     | > decoder_loss: 0.4635530114173889  (0.4624242889029639)
     | > postnet_loss: 0.31397268176078796  (0.31690860858985354)
     | > stopnet_loss: 0.00518501503393054  (0.007615981191130621)
     | > loss: 0.19956642389297485  (0.20244920466627395)
     | > align_error: 0.5562431216239929  (0.6126070192881993)

   --> STEP: 15
     | > decoder_loss: 0.4685380458831787  (0.4628318727016449)
     | > postnet_loss: 0.32171887159347534  (0.317229292790095)
     | > stopnet_loss: 0.005202584899961948  (0.00745508810505271)
     | > loss: 0.20276682078838348  (0.20247037907441456)
     | > align_error: 0.590366780757904  (0.6111243367195129)

   --> STEP: 16
     | > decoder_loss: 0.46852269768714905  (0.4631875492632389)
     | > postnet_loss: 0.3134043514728546  (0.3169902339577675)
     | > stopnet_loss: 0.005330425221472979  (0.007322296674828976)
     | > loss: 0.2008121907711029  (0.2023667423054576)
     | > align_error: 0.6085554659366608  (0.6109637822955847)

   --> STEP: 17
     | > decoder_loss: 0.47564005851745605  (0.4639200498076046)
     | > postnet_loss: 0.32377710938453674  (0.31738946192404804)
     | > stopnet_loss: 0.005054918583482504  (0.007188921492985066)
     | > loss: 0.20490920543670654  (0.20251629896023693)
     | > align_error: 0.5600632131099701  (0.6079696311670191)

   --> STEP: 18
     | > decoder_loss: 0.4718320071697235  (0.464359602994389)
     | > postnet_loss: 0.3165595233440399  (0.3173433542251587)
     | > stopnet_loss: 0.00557402940467  (0.007099205265856451)
     | > loss: 0.20267191529273987  (0.20252494431204265)
     | > align_error: 0.6054958403110504  (0.6078321983416876)

   --> STEP: 19
     | > decoder_loss: 0.4710550904273987  (0.4647119970698106)
     | > postnet_loss: 0.315952330827713  (0.3172701424673984)
     | > stopnet_loss: 0.00510544516146183  (0.006994270523519893)
     | > loss: 0.2018573135137558  (0.20248980584897494)
     | > align_error: 0.6029040813446045  (0.6075728237628937)

   --> STEP: 20
     | > decoder_loss: 0.46537405252456665  (0.46474509984254836)
     | > postnet_loss: 0.3141935467720032  (0.31711631268262863)
     | > stopnet_loss: 0.004723194520920515  (0.006880716723389924)
     | > loss: 0.19961509108543396  (0.2023460701107979)
     | > align_error: 0.6240425109863281  (0.6083963081240654)

   --> STEP: 21
     | > decoder_loss: 0.4621945023536682  (0.4646236428192684)
     | > postnet_loss: 0.3093473017215729  (0.3167463597797212)
     | > stopnet_loss: 0.004192724358290434  (0.006752717086956615)
     | > loss: 0.1970781832933426  (0.20209521835758573)
     | > align_error: 0.5625690817832947  (0.6062140592506954)

   --> STEP: 22
     | > decoder_loss: 0.4644111692905426  (0.464613984931599)
     | > postnet_loss: 0.3135887086391449  (0.3166028301824223)
     | > stopnet_loss: 0.005078979302197695  (0.0066766380967403)
     | > loss: 0.19957895576953888  (0.20198084278540177)
     | > align_error: 0.626729816198349  (0.6071465936574069)

   --> STEP: 23
     | > decoder_loss: 0.4362421929836273  (0.46338042875994806)
     | > postnet_loss: 0.3024913966655731  (0.3159892895947332)
     | > stopnet_loss: 0.004750542808324099  (0.0065928948233309)
     | > loss: 0.18943394720554352  (0.2014353255862775)
     | > align_error: 0.5680788159370422  (0.6054479946260867)

   --> STEP: 24
     | > decoder_loss: 0.47166571021080017  (0.46372564882040024)
     | > postnet_loss: 0.3184886574745178  (0.31609342992305756)
     | > stopnet_loss: 0.004575071390718222  (0.006508818846972038)
     | > loss: 0.20211365818977356  (0.2014635894447565)
     | > align_error: 0.5811958909034729  (0.6044374903043112)

   --> STEP: 25
     | > decoder_loss: 0.47252151370048523  (0.4640774834156036)
     | > postnet_loss: 0.3153880536556244  (0.3160652148723602)
     | > stopnet_loss: 0.003879914991557598  (0.006403662692755461)
     | > loss: 0.20085731148719788  (0.20143933832645416)
     | > align_error: 0.5604539215564728  (0.6026781475543976)

   --> STEP: 26
     | > decoder_loss: 0.44564923644065857  (0.46336870468579805)
     | > postnet_loss: 0.30216652154922485  (0.3155306497445473)
     | > stopnet_loss: 0.0046204375103116035  (0.006335077108815312)
     | > loss: 0.191574364900589  (0.20105991627161318)
     | > align_error: 0.5488963723182678  (0.6006096177376234)

   --> STEP: 27
     | > decoder_loss: 0.4424756169319153  (0.4625948866208394)
     | > postnet_loss: 0.2997840642929077  (0.3149474428759681)
     | > stopnet_loss: 0.00408509373664856  (0.006251744391327655)
     | > loss: 0.1896500140428543  (0.2006373273001777)
     | > align_error: 0.5429605841636658  (0.5984744683459953)

   --> STEP: 28
     | > decoder_loss: 0.44815289974212646  (0.4620791013751711)
     | > postnet_loss: 0.3028896450996399  (0.3145168072410992)
     | > stopnet_loss: 0.0040992326103150845  (0.006174868970577206)
     | > loss: 0.1918598711490631  (0.20032384672335216)
     | > align_error: 0.5671607553958893  (0.5973561214549201)

   --> STEP: 29
     | > decoder_loss: 0.44394561648368835  (0.4614538087927062)
     | > postnet_loss: 0.29870665073394775  (0.31397162943050777)
     | > stopnet_loss: 0.0037632177118211985  (0.00609170858234424)
     | > loss: 0.18942628800868988  (0.19994806883663968)
     | > align_error: 0.5420135259628296  (0.5954477560931238)

   --> STEP: 30
     | > decoder_loss: 0.44333794713020325  (0.4608499467372894)
     | > postnet_loss: 0.29941943287849426  (0.31348655621210736)
     | > stopnet_loss: 0.003092308761551976  (0.005991728588317831)
     | > loss: 0.18878164887428284  (0.19957585483789445)
     | > align_error: 0.5351034700870514  (0.5934362798929215)

   --> STEP: 31
     | > decoder_loss: 0.44329023361206055  (0.4602835043784111)
     | > postnet_loss: 0.30225715041160583  (0.313124317315317)
     | > stopnet_loss: 0.004126089159399271  (0.0059315466712559425)
     | > loss: 0.19051294028759003  (0.19928350275562656)
     | > align_error: 0.5610219240188599  (0.5923906555098872)

   --> STEP: 32
     | > decoder_loss: 0.4496273100376129  (0.45995049830526114)
     | > postnet_loss: 0.3041614294052124  (0.3128442270681262)
     | > stopnet_loss: 0.004079095087945461  (0.00587365755927749)
     | > loss: 0.19252626597881317  (0.19907233910635114)
     | > align_error: 0.5326545238494873  (0.5905239013954997)

   --> STEP: 33
     | > decoder_loss: 0.44850969314575195  (0.45960380723982147)
     | > postnet_loss: 0.30403271317481995  (0.31257721149560175)
     | > stopnet_loss: 0.004195495508611202  (0.0058228041638027535)
     | > loss: 0.19233109056949615  (0.19886805884765857)
     | > align_error: 0.5470384657382965  (0.5892061609210391)

   --> STEP: 34
     | > decoder_loss: 0.45403146743774414  (0.45943991489270153)
     | > postnet_loss: 0.306156724691391  (0.3123883736484191)
     | > stopnet_loss: 0.0035586466547101736  (0.005756211295888266)
     | > loss: 0.1936057060956955  (0.19871328376671848)
     | > align_error: 0.5646043419837952  (0.58848257801112)

   --> STEP: 35
     | > decoder_loss: 0.450981080532074  (0.4591982339109693)
     | > postnet_loss: 0.30374372005462646  (0.31214138354573934)
     | > stopnet_loss: 0.0037080454640090466  (0.005697692272120289)
     | > loss: 0.19238924980163574  (0.19853259708200183)
     | > align_error: 0.5352665781974792  (0.5869621208735875)

   --> STEP: 36
     | > decoder_loss: 0.457874596118927  (0.4591614661945237)
     | > postnet_loss: 0.3082239627838135  (0.31203256630235254)
     | > stopnet_loss: 0.0038922985550016165  (0.00564754244664477)
     | > loss: 0.19541694223880768  (0.19844605111413532)
     | > align_error: 0.6349420547485352  (0.5882948968145583)

   --> STEP: 37
     | > decoder_loss: 0.4495111107826233  (0.45890064577798584)
     | > postnet_loss: 0.30458781123161316  (0.31183135670584605)
     | > stopnet_loss: 0.0037514343857765198  (0.00559629628283752)
     | > loss: 0.19227614998817444  (0.1982792970296499)
     | > align_error: 0.5202380418777466  (0.5864555223568065)

   --> STEP: 38
     | > decoder_loss: 0.43906253576278687  (0.4583785902512701)
     | > postnet_loss: 0.2986670136451721  (0.311484926625302)
     | > stopnet_loss: 0.003299533389508724  (0.005535855154065709)
     | > loss: 0.18773192167282104  (0.19800173452025965)
     | > align_error: 0.5521191358566284  (0.5855519332383808)

   --> STEP: 39
     | > decoder_loss: 0.45183107256889343  (0.4582107051824912)
     | > postnet_loss: 0.3066500723361969  (0.31136095600250446)
     | > stopnet_loss: 0.003634473541751504  (0.005487101779390986)
     | > loss: 0.193254753947258  (0.19788001706966987)
     | > align_error: 0.5472110509872437  (0.5845688336934799)

   --> STEP: 40
     | > decoder_loss: 0.4493851661682129  (0.45799006670713427)
     | > postnet_loss: 0.3054634928703308  (0.3112135194242001)
     | > stopnet_loss: 0.0032016478944569826  (0.005429965432267636)
     | > loss: 0.19191381335258484  (0.19773086197674275)
     | > align_error: 0.585383951663971  (0.5845892116427421)

   --> STEP: 41
     | > decoder_loss: 0.4392973482608795  (0.45753414674503046)
     | > postnet_loss: 0.29747024178504944  (0.3108783175305623)
     | > stopnet_loss: 0.0038455422036349773  (0.0053913209632765954)
     | > loss: 0.1880374401807785  (0.19749443705488995)
     | > align_error: 0.5052910447120667  (0.5826551100102867)

   --> STEP: 42
     | > decoder_loss: 0.44384467601776123  (0.45720820696580977)
     | > postnet_loss: 0.3008545935153961  (0.3106396574349631)
     | > stopnet_loss: 0.003422107780352235  (0.00534443493511173)
     | > loss: 0.18959692120552063  (0.19730640096323832)
     | > align_error: 0.5806101560592651  (0.5826064206305004)

   --> STEP: 43
     | > decoder_loss: 0.4434537887573242  (0.45688833677491475)
     | > postnet_loss: 0.30034080147743225  (0.31040014915688097)
     | > stopnet_loss: 0.0031034424901008606  (0.005292318831739384)
     | > loss: 0.18905207514762878  (0.197114439897759)
     | > align_error: 0.5529296398162842  (0.5819162629371466)

   --> STEP: 44
     | > decoder_loss: 0.46127188205718994  (0.4569879628040574)
     | > postnet_loss: 0.3091813921928406  (0.31037245013497095)
     | > stopnet_loss: 0.0028594722971320152  (0.005237026865043762)
     | > loss: 0.19547279179096222  (0.19707712971351363)
     | > align_error: 0.5524201989173889  (0.5812458978457884)

   --> STEP: 45
     | > decoder_loss: 0.4538903832435608  (0.45691912770271303)
     | > postnet_loss: 0.30808407068252563  (0.3103215972582499)
     | > stopnet_loss: 0.0034933725837618113  (0.005198278992126385)
     | > loss: 0.19398698210716248  (0.19700845976670583)
     | > align_error: 0.5538160800933838  (0.5806363463401795)

   --> STEP: 46
     | > decoder_loss: 0.4451929032802582  (0.4566642097804857)
     | > postnet_loss: 0.29970917105674744  (0.31009089234082593)
     | > stopnet_loss: 0.0033667900133877993  (0.00515846401432772)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3552222938248606 (+0.02231387297312426)
     | > avg_decoder_loss: 0.45257934611855133 (+0.00033171745863830315)
     | > avg_postnet_loss: 0.30652573614409473 (-0.0008063844659111918)
     | > avg_stopnet_loss: 0.004569452569932874 (+1.2853419210650738e-05)
     | > avg_loss: 0.19434572237007547 (-0.00010581517761401593)
     | > avg_align_error: 0.5733229364409591 (+0.0012743942665330854)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_1359.pth

 > EPOCH: 9/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 21:49:07)

   --> TIME: 2025-12-27 21:49:30 -- STEP: 16/150 -- GLOBAL_STEP: 1375
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4923689067363739  (0.4880864638835192)
     | > postnet_loss: 0.41972076892852783  (0.4223977420479059)
     | > stopnet_loss: 0.007804577704519033  (0.011240324791288003)
     | > loss: 0.2358269989490509  (0.23886137548834085)
     | > align_error: 0.6804067194461823  (0.6832898389548063)
     | > grad_norm: tensor(0.2367, device='cuda:0')  (tensor(0.3096, device='cuda:0'))
     | > step_time: 0.7451  (0.5651792883872986)
     | > loader_time: 1.0154  (0.8267040252685547)


   --> TIME: 2025-12-27 21:50:19 -- STEP: 41/150 -- GLOBAL_STEP: 1400
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5056152939796448  (0.49524264655462125)
     | > postnet_loss: 0.42418938875198364  (0.42183353406627005)
     | > stopnet_loss: 0.005290795583277941  (0.008311578379262512)
     | > loss: 0.23774196207523346  (0.23758062247822925)
     | > align_error: 0.5980420410633087  (0.6551466656894219)
     | > grad_norm: tensor(0.1396, device='cuda:0')  (tensor(0.2473, device='cuda:0'))
     | > step_time: 1.1353  (0.80231138555015)
     | > loader_time: 1.0367  (0.934271579835473)


   --> TIME: 2025-12-27 21:51:21 -- STEP: 66/150 -- GLOBAL_STEP: 1425
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5085709095001221  (0.4986403850894986)
     | > postnet_loss: 0.4201776087284088  (0.42079353919534973)
     | > stopnet_loss: 0.003824070328846574  (0.006934445453666602)
     | > loss: 0.23601119220256805  (0.23679292585813638)
     | > align_error: 0.615608811378479  (0.6413390731269664)
     | > grad_norm: tensor(0.1854, device='cuda:0')  (tensor(0.2152, device='cuda:0'))
     | > step_time: 1.4225  (0.9801339958653306)
     | > loader_time: 1.2327  (1.0312914523211394)


   --> TIME: 2025-12-27 21:52:33 -- STEP: 91/150 -- GLOBAL_STEP: 1450
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5001654624938965  (0.5001608899661475)
     | > postnet_loss: 0.41316670179367065  (0.42017238971951243)
     | > stopnet_loss: 0.003648163052275777  (0.006136659834697679)
     | > loss: 0.23198120296001434  (0.23621997859451796)
     | > align_error: 0.5978361964225769  (0.6352984076672858)
     | > grad_norm: tensor(0.1400, device='cuda:0')  (tensor(0.1978, device='cuda:0'))
     | > step_time: 1.4527  (1.1192332493079897)
     | > loader_time: 1.5757  (1.1320370160616364)


   --> TIME: 2025-12-27 21:53:56 -- STEP: 116/150 -- GLOBAL_STEP: 1475
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5011091828346252  (0.5009259915557405)
     | > postnet_loss: 0.4129256010055542  (0.4197156285417491)
     | > stopnet_loss: 0.0033387080766260624  (0.005598113037131983)
     | > loss: 0.23184740543365479  (0.23575851732286915)
     | > align_error: 0.5913562774658203  (0.6302514433346948)
     | > grad_norm: tensor(0.2188, device='cuda:0')  (tensor(0.1856, device='cuda:0'))
     | > step_time: 1.6979  (1.2438999167804066)
     | > loader_time: 1.6762  (1.2400600827973467)


   --> TIME: 2025-12-27 21:55:32 -- STEP: 141/150 -- GLOBAL_STEP: 1500
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5061542391777039  (0.501904806558122)
     | > postnet_loss: 0.41296347975730896  (0.4190615802369219)
     | > stopnet_loss: 0.003167359856888652  (0.0051938795141135965)
     | > loss: 0.23294678330421448  (0.2354354756943723)
     | > align_error: 0.6068300604820251  (0.6267591480244984)
     | > grad_norm: tensor(0.1216, device='cuda:0')  (tensor(0.1834, device='cuda:0'))
     | > step_time: 2.2981  (1.3773982795417736)
     | > loader_time: 1.7787  (1.3415196415380386)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4783496856689453  (0.4783496856689453)
     | > postnet_loss: 0.3369556963443756  (0.3369556963443756)
     | > stopnet_loss: 0.01250073779374361  (0.01250073779374361)
     | > loss: 0.21632707118988037  (0.21632707118988037)
     | > align_error: 0.7195126116275787  (0.7195126116275787)

   --> STEP: 1
     | > decoder_loss: 0.4607781767845154  (0.4607781767845154)
     | > postnet_loss: 0.32346072793006897  (0.32346072793006897)
     | > stopnet_loss: 0.009871421381831169  (0.009871421381831169)
     | > loss: 0.205931156873703  (0.205931156873703)
     | > align_error: 0.6605283617973328  (0.6605283617973328)

   --> STEP: 2
     | > decoder_loss: 0.45279452204704285  (0.4567863494157791)
     | > postnet_loss: 0.31663909554481506  (0.320049911737442)
     | > stopnet_loss: 0.011163241229951382  (0.010517331305891275)
     | > loss: 0.20352163910865784  (0.20472639799118042)
     | > align_error: 0.6581317484378815  (0.6593300551176071)

   --> STEP: 3
     | > decoder_loss: 0.45399072766304016  (0.45585447549819946)
     | > postnet_loss: 0.3126288950443268  (0.3175762395064036)
     | > stopnet_loss: 0.008702521212399006  (0.009912394608060518)
     | > loss: 0.20035742223262787  (0.20327007273832956)
     | > align_error: 0.736144483089447  (0.6849348644415537)

   --> STEP: 4
     | > decoder_loss: 0.4663650691509247  (0.45848212391138077)
     | > postnet_loss: 0.32421088218688965  (0.3192349001765251)
     | > stopnet_loss: 0.008489462547004223  (0.009556661592796445)
     | > loss: 0.20613345503807068  (0.20398591831326485)
     | > align_error: 0.6059491634368896  (0.6651884391903877)

   --> STEP: 5
     | > decoder_loss: 0.4465789794921875  (0.4561014950275421)
     | > postnet_loss: 0.3074120879173279  (0.31687033772468565)
     | > stopnet_loss: 0.008443065918982029  (0.009333942458033562)
     | > loss: 0.1969408392906189  (0.20257690250873567)
     | > align_error: 0.6441267728805542  (0.660976105928421)

   --> STEP: 6
     | > decoder_loss: 0.4626449942588806  (0.4571920782327652)
     | > postnet_loss: 0.3173159658908844  (0.3169446090857188)
     | > stopnet_loss: 0.007467464543879032  (0.009022862805674473)
     | > loss: 0.2024577111005783  (0.20255703727404276)
     | > align_error: 0.5960825085639954  (0.6501605063676834)

   --> STEP: 7
     | > decoder_loss: 0.46823588013648987  (0.45876976421901156)
     | > postnet_loss: 0.31534698605537415  (0.316716377224241)
     | > stopnet_loss: 0.006617782171815634  (0.008679279857980353)
     | > loss: 0.20251350104808807  (0.2025508178131921)
     | > align_error: 0.5811023116111755  (0.6402950499738965)

   --> STEP: 8
     | > decoder_loss: 0.4644862711429596  (0.4594843275845051)
     | > postnet_loss: 0.3155345320701599  (0.31656864657998085)
     | > stopnet_loss: 0.007581269834190607  (0.008542028605006635)
     | > loss: 0.20258647203445435  (0.20255527459084988)
     | > align_error: 0.5776130557060242  (0.6324598006904125)

   --> STEP: 9
     | > decoder_loss: 0.4624885618686676  (0.45981813139385647)
     | > postnet_loss: 0.3170419931411743  (0.31662124064233566)
     | > stopnet_loss: 0.006836513057351112  (0.008352526877489354)
     | > loss: 0.20171914994716644  (0.20246237185266283)
     | > align_error: 0.5942379534244537  (0.6282129287719727)

   --> STEP: 10
     | > decoder_loss: 0.4929697811603546  (0.46313329637050626)
     | > postnet_loss: 0.33188962936401367  (0.31814807951450347)
     | > stopnet_loss: 0.005703927017748356  (0.008087666891515254)
     | > loss: 0.21191877126693726  (0.20340801179409027)
     | > align_error: 0.5886116027832031  (0.6242527961730957)

   --> STEP: 11
     | > decoder_loss: 0.4765351712703705  (0.4643516486341303)
     | > postnet_loss: 0.32356739044189453  (0.3186407441442663)
     | > stopnet_loss: 0.006032908800989389  (0.00790087070146745)
     | > loss: 0.2060585618019104  (0.2036489708857103)
     | > align_error: 0.5958774983882904  (0.6216732236472043)

   --> STEP: 12
     | > decoder_loss: 0.47013282775878906  (0.4648334135611852)
     | > postnet_loss: 0.31492331624031067  (0.31833095848560333)
     | > stopnet_loss: 0.008095153607428074  (0.007917060943630835)
     | > loss: 0.20435918867588043  (0.20370815570155779)
     | > align_error: 0.5899450778961182  (0.6190292115012804)

   --> STEP: 13
     | > decoder_loss: 0.46324387192726135  (0.4647111411278064)
     | > postnet_loss: 0.31667837500572205  (0.3182038366794586)
     | > stopnet_loss: 0.005743727553635836  (0.0077498814520927575)
     | > loss: 0.2007242888212204  (0.20347862747999337)
     | > align_error: 0.5881917476654053  (0.6166570988985208)

   --> STEP: 14
     | > decoder_loss: 0.4656568765640259  (0.46477869365896496)
     | > postnet_loss: 0.3144407868385315  (0.3179350474051067)
     | > stopnet_loss: 0.00514149060472846  (0.007563567820138165)
     | > loss: 0.20016591250896454  (0.20324200498206274)
     | > align_error: 0.5557887554168701  (0.612309360078403)

   --> STEP: 15
     | > decoder_loss: 0.47083327174186707  (0.4651823321978251)
     | > postnet_loss: 0.32183489203453064  (0.31819503704706825)
     | > stopnet_loss: 0.005171847529709339  (0.007404119800776243)
     | > loss: 0.2033388912677765  (0.203248464067777)
     | > align_error: 0.5897884666919708  (0.6108079671859741)

   --> STEP: 16
     | > decoder_loss: 0.46995046734809875  (0.4654803406447172)
     | > postnet_loss: 0.3131375014781952  (0.3178789410740137)
     | > stopnet_loss: 0.005298076197504997  (0.00727249207557179)
     | > loss: 0.20107007026672363  (0.20311231445521116)
     | > align_error: 0.6081766188144684  (0.610643507912755)

   --> STEP: 17
     | > decoder_loss: 0.4780575633049011  (0.4662201772717869)
     | > postnet_loss: 0.32410433888435364  (0.31824514094521017)
     | > stopnet_loss: 0.005045384634286165  (0.007141485755496165)
     | > loss: 0.20558586716651917  (0.20325781755587635)
     | > align_error: 0.5598096549510956  (0.6076532812679515)

   --> STEP: 18
     | > decoder_loss: 0.47369468212127686  (0.46663542754120296)
     | > postnet_loss: 0.31653857231140137  (0.3181503315766652)
     | > stopnet_loss: 0.0055777449160814285  (0.007054611264417569)
     | > loss: 0.20313605666160583  (0.2032510530617502)
     | > align_error: 0.6050366759300232  (0.6075079143047333)

   --> STEP: 19
     | > decoder_loss: 0.47181808948516846  (0.4669081992224643)
     | > postnet_loss: 0.31550833582878113  (0.3180112791688819)
     | > stopnet_loss: 0.005041438154876232  (0.006948654784968025)
     | > loss: 0.2018730491399765  (0.2031785265395516)
     | > align_error: 0.6025573909282684  (0.607247360442814)

   --> STEP: 20
     | > decoder_loss: 0.46617183089256287  (0.46687138080596924)
     | > postnet_loss: 0.31323444843292236  (0.3177724376320839)
     | > stopnet_loss: 0.004693878348916769  (0.006835915963165462)
     | > loss: 0.1995454579591751  (0.20299687311053277)
     | > align_error: 0.623547226190567  (0.6080623537302017)

   --> STEP: 21
     | > decoder_loss: 0.46452993154525757  (0.4667598832221258)
     | > postnet_loss: 0.30968016386032104  (0.31738709126199993)
     | > stopnet_loss: 0.0041840714402496815  (0.006709637652550425)
     | > loss: 0.19773659110069275  (0.20274638349101656)
     | > align_error: 0.5622931718826294  (0.6058828688803173)

   --> STEP: 22
     | > decoder_loss: 0.46690791845321655  (0.4667666120962663)
     | > postnet_loss: 0.3137240707874298  (0.31722059033133765)
     | > stopnet_loss: 0.005050043575465679  (0.006634201558137482)
     | > loss: 0.20020805299282074  (0.20263100483200766)
     | > align_error: 0.626798689365387  (0.606833587993275)

   --> STEP: 23
     | > decoder_loss: 0.43717601895332336  (0.46548006456831226)
     | > postnet_loss: 0.30183500051498413  (0.3165516516436701)
     | > stopnet_loss: 0.004731172230094671  (0.006551461152570403)
     | > loss: 0.18948394060134888  (0.20205939334371817)
     | > align_error: 0.5677078366279602  (0.6051324683686962)

   --> STEP: 24
     | > decoder_loss: 0.4732597768306732  (0.46580421924591064)
     | > postnet_loss: 0.31790539622306824  (0.3166080576678117)
     | > stopnet_loss: 0.004573920741677284  (0.0064690636354498565)
     | > loss: 0.2023652195930481  (0.2020721361041069)
     | > align_error: 0.581605076789856  (0.6041521603862444)

   --> STEP: 25
     | > decoder_loss: 0.47348687052726746  (0.46611152529716493)
     | > postnet_loss: 0.3148995637893677  (0.31653971791267393)
     | > stopnet_loss: 0.0038535629864782095  (0.006364443609490991)
     | > loss: 0.20095017552375793  (0.20202725768089294)
     | > align_error: 0.5599899291992188  (0.6023856711387634)

   --> STEP: 26
     | > decoder_loss: 0.4468580484390259  (0.46537100695646727)
     | > postnet_loss: 0.3020339906215668  (0.31598180532455444)
     | > stopnet_loss: 0.004604819230735302  (0.006296765748769618)
     | > loss: 0.19182783365249634  (0.20163497214133924)
     | > align_error: 0.5488013923168182  (0.6003247373379194)

   --> STEP: 27
     | > decoder_loss: 0.44365203380584717  (0.4645666005434813)
     | > postnet_loss: 0.2994194030761719  (0.3153683830190588)
     | > stopnet_loss: 0.004061092156916857  (0.006213963023145442)
     | > loss: 0.18982894718647003  (0.20119771195782554)
     | > align_error: 0.5426850318908691  (0.5981899334324731)

   --> STEP: 28
     | > decoder_loss: 0.44942066073417664  (0.46402567412172047)
     | > postnet_loss: 0.30239009857177734  (0.31490487286022734)
     | > stopnet_loss: 0.004075521603226662  (0.006137590115291199)
     | > loss: 0.1920282244682312  (0.20087023026176862)
     | > align_error: 0.5668559670448303  (0.597070863204343)

   --> STEP: 29
     | > decoder_loss: 0.44517782330513  (0.4633757482314932)
     | > postnet_loss: 0.29833775758743286  (0.3143335930232344)
     | > stopnet_loss: 0.003754089819267392  (0.006055400449911068)
     | > loss: 0.18963299691677094  (0.2004827394567687)
     | > align_error: 0.541808545589447  (0.5951652660452086)

   --> STEP: 30
     | > decoder_loss: 0.44432157278060913  (0.4627406090497971)
     | > postnet_loss: 0.29911109805107117  (0.3138261765241623)
     | > stopnet_loss: 0.0030988845974206924  (0.005956849921494723)
     | > loss: 0.18895705044269562  (0.20009854982296627)
     | > align_error: 0.5347031950950623  (0.5931498636802037)

   --> STEP: 31
     | > decoder_loss: 0.44314897060394287  (0.46210862071283404)
     | > postnet_loss: 0.3010300099849701  (0.3134133969583819)
     | > stopnet_loss: 0.004126370884478092  (0.005897802210623218)
     | > loss: 0.19017112255096436  (0.19977831023354684)
     | > align_error: 0.5605477392673492  (0.5920981822475311)

   --> STEP: 32
     | > decoder_loss: 0.4509132504463196  (0.46175876539200544)
     | > postnet_loss: 0.3039498031139374  (0.313117659650743)
     | > stopnet_loss: 0.004057190380990505  (0.005840283090947196)
     | > loss: 0.19277293980121613  (0.1995593924075365)
     | > align_error: 0.5322334170341492  (0.5902274083346128)

   --> STEP: 33
     | > decoder_loss: 0.4482424855232239  (0.4613491811535575)
     | > postnet_loss: 0.3027735650539398  (0.3128042022387187)
     | > stopnet_loss: 0.004136829636991024  (0.0057886632893121605)
     | > loss: 0.19189083576202393  (0.19932701190312704)
     | > align_error: 0.546440452337265  (0.5889005308801477)

   --> STEP: 34
     | > decoder_loss: 0.4549005329608917  (0.4611595150302438)
     | > postnet_loss: 0.30535364151000977  (0.312585068099639)
     | > stopnet_loss: 0.003530844347551465  (0.00572225684984861)
     | > loss: 0.19359438121318817  (0.19915840511812882)
     | > align_error: 0.5640666484832764  (0.5881701225743574)

   --> STEP: 35
     | > decoder_loss: 0.45180943608283997  (0.46089236991746085)
     | > postnet_loss: 0.3029937744140625  (0.31231103113719394)
     | > stopnet_loss: 0.0037112876307219267  (0.005664800586444991)
     | > loss: 0.19241207838058472  (0.19896565292562757)
     | > align_error: 0.5348014235496521  (0.586645302602223)

   --> STEP: 36
     | > decoder_loss: 0.45904436707496643  (0.46084103650516933)
     | > postnet_loss: 0.307832270860672  (0.3121866211295128)
     | > stopnet_loss: 0.0038859269116073847  (0.005615387428810613)
     | > loss: 0.1956050843000412  (0.19887230379713905)
     | > align_error: 0.6346642971038818  (0.5879791635606024)

   --> STEP: 37
     | > decoder_loss: 0.45016980171203613  (0.4605526247540036)
     | > postnet_loss: 0.304019957780838  (0.3119659004984675)
     | > stopnet_loss: 0.003746710019186139  (0.0055648826339558975)
     | > loss: 0.1922941356897354  (0.19869451546991193)
     | > align_error: 0.519647479057312  (0.5861323612767297)

   --> STEP: 38
     | > decoder_loss: 0.4395855665206909  (0.46000086006365326)
     | > postnet_loss: 0.2979404628276825  (0.31159681003344686)
     | > stopnet_loss: 0.0032870336435735226  (0.005504939239472151)
     | > loss: 0.1876685470342636  (0.19840435840581594)
     | > align_error: 0.5515933632850647  (0.5852234402769492)

   --> STEP: 39
     | > decoder_loss: 0.4524107277393341  (0.4598062412861066)
     | > postnet_loss: 0.3061527609825134  (0.31145721903214085)
     | > stopnet_loss: 0.003638200694695115  (0.005457074148580432)
     | > loss: 0.19327908754348755  (0.19827294120421776)
     | > align_error: 0.5469532012939453  (0.5842421520978979)

   --> STEP: 40
     | > decoder_loss: 0.44985178112983704  (0.45955737978219985)
     | > postnet_loss: 0.3048549294471741  (0.3112921617925167)
     | > stopnet_loss: 0.0031995184253901243  (0.005400635255500674)
     | > loss: 0.19187620282173157  (0.19811302274465561)
     | > align_error: 0.584993451833725  (0.5842609345912935)

   --> STEP: 41
     | > decoder_loss: 0.4399014711380005  (0.4590779673762438)
     | > postnet_loss: 0.29696324467658997  (0.3109426760092014)
     | > stopnet_loss: 0.003847691463306546  (0.005362758577642281)
     | > loss: 0.1880638599395752  (0.19786792121282437)
     | > align_error: 0.5046250522136688  (0.5823185959967173)

   --> STEP: 42
     | > decoder_loss: 0.44505035877227783  (0.45874397669519695)
     | > postnet_loss: 0.3003295660018921  (0.31068998291378924)
     | > stopnet_loss: 0.0034204083494842052  (0.0053165121436385175)
     | > loss: 0.18976539373397827  (0.19767500389189946)
     | > align_error: 0.5803969502449036  (0.5822728425264361)

   --> STEP: 43
     | > decoder_loss: 0.4437161087989807  (0.458394491395285)
     | > postnet_loss: 0.2993413209915161  (0.31042606054350386)
     | > stopnet_loss: 0.0030799901578575373  (0.005264500004434309)
     | > loss: 0.18884435296058655  (0.19746963991675265)
     | > align_error: 0.5522670149803162  (0.5815750325835031)

   --> STEP: 44
     | > decoder_loss: 0.4615744650363922  (0.45846676352349197)
     | > postnet_loss: 0.3082369267940521  (0.3103763075037436)
     | > stopnet_loss: 0.0028521937783807516  (0.005209674862933091)
     | > loss: 0.19530503451824188  (0.19742044433951378)
     | > align_error: 0.5519874691963196  (0.5809025879610671)

   --> STEP: 45
     | > decoder_loss: 0.4536498486995697  (0.45835972097184924)
     | > postnet_loss: 0.3070289194583893  (0.31030192110273574)
     | > stopnet_loss: 0.0034915334545075893  (0.005171493942745858)
     | > loss: 0.19366122782230377  (0.19733690619468688)
     | > align_error: 0.5534265041351318  (0.5802920083204908)

   --> STEP: 46
     | > decoder_loss: 0.44569966197013855  (0.458084502297899)
     | > postnet_loss: 0.29903843998908997  (0.3100570628176565)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3623305306290136 (+0.007108236804153012)
     | > avg_decoder_loss: 0.4535709416324442 (+0.0009915955138928845)
     | > avg_postnet_loss: 0.30627820753689966 (-0.00024752860719506886)
     | > avg_stopnet_loss: 0.0045500869270075454 (-1.936564292532878e-05)
     | > avg_loss: 0.19451237560221643 (+0.00016665323214096195)
     | > avg_align_error: 0.5729661963202739 (-0.0003567401206852061)


 > EPOCH: 10/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 21:58:09)

   --> TIME: 2025-12-27 21:58:29 -- STEP: 15/150 -- GLOBAL_STEP: 1525
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4888882339000702  (0.489255303144455)
     | > postnet_loss: 0.4176226556301117  (0.42343862652778624)
     | > stopnet_loss: 0.008542864583432674  (0.011604127598305543)
     | > loss: 0.23517058789730072  (0.23977761069933573)
     | > align_error: 0.6641495227813721  (0.6827497700850169)
     | > grad_norm: tensor(0.1915, device='cuda:0')  (tensor(0.2681, device='cuda:0'))
     | > step_time: 0.7303  (0.5554481347401937)
     | > loader_time: 0.8973  (0.6853882471720377)


   --> TIME: 2025-12-27 21:59:16 -- STEP: 40/150 -- GLOBAL_STEP: 1550
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.5074754953384399  (0.4955017276108265)
     | > postnet_loss: 0.4230467677116394  (0.4221480540931225)
     | > stopnet_loss: 0.00523512763902545  (0.008453212748281659)
     | > loss: 0.23786568641662598  (0.2378656566143036)
     | > align_error: 0.6211558282375336  (0.6557773254811764)
     | > grad_norm: tensor(0.1905, device='cuda:0')  (tensor(0.2534, device='cuda:0'))
     | > step_time: 1.0613  (0.7949087619781494)
     | > loader_time: 1.0147  (0.8582036435604096)


   --> TIME: 2025-12-27 22:00:17 -- STEP: 65/150 -- GLOBAL_STEP: 1575
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5029945969581604  (0.4990217117162851)
     | > postnet_loss: 0.41684412956237793  (0.4212120867692507)
     | > stopnet_loss: 0.004648875445127487  (0.007034416195864863)
     | > loss: 0.23460856080055237  (0.2370928649718945)
     | > align_error: 0.6636376082897186  (0.6407879824821766)
     | > grad_norm: tensor(0.1755, device='cuda:0')  (tensor(0.2369, device='cuda:0'))
     | > step_time: 1.4572  (0.9828292479881874)
     | > loader_time: 1.1962  (0.9674511102529673)


   --> TIME: 2025-12-27 22:01:30 -- STEP: 90/150 -- GLOBAL_STEP: 1600
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5035369396209717  (0.500321676664882)
     | > postnet_loss: 0.41537195444107056  (0.4203879714012146)
     | > stopnet_loss: 0.0037920698523521423  (0.006203680428572828)
     | > loss: 0.2335192859172821  (0.2363810916741689)
     | > align_error: 0.6666571497917175  (0.6347523692581389)
     | > grad_norm: tensor(0.3938, device='cuda:0')  (tensor(0.2235, device='cuda:0'))
     | > step_time: 1.7212  (1.1380770206451418)
     | > loader_time: 1.4795  (1.084671158260769)


   --> TIME: 2025-12-27 22:02:59 -- STEP: 115/150 -- GLOBAL_STEP: 1625
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5032069683074951  (0.5011358154856638)
     | > postnet_loss: 0.4140584170818329  (0.4199199404405511)
     | > stopnet_loss: 0.003578518284484744  (0.005642284999561052)
     | > loss: 0.2328948676586151  (0.23590622440628384)
     | > align_error: 0.6625852584838867  (0.6295368772485982)
     | > grad_norm: tensor(0.1563, device='cuda:0')  (tensor(0.2097, device='cuda:0'))
     | > step_time: 1.923  (1.2681950030119524)
     | > loader_time: 1.6561  (1.2418699409650718)


   --> TIME: 2025-12-27 22:04:36 -- STEP: 140/150 -- GLOBAL_STEP: 1650
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5097106695175171  (0.5019175629530633)
     | > postnet_loss: 0.41537678241729736  (0.4191604250243732)
     | > stopnet_loss: 0.0029737111181020737  (0.005230209710342544)
     | > loss: 0.23424556851387024  (0.23549970697079387)
     | > align_error: 0.5934270620346069  (0.6259616172739437)
     | > grad_norm: tensor(0.1456, device='cuda:0')  (tensor(0.2044, device='cuda:0'))
     | > step_time: 2.0592  (1.4013040338243758)
     | > loader_time: 1.751  (1.3538359897477283)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47702690958976746  (0.47702690958976746)
     | > postnet_loss: 0.33677414059638977  (0.33677414059638977)
     | > stopnet_loss: 0.01256247702986002  (0.01256247702986002)
     | > loss: 0.21601274609565735  (0.21601274609565735)
     | > align_error: 0.7191187739372253  (0.7191187739372253)

   --> STEP: 1
     | > decoder_loss: 0.45780065655708313  (0.45780065655708313)
     | > postnet_loss: 0.3223358392715454  (0.3223358392715454)
     | > stopnet_loss: 0.009920461103320122  (0.009920461103320122)
     | > loss: 0.2049545794725418  (0.2049545794725418)
     | > align_error: 0.660170167684555  (0.660170167684555)

   --> STEP: 2
     | > decoder_loss: 0.4505423903465271  (0.4541715234518051)
     | > postnet_loss: 0.3160266578197479  (0.31918124854564667)
     | > stopnet_loss: 0.011214741505682468  (0.010567601304501295)
     | > loss: 0.20285700261592865  (0.20390579104423523)
     | > align_error: 0.6576111316680908  (0.6588906496763229)

   --> STEP: 3
     | > decoder_loss: 0.4522485136985779  (0.45353052020072937)
     | > postnet_loss: 0.31234753131866455  (0.3169033428033193)
     | > stopnet_loss: 0.008699581027030945  (0.009944927878677845)
     | > loss: 0.19984859228134155  (0.202553391456604)
     | > align_error: 0.7358086109161377  (0.6845299700895945)

   --> STEP: 4
     | > decoder_loss: 0.4640454649925232  (0.4561592563986778)
     | > postnet_loss: 0.3237585723400116  (0.31861715018749237)
     | > stopnet_loss: 0.00849777553230524  (0.009583139792084694)
     | > loss: 0.20544877648353577  (0.20327723771333694)
     | > align_error: 0.6053950786590576  (0.6647462472319603)

   --> STEP: 5
     | > decoder_loss: 0.44365617632865906  (0.4536586403846741)
     | > postnet_loss: 0.3066142201423645  (0.3162165641784668)
     | > stopnet_loss: 0.008462752215564251  (0.009359062276780605)
     | > loss: 0.19603034853935242  (0.20182785987854004)
     | > align_error: 0.6436409950256348  (0.6605251967906952)

   --> STEP: 6
     | > decoder_loss: 0.46034592390060425  (0.4547731876373291)
     | > postnet_loss: 0.31668105721473694  (0.31629397968451184)
     | > stopnet_loss: 0.007490464020520449  (0.009047629234070579)
     | > loss: 0.20174722373485565  (0.2018144205212593)
     | > align_error: 0.5954751372337341  (0.6496835201978683)

   --> STEP: 7
     | > decoder_loss: 0.46573522686958313  (0.45633919324193684)
     | > postnet_loss: 0.31455308198928833  (0.3160452800137656)
     | > stopnet_loss: 0.006609279662370682  (0.008699293580970593)
     | > loss: 0.20168136060237885  (0.20179541196141923)
     | > align_error: 0.5805608630180359  (0.6398088548864637)

   --> STEP: 8
     | > decoder_loss: 0.4622933864593506  (0.45708346739411354)
     | > postnet_loss: 0.31485992670059204  (0.3158971108496189)
     | > stopnet_loss: 0.007463822141289711  (0.008544859651010484)
     | > loss: 0.20175215601921082  (0.2017900049686432)
     | > align_error: 0.576734721660614  (0.6319245882332325)

   --> STEP: 9
     | > decoder_loss: 0.46044018864631653  (0.45745643642213607)
     | > postnet_loss: 0.3162408769130707  (0.31593530707889134)
     | > stopnet_loss: 0.006861764471977949  (0.008357849075562425)
     | > loss: 0.20103202760219574  (0.20170578526126015)
     | > align_error: 0.593614399433136  (0.6276679005887773)

   --> STEP: 10
     | > decoder_loss: 0.4897778332233429  (0.4606885761022568)
     | > postnet_loss: 0.3309662342071533  (0.3174383997917175)
     | > stopnet_loss: 0.005656554363667965  (0.008087719604372979)
     | > loss: 0.210842564702034  (0.20261946320533752)
     | > align_error: 0.5868294835090637  (0.6235840588808059)

   --> STEP: 11
     | > decoder_loss: 0.47478511929512024  (0.46197008002888074)
     | > postnet_loss: 0.3232418894767761  (0.3179659897630865)
     | > stopnet_loss: 0.00604374660179019  (0.007901903876865452)
     | > loss: 0.20555050671100616  (0.20288592170585285)
     | > align_error: 0.5955111086368561  (0.6210319724949923)

   --> STEP: 12
     | > decoder_loss: 0.46788153052330017  (0.4624627009034157)
     | > postnet_loss: 0.31426021456718445  (0.317657175163428)
     | > stopnet_loss: 0.008057935163378716  (0.00791490648407489)
     | > loss: 0.20359337329864502  (0.2029448760052522)
     | > align_error: 0.5892947018146515  (0.6183871999382973)

   --> STEP: 13
     | > decoder_loss: 0.4608471393585205  (0.46233842693842375)
     | > postnet_loss: 0.31600701808929443  (0.31753024000387925)
     | > stopnet_loss: 0.005743502639234066  (0.007747875419087135)
     | > loss: 0.19995704293251038  (0.20271504269196436)
     | > align_error: 0.5879315435886383  (0.6160444571421697)

   --> STEP: 14
     | > decoder_loss: 0.4637472331523895  (0.462439055953707)
     | > postnet_loss: 0.31413745880126953  (0.31728789848940714)
     | > stopnet_loss: 0.005167790222913027  (0.007563583619360413)
     | > loss: 0.1996389776468277  (0.2024953237601689)
     | > align_error: 0.5552890598773956  (0.6117047859089715)

   --> STEP: 15
     | > decoder_loss: 0.46813318133354187  (0.4628186643123627)
     | > postnet_loss: 0.32076647877693176  (0.31751980384190875)
     | > stopnet_loss: 0.005135911516845226  (0.007401738812526067)
     | > loss: 0.2023608237504959  (0.20248635709285737)
     | > align_error: 0.5891311764717102  (0.6101998786131541)

   --> STEP: 16
     | > decoder_loss: 0.4680461883544922  (0.46314538456499577)
     | > postnet_loss: 0.3125098943710327  (0.317206684499979)
     | > stopnet_loss: 0.005298912525177002  (0.0072703121695667505)
     | > loss: 0.20043793320655823  (0.20235833059996367)
     | > align_error: 0.6075868606567383  (0.6100365649908781)

   --> STEP: 17
     | > decoder_loss: 0.4753865599632263  (0.46386545370606813)
     | > postnet_loss: 0.3228607773780823  (0.317539278198691)
     | > stopnet_loss: 0.0050501590594649315  (0.007139714927796055)
     | > loss: 0.20461198687553406  (0.2024908986161737)
     | > align_error: 0.5592873990535736  (0.6070513199357426)

   --> STEP: 18
     | > decoder_loss: 0.47151392698287964  (0.46429036888811326)
     | > postnet_loss: 0.3157808482646942  (0.31744158764680225)
     | > stopnet_loss: 0.0055550867691636086  (0.007051680030094253)
     | > loss: 0.2023787796497345  (0.20248466978470483)
     | > align_error: 0.6046367883682251  (0.6069171792931027)

   --> STEP: 19
     | > decoder_loss: 0.4700019359588623  (0.4645909776813106)
     | > postnet_loss: 0.3149276673793793  (0.31730927605378)
     | > stopnet_loss: 0.004998119082301855  (0.006943597874947284)
     | > loss: 0.20123052597045898  (0.202418662215534)
     | > align_error: 0.6018146872520447  (0.6066486270804154)

   --> STEP: 20
     | > decoder_loss: 0.4645083248615265  (0.46458684504032133)
     | > postnet_loss: 0.3127008080482483  (0.31707885265350344)
     | > stopnet_loss: 0.004684621933847666  (0.006830649077892303)
     | > loss: 0.19898691773414612  (0.2022470749914646)
     | > align_error: 0.6232710182666779  (0.6074797466397286)

   --> STEP: 21
     | > decoder_loss: 0.46260717511177063  (0.4644925750437237)
     | > postnet_loss: 0.30908530950546265  (0.31669820774169194)
     | > stopnet_loss: 0.004196309018880129  (0.006705204313177438)
     | > loss: 0.19711944460868835  (0.2020029021160943)
     | > align_error: 0.5617192387580872  (0.6053006748358408)

   --> STEP: 22
     | > decoder_loss: 0.4644584357738495  (0.46449102325872943)
     | > postnet_loss: 0.3129379451274872  (0.31652728671377356)
     | > stopnet_loss: 0.005054997745901346  (0.006630194923755797)
     | > loss: 0.19940409064292908  (0.20188477432185953)
     | > align_error: 0.6262096762657166  (0.6062510839917443)

   --> STEP: 23
     | > decoder_loss: 0.4360118508338928  (0.46325279837069305)
     | > postnet_loss: 0.30155885219573975  (0.3158764852129895)
     | > stopnet_loss: 0.004726280923932791  (0.0065474160541982756)
     | > loss: 0.18911895155906677  (0.2013297385495642)
     | > align_error: 0.5673812329769135  (0.6045610904693604)

   --> STEP: 24
     | > decoder_loss: 0.4712275564670563  (0.4635850799580415)
     | > postnet_loss: 0.3171878159046173  (0.31593112399180734)
     | > stopnet_loss: 0.004544933792203665  (0.006463979293281834)
     | > loss: 0.2016487717628479  (0.20134303160011768)
     | > align_error: 0.5805136561393738  (0.6035591140389442)

   --> STEP: 25
     | > decoder_loss: 0.47136837244033813  (0.46389641165733336)
     | > postnet_loss: 0.31405624747276306  (0.3158561289310456)
     | > stopnet_loss: 0.0038577078375965357  (0.0063597284350544216)
     | > loss: 0.20021384954452515  (0.20129786431789398)
     | > align_error: 0.5593903064727783  (0.6017923617362976)

   --> STEP: 26
     | > decoder_loss: 0.4457467496395111  (0.463198347733571)
     | > postnet_loss: 0.3016446530818939  (0.3153095337060782)
     | > stopnet_loss: 0.0046013458631932735  (0.006292098336136685)
     | > loss: 0.19144919514656067  (0.20091906934976578)
     | > align_error: 0.5481637120246887  (0.5997297213627741)

   --> STEP: 27
     | > decoder_loss: 0.441926509141922  (0.4624105018598062)
     | > postnet_loss: 0.2985069751739502  (0.3146872167234068)
     | > stopnet_loss: 0.0040728687308728695  (0.00620990464705284)
     | > loss: 0.18918123841285706  (0.200484334870621)
     | > align_error: 0.5421904027462006  (0.5975986354880862)

   --> STEP: 28
     | > decoder_loss: 0.4480946660041809  (0.4618992220078196)
     | > postnet_loss: 0.3021335303783417  (0.3142388707825116)
     | > stopnet_loss: 0.0040704370476305485  (0.006133495089930615)
     | > loss: 0.19162747263908386  (0.20016801836235182)
     | > align_error: 0.5664558112621307  (0.5964863917657307)

   --> STEP: 29
     | > decoder_loss: 0.44332513213157654  (0.4612587361500181)
     | > postnet_loss: 0.29769033193588257  (0.31366823151193823)
     | > stopnet_loss: 0.0037567391991615295  (0.006051537990248923)
     | > loss: 0.1890105903148651  (0.19978327946416263)
     | > align_error: 0.5413340330123901  (0.5945845862914776)

   --> STEP: 30
     | > decoder_loss: 0.4431059658527374  (0.4606536438067754)
     | > postnet_loss: 0.2985745370388031  (0.31316510836283373)
     | > stopnet_loss: 0.0030727703124284744  (0.005952245734321574)
     | > loss: 0.18849289417266846  (0.1994069332877795)
     | > align_error: 0.534296840429306  (0.5925749947627386)

   --> STEP: 31
     | > decoder_loss: 0.44240641593933105  (0.4600650235529869)
     | > postnet_loss: 0.3008413016796112  (0.31276756621176205)
     | > stopnet_loss: 0.004109451547265053  (0.005892800760545557)
     | > loss: 0.18992139399051666  (0.1991009481491581)
     | > align_error: 0.5600910186767578  (0.5915271245664165)

   --> STEP: 32
     | > decoder_loss: 0.45016318559646606  (0.4597555911168456)
     | > postnet_loss: 0.30372345447540283  (0.3124849377200008)
     | > stopnet_loss: 0.004054346587508917  (0.0058353490676381625)
     | > loss: 0.19252601265907288  (0.19889548141509295)
     | > align_error: 0.5316065549850464  (0.5896546067669988)

   --> STEP: 33
     | > decoder_loss: 0.44748085737228394  (0.45938362948822253)
     | > postnet_loss: 0.3024654984474182  (0.31218131834810436)
     | > stopnet_loss: 0.004200173541903496  (0.005785798294131051)
     | > loss: 0.19168676435947418  (0.19867703544371057)
     | > align_error: 0.546082615852356  (0.588334243405949)

   --> STEP: 34
     | > decoder_loss: 0.45345550775527954  (0.45920927296666536)
     | > postnet_loss: 0.3046450614929199  (0.31195966373471656)
     | > stopnet_loss: 0.003524889936670661  (0.005719300989499863)
     | > loss: 0.19305002689361572  (0.1985115351922372)
     | > align_error: 0.5637764930725098  (0.5876119566314361)

   --> STEP: 35
     | > decoder_loss: 0.4506831467151642  (0.45896566935947963)
     | > postnet_loss: 0.3027210831642151  (0.3116957042898451)
     | > stopnet_loss: 0.003708772361278534  (0.0056618573144078255)
     | > loss: 0.19205984473228455  (0.19832720117909566)
     | > align_error: 0.5342615246772766  (0.586087658575603)

   --> STEP: 36
     | > decoder_loss: 0.4576451778411865  (0.45892898903952706)
     | > postnet_loss: 0.3071571886539459  (0.3115696344110701)
     | > stopnet_loss: 0.0038794486317783594  (0.005612345962112563)
     | > loss: 0.19508002698421478  (0.1982370018959045)
     | > align_error: 0.634304940700531  (0.5874270275235176)

   --> STEP: 37
     | > decoder_loss: 0.44911274313926697  (0.45866368509627675)
     | > postnet_loss: 0.3035346269607544  (0.311352472047548)
     | > stopnet_loss: 0.0037477556616067886  (0.00556195162966646)
     | > loss: 0.19190961122512817  (0.19806599133723488)
     | > align_error: 0.5192115306854248  (0.5855833654468124)

   --> STEP: 38
     | > decoder_loss: 0.43867895007133484  (0.458137771016673)
     | > postnet_loss: 0.29747307300567627  (0.31098722470434087)
     | > stopnet_loss: 0.003290519118309021  (0.005502177089893897)
     | > loss: 0.1873285323381424  (0.19778342662673246)
     | > align_error: 0.5513116121292114  (0.5846814772016123)

   --> STEP: 39
     | > decoder_loss: 0.4515095055103302  (0.4579678154908694)
     | > postnet_loss: 0.3056527078151703  (0.3108504422200032)
     | > stopnet_loss: 0.003639386035501957  (0.005454413216704359)
     | > loss: 0.1929299384355545  (0.19765897821157405)
     | > align_error: 0.5464180707931519  (0.5837003642167801)

   --> STEP: 40
     | > decoder_loss: 0.449220210313797  (0.4577491253614426)
     | > postnet_loss: 0.30444005131721497  (0.31069018244743346)
     | > stopnet_loss: 0.0032033261377364397  (0.005398136039730161)
     | > loss: 0.1916183978319168  (0.19750796370208262)
     | > align_error: 0.584691047668457  (0.583725131303072)

   --> STEP: 41
     | > decoder_loss: 0.43894171714782715  (0.45729040808793975)
     | > postnet_loss: 0.29646676778793335  (0.31034326989476274)
     | > stopnet_loss: 0.0038413964211940765  (0.005360166780741476)
     | > loss: 0.1876935213804245  (0.19726858706009098)
     | > align_error: 0.5040759444236755  (0.5817824682084526)

   --> STEP: 42
     | > decoder_loss: 0.4446713924407959  (0.4569899553344363)
     | > postnet_loss: 0.3000475764274597  (0.3100981343360174)
     | > stopnet_loss: 0.0034142821095883846  (0.00531383619333307)
     | > loss: 0.18959403038024902  (0.19708585952009475)
     | > align_error: 0.5800305306911469  (0.5817407554104215)

   --> STEP: 43
     | > decoder_loss: 0.4428425133228302  (0.45666094505509663)
     | > postnet_loss: 0.29889997839927673  (0.30983771210493044)
     | > stopnet_loss: 0.003088906407356262  (0.005262093640170818)
     | > loss: 0.188524529337883  (0.19688675881818282)
     | > align_error: 0.5519248247146606  (0.5810473616733107)

   --> STEP: 44
     | > decoder_loss: 0.4608815908432007  (0.4567568688230081)
     | > postnet_loss: 0.308071106672287  (0.30979756198146124)
     | > stopnet_loss: 0.0028530829586088657  (0.005207343397408046)
     | > loss: 0.19509126245975494  (0.196845952082764)
     | > align_error: 0.5514418482780457  (0.5803745090961456)

   --> STEP: 45
     | > decoder_loss: 0.4529089331626892  (0.4566713591416677)
     | > postnet_loss: 0.3065732419490814  (0.30972591042518616)
     | > stopnet_loss: 0.003471223870292306  (0.005168762963472141)
     | > loss: 0.19334176182746887  (0.1967680811882019)
     | > align_error: 0.5531282126903534  (0.5797690358426836)

   --> STEP: 46
     | > decoder_loss: 0.44495177268981934  (0.45641658552314923)
     | > postnet_loss: 0.2987077832221985  (0.3094863859207734)
     | > stopnet_loss: 0.003358320565894246  (0.0051294055200465346)
     | > loss: 0.18927320837974548  (0.19660514917062677)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35028342044714733 (-0.012047110181866272)
     | > avg_decoder_loss: 0.45241632876974164 (-0.0011546128627025753)
     | > avg_postnet_loss: 0.30590533126484265 (-0.00037287627205701)
     | > avg_stopnet_loss: 0.004547288849470065 (-2.798077537480813e-06)
     | > avg_loss: 0.1941277046095241 (-0.00038467099269232086)
     | > avg_align_error: 0.5724905092607846 (-0.0004756870594893048)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_1661.pth

 > EPOCH: 11/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 22:07:23)

   --> TIME: 2025-12-27 22:07:44 -- STEP: 14/150 -- GLOBAL_STEP: 1675
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4882979989051819  (0.4884625034672873)
     | > postnet_loss: 0.4172841012477875  (0.42330098152160645)
     | > stopnet_loss: 0.009051179513335228  (0.011631691030093603)
     | > loss: 0.23544669151306152  (0.2395725612129484)
     | > align_error: 0.6432843208312988  (0.6837811108146395)
     | > grad_norm: tensor(0.2076, device='cuda:0')  (tensor(0.2899, device='cuda:0'))
     | > step_time: 0.6499  (0.5736203704561506)
     | > loader_time: 0.91  (0.854094317981175)


   --> TIME: 2025-12-27 22:08:30 -- STEP: 39/150 -- GLOBAL_STEP: 1700
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.5024605393409729  (0.49509753707127696)
     | > postnet_loss: 0.4220612645149231  (0.42199428570576203)
     | > stopnet_loss: 0.005171320401132107  (0.00845259682346995)
     | > loss: 0.23630176484584808  (0.23772555131178635)
     | > align_error: 0.5942023396492004  (0.6570465450103465)
     | > grad_norm: tensor(0.2041, device='cuda:0')  (tensor(0.2498, device='cuda:0'))
     | > step_time: 1.0043  (0.7867746781080196)
     | > loader_time: 1.0714  (0.9164064969771948)


   --> TIME: 2025-12-27 22:09:32 -- STEP: 64/150 -- GLOBAL_STEP: 1725
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5038662552833557  (0.49875504383817315)
     | > postnet_loss: 0.41752955317497253  (0.4210271257907152)
     | > stopnet_loss: 0.004421968478709459  (0.007018716765742283)
     | > loss: 0.23477090895175934  (0.23696425766684115)
     | > align_error: 0.6166829168796539  (0.6410450492985545)
     | > grad_norm: tensor(0.1305, device='cuda:0')  (tensor(0.2169, device='cuda:0'))
     | > step_time: 1.5067  (0.9892962388694286)
     | > loader_time: 1.1971  (1.0138927772641184)


   --> TIME: 2025-12-27 22:10:46 -- STEP: 89/150 -- GLOBAL_STEP: 1750
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4976414144039154  (0.50004443526268)
     | > postnet_loss: 0.41226017475128174  (0.42014548349916264)
     | > stopnet_loss: 0.0037461614701896906  (0.0061815722552494385)
     | > loss: 0.23122157156467438  (0.23622905069522643)
     | > align_error: 0.65972039103508  (0.6348755483546953)
     | > grad_norm: tensor(0.2633, device='cuda:0')  (tensor(0.2018, device='cuda:0'))
     | > step_time: 1.7357  (1.1528161723961992)
     | > loader_time: 1.6562  (1.115149752477582)


   --> TIME: 2025-12-27 22:12:11 -- STEP: 114/150 -- GLOBAL_STEP: 1775
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5061561465263367  (0.5010043160434354)
     | > postnet_loss: 0.41632282733917236  (0.4197492581187633)
     | > stopnet_loss: 0.0035147974267601967  (0.005622272959730604)
     | > loss: 0.23413453996181488  (0.2358106658385511)
     | > align_error: 0.6108557879924774  (0.629697965948205)
     | > grad_norm: tensor(0.1206, device='cuda:0')  (tensor(0.1938, device='cuda:0'))
     | > step_time: 1.8458  (1.2827059302413677)
     | > loader_time: 1.8432  (1.2362073095221269)


   --> TIME: 2025-12-27 22:13:46 -- STEP: 139/150 -- GLOBAL_STEP: 1800
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5137082934379578  (0.5016787043578333)
     | > postnet_loss: 0.4198959171772003  (0.4189150908010469)
     | > stopnet_loss: 0.003398522036150098  (0.005215833725729328)
     | > loss: 0.23679958283901215  (0.23536428187390884)
     | > align_error: 0.6508773565292358  (0.6266082973360156)
     | > grad_norm: tensor(0.2242, device='cuda:0')  (tensor(0.1876, device='cuda:0'))
     | > step_time: 2.1217  (1.4049753971237076)
     | > loader_time: 1.9968  (1.3421620207724811)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47707653045654297  (0.47707653045654297)
     | > postnet_loss: 0.3364619314670563  (0.3364619314670563)
     | > stopnet_loss: 0.012545359320938587  (0.012545359320938587)
     | > loss: 0.21592997014522552  (0.21592997014522552)
     | > align_error: 0.7194443643093109  (0.7194443643093109)

   --> STEP: 1
     | > decoder_loss: 0.4575650095939636  (0.4575650095939636)
     | > postnet_loss: 0.3220166862010956  (0.3220166862010956)
     | > stopnet_loss: 0.009961058385670185  (0.009961058385670185)
     | > loss: 0.20485647022724152  (0.20485647022724152)
     | > align_error: 0.6606655716896057  (0.6606655716896057)

   --> STEP: 2
     | > decoder_loss: 0.4514991044998169  (0.45453205704689026)
     | > postnet_loss: 0.3163034915924072  (0.3191600888967514)
     | > stopnet_loss: 0.011237839236855507  (0.010599448811262846)
     | > loss: 0.20318849384784698  (0.20402248203754425)
     | > align_error: 0.6580572724342346  (0.6593614220619202)

   --> STEP: 3
     | > decoder_loss: 0.45313021540641785  (0.4540647765000661)
     | > postnet_loss: 0.31247106194496155  (0.3169304132461548)
     | > stopnet_loss: 0.00866848323494196  (0.009955793619155884)
     | > loss: 0.20006880164146423  (0.20270458857218424)
     | > align_error: 0.7363455891609192  (0.6850228110949198)

   --> STEP: 4
     | > decoder_loss: 0.4643308222293854  (0.45663128793239594)
     | > postnet_loss: 0.3235647678375244  (0.3185890018939972)
     | > stopnet_loss: 0.008518979884684086  (0.009596590185537934)
     | > loss: 0.20549286901950836  (0.20340165868401527)
     | > align_error: 0.6058114767074585  (0.6652199774980545)

   --> STEP: 5
     | > decoder_loss: 0.4451861083507538  (0.4543422520160675)
     | > postnet_loss: 0.30690810084342957  (0.3162528216838837)
     | > stopnet_loss: 0.008435698226094246  (0.009364411793649196)
     | > loss: 0.19645924866199493  (0.20201317667961122)
     | > align_error: 0.6441000401973724  (0.6609959900379181)

   --> STEP: 6
     | > decoder_loss: 0.4603551924228668  (0.45534440875053406)
     | > postnet_loss: 0.3164653480052948  (0.3162882427374522)
     | > stopnet_loss: 0.007505705114454031  (0.00905462734711667)
     | > loss: 0.20171083509922028  (0.2019627864162127)
     | > align_error: 0.5958220958709717  (0.6501336743434271)

   --> STEP: 7
     | > decoder_loss: 0.46677806973457336  (0.4569777888911111)
     | > postnet_loss: 0.314716637134552  (0.31606372765132357)
     | > stopnet_loss: 0.00660666124895215  (0.008704917904521738)
     | > loss: 0.2019803524017334  (0.20196529584271566)
     | > align_error: 0.5812389254570007  (0.6402915673596519)

   --> STEP: 8
     | > decoder_loss: 0.46203672885894775  (0.4576101563870907)
     | > postnet_loss: 0.3145713210105896  (0.31587717682123184)
     | > stopnet_loss: 0.007526406552642584  (0.008557603985536844)
     | > loss: 0.20167842507362366  (0.20192943699657917)
     | > align_error: 0.5770850777626038  (0.6323907561600208)

   --> STEP: 9
     | > decoder_loss: 0.4598058760166168  (0.45785412523481583)
     | > postnet_loss: 0.31571024656295776  (0.3158586290147569)
     | > stopnet_loss: 0.0068332962691783905  (0.008366014239274792)
     | > loss: 0.20071233808994293  (0.2017942037847307)
     | > align_error: 0.5940876603126526  (0.6281348566214243)

   --> STEP: 10
     | > decoder_loss: 0.49134185910224915  (0.46120289862155917)
     | > postnet_loss: 0.3311721086502075  (0.317389976978302)
     | > stopnet_loss: 0.005895288661122322  (0.008118941681459546)
     | > loss: 0.21152377128601074  (0.20276716053485871)
     | > align_error: 0.5884506702423096  (0.6241664379835129)

   --> STEP: 11
     | > decoder_loss: 0.47542181611061096  (0.4624955274842002)
     | > postnet_loss: 0.3230823874473572  (0.3179074688391252)
     | > stopnet_loss: 0.006048290058970451  (0.007930700624869629)
     | > loss: 0.20567435026168823  (0.20303145051002502)
     | > align_error: 0.5957537293434143  (0.6215834644707766)

   --> STEP: 12
     | > decoder_loss: 0.4674859642982483  (0.4629113972187042)
     | > postnet_loss: 0.3140372335910797  (0.3175849492351214)
     | > stopnet_loss: 0.008046134375035763  (0.007940320104050139)
     | > loss: 0.20342694222927094  (0.20306440815329552)
     | > align_error: 0.5896629691123962  (0.6189234231909116)

   --> STEP: 13
     | > decoder_loss: 0.4607734978199005  (0.46274694341879624)
     | > postnet_loss: 0.3155944347381592  (0.3174318327353551)
     | > stopnet_loss: 0.0057462044060230255  (0.007771541973432669)
     | > loss: 0.19983817636966705  (0.20281623647763178)
     | > align_error: 0.5880873799324036  (0.6165514198633341)

   --> STEP: 14
     | > decoder_loss: 0.4633818566799164  (0.4627922943660191)
     | > postnet_loss: 0.3136039078235626  (0.3171584095273699)
     | > stopnet_loss: 0.005175014492124319  (0.007586075724767787)
     | > loss: 0.1994214504957199  (0.20257375176463807)
     | > align_error: 0.5557501018047333  (0.612208468573434)

   --> STEP: 15
     | > decoder_loss: 0.46918612718582153  (0.4632185498873393)
     | > postnet_loss: 0.3211955726146698  (0.3174275537331899)
     | > stopnet_loss: 0.005156825762242079  (0.007424125727266073)
     | > loss: 0.2027522474527359  (0.20258565147717794)
     | > align_error: 0.5897166728973389  (0.610709015528361)

   --> STEP: 16
     | > decoder_loss: 0.46863606572151184  (0.46355714462697506)
     | > postnet_loss: 0.31250885128974915  (0.31712013483047485)
     | > stopnet_loss: 0.005289712455123663  (0.007290724897757173)
     | > loss: 0.20057594776153564  (0.2024600449949503)
     | > align_error: 0.607809841632843  (0.6105278171598911)

   --> STEP: 17
     | > decoder_loss: 0.4762653708457947  (0.46430468734572916)
     | > postnet_loss: 0.323102742433548  (0.31747205292477326)
     | > stopnet_loss: 0.0050397696904838085  (0.007158315767917563)
     | > loss: 0.20488180220127106  (0.20260250130120447)
     | > align_error: 0.5595404803752899  (0.6075285620549146)

   --> STEP: 18
     | > decoder_loss: 0.4717121422290802  (0.46471621261702645)
     | > postnet_loss: 0.3157014846801758  (0.31737368802229565)
     | > stopnet_loss: 0.005556072108447552  (0.00706930223128034)
     | > loss: 0.20240947604179382  (0.20259177767568165)
     | > align_error: 0.6048250794410706  (0.6073783685763677)

   --> STEP: 19
     | > decoder_loss: 0.4712701439857483  (0.46506115637327494)
     | > postnet_loss: 0.31509464979171753  (0.3172537386417389)
     | > stopnet_loss: 0.005055889021605253  (0.006963333114981651)
     | > loss: 0.201647087931633  (0.202542057162837)
     | > align_error: 0.6020759344100952  (0.6070992930939323)

   --> STEP: 20
     | > decoder_loss: 0.4652739465236664  (0.4650717958807945)
     | > postnet_loss: 0.3128347396850586  (0.3170327886939049)
     | > stopnet_loss: 0.004680875223129988  (0.006849210220389068)
     | > loss: 0.19920805096626282  (0.20237535685300828)
     | > align_error: 0.6233654022216797  (0.6079125985503196)

   --> STEP: 21
     | > decoder_loss: 0.46256333589553833  (0.4649523454053061)
     | > postnet_loss: 0.3089732825756073  (0.3166490026882717)
     | > stopnet_loss: 0.0041830637492239475  (0.0067222508646193006)
     | > loss: 0.19706721603870392  (0.2021225882428033)
     | > align_error: 0.5618423819541931  (0.6057187787124089)

   --> STEP: 22
     | > decoder_loss: 0.46530357003211975  (0.4649683101610704)
     | > postnet_loss: 0.31312036514282227  (0.3164886100725694)
     | > stopnet_loss: 0.00505030807107687  (0.0066462534649128265)
     | > loss: 0.19965627789497375  (0.20201048322699286)
     | > align_error: 0.6264818906784058  (0.6066625565290451)

   --> STEP: 23
     | > decoder_loss: 0.43639442324638367  (0.4637259672517362)
     | > postnet_loss: 0.30170443654060364  (0.3158458199190057)
     | > stopnet_loss: 0.004707669373601675  (0.006561967200073211)
     | > loss: 0.18923237919807434  (0.2014549134866051)
     | > align_error: 0.5673014521598816  (0.6049512041651685)

   --> STEP: 24
     | > decoder_loss: 0.4719732105731964  (0.46406960239013034)
     | > postnet_loss: 0.3173201084136963  (0.31590724860628444)
     | > stopnet_loss: 0.004533146973699331  (0.006477433023974299)
     | > loss: 0.20185646414756775  (0.20147164476414522)
     | > align_error: 0.5805100798606873  (0.603932823985815)

   --> STEP: 25
     | > decoder_loss: 0.47177955508232117  (0.46437800049781797)
     | > postnet_loss: 0.3139888644218445  (0.3158305132389069)
     | > stopnet_loss: 0.0038349416572600603  (0.00637173336930573)
     | > loss: 0.20027704536914825  (0.20142386078834534)
     | > align_error: 0.5597166419029236  (0.6021641767024994)

   --> STEP: 26
     | > decoder_loss: 0.44551828503608704  (0.46365262682621294)
     | > postnet_loss: 0.3014734387397766  (0.31527831806586337)
     | > stopnet_loss: 0.004600169602781534  (0.006303596301362491)
     | > loss: 0.1913481056690216  (0.20103633174529442)
     | > align_error: 0.5483580827713013  (0.6000947115512996)

   --> STEP: 27
     | > decoder_loss: 0.4421827495098114  (0.46285744618486474)
     | > postnet_loss: 0.29843905568122864  (0.3146546416812473)
     | > stopnet_loss: 0.004064266569912434  (0.006220658163160637)
     | > loss: 0.18921971321105957  (0.20059867920698943)
     | > align_error: 0.5423656105995178  (0.5979565967012336)

   --> STEP: 28
     | > decoder_loss: 0.44793176651000977  (0.4623243861964771)
     | > postnet_loss: 0.30189764499664307  (0.31419903465679716)
     | > stopnet_loss: 0.004055751021951437  (0.006143340050974595)
     | > loss: 0.19151310622692108  (0.20027419445770128)
     | > align_error: 0.5666047930717468  (0.5968368894287519)

   --> STEP: 29
     | > decoder_loss: 0.4435557425022125  (0.46167719158633)
     | > postnet_loss: 0.29762816429138184  (0.3136276253338518)
     | > stopnet_loss: 0.003748933784663677  (0.006060774317653528)
     | > loss: 0.18904490768909454  (0.1998869776725769)
     | > align_error: 0.5413773059844971  (0.5949244899996396)

   --> STEP: 30
     | > decoder_loss: 0.44365739822387695  (0.46107653180758157)
     | > postnet_loss: 0.2987428903579712  (0.3131314675013224)
     | > stopnet_loss: 0.0030824101995676756  (0.005961495513717333)
     | > loss: 0.18868248164653778  (0.19951349447170894)
     | > align_error: 0.5344075560569763  (0.5929072588682176)

   --> STEP: 31
     | > decoder_loss: 0.4428463280200958  (0.4604884607176627)
     | > postnet_loss: 0.300882488489151  (0.3127363391460911)
     | > stopnet_loss: 0.0041025374084711075  (0.00590152912322552)
     | > loss: 0.19003474712371826  (0.19920772842822537)
     | > align_error: 0.5603188574314117  (0.5918560201121916)

   --> STEP: 32
     | > decoder_loss: 0.4497811198234558  (0.4601538563147187)
     | > postnet_loss: 0.3033202290534973  (0.31244208570569754)
     | > stopnet_loss: 0.004041141364723444  (0.00584339200577233)
     | > loss: 0.192316472530365  (0.19899237668141723)
     | > align_error: 0.5318020284175873  (0.5899793328717352)

   --> STEP: 33
     | > decoder_loss: 0.44792166352272034  (0.4597831838058703)
     | > postnet_loss: 0.3023677170276642  (0.3121368018063632)
     | > stopnet_loss: 0.00416146032512188  (0.005792424379085953)
     | > loss: 0.19173380732536316  (0.19877242003426407)
     | > align_error: 0.5463524758815765  (0.5886573069023364)

   --> STEP: 34
     | > decoder_loss: 0.4539251923561096  (0.45961088993970084)
     | > postnet_loss: 0.3045808970928192  (0.3119145693147884)
     | > stopnet_loss: 0.003510784823447466  (0.005725317333331879)
     | > loss: 0.1931373029947281  (0.19860668129780712)
     | > align_error: 0.5637655258178711  (0.5879251956939698)

   --> STEP: 35
     | > decoder_loss: 0.4512729346752167  (0.4593726626464299)
     | > postnet_loss: 0.3028368055820465  (0.31165520463671004)
     | > stopnet_loss: 0.0037037343718111515  (0.005667557820145573)
     | > loss: 0.1922311633825302  (0.19842452364308494)
     | > align_error: 0.5344660580158234  (0.5863977917603085)

   --> STEP: 36
     | > decoder_loss: 0.45734456181526184  (0.45931632651223075)
     | > postnet_loss: 0.3068810999393463  (0.31152259061733883)
     | > stopnet_loss: 0.0038696664851158857  (0.005617616394172526)
     | > loss: 0.19492608308792114  (0.19832734473877484)
     | > align_error: 0.6343336999416351  (0.5877293447653453)

   --> STEP: 37
     | > decoder_loss: 0.44948524236679077  (0.459050621535327)
     | > postnet_loss: 0.3035906255245209  (0.31130821318239776)
     | > stopnet_loss: 0.0037431344389915466  (0.005566954719708176)
     | > loss: 0.19201210141181946  (0.19815666248669495)
     | > align_error: 0.5195092558860779  (0.5858855585794192)

   --> STEP: 38
     | > decoder_loss: 0.43914714455604553  (0.4585268458253459)
     | > postnet_loss: 0.29751357436180115  (0.3109451963713294)
     | > stopnet_loss: 0.003270126646384597  (0.005506511875673345)
     | > loss: 0.1874352991580963  (0.19787452134646868)
     | > align_error: 0.551325798034668  (0.5849760911966625)

   --> STEP: 39
     | > decoder_loss: 0.4516153931617737  (0.4583496290903825)
     | > postnet_loss: 0.30574163794517517  (0.3108117717962998)
     | > stopnet_loss: 0.0036356374621391296  (0.005458540736864775)
     | > loss: 0.19297489523887634  (0.19774888990781245)
     | > align_error: 0.5467337965965271  (0.5839955195402488)

   --> STEP: 40
     | > decoder_loss: 0.44923135638237  (0.4581216722726822)
     | > postnet_loss: 0.30429744720458984  (0.31064891368150704)
     | > stopnet_loss: 0.003200698643922806  (0.005402094684541226)
     | > loss: 0.19158290326595306  (0.19759474024176596)
     | > align_error: 0.5847681164741516  (0.5840148344635964)

   --> STEP: 41
     | > decoder_loss: 0.439361572265625  (0.4576641088578759)
     | > postnet_loss: 0.2965829074382782  (0.31030584035850145)
     | > stopnet_loss: 0.0038282459136098623  (0.0053637081291526565)
     | > loss: 0.1878143697977066  (0.19735619462117915)
     | > align_error: 0.5044383406639099  (0.5820739443709211)

   --> STEP: 42
     | > decoder_loss: 0.44420504570007324  (0.4573436549731663)
     | > postnet_loss: 0.29955148696899414  (0.3100497843254179)
     | > stopnet_loss: 0.0034077069722115993  (0.005317136673035012)
     | > loss: 0.18934683501720428  (0.1971654955829893)
     | > align_error: 0.579987108707428  (0.5820242578075046)

   --> STEP: 43
     | > decoder_loss: 0.44321781396865845  (0.4570151470428289)
     | > postnet_loss: 0.2988358736038208  (0.3097889957039854)
     | > stopnet_loss: 0.0030780392698943615  (0.005265064640403834)
     | > loss: 0.18859146535396576  (0.19696609953115152)
     | > align_error: 0.5518952012062073  (0.5813235820725907)

   --> STEP: 44
     | > decoder_loss: 0.46068596839904785  (0.4570985748009248)
     | > postnet_loss: 0.3078027665615082  (0.30974385413256544)
     | > stopnet_loss: 0.002846012357622385  (0.005210086179431529)
     | > loss: 0.19496820867061615  (0.19692069292068481)
     | > align_error: 0.5514713525772095  (0.5806451223113321)

   --> STEP: 45
     | > decoder_loss: 0.4532642066478729  (0.4570133666197459)
     | > postnet_loss: 0.30662617087364197  (0.3096745722823671)
     | > stopnet_loss: 0.0034810048528015614  (0.005171662149950863)
     | > loss: 0.1934535950422287  (0.19684364630116358)
     | > align_error: 0.5531060099601746  (0.580033142036862)

   --> STEP: 46
     | > decoder_loss: 0.44503748416900635  (0.45675302134907764)
     | > postnet_loss: 0.2986016571521759  (0.3094338567360586)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3719427260485563 (+0.021659305601408996)
     | > avg_decoder_loss: 0.45255968381058087 (+0.00014335504083923256)
     | > avg_postnet_loss: 0.30584739780787257 (-5.79334569700829e-05)
     | > avg_stopnet_loss: 0.004548331726144887 (+1.0428766748227236e-06)
     | > avg_loss: 0.19415010195789914 (+2.23973483750306e-05)
     | > avg_align_error: 0.5726911533962596 (+0.00020064413547504767)


 > EPOCH: 12/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 22:16:31)

   --> TIME: 2025-12-27 22:16:47 -- STEP: 13/150 -- GLOBAL_STEP: 1825
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4806426465511322  (0.486765593290329)
     | > postnet_loss: 0.4128013849258423  (0.42228846137340253)
     | > stopnet_loss: 0.008785099722445011  (0.011801184226687137)
     | > loss: 0.23214611411094666  (0.23906469574341407)
     | > align_error: 0.659903347492218  (0.6872709049628332)
     | > grad_norm: tensor(0.3339, device='cuda:0')  (tensor(0.2826, device='cuda:0'))
     | > step_time: 0.6018  (0.5301242058093731)
     | > loader_time: 0.8101  (0.6760871960566595)


   --> TIME: 2025-12-27 22:17:34 -- STEP: 38/150 -- GLOBAL_STEP: 1850
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.5041035413742065  (0.4937414393613213)
     | > postnet_loss: 0.4224283993244171  (0.4209673467435335)
     | > stopnet_loss: 0.005605912767350674  (0.008533731605367441)
     | > loss: 0.23723888397216797  (0.2372109270409534)
     | > align_error: 0.6099827289581299  (0.6585220835710827)
     | > grad_norm: tensor(0.2268, device='cuda:0')  (tensor(0.2327, device='cuda:0'))
     | > step_time: 1.0469  (0.7772309905604312)
     | > loader_time: 0.9855  (0.873420558477703)


   --> TIME: 2025-12-27 22:18:34 -- STEP: 63/150 -- GLOBAL_STEP: 1875
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5109307169914246  (0.49764114807522486)
     | > postnet_loss: 0.42174944281578064  (0.42027134081674)
     | > stopnet_loss: 0.003994144964963198  (0.007053834053554705)
     | > loss: 0.2371641844511032  (0.23653195561870696)
     | > align_error: 0.570338785648346  (0.6410106264409565)
     | > grad_norm: tensor(0.2012, device='cuda:0')  (tensor(0.2076, device='cuda:0'))
     | > step_time: 1.3577  (0.9642203232598683)
     | > loader_time: 1.2044  (0.9768178690047491)


   --> TIME: 2025-12-27 22:19:40 -- STEP: 88/150 -- GLOBAL_STEP: 1900
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5048814415931702  (0.49934939261187206)
     | > postnet_loss: 0.4178374111652374  (0.4196814044632695)
     | > stopnet_loss: 0.004261705558747053  (0.0062145273629787634)
     | > loss: 0.23494142293930054  (0.23597222634337164)
     | > align_error: 0.611683189868927  (0.6345866278491237)
     | > grad_norm: tensor(0.1472, device='cuda:0')  (tensor(0.1960, device='cuda:0'))
     | > step_time: 1.7134  (1.0820174108852039)
     | > loader_time: 2.515  (1.0593987974253574)


   --> TIME: 2025-12-27 22:21:09 -- STEP: 113/150 -- GLOBAL_STEP: 1925
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5127302408218384  (0.5002717528722982)
     | > postnet_loss: 0.42110633850097656  (0.4192590093718166)
     | > stopnet_loss: 0.0035922378301620483  (0.005649577976674237)
     | > loss: 0.23705138266086578  (0.2355322680905857)
     | > align_error: 0.6122472882270813  (0.6298906837416961)
     | > grad_norm: tensor(0.2127, device='cuda:0')  (tensor(0.1909, device='cuda:0'))
     | > step_time: 1.8168  (1.231160140670506)
     | > loader_time: 1.9122  (1.2219717312703091)


   --> TIME: 2025-12-27 22:22:44 -- STEP: 138/150 -- GLOBAL_STEP: 1950
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.508421778678894  (0.5010410426319508)
     | > postnet_loss: 0.4161979556083679  (0.4184707502524058)
     | > stopnet_loss: 0.0033947841729968786  (0.005235969309992009)
     | > loss: 0.23454971611499786  (0.2351139168376508)
     | > align_error: 0.5880696177482605  (0.6264952021664467)
     | > grad_norm: tensor(0.1197, device='cuda:0')  (tensor(0.1886, device='cuda:0'))
     | > step_time: 1.9608  (1.354883764101111)
     | > loader_time: 1.835  (1.3446842760279558)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47725412249565125  (0.47725412249565125)
     | > postnet_loss: 0.33543792366981506  (0.33543792366981506)
     | > stopnet_loss: 0.012491469271481037  (0.012491469271481037)
     | > loss: 0.21566447615623474  (0.21566447615623474)
     | > align_error: 0.7197127342224121  (0.7197127342224121)

   --> STEP: 1
     | > decoder_loss: 0.45909222960472107  (0.45909222960472107)
     | > postnet_loss: 0.32092466950416565  (0.32092466950416565)
     | > stopnet_loss: 0.009953262284398079  (0.009953262284398079)
     | > loss: 0.2049574851989746  (0.2049574851989746)
     | > align_error: 0.6610476970672607  (0.6610476970672607)

   --> STEP: 2
     | > decoder_loss: 0.4523746967315674  (0.4557334631681442)
     | > postnet_loss: 0.3163384795188904  (0.318631574511528)
     | > stopnet_loss: 0.011187602765858173  (0.010570432525128126)
     | > loss: 0.20336589217185974  (0.20416168868541718)
     | > align_error: 0.6590662598609924  (0.6600569784641266)

   --> STEP: 3
     | > decoder_loss: 0.45426613092422485  (0.4552443524201711)
     | > postnet_loss: 0.3123880922794342  (0.31655041376749676)
     | > stopnet_loss: 0.008564230054616928  (0.00990169836829106)
     | > loss: 0.2002277970314026  (0.20285039146741232)
     | > align_error: 0.7367740869522095  (0.6856293479601542)

   --> STEP: 4
     | > decoder_loss: 0.4649830758571625  (0.45767903327941895)
     | > postnet_loss: 0.3227602541446686  (0.3181028738617897)
     | > stopnet_loss: 0.008549820631742477  (0.009563728934153914)
     | > loss: 0.20548565685749054  (0.20350920781493187)
     | > align_error: 0.6063555181026459  (0.6658108904957771)

   --> STEP: 5
     | > decoder_loss: 0.44560015201568604  (0.45526325702667236)
     | > postnet_loss: 0.30658799409866333  (0.3157998979091644)
     | > stopnet_loss: 0.008465924300253391  (0.00934416800737381)
     | > loss: 0.19651296734809875  (0.20210995972156526)
     | > align_error: 0.6444546580314636  (0.6615396440029144)

   --> STEP: 6
     | > decoder_loss: 0.46093395352363586  (0.45620837310949963)
     | > postnet_loss: 0.3157521188259125  (0.31579193472862244)
     | > stopnet_loss: 0.007436913438141346  (0.009026292245835066)
     | > loss: 0.20160843431949615  (0.20202637215455374)
     | > align_error: 0.5963443517684937  (0.6506737619638443)

   --> STEP: 7
     | > decoder_loss: 0.46714988350868225  (0.45777144602366854)
     | > postnet_loss: 0.3148212134838104  (0.31565326026507784)
     | > stopnet_loss: 0.0066027226857841015  (0.008680068022970642)
     | > loss: 0.20209549367427826  (0.20203624665737152)
     | > align_error: 0.5818031430244446  (0.6408351021153587)

   --> STEP: 8
     | > decoder_loss: 0.46401193737983704  (0.4585515074431896)
     | > postnet_loss: 0.3150068521499634  (0.31557245925068855)
     | > stopnet_loss: 0.007691660895943642  (0.008556517132092267)
     | > loss: 0.2024463564157486  (0.20208751037716866)
     | > align_error: 0.5777348875999451  (0.6329475753009319)

   --> STEP: 9
     | > decoder_loss: 0.4623241126537323  (0.45897068579991657)
     | > postnet_loss: 0.31682246923446655  (0.3157113492488861)
     | > stopnet_loss: 0.006830933969467878  (0.008364785669578446)
     | > loss: 0.20161756873130798  (0.2020352946387397)
     | > align_error: 0.5948026180267334  (0.6287092467149099)

   --> STEP: 10
     | > decoder_loss: 0.49271389842033386  (0.4623450070619583)
     | > postnet_loss: 0.33130258321762085  (0.3172704726457596)
     | > stopnet_loss: 0.005902223754674196  (0.008118529478088022)
     | > loss: 0.2119063436985016  (0.20302239954471588)
     | > align_error: 0.5890277624130249  (0.6247410982847214)

   --> STEP: 11
     | > decoder_loss: 0.47591283917427063  (0.4635784463448958)
     | > postnet_loss: 0.32343095541000366  (0.31783051653341815)
     | > stopnet_loss: 0.005995732732117176  (0.007925547955727036)
     | > loss: 0.20583169162273407  (0.20327778973362662)
     | > align_error: 0.596348762512207  (0.6221599768508564)

   --> STEP: 12
     | > decoder_loss: 0.4693208336830139  (0.4640569786230723)
     | > postnet_loss: 0.31467679142951965  (0.31756770610809326)
     | > stopnet_loss: 0.00808075349777937  (0.007938481750898063)
     | > loss: 0.20408016443252563  (0.2033446542918682)
     | > align_error: 0.5902400016784668  (0.619499978919824)

   --> STEP: 13
     | > decoder_loss: 0.4621712267398834  (0.46391192078590393)
     | > postnet_loss: 0.3158133625984192  (0.3174327566073491)
     | > stopnet_loss: 0.005750368349254131  (0.0077701653353869915)
     | > loss: 0.20024652779102325  (0.20310633686872628)
     | > align_error: 0.5888636410236359  (0.6171433375431941)

   --> STEP: 14
     | > decoder_loss: 0.4653300940990448  (0.4640132188796997)
     | > postnet_loss: 0.3145521581172943  (0.3172269995723452)
     | > stopnet_loss: 0.005132848862558603  (0.007581785587327821)
     | > loss: 0.20010341703891754  (0.20289184259516851)
     | > align_error: 0.5562248826026917  (0.6127920193331582)

   --> STEP: 15
     | > decoder_loss: 0.46973055601119995  (0.4643943746884664)
     | > postnet_loss: 0.32193586230278015  (0.3175409237543742)
     | > stopnet_loss: 0.0051198904402554035  (0.00741765924418966)
     | > loss: 0.20303648710250854  (0.2029014855623245)
     | > align_error: 0.5905194282531738  (0.6113071799278259)

   --> STEP: 16
     | > decoder_loss: 0.4681651294231415  (0.4646300468593836)
     | > postnet_loss: 0.3129127621650696  (0.31725166365504265)
     | > stopnet_loss: 0.005283425562083721  (0.007284269639058039)
     | > loss: 0.20055289566516876  (0.2027546986937523)
     | > align_error: 0.608241468667984  (0.6111155729740858)

   --> STEP: 17
     | > decoder_loss: 0.47754597663879395  (0.46538980743464303)
     | > postnet_loss: 0.3247540295124054  (0.31769297929371104)
     | > stopnet_loss: 0.00502895750105381  (0.007151604219175437)
     | > loss: 0.2056039571762085  (0.20292230213389678)
     | > align_error: 0.5599933862686157  (0.6081083855208229)

   --> STEP: 18
     | > decoder_loss: 0.4719620943069458  (0.4657549344831043)
     | > postnet_loss: 0.3162320554256439  (0.31761181685659623)
     | > stopnet_loss: 0.005557776894420385  (0.0070630582566890455)
     | > loss: 0.20260632038116455  (0.20290474759207833)
     | > align_error: 0.605260968208313  (0.6079501956701279)

   --> STEP: 19
     | > decoder_loss: 0.4719180464744568  (0.4660793087984386)
     | > postnet_loss: 0.31605055928230286  (0.3175296454053176)
     | > stopnet_loss: 0.005038170609623194  (0.006956485222632948)
     | > loss: 0.20203033089637756  (0.20285872566072563)
     | > align_error: 0.6027892529964447  (0.6076785671083551)

   --> STEP: 20
     | > decoder_loss: 0.46573346853256226  (0.4660620167851448)
     | > postnet_loss: 0.31420162320137024  (0.31736324429512025)
     | > stopnet_loss: 0.0046628136187791824  (0.00684180164244026)
     | > loss: 0.19964659214019775  (0.20269811898469925)
     | > align_error: 0.6238924562931061  (0.6084892615675926)

   --> STEP: 21
     | > decoder_loss: 0.4632216989994049  (0.46592676355725243)
     | > postnet_loss: 0.3094486892223358  (0.31698636072022573)
     | > stopnet_loss: 0.004163672216236591  (0.0067142716697638945)
     | > loss: 0.1973312646150589  (0.20244255449090684)
     | > align_error: 0.562532901763916  (0.6063008634817033)

   --> STEP: 22
     | > decoder_loss: 0.4658728837966919  (0.46592431447722693)
     | > postnet_loss: 0.31407079100608826  (0.3168538348241286)
     | > stopnet_loss: 0.005056898575276136  (0.00663893652910536)
     | > loss: 0.20004282891750336  (0.20233347605575214)
     | > align_error: 0.6268319487571716  (0.6072340946305883)

   --> STEP: 23
     | > decoder_loss: 0.4365041255950928  (0.4646451758301776)
     | > postnet_loss: 0.30225756764411926  (0.3162192145119543)
     | > stopnet_loss: 0.004728051368147135  (0.006555854565585437)
     | > loss: 0.1894184648990631  (0.20177195383154828)
     | > align_error: 0.5679428577423096  (0.6055257799832718)

   --> STEP: 24
     | > decoder_loss: 0.472181111574173  (0.46495917315284413)
     | > postnet_loss: 0.3185335695743561  (0.3163156459728877)
     | > stopnet_loss: 0.004539034329354763  (0.006471820389075826)
     | > loss: 0.202217698097229  (0.20179052650928497)
     | > align_error: 0.5813345909118652  (0.6045178137719632)

   --> STEP: 25
     | > decoder_loss: 0.4718608558177948  (0.46523524045944215)
     | > postnet_loss: 0.3149409294128418  (0.31626065731048586)
     | > stopnet_loss: 0.003830407978966832  (0.006366163892671466)
     | > loss: 0.20053085684776306  (0.2017401397228241)
     | > align_error: 0.5601746141910553  (0.602744085788727)

   --> STEP: 26
     | > decoder_loss: 0.4462067782878876  (0.464503376529767)
     | > postnet_loss: 0.3022341728210449  (0.31572117713781506)
     | > stopnet_loss: 0.0046082730405032635  (0.006298552706049612)
     | > loss: 0.19171851873397827  (0.20135469276171464)
     | > align_error: 0.5493414998054504  (0.6006901401739856)

   --> STEP: 27
     | > decoder_loss: 0.44298461079597473  (0.4637063852062932)
     | > postnet_loss: 0.2999984920024872  (0.31513885546613624)
     | > stopnet_loss: 0.004050465766340494  (0.006215290226801126)
     | > loss: 0.18979623913764954  (0.20092660188674927)
     | > align_error: 0.5431434810161591  (0.5985587824273995)

   --> STEP: 28
     | > decoder_loss: 0.44815048575401306  (0.4631508173687117)
     | > postnet_loss: 0.30279868841171265  (0.31469813521419254)
     | > stopnet_loss: 0.004053766839206219  (0.006138092962958451)
     | > loss: 0.19179105758666992  (0.20060033244746073)
     | > align_error: 0.5671299695968628  (0.5974363248263089)

   --> STEP: 29
     | > decoder_loss: 0.44405946135520935  (0.4624924947475565)
     | > postnet_loss: 0.2985627353191376  (0.314141742114363)
     | > stopnet_loss: 0.003731467993929982  (0.006055105895060918)
     | > loss: 0.1893870234489441  (0.20021366661992565)
     | > align_error: 0.541955977678299  (0.595523209407412)

   --> STEP: 30
     | > decoder_loss: 0.44399937987327576  (0.4618760575850805)
     | > postnet_loss: 0.2996833622455597  (0.3136597961187363)
     | > stopnet_loss: 0.003059900365769863  (0.005955265710751215)
     | > loss: 0.1889805793762207  (0.19983923037846882)
     | > align_error: 0.5350385010242462  (0.5935070524613065)

   --> STEP: 31
     | > decoder_loss: 0.4426499903202057  (0.4612558618668587)
     | > postnet_loss: 0.30189406871795654  (0.3132802565251627)
     | > stopnet_loss: 0.004115684889256954  (0.00589592439392882)
     | > loss: 0.1902516931295395  (0.19952995498334208)
     | > align_error: 0.5613304078578949  (0.5924690961837771)

   --> STEP: 32
     | > decoder_loss: 0.4491739869117737  (0.4608783032745123)
     | > postnet_loss: 0.30387067794799805  (0.31298620719462633)
     | > stopnet_loss: 0.004040229134261608  (0.00583793391706422)
     | > loss: 0.19230139255523682  (0.1993040624074638)
     | > align_error: 0.5325000882148743  (0.5905950646847489)

   --> STEP: 33
     | > decoder_loss: 0.447869211435318  (0.4604840883702943)
     | > postnet_loss: 0.3036539852619171  (0.31270341259060486)
     | > stopnet_loss: 0.004152004607021809  (0.005786845150093238)
     | > loss: 0.1920327991247177  (0.19908372109586542)
     | > align_error: 0.5470464825630188  (0.58927541068106)

   --> STEP: 34
     | > decoder_loss: 0.4536105990409851  (0.46028192691943226)
     | > postnet_loss: 0.30583199858665466  (0.31250131217872396)
     | > stopnet_loss: 0.0035054790787398815  (0.005719746147994609)
     | > loss: 0.1933661252260208  (0.19891555651145823)
     | > align_error: 0.5644462704658508  (0.588545141851201)

   --> STEP: 35
     | > decoder_loss: 0.45145153999328613  (0.4600296301501138)
     | > postnet_loss: 0.3038763403892517  (0.31225488441331045)
     | > stopnet_loss: 0.003700511995702982  (0.0056620537436434205)
     | > loss: 0.192532479763031  (0.1987331828900746)
     | > align_error: 0.5352184176445007  (0.587021521159581)

   --> STEP: 36
     | > decoder_loss: 0.45809808373451233  (0.45997597608301377)
     | > postnet_loss: 0.30856239795684814  (0.31215231534507537)
     | > stopnet_loss: 0.0038669120986014605  (0.005612188697947811)
     | > loss: 0.19553202390670776  (0.1986442618072033)
     | > align_error: 0.6349653601646423  (0.5883532944652772)

   --> STEP: 37
     | > decoder_loss: 0.4495339095592499  (0.459693758068858)
     | > postnet_loss: 0.304491251707077  (0.31194525957107544)
     | > stopnet_loss: 0.003744928864762187  (0.005561722215969822)
     | > loss: 0.19225122034549713  (0.19847147690283284)
     | > align_error: 0.5200040340423584  (0.5865060171565496)

   --> STEP: 38
     | > decoder_loss: 0.43892642855644226  (0.4591472493974786)
     | > postnet_loss: 0.2985744774341583  (0.3115933968832618)
     | > stopnet_loss: 0.0032698526047170162  (0.005501409857778959)
     | > loss: 0.1876450777053833  (0.1981865716607947)
     | > align_error: 0.5520327091217041  (0.5855988248398432)

   --> STEP: 39
     | > decoder_loss: 0.4516794681549072  (0.45895576782715625)
     | > postnet_loss: 0.30657923221588135  (0.3114648285584572)
     | > stopnet_loss: 0.003631153842434287  (0.005453454575334223)
     | > loss: 0.19319583475589752  (0.19805860404784864)
     | > align_error: 0.5475586652755737  (0.584623436133067)

   --> STEP: 40
     | > decoder_loss: 0.44887927174568176  (0.4587038554251194)
     | > postnet_loss: 0.30519017577171326  (0.3113079622387886)
     | > stopnet_loss: 0.0031839413568377495  (0.005396716744871811)
     | > loss: 0.19170130789279938  (0.19789967164397243)
     | > align_error: 0.5853762626647949  (0.5846422567963602)

   --> STEP: 41
     | > decoder_loss: 0.43949049711227417  (0.45823523692968415)
     | > postnet_loss: 0.2975515127182007  (0.31097243907974986)
     | > stopnet_loss: 0.0038414818700402975  (0.005358784186949092)
     | > loss: 0.18810197710990906  (0.19766070348460504)
     | > align_error: 0.5052546262741089  (0.5827059731250858)

   --> STEP: 42
     | > decoder_loss: 0.4445992112159729  (0.45791056965078625)
     | > postnet_loss: 0.3012565076351166  (0.31074110737868715)
     | > stopnet_loss: 0.0034076524898409843  (0.0053123286703512795)
     | > loss: 0.18987157940864563  (0.19747524814946316)
     | > align_error: 0.5806191563606262  (0.5826562870116463)

   --> STEP: 43
     | > decoder_loss: 0.4431878626346588  (0.4575681811155275)
     | > postnet_loss: 0.30035388469696045  (0.31049954406050745)
     | > stopnet_loss: 0.0030718897469341755  (0.005260225439574138)
     | > loss: 0.1889573186635971  (0.1972771567660709)
     | > align_error: 0.5526486933231354  (0.5819584359956343)

   --> STEP: 44
     | > decoder_loss: 0.4609121084213257  (0.45764417946338654)
     | > postnet_loss: 0.3088947534561157  (0.3104630715467713)
     | > stopnet_loss: 0.0028465082868933678  (0.005205368231558666)
     | > loss: 0.1952982246875763  (0.19723218103701423)
     | > align_error: 0.5523921251296997  (0.581286474385045)

   --> STEP: 45
     | > decoder_loss: 0.45305904746055603  (0.4575422876411014)
     | > postnet_loss: 0.30770039558410645  (0.31040167874760094)
     | > stopnet_loss: 0.003497539320960641  (0.005167416477989821)
     | > loss: 0.19368740916252136  (0.19715340832869216)
     | > align_error: 0.5538113117218018  (0.5806759152147507)

   --> STEP: 46
     | > decoder_loss: 0.4451633095741272  (0.45727317942225415)
     | > postnet_loss: 0.2997802495956421  (0.3101707781138627)
     | > stopnet_loss: 0.003341476432979107  (0.00512772212918524)
     | > loss: 0.1895773708820343  (0.19698871186246047)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34316576610911975 (-0.028776959939436575)
     | > avg_decoder_loss: 0.452860870144584 (+0.0003011863340031118)
     | > avg_postnet_loss: 0.3065621830297238 (+0.0007147852218512551)
     | > avg_stopnet_loss: 0.004544458020422045 (-3.873705722842735e-06)
     | > avg_loss: 0.1944002217867158 (+0.0002501198288166473)
     | > avg_align_error: 0.573367171666839 (+0.0006760182705793927)


 > EPOCH: 13/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 22:25:32)

   --> TIME: 2025-12-27 22:25:50 -- STEP: 12/150 -- GLOBAL_STEP: 1975
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49839699268341064  (0.4875938718517621)
     | > postnet_loss: 0.42803603410720825  (0.42363186180591583)
     | > stopnet_loss: 0.009735137224197388  (0.012077227933332324)
     | > loss: 0.2413433939218521  (0.23988366251190504)
     | > align_error: 0.669016569852829  (0.6888361548384031)
     | > grad_norm: tensor(0.3101, device='cuda:0')  (tensor(0.3306, device='cuda:0'))
     | > step_time: 0.7109  (0.5445476571718851)
     | > loader_time: 0.8271  (0.8613917032877604)


   --> TIME: 2025-12-27 22:26:36 -- STEP: 37/150 -- GLOBAL_STEP: 2000
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.5030809044837952  (0.49388514902140646)
     | > postnet_loss: 0.42186933755874634  (0.42122573304820704)
     | > stopnet_loss: 0.005718184635043144  (0.008648471504047111)
     | > loss: 0.23695574700832367  (0.23742619358204506)
     | > align_error: 0.6232926547527313  (0.658991198281984)
     | > grad_norm: tensor(0.1795, device='cuda:0')  (tensor(0.2505, device='cuda:0'))
     | > step_time: 1.0052  (0.7670131953986915)
     | > loader_time: 1.0242  (0.9235919875067633)


   --> TIME: 2025-12-27 22:27:36 -- STEP: 62/150 -- GLOBAL_STEP: 2025
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5011226534843445  (0.49814961514165323)
     | > postnet_loss: 0.4144097566604614  (0.42069296346556756)
     | > stopnet_loss: 0.004082044120877981  (0.007126881756008635)
     | > loss: 0.2329651415348053  (0.23683752792496834)
     | > align_error: 0.5791759490966797  (0.6421210078462478)
     | > grad_norm: tensor(0.1786, device='cuda:0')  (tensor(0.2358, device='cuda:0'))
     | > step_time: 1.3965  (0.9578618349567536)
     | > loader_time: 1.1897  (1.0111548785240418)


   --> TIME: 2025-12-27 22:28:46 -- STEP: 87/150 -- GLOBAL_STEP: 2050
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49097344279289246  (0.49973562462576504)
     | > postnet_loss: 0.40766632556915283  (0.419948465865234)
     | > stopnet_loss: 0.0036262059584259987  (0.006260461104370054)
     | > loss: 0.22828616201877594  (0.23618148489930163)
     | > align_error: 0.6033413410186768  (0.6344646160629974)
     | > grad_norm: tensor(0.1651, device='cuda:0')  (tensor(0.2148, device='cuda:0'))
     | > step_time: 1.5762  (1.1047079234287656)
     | > loader_time: 1.5125  (1.1076744644121193)


   --> TIME: 2025-12-27 22:30:10 -- STEP: 112/150 -- GLOBAL_STEP: 2075
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4961046874523163  (0.5004987445260796)
     | > postnet_loss: 0.41139835119247437  (0.4194171495203462)
     | > stopnet_loss: 0.0038307346403598785  (0.0056896926544141024)
     | > loss: 0.23070648312568665  (0.23566866759210825)
     | > align_error: 0.6414933800697327  (0.6296368861304862)
     | > grad_norm: tensor(0.1144, device='cuda:0')  (tensor(0.2039, device='cuda:0'))
     | > step_time: 1.641  (1.2371643739087246)
     | > loader_time: 1.6883  (1.2324873017413278)


   --> TIME: 2025-12-27 22:31:44 -- STEP: 137/150 -- GLOBAL_STEP: 2100
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5158964395523071  (0.5012678678018333)
     | > postnet_loss: 0.4209459722042084  (0.4185940451430579)
     | > stopnet_loss: 0.0031014205887913704  (0.005262714008508373)
     | > loss: 0.23731203377246857  (0.23522819339358894)
     | > align_error: 0.599517434835434  (0.6264951727251067)
     | > grad_norm: tensor(0.1947, device='cuda:0')  (tensor(0.1976, device='cuda:0'))
     | > step_time: 2.1287  (1.3629604151649202)
     | > loader_time: 2.3314  (1.3423892668563957)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4759608507156372  (0.4759608507156372)
     | > postnet_loss: 0.335367351770401  (0.335367351770401)
     | > stopnet_loss: 0.012514114379882812  (0.012514114379882812)
     | > loss: 0.21534615755081177  (0.21534615755081177)
     | > align_error: 0.7194607555866241  (0.7194607555866241)

   --> STEP: 1
     | > decoder_loss: 0.4593285024166107  (0.4593285024166107)
     | > postnet_loss: 0.32226479053497314  (0.32226479053497314)
     | > stopnet_loss: 0.009919879958033562  (0.009919879958033562)
     | > loss: 0.20531821250915527  (0.20531821250915527)
     | > align_error: 0.6606336832046509  (0.6606336832046509)

   --> STEP: 2
     | > decoder_loss: 0.4526972770690918  (0.45601288974285126)
     | > postnet_loss: 0.3168874979019165  (0.3195761442184448)
     | > stopnet_loss: 0.011177437379956245  (0.010548658668994904)
     | > loss: 0.20357362926006317  (0.20444592088460922)
     | > align_error: 0.6586610078811646  (0.6596473455429077)

   --> STEP: 3
     | > decoder_loss: 0.45436832308769226  (0.4554647008577983)
     | > postnet_loss: 0.31347396969795227  (0.3175420860449473)
     | > stopnet_loss: 0.008712505921721458  (0.009936607753237089)
     | > loss: 0.20067307353019714  (0.2031883050998052)
     | > align_error: 0.7367580235004425  (0.6853509048620859)

   --> STEP: 4
     | > decoder_loss: 0.46619847416877747  (0.45814814418554306)
     | > postnet_loss: 0.3243872821331024  (0.3192533850669861)
     | > stopnet_loss: 0.008473454043269157  (0.009570819325745106)
     | > loss: 0.20611989498138428  (0.20392120257019997)
     | > align_error: 0.6062902808189392  (0.6655857488512993)

   --> STEP: 5
     | > decoder_loss: 0.4458155333995819  (0.45568162202835083)
     | > postnet_loss: 0.3073323965072632  (0.3168691873550415)
     | > stopnet_loss: 0.00842486321926117  (0.00934162810444832)
     | > loss: 0.19671185314655304  (0.20247933268547058)
     | > align_error: 0.6444489359855652  (0.6613583862781525)

   --> STEP: 6
     | > decoder_loss: 0.4619047939777374  (0.4567188173532486)
     | > postnet_loss: 0.3171223998069763  (0.31691138943036395)
     | > stopnet_loss: 0.0074335443787276745  (0.009023614150161544)
     | > loss: 0.2021903544664383  (0.2024311696489652)
     | > align_error: 0.5963864922523499  (0.650529737273852)

   --> STEP: 7
     | > decoder_loss: 0.4695541560649872  (0.45855243716921124)
     | > postnet_loss: 0.3169030249118805  (0.31691019449915203)
     | > stopnet_loss: 0.006610619369894266  (0.008678900610123361)
     | > loss: 0.20322491228580475  (0.202544561454228)
     | > align_error: 0.581660121679306  (0.6406912207603455)

   --> STEP: 8
     | > decoder_loss: 0.4660285413265228  (0.4594869501888752)
     | > postnet_loss: 0.31696924567222595  (0.3169175758957863)
     | > stopnet_loss: 0.007662797346711159  (0.008551887702196836)
     | > loss: 0.2034122496843338  (0.20265302248299122)
     | > align_error: 0.5781909227371216  (0.6328786835074425)

   --> STEP: 9
     | > decoder_loss: 0.4653520882129669  (0.46013863219155204)
     | > postnet_loss: 0.32002076506614685  (0.317262374692493)
     | > stopnet_loss: 0.006848776713013649  (0.008362653147843149)
     | > loss: 0.20319199562072754  (0.20271290838718414)
     | > align_error: 0.5947102904319763  (0.6286377509435018)

   --> STEP: 10
     | > decoder_loss: 0.4949786067008972  (0.4636226296424866)
     | > postnet_loss: 0.33360323309898376  (0.3188964605331421)
     | > stopnet_loss: 0.005891491658985615  (0.008115536998957396)
     | > loss: 0.2130369395017624  (0.20374531149864197)
     | > align_error: 0.5889707207679749  (0.6246710479259491)

   --> STEP: 11
     | > decoder_loss: 0.4773847758769989  (0.4648737338456241)
     | > postnet_loss: 0.3252641558647156  (0.3194753419269215)
     | > stopnet_loss: 0.0060019236989319324  (0.007923390335318718)
     | > loss: 0.20666414499282837  (0.20401065999811346)
     | > align_error: 0.5965899229049683  (0.6221182183785872)

   --> STEP: 12
     | > decoder_loss: 0.4712354838848114  (0.465403879682223)
     | > postnet_loss: 0.3166973292827606  (0.3192438408732414)
     | > stopnet_loss: 0.008135664276778698  (0.007941079830440383)
     | > loss: 0.20511886477470398  (0.20410301039616266)
     | > align_error: 0.5900745987892151  (0.6194479167461395)

   --> STEP: 13
     | > decoder_loss: 0.4634777307510376  (0.4652557143798241)
     | > postnet_loss: 0.3175879120826721  (0.31911646173550534)
     | > stopnet_loss: 0.005761587992310524  (0.007773426612122701)
     | > loss: 0.2010280042886734  (0.20386647146481734)
     | > align_error: 0.5887443721294403  (0.617086105621778)

   --> STEP: 14
     | > decoder_loss: 0.4666859209537506  (0.46535787199224743)
     | > postnet_loss: 0.31619003415107727  (0.31890743119376047)
     | > stopnet_loss: 0.005116705317050219  (0.00758366080533181)
     | > loss: 0.2008356899023056  (0.20364998706749507)
     | > align_error: 0.5563569068908691  (0.6127483057124274)

   --> STEP: 15
     | > decoder_loss: 0.4717850983142853  (0.46578635374704996)
     | > postnet_loss: 0.3237219452857971  (0.31922839879989623)
     | > stopnet_loss: 0.005138657055795193  (0.007420660555362702)
     | > loss: 0.20401541888713837  (0.20367434918880462)
     | > align_error: 0.5903993844985962  (0.6112583776315054)

   --> STEP: 16
     | > decoder_loss: 0.4698333442211151  (0.46603929065167904)
     | > postnet_loss: 0.3145284652709961  (0.31893465295434)
     | > stopnet_loss: 0.005299004726111889  (0.0072880570660345265)
     | > loss: 0.20138946175575256  (0.20353154372423887)
     | > align_error: 0.6082575917243958  (0.611070828512311)

   --> STEP: 17
     | > decoder_loss: 0.47818946838378906  (0.466754006988862)
     | > postnet_loss: 0.325930655002594  (0.3193461824865902)
     | > stopnet_loss: 0.005008874461054802  (0.0071539875010357195)
     | > loss: 0.20603890717029572  (0.203679035691654)
     | > align_error: 0.5601587295532227  (0.6080759991617763)

   --> STEP: 18
     | > decoder_loss: 0.47284457087516785  (0.4670923716492123)
     | > postnet_loss: 0.3177674114704132  (0.3192584729856915)
     | > stopnet_loss: 0.005560292396694422  (0.007065448884127868)
     | > loss: 0.20321328938007355  (0.20365316089656618)
     | > align_error: 0.6052566170692444  (0.6079193668233024)

   --> STEP: 19
     | > decoder_loss: 0.4737323522567749  (0.46744184431276825)
     | > postnet_loss: 0.3182961642742157  (0.3192078251587717)
     | > stopnet_loss: 0.005094014108181  (0.006961689159078033)
     | > loss: 0.20310115814208984  (0.2036241081200148)
     | > align_error: 0.6029270589351654  (0.6076566137765583)

   --> STEP: 20
     | > decoder_loss: 0.4662345051765442  (0.46738147735595703)
     | > postnet_loss: 0.31514620780944824  (0.31900474429130554)
     | > stopnet_loss: 0.004681576043367386  (0.006847683503292501)
     | > loss: 0.2000267505645752  (0.2034442402422428)
     | > align_error: 0.6238477230072021  (0.6084661692380905)

   --> STEP: 21
     | > decoder_loss: 0.4644043743610382  (0.4672397105466752)
     | > postnet_loss: 0.31106439232826233  (0.31862663229306537)
     | > stopnet_loss: 0.0041588470339775085  (0.0067196436714203585)
     | > loss: 0.19802603125572205  (0.20318623029050373)
     | > align_error: 0.5627806186676025  (0.606290666829972)

   --> STEP: 22
     | > decoder_loss: 0.4673004448413849  (0.4672424711964347)
     | > postnet_loss: 0.3154468238353729  (0.31848209554498846)
     | > stopnet_loss: 0.005058187525719404  (0.00664412293752486)
     | > loss: 0.20074500143527985  (0.203075265342539)
     | > align_error: 0.6268191933631897  (0.607223781672391)

   --> STEP: 23
     | > decoder_loss: 0.4368344843387604  (0.4659203848113184)
     | > postnet_loss: 0.3032369315624237  (0.3178192623283552)
     | > stopnet_loss: 0.004711946938186884  (0.006560115285379731)
     | > loss: 0.18972979485988617  (0.20249502749546713)
     | > align_error: 0.567791223526001  (0.605509322622548)

   --> STEP: 24
     | > decoder_loss: 0.47268903255462646  (0.46620241180062294)
     | > postnet_loss: 0.31953728199005127  (0.31789084648092586)
     | > stopnet_loss: 0.004559291992336512  (0.006476747648169597)
     | > loss: 0.2026158720254898  (0.20250006268421808)
     | > align_error: 0.581413745880127  (0.6045053402582804)

   --> STEP: 25
     | > decoder_loss: 0.4726755917072296  (0.4664613389968872)
     | > postnet_loss: 0.31617987155914307  (0.31782240748405455)
     | > stopnet_loss: 0.0038253951352089643  (0.006370693547651172)
     | > loss: 0.20103925466537476  (0.20244163036346435)
     | > align_error: 0.5603424608707428  (0.602738825082779)

   --> STEP: 26
     | > decoder_loss: 0.4459000527858734  (0.4656705202964636)
     | > postnet_loss: 0.30280277132987976  (0.31724472917043245)
     | > stopnet_loss: 0.004594165366142988  (0.006302365540670088)
     | > loss: 0.19176986813545227  (0.20203117797007927)
     | > align_error: 0.5492644011974335  (0.6006821164718041)

   --> STEP: 27
     | > decoder_loss: 0.4451238214969635  (0.46490953145203767)
     | > postnet_loss: 0.3022143840789795  (0.31668804972260084)
     | > stopnet_loss: 0.004033792298287153  (0.00621834430947072)
     | > loss: 0.1908683329820633  (0.20161773926681942)
     | > align_error: 0.542935848236084  (0.5985433657964071)

   --> STEP: 28
     | > decoder_loss: 0.44880926609039307  (0.4643345219748361)
     | > postnet_loss: 0.3039025664329529  (0.31623142531939913)
     | > stopnet_loss: 0.004056533798575401  (0.0061411367912244585)
     | > loss: 0.19223448634147644  (0.20128262309091433)
     | > align_error: 0.5671595931053162  (0.5974225167717252)

   --> STEP: 29
     | > decoder_loss: 0.4446171820163727  (0.4636546137004063)
     | > postnet_loss: 0.29977238178253174  (0.31566387209398994)
     | > stopnet_loss: 0.0037755502853542566  (0.006059564842746176)
     | > loss: 0.18987293541431427  (0.20088918558482466)
     | > align_error: 0.5420495271682739  (0.5955131033371235)

   --> STEP: 30
     | > decoder_loss: 0.4435621500015259  (0.4629848649104436)
     | > postnet_loss: 0.30016326904296875  (0.3151471853256226)
     | > stopnet_loss: 0.003054650267586112  (0.0059594010235741735)
     | > loss: 0.18898600339889526  (0.20049241284529368)
     | > align_error: 0.5350678563117981  (0.5934982617696126)

   --> STEP: 31
     | > decoder_loss: 0.4425605535507202  (0.46232601615690416)
     | > postnet_loss: 0.3026348948478699  (0.3147435630521467)
     | > stopnet_loss: 0.004110324662178755  (0.005899753399013031)
     | > loss: 0.19040918350219727  (0.20016714738261315)
     | > align_error: 0.5608137845993042  (0.5924439237963769)

   --> STEP: 32
     | > decoder_loss: 0.4496401250362396  (0.4619295820593834)
     | > postnet_loss: 0.3052545487880707  (0.3144470313563943)
     | > stopnet_loss: 0.004057451616972685  (0.00584218146832427)
     | > loss: 0.19278112053871155  (0.19993633404374123)
     | > align_error: 0.5324839353561401  (0.5905701741576195)

   --> STEP: 33
     | > decoder_loss: 0.4482763111591339  (0.4615158465775577)
     | > postnet_loss: 0.3047870695590973  (0.3141543052413247)
     | > stopnet_loss: 0.004162995610386133  (0.005791297048386751)
     | > loss: 0.1924288421869278  (0.19970883429050446)
     | > align_error: 0.5468204021453857  (0.589244423490582)

   --> STEP: 34
     | > decoder_loss: 0.4540007412433624  (0.4612948140677284)
     | > postnet_loss: 0.30699750781059265  (0.3139438111992443)
     | > stopnet_loss: 0.0035096430219709873  (0.005724189577021581)
     | > loss: 0.19375920295715332  (0.1995338451336412)
     | > align_error: 0.5643659830093384  (0.5885127046528984)

   --> STEP: 35
     | > decoder_loss: 0.45096564292907715  (0.46099969489233833)
     | > postnet_loss: 0.3044646978378296  (0.3136729793889182)
     | > stopnet_loss: 0.0037090496625751257  (0.005666614150894539)
     | > loss: 0.1925666332244873  (0.1993347819362368)
     | > align_error: 0.5351694226264954  (0.5869886108807155)

   --> STEP: 36
     | > decoder_loss: 0.45899030566215515  (0.46094387852483326)
     | > postnet_loss: 0.30986639857292175  (0.3135672410329183)
     | > stopnet_loss: 0.0038676573894917965  (0.005616643129744464)
     | > loss: 0.19608183205127716  (0.19924442221721014)
     | > align_error: 0.6349815130233765  (0.588321747051345)

   --> STEP: 37
     | > decoder_loss: 0.44957444071769714  (0.46063659642193766)
     | > postnet_loss: 0.30548709630966187  (0.31334885874310053)
     | > stopnet_loss: 0.0037612703163176775  (0.0055664979185707664)
     | > loss: 0.1925266534090042  (0.19906286089806943)
     | > align_error: 0.5199178457260132  (0.5864729929614712)

   --> STEP: 38
     | > decoder_loss: 0.4385986030101776  (0.4600566492268914)
     | > postnet_loss: 0.2993108034133911  (0.312979436234424)
     | > stopnet_loss: 0.0032757369335740805  (0.005506214734755065)
     | > loss: 0.1877530962228775  (0.19876523551188016)
     | > align_error: 0.5518814921379089  (0.5855626903082195)

   --> STEP: 39
     | > decoder_loss: 0.45133253931999207  (0.45983295410107344)
     | > postnet_loss: 0.30723923444747925  (0.31283225157322025)
     | > stopnet_loss: 0.003638504771515727  (0.005458324735697646)
     | > loss: 0.19328144192695618  (0.19862462541995904)
     | > align_error: 0.5474293231964111  (0.584584911664327)

   --> STEP: 40
     | > decoder_loss: 0.4487111568450928  (0.4595549091696739)
     | > postnet_loss: 0.3060791492462158  (0.31266342401504515)
     | > stopnet_loss: 0.003198313293978572  (0.005401824449654669)
     | > loss: 0.19189588725566864  (0.1984564069658518)
     | > align_error: 0.5851238369941711  (0.5845983847975731)

   --> STEP: 41
     | > decoder_loss: 0.43920058012008667  (0.459058462119684)
     | > postnet_loss: 0.2983081638813019  (0.3123132957191002)
     | > stopnet_loss: 0.0038406257517635822  (0.005363746432632935)
     | > loss: 0.18821781873703003  (0.1982066853017342)
     | > align_error: 0.5053187012672424  (0.5826647339797602)

   --> STEP: 42
     | > decoder_loss: 0.44467130303382874  (0.45871591071287793)
     | > postnet_loss: 0.30211877822875977  (0.31207056911218733)
     | > stopnet_loss: 0.003414504462853074  (0.005317335909542938)
     | > loss: 0.19011202454566956  (0.19801395528373264)
     | > align_error: 0.5807222723960876  (0.5826184848944346)

   --> STEP: 43
     | > decoder_loss: 0.44348329305648804  (0.4583616637906363)
     | > postnet_loss: 0.3013312518596649  (0.3118208175481752)
     | > stopnet_loss: 0.0030725288670510054  (0.005265131094601265)
     | > loss: 0.18927615880966187  (0.19781075071456822)
     | > align_error: 0.5526542663574219  (0.5819216426028762)

   --> STEP: 44
     | > decoder_loss: 0.4608669877052307  (0.45841860297051346)
     | > postnet_loss: 0.3097025752067566  (0.3117726756767793)
     | > stopnet_loss: 0.002838526153936982  (0.005209980982313441)
     | > loss: 0.19548091292381287  (0.1977577998556874)
     | > align_error: 0.5523137152194977  (0.5812487351623449)

   --> STEP: 45
     | > decoder_loss: 0.4528169631958008  (0.45829412208663095)
     | > postnet_loss: 0.30834686756134033  (0.3116965466075473)
     | > stopnet_loss: 0.0034858770668506622  (0.0051716675619698236)
     | > loss: 0.19377683103084564  (0.19766933388180202)
     | > align_error: 0.5537223219871521  (0.580637037091785)

   --> STEP: 46
     | > decoder_loss: 0.4448801577091217  (0.45800251416538074)
     | > postnet_loss: 0.30040407180786133  (0.31145105802494544)
     | > stopnet_loss: 0.0033442454878240824  (0.005131940995140568)
     | > loss: 0.1896653026342392  (0.19749533320250717)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3723514369039824 (+0.029185670794862673)
     | > avg_decoder_loss: 0.4531313469915679 (+0.0002704768469838914)
     | > avg_postnet_loss: 0.307515190406279 (+0.0009530073765551816)
     | > avg_stopnet_loss: 0.004549160606764031 (+4.702586341986774e-06)
     | > avg_loss: 0.19471079449761997 (+0.0003105727109041778)
     | > avg_align_error: 0.573280137145158 (-8.703452168101755e-05)


 > EPOCH: 14/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 22:34:38)

   --> TIME: 2025-12-27 22:34:54 -- STEP: 11/150 -- GLOBAL_STEP: 2125
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49243268370628357  (0.4856687811287967)
     | > postnet_loss: 0.4219842255115509  (0.4219004593112252)
     | > stopnet_loss: 0.009532063268125057  (0.012251285751434889)
     | > loss: 0.23813629150390625  (0.23914359509944916)
     | > align_error: 0.6725079715251923  (0.6911809363148429)
     | > grad_norm: tensor(0.2563, device='cuda:0')  (tensor(0.2888, device='cuda:0'))
     | > step_time: 0.6499  (0.5036013993349943)
     | > loader_time: 0.8588  (0.8305928273634477)


   --> TIME: 2025-12-27 22:35:39 -- STEP: 36/150 -- GLOBAL_STEP: 2150
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.507477879524231  (0.4931647189789348)
     | > postnet_loss: 0.4251728951931  (0.42080308083030915)
     | > stopnet_loss: 0.006043013650923967  (0.008667087014247146)
     | > loss: 0.2392057180404663  (0.23715903692775303)
     | > align_error: 0.6198238730430603  (0.6607687970002493)
     | > grad_norm: tensor(0.2036, device='cuda:0')  (tensor(0.2611, device='cuda:0'))
     | > step_time: 1.0834  (0.7473510503768921)
     | > loader_time: 0.9796  (0.920500291718377)


   --> TIME: 2025-12-27 22:36:38 -- STEP: 61/150 -- GLOBAL_STEP: 2175
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5016733407974243  (0.4974489544258743)
     | > postnet_loss: 0.41644901037216187  (0.42024939910310216)
     | > stopnet_loss: 0.004462271463125944  (0.0071372737970630635)
     | > loss: 0.23399285972118378  (0.23656186217167338)
     | > align_error: 0.6073389649391174  (0.6435047866868191)
     | > grad_norm: tensor(0.1729, device='cuda:0')  (tensor(0.2435, device='cuda:0'))
     | > step_time: 1.3965  (0.9362055903575459)
     | > loader_time: 1.2703  (1.0059207697383692)


   --> TIME: 2025-12-27 22:37:49 -- STEP: 86/150 -- GLOBAL_STEP: 2200
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4997485280036926  (0.4992474418046863)
     | > postnet_loss: 0.416029691696167  (0.4195492891378181)
     | > stopnet_loss: 0.0038431237917393446  (0.006249298839721569)
     | > loss: 0.23278768360614777  (0.2359484822251076)
     | > align_error: 0.5821858644485474  (0.6354221642710443)
     | > grad_norm: tensor(0.2286, device='cuda:0')  (tensor(0.2240, device='cuda:0'))
     | > step_time: 1.435  (1.0879953378854799)
     | > loader_time: 1.6474  (1.118808516236239)


   --> TIME: 2025-12-27 22:39:17 -- STEP: 111/150 -- GLOBAL_STEP: 2225
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4919096529483795  (0.4999205778847944)
     | > postnet_loss: 0.40849652886390686  (0.4188636079564825)
     | > stopnet_loss: 0.0036633380223065615  (0.005674424690303502)
     | > loss: 0.2287648767232895  (0.2353704718050656)
     | > align_error: 0.582264244556427  (0.6300604960939907)
     | > grad_norm: tensor(0.1171, device='cuda:0')  (tensor(0.2072, device='cuda:0'))
     | > step_time: 1.624  (1.2112439237199388)
     | > loader_time: 1.8499  (1.288632304818781)


   --> TIME: 2025-12-27 22:40:50 -- STEP: 136/150 -- GLOBAL_STEP: 2250
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5059539675712585  (0.5006221841801616)
     | > postnet_loss: 0.4150618314743042  (0.418041174464366)
     | > stopnet_loss: 0.003300668438896537  (0.00525110131745939)
     | > loss: 0.23355461657047272  (0.23491694153670006)
     | > align_error: 0.600971519947052  (0.6269722960012801)
     | > grad_norm: tensor(0.2866, device='cuda:0')  (tensor(0.1990, device='cuda:0'))
     | > step_time: 2.0776  (1.3331946818267597)
     | > loader_time: 1.784  (1.3896166454343237)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47617197036743164  (0.47617197036743164)
     | > postnet_loss: 0.33536121249198914  (0.33536121249198914)
     | > stopnet_loss: 0.012519004754722118  (0.012519004754722118)
     | > loss: 0.21540230512619019  (0.21540230512619019)
     | > align_error: 0.7198631763458252  (0.7198631763458252)

   --> STEP: 1
     | > decoder_loss: 0.4577628970146179  (0.4577628970146179)
     | > postnet_loss: 0.32108190655708313  (0.32108190655708313)
     | > stopnet_loss: 0.009886661544442177  (0.009886661544442177)
     | > loss: 0.20459787547588348  (0.20459787547588348)
     | > align_error: 0.660915732383728  (0.660915732383728)

   --> STEP: 2
     | > decoder_loss: 0.4512958526611328  (0.45452937483787537)
     | > postnet_loss: 0.31571507453918457  (0.31839849054813385)
     | > stopnet_loss: 0.011182875372469425  (0.010534768458455801)
     | > loss: 0.2029356062412262  (0.20376674085855484)
     | > align_error: 0.6587491631507874  (0.6598324477672577)

   --> STEP: 3
     | > decoder_loss: 0.45306098461151123  (0.45403991142908734)
     | > postnet_loss: 0.31175994873046875  (0.3161856432755788)
     | > stopnet_loss: 0.008704478852450848  (0.009924671923120817)
     | > loss: 0.19990971684455872  (0.2024810661872228)
     | > align_error: 0.7362920641899109  (0.6853189865748087)

   --> STEP: 4
     | > decoder_loss: 0.46349984407424927  (0.4564048945903778)
     | > postnet_loss: 0.32261088490486145  (0.3177919536828995)
     | > stopnet_loss: 0.008462159894406796  (0.009559043915942311)
     | > loss: 0.20498985052108765  (0.203108262270689)
     | > align_error: 0.6063775420188904  (0.6655836254358292)

   --> STEP: 5
     | > decoder_loss: 0.44374316930770874  (0.453872549533844)
     | > postnet_loss: 0.3058534562587738  (0.31540425419807433)
     | > stopnet_loss: 0.00841474998742342  (0.009330185130238533)
     | > loss: 0.19581389427185059  (0.20164938867092133)
     | > align_error: 0.6445257067680359  (0.6613720417022705)

   --> STEP: 6
     | > decoder_loss: 0.4595404863357544  (0.4548172056674957)
     | > postnet_loss: 0.3152363896369934  (0.31537627677122754)
     | > stopnet_loss: 0.00742540555074811  (0.009012721866990129)
     | > loss: 0.20111963152885437  (0.20156109581391016)
     | > align_error: 0.5964063405990601  (0.6505444248517355)

   --> STEP: 7
     | > decoder_loss: 0.46639513969421387  (0.4564711962427412)
     | > postnet_loss: 0.31439289450645447  (0.31523579359054565)
     | > stopnet_loss: 0.006597406230866909  (0.008667676776115383)
     | > loss: 0.20179441571235657  (0.20159442722797394)
     | > align_error: 0.581677109003067  (0.6407062368733543)

   --> STEP: 8
     | > decoder_loss: 0.4629668891429901  (0.4572831578552723)
     | > postnet_loss: 0.31463390588760376  (0.3151605576276779)
     | > stopnet_loss: 0.0076762414537370205  (0.008543747360818088)
     | > loss: 0.20207643508911133  (0.2016546782106161)
     | > align_error: 0.5778410136699677  (0.6328480839729309)

   --> STEP: 9
     | > decoder_loss: 0.45985138416290283  (0.4575685163338979)
     | > postnet_loss: 0.3154972195625305  (0.3151979645093282)
     | > stopnet_loss: 0.006841208320111036  (0.008354576356295083)
     | > loss: 0.20067836344242096  (0.20154619879192776)
     | > align_error: 0.5947404503822327  (0.6286139024628533)

   --> STEP: 10
     | > decoder_loss: 0.4907682240009308  (0.4608884871006012)
     | > postnet_loss: 0.330538272857666  (0.31673199534416197)
     | > stopnet_loss: 0.005895133595913649  (0.00810863208025694)
     | > loss: 0.21122175455093384  (0.20251375436782837)
     | > align_error: 0.5892213582992554  (0.6246746480464935)

   --> STEP: 11
     | > decoder_loss: 0.47456094622612  (0.4621314379301938)
     | > postnet_loss: 0.32271426916122437  (0.31727583841844037)
     | > stopnet_loss: 0.005999832879751921  (0.00791692306202921)
     | > loss: 0.2053186297416687  (0.2027687430381775)
     | > align_error: 0.596634715795517  (0.6221255632964048)

   --> STEP: 12
     | > decoder_loss: 0.4675554037094116  (0.46258343507846195)
     | > postnet_loss: 0.31349533796310425  (0.31696079671382904)
     | > stopnet_loss: 0.00802823156118393  (0.007926198770292102)
     | > loss: 0.2032909095287323  (0.20281225691239038)
     | > align_error: 0.5903278887271881  (0.6194757570823034)

   --> STEP: 13
     | > decoder_loss: 0.46057671308517456  (0.4624290718482091)
     | > postnet_loss: 0.3151586353778839  (0.31682216891875636)
     | > stopnet_loss: 0.005761096253991127  (0.007759652422884334)
     | > loss: 0.1996949464082718  (0.20257246379668897)
     | > align_error: 0.5888915061950684  (0.61712312239867)

   --> STEP: 14
     | > decoder_loss: 0.4647170603275299  (0.462592499596732)
     | > postnet_loss: 0.31427979469299316  (0.31664057075977325)
     | > stopnet_loss: 0.005143870133906603  (0.0075728108308144955)
     | > loss: 0.1998930722475052  (0.20238107868603297)
     | > align_error: 0.556571364402771  (0.6127979968275342)

   --> STEP: 15
     | > decoder_loss: 0.46746325492858887  (0.4629172166188558)
     | > postnet_loss: 0.320384681224823  (0.3168901781241099)
     | > stopnet_loss: 0.005139222368597984  (0.007410571600000062)
     | > loss: 0.2021012008190155  (0.20236242016156514)
     | > align_error: 0.5903884172439575  (0.6113040248552958)

   --> STEP: 16
     | > decoder_loss: 0.46654585003852844  (0.46314400620758533)
     | > postnet_loss: 0.31187963485717773  (0.31657701916992664)
     | > stopnet_loss: 0.005276189651340246  (0.007277172728208823)
     | > loss: 0.19988255202770233  (0.20220742840319872)
     | > align_error: 0.6083545088768005  (0.6111196801066399)

   --> STEP: 17
     | > decoder_loss: 0.47568175196647644  (0.4638815206639907)
     | > postnet_loss: 0.3232884109020233  (0.3169718069188735)
     | > stopnet_loss: 0.00499444967135787  (0.007142894901335238)
     | > loss: 0.20473699271678925  (0.20235622630399816)
     | > align_error: 0.5605089962482452  (0.608142581056146)

   --> STEP: 18
     | > decoder_loss: 0.47065865993499756  (0.46425802840126884)
     | > postnet_loss: 0.31535664200782776  (0.31688207553492653)
     | > stopnet_loss: 0.005566751584410667  (0.007055331383728317)
     | > loss: 0.20207056403160095  (0.20234035617775387)
     | > align_error: 0.6057315170764923  (0.6080086330572764)

   --> STEP: 19
     | > decoder_loss: 0.4705001711845398  (0.4645865622319673)
     | > postnet_loss: 0.3149574100971222  (0.31678077735398946)
     | > stopnet_loss: 0.005031522363424301  (0.00694881511950179)
     | > loss: 0.2013959288597107  (0.20229064947680422)
     | > align_error: 0.6030493974685669  (0.6077476206578707)

   --> STEP: 20
     | > decoder_loss: 0.46433570981025696  (0.4645740196108818)
     | > postnet_loss: 0.31284046173095703  (0.31658376157283785)
     | > stopnet_loss: 0.004663487896323204  (0.006834548758342861)
     | > loss: 0.19895751774311066  (0.20212399289011956)
     | > align_error: 0.6244359612464905  (0.6085820376873017)

   --> STEP: 21
     | > decoder_loss: 0.46204066276550293  (0.46445338357062566)
     | > postnet_loss: 0.3086853623390198  (0.3162076473236084)
     | > stopnet_loss: 0.004147437866777182  (0.006706591096839733)
     | > loss: 0.1968289464712143  (0.20187184782255263)
     | > align_error: 0.5629428327083588  (0.6064087422121138)

   --> STEP: 22
     | > decoder_loss: 0.4641791880130768  (0.46444092013619165)
     | > postnet_loss: 0.3127400875091553  (0.316050030968406)
     | > stopnet_loss: 0.0050390735268592834  (0.006630794843658804)
     | > loss: 0.1992688775062561  (0.2017535309899937)
     | > align_error: 0.6274176239967346  (0.607363691384142)

   --> STEP: 23
     | > decoder_loss: 0.43547341227531433  (0.46318146327267523)
     | > postnet_loss: 0.3013657033443451  (0.3154115819412729)
     | > stopnet_loss: 0.004701143596321344  (0.006546896963339784)
     | > loss: 0.18891091644763947  (0.20119515644467395)
     | > align_error: 0.5684242844581604  (0.605670673691708)

   --> STEP: 24
     | > decoder_loss: 0.47002601623535156  (0.4634666529794534)
     | > postnet_loss: 0.3168506920337677  (0.3154715448617935)
     | > stopnet_loss: 0.004545185249298811  (0.0064634923085880765)
     | > loss: 0.20126435160636902  (0.20119803957641125)
     | > align_error: 0.5816309452056885  (0.6046690183381239)

   --> STEP: 25
     | > decoder_loss: 0.47025883197784424  (0.463738340139389)
     | > postnet_loss: 0.3136589229106903  (0.3153990399837494)
     | > stopnet_loss: 0.0038142192643135786  (0.006357521386817096)
     | > loss: 0.19979366660118103  (0.20114186465740203)
     | > align_error: 0.5608568787574768  (0.6029165327548981)

   --> STEP: 26
     | > decoder_loss: 0.44485875964164734  (0.46301220242793745)
     | > postnet_loss: 0.3012158274650574  (0.31485353180995357)
     | > stopnet_loss: 0.0045943232253193855  (0.0062897060729133385)
     | > loss: 0.1911129653453827  (0.2007561377607859)
     | > align_error: 0.5495812892913818  (0.6008651772370706)

   --> STEP: 27
     | > decoder_loss: 0.4412473738193512  (0.4622060976646565)
     | > postnet_loss: 0.29859599471092224  (0.3142514008062857)
     | > stopnet_loss: 0.004052363336086273  (0.0062068415271049285)
     | > loss: 0.18901321291923523  (0.20032121461850624)
     | > align_error: 0.5437373518943787  (0.5987493318540079)

   --> STEP: 28
     | > decoder_loss: 0.44709113240242004  (0.46166627747671946)
     | > postnet_loss: 0.30168643593788147  (0.31380265206098557)
     | > stopnet_loss: 0.004049350041896105  (0.006129788259776042)
     | > loss: 0.1912437379360199  (0.19999701902270317)
     | > align_error: 0.5679253041744232  (0.5976484737225941)

   --> STEP: 29
     | > decoder_loss: 0.4430118799209595  (0.4610230223885898)
     | > postnet_loss: 0.2975699305534363  (0.31324290304348384)
     | > stopnet_loss: 0.0037384319584816694  (0.006047327697662443)
     | > loss: 0.18888388574123383  (0.19961380753023872)
     | > align_error: 0.5426754951477051  (0.5957528537717359)

   --> STEP: 30
     | > decoder_loss: 0.44257181882858276  (0.4604079822699229)
     | > postnet_loss: 0.2984378933906555  (0.3127494027217229)
     | > stopnet_loss: 0.0030771701131016016  (0.0059483224448437485)
     | > loss: 0.18832959234714508  (0.1992376670241356)
     | > align_error: 0.535792350769043  (0.5937541703383128)

   --> STEP: 31
     | > decoder_loss: 0.4415309727191925  (0.4597990464779638)
     | > postnet_loss: 0.3007296919822693  (0.31236167011722443)
     | > stopnet_loss: 0.004105507396161556  (0.005888876798112065)
     | > loss: 0.18967068195343018  (0.19892905460249993)
     | > align_error: 0.5614525079727173  (0.5927121812297452)

   --> STEP: 32
     | > decoder_loss: 0.4492828845977783  (0.45947041641920805)
     | > postnet_loss: 0.3035506308078766  (0.3120863251388073)
     | > stopnet_loss: 0.004043037537485361  (0.00583119432121748)
     | > loss: 0.19225141406059265  (0.19872037833556533)
     | > align_error: 0.5332378149032593  (0.5908536072820425)

   --> STEP: 33
     | > decoder_loss: 0.44667649269104004  (0.4590827217607787)
     | > postnet_loss: 0.3024369180202484  (0.3117939188624873)
     | > stopnet_loss: 0.004146210383623838  (0.005780134201896461)
     | > loss: 0.19142456352710724  (0.19849929303833933)
     | > align_error: 0.5477592945098877  (0.5895477190162196)

   --> STEP: 34
     | > decoder_loss: 0.45230475068092346  (0.4588833696701947)
     | > postnet_loss: 0.30444684624671936  (0.31157782849143534)
     | > stopnet_loss: 0.003501950530335307  (0.005713128799791721)
     | > loss: 0.19268985092639923  (0.1983284270938705)
     | > align_error: 0.56540247797966  (0.5888375648680855)

   --> STEP: 35
     | > decoder_loss: 0.44980868697166443  (0.4586240930216653)
     | > postnet_loss: 0.302385538816452  (0.3113151916435787)
     | > stopnet_loss: 0.003685806645080447  (0.005655205309657113)
     | > loss: 0.19173435866832733  (0.19814002513885498)
     | > align_error: 0.5356696248054504  (0.5873184808662959)

   --> STEP: 36
     | > decoder_loss: 0.45715945959091187  (0.45858340875969994)
     | > postnet_loss: 0.30738773941993713  (0.3112060957484775)
     | > stopnet_loss: 0.0038492020685225725  (0.005605038552958932)
     | > loss: 0.1949860155582428  (0.19805241376161575)
     | > align_error: 0.6356450915336609  (0.5886608867181672)

   --> STEP: 37
     | > decoder_loss: 0.4486227035522461  (0.4583142005108498)
     | > postnet_loss: 0.303467333316803  (0.3109969400070809)
     | > stopnet_loss: 0.0037389069329947233  (0.00555460256323017)
     | > loss: 0.19176141917705536  (0.19788238688095197)
     | > align_error: 0.5209231972694397  (0.5868301383546881)

   --> STEP: 38
     | > decoder_loss: 0.4378128945827484  (0.4577746924601103)
     | > postnet_loss: 0.2974601089954376  (0.31064070761203766)
     | > stopnet_loss: 0.0032765227369964123  (0.005494653094118755)
     | > loss: 0.1870947778224945  (0.19759850243204521)
     | > align_error: 0.5529003739356995  (0.5859372498173463)

   --> STEP: 39
     | > decoder_loss: 0.4510326385498047  (0.457601819282923)
     | > postnet_loss: 0.30574771761894226  (0.3105152463301634)
     | > stopnet_loss: 0.003617021255195141  (0.0054465086879925085)
     | > loss: 0.19281211495399475  (0.19747577454799264)
     | > align_error: 0.5478980541229248  (0.5849618858251816)

   --> STEP: 40
     | > decoder_loss: 0.44814419746398926  (0.45736537873744965)
     | > postnet_loss: 0.30429142713546753  (0.31035965085029604)
     | > stopnet_loss: 0.0031801476143300533  (0.005389849661150947)
     | > loss: 0.1912890523672104  (0.1973211064934731)
     | > align_error: 0.5858516097068787  (0.5849841289222241)

   --> STEP: 41
     | > decoder_loss: 0.43820664286613464  (0.4568980924966859)
     | > postnet_loss: 0.2963593304157257  (0.3100181796201846)
     | > stopnet_loss: 0.0038295381236821413  (0.005351793282188293)
     | > loss: 0.18747103214263916  (0.1970808607775991)
     | > align_error: 0.5059907734394073  (0.5830574617153261)

   --> STEP: 42
     | > decoder_loss: 0.4441729784011841  (0.4565951135896501)
     | > postnet_loss: 0.3003518581390381  (0.3097880291087287)
     | > stopnet_loss: 0.003398813074454665  (0.005305293753432731)
     | > loss: 0.18953001499176025  (0.19690107873507912)
     | > align_error: 0.5812790393829346  (0.5830151183264597)

   --> STEP: 43
     | > decoder_loss: 0.4422841966152191  (0.45626230156698894)
     | > postnet_loss: 0.2991481423377991  (0.3095405898814978)
     | > stopnet_loss: 0.0030727642588317394  (0.005253374462860615)
     | > loss: 0.18843084573745728  (0.19670409657234372)
     | > align_error: 0.5534002184867859  (0.582326399725537)

   --> STEP: 44
     | > decoder_loss: 0.4597955644130707  (0.456342602995309)
     | > postnet_loss: 0.30776914954185486  (0.3095003298737786)
     | > stopnet_loss: 0.0028242196422070265  (0.005198166398754852)
     | > loss: 0.19471539556980133  (0.19665889882228596)
     | > align_error: 0.5527109503746033  (0.5816533213311976)

   --> STEP: 45
     | > decoder_loss: 0.4524601399898529  (0.4562563260396322)
     | > postnet_loss: 0.30686554312705994  (0.30944177905718484)
     | > stopnet_loss: 0.0034688885789364576  (0.005159738002758887)
     | > loss: 0.1933003067970276  (0.1965842634439469)
     | > align_error: 0.5546252727508545  (0.5810526980294123)

   --> STEP: 46
     | > decoder_loss: 0.4440917372703552  (0.45599187845769135)
     | > postnet_loss: 0.29869335889816284  (0.30920811774938)
     | > stopnet_loss: 0.0033300798386335373  (0.005119962825277901)
     | > loss: 0.1890263557434082  (0.19641996110263082)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3545821977384162 (-0.01776923916556622)
     | > avg_decoder_loss: 0.4518391169381864 (-0.0012922300533814712)
     | > avg_postnet_loss: 0.3056352535883586 (-0.0018799368179204246)
     | > avg_stopnet_loss: 0.004537726367936666 (-1.1434238827365273e-05)
     | > avg_loss: 0.19390631873499267 (-0.0008044757626272936)
     | > avg_align_error: 0.5738598749493108 (+0.000579737804152769)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_2265.pth

 > EPOCH: 15/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 22:43:49)

   --> TIME: 2025-12-27 22:44:03 -- STEP: 10/150 -- GLOBAL_STEP: 2275
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49191761016845703  (0.4851209968328476)
     | > postnet_loss: 0.42093539237976074  (0.42220679521560667)
     | > stopnet_loss: 0.009465779177844524  (0.012296644132584333)
     | > loss: 0.23767903447151184  (0.23912859112024307)
     | > align_error: 0.6519896686077118  (0.6930857956409454)
     | > grad_norm: tensor(0.2242, device='cuda:0')  (tensor(0.3000, device='cuda:0'))
     | > step_time: 0.5709  (0.5280849456787109)
     | > loader_time: 0.6646  (0.793082308769226)


   --> TIME: 2025-12-27 22:44:49 -- STEP: 35/150 -- GLOBAL_STEP: 2300
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.5084478259086609  (0.4926171796662467)
     | > postnet_loss: 0.42471298575401306  (0.42049020273344856)
     | > stopnet_loss: 0.00594839034602046  (0.00874358428908246)
     | > loss: 0.23923859000205994  (0.2370204303945814)
     | > align_error: 0.6124498844146729  (0.6626788573605674)
     | > grad_norm: tensor(0.2171, device='cuda:0')  (tensor(0.2477, device='cuda:0'))
     | > step_time: 0.9949  (0.7395312309265136)
     | > loader_time: 1.0344  (0.9379498822348459)


   --> TIME: 2025-12-27 22:45:47 -- STEP: 60/150 -- GLOBAL_STEP: 2325
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5024492740631104  (0.49735838969548546)
     | > postnet_loss: 0.421188086271286  (0.42010899384816486)
     | > stopnet_loss: 0.004454089794307947  (0.007186819395671288)
     | > loss: 0.2353634387254715  (0.23655366549889248)
     | > align_error: 0.6274736523628235  (0.6440705095728239)
     | > grad_norm: tensor(0.1514, device='cuda:0')  (tensor(0.2286, device='cuda:0'))
     | > step_time: 1.3313  (0.9397913614908854)
     | > loader_time: 1.173  (1.014788516362508)


   --> TIME: 2025-12-27 22:46:58 -- STEP: 85/150 -- GLOBAL_STEP: 2350
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5080728530883789  (0.49922999389031353)
     | > postnet_loss: 0.42272114753723145  (0.41944861867848565)
     | > stopnet_loss: 0.004090180154889822  (0.006284730328137384)
     | > loss: 0.23678867518901825  (0.23595438284032486)
     | > align_error: 0.5881414413452148  (0.6360038283993215)
     | > grad_norm: tensor(0.2343, device='cuda:0')  (tensor(0.2186, device='cuda:0'))
     | > step_time: 1.5651  (1.1009659711052386)
     | > loader_time: 1.4676  (1.1116199100718778)


   --> TIME: 2025-12-27 22:48:22 -- STEP: 110/150 -- GLOBAL_STEP: 2375
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5053810477256775  (0.4999968488108028)
     | > postnet_loss: 0.4176068603992462  (0.41883343864570965)
     | > stopnet_loss: 0.003331561107188463  (0.00569477054417472)
     | > loss: 0.2340785413980484  (0.23540234172886068)
     | > align_error: 0.6057610511779785  (0.630494031039151)
     | > grad_norm: tensor(0.1290, device='cuda:0')  (tensor(0.2112, device='cuda:0'))
     | > step_time: 1.8162  (1.2437768957831645)
     | > loader_time: 1.5463  (1.222473070838234)


   --> TIME: 2025-12-27 22:49:56 -- STEP: 135/150 -- GLOBAL_STEP: 2400
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5087409019470215  (0.5005893139927474)
     | > postnet_loss: 0.41670936346054077  (0.4179435756471422)
     | > stopnet_loss: 0.0029056298080831766  (0.005263930750596855)
     | > loss: 0.2342682033777237  (0.2348971522516674)
     | > align_error: 0.6171601414680481  (0.6272412158824777)
     | > grad_norm: tensor(0.1295, device='cuda:0')  (tensor(0.2011, device='cuda:0'))
     | > step_time: 2.1213  (1.3732667516779018)
     | > loader_time: 2.1776  (1.3338111365282972)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4749675393104553  (0.4749675393104553)
     | > postnet_loss: 0.33466604351997375  (0.33466604351997375)
     | > stopnet_loss: 0.012501006945967674  (0.012501006945967674)
     | > loss: 0.2149094045162201  (0.2149094045162201)
     | > align_error: 0.719369649887085  (0.719369649887085)

   --> STEP: 1
     | > decoder_loss: 0.45687317848205566  (0.45687317848205566)
     | > postnet_loss: 0.32035765051841736  (0.32035765051841736)
     | > stopnet_loss: 0.009871856309473515  (0.009871856309473515)
     | > loss: 0.2041795700788498  (0.2041795700788498)
     | > align_error: 0.6605187356472015  (0.6605187356472015)

   --> STEP: 2
     | > decoder_loss: 0.4503566026687622  (0.45361489057540894)
     | > postnet_loss: 0.31501051783561707  (0.3176840841770172)
     | > stopnet_loss: 0.011166204698383808  (0.010519030503928661)
     | > loss: 0.20250798761844635  (0.20334377884864807)
     | > align_error: 0.6585906744003296  (0.6595547050237656)

   --> STEP: 3
     | > decoder_loss: 0.4517190754413605  (0.45298295219739276)
     | > postnet_loss: 0.31125277280807495  (0.3155403137207031)
     | > stopnet_loss: 0.00855919998139143  (0.009865753663082918)
     | > loss: 0.19930216670036316  (0.20199657479921976)
     | > align_error: 0.7360861301422119  (0.6850651800632477)

   --> STEP: 4
     | > decoder_loss: 0.4627516567707062  (0.45542512834072113)
     | > postnet_loss: 0.32210680842399597  (0.31718193739652634)
     | > stopnet_loss: 0.008463041856884956  (0.009515075711533427)
     | > loss: 0.20467765629291534  (0.20266684517264366)
     | > align_error: 0.6056593656539917  (0.6652137264609337)

   --> STEP: 5
     | > decoder_loss: 0.44234392046928406  (0.4528088867664337)
     | > postnet_loss: 0.30513694882392883  (0.3147729396820068)
     | > stopnet_loss: 0.008436334319412708  (0.009299327433109284)
     | > loss: 0.19530655443668365  (0.20119478702545165)
     | > align_error: 0.6439098715782166  (0.6609529554843903)

   --> STEP: 6
     | > decoder_loss: 0.4588479995727539  (0.45381540556748706)
     | > postnet_loss: 0.31486478447914124  (0.3147882471481959)
     | > stopnet_loss: 0.007448387332260609  (0.00899083741630117)
     | > loss: 0.20087657868862152  (0.20114175230264664)
     | > align_error: 0.5958782434463501  (0.6501071701447169)

   --> STEP: 7
     | > decoder_loss: 0.46631354093551636  (0.4556008534772055)
     | > postnet_loss: 0.31429341435432434  (0.31471755674907137)
     | > stopnet_loss: 0.006573190446943045  (0.008645459277821439)
     | > loss: 0.20172493159770966  (0.2012250636305128)
     | > align_error: 0.5809313058853149  (0.6402249038219452)

   --> STEP: 8
     | > decoder_loss: 0.46212562918663025  (0.45641645044088364)
     | > postnet_loss: 0.31409043073654175  (0.3146391659975052)
     | > stopnet_loss: 0.007707634940743446  (0.00852823123568669)
     | > loss: 0.2017616480588913  (0.2012921366840601)
     | > align_error: 0.577481746673584  (0.6323820091784)

   --> STEP: 9
     | > decoder_loss: 0.4590175449848175  (0.4567054609457652)
     | > postnet_loss: 0.3151881694793701  (0.3147001663843791)
     | > stopnet_loss: 0.006859353743493557  (0.008342800403220786)
     | > loss: 0.20041076838970184  (0.20119420687357584)
     | > align_error: 0.5941861271858215  (0.6281380222903358)

   --> STEP: 10
     | > decoder_loss: 0.4901145100593567  (0.46004636585712433)
     | > postnet_loss: 0.3302026391029358  (0.31625041365623474)
     | > stopnet_loss: 0.0058643207885324955  (0.008094952441751957)
     | > loss: 0.21094360947608948  (0.20216914713382722)
     | > align_error: 0.5886631608009338  (0.6241905361413955)

   --> STEP: 11
     | > decoder_loss: 0.4742482304573059  (0.4613374444571408)
     | > postnet_loss: 0.3226538598537445  (0.31683254512873565)
     | > stopnet_loss: 0.0060204677283763885  (0.007906362922354178)
     | > loss: 0.2052459865808487  (0.20244885981082916)
     | > align_error: 0.5961672365665436  (0.6216429634527727)

   --> STEP: 12
     | > decoder_loss: 0.4666379392147064  (0.4617791523536046)
     | > postnet_loss: 0.3131341338157654  (0.3165243441859881)
     | > stopnet_loss: 0.0080105010420084  (0.00791504109899203)
     | > loss: 0.2029535174369812  (0.2024909146130085)
     | > align_error: 0.589726984500885  (0.6189832985401154)

   --> STEP: 13
     | > decoder_loss: 0.45999830961227417  (0.4616421644504254)
     | > postnet_loss: 0.31506359577178955  (0.31641197892335743)
     | > stopnet_loss: 0.005748503375798464  (0.007748384351054063)
     | > loss: 0.1995139867067337  (0.20226192015867966)
     | > align_error: 0.5882182121276855  (0.6166167534314669)

   --> STEP: 14
     | > decoder_loss: 0.4636107385158539  (0.46178277688367025)
     | > postnet_loss: 0.31363946199417114  (0.31621394199984415)
     | > stopnet_loss: 0.005117400549352169  (0.007560456936646785)
     | > loss: 0.1994299441576004  (0.2020596361586026)
     | > align_error: 0.5557278692722321  (0.612267547420093)

   --> STEP: 15
     | > decoder_loss: 0.4675038158893585  (0.4621641794840495)
     | > postnet_loss: 0.32035091519355774  (0.3164897402127584)
     | > stopnet_loss: 0.005113696679472923  (0.007397339586168528)
     | > loss: 0.20207737386226654  (0.20206081867218018)
     | > align_error: 0.5898645520210266  (0.6107740143934886)

   --> STEP: 16
     | > decoder_loss: 0.4663989543914795  (0.46242885291576385)
     | > postnet_loss: 0.3118809163570404  (0.316201688721776)
     | > stopnet_loss: 0.005274117458611727  (0.0072646382031962276)
     | > loss: 0.199844092130661  (0.20192227326333523)
     | > align_error: 0.608000785112381  (0.6106006875634193)

   --> STEP: 17
     | > decoder_loss: 0.47517895698547363  (0.4631788590375115)
     | > postnet_loss: 0.3229672610759735  (0.31659966356614055)
     | > stopnet_loss: 0.005014652386307716  (0.007132286096320432)
     | > loss: 0.20455121994018555  (0.20207691718550289)
     | > align_error: 0.5598264932632446  (0.6076139702516443)

   --> STEP: 18
     | > decoder_loss: 0.46997082233428955  (0.4635561903317769)
     | > postnet_loss: 0.31512147188186646  (0.31651754180590314)
     | > stopnet_loss: 0.005566410720348358  (0.00704529301987754)
     | > loss: 0.20183947682380676  (0.20206372605429757)
     | > align_error: 0.6051406860351562  (0.6074765655729506)

   --> STEP: 19
     | > decoder_loss: 0.4696618616580963  (0.4638775414542148)
     | > postnet_loss: 0.314681738615036  (0.31642092058533117)
     | > stopnet_loss: 0.005056805443018675  (0.006940635778990231)
     | > loss: 0.20114269852638245  (0.2020152509212494)
     | > align_error: 0.6025076806545258  (0.6072150453140861)

   --> STEP: 20
     | > decoder_loss: 0.4633750319480896  (0.4638524159789085)
     | > postnet_loss: 0.3124277591705322  (0.3162212625145912)
     | > stopnet_loss: 0.004667447879910469  (0.006826976384036243)
     | > loss: 0.19861814379692078  (0.20184539556503295)
     | > align_error: 0.6236457228660583  (0.6080365791916847)

   --> STEP: 21
     | > decoder_loss: 0.461492657661438  (0.46374004653521944)
     | > postnet_loss: 0.30852261185646057  (0.3158546601022993)
     | > stopnet_loss: 0.004163158591836691  (0.006700127917741027)
     | > loss: 0.19666697084903717  (0.2015988039118903)
     | > align_error: 0.562132328748703  (0.6058506625039237)

   --> STEP: 22
     | > decoder_loss: 0.4636761248111725  (0.46373714100230823)
     | > postnet_loss: 0.31253474950790405  (0.3157037550752813)
     | > stopnet_loss: 0.00502434466034174  (0.0066239559514956045)
     | > loss: 0.1990770697593689  (0.20148417963223023)
     | > align_error: 0.626779705286026  (0.6068019826303829)

   --> STEP: 23
     | > decoder_loss: 0.4351687431335449  (0.4624950367471446)
     | > postnet_loss: 0.30119913816452026  (0.3150731195574221)
     | > stopnet_loss: 0.004695892333984375  (0.006540127098560333)
     | > loss: 0.18878786265850067  (0.20093216585076373)
     | > align_error: 0.5677777528762817  (0.6051052769889003)

   --> STEP: 24
     | > decoder_loss: 0.4697769582271576  (0.46279845014214516)
     | > postnet_loss: 0.3168269395828247  (0.31514619539181393)
     | > stopnet_loss: 0.004541972652077675  (0.006456870663290222)
     | > loss: 0.2011929601430893  (0.20094303227961063)
     | > align_error: 0.5808574557304382  (0.6040949511031309)

   --> STEP: 25
     | > decoder_loss: 0.4700062572956085  (0.46308676242828367)
     | > postnet_loss: 0.31337636709213257  (0.31507540225982666)
     | > stopnet_loss: 0.0038117049261927605  (0.006351064033806324)
     | > loss: 0.1996573656797409  (0.20089160561561584)
     | > align_error: 0.5600422322750092  (0.6023328423500061)

   --> STEP: 26
     | > decoder_loss: 0.44420352578163147  (0.46236048409572017)
     | > postnet_loss: 0.3009050488471985  (0.31453038866703326)
     | > stopnet_loss: 0.0046127247624099255  (0.006284204831060309)
     | > loss: 0.1908898800611496  (0.20050692386352098)
     | > align_error: 0.5488906502723694  (0.600277373423943)

   --> STEP: 27
     | > decoder_loss: 0.44090813398361206  (0.46156595261008654)
     | > postnet_loss: 0.29835188388824463  (0.3139311847863374)
     | > stopnet_loss: 0.004044047091156244  (0.0062012360258786765)
     | > loss: 0.18885904550552368  (0.20007552096137293)
     | > align_error: 0.5428901612758636  (0.5981519211221623)

   --> STEP: 28
     | > decoder_loss: 0.4465983510017395  (0.4610313954097884)
     | > postnet_loss: 0.30158093571662903  (0.31349010446241926)
     | > stopnet_loss: 0.004045343026518822  (0.006124239847330111)
     | > loss: 0.1910901665687561  (0.1997546154473509)
     | > align_error: 0.5670855641365051  (0.5970424083726745)

   --> STEP: 29
     | > decoder_loss: 0.4428148567676544  (0.4604032389048872)
     | > postnet_loss: 0.2974757254123688  (0.3129378844951761)
     | > stopnet_loss: 0.0037368638440966606  (0.006041916536873785)
     | > loss: 0.18880951404571533  (0.19937719815763935)
     | > align_error: 0.5417799949645996  (0.5951368079103271)

   --> STEP: 30
     | > decoder_loss: 0.4421885013580322  (0.45979608098665875)
     | > postnet_loss: 0.2983720004558563  (0.3124523550271988)
     | > stopnet_loss: 0.0030631842091679573  (0.00594262545928359)
     | > loss: 0.18820331990718842  (0.19900473554929096)
     | > align_error: 0.534878134727478  (0.5931281854708988)

   --> STEP: 31
     | > decoder_loss: 0.44130274653434753  (0.4591995218107777)
     | > postnet_loss: 0.3004557490348816  (0.31206536773712407)
     | > stopnet_loss: 0.00409564608708024  (0.005883045479535095)
     | > loss: 0.1895352602005005  (0.1986992686025558)
     | > align_error: 0.5609488487243652  (0.5920901423500429)

   --> STEP: 32
     | > decoder_loss: 0.4486745595932007  (0.45887061674147844)
     | > postnet_loss: 0.30312278866767883  (0.3117859121412039)
     | > stopnet_loss: 0.004051628056913614  (0.005825813685078174)
     | > loss: 0.19200095534324646  (0.19848994631320238)
     | > align_error: 0.5326418280601501  (0.5902323825284838)

   --> STEP: 33
     | > decoder_loss: 0.4459288418292999  (0.4584784417441397)
     | > postnet_loss: 0.3019530177116394  (0.3114879456433383)
     | > stopnet_loss: 0.004134193062782288  (0.00577455245409951)
     | > loss: 0.19110466539859772  (0.19826614992185074)
     | > align_error: 0.5469067394733429  (0.5889194842540856)

   --> STEP: 34
     | > decoder_loss: 0.45213308930397034  (0.45829181373119354)
     | > postnet_loss: 0.3043287992477417  (0.311277382514056)
     | > stopnet_loss: 0.0034978396724909544  (0.005707590313463965)
     | > loss: 0.19261330366134644  (0.19809988973771825)
     | > align_error: 0.5645344257354736  (0.588202276650597)

   --> STEP: 35
     | > decoder_loss: 0.45031848549842834  (0.45806400435311456)
     | > postnet_loss: 0.30258268117904663  (0.3110289624759129)
     | > stopnet_loss: 0.003670955542474985  (0.005649400748578565)
     | > loss: 0.1918962597846985  (0.19792264316763197)
     | > align_error: 0.534943699836731  (0.5866806030273436)

   --> STEP: 36
     | > decoder_loss: 0.45628952980041504  (0.45801471339331734)
     | > postnet_loss: 0.30699941515922546  (0.3109170306060049)
     | > stopnet_loss: 0.0038527166470885277  (0.005599492856870509)
     | > loss: 0.19467495381832123  (0.19783242957459557)
     | > align_error: 0.6349437236785889  (0.5880212452676559)

   --> STEP: 37
     | > decoder_loss: 0.44818753004074097  (0.4577491138432477)
     | > postnet_loss: 0.30325138568878174  (0.3107098510136475)
     | > stopnet_loss: 0.0037260211538523436  (0.005548858486518667)
     | > loss: 0.1915857493877411  (0.19766360038035624)
     | > align_error: 0.5200583934783936  (0.5861844114355137)

   --> STEP: 38
     | > decoder_loss: 0.4375726878643036  (0.45721815526485443)
     | > postnet_loss: 0.2972169518470764  (0.31035477471979034)
     | > stopnet_loss: 0.00327676092274487  (0.005489066445366724)
     | > loss: 0.1869741678237915  (0.19738229952360453)
     | > align_error: 0.551979273557663  (0.5852842762282018)

   --> STEP: 39
     | > decoder_loss: 0.4506801664829254  (0.45705051452685624)
     | > postnet_loss: 0.3054206073284149  (0.31022825760719097)
     | > stopnet_loss: 0.003615562804043293  (0.005441027890460996)
     | > loss: 0.1926407516002655  (0.19726072137172407)
     | > align_error: 0.5471504926681519  (0.5843064869061493)

   --> STEP: 40
     | > decoder_loss: 0.44790542125701904  (0.4568218871951103)
     | > postnet_loss: 0.30414602160453796  (0.3100762017071247)
     | > stopnet_loss: 0.0031748448964208364  (0.005384373315609993)
     | > loss: 0.19118770956993103  (0.19710889607667925)
     | > align_error: 0.5851865410804749  (0.5843284882605074)

   --> STEP: 41
     | > decoder_loss: 0.43813568353652954  (0.4563661261302669)
     | > postnet_loss: 0.2963501214981079  (0.30974141926300236)
     | > stopnet_loss: 0.003837290685623884  (0.005346639592927405)
     | > loss: 0.18745873868465424  (0.1968735263841908)
     | > align_error: 0.5047880113124847  (0.5823884766276288)

   --> STEP: 42
     | > decoder_loss: 0.4440723657608032  (0.45607341755004155)
     | > postnet_loss: 0.3003726601600647  (0.3095183535700753)
     | > stopnet_loss: 0.0034065889194607735  (0.005300447910225819)
     | > loss: 0.18951784074306488  (0.19669839101178305)
     | > align_error: 0.5807003080844879  (0.5823482821385064)

   --> STEP: 43
     | > decoder_loss: 0.44187721610069275  (0.45574327333028924)
     | > postnet_loss: 0.2988196015357971  (0.30926954538323165)
     | > stopnet_loss: 0.0030611895490437746  (0.005248372134384376)
     | > loss: 0.18823538720607758  (0.1965015769697899)
     | > align_error: 0.5526968538761139  (0.581658714039381)

   --> STEP: 44
     | > decoder_loss: 0.4597227871417999  (0.45583371682600543)
     | > postnet_loss: 0.3076656460762024  (0.30923309312625374)
     | > stopnet_loss: 0.0028312678914517164  (0.0051934379470449975)
     | > loss: 0.1946783810853958  (0.19646014069969003)
     | > align_error: 0.5523251593112946  (0.5809920423410154)

   --> STEP: 45
     | > decoder_loss: 0.45181435346603394  (0.4557443976402283)
     | > postnet_loss: 0.30644690990448  (0.30917117794354765)
     | > stopnet_loss: 0.003464627778157592  (0.005155019943291944)
     | > loss: 0.19302994012832642  (0.1963839140203264)
     | > align_error: 0.5537612438201904  (0.580386913484997)

   --> STEP: 46
     | > decoder_loss: 0.44393032789230347  (0.4554875700370125)
     | > postnet_loss: 0.2986569106578827  (0.3089426069155984)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35934023423628375 (+0.004758036497867546)
     | > avg_decoder_loss: 0.4513384988813689 (-0.0005006180568175034)
     | > avg_postnet_loss: 0.305384433630741 (-0.00025081995761755405)
     | > avg_stopnet_loss: 0.004533324440038115 (-4.4019278985507615e-06)
     | > avg_loss: 0.1937140580831152 (-0.00019226065187746832)
     | > avg_align_error: 0.5731437879078316 (-0.0007160870414791853)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_2416.pth

 > EPOCH: 16/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 22:52:59)

   --> TIME: 2025-12-27 22:53:13 -- STEP: 9/150 -- GLOBAL_STEP: 2425
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4917563796043396  (0.4844549066490597)
     | > postnet_loss: 0.4211778938770294  (0.42182352476649815)
     | > stopnet_loss: 0.010477425530552864  (0.01275172032829788)
     | > loss: 0.23871099948883057  (0.23932132787174648)
     | > align_error: 0.6478841304779053  (0.6973840031358931)
     | > grad_norm: tensor(0.3052, device='cuda:0')  (tensor(0.3151, device='cuda:0'))
     | > step_time: 0.6031  (0.4991214805179172)
     | > loader_time: 0.9233  (0.8360503249698215)


   --> TIME: 2025-12-27 22:53:57 -- STEP: 34/150 -- GLOBAL_STEP: 2450
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.49594148993492126  (0.4912558855379329)
     | > postnet_loss: 0.4164701998233795  (0.4195382735308479)
     | > stopnet_loss: 0.0058546727523207664  (0.00887397860231645)
     | > loss: 0.23395758867263794  (0.2365725189447403)
     | > align_error: 0.6197560429573059  (0.6632901500253117)
     | > grad_norm: tensor(0.1814, device='cuda:0')  (tensor(0.2464, device='cuda:0'))
     | > step_time: 1.022  (0.7384730717715096)
     | > loader_time: 0.9441  (0.9137358875835643)


   --> TIME: 2025-12-27 22:54:53 -- STEP: 59/150 -- GLOBAL_STEP: 2475
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.5017412900924683  (0.49642669699959835)
     | > postnet_loss: 0.4188847541809082  (0.4193952735197746)
     | > stopnet_loss: 0.004483737051486969  (0.007238120116861695)
     | > loss: 0.2346402406692505  (0.2361936129755893)
     | > align_error: 0.6067035794258118  (0.6441264541472419)
     | > grad_norm: tensor(0.1418, device='cuda:0')  (tensor(0.2128, device='cuda:0'))
     | > step_time: 1.2705  (0.9241497961141296)
     | > loader_time: 1.2185  (0.9854660599918689)


   --> TIME: 2025-12-27 22:56:04 -- STEP: 84/150 -- GLOBAL_STEP: 2500
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.499623566865921  (0.4985427036881447)
     | > postnet_loss: 0.4197496473789215  (0.4188861832732246)
     | > stopnet_loss: 0.0035668197087943554  (0.006313044017934729)
     | > loss: 0.23341012001037598  (0.23567026587469236)
     | > align_error: 0.6699355244636536  (0.6363788349997429)
     | > grad_norm: tensor(0.1273, device='cuda:0')  (tensor(0.1989, device='cuda:0'))
     | > step_time: 1.6955  (1.081868038291023)
     | > loader_time: 2.1494  (1.1028585235277812)


   --> TIME: 2025-12-27 22:57:31 -- STEP: 109/150 -- GLOBAL_STEP: 2525
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49695685505867004  (0.4994562227244771)
     | > postnet_loss: 0.4164072275161743  (0.4183936619430507)
     | > stopnet_loss: 0.003884796053171158  (0.005720618524836427)
     | > loss: 0.23222580552101135  (0.23518308969812657)
     | > align_error: 0.6343333125114441  (0.630446956518593)
     | > grad_norm: tensor(0.1369, device='cuda:0')  (tensor(0.1901, device='cuda:0'))
     | > step_time: 1.817  (1.2200666348868554)
     | > loader_time: 2.1465  (1.2569644997972962)


   --> TIME: 2025-12-27 22:59:02 -- STEP: 134/150 -- GLOBAL_STEP: 2550
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5009426474571228  (0.49997016720807375)
     | > postnet_loss: 0.4125368297100067  (0.41749744495349145)
     | > stopnet_loss: 0.0033891345374286175  (0.005279274030115956)
     | > loss: 0.2317589968442917  (0.23464617678033772)
     | > align_error: 0.6345372200012207  (0.6270495232806275)
     | > grad_norm: tensor(0.1529, device='cuda:0')  (tensor(0.1861, device='cuda:0'))
     | > step_time: 1.9612  (1.338037871602756)
     | > loader_time: 1.7231  (1.3542629729455977)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4757336676120758  (0.4757336676120758)
     | > postnet_loss: 0.3354359567165375  (0.3354359567165375)
     | > stopnet_loss: 0.01257805060595274  (0.01257805060595274)
     | > loss: 0.21537046134471893  (0.21537046134471893)
     | > align_error: 0.719273716211319  (0.719273716211319)

   --> STEP: 1
     | > decoder_loss: 0.4575389325618744  (0.4575389325618744)
     | > postnet_loss: 0.32151079177856445  (0.32151079177856445)
     | > stopnet_loss: 0.00989067554473877  (0.00989067554473877)
     | > loss: 0.20465311408042908  (0.20465311408042908)
     | > align_error: 0.6603434681892395  (0.6603434681892395)

   --> STEP: 2
     | > decoder_loss: 0.45044955611228943  (0.4539942443370819)
     | > postnet_loss: 0.3154878616333008  (0.3184993267059326)
     | > stopnet_loss: 0.011233346536755562  (0.010562011040747166)
     | > loss: 0.20271770656108856  (0.20368541032075882)
     | > align_error: 0.6582854390144348  (0.6593144536018372)

   --> STEP: 3
     | > decoder_loss: 0.45341432094573975  (0.45380093653996784)
     | > postnet_loss: 0.3125176727771759  (0.31650544206301373)
     | > stopnet_loss: 0.008712238632142544  (0.009945420237878958)
     | > loss: 0.20019522309303284  (0.2025220145781835)
     | > align_error: 0.7357794642448425  (0.684802790482839)

   --> STEP: 4
     | > decoder_loss: 0.4641949236392975  (0.45639943331480026)
     | > postnet_loss: 0.32321029901504517  (0.3181816563010216)
     | > stopnet_loss: 0.008503279648721218  (0.009584885090589523)
     | > loss: 0.20535458624362946  (0.20323015749454498)
     | > align_error: 0.6057054400444031  (0.66502845287323)

   --> STEP: 5
     | > decoder_loss: 0.4439760148525238  (0.45391474962234496)
     | > postnet_loss: 0.3060985803604126  (0.31576504111289977)
     | > stopnet_loss: 0.00850959774106741  (0.009369827620685101)
     | > loss: 0.19602824747562408  (0.2017897754907608)
     | > align_error: 0.6435699462890625  (0.6607367515563964)

   --> STEP: 6
     | > decoder_loss: 0.4597904086112976  (0.4548940261205037)
     | > postnet_loss: 0.3159620761871338  (0.3157978802919388)
     | > stopnet_loss: 0.007499452214688063  (0.009058098386352261)
     | > loss: 0.2014375776052475  (0.20173107584317526)
     | > align_error: 0.595808207988739  (0.6499153276284536)

   --> STEP: 7
     | > decoder_loss: 0.4668954908847809  (0.45660852108682903)
     | > postnet_loss: 0.3150884509086609  (0.3156965332371848)
     | > stopnet_loss: 0.006586043629795313  (0.008704947706844126)
     | > loss: 0.20208203792572021  (0.20178121328353882)
     | > align_error: 0.581010639667511  (0.6400718007768903)

   --> STEP: 8
     | > decoder_loss: 0.46311643719673157  (0.45742201060056686)
     | > postnet_loss: 0.3152030110359192  (0.3156348429620266)
     | > stopnet_loss: 0.007724622264504433  (0.008582407026551664)
     | > loss: 0.20230449736118317  (0.20184662379324436)
     | > align_error: 0.5773527324199677  (0.632231917232275)

   --> STEP: 9
     | > decoder_loss: 0.4605727195739746  (0.45777208937538993)
     | > postnet_loss: 0.3162688612937927  (0.3157052894433339)
     | > stopnet_loss: 0.006816951557993889  (0.008386245307823023)
     | > loss: 0.20102734863758087  (0.20175559322039285)
     | > align_error: 0.593843549489975  (0.6279665430386862)

   --> STEP: 10
     | > decoder_loss: 0.49235013127326965  (0.4612298935651779)
     | > postnet_loss: 0.3316800594329834  (0.3173027664422989)
     | > stopnet_loss: 0.005919590126723051  (0.008139579789713025)
     | > loss: 0.211927130818367  (0.20277274698019027)
     | > align_error: 0.5885331034660339  (0.6240231990814209)

   --> STEP: 11
     | > decoder_loss: 0.47541120648384094  (0.4625191038305109)
     | > postnet_loss: 0.3233465552330017  (0.31785220178690826)
     | > stopnet_loss: 0.0060677132569253445  (0.007951228286732327)
     | > loss: 0.20575715601444244  (0.20304405689239502)
     | > align_error: 0.5960265398025513  (0.6214780482378873)

   --> STEP: 12
     | > decoder_loss: 0.4687795639038086  (0.4630408088366191)
     | > postnet_loss: 0.31479257345199585  (0.3175972327589989)
     | > stopnet_loss: 0.008012228645384312  (0.007956311649953326)
     | > loss: 0.20390526950359344  (0.2031158246099949)
     | > align_error: 0.5897833108901978  (0.6188368201255798)

   --> STEP: 13
     | > decoder_loss: 0.46079662442207336  (0.4628681792662694)
     | > postnet_loss: 0.3157563805580139  (0.31745562874353855)
     | > stopnet_loss: 0.005774380639195442  (0.00778847080297195)
     | > loss: 0.1999126374721527  (0.20286942559939164)
     | > align_error: 0.5882130265235901  (0.6164811436946576)

   --> STEP: 14
     | > decoder_loss: 0.4643024206161499  (0.4629706250769751)
     | > postnet_loss: 0.3143373727798462  (0.3172328961747034)
     | > stopnet_loss: 0.005166251212358475  (0.007601169403642416)
     | > loss: 0.1998261958360672  (0.20265205204486847)
     | > align_error: 0.5561010241508484  (0.6121682780129569)

   --> STEP: 15
     | > decoder_loss: 0.46893343329429626  (0.46336814562479656)
     | > postnet_loss: 0.32106471061706543  (0.3174883504708609)
     | > stopnet_loss: 0.005146291106939316  (0.007437510850528876)
     | > loss: 0.20264583826065063  (0.20265163779258727)
     | > align_error: 0.5897799730300903  (0.6106757243474324)

   --> STEP: 16
     | > decoder_loss: 0.46888506412506104  (0.4637129530310631)
     | > postnet_loss: 0.31313732266426086  (0.31721641123294836)
     | > stopnet_loss: 0.005308304913341999  (0.007304435479454696)
     | > loss: 0.200813889503479  (0.202536778524518)
     | > align_error: 0.608016848564148  (0.6105095446109772)

   --> STEP: 17
     | > decoder_loss: 0.4763006269931793  (0.46445340444059935)
     | > postnet_loss: 0.3235059082508087  (0.3175863816457637)
     | > stopnet_loss: 0.005034961272031069  (0.007170936996665071)
     | > loss: 0.2049866020679474  (0.20268088579177856)
     | > align_error: 0.5599431991577148  (0.6075350537019617)

   --> STEP: 18
     | > decoder_loss: 0.4723512828350067  (0.4648921754625108)
     | > postnet_loss: 0.31643274426460266  (0.3175222906801436)
     | > stopnet_loss: 0.005572225898504257  (0.007082119713433915)
     | > loss: 0.2027682363986969  (0.20268573860327402)
     | > align_error: 0.6051520705223083  (0.6074026657475365)

   --> STEP: 19
     | > decoder_loss: 0.47232598066329956  (0.4652834283678155)
     | > postnet_loss: 0.3160799741744995  (0.31744637928510966)
     | > stopnet_loss: 0.005089426878839731  (0.006977241143192116)
     | > loss: 0.20219092071056366  (0.20265969555628927)
     | > align_error: 0.6023532152175903  (0.6071369051933289)

   --> STEP: 20
     | > decoder_loss: 0.46543633937835693  (0.46529107391834257)
     | > postnet_loss: 0.31338831782341003  (0.3172434762120247)
     | > stopnet_loss: 0.004691647831350565  (0.006862961477600038)
     | > loss: 0.19939781725406647  (0.20249660164117814)
     | > align_error: 0.6238425374031067  (0.6079721868038177)

   --> STEP: 21
     | > decoder_loss: 0.4623641073703766  (0.46515169455891564)
     | > postnet_loss: 0.30909281969070435  (0.3168553497110094)
     | > stopnet_loss: 0.004191641230136156  (0.00673575575153033)
     | > loss: 0.1970558762550354  (0.20223751947993324)
     | > align_error: 0.5620883107185364  (0.6057872403235662)

   --> STEP: 22
     | > decoder_loss: 0.46530085802078247  (0.4651584747162732)
     | > postnet_loss: 0.31353679299354553  (0.316704506223852)
     | > stopnet_loss: 0.005061035975813866  (0.0066596321253614)
     | > loss: 0.19977045059204102  (0.20212537998502905)
     | > align_error: 0.6268439888954163  (0.6067443652586504)

   --> STEP: 23
     | > decoder_loss: 0.43657734990119934  (0.46391581711561786)
     | > postnet_loss: 0.3020172119140625  (0.3160659282103829)
     | > stopnet_loss: 0.00472712516784668  (0.006575610083730325)
     | > loss: 0.18937575817108154  (0.20157104860181393)
     | > align_error: 0.5679014623165131  (0.605055543391601)

   --> STEP: 24
     | > decoder_loss: 0.4719044864177704  (0.4642486783365409)
     | > postnet_loss: 0.3180323839187622  (0.3161478638648987)
     | > stopnet_loss: 0.004551623482257128  (0.006491277308668941)
     | > loss: 0.2020358443260193  (0.2015904150903225)
     | > align_error: 0.5810143053531647  (0.6040538251399995)

   --> STEP: 25
     | > decoder_loss: 0.4714928865432739  (0.4645384466648102)
     | > postnet_loss: 0.31423965096473694  (0.3160715353488922)
     | > stopnet_loss: 0.0038594496436417103  (0.006386004202067852)
     | > loss: 0.20029257237911224  (0.2015385013818741)
     | > align_error: 0.5600937008857727  (0.6022954201698305)

   --> STEP: 26
     | > decoder_loss: 0.4453929662704468  (0.46380208203425777)
     | > postnet_loss: 0.30176499485969543  (0.3155212837916154)
     | > stopnet_loss: 0.00460568955168128  (0.006317530561668368)
     | > loss: 0.19139517843723297  (0.20114837357631096)
     | > align_error: 0.548690676689148  (0.6002336992667273)

   --> STEP: 27
     | > decoder_loss: 0.4422345459461212  (0.4630032844013638)
     | > postnet_loss: 0.29918140172958374  (0.3149161029745031)
     | > stopnet_loss: 0.004071584437042475  (0.00623434737186741)
     | > loss: 0.18942557275295258  (0.20071419576803842)
     | > align_error: 0.5429643392562866  (0.5981126118589332)

   --> STEP: 28
     | > decoder_loss: 0.44769713282585144  (0.4624566361308098)
     | > postnet_loss: 0.3022528886795044  (0.3144638453211103)
     | > stopnet_loss: 0.004072660580277443  (0.006157144272167768)
     | > loss: 0.19156017899513245  (0.2003872665975775)
     | > align_error: 0.5671210885047913  (0.5970057717391424)

   --> STEP: 29
     | > decoder_loss: 0.44405901432037354  (0.4618222353787258)
     | > postnet_loss: 0.2983517050743103  (0.3139082542781172)
     | > stopnet_loss: 0.0037544595543295145  (0.006074293075000931)
     | > loss: 0.18935714662075043  (0.20000691763285933)
     | > align_error: 0.5417098999023438  (0.5950990175378735)

   --> STEP: 30
     | > decoder_loss: 0.44305747747421265  (0.46119674344857536)
     | > postnet_loss: 0.2988571524620056  (0.31340655088424685)
     | > stopnet_loss: 0.00307486136443913  (0.005974312017982205)
     | > loss: 0.18855351209640503  (0.19962513744831084)
     | > align_error: 0.5350706577301025  (0.5930980722109478)

   --> STEP: 31
     | > decoder_loss: 0.4426659941673279  (0.46059897734272864)
     | > postnet_loss: 0.3013337254524231  (0.3130171049025751)
     | > stopnet_loss: 0.004102407954633236  (0.005913928015938689)
     | > loss: 0.19010233879089355  (0.1993179503948458)
     | > align_error: 0.5609838664531708  (0.5920621300897292)

   --> STEP: 32
     | > decoder_loss: 0.4489634037017822  (0.46023536566644907)
     | > postnet_loss: 0.3035270869731903  (0.3127205418422818)
     | > stopnet_loss: 0.004081070423126221  (0.0058566512161633)
     | > loss: 0.19220370054244995  (0.1990956300869584)
     | > align_error: 0.5326151251792908  (0.590204411186278)

   --> STEP: 33
     | > decoder_loss: 0.44780880212783813  (0.459858803134976)
     | > postnet_loss: 0.30303817987442017  (0.3124271369341648)
     | > stopnet_loss: 0.00415706355124712  (0.005805148559650688)
     | > loss: 0.19186881184577942  (0.19887663559480148)
     | > align_error: 0.5471056997776031  (0.5888983896284393)

   --> STEP: 34
     | > decoder_loss: 0.4538091719150543  (0.4596808728049783)
     | > postnet_loss: 0.30535566806793213  (0.31221915255574617)
     | > stopnet_loss: 0.003535256953909993  (0.005738387041834786)
     | > loss: 0.1933264583349228  (0.198713395087158)
     | > align_error: 0.5645774304866791  (0.5881830673007405)

   --> STEP: 35
     | > decoder_loss: 0.4508990943431854  (0.45942996484892706)
     | > postnet_loss: 0.3030118942260742  (0.3119560880320413)
     | > stopnet_loss: 0.0036939692217856646  (0.0056799751041190965)
     | > loss: 0.19217172265052795  (0.1985264901603971)
     | > align_error: 0.5348764061927795  (0.5866600198405131)

   --> STEP: 36
     | > decoder_loss: 0.4577006995677948  (0.45938192970222896)
     | > postnet_loss: 0.3076632618904114  (0.3118368428614404)
     | > stopnet_loss: 0.00387846352532506  (0.005629933115819262)
     | > loss: 0.19521944224834442  (0.19843462771839565)
     | > align_error: 0.6350854635238647  (0.5880051710539395)

   --> STEP: 37
     | > decoder_loss: 0.44936853647232056  (0.45911129745277196)
     | > postnet_loss: 0.3040834963321686  (0.3116272929552439)
     | > stopnet_loss: 0.003737581195309758  (0.005578788469319005)
     | > loss: 0.19210059940814972  (0.1982634377640647)
     | > align_error: 0.5201264321804047  (0.586170610543844)

   --> STEP: 38
     | > decoder_loss: 0.4384763538837433  (0.45856827262200806)
     | > postnet_loss: 0.2978440523147583  (0.3112645760962837)
     | > stopnet_loss: 0.003298663767054677  (0.00551878518768047)
     | > loss: 0.18737876415252686  (0.1979769989848137)
     | > align_error: 0.5521169304847717  (0.5852744610686053)

   --> STEP: 39
     | > decoder_loss: 0.4511438310146332  (0.4583779023243831)
     | > postnet_loss: 0.3058873414993286  (0.3111266982861054)
     | > stopnet_loss: 0.003630296792834997  (0.005470362408325458)
     | > loss: 0.19288809597492218  (0.19784651429225236)
     | > align_error: 0.5473043620586395  (0.5843008687862984)

   --> STEP: 40
     | > decoder_loss: 0.44892776012420654  (0.4581416487693787)
     | > postnet_loss: 0.3049284815788269  (0.31097174286842344)
     | > stopnet_loss: 0.0031945058144629  (0.005413465993478894)
     | > loss: 0.19165857136249542  (0.19769181571900846)
     | > align_error: 0.5853496193885803  (0.5843270875513554)

   --> STEP: 41
     | > decoder_loss: 0.4390161335468292  (0.45767517278834086)
     | > postnet_loss: 0.29694676399230957  (0.3106296702129085)
     | > stopnet_loss: 0.003832554677501321  (0.005374907180894076)
     | > loss: 0.18782326579093933  (0.19745111937929943)
     | > align_error: 0.5050188899040222  (0.5823927412672741)

   --> STEP: 42
     | > decoder_loss: 0.4438447654247284  (0.45734587737492155)
     | > postnet_loss: 0.30018216371536255  (0.310380920058205)
     | > stopnet_loss: 0.003413880942389369  (0.005328216079977297)
     | > loss: 0.18942061066627502  (0.1972599167908941)
     | > align_error: 0.5808289051055908  (0.5823555070729484)

   --> STEP: 43
     | > decoder_loss: 0.4429342746734619  (0.4570107238237248)
     | > postnet_loss: 0.29951339960098267  (0.3101281870243161)
     | > stopnet_loss: 0.003080749651417136  (0.00527594941884799)
     | > loss: 0.18869267404079437  (0.19706067858740342)
     | > align_error: 0.5529025793075562  (0.5816705552644509)

   --> STEP: 44
     | > decoder_loss: 0.4609096050262451  (0.4570993347601457)
     | > postnet_loss: 0.3083885610103607  (0.3100886500694535)
     | > stopnet_loss: 0.00285279075615108  (0.005220877631059425)
     | > loss: 0.1951773464679718  (0.19701787558468906)
     | > align_error: 0.5523499250411987  (0.5810041773048314)

   --> STEP: 45
     | > decoder_loss: 0.45295438170433044  (0.4570072246922387)
     | > postnet_loss: 0.30713433027267456  (0.310022998518414)
     | > stopnet_loss: 0.003502379171550274  (0.005182688776403667)
     | > loss: 0.1935245543718338  (0.19694024622440337)
     | > align_error: 0.554000198841095  (0.5804040888945262)

   --> STEP: 46
     | > decoder_loss: 0.44490864872932434  (0.4567442121713058)
     | > postnet_loss: 0.2992173433303833  (0.3097880929708481)
     | > stopnet_loss: 0.0033545545302331448  (0.0051429467275738725)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3427031004067622 (-0.016637133829521533)
     | > avg_decoder_loss: 0.452347273627917 (+0.0010087747465480912)
     | > avg_postnet_loss: 0.3061173833680875 (+0.0007329497373464999)
     | > avg_stopnet_loss: 0.004555269091559406 (+2.1944651521290347e-05)
     | > avg_loss: 0.19417143432479916 (+0.00045737624168395996)
     | > avg_align_error: 0.5732378124287634 (+9.402452093176805e-05)


 > EPOCH: 17/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 23:02:24)

   --> TIME: 2025-12-27 23:02:34 -- STEP: 8/150 -- GLOBAL_STEP: 2575
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4916452467441559  (0.4852832406759262)
     | > postnet_loss: 0.42153918743133545  (0.42290741577744484)
     | > stopnet_loss: 0.01068150531500578  (0.01307762588839978)
     | > loss: 0.2389776110649109  (0.24012529104948044)
     | > align_error: 0.689706414937973  (0.703788373619318)
     | > grad_norm: tensor(0.3274, device='cuda:0')  (tensor(0.2935, device='cuda:0'))
     | > step_time: 0.5732  (0.4832879304885864)
     | > loader_time: 0.5562  (0.749318540096283)


   --> TIME: 2025-12-27 23:03:18 -- STEP: 33/150 -- GLOBAL_STEP: 2600
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.4995760917663574  (0.49189306569821906)
     | > postnet_loss: 0.41908538341522217  (0.42008490002516546)
     | > stopnet_loss: 0.0056029558181762695  (0.008961211791205587)
     | > loss: 0.23526832461357117  (0.23695570275639044)
     | > align_error: 0.6534855961799622  (0.6646663709120317)
     | > grad_norm: tensor(0.2475, device='cuda:0')  (tensor(0.2371, device='cuda:0'))
     | > step_time: 1.0273  (0.7384455781994443)
     | > loader_time: 1.0018  (0.8752991430687181)


   --> TIME: 2025-12-27 23:04:15 -- STEP: 58/150 -- GLOBAL_STEP: 2625
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.5069021582603455  (0.49678392348618344)
     | > postnet_loss: 0.4203769862651825  (0.41973235843510465)
     | > stopnet_loss: 0.004048855975270271  (0.007297884167075667)
     | > loss: 0.2358686327934265  (0.23642695361170277)
     | > align_error: 0.6018027067184448  (0.6451682874868656)
     | > grad_norm: tensor(0.2734, device='cuda:0')  (tensor(0.2305, device='cuda:0'))
     | > step_time: 1.2826  (0.9222036764539522)
     | > loader_time: 1.2784  (0.9721309604315922)


   --> TIME: 2025-12-27 23:05:24 -- STEP: 83/150 -- GLOBAL_STEP: 2650
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49754393100738525  (0.4987076226487217)
     | > postnet_loss: 0.4224414527416229  (0.41902512276029014)
     | > stopnet_loss: 0.004015099722892046  (0.0063535313525921585)
     | > loss: 0.2340114563703537  (0.23578671662204237)
     | > align_error: 0.6237937808036804  (0.6362925171852112)
     | > grad_norm: tensor(0.1635, device='cuda:0')  (tensor(0.2150, device='cuda:0'))
     | > step_time: 1.7031  (1.0955233114311496)
     | > loader_time: 1.4173  (1.0623494113784242)


   --> TIME: 2025-12-27 23:06:47 -- STEP: 108/150 -- GLOBAL_STEP: 2675
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5007391571998596  (0.4995407313108444)
     | > postnet_loss: 0.4217510223388672  (0.4184656764070193)
     | > stopnet_loss: 0.003337612608447671  (0.005743082416571537)
     | > loss: 0.23396015167236328  (0.23524468405931084)
     | > align_error: 0.5842015743255615  (0.6309031529559029)
     | > grad_norm: tensor(0.1766, device='cuda:0')  (tensor(0.1985, device='cuda:0'))
     | > step_time: 1.8429  (1.2401683551293832)
     | > loader_time: 1.6821  (1.1889529117831477)


   --> TIME: 2025-12-27 23:08:20 -- STEP: 133/150 -- GLOBAL_STEP: 2700
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.501952052116394  (0.5000464795227337)
     | > postnet_loss: 0.41079390048980713  (0.4175348656069964)
     | > stopnet_loss: 0.003433993784710765  (0.0053017169947883)
     | > loss: 0.23162047564983368  (0.23469705353105874)
     | > align_error: 0.5625600218772888  (0.6274521126782984)
     | > grad_norm: tensor(0.1429, device='cuda:0')  (tensor(0.1920, device='cuda:0'))
     | > step_time: 1.9425  (1.3555332986932052)
     | > loader_time: 1.9018  (1.3135173338696473)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4745878279209137  (0.4745878279209137)
     | > postnet_loss: 0.33436137437820435  (0.33436137437820435)
     | > stopnet_loss: 0.012494836002588272  (0.012494836002588272)
     | > loss: 0.21473214030265808  (0.21473214030265808)
     | > align_error: 0.7192600667476654  (0.7192600667476654)

   --> STEP: 1
     | > decoder_loss: 0.45591363310813904  (0.45591363310813904)
     | > postnet_loss: 0.3195936381816864  (0.3195936381816864)
     | > stopnet_loss: 0.009893406182527542  (0.009893406182527542)
     | > loss: 0.2037702202796936  (0.2037702202796936)
     | > align_error: 0.6602429449558258  (0.6602429449558258)

   --> STEP: 2
     | > decoder_loss: 0.4496062994003296  (0.4527599662542343)
     | > postnet_loss: 0.315241277217865  (0.3174174576997757)
     | > stopnet_loss: 0.011249154806137085  (0.010571280494332314)
     | > loss: 0.20246104896068573  (0.20311563462018967)
     | > align_error: 0.6582168340682983  (0.6592298895120621)

   --> STEP: 3
     | > decoder_loss: 0.4519375264644623  (0.4524858196576436)
     | > postnet_loss: 0.31133413314819336  (0.31538968284924823)
     | > stopnet_loss: 0.008719461038708687  (0.009954007342457771)
     | > loss: 0.19953738152980804  (0.20192288359006247)
     | > align_error: 0.7360203266143799  (0.6848267018795013)

   --> STEP: 4
     | > decoder_loss: 0.4624665081501007  (0.4549809917807579)
     | > postnet_loss: 0.3220738470554352  (0.317060723900795)
     | > stopnet_loss: 0.008444193750619888  (0.0095765539444983)
     | > loss: 0.20457927882671356  (0.20258698239922523)
     | > align_error: 0.6057740449905396  (0.6650635376572609)

   --> STEP: 5
     | > decoder_loss: 0.4420687258243561  (0.45239853858947754)
     | > postnet_loss: 0.30532070994377136  (0.31471272110939025)
     | > stopnet_loss: 0.008471434004604816  (0.009355529956519604)
     | > loss: 0.1953187882900238  (0.20113334357738494)
     | > align_error: 0.6437999606132507  (0.6608108222484589)

   --> STEP: 6
     | > decoder_loss: 0.4577871561050415  (0.4532966415087382)
     | > postnet_loss: 0.3146609365940094  (0.3147040903568268)
     | > stopnet_loss: 0.007436603773385286  (0.009035708925997218)
     | > loss: 0.20054861903190613  (0.2010358894864718)
     | > align_error: 0.5958595871925354  (0.649985616405805)

   --> STEP: 7
     | > decoder_loss: 0.465995728969574  (0.45511079686028616)
     | > postnet_loss: 0.3144674599170685  (0.3146702860082899)
     | > stopnet_loss: 0.006582313682883978  (0.008685223891266755)
     | > loss: 0.20169812440872192  (0.20113049447536469)
     | > align_error: 0.5809886455535889  (0.6401289062840598)

   --> STEP: 8
     | > decoder_loss: 0.461268812417984  (0.4558805488049984)
     | > postnet_loss: 0.31393489241600037  (0.3145783618092537)
     | > stopnet_loss: 0.007683994714170694  (0.008560070244129747)
     | > loss: 0.20148491859436035  (0.20117479749023914)
     | > align_error: 0.5775562524795532  (0.6323073245584965)

   --> STEP: 9
     | > decoder_loss: 0.45865461230278015  (0.4561887780825297)
     | > postnet_loss: 0.31527209281921387  (0.3146554430325826)
     | > stopnet_loss: 0.006859349086880684  (0.008371101226657629)
     | > loss: 0.20034103095531464  (0.20108215676413643)
     | > align_error: 0.5940913558006287  (0.6280611058076223)

   --> STEP: 10
     | > decoder_loss: 0.4898364245891571  (0.45955354273319243)
     | > postnet_loss: 0.33011892437934875  (0.3162017911672592)
     | > stopnet_loss: 0.005911975167691708  (0.008125188620761037)
     | > loss: 0.21090081334114075  (0.20206402242183685)
     | > align_error: 0.588467001914978  (0.6241016954183578)

   --> STEP: 11
     | > decoder_loss: 0.4732849597930908  (0.4608018533750014)
     | > postnet_loss: 0.3225879371166229  (0.31678234988992865)
     | > stopnet_loss: 0.006033262237906456  (0.007935013495046984)
     | > loss: 0.20500148832798004  (0.20233106477694077)
     | > align_error: 0.5962414741516113  (0.6215689480304718)

   --> STEP: 12
     | > decoder_loss: 0.46629393100738525  (0.46125952651103336)
     | > postnet_loss: 0.313280314207077  (0.3164905135830243)
     | > stopnet_loss: 0.008047923445701599  (0.007944422657601535)
     | > loss: 0.20294149219989777  (0.20238193372885385)
     | > align_error: 0.5898469090461731  (0.6189254447817802)

   --> STEP: 13
     | > decoder_loss: 0.4600665867328644  (0.4611677619127127)
     | > postnet_loss: 0.31522855162620544  (0.31639343958634597)
     | > stopnet_loss: 0.005728549789637327  (0.007773970898527365)
     | > loss: 0.19955232739448547  (0.20216427170313322)
     | > align_error: 0.5884749293327332  (0.6165830974395459)

   --> STEP: 14
     | > decoder_loss: 0.46470335125923157  (0.4614203040088926)
     | > postnet_loss: 0.3144270181655884  (0.31625298091343473)
     | > stopnet_loss: 0.005126248579472303  (0.007584847875737718)
     | > loss: 0.19990883767604828  (0.20200316927262715)
     | > align_error: 0.5563098788261414  (0.6122778675385884)

   --> STEP: 15
     | > decoder_loss: 0.46749165654182434  (0.4618250608444214)
     | > postnet_loss: 0.32112425565719604  (0.3165777325630188)
     | > stopnet_loss: 0.005095429718494415  (0.007418886665254832)
     | > loss: 0.2022494077682495  (0.20201958517233531)
     | > align_error: 0.5899050831794739  (0.6107863485813141)

   --> STEP: 16
     | > decoder_loss: 0.46691539883613586  (0.46214320696890354)
     | > postnet_loss: 0.3126712441444397  (0.3163335770368576)
     | > stopnet_loss: 0.005283727310597897  (0.007285439205588773)
     | > loss: 0.20018039643764496  (0.20190463587641716)
     | > align_error: 0.60843425989151  (0.6106393430382013)

   --> STEP: 17
     | > decoder_loss: 0.47519946098327637  (0.4629112219109255)
     | > postnet_loss: 0.32374337315559387  (0.31676944739678325)
     | > stopnet_loss: 0.005023342557251453  (0.007152374696863049)
     | > loss: 0.20475904643535614  (0.20207254237988415)
     | > align_error: 0.5599007606506348  (0.6076547205448151)

   --> STEP: 18
     | > decoder_loss: 0.4704039394855499  (0.4633274839984046)
     | > postnet_loss: 0.31591302156448364  (0.3167218681838777)
     | > stopnet_loss: 0.005551176145672798  (0.007063419221796923)
     | > loss: 0.20213042199611664  (0.2020757579141193)
     | > align_error: 0.6053647100925446  (0.6075274977419112)

   --> STEP: 19
     | > decoder_loss: 0.4698585569858551  (0.46367122468195465)
     | > postnet_loss: 0.3153689205646515  (0.3166506604144448)
     | > stopnet_loss: 0.005080800503492355  (0.006959070868201946)
     | > loss: 0.2013876736164093  (0.20203954295108192)
     | > align_error: 0.6026314496994019  (0.6072698110028317)

   --> STEP: 20
     | > decoder_loss: 0.463619589805603  (0.46366864293813703)
     | > postnet_loss: 0.3133809268474579  (0.3164871737360954)
     | > stopnet_loss: 0.00466964254155755  (0.006844599451869726)
     | > loss: 0.19891977310180664  (0.20188355445861816)
     | > align_error: 0.6238572001457214  (0.6080991804599762)

   --> STEP: 21
     | > decoder_loss: 0.46155840158462524  (0.4635681552546365)
     | > postnet_loss: 0.30908203125  (0.3161345479034242)
     | > stopnet_loss: 0.004164875950664282  (0.006716993570859943)
     | > loss: 0.19682498276233673  (0.20164267009212858)
     | > align_error: 0.5624338686466217  (0.6059246418021974)

   --> STEP: 22
     | > decoder_loss: 0.4633820354938507  (0.4635596952655099)
     | > postnet_loss: 0.3129941523075104  (0.3159918026490645)
     | > stopnet_loss: 0.005052435211837292  (0.006641331827268004)
     | > loss: 0.19914647936820984  (0.201529206877405)
     | > align_error: 0.626963198184967  (0.606880939819596)

   --> STEP: 23
     | > decoder_loss: 0.4349114000797272  (0.4623141172139541)
     | > postnet_loss: 0.30169057846069336  (0.31537001029304834)
     | > stopnet_loss: 0.004691235721111298  (0.0065565450400437994)
     | > loss: 0.18884173035621643  (0.20097757746344028)
     | > align_error: 0.5678825378417969  (0.6051853571249091)

   --> STEP: 24
     | > decoder_loss: 0.47033578157424927  (0.4626483532289664)
     | > postnet_loss: 0.3178068995475769  (0.3154715473453204)
     | > stopnet_loss: 0.004543898161500692  (0.006472684753437837)
     | > loss: 0.20157957077026367  (0.20100266051789126)
     | > align_error: 0.5811538696289062  (0.604184045145909)

   --> STEP: 25
     | > decoder_loss: 0.4706529974937439  (0.4629685389995575)
     | > postnet_loss: 0.3143244981765747  (0.31542566537857053)
     | > stopnet_loss: 0.003819936653599143  (0.006366574829444289)
     | > loss: 0.20006431639194489  (0.20096512675285338)
     | > align_error: 0.5603204071521759  (0.6024294996261597)

   --> STEP: 26
     | > decoder_loss: 0.4440383315086365  (0.4622404540960605)
     | > postnet_loss: 0.3014492392539978  (0.31488811052762544)
     | > stopnet_loss: 0.0045819939114153385  (0.006297937101827791)
     | > loss: 0.19095388054847717  (0.20058007882191584)
     | > align_error: 0.5488243103027344  (0.6003677615752587)

   --> STEP: 27
     | > decoder_loss: 0.4415530860424042  (0.46147425527925845)
     | > postnet_loss: 0.2995363473892212  (0.31431952670768454)
     | > stopnet_loss: 0.004036460537463427  (0.006214178710555037)
     | > loss: 0.18930882215499878  (0.2001626248712893)
     | > align_error: 0.5429587960243225  (0.5982415035918907)

   --> STEP: 28
     | > decoder_loss: 0.44666850566864014  (0.46094547850745066)
     | > postnet_loss: 0.30220746994018555  (0.31388695325170246)
     | > stopnet_loss: 0.004066563211381435  (0.006137478157013122)
     | > loss: 0.19128555059432983  (0.19984558650425502)
     | > align_error: 0.567230224609375  (0.5971339579139437)

   --> STEP: 29
     | > decoder_loss: 0.4422881305217743  (0.46030212168035833)
     | > postnet_loss: 0.297853946685791  (0.3133340909563262)
     | > stopnet_loss: 0.0037366379983723164  (0.006054690565335853)
     | > loss: 0.18877217173576355  (0.19946374461568636)
     | > align_error: 0.5418746173381805  (0.5952284634113312)

   --> STEP: 30
     | > decoder_loss: 0.44230347871780396  (0.45970216691493987)
     | > postnet_loss: 0.29886534810066223  (0.31285179952780406)
     | > stopnet_loss: 0.003042614320293069  (0.005954288023834427)
     | > loss: 0.18833482265472412  (0.19909278055032095)
     | > align_error: 0.5351945459842682  (0.593227332830429)

   --> STEP: 31
     | > decoder_loss: 0.44086167216300964  (0.4590944090197163)
     | > postnet_loss: 0.3010815680027008  (0.3124721146398975)
     | > stopnet_loss: 0.004116688389331102  (0.005895010616269803)
     | > loss: 0.18960249423980713  (0.19878664228223986)
     | > align_error: 0.5610297322273254  (0.5921887005529096)

   --> STEP: 32
     | > decoder_loss: 0.4486387372016907  (0.458767669275403)
     | > postnet_loss: 0.30381515622138977  (0.31220158468931913)
     | > stopnet_loss: 0.004054051358252764  (0.005837480639456771)
     | > loss: 0.19216753542423248  (0.19857979519292712)
     | > align_error: 0.532558023929596  (0.590325241908431)

   --> STEP: 33
     | > decoder_loss: 0.44644060730934143  (0.45839412194309814)
     | > postnet_loss: 0.3031465709209442  (0.3119271903327017)
     | > stopnet_loss: 0.004175318870693445  (0.0057871121010093975)
     | > loss: 0.19157211482524872  (0.19836744124239142)
     | > align_error: 0.5472017824649811  (0.5890184704101447)

   --> STEP: 34
     | > decoder_loss: 0.45205095410346985  (0.45820755818310904)
     | > postnet_loss: 0.3052244186401367  (0.3117300499888027)
     | > stopnet_loss: 0.003514915006235242  (0.005720282774692511)
     | > loss: 0.19283375144004822  (0.19820468565996954)
     | > align_error: 0.5645051002502441  (0.5882974889348535)

   --> STEP: 35
     | > decoder_loss: 0.44890472292900085  (0.45794176289013455)
     | > postnet_loss: 0.3026125133037567  (0.3114695489406586)
     | > stopnet_loss: 0.0037049627862870693  (0.005662702203595212)
     | > loss: 0.1915842741727829  (0.19801553104604994)
     | > align_error: 0.5348801612854004  (0.5867712795734406)

   --> STEP: 36
     | > decoder_loss: 0.45685461163520813  (0.45791156424416435)
     | > postnet_loss: 0.3080631196498871  (0.3113749259048038)
     | > stopnet_loss: 0.0038630515336990356  (0.005612711907209207)
     | > loss: 0.19509248435497284  (0.19793433530463111)
     | > align_error: 0.6349290013313293  (0.5881089940667152)

   --> STEP: 37
     | > decoder_loss: 0.44768211245536804  (0.4576350925741969)
     | > postnet_loss: 0.3037385046482086  (0.31116853614111206)
     | > stopnet_loss: 0.0037265804130584  (0.005561735380340267)
     | > loss: 0.19158174097537994  (0.1977626435660027)
     | > align_error: 0.5201038122177124  (0.5862710161789043)

   --> STEP: 38
     | > decoder_loss: 0.43761470913887024  (0.45710824037853043)
     | > postnet_loss: 0.298046737909317  (0.310823225661328)
     | > stopnet_loss: 0.003268549917265773  (0.005501388394469886)
     | > loss: 0.1871839165687561  (0.1974842560134436)
     | > align_error: 0.5520947575569153  (0.5853716409520099)

   --> STEP: 39
     | > decoder_loss: 0.4503432512283325  (0.4569347791182689)
     | > postnet_loss: 0.3060508668422699  (0.3107008574864803)
     | > stopnet_loss: 0.003627888159826398  (0.005453349926914925)
     | > loss: 0.19272641837596893  (0.19736226017658526)
     | > align_error: 0.5472214818000793  (0.5843934317429861)

   --> STEP: 40
     | > decoder_loss: 0.4474546015262604  (0.4566977746784687)
     | > postnet_loss: 0.30469030141830444  (0.3105505935847759)
     | > stopnet_loss: 0.0031818291172385216  (0.005396561906673015)
     | > loss: 0.1912180632352829  (0.1972086552530527)
     | > align_error: 0.585256040096283  (0.5844149969518184)

   --> STEP: 41
     | > decoder_loss: 0.43773388862609863  (0.4562352408723133)
     | > postnet_loss: 0.29675358533859253  (0.3102140811885275)
     | > stopnet_loss: 0.003838880453258753  (0.005358569676101935)
     | > loss: 0.1874607503414154  (0.1969709014747201)
     | > align_error: 0.5051795542240143  (0.5824824251779696)

   --> STEP: 42
     | > decoder_loss: 0.4440188705921173  (0.45594437491326106)
     | > postnet_loss: 0.3011636435985565  (0.3099985945792425)
     | > stopnet_loss: 0.0034096306189894676  (0.005312166365218305)
     | > loss: 0.1897052526473999  (0.19679790983597437)
     | > align_error: 0.580748438835144  (0.5824411397888547)

   --> STEP: 43
     | > decoder_loss: 0.44174981117248535  (0.45561426877975464)
     | > postnet_loss: 0.29961439967155457  (0.30975710167441256)
     | > stopnet_loss: 0.0030546768102794886  (0.005259666608126705)
     | > loss: 0.18839573860168457  (0.19660251050494437)
     | > align_error: 0.5526189208030701  (0.5817475998124411)

   --> STEP: 44
     | > decoder_loss: 0.4602985978126526  (0.4557207308032296)
     | > postnet_loss: 0.30871930718421936  (0.3097335154359991)
     | > stopnet_loss: 0.0028316539246588945  (0.005204484501684255)
     | > loss: 0.19508613646030426  (0.19656804745847528)
     | > align_error: 0.5522726774215698  (0.5810777152126486)

   --> STEP: 45
     | > decoder_loss: 0.45231351256370544  (0.45564501484235126)
     | > postnet_loss: 0.3075127899646759  (0.3096841659810808)
     | > stopnet_loss: 0.0034705246798694134  (0.00516595206119948)
     | > loss: 0.19342710077762604  (0.1964982486433453)
     | > align_error: 0.5537475943565369  (0.580470379193624)

   --> STEP: 46
     | > decoder_loss: 0.443843275308609  (0.4553884552872699)
     | > postnet_loss: 0.29938602447509766  (0.30946029333964636)
     | > stopnet_loss: 0.0033362943213433027  (0.0051261768929417376)
     | > loss: 0.1891436129808426  (0.19633836525937784)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.343622240153226 (+0.0009191397464637929)
     | > avg_decoder_loss: 0.45122365472894727 (-0.0011236188989697249)
     | > avg_postnet_loss: 0.3058964601068786 (-0.00022092326120892736)
     | > avg_stopnet_loss: 0.0045425393971417 (-1.2729694417706015e-05)
     | > avg_loss: 0.1938225683389288 (-0.00034886598587036133)
     | > avg_align_error: 0.5732202927271525 (-1.7519701610901883e-05)


 > EPOCH: 18/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 23:11:35)

   --> TIME: 2025-12-27 23:11:45 -- STEP: 7/150 -- GLOBAL_STEP: 2725
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4896301329135895  (0.48214926038469585)
     | > postnet_loss: 0.4237256944179535  (0.4218274695532663)
     | > stopnet_loss: 0.011202866211533546  (0.013551585908446993)
     | > loss: 0.23954182863235474  (0.23954577105385916)
     | > align_error: 0.673103928565979  (0.7052082717418671)
     | > grad_norm: tensor(0.2523, device='cuda:0')  (tensor(0.2859, device='cuda:0'))
     | > step_time: 0.5379  (0.5019674301147461)
     | > loader_time: 0.7172  (0.7928604739052909)


   --> TIME: 2025-12-27 23:12:27 -- STEP: 32/150 -- GLOBAL_STEP: 2750
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.5010547637939453  (0.4900532113388181)
     | > postnet_loss: 0.4204925298690796  (0.4188253190368414)
     | > stopnet_loss: 0.006076474208384752  (0.009050535838468932)
     | > loss: 0.2364632934331894  (0.23627016926184297)
     | > align_error: 0.6339253187179565  (0.664848675020039)
     | > grad_norm: tensor(0.2122, device='cuda:0')  (tensor(0.2386, device='cuda:0'))
     | > step_time: 1.0822  (0.7338961213827133)
     | > loader_time: 0.9882  (0.8388386219739914)


   --> TIME: 2025-12-27 23:13:22 -- STEP: 57/150 -- GLOBAL_STEP: 2775
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.5032095909118652  (0.49543059499640213)
     | > postnet_loss: 0.4171752333641052  (0.41868378927833155)
     | > stopnet_loss: 0.0048081232234835625  (0.007337011821698724)
     | > loss: 0.23490433394908905  (0.23586560811912805)
     | > align_error: 0.6594542860984802  (0.6453059984926589)
     | > grad_norm: tensor(0.2084, device='cuda:0')  (tensor(0.2234, device='cuda:0'))
     | > step_time: 1.2848  (0.9221009497056928)
     | > loader_time: 1.1942  (0.9405981908764756)


   --> TIME: 2025-12-27 23:14:32 -- STEP: 82/150 -- GLOBAL_STEP: 2800
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.50185227394104  (0.4976722140137742)
     | > postnet_loss: 0.4144359230995178  (0.41806916783495646)
     | > stopnet_loss: 0.0036967943888157606  (0.0063720686963146065)
     | > loss: 0.23276884853839874  (0.23530741417553366)
     | > align_error: 0.6457970142364502  (0.6358305059555098)
     | > grad_norm: tensor(0.1599, device='cuda:0')  (tensor(0.2065, device='cuda:0'))
     | > step_time: 1.6076  (1.0867554705317428)
     | > loader_time: 1.5612  (1.0516086351580736)


   --> TIME: 2025-12-27 23:15:56 -- STEP: 107/150 -- GLOBAL_STEP: 2825
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5037579536437988  (0.4984729557393867)
     | > postnet_loss: 0.42516371607780457  (0.41753503819492377)
     | > stopnet_loss: 0.003551706438884139  (0.005752490491771671)
     | > loss: 0.23578213155269623  (0.2347544891254924)
     | > align_error: 0.6037605702877045  (0.6308116497837493)
     | > grad_norm: tensor(0.1663, device='cuda:0')  (tensor(0.1995, device='cuda:0'))
     | > step_time: 1.6227  (1.2208933718850674)
     | > loader_time: 1.5658  (1.2103509479594008)


   --> TIME: 2025-12-27 23:17:27 -- STEP: 132/150 -- GLOBAL_STEP: 2850
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5011584162712097  (0.499115179208192)
     | > postnet_loss: 0.41064217686653137  (0.4168076930624066)
     | > stopnet_loss: 0.003391521517187357  (0.005305252385424507)
     | > loss: 0.2313416749238968  (0.2342859705289205)
     | > align_error: 0.5919329226016998  (0.6275597650444867)
     | > grad_norm: tensor(0.2230, device='cuda:0')  (tensor(0.1972, device='cuda:0'))
     | > step_time: 1.9656  (1.3425643227317112)
     | > loader_time: 1.7416  (1.309830539154284)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4742961525917053  (0.4742961525917053)
     | > postnet_loss: 0.3337726593017578  (0.3337726593017578)
     | > stopnet_loss: 0.012530370615422726  (0.012530370615422726)
     | > loss: 0.21454757452011108  (0.21454757452011108)
     | > align_error: 0.7191093862056732  (0.7191093862056732)

   --> STEP: 1
     | > decoder_loss: 0.4551243782043457  (0.4551243782043457)
     | > postnet_loss: 0.31899523735046387  (0.31899523735046387)
     | > stopnet_loss: 0.009926943108439445  (0.009926943108439445)
     | > loss: 0.203456848859787  (0.203456848859787)
     | > align_error: 0.660232424736023  (0.660232424736023)

   --> STEP: 2
     | > decoder_loss: 0.4503016769886017  (0.4527130275964737)
     | > postnet_loss: 0.31539809703826904  (0.31719666719436646)
     | > stopnet_loss: 0.01125156320631504  (0.010589253157377243)
     | > loss: 0.20267650485038757  (0.20306667685508728)
     | > align_error: 0.6580895185470581  (0.6591609716415405)

   --> STEP: 3
     | > decoder_loss: 0.45257216691970825  (0.4526660740375519)
     | > postnet_loss: 0.3114987909793854  (0.3152973751227061)
     | > stopnet_loss: 0.008717508055269718  (0.009965338123341402)
     | > loss: 0.19973525404930115  (0.2019562025864919)
     | > align_error: 0.7357747256755829  (0.6846988896528879)

   --> STEP: 4
     | > decoder_loss: 0.4615369737148285  (0.45488379895687103)
     | > postnet_loss: 0.32118940353393555  (0.31677038222551346)
     | > stopnet_loss: 0.008467111736536026  (0.009590781526640058)
     | > loss: 0.20414870977401733  (0.20250432938337326)
     | > align_error: 0.6054734885692596  (0.6648925393819809)

   --> STEP: 5
     | > decoder_loss: 0.4428291916847229  (0.4524728775024414)
     | > postnet_loss: 0.30559784173965454  (0.31453587412834166)
     | > stopnet_loss: 0.008455219678580761  (0.009363669157028198)
     | > loss: 0.1955619752407074  (0.2011158585548401)
     | > align_error: 0.6436063051223755  (0.6606352925300598)

   --> STEP: 6
     | > decoder_loss: 0.4578993320465088  (0.4533772865931193)
     | > postnet_loss: 0.3143637478351593  (0.3145071864128113)
     | > stopnet_loss: 0.007462593726813793  (0.009046823251992464)
     | > loss: 0.2005283534526825  (0.2010179410378138)
     | > align_error: 0.5956459045410156  (0.6498037278652191)

   --> STEP: 7
     | > decoder_loss: 0.4664161205291748  (0.4552399771554129)
     | > postnet_loss: 0.3147128224372864  (0.3145365629877363)
     | > stopnet_loss: 0.006573880556970835  (0.008693545724132232)
     | > loss: 0.2018561214208603  (0.20113768109253474)
     | > align_error: 0.5808425843715668  (0.6399521359375545)

   --> STEP: 8
     | > decoder_loss: 0.46164360642433167  (0.4560404308140278)
     | > postnet_loss: 0.31416183710098267  (0.3144897222518921)
     | > stopnet_loss: 0.007701127789914608  (0.008569493482355028)
     | > loss: 0.20165249705314636  (0.2012020330876112)
     | > align_error: 0.5770477950572968  (0.6320890933275223)

   --> STEP: 9
     | > decoder_loss: 0.4584433138370514  (0.45630741781658596)
     | > postnet_loss: 0.31524336338043213  (0.3145734601550632)
     | > stopnet_loss: 0.006875840947031975  (0.008381309867319133)
     | > loss: 0.2002975046634674  (0.201101529929373)
     | > align_error: 0.5938780605792999  (0.6278434230221642)

   --> STEP: 10
     | > decoder_loss: 0.4908388555049896  (0.45976056158542633)
     | > postnet_loss: 0.33056536316871643  (0.3161726504564285)
     | > stopnet_loss: 0.005949835758656263  (0.008138162456452847)
     | > loss: 0.21130089461803436  (0.20212146639823914)
     | > align_error: 0.5882942080497742  (0.6238885015249253)

   --> STEP: 11
     | > decoder_loss: 0.4729524850845337  (0.46095982735807245)
     | > postnet_loss: 0.32270491123199463  (0.31676649234511634)
     | > stopnet_loss: 0.006039900705218315  (0.007947411388158798)
     | > loss: 0.20495425164699554  (0.20237899232994427)
     | > align_error: 0.5958291590213776  (0.6213376522064209)

   --> STEP: 12
     | > decoder_loss: 0.46584591269493103  (0.461367001136144)
     | > postnet_loss: 0.3135095536708832  (0.31649508078893024)
     | > stopnet_loss: 0.0080487672239542  (0.007955857707808415)
     | > loss: 0.2028876394033432  (0.20242137958606085)
     | > align_error: 0.5893484354019165  (0.6186718841393789)

   --> STEP: 13
     | > decoder_loss: 0.45918214321136475  (0.4611989351419302)
     | > postnet_loss: 0.31514906883239746  (0.3163915414076585)
     | > stopnet_loss: 0.005737975239753723  (0.0077852513641119)
     | > loss: 0.19932077825069427  (0.20218287179103264)
     | > align_error: 0.5881515741348267  (0.6163241679851825)

   --> STEP: 14
     | > decoder_loss: 0.46458008885383606  (0.46144044612135204)
     | > postnet_loss: 0.3147173821926117  (0.31627195860658375)
     | > stopnet_loss: 0.005145631264895201  (0.007596707071310708)
     | > loss: 0.19996999204158783  (0.2020248089517866)
     | > align_error: 0.5558174550533295  (0.6120022599186216)

   --> STEP: 15
     | > decoder_loss: 0.46838104724884033  (0.4619031528631846)
     | > postnet_loss: 0.3221437931060791  (0.3166634142398834)
     | > stopnet_loss: 0.005121150519698858  (0.007431669967869917)
     | > loss: 0.20275236666202545  (0.20207331279913585)
     | > align_error: 0.5899576544761658  (0.6105326195557912)

   --> STEP: 16
     | > decoder_loss: 0.46796613931655884  (0.4622820895165205)
     | > postnet_loss: 0.3138287365436554  (0.31648624688386917)
     | > stopnet_loss: 0.005315633025020361  (0.00729941765894182)
     | > loss: 0.20076435804367065  (0.20199150312691927)
     | > align_error: 0.6081547737121582  (0.6103840041905642)

   --> STEP: 17
     | > decoder_loss: 0.47516727447509766  (0.4630400415729074)
     | > postnet_loss: 0.32419726252555847  (0.3169398360392627)
     | > stopnet_loss: 0.005008999723941088  (0.0071646871921770714)
     | > loss: 0.20485013723373413  (0.20215965807437897)
     | > align_error: 0.559668779373169  (0.6074007556718939)

   --> STEP: 18
     | > decoder_loss: 0.47177407145500183  (0.46352526545524597)
     | > postnet_loss: 0.31739169359207153  (0.31696493923664093)
     | > stopnet_loss: 0.005487444344907999  (0.007071507033995456)
     | > loss: 0.2027788758277893  (0.20219405906067955)
     | > align_error: 0.6053399443626404  (0.6072862661547132)

   --> STEP: 19
     | > decoder_loss: 0.47025877237319946  (0.4638796605561909)
     | > postnet_loss: 0.31597211956977844  (0.31691268556996394)
     | > stopnet_loss: 0.005075954366475344  (0.00696647794623124)
     | > loss: 0.20163369178771973  (0.20216456604631325)
     | > align_error: 0.602351725101471  (0.6070265534677004)

   --> STEP: 20
     | > decoder_loss: 0.4650043249130249  (0.4639358937740326)
     | > postnet_loss: 0.3147467076778412  (0.3168043866753578)
     | > stopnet_loss: 0.004702313803136349  (0.006853269739076495)
     | > loss: 0.19964008033275604  (0.20203834176063537)
     | > align_error: 0.6237253844738007  (0.6078614950180053)

   --> STEP: 21
     | > decoder_loss: 0.4616859257221222  (0.46382875243822735)
     | > postnet_loss: 0.30977609753608704  (0.31646970624015447)
     | > stopnet_loss: 0.004151143599301577  (0.00672459706575388)
     | > loss: 0.1970166563987732  (0.201799213886261)
     | > align_error: 0.5621160566806793  (0.605683140811466)

   --> STEP: 22
     | > decoder_loss: 0.4631863236427307  (0.4637995511293411)
     | > postnet_loss: 0.3136272132396698  (0.3163405020128597)
     | > stopnet_loss: 0.005046452861279249  (0.0066483177837323056)
     | > loss: 0.19924983382225037  (0.2016833329742605)
     | > align_error: 0.626695305109024  (0.6066382391886278)

   --> STEP: 23
     | > decoder_loss: 0.4360671937465668  (0.46259379646052484)
     | > postnet_loss: 0.3030267059803009  (0.31576164131579193)
     | > stopnet_loss: 0.004699175711721182  (0.006563572476253561)
     | > loss: 0.18947264552116394  (0.20115243351977805)
     | > align_error: 0.5678601562976837  (0.6049522355846737)

   --> STEP: 24
     | > decoder_loss: 0.47152844071388245  (0.46296607330441475)
     | > postnet_loss: 0.31936976313591003  (0.3159119797249635)
     | > stopnet_loss: 0.00454356474801898  (0.006479405487577121)
     | > loss: 0.2022681087255478  (0.20119891998668513)
     | > align_error: 0.5811131298542023  (0.6039589395125707)

   --> STEP: 25
     | > decoder_loss: 0.4720856249332428  (0.46333085536956786)
     | > postnet_loss: 0.3160816729068756  (0.31591876745224)
     | > stopnet_loss: 0.003816688433289528  (0.006372896805405617)
     | > loss: 0.20085851848125458  (0.20118530392646788)
     | > align_error: 0.5601551532745361  (0.6022067880630493)

   --> STEP: 26
     | > decoder_loss: 0.4451390504837036  (0.4626311705662654)
     | > postnet_loss: 0.30256810784339905  (0.31540528054420763)
     | > stopnet_loss: 0.00458497041836381  (0.006304130405904009)
     | > loss: 0.19151175022125244  (0.200813244168575)
     | > align_error: 0.5486520230770111  (0.6001469894097402)

   --> STEP: 27
     | > decoder_loss: 0.4421022832393646  (0.4618708414060098)
     | > postnet_loss: 0.3005737364292145  (0.3148559640955042)
     | > stopnet_loss: 0.004048802889883518  (0.006220599757162509)
     | > loss: 0.18971781432628632  (0.2004023023225643)
     | > align_error: 0.5427329540252686  (0.5980205436547598)

   --> STEP: 28
     | > decoder_loss: 0.44822078943252563  (0.461383339549814)
     | > postnet_loss: 0.30397817492485046  (0.31446747162512373)
     | > stopnet_loss: 0.0040796175599098206  (0.006144136107260627)
     | > loss: 0.19212934374809265  (0.20010683951633318)
     | > align_error: 0.567228764295578  (0.5969208372490746)

   --> STEP: 29
     | > decoder_loss: 0.44294437766075134  (0.4607475132777773)
     | > postnet_loss: 0.29889434576034546  (0.31393046728495894)
     | > stopnet_loss: 0.003736308543011546  (0.006061107570562383)
     | > loss: 0.18919597566127777  (0.1997306028316761)
     | > align_error: 0.5417086780071259  (0.5950169696890074)

   --> STEP: 30
     | > decoder_loss: 0.442456990480423  (0.46013782918453217)
     | > postnet_loss: 0.2995849847793579  (0.31345228453477225)
     | > stopnet_loss: 0.0030354417394846678  (0.005960252042859793)
     | > loss: 0.18854592740535736  (0.19935778031746546)
     | > align_error: 0.5350621938705444  (0.5930184771617254)

   --> STEP: 31
     | > decoder_loss: 0.44219017028808594  (0.4595588724459371)
     | > postnet_loss: 0.30275288224220276  (0.3131071425253345)
     | > stopnet_loss: 0.0040916865691542625  (0.005899975737256389)
     | > loss: 0.19032743573188782  (0.19906647887922102)
     | > align_error: 0.5609543919563293  (0.5919841518325191)

   --> STEP: 32
     | > decoder_loss: 0.4502131938934326  (0.45926681999117136)
     | > postnet_loss: 0.3054603934288025  (0.3128681816160679)
     | > stopnet_loss: 0.004054682794958353  (0.005842310332809575)
     | > loss: 0.1929730772972107  (0.1988760600797832)
     | > align_error: 0.5324680209159851  (0.5901242727413774)

   --> STEP: 33
     | > decoder_loss: 0.4478387236595154  (0.45892051404172723)
     | > postnet_loss: 0.30485695600509644  (0.3126254172036142)
     | > stopnet_loss: 0.004181911703199148  (0.005791995222821381)
     | > loss: 0.19235582649707794  (0.19867847724394364)
     | > align_error: 0.5471404194831848  (0.5888217317335533)

   --> STEP: 34
     | > decoder_loss: 0.45410048961639404  (0.4587787486174527)
     | > postnet_loss: 0.30718523263931274  (0.3124654117752524)
     | > stopnet_loss: 0.0035142451524734497  (0.0057250025736935)
     | > loss: 0.19383567571640015  (0.19853604190489826)
     | > align_error: 0.5645173192024231  (0.5881068960708731)

   --> STEP: 35
     | > decoder_loss: 0.4502508044242859  (0.4585350930690765)
     | > postnet_loss: 0.3040703535079956  (0.3122255529676165)
     | > stopnet_loss: 0.0036891864147037268  (0.0056668363977223635)
     | > loss: 0.1922694742679596  (0.19835699711527144)
     | > align_error: 0.5349437594413757  (0.5865879493100302)

   --> STEP: 36
     | > decoder_loss: 0.45742493867874146  (0.4585042554471228)
     | > postnet_loss: 0.3090551197528839  (0.31213748537831837)
     | > stopnet_loss: 0.00385984661988914  (0.0056166422372269965)
     | > loss: 0.1954798698425293  (0.1982770769132508)
     | > align_error: 0.6349166333675385  (0.5879304127560722)

   --> STEP: 37
     | > decoder_loss: 0.44908782839775085  (0.4582497574187614)
     | > postnet_loss: 0.3052634298801422  (0.3119517000945839)
     | > stopnet_loss: 0.0037323269061744213  (0.0055657147958471966)
     | > loss: 0.19232013821601868  (0.19811607857008237)
     | > align_error: 0.5201376676559448  (0.5860981764020147)

   --> STEP: 38
     | > decoder_loss: 0.4384002983570099  (0.4577274032329258)
     | > postnet_loss: 0.2991567850112915  (0.3116149918029183)
     | > stopnet_loss: 0.0032647144980728626  (0.005505162156432083)
     | > loss: 0.18765397369861603  (0.19784076002083326)
     | > align_error: 0.5521214604377747  (0.5852040522976926)

   --> STEP: 39
     | > decoder_loss: 0.4510030448436737  (0.45755498378704756)
     | > postnet_loss: 0.3069329261779785  (0.31149493883817625)
     | > stopnet_loss: 0.003631024621427059  (0.00545710734784221)
     | > loss: 0.1931150257587433  (0.19771958734744635)
     | > align_error: 0.5472212433815002  (0.5842301341203543)

   --> STEP: 40
     | > decoder_loss: 0.4484284520149231  (0.4573268204927444)
     | > postnet_loss: 0.30599546432495117  (0.3113574519753456)
     | > stopnet_loss: 0.0031769864726811647  (0.005400104325963184)
     | > loss: 0.19178296625614166  (0.19757117182016373)
     | > align_error: 0.5851783752441406  (0.5842538401484489)

   --> STEP: 41
     | > decoder_loss: 0.4389893412590027  (0.4568795649016776)
     | > postnet_loss: 0.29805198311805725  (0.31103292834468005)
     | > stopnet_loss: 0.003821255872026086  (0.005361595827086669)
     | > loss: 0.18808159232139587  (0.1973397186616572)
     | > align_error: 0.505361020565033  (0.5823296250366583)

   --> STEP: 42
     | > decoder_loss: 0.4446548521518707  (0.45658850031239645)
     | > postnet_loss: 0.3022330403327942  (0.3108234072015399)
     | > stopnet_loss: 0.003394421422854066  (0.0053147583412716075)
     | > loss: 0.19011640548706055  (0.197167735014643)
     | > align_error: 0.5807502269744873  (0.5822920203208923)

   --> STEP: 43
     | > decoder_loss: 0.4431988000869751  (0.4562771119350611)
     | > postnet_loss: 0.30137982964515686  (0.3106037891188333)
     | > stopnet_loss: 0.003068518592044711  (0.005262520207568656)
     | > loss: 0.18921317160129547  (0.19698274516782097)
     | > align_error: 0.5526981353759766  (0.5816037904384525)

   --> STEP: 44
     | > decoder_loss: 0.4609903395175934  (0.456384230743755)
     | > postnet_loss: 0.30967703461647034  (0.31058272651650687)
     | > stopnet_loss: 0.0028458628803491592  (0.005207596177404577)
     | > loss: 0.19551271200180054  (0.19694933532313866)
     | > align_error: 0.5521283745765686  (0.5809338946234096)

   --> STEP: 45
     | > decoder_loss: 0.45380258560180664  (0.4563268608517117)
     | > postnet_loss: 0.3090408444404602  (0.31054846247037254)
     | > stopnet_loss: 0.0034852081444114447  (0.005169320887782507)
     | > loss: 0.19419606029987335  (0.19688815143373278)
     | > align_error: 0.5538392663002014  (0.5803317917717827)

   --> STEP: 46
     | > decoder_loss: 0.4445838928222656  (0.4560715789380281)
     | > postnet_loss: 0.3005140721797943  (0.31033032355101214)
     | > stopnet_loss: 0.0033466483000665903  (0.005129697570658248)
     | > loss: 0.18962115049362183  (0.19673017315242602)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34718108177185064 (+0.0035588416186246308)
     | > avg_decoder_loss: 0.4517640101187157 (+0.0005403553897684321)
     | > avg_postnet_loss: 0.30674167970816296 (+0.0008452196012843638)
     | > avg_stopnet_loss: 0.004544992719522929 (+2.4533223812297014e-06)
     | > avg_loss: 0.19417141490813458 (+0.0003488465692057796)
     | > avg_align_error: 0.5731109249772448 (-0.00010936774990766285)


 > EPOCH: 19/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 23:20:32)

   --> TIME: 2025-12-27 23:20:40 -- STEP: 6/150 -- GLOBAL_STEP: 2875
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47768163681030273  (0.48411478102207184)
     | > postnet_loss: 0.4118848145008087  (0.42341792583465576)
     | > stopnet_loss: 0.012266035191714764  (0.013905444803337256)
     | > loss: 0.2346576452255249  (0.24078862369060516)
     | > align_error: 0.7011277079582214  (0.7107248504956564)
     | > grad_norm: tensor(0.2780, device='cuda:0')  (tensor(0.3048, device='cuda:0'))
     | > step_time: 0.5895  (0.48398590087890625)
     | > loader_time: 1.0099  (0.7271628379821777)


   --> TIME: 2025-12-27 23:21:23 -- STEP: 31/150 -- GLOBAL_STEP: 2900
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.5005666017532349  (0.4908886869107523)
     | > postnet_loss: 0.42229658365249634  (0.4195744914393271)
     | > stopnet_loss: 0.006391642149537802  (0.009214811928329932)
     | > loss: 0.23710744082927704  (0.2368306060952525)
     | > align_error: 0.6462389826774597  (0.6657597316849616)
     | > grad_norm: tensor(0.1962, device='cuda:0')  (tensor(0.2398, device='cuda:0'))
     | > step_time: 1.0279  (0.7365416326830464)
     | > loader_time: 0.9889  (0.8843137525743053)


   --> TIME: 2025-12-27 23:22:19 -- STEP: 56/150 -- GLOBAL_STEP: 2925
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.5010960698127747  (0.4957961429442678)
     | > postnet_loss: 0.41619008779525757  (0.4190703108906746)
     | > stopnet_loss: 0.004555942956358194  (0.007401302199078988)
     | > loss: 0.23387748003005981  (0.23611791591559136)
     | > align_error: 0.6176849603652954  (0.6453321639980587)
     | > grad_norm: tensor(0.1459, device='cuda:0')  (tensor(0.2129, device='cuda:0'))
     | > step_time: 1.1685  (0.9167832221303668)
     | > loader_time: 1.212  (0.967317738703319)


   --> TIME: 2025-12-27 23:23:28 -- STEP: 81/150 -- GLOBAL_STEP: 2950
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5068218111991882  (0.49819977011209654)
     | > postnet_loss: 0.41708385944366455  (0.41846312637682315)
     | > stopnet_loss: 0.0039355861954391  (0.006420592535977008)
     | > loss: 0.23491200804710388  (0.23558631594534274)
     | > align_error: 0.6944372355937958  (0.6358275711536407)
     | > grad_norm: tensor(0.1404, device='cuda:0')  (tensor(0.1991, device='cuda:0'))
     | > step_time: 1.4953  (1.0855667502791797)
     | > loader_time: 1.4064  (1.0725738472408715)


   --> TIME: 2025-12-27 23:24:49 -- STEP: 106/150 -- GLOBAL_STEP: 2975
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5006561875343323  (0.49892077412245406)
     | > postnet_loss: 0.41227540373802185  (0.4177593898098424)
     | > stopnet_loss: 0.0034599308855831623  (0.005779627060412234)
     | > loss: 0.2316928207874298  (0.2349496676393275)
     | > align_error: 0.6259430646896362  (0.6310002961248722)
     | > grad_norm: tensor(0.1541, device='cuda:0')  (tensor(0.1866, device='cuda:0'))
     | > step_time: 1.7506  (1.2214422225952146)
     | > loader_time: 1.5151  (1.1888041068922799)


   --> TIME: 2025-12-27 23:26:22 -- STEP: 131/150 -- GLOBAL_STEP: 3000
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5018581748008728  (0.4994868217533781)
     | > postnet_loss: 0.41122302412986755  (0.417049033496216)
     | > stopnet_loss: 0.003221295541152358  (0.005329604720952741)
     | > loss: 0.2314915806055069  (0.23446356840716062)
     | > align_error: 0.5938147902488708  (0.627679281107342)
     | > grad_norm: tensor(0.1219, device='cuda:0')  (tensor(0.1788, device='cuda:0'))
     | > step_time: 1.849  (1.352169486402555)
     | > loader_time: 2.2318  (1.311191729916871)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4744792580604553  (0.4744792580604553)
     | > postnet_loss: 0.3356612026691437  (0.3356612026691437)
     | > stopnet_loss: 0.012506584636867046  (0.012506584636867046)
     | > loss: 0.21504171192646027  (0.21504171192646027)
     | > align_error: 0.719006359577179  (0.719006359577179)

   --> STEP: 1
     | > decoder_loss: 0.45443740487098694  (0.45443740487098694)
     | > postnet_loss: 0.32114800810813904  (0.32114800810813904)
     | > stopnet_loss: 0.009929507039487362  (0.009929507039487362)
     | > loss: 0.20382586121559143  (0.20382586121559143)
     | > align_error: 0.6600152254104614  (0.6600152254104614)

   --> STEP: 2
     | > decoder_loss: 0.44864189624786377  (0.45153965055942535)
     | > postnet_loss: 0.314881831407547  (0.318014919757843)
     | > stopnet_loss: 0.011207181960344315  (0.010568344499915838)
     | > loss: 0.2020881026983261  (0.20295698195695877)
     | > align_error: 0.6576262712478638  (0.6588207483291626)

   --> STEP: 3
     | > decoder_loss: 0.4508426785469055  (0.4513073265552521)
     | > postnet_loss: 0.31178727746009827  (0.3159390389919281)
     | > stopnet_loss: 0.008609111420810223  (0.009915266806880632)
     | > loss: 0.19926661252975464  (0.2017268588145574)
     | > align_error: 0.7351645231246948  (0.6842686732610067)

   --> STEP: 4
     | > decoder_loss: 0.46178752183914185  (0.4539273753762245)
     | > postnet_loss: 0.3229261636734009  (0.3176858201622963)
     | > stopnet_loss: 0.008443488739430904  (0.009547322290018201)
     | > loss: 0.20462191104888916  (0.20245062187314034)
     | > align_error: 0.6048413515090942  (0.6644118428230286)

   --> STEP: 5
     | > decoder_loss: 0.44073063135147095  (0.4512880265712738)
     | > postnet_loss: 0.30522316694259644  (0.31519328951835635)
     | > stopnet_loss: 0.008458114229142666  (0.009329480677843094)
     | > loss: 0.1949465572834015  (0.20094980895519257)
     | > align_error: 0.643184632062912  (0.6601664006710053)

   --> STEP: 6
     | > decoder_loss: 0.45764097571372986  (0.4523468514283498)
     | > postnet_loss: 0.3156401515007019  (0.31526776651541394)
     | > stopnet_loss: 0.0074027846567332745  (0.00900836467432479)
     | > loss: 0.2007230520248413  (0.20091201613346735)
     | > align_error: 0.5952402353286743  (0.6493453731139501)

   --> STEP: 7
     | > decoder_loss: 0.46390417218208313  (0.4539978972503117)
     | > postnet_loss: 0.3138788342475891  (0.3150693476200104)
     | > stopnet_loss: 0.006547349970787764  (0.008656791145248073)
     | > loss: 0.2009931057691574  (0.20092360036713736)
     | > align_error: 0.5802412629127502  (0.6394733573709216)

   --> STEP: 8
     | > decoder_loss: 0.45916834473609924  (0.45464420318603516)
     | > postnet_loss: 0.3138771057128906  (0.3149203173816204)
     | > stopnet_loss: 0.007161270827054977  (0.008469851105473936)
     | > loss: 0.20042262971401215  (0.2008609790354967)
     | > align_error: 0.5757895708084106  (0.6315128840506077)

   --> STEP: 9
     | > decoder_loss: 0.45766159892082214  (0.45497946937878925)
     | > postnet_loss: 0.3152502477169037  (0.314956976307763)
     | > stopnet_loss: 0.0068278806284070015  (0.008287409941355387)
     | > loss: 0.20005583763122559  (0.2007715188794666)
     | > align_error: 0.5931558609008789  (0.6272509925895267)

   --> STEP: 10
     | > decoder_loss: 0.48813122510910034  (0.4582946449518204)
     | > postnet_loss: 0.33051934838294983  (0.31651321351528167)
     | > stopnet_loss: 0.005669041071087122  (0.00802557305432856)
     | > loss: 0.21033169329166412  (0.20172753632068635)
     | > align_error: 0.5864841341972351  (0.6231743067502975)

   --> STEP: 11
     | > decoder_loss: 0.47288861870765686  (0.4596213698387146)
     | > postnet_loss: 0.3224632441997528  (0.31705412539568817)
     | > stopnet_loss: 0.005995376966893673  (0.007841009773652662)
     | > loss: 0.20483334362506866  (0.20200988243926654)
     | > align_error: 0.595416933298111  (0.6206509091637351)

   --> STEP: 12
     | > decoder_loss: 0.4642173647880554  (0.46000436941782635)
     | > postnet_loss: 0.31291210651397705  (0.3167089571555456)
     | > stopnet_loss: 0.00802429486066103  (0.00785628353090336)
     | > loss: 0.20230665802955627  (0.20203461373845735)
     | > align_error: 0.588760256767273  (0.6179933547973633)

   --> STEP: 13
     | > decoder_loss: 0.45833057165145874  (0.45987561574349034)
     | > postnet_loss: 0.3150544762611389  (0.31658168939443737)
     | > stopnet_loss: 0.0057211993262171745  (0.007692046284389038)
     | > loss: 0.19906745851039886  (0.2018063710286067)
     | > align_error: 0.5880158841609955  (0.6156873955176427)

   --> STEP: 14
     | > decoder_loss: 0.46144190430641174  (0.45998749349798473)
     | > postnet_loss: 0.31328871846199036  (0.3163464771849768)
     | > stopnet_loss: 0.005126054398715496  (0.00750876114969807)
     | > loss: 0.1988087147474289  (0.20159225272280829)
     | > align_error: 0.5553653836250305  (0.6113786803824561)

   --> STEP: 15
     | > decoder_loss: 0.4664445221424103  (0.46041796207427976)
     | > postnet_loss: 0.31999728083610535  (0.3165898640950521)
     | > stopnet_loss: 0.005071473773568869  (0.00734627532462279)
     | > loss: 0.2016819268465042  (0.20159823099772137)
     | > align_error: 0.5893226265907288  (0.609908276796341)

   --> STEP: 16
     | > decoder_loss: 0.46578449010849  (0.4607533700764179)
     | > postnet_loss: 0.3117377758026123  (0.3162866085767746)
     | > stopnet_loss: 0.005282391328364611  (0.007217282574856654)
     | > loss: 0.1996629536151886  (0.20147727616131306)
     | > align_error: 0.607381284236908  (0.6097503397613764)

   --> STEP: 17
     | > decoder_loss: 0.4737358093261719  (0.4615170429734623)
     | > postnet_loss: 0.32235297560691833  (0.31664345369619484)
     | > stopnet_loss: 0.004983275663107634  (0.007085870403577299)
     | > loss: 0.20400547981262207  (0.20162599402315476)
     | > align_error: 0.5593294501304626  (0.606784405077205)

   --> STEP: 18
     | > decoder_loss: 0.4693935513496399  (0.46195462677213883)
     | > postnet_loss: 0.3150654733181  (0.316555788119634)
     | > stopnet_loss: 0.0054978178814053535  (0.006997645263456636)
     | > loss: 0.20161256194114685  (0.20162524779637656)
     | > align_error: 0.6047898530960083  (0.6066735966338052)

   --> STEP: 19
     | > decoder_loss: 0.46861106157302856  (0.46230496544586985)
     | > postnet_loss: 0.3143785893917084  (0.31644119871290105)
     | > stopnet_loss: 0.004916321486234665  (0.006888101906760743)
     | > loss: 0.2006637305021286  (0.20157464162299507)
     | > align_error: 0.6015766859054565  (0.6064053381744184)

   --> STEP: 20
     | > decoder_loss: 0.46315130591392517  (0.4623472824692726)
     | > postnet_loss: 0.3120431900024414  (0.3162212982773781)
     | > stopnet_loss: 0.00465842429548502  (0.006776618026196957)
     | > loss: 0.19845706224441528  (0.20141876265406608)
     | > align_error: 0.623493105173111  (0.607259726524353)

   --> STEP: 21
     | > decoder_loss: 0.4602307975292206  (0.46224649747212726)
     | > postnet_loss: 0.3083431124687195  (0.3158461465722039)
     | > stopnet_loss: 0.004148736130446196  (0.006651480793065968)
     | > loss: 0.1962922066450119  (0.20117464093934923)
     | > align_error: 0.5618909597396851  (0.6050993090584165)

   --> STEP: 22
     | > decoder_loss: 0.46278300881385803  (0.4622708843512969)
     | > postnet_loss: 0.3123297393321991  (0.31568630987947643)
     | > stopnet_loss: 0.005013426300138235  (0.006577023770660162)
     | > loss: 0.19879160821437836  (0.20106632127003235)
     | > align_error: 0.6264765560626984  (0.6060710021040656)

   --> STEP: 23
     | > decoder_loss: 0.43461886048316956  (0.461068622443987)
     | > postnet_loss: 0.30111002922058105  (0.315052558546481)
     | > stopnet_loss: 0.004684488754719496  (0.006494739639532307)
     | > loss: 0.18861670792102814  (0.20052503373311914)
     | > align_error: 0.5675743222236633  (0.6043972334136134)

   --> STEP: 24
     | > decoder_loss: 0.4693836569786072  (0.4614150822162628)
     | > postnet_loss: 0.31646373867988586  (0.3151113577187062)
     | > stopnet_loss: 0.004520520102232695  (0.006412480492144823)
     | > loss: 0.20098237693309784  (0.2005440896997849)
     | > align_error: 0.5805920362472534  (0.6034053501983484)

   --> STEP: 25
     | > decoder_loss: 0.468970388174057  (0.4617172944545746)
     | > postnet_loss: 0.3132179379463196  (0.31503562092781073)
     | > stopnet_loss: 0.0037993299774825573  (0.0063079544715583325)
     | > loss: 0.1993464082479477  (0.2004961824417114)
     | > align_error: 0.5594571232795715  (0.6016474211215973)

   --> STEP: 26
     | > decoder_loss: 0.4434351921081543  (0.46101413667201996)
     | > postnet_loss: 0.30115583539009094  (0.3145017830225138)
     | > stopnet_loss: 0.0045642186887562275  (0.0062408877106813285)
     | > loss: 0.19071197509765625  (0.2001198667746324)
     | > align_error: 0.5481821298599243  (0.5995910637653791)

   --> STEP: 27
     | > decoder_loss: 0.44091150164604187  (0.4602695946340208)
     | > postnet_loss: 0.29824212193489075  (0.3138995733526019)
     | > stopnet_loss: 0.0040342481806874275  (0.0061591603206815546)
     | > loss: 0.1888226568698883  (0.1997014515929752)
     | > align_error: 0.5428253412246704  (0.5974886295972047)

   --> STEP: 28
     | > decoder_loss: 0.44625067710876465  (0.4597689190081188)
     | > postnet_loss: 0.301626056432724  (0.31346123346260624)
     | > stopnet_loss: 0.004040643107146025  (0.006083498991626714)
     | > loss: 0.19100983440876007  (0.19939103669353894)
     | > align_error: 0.5670300424098969  (0.5964008229119437)

   --> STEP: 29
     | > decoder_loss: 0.44226086139678955  (0.45916519288359015)
     | > postnet_loss: 0.29773423075675964  (0.3129189230244736)
     | > stopnet_loss: 0.003724444191902876  (0.006002152274394858)
     | > loss: 0.18872322142124176  (0.1990231809944942)
     | > align_error: 0.5414831638336182  (0.5945071105299324)

   --> STEP: 30
     | > decoder_loss: 0.4414646625518799  (0.4585751752058665)
     | > postnet_loss: 0.29830867052078247  (0.3124319146076839)
     | > stopnet_loss: 0.0030057227704674006  (0.005902271290930609)
     | > loss: 0.1879490613937378  (0.19865404367446898)
     | > align_error: 0.5348109304904938  (0.5925172378619512)

   --> STEP: 31
     | > decoder_loss: 0.4413084387779236  (0.4580181837081909)
     | > postnet_loss: 0.30061131715774536  (0.3120506050125246)
     | > stopnet_loss: 0.004082033410668373  (0.005843553939954408)
     | > loss: 0.18956197798252106  (0.19836075123279326)
     | > align_error: 0.5606107115745544  (0.5914879950784868)

   --> STEP: 32
     | > decoder_loss: 0.447836697101593  (0.45770001225173473)
     | > postnet_loss: 0.30312949419021606  (0.31177182029932743)
     | > stopnet_loss: 0.0040251449681818485  (0.005786728659586515)
     | > loss: 0.19176669418811798  (0.19815468695014715)
     | > align_error: 0.532381534576416  (0.5896409181877971)

   --> STEP: 33
     | > decoder_loss: 0.44612762331962585  (0.4573493337992466)
     | > postnet_loss: 0.3021218180656433  (0.3114793959892158)
     | > stopnet_loss: 0.004126186482608318  (0.005736409199678085)
     | > loss: 0.19118854403495789  (0.19794359171029294)
     | > align_error: 0.5469409823417664  (0.5883469807379174)

   --> STEP: 34
     | > decoder_loss: 0.451890230178833  (0.45718877192805796)
     | > postnet_loss: 0.30392342805862427  (0.311257161638316)
     | > stopnet_loss: 0.0034994236193597317  (0.00567061550613931)
     | > loss: 0.1924528330564499  (0.1977820988087093)
     | > align_error: 0.5644068121910095  (0.5876428581335965)

   --> STEP: 35
     | > decoder_loss: 0.4494534432888031  (0.45696776253836496)
     | > postnet_loss: 0.30255213379859924  (0.3110084465571813)
     | > stopnet_loss: 0.0036663012579083443  (0.005613349384761282)
     | > loss: 0.19166769087314606  (0.19760740143912178)
     | > align_error: 0.5348314642906189  (0.5861339611666543)

   --> STEP: 36
     | > decoder_loss: 0.4564284384250641  (0.4569527813129955)
     | > postnet_loss: 0.3070341646671295  (0.31089804983801317)
     | > stopnet_loss: 0.0038504190742969513  (0.005564379098359495)
     | > loss: 0.19471606612205505  (0.19752708656920326)
     | > align_error: 0.6349518895149231  (0.587490014731884)

   --> STEP: 37
     | > decoder_loss: 0.44806864857673645  (0.4567126696174209)
     | > postnet_loss: 0.3037109971046448  (0.31070380516954377)
     | > stopnet_loss: 0.0037092212587594986  (0.005514239697289225)
     | > loss: 0.19165414571762085  (0.19736835843807943)
     | > align_error: 0.5201119184494019  (0.5856689851026278)

   --> STEP: 38
     | > decoder_loss: 0.4371316432952881  (0.456197379451049)
     | > postnet_loss: 0.29720091819763184  (0.310348466038704)
     | > stopnet_loss: 0.0032522256951779127  (0.005454713013023138)
     | > loss: 0.1868353635072708  (0.1970911743609529)
     | > align_error: 0.5521249175071716  (0.5847862464816946)

   --> STEP: 39
     | > decoder_loss: 0.45011255145072937  (0.4560413582202716)
     | > postnet_loss: 0.3054724931716919  (0.31022344109339595)
     | > stopnet_loss: 0.0036023720167577267  (0.005407217090041974)
     | > loss: 0.19249863922595978  (0.1969734170497992)
     | > align_error: 0.5470542311668396  (0.583818758909519)

   --> STEP: 40
     | > decoder_loss: 0.44782692193984985  (0.455835997313261)
     | > postnet_loss: 0.30444422364234924  (0.3100789606571198)
     | > stopnet_loss: 0.0031522123608738184  (0.005350841971812769)
     | > loss: 0.1912200003862381  (0.19682958163321018)
     | > align_error: 0.5852939486503601  (0.58385563865304)

   --> STEP: 41
     | > decoder_loss: 0.4375569224357605  (0.45539016621868783)
     | > postnet_loss: 0.2962213158607483  (0.30974096932062295)
     | > stopnet_loss: 0.00380796380341053  (0.005313210796973691)
     | > loss: 0.18725252151489258  (0.1965959948010561)
     | > align_error: 0.5048305094242096  (0.5819281964767271)

   --> STEP: 42
     | > decoder_loss: 0.4431091547012329  (0.45509776118255796)
     | > postnet_loss: 0.29962223768234253  (0.3095000471387591)
     | > stopnet_loss: 0.00339293060824275  (0.005267489840099145)
     | > loss: 0.1890757828950882  (0.19641694213662828)
     | > align_error: 0.5806135535240173  (0.5818968954540436)

   --> STEP: 43
     | > decoder_loss: 0.44162753224372864  (0.45478450004444565)
     | > postnet_loss: 0.29889804124832153  (0.3092534888622373)
     | > stopnet_loss: 0.0030542209278792143  (0.0052160184700475185)
     | > loss: 0.18818561732769012  (0.1962255159782809)
     | > align_error: 0.5529317855834961  (0.5812232882477517)

   --> STEP: 44
     | > decoder_loss: 0.45985648036003113  (0.4548997723243453)
     | > postnet_loss: 0.30794116854667664  (0.30922366340052004)
     | > stopnet_loss: 0.0028165734838694334  (0.005161485629452562)
     | > loss: 0.19476598501205444  (0.19619234481995756)
     | > align_error: 0.5520994365215302  (0.5805613825267012)

   --> STEP: 45
     | > decoder_loss: 0.4521847367286682  (0.45483943819999695)
     | > postnet_loss: 0.3068290054798126  (0.3091704487800599)
     | > stopnet_loss: 0.003464776324108243  (0.005123780978222688)
     | > loss: 0.19321821630001068  (0.19612625307506984)
     | > align_error: 0.5537286102771759  (0.579965098698934)

   --> STEP: 46
     | > decoder_loss: 0.4435166120529175  (0.45459328980549524)
     | > postnet_loss: 0.2986990511417389  (0.30894280970096594)
     | > stopnet_loss: 0.0033192019909620285  (0.005084551000238761)
     | > loss: 0.18887311220169067  (0.19596857609956161)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3510656284563469 (+0.0038845466844962817)
     | > avg_decoder_loss: 0.4505801313754284 (-0.0011838787432872921)
     | > avg_postnet_loss: 0.305578967387026 (-0.0011627123211369605)
     | > avg_stopnet_loss: 0.004508430378116443 (-3.6562341406486815e-05)
     | > avg_loss: 0.19354820612705115 (-0.0006232087810834341)
     | > avg_align_error: 0.5728639508738664 (-0.00024697410337837233)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_3020.pth

 > EPOCH: 20/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 23:29:55)

   --> TIME: 2025-12-27 23:30:02 -- STEP: 5/150 -- GLOBAL_STEP: 3025
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.487697958946228  (0.4812698721885681)
     | > postnet_loss: 0.4214114546775818  (0.42248609066009524)
     | > stopnet_loss: 0.012553185224533081  (0.013728109188377857)
     | > loss: 0.23983053863048553  (0.23966709971427919)
     | > align_error: 0.7259517312049866  (0.7124520361423492)
     | > grad_norm: tensor(0.2392, device='cuda:0')  (tensor(0.3006, device='cuda:0'))
     | > step_time: 0.5513  (0.4730091094970703)
     | > loader_time: 0.6803  (0.654608678817749)


   --> TIME: 2025-12-27 23:30:44 -- STEP: 30/150 -- GLOBAL_STEP: 3050
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.4918450117111206  (0.4895420432090759)
     | > postnet_loss: 0.4127282202243805  (0.41869569619496666)
     | > stopnet_loss: 0.006170629523694515  (0.009241083326439062)
     | > loss: 0.23231393098831177  (0.23630051761865617)
     | > align_error: 0.6116749048233032  (0.6663102398316065)
     | > grad_norm: tensor(0.1941, device='cuda:0')  (tensor(0.2516, device='cuda:0'))
     | > step_time: 0.9592  (0.7023885806401571)
     | > loader_time: 0.9963  (0.8908930937449138)


   --> TIME: 2025-12-27 23:31:39 -- STEP: 55/150 -- GLOBAL_STEP: 3075
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.5029833316802979  (0.4952233764258298)
     | > postnet_loss: 0.41567376255989075  (0.41873290592973883)
     | > stopnet_loss: 0.004469139501452446  (0.007406163867563008)
     | > loss: 0.23413340747356415  (0.23589523380452937)
     | > align_error: 0.6512522995471954  (0.6455264118584719)
     | > grad_norm: tensor(0.2560, device='cuda:0')  (tensor(0.2377, device='cuda:0'))
     | > step_time: 1.2987  (0.9007854981855913)
     | > loader_time: 1.1981  (0.9686863205649636)


   --> TIME: 2025-12-27 23:32:48 -- STEP: 80/150 -- GLOBAL_STEP: 3100
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4937581717967987  (0.4974347032606602)
     | > postnet_loss: 0.40819281339645386  (0.41797768138349056)
     | > stopnet_loss: 0.0042252629064023495  (0.006421557042631321)
     | > loss: 0.22971300780773163  (0.23527465332299471)
     | > align_error: 0.5871796011924744  (0.6349147468805312)
     | > grad_norm: tensor(0.3205, device='cuda:0')  (tensor(0.2369, device='cuda:0'))
     | > step_time: 1.5585  (1.0641727477312088)
     | > loader_time: 1.754  (1.0787062138319017)


   --> TIME: 2025-12-27 23:34:12 -- STEP: 105/150 -- GLOBAL_STEP: 3125
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5030348896980286  (0.49843245347340903)
     | > postnet_loss: 0.41396045684814453  (0.4173962462516058)
     | > stopnet_loss: 0.0036872972268611193  (0.0057776682145361385)
     | > loss: 0.23293612897396088  (0.2347348431746165)
     | > align_error: 0.6142514050006866  (0.6308651399044761)
     | > grad_norm: tensor(0.1689, device='cuda:0')  (tensor(0.2222, device='cuda:0'))
     | > step_time: 1.846  (1.2116106759934198)
     | > loader_time: 1.6392  (1.2233555816468744)


   --> TIME: 2025-12-27 23:35:42 -- STEP: 130/150 -- GLOBAL_STEP: 3150
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5034539103507996  (0.4991688315684979)
     | > postnet_loss: 0.41241589188575745  (0.4167946240076652)
     | > stopnet_loss: 0.003162943059578538  (0.005325001053727017)
     | > loss: 0.23213040828704834  (0.2343158654295481)
     | > align_error: 0.5986908078193665  (0.627667429584723)
     | > grad_norm: tensor(0.1427, device='cuda:0')  (tensor(0.2051, device='cuda:0'))
     | > step_time: 2.0893  (1.3349999372775738)
     | > loader_time: 2.1227  (1.3241383075714115)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47441425919532776  (0.47441425919532776)
     | > postnet_loss: 0.33422163128852844  (0.33422163128852844)
     | > stopnet_loss: 0.012442233972251415  (0.012442233972251415)
     | > loss: 0.21460120379924774  (0.21460120379924774)
     | > align_error: 0.7195327877998352  (0.7195327877998352)

   --> STEP: 1
     | > decoder_loss: 0.4544735252857208  (0.4544735252857208)
     | > postnet_loss: 0.31895190477371216  (0.31895190477371216)
     | > stopnet_loss: 0.009878621436655521  (0.009878621436655521)
     | > loss: 0.2032349854707718  (0.2032349854707718)
     | > align_error: 0.6603317260742188  (0.6603317260742188)

   --> STEP: 2
     | > decoder_loss: 0.44966205954551697  (0.4520677924156189)
     | > postnet_loss: 0.31497305631637573  (0.31696248054504395)
     | > stopnet_loss: 0.011252017691731453  (0.010565319564193487)
     | > loss: 0.20241078734397888  (0.20282288640737534)
     | > align_error: 0.6580759286880493  (0.659203827381134)

   --> STEP: 3
     | > decoder_loss: 0.4525735378265381  (0.4522363742192586)
     | > postnet_loss: 0.31169673800468445  (0.31520723303159076)
     | > stopnet_loss: 0.008728232234716415  (0.009952957121034464)
     | > loss: 0.19979581236839294  (0.20181386172771454)
     | > align_error: 0.7366023063659668  (0.6850033203760783)

   --> STEP: 4
     | > decoder_loss: 0.46233975887298584  (0.45476222038269043)
     | > postnet_loss: 0.3217720687389374  (0.31684844195842743)
     | > stopnet_loss: 0.008391660638153553  (0.009562633000314236)
     | > loss: 0.20441962778568268  (0.20246530324220657)
     | > align_error: 0.6058789491653442  (0.6652222275733948)

   --> STEP: 5
     | > decoder_loss: 0.4425109326839447  (0.4523119628429413)
     | > postnet_loss: 0.3053288757801056  (0.31454452872276306)
     | > stopnet_loss: 0.008409782312810421  (0.009332062862813472)
     | > loss: 0.19536973536014557  (0.20104618966579438)
     | > align_error: 0.6441301703453064  (0.6610038161277771)

   --> STEP: 6
     | > decoder_loss: 0.4578615725040436  (0.4532368977864583)
     | > postnet_loss: 0.31458547711372375  (0.31455135345458984)
     | > stopnet_loss: 0.007406082935631275  (0.009011066208283106)
     | > loss: 0.20051784813404083  (0.20095813274383545)
     | > align_error: 0.596122145652771  (0.6501902043819427)

   --> STEP: 7
     | > decoder_loss: 0.4651305079460144  (0.4549359849521092)
     | > postnet_loss: 0.3140903115272522  (0.31448549032211304)
     | > stopnet_loss: 0.006535716820508242  (0.008657444867172412)
     | > loss: 0.2013409286737442  (0.20101281787667954)
     | > align_error: 0.5811077356338501  (0.6403212802750724)

   --> STEP: 8
     | > decoder_loss: 0.4610919654369354  (0.4557054825127125)
     | > postnet_loss: 0.31402337551116943  (0.3144277259707451)
     | > stopnet_loss: 0.007695476524531841  (0.00853719882434234)
     | > loss: 0.20147432386875153  (0.20107050612568855)
     | > align_error: 0.5772810578346252  (0.6324412524700165)

   --> STEP: 9
     | > decoder_loss: 0.45871245861053467  (0.45603959096802604)
     | > postnet_loss: 0.31506961584091187  (0.31449904706743026)
     | > stopnet_loss: 0.006848041899502277  (0.008349514721582333)
     | > loss: 0.20029355585575104  (0.2009841783179177)
     | > align_error: 0.5946052074432373  (0.628237247467041)

   --> STEP: 10
     | > decoder_loss: 0.489454060792923  (0.45938103795051577)
     | > postnet_loss: 0.3300144076347351  (0.3160505831241608)
     | > stopnet_loss: 0.0059268358163535595  (0.008107246831059456)
     | > loss: 0.21079395711421967  (0.2019651561975479)
     | > align_error: 0.5886016488075256  (0.6242736876010895)

   --> STEP: 11
     | > decoder_loss: 0.4727349579334259  (0.46059503067623486)
     | > postnet_loss: 0.3222073018550873  (0.3166102848269723)
     | > stopnet_loss: 0.005978767294436693  (0.007913748691366478)
     | > loss: 0.2047143280506134  (0.20221508091146295)
     | > align_error: 0.5960721969604492  (0.6217099157246676)

   --> STEP: 12
     | > decoder_loss: 0.465728759765625  (0.46102284143368405)
     | > postnet_loss: 0.3130813539028168  (0.3163162072499593)
     | > stopnet_loss: 0.008063001558184624  (0.00792618643026799)
     | > loss: 0.2027655392885208  (0.20226095244288445)
     | > align_error: 0.5898823738098145  (0.6190576205650965)

   --> STEP: 13
     | > decoder_loss: 0.45901960134506226  (0.4608687460422516)
     | > postnet_loss: 0.3146912753582001  (0.31619121248905474)
     | > stopnet_loss: 0.005730701610445976  (0.007757302982589373)
     | > loss: 0.1991584151983261  (0.20202229573176458)
     | > align_error: 0.5882872641086578  (0.6166906700684474)

   --> STEP: 14
     | > decoder_loss: 0.4620860517024994  (0.460955696446555)
     | > postnet_loss: 0.31338754296302795  (0.3159909503800528)
     | > stopnet_loss: 0.005114773288369179  (0.007568550861573645)
     | > loss: 0.19898317754268646  (0.20180521586111613)
     | > align_error: 0.5562101006507874  (0.6123706293957574)

   --> STEP: 15
     | > decoder_loss: 0.4677789509296417  (0.4614105800787608)
     | > postnet_loss: 0.3210095763206482  (0.3163255254427592)
     | > stopnet_loss: 0.005104172974824905  (0.007404259002457062)
     | > loss: 0.20230130851268768  (0.20183828870455425)
     | > align_error: 0.5900564193725586  (0.6108830153942109)

   --> STEP: 16
     | > decoder_loss: 0.4671988785266876  (0.4617723487317562)
     | > postnet_loss: 0.31243547797203064  (0.31608239747583866)
     | > stopnet_loss: 0.005297530442476273  (0.007272588467458263)
     | > loss: 0.20020611584186554  (0.2017362779006362)
     | > align_error: 0.6083612143993378  (0.6107254028320312)

   --> STEP: 17
     | > decoder_loss: 0.4745551645755768  (0.46252427907551036)
     | > postnet_loss: 0.3231346607208252  (0.31649723649024963)
     | > stopnet_loss: 0.004981690552085638  (0.007137829766553991)
     | > loss: 0.20440414547920227  (0.20189321128761067)
     | > align_error: 0.5597665011882782  (0.6077278203823987)

   --> STEP: 18
     | > decoder_loss: 0.4705125689506531  (0.46296807295746273)
     | > postnet_loss: 0.31593310832977295  (0.3164658960368898)
     | > stopnet_loss: 0.00555228628218174  (0.007049744017422199)
     | > loss: 0.2021637111902237  (0.20190823905997807)
     | > align_error: 0.60496786236763  (0.6075744893815782)

   --> STEP: 19
     | > decoder_loss: 0.47012391686439514  (0.4633446963209855)
     | > postnet_loss: 0.31532368063926697  (0.3164057794370149)
     | > stopnet_loss: 0.005069095641374588  (0.006945499366051273)
     | > loss: 0.20143099129199982  (0.20188312075640025)
     | > align_error: 0.6024631857872009  (0.6073054734029268)

   --> STEP: 20
     | > decoder_loss: 0.4633203148841858  (0.4633434772491455)
     | > postnet_loss: 0.3128717839717865  (0.3162290796637535)
     | > stopnet_loss: 0.00467446306720376  (0.006831947551108897)
     | > loss: 0.1987224817276001  (0.20172508880496026)
     | > align_error: 0.6234662234783173  (0.6081135109066963)

   --> STEP: 21
     | > decoder_loss: 0.4606417119503021  (0.4632148217587244)
     | > postnet_loss: 0.30856138467788696  (0.3158639513310932)
     | > stopnet_loss: 0.00414580712094903  (0.006704036102053665)
     | > loss: 0.19644656777381897  (0.2014737306606202)
     | > align_error: 0.5620416104793549  (0.6059196108863467)

   --> STEP: 22
     | > decoder_loss: 0.4636075496673584  (0.46323267302729865)
     | > postnet_loss: 0.31340092420578003  (0.31575199555266986)
     | > stopnet_loss: 0.005038852337747812  (0.0066283459309488535)
     | > loss: 0.19929097592830658  (0.2013745145364241)
     | > align_error: 0.6266426146030426  (0.606861565600742)

   --> STEP: 23
     | > decoder_loss: 0.4347052574157715  (0.4619923506094062)
     | > postnet_loss: 0.30125296115875244  (0.3151216027529343)
     | > stopnet_loss: 0.00468827597796917  (0.006543995063427998)
     | > loss: 0.1886778324842453  (0.20082248488198157)
     | > align_error: 0.567415714263916  (0.6051465285860974)

   --> STEP: 24
     | > decoder_loss: 0.470736563205719  (0.46235669280091923)
     | > postnet_loss: 0.31800466775894165  (0.315241730461518)
     | > stopnet_loss: 0.004548439756035805  (0.00646084692561999)
     | > loss: 0.2017337530851364  (0.20086045439044634)
     | > align_error: 0.5812026560306549  (0.6041488672296206)

   --> STEP: 25
     | > decoder_loss: 0.4705168604850769  (0.4626830995082855)
     | > postnet_loss: 0.3144344389438629  (0.31520943880081176)
     | > stopnet_loss: 0.003816441399976611  (0.0063550707045942545)
     | > loss: 0.20005427300930023  (0.2008282071352005)
     | > align_error: 0.5597102642059326  (0.6023713231086731)

   --> STEP: 26
     | > decoder_loss: 0.4438231289386749  (0.461957716024839)
     | > postnet_loss: 0.3014104664325714  (0.314678709094341)
     | > stopnet_loss: 0.004589882679283619  (0.006287178857466922)
     | > loss: 0.19089828431606293  (0.20044628702677214)
     | > align_error: 0.548276960849762  (0.6002907707140996)

   --> STEP: 27
     | > decoder_loss: 0.44113215804100037  (0.46118639906247455)
     | > postnet_loss: 0.2990471124649048  (0.31409976107102855)
     | > stopnet_loss: 0.004050188232213259  (0.006204327352827898)
     | > loss: 0.18909502029418945  (0.20002586974038017)
     | > align_error: 0.5423663258552551  (0.5981454209045127)

   --> STEP: 28
     | > decoder_loss: 0.44627416133880615  (0.4606538191437721)
     | > postnet_loss: 0.3020477592945099  (0.31366933243615286)
     | > stopnet_loss: 0.004054421558976173  (0.006127545003047479)
     | > loss: 0.19113489985466003  (0.19970833510160446)
     | > align_error: 0.5667389929294586  (0.5970237627625465)

   --> STEP: 29
     | > decoder_loss: 0.442094087600708  (0.4600138284009078)
     | > postnet_loss: 0.29780325293540955  (0.31312222624647207)
     | > stopnet_loss: 0.003729624440893531  (0.006044858087111136)
     | > loss: 0.1887039691209793  (0.19932887420572085)
     | > align_error: 0.541339635848999  (0.5951036204551828)

   --> STEP: 30
     | > decoder_loss: 0.4421268701553345  (0.45941759645938873)
     | > postnet_loss: 0.2989824712276459  (0.31265090107917787)
     | > stopnet_loss: 0.0030692594591528177  (0.005945671466179192)
     | > loss: 0.18834660947322845  (0.19896279871463776)
     | > align_error: 0.5346867740154266  (0.5930897255738576)

   --> STEP: 31
     | > decoder_loss: 0.44121110439300537  (0.4588302902636989)
     | > postnet_loss: 0.301204651594162  (0.3122816672248225)
     | > stopnet_loss: 0.004095414187759161  (0.005885985747520481)
     | > loss: 0.18969936668872833  (0.19866397832670518)
     | > align_error: 0.559648185968399  (0.5920109662317461)

   --> STEP: 32
     | > decoder_loss: 0.44815051555633545  (0.45849654730409384)
     | > postnet_loss: 0.30357253551483154  (0.3120095068588853)
     | > stopnet_loss: 0.0040357280522584915  (0.005828165194543544)
     | > loss: 0.1919664889574051  (0.19845468178391457)
     | > align_error: 0.5319676995277405  (0.5901346141472459)

   --> STEP: 33
     | > decoder_loss: 0.44633546471595764  (0.4581280296499079)
     | > postnet_loss: 0.3030262589454651  (0.31173728722514527)
     | > stopnet_loss: 0.0041350736282765865  (0.005776859389505152)
     | > loss: 0.191475510597229  (0.1982431917479544)
     | > align_error: 0.5461145043373108  (0.5888006714257327)

   --> STEP: 34
     | > decoder_loss: 0.4522981345653534  (0.457956562147421)
     | > postnet_loss: 0.3051186203956604  (0.31154262055368986)
     | > stopnet_loss: 0.0035060662776231766  (0.005710071356802741)
     | > loss: 0.19286024570465088  (0.1980848698055043)
     | > align_error: 0.5638061165809631  (0.58806553745971)

   --> STEP: 35
     | > decoder_loss: 0.4491097033023834  (0.45770379475184847)
     | > postnet_loss: 0.30284595489501953  (0.3112941443920135)
     | > stopnet_loss: 0.003682233626022935  (0.005652133135923318)
     | > loss: 0.19167114794254303  (0.19790162060941968)
     | > align_error: 0.5342040657997131  (0.5865266382694244)

   --> STEP: 36
     | > decoder_loss: 0.4571698307991028  (0.45768896241982776)
     | > postnet_loss: 0.30832400918006897  (0.3112116406361262)
     | > stopnet_loss: 0.0038711067754775286  (0.00560266018146649)
     | > loss: 0.19524458050727844  (0.19782781393991578)
     | > align_error: 0.6344249546527863  (0.5878571470578512)

   --> STEP: 37
     | > decoder_loss: 0.4479774832725525  (0.45742649001044194)
     | > postnet_loss: 0.3038792908191681  (0.31101346901945165)
     | > stopnet_loss: 0.0037246758583933115  (0.005551903848410459)
     | > loss: 0.1916888803243637  (0.1976618968151711)
     | > align_error: 0.519468754529953  (0.5860088121246647)

   --> STEP: 38
     | > decoder_loss: 0.4373529553413391  (0.4568982390980971)
     | > postnet_loss: 0.29799380898475647  (0.3106708463869597)
     | > stopnet_loss: 0.00327864452265203  (0.005492081234574711)
     | > loss: 0.18711534142494202  (0.19738435588384928)
     | > align_error: 0.5515218079090118  (0.5851012593821475)

   --> STEP: 39
     | > decoder_loss: 0.45020246505737305  (0.45672655258423245)
     | > postnet_loss: 0.3061913251876831  (0.3105559868690295)
     | > stopnet_loss: 0.0036151697859168053  (0.0054439552999937385)
     | > loss: 0.19271361827850342  (0.19726459338114813)
     | > align_error: 0.5466661155223846  (0.5841157428729229)

   --> STEP: 40
     | > decoder_loss: 0.4474358856678009  (0.45649428591132163)
     | > postnet_loss: 0.30495601892471313  (0.3104159876704216)
     | > stopnet_loss: 0.003162901848554611  (0.00538692896370776)
     | > loss: 0.19126088917255402  (0.19711450077593326)
     | > align_error: 0.5847283005714417  (0.5841310568153858)

   --> STEP: 41
     | > decoder_loss: 0.4380629360675812  (0.45604474079318164)
     | > postnet_loss: 0.2971690595149994  (0.31009289186175276)
     | > stopnet_loss: 0.0038258726708590984  (0.005348854419979744)
     | > loss: 0.18763387203216553  (0.1968832659285243)
     | > align_error: 0.5045985579490662  (0.5821912397698659)

   --> STEP: 42
     | > decoder_loss: 0.44311442971229553  (0.45573687624363673)
     | > postnet_loss: 0.30062320828437805  (0.3098674232051486)
     | > stopnet_loss: 0.003397722030058503  (0.005302398886886381)
     | > loss: 0.18933212757110596  (0.19670347692001433)
     | > align_error: 0.5799744129180908  (0.5821384581781569)

   --> STEP: 43
     | > decoder_loss: 0.4418327510356903  (0.4554135244946147)
     | > postnet_loss: 0.29985132813453674  (0.309634490761646)
     | > stopnet_loss: 0.003065705532208085  (0.0052503827623589785)
     | > loss: 0.1884867250919342  (0.1965123896681985)
     | > align_error: 0.5520365536212921  (0.5814384138861368)

   --> STEP: 44
     | > decoder_loss: 0.4600929617881775  (0.4555198753421957)
     | > postnet_loss: 0.30877864360809326  (0.30961503968997434)
     | > stopnet_loss: 0.0028305414598435163  (0.005195386369119991)
     | > loss: 0.19504843652248383  (0.1964791180057959)
     | > align_error: 0.5514429807662964  (0.5807566994970496)

   --> STEP: 45
     | > decoder_loss: 0.45202377438545227  (0.45544218420982363)
     | > postnet_loss: 0.30755895376205444  (0.3095693488915761)
     | > stopnet_loss: 0.003462750231847167  (0.0051568833438472616)
     | > loss: 0.1933584362268448  (0.1964097695218192)
     | > align_error: 0.5530427098274231  (0.5801408330599468)

   --> STEP: 46
     | > decoder_loss: 0.4438762366771698  (0.4551907505678094)
     | > postnet_loss: 0.2994951009750366  (0.3093503435020861)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35937530344182805 (+0.00830967498548113)
     | > avg_decoder_loss: 0.451110252828309 (+0.0005301214528806164)
     | > avg_postnet_loss: 0.30603548432841443 (+0.0004565169413884296)
     | > avg_stopnet_loss: 0.0045375325717031964 (+2.9102193586753866e-05)
     | > avg_loss: 0.19382396882230585 (+0.0002757626952546999)
     | > avg_align_error: 0.5727762132883073 (-8.773758555913336e-05)


 > EPOCH: 21/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 23:39:04)

   --> TIME: 2025-12-27 23:39:10 -- STEP: 4/150 -- GLOBAL_STEP: 3175
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48148098587989807  (0.4829956442117691)
     | > postnet_loss: 0.4230310618877411  (0.42576876282691956)
     | > stopnet_loss: 0.014178892597556114  (0.014539425959810615)
     | > loss: 0.24030689895153046  (0.24173052236437798)
     | > align_error: 0.6885692775249481  (0.7092534676194191)
     | > grad_norm: tensor(0.3289, device='cuda:0')  (tensor(0.3413, device='cuda:0'))
     | > step_time: 0.5053  (0.4426860213279724)
     | > loader_time: 0.6126  (0.6753625869750977)


   --> TIME: 2025-12-27 23:39:50 -- STEP: 29/150 -- GLOBAL_STEP: 3200
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.49679702520370483  (0.4893995985902589)
     | > postnet_loss: 0.4181601405143738  (0.4187502706873006)
     | > stopnet_loss: 0.006145852617919445  (0.009348610817486872)
     | > loss: 0.23488514125347137  (0.2363860771573823)
     | > align_error: 0.6734234690666199  (0.6688590707450077)
     | > grad_norm: tensor(0.2347, device='cuda:0')  (tensor(0.2470, device='cuda:0'))
     | > step_time: 0.8982  (0.6806991840231007)
     | > loader_time: 0.8907  (0.853910807905526)


   --> TIME: 2025-12-27 23:40:45 -- STEP: 54/150 -- GLOBAL_STEP: 3225
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4998275637626648  (0.49500769818270646)
     | > postnet_loss: 0.4132852852344513  (0.4186529285377926)
     | > stopnet_loss: 0.005090454593300819  (0.0074713145365455655)
     | > loss: 0.2333686798810959  (0.23588647031121784)
     | > align_error: 0.5788160860538483  (0.645773923507443)
     | > grad_norm: tensor(0.1476, device='cuda:0')  (tensor(0.2157, device='cuda:0'))
     | > step_time: 1.317  (0.8982286320792304)
     | > loader_time: 1.16  (0.949240212087278)


   --> TIME: 2025-12-27 23:41:53 -- STEP: 79/150 -- GLOBAL_STEP: 3250
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5004909038543701  (0.4974805625933635)
     | > postnet_loss: 0.41245684027671814  (0.4180518271802347)
     | > stopnet_loss: 0.004264541901648045  (0.006455826455184934)
     | > loss: 0.23250149190425873  (0.2353389238632178)
     | > align_error: 0.5968329906463623  (0.6357963632179212)
     | > grad_norm: tensor(0.1161, device='cuda:0')  (tensor(0.2014, device='cuda:0'))
     | > step_time: 1.5998  (1.0722018193595015)
     | > loader_time: 1.5501  (1.0515975952148433)


   --> TIME: 2025-12-27 23:43:14 -- STEP: 104/150 -- GLOBAL_STEP: 3275
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.505632221698761  (0.49833248355067694)
     | > postnet_loss: 0.41644740104675293  (0.41733494515602404)
     | > stopnet_loss: 0.003550977911800146  (0.005811968155635093)
     | > loss: 0.23407088220119476  (0.23472882535022038)
     | > align_error: 0.6152079105377197  (0.6313060315755697)
     | > grad_norm: tensor(0.1736, device='cuda:0')  (tensor(0.1921, device='cuda:0'))
     | > step_time: 1.8831  (1.2180903416413527)
     | > loader_time: 1.6073  (1.1705510432903579)


   --> TIME: 2025-12-27 23:44:48 -- STEP: 129/150 -- GLOBAL_STEP: 3300
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5039589405059814  (0.4989900249381398)
     | > postnet_loss: 0.4131995737552643  (0.4166596993919491)
     | > stopnet_loss: 0.003351720282807946  (0.0053498107189124885)
     | > loss: 0.232641339302063  (0.23426224152709163)
     | > align_error: 0.6646338701248169  (0.6283651278462521)
     | > grad_norm: tensor(0.2198, device='cuda:0')  (tensor(0.1835, device='cuda:0'))
     | > step_time: 1.9926  (1.3394573252330455)
     | > loader_time: 2.0775  (1.3140311352042262)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4741370379924774  (0.4741370379924774)
     | > postnet_loss: 0.33469754457473755  (0.33469754457473755)
     | > stopnet_loss: 0.01246094610542059  (0.01246094610542059)
     | > loss: 0.2146695852279663  (0.2146695852279663)
     | > align_error: 0.7193876504898071  (0.7193876504898071)

   --> STEP: 1
     | > decoder_loss: 0.45495492219924927  (0.45495492219924927)
     | > postnet_loss: 0.3204788565635681  (0.3204788565635681)
     | > stopnet_loss: 0.009910502471029758  (0.009910502471029758)
     | > loss: 0.20376895368099213  (0.20376895368099213)
     | > align_error: 0.6604542136192322  (0.6604542136192322)

   --> STEP: 2
     | > decoder_loss: 0.45017051696777344  (0.45256271958351135)
     | > postnet_loss: 0.31546804308891296  (0.31797344982624054)
     | > stopnet_loss: 0.011175204999744892  (0.010542853735387325)
     | > loss: 0.20258484780788422  (0.20317690074443817)
     | > align_error: 0.6580708026885986  (0.6592625081539154)

   --> STEP: 3
     | > decoder_loss: 0.4509870111942291  (0.4520374834537506)
     | > postnet_loss: 0.3112734854221344  (0.31574012835820514)
     | > stopnet_loss: 0.008670552633702755  (0.009918753368159136)
     | > loss: 0.1992356777191162  (0.20186315973599753)
     | > align_error: 0.7360522747039795  (0.6848590970039368)

   --> STEP: 4
     | > decoder_loss: 0.4613810181617737  (0.4543733671307564)
     | > postnet_loss: 0.3220308721065521  (0.3173128142952919)
     | > stopnet_loss: 0.008463531732559204  (0.009554947959259152)
     | > loss: 0.20431649684906006  (0.20247649401426315)
     | > align_error: 0.6054973900318146  (0.6650186702609062)

   --> STEP: 5
     | > decoder_loss: 0.4413246512413025  (0.4517636239528656)
     | > postnet_loss: 0.30529162287712097  (0.3149085760116577)
     | > stopnet_loss: 0.008399187587201595  (0.00932379588484764)
     | > loss: 0.19505324959754944  (0.20099184513092042)
     | > align_error: 0.6438924074172974  (0.6607934176921845)

   --> STEP: 6
     | > decoder_loss: 0.4573844075202942  (0.4527004212141037)
     | > postnet_loss: 0.3150741457939148  (0.31493617097536725)
     | > stopnet_loss: 0.00741229485720396  (0.00900521238024036)
     | > loss: 0.20052693784236908  (0.20091436058282852)
     | > align_error: 0.5957762002944946  (0.6499572147925695)

   --> STEP: 7
     | > decoder_loss: 0.4662473201751709  (0.45463569249425617)
     | > postnet_loss: 0.31498974561691284  (0.31494382449558805)
     | > stopnet_loss: 0.006506066769361496  (0.008648191578686237)
     | > loss: 0.20181533694267273  (0.2010430714913777)
     | > align_error: 0.5810524523258209  (0.6401136772973197)

   --> STEP: 8
     | > decoder_loss: 0.46068882942199707  (0.45539233461022377)
     | > postnet_loss: 0.31451544165611267  (0.3148902766406536)
     | > stopnet_loss: 0.0076404293067753315  (0.008522221294697374)
     | > loss: 0.20144151151180267  (0.20109287649393082)
     | > align_error: 0.5771504044532776  (0.6322432681918144)

   --> STEP: 9
     | > decoder_loss: 0.45899543166160583  (0.455792678727044)
     | > postnet_loss: 0.31593069434165955  (0.31500587860743207)
     | > stopnet_loss: 0.0068549201823771  (0.008336965615550676)
     | > loss: 0.2005864530801773  (0.201036607225736)
     | > align_error: 0.5940646827220917  (0.628001203139623)

   --> STEP: 10
     | > decoder_loss: 0.4879601299762726  (0.45900942385196686)
     | > postnet_loss: 0.33025214076042175  (0.31653050482273104)
     | > stopnet_loss: 0.005701142828911543  (0.008073383336886763)
     | > loss: 0.21025420725345612  (0.201958367228508)
     | > align_error: 0.5874329805374146  (0.6239443808794022)

   --> STEP: 11
     | > decoder_loss: 0.47278502583503723  (0.46026175130497327)
     | > postnet_loss: 0.322557270526886  (0.3170783926140178)
     | > stopnet_loss: 0.0060074832290410995  (0.007885574236173521)
     | > loss: 0.20484305918216705  (0.2022206119515679)
     | > align_error: 0.5960887968540192  (0.6214120550589128)

   --> STEP: 12
     | > decoder_loss: 0.46536919474601746  (0.46068737159172696)
     | > postnet_loss: 0.3133936822414398  (0.316771333416303)
     | > stopnet_loss: 0.008001653477549553  (0.007895247506288191)
     | > loss: 0.20269237458705902  (0.2022599255045255)
     | > align_error: 0.589537113904953  (0.6187558099627495)

   --> STEP: 13
     | > decoder_loss: 0.45843517780303955  (0.4605141259156741)
     | > postnet_loss: 0.31470754742622375  (0.3166125806478354)
     | > stopnet_loss: 0.0057522631250321865  (0.007730402553883882)
     | > loss: 0.19903793931007385  (0.2020120804126446)
     | > align_error: 0.5881914794445038  (0.6164047076151922)

   --> STEP: 14
     | > decoder_loss: 0.46421265602111816  (0.4607783066374915)
     | > postnet_loss: 0.3145650327205658  (0.31646632722445894)
     | > stopnet_loss: 0.005123948212713003  (0.007544227243800249)
     | > loss: 0.19981837272644043  (0.20185538700648717)
     | > align_error: 0.5562095642089844  (0.6121050545147487)

   --> STEP: 15
     | > decoder_loss: 0.46623775362968445  (0.46114226977030437)
     | > postnet_loss: 0.3203675150871277  (0.31672640641530353)
     | > stopnet_loss: 0.005139926914125681  (0.007383940555155277)
     | > loss: 0.20179124176502228  (0.20185111065705616)
     | > align_error: 0.5898861885070801  (0.6106237967809042)

   --> STEP: 16
     | > decoder_loss: 0.4652281701564789  (0.46139763854444027)
     | > postnet_loss: 0.31194955110549927  (0.3164278529584408)
     | > stopnet_loss: 0.005305003374814987  (0.007254006981384009)
     | > loss: 0.19959942996501923  (0.20171038061380386)
     | > align_error: 0.6080785393714905  (0.6104647181928158)

   --> STEP: 17
     | > decoder_loss: 0.47403568029403687  (0.4621410527650048)
     | > postnet_loss: 0.3231201767921448  (0.31682151906630573)
     | > stopnet_loss: 0.004994271323084831  (0.0071210813544252335)
     | > loss: 0.2042832374572754  (0.20186172513400807)
     | > align_error: 0.5596256852149963  (0.6074741868411794)

   --> STEP: 18
     | > decoder_loss: 0.4693117141723633  (0.4625394228431914)
     | > postnet_loss: 0.3156163990497589  (0.31675456795427537)
     | > stopnet_loss: 0.005541394464671612  (0.007033320971661144)
     | > loss: 0.20177341997623444  (0.20185681929190954)
     | > align_error: 0.6050922870635986  (0.6073418590757582)

   --> STEP: 19
     | > decoder_loss: 0.4685893654823303  (0.46285784087683024)
     | > postnet_loss: 0.31489333510398865  (0.316656608330576)
     | > stopnet_loss: 0.005064360797405243  (0.00692969148880557)
     | > loss: 0.20093503594398499  (0.20180830437886088)
     | > align_error: 0.6022347211837769  (0.6070730623446012)

   --> STEP: 20
     | > decoder_loss: 0.4622430205345154  (0.4628270998597145)
     | > postnet_loss: 0.3123595714569092  (0.31644175648689266)
     | > stopnet_loss: 0.004638455342501402  (0.006815129681490362)
     | > loss: 0.19828909635543823  (0.20163234397768975)
     | > align_error: 0.6236091256141663  (0.6078998655080795)

   --> STEP: 21
     | > decoder_loss: 0.46022170782089233  (0.46270303357215153)
     | > postnet_loss: 0.3087449073791504  (0.31607523986271446)
     | > stopnet_loss: 0.0041549960151314735  (0.006688456649758986)
     | > loss: 0.19639664888381958  (0.20138302516369594)
     | > align_error: 0.5621241629123688  (0.605720070146379)

   --> STEP: 22
     | > decoder_loss: 0.4623551368713379  (0.4626872200857509)
     | > postnet_loss: 0.3124825358390808  (0.3159119351343675)
     | > stopnet_loss: 0.005054233595728874  (0.006614173783666708)
     | > loss: 0.1987636536359787  (0.20126396282152695)
     | > align_error: 0.6266235113143921  (0.6066702265631068)

   --> STEP: 23
     | > decoder_loss: 0.433565616607666  (0.4614210634127907)
     | > postnet_loss: 0.3010255694389343  (0.3152647018432617)
     | > stopnet_loss: 0.004696579184383154  (0.006530800105436989)
     | > loss: 0.18834437429904938  (0.20070224158141925)
     | > align_error: 0.5676037669181824  (0.6049716848394143)

   --> STEP: 24
     | > decoder_loss: 0.46912074089050293  (0.4617418833076954)
     | > postnet_loss: 0.3171038329601288  (0.3153413323064645)
     | > stopnet_loss: 0.004536234308034182  (0.006447693197211872)
     | > loss: 0.20109239220619202  (0.20071849785745144)
     | > align_error: 0.5808075070381165  (0.6039648440976936)

   --> STEP: 25
     | > decoder_loss: 0.46938443183898926  (0.4620475852489471)
     | > postnet_loss: 0.31395959854125977  (0.3152860629558563)
     | > stopnet_loss: 0.00383727066218853  (0.0063432762958109375)
     | > loss: 0.19967328011989594  (0.20067668914794923)
     | > align_error: 0.5599684417247772  (0.602204988002777)

   --> STEP: 26
     | > decoder_loss: 0.4427269399166107  (0.46130448350539577)
     | > postnet_loss: 0.30116021633148193  (0.31474276116261113)
     | > stopnet_loss: 0.004586989060044289  (0.00627572678674299)
     | > loss: 0.1905587911605835  (0.20028753922535822)
     | > align_error: 0.5484948754310608  (0.6001392144423264)

   --> STEP: 27
     | > decoder_loss: 0.4407510459423065  (0.4605432450771332)
     | > postnet_loss: 0.2988899350166321  (0.31415561945350085)
     | > stopnet_loss: 0.0040597086772322655  (0.006193652041946296)
     | > loss: 0.1889699399471283  (0.19986836888172008)
     | > align_error: 0.5427781343460083  (0.5980147299943147)

   --> STEP: 28
     | > decoder_loss: 0.4457736611366272  (0.4600157599364008)
     | > postnet_loss: 0.3017857074737549  (0.3137138368827956)
     | > stopnet_loss: 0.004041636828333139  (0.006116794355745826)
     | > loss: 0.19093148410320282  (0.19954919442534447)
     | > align_error: 0.5670222640037537  (0.5969078562089375)

   --> STEP: 29
     | > decoder_loss: 0.44154679775238037  (0.4593788991714346)
     | > postnet_loss: 0.2978363633155823  (0.313166337794271)
     | > stopnet_loss: 0.003717486746609211  (0.006034059610603185)
     | > loss: 0.188563272356987  (0.19917036952643558)
     | > align_error: 0.5414955914020538  (0.594997088456976)

   --> STEP: 30
     | > decoder_loss: 0.44161495566368103  (0.45878676772117616)
     | > postnet_loss: 0.2987579107284546  (0.3126860568920771)
     | > stopnet_loss: 0.003071357263252139  (0.005935302865691483)
     | > loss: 0.1881645768880844  (0.19880350977182387)
     | > align_error: 0.5348259508609772  (0.5929913838704427)

   --> STEP: 31
     | > decoder_loss: 0.4405452609062195  (0.45819833201746785)
     | > postnet_loss: 0.3009074330329895  (0.31230610128371944)
     | > stopnet_loss: 0.004080991726368666  (0.005875486377326231)
     | > loss: 0.1894441694021225  (0.19850159556634964)
     | > align_error: 0.5603146255016327  (0.5919372948908037)

   --> STEP: 32
     | > decoder_loss: 0.4474351108074188  (0.45786198135465384)
     | > postnet_loss: 0.30346617102622986  (0.3120298534631729)
     | > stopnet_loss: 0.00403059646487236  (0.005817833567562047)
     | > loss: 0.19175592064857483  (0.19829079322516918)
     | > align_error: 0.5321883857250214  (0.590070141479373)

   --> STEP: 33
     | > decoder_loss: 0.4450354278087616  (0.4574732979138692)
     | > postnet_loss: 0.3023277521133423  (0.31173585039196594)
     | > stopnet_loss: 0.00414217310026288  (0.00576705597764389)
     | > loss: 0.19098298251628876  (0.19806934441580917)
     | > align_error: 0.5465930104255676  (0.5887526526595607)

   --> STEP: 34
     | > decoder_loss: 0.4510314464569092  (0.4572838316945469)
     | > postnet_loss: 0.3043636679649353  (0.31151902149705324)
     | > stopnet_loss: 0.0035189285408705473  (0.0057009345824446745)
     | > loss: 0.19236770272254944  (0.19790164907188976)
     | > align_error: 0.5643168091773987  (0.5880339513806736)

   --> STEP: 35
     | > decoder_loss: 0.4479224979877472  (0.4570163650172097)
     | > postnet_loss: 0.30228185653686523  (0.3112551024981907)
     | > stopnet_loss: 0.003682764247059822  (0.00564327257286225)
     | > loss: 0.19123384356498718  (0.19771114034312112)
     | > align_error: 0.5346484780311584  (0.586508652142116)

   --> STEP: 36
     | > decoder_loss: 0.4557446241378784  (0.45698103888167274)
     | > postnet_loss: 0.30746990442276  (0.3111499581072065)
     | > stopnet_loss: 0.0038671079091727734  (0.005593934665537543)
     | > loss: 0.19467073678970337  (0.19762668468885952)
     | > align_error: 0.634719729423523  (0.5878478487332662)

   --> STEP: 37
     | > decoder_loss: 0.4471219778060913  (0.4567145777715219)
     | > postnet_loss: 0.3034956753253937  (0.31094308559958994)
     | > stopnet_loss: 0.0037150795105844736  (0.005543154796484757)
     | > loss: 0.19136948883533478  (0.1974575712874129)
     | > align_error: 0.519877016544342  (0.5860107992146466)

   --> STEP: 38
     | > decoder_loss: 0.43637219071388245  (0.45617925179632085)
     | > postnet_loss: 0.2973175644874573  (0.31058451925453384)
     | > stopnet_loss: 0.0032777420710772276  (0.005483538672131927)
     | > loss: 0.18670019507408142  (0.19717448243969365)
     | > align_error: 0.5518033802509308  (0.5851106039787594)

   --> STEP: 39
     | > decoder_loss: 0.4496575593948364  (0.45601202891423154)
     | > postnet_loss: 0.3057838976383209  (0.3104614263925796)
     | > stopnet_loss: 0.0036147483624517918  (0.005435620971883718)
     | > loss: 0.1924751102924347  (0.19705398571796906)
     | > align_error: 0.546904444694519  (0.5841309588689071)

   --> STEP: 40
     | > decoder_loss: 0.4465775489807129  (0.45577616691589357)
     | > postnet_loss: 0.30445560812950134  (0.31031128093600263)
     | > stopnet_loss: 0.003169266041368246  (0.005378962098620831)
     | > loss: 0.19092756509780884  (0.19690082520246505)
     | > align_error: 0.5851079821586609  (0.5841553844511509)

   --> STEP: 41
     | > decoder_loss: 0.4368061125278473  (0.4553134826625266)
     | > postnet_loss: 0.2965138852596283  (0.3099747590902374)
     | > stopnet_loss: 0.0038273343816399574  (0.005341117520157883)
     | > loss: 0.18715733289718628  (0.19666317904867778)
     | > align_error: 0.504551887512207  (0.582213835745323)

   --> STEP: 42
     | > decoder_loss: 0.44294947385787964  (0.45501910150051117)
     | > postnet_loss: 0.30022886395454407  (0.309742713967959)
     | > stopnet_loss: 0.003405726980417967  (0.0052950367930212185)
     | > loss: 0.18920031189918518  (0.19648549173559463)
     | > align_error: 0.5803484320640564  (0.5821694213719595)

   --> STEP: 43
     | > decoder_loss: 0.44063472747802734  (0.4546845811744069)
     | > postnet_loss: 0.29905253648757935  (0.3094941051893455)
     | > stopnet_loss: 0.003073022235184908  (0.005243362035862235)
     | > loss: 0.1879948377609253  (0.19628803466641626)
     | > align_error: 0.5524170994758606  (0.5814775069092595)

   --> STEP: 44
     | > decoder_loss: 0.45947781205177307  (0.4547935182398016)
     | > postnet_loss: 0.3082880973815918  (0.30946669592098747)
     | > stopnet_loss: 0.002821349771693349  (0.005188316302585669)
     | > loss: 0.19476282596588135  (0.1962533708323132)
     | > align_error: 0.5517509281635284  (0.5808019028468565)

   --> STEP: 45
     | > decoder_loss: 0.45096513628959656  (0.4547084430853526)
     | > postnet_loss: 0.3068348169326782  (0.3094082097212473)
     | > stopnet_loss: 0.0034734040964394808  (0.005150207142449088)
     | > loss: 0.1929233968257904  (0.196179371409946)
     | > align_error: 0.5534376502037048  (0.5801938083436754)

   --> STEP: 46
     | > decoder_loss: 0.44257548451423645  (0.4544446831164153)
     | > postnet_loss: 0.29880857467651367  (0.30917778287244874)
     | > stopnet_loss: 0.003331642597913742  (0.0051106731306113625)
     | > loss: 0.18867765367031097  (0.19601629058951917)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3504845770922574 (-0.008890726349570666)
     | > avg_decoder_loss: 0.4502732681505608 (-0.0008369846777482315)
     | > avg_postnet_loss: 0.3057186969301917 (-0.0003167873982227176)
     | > avg_stopnet_loss: 0.004528123987697516 (-9.408584005680433e-06)
     | > avg_loss: 0.19352611605868195 (-0.00029785276362390145)
     | > avg_align_error: 0.5729316599441298 (+0.00015544665582245543)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_3322.pth

 > EPOCH: 22/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 23:48:09)

   --> TIME: 2025-12-27 23:48:13 -- STEP: 3/150 -- GLOBAL_STEP: 3325
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4768275022506714  (0.48093925913174945)
     | > postnet_loss: 0.41966676712036133  (0.42472581068674725)
     | > stopnet_loss: 0.014353543519973755  (0.014677175941566626)
     | > loss: 0.23847711086273193  (0.2410934418439865)
     | > align_error: 0.7001373171806335  (0.7163651287555695)
     | > grad_norm: tensor(0.3173, device='cuda:0')  (tensor(0.3125, device='cuda:0'))
     | > step_time: 0.4898  (0.46400872866312665)
     | > loader_time: 0.7145  (0.7229298750559489)


   --> TIME: 2025-12-27 23:48:55 -- STEP: 28/150 -- GLOBAL_STEP: 3350
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.49291524291038513  (0.48845123180321287)
     | > postnet_loss: 0.41466572880744934  (0.4181237391063145)
     | > stopnet_loss: 0.006345011293888092  (0.009443084160531206)
     | > loss: 0.2332402467727661  (0.23608682677149773)
     | > align_error: 0.6443082988262177  (0.6686800164835793)
     | > grad_norm: tensor(0.1518, device='cuda:0')  (tensor(0.2324, device='cuda:0'))
     | > step_time: 0.8798  (0.701946565083095)
     | > loader_time: 0.9407  (0.9074031625475202)


   --> TIME: 2025-12-27 23:49:49 -- STEP: 53/150 -- GLOBAL_STEP: 3375
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.5021441578865051  (0.49463717498869264)
     | > postnet_loss: 0.4176441729068756  (0.4184520998091068)
     | > stopnet_loss: 0.004408735316246748  (0.007489764852062713)
     | > loss: 0.23435582220554352  (0.2357620838678108)
     | > align_error: 0.5815716981887817  (0.6468593804341443)
     | > grad_norm: tensor(0.1973, device='cuda:0')  (tensor(0.2336, device='cuda:0'))
     | > step_time: 1.1629  (0.9015103556075186)
     | > loader_time: 1.2038  (0.9684295879220063)


   --> TIME: 2025-12-27 23:50:56 -- STEP: 78/150 -- GLOBAL_STEP: 3400
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5035609602928162  (0.4972170010591165)
     | > postnet_loss: 0.4152716100215912  (0.4178038537502289)
     | > stopnet_loss: 0.004004721064120531  (0.006452569618630106)
     | > loss: 0.23371285200119019  (0.2352077834881269)
     | > align_error: 0.6174614429473877  (0.636061586248569)
     | > grad_norm: tensor(0.2295, device='cuda:0')  (tensor(0.2218, device='cuda:0'))
     | > step_time: 1.5739  (1.0680316778329701)
     | > loader_time: 1.3032  (1.0611448135131445)


   --> TIME: 2025-12-27 23:52:19 -- STEP: 103/150 -- GLOBAL_STEP: 3425
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.508783221244812  (0.49816548853244597)
     | > postnet_loss: 0.417888343334198  (0.417104873842406)
     | > stopnet_loss: 0.003673226572573185  (0.005808827399447996)
     | > loss: 0.2353411167860031  (0.23462641861253572)
     | > align_error: 0.5975529849529266  (0.631325475509884)
     | > grad_norm: tensor(0.1584, device='cuda:0')  (tensor(0.2118, device='cuda:0'))
     | > step_time: 1.7101  (1.2134551886215952)
     | > loader_time: 1.7651  (1.2054855082798939)


   --> TIME: 2025-12-27 23:53:48 -- STEP: 128/150 -- GLOBAL_STEP: 3450
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5046824216842651  (0.4989271597005427)
     | > postnet_loss: 0.4127463698387146  (0.41652119322679937)
     | > stopnet_loss: 0.003406745847314596  (0.005346533111151077)
     | > loss: 0.23276394605636597  (0.23420862178318202)
     | > align_error: 0.6211504936218262  (0.627902563428506)
     | > grad_norm: tensor(0.2034, device='cuda:0')  (tensor(0.2002, device='cuda:0'))
     | > step_time: 2.1042  (1.3417780883610249)
     | > loader_time: 1.8109  (1.3012327440083034)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.475625604391098  (0.475625604391098)
     | > postnet_loss: 0.3346012234687805  (0.3346012234687805)
     | > stopnet_loss: 0.012499136850237846  (0.012499136850237846)
     | > loss: 0.21505583822727203  (0.21505583822727203)
     | > align_error: 0.7195587158203125  (0.7195587158203125)

   --> STEP: 1
     | > decoder_loss: 0.4559740126132965  (0.4559740126132965)
     | > postnet_loss: 0.31968989968299866  (0.31968989968299866)
     | > stopnet_loss: 0.009847162291407585  (0.009847162291407585)
     | > loss: 0.20376314222812653  (0.20376314222812653)
     | > align_error: 0.6605704426765442  (0.6605704426765442)

   --> STEP: 2
     | > decoder_loss: 0.4502839148044586  (0.45312896370887756)
     | > postnet_loss: 0.3152865171432495  (0.3174882084131241)
     | > stopnet_loss: 0.011238113045692444  (0.010542637668550014)
     | > loss: 0.20263071358203888  (0.2031969279050827)
     | > align_error: 0.6578608751296997  (0.659215658903122)

   --> STEP: 3
     | > decoder_loss: 0.453289657831192  (0.45318252841631573)
     | > postnet_loss: 0.31225067377090454  (0.3157423635323842)
     | > stopnet_loss: 0.00871554296463728  (0.009933606100579103)
     | > loss: 0.2001006305217743  (0.20216482877731323)
     | > align_error: 0.7366975843906403  (0.6850429673989614)

   --> STEP: 4
     | > decoder_loss: 0.46326741576194763  (0.4557037502527237)
     | > postnet_loss: 0.32238733768463135  (0.317403607070446)
     | > stopnet_loss: 0.008435561321675777  (0.009559094905853271)
     | > loss: 0.2048492580652237  (0.20283593609929085)
     | > align_error: 0.6059306263923645  (0.6652648821473122)

   --> STEP: 5
     | > decoder_loss: 0.44256627559661865  (0.4530762553215027)
     | > postnet_loss: 0.30529582500457764  (0.31498205065727236)
     | > stopnet_loss: 0.008435570634901524  (0.009334390051662922)
     | > loss: 0.19540110230445862  (0.2013489693403244)
     | > align_error: 0.6439783871173859  (0.6610075831413269)

   --> STEP: 6
     | > decoder_loss: 0.4581928551197052  (0.45392902195453644)
     | > postnet_loss: 0.31467947363853455  (0.31493162115414935)
     | > stopnet_loss: 0.007423297502100468  (0.009015874626735846)
     | > loss: 0.20064137876033783  (0.20123103757699332)
     | > align_error: 0.5957834124565125  (0.6501368880271912)

   --> STEP: 7
     | > decoder_loss: 0.4647296667098999  (0.45547197120530264)
     | > postnet_loss: 0.31397563219070435  (0.3147950513022287)
     | > stopnet_loss: 0.006534321699291468  (0.008661367065672363)
     | > loss: 0.2012106478214264  (0.20122812475476945)
     | > align_error: 0.581108033657074  (0.6402756231171745)

   --> STEP: 8
     | > decoder_loss: 0.46225738525390625  (0.4563201479613781)
     | > postnet_loss: 0.31431886553764343  (0.3147355280816555)
     | > stopnet_loss: 0.007721533998847008  (0.008543887932319194)
     | > loss: 0.20186559855937958  (0.20130780898034573)
     | > align_error: 0.5771304965019226  (0.6323824822902679)

   --> STEP: 9
     | > decoder_loss: 0.4591584801673889  (0.4566355182064904)
     | > postnet_loss: 0.3155989348888397  (0.3148314621713426)
     | > stopnet_loss: 0.006850503850728273  (0.008355734145475758)
     | > loss: 0.20053985714912415  (0.2012224809990989)
     | > align_error: 0.593975692987442  (0.6281150612566206)

   --> STEP: 10
     | > decoder_loss: 0.4899360239505768  (0.45996556878089906)
     | > postnet_loss: 0.3302834630012512  (0.3163766622543335)
     | > stopnet_loss: 0.005964532494544983  (0.008116613980382681)
     | > loss: 0.21101941168308258  (0.20220217406749724)
     | > align_error: 0.5884210467338562  (0.6241456598043442)

   --> STEP: 11
     | > decoder_loss: 0.47273245453834534  (0.4611261947588487)
     | > postnet_loss: 0.32221266627311707  (0.3169072080742229)
     | > stopnet_loss: 0.006010332144796848  (0.007925133813511242)
     | > loss: 0.20474661886692047  (0.20243348723108118)
     | > align_error: 0.595867395401001  (0.6215749084949493)

   --> STEP: 12
     | > decoder_loss: 0.46608200669288635  (0.4615391790866852)
     | > postnet_loss: 0.3132212162017822  (0.3166000420848529)
     | > stopnet_loss: 0.00802676472812891  (0.007933603056396047)
     | > loss: 0.20285256206989288  (0.2024684101343155)
     | > align_error: 0.5893905758857727  (0.6188928807775179)

   --> STEP: 13
     | > decoder_loss: 0.458670973777771  (0.4613185479090764)
     | > postnet_loss: 0.3145880401134491  (0.31644527270243716)
     | > stopnet_loss: 0.005744244437664747  (0.007765190854955178)
     | > loss: 0.19905900955200195  (0.20220614855106062)
     | > align_error: 0.588151752948761  (0.6165281786368444)

   --> STEP: 14
     | > decoder_loss: 0.46255597472190857  (0.46140693553856443)
     | > postnet_loss: 0.3135703206062317  (0.3162399189812796)
     | > stopnet_loss: 0.005127795971930027  (0.0075768055061676675)
     | > loss: 0.19915936887264252  (0.2019885214311736)
     | > align_error: 0.5560058653354645  (0.6122051562581744)

   --> STEP: 15
     | > decoder_loss: 0.4667975604534149  (0.4617663105328878)
     | > postnet_loss: 0.32069456577301025  (0.31653689543406166)
     | > stopnet_loss: 0.005113703198730946  (0.007412598685671886)
     | > loss: 0.20198674499988556  (0.20198840300242107)
     | > align_error: 0.5900999307632446  (0.6107314745585124)

   --> STEP: 16
     | > decoder_loss: 0.466440886259079  (0.4620584715157747)
     | > postnet_loss: 0.3122870922088623  (0.3162712827324867)
     | > stopnet_loss: 0.005292041227221489  (0.007280063844518736)
     | > loss: 0.19997404515743256  (0.20186250563710928)
     | > align_error: 0.6081953048706055  (0.6105729639530182)

   --> STEP: 17
     | > decoder_loss: 0.47486862540245056  (0.46281200997969685)
     | > postnet_loss: 0.323647677898407  (0.31670518833048206)
     | > stopnet_loss: 0.00498767988756299  (0.0071452177294036925)
     | > loss: 0.2046167552471161  (0.20202452032005086)
     | > align_error: 0.5596933364868164  (0.6075800446903005)

   --> STEP: 18
     | > decoder_loss: 0.4701840877532959  (0.4632215698560079)
     | > postnet_loss: 0.3158648908138275  (0.31665850513511234)
     | > stopnet_loss: 0.005533337127417326  (0.007055668807071116)
     | > loss: 0.20204558968544006  (0.20202569084035027)
     | > align_error: 0.6050394773483276  (0.6074389020601908)

   --> STEP: 19
     | > decoder_loss: 0.4685561954975128  (0.4635023396266134)
     | > postnet_loss: 0.31473976373672485  (0.3165575187457235)
     | > stopnet_loss: 0.00505546759814024  (0.006950395059232649)
     | > loss: 0.20087946951389313  (0.20196536340211568)
     | > align_error: 0.6021780967712402  (0.6071620175712987)

   --> STEP: 20
     | > decoder_loss: 0.4629683792591095  (0.46347564160823823)
     | > postnet_loss: 0.312904953956604  (0.31637489050626755)
     | > stopnet_loss: 0.004661048296838999  (0.0068359277211129665)
     | > loss: 0.19862937927246094  (0.20179856419563294)
     | > align_error: 0.6235937774181366  (0.6079836055636406)

   --> STEP: 21
     | > decoder_loss: 0.4606753885746002  (0.463342296225684)
     | > postnet_loss: 0.30879759788513184  (0.31601406704811824)
     | > stopnet_loss: 0.004178017843514681  (0.006709360584084477)
     | > loss: 0.1965462565422058  (0.2015484543073745)
     | > align_error: 0.5620521605014801  (0.6057963938940139)

   --> STEP: 22
     | > decoder_loss: 0.46273016929626465  (0.4633144722743468)
     | > postnet_loss: 0.31284359097480774  (0.31586995449933136)
     | > stopnet_loss: 0.005058690439909697  (0.006634330122985623)
     | > loss: 0.19895212352275848  (0.20143043927171014)
     | > align_error: 0.6266295313835144  (0.6067433546889911)

   --> STEP: 23
     | > decoder_loss: 0.4343569576740265  (0.4620554499004198)
     | > postnet_loss: 0.3013548254966736  (0.3152388619339984)
     | > stopnet_loss: 0.004683983977884054  (0.006549532464502946)
     | > loss: 0.1886119395494461  (0.2008731131968291)
     | > align_error: 0.5676313638687134  (0.605042833348979)

   --> STEP: 24
     | > decoder_loss: 0.4702721834182739  (0.46239781379699707)
     | > postnet_loss: 0.317728191614151  (0.3153425840040048)
     | > stopnet_loss: 0.004539493937045336  (0.006465780859192212)
     | > loss: 0.20153957605361938  (0.2009008824825287)
     | > align_error: 0.5812371075153351  (0.6040509281059105)

   --> STEP: 25
     | > decoder_loss: 0.4690636694431305  (0.4626644480228424)
     | > postnet_loss: 0.3137301504611969  (0.31527808666229246)
     | > stopnet_loss: 0.0038476292975246906  (0.006361054796725512)
     | > loss: 0.19954608380794525  (0.20084669053554535)
     | > align_error: 0.5593271255493164  (0.6022619760036467)

   --> STEP: 26
     | > decoder_loss: 0.44374778866767883  (0.46193688420149)
     | > postnet_loss: 0.3014703691005707  (0.31474702060222626)
     | > stopnet_loss: 0.004591633565723896  (0.00629300013399468)
     | > loss: 0.1908961683511734  (0.20046397814383873)
     | > align_error: 0.5484224557876587  (0.6001912252261087)

   --> STEP: 27
     | > decoder_loss: 0.44073086977005005  (0.4611514762595848)
     | > postnet_loss: 0.29894891381263733  (0.3141619055359452)
     | > stopnet_loss: 0.004051912575960159  (0.006209996891104513)
     | > loss: 0.1889718621969223  (0.20003834421987887)
     | > align_error: 0.5423955321311951  (0.5980506440003711)

   --> STEP: 28
     | > decoder_loss: 0.4463863670825958  (0.4606241509318352)
     | > postnet_loss: 0.30213481187820435  (0.31373236647674013)
     | > stopnet_loss: 0.004053400829434395  (0.006132975603187723)
     | > loss: 0.19118370115756989  (0.19972210696765355)
     | > align_error: 0.5668431520462036  (0.5969360907162937)

   --> STEP: 29
     | > decoder_loss: 0.44154471158981323  (0.45996623923038615)
     | > postnet_loss: 0.2975003719329834  (0.3131726425269554)
     | > stopnet_loss: 0.0037227366119623184  (0.006049863913835123)
     | > loss: 0.18848401308059692  (0.19933458648878952)
     | > align_error: 0.5414198040962219  (0.5950217360052568)

   --> STEP: 30
     | > decoder_loss: 0.4418184161186218  (0.45936131179332734)
     | > postnet_loss: 0.298839807510376  (0.3126948813597361)
     | > stopnet_loss: 0.0030665509402751923  (0.005950420148049792)
     | > loss: 0.18823111057281494  (0.1989644706249237)
     | > align_error: 0.5348130166530609  (0.5930147786935169)

   --> STEP: 31
     | > decoder_loss: 0.44092679023742676  (0.45876664980765314)
     | > postnet_loss: 0.3012627363204956  (0.31232610248750253)
     | > stopnet_loss: 0.004077922087162733  (0.005890016984795371)
     | > loss: 0.1896253079175949  (0.19866320731178408)
     | > align_error: 0.5598861575126648  (0.5919461134941346)

   --> STEP: 32
     | > decoder_loss: 0.44786491990089417  (0.4584259707480669)
     | > postnet_loss: 0.3034992814064026  (0.3120502643287182)
     | > stopnet_loss: 0.004037423990666866  (0.005832123453728855)
     | > loss: 0.19187848269939423  (0.19845118466764688)
     | > align_error: 0.5319792032241821  (0.5900721475481986)

   --> STEP: 33
     | > decoder_loss: 0.44579893350601196  (0.4580433332558834)
     | > postnet_loss: 0.30295753479003906  (0.31177472706997034)
     | > stopnet_loss: 0.004152762237936258  (0.005781233719916958)
     | > loss: 0.19134187698364258  (0.19823575110146494)
     | > align_error: 0.5464753210544586  (0.5887510315938428)

   --> STEP: 34
     | > decoder_loss: 0.45212793350219727  (0.45786935091018677)
     | > postnet_loss: 0.3051179349422455  (0.3115789390662137)
     | > stopnet_loss: 0.003513692645356059  (0.005714541335371049)
     | > loss: 0.19282516837120056  (0.1980766163152807)
     | > align_error: 0.5640780925750732  (0.5880253569168202)

   --> STEP: 35
     | > decoder_loss: 0.4489344656467438  (0.4576140684740884)
     | > postnet_loss: 0.3027470111846924  (0.3113265982695988)
     | > stopnet_loss: 0.0036822869442403316  (0.005656476924195885)
     | > loss: 0.1916026473045349  (0.19789164577211651)
     | > align_error: 0.5347244739532471  (0.5865024745464323)

   --> STEP: 36
     | > decoder_loss: 0.4558677077293396  (0.4575655584534009)
     | > postnet_loss: 0.30763179063796997  (0.31122396472427577)
     | > stopnet_loss: 0.0038655430544167757  (0.005606728761146466)
     | > loss: 0.1947404146194458  (0.19780411157343122)
     | > align_error: 0.6345725059509277  (0.5878377531965572)

   --> STEP: 37
     | > decoder_loss: 0.4473280906677246  (0.45728887013486913)
     | > postnet_loss: 0.30365726351737976  (0.3110194592862515)
     | > stopnet_loss: 0.003714642720296979  (0.005555591300582966)
     | > loss: 0.191460981965065  (0.19763267563806997)
     | > align_error: 0.5196477472782135  (0.5859947800636289)

   --> STEP: 38
     | > decoder_loss: 0.4368644952774048  (0.4567513865859885)
     | > postnet_loss: 0.29759979248046875  (0.3106663101597836)
     | > stopnet_loss: 0.003288363805040717  (0.005495927419121328)
     | > loss: 0.1869044303894043  (0.19735035339468404)
     | > align_error: 0.5517017841339111  (0.5850923328023206)

   --> STEP: 39
     | > decoder_loss: 0.45052045583724976  (0.45659161913089263)
     | > postnet_loss: 0.30603936314582825  (0.31054767049275905)
     | > stopnet_loss: 0.0036111450754106045  (0.0054475996667184895)
     | > loss: 0.19275110960006714  (0.19723242406661695)
     | > align_error: 0.5469364523887634  (0.5841139768942808)

   --> STEP: 40
     | > decoder_loss: 0.44770967960357666  (0.4563695706427097)
     | > postnet_loss: 0.3048275411128998  (0.3104046672582626)
     | > stopnet_loss: 0.0031791648361831903  (0.005390888795955107)
     | > loss: 0.1913134753704071  (0.1970844503492117)
     | > align_error: 0.5849461555480957  (0.5841347813606261)

   --> STEP: 41
     | > decoder_loss: 0.4378766119480133  (0.45591852286966833)
     | > postnet_loss: 0.2969737648963928  (0.31007708427382674)
     | > stopnet_loss: 0.0038338862359523773  (0.005352913123759919)
     | > loss: 0.1875464916229248  (0.19685181720954617)
     | > align_error: 0.504438579082489  (0.5821909715489643)

   --> STEP: 42
     | > decoder_loss: 0.4431374967098236  (0.4556142127230054)
     | > postnet_loss: 0.30039000511169434  (0.3098464395318712)
     | > stopnet_loss: 0.0034053141716867685  (0.0053065417201391294)
     | > loss: 0.1892872005701065  (0.1966717072895595)
     | > align_error: 0.5801680684089661  (0.5821428071884881)

   --> STEP: 43
     | > decoder_loss: 0.4414334297180176  (0.4552844270717266)
     | > postnet_loss: 0.2995729148387909  (0.3096075203529623)
     | > stopnet_loss: 0.003068202408030629  (0.005254487317531955)
     | > loss: 0.18831980228424072  (0.1964774769405986)
     | > align_error: 0.552193820476532  (0.5814463191254193)

   --> STEP: 44
     | > decoder_loss: 0.4598676860332489  (0.4553885920481248)
     | > postnet_loss: 0.30850857496261597  (0.3095825443213635)
     | > stopnet_loss: 0.002817392349243164  (0.005199098795525391)
     | > loss: 0.19491145014762878  (0.19644188542257657)
     | > align_error: 0.5516433119773865  (0.5807689780538732)

   --> STEP: 45
     | > decoder_loss: 0.45221447944641113  (0.4553180562125312)
     | > postnet_loss: 0.30759599804878235  (0.3095383988486395)
     | > stopnet_loss: 0.003466082504019141  (0.005160587322380807)
     | > loss: 0.1934186965227127  (0.19637470344702404)
     | > align_error: 0.5532254874706268  (0.5801569004853566)

   --> STEP: 46
     | > decoder_loss: 0.4433349072933197  (0.45505755297515704)
     | > postnet_loss: 0.2990436255931854  (0.3093102516039557)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.36670210867217085 (+0.016217531579913458)
     | > avg_decoder_loss: 0.4509441757744009 (+0.0006709076238400891)
     | > avg_postnet_loss: 0.3058371760628439 (+0.00011847913265217169)
     | > avg_stopnet_loss: 0.004536526986736465 (+8.402999038949026e-06)
     | > avg_loss: 0.19373186587384253 (+0.000205749815160583)
     | > avg_align_error: 0.5728547279581879 (-7.693198594183048e-05)


 > EPOCH: 23/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-27 23:57:19)

   --> TIME: 2025-12-27 23:57:22 -- STEP: 2/150 -- GLOBAL_STEP: 3475
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4770057797431946  (0.4811422973871231)
     | > postnet_loss: 0.4233431816101074  (0.42615725100040436)
     | > stopnet_loss: 0.014980148524045944  (0.01554130669683218)
     | > loss: 0.24006739258766174  (0.24236619472503662)
     | > align_error: 0.7325053215026855  (0.7239725291728973)
     | > grad_norm: tensor(0.3248, device='cuda:0')  (tensor(0.3238, device='cuda:0'))
     | > step_time: 0.4282  (0.42159247398376465)
     | > loader_time: 0.6857  (0.7345101833343506)


   --> TIME: 2025-12-27 23:58:01 -- STEP: 27/150 -- GLOBAL_STEP: 3500
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.5002741813659668  (0.4887914801085437)
     | > postnet_loss: 0.4199472665786743  (0.4186005007337641)
     | > stopnet_loss: 0.00615660659968853  (0.009644021556057314)
     | > loss: 0.23621197044849396  (0.2364920179049174)
     | > align_error: 0.6573516726493835  (0.6693833039866554)
     | > grad_norm: tensor(0.2362, device='cuda:0')  (tensor(0.2460, device='cuda:0'))
     | > step_time: 1.0103  (0.6653763364862513)
     | > loader_time: 0.908  (0.8367244049354836)


   --> TIME: 2025-12-27 23:58:53 -- STEP: 52/150 -- GLOBAL_STEP: 3525
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.49870848655700684  (0.494677314391503)
     | > postnet_loss: 0.41497376561164856  (0.41868142783641815)
     | > stopnet_loss: 0.004361679311841726  (0.007620625833694179)
     | > loss: 0.23278222978115082  (0.23596031190111086)
     | > align_error: 0.6612159907817841  (0.6484774609024708)
     | > grad_norm: tensor(0.2254, device='cuda:0')  (tensor(0.2327, device='cuda:0'))
     | > step_time: 1.2356  (0.8579528652704679)
     | > loader_time: 1.1668  (0.9276672097352835)


   --> TIME: 2025-12-27 23:59:58 -- STEP: 77/150 -- GLOBAL_STEP: 3550
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.502292275428772  (0.4970955651301842)
     | > postnet_loss: 0.4143338203430176  (0.41787051999723757)
     | > stopnet_loss: 0.004578669089823961  (0.0065364726371579356)
     | > loss: 0.23373518884181976  (0.23527799430605653)
     | > align_error: 0.6124083399772644  (0.6369316752080795)
     | > grad_norm: tensor(0.1467, device='cuda:0')  (tensor(0.2184, device='cuda:0'))
     | > step_time: 1.5879  (1.0210227501856817)
     | > loader_time: 1.2584  (1.0292437788727995)


   --> TIME: 2025-12-28 00:01:16 -- STEP: 102/150 -- GLOBAL_STEP: 3575
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5052452087402344  (0.49778006211215375)
     | > postnet_loss: 0.41500383615493774  (0.416970742391605)
     | > stopnet_loss: 0.0035318585578352213  (0.0058753850856138505)
     | > loss: 0.2335941195487976  (0.2345630868392832)
     | > align_error: 0.6061310768127441  (0.6323138025461459)
     | > grad_norm: tensor(0.1181, device='cuda:0')  (tensor(0.2058, device='cuda:0'))
     | > step_time: 1.8145  (1.1665662784202426)
     | > loader_time: 1.5972  (1.147780769011554)


   --> TIME: 2025-12-28 00:02:50 -- STEP: 127/150 -- GLOBAL_STEP: 3600
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5084004998207092  (0.4985582103410105)
     | > postnet_loss: 0.41859111189842224  (0.4163534488734298)
     | > stopnet_loss: 0.003288320265710354  (0.005394646888745465)
     | > loss: 0.2350362092256546  (0.23412256177485458)
     | > align_error: 0.6013116538524628  (0.6285161153068692)
     | > grad_norm: tensor(0.1269, device='cuda:0')  (tensor(0.1974, device='cuda:0'))
     | > step_time: 2.0408  (1.3008577354311004)
     | > loader_time: 2.0049  (1.2944558023467783)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4754224121570587  (0.4754224121570587)
     | > postnet_loss: 0.3354403078556061  (0.3354403078556061)
     | > stopnet_loss: 0.012428352609276772  (0.012428352609276772)
     | > loss: 0.21514403820037842  (0.21514403820037842)
     | > align_error: 0.7188344299793243  (0.7188344299793243)

   --> STEP: 1
     | > decoder_loss: 0.4561850130558014  (0.4561850130558014)
     | > postnet_loss: 0.3212493658065796  (0.3212493658065796)
     | > stopnet_loss: 0.009878451935946941  (0.009878451935946941)
     | > loss: 0.20423704385757446  (0.20423704385757446)
     | > align_error: 0.6601029634475708  (0.6601029634475708)

   --> STEP: 2
     | > decoder_loss: 0.45048096776008606  (0.4533329904079437)
     | > postnet_loss: 0.3156755268573761  (0.31846244633197784)
     | > stopnet_loss: 0.011297442950308323  (0.010587947443127632)
     | > loss: 0.20283657312393188  (0.20353680849075317)
     | > align_error: 0.6574196219444275  (0.6587612926959991)

   --> STEP: 3
     | > decoder_loss: 0.4525817632675171  (0.45308258136113483)
     | > postnet_loss: 0.312238872051239  (0.31638792157173157)
     | > stopnet_loss: 0.008644535206258297  (0.009940143364171187)
     | > loss: 0.1998496949672699  (0.20230777064959207)
     | > align_error: 0.7357006371021271  (0.6844077408313751)

   --> STEP: 4
     | > decoder_loss: 0.4636753797531128  (0.45573078095912933)
     | > postnet_loss: 0.3230730891227722  (0.31805921345949173)
     | > stopnet_loss: 0.008389550261199474  (0.009552495088428259)
     | > loss: 0.205076664686203  (0.2029999941587448)
     | > align_error: 0.60484379529953  (0.6645167544484138)

   --> STEP: 5
     | > decoder_loss: 0.44346529245376587  (0.4532776832580566)
     | > postnet_loss: 0.3061624765396118  (0.31567986607551574)
     | > stopnet_loss: 0.008438714779913425  (0.009329739026725292)
     | > loss: 0.19584566354751587  (0.201569128036499)
     | > align_error: 0.6433369517326355  (0.6602807939052582)

   --> STEP: 6
     | > decoder_loss: 0.4586127698421478  (0.45416686435540515)
     | > postnet_loss: 0.31562867760658264  (0.3156713346640269)
     | > stopnet_loss: 0.00740567222237587  (0.009009061226000389)
     | > loss: 0.2009660303592682  (0.20146861175696054)
     | > align_error: 0.5951361060142517  (0.6494233459234238)

   --> STEP: 7
     | > decoder_loss: 0.46617385745048523  (0.45588214908327374)
     | > postnet_loss: 0.31479302048683167  (0.3155458612101419)
     | > stopnet_loss: 0.006510907784104347  (0.008652182162872382)
     | > loss: 0.20175263285636902  (0.20150918619973318)
     | > align_error: 0.5800970196723938  (0.6395195850304195)

   --> STEP: 8
     | > decoder_loss: 0.4621110260486603  (0.45666075870394707)
     | > postnet_loss: 0.31489405035972595  (0.3154643848538399)
     | > stopnet_loss: 0.007649464067071676  (0.008526842400897294)
     | > loss: 0.20190073549747467  (0.20155812986195087)
     | > align_error: 0.5767049193382263  (0.6316677518188953)

   --> STEP: 9
     | > decoder_loss: 0.46029338240623474  (0.4570643835597568)
     | > postnet_loss: 0.31652042269706726  (0.31558172239197624)
     | > stopnet_loss: 0.006823096890002489  (0.008337537344131205)
     | > loss: 0.2010265439748764  (0.20149906476338705)
     | > align_error: 0.5933283567428589  (0.6274078190326691)

   --> STEP: 10
     | > decoder_loss: 0.4913584887981415  (0.46049379408359525)
     | > postnet_loss: 0.33149397373199463  (0.3171729475259781)
     | > stopnet_loss: 0.005932722240686417  (0.008097055833786726)
     | > loss: 0.21164584159851074  (0.2025137424468994)
     | > align_error: 0.5877188444137573  (0.6234389215707778)

   --> STEP: 11
     | > decoder_loss: 0.47311529517173767  (0.4616412032734264)
     | > postnet_loss: 0.32222050428390503  (0.31763181632215326)
     | > stopnet_loss: 0.006018239539116621  (0.007908072534271261)
     | > loss: 0.2048521786928177  (0.2027263275601647)
     | > align_error: 0.595196008682251  (0.6208713840354573)

   --> STEP: 12
     | > decoder_loss: 0.4670271873474121  (0.46209003527959186)
     | > postnet_loss: 0.3140033185482025  (0.31732944150765735)
     | > stopnet_loss: 0.008071068674325943  (0.007921655545942485)
     | > loss: 0.2033286988735199  (0.20277652516961098)
     | > align_error: 0.5885523855686188  (0.6181781341632208)

   --> STEP: 13
     | > decoder_loss: 0.45962145924568176  (0.46190014481544495)
     | > postnet_loss: 0.31523844599723816  (0.31716859569916356)
     | > stopnet_loss: 0.005699066910892725  (0.007750687189400196)
     | > loss: 0.19941404461860657  (0.2025178728195337)
     | > align_error: 0.587388813495636  (0.6158097248810989)

   --> STEP: 14
     | > decoder_loss: 0.4633781313896179  (0.4620057152850287)
     | > postnet_loss: 0.31384727358818054  (0.31693135840552195)
     | > stopnet_loss: 0.0051037585362792015  (0.007561620857034411)
     | > loss: 0.1994100958108902  (0.20229588874748775)
     | > align_error: 0.554835170507431  (0.611454399568694)

   --> STEP: 15
     | > decoder_loss: 0.4673709571361542  (0.46236339807510374)
     | > postnet_loss: 0.3203197121620178  (0.317157248655955)
     | > stopnet_loss: 0.005089214071631432  (0.007396793738007545)
     | > loss: 0.2020118683576584  (0.20227695405483245)
     | > align_error: 0.5892561078071594  (0.6099745134512583)

   --> STEP: 16
     | > decoder_loss: 0.46702954173088074  (0.4626550320535898)
     | > postnet_loss: 0.3120473623275757  (0.3168378807604313)
     | > stopnet_loss: 0.0052659772336483  (0.007263617706485093)
     | > loss: 0.2000352144241333  (0.20213684532791376)
     | > align_error: 0.6072818040847778  (0.6098062191158533)

   --> STEP: 17
     | > decoder_loss: 0.47579196095466614  (0.46342779257718253)
     | > postnet_loss: 0.32351234555244446  (0.3172304963364321)
     | > stopnet_loss: 0.004980909172445536  (0.007129340733894531)
     | > loss: 0.20480698347091675  (0.20229391227750218)
     | > align_error: 0.558813214302063  (0.606806630597395)

   --> STEP: 18
     | > decoder_loss: 0.47060051560401917  (0.4638262771897846)
     | > postnet_loss: 0.31546637415885925  (0.31713248954878914)
     | > stopnet_loss: 0.005480537656694651  (0.007037740562938982)
     | > loss: 0.20199726521968842  (0.2022774318854014)
     | > align_error: 0.604426383972168  (0.6066743946737714)

   --> STEP: 19
     | > decoder_loss: 0.4693661332130432  (0.4641178485594298)
     | > postnet_loss: 0.314860075712204  (0.3170128888205478)
     | > stopnet_loss: 0.0050299447029829025  (0.006932067096625504)
     | > loss: 0.20108649134635925  (0.20221475080439918)
     | > align_error: 0.6014057397842407  (0.6063970970480066)

   --> STEP: 20
     | > decoder_loss: 0.46380823850631714  (0.46410236805677413)
     | > postnet_loss: 0.3125855028629303  (0.31679151952266693)
     | > stopnet_loss: 0.004638324957340956  (0.006817379989661277)
     | > loss: 0.198736771941185  (0.2020408518612385)
     | > align_error: 0.62261962890625  (0.6072082236409188)

   --> STEP: 21
     | > decoder_loss: 0.4611174166202545  (0.46396022751217797)
     | > postnet_loss: 0.30866625905036926  (0.31640460235731943)
     | > stopnet_loss: 0.004158565774559975  (0.006690769788942167)
     | > loss: 0.19660449028015137  (0.20178197750023433)
     | > align_error: 0.5613023042678833  (0.605022227480298)

   --> STEP: 22
     | > decoder_loss: 0.464102566242218  (0.4639666974544525)
     | > postnet_loss: 0.3130004107952118  (0.31624986637722363)
     | > stopnet_loss: 0.005002633668482304  (0.006614036328921264)
     | > loss: 0.19927836954593658  (0.20166817713867535)
     | > align_error: 0.6258367300033569  (0.6059683412313461)

   --> STEP: 23
     | > decoder_loss: 0.43514254689216614  (0.4627134735169618)
     | > postnet_loss: 0.30116599798202515  (0.31559404601221497)
     | > stopnet_loss: 0.004675238858908415  (0.006529740786746792)
     | > loss: 0.18875238299369812  (0.2011066208715024)
     | > align_error: 0.5666340887546539  (0.6042581563410552)

   --> STEP: 24
     | > decoder_loss: 0.46979856491088867  (0.46300868565837544)
     | > postnet_loss: 0.31658750772476196  (0.31563544025023776)
     | > stopnet_loss: 0.004511492792516947  (0.006445647120320548)
     | > loss: 0.20110800862312317  (0.20110667869448662)
     | > align_error: 0.5798739790916443  (0.6032421489556631)

   --> STEP: 25
     | > decoder_loss: 0.46902912855148315  (0.46324950337409976)
     | > postnet_loss: 0.3130251169204712  (0.31553102731704713)
     | > stopnet_loss: 0.0038026461843401194  (0.0063399270828813315)
     | > loss: 0.19931620359420776  (0.20103505969047547)
     | > align_error: 0.5582212805747986  (0.6014413142204285)

   --> STEP: 26
     | > decoder_loss: 0.4437043070793152  (0.46249776505506957)
     | > postnet_loss: 0.3008410632610321  (0.31496602869950807)
     | > stopnet_loss: 0.004586900118738413  (0.006272502968875835)
     | > loss: 0.1907232403755188  (0.20063845125528482)
     | > align_error: 0.547723263502121  (0.5993752353466474)

   --> STEP: 27
     | > decoder_loss: 0.441171258687973  (0.4617078944488808)
     | > postnet_loss: 0.29849445819854736  (0.31435597053280584)
     | > stopnet_loss: 0.0040281969122588634  (0.006189380522334465)
     | > loss: 0.18894463777542114  (0.2002053470523269)
     | > align_error: 0.5415298938751221  (0.5972328152921464)

   --> STEP: 28
     | > decoder_loss: 0.4468967914581299  (0.4611789264849254)
     | > postnet_loss: 0.3017650246620178  (0.3139062938945634)
     | > stopnet_loss: 0.0040196869522333145  (0.006111891466259424)
     | > loss: 0.1911851465702057  (0.1998831970351083)
     | > align_error: 0.5661443173885345  (0.596122511795589)

   --> STEP: 29
     | > decoder_loss: 0.4423827528953552  (0.4605307825680437)
     | > postnet_loss: 0.2976495325565338  (0.31334571591738997)
     | > stopnet_loss: 0.0037198492791503668  (0.006029407252910836)
     | > loss: 0.18872793018817902  (0.19949853266107626)
     | > align_error: 0.5408003330230713  (0.5942148504586056)

   --> STEP: 30
     | > decoder_loss: 0.4420472979545593  (0.4599146664142609)
     | > postnet_loss: 0.2984278202056885  (0.3128484527269999)
     | > stopnet_loss: 0.003040651325136423  (0.0059297820553183556)
     | > loss: 0.18815943598747253  (0.19912056277195614)
     | > align_error: 0.5338626503944397  (0.5922031104564667)

   --> STEP: 31
     | > decoder_loss: 0.4408794045448303  (0.4593006257087954)
     | > postnet_loss: 0.3004266321659088  (0.31244774883793247)
     | > stopnet_loss: 0.004069519229233265  (0.005869773577057546)
     | > loss: 0.18939603865146637  (0.19880686844548873)
     | > align_error: 0.5593644380569458  (0.5911437984435789)

   --> STEP: 32
     | > decoder_loss: 0.4480675458908081  (0.45894959196448326)
     | > postnet_loss: 0.30307626724243164  (0.31215489003807306)
     | > stopnet_loss: 0.004022951237857342  (0.00581206037895754)
     | > loss: 0.19180890917778015  (0.19858818221837282)
     | > align_error: 0.5312936305999756  (0.5892734806984663)

   --> STEP: 33
     | > decoder_loss: 0.4460110366344452  (0.4585575145302397)
     | > postnet_loss: 0.3021547198295593  (0.311851854577209)
     | > stopnet_loss: 0.004140215925872326  (0.005761398425833745)
     | > loss: 0.19118164479732513  (0.19836374169046228)
     | > align_error: 0.5455919206142426  (0.5879497970595504)

   --> STEP: 34
     | > decoder_loss: 0.4523361027240753  (0.4583745318300584)
     | > postnet_loss: 0.30446261167526245  (0.31163452390362234)
     | > stopnet_loss: 0.003474155440926552  (0.005694126573336475)
     | > loss: 0.19267384707927704  (0.19819639184895685)
     | > align_error: 0.5631605386734009  (0.5872207012246636)

   --> STEP: 35
     | > decoder_loss: 0.44928109645843506  (0.4581147193908691)
     | > postnet_loss: 0.3023501932621002  (0.31136925731386456)
     | > stopnet_loss: 0.0036812787875533104  (0.005636616636599813)
     | > loss: 0.1915890872478485  (0.1980076117174966)
     | > align_error: 0.5334478616714478  (0.5856843343802861)

   --> STEP: 36
     | > decoder_loss: 0.45643559098243713  (0.45806807693507934)
     | > postnet_loss: 0.30722010135650635  (0.31125400298171574)
     | > stopnet_loss: 0.0038385093212127686  (0.005586669211172395)
     | > loss: 0.19475242495536804  (0.19791718986299303)
     | > align_error: 0.6341163516044617  (0.5870296681920687)

   --> STEP: 37
     | > decoder_loss: 0.448009729385376  (0.4577962297040063)
     | > postnet_loss: 0.3033984899520874  (0.3110416918187528)
     | > stopnet_loss: 0.0037041548639535904  (0.0055357904450313465)
     | > loss: 0.19155621528625488  (0.1977452716311893)
     | > align_error: 0.5187135934829712  (0.5851832877945256)

   --> STEP: 38
     | > decoder_loss: 0.4372013509273529  (0.45725425920988383)
     | > postnet_loss: 0.2970813512802124  (0.3106743144361596)
     | > stopnet_loss: 0.0032646998297423124  (0.00547602490252374)
     | > loss: 0.186835378408432  (0.19745816917795883)
     | > align_error: 0.5507550537586212  (0.5842772816356859)

   --> STEP: 39
     | > decoder_loss: 0.45024481415748596  (0.4570745298495659)
     | > postnet_loss: 0.30530688166618347  (0.3105366879548782)
     | > stopnet_loss: 0.003600030904635787  (0.005427922492321485)
     | > loss: 0.1924879550933838  (0.19733072779117486)
     | > align_error: 0.5458289086818695  (0.5832914259189215)

   --> STEP: 40
     | > decoder_loss: 0.44813990592956543  (0.4568511642515659)
     | > postnet_loss: 0.3044629395008087  (0.31038484424352647)
     | > stopnet_loss: 0.0031619654037058353  (0.005371273565106093)
     | > loss: 0.19131267070770264  (0.19718027636408805)
     | > align_error: 0.5840566456317902  (0.5833105564117431)

   --> STEP: 41
     | > decoder_loss: 0.43803027272224426  (0.45639211811670444)
     | > postnet_loss: 0.2965443432331085  (0.3100472710481504)
     | > stopnet_loss: 0.003825464751571417  (0.005333570911117443)
     | > loss: 0.18746912479400635  (0.1969434190087202)
     | > align_error: 0.5035522282123566  (0.5813652313337093)

   --> STEP: 42
     | > decoder_loss: 0.44301140308380127  (0.4560735296635401)
     | > postnet_loss: 0.29972830414772034  (0.3098015813600449)
     | > stopnet_loss: 0.003391730599105358  (0.005287336617974299)
     | > loss: 0.18907664716243744  (0.19675611491714204)
     | > align_error: 0.5793290734291077  (0.5813167513835997)

   --> STEP: 43
     | > decoder_loss: 0.4415533244609833  (0.4557358504727829)
     | > postnet_loss: 0.29903268814086914  (0.30955114198285477)
     | > stopnet_loss: 0.0030379979871213436  (0.0052350264172567875)
     | > loss: 0.18818451464176178  (0.19655677537585414)
     | > align_error: 0.5513541102409363  (0.5806199457756308)

   --> STEP: 44
     | > decoder_loss: 0.4594784080982208  (0.4558209086006338)
     | > postnet_loss: 0.3076816201210022  (0.30950865284963086)
     | > stopnet_loss: 0.0028171525336802006  (0.005180074738084592)
     | > loss: 0.19460716843605042  (0.19651246612722223)
     | > align_error: 0.5509789288043976  (0.5799462862990118)

   --> STEP: 45
     | > decoder_loss: 0.4520986080169678  (0.45573819080988565)
     | > postnet_loss: 0.3068934977054596  (0.3094505382908715)
     | > stopnet_loss: 0.0034617427736520767  (0.005141889583319426)
     | > loss: 0.19320976734161377  (0.1964390728208754)
     | > align_error: 0.5525194704532623  (0.5793368015024396)

   --> STEP: 46
     | > decoder_loss: 0.44392600655555725  (0.45548140419566113)
     | > postnet_loss: 0.2988628149032593  (0.30922037039114075)
     | > stopnet_loss: 0.0033195314463227987  (0.005102273102080369)
     | > loss: 0.18901672959327698  (0.19627771753331888)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3569256356268218 (-0.009776473045349066)
     | > avg_decoder_loss: 0.45121180830579816 (+0.00026763253139727716)
     | > avg_postnet_loss: 0.3057081274914019 (-0.0001290485714419698)
     | > avg_stopnet_loss: 0.004521619736668513 (-1.4907250067952224e-05)
     | > avg_loss: 0.19375160404226996 (+1.9738168427430036e-05)
     | > avg_align_error: 0.5720356815692149 (-0.0008190463889730104)


 > EPOCH: 24/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 00:06:30)

   --> TIME: 2025-12-28 00:06:32 -- STEP: 1/150 -- GLOBAL_STEP: 3625
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.485317200422287  (0.485317200422287)
     | > postnet_loss: 0.42816683650016785  (0.42816683650016785)
     | > stopnet_loss: 0.016221484169363976  (0.016221484169363976)
     | > loss: 0.24459248781204224  (0.24459248781204224)
     | > align_error: 0.7155661582946777  (0.7155661582946777)
     | > grad_norm: tensor(0.3437, device='cuda:0')  (tensor(0.3437, device='cuda:0'))
     | > step_time: 0.3157  (0.31572389602661133)
     | > loader_time: 0.7371  (0.7370734214782715)


   --> TIME: 2025-12-28 00:07:11 -- STEP: 26/150 -- GLOBAL_STEP: 3650
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.4964755177497864  (0.48782313213898587)
     | > postnet_loss: 0.4180930256843567  (0.41816162833800685)
     | > stopnet_loss: 0.006905661430209875  (0.009758006763429595)
     | > loss: 0.23554779589176178  (0.23625419690058783)
     | > align_error: 0.619031548500061  (0.6696853179198045)
     | > grad_norm: tensor(0.1824, device='cuda:0')  (tensor(0.2549, device='cuda:0'))
     | > step_time: 0.8059  (0.6437502274146447)
     | > loader_time: 0.8958  (0.8734407975123479)


   --> TIME: 2025-12-28 00:08:05 -- STEP: 51/150 -- GLOBAL_STEP: 3675
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5049811005592346  (0.49412765689924654)
     | > postnet_loss: 0.418589323759079  (0.4183313560252096)
     | > stopnet_loss: 0.004378830548375845  (0.007659006206428305)
     | > loss: 0.2352714240550995  (0.2357737600219016)
     | > align_error: 0.6134112775325775  (0.6479754003823972)
     | > grad_norm: tensor(0.2529, device='cuda:0')  (tensor(0.2413, device='cuda:0'))
     | > step_time: 1.2668  (0.8781504771288704)
     | > loader_time: 1.3713  (0.9539151238460167)


   --> TIME: 2025-12-28 00:09:11 -- STEP: 76/150 -- GLOBAL_STEP: 3700
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.508674681186676  (0.49663147447924866)
     | > postnet_loss: 0.41844892501831055  (0.4175729261417138)
     | > stopnet_loss: 0.003966015297919512  (0.006537951522898911)
     | > loss: 0.23574692010879517  (0.23508905207640246)
     | > align_error: 0.6053644418716431  (0.6369117314093992)
     | > grad_norm: tensor(0.1394, device='cuda:0')  (tensor(0.2201, device='cuda:0'))
     | > step_time: 1.4448  (1.0461525477861102)
     | > loader_time: 1.3216  (1.0574667014573749)


   --> TIME: 2025-12-28 00:10:32 -- STEP: 101/150 -- GLOBAL_STEP: 3725
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5033760070800781  (0.49759448489340224)
     | > postnet_loss: 0.415600448846817  (0.416819822965282)
     | > stopnet_loss: 0.004006284289062023  (0.0058784424488681685)
     | > loss: 0.2337503880262375  (0.23448201940201296)
     | > align_error: 0.6084353923797607  (0.6319801264470171)
     | > grad_norm: tensor(0.1933, device='cuda:0')  (tensor(0.2095, device='cuda:0'))
     | > step_time: 1.6121  (1.185155797712874)
     | > loader_time: 1.6243  (1.1932176080080545)


   --> TIME: 2025-12-28 00:12:00 -- STEP: 126/150 -- GLOBAL_STEP: 3750
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5042174458503723  (0.4984011101344275)
     | > postnet_loss: 0.4147571623325348  (0.41617614432932837)
     | > stopnet_loss: 0.003121043788269162  (0.005392391175504716)
     | > loss: 0.23286470770835876  (0.23403670520536482)
     | > align_error: 0.6117954552173615  (0.6281499053750723)
     | > grad_norm: tensor(0.1271, device='cuda:0')  (tensor(0.1989, device='cuda:0'))
     | > step_time: 2.0735  (1.3129468456147213)
     | > loader_time: 1.7819  (1.2912638944292825)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4747695028781891  (0.4747695028781891)
     | > postnet_loss: 0.33554691076278687  (0.33554691076278687)
     | > stopnet_loss: 0.012466182000935078  (0.012466182000935078)
     | > loss: 0.2150452882051468  (0.2150452882051468)
     | > align_error: 0.7193928062915802  (0.7193928062915802)

   --> STEP: 1
     | > decoder_loss: 0.45409315824508667  (0.45409315824508667)
     | > postnet_loss: 0.3208784759044647  (0.3208784759044647)
     | > stopnet_loss: 0.009795501828193665  (0.009795501828193665)
     | > loss: 0.20353840291500092  (0.20353840291500092)
     | > align_error: 0.6603508591651917  (0.6603508591651917)

   --> STEP: 2
     | > decoder_loss: 0.44864681363105774  (0.4513699859380722)
     | > postnet_loss: 0.3148452043533325  (0.3178618401288986)
     | > stopnet_loss: 0.011209985241293907  (0.010502743534743786)
     | > loss: 0.20208297669887543  (0.20281068980693817)
     | > align_error: 0.6576306223869324  (0.658990740776062)

   --> STEP: 3
     | > decoder_loss: 0.4510806202888489  (0.45127353072166443)
     | > postnet_loss: 0.31178638339042664  (0.3158366878827413)
     | > stopnet_loss: 0.008683174848556519  (0.00989622063934803)
     | > loss: 0.1993999183177948  (0.20167376597722372)
     | > align_error: 0.7358857691287994  (0.6846224168936411)

   --> STEP: 4
     | > decoder_loss: 0.4605962634086609  (0.45360421389341354)
     | > postnet_loss: 0.32218503952026367  (0.3174237757921219)
     | > stopnet_loss: 0.00842447392642498  (0.009528283961117268)
     | > loss: 0.20411980152130127  (0.2022852748632431)
     | > align_error: 0.6054487228393555  (0.6648289933800697)

   --> STEP: 5
     | > decoder_loss: 0.4412972629070282  (0.45114282369613645)
     | > postnet_loss: 0.3051935136318207  (0.31497772336006163)
     | > stopnet_loss: 0.008423760533332825  (0.00930737927556038)
     | > loss: 0.19504645466804504  (0.20083751082420348)
     | > align_error: 0.6437214314937592  (0.6606074810028076)

   --> STEP: 6
     | > decoder_loss: 0.45696279406547546  (0.452112818757693)
     | > postnet_loss: 0.31524255871772766  (0.3150218625863393)
     | > stopnet_loss: 0.007396271452307701  (0.008988861305018267)
     | > loss: 0.20044760406017303  (0.20077252636353174)
     | > align_error: 0.5958877205848694  (0.6498208542664846)

   --> STEP: 7
     | > decoder_loss: 0.4649198651313782  (0.45394239681107657)
     | > postnet_loss: 0.3141762912273407  (0.31490106667791096)
     | > stopnet_loss: 0.0065430584363639355  (0.008639460895210505)
     | > loss: 0.20131708681583405  (0.20085032071386064)
     | > align_error: 0.5808388590812683  (0.6399662835257394)

   --> STEP: 8
     | > decoder_loss: 0.4609185457229614  (0.4548144154250622)
     | > postnet_loss: 0.3147597908973694  (0.31488340720534325)
     | > stopnet_loss: 0.007696507032960653  (0.008521591662429273)
     | > loss: 0.2016160935163498  (0.2009460423141718)
     | > align_error: 0.5772341787815094  (0.6321247704327106)

   --> STEP: 9
     | > decoder_loss: 0.45720329880714417  (0.4550798469119602)
     | > postnet_loss: 0.31466975808143616  (0.31485966841379803)
     | > stopnet_loss: 0.00684267608448863  (0.008335045487102535)
     | > loss: 0.1998109370470047  (0.20081991950670877)
     | > align_error: 0.5937395095825195  (0.6278597414493561)

   --> STEP: 10
     | > decoder_loss: 0.4891121983528137  (0.45848308205604554)
     | > postnet_loss: 0.3309575915336609  (0.3164694607257843)
     | > stopnet_loss: 0.005995253100991249  (0.008101066248491407)
     | > loss: 0.21101270616054535  (0.20183919817209245)
     | > align_error: 0.5883359909057617  (0.6239073663949967)

   --> STEP: 11
     | > decoder_loss: 0.472718209028244  (0.4597771845080636)
     | > postnet_loss: 0.3222293257713318  (0.31699308482083405)
     | > stopnet_loss: 0.006029000040143728  (0.007912696593187073)
     | > loss: 0.20476587116718292  (0.2021052593534643)
     | > align_error: 0.5960694849491119  (0.6213766498999163)

   --> STEP: 12
     | > decoder_loss: 0.465409517288208  (0.4602465455730756)
     | > postnet_loss: 0.31322771310806274  (0.3166793038447698)
     | > stopnet_loss: 0.008038661442697048  (0.00792319366397957)
     | > loss: 0.2026979625225067  (0.20215465128421783)
     | > align_error: 0.5891828238964081  (0.6186938310662905)

   --> STEP: 13
     | > decoder_loss: 0.45732662081718445  (0.4600219359764686)
     | > postnet_loss: 0.3143017590045929  (0.3164964157801408)
     | > stopnet_loss: 0.005757484585046768  (0.007756600657907816)
     | > loss: 0.1986645758152008  (0.2018861839404473)
     | > align_error: 0.5882613658905029  (0.6163528722066146)

   --> STEP: 14
     | > decoder_loss: 0.46301281452178955  (0.46023557015827726)
     | > postnet_loss: 0.3138696551322937  (0.3163087900195803)
     | > stopnet_loss: 0.005156851373612881  (0.007570904280458178)
     | > loss: 0.19937746226787567  (0.20170698953526361)
     | > align_error: 0.5557350814342499  (0.6120230300085885)

   --> STEP: 15
     | > decoder_loss: 0.4655846059322357  (0.4605921725432078)
     | > postnet_loss: 0.31944265961647034  (0.31651771465937295)
     | > stopnet_loss: 0.005111140199005604  (0.007406920008361339)
     | > loss: 0.20136795938014984  (0.20168438752492268)
     | > align_error: 0.5899848937988281  (0.6105538209279379)

   --> STEP: 16
     | > decoder_loss: 0.46531450748443604  (0.46088731847703457)
     | > postnet_loss: 0.3113395869731903  (0.31619408167898655)
     | > stopnet_loss: 0.005289637017995119  (0.007274589821463451)
     | > loss: 0.1994531750679016  (0.20154493674635887)
     | > align_error: 0.6081205010414124  (0.61040173843503)

   --> STEP: 17
     | > decoder_loss: 0.473411500453949  (0.46162403506391186)
     | > postnet_loss: 0.3216926157474518  (0.3165175248594845)
     | > stopnet_loss: 0.004985336679965258  (0.007139927871963557)
     | > loss: 0.20376136898994446  (0.2016753151136286)
     | > align_error: 0.5597713589668274  (0.6074234808192533)

   --> STEP: 18
     | > decoder_loss: 0.46898752450942993  (0.46203311781088513)
     | > postnet_loss: 0.31454434990882874  (0.3164079040288925)
     | > stopnet_loss: 0.005511761177331209  (0.007049474166706204)
     | > loss: 0.20139473676681519  (0.20165972742769453)
     | > align_error: 0.6053867638111115  (0.6073103298743566)

   --> STEP: 19
     | > decoder_loss: 0.4663955867290497  (0.46226272143815694)
     | > postnet_loss: 0.3132399916648865  (0.31624117179920797)
     | > stopnet_loss: 0.005018664989620447  (0.0069425894731753755)
     | > loss: 0.19992755353450775  (0.2015685603806847)
     | > align_error: 0.6021762490272522  (0.60704011509293)

   --> STEP: 20
     | > decoder_loss: 0.4617077708244324  (0.4622349739074707)
     | > postnet_loss: 0.3111858069896698  (0.3159884035587311)
     | > stopnet_loss: 0.004682096652686596  (0.0068295648321509365)
     | > loss: 0.19790548086166382  (0.20138540640473365)
     | > align_error: 0.6238554120063782  (0.6078808799386024)

   --> STEP: 21
     | > decoder_loss: 0.45919787883758545  (0.4620903503327143)
     | > postnet_loss: 0.30769750475883484  (0.3155935988539741)
     | > stopnet_loss: 0.004183246288448572  (0.006703549663403204)
     | > loss: 0.1959071010351181  (0.20112453472046626)
     | > align_error: 0.5620966851711273  (0.6057006801877703)

   --> STEP: 22
     | > decoder_loss: 0.461430162191391  (0.46206034178083594)
     | > postnet_loss: 0.31156232953071594  (0.3154103593392805)
     | > stopnet_loss: 0.005051578860729933  (0.0066284600814635105)
     | > loss: 0.19829970598220825  (0.2009961334141818)
     | > align_error: 0.626748263835907  (0.606657388535413)

   --> STEP: 23
     | > decoder_loss: 0.43349531292915344  (0.46081838400467584)
     | > postnet_loss: 0.30023515224456787  (0.3147505677264669)
     | > stopnet_loss: 0.004671445116400719  (0.006543372474286867)
     | > loss: 0.188104048371315  (0.2004356079775354)
     | > align_error: 0.5678478479385376  (0.604970017205114)

   --> STEP: 24
     | > decoder_loss: 0.46834084391593933  (0.4611318198343118)
     | > postnet_loss: 0.31564828753471375  (0.3147879727184772)
     | > stopnet_loss: 0.0045259129256010056  (0.006459311659758289)
     | > loss: 0.20052319765090942  (0.20043925754725933)
     | > align_error: 0.5808771848678589  (0.6039661491910617)

   --> STEP: 25
     | > decoder_loss: 0.4688636362552643  (0.4614410924911499)
     | > postnet_loss: 0.3127456605434418  (0.31470628023147573)
     | > stopnet_loss: 0.0038197366520762444  (0.006353728659451008)
     | > loss: 0.19922205805778503  (0.20039056956768037)
     | > align_error: 0.5599531531333923  (0.602205629348755)

   --> STEP: 26
     | > decoder_loss: 0.4427642226219177  (0.46072275134233326)
     | > postnet_loss: 0.3005079925060272  (0.31416019224203534)
     | > stopnet_loss: 0.004587927833199501  (0.006285813243056719)
     | > loss: 0.1904059797525406  (0.20000654688248268)
     | > align_error: 0.5485836267471313  (0.6001432446333079)

   --> STEP: 27
     | > decoder_loss: 0.43967100977897644  (0.4599430572103571)
     | > postnet_loss: 0.2972567677497864  (0.3135341394830632)
     | > stopnet_loss: 0.0040621100924909115  (0.006203453867109837)
     | > loss: 0.18829405307769775  (0.1995727508156388)
     | > align_error: 0.5426841676235199  (0.5980151306699825)

   --> STEP: 28
     | > decoder_loss: 0.445511132478714  (0.45942763132708414)
     | > postnet_loss: 0.30081674456596375  (0.3130799468074525)
     | > stopnet_loss: 0.0040315063670277596  (0.006125884313535478)
     | > loss: 0.19061347842216492  (0.19925277680158615)
     | > align_error: 0.5670507252216339  (0.5969092590468271)

   --> STEP: 29
     | > decoder_loss: 0.4410040080547333  (0.4587923339728651)
     | > postnet_loss: 0.2969728708267212  (0.3125245303943238)
     | > stopnet_loss: 0.003724011592566967  (0.006043061116260701)
     | > loss: 0.18821823596954346  (0.19887227539358468)
     | > align_error: 0.5418002307415009  (0.5950089477259538)

   --> STEP: 30
     | > decoder_loss: 0.4407939910888672  (0.4581923892100652)
     | > postnet_loss: 0.2975916862487793  (0.3120267689228057)
     | > stopnet_loss: 0.0030725563410669565  (0.005944044290420909)
     | > loss: 0.18766897916793823  (0.19849883218606312)
     | > align_error: 0.5350817739963531  (0.5930113752683005)

   --> STEP: 31
     | > decoder_loss: 0.4402986466884613  (0.45761517170936833)
     | > postnet_loss: 0.2999837398529053  (0.3116382841140992)
     | > stopnet_loss: 0.004056072328239679  (0.005883141969060225)
     | > loss: 0.18912667036056519  (0.1981965043852406)
     | > align_error: 0.5603731274604797  (0.5919585285648225)

   --> STEP: 32
     | > decoder_loss: 0.4469228684902191  (0.4572810372337699)
     | > postnet_loss: 0.3023795783519745  (0.3113489495590328)
     | > stopnet_loss: 0.004026087932288647  (0.005825109030411113)
     | > loss: 0.19135169684886932  (0.197982604149729)
     | > align_error: 0.5324711799621582  (0.5900995489209891)

   --> STEP: 33
     | > decoder_loss: 0.44461435079574585  (0.45689719825079944)
     | > postnet_loss: 0.3010157644748688  (0.31103582273830055)
     | > stopnet_loss: 0.004168171435594559  (0.005774898800265157)
     | > loss: 0.1905757039785385  (0.1977581526293899)
     | > align_error: 0.5466671586036682  (0.5887834158810703)

   --> STEP: 34
     | > decoder_loss: 0.45101016759872437  (0.45672405029044433)
     | > postnet_loss: 0.3031795620918274  (0.3108047562486984)
     | > stopnet_loss: 0.0035062474198639393  (0.005708173759665121)
     | > loss: 0.1920536756515503  (0.19759037389474757)
     | > align_error: 0.5643838047981262  (0.5880657802609838)

   --> STEP: 35
     | > decoder_loss: 0.44783690571784973  (0.4564701318740845)
     | > postnet_loss: 0.3014450967311859  (0.3105373374053409)
     | > stopnet_loss: 0.00365859130397439  (0.0056496142609311)
     | > loss: 0.19097909331321716  (0.1974014801638467)
     | > align_error: 0.5351360440254211  (0.5865535020828249)

   --> STEP: 36
     | > decoder_loss: 0.45531976222991943  (0.45643817716174656)
     | > postnet_loss: 0.3062385022640228  (0.3104179253180821)
     | > stopnet_loss: 0.0038427843246608973  (0.00559942454047915)
     | > loss: 0.19423235952854156  (0.1973134490350882)
     | > align_error: 0.6348979473114014  (0.5878964033391743)

   --> STEP: 37
     | > decoder_loss: 0.446625292301178  (0.45617296405740687)
     | > postnet_loss: 0.30251428484916687  (0.3102043134135168)
     | > stopnet_loss: 0.0037023434415459633  (0.005548152078345821)
     | > loss: 0.190987229347229  (0.19714247012460553)
     | > align_error: 0.5200223922729492  (0.5860619706076546)

   --> STEP: 38
     | > decoder_loss: 0.4364634156227112  (0.455654291730178)
     | > postnet_loss: 0.2964516580104828  (0.3098424014292264)
     | > stopnet_loss: 0.0032878811471164227  (0.0054886712643661)
     | > loss: 0.1865166425704956  (0.1968628430837079)
     | > align_error: 0.5521518290042877  (0.5851695984601977)

   --> STEP: 39
     | > decoder_loss: 0.449553906917572  (0.45549787160677785)
     | > postnet_loss: 0.3049808144569397  (0.30971774535301394)
     | > stopnet_loss: 0.003597858129069209  (0.005440188876281564)
     | > loss: 0.19223153591156006  (0.1967440916177554)
     | > align_error: 0.5470959544181824  (0.584193351177069)

   --> STEP: 40
     | > decoder_loss: 0.4466949701309204  (0.4552777990698814)
     | > postnet_loss: 0.30357053875923157  (0.30956406518816937)
     | > stopnet_loss: 0.0031741608399897814  (0.005383538175374269)
     | > loss: 0.19074052572250366  (0.19659400247037412)
     | > align_error: 0.5851901173591614  (0.5842182703316213)

   --> STEP: 41
     | > decoder_loss: 0.43671923875808716  (0.45482515125739864)
     | > postnet_loss: 0.29565638303756714  (0.3092248534283986)
     | > stopnet_loss: 0.0038206921890378  (0.005345419980585575)
     | > loss: 0.1869145929813385  (0.19635791931210494)
     | > align_error: 0.5047788023948669  (0.582280722333164)

   --> STEP: 42
     | > decoder_loss: 0.4432870149612427  (0.4545504337265378)
     | > postnet_loss: 0.29939645528793335  (0.3089908439488637)
     | > stopnet_loss: 0.0033956910483539104  (0.0052989978631514875)
     | > loss: 0.1890665590763092  (0.19618431549696697)
     | > align_error: 0.5805629789829254  (0.5822398236819678)

   --> STEP: 43
     | > decoder_loss: 0.4405880570411682  (0.45422572729199434)
     | > postnet_loss: 0.29809173941612244  (0.30873737640159066)
     | > stopnet_loss: 0.0030620212201029062  (0.005246975150522451)
     | > loss: 0.18773196637630463  (0.1959877492383469)
     | > align_error: 0.5524804890155792  (0.5815477461315867)

   --> STEP: 44
     | > decoder_loss: 0.4594387114048004  (0.454344204203649)
     | > postnet_loss: 0.30745190382003784  (0.3087081611156463)
     | > stopnet_loss: 0.0028244645800441504  (0.00519191809210249)
     | > loss: 0.1945471316576004  (0.19595500792969356)
     | > align_error: 0.552121102809906  (0.5808789587833666)

   --> STEP: 45
     | > decoder_loss: 0.45171505212783813  (0.45428577860196434)
     | > postnet_loss: 0.3064042329788208  (0.30865696271260573)
     | > stopnet_loss: 0.003451803233474493  (0.0051532488730218675)
     | > loss: 0.19298163056373596  (0.19588893287711673)
     | > align_error: 0.5535933971405029  (0.5802726129690807)

   --> STEP: 46
     | > decoder_loss: 0.44210371375083923  (0.45402095110520074)
     | > postnet_loss: 0.29766181111335754  (0.3084179376778394)
     | > stopnet_loss: 0.0033176271244883537  (0.005113344052401574)
     | > loss: 0.18825900554656982  (0.19572306489167007)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.41299090602181177 (+0.056065270394989986)
     | > avg_decoder_loss: 0.4498896093079538 (-0.0013221989978443593)
     | > avg_postnet_loss: 0.30501983472795186 (-0.0006882927634500602)
     | > avg_stopnet_loss: 0.004529811657090305 (+8.19192042179201e-06)
     | > avg_loss: 0.19325717199932446 (-0.0004944320429454974)
     | > avg_align_error: 0.5730239446416046 (+0.000988263072389639)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_3775.pth

 > EPOCH: 25/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 00:15:46)

   --> TIME: 2025-12-28 00:15:47 -- STEP: 0/150 -- GLOBAL_STEP: 3775
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46865320205688477  (0.46865320205688477)
     | > postnet_loss: 0.4127834141254425  (0.4127834141254425)
     | > stopnet_loss: 0.01898467168211937  (0.01898467168211937)
     | > loss: 0.2393438220024109  (0.2393438220024109)
     | > align_error: 0.7514806985855103  (0.7514806985855103)
     | > grad_norm: tensor(0.4314, device='cuda:0')  (tensor(0.4314, device='cuda:0'))
     | > step_time: 0.519  (0.519024133682251)
     | > loader_time: 0.3664  (0.36635613441467285)


   --> TIME: 2025-12-28 00:16:25 -- STEP: 25/150 -- GLOBAL_STEP: 3800
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.4964921474456787  (0.4869615793228149)
     | > postnet_loss: 0.41841068863868713  (0.41760155200958254)
     | > stopnet_loss: 0.006554212421178818  (0.00979892777279019)
     | > loss: 0.23527991771697998  (0.23593971073627473)
     | > align_error: 0.6186082661151886  (0.6721711099147797)
     | > grad_norm: tensor(0.2543, device='cuda:0')  (tensor(0.2412, device='cuda:0'))
     | > step_time: 0.8891  (0.665599489212036)
     | > loader_time: 0.9014  (0.8612315845489502)


   --> TIME: 2025-12-28 00:17:18 -- STEP: 50/150 -- GLOBAL_STEP: 3825
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5031717419624329  (0.49354636490345)
     | > postnet_loss: 0.41807830333709717  (0.4179335576295853)
     | > stopnet_loss: 0.004533820785582066  (0.007697946773841975)
     | > loss: 0.2348463386297226  (0.23556792855262756)
     | > align_error: 0.6357353925704956  (0.6490674716234207)
     | > grad_norm: tensor(0.1336, device='cuda:0')  (tensor(0.2267, device='cuda:0'))
     | > step_time: 1.1216  (0.8871527576446533)
     | > loader_time: 0.8257  (0.9361273670196533)


   --> TIME: 2025-12-28 00:18:17 -- STEP: 75/150 -- GLOBAL_STEP: 3850
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49566319584846497  (0.4961438326040904)
     | > postnet_loss: 0.41603174805641174  (0.4171695359547933)
     | > stopnet_loss: 0.003671708982437849  (0.006566070265447098)
     | > loss: 0.23159544169902802  (0.23489441335201264)
     | > align_error: 0.6140294373035431  (0.637568967739741)
     | > grad_norm: tensor(0.1228, device='cuda:0')  (tensor(0.2056, device='cuda:0'))
     | > step_time: 1.4824  (1.011095921198527)
     | > loader_time: 1.3198  (0.9965264352162679)


   --> TIME: 2025-12-28 00:19:36 -- STEP: 100/150 -- GLOBAL_STEP: 3875
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4981760084629059  (0.4971789601445198)
     | > postnet_loss: 0.4111438989639282  (0.4164534595608711)
     | > stopnet_loss: 0.0035083231050521135  (0.005889612308237699)
     | > loss: 0.23083829879760742  (0.23429771840572358)
     | > align_error: 0.5858203768730164  (0.6325158128142357)
     | > grad_norm: tensor(0.1266, device='cuda:0')  (tensor(0.2009, device='cuda:0'))
     | > step_time: 1.6248  (1.1712047195434576)
     | > loader_time: 1.6568  (1.1205998849868777)


   --> TIME: 2025-12-28 00:21:11 -- STEP: 125/150 -- GLOBAL_STEP: 3900
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4978913962841034  (0.498107714176178)
     | > postnet_loss: 0.4085577726364136  (0.4159058117866516)
     | > stopnet_loss: 0.00319605297408998  (0.005408691983669995)
     | > loss: 0.22980834543704987  (0.2339120738506317)
     | > align_error: 0.5929025113582611  (0.6285594837665558)
     | > grad_norm: tensor(0.1083, device='cuda:0')  (tensor(0.1906, device='cuda:0'))
     | > step_time: 2.0489  (1.3153346500396732)
     | > loader_time: 2.1542  (1.275436460494995)


   --> TIME: 2025-12-28 00:23:07 -- STEP: 150/150 -- GLOBAL_STEP: 3925
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5144529938697815  (0.4995324774583181)
     | > postnet_loss: 0.41956666111946106  (0.415598699649175)
     | > stopnet_loss: 0.002568819560110569  (0.005028776947098471)
     | > loss: 0.23607374727725983  (0.2338115714987119)
     | > align_error: 0.5870461165904999  (0.6252702059348424)
     | > grad_norm: tensor(0.2123, device='cuda:0')  (tensor(0.1907, device='cuda:0'))
     | > step_time: 11.8892  (1.5509713363647464)
     | > loader_time: 0.744  (1.3805755837758382)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47414153814315796  (0.47414153814315796)
     | > postnet_loss: 0.3337797224521637  (0.3337797224521637)
     | > stopnet_loss: 0.012506410479545593  (0.012506410479545593)
     | > loss: 0.2144867330789566  (0.2144867330789566)
     | > align_error: 0.7192228436470032  (0.7192228436470032)

   --> STEP: 1
     | > decoder_loss: 0.4540136754512787  (0.4540136754512787)
     | > postnet_loss: 0.3187020719051361  (0.3187020719051361)
     | > stopnet_loss: 0.009863500483334064  (0.009863500483334064)
     | > loss: 0.2030424326658249  (0.2030424326658249)
     | > align_error: 0.6604592204093933  (0.6604592204093933)

   --> STEP: 2
     | > decoder_loss: 0.44922250509262085  (0.45161809027194977)
     | > postnet_loss: 0.3148162364959717  (0.3167591542005539)
     | > stopnet_loss: 0.011187347583472729  (0.010525424033403397)
     | > loss: 0.20219703018665314  (0.202619731426239)
     | > align_error: 0.6580901443958282  (0.6592746824026108)

   --> STEP: 3
     | > decoder_loss: 0.45116692781448364  (0.45146770278612774)
     | > postnet_loss: 0.3108106553554535  (0.3147763212521871)
     | > stopnet_loss: 0.008677102625370026  (0.009909316897392273)
     | > loss: 0.19917148351669312  (0.20147031545639038)
     | > align_error: 0.7359618544578552  (0.6848370730876923)

   --> STEP: 4
     | > decoder_loss: 0.4610579311847687  (0.45386525988578796)
     | > postnet_loss: 0.32135167717933655  (0.31642016023397446)
     | > stopnet_loss: 0.008419428952038288  (0.009536844911053777)
     | > loss: 0.20402182638645172  (0.20210819318890572)
     | > align_error: 0.6055077910423279  (0.6650047525763512)

   --> STEP: 5
     | > decoder_loss: 0.4414130449295044  (0.45137481689453124)
     | > postnet_loss: 0.3048187494277954  (0.31409987807273865)
     | > stopnet_loss: 0.008427895605564117  (0.009315055049955844)
     | > loss: 0.19498583674430847  (0.20068372189998626)
     | > align_error: 0.6437450647354126  (0.6607528150081634)

   --> STEP: 6
     | > decoder_loss: 0.45784470438957214  (0.4524531314770381)
     | > postnet_loss: 0.31477802991867065  (0.314212903380394)
     | > stopnet_loss: 0.007406365592032671  (0.008996940140301982)
     | > loss: 0.20056204497814178  (0.20066344241301218)
     | > align_error: 0.5957029759883881  (0.6499111751715342)

   --> STEP: 7
     | > decoder_loss: 0.46570834517478943  (0.4543467334338597)
     | > postnet_loss: 0.3148883879184723  (0.31430940117154804)
     | > stopnet_loss: 0.006564020179212093  (0.00864938014586057)
     | > loss: 0.2017132043838501  (0.20081340840884618)
     | > align_error: 0.5809498131275177  (0.640059552022389)

   --> STEP: 8
     | > decoder_loss: 0.4614310562610626  (0.45523227378726006)
     | > postnet_loss: 0.31416749954223633  (0.31429166346788406)
     | > stopnet_loss: 0.007682334631681442  (0.008528499456588179)
     | > loss: 0.20158196985721588  (0.2009094785898924)
     | > align_error: 0.5771588981151581  (0.6321969702839851)

   --> STEP: 9
     | > decoder_loss: 0.4587220251560211  (0.45562002393934464)
     | > postnet_loss: 0.315461665391922  (0.3144216636816661)
     | > stopnet_loss: 0.0068422951735556126  (0.008341143425140116)
     | > loss: 0.20038822293281555  (0.20085156129466164)
     | > align_error: 0.5938462018966675  (0.6279357737965054)

   --> STEP: 10
     | > decoder_loss: 0.49027857184410095  (0.45908587872982026)
     | > postnet_loss: 0.3309086263179779  (0.31607035994529725)
     | > stopnet_loss: 0.006002690177410841  (0.00810729810036719)
     | > loss: 0.21129949390888214  (0.20189635455608368)
     | > align_error: 0.5881657600402832  (0.6239587724208832)

   --> STEP: 11
     | > decoder_loss: 0.47339242696762085  (0.46038647402416577)
     | > postnet_loss: 0.32281720638275146  (0.31668370962142944)
     | > stopnet_loss: 0.006041498389095068  (0.007919498126615177)
     | > loss: 0.20509390532970428  (0.2021870409900492)
     | > align_error: 0.595978856086731  (0.621415143663233)

   --> STEP: 12
     | > decoder_loss: 0.4652833044528961  (0.46079454322655994)
     | > postnet_loss: 0.3129025399684906  (0.3163686121503512)
     | > stopnet_loss: 0.008018424734473228  (0.007927742010603348)
     | > loss: 0.20256488025188446  (0.20221852759520212)
     | > align_error: 0.5894154012203217  (0.6187484984596571)

   --> STEP: 13
     | > decoder_loss: 0.458172082901001  (0.4605928155092093)
     | > postnet_loss: 0.3145258128643036  (0.3162268583591168)
     | > stopnet_loss: 0.005759404040873051  (0.007760946782162556)
     | > loss: 0.19893388450145721  (0.20196586274183714)
     | > align_error: 0.5881166458129883  (0.616392202102221)

   --> STEP: 14
     | > decoder_loss: 0.4645063281059265  (0.4608723521232605)
     | > postnet_loss: 0.3147398829460144  (0.31612064582960947)
     | > stopnet_loss: 0.005134244915097952  (0.00757332522022937)
     | > loss: 0.19994579255580902  (0.2018215720142637)
     | > align_error: 0.5557109117507935  (0.6120578242199761)

   --> STEP: 15
     | > decoder_loss: 0.46645039319992065  (0.4612442215283712)
     | > postnet_loss: 0.32102856040000916  (0.31644784013430277)
     | > stopnet_loss: 0.00513102812692523  (0.007410505414009094)
     | > loss: 0.20200075209140778  (0.20183351735273997)
     | > align_error: 0.5900366604328156  (0.6105897466341654)

   --> STEP: 16
     | > decoder_loss: 0.46517884731292725  (0.46149013563990593)
     | > postnet_loss: 0.31241366267204285  (0.31619570404291153)
     | > stopnet_loss: 0.005313193891197443  (0.007279423443833366)
     | > loss: 0.19971132278442383  (0.2017008801922202)
     | > align_error: 0.6081317663192749  (0.6104361228644848)

   --> STEP: 17
     | > decoder_loss: 0.475243479013443  (0.4622991558383493)
     | > postnet_loss: 0.3243355453014374  (0.31667451823458953)
     | > stopnet_loss: 0.004985725972801447  (0.00714450006318443)
     | > loss: 0.2048804759979248  (0.2018879152396146)
     | > align_error: 0.559495210647583  (0.6074395986164317)

   --> STEP: 18
     | > decoder_loss: 0.46990758180618286  (0.4627218461698956)
     | > postnet_loss: 0.31638777256011963  (0.3166585879193412)
     | > stopnet_loss: 0.005508313421159983  (0.007053600805294182)
     | > loss: 0.20208215713500977  (0.20189870645602545)
     | > align_error: 0.6051439940929413  (0.6073120650317934)

   --> STEP: 19
     | > decoder_loss: 0.46731168031692505  (0.4629634163881603)
     | > postnet_loss: 0.31472864747047424  (0.31655701210624293)
     | > stopnet_loss: 0.005027041304856539  (0.0069469397789553595)
     | > loss: 0.20053713023662567  (0.20182704454974124)
     | > align_error: 0.6020638644695282  (0.6070358439495689)

   --> STEP: 20
     | > decoder_loss: 0.46275460720062256  (0.46295297592878343)
     | > postnet_loss: 0.31353893876075745  (0.31640610843896866)
     | > stopnet_loss: 0.00468404870480299  (0.006833795225247741)
     | > loss: 0.19875742495059967  (0.20167356356978416)
     | > align_error: 0.62354776263237  (0.607861439883709)

   --> STEP: 21
     | > decoder_loss: 0.460379958152771  (0.46283045127278283)
     | > postnet_loss: 0.3090822696685791  (0.31605735421180725)
     | > stopnet_loss: 0.004179622512310743  (0.006707406048441217)
     | > loss: 0.19654518365859985  (0.2014293550025849)
     | > align_error: 0.5618855953216553  (0.6056721139521826)

   --> STEP: 22
     | > decoder_loss: 0.46204596757888794  (0.4627947929230603)
     | > postnet_loss: 0.3128003478050232  (0.3159093084660443)
     | > stopnet_loss: 0.0050705112516880035  (0.0066330017394978895)
     | > loss: 0.1987820863723755  (0.20130902461030267)
     | > align_error: 0.6266191303730011  (0.6066242510622198)

   --> STEP: 23
     | > decoder_loss: 0.43410053849220276  (0.4615472166434578)
     | > postnet_loss: 0.30185630917549133  (0.31529830849688983)
     | > stopnet_loss: 0.004696105606853962  (0.0065487888641655445)
     | > loss: 0.1886853128671646  (0.2007601675779923)
     | > align_error: 0.567592442035675  (0.6049272158871527)

   --> STEP: 24
     | > decoder_loss: 0.46908533573150635  (0.4618613049387932)
     | > postnet_loss: 0.31792011857032776  (0.31540755058328307)
     | > stopnet_loss: 0.004519111011177301  (0.006464218953624368)
     | > loss: 0.2012704610824585  (0.20078142980734506)
     | > align_error: 0.5807390213012695  (0.6039193744460742)

   --> STEP: 25
     | > decoder_loss: 0.46923571825027466  (0.46215628147125243)
     | > postnet_loss: 0.314468652009964  (0.3153699946403503)
     | > stopnet_loss: 0.00383487856015563  (0.006359045337885619)
     | > loss: 0.19976097345352173  (0.20074061155319214)
     | > align_error: 0.559638500213623  (0.6021481394767761)

   --> STEP: 26
     | > decoder_loss: 0.443024218082428  (0.46142043287937456)
     | > postnet_loss: 0.3016757369041443  (0.314843292419727)
     | > stopnet_loss: 0.0046042464673519135  (0.006291553073634322)
     | > loss: 0.19077923893928528  (0.20035748183727264)
     | > align_error: 0.5485582947731018  (0.6000869916035578)

   --> STEP: 27
     | > decoder_loss: 0.4405157268047333  (0.46064618450623973)
     | > postnet_loss: 0.2997203767299652  (0.31428318443121733)
     | > stopnet_loss: 0.00406032195314765  (0.006208914883986667)
     | > loss: 0.189119353890419  (0.19994125487627806)
     | > align_error: 0.5423824787139893  (0.5979497874224627)

   --> STEP: 28
     | > decoder_loss: 0.44599848985671997  (0.46012305255447117)
     | > postnet_loss: 0.30257707834243774  (0.31386510921376093)
     | > stopnet_loss: 0.004047428257763386  (0.006131718933050122)
     | > loss: 0.19119131565093994  (0.1996287570468017)
     | > align_error: 0.5670838356018066  (0.5968474320002964)

   --> STEP: 29
     | > decoder_loss: 0.4414919316768646  (0.45948060011041575)
     | > postnet_loss: 0.29824116826057434  (0.3133263526291683)
     | > stopnet_loss: 0.003729971358552575  (0.006048900051170896)
     | > loss: 0.18866324424743652  (0.19925063591578912)
     | > align_error: 0.541475772857666  (0.594938064443654)

   --> STEP: 30
     | > decoder_loss: 0.44114455580711365  (0.458869398633639)
     | > postnet_loss: 0.2990206778049469  (0.3128494968016942)
     | > stopnet_loss: 0.003066134173423052  (0.005949474521912634)
     | > loss: 0.1881074458360672  (0.19887919624646505)
     | > align_error: 0.5349390506744385  (0.5929380973180135)

   --> STEP: 31
     | > decoder_loss: 0.44027936458587646  (0.4582697201159693)
     | > postnet_loss: 0.3018171489238739  (0.31249361461208713)
     | > stopnet_loss: 0.0040750824846327305  (0.005889010262645541)
     | > loss: 0.18959921598434448  (0.19857984204446116)
     | > align_error: 0.5600202679634094  (0.5918762318549617)

   --> STEP: 32
     | > decoder_loss: 0.44770780205726624  (0.4579396601766348)
     | > postnet_loss: 0.3042818605899811  (0.3122369972988963)
     | > stopnet_loss: 0.004024931229650974  (0.0058307577928644605)
     | > loss: 0.19202235341072083  (0.19837492052465677)
     | > align_error: 0.5323399901390076  (0.5900157243013382)

   --> STEP: 33
     | > decoder_loss: 0.4453548192977905  (0.45755830136212433)
     | > postnet_loss: 0.303602397441864  (0.3119753427577741)
     | > stopnet_loss: 0.004199278075248003  (0.005781319013542749)
     | > loss: 0.19143858551979065  (0.19816472855481235)
     | > align_error: 0.5465526580810547  (0.5886986616886023)

   --> STEP: 34
     | > decoder_loss: 0.45128822326660156  (0.45737388730049133)
     | > postnet_loss: 0.30566349625587463  (0.3117897002136006)
     | > stopnet_loss: 0.0035131212789565325  (0.005714607315466684)
     | > loss: 0.19275104999542236  (0.19800550271483028)
     | > align_error: 0.5639880895614624  (0.5879718801554512)

   --> STEP: 35
     | > decoder_loss: 0.4485262930393219  (0.4571210988930294)
     | > postnet_loss: 0.30331283807754517  (0.31154750415257043)
     | > stopnet_loss: 0.0036681725177913904  (0.005656137749818819)
     | > loss: 0.19162796437740326  (0.19782328733376095)
     | > align_error: 0.5346538126468658  (0.586448506798063)

   --> STEP: 36
     | > decoder_loss: 0.4557189345359802  (0.4570821498831113)
     | > postnet_loss: 0.30831944942474365  (0.3114578359656864)
     | > stopnet_loss: 0.0038484157994389534  (0.0056059232511971565)
     | > loss: 0.19485801458358765  (0.19774091864625612)
     | > align_error: 0.6345920264720917  (0.5877858267890083)

   --> STEP: 37
     | > decoder_loss: 0.44712164998054504  (0.45681294718304194)
     | > postnet_loss: 0.3043470084667206  (0.3112656514386873)
     | > stopnet_loss: 0.0037338370457291603  (0.005555326326725049)
     | > loss: 0.1916010081768036  (0.1975749751200547)
     | > align_error: 0.5197197794914246  (0.5859462038890736)

   --> STEP: 38
     | > decoder_loss: 0.43652355670928955  (0.4562790158547853)
     | > postnet_loss: 0.29844605922698975  (0.3109282937489058)
     | > stopnet_loss: 0.0032890525180846453  (0.005495687542287144)
     | > loss: 0.18703146278858185  (0.19729751426922648)
     | > align_error: 0.5516769886016846  (0.5850443824341423)

   --> STEP: 39
     | > decoder_loss: 0.4489798843860626  (0.45609185863763857)
     | > postnet_loss: 0.30607742071151733  (0.31080391238897276)
     | > stopnet_loss: 0.0036220019683241844  (0.00544764432244194)
     | > loss: 0.19238632917404175  (0.19717158644627303)
     | > align_error: 0.5468642711639404  (0.5840654052220858)

   --> STEP: 40
     | > decoder_loss: 0.4462263882160187  (0.4558452218770981)
     | > postnet_loss: 0.3048265874385834  (0.310654479265213)
     | > stopnet_loss: 0.00317910173907876  (0.00539093075785786)
     | > loss: 0.19094234704971313  (0.19701585546135902)
     | > align_error: 0.5848170816898346  (0.5840841971337796)

   --> STEP: 41
     | > decoder_loss: 0.4370875358581543  (0.4553877173400507)
     | > postnet_loss: 0.29723161458969116  (0.3103270923219076)
     | > stopnet_loss: 0.0038230130448937416  (0.005352688862419712)
     | > loss: 0.18740279972553253  (0.19678139068731448)
     | > align_error: 0.5044673085212708  (0.5821423218017672)

   --> STEP: 42
     | > decoder_loss: 0.4429854154586792  (0.45509242443811326)
     | > postnet_loss: 0.30146604776382446  (0.31011611507052467)
     | > stopnet_loss: 0.003402682486921549  (0.005306260139193565)
     | > loss: 0.18951554596424103  (0.19660839438438416)
     | > align_error: 0.5801757574081421  (0.5820954988400142)

   --> STEP: 43
     | > decoder_loss: 0.440755695104599  (0.45475901212803155)
     | > postnet_loss: 0.3001730740070343  (0.3098848815574202)
     | > stopnet_loss: 0.0030753209721297026  (0.005254377832982777)
     | > loss: 0.1883075088262558  (0.19641535053419512)
     | > align_error: 0.5521988272666931  (0.5814002274080765)

   --> STEP: 44
     | > decoder_loss: 0.4590429663658142  (0.45485637472434476)
     | > postnet_loss: 0.3090294301509857  (0.3098654394800013)
     | > stopnet_loss: 0.0028178421780467033  (0.00519900202264332)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3567296411051895 (-0.056261264916622256)
     | > avg_decoder_loss: 0.45007981630888855 (+0.00019020700093475007)
     | > avg_postnet_loss: 0.3060073039748452 (+0.0009874692468933577)
     | > avg_stopnet_loss: 0.004536482590166005 (+6.670933075700325e-06)
     | > avg_loss: 0.19355826147577979 (+0.000301089476455324)
     | > avg_align_error: 0.5728367698011976 (-0.0001871748404069784)


 > EPOCH: 26/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 00:24:54)

   --> TIME: 2025-12-28 00:25:31 -- STEP: 24/150 -- GLOBAL_STEP: 3950
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4909203052520752  (0.48674367119868595)
     | > postnet_loss: 0.41768699884414673  (0.4178238684932391)
     | > stopnet_loss: 0.006515070796012878  (0.009947660165683676)
     | > loss: 0.23366689682006836  (0.2360895456125339)
     | > align_error: 0.6928861737251282  (0.6730989292263985)
     | > grad_norm: tensor(0.2007, device='cuda:0')  (tensor(0.2784, device='cuda:0'))
     | > step_time: 0.8852  (0.6518547733624777)
     | > loader_time: 0.8778  (0.8317262430985769)


   --> TIME: 2025-12-28 00:26:24 -- STEP: 49/150 -- GLOBAL_STEP: 3975
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.49896883964538574  (0.4930457010561106)
     | > postnet_loss: 0.41413500905036926  (0.41778372136914)
     | > stopnet_loss: 0.005161808338016272  (0.007769320616308521)
     | > loss: 0.23343776166439056  (0.23547667690685817)
     | > align_error: 0.5852751135826111  (0.6482622355830914)
     | > grad_norm: tensor(0.1759, device='cuda:0')  (tensor(0.2452, device='cuda:0'))
     | > step_time: 1.2831  (0.8812351518747757)
     | > loader_time: 1.2076  (0.9307645778266751)


   --> TIME: 2025-12-28 00:27:29 -- STEP: 74/150 -- GLOBAL_STEP: 4000
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4994470775127411  (0.49579043686389923)
     | > postnet_loss: 0.4210500121116638  (0.4169604250708142)
     | > stopnet_loss: 0.0038662508595734835  (0.006613687077235127)
     | > loss: 0.23399052023887634  (0.2348014029699403)
     | > align_error: 0.6032602190971375  (0.6372305319921391)
     | > grad_norm: tensor(0.1527, device='cuda:0')  (tensor(0.2192, device='cuda:0'))
     | > step_time: 1.4588  (1.0494969889924337)
     | > loader_time: 1.2774  (1.0287399130898554)


   --> TIME: 2025-12-28 00:28:48 -- STEP: 99/150 -- GLOBAL_STEP: 4025
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5057677030563354  (0.49694050502295445)
     | > postnet_loss: 0.41887250542640686  (0.41632395109744996)
     | > stopnet_loss: 0.003673932049423456  (0.0059217502400655325)
     | > loss: 0.2348339706659317  (0.2342378647640498)
     | > align_error: 0.6049519181251526  (0.6325459037766313)
     | > grad_norm: tensor(0.2917, device='cuda:0')  (tensor(0.2065, device='cuda:0'))
     | > step_time: 1.6402  (1.2015868822733557)
     | > loader_time: 1.6454  (1.1528196334838867)


   --> TIME: 2025-12-28 00:30:17 -- STEP: 124/150 -- GLOBAL_STEP: 4050
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.500514566898346  (0.4977682619806259)
     | > postnet_loss: 0.40998873114585876  (0.41569606407034787)
     | > stopnet_loss: 0.0036268155090510845  (0.005428474839596497)
     | > loss: 0.23125262558460236  (0.23379455687057588)
     | > align_error: 0.6161928176879883  (0.6285585023222431)
     | > grad_norm: tensor(0.1093, device='cuda:0')  (tensor(0.1970, device='cuda:0'))
     | > step_time: 1.7858  (1.3319999248750745)
     | > loader_time: 1.7198  (1.2601496000443737)


   --> TIME: 2025-12-28 00:32:12 -- STEP: 149/150 -- GLOBAL_STEP: 4075
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5296460390090942  (0.4991166473635091)
     | > postnet_loss: 0.42926567792892456  (0.41530605030539863)
     | > stopnet_loss: 0.0026042102836072445  (0.005048350062246289)
     | > loss: 0.24233214557170868  (0.2336540248169995)
     | > align_error: 0.6263467669487  (0.6252962748876354)
     | > grad_norm: tensor(0.2183, device='cuda:0')  (tensor(0.1922, device='cuda:0'))
     | > step_time: 14.6046  (1.5599947215726708)
     | > loader_time: 2.1562  (1.3703528218621372)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4740540087223053  (0.4740540087223053)
     | > postnet_loss: 0.3335304260253906  (0.3335304260253906)
     | > stopnet_loss: 0.01243823766708374  (0.01243823766708374)
     | > loss: 0.21433433890342712  (0.21433433890342712)
     | > align_error: 0.7190670073032379  (0.7190670073032379)

   --> STEP: 1
     | > decoder_loss: 0.45467978715896606  (0.45467978715896606)
     | > postnet_loss: 0.31937354803085327  (0.31937354803085327)
     | > stopnet_loss: 0.009851621463894844  (0.009851621463894844)
     | > loss: 0.20336495339870453  (0.20336495339870453)
     | > align_error: 0.6602786481380463  (0.6602786481380463)

   --> STEP: 2
     | > decoder_loss: 0.4492300748825073  (0.4519549310207367)
     | > postnet_loss: 0.31433844566345215  (0.3168559968471527)
     | > stopnet_loss: 0.011200978420674801  (0.010526299942284822)
     | > loss: 0.20209310948848724  (0.2027290314435959)
     | > align_error: 0.6576046943664551  (0.6589416712522507)

   --> STEP: 3
     | > decoder_loss: 0.45187273621559143  (0.4519275327523549)
     | > postnet_loss: 0.311074435710907  (0.3149288098017375)
     | > stopnet_loss: 0.008540179580450058  (0.009864259821673235)
     | > loss: 0.19927698373794556  (0.20157834887504578)
     | > align_error: 0.7354738414287567  (0.6844523946444193)

   --> STEP: 4
     | > decoder_loss: 0.4617411494255066  (0.45438093692064285)
     | > postnet_loss: 0.321820467710495  (0.31665172427892685)
     | > stopnet_loss: 0.008398447185754776  (0.00949780666269362)
     | > loss: 0.20428884029388428  (0.2022559717297554)
     | > align_error: 0.605598121881485  (0.6647388264536858)

   --> STEP: 5
     | > decoder_loss: 0.4414862394332886  (0.451801997423172)
     | > postnet_loss: 0.3045177459716797  (0.3142249286174774)
     | > stopnet_loss: 0.00840037688612938  (0.009278320707380772)
     | > loss: 0.19490137696266174  (0.20078505277633668)
     | > align_error: 0.6435916423797607  (0.6605093896389007)

   --> STEP: 6
     | > decoder_loss: 0.45822674036026  (0.45287278791268665)
     | > postnet_loss: 0.3147408068180084  (0.3143109083175659)
     | > stopnet_loss: 0.007407900411635637  (0.00896658399142325)
     | > loss: 0.20064979791641235  (0.20076251029968262)
     | > align_error: 0.5956531167030334  (0.6497000108162562)

   --> STEP: 7
     | > decoder_loss: 0.46474066376686096  (0.4545681987489973)
     | > postnet_loss: 0.31380435824394226  (0.31423854402133394)
     | > stopnet_loss: 0.006517683621495962  (0.008616741081433637)
     | > loss: 0.2011539340019226  (0.20081842797143118)
     | > align_error: 0.580925852060318  (0.6398751309939793)

   --> STEP: 8
     | > decoder_loss: 0.4617744982242584  (0.4554689861834049)
     | > postnet_loss: 0.31421247124671936  (0.31423528492450714)
     | > stopnet_loss: 0.007632917258888483  (0.008493763103615493)
     | > loss: 0.2016296535730362  (0.2009198311716318)
     | > align_error: 0.5770277976989746  (0.6320192143321037)

   --> STEP: 9
     | > decoder_loss: 0.4586198627948761  (0.4558190835846795)
     | > postnet_loss: 0.3149605393409729  (0.3143158687485589)
     | > stopnet_loss: 0.006854336708784103  (0.008311604615300894)
     | > loss: 0.20024944841861725  (0.20084534419907463)
     | > align_error: 0.593743085861206  (0.6277663111686707)

   --> STEP: 10
     | > decoder_loss: 0.4902607798576355  (0.4592632532119751)
     | > postnet_loss: 0.33053746819496155  (0.31593802869319915)
     | > stopnet_loss: 0.005952651612460613  (0.008075709315016865)
     | > loss: 0.21115222573280334  (0.2018760323524475)
     | > align_error: 0.5882519781589508  (0.6238148778676986)

   --> STEP: 11
     | > decoder_loss: 0.47247302532196045  (0.4604641415856101)
     | > postnet_loss: 0.3218673765659332  (0.31647706031799316)
     | > stopnet_loss: 0.00599374994635582  (0.007886440281502226)
     | > loss: 0.20457884669303894  (0.20212174274704672)
     | > align_error: 0.595774382352829  (0.6212657419118014)

   --> STEP: 12
     | > decoder_loss: 0.4647236168384552  (0.46081909785668057)
     | > postnet_loss: 0.31210049986839294  (0.31611234694719315)
     | > stopnet_loss: 0.008069809526205063  (0.007901721051894128)
     | > loss: 0.2022758424282074  (0.20213458438714346)
     | > align_error: 0.5893340408802032  (0.6186047668258349)

   --> STEP: 13
     | > decoder_loss: 0.458324134349823  (0.4606271775869223)
     | > postnet_loss: 0.3143165409564972  (0.3159742080248319)
     | > stopnet_loss: 0.005722535774111748  (0.0077340914151416374)
     | > loss: 0.19888271391391754  (0.20188444050458762)
     | > align_error: 0.5880506038665771  (0.6162544465981997)

   --> STEP: 14
     | > decoder_loss: 0.46447187662124634  (0.46090179894651684)
     | > postnet_loss: 0.31402847170829773  (0.3158352268593652)
     | > stopnet_loss: 0.005114625208079815  (0.007546986686065793)
     | > loss: 0.1997397094964981  (0.20173124543258122)
     | > align_error: 0.5557200014591217  (0.6119305576596942)

   --> STEP: 15
     | > decoder_loss: 0.4668129086494446  (0.46129587292671204)
     | > postnet_loss: 0.3201577663421631  (0.3161233961582184)
     | > stopnet_loss: 0.005106315016746521  (0.0073842752414445085)
     | > loss: 0.20184898376464844  (0.20173909465471904)
     | > align_error: 0.5898872017860413  (0.6104610006014506)

   --> STEP: 16
     | > decoder_loss: 0.46536847949028015  (0.46155041083693504)
     | > postnet_loss: 0.3114606440067291  (0.3158319741487503)
     | > stopnet_loss: 0.005282748490571976  (0.007252929819514975)
     | > loss: 0.199490025639534  (0.20159852784126997)
     | > align_error: 0.6080925762653351  (0.6103129740804434)

   --> STEP: 17
     | > decoder_loss: 0.4746336042881012  (0.4623200104517095)
     | > postnet_loss: 0.3230206370353699  (0.3162548366714926)
     | > stopnet_loss: 0.004966393578797579  (0.007118427687708069)
     | > loss: 0.20437996089458466  (0.2017621415502885)
     | > align_error: 0.559600293636322  (0.6073298752307892)

   --> STEP: 18
     | > decoder_loss: 0.46958792209625244  (0.4627237833208508)
     | > postnet_loss: 0.31517496705055237  (0.3161948439147737)
     | > stopnet_loss: 0.005477939732372761  (0.007027289467967219)
     | > loss: 0.2016686499118805  (0.20175694757037693)
     | > align_error: 0.6050750017166138  (0.6072046044800017)

   --> STEP: 19
     | > decoder_loss: 0.46711626648902893  (0.46295496664549174)
     | > postnet_loss: 0.31372910737991333  (0.31606506830767583)
     | > stopnet_loss: 0.005000657867640257  (0.006920624646897379)
     | > loss: 0.2002120018005371  (0.2016756346351222)
     | > align_error: 0.6021138429641724  (0.6069366696633791)

   --> STEP: 20
     | > decoder_loss: 0.4620121717453003  (0.46290782690048216)
     | > postnet_loss: 0.31187567114830017  (0.315855598449707)
     | > stopnet_loss: 0.0046605137176811695  (0.006807619100436568)
     | > loss: 0.1981324851512909  (0.20149847716093064)
     | > align_error: 0.6235256493091583  (0.607766118645668)

   --> STEP: 21
     | > decoder_loss: 0.45971280336380005  (0.46275568292254493)
     | > postnet_loss: 0.30781400203704834  (0.31547266528719947)
     | > stopnet_loss: 0.004154970869421959  (0.006681302518007301)
     | > loss: 0.1960366666316986  (0.20123839094525292)
     | > align_error: 0.5619284510612488  (0.6055833725702195)

   --> STEP: 22
     | > decoder_loss: 0.4621180295944214  (0.4627266986803575)
     | > postnet_loss: 0.311850905418396  (0.3153080398386175)
     | > stopnet_loss: 0.005061793141067028  (0.0066076884554191065)
     | > loss: 0.19855402410030365  (0.20111637427048248)
     | > align_error: 0.6264081597328186  (0.6065299538048832)

   --> STEP: 23
     | > decoder_loss: 0.43341049551963806  (0.46145208115163056)
     | > postnet_loss: 0.3005329966545105  (0.3146656466566998)
     | > stopnet_loss: 0.004687519744038582  (0.006524202859272127)
     | > loss: 0.18817338347434998  (0.20055363554021585)
     | > align_error: 0.5674121975898743  (0.6048291817955349)

   --> STEP: 24
     | > decoder_loss: 0.468959778547287  (0.4617649018764496)
     | > postnet_loss: 0.31654688715934753  (0.3147440316776435)
     | > stopnet_loss: 0.004510592203587294  (0.0064403024152852595)
     | > loss: 0.2008872628211975  (0.20056753667692342)
     | > align_error: 0.5809310674667358  (0.603833427031835)

   --> STEP: 25
     | > decoder_loss: 0.46919044852256775  (0.4620619237422943)
     | > postnet_loss: 0.3133223354816437  (0.31468716382980344)
     | > stopnet_loss: 0.0038253965321928263  (0.006335706179961562)
     | > loss: 0.19945359230041504  (0.2005229789018631)
     | > align_error: 0.5597689747810364  (0.602070848941803)

   --> STEP: 26
     | > decoder_loss: 0.4424116909503937  (0.46130614555799043)
     | > postnet_loss: 0.30033665895462036  (0.31413522133460414)
     | > stopnet_loss: 0.004582536872476339  (0.00626827659121213)
     | > loss: 0.19026963412761688  (0.20012861948746902)
     | > align_error: 0.5483863949775696  (0.6000060622508709)

   --> STEP: 27
     | > decoder_loss: 0.44034790992736816  (0.4605299146087081)
     | > postnet_loss: 0.29829180240631104  (0.3135484280409636)
     | > stopnet_loss: 0.004049951676279306  (0.006186116409177582)
     | > loss: 0.18870988488197327  (0.19970570339096916)
     | > align_error: 0.5424773097038269  (0.5978753677120915)

   --> STEP: 28
     | > decoder_loss: 0.4453950524330139  (0.45998938381671906)
     | > postnet_loss: 0.30125394463539124  (0.31310933934790747)
     | > stopnet_loss: 0.004051819909363985  (0.006109891534184239)
     | > loss: 0.19071407616138458  (0.19938457384705544)
     | > align_error: 0.5667517781257629  (0.5967638109411512)

   --> STEP: 29
     | > decoder_loss: 0.44096770882606506  (0.4593334639894551)
     | > postnet_loss: 0.2970033586025238  (0.3125539607015149)
     | > stopnet_loss: 0.0037211081944406033  (0.006027519694882734)
     | > loss: 0.18821386992931366  (0.19899937716023675)
     | > align_error: 0.5414267778396606  (0.5948556373859274)

   --> STEP: 30
     | > decoder_loss: 0.4408036470413208  (0.4587158034245173)
     | > postnet_loss: 0.2978377342224121  (0.3120634198188782)
     | > stopnet_loss: 0.0030420003458857536  (0.0059280023832495015)
     | > loss: 0.18770234286785126  (0.19862280935049056)
     | > align_error: 0.5348077416419983  (0.5928540408611298)

   --> STEP: 31
     | > decoder_loss: 0.44000619649887085  (0.4581122677172384)
     | > postnet_loss: 0.3003806471824646  (0.3116865561854455)
     | > stopnet_loss: 0.004075686447322369  (0.00586825025628411)
     | > loss: 0.1891724020242691  (0.1983179575012576)
     | > align_error: 0.5601052641868591  (0.5917976287103468)

   --> STEP: 32
     | > decoder_loss: 0.4472627639770508  (0.45777322072535753)
     | > postnet_loss: 0.30285724997520447  (0.31141064036637545)
     | > stopnet_loss: 0.004024744499474764  (0.005810640701383818)
     | > loss: 0.19155475497245789  (0.19810660742223263)
     | > align_error: 0.5321427583694458  (0.5899334140121937)

   --> STEP: 33
     | > decoder_loss: 0.4448206126689911  (0.4573807174509222)
     | > postnet_loss: 0.3019507825374603  (0.31112397800792346)
     | > stopnet_loss: 0.004161771386861801  (0.00576067496458012)
     | > loss: 0.19085462391376495  (0.19788685034621845)
     | > align_error: 0.5464321076869965  (0.5886151926083998)

   --> STEP: 34
     | > decoder_loss: 0.4506264925003052  (0.45718206377590404)
     | > postnet_loss: 0.3038879632949829  (0.3109111540457782)
     | > stopnet_loss: 0.003495501819998026  (0.005694052225033588)
     | > loss: 0.1921241134405136  (0.19771735808428595)
     | > align_error: 0.5639601051807404  (0.5878900429781746)

   --> STEP: 35
     | > decoder_loss: 0.4477172791957855  (0.4569116413593292)
     | > postnet_loss: 0.30171477794647217  (0.31064840044294084)
     | > stopnet_loss: 0.003676448715850711  (0.005636406410485506)
     | > loss: 0.1910344660282135  (0.1975264183112553)
     | > align_error: 0.5345828533172607  (0.5863669804164342)

   --> STEP: 36
     | > decoder_loss: 0.45558544993400574  (0.4568748027086258)
     | > postnet_loss: 0.30697503685951233  (0.3105463625656234)
     | > stopnet_loss: 0.003834458300843835  (0.005586352296328793)
     | > loss: 0.19447457790374756  (0.19744164496660233)
     | > align_error: 0.6344226896762848  (0.5877018612292078)

   --> STEP: 37
     | > decoder_loss: 0.4466455578804016  (0.4565983366321873)
     | > postnet_loss: 0.302909255027771  (0.3103399542537895)
     | > stopnet_loss: 0.003706097835674882  (0.005535534608203011)
     | > loss: 0.1910948008298874  (0.197270108638583)
     | > align_error: 0.5196558237075806  (0.5858627791340286)

   --> STEP: 38
     | > decoder_loss: 0.43574681878089905  (0.456049612478206)
     | > postnet_loss: 0.2966856062412262  (0.3099806293060905)
     | > stopnet_loss: 0.0032631640788167715  (0.005475735383745479)
     | > loss: 0.18637126684188843  (0.1969832970123542)
     | > align_error: 0.5517444908618927  (0.5849649294426567)

   --> STEP: 39
     | > decoder_loss: 0.44902873039245605  (0.4558695898606227)
     | > postnet_loss: 0.30488353967666626  (0.30984993470020783)
     | > stopnet_loss: 0.003609924577176571  (0.005427894081012943)
     | > loss: 0.19208799302577972  (0.19685777639731383)
     | > align_error: 0.5466864705085754  (0.583983430495629)

   --> STEP: 40
     | > decoder_loss: 0.44619959592819214  (0.45562784001231194)
     | > postnet_loss: 0.3036302328109741  (0.309694442152977)
     | > stopnet_loss: 0.0031545760575681925  (0.005371061130426824)
     | > loss: 0.1906120330095291  (0.1967016328126192)
     | > align_error: 0.5848508477210999  (0.5840051159262657)

   --> STEP: 41
     | > decoder_loss: 0.4368821084499359  (0.45517062704737593)
     | > postnet_loss: 0.2958630621433258  (0.3093570914210343)
     | > stopnet_loss: 0.003823311999440193  (0.005333311151622272)
     | > loss: 0.18700960278511047  (0.1964652418363385)
     | > align_error: 0.5045453906059265  (0.5820670738452818)

   --> STEP: 42
     | > decoder_loss: 0.4425625503063202  (0.45487043474401745)
     | > postnet_loss: 0.2997303307056427  (0.3091278828325726)
     | > stopnet_loss: 0.0034082119818776846  (0.005287475457104544)
     | > loss: 0.18898142874240875  (0.19628705581029257)
     | > align_error: 0.5800924897193909  (0.5820200599375225)

   --> STEP: 43
     | > decoder_loss: 0.44041916728019714  (0.45453435875648673)
     | > postnet_loss: 0.29844292998313904  (0.30887939555700433)
     | > stopnet_loss: 0.003054084489122033  (0.005235536132267741)
     | > loss: 0.18776960670948029  (0.19608897559864577)
     | > align_error: 0.5520827770233154  (0.5813238440557967)

   --> STEP: 44
     | > decoder_loss: 0.45824044942855835  (0.45461858808994293)
     | > postnet_loss: 0.30720385909080505  (0.3088413151827725)
     | > stopnet_loss: 0.0028102819342166185  (0.0051804167186756695)
     | > loss: 0.19417135417461395  (0.19604539329355414)
     | > align_error: 0.5517818331718445  (0.580652434717525)

   --> STEP: 45
     | > decoder_loss: 0.4514346718788147  (0.4545478343963623)
     | > postnet_loss: 0.30668988823890686  (0.30879350569513103)
     | > stopnet_loss: 0.0034708227030932903  (0.0051424257405516165)
     | > loss: 0.19300197064876556  (0.1959777616792255)
     | > align_error: 0.5533786416053772  (0.5800463504261439)

   --> STEP: 46
     | > decoder_loss: 0.4418082535266876  (0.454270886986152)
     | > postnet_loss: 0.29786235094070435  (0.30855587189612177)
     | > stopnet_loss: 0.0033217628952115774  (0.005102846113479007)
     | > loss: 0.1882394254207611  (0.19580953697795453)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.36111446221669513 (+0.004384821111505621)
     | > avg_decoder_loss: 0.44980520913095184 (-0.0002746071779367032)
     | > avg_postnet_loss: 0.3048466006011673 (-0.001160703373677907)
     | > avg_stopnet_loss: 0.004521268776222837 (-1.5213813943168106e-05)
     | > avg_loss: 0.1931842224615993 (-0.0003740390141804828)
     | > avg_align_error: 0.5727506645701147 (-8.610523108287804e-05)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_4077.pth

 > EPOCH: 27/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 00:34:10)

   --> TIME: 2025-12-28 00:34:45 -- STEP: 23/150 -- GLOBAL_STEP: 4100
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4902908504009247  (0.4856770362543023)
     | > postnet_loss: 0.41790685057640076  (0.4166988212129344)
     | > stopnet_loss: 0.006528960540890694  (0.010052843626750551)
     | > loss: 0.2335783839225769  (0.235646806333376)
     | > align_error: 0.6393699645996094  (0.6729207090709519)
     | > grad_norm: tensor(0.3749, device='cuda:0')  (tensor(0.2431, device='cuda:0'))
     | > step_time: 0.8667  (0.631835647251295)
     | > loader_time: 0.8935  (0.8283041352811067)


   --> TIME: 2025-12-28 00:35:36 -- STEP: 48/150 -- GLOBAL_STEP: 4125
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4939367473125458  (0.4927863193054994)
     | > postnet_loss: 0.4109771251678467  (0.4174489577611287)
     | > stopnet_loss: 0.004790896084159613  (0.0078044649077734585)
     | > loss: 0.23101937770843506  (0.2353632841259241)
     | > align_error: 0.624578595161438  (0.6502472137411434)
     | > grad_norm: tensor(0.1804, device='cuda:0')  (tensor(0.2476, device='cuda:0'))
     | > step_time: 1.2355  (0.8548719386259714)
     | > loader_time: 1.0496  (0.910301461815834)


   --> TIME: 2025-12-28 00:36:40 -- STEP: 73/150 -- GLOBAL_STEP: 4150
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5050684809684753  (0.4957202770938612)
     | > postnet_loss: 0.41409629583358765  (0.4166602451507359)
     | > stopnet_loss: 0.004008993972092867  (0.006636067108595616)
     | > loss: 0.23380018770694733  (0.2347311981736797)
     | > align_error: 0.6535110771656036  (0.638397061661498)
     | > grad_norm: tensor(0.2784, device='cuda:0')  (tensor(0.2381, device='cuda:0'))
     | > step_time: 1.4607  (1.022074673273792)
     | > loader_time: 1.2432  (1.0143425138029334)


   --> TIME: 2025-12-28 00:38:00 -- STEP: 98/150 -- GLOBAL_STEP: 4175
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5046897530555725  (0.4966316831355192)
     | > postnet_loss: 0.42331862449645996  (0.4159278684124654)
     | > stopnet_loss: 0.004101710859686136  (0.005944649615249008)
     | > loss: 0.23610380291938782  (0.23408453759490228)
     | > align_error: 0.609201192855835  (0.6333625423056737)
     | > grad_norm: tensor(0.2060, device='cuda:0')  (tensor(0.2252, device='cuda:0'))
     | > step_time: 1.7191  (1.1772141116006034)
     | > loader_time: 1.7551  (1.1545787149546103)


   --> TIME: 2025-12-28 00:39:33 -- STEP: 123/150 -- GLOBAL_STEP: 4200
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49942949414253235  (0.4975976238890392)
     | > postnet_loss: 0.4092216491699219  (0.4154219242130837)
     | > stopnet_loss: 0.0034131137654185295  (0.0054458166733838435)
     | > loss: 0.23057588934898376  (0.2337007035569447)
     | > align_error: 0.6026456952095032  (0.6289702765340728)
     | > grad_norm: tensor(0.1122, device='cuda:0')  (tensor(0.2076, device='cuda:0'))
     | > step_time: 1.8567  (1.3081419991283882)
     | > loader_time: 1.8534  (1.3014657574940505)


   --> TIME: 2025-12-28 00:41:14 -- STEP: 148/150 -- GLOBAL_STEP: 4225
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5166730880737305  (0.49882178431427154)
     | > postnet_loss: 0.41943466663360596  (0.41495446699696614)
     | > stopnet_loss: 0.00282698730006814  (0.005062188400975051)
     | > loss: 0.2368539273738861  (0.23350625132789482)
     | > align_error: 0.6129886507987976  (0.6254213089878494)
     | > grad_norm: tensor(0.3228, device='cuda:0')  (tensor(0.2015, device='cuda:0'))
     | > step_time: 2.4667  (1.4448975630708638)
     | > loader_time: 2.0254  (1.4068811036444997)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4742668569087982  (0.4742668569087982)
     | > postnet_loss: 0.33539295196533203  (0.33539295196533203)
     | > stopnet_loss: 0.01250337716192007  (0.01250337716192007)
     | > loss: 0.2149183303117752  (0.2149183303117752)
     | > align_error: 0.7190638482570648  (0.7190638482570648)

   --> STEP: 1
     | > decoder_loss: 0.45481374859809875  (0.45481374859809875)
     | > postnet_loss: 0.32128414511680603  (0.32128414511680603)
     | > stopnet_loss: 0.009830721653997898  (0.009830721653997898)
     | > loss: 0.20385520160198212  (0.20385520160198212)
     | > align_error: 0.6600411236286163  (0.6600411236286163)

   --> STEP: 2
     | > decoder_loss: 0.4488535523414612  (0.45183365046977997)
     | > postnet_loss: 0.3146962821483612  (0.3179902136325836)
     | > stopnet_loss: 0.011210383847355843  (0.01052055275067687)
     | > loss: 0.2020978331565857  (0.2029765173792839)
     | > align_error: 0.6570236682891846  (0.6585323959589005)

   --> STEP: 3
     | > decoder_loss: 0.4523719847202301  (0.45201309521993)
     | > postnet_loss: 0.312122106552124  (0.3160341779390971)
     | > stopnet_loss: 0.008669092319905758  (0.009903399273753166)
     | > loss: 0.19979260861873627  (0.20191521445910135)
     | > align_error: 0.7354779243469238  (0.684180905421575)

   --> STEP: 4
     | > decoder_loss: 0.46265748143196106  (0.4546741917729378)
     | > postnet_loss: 0.32306376099586487  (0.31779157370328903)
     | > stopnet_loss: 0.008403525687754154  (0.009528430877253413)
     | > loss: 0.20483383536338806  (0.20264486968517303)
     | > align_error: 0.6054098010063171  (0.6644881293177605)

   --> STEP: 5
     | > decoder_loss: 0.44163405895233154  (0.45206616520881654)
     | > postnet_loss: 0.3051075041294098  (0.3152547597885132)
     | > stopnet_loss: 0.008378399536013603  (0.009298424609005452)
     | > loss: 0.1950637847185135  (0.20112865269184113)
     | > align_error: 0.6434364318847656  (0.6602777898311615)

   --> STEP: 6
     | > decoder_loss: 0.45844584703445435  (0.4531294455130895)
     | > postnet_loss: 0.3157508671283722  (0.31533744434515637)
     | > stopnet_loss: 0.007413926068693399  (0.008984341518953443)
     | > loss: 0.2009631097316742  (0.20110106219847998)
     | > align_error: 0.5953832268714905  (0.649462029337883)

   --> STEP: 7
     | > decoder_loss: 0.46545180678367615  (0.454889782837459)
     | > postnet_loss: 0.31406813859939575  (0.31515611495290485)
     | > stopnet_loss: 0.006506678648293018  (0.008630389680287667)
     | > loss: 0.20138666033744812  (0.20114186193261827)
     | > align_error: 0.5806631147861481  (0.6396336129733494)

   --> STEP: 8
     | > decoder_loss: 0.46193554997444153  (0.45577050372958183)
     | > postnet_loss: 0.3148696720600128  (0.31512030959129333)
     | > stopnet_loss: 0.007672866806387901  (0.008510699321050197)
     | > loss: 0.20187416672706604  (0.20123340003192425)
     | > align_error: 0.5767198503017426  (0.6317693926393986)

   --> STEP: 9
     | > decoder_loss: 0.46013668179512024  (0.45625563462575275)
     | > postnet_loss: 0.31592634320259094  (0.31520986888143754)
     | > stopnet_loss: 0.006807792000472546  (0.00832148739654157)
     | > loss: 0.20082354545593262  (0.20118786063459185)
     | > align_error: 0.5934809446334839  (0.6275151206387414)

   --> STEP: 10
     | > decoder_loss: 0.4911656975746155  (0.45974664092063905)
     | > postnet_loss: 0.3314826786518097  (0.3168371498584747)
     | > stopnet_loss: 0.0059240651316940784  (0.00808174517005682)
     | > loss: 0.21158616244792938  (0.2022276908159256)
     | > align_error: 0.5878119766712189  (0.6235448062419892)

   --> STEP: 11
     | > decoder_loss: 0.4738367795944214  (0.4610275626182556)
     | > postnet_loss: 0.3219778537750244  (0.31730448657816107)
     | > stopnet_loss: 0.006018396001309156  (0.007894167972897942)
     | > loss: 0.2049720585346222  (0.20247717879035257)
     | > align_error: 0.5954152345657349  (0.6209875724532388)

   --> STEP: 12
     | > decoder_loss: 0.46716782450675964  (0.46153925110896427)
     | > postnet_loss: 0.31345486640930176  (0.3169836848974228)
     | > stopnet_loss: 0.008061084896326065  (0.007908077716516951)
     | > loss: 0.2032167613506317  (0.20253881067037582)
     | > align_error: 0.5891014933586121  (0.6183303991953532)

   --> STEP: 13
     | > decoder_loss: 0.45855486392974854  (0.4613096828644092)
     | > postnet_loss: 0.3144337236881256  (0.3167875340351692)
     | > stopnet_loss: 0.005730395205318928  (0.007740563677194027)
     | > loss: 0.198977530002594  (0.20226486600362337)
     | > align_error: 0.5874751210212708  (0.6159569162588853)

   --> STEP: 14
     | > decoder_loss: 0.4637848436832428  (0.4614864800657545)
     | > postnet_loss: 0.3134574890136719  (0.3165496736764908)
     | > stopnet_loss: 0.005095422267913818  (0.0075516250051025835)
     | > loss: 0.1994059979915619  (0.202060661145619)
     | > align_error: 0.5554924607276917  (0.6116380265780857)

   --> STEP: 15
     | > decoder_loss: 0.46738922595977783  (0.4618799964586894)
     | > postnet_loss: 0.3192758560180664  (0.3167314191659292)
     | > stopnet_loss: 0.005126310978084803  (0.0073899374033013976)
     | > loss: 0.20179258286952972  (0.20204278926054636)
     | > align_error: 0.5894919633865356  (0.6101616223653158)

   --> STEP: 16
     | > decoder_loss: 0.46628546714782715  (0.4621553383767605)
     | > postnet_loss: 0.3106613755226135  (0.31635204143822193)
     | > stopnet_loss: 0.005285012070089579  (0.007258379569975659)
     | > loss: 0.1995217204093933  (0.2018852224573493)
     | > align_error: 0.6075923442840576  (0.6100010424852371)

   --> STEP: 17
     | > decoder_loss: 0.4745130240917206  (0.46288226106587577)
     | > postnet_loss: 0.32171040773391724  (0.31666723945561576)
     | > stopnet_loss: 0.004973419010639191  (0.007123970125308808)
     | > loss: 0.20402926206588745  (0.20201134243432214)
     | > align_error: 0.5592368841171265  (0.607014915522407)

   --> STEP: 18
     | > decoder_loss: 0.4699558615684509  (0.4632752388715744)
     | > postnet_loss: 0.3139796257019043  (0.3165179275804096)
     | > stopnet_loss: 0.005517664365470409  (0.0070347309164288975)
     | > loss: 0.2015015333890915  (0.2019830197095871)
     | > align_error: 0.6044678092002869  (0.6068734096156226)

   --> STEP: 19
     | > decoder_loss: 0.46875637769699097  (0.4635637198623858)
     | > postnet_loss: 0.3134283721446991  (0.3163553193995827)
     | > stopnet_loss: 0.005048616789281368  (0.006930198593947448)
     | > loss: 0.20059479773044586  (0.20190995539489545)
     | > align_error: 0.6016859412193298  (0.6066003849631861)

   --> STEP: 20
     | > decoder_loss: 0.4626905918121338  (0.4635200634598732)
     | > postnet_loss: 0.31049850583076477  (0.3160624787211418)
     | > stopnet_loss: 0.004665022250264883  (0.00681693977676332)
     | > loss: 0.19796228408813477  (0.20171257182955743)
     | > align_error: 0.6232655942440033  (0.607433645427227)

   --> STEP: 21
     | > decoder_loss: 0.4598434269428253  (0.46334498553049)
     | > postnet_loss: 0.3070202171802521  (0.3156318948382423)
     | > stopnet_loss: 0.004147831816226244  (0.006689839397690126)
     | > loss: 0.195863738656044  (0.201434055964152)
     | > align_error: 0.5613685846328735  (0.6052400711036864)

   --> STEP: 22
     | > decoder_loss: 0.46361789107322693  (0.4633573903278871)
     | > postnet_loss: 0.31157490611076355  (0.3154474862597205)
     | > stopnet_loss: 0.005022459197789431  (0.00661404938860373)
     | > loss: 0.19882066547870636  (0.20131526548754086)
     | > align_error: 0.6261177659034729  (0.6061890572309494)

   --> STEP: 23
     | > decoder_loss: 0.4339940547943115  (0.46208072356555774)
     | > postnet_loss: 0.29939430952072144  (0.3147495220536771)
     | > stopnet_loss: 0.004709260538220406  (0.006531232482065325)
     | > loss: 0.1880563497543335  (0.20073879089044488)
     | > align_error: 0.5674436390399933  (0.6045044738313426)

   --> STEP: 24
     | > decoder_loss: 0.46936899423599243  (0.4623844015101592)
     | > postnet_loss: 0.3148813843727112  (0.31475501631697017)
     | > stopnet_loss: 0.00450889440253377  (0.006446968395418177)
     | > loss: 0.20057149231433868  (0.20073182011644045)
     | > align_error: 0.5805377960205078  (0.6035058622558912)

   --> STEP: 25
     | > decoder_loss: 0.4690372049808502  (0.4626505136489868)
     | > postnet_loss: 0.31164315342903137  (0.3146305418014526)
     | > stopnet_loss: 0.0038032380398362875  (0.0063412191811949015)
     | > loss: 0.19897332787513733  (0.20066148042678833)
     | > align_error: 0.5593566298484802  (0.6017398929595947)

   --> STEP: 26
     | > decoder_loss: 0.44299018383026123  (0.4618943471174974)
     | > postnet_loss: 0.2996087074279785  (0.3140527789409344)
     | > stopnet_loss: 0.004577284213155508  (0.006273375528578002)
     | > loss: 0.19022700190544128  (0.20026015432981345)
     | > align_error: 0.5478082895278931  (0.5996656005199139)

   --> STEP: 27
     | > decoder_loss: 0.44064804911613464  (0.46110744719152097)
     | > postnet_loss: 0.2966145873069763  (0.31340691999152853)
     | > stopnet_loss: 0.004049276001751423  (0.006191001472028869)
     | > loss: 0.1883649230003357  (0.19981959020649945)
     | > align_error: 0.5422486364841461  (0.5975390462963669)

   --> STEP: 28
     | > decoder_loss: 0.44564464688301086  (0.4605552043233599)
     | > postnet_loss: 0.29975107312202454  (0.31291921117476057)
     | > stopnet_loss: 0.004033575300127268  (0.006113950537318098)
     | > loss: 0.19038251042366028  (0.19948255164282663)
     | > align_error: 0.566252589225769  (0.5964216728295598)

   --> STEP: 29
     | > decoder_loss: 0.44159048795700073  (0.4599012485865889)
     | > postnet_loss: 0.29615387320518494  (0.3123410960723614)
     | > stopnet_loss: 0.0037177803460508585  (0.0060313239789985375)
     | > loss: 0.18815386295318604  (0.1990919072052528)
     | > align_error: 0.5409955382347107  (0.5945104268090479)

   --> STEP: 30
     | > decoder_loss: 0.44139307737350464  (0.45928430954615274)
     | > postnet_loss: 0.29676997661590576  (0.3118220587571462)
     | > stopnet_loss: 0.003056812100112438  (0.005932173583035668)
     | > loss: 0.18759757280349731  (0.1987087627251943)
     | > align_error: 0.5344733595848083  (0.5925091912349065)

   --> STEP: 31
     | > decoder_loss: 0.43999072909355164  (0.4586619359831656)
     | > postnet_loss: 0.29825201630592346  (0.311384315452268)
     | > stopnet_loss: 0.004083171486854553  (0.0058725283541266)
     | > loss: 0.18864385783672333  (0.1983840883739533)
     | > align_error: 0.5597496628761292  (0.5914524322555911)

   --> STEP: 32
     | > decoder_loss: 0.4468289613723755  (0.4582921555265784)
     | > postnet_loss: 0.3010117709636688  (0.3110601734369993)
     | > stopnet_loss: 0.0040120892226696014  (0.005814389631268568)
     | > loss: 0.19097228348255157  (0.198152469471097)
     | > align_error: 0.5317361354827881  (0.589586297981441)

   --> STEP: 33
     | > decoder_loss: 0.44516122341156006  (0.45789424849279)
     | > postnet_loss: 0.29989486932754517  (0.31072183088822797)
     | > stopnet_loss: 0.00419624475762248  (0.005765354938127778)
     | > loss: 0.19046026468276978  (0.1979193723562992)
     | > align_error: 0.546053409576416  (0.5882671195449252)

   --> STEP: 34
     | > decoder_loss: 0.451364666223526  (0.4577022019554587)
     | > postnet_loss: 0.30196747183799744  (0.3104643497396918)
     | > stopnet_loss: 0.0034673369955271482  (0.005697766175110112)
     | > loss: 0.19180037081241608  (0.19773940172265558)
     | > align_error: 0.5634492933750153  (0.5875371834811043)

   --> STEP: 35
     | > decoder_loss: 0.4490409195423126  (0.4574547367436545)
     | > postnet_loss: 0.30073311924934387  (0.3101863145828247)
     | > stopnet_loss: 0.0036654856521636248  (0.005639701017311641)
     | > loss: 0.19110900163650513  (0.19754996172019412)
     | > align_error: 0.5342298150062561  (0.5860141158103943)

   --> STEP: 36
     | > decoder_loss: 0.4553370773792267  (0.45739591287242043)
     | > postnet_loss: 0.30493274331092834  (0.31004038204749423)
     | > stopnet_loss: 0.003841795027256012  (0.00558975918425454)
     | > loss: 0.19390925765037537  (0.19744883105158806)
     | > align_error: 0.6340897083282471  (0.5873495489358902)

   --> STEP: 37
     | > decoder_loss: 0.4467887282371521  (0.4571092322066024)
     | > postnet_loss: 0.30136463046073914  (0.30980590227487925)
     | > stopnet_loss: 0.003711290191859007  (0.005538989752027634)
     | > loss: 0.1907496154308319  (0.197267771169946)
     | > align_error: 0.5194043517112732  (0.5855131922541438)

   --> STEP: 38
     | > decoder_loss: 0.4361523687839508  (0.4565577358007431)
     | > postnet_loss: 0.2950253188610077  (0.30941693955346156)
     | > stopnet_loss: 0.003258616430684924  (0.005478979927781773)
     | > loss: 0.18605303764343262  (0.1969726466034588)
     | > align_error: 0.551304280757904  (0.5846129577410849)

   --> STEP: 39
     | > decoder_loss: 0.44903290271759033  (0.4563647913627135)
     | > postnet_loss: 0.3034132719039917  (0.3092629993573213)
     | > stopnet_loss: 0.003604358062148094  (0.005430912700457833)
     | > loss: 0.19171589612960815  (0.19683785812977034)
     | > align_error: 0.5465049743652344  (0.583635829962217)

   --> STEP: 40
     | > decoder_loss: 0.4467657208442688  (0.4561248145997524)
     | > postnet_loss: 0.3023611903190613  (0.3090904541313648)
     | > stopnet_loss: 0.003155151614919305  (0.005374018673319369)
     | > loss: 0.19043688476085663  (0.19667783379554749)
     | > align_error: 0.5844252109527588  (0.5836555644869805)

   --> STEP: 41
     | > decoder_loss: 0.436919629573822  (0.45565639545277853)
     | > postnet_loss: 0.2944818437099457  (0.3087341465601107)
     | > stopnet_loss: 0.00382953230291605  (0.00533634827404124)
     | > loss: 0.1866798996925354  (0.1964339817442545)
     | > align_error: 0.5040538907051086  (0.5817140602483983)

   --> STEP: 42
     | > decoder_loss: 0.44129934906959534  (0.45531456101508366)
     | > postnet_loss: 0.2970265746116638  (0.3084553948470525)
     | > stopnet_loss: 0.003390768775716424  (0.005290024952652554)
     | > loss: 0.1879722625017166  (0.1962325122384798)
     | > align_error: 0.5797513127326965  (0.5816673281646911)

   --> STEP: 43
     | > decoder_loss: 0.440681129693985  (0.45497424865877906)
     | > postnet_loss: 0.29658493399620056  (0.3081793376179629)
     | > stopnet_loss: 0.003047542879357934  (0.005237874206761981)
     | > loss: 0.18736405670642853  (0.19602626908657161)
     | > align_error: 0.5519035756587982  (0.5809751478738564)

   --> STEP: 44
     | > decoder_loss: 0.4586513638496399  (0.4550578194585713)
     | > postnet_loss: 0.30574527382850647  (0.30812401798638434)
     | > stopnet_loss: 0.0028031275141984224  (0.005182539054658263)
     | > loss: 0.19390229880809784  (0.19597799703478813)
     | > align_error: 0.5513132512569427  (0.5803010138598356)

   --> STEP: 45
     | > decoder_loss: 0.451180636882782  (0.45497165984577603)
     | > postnet_loss: 0.30482345819473267  (0.3080506722132365)
     | > stopnet_loss: 0.0034627150744199753  (0.005144320743986301)
     | > loss: 0.1924637407064438  (0.1958999024497138)
     | > align_error: 0.5529792308807373  (0.5796938631269667)

   --> STEP: 46
     | > decoder_loss: 0.44249486923217773  (0.45470042526721954)
     | > postnet_loss: 0.29641661047935486  (0.30779775782771734)
     | > stopnet_loss: 0.0033202425111085176  (0.005104666869358523)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34567103241429187 (-0.015443429802403263)
     | > avg_decoder_loss: 0.45039122890342365 (+0.0005860197724718019)
     | > avg_postnet_loss: 0.3041797524148767 (-0.0006668481862905917)
     | > avg_stopnet_loss: 0.004521955725398253 (+6.869491754159587e-07)
     | > avg_loss: 0.19316470058578433 (-1.952187581497067e-05)
     | > avg_align_error: 0.5723821078286027 (-0.0003685567415120383)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_4228.pth

 > EPOCH: 28/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 00:43:11)

   --> TIME: 2025-12-28 00:43:45 -- STEP: 22/150 -- GLOBAL_STEP: 4250
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.49518609046936035  (0.4853267547759143)
     | > postnet_loss: 0.41743358969688416  (0.41663061624223535)
     | > stopnet_loss: 0.006865339819341898  (0.010294745210558176)
     | > loss: 0.23502026498317719  (0.23578408699144016)
     | > align_error: 0.6329838931560516  (0.6742495217106561)
     | > grad_norm: tensor(0.2034, device='cuda:0')  (tensor(0.2807, device='cuda:0'))
     | > step_time: 0.8255  (0.6403435685417869)
     | > loader_time: 1.0094  (0.8645488673990424)


   --> TIME: 2025-12-28 00:44:38 -- STEP: 47/150 -- GLOBAL_STEP: 4275
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4978266656398773  (0.49256420769590015)
     | > postnet_loss: 0.4145752787590027  (0.4173793171314483)
     | > stopnet_loss: 0.00446939654648304  (0.007904546622662469)
     | > loss: 0.2325698733329773  (0.23539042631362347)
     | > align_error: 0.658003568649292  (0.6507772701851864)
     | > grad_norm: tensor(0.1546, device='cuda:0')  (tensor(0.2432, device='cuda:0'))
     | > step_time: 1.2161  (0.8758908941390666)
     | > loader_time: 1.051  (0.9423815037341828)


   --> TIME: 2025-12-28 00:45:43 -- STEP: 72/150 -- GLOBAL_STEP: 4300
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4944613575935364  (0.49559038546350265)
     | > postnet_loss: 0.40789079666137695  (0.4166175578203466)
     | > stopnet_loss: 0.00393686443567276  (0.006679611975818666)
     | > loss: 0.2295249104499817  (0.23473159699804252)
     | > align_error: 0.6010257601737976  (0.6382360131376318)
     | > grad_norm: tensor(0.1417, device='cuda:0')  (tensor(0.2139, device='cuda:0'))
     | > step_time: 1.459  (1.0391948819160461)
     | > loader_time: 1.2791  (1.0504817598395877)


   --> TIME: 2025-12-28 00:46:55 -- STEP: 97/150 -- GLOBAL_STEP: 4325
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4950472116470337  (0.4966057262469813)
     | > postnet_loss: 0.4077341854572296  (0.41581776062237846)
     | > stopnet_loss: 0.003497486701235175  (0.005950912991634656)
     | > loss: 0.2291928231716156  (0.23405678385926276)
     | > align_error: 0.5772592127323151  (0.6336694470385914)
     | > grad_norm: tensor(0.1604, device='cuda:0')  (tensor(0.2001, device='cuda:0'))
     | > step_time: 1.7841  (1.1554725637140963)
     | > loader_time: 2.2033  (1.1427177670075723)


   --> TIME: 2025-12-28 00:48:23 -- STEP: 122/150 -- GLOBAL_STEP: 4350
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49638357758522034  (0.4976081115300538)
     | > postnet_loss: 0.4121614694595337  (0.41542090890837496)
     | > stopnet_loss: 0.003223559819161892  (0.0054520782709243844)
     | > loss: 0.23035980761051178  (0.23370933312861647)
     | > align_error: 0.597335159778595  (0.6294121747134162)
     | > grad_norm: tensor(0.1468, device='cuda:0')  (tensor(0.1878, device='cuda:0'))
     | > step_time: 2.0301  (1.2906988995974182)
     | > loader_time: 1.6887  (1.255429140857009)


   --> TIME: 2025-12-28 00:50:04 -- STEP: 147/150 -- GLOBAL_STEP: 4375
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5081645846366882  (0.4986594783611038)
     | > postnet_loss: 0.41403234004974365  (0.4148266102586474)
     | > stopnet_loss: 0.002771604573354125  (0.005067491466749688)
     | > loss: 0.23332083225250244  (0.2334390132605624)
     | > align_error: 0.6303895115852356  (0.6258459462195026)
     | > grad_norm: tensor(0.1456, device='cuda:0')  (tensor(0.1825, device='cuda:0'))
     | > step_time: 2.3287  (1.4262977960158367)
     | > loader_time: 2.0222  (1.3701435303201486)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4732917249202728  (0.4732917249202728)
     | > postnet_loss: 0.33338385820388794  (0.33338385820388794)
     | > stopnet_loss: 0.012529248371720314  (0.012529248371720314)
     | > loss: 0.21419814229011536  (0.21419814229011536)
     | > align_error: 0.7193805873394012  (0.7193805873394012)

   --> STEP: 1
     | > decoder_loss: 0.4529849886894226  (0.4529849886894226)
     | > postnet_loss: 0.31777510046958923  (0.31777510046958923)
     | > stopnet_loss: 0.009921247139573097  (0.009921247139573097)
     | > loss: 0.2026112675666809  (0.2026112675666809)
     | > align_error: 0.6603721380233765  (0.6603721380233765)

   --> STEP: 2
     | > decoder_loss: 0.44893234968185425  (0.4509586691856384)
     | > postnet_loss: 0.31497928500175476  (0.316377192735672)
     | > stopnet_loss: 0.011155989952385426  (0.010538618545979261)
     | > loss: 0.2021338939666748  (0.20237258076667786)
     | > align_error: 0.6574922800064087  (0.6589322090148926)

   --> STEP: 3
     | > decoder_loss: 0.45163193345069885  (0.45118309060732525)
     | > postnet_loss: 0.3111898899078369  (0.3146480917930603)
     | > stopnet_loss: 0.00863736029714346  (0.009904865796367327)
     | > loss: 0.19934280216693878  (0.20136265456676483)
     | > align_error: 0.7353078722953796  (0.6843907634417216)

   --> STEP: 4
     | > decoder_loss: 0.46078819036483765  (0.45358436554670334)
     | > postnet_loss: 0.32095783948898315  (0.316225528717041)
     | > stopnet_loss: 0.008478231728076935  (0.00954820727929473)
     | > loss: 0.20391473174095154  (0.2020006738603115)
     | > align_error: 0.6048910915851593  (0.664515845477581)

   --> STEP: 5
     | > decoder_loss: 0.441632479429245  (0.45119398832321167)
     | > postnet_loss: 0.3050392270088196  (0.31398826837539673)
     | > stopnet_loss: 0.008396748453378677  (0.009317915514111519)
     | > loss: 0.19506466388702393  (0.20061347186565398)
     | > align_error: 0.643261194229126  (0.66026491522789)

   --> STEP: 6
     | > decoder_loss: 0.4562799334526062  (0.4520416458447774)
     | > postnet_loss: 0.31397876143455505  (0.31398668388525647)
     | > stopnet_loss: 0.007449236698448658  (0.009006469044834375)
     | > loss: 0.2000139057636261  (0.20051354418198267)
     | > align_error: 0.5948817729949951  (0.6493677248557409)

   --> STEP: 7
     | > decoder_loss: 0.4632166028022766  (0.4536380682672773)
     | > postnet_loss: 0.31367027759552  (0.3139414829867227)
     | > stopnet_loss: 0.00652519753202796  (0.00865200168586203)
     | > loss: 0.20074692368507385  (0.2005468841109957)
     | > align_error: 0.5807352662086487  (0.6395630879061562)

   --> STEP: 8
     | > decoder_loss: 0.4595392644405365  (0.4543757177889347)
     | > postnet_loss: 0.313431054353714  (0.3138776794075966)
     | > stopnet_loss: 0.007618814706802368  (0.008522853313479573)
     | > loss: 0.200861394405365  (0.20058619789779186)
     | > align_error: 0.5766922831535339  (0.6317042373120785)

   --> STEP: 9
     | > decoder_loss: 0.45718368887901306  (0.4546877145767212)
     | > postnet_loss: 0.3148655593395233  (0.31398744384447735)
     | > stopnet_loss: 0.006867887917906046  (0.008338968269526958)
     | > loss: 0.1998801976442337  (0.2005077534251743)
     | > align_error: 0.5933904647827148  (0.6274471514754825)

   --> STEP: 10
     | > decoder_loss: 0.4885213077068329  (0.45807107388973234)
     | > postnet_loss: 0.3296467363834381  (0.3155533730983734)
     | > stopnet_loss: 0.0058905091136693954  (0.008094122353941201)
     | > loss: 0.2104325145483017  (0.20150022953748703)
     | > align_error: 0.5879692137241364  (0.6234993577003479)

   --> STEP: 11
     | > decoder_loss: 0.47249385714530945  (0.45938223600387573)
     | > postnet_loss: 0.3228277862071991  (0.31621468338099396)
     | > stopnet_loss: 0.006004790775477886  (0.007904183119535446)
     | > loss: 0.2048352062702179  (0.20180340924046256)
     | > align_error: 0.5956302285194397  (0.6209658005020835)

   --> STEP: 12
     | > decoder_loss: 0.46522241830825806  (0.4598689178625743)
     | > postnet_loss: 0.31341007351875305  (0.3159809658924739)
     | > stopnet_loss: 0.008027124218642712  (0.007914428211127719)
     | > loss: 0.20268525183200836  (0.20187689612309137)
     | > align_error: 0.5890594720840454  (0.6183069398005804)

   --> STEP: 13
     | > decoder_loss: 0.45753154158592224  (0.4596891196874472)
     | > postnet_loss: 0.3147105276584625  (0.315883239874473)
     | > stopnet_loss: 0.005718879401683807  (0.0077455398411704944)
     | > loss: 0.1987794041633606  (0.20163862751080439)
     | > align_error: 0.5876466631889343  (0.6159484569842999)

   --> STEP: 14
     | > decoder_loss: 0.46224090456962585  (0.4598713900361742)
     | > postnet_loss: 0.3139214813709259  (0.31574311426707674)
     | > stopnet_loss: 0.005133884493261576  (0.007558993030605572)
     | > loss: 0.19917447865009308  (0.20146261687789643)
     | > align_error: 0.5553404688835144  (0.6116193149771009)

   --> STEP: 15
     | > decoder_loss: 0.46609336137771606  (0.46028618812561034)
     | > postnet_loss: 0.3213024139404297  (0.3161137342453003)
     | > stopnet_loss: 0.005088818725198507  (0.007394314743578434)
     | > loss: 0.20193776488304138  (0.20149429341157277)
     | > align_error: 0.5892819762229919  (0.6101301590601603)

   --> STEP: 16
     | > decoder_loss: 0.4655663073062897  (0.4606161955744028)
     | > postnet_loss: 0.31296485662460327  (0.31591692939400673)
     | > stopnet_loss: 0.005294548813253641  (0.0072630793729331344)
     | > loss: 0.19992734491825104  (0.20139635913074017)
     | > align_error: 0.6075096428394318  (0.6099663767963648)

   --> STEP: 17
     | > decoder_loss: 0.47409090399742126  (0.4614088254816392)
     | > postnet_loss: 0.3245260417461395  (0.3164233477676616)
     | > stopnet_loss: 0.0049974857829511166  (0.007129809161757722)
     | > loss: 0.20465172827243805  (0.201587851433193)
     | > align_error: 0.5594253242015839  (0.6069933737025541)

   --> STEP: 18
     | > decoder_loss: 0.4692470133304596  (0.4618442803621292)
     | > postnet_loss: 0.31642574071884155  (0.3164234807093938)
     | > stopnet_loss: 0.005478227976709604  (0.007038054651477271)
     | > loss: 0.20189642906188965  (0.20160499463478723)
     | > align_error: 0.6050029993057251  (0.6068827973471748)

   --> STEP: 19
     | > decoder_loss: 0.4678736627101898  (0.46216161627518504)
     | > postnet_loss: 0.3154885172843933  (0.316374272108078)
     | > stopnet_loss: 0.005000322591513395  (0.006930805595689698)
     | > loss: 0.20084086060523987  (0.20156477705428474)
     | > align_error: 0.6017504334449768  (0.6066126729312696)

   --> STEP: 20
     | > decoder_loss: 0.4629262089729309  (0.46219984591007235)
     | > postnet_loss: 0.314110666513443  (0.3162610918283463)
     | > stopnet_loss: 0.004642236977815628  (0.006816377164795995)
     | > loss: 0.1989014595746994  (0.20143161118030548)
     | > align_error: 0.6236377060413361  (0.6074639245867729)

   --> STEP: 21
     | > decoder_loss: 0.4597308039665222  (0.462082272484189)
     | > postnet_loss: 0.3091162443161011  (0.31592086099442984)
     | > stopnet_loss: 0.004125158302485943  (0.0066882238856383735)
     | > loss: 0.19633692502975464  (0.2011890070778983)
     | > align_error: 0.5617576241493225  (0.6052874340897515)

   --> STEP: 22
     | > decoder_loss: 0.46296799182891846  (0.462122532454404)
     | > postnet_loss: 0.3143327236175537  (0.3158486729318446)
     | > stopnet_loss: 0.005033599678426981  (0.006613013694401492)
     | > loss: 0.1993587762117386  (0.20110581476580014)
     | > align_error: 0.6263973712921143  (0.6062469766898588)

   --> STEP: 23
     | > decoder_loss: 0.43395334482192993  (0.4608977851660355)
     | > postnet_loss: 0.30214133858680725  (0.31525270187336474)
     | > stopnet_loss: 0.0047067916020751  (0.0065301344729959965)
     | > loss: 0.18873046338558197  (0.20056775601013846)
     | > align_error: 0.5676926970481873  (0.6045707036619601)

   --> STEP: 24
     | > decoder_loss: 0.4686791002750397  (0.4612220066289107)
     | > postnet_loss: 0.31844016909599304  (0.3153855130076409)
     | > stopnet_loss: 0.004491861909627914  (0.006445206449522327)
     | > loss: 0.2012716829776764  (0.20059708630045256)
     | > align_error: 0.5803695917129517  (0.603562323997418)

   --> STEP: 25
     | > decoder_loss: 0.4685395061969757  (0.4615147066116333)
     | > postnet_loss: 0.3145081102848053  (0.3153504168987275)
     | > stopnet_loss: 0.0038025418762117624  (0.006339499866589904)
     | > loss: 0.19956444203853607  (0.20055578052997589)
     | > align_error: 0.5589864552021027  (0.6017792892456054)

   --> STEP: 26
     | > decoder_loss: 0.4432442784309387  (0.46081199783545274)
     | > postnet_loss: 0.30225005745887756  (0.31484655692027175)
     | > stopnet_loss: 0.004599747713655233  (0.006272586322246263)
     | > loss: 0.19097334146499634  (0.20018722518132284)
     | > align_error: 0.5480840802192688  (0.5997140888984386)

   --> STEP: 27
     | > decoder_loss: 0.4401130676269531  (0.4600453707906935)
     | > postnet_loss: 0.3000989258289337  (0.3143003483613333)
     | > stopnet_loss: 0.004023807588964701  (0.006189298221013612)
     | > loss: 0.18907679617404938  (0.19977572781068306)
     | > align_error: 0.5426989495754242  (0.5976024170716604)

   --> STEP: 28
     | > decoder_loss: 0.44532501697540283  (0.45951964386871885)
     | > postnet_loss: 0.3027995526790619  (0.313889605658395)
     | > stopnet_loss: 0.004022208973765373  (0.006111902176469032)
     | > loss: 0.1910533607006073  (0.19946421469960893)
     | > align_error: 0.5667964816093445  (0.5965022050908634)

   --> STEP: 29
     | > decoder_loss: 0.44139063358306885  (0.45889450558300676)
     | > postnet_loss: 0.29887792468070984  (0.31337196148675067)
     | > stopnet_loss: 0.003714015008881688  (0.006029216412069468)
     | > loss: 0.18878115713596344  (0.1990958334043108)
     | > align_error: 0.5413759648799896  (0.5946013002560057)

   --> STEP: 30
     | > decoder_loss: 0.4411240220069885  (0.4583021561304728)
     | > postnet_loss: 0.2996710240840912  (0.3129152635733287)
     | > stopnet_loss: 0.0030246416572481394  (0.005929063920242091)
     | > loss: 0.18822339177131653  (0.198733418683211)
     | > align_error: 0.5347654819488525  (0.5926067729791006)

   --> STEP: 31
     | > decoder_loss: 0.43970009684562683  (0.4577020897019294)
     | > postnet_loss: 0.3019665479660034  (0.3125620791988989)
     | > stopnet_loss: 0.004013197496533394  (0.005867261777541811)
     | > loss: 0.1894298642873764  (0.19843330402528087)
     | > align_error: 0.5610553920269012  (0.5915889864967715)

   --> STEP: 32
     | > decoder_loss: 0.4472278654575348  (0.45737477019429207)
     | > postnet_loss: 0.30452996492385864  (0.31231107562780386)
     | > stopnet_loss: 0.004002558067440987  (0.00580898978660116)
     | > loss: 0.1919420212507248  (0.19823045143857598)
     | > align_error: 0.5323002934455872  (0.589736214838922)

   --> STEP: 33
     | > decoder_loss: 0.4459986090660095  (0.4570300380388896)
     | > postnet_loss: 0.30436915159225464  (0.31207041126309026)
     | > stopnet_loss: 0.0041199601255357265  (0.005757807069599177)
     | > loss: 0.1917119026184082  (0.19803291965614667)
     | > align_error: 0.5468716621398926  (0.5884372889995575)

   --> STEP: 34
     | > decoder_loss: 0.45146459341049194  (0.4568663484909955)
     | > postnet_loss: 0.30626699328422546  (0.311899722499006)
     | > stopnet_loss: 0.003462351392954588  (0.005690293667344924)
     | > loss: 0.19289523363113403  (0.1978818112436463)
     | > align_error: 0.5644101202487946  (0.5877306075657115)

   --> STEP: 35
     | > decoder_loss: 0.44933968782424927  (0.4566513010433742)
     | > postnet_loss: 0.3041992485523224  (0.31167970895767216)
     | > stopnet_loss: 0.0036605149507522583  (0.005632299989727991)
     | > loss: 0.19204525649547577  (0.1977150525365557)
     | > align_error: 0.534777969121933  (0.5862176750387464)

   --> STEP: 36
     | > decoder_loss: 0.4554375410079956  (0.4566175854868359)
     | > postnet_loss: 0.3090435266494751  (0.31160648167133337)
     | > stopnet_loss: 0.0038250170182436705  (0.005582097684964538)
     | > loss: 0.1949452906847  (0.1976381147073375)
     | > align_error: 0.6346544623374939  (0.5875631413526006)

   --> STEP: 37
     | > decoder_loss: 0.4471723437309265  (0.4563623086826221)
     | > postnet_loss: 0.3047952950000763  (0.31142239554508316)
     | > stopnet_loss: 0.003707350930199027  (0.005531428853754659)
     | > loss: 0.19169926643371582  (0.1974776052945369)
     | > align_error: 0.5199282467365265  (0.5857351712278418)

   --> STEP: 38
     | > decoder_loss: 0.43627554178237915  (0.45583370955366836)
     | > postnet_loss: 0.2988772988319397  (0.31109226142105306)
     | > stopnet_loss: 0.0032484298571944237  (0.0054713499327925475)
     | > loss: 0.1870366334915161  (0.19720284287866793)
     | > align_error: 0.551885724067688  (0.5848443963025746)

   --> STEP: 39
     | > decoder_loss: 0.44980090856552124  (0.4556790223488441)
     | > postnet_loss: 0.3071112632751465  (0.310990184545517)
     | > stopnet_loss: 0.0035790479741990566  (0.005422829369751689)
     | > loss: 0.19280709326267242  (0.19709013135005266)
     | > align_error: 0.5470978915691376  (0.5838765372068454)

   --> STEP: 40
     | > decoder_loss: 0.44699710607528687  (0.45546197444200515)
     | > postnet_loss: 0.3061492443084717  (0.3108691610395909)
     | > stopnet_loss: 0.003142349421977997  (0.0053658173710573465)
     | > loss: 0.19142892956733704  (0.19694860130548478)
     | > align_error: 0.5848926901817322  (0.5839019410312176)

   --> STEP: 41
     | > decoder_loss: 0.43719977140426636  (0.45501655485571885)
     | > postnet_loss: 0.29810062050819397  (0.31055773322175195)
     | > stopnet_loss: 0.003808912355452776  (0.005327844077993821)
     | > loss: 0.18763402104377747  (0.1967214164210529)
     | > align_error: 0.5048537850379944  (0.5819739372265048)

   --> STEP: 42
     | > decoder_loss: 0.4425717890262604  (0.4547202509073984)
     | > postnet_loss: 0.3018617033958435  (0.3103506848925637)
     | > stopnet_loss: 0.0033770466689020395  (0.005281396520634492)
     | > loss: 0.18948543071746826  (0.19654913104715802)
     | > align_error: 0.5802741646766663  (0.5819334664515087)

   --> STEP: 43
     | > decoder_loss: 0.4408115744590759  (0.454396793315577)
     | > postnet_loss: 0.3010551631450653  (0.31013450996820324)
     | > stopnet_loss: 0.003047187812626362  (0.005229438178587792)
     | > loss: 0.1885138601064682  (0.19636226428109546)
     | > align_error: 0.552314817905426  (0.5812446606713672)

   --> STEP: 44
     | > decoder_loss: 0.45885270833969116  (0.45449806411157956)
     | > postnet_loss: 0.3095671832561493  (0.31012161617929296)
     | > stopnet_loss: 0.0027984464541077614  (0.0051741883666677905)
     | > loss: 0.1949034184217453  (0.19632910869338296)
     | > align_error: 0.5520097315311432  (0.5805802304636347)

   --> STEP: 45
     | > decoder_loss: 0.45170965790748596  (0.45443609952926634)
     | > postnet_loss: 0.308902770280838  (0.31009453071488285)
     | > stopnet_loss: 0.003454560413956642  (0.005135974412163098)
     | > loss: 0.19360767304897308  (0.19626863234572942)
     | > align_error: 0.5535398125648499  (0.5799793322881062)

   --> STEP: 46
     | > decoder_loss: 0.44305500388145447  (0.45418868440648785)
     | > postnet_loss: 0.3006349802017212  (0.30988888831242284)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3599412152261445 (+0.014270182811852605)
     | > avg_decoder_loss: 0.4500696261723836 (-0.0003216027310400382)
     | > avg_postnet_loss: 0.3066247602303824 (+0.002445007815505662)
     | > avg_stopnet_loss: 0.004513663599606264 (-8.292125791988826e-06)
     | > avg_loss: 0.19368726015090942 (+0.0005225595651250914)
     | > avg_align_error: 0.5727784498171372 (+0.00039634198853455427)


 > EPOCH: 29/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 00:52:15)

   --> TIME: 2025-12-28 00:52:45 -- STEP: 21/150 -- GLOBAL_STEP: 4400
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4887394607067108  (0.4850996463071732)
     | > postnet_loss: 0.41382119059562683  (0.4167006796314603)
     | > stopnet_loss: 0.007034490816295147  (0.010441366183970655)
     | > loss: 0.23267465829849243  (0.2358914464712143)
     | > align_error: 0.6275296211242676  (0.676063441094898)
     | > grad_norm: tensor(0.1530, device='cuda:0')  (tensor(0.2634, device='cuda:0'))
     | > step_time: 0.7802  (0.6262907527741932)
     | > loader_time: 0.8328  (0.7667035829453241)


   --> TIME: 2025-12-28 00:53:34 -- STEP: 46/150 -- GLOBAL_STEP: 4425
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.509016752243042  (0.49241437212280603)
     | > postnet_loss: 0.421348512172699  (0.41731581351031427)
     | > stopnet_loss: 0.0051894462667405605  (0.008004179143387339)
     | > loss: 0.23778076469898224  (0.23543672522772913)
     | > align_error: 0.661608099937439  (0.6504032508186671)
     | > grad_norm: tensor(0.1780, device='cuda:0')  (tensor(0.2292, device='cuda:0'))
     | > step_time: 1.1888  (0.839907345564469)
     | > loader_time: 1.0495  (0.8768882284993711)


   --> TIME: 2025-12-28 00:54:38 -- STEP: 71/150 -- GLOBAL_STEP: 4450
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49958866834640503  (0.4953859876578962)
     | > postnet_loss: 0.41173967719078064  (0.41649313250058134)
     | > stopnet_loss: 0.004137001000344753  (0.006738660529150929)
     | > loss: 0.23196907341480255  (0.23470844013590209)
     | > align_error: 0.6067988872528076  (0.6383366018113955)
     | > grad_norm: tensor(0.1856, device='cuda:0')  (tensor(0.2127, device='cuda:0'))
     | > step_time: 1.511  (1.0183134381200227)
     | > loader_time: 1.2252  (0.9923000940134827)


   --> TIME: 2025-12-28 00:55:55 -- STEP: 96/150 -- GLOBAL_STEP: 4475
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5029536485671997  (0.49633135584493476)
     | > postnet_loss: 0.4135790765285492  (0.415614765137434)
     | > stopnet_loss: 0.0037142648361623287  (0.005997801631262216)
     | > loss: 0.2328474521636963  (0.23398433128992716)
     | > align_error: 0.606626033782959  (0.6338134383161862)
     | > grad_norm: tensor(0.1523, device='cuda:0')  (tensor(0.2019, device='cuda:0'))
     | > step_time: 1.7847  (1.163642011582851)
     | > loader_time: 1.6073  (1.1213877250750859)


   --> TIME: 2025-12-28 00:57:27 -- STEP: 121/150 -- GLOBAL_STEP: 4500
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5027688145637512  (0.4973416212669089)
     | > postnet_loss: 0.41406869888305664  (0.4151792435114049)
     | > stopnet_loss: 0.003107968717813492  (0.00548055556926045)
     | > loss: 0.23231734335422516  (0.2336107712885565)
     | > align_error: 0.650978147983551  (0.629305809982552)
     | > grad_norm: tensor(0.1086, device='cuda:0')  (tensor(0.1884, device='cuda:0'))
     | > step_time: 1.8819  (1.2892700384471036)
     | > loader_time: 2.2632  (1.2829752244239996)


   --> TIME: 2025-12-28 00:59:07 -- STEP: 146/150 -- GLOBAL_STEP: 4525
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5095362663269043  (0.4983670039944453)
     | > postnet_loss: 0.4143788814544678  (0.4146067843045274)
     | > stopnet_loss: 0.003073460189625621  (0.005097827792792798)
     | > loss: 0.23405224084854126  (0.2333412742982172)
     | > align_error: 0.6269987225532532  (0.6255094039521807)
     | > grad_norm: tensor(0.1165, device='cuda:0')  (tensor(0.1852, device='cuda:0'))
     | > step_time: 2.3876  (1.4218235522100362)
     | > loader_time: 1.9078  (1.391694377546441)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4753449261188507  (0.4753449261188507)
     | > postnet_loss: 0.33489271998405457  (0.33489271998405457)
     | > stopnet_loss: 0.012471665628254414  (0.012471665628254414)
     | > loss: 0.21503107249736786  (0.21503107249736786)
     | > align_error: 0.7194478213787079  (0.7194478213787079)

   --> STEP: 1
     | > decoder_loss: 0.4555363953113556  (0.4555363953113556)
     | > postnet_loss: 0.32057031989097595  (0.32057031989097595)
     | > stopnet_loss: 0.009885100647807121  (0.009885100647807121)
     | > loss: 0.20391178131103516  (0.20391178131103516)
     | > align_error: 0.6606855392456055  (0.6606855392456055)

   --> STEP: 2
     | > decoder_loss: 0.4492500126361847  (0.45239320397377014)
     | > postnet_loss: 0.31479963660240173  (0.31768497824668884)
     | > stopnet_loss: 0.011165685020387173  (0.010525392834097147)
     | > loss: 0.20217809081077576  (0.20304493606090546)
     | > align_error: 0.6579271554946899  (0.6593063473701477)

   --> STEP: 3
     | > decoder_loss: 0.4531170725822449  (0.4526344935099284)
     | > postnet_loss: 0.3118920624256134  (0.3157540063063304)
     | > stopnet_loss: 0.00863625667989254  (0.009895680782695612)
     | > loss: 0.19988854229450226  (0.20199280480543771)
     | > align_error: 0.7361743152141571  (0.6849290033181509)

   --> STEP: 4
     | > decoder_loss: 0.46264585852622986  (0.45513733476400375)
     | > postnet_loss: 0.32233190536499023  (0.31739848107099533)
     | > stopnet_loss: 0.008441922254860401  (0.009532241150736809)
     | > loss: 0.20468637347221375  (0.20266619697213173)
     | > align_error: 0.6055197715759277  (0.6650766953825951)

   --> STEP: 5
     | > decoder_loss: 0.4427899122238159  (0.4526678502559662)
     | > postnet_loss: 0.30543434619903564  (0.3150056540966034)
     | > stopnet_loss: 0.008384967222809792  (0.009302786365151406)
     | > loss: 0.19544103741645813  (0.20122116506099702)
     | > align_error: 0.6439111828804016  (0.6608435928821563)

   --> STEP: 6
     | > decoder_loss: 0.4582616090774536  (0.45360014339288074)
     | > postnet_loss: 0.31494614481925964  (0.31499573588371277)
     | > stopnet_loss: 0.007454989943653345  (0.008994820294901729)
     | > loss: 0.20075693726539612  (0.2011437937617302)
     | > align_error: 0.5957149863243103  (0.6499888251225153)

   --> STEP: 7
     | > decoder_loss: 0.46431219577789307  (0.45513043659073965)
     | > postnet_loss: 0.31317925453186035  (0.31473623854773386)
     | > stopnet_loss: 0.0065194983035326  (0.008641202867563282)
     | > loss: 0.2008923590183258  (0.20110787451267242)
     | > align_error: 0.5810568034648895  (0.6401413934571403)

   --> STEP: 8
     | > decoder_loss: 0.461081862449646  (0.45587436482310295)
     | > postnet_loss: 0.31383609771728516  (0.31462372094392776)
     | > stopnet_loss: 0.007618181873112917  (0.008513325243256986)
     | > loss: 0.20134767889976501  (0.201137850061059)
     | > align_error: 0.5771118402481079  (0.6322626993060112)

   --> STEP: 9
     | > decoder_loss: 0.45820701122283936  (0.456133547756407)
     | > postnet_loss: 0.3144313395023346  (0.3146023452281952)
     | > stopnet_loss: 0.006868473254144192  (0.008330563911133342)
     | > loss: 0.20002804696559906  (0.2010145386060079)
     | > align_error: 0.5940294861793518  (0.6280145645141602)

   --> STEP: 10
     | > decoder_loss: 0.48794785141944885  (0.45931497812271116)
     | > postnet_loss: 0.3291972577571869  (0.31606183648109437)
     | > stopnet_loss: 0.005690352525562048  (0.008066542772576213)
     | > loss: 0.20997662842273712  (0.20191074758768082)
     | > align_error: 0.5871039927005768  (0.6239235073328018)

   --> STEP: 11
     | > decoder_loss: 0.472788006067276  (0.46053979884494434)
     | > postnet_loss: 0.3216838538646698  (0.3165729289705103)
     | > stopnet_loss: 0.0059932321310043335  (0.00787805998697877)
     | > loss: 0.20461119711399078  (0.20215624299916354)
     | > align_error: 0.5961708128452301  (0.6214005351066589)

   --> STEP: 12
     | > decoder_loss: 0.4665435552597046  (0.4610401118795077)
     | > postnet_loss: 0.31254905462265015  (0.31623760610818863)
     | > stopnet_loss: 0.008025254122912884  (0.00789032616497328)
     | > loss: 0.20279841125011444  (0.20220975702007613)
     | > align_error: 0.5896218717098236  (0.6187523131569227)

   --> STEP: 13
     | > decoder_loss: 0.45793044567108154  (0.46080090678655183)
     | > postnet_loss: 0.3138309717178345  (0.3160524803858537)
     | > stopnet_loss: 0.005709530785679817  (0.007722572674258397)
     | > loss: 0.19864988327026367  (0.20193592057778284)
     | > align_error: 0.5882678031921387  (0.6164073508519393)

   --> STEP: 14
     | > decoder_loss: 0.4638412296772003  (0.46101807270731243)
     | > postnet_loss: 0.31352701783180237  (0.31587209020342144)
     | > stopnet_loss: 0.005129880737513304  (0.0075373803930623194)
     | > loss: 0.19947193562984467  (0.20175992165293014)
     | > align_error: 0.5559098720550537  (0.6120861023664474)

   --> STEP: 15
     | > decoder_loss: 0.46599793434143066  (0.46135006348292035)
     | > postnet_loss: 0.31898730993270874  (0.31607977151870725)
     | > stopnet_loss: 0.005084247328341007  (0.007373838188747565)
     | > loss: 0.20133055746555328  (0.20173129737377166)
     | > align_error: 0.5897139608860016  (0.6105946262677511)

   --> STEP: 16
     | > decoder_loss: 0.46593177318573  (0.46163642033934593)
     | > postnet_loss: 0.3110048770904541  (0.31576259061694145)
     | > stopnet_loss: 0.0052697425708174706  (0.007242332212626934)
     | > loss: 0.19950389862060547  (0.20159208495169878)
     | > align_error: 0.6081032454967499  (0.6104389149695635)

   --> STEP: 17
     | > decoder_loss: 0.47368454933166504  (0.46234513380948233)
     | > postnet_loss: 0.32173457741737366  (0.3161138839581433)
     | > stopnet_loss: 0.004989620763808489  (0.0071098197744611435)
     | > loss: 0.20384439826011658  (0.201724573969841)
     | > align_error: 0.5598307847976685  (0.6074619661359226)

   --> STEP: 18
     | > decoder_loss: 0.4689565896987915  (0.46271243691444397)
     | > postnet_loss: 0.3139549493789673  (0.3159939431481891)
     | > stopnet_loss: 0.005490998737514019  (0.0070198852724085254)
     | > loss: 0.2012188881635666  (0.20169648031393686)
     | > align_error: 0.6053463518619537  (0.607344432009591)

   --> STEP: 19
     | > decoder_loss: 0.4681786298751831  (0.46300013128079864)
     | > postnet_loss: 0.3135426640510559  (0.3158649284588663)
     | > stopnet_loss: 0.005032462067902088  (0.006915284051118712)
     | > loss: 0.20046278834342957  (0.20163154915759438)
     | > align_error: 0.6021194458007812  (0.6070694327354431)

   --> STEP: 20
     | > decoder_loss: 0.46225303411483765  (0.4629627764225006)
     | > postnet_loss: 0.3108353912830353  (0.31561345160007476)
     | > stopnet_loss: 0.004636510740965605  (0.006801345385611057)
     | > loss: 0.19790862500667572  (0.20144540295004845)
     | > align_error: 0.6237887442111969  (0.6079053983092308)

   --> STEP: 21
     | > decoder_loss: 0.4601192772388458  (0.4628273716994694)
     | > postnet_loss: 0.30726078152656555  (0.3152157054060981)
     | > stopnet_loss: 0.0041218968108296394  (0.006673752596335751)
     | > loss: 0.1959669142961502  (0.20118452253795804)
     | > align_error: 0.5620594918727875  (0.6057222599074954)

   --> STEP: 22
     | > decoder_loss: 0.4623107314109802  (0.4628038880499927)
     | > postnet_loss: 0.3113064467906952  (0.3150380118326707)
     | > stopnet_loss: 0.005021052900701761  (0.006598629882897843)
     | > loss: 0.19842533767223358  (0.2010591050440615)
     | > align_error: 0.6268109083175659  (0.6066808348352258)

   --> STEP: 23
     | > decoder_loss: 0.4340514540672302  (0.46155378222465515)
     | > postnet_loss: 0.29993873834609985  (0.3143815216810807)
     | > stopnet_loss: 0.004708784632384777  (0.006516462698092927)
     | > loss: 0.18820632994174957  (0.20050028873526532)
     | > align_error: 0.5678187608718872  (0.6049911794455154)

   --> STEP: 24
     | > decoder_loss: 0.4680798053741455  (0.4618256998558839)
     | > postnet_loss: 0.31511133909225464  (0.3144119307398796)
     | > stopnet_loss: 0.004496314562857151  (0.0064322898591247695)
     | > loss: 0.2002941071987152  (0.20049169783790907)
     | > align_error: 0.5808106064796448  (0.6039836555719375)

   --> STEP: 25
     | > decoder_loss: 0.4685913920402527  (0.4620963275432587)
     | > postnet_loss: 0.312037855386734  (0.3143169677257538)
     | > stopnet_loss: 0.0038042105734348297  (0.006327166687697172)
     | > loss: 0.1989615261554718  (0.20043049097061158)
     | > align_error: 0.5598738193511963  (0.6022192621231077)

   --> STEP: 26
     | > decoder_loss: 0.4432106018066406  (0.46136995347646564)
     | > postnet_loss: 0.3000268042087555  (0.31376734605202306)
     | > stopnet_loss: 0.00458214757964015  (0.006260050568156517)
     | > loss: 0.19039149582386017  (0.2000443757726596)
     | > align_error: 0.5485902428627014  (0.600156607536169)

   --> STEP: 27
     | > decoder_loss: 0.4394235908985138  (0.4605571252328378)
     | > postnet_loss: 0.2968253493309021  (0.3131398646919816)
     | > stopnet_loss: 0.00402764743193984  (0.006177368970518863)
     | > loss: 0.18808989226818085  (0.19960161712434557)
     | > align_error: 0.5428343415260315  (0.5980335606469046)

   --> STEP: 28
     | > decoder_loss: 0.44502511620521545  (0.4600024106247084)
     | > postnet_loss: 0.3001326322555542  (0.31267532067639486)
     | > stopnet_loss: 0.00404065428301692  (0.006101057731679508)
     | > loss: 0.19033008813858032  (0.19927049108913966)
     | > align_error: 0.5670361518859863  (0.5969265103340147)

   --> STEP: 29
     | > decoder_loss: 0.44096678495407104  (0.45934600973951406)
     | > postnet_loss: 0.2960205674171448  (0.312101018839869)
     | > stopnet_loss: 0.0036981708835810423  (0.006018199564503698)
     | > loss: 0.18794500827789307  (0.19887995719909668)
     | > align_error: 0.541597843170166  (0.5950186252593992)

   --> STEP: 30
     | > decoder_loss: 0.4413558840751648  (0.45874633888403576)
     | > postnet_loss: 0.2972332239151001  (0.31160542567571003)
     | > stopnet_loss: 0.0030152234248816967  (0.005918100359849632)
     | > loss: 0.1876624971628189  (0.1985060418645541)
     | > align_error: 0.535007119178772  (0.5930182417233782)

   --> STEP: 31
     | > decoder_loss: 0.4395810067653656  (0.45812810236407864)
     | > postnet_loss: 0.2988004684448242  (0.3111923625392298)
     | > stopnet_loss: 0.004086554981768131  (0.005859018250879261)
     | > loss: 0.1886819303035736  (0.19818913504000632)
     | > align_error: 0.5605114698410034  (0.5919696361787855)

   --> STEP: 32
     | > decoder_loss: 0.44709348678588867  (0.4577832706272602)
     | > postnet_loss: 0.3016684949398041  (0.3108947416767478)
     | > stopnet_loss: 0.003996587824076414  (0.005800817300041672)
     | > loss: 0.1911870837211609  (0.1979703209362924)
     | > align_error: 0.5324382185935974  (0.5901092793792484)

   --> STEP: 33
     | > decoder_loss: 0.44493937492370605  (0.45739406166654645)
     | > postnet_loss: 0.300620973110199  (0.3105834153565494)
     | > stopnet_loss: 0.004143500700592995  (0.005750595584906863)
     | > loss: 0.1905335932970047  (0.1977449655532837)
     | > align_error: 0.5470379590988159  (0.5888040878555989)

   --> STEP: 34
     | > decoder_loss: 0.450628399848938  (0.45719507161308737)
     | > postnet_loss: 0.30254676938056946  (0.3103470434160793)
     | > stopnet_loss: 0.0034694215282797813  (0.005683502230300184)
     | > loss: 0.19176320731639862  (0.19756903148749294)
     | > align_error: 0.5643555819988251  (0.5880850141539291)

   --> STEP: 35
     | > decoder_loss: 0.4489274322986603  (0.4569588533469609)
     | > postnet_loss: 0.3011516034603119  (0.3100843165602003)
     | > stopnet_loss: 0.003675582353025675  (0.005626133090949484)
     | > loss: 0.19119533896446228  (0.19738692598683494)
     | > align_error: 0.5349850952625275  (0.5865678736141747)

   --> STEP: 36
     | > decoder_loss: 0.4548184275627136  (0.45689939707517624)
     | > postnet_loss: 0.30528122186660767  (0.30995089726315606)
     | > stopnet_loss: 0.003833068534731865  (0.005576325742165661)
     | > loss: 0.19385798275470734  (0.1972888997859425)
     | > align_error: 0.6347631812095642  (0.5879066321584911)

   --> STEP: 37
     | > decoder_loss: 0.4463433623313904  (0.45661409883885773)
     | > postnet_loss: 0.3014582395553589  (0.3097213659737561)
     | > stopnet_loss: 0.00369713781401515  (0.0055255368792426745)
     | > loss: 0.19064754247665405  (0.19710940364244822)
     | > align_error: 0.5201463997364044  (0.5860752745254618)

   --> STEP: 38
     | > decoder_loss: 0.43575671315193176  (0.4560652202681491)
     | > postnet_loss: 0.2955873906612396  (0.3093494192550057)
     | > stopnet_loss: 0.0032493271864950657  (0.005465636624170369)
     | > loss: 0.18608535826206207  (0.19681929718506963)
     | > align_error: 0.5520496964454651  (0.5851798645759881)

   --> STEP: 39
     | > decoder_loss: 0.4491938650608063  (0.45588903167308903)
     | > postnet_loss: 0.3041202425956726  (0.3092153378022023)
     | > stopnet_loss: 0.003583958838135004  (0.005417388475810488)
     | > loss: 0.1919124871492386  (0.19669348154312524)
     | > align_error: 0.5471477508544922  (0.5842046821728729)

   --> STEP: 40
     | > decoder_loss: 0.44670429825782776  (0.45565941333770754)
     | > postnet_loss: 0.30283036828041077  (0.3090557135641575)
     | > stopnet_loss: 0.0031500146724283695  (0.005360704130725935)
     | > loss: 0.19053368270397186  (0.19653948657214643)
     | > align_error: 0.5851146578788757  (0.5842274315655229)

   --> STEP: 41
     | > decoder_loss: 0.43618419766426086  (0.45518440807737953)
     | > postnet_loss: 0.2946262061595917  (0.30870377435916807)
     | > stopnet_loss: 0.003817226504907012  (0.005323058334974254)
     | > loss: 0.1865198314189911  (0.19629510473914263)
     | > align_error: 0.5049181282520294  (0.5822930583139744)

   --> STEP: 42
     | > decoder_loss: 0.44206205010414124  (0.45487197098277865)
     | > postnet_loss: 0.2984175384044647  (0.3084588639792942)
     | > stopnet_loss: 0.0033777281641960144  (0.005276740949955725)
     | > loss: 0.1884976327419281  (0.19610945064397084)
     | > align_error: 0.5804141759872437  (0.5822483230204808)

   --> STEP: 43
     | > decoder_loss: 0.44032764434814453  (0.4545337308284848)
     | > postnet_loss: 0.2972082495689392  (0.3081972217837045)
     | > stopnet_loss: 0.003050260478630662  (0.0052249623343435135)
     | > loss: 0.18743424117565155  (0.1959077015865681)
     | > align_error: 0.552408367395401  (0.5815543705640835)

   --> STEP: 44
     | > decoder_loss: 0.4587463140487671  (0.4546294713562185)
     | > postnet_loss: 0.30645546317100525  (0.3081576363606886)
     | > stopnet_loss: 0.002798019675537944  (0.005169804546643387)
     | > loss: 0.19409847259521484  (0.1958665827458555)
     | > align_error: 0.5522029101848602  (0.5808872919191012)

   --> STEP: 45
     | > decoder_loss: 0.4510127305984497  (0.4545490993393792)
     | > postnet_loss: 0.3054434061050415  (0.30809732013278535)
     | > stopnet_loss: 0.003443849738687277  (0.005131449995355474)
     | > loss: 0.19255788624286652  (0.19579305615690018)
     | > align_error: 0.5535506308078766  (0.5802798105610739)

   --> STEP: 46
     | > decoder_loss: 0.44242605566978455  (0.4542855549117793)
     | > postnet_loss: 0.2970951497554779  (0.30785814251588733)
     | > stopnet_loss: 0.003315873444080353  (0.005091980939892972)
     | > loss: 0.18819618225097656  (0.19562790672416272)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.33874111825769604 (-0.021200096968448434)
     | > avg_decoder_loss: 0.45013397886897577 (+6.435269659216258e-05)
     | > avg_postnet_loss: 0.30428677436077234 (-0.0023379858696100375)
     | > avg_stopnet_loss: 0.00451049107042226 (-3.172529184003979e-06)
     | > avg_loss: 0.19311568118406064 (-0.0005715789668487847)
     | > avg_align_error: 0.5730016407641495 (+0.00022319094701228614)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_4530.pth

 > EPOCH: 30/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 01:01:39)

   --> TIME: 2025-12-28 01:02:09 -- STEP: 20/150 -- GLOBAL_STEP: 4550
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4839569628238678  (0.4840905860066414)
     | > postnet_loss: 0.4099915623664856  (0.41620157212018966)
     | > stopnet_loss: 0.007722615264356136  (0.010523708444088698)
     | > loss: 0.23120975494384766  (0.23559674993157387)
     | > align_error: 0.6307877898216248  (0.6784527987241745)
     | > grad_norm: tensor(0.1867, device='cuda:0')  (tensor(0.2719, device='cuda:0'))
     | > step_time: 0.9403  (0.6049203515052796)
     | > loader_time: 1.201  (0.8360023736953736)


   --> TIME: 2025-12-28 01:02:59 -- STEP: 45/150 -- GLOBAL_STEP: 4575
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5009027123451233  (0.4919409586323632)
     | > postnet_loss: 0.41752585768699646  (0.4172022567854987)
     | > stopnet_loss: 0.005212403368204832  (0.007937887021236949)
     | > loss: 0.23481953144073486  (0.2352236913310157)
     | > align_error: 0.6326195597648621  (0.6503498978084988)
     | > grad_norm: tensor(0.2122, device='cuda:0')  (tensor(0.2550, device='cuda:0'))
     | > step_time: 1.2539  (0.8110054863823783)
     | > loader_time: 1.0552  (0.9512956407335069)


   --> TIME: 2025-12-28 01:04:01 -- STEP: 70/150 -- GLOBAL_STEP: 4600
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.5005210638046265  (0.4952573593173708)
     | > postnet_loss: 0.4129748046398163  (0.4164679765701294)
     | > stopnet_loss: 0.004279621411114931  (0.006697314678292189)
     | > loss: 0.23265360295772552  (0.23462864990745272)
     | > align_error: 0.5970830619335175  (0.6389605777604239)
     | > grad_norm: tensor(0.2586, device='cuda:0')  (tensor(0.2395, device='cuda:0'))
     | > step_time: 1.4139  (0.9772614785603114)
     | > loader_time: 1.3042  (1.0392907006399972)


   --> TIME: 2025-12-28 01:05:16 -- STEP: 95/150 -- GLOBAL_STEP: 4625
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.500591516494751  (0.49636505308904144)
     | > postnet_loss: 0.4115356206893921  (0.4156442290858219)
     | > stopnet_loss: 0.003457067534327507  (0.005953838644353184)
     | > loss: 0.23148885369300842  (0.23395616051397825)
     | > align_error: 0.6039352715015411  (0.6342018535262656)
     | > grad_norm: tensor(0.3037, device='cuda:0')  (tensor(0.2317, device='cuda:0'))
     | > step_time: 1.6895  (1.1297173399674267)
     | > loader_time: 1.5114  (1.1423824485979581)


   --> TIME: 2025-12-28 01:06:40 -- STEP: 120/150 -- GLOBAL_STEP: 4650
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5001420974731445  (0.497333554426829)
     | > postnet_loss: 0.41024908423423767  (0.415148680160443)
     | > stopnet_loss: 0.003205637214705348  (0.005447402286032837)
     | > loss: 0.230803444981575  (0.23356796267131966)
     | > align_error: 0.6237513422966003  (0.6291263237595556)
     | > grad_norm: tensor(0.2278, device='cuda:0')  (tensor(0.2213, device='cuda:0'))
     | > step_time: 1.7863  (1.2497583587964383)
     | > loader_time: 1.7037  (1.250271666049957)


   --> TIME: 2025-12-28 01:08:18 -- STEP: 145/150 -- GLOBAL_STEP: 4675
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.506862998008728  (0.4983765842585728)
     | > postnet_loss: 0.41313424706459045  (0.41457661390304573)
     | > stopnet_loss: 0.002935625845566392  (0.005065776537782674)
     | > loss: 0.23293493688106537  (0.23330407769515596)
     | > align_error: 0.638435959815979  (0.6257217131811995)
     | > grad_norm: tensor(0.1574, device='cuda:0')  (tensor(0.2108, device='cuda:0'))
     | > step_time: 2.1461  (1.3765426027363747)
     | > loader_time: 2.0779  (1.365492189341578)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4744008183479309  (0.4744008183479309)
     | > postnet_loss: 0.3365127146244049  (0.3365127146244049)
     | > stopnet_loss: 0.012446747161448002  (0.012446747161448002)
     | > loss: 0.21517513692378998  (0.21517513692378998)
     | > align_error: 0.7190758585929871  (0.7190758585929871)

   --> STEP: 1
     | > decoder_loss: 0.4568421542644501  (0.4568421542644501)
     | > postnet_loss: 0.32444852590560913  (0.32444852590560913)
     | > stopnet_loss: 0.009873091243207455  (0.009873091243207455)
     | > loss: 0.20519575476646423  (0.20519575476646423)
     | > align_error: 0.6600155532360077  (0.6600155532360077)

   --> STEP: 2
     | > decoder_loss: 0.4492653012275696  (0.4530537277460098)
     | > postnet_loss: 0.31567224860191345  (0.3200603872537613)
     | > stopnet_loss: 0.011203426867723465  (0.01053825905546546)
     | > loss: 0.20243780314922333  (0.20381677895784378)
     | > align_error: 0.6571088433265686  (0.6585621982812881)

   --> STEP: 3
     | > decoder_loss: 0.45163917541503906  (0.4525822103023529)
     | > postnet_loss: 0.31285804510116577  (0.31765960653622943)
     | > stopnet_loss: 0.00855204276740551  (0.009876186959445477)
     | > loss: 0.19967634975910187  (0.20243663589159647)
     | > align_error: 0.7351106405258179  (0.6840783456961314)

   --> STEP: 4
     | > decoder_loss: 0.46319639682769775  (0.4552357569336891)
     | > postnet_loss: 0.32463622093200684  (0.3194037601351738)
     | > stopnet_loss: 0.008381616324186325  (0.009502544300630689)
     | > loss: 0.20533977448940277  (0.20316242054104805)
     | > align_error: 0.6051001846790314  (0.6643338054418564)

   --> STEP: 5
     | > decoder_loss: 0.44193035364151  (0.4525746762752533)
     | > postnet_loss: 0.3060760200023651  (0.3167382121086121)
     | > stopnet_loss: 0.008428857661783695  (0.00928780697286129)
     | > loss: 0.1954304426908493  (0.2016160249710083)
     | > align_error: 0.6429204344749451  (0.6600511312484741)

   --> STEP: 6
     | > decoder_loss: 0.4576945900917053  (0.453427995244662)
     | > postnet_loss: 0.3166258931159973  (0.3167194922765096)
     | > stopnet_loss: 0.0074237952940166  (0.008977138359720508)
     | > loss: 0.20100390911102295  (0.20151400566101074)
     | > align_error: 0.5950808823108673  (0.6492227564255396)

   --> STEP: 7
     | > decoder_loss: 0.46537959575653076  (0.4551353667463575)
     | > postnet_loss: 0.31466609239578247  (0.31642614943640573)
     | > stopnet_loss: 0.006517371628433466  (0.008625743112393789)
     | > loss: 0.20152878761291504  (0.20151611736842565)
     | > align_error: 0.5803170204162598  (0.6393790798527854)

   --> STEP: 8
     | > decoder_loss: 0.46210506558418274  (0.45600657910108566)
     | > postnet_loss: 0.3161228895187378  (0.31638824194669724)
     | > stopnet_loss: 0.007664015982300043  (0.00850552722113207)
     | > loss: 0.20222099125385284  (0.20160422660410404)
     | > align_error: 0.5763477087020874  (0.6315001584589481)

   --> STEP: 9
     | > decoder_loss: 0.4589536190032959  (0.45633402797910905)
     | > postnet_loss: 0.31633874773979187  (0.3163827425903744)
     | > stopnet_loss: 0.006824463605880737  (0.008318742374993034)
     | > loss: 0.20064756274223328  (0.20149793061945173)
     | > align_error: 0.5930373668670654  (0.6272265149487389)

   --> STEP: 10
     | > decoder_loss: 0.49039551615715027  (0.45974017679691315)
     | > postnet_loss: 0.33248159289360046  (0.317992627620697)
     | > stopnet_loss: 0.005867845378816128  (0.008073652675375343)
     | > loss: 0.2115871161222458  (0.20250684916973113)
     | > align_error: 0.5877112150192261  (0.6232749849557877)

   --> STEP: 11
     | > decoder_loss: 0.47312209010124207  (0.46095671437003394)
     | > postnet_loss: 0.3225020170211792  (0.31840257211164996)
     | > stopnet_loss: 0.006015490274876356  (0.007886547002602707)
     | > loss: 0.20492152869701385  (0.20272636549039322)
     | > align_error: 0.5954782962799072  (0.6207480132579803)

   --> STEP: 12
     | > decoder_loss: 0.4666193425655365  (0.4614286000529925)
     | > postnet_loss: 0.31396791338920593  (0.31803301721811295)
     | > stopnet_loss: 0.008031354285776615  (0.007898614276200533)
     | > loss: 0.20317816734313965  (0.20276401564478874)
     | > align_error: 0.5886254608631134  (0.6180711338917414)

   --> STEP: 13
     | > decoder_loss: 0.45808982849121094  (0.461171771471317)
     | > postnet_loss: 0.3152466118335724  (0.31781867834237904)
     | > stopnet_loss: 0.0057253483682870865  (0.007731439975591807)
     | > loss: 0.19905945658683777  (0.2024790495634079)
     | > align_error: 0.5871526300907135  (0.6156927874455085)

   --> STEP: 14
     | > decoder_loss: 0.4628206789493561  (0.4612895505768912)
     | > postnet_loss: 0.3138698637485504  (0.3175366201571056)
     | > stopnet_loss: 0.0051125334575772285  (0.007544375224305051)
     | > loss: 0.19928516447544098  (0.20225091491426742)
     | > align_error: 0.5550503134727478  (0.6113611821617398)

   --> STEP: 15
     | > decoder_loss: 0.4668280780315399  (0.4616587857405345)
     | > postnet_loss: 0.31923291087150574  (0.31764970620473226)
     | > stopnet_loss: 0.005088735371828079  (0.007380665900806586)
     | > loss: 0.2016039788722992  (0.20220778584480287)
     | > align_error: 0.5892695486545563  (0.6098884065945943)

   --> STEP: 16
     | > decoder_loss: 0.46525809168815613  (0.4618837423622608)
     | > postnet_loss: 0.3108733594417572  (0.3172261845320463)
     | > stopnet_loss: 0.0052851224318146706  (0.007249694433994591)
     | > loss: 0.19931799173355103  (0.20202717371284962)
     | > align_error: 0.6072797179222107  (0.6097253635525703)

   --> STEP: 17
     | > decoder_loss: 0.4740704298019409  (0.46260060632930083)
     | > postnet_loss: 0.3217896819114685  (0.31749462555436525)
     | > stopnet_loss: 0.004997457843273878  (0.007117209928658079)
     | > loss: 0.20396248996257782  (0.20214101584518657)
     | > align_error: 0.5591445863246918  (0.6067500237156364)

   --> STEP: 18
     | > decoder_loss: 0.4690583646297455  (0.4629593706793255)
     | > postnet_loss: 0.3140125572681427  (0.3173011773162418)
     | > stopnet_loss: 0.005492454394698143  (0.007026945732326971)
     | > loss: 0.20126017928123474  (0.20209208048052257)
     | > align_error: 0.6046996116638184  (0.6066361119349798)

   --> STEP: 19
     | > decoder_loss: 0.46779054403305054  (0.4632136429611005)
     | > postnet_loss: 0.3135889172554016  (0.31710579520777654)
     | > stopnet_loss: 0.0050498140044510365  (0.006922886167701922)
     | > loss: 0.2003946751356125  (0.20200274335710625)
     | > align_error: 0.6014769673347473  (0.6063645780086517)

   --> STEP: 20
     | > decoder_loss: 0.4624521732330322  (0.4631755694746971)
     | > postnet_loss: 0.3106692433357239  (0.3167839676141739)
     | > stopnet_loss: 0.004651971161365509  (0.006809340417385101)
     | > loss: 0.19793233275413513  (0.2017992228269577)
     | > align_error: 0.623292863368988  (0.6072109922766685)

   --> STEP: 21
     | > decoder_loss: 0.45927879214286804  (0.4629900086493719)
     | > postnet_loss: 0.30757108330726624  (0.31634525883765446)
     | > stopnet_loss: 0.004137646406888962  (0.006682116893075761)
     | > loss: 0.19585011899471283  (0.20151593216827937)
     | > align_error: 0.561149388551712  (0.6050175825754801)

   --> STEP: 22
     | > decoder_loss: 0.4623667597770691  (0.46296167915517633)
     | > postnet_loss: 0.311470091342926  (0.3161236603151668)
     | > stopnet_loss: 0.0050398060120642185  (0.006607466398484327)
     | > loss: 0.19849902391433716  (0.20137879997491837)
     | > align_error: 0.6263194680213928  (0.6059858500957489)

   --> STEP: 23
     | > decoder_loss: 0.43382537364959717  (0.4616948832636294)
     | > postnet_loss: 0.2999480068683624  (0.31542037103487097)
     | > stopnet_loss: 0.004693793598562479  (0.006524263233270334)
     | > loss: 0.18813712894916534  (0.2008030751477117)
     | > align_error: 0.5673741698265076  (0.6043070813883906)

   --> STEP: 24
     | > decoder_loss: 0.468788206577301  (0.46199043840169907)
     | > postnet_loss: 0.31502631306648254  (0.3154039519528548)
     | > stopnet_loss: 0.004497386049479246  (0.006439810017279039)
     | > loss: 0.20045101642608643  (0.20078840603431067)
     | > align_error: 0.5805927813053131  (0.6033189855515957)

   --> STEP: 25
     | > decoder_loss: 0.4697592258453369  (0.4623011898994446)
     | > postnet_loss: 0.3126363754272461  (0.31529324889183047)
     | > stopnet_loss: 0.003809630870819092  (0.0063346028514206405)
     | > loss: 0.19940853118896484  (0.20073321104049682)
     | > align_error: 0.5594663918018341  (0.6015648818016053)

   --> STEP: 26
     | > decoder_loss: 0.4427244961261749  (0.4615482401389342)
     | > postnet_loss: 0.30017560720443726  (0.314711801134623)
     | > stopnet_loss: 0.004585713148117065  (0.0062673378628320415)
     | > loss: 0.1903107464313507  (0.20033234701706812)
     | > align_error: 0.5478619933128357  (0.5994993860904988)

   --> STEP: 27
     | > decoder_loss: 0.4397770166397095  (0.4607418985278518)
     | > postnet_loss: 0.2966006100177765  (0.3140410162784435)
     | > stopnet_loss: 0.004028125666081905  (0.006184404077767222)
     | > loss: 0.18812252581119537  (0.19988013141685063)
     | > align_error: 0.5422028303146362  (0.5973772914321335)

   --> STEP: 28
     | > decoder_loss: 0.44570374488830566  (0.46020482161215376)
     | > postnet_loss: 0.30036062002182007  (0.3135524306978498)
     | > stopnet_loss: 0.004057378973811865  (0.0061084388954831025)
     | > loss: 0.19057346880435944  (0.19954775060926164)
     | > align_error: 0.5664986670017242  (0.5962744834167617)

   --> STEP: 29
     | > decoder_loss: 0.44196319580078125  (0.45957580003245124)
     | > postnet_loss: 0.2972155809402466  (0.3129890910510359)
     | > stopnet_loss: 0.00372103089466691  (0.0060261144816618544)
     | > loss: 0.18851572275161743  (0.19916733585554977)
     | > align_error: 0.5408112704753876  (0.5943619588325764)

   --> STEP: 30
     | > decoder_loss: 0.44129806756973267  (0.45896654228369393)
     | > postnet_loss: 0.29761528968811035  (0.3124766310056051)
     | > stopnet_loss: 0.003044883254915476  (0.005926740107436975)
     | > loss: 0.1877732276916504  (0.19878753225008647)
     | > align_error: 0.5345168709754944  (0.5923671225706736)

   --> STEP: 31
     | > decoder_loss: 0.43977460265159607  (0.4583474474568521)
     | > postnet_loss: 0.29878008365631104  (0.3120348068975633)
     | > stopnet_loss: 0.00407057162374258  (0.005866863704737156)
     | > loss: 0.18870924413204193  (0.19846242618176244)
     | > align_error: 0.5596326291561127  (0.5913111711702039)

   --> STEP: 32
     | > decoder_loss: 0.44695624709129333  (0.45799147244542837)
     | > postnet_loss: 0.30180010199546814  (0.31171497236937284)
     | > stopnet_loss: 0.004005972295999527  (0.005808710848214105)
     | > loss: 0.1911950558423996  (0.19823532085865736)
     | > align_error: 0.5317213237285614  (0.5894489884376526)

   --> STEP: 33
     | > decoder_loss: 0.44517427682876587  (0.4576030725782568)
     | > postnet_loss: 0.30060794949531555  (0.31137839591864386)
     | > stopnet_loss: 0.004124317783862352  (0.0057576686341428394)
     | > loss: 0.19056987762451172  (0.19800303470004688)
     | > align_error: 0.5461048483848572  (0.588135529648174)

   --> STEP: 34
     | > decoder_loss: 0.4507099688053131  (0.4574003342319937)
     | > postnet_loss: 0.302287757396698  (0.31111102419741016)
     | > stopnet_loss: 0.003458736464381218  (0.0056900529820910276)
     | > loss: 0.19170817732810974  (0.19781789183616638)
     | > align_error: 0.5636405348777771  (0.5874150886255152)

   --> STEP: 35
     | > decoder_loss: 0.44847843050956726  (0.45714542269706726)
     | > postnet_loss: 0.3011871874332428  (0.3108274860041482)
     | > stopnet_loss: 0.003666248871013522  (0.005632230007488813)
     | > loss: 0.1910826563835144  (0.19762545653751917)
     | > align_error: 0.5343685150146484  (0.5858994722366333)

   --> STEP: 36
     | > decoder_loss: 0.45487385988235474  (0.4570823237299919)
     | > postnet_loss: 0.305296391248703  (0.3106738444831636)
     | > stopnet_loss: 0.003858399810269475  (0.005582956946454942)
     | > loss: 0.1939009577035904  (0.1975219982365767)
     | > align_error: 0.6342198848724365  (0.5872417059209611)

   --> STEP: 37
     | > decoder_loss: 0.4469234049320221  (0.4568077583570738)
     | > postnet_loss: 0.3022399842739105  (0.31044590231534597)
     | > stopnet_loss: 0.003704142291098833  (0.005532178171985858)
     | > loss: 0.190994992852211  (0.1973455926856479)
     | > align_error: 0.5193833708763123  (0.5854076968657004)

   --> STEP: 38
     | > decoder_loss: 0.4355508089065552  (0.4562483649504812)
     | > postnet_loss: 0.29543009400367737  (0.3100507494650389)
     | > stopnet_loss: 0.0032624881714582443  (0.0054724494877614474)
     | > loss: 0.18600770831108093  (0.19704722730736984)
     | > align_error: 0.5515645742416382  (0.5845170883755935)

   --> STEP: 39
     | > decoder_loss: 0.4494178891181946  (0.45607322454452515)
     | > postnet_loss: 0.3043983578681946  (0.3099058163471711)
     | > stopnet_loss: 0.0036028940230607986  (0.005424512168153739)
     | > loss: 0.19205695390701294  (0.19691927157915556)
     | > align_error: 0.5464079082012177  (0.5835399299095838)

   --> STEP: 40
     | > decoder_loss: 0.4470887780189514  (0.4558486133813858)
     | > postnet_loss: 0.3031759560108185  (0.3097375698387623)
     | > stopnet_loss: 0.0031495103612542152  (0.00536763712298125)
     | > loss: 0.1907157003879547  (0.19676418229937553)
     | > align_error: 0.5846123099327087  (0.583566739410162)

   --> STEP: 41
     | > decoder_loss: 0.4366293251514435  (0.4553798502538262)
     | > postnet_loss: 0.2950171232223511  (0.30937853455543524)
     | > stopnet_loss: 0.0038116758223623037  (0.005329686847356398)
     | > loss: 0.1867232769727707  (0.19651928216945835)
     | > align_error: 0.5039073824882507  (0.5816238282657251)

   --> STEP: 42
     | > decoder_loss: 0.4420323669910431  (0.4550620530332838)
     | > postnet_loss: 0.2979533076286316  (0.3091065053428923)
     | > stopnet_loss: 0.0033870888873934746  (0.005283434514976328)
     | > loss: 0.18838351964950562  (0.1963255735380309)
     | > align_error: 0.5799279808998108  (0.5815834509474891)

   --> STEP: 43
     | > decoder_loss: 0.440908819437027  (0.454732908065929)
     | > postnet_loss: 0.29742932319641113  (0.3088349429673928)
     | > stopnet_loss: 0.0030475223902612925  (0.005231436558587607)
     | > loss: 0.18763205409049988  (0.19612339866715808)
     | > align_error: 0.5519077777862549  (0.5808933190135068)

   --> STEP: 44
     | > decoder_loss: 0.4587678015232086  (0.45482461018995807)
     | > postnet_loss: 0.3066866397857666  (0.3087861178950831)
     | > stopnet_loss: 0.002803499810397625  (0.005176256177946925)
     | > loss: 0.1941671073436737  (0.19607893750071526)
     | > align_error: 0.5517876148223877  (0.580231825736436)

   --> STEP: 45
     | > decoder_loss: 0.4512343108654022  (0.4547448257605235)
     | > postnet_loss: 0.30543121695518494  (0.3087115645408631)
     | > stopnet_loss: 0.003455705475062132  (0.005138021717882819)
     | > loss: 0.1926220804452896  (0.19600211845503912)
     | > align_error: 0.5528327226638794  (0.579622956779268)

   --> STEP: 46
     | > decoder_loss: 0.44277819991111755  (0.45448468172031903)
     | > postnet_loss: 0.2974087595939636  (0.30846585138984356)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.364530957106388 (+0.02578983884869196)
     | > avg_decoder_loss: 0.450340445746075 (+0.00020646687709924283)
     | > avg_postnet_loss: 0.3050541593269869 (+0.0007673849662145349)
     | > avg_stopnet_loss: 0.004516143870370632 (+5.65279994837152e-06)
     | > avg_loss: 0.19336479450717117 (+0.0002491133231105336)
     | > avg_align_error: 0.5723699317737058 (-0.0006317089904437356)


 > EPOCH: 31/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 01:10:36)

   --> TIME: 2025-12-28 01:11:04 -- STEP: 19/150 -- GLOBAL_STEP: 4700
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4948526918888092  (0.4851633247576262)
     | > postnet_loss: 0.4171444773674011  (0.4169757052471763)
     | > stopnet_loss: 0.008360767737030983  (0.010904393600005852)
     | > loss: 0.2363600730895996  (0.2364391488464255)
     | > align_error: 0.6370387971401215  (0.6814833659874765)
     | > grad_norm: tensor(0.2493, device='cuda:0')  (tensor(0.3036, device='cuda:0'))
     | > step_time: 0.6173  (0.5697867493880423)
     | > loader_time: 1.129  (0.8447768562718442)


   --> TIME: 2025-12-28 01:11:52 -- STEP: 44/150 -- GLOBAL_STEP: 4725
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5033931136131287  (0.49179058047858154)
     | > postnet_loss: 0.417414128780365  (0.4170898321000012)
     | > stopnet_loss: 0.005122936796396971  (0.008172442670911549)
     | > loss: 0.23532474040985107  (0.23539254475723614)
     | > align_error: 0.5913474559783936  (0.650397808037021)
     | > grad_norm: tensor(0.1587, device='cuda:0')  (tensor(0.2499, device='cuda:0'))
     | > step_time: 1.1566  (0.7969113859263334)
     | > loader_time: 0.977  (0.9040647365830161)


   --> TIME: 2025-12-28 01:12:53 -- STEP: 69/150 -- GLOBAL_STEP: 4750
     | > current_lr: 1e-05  (1.0000000000000016e-05)
     | > decoder_loss: 0.502008855342865  (0.49499894397846167)
     | > postnet_loss: 0.41757312417030334  (0.4163154856018398)
     | > stopnet_loss: 0.0044787111692130566  (0.006856154869782968)
     | > loss: 0.23437421023845673  (0.2346847612356794)
     | > align_error: 0.6116984486579895  (0.6391306558380956)
     | > grad_norm: tensor(0.1246, device='cuda:0')  (tensor(0.2257, device='cuda:0'))
     | > step_time: 1.3766  (0.9705887877422831)
     | > loader_time: 1.2571  (1.005168786947278)


   --> TIME: 2025-12-28 01:14:09 -- STEP: 94/150 -- GLOBAL_STEP: 4775
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49880146980285645  (0.4961719490746234)
     | > postnet_loss: 0.4141620099544525  (0.41550395463375334)
     | > stopnet_loss: 0.003975663334131241  (0.00607733523839728)
     | > loss: 0.23221653699874878  (0.2339963104496611)
     | > align_error: 0.6187467575073242  (0.6342383749941564)
     | > grad_norm: tensor(0.1637, device='cuda:0')  (tensor(0.2143, device='cuda:0'))
     | > step_time: 1.6722  (1.1221667604243504)
     | > loader_time: 2.0904  (1.1348793531985992)


   --> TIME: 2025-12-28 01:15:39 -- STEP: 119/150 -- GLOBAL_STEP: 4800
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49685409665107727  (0.4971376845315725)
     | > postnet_loss: 0.4094119966030121  (0.4150155111521232)
     | > stopnet_loss: 0.0032972577027976513  (0.005538375915161201)
     | > loss: 0.22986377775669098  (0.23357667492217377)
     | > align_error: 0.6167643070220947  (0.6290667883488313)
     | > grad_norm: tensor(0.1210, device='cuda:0')  (tensor(0.2019, device='cuda:0'))
     | > step_time: 1.6862  (1.2470367615964228)
     | > loader_time: 1.8205  (1.2874119762612992)


   --> TIME: 2025-12-28 01:17:16 -- STEP: 144/150 -- GLOBAL_STEP: 4825
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.501616358757019  (0.4980681039806869)
     | > postnet_loss: 0.4093112349510193  (0.41435787619815934)
     | > stopnet_loss: 0.002985348692163825  (0.005139793969445036)
     | > loss: 0.2307172417640686  (0.23324628940059078)
     | > align_error: 0.5963085889816284  (0.6253936003065774)
     | > grad_norm: tensor(0.1523, device='cuda:0')  (tensor(0.1963, device='cuda:0'))
     | > step_time: 2.1112  (1.377670930491553)
     | > loader_time: 1.8818  (1.3922475510173373)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47301793098449707  (0.47301793098449707)
     | > postnet_loss: 0.33292990922927856  (0.33292990922927856)
     | > stopnet_loss: 0.012426167726516724  (0.012426167726516724)
     | > loss: 0.21391312777996063  (0.21391312777996063)
     | > align_error: 0.7187298536300659  (0.7187298536300659)

   --> STEP: 1
     | > decoder_loss: 0.4543509781360626  (0.4543509781360626)
     | > postnet_loss: 0.3185550570487976  (0.3185550570487976)
     | > stopnet_loss: 0.009819312021136284  (0.009819312021136284)
     | > loss: 0.2030458301305771  (0.2030458301305771)
     | > align_error: 0.6597639322280884  (0.6597639322280884)

   --> STEP: 2
     | > decoder_loss: 0.44726938009262085  (0.45081017911434174)
     | > postnet_loss: 0.3137706518173218  (0.3161628544330597)
     | > stopnet_loss: 0.011230667121708393  (0.010524989571422338)
     | > loss: 0.20149067044258118  (0.20226825028657913)
     | > align_error: 0.6567963361740112  (0.6582801342010498)

   --> STEP: 3
     | > decoder_loss: 0.45121893286705017  (0.45094643036524457)
     | > postnet_loss: 0.3108709454536438  (0.3143988847732544)
     | > stopnet_loss: 0.008594619110226631  (0.00988153275102377)
     | > loss: 0.19911707937717438  (0.2012178599834442)
     | > align_error: 0.735401451587677  (0.6839872399965922)

   --> STEP: 4
     | > decoder_loss: 0.4603669047355652  (0.4533015489578247)
     | > postnet_loss: 0.3207714259624481  (0.3159920200705528)
     | > stopnet_loss: 0.008412753231823444  (0.009514337871223688)
     | > loss: 0.2036973237991333  (0.20183772593736649)
     | > align_error: 0.6046173870563507  (0.6641447767615318)

   --> STEP: 5
     | > decoder_loss: 0.44093286991119385  (0.4508278131484985)
     | > postnet_loss: 0.30428463220596313  (0.3136505424976349)
     | > stopnet_loss: 0.008392413146793842  (0.009289952926337719)
     | > loss: 0.19469678401947021  (0.20040953755378724)
     | > align_error: 0.6429885625839233  (0.6599135339260102)

   --> STEP: 6
     | > decoder_loss: 0.45638230443000793  (0.45175356169541675)
     | > postnet_loss: 0.3137746751308441  (0.3136712312698364)
     | > stopnet_loss: 0.007456693798303604  (0.008984409738332033)
     | > loss: 0.19999593496322632  (0.20034060378869376)
     | > align_error: 0.5948721766471863  (0.6490733077128729)

   --> STEP: 7
     | > decoder_loss: 0.4644906520843506  (0.453573146036693)
     | > postnet_loss: 0.31402984261512756  (0.3137224614620209)
     | > stopnet_loss: 0.0065148151479661465  (0.008631610511136907)
     | > loss: 0.20114493370056152  (0.20045550806181772)
     | > align_error: 0.5802063941955566  (0.6392351772103991)

   --> STEP: 8
     | > decoder_loss: 0.45971089601516724  (0.4543403647840023)
     | > postnet_loss: 0.31308549642562866  (0.31364284083247185)
     | > stopnet_loss: 0.007445197552442551  (0.008483308891300112)
     | > loss: 0.20064429938793182  (0.20047910697758198)
     | > align_error: 0.5761005282402039  (0.6313433460891247)

   --> STEP: 9
     | > decoder_loss: 0.45709460973739624  (0.45464639200104606)
     | > postnet_loss: 0.31448569893836975  (0.3137364917331272)
     | > stopnet_loss: 0.006792963016778231  (0.008295492683019903)
     | > loss: 0.19968804717063904  (0.2003912114434772)
     | > align_error: 0.5930275917053223  (0.6270860400464799)

   --> STEP: 10
     | > decoder_loss: 0.4881024658679962  (0.4579919993877411)
     | > postnet_loss: 0.3293517231941223  (0.3152980148792267)
     | > stopnet_loss: 0.005778039805591106  (0.008043747395277023)
     | > loss: 0.2101415991783142  (0.20136625021696092)
     | > align_error: 0.5875943303108215  (0.6231368690729141)

   --> STEP: 11
     | > decoder_loss: 0.4729732871055603  (0.45935393463481555)
     | > postnet_loss: 0.322265625  (0.3159314339811152)
     | > stopnet_loss: 0.006024315021932125  (0.00786016263406385)
     | > loss: 0.20483404397964478  (0.20168150419538672)
     | > align_error: 0.5951281487941742  (0.6205906217748468)

   --> STEP: 12
     | > decoder_loss: 0.4660274088382721  (0.4599100574851036)
     | > postnet_loss: 0.3128863275051117  (0.3156776751081149)
     | > stopnet_loss: 0.008038939908146858  (0.007875060740237435)
     | > loss: 0.20276737213134766  (0.20177199319005013)
     | > align_error: 0.5885914862155914  (0.6179240271449088)

   --> STEP: 13
     | > decoder_loss: 0.45688578486442566  (0.45967742112966686)
     | > postnet_loss: 0.31362998485565186  (0.31552016047331005)
     | > stopnet_loss: 0.005729949101805687  (0.007710052152665762)
     | > loss: 0.19835889339447021  (0.20150944705192858)
     | > align_error: 0.5872865915298462  (0.6155673013283655)

   --> STEP: 14
     | > decoder_loss: 0.46265220642089844  (0.4598899057933262)
     | > postnet_loss: 0.3133138418197632  (0.31536256628377096)
     | > stopnet_loss: 0.005098664201796055  (0.007523524441889354)
     | > loss: 0.19909018278121948  (0.20133664246116365)
     | > align_error: 0.5549054145812988  (0.6112343094178607)

   --> STEP: 15
     | > decoder_loss: 0.46629783511161804  (0.4603171010812124)
     | > postnet_loss: 0.32023027539253235  (0.31568708022435504)
     | > stopnet_loss: 0.005105625372380018  (0.007362331170588732)
     | > loss: 0.2017376571893692  (0.20136337677637736)
     | > align_error: 0.5892607569694519  (0.6097694059213001)

   --> STEP: 16
     | > decoder_loss: 0.46482864022254944  (0.46059907227754593)
     | > postnet_loss: 0.311422199010849  (0.31542052514851093)
     | > stopnet_loss: 0.005268546286970377  (0.007231469615362585)
     | > loss: 0.19933125376701355  (0.20123636908829212)
     | > align_error: 0.6070765256881714  (0.6096011009067296)

   --> STEP: 17
     | > decoder_loss: 0.47337818145751953  (0.46135078458225026)
     | > postnet_loss: 0.3226843774318695  (0.3158478105769438)
     | > stopnet_loss: 0.004981029778718948  (0.0070990908014423705)
     | > loss: 0.2039966732263565  (0.20139873991994298)
     | > align_error: 0.5587670803070068  (0.6066108644008635)

   --> STEP: 18
     | > decoder_loss: 0.46845710277557373  (0.4617455800374349)
     | > postnet_loss: 0.31474241614341736  (0.3157863997750812)
     | > stopnet_loss: 0.005477205850183964  (0.007008986081928015)
     | > loss: 0.20127709209918976  (0.2013919817076789)
     | > align_error: 0.6044125258922577  (0.6064887344837188)

   --> STEP: 19
     | > decoder_loss: 0.46638455986976624  (0.4619897368707155)
     | > postnet_loss: 0.3136845529079437  (0.3156757762557582)
     | > stopnet_loss: 0.0050259302370250225  (0.006904614721669962)
     | > loss: 0.2000432014465332  (0.20132099327288175)
     | > align_error: 0.6012976765632629  (0.6062155209089579)

   --> STEP: 20
     | > decoder_loss: 0.46220171451568604  (0.462000335752964)
     | > postnet_loss: 0.31227681040763855  (0.31550582796335225)
     | > stopnet_loss: 0.004657095763832331  (0.006792238773778081)
     | > loss: 0.19827672839164734  (0.20116878002882005)
     | > align_error: 0.623117059469223  (0.6070605978369712)

   --> STEP: 21
     | > decoder_loss: 0.45924773812294006  (0.4618692596753438)
     | > postnet_loss: 0.30784910917282104  (0.3151412223066603)
     | > stopnet_loss: 0.004140411037951708  (0.006665961262548254)
     | > loss: 0.195914626121521  (0.20091858222371056)
     | > align_error: 0.5608891844749451  (0.6048619591054462)

   --> STEP: 22
     | > decoder_loss: 0.46138420701026917  (0.46184721182693134)
     | > postnet_loss: 0.3118140697479248  (0.31498998809944506)
     | > stopnet_loss: 0.005053436849266291  (0.006592664698308165)
     | > loss: 0.19835299253463745  (0.20080196451057086)
     | > align_error: 0.6260617971420288  (0.605825588107109)

   --> STEP: 23
     | > decoder_loss: 0.433103084564209  (0.4605974671633347)
     | > postnet_loss: 0.3004249334335327  (0.31435672485310107)
     | > stopnet_loss: 0.004685068503022194  (0.006509725733295731)
     | > loss: 0.18806707859039307  (0.20024827381838922)
     | > align_error: 0.5669994354248047  (0.6041374945122262)

   --> STEP: 24
     | > decoder_loss: 0.46781137585639954  (0.4608980466922124)
     | > postnet_loss: 0.3162393271923065  (0.31443516661723464)
     | > stopnet_loss: 0.004502223338931799  (0.0064260798001972335)
     | > loss: 0.20051489770412445  (0.20025938314696154)
     | > align_error: 0.5802525579929352  (0.6031422888239224)

   --> STEP: 25
     | > decoder_loss: 0.46917006373405457  (0.4612289273738861)
     | > postnet_loss: 0.3134521543979645  (0.31439584612846383)
     | > stopnet_loss: 0.003806896274909377  (0.00632131245918572)
     | > loss: 0.19946244359016418  (0.20022750556468963)
     | > align_error: 0.5590602159500122  (0.601379005908966)

   --> STEP: 26
     | > decoder_loss: 0.4423217475414276  (0.4605017281495608)
     | > postnet_loss: 0.3005446195602417  (0.31386310664507067)
     | > stopnet_loss: 0.0045665716752409935  (0.006253822429033999)
     | > loss: 0.1902831643819809  (0.19984503090381622)
     | > align_error: 0.5477583408355713  (0.5993166726369124)

   --> STEP: 27
     | > decoder_loss: 0.4395798444747925  (0.45972684356901383)
     | > postnet_loss: 0.29816511273384094  (0.31328169946317325)
     | > stopnet_loss: 0.00403184536844492  (0.006171526982345515)
     | > loss: 0.1884680837392807  (0.1994236624903149)
     | > align_error: 0.5418551564216614  (0.5971884683326438)

   --> STEP: 28
     | > decoder_loss: 0.4446284770965576  (0.45918761619499754)
     | > postnet_loss: 0.3009132146835327  (0.3128399678639004)
     | > stopnet_loss: 0.0040466561913490295  (0.0060956387398099264)
     | > loss: 0.19043207168579102  (0.1991025342472962)
     | > align_error: 0.5661343336105347  (0.5960793920925685)

   --> STEP: 29
     | > decoder_loss: 0.4403778314590454  (0.45853900292824057)
     | > postnet_loss: 0.2969006299972534  (0.3122903355236712)
     | > stopnet_loss: 0.003700432600453496  (0.006013045424659704)
     | > loss: 0.18802005052566528  (0.19872037963620548)
     | > align_error: 0.5406999289989471  (0.5941697554341678)

   --> STEP: 30
     | > decoder_loss: 0.44093406200408936  (0.4579521715641022)
     | > postnet_loss: 0.29819026589393616  (0.31182033320268)
     | > stopnet_loss: 0.003058880800381303  (0.005914573270517091)
     | > loss: 0.18783995509147644  (0.19835769881804785)
     | > align_error: 0.5340609550476074  (0.5921661287546158)

   --> STEP: 31
     | > decoder_loss: 0.4390060305595398  (0.45734100572524533)
     | > postnet_loss: 0.3000302314758301  (0.3114400073405236)
     | > stopnet_loss: 0.0040780953131616116  (0.005855332046086269)
     | > loss: 0.18883715569972992  (0.19805058452390856)
     | > align_error: 0.5596029162406921  (0.5911157025444892)

   --> STEP: 32
     | > decoder_loss: 0.44617563486099243  (0.4569920878857374)
     | > postnet_loss: 0.3025091588497162  (0.31116091832518583)
     | > stopnet_loss: 0.0040009524673223495  (0.0057973826842498966)
     | > loss: 0.19117213785648346  (0.19783563306555152)
     | > align_error: 0.5314181745052338  (0.5892501547932625)

   --> STEP: 33
     | > decoder_loss: 0.44402140378952026  (0.45659903685251874)
     | > postnet_loss: 0.3016853630542755  (0.3108737802866734)
     | > stopnet_loss: 0.004133201204240322  (0.005746952942431424)
     | > loss: 0.19055989384651184  (0.19761515611952002)
     | > align_error: 0.5458085536956787  (0.5879337426387903)

   --> STEP: 34
     | > decoder_loss: 0.45023488998413086  (0.456411856062272)
     | > postnet_loss: 0.30388104915618896  (0.3106681117240121)
     | > stopnet_loss: 0.0034669428132474422  (0.005679893820984837)
     | > loss: 0.19199593365192413  (0.19744988487047307)
     | > align_error: 0.5633585453033447  (0.5872109427171595)

   --> STEP: 35
     | > decoder_loss: 0.447710245847702  (0.45616323862757)
     | > postnet_loss: 0.3017403185367584  (0.310413031918662)
     | > stopnet_loss: 0.00365548231638968  (0.005622053492282118)
     | > loss: 0.19101811945438385  (0.1972661201442991)
     | > align_error: 0.5340222120285034  (0.5856912646974836)

   --> STEP: 36
     | > decoder_loss: 0.45444443821907043  (0.4561154941717784)
     | > postnet_loss: 0.30677852034568787  (0.3103120732638571)
     | > stopnet_loss: 0.00384512753225863  (0.005572694437837021)
     | > loss: 0.1941508650779724  (0.19717958528134558)
     | > align_error: 0.6340425312519073  (0.5870343554351065)

   --> STEP: 37
     | > decoder_loss: 0.4461079239845276  (0.45584501930185267)
     | > postnet_loss: 0.3026554584503174  (0.310105137728356)
     | > stopnet_loss: 0.0036891100462526083  (0.005521786751577983)
     | > loss: 0.1908799558877945  (0.19700932502746582)
     | > align_error: 0.519147515296936  (0.5851995759719127)

   --> STEP: 38
     | > decoder_loss: 0.43528643250465393  (0.4553040038598211)
     | > postnet_loss: 0.29665932059288025  (0.3097513004353172)
     | > stopnet_loss: 0.003239542944356799  (0.005461727704019531)
     | > loss: 0.1862259805202484  (0.1967255528035917)
     | > align_error: 0.5511026382446289  (0.5843022881369843)

   --> STEP: 39
     | > decoder_loss: 0.44859930872917175  (0.4551320886000609)
     | > postnet_loss: 0.30483734607696533  (0.30962530160561585)
     | > stopnet_loss: 0.0035952269099652767  (0.005413868709300191)
     | > loss: 0.19195440411567688  (0.19660321565774774)
     | > align_error: 0.5461863875389099  (0.5833249573524183)

   --> STEP: 40
     | > decoder_loss: 0.445900022983551  (0.45490128695964815)
     | > postnet_loss: 0.303747296333313  (0.3094783514738083)
     | > stopnet_loss: 0.00315465428866446  (0.005357388348784298)
     | > loss: 0.19056648015975952  (0.19645229727029806)
     | > align_error: 0.5841918587684631  (0.5833466298878194)

   --> STEP: 41
     | > decoder_loss: 0.4363396465778351  (0.45444856402350636)
     | > postnet_loss: 0.29597949981689453  (0.30914911118949334)
     | > stopnet_loss: 0.0038169948384165764  (0.005319817775360695)
     | > loss: 0.18689677119255066  (0.19621923565864569)
     | > align_error: 0.5039601922035217  (0.5814103753101536)

   --> STEP: 42
     | > decoder_loss: 0.4416012167930603  (0.4541426748037338)
     | > postnet_loss: 0.2997751533985138  (0.30892592171827954)
     | > stopnet_loss: 0.0033870874904096127  (0.005273800387623764)
     | > loss: 0.18873119354248047  (0.19604094894159413)
     | > align_error: 0.5794900953769684  (0.5813646543593635)

   --> STEP: 43
     | > decoder_loss: 0.4400760531425476  (0.4538155440674272)
     | > postnet_loss: 0.2986653745174408  (0.3086873043415158)
     | > stopnet_loss: 0.003055643755942583  (0.00522221534967769)
     | > loss: 0.1877409964799881  (0.1958479267913242)
     | > align_error: 0.551529586315155  (0.5806708155676377)

   --> STEP: 44
     | > decoder_loss: 0.4582865238189697  (0.4539171572435986)
     | > postnet_loss: 0.3075408935546875  (0.30866124955090607)
     | > stopnet_loss: 0.002793213352560997  (0.005167010758834129)
     | > loss: 0.19425006210803986  (0.19581161168488592)
     | > align_error: 0.5510727167129517  (0.5799981315027585)

   --> STEP: 45
     | > decoder_loss: 0.45091328024864197  (0.45385040442148844)
     | > postnet_loss: 0.30676203966140747  (0.30861904488669495)
     | > stopnet_loss: 0.0034582000225782394  (0.005129037186917332)
     | > loss: 0.19287702441215515  (0.1957463986343808)
     | > align_error: 0.5525954365730286  (0.5793891827265423)

   --> STEP: 46
     | > decoder_loss: 0.4416479170322418  (0.4535851329565048)
     | > postnet_loss: 0.29799193143844604  (0.3083880206812982)
     | > stopnet_loss: 0.003317379392683506  (0.005089653321825292)
     | > loss: 0.1882273554801941  (0.19558294117450717)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35283335411187366 (-0.011697602994514333)
     | > avg_decoder_loss: 0.4494124939947417 (-0.0009279517513333113)
     | > avg_postnet_loss: 0.30490525653868 (-0.00014890278830687054)
     | > avg_stopnet_loss: 0.0045086222552609715 (-7.521615109660172e-06)
     | > avg_loss: 0.19308805984981134 (-0.00027673465735983394)
     | > avg_align_error: 0.5720810519926476 (-0.00028887978105818224)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_4832.pth

 > EPOCH: 32/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 01:19:38)

   --> TIME: 2025-12-28 01:20:05 -- STEP: 18/150 -- GLOBAL_STEP: 4850
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4840051829814911  (0.4832538929250505)
     | > postnet_loss: 0.411939799785614  (0.41582726107703316)
     | > stopnet_loss: 0.007869153283536434  (0.010876230688558685)
     | > loss: 0.2318553924560547  (0.23564651939604017)
     | > align_error: 0.7044236660003662  (0.6835842811399035)
     | > grad_norm: tensor(0.2629, device='cuda:0')  (tensor(0.2595, device='cuda:0'))
     | > step_time: 0.7038  (0.5681612491607666)
     | > loader_time: 1.2217  (0.9023848507139418)


   --> TIME: 2025-12-28 01:20:55 -- STEP: 43/150 -- GLOBAL_STEP: 4875
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.5026574730873108  (0.4910089789434921)
     | > postnet_loss: 0.4175485670566559  (0.41665344044219615)
     | > stopnet_loss: 0.005355756264179945  (0.008135138696795977)
     | > loss: 0.2354072779417038  (0.23505074444205262)
     | > align_error: 0.608945220708847  (0.6518132062845453)
     | > grad_norm: tensor(0.2566, device='cuda:0')  (tensor(0.2534, device='cuda:0'))
     | > step_time: 1.1684  (0.7940239074618317)
     | > loader_time: 1.2477  (0.9752158342405807)


   --> TIME: 2025-12-28 01:21:56 -- STEP: 68/150 -- GLOBAL_STEP: 4900
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5093193650245667  (0.4946839011767331)
     | > postnet_loss: 0.42045482993125916  (0.416083499789238)
     | > stopnet_loss: 0.00437723845243454  (0.006816525077310336)
     | > loss: 0.236820787191391  (0.23450837613028638)
     | > align_error: 0.6160500943660736  (0.6395636069424012)
     | > grad_norm: tensor(0.1496, device='cuda:0')  (tensor(0.2387, device='cuda:0'))
     | > step_time: 1.3427  (0.9649140975054573)
     | > loader_time: 1.2601  (1.058425082879908)


   --> TIME: 2025-12-28 01:23:10 -- STEP: 93/150 -- GLOBAL_STEP: 4925
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4964364469051361  (0.49580193879783796)
     | > postnet_loss: 0.41849926114082336  (0.4152107088155644)
     | > stopnet_loss: 0.0038115589413791895  (0.006048374629068759)
     | > loss: 0.23254548013210297  (0.23380153714328683)
     | > align_error: 0.6042065620422363  (0.6341633078872515)
     | > grad_norm: tensor(0.1325, device='cuda:0')  (tensor(0.2256, device='cuda:0'))
     | > step_time: 1.6563  (1.1068736071227698)
     | > loader_time: 1.4306  (1.1634170624517621)


   --> TIME: 2025-12-28 01:24:32 -- STEP: 118/150 -- GLOBAL_STEP: 4950
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.512921154499054  (0.49682552683151376)
     | > postnet_loss: 0.4196012318134308  (0.4147439540947898)
     | > stopnet_loss: 0.0032169779296964407  (0.00552116767542784)
     | > loss: 0.23634758591651917  (0.23341353869034073)
     | > align_error: 0.6053003668785095  (0.6287845047348636)
     | > grad_norm: tensor(0.1357, device='cuda:0')  (tensor(0.2105, device='cuda:0'))
     | > step_time: 1.8484  (1.2324693425227018)
     | > loader_time: 1.536  (1.2532698158490456)


   --> TIME: 2025-12-28 01:26:12 -- STEP: 143/150 -- GLOBAL_STEP: 4975
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49944522976875305  (0.4976652202072677)
     | > postnet_loss: 0.4076858162879944  (0.4140800552351491)
     | > stopnet_loss: 0.003154770005494356  (0.005128755760086061)
     | > loss: 0.22993753850460052  (0.2330650753908224)
     | > align_error: 0.5762717723846436  (0.6251285307474068)
     | > grad_norm: tensor(0.1620, device='cuda:0')  (tensor(0.2030, device='cuda:0'))
     | > step_time: 2.3307  (1.3691518640184732)
     | > loader_time: 2.4852  (1.3767697894489848)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4738119840621948  (0.4738119840621948)
     | > postnet_loss: 0.33640867471694946  (0.33640867471694946)
     | > stopnet_loss: 0.01254386454820633  (0.01254386454820633)
     | > loss: 0.215099036693573  (0.215099036693573)
     | > align_error: 0.7194802761077881  (0.7194802761077881)

   --> STEP: 1
     | > decoder_loss: 0.4547613263130188  (0.4547613263130188)
     | > postnet_loss: 0.32358989119529724  (0.32358989119529724)
     | > stopnet_loss: 0.009839187376201153  (0.009839187376201153)
     | > loss: 0.20442698895931244  (0.20442698895931244)
     | > align_error: 0.6605262756347656  (0.6605262756347656)

   --> STEP: 2
     | > decoder_loss: 0.44793587923049927  (0.45134860277175903)
     | > postnet_loss: 0.3147619068622589  (0.3191758990287781)
     | > stopnet_loss: 0.011206143535673618  (0.010522665455937386)
     | > loss: 0.20188060402870178  (0.2031537964940071)
     | > align_error: 0.6574979424476624  (0.659012109041214)

   --> STEP: 3
     | > decoder_loss: 0.4508529007434845  (0.45118336876233417)
     | > postnet_loss: 0.3126978278160095  (0.3170165419578552)
     | > stopnet_loss: 0.008674666285514832  (0.009906665732463201)
     | > loss: 0.19956235587596893  (0.20195664962132773)
     | > align_error: 0.7359470427036285  (0.6846570869286855)

   --> STEP: 4
     | > decoder_loss: 0.4606879651546478  (0.4535595178604126)
     | > postnet_loss: 0.3234177827835083  (0.3186168521642685)
     | > stopnet_loss: 0.008413434959948063  (0.009533358039334416)
     | > loss: 0.20443987846374512  (0.20257745683193207)
     | > align_error: 0.6051691770553589  (0.6647851094603539)

   --> STEP: 5
     | > decoder_loss: 0.4403134286403656  (0.4509103000164032)
     | > postnet_loss: 0.3052479028701782  (0.31594306230545044)
     | > stopnet_loss: 0.00842592678964138  (0.009311871789395808)
     | > loss: 0.19481626152992249  (0.20102521777153015)
     | > align_error: 0.6435777246952057  (0.6605436325073242)

   --> STEP: 6
     | > decoder_loss: 0.45690014958381653  (0.45190860827763873)
     | > postnet_loss: 0.31619349122047424  (0.3159848004579544)
     | > stopnet_loss: 0.007466642651706934  (0.009004333599780997)
     | > loss: 0.2007400542497635  (0.20097769051790237)
     | > align_error: 0.595652312040329  (0.6497284124294916)

   --> STEP: 7
     | > decoder_loss: 0.46485233306884766  (0.45375771181924)
     | > postnet_loss: 0.3142647445201874  (0.31573907818113056)
     | > stopnet_loss: 0.006533088628202677  (0.008651298603841237)
     | > loss: 0.2013123631477356  (0.20102550089359283)
     | > align_error: 0.580949068069458  (0.6399027918066297)

   --> STEP: 8
     | > decoder_loss: 0.4602050483226776  (0.4545636288821697)
     | > postnet_loss: 0.3152206540107727  (0.3156742751598358)
     | > stopnet_loss: 0.007692299317568541  (0.00853142369305715)
     | > loss: 0.2015487104654312  (0.20109090209007263)
     | > align_error: 0.5769665837287903  (0.6320357657968998)

   --> STEP: 9
     | > decoder_loss: 0.45702335238456726  (0.4548369314935472)
     | > postnet_loss: 0.31500568985939026  (0.31559998790423077)
     | > stopnet_loss: 0.006837982218712568  (0.008343263529241085)
     | > loss: 0.19984523952007294  (0.20095249513785043)
     | > align_error: 0.5935264825820923  (0.6277569565508101)

   --> STEP: 10
     | > decoder_loss: 0.4883798360824585  (0.45819122195243833)
     | > postnet_loss: 0.3313805162906647  (0.31717804074287415)
     | > stopnet_loss: 0.00585696566849947  (0.008094633743166924)
     | > loss: 0.2107970416545868  (0.2019369497895241)
     | > align_error: 0.5883125364780426  (0.6238125145435334)

   --> STEP: 11
     | > decoder_loss: 0.47198018431663513  (0.4594447639855472)
     | > postnet_loss: 0.32148781418800354  (0.317569838328795)
     | > stopnet_loss: 0.00602814182639122  (0.007906770841641859)
     | > loss: 0.2043951451778412  (0.20216042209755292)
     | > align_error: 0.5959027111530304  (0.6212752596898512)

   --> STEP: 12
     | > decoder_loss: 0.4655478596687317  (0.4599533552924792)
     | > postnet_loss: 0.31355711817741394  (0.31723544498284656)
     | > stopnet_loss: 0.0080147385597229  (0.007915768151481947)
     | > loss: 0.2027909755706787  (0.2022129682203134)
     | > align_error: 0.5892424583435059  (0.6186058595776558)

   --> STEP: 13
     | > decoder_loss: 0.45780953764915466  (0.4597884462429927)
     | > postnet_loss: 0.3147761821746826  (0.3170462709206801)
     | > stopnet_loss: 0.005757872015237808  (0.007749776141001628)
     | > loss: 0.19890430569648743  (0.20195845571848062)
     | > align_error: 0.5878331661224365  (0.6162387293118697)

   --> STEP: 14
     | > decoder_loss: 0.46237802505493164  (0.4599734161581312)
     | > postnet_loss: 0.3134014308452606  (0.3167859252010073)
     | > stopnet_loss: 0.005127731245011091  (0.007562487219859447)
     | > loss: 0.19907259941101074  (0.20175232312508992)
     | > align_error: 0.5557262599468231  (0.6119164100715092)

   --> STEP: 15
     | > decoder_loss: 0.4666633903980255  (0.4604194144407908)
     | > postnet_loss: 0.31867510080337524  (0.3169118702411652)
     | > stopnet_loss: 0.005139322020113468  (0.007400942873209715)
     | > loss: 0.20147395133972168  (0.20173376500606538)
     | > align_error: 0.5898157358169556  (0.6104430317878723)

   --> STEP: 16
     | > decoder_loss: 0.4653971493244171  (0.46073052287101746)
     | > postnet_loss: 0.31024524569511414  (0.31649520620703697)
     | > stopnet_loss: 0.005292186513543129  (0.007269145600730553)
     | > loss: 0.1992027908563614  (0.20157557912170887)
     | > align_error: 0.6077291369438171  (0.6102734133601189)

   --> STEP: 17
     | > decoder_loss: 0.4731691777706146  (0.4614622084533467)
     | > postnet_loss: 0.3204340934753418  (0.3167269054581137)
     | > stopnet_loss: 0.0050061852671206  (0.007136030286988791)
     | > loss: 0.20340700447559357  (0.20168331002487855)
     | > align_error: 0.5596747994422913  (0.607297024306129)

   --> STEP: 18
     | > decoder_loss: 0.46857187151908875  (0.4618571897347768)
     | > postnet_loss: 0.3131435811519623  (0.3165278318855498)
     | > stopnet_loss: 0.005505336914211512  (0.007045436210723387)
     | > loss: 0.20093420147895813  (0.20164169288343853)
     | > align_error: 0.6049883961677551  (0.6071687671873305)

   --> STEP: 19
     | > decoder_loss: 0.4671933352947235  (0.4621380395010898)
     | > postnet_loss: 0.3126635253429413  (0.3163244473306756)
     | > stopnet_loss: 0.0050348336808383465  (0.006939615024939964)
     | > loss: 0.19999904930591583  (0.20155523795830577)
     | > align_error: 0.601790726184845  (0.6068857123977259)

   --> STEP: 20
     | > decoder_loss: 0.46261900663375854  (0.4621620878577232)
     | > postnet_loss: 0.3099842071533203  (0.31600743532180786)
     | > stopnet_loss: 0.004679841920733452  (0.006826626369729638)
     | > loss: 0.19783064723014832  (0.2013690084218979)
     | > align_error: 0.6235406994819641  (0.6077184617519379)

   --> STEP: 21
     | > decoder_loss: 0.45943015813827515  (0.46203199596632094)
     | > postnet_loss: 0.3072282075881958  (0.3155893768583025)
     | > stopnet_loss: 0.004147517029196024  (0.006699049734466132)
     | > loss: 0.19581210613250732  (0.201104394027165)
     | > align_error: 0.5615862011909485  (0.6055216874395098)

   --> STEP: 22
     | > decoder_loss: 0.46173205971717834  (0.4620183625004508)
     | > postnet_loss: 0.31067585945129395  (0.31536603515798395)
     | > stopnet_loss: 0.005038435570895672  (0.006623567272485657)
     | > loss: 0.19814041256904602  (0.20096966759725052)
     | > align_error: 0.6264579892158508  (0.6064733375202527)

   --> STEP: 23
     | > decoder_loss: 0.43371960520744324  (0.46078798174858093)
     | > postnet_loss: 0.29913952946662903  (0.31466053491053375)
     | > stopnet_loss: 0.004698124714195728  (0.006539852378646965)
     | > loss: 0.18791291117668152  (0.20040198253548663)
     | > align_error: 0.5676666796207428  (0.6047860915246218)

   --> STEP: 24
     | > decoder_loss: 0.4686603844165802  (0.4611159985264142)
     | > postnet_loss: 0.31411826610565186  (0.314637940376997)
     | > stopnet_loss: 0.004511489998549223  (0.006455337279476225)
     | > loss: 0.20020614564418793  (0.20039382266501585)
     | > align_error: 0.5812098681926727  (0.6038037488857906)

   --> STEP: 25
     | > decoder_loss: 0.46859270334243774  (0.4614150667190552)
     | > postnet_loss: 0.3112783133983612  (0.31450355529785157)
     | > stopnet_loss: 0.0038234470412135124  (0.006350061669945717)
     | > loss: 0.19879119098186493  (0.20032971739768982)
     | > align_error: 0.5594249367713928  (0.6020285964012146)

   --> STEP: 26
     | > decoder_loss: 0.4426295757293701  (0.46069254783483654)
     | > postnet_loss: 0.29966017603874207  (0.31393265609557813)
     | > stopnet_loss: 0.004572401288896799  (0.006281690116828451)
     | > loss: 0.1901448518037796  (0.19993799179792404)
     | > align_error: 0.548553466796875  (0.5999718606472016)

   --> STEP: 27
     | > decoder_loss: 0.4397525191307068  (0.459916991216165)
     | > postnet_loss: 0.2957562506198883  (0.3132594558927748)
     | > stopnet_loss: 0.004040684085339308  (0.006198689893439964)
     | > loss: 0.18791788816452026  (0.19949280277446466)
     | > align_error: 0.5425019264221191  (0.5978433445647912)

   --> STEP: 28
     | > decoder_loss: 0.4449246823787689  (0.45938155161482946)
     | > postnet_loss: 0.29933613538742065  (0.312762194446155)
     | > stopnet_loss: 0.004049735609441996  (0.006121941526154322)
     | > loss: 0.19011493027210236  (0.19915787875652313)
     | > align_error: 0.566829264163971  (0.5967356988361905)

   --> STEP: 29
     | > decoder_loss: 0.4410632848739624  (0.45874988724445476)
     | > postnet_loss: 0.29615214467048645  (0.31218943410906297)
     | > stopnet_loss: 0.0037128166295588017  (0.006038868253857925)
     | > loss: 0.18801666796207428  (0.19877369907395592)
     | > align_error: 0.5413719415664673  (0.5948266037579242)

   --> STEP: 30
     | > decoder_loss: 0.4409202039241791  (0.4581555644671122)
     | > postnet_loss: 0.29691699147224426  (0.31168035268783567)
     | > stopnet_loss: 0.00306753721088171  (0.0059398238857587176)
     | > loss: 0.18752683699131012  (0.19839880367120108)
     | > align_error: 0.5348304510116577  (0.5928267319997153)

   --> STEP: 31
     | > decoder_loss: 0.439612478017807  (0.4575574003881024)
     | > postnet_loss: 0.29778188467025757  (0.3112320150098493)
     | > stopnet_loss: 0.004081550985574722  (0.005879879598656009)
     | > loss: 0.18843013048171997  (0.19807723356831458)
     | > align_error: 0.560302346944809  (0.5917775582882667)

   --> STEP: 32
     | > decoder_loss: 0.44658342003822327  (0.45721446350216866)
     | > postnet_loss: 0.30087152123451233  (0.31090824957937)
     | > stopnet_loss: 0.004026069771498442  (0.005821948041557334)
     | > loss: 0.19088980555534363  (0.19785262644290924)
     | > align_error: 0.5320127904415131  (0.5899099092930556)

   --> STEP: 33
     | > decoder_loss: 0.4448428750038147  (0.4568395668810064)
     | > postnet_loss: 0.2994769811630249  (0.31056184750614746)
     | > stopnet_loss: 0.004191099666059017  (0.005772528393814961)
     | > loss: 0.1902710646390915  (0.19762288214582385)
     | > align_error: 0.5463561415672302  (0.5885900981498489)

   --> STEP: 34
     | > decoder_loss: 0.4507692754268646  (0.45666102889706106)
     | > postnet_loss: 0.3013512194156647  (0.31029094667995677)
     | > stopnet_loss: 0.0034834793768823147  (0.005705203422728707)
     | > loss: 0.19151359796524048  (0.19744319731698318)
     | > align_error: 0.5640389323234558  (0.5878680050373079)

   --> STEP: 35
     | > decoder_loss: 0.4486214816570282  (0.45643132754734583)
     | > postnet_loss: 0.3005385398864746  (0.31001230648585726)
     | > stopnet_loss: 0.003669949248433113  (0.005647053303463118)
     | > loss: 0.19095996022224426  (0.1972579619714192)
     | > align_error: 0.5345614552497864  (0.5863449607576644)

   --> STEP: 36
     | > decoder_loss: 0.45486727356910706  (0.45638788160350585)
     | > postnet_loss: 0.3046157956123352  (0.3098624034060372)
     | > stopnet_loss: 0.0038482716772705317  (0.005597087147179991)
     | > loss: 0.1937190443277359  (0.1971596587035391)
     | > align_error: 0.6347078084945679  (0.5876883731948006)

   --> STEP: 37
     | > decoder_loss: 0.4466956853866577  (0.45612593035440185)
     | > postnet_loss: 0.3013917803764343  (0.3096334676484804)
     | > stopnet_loss: 0.0037137202452868223  (0.005546185339020716)
     | > loss: 0.1907355934381485  (0.196986035317988)
     | > align_error: 0.5197775363922119  (0.585852945173109)

   --> STEP: 38
     | > decoder_loss: 0.43571576476097107  (0.45558882073352214)
     | > postnet_loss: 0.29473134875297546  (0.30924130662491445)
     | > stopnet_loss: 0.0032589843031018972  (0.0054859958380754845)
     | > loss: 0.18587076663970947  (0.196693528247507)
     | > align_error: 0.5517615675926208  (0.584955803657833)

   --> STEP: 39
     | > decoder_loss: 0.44898462295532227  (0.4554194823289529)
     | > postnet_loss: 0.3036580979824066  (0.30909814742895275)
     | > stopnet_loss: 0.0035983051639050245  (0.0054375935130967544)
     | > loss: 0.19175899028778076  (0.19656700163315505)
     | > align_error: 0.5467638969421387  (0.5839765239984562)

   --> STEP: 40
     | > decoder_loss: 0.44648727774620056  (0.4551961772143841)
     | > postnet_loss: 0.3023989796638489  (0.3089306682348251)
     | > stopnet_loss: 0.003160760272294283  (0.005380672682076692)
     | > loss: 0.19038231670856476  (0.19641238451004028)
     | > align_error: 0.5847756862640381  (0.5839965030550958)

   --> STEP: 41
     | > decoder_loss: 0.4365517199039459  (0.4547414343531539)
     | > postnet_loss: 0.2945058047771454  (0.30857884229683297)
     | > stopnet_loss: 0.003823088249191642  (0.005342682817859984)
     | > loss: 0.18658746778964996  (0.1961727523949088)
     | > align_error: 0.5044413208961487  (0.5820561327585361)

   --> STEP: 42
     | > decoder_loss: 0.44139334559440613  (0.45442362271604086)
     | > postnet_loss: 0.29673537611961365  (0.30829685500689913)
     | > stopnet_loss: 0.0033831822220236063  (0.005296028041768642)
     | > loss: 0.1879153698682785  (0.19597614804903665)
     | > align_error: 0.5803821980953217  (0.5820162771713167)

   --> STEP: 43
     | > decoder_loss: 0.44043251872062683  (0.4540982482045196)
     | > postnet_loss: 0.2962607145309448  (0.3080169447632723)
     | > stopnet_loss: 0.0030629043467342854  (0.005244094932581796)
     | > loss: 0.1872362196445465  (0.19577289390009503)
     | > align_error: 0.5523047745227814  (0.5813253119934437)

   --> STEP: 44
     | > decoder_loss: 0.45838263630867004  (0.4541956206614321)
     | > postnet_loss: 0.30579841136932373  (0.3079665235497735)
     | > stopnet_loss: 0.002805239288136363  (0.005188666395208036)
     | > loss: 0.19385048747062683  (0.19572920284487985)
     | > align_error: 0.5517712235450745  (0.5806536281650717)

   --> STEP: 45
     | > decoder_loss: 0.4508105218410492  (0.4541203962432014)
     | > postnet_loss: 0.3045339584350586  (0.30789024432500206)
     | > stopnet_loss: 0.003479852806776762  (0.005150692759909563)
     | > loss: 0.1923159807920456  (0.19565335346592796)
     | > align_error: 0.5533434748649597  (0.5800467358695137)

   --> STEP: 46
     | > decoder_loss: 0.44267839193344116  (0.4538716570190761)
     | > postnet_loss: 0.29674285650253296  (0.3076479098071223)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.37500832658825495 (+0.022174972476381283)
     | > avg_decoder_loss: 0.449781852238106 (+0.000369358243364315)
     | > avg_postnet_loss: 0.3043897585435348 (-0.0005154979951452199)
     | > avg_stopnet_loss: 0.004526592716997998 (+1.7970461737026183e-05)
     | > avg_loss: 0.19306949616381616 (-1.856368599517655e-05)
     | > avg_align_error: 0.572743107423638 (+0.0006620554309904048)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_4983.pth

 > EPOCH: 33/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 01:28:33)

   --> TIME: 2025-12-28 01:28:57 -- STEP: 17/150 -- GLOBAL_STEP: 5000
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48053598403930664  (0.4815799997133367)
     | > postnet_loss: 0.4074946343898773  (0.41483986377716064)
     | > stopnet_loss: 0.007931393571197987  (0.011098383816287798)
     | > loss: 0.2299390584230423  (0.23520335116807153)
     | > align_error: 0.692556232213974  (0.6829427322920631)
     | > grad_norm: tensor(0.2208, device='cuda:0')  (tensor(0.2849, device='cuda:0'))
     | > step_time: 0.7148  (0.5442623110378491)
     | > loader_time: 1.1329  (0.8343936976264504)


   --> TIME: 2025-12-28 01:29:45 -- STEP: 42/150 -- GLOBAL_STEP: 5025
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.498250275850296  (0.4902381265447253)
     | > postnet_loss: 0.41603007912635803  (0.4160952589341572)
     | > stopnet_loss: 0.005328708793967962  (0.008240975583681752)
     | > loss: 0.2338988035917282  (0.23482432216405869)
     | > align_error: 0.6006824970245361  (0.6529439659345717)
     | > grad_norm: tensor(0.1722, device='cuda:0')  (tensor(0.2570, device='cuda:0'))
     | > step_time: 1.0754  (0.7715809912908644)
     | > loader_time: 1.0332  (0.9200376612799508)


   --> TIME: 2025-12-28 01:30:45 -- STEP: 67/150 -- GLOBAL_STEP: 5050
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5034499168395996  (0.4937208815297084)
     | > postnet_loss: 0.41564393043518066  (0.4153699794811989)
     | > stopnet_loss: 0.004191529471427202  (0.006857925831381956)
     | > loss: 0.23396499454975128  (0.2341306409729061)
     | > align_error: 0.6172102093696594  (0.639923425752725)
     | > grad_norm: tensor(0.1466, device='cuda:0')  (tensor(0.2290, device='cuda:0'))
     | > step_time: 1.4434  (0.9561477098891984)
     | > loader_time: 1.227  (1.0091380254546207)


   --> TIME: 2025-12-28 01:32:00 -- STEP: 92/150 -- GLOBAL_STEP: 5075
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4954870045185089  (0.49508384388426074)
     | > postnet_loss: 0.40857550501823425  (0.41457993990701175)
     | > stopnet_loss: 0.003785043954849243  (0.006072088577480907)
     | > loss: 0.22980067133903503  (0.23348803429499917)
     | > align_error: 0.6608559787273407  (0.6348438088012777)
     | > grad_norm: tensor(0.1211, device='cuda:0')  (tensor(0.2067, device='cuda:0'))
     | > step_time: 1.5269  (1.0959123476691874)
     | > loader_time: 1.5473  (1.1400707260422087)


   --> TIME: 2025-12-28 01:33:26 -- STEP: 117/150 -- GLOBAL_STEP: 5100
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4959484934806824  (0.49602827735436267)
     | > postnet_loss: 0.40814289450645447  (0.4141445320386153)
     | > stopnet_loss: 0.003498953999951482  (0.005542726013172641)
     | > loss: 0.22952179610729218  (0.2330859278002356)
     | > align_error: 0.6233310997486115  (0.6291933375546054)
     | > grad_norm: tensor(0.2384, device='cuda:0')  (tensor(0.2017, device='cuda:0'))
     | > step_time: 1.767  (1.2243334126268703)
     | > loader_time: 1.9234  (1.2730870674817985)


   --> TIME: 2025-12-28 01:34:59 -- STEP: 142/150 -- GLOBAL_STEP: 5125
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5091713666915894  (0.49705351196544273)
     | > postnet_loss: 0.4158989489078522  (0.41358131464098546)
     | > stopnet_loss: 0.003093650098890066  (0.005141060912496294)
     | > loss: 0.2343612164258957  (0.23279976729356067)
     | > align_error: 0.5922253727912903  (0.6253965679608599)
     | > grad_norm: tensor(0.0976, device='cuda:0')  (tensor(0.1955, device='cuda:0'))
     | > step_time: 2.0148  (1.3428762798577971)
     | > loader_time: 1.8933  (1.3715343592872078)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47243204712867737  (0.47243204712867737)
     | > postnet_loss: 0.33332177996635437  (0.33332177996635437)
     | > stopnet_loss: 0.012512845918536186  (0.012512845918536186)
     | > loss: 0.21395130455493927  (0.21395130455493927)
     | > align_error: 0.7190705239772797  (0.7190705239772797)

   --> STEP: 1
     | > decoder_loss: 0.45163434743881226  (0.45163434743881226)
     | > postnet_loss: 0.3185139298439026  (0.3185139298439026)
     | > stopnet_loss: 0.009872580878436565  (0.009872580878436565)
     | > loss: 0.20240965485572815  (0.20240965485572815)
     | > align_error: 0.6602432429790497  (0.6602432429790497)

   --> STEP: 2
     | > decoder_loss: 0.4471896290779114  (0.4494119882583618)
     | > postnet_loss: 0.3134154975414276  (0.3159647136926651)
     | > stopnet_loss: 0.011185347102582455  (0.01052896399050951)
     | > loss: 0.20133662223815918  (0.20187313854694366)
     | > align_error: 0.6572421193122864  (0.658742681145668)

   --> STEP: 3
     | > decoder_loss: 0.44998422265052795  (0.44960273305575055)
     | > postnet_loss: 0.3104223310947418  (0.3141172528266907)
     | > stopnet_loss: 0.008570033125579357  (0.009875987035532793)
     | > loss: 0.19867166876792908  (0.2008059819539388)
     | > align_error: 0.7352884411811829  (0.6842579344908396)

   --> STEP: 4
     | > decoder_loss: 0.45744791626930237  (0.4515640288591385)
     | > postnet_loss: 0.3192070424556732  (0.3153897002339363)
     | > stopnet_loss: 0.0084379892796278  (0.009516487596556544)
     | > loss: 0.20260173082351685  (0.2012549191713333)
     | > align_error: 0.6046082377433777  (0.6643455103039742)

   --> STEP: 5
     | > decoder_loss: 0.43984144926071167  (0.4492195129394531)
     | > postnet_loss: 0.30376482009887695  (0.31306472420692444)
     | > stopnet_loss: 0.008360124193131924  (0.00928521491587162)
     | > loss: 0.19426168501377106  (0.19985627233982087)
     | > align_error: 0.6428570747375488  (0.6600478231906891)

   --> STEP: 6
     | > decoder_loss: 0.4548054337501526  (0.4501504997412364)
     | > postnet_loss: 0.3130045533180237  (0.313054695725441)
     | > stopnet_loss: 0.007460891269147396  (0.008981160974750916)
     | > loss: 0.19941338896751404  (0.1997824584444364)
     | > align_error: 0.5948947668075562  (0.6491889804601669)

   --> STEP: 7
     | > decoder_loss: 0.4620443284511566  (0.4518496181283678)
     | > postnet_loss: 0.3117852509021759  (0.31287334646497456)
     | > stopnet_loss: 0.006514495704323053  (0.00862878022183265)
     | > loss: 0.19997188448905945  (0.19980951930795396)
     | > align_error: 0.5806773900985718  (0.6394016104085105)

   --> STEP: 8
     | > decoder_loss: 0.45847535133361816  (0.4526778347790241)
     | > postnet_loss: 0.31219160556793213  (0.31278812885284424)
     | > stopnet_loss: 0.007526949048042297  (0.008491051325108856)
     | > loss: 0.20019368827342987  (0.19985754042863846)
     | > align_error: 0.5762637257575989  (0.6315093748271465)

   --> STEP: 9
     | > decoder_loss: 0.45456093549728394  (0.4528870681921641)
     | > postnet_loss: 0.3122342526912689  (0.31272658705711365)
     | > stopnet_loss: 0.0068018678575754166  (0.008303364273160696)
     | > loss: 0.19850066304206848  (0.19970677627457512)
     | > align_error: 0.5929128229618073  (0.627220869064331)

   --> STEP: 10
     | > decoder_loss: 0.48643165826797485  (0.4562415271997452)
     | > postnet_loss: 0.32799601554870605  (0.31425352990627287)
     | > stopnet_loss: 0.005901668686419725  (0.0080631947144866)
     | > loss: 0.20950858294963837  (0.20068695694208144)
     | > align_error: 0.5876938104629517  (0.6232681632041931)

   --> STEP: 11
     | > decoder_loss: 0.4702247977256775  (0.45751273361119354)
     | > postnet_loss: 0.3196570873260498  (0.31474476239897986)
     | > stopnet_loss: 0.006005631294101477  (0.007876143494451588)
     | > loss: 0.20347610116004944  (0.20094051550735126)
     | > align_error: 0.5952674448490143  (0.6207226433537223)

   --> STEP: 12
     | > decoder_loss: 0.46382686495780945  (0.45803891122341156)
     | > postnet_loss: 0.31123456358909607  (0.31445224583148956)
     | > stopnet_loss: 0.008005618117749691  (0.007886933046393096)
     | > loss: 0.20177097618579865  (0.20100972056388855)
     | > align_error: 0.588752269744873  (0.6180584455529848)

   --> STEP: 13
     | > decoder_loss: 0.4556162357330322  (0.45785255157030547)
     | > postnet_loss: 0.31232935190200806  (0.3142889462984525)
     | > stopnet_loss: 0.005711560137569904  (0.007719596668791313)
     | > loss: 0.1976979523897171  (0.20075496916587537)
     | > align_error: 0.587229311466217  (0.6156869737001566)

   --> STEP: 14
     | > decoder_loss: 0.4595123529434204  (0.45797110881124226)
     | > postnet_loss: 0.31115254759788513  (0.3140649178198406)
     | > stopnet_loss: 0.005103376228362322  (0.007532723780189242)
     | > loss: 0.19776961207389832  (0.2005417293735913)
     | > align_error: 0.5549504160881042  (0.6113486481564385)

   --> STEP: 15
     | > decoder_loss: 0.4649186134338379  (0.4584342757860819)
     | > postnet_loss: 0.31796687841415405  (0.31432504852612814)
     | > stopnet_loss: 0.005097685847431421  (0.007370387918005387)
     | > loss: 0.20081906020641327  (0.20056021809577942)
     | > align_error: 0.5891148149967194  (0.6098663926124572)

   --> STEP: 16
     | > decoder_loss: 0.4642624258995056  (0.45879853516817093)
     | > postnet_loss: 0.30944523215293884  (0.3140200600028038)
     | > stopnet_loss: 0.005272053647786379  (0.007239242026116699)
     | > loss: 0.1986989676952362  (0.20044388994574547)
     | > align_error: 0.6071655750274658  (0.6096975915133953)

   --> STEP: 17
     | > decoder_loss: 0.47145795822143555  (0.4595432071124806)
     | > postnet_loss: 0.3198506832122803  (0.3143630378386554)
     | > stopnet_loss: 0.004992255009710789  (0.007107066319269293)
     | > loss: 0.20281942188739777  (0.20058362711878383)
     | > align_error: 0.559186577796936  (0.6067263554124271)

   --> STEP: 18
     | > decoder_loss: 0.46719110012054443  (0.45996809005737305)
     | > postnet_loss: 0.312378466129303  (0.31425278385480243)
     | > stopnet_loss: 0.005475231446325779  (0.007016408826327986)
     | > loss: 0.20036762952804565  (0.20057162725263172)
     | > align_error: 0.6045167744159698  (0.6066036009126239)

   --> STEP: 19
     | > decoder_loss: 0.46402573585510254  (0.4601816503625167)
     | > postnet_loss: 0.3106038570404053  (0.31406073507509735)
     | > stopnet_loss: 0.004876716062426567  (0.006903793417701596)
     | > loss: 0.19853411614894867  (0.20046438982612208)
     | > align_error: 0.6008007526397705  (0.6062981878456316)

   --> STEP: 20
     | > decoder_loss: 0.4614337384700775  (0.46024425476789477)
     | > postnet_loss: 0.3096045255661011  (0.31383792459964754)
     | > stopnet_loss: 0.00464948546141386  (0.006791078019887209)
     | > loss: 0.19740906357765198  (0.20031162351369858)
     | > align_error: 0.6230564713478088  (0.6071361020207405)

   --> STEP: 21
     | > decoder_loss: 0.4589211344718933  (0.46018124903951374)
     | > postnet_loss: 0.30644485354423523  (0.31348587359700886)
     | > stopnet_loss: 0.004136108327656984  (0.00666465089168577)
     | > loss: 0.19547760486602783  (0.20008143214952379)
     | > align_error: 0.5610427260398865  (0.6049411793549856)

   --> STEP: 22
     | > decoder_loss: 0.46040448546409607  (0.460191396149722)
     | > postnet_loss: 0.3099985718727112  (0.31332735988226806)
     | > stopnet_loss: 0.005014028400182724  (0.00658962259661745)
     | > loss: 0.19761478900909424  (0.19996931200677698)
     | > align_error: 0.6260481476783752  (0.6059005870060488)

   --> STEP: 23
     | > decoder_loss: 0.43310442566871643  (0.45901370178098266)
     | > postnet_loss: 0.29901474714279175  (0.3127050723718561)
     | > stopnet_loss: 0.004679454490542412  (0.006506571809396795)
     | > loss: 0.1877092570066452  (0.19943626613720603)
     | > align_error: 0.5669511556625366  (0.6042071334693743)

   --> STEP: 24
     | > decoder_loss: 0.4676057994365692  (0.4593717058499654)
     | > postnet_loss: 0.3141804039478302  (0.312766544520855)
     | > stopnet_loss: 0.004493834916502237  (0.006422707772192855)
     | > loss: 0.19994038343429565  (0.19945727102458477)
     | > align_error: 0.5801513493061066  (0.6032048091292381)

   --> STEP: 25
     | > decoder_loss: 0.4679267704486847  (0.4597139084339142)
     | > postnet_loss: 0.3111170530319214  (0.31270056486129766)
     | > stopnet_loss: 0.00382117903791368  (0.006318646622821689)
     | > loss: 0.19858212769031525  (0.19942226529121398)
     | > align_error: 0.5590071678161621  (0.6014369034767151)

   --> STEP: 26
     | > decoder_loss: 0.44212833046913147  (0.45903754005065334)
     | > postnet_loss: 0.2992764115333557  (0.31218425127176136)
     | > stopnet_loss: 0.004565911367535591  (0.006251233728387608)
     | > loss: 0.18991710245609283  (0.1990566821052478)
     | > align_error: 0.5477434992790222  (0.5993717725460346)

   --> STEP: 27
     | > decoder_loss: 0.4386366009712219  (0.4582819497143781)
     | > postnet_loss: 0.29558777809143066  (0.3115695670798973)
     | > stopnet_loss: 0.004031548276543617  (0.00616902315609709)
     | > loss: 0.1875876486301422  (0.1986319030876513)
     | > align_error: 0.5420381128787994  (0.5972483036694703)

   --> STEP: 28
     | > decoder_loss: 0.44434499740600586  (0.45778420141765047)
     | > postnet_loss: 0.29919368028640747  (0.31112757112298695)
     | > stopnet_loss: 0.004028900992125273  (0.006092590221669525)
     | > loss: 0.1899135708808899  (0.19832053408026695)
     | > align_error: 0.5664533972740173  (0.5961484855839184)

   --> STEP: 29
     | > decoder_loss: 0.4403265416622162  (0.45718221315022173)
     | > postnet_loss: 0.29538559913635254  (0.31058474450275814)
     | > stopnet_loss: 0.003701987909153104  (0.006010155659168959)
     | > loss: 0.18763002753257751  (0.19795189592345008)
     | > align_error: 0.5408296883106232  (0.5942409408503565)

   --> STEP: 30
     | > decoder_loss: 0.4411999583244324  (0.4566494713226954)
     | > postnet_loss: 0.29686805605888367  (0.310127521554629)
     | > stopnet_loss: 0.0030609997920691967  (0.005911850463598966)
     | > loss: 0.1875779926776886  (0.19760609914859137)
     | > align_error: 0.5341827869415283  (0.5922390023867289)

   --> STEP: 31
     | > decoder_loss: 0.4388427436351776  (0.45607506075213033)
     | > postnet_loss: 0.29771462082862854  (0.3097271054021774)
     | > stopnet_loss: 0.004071865230798721  (0.005852496101250572)
     | > loss: 0.18821120262145996  (0.1973030379702968)
     | > align_error: 0.5602082014083862  (0.5912057507422662)

   --> STEP: 32
     | > decoder_loss: 0.4456285536289215  (0.45574860740453005)
     | > postnet_loss: 0.3002239167690277  (0.30943013075739145)
     | > stopnet_loss: 0.0039925468154251575  (0.005794372686068527)
     | > loss: 0.19045566022396088  (0.1970890574157238)
     | > align_error: 0.531584620475769  (0.5893425904214382)

   --> STEP: 33
     | > decoder_loss: 0.4436461627483368  (0.4553818666573727)
     | > postnet_loss: 0.299252450466156  (0.3091217162031116)
     | > stopnet_loss: 0.004135078750550747  (0.005744091051658897)
     | > loss: 0.18985971808433533  (0.19686998652689386)
     | > align_error: 0.546158492565155  (0.5880339813954902)

   --> STEP: 34
     | > decoder_loss: 0.4499637484550476  (0.4552225102396572)
     | > postnet_loss: 0.30153828859329224  (0.3088986742145875)
     | > stopnet_loss: 0.0034558710176497698  (0.005676790462423335)
     | > loss: 0.1913313865661621  (0.1967070865280488)
     | > align_error: 0.5636482834815979  (0.5873167549862581)

   --> STEP: 35
     | > decoder_loss: 0.4481492340564728  (0.4550204166344234)
     | > postnet_loss: 0.3002657890319824  (0.30865202035222733)
     | > stopnet_loss: 0.0036641559563577175  (0.005619286619392889)
     | > loss: 0.19076789915561676  (0.19653739546026502)
     | > align_error: 0.5340507626533508  (0.5857948694910322)

   --> STEP: 36
     | > decoder_loss: 0.4535045921802521  (0.4549783103995853)
     | > postnet_loss: 0.3040194809436798  (0.3085233387019899)
     | > stopnet_loss: 0.0038243369199335575  (0.005569426905519019)
     | > loss: 0.1932053565979004  (0.19644483882519934)
     | > align_error: 0.6341941356658936  (0.587139293551445)

   --> STEP: 37
     | > decoder_loss: 0.44628068804740906  (0.4547432395252022)
     | > postnet_loss: 0.3010699152946472  (0.30832189482611577)
     | > stopnet_loss: 0.003693690989166498  (0.005518731340212193)
     | > loss: 0.19053132832050323  (0.19628501421696432)
     | > align_error: 0.519395649433136  (0.5853083842509502)

   --> STEP: 38
     | > decoder_loss: 0.43537360429763794  (0.4542335122823715)
     | > postnet_loss: 0.29470083117485046  (0.30796344578266144)
     | > stopnet_loss: 0.0032548399176448584  (0.005459155250144632)
     | > loss: 0.18577344715595245  (0.1960083940311482)
     | > align_error: 0.5513476133346558  (0.5844146797531531)

   --> STEP: 39
     | > decoder_loss: 0.44857725501060486  (0.4540884800446339)
     | > postnet_loss: 0.3033801317214966  (0.30784592490929824)
     | > stopnet_loss: 0.003580597462132573  (0.0054109871017340655)
     | > loss: 0.1915699541568756  (0.19589458788052583)
     | > align_error: 0.5462441444396973  (0.5834359480784491)

   --> STEP: 40
     | > decoder_loss: 0.44570809602737427  (0.45387897044420245)
     | > postnet_loss: 0.3017127215862274  (0.30769259482622147)
     | > stopnet_loss: 0.0031537883915007114  (0.0053545571339782315)
     | > loss: 0.1900089830160141  (0.19574744775891303)
     | > align_error: 0.58429354429245  (0.5834573879837992)

   --> STEP: 41
     | > decoder_loss: 0.43644973635673523  (0.4534538671737764)
     | > postnet_loss: 0.2943023443222046  (0.30736600335051373)
     | > stopnet_loss: 0.0038072008173912764  (0.0053168167360126955)
     | > loss: 0.18649522960186005  (0.19552178390142394)
     | > align_error: 0.5037677884101868  (0.5815137392137111)

   --> STEP: 42
     | > decoder_loss: 0.4405533969402313  (0.45314671312059673)
     | > postnet_loss: 0.29675984382629395  (0.30711347574279424)
     | > stopnet_loss: 0.0033823903650045395  (0.005270758965274406)
     | > loss: 0.187710702419281  (0.19533580577089674)
     | > align_error: 0.5796879827976227  (0.5814702688228518)

   --> STEP: 43
     | > decoder_loss: 0.43977615237236023  (0.45283576984738194)
     | > postnet_loss: 0.2961867153644562  (0.3068593650363212)
     | > stopnet_loss: 0.003044083947315812  (0.00521897582532188)
     | > loss: 0.18703480064868927  (0.19514275914014773)
     | > align_error: 0.5517979860305786  (0.5807802157346594)

   --> STEP: 44
     | > decoder_loss: 0.4578603208065033  (0.452949964187362)
     | > postnet_loss: 0.3054984509944916  (0.30682843517173414)
     | > stopnet_loss: 0.0027847331948578358  (0.0051636521291749705)
     | > loss: 0.19362442195415497  (0.1951082514768297)
     | > align_error: 0.5510311126708984  (0.5801040997559376)

   --> STEP: 45
     | > decoder_loss: 0.4501071274280548  (0.45288679003715515)
     | > postnet_loss: 0.3043145537376404  (0.3067725711398654)
     | > stopnet_loss: 0.0034627080895006657  (0.005125853372737764)
     | > loss: 0.19206812977790833  (0.19504069321685366)
     | > align_error: 0.5527955889701843  (0.5794972439606986)

   --> STEP: 46
     | > decoder_loss: 0.44127923250198364  (0.45263445182986883)
     | > postnet_loss: 0.29606109857559204  (0.30653971304064204)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35517405018661974 (-0.01983427640163521)
     | > avg_decoder_loss: 0.4487646325971141 (-0.0010172196409919398)
     | > avg_postnet_loss: 0.30325559142864106 (-0.001134167114893725)
     | > avg_stopnet_loss: 0.004507536481303923 (-1.9056235694074435e-05)
     | > avg_loss: 0.19251259303454196 (-0.0005569031292741999)
     | > avg_align_error: 0.5722230988921543 (-0.0005200085314837066)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_5134.pth

 > EPOCH: 34/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 01:37:44)

   --> TIME: 2025-12-28 01:38:07 -- STEP: 16/150 -- GLOBAL_STEP: 5150
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48570355772972107  (0.4831470958888531)
     | > postnet_loss: 0.4133763909339905  (0.41588923521339893)
     | > stopnet_loss: 0.008178208023309708  (0.011316735937725753)
     | > loss: 0.2329481840133667  (0.23607581946998835)
     | > align_error: 0.6766562163829803  (0.6815560590475798)
     | > grad_norm: tensor(0.2504, device='cuda:0')  (tensor(0.2920, device='cuda:0'))
     | > step_time: 0.667  (0.5598405003547668)
     | > loader_time: 1.1489  (0.8083089739084244)


   --> TIME: 2025-12-28 01:38:55 -- STEP: 41/150 -- GLOBAL_STEP: 5175
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4974990487098694  (0.49014103994136904)
     | > postnet_loss: 0.4170282185077667  (0.41609775729295684)
     | > stopnet_loss: 0.005668473895639181  (0.008362984307473752)
     | > loss: 0.23430030047893524  (0.23492268418393483)
     | > align_error: 0.5945892333984375  (0.653913652024618)
     | > grad_norm: tensor(0.1565, device='cuda:0')  (tensor(0.2655, device='cuda:0'))
     | > step_time: 1.0929  (0.7843149813210092)
     | > loader_time: 1.1465  (0.9348565252815805)


   --> TIME: 2025-12-28 01:39:57 -- STEP: 66/150 -- GLOBAL_STEP: 5200
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5020630955696106  (0.4937450863195188)
     | > postnet_loss: 0.4144260883331299  (0.41541544370579)
     | > stopnet_loss: 0.0039289542473852634  (0.006950956818675902)
     | > loss: 0.23305125534534454  (0.234241090037606)
     | > align_error: 0.6163679659366608  (0.6401384603796583)
     | > grad_norm: tensor(0.3147, device='cuda:0')  (tensor(0.2517, device='cuda:0'))
     | > step_time: 1.3494  (0.9651081778786399)
     | > loader_time: 1.3861  (1.0295827641631619)


   --> TIME: 2025-12-28 01:41:08 -- STEP: 91/150 -- GLOBAL_STEP: 5225
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4993448853492737  (0.4950410445312877)
     | > postnet_loss: 0.4104991555213928  (0.41459728695534087)
     | > stopnet_loss: 0.004064172971993685  (0.006151080789085434)
     | > loss: 0.23152518272399902  (0.23356066398568207)
     | > align_error: 0.5971020460128784  (0.634108697975075)
     | > grad_norm: tensor(0.1329, device='cuda:0')  (tensor(0.2399, device='cuda:0'))
     | > step_time: 1.4973  (1.1127275163000756)
     | > loader_time: 1.493  (1.12248064659454)


   --> TIME: 2025-12-28 01:42:33 -- STEP: 116/150 -- GLOBAL_STEP: 5250
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49567875266075134  (0.4960314854979515)
     | > postnet_loss: 0.4079143702983856  (0.41417609463477956)
     | > stopnet_loss: 0.0032889130525290966  (0.005602526313882191)
     | > loss: 0.22918719053268433  (0.23315442186491242)
     | > align_error: 0.5899553894996643  (0.6289931206867613)
     | > grad_norm: tensor(0.1502, device='cuda:0')  (tensor(0.2239, device='cuda:0'))
     | > step_time: 1.6718  (1.24589316392767)
     | > loader_time: 1.7537  (1.232948231286016)


   --> TIME: 2025-12-28 01:44:11 -- STEP: 141/150 -- GLOBAL_STEP: 5275
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5048341155052185  (0.4969325824409512)
     | > postnet_loss: 0.4103608727455139  (0.41349618485633366)
     | > stopnet_loss: 0.0030920456629246473  (0.005189915816795)
     | > loss: 0.23189079761505127  (0.23279710832639788)
     | > align_error: 0.6048761010169983  (0.6255341523082544)
     | > grad_norm: tensor(0.1699, device='cuda:0')  (tensor(0.2121, device='cuda:0'))
     | > step_time: 2.2988  (1.3744758629629799)
     | > loader_time: 2.1664  (1.3601429158068719)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4731111526489258  (0.4731111526489258)
     | > postnet_loss: 0.3351539075374603  (0.3351539075374603)
     | > stopnet_loss: 0.012473068200051785  (0.012473068200051785)
     | > loss: 0.2145393341779709  (0.2145393341779709)
     | > align_error: 0.719081848859787  (0.719081848859787)

   --> STEP: 1
     | > decoder_loss: 0.45375949144363403  (0.45375949144363403)
     | > postnet_loss: 0.3219563961029053  (0.3219563961029053)
     | > stopnet_loss: 0.009831980802118778  (0.009831980802118778)
     | > loss: 0.20376095175743103  (0.20376095175743103)
     | > align_error: 0.6602491140365601  (0.6602491140365601)

   --> STEP: 2
     | > decoder_loss: 0.44697844982147217  (0.4503689706325531)
     | > postnet_loss: 0.3137189745903015  (0.3178376853466034)
     | > stopnet_loss: 0.011184661649167538  (0.010508321225643158)
     | > loss: 0.20135901868343353  (0.20255998522043228)
     | > align_error: 0.6571881473064423  (0.6587186306715012)

   --> STEP: 3
     | > decoder_loss: 0.450551301240921  (0.4504297475020091)
     | > postnet_loss: 0.31177589297294617  (0.31581708788871765)
     | > stopnet_loss: 0.008636778220534325  (0.009884473557273546)
     | > loss: 0.19921857118606567  (0.2014461805423101)
     | > align_error: 0.7356516420841217  (0.6843629678090414)

   --> STEP: 4
     | > decoder_loss: 0.4606039524078369  (0.45297329872846603)
     | > postnet_loss: 0.3226088583469391  (0.317515030503273)
     | > stopnet_loss: 0.008423835970461369  (0.009519314160570502)
     | > loss: 0.2042270302772522  (0.2021413929760456)
     | > align_error: 0.6051027774810791  (0.6645479202270508)

   --> STEP: 5
     | > decoder_loss: 0.44149500131607056  (0.4506776392459869)
     | > postnet_loss: 0.3051810562610626  (0.3150482356548309)
     | > stopnet_loss: 0.008391814306378365  (0.009293814189732075)
     | > loss: 0.1950608342885971  (0.2007252812385559)
     | > align_error: 0.6432167887687683  (0.6602816939353943)

   --> STEP: 6
     | > decoder_loss: 0.4562068283557892  (0.4515991707642873)
     | > postnet_loss: 0.31500259041786194  (0.3150406281153361)
     | > stopnet_loss: 0.007450583390891552  (0.008986609056591988)
     | > loss: 0.2002529352903366  (0.2006465569138527)
     | > align_error: 0.5954436659812927  (0.6494753559430441)

   --> STEP: 7
     | > decoder_loss: 0.46354246139526367  (0.4533053551401411)
     | > postnet_loss: 0.31317436695098877  (0.3147740193775722)
     | > stopnet_loss: 0.006542897317558527  (0.008637507379587208)
     | > loss: 0.2007220983505249  (0.200657348547663)
     | > align_error: 0.5807726979255676  (0.6396606905119759)

   --> STEP: 8
     | > decoder_loss: 0.45910874009132385  (0.4540307782590389)
     | > postnet_loss: 0.31391066312789917  (0.31466609984636307)
     | > stopnet_loss: 0.007375964894890785  (0.008479814569000155)
     | > loss: 0.20063082873821259  (0.2006540335714817)
     | > align_error: 0.57575523853302  (0.6316725090146065)

   --> STEP: 9
     | > decoder_loss: 0.4569081664085388  (0.4543504880534278)
     | > postnet_loss: 0.3145550787448883  (0.31465376416842145)
     | > stopnet_loss: 0.006781682372093201  (0.008291133213788271)
     | > loss: 0.19964750111103058  (0.20054219663143158)
     | > align_error: 0.593451201915741  (0.6274256971147325)

   --> STEP: 10
     | > decoder_loss: 0.4864574074745178  (0.4575611799955368)
     | > postnet_loss: 0.3298719525337219  (0.31617558300495147)
     | > stopnet_loss: 0.00566378328949213  (0.008028398221358656)
     | > loss: 0.2097461223602295  (0.20146258920431137)
     | > align_error: 0.5864974558353424  (0.6233328729867935)

   --> STEP: 11
     | > decoder_loss: 0.4720208942890167  (0.45887569947676227)
     | > postnet_loss: 0.3212536871433258  (0.31663722883571277)
     | > stopnet_loss: 0.0060288929380476475  (0.00784662501378493)
     | > loss: 0.20434753596782684  (0.2017248570919037)
     | > align_error: 0.5954967439174652  (0.6208023157986727)

   --> STEP: 12
     | > decoder_loss: 0.465349018573761  (0.45941514273484546)
     | > postnet_loss: 0.3130572736263275  (0.3163388992349307)
     | > stopnet_loss: 0.008006793446838856  (0.00785997238320609)
     | > loss: 0.2026083618402481  (0.20179848248759905)
     | > align_error: 0.5889243483543396  (0.618145818511645)

   --> STEP: 13
     | > decoder_loss: 0.45755574107170105  (0.4592721118376805)
     | > postnet_loss: 0.3143487870693207  (0.3161858136837299)
     | > stopnet_loss: 0.005739476997405291  (0.007696857353529105)
     | > loss: 0.19871561229228973  (0.20156133862642142)
     | > align_error: 0.5877962112426758  (0.6158112333371089)

   --> STEP: 14
     | > decoder_loss: 0.4595487415790558  (0.4592918711049216)
     | > postnet_loss: 0.31172406673431396  (0.31586711747305735)
     | > stopnet_loss: 0.005097910761833191  (0.007511218311265111)
     | > loss: 0.19791610538959503  (0.20130096482379095)
     | > align_error: 0.5555760860443115  (0.6115087228161948)

   --> STEP: 15
     | > decoder_loss: 0.46634650230407715  (0.459762179851532)
     | > postnet_loss: 0.31871116161346436  (0.3160567204157511)
     | > stopnet_loss: 0.005120234098285437  (0.007351819363733133)
     | > loss: 0.20138464868068695  (0.20130654374758403)
     | > align_error: 0.5897365212440491  (0.6100572427113851)

   --> STEP: 16
     | > decoder_loss: 0.4660910665988922  (0.460157735273242)
     | > postnet_loss: 0.3106639087200165  (0.3157196696847677)
     | > stopnet_loss: 0.00526835722848773  (0.007221602980280295)
     | > loss: 0.1994570940732956  (0.201190953142941)
     | > align_error: 0.6076560616493225  (0.6099071688950062)

   --> STEP: 17
     | > decoder_loss: 0.4735252857208252  (0.4609440617701587)
     | > postnet_loss: 0.32090893387794495  (0.3160249205196605)
     | > stopnet_loss: 0.004962653387337923  (0.0070887235924601555)
     | > loss: 0.20357120037078857  (0.20133096768575556)
     | > align_error: 0.5598035454750061  (0.6069598969291238)

   --> STEP: 18
     | > decoder_loss: 0.46910643577575684  (0.4613975269926919)
     | > postnet_loss: 0.31342676281929016  (0.31588057842519546)
     | > stopnet_loss: 0.005470672156661749  (0.0069988318460269105)
     | > loss: 0.20110397040843964  (0.20131835672590467)
     | > align_error: 0.6048798263072968  (0.6068443374501334)

   --> STEP: 19
     | > decoder_loss: 0.4670439660549164  (0.46169470799596685)
     | > postnet_loss: 0.312562495470047  (0.3157059424801877)
     | > stopnet_loss: 0.005056310445070267  (0.006896593877555509)
     | > loss: 0.1999579221010208  (0.20124675490354238)
     | > align_error: 0.6015328466892242  (0.6065647853048224)

   --> STEP: 20
     | > decoder_loss: 0.46218517422676086  (0.4617192313075066)
     | > postnet_loss: 0.30991601943969727  (0.3154164463281631)
     | > stopnet_loss: 0.0046617756597697735  (0.006784852966666222)
     | > loss: 0.1976870596408844  (0.20106877014040947)
     | > align_error: 0.623463362455368  (0.6074097141623497)

   --> STEP: 21
     | > decoder_loss: 0.4593709409236908  (0.4616074079558963)
     | > postnet_loss: 0.3070472776889801  (0.31501791448820204)
     | > stopnet_loss: 0.004127938766032457  (0.006658333242826518)
     | > loss: 0.1957324892282486  (0.20081466152554467)
     | > align_error: 0.5613156855106354  (0.6052147604170299)

   --> STEP: 22
     | > decoder_loss: 0.46162310242652893  (0.46160812134092505)
     | > postnet_loss: 0.3106211721897125  (0.31481806256554346)
     | > stopnet_loss: 0.005037962459027767  (0.006584680025381121)
     | > loss: 0.1980990320444107  (0.20069122382185675)
     | > align_error: 0.6264261603355408  (0.6061789149587805)

   --> STEP: 23
     | > decoder_loss: 0.4337978959083557  (0.4603989811047264)
     | > postnet_loss: 0.29930639266967773  (0.3141436421352884)
     | > stopnet_loss: 0.004671838600188494  (0.0065015130068944845)
     | > loss: 0.18794791400432587  (0.20013716687326846)
     | > align_error: 0.5673706233501434  (0.6044915979323181)

   --> STEP: 24
     | > decoder_loss: 0.46924546360969543  (0.46076758454243344)
     | > postnet_loss: 0.314652681350708  (0.31416485210259754)
     | > stopnet_loss: 0.00452982634305954  (0.006419359395901362)
     | > loss: 0.2005043625831604  (0.20015246669451395)
     | > align_error: 0.5807665586471558  (0.6035030546287697)

   --> STEP: 25
     | > decoder_loss: 0.4690767824649811  (0.4610999524593353)
     | > postnet_loss: 0.31163492798805237  (0.31406365513801576)
     | > stopnet_loss: 0.0038108164444565773  (0.00631501767784357)
     | > loss: 0.19898875057697296  (0.20010591804981231)
     | > align_error: 0.5594703853130341  (0.6017417478561403)

   --> STEP: 26
     | > decoder_loss: 0.442722350358963  (0.460393121609321)
     | > postnet_loss: 0.2997356355190277  (0.3135125774603624)
     | > stopnet_loss: 0.004568841774016619  (0.0062478570661579184)
     | > loss: 0.1901833415031433  (0.19972428049032503)
     | > align_error: 0.5484548807144165  (0.5996922529660741)

   --> STEP: 27
     | > decoder_loss: 0.4398009181022644  (0.45963044740535597)
     | > postnet_loss: 0.29606419801712036  (0.31286634118468676)
     | > stopnet_loss: 0.004046508576720953  (0.006166325640623216)
     | > loss: 0.18801279366016388  (0.1992905217188376)
     | > align_error: 0.5423054695129395  (0.5975668165418839)

   --> STEP: 28
     | > decoder_loss: 0.44539615511894226  (0.4591220798236983)
     | > postnet_loss: 0.2998632490634918  (0.3124019450375012)
     | > stopnet_loss: 0.004041641019284725  (0.0060904440470039845)
     | > loss: 0.19035649299621582  (0.19897144926445826)
     | > align_error: 0.5665785670280457  (0.5964600933449612)

   --> STEP: 29
     | > decoder_loss: 0.44060054421424866  (0.4584834061819932)
     | > postnet_loss: 0.29589134454727173  (0.31183261398611395)
     | > stopnet_loss: 0.003714068792760372  (0.006008500072719722)
     | > loss: 0.18783704936504364  (0.1985875044403405)
     | > align_error: 0.5411881804466248  (0.5945541653139841)

   --> STEP: 30
     | > decoder_loss: 0.44124850630760193  (0.45790890951951346)
     | > postnet_loss: 0.29710352420806885  (0.3113416443268458)
     | > stopnet_loss: 0.0030812928453087807  (0.005910926498472691)
     | > loss: 0.1876693069934845  (0.1982235645254453)
     | > align_error: 0.5345863699913025  (0.592555238803228)

   --> STEP: 31
     | > decoder_loss: 0.4398706555366516  (0.457327030358776)
     | > postnet_loss: 0.2982172667980194  (0.3109182773097869)
     | > stopnet_loss: 0.00408406974747777  (0.005851995635537371)
     | > loss: 0.18860603868961334  (0.1979133217565475)
     | > align_error: 0.5602887868881226  (0.591514385515644)

   --> STEP: 32
     | > decoder_loss: 0.44667190313339233  (0.45699405763298273)
     | > postnet_loss: 0.3010042607784271  (0.3106084642931819)
     | > stopnet_loss: 0.0040092142298817635  (0.005794408716610633)
     | > loss: 0.19092825055122375  (0.19769503828138113)
     | > align_error: 0.5315719544887543  (0.5896411845460536)

   --> STEP: 33
     | > decoder_loss: 0.44510388374328613  (0.456633749333295)
     | > postnet_loss: 0.2998455762863159  (0.3102823161717617)
     | > stopnet_loss: 0.0041964855045080185  (0.005745986801092372)
     | > loss: 0.19043384492397308  (0.19747500211903543)
     | > align_error: 0.5464848279953003  (0.5883334161657278)

   --> STEP: 34
     | > decoder_loss: 0.450817346572876  (0.45646267866387086)
     | > postnet_loss: 0.3017529845237732  (0.3100314534762326)
     | > stopnet_loss: 0.003478564089164138  (0.005679297897800365)
     | > loss: 0.19162113964557648  (0.19730282969334545)
     | > align_error: 0.5639160573482513  (0.5876152585534491)

   --> STEP: 35
     | > decoder_loss: 0.44839924573898315  (0.4562322948660169)
     | > postnet_loss: 0.3005372881889343  (0.30976019161088125)
     | > stopnet_loss: 0.003646559314802289  (0.005621219652571848)
     | > loss: 0.190880686044693  (0.19711933987481253)
     | > align_error: 0.5343753099441528  (0.586094117164612)

   --> STEP: 36
     | > decoder_loss: 0.4546123147010803  (0.45618729541699093)
     | > postnet_loss: 0.30462875962257385  (0.30961765183342826)
     | > stopnet_loss: 0.003841764759272337  (0.005571790349980195)
     | > loss: 0.19365203380584717  (0.19702302581734127)
     | > align_error: 0.6344977617263794  (0.5874386628468833)

   --> STEP: 37
     | > decoder_loss: 0.44690826535224915  (0.45593651082064657)
     | > postnet_loss: 0.30148452520370483  (0.3093978376001925)
     | > stopnet_loss: 0.0036963073071092367  (0.005521101619091791)
     | > loss: 0.19079451262950897  (0.19685468762307554)
     | > align_error: 0.5196416079998016  (0.5856063100131784)

   --> STEP: 38
     | > decoder_loss: 0.4358174502849579  (0.45540706185918106)
     | > postnet_loss: 0.2949599325656891  (0.3090178927308635)
     | > stopnet_loss: 0.0032592054922133684  (0.005461578036805517)
     | > loss: 0.1859535574913025  (0.19656781577750257)
     | > align_error: 0.5516733229160309  (0.5847133366685167)

   --> STEP: 39
     | > decoder_loss: 0.44860216975212097  (0.4552325774461795)
     | > postnet_loss: 0.3034975528717041  (0.3088763455549876)
     | > stopnet_loss: 0.0035797457676380873  (0.005413325927339685)
     | > loss: 0.19160468876361847  (0.1964405561104799)
     | > align_error: 0.5464462041854858  (0.5837321281433108)

   --> STEP: 40
     | > decoder_loss: 0.4462403655052185  (0.4550077721476555)
     | > postnet_loss: 0.30224359035491943  (0.3087105266749859)
     | > stopnet_loss: 0.003159098094329238  (0.005356970231514424)
     | > loss: 0.19028007984161377  (0.19628654420375824)
     | > align_error: 0.5846003592014313  (0.5837538339197638)

   --> STEP: 41
     | > decoder_loss: 0.4372195303440094  (0.454573912591469)
     | > postnet_loss: 0.2948015630245209  (0.30837128365912087)
     | > stopnet_loss: 0.0038078315556049347  (0.0053191863613702905)
     | > loss: 0.1868131011724472  (0.1960554846176287)
     | > align_error: 0.5042330026626587  (0.5818143014500783)

   --> STEP: 42
     | > decoder_loss: 0.44087398052215576  (0.4542477237326758)
     | > postnet_loss: 0.2968102991580963  (0.3080960221233822)
     | > stopnet_loss: 0.0033888276666402817  (0.005273225440067195)
     | > loss: 0.18780988454818726  (0.19585916080645152)
     | > align_error: 0.5799658596515656  (0.581770290931066)

   --> STEP: 43
     | > decoder_loss: 0.4408762753009796  (0.4539367598156596)
     | > postnet_loss: 0.2967803180217743  (0.3078328662140425)
     | > stopnet_loss: 0.003057383233681321  (0.005221694225965198)
     | > loss: 0.18747153878211975  (0.19566409982914149)
     | > align_error: 0.5521345138549805  (0.5810810868130175)

   --> STEP: 44
     | > decoder_loss: 0.45848244428634644  (0.45404007082635706)
     | > postnet_loss: 0.30598241090774536  (0.30779081041162665)
     | > stopnet_loss: 0.002795279258862138  (0.00516654843125831)
     | > loss: 0.19391149282455444  (0.1956242678517645)
     | > align_error: 0.5512831509113312  (0.5804038609970701)

   --> STEP: 45
     | > decoder_loss: 0.45049768686294556  (0.4539613511827257)
     | > postnet_loss: 0.3044887185096741  (0.30771743059158324)
     | > stopnet_loss: 0.0034472693223506212  (0.005128342228838139)
     | > loss: 0.192193865776062  (0.19554803669452667)
     | > align_error: 0.553092360496521  (0.5797969387637246)

   --> STEP: 46
     | > decoder_loss: 0.4423762559890747  (0.45370950128721155)
     | > postnet_loss: 0.29667341709136963  (0.3074773433415786)
     | > stopnet_loss: 0.0033083606977015734  (0.005088777412943865)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.36189339738903625 (+0.006719347202416515)
     | > avg_decoder_loss: 0.4495211121710864 (+0.0007564795739723462)
     | > avg_postnet_loss: 0.30413154580376367 (+0.0008759543751226118)
     | > avg_stopnet_loss: 0.004511304563052499 (+3.768081748576138e-06)
     | > avg_loss: 0.19292446812897018 (+0.00041187509442822123)
     | > avg_align_error: 0.5725545652888038 (+0.0003314663966494935)


 > EPOCH: 35/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 01:47:00)

   --> TIME: 2025-12-28 01:47:21 -- STEP: 15/150 -- GLOBAL_STEP: 5300
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48440003395080566  (0.48218940099080404)
     | > postnet_loss: 0.41214457154273987  (0.41604440013567606)
     | > stopnet_loss: 0.008073567412793636  (0.011277257837355137)
     | > loss: 0.232209712266922  (0.2358357071876526)
     | > align_error: 0.6634922623634338  (0.6827497998873393)
     | > grad_norm: tensor(0.2413, device='cuda:0')  (tensor(0.2806, device='cuda:0'))
     | > step_time: 0.7071  (0.5489729086558025)
     | > loader_time: 0.8183  (0.8207131544748942)


   --> TIME: 2025-12-28 01:48:09 -- STEP: 40/150 -- GLOBAL_STEP: 5325
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.503312349319458  (0.48927095979452134)
     | > postnet_loss: 0.4192001521587372  (0.4157388523221016)
     | > stopnet_loss: 0.005570516921579838  (0.008283985650632528)
     | > loss: 0.23619864881038666  (0.23453643843531607)
     | > align_error: 0.6226573884487152  (0.6560846991837026)
     | > grad_norm: tensor(0.2339, device='cuda:0')  (tensor(0.2443, device='cuda:0'))
     | > step_time: 1.0158  (0.783264833688736)
     | > loader_time: 1.0607  (0.9111017107963562)


   --> TIME: 2025-12-28 01:49:10 -- STEP: 65/150 -- GLOBAL_STEP: 5350
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5039600729942322  (0.49346240758895876)
     | > postnet_loss: 0.4150443971157074  (0.41538530037953303)
     | > stopnet_loss: 0.004267646931111813  (0.006894798397731323)
     | > loss: 0.23401875793933868  (0.23410672499583318)
     | > align_error: 0.6646758615970612  (0.6409504358585064)
     | > grad_norm: tensor(0.1868, device='cuda:0')  (tensor(0.2232, device='cuda:0'))
     | > step_time: 1.3799  (0.959578957924476)
     | > loader_time: 1.1957  (1.0174828309279222)


   --> TIME: 2025-12-28 01:50:24 -- STEP: 90/150 -- GLOBAL_STEP: 5375
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49679067730903625  (0.49511284397708044)
     | > postnet_loss: 0.40883007645606995  (0.41470810075600945)
     | > stopnet_loss: 0.0036525630857795477  (0.006099861027258966)
     | > loss: 0.2300577461719513  (0.23355509721570544)
     | > align_error: 0.6650143265724182  (0.6348880145284864)
     | > grad_norm: tensor(0.3234, device='cuda:0')  (tensor(0.2196, device='cuda:0'))
     | > step_time: 1.585  (1.1034727149539523)
     | > loader_time: 1.6133  (1.1516479121314154)


   --> TIME: 2025-12-28 01:51:51 -- STEP: 115/150 -- GLOBAL_STEP: 5400
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49750635027885437  (0.496035744573759)
     | > postnet_loss: 0.40852490067481995  (0.41420233923455946)
     | > stopnet_loss: 0.0034803918097168207  (0.005559634245203241)
     | > loss: 0.2299882024526596  (0.23311915488346763)
     | > align_error: 0.661051332950592  (0.6294529393963191)
     | > grad_norm: tensor(0.1430, device='cuda:0')  (tensor(0.2111, device='cuda:0'))
     | > step_time: 1.6399  (1.226563756362252)
     | > loader_time: 1.6832  (1.2891458117443582)


   --> TIME: 2025-12-28 01:53:23 -- STEP: 140/150 -- GLOBAL_STEP: 5425
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5044823884963989  (0.49680683336087633)
     | > postnet_loss: 0.4101741313934326  (0.4134408769862992)
     | > stopnet_loss: 0.003031865693628788  (0.00516162070811593)
     | > loss: 0.2316959947347641  (0.23272354826331138)
     | > align_error: 0.5940588116645813  (0.6258425105895314)
     | > grad_norm: tensor(0.2900, device='cuda:0')  (tensor(0.2031, device='cuda:0'))
     | > step_time: 2.0404  (1.3511681539671763)
     | > loader_time: 1.9804  (1.3773087791034153)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47111976146698  (0.47111976146698)
     | > postnet_loss: 0.3350274860858917  (0.3350274860858917)
     | > stopnet_loss: 0.012432972900569439  (0.012432972900569439)
     | > loss: 0.21396978199481964  (0.21396978199481964)
     | > align_error: 0.7186846733093262  (0.7186846733093262)

   --> STEP: 1
     | > decoder_loss: 0.4518563449382782  (0.4518563449382782)
     | > postnet_loss: 0.32152852416038513  (0.32152852416038513)
     | > stopnet_loss: 0.009889566339552402  (0.009889566339552402)
     | > loss: 0.20323579013347626  (0.20323579013347626)
     | > align_error: 0.6595752835273743  (0.6595752835273743)

   --> STEP: 2
     | > decoder_loss: 0.44666609168052673  (0.44926121830940247)
     | > postnet_loss: 0.31399816274642944  (0.3177633434534073)
     | > stopnet_loss: 0.011184781789779663  (0.010537174064666033)
     | > loss: 0.2013508379459381  (0.20229331403970718)
     | > align_error: 0.6567850708961487  (0.6581801772117615)

   --> STEP: 3
     | > decoder_loss: 0.44902318716049194  (0.44918187459309894)
     | > postnet_loss: 0.31137242913246155  (0.3156330386797587)
     | > stopnet_loss: 0.008623016998171806  (0.009899121709167957)
     | > loss: 0.19872193038463593  (0.2011028528213501)
     | > align_error: 0.7349759936332703  (0.6837787826855978)

   --> STEP: 4
     | > decoder_loss: 0.4583336114883423  (0.4514698088169098)
     | > postnet_loss: 0.32209542393684387  (0.31724863499403)
     | > stopnet_loss: 0.008435556665062904  (0.009533230448141694)
     | > loss: 0.2035428136587143  (0.20171284303069115)
     | > align_error: 0.6041010618209839  (0.6638593524694443)

   --> STEP: 5
     | > decoder_loss: 0.439584344625473  (0.44909271597862244)
     | > postnet_loss: 0.30480366945266724  (0.31475964188575745)
     | > stopnet_loss: 0.008389425463974476  (0.00930446945130825)
     | > loss: 0.19448642432689667  (0.20026755928993226)
     | > align_error: 0.6423899233341217  (0.6595654666423798)

   --> STEP: 6
     | > decoder_loss: 0.4552355110645294  (0.45011651515960693)
     | > postnet_loss: 0.31516093015670776  (0.31482652326424915)
     | > stopnet_loss: 0.007451483979821205  (0.008995638539393743)
     | > loss: 0.20005060732364655  (0.20023140062888464)
     | > align_error: 0.5945395827293396  (0.6487278193235397)

   --> STEP: 7
     | > decoder_loss: 0.46373558044433594  (0.4520620959145682)
     | > postnet_loss: 0.31394267082214355  (0.31470025862966267)
     | > stopnet_loss: 0.006551610305905342  (0.0086464916488954)
     | > loss: 0.20097117125988007  (0.20033708214759827)
     | > align_error: 0.5797346532344818  (0.6388716527393886)

   --> STEP: 8
     | > decoder_loss: 0.4580248296260834  (0.4528074376285076)
     | > postnet_loss: 0.3140030801296234  (0.31461311131715775)
     | > stopnet_loss: 0.00734058627858758  (0.008483253477606922)
     | > loss: 0.20034755766391754  (0.20033839158713818)
     | > align_error: 0.5747983455657959  (0.6308624893426895)

   --> STEP: 9
     | > decoder_loss: 0.45572343468666077  (0.45313143730163574)
     | > postnet_loss: 0.3144701421260834  (0.3145972258514828)
     | > stopnet_loss: 0.006748626474291086  (0.008290517143905163)
     | > loss: 0.19929702579975128  (0.2002226842774285)
     | > align_error: 0.5923193097114563  (0.6265799138281081)

   --> STEP: 10
     | > decoder_loss: 0.48645785450935364  (0.45646407902240754)
     | > postnet_loss: 0.3302217125892639  (0.31615967452526095)
     | > stopnet_loss: 0.005759367253631353  (0.008037402154877782)
     | > loss: 0.20992927253246307  (0.20119334310293197)
     | > align_error: 0.5871107578277588  (0.6226329982280732)

   --> STEP: 11
     | > decoder_loss: 0.47082746028900146  (0.45776984095573425)
     | > postnet_loss: 0.3213641047477722  (0.3166328045454892)
     | > stopnet_loss: 0.006011622957885265  (0.007853240409696644)
     | > loss: 0.20405951142311096  (0.2014539038593119)
     | > align_error: 0.5947884917259216  (0.6201016794551503)

   --> STEP: 12
     | > decoder_loss: 0.46432483196258545  (0.4583160902063052)
     | > postnet_loss: 0.3131978213787079  (0.3163465559482574)
     | > stopnet_loss: 0.007987392134964466  (0.00786441972013563)
     | > loss: 0.20236806571483612  (0.2015300840139389)
     | > align_error: 0.5879836082458496  (0.6174251735210419)

   --> STEP: 13
     | > decoder_loss: 0.45610159635543823  (0.45814574452546925)
     | > postnet_loss: 0.31408533453941345  (0.31617261583988476)
     | > stopnet_loss: 0.00573606975376606  (0.007700700491953354)
     | > loss: 0.19828279316425323  (0.20128029241011694)
     | > align_error: 0.5868427455425262  (0.615072679061156)

   --> STEP: 14
     | > decoder_loss: 0.4614819586277008  (0.4583840455327715)
     | > postnet_loss: 0.31322550773620605  (0.3159621081181934)
     | > stopnet_loss: 0.005103641655296087  (0.007515196289334979)
     | > loss: 0.19878050684928894  (0.2011017362986292)
     | > align_error: 0.5544463992118835  (0.6107422305004937)

   --> STEP: 15
     | > decoder_loss: 0.4649205207824707  (0.4588198105494181)
     | > postnet_loss: 0.3186562955379486  (0.3161417206128438)
     | > stopnet_loss: 0.00511237932369113  (0.0073550084916253885)
     | > loss: 0.20100659132003784  (0.20109539330005646)
     | > align_error: 0.5884301662445068  (0.6092547595500946)

   --> STEP: 16
     | > decoder_loss: 0.46437692642211914  (0.45916713029146194)
     | > postnet_loss: 0.31051966547966003  (0.3157903421670198)
     | > stopnet_loss: 0.005270532798022032  (0.007224728760775179)
     | > loss: 0.1989946812391281  (0.20096409879624844)
     | > align_error: 0.6067429482936859  (0.6090977713465691)

   --> STEP: 17
     | > decoder_loss: 0.4720326066017151  (0.4599239230155945)
     | > postnet_loss: 0.3206442594528198  (0.31607586671324334)
     | > stopnet_loss: 0.004956670571118593  (0.007091313573148321)
     | > loss: 0.20312589406967163  (0.20109126322409687)
     | > align_error: 0.5588405132293701  (0.6061414620455574)

   --> STEP: 18
     | > decoder_loss: 0.468084454536438  (0.4603772858778636)
     | > postnet_loss: 0.3138006925582886  (0.31594946814907915)
     | > stopnet_loss: 0.005511998198926449  (0.007003573830135995)
     | > loss: 0.20098328590393066  (0.20108526448408762)
     | > align_error: 0.6040676534175873  (0.6060262504551146)

   --> STEP: 19
     | > decoder_loss: 0.4661370515823364  (0.46068043144125687)
     | > postnet_loss: 0.31264588236808777  (0.3157755952132375)
     | > stopnet_loss: 0.004981625825166702  (0.006897155514084979)
     | > loss: 0.19967736303806305  (0.20101116440798106)
     | > align_error: 0.6008669137954712  (0.6057547064203965)

   --> STEP: 20
     | > decoder_loss: 0.461434930562973  (0.4607181563973427)
     | > postnet_loss: 0.3101172149181366  (0.3154926761984825)
     | > stopnet_loss: 0.004652572795748711  (0.006784926378168165)
     | > loss: 0.19754061102867126  (0.20083763673901558)
     | > align_error: 0.6229250431060791  (0.6066132232546806)

   --> STEP: 21
     | > decoder_loss: 0.45846065878868103  (0.4606106565112159)
     | > postnet_loss: 0.30728134512901306  (0.31510166043326965)
     | > stopnet_loss: 0.004130270332098007  (0.006658514185498158)
     | > loss: 0.19556577503681183  (0.2005865957055773)
     | > align_error: 0.5606764256954193  (0.6044257567042396)

   --> STEP: 22
     | > decoder_loss: 0.45986905694007874  (0.4605769474398006)
     | > postnet_loss: 0.3102770149707794  (0.3148823583667928)
     | > stopnet_loss: 0.005044517107307911  (0.006585150681944056)
     | > loss: 0.19758103787899017  (0.20044997944073242)
     | > align_error: 0.6257411241531372  (0.6053946370428259)

   --> STEP: 23
     | > decoder_loss: 0.43267375230789185  (0.4593637650427611)
     | > postnet_loss: 0.2993313670158386  (0.3142062283080556)
     | > stopnet_loss: 0.0046662078239023685  (0.0065017183837683306)
     | > loss: 0.18766748905181885  (0.19989421898904053)
     | > align_error: 0.5668165683746338  (0.6037173297094263)

   --> STEP: 24
     | > decoder_loss: 0.46752792596817017  (0.4597039384146531)
     | > postnet_loss: 0.31443947553634644  (0.3142159469425677)
     | > stopnet_loss: 0.004511428531259298  (0.006418789639913787)
     | > loss: 0.20000328123569489  (0.1998987632493178)
     | > align_error: 0.5801283717155457  (0.6027344564596813)

   --> STEP: 25
     | > decoder_loss: 0.4669189751148224  (0.4599925398826599)
     | > postnet_loss: 0.31124797463417053  (0.3140972280502318)
     | > stopnet_loss: 0.0038242079317569733  (0.006315006371587515)
     | > loss: 0.1983659416437149  (0.19983745038509368)
     | > align_error: 0.5585148930549622  (0.6009656739234925)

   --> STEP: 26
     | > decoder_loss: 0.4409312605857849  (0.45925941375585705)
     | > postnet_loss: 0.29945215582847595  (0.3135339560417027)
     | > stopnet_loss: 0.004585064947605133  (0.006248470162972808)
     | > loss: 0.18968090415000916  (0.1994468139914366)
     | > align_error: 0.5476303696632385  (0.5989143160673289)

   --> STEP: 27
     | > decoder_loss: 0.4386167526245117  (0.4584948707509924)
     | > postnet_loss: 0.29612720012664795  (0.3128892613781822)
     | > stopnet_loss: 0.004046169109642506  (0.006166903457293908)
     | > loss: 0.18773216009140015  (0.19901293792106486)
     | > align_error: 0.5418725609779358  (0.5968016584714255)

   --> STEP: 28
     | > decoder_loss: 0.44396883249282837  (0.45797608367034365)
     | > postnet_loss: 0.29962611198425293  (0.31241557747125615)
     | > stopnet_loss: 0.004024798981845379  (0.006090399726027889)
     | > loss: 0.18992353975772858  (0.19868831655808858)
     | > align_error: 0.566320538520813  (0.5957130470446179)

   --> STEP: 29
     | > decoder_loss: 0.43980321288108826  (0.4573494329534728)
     | > postnet_loss: 0.2959541380405426  (0.31184794162881774)
     | > stopnet_loss: 0.0037107462994754314  (0.006008342711319183)
     | > loss: 0.18765008449554443  (0.1983076878662767)
     | > align_error: 0.5406911373138428  (0.5938157398125222)

   --> STEP: 30
     | > decoder_loss: 0.4397517442703247  (0.4567628433307012)
     | > postnet_loss: 0.29673856496810913  (0.31134429574012745)
     | > stopnet_loss: 0.0030659339390695095  (0.005910262418910861)
     | > loss: 0.1871885061264038  (0.1979370484749476)
     | > align_error: 0.5340632498264313  (0.5918239901463191)

   --> STEP: 31
     | > decoder_loss: 0.4391804039478302  (0.4561956678667376)
     | > postnet_loss: 0.29834383726119995  (0.31092492611177497)
     | > stopnet_loss: 0.00406049657613039  (0.005850592553014716)
     | > loss: 0.18844155967235565  (0.19763074238454142)
     | > align_error: 0.5598899126052856  (0.5907938586127375)

   --> STEP: 32
     | > decoder_loss: 0.44571197032928467  (0.4558680523186922)
     | > postnet_loss: 0.3011438846588135  (0.3106192685663699)
     | > stopnet_loss: 0.004002166911959648  (0.005792829251731746)
     | > loss: 0.19071613252162933  (0.19741466082632542)
     | > align_error: 0.5314339399337769  (0.5889388611540199)

   --> STEP: 33
     | > decoder_loss: 0.44382593035697937  (0.45550313953197363)
     | > postnet_loss: 0.29974621534347534  (0.3102897821050701)
     | > stopnet_loss: 0.004190604668110609  (0.005744276991622014)
     | > loss: 0.19008363783359528  (0.1971925086144245)
     | > align_error: 0.5462003946304321  (0.5876437561078506)

   --> STEP: 34
     | > decoder_loss: 0.45001477003097534  (0.45534171689959135)
     | > postnet_loss: 0.30197200179100037  (0.31004514150759743)
     | > stopnet_loss: 0.00346957053989172  (0.005677373860688771)
     | > loss: 0.19146625697612762  (0.19702408944859223)
     | > align_error: 0.5636871159076691  (0.5869391490431394)

   --> STEP: 35
     | > decoder_loss: 0.44718265533447266  (0.45510860085487365)
     | > postnet_loss: 0.3004896640777588  (0.3097721278667449)
     | > stopnet_loss: 0.003647712292149663  (0.005619383530159082)
     | > loss: 0.1905657947063446  (0.19683956674167088)
     | > align_error: 0.5338885188102722  (0.5854234167507718)

   --> STEP: 36
     | > decoder_loss: 0.45390236377716064  (0.45507509426938164)
     | > postnet_loss: 0.3046681880950928  (0.3096303517619768)
     | > stopnet_loss: 0.0038431216962635517  (0.005570042923661984)
     | > loss: 0.19348576664924622  (0.19674640562799242)
     | > align_error: 0.6341539025306702  (0.5867770413557689)

   --> STEP: 37
     | > decoder_loss: 0.4461129307746887  (0.45483287363438996)
     | > postnet_loss: 0.3016611933708191  (0.3094149691027563)
     | > stopnet_loss: 0.0036868155002593994  (0.005519144885191643)
     | > loss: 0.19063034653663635  (0.19658110673363144)
     | > align_error: 0.5193748772144318  (0.584955361243841)

   --> STEP: 38
     | > decoder_loss: 0.4343412220478058  (0.4542936196452693)
     | > postnet_loss: 0.2947502136230469  (0.3090290544848692)
     | > stopnet_loss: 0.0032657391857355833  (0.005459844735205958)
     | > loss: 0.18553858995437622  (0.19629051418680893)
     | > align_error: 0.551364541053772  (0.5840713922914708)

   --> STEP: 39
     | > decoder_loss: 0.4479045271873474  (0.4541297967617328)
     | > postnet_loss: 0.30361208319664  (0.30889015778517104)
     | > stopnet_loss: 0.003582327626645565  (0.005411703270883896)
     | > loss: 0.1914614737033844  (0.1961666926359519)
     | > align_error: 0.5461649894714355  (0.5830994332448032)

   --> STEP: 40
     | > decoder_loss: 0.44507896900177  (0.45390352606773376)
     | > postnet_loss: 0.30215984582901  (0.308721899986267)
     | > stopnet_loss: 0.0031520486809313297  (0.005355211906135082)
     | > loss: 0.1899617463350296  (0.19601156897842884)
     | > align_error: 0.5841562151908875  (0.5831258527934553)

   --> STEP: 41
     | > decoder_loss: 0.4356929659843445  (0.45345936606569986)
     | > postnet_loss: 0.294599711894989  (0.3083774563742846)
     | > stopnet_loss: 0.0038303134497255087  (0.0053180192608568)
     | > loss: 0.18640348315238953  (0.19577722542169618)
     | > align_error: 0.503774881362915  (0.5811904632463689)

   --> STEP: 42
     | > decoder_loss: 0.4410748779773712  (0.45316449730169206)
     | > postnet_loss: 0.2974642217159271  (0.3081176174538475)
     | > stopnet_loss: 0.00339136878028512  (0.005272146630366998)
     | > loss: 0.18802614510059357  (0.19559267589024135)
     | > align_error: 0.5797095596790314  (0.5811552036376229)

   --> STEP: 43
     | > decoder_loss: 0.4393807053565979  (0.4528439440006434)
     | > postnet_loss: 0.2965797483921051  (0.30784929491752794)
     | > stopnet_loss: 0.0030550037045031786  (0.005220585166974817)
     | > loss: 0.1870451271533966  (0.19539389568705892)
     | > align_error: 0.5518574118614197  (0.5804738596428274)

   --> STEP: 44
     | > decoder_loss: 0.45799368619918823  (0.45296098359606485)
     | > postnet_loss: 0.3061084449291229  (0.3078097301450642)
     | > stopnet_loss: 0.002795933512970805  (0.0051654794475656345)
     | > loss: 0.19382146000862122  (0.19535815851254898)
     | > align_error: 0.5510085821151733  (0.5798041942444716)

   --> STEP: 45
     | > decoder_loss: 0.4497486650943756  (0.45288959874047174)
     | > postnet_loss: 0.30464085936546326  (0.30773931079440636)
     | > stopnet_loss: 0.00340654538013041  (0.005126392023844851)
     | > loss: 0.19200392067432404  (0.19528361989392173)
     | > align_error: 0.552703320980072  (0.5792019526163739)

   --> STEP: 46
     | > decoder_loss: 0.4411705732345581  (0.4526348373164301)
     | > postnet_loss: 0.2965506315231323  (0.30749607863633516)
     | > stopnet_loss: 0.0033098668791353703  (0.005086902346785949)
     | > loss: 0.18774016201496124  (0.19511963167916174)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3432586807193178 (-0.018634716669718443)
     | > avg_decoder_loss: 0.4483957462238543 (-0.0011253659472321154)
     | > avg_postnet_loss: 0.3039998412132263 (-0.0001317045905373515)
     | > avg_stopnet_loss: 0.004508478387089617 (-2.8261759628823296e-06)
     | > avg_loss: 0.19260737503116782 (-0.00031709309780236783)
     | > avg_align_error: 0.5720587435996894 (-0.0004958216891143286)


 > EPOCH: 36/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 01:56:08)

   --> TIME: 2025-12-28 01:56:28 -- STEP: 14/150 -- GLOBAL_STEP: 5450
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4870477616786957  (0.4805586763790676)
     | > postnet_loss: 0.41453301906585693  (0.414549137864794)
     | > stopnet_loss: 0.008479771204292774  (0.01165112853050232)
     | > loss: 0.23387497663497925  (0.23542808209146773)
     | > align_error: 0.643568754196167  (0.6835037171840668)
     | > grad_norm: tensor(0.1934, device='cuda:0')  (tensor(0.2704, device='cuda:0'))
     | > step_time: 0.7025  (0.577151962688991)
     | > loader_time: 1.1305  (0.7568155697413853)


   --> TIME: 2025-12-28 01:57:15 -- STEP: 39/150 -- GLOBAL_STEP: 5475
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4989912807941437  (0.48860495059918135)
     | > postnet_loss: 0.41780734062194824  (0.41524073481559753)
     | > stopnet_loss: 0.005171564407646656  (0.008439378765148994)
     | > loss: 0.23437121510505676  (0.23440080116956663)
     | > align_error: 0.5933932065963745  (0.6568733148085766)
     | > grad_norm: tensor(0.2359, device='cuda:0')  (tensor(0.2583, device='cuda:0'))
     | > step_time: 1.0559  (0.7725876661447378)
     | > loader_time: 1.0551  (0.907749396104079)


   --> TIME: 2025-12-28 01:58:14 -- STEP: 64/150 -- GLOBAL_STEP: 5500
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.5009025931358337  (0.49278131779283285)
     | > postnet_loss: 0.41413429379463196  (0.4148639589548111)
     | > stopnet_loss: 0.004460764583200216  (0.006984398409258574)
     | > loss: 0.23321999609470367  (0.23389571881853044)
     | > align_error: 0.6139934062957764  (0.6402114178054035)
     | > grad_norm: tensor(0.1427, device='cuda:0')  (tensor(0.2353, device='cuda:0'))
     | > step_time: 1.2713  (0.9385095089673996)
     | > loader_time: 1.2201  (1.00529358163476)


   --> TIME: 2025-12-28 01:59:25 -- STEP: 89/150 -- GLOBAL_STEP: 5525
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4939591884613037  (0.49464775739091166)
     | > postnet_loss: 0.40758857131004333  (0.414268232463451)
     | > stopnet_loss: 0.003767212852835655  (0.006148916598555915)
     | > loss: 0.22915415465831757  (0.2333779147501742)
     | > align_error: 0.6624991595745087  (0.6342532236254617)
     | > grad_norm: tensor(0.2224, device='cuda:0')  (tensor(0.2214, device='cuda:0'))
     | > step_time: 1.6077  (1.0887015053395477)
     | > loader_time: 1.4519  (1.1101348694790623)


   --> TIME: 2025-12-28 02:00:46 -- STEP: 114/150 -- GLOBAL_STEP: 5550
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4970465302467346  (0.4957024222403242)
     | > postnet_loss: 0.40872469544410706  (0.4138812370467605)
     | > stopnet_loss: 0.003584371879696846  (0.005583330535476929)
     | > loss: 0.2300271838903427  (0.23297924600672304)
     | > align_error: 0.6108933091163635  (0.6291405033124121)
     | > grad_norm: tensor(0.1162, device='cuda:0')  (tensor(0.2094, device='cuda:0'))
     | > step_time: 1.723  (1.2130740755482723)
     | > loader_time: 1.5789  (1.2110916627080828)


   --> TIME: 2025-12-28 02:02:21 -- STEP: 139/150 -- GLOBAL_STEP: 5575
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.508332371711731  (0.4966687107686516)
     | > postnet_loss: 0.4144859313964844  (0.4132539012449251)
     | > stopnet_loss: 0.003207847708836198  (0.005171813301929683)
     | > loss: 0.2339124232530594  (0.23265246671738385)
     | > align_error: 0.6489154100418091  (0.6260114181384766)
     | > grad_norm: tensor(0.2155, device='cuda:0')  (tensor(0.2056, device='cuda:0'))
     | > step_time: 2.1554  (1.336396526089675)
     | > loader_time: 2.038  (1.3321691605684576)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.47255077958106995  (0.47255077958106995)
     | > postnet_loss: 0.33456355333328247  (0.33456355333328247)
     | > stopnet_loss: 0.01244946476072073  (0.01244946476072073)
     | > loss: 0.2142280489206314  (0.2142280489206314)
     | > align_error: 0.7194713354110718  (0.7194713354110718)

   --> STEP: 1
     | > decoder_loss: 0.45277345180511475  (0.45277345180511475)
     | > postnet_loss: 0.3205527663230896  (0.3205527663230896)
     | > stopnet_loss: 0.009853311814367771  (0.009853311814367771)
     | > loss: 0.20318487286567688  (0.20318487286567688)
     | > align_error: 0.6607486605644226  (0.6607486605644226)

   --> STEP: 2
     | > decoder_loss: 0.4468493163585663  (0.4498113840818405)
     | > postnet_loss: 0.3138308823108673  (0.31719182431697845)
     | > stopnet_loss: 0.011156071908771992  (0.010504691861569881)
     | > loss: 0.20132611691951752  (0.2022554948925972)
     | > align_error: 0.6576473116874695  (0.659197986125946)

   --> STEP: 3
     | > decoder_loss: 0.44938912987709045  (0.44967063268025714)
     | > postnet_loss: 0.3110658526420593  (0.31514983375867206)
     | > stopnet_loss: 0.008694473654031754  (0.009901285792390505)
     | > loss: 0.1988082230091095  (0.20110640426476797)
     | > align_error: 0.7361447215080261  (0.6848468979199728)

   --> STEP: 4
     | > decoder_loss: 0.4605005085468292  (0.4523781016469002)
     | > postnet_loss: 0.3221632242202759  (0.31690318137407303)
     | > stopnet_loss: 0.008417312055826187  (0.009530292358249426)
     | > loss: 0.20408323407173157  (0.20185061171650887)
     | > align_error: 0.605568915605545  (0.6650274023413658)

   --> STEP: 5
     | > decoder_loss: 0.4397521913051605  (0.4498529195785522)
     | > postnet_loss: 0.30426838994026184  (0.3143762230873108)
     | > stopnet_loss: 0.008394785225391388  (0.009303190931677818)
     | > loss: 0.19439992308616638  (0.20036047399044038)
     | > align_error: 0.6434412896633148  (0.6607101798057556)

   --> STEP: 6
     | > decoder_loss: 0.4559703469276428  (0.4508724908034007)
     | > postnet_loss: 0.3145780861377716  (0.31440986692905426)
     | > stopnet_loss: 0.007485261652618647  (0.00900020271850129)
     | > loss: 0.20012237131595612  (0.20032079021135965)
     | > align_error: 0.5957816243171692  (0.6498887538909912)

   --> STEP: 7
     | > decoder_loss: 0.46407389640808105  (0.4527584058897836)
     | > postnet_loss: 0.3133530020713806  (0.3142588862351009)
     | > stopnet_loss: 0.006536897271871567  (0.00864830194041133)
     | > loss: 0.20089362561702728  (0.20040262384074076)
     | > align_error: 0.580858051776886  (0.6400272250175476)

   --> STEP: 8
     | > decoder_loss: 0.4593183696269989  (0.4535784013569355)
     | > postnet_loss: 0.3135811388492584  (0.3141741678118706)
     | > stopnet_loss: 0.007670895662158728  (0.008526126155629754)
     | > loss: 0.2008957713842392  (0.20046426728367805)
     | > align_error: 0.5769373774528503  (0.6321409940719604)

   --> STEP: 9
     | > decoder_loss: 0.4563915729522705  (0.45389097597863937)
     | > postnet_loss: 0.3137156069278717  (0.3141232166025374)
     | > stopnet_loss: 0.006771339103579521  (0.008331149816513062)
     | > loss: 0.19929812848567963  (0.20033469630612266)
     | > align_error: 0.5938749313354492  (0.6278892093234592)

   --> STEP: 10
     | > decoder_loss: 0.48513516783714294  (0.45701539516448975)
     | > postnet_loss: 0.32848960161209106  (0.3155598551034927)
     | > stopnet_loss: 0.005657759495079517  (0.008063810784369707)
     | > loss: 0.20906394720077515  (0.20120762139558793)
     | > align_error: 0.5868925452232361  (0.6237895429134369)

   --> STEP: 11
     | > decoder_loss: 0.47090864181518555  (0.4582784175872803)
     | > postnet_loss: 0.32064107060432434  (0.31602178378538653)
     | > stopnet_loss: 0.006021040957421064  (0.007878104436465284)
     | > loss: 0.20390845835208893  (0.2014531520279971)
     | > align_error: 0.5957657694816589  (0.6212419271469116)

   --> STEP: 12
     | > decoder_loss: 0.46452221274375916  (0.45879873385032016)
     | > postnet_loss: 0.312112957239151  (0.3156960482398669)
     | > stopnet_loss: 0.00796553399413824  (0.00788539023293803)
     | > loss: 0.20212432742118835  (0.20150908331076303)
     | > align_error: 0.5894269347190857  (0.6185906777779261)

   --> STEP: 13
     | > decoder_loss: 0.45701587200164795  (0.45866159063119155)
     | > postnet_loss: 0.31354206800460815  (0.3155303574525393)
     | > stopnet_loss: 0.005736385006457567  (0.00772008213859338)
     | > loss: 0.19837586581707  (0.20126806658047897)
     | > align_error: 0.5877106189727783  (0.6162152886390686)

   --> STEP: 14
     | > decoder_loss: 0.46196886897087097  (0.4588978247983115)
     | > postnet_loss: 0.3125638961791992  (0.3153184673615864)
     | > stopnet_loss: 0.0051225521601736546  (0.007534544282991972)
     | > loss: 0.19875575602054596  (0.20108861582619802)
     | > align_error: 0.5557467639446259  (0.6118961083037513)

   --> STEP: 15
     | > decoder_loss: 0.46519580483436584  (0.45931769013404844)
     | > postnet_loss: 0.31801167130470276  (0.3154980142911275)
     | > stopnet_loss: 0.005101366434246302  (0.007372332426408927)
     | > loss: 0.20090323686599731  (0.2010762572288513)
     | > align_error: 0.5897238254547119  (0.6104179561138153)

   --> STEP: 16
     | > decoder_loss: 0.46446818113327026  (0.4596395958214998)
     | > postnet_loss: 0.30990874767303467  (0.3151486851274967)
     | > stopnet_loss: 0.005291409324854612  (0.007242274732561782)
     | > loss: 0.19888563454151154  (0.20093934331089258)
     | > align_error: 0.607729434967041  (0.6102499235421419)

   --> STEP: 17
     | > decoder_loss: 0.47196805477142334  (0.46036479928914237)
     | > postnet_loss: 0.32017746567726135  (0.3154444957480711)
     | > stopnet_loss: 0.004977328237146139  (0.007109042585772627)
     | > loss: 0.20301370322704315  (0.20106136448243084)
     | > align_error: 0.5597223043441772  (0.607277710648144)

   --> STEP: 18
     | > decoder_loss: 0.4682615101337433  (0.46080350544717574)
     | > postnet_loss: 0.3131375014781952  (0.3153163293997447)
     | > stopnet_loss: 0.005496420431882143  (0.007019452466112044)
     | > loss: 0.20084618031978607  (0.20104940980672836)
     | > align_error: 0.6049222946166992  (0.6071468542019526)

   --> STEP: 19
     | > decoder_loss: 0.46661368012428284  (0.46110930411439194)
     | > postnet_loss: 0.312237948179245  (0.31515430933550787)
     | > stopnet_loss: 0.005080989561975002  (0.00691742810273641)
     | > loss: 0.19979389011859894  (0.2009833298231426)
     | > align_error: 0.6017918884754181  (0.606865013900556)

   --> STEP: 20
     | > decoder_loss: 0.46103954315185547  (0.4611058160662651)
     | > postnet_loss: 0.309313029050827  (0.3148622453212738)
     | > stopnet_loss: 0.004659657366573811  (0.00680453956592828)
     | > loss: 0.19724780321121216  (0.20079655349254608)
     | > align_error: 0.6234796643257141  (0.607695746421814)

   --> STEP: 21
     | > decoder_loss: 0.4584883749485016  (0.4609811760130383)
     | > postnet_loss: 0.3063400387763977  (0.31445642596199397)
     | > stopnet_loss: 0.004137501586228609  (0.0066775377573711535)
     | > loss: 0.19534461200237274  (0.20053693723110927)
     | > align_error: 0.5614587366580963  (0.6054939840521131)

   --> STEP: 22
     | > decoder_loss: 0.46070337295532227  (0.4609685486013239)
     | > postnet_loss: 0.30990538001060486  (0.31424956023693085)
     | > stopnet_loss: 0.005047748330980539  (0.006603456419807943)
     | > loss: 0.19769994914531708  (0.20040798322720962)
     | > align_error: 0.6264148950576782  (0.606444934552366)

   --> STEP: 23
     | > decoder_loss: 0.43269744515419006  (0.459739370190579)
     | > postnet_loss: 0.2986800968647003  (0.31357262704683386)
     | > stopnet_loss: 0.004689375404268503  (0.006520235506088838)
     | > loss: 0.18753376603126526  (0.1998482346534729)
     | > align_error: 0.5676368176937103  (0.6047576251237288)

   --> STEP: 24
     | > decoder_loss: 0.46758320927619934  (0.46006619681914646)
     | > postnet_loss: 0.31379520893096924  (0.3135819012920062)
     | > stopnet_loss: 0.0045411051250994205  (0.006437771740214278)
     | > loss: 0.19988569617271423  (0.19984979555010796)
     | > align_error: 0.5807627141475677  (0.6037578371663888)

   --> STEP: 25
     | > decoder_loss: 0.4683586359024048  (0.4603978943824768)
     | > postnet_loss: 0.3113277852535248  (0.3134917366504669)
     | > stopnet_loss: 0.003836787538602948  (0.006333732372149825)
     | > loss: 0.19875839352607727  (0.19980613946914672)
     | > align_error: 0.559771329164505  (0.6019983768463134)

   --> STEP: 26
     | > decoder_loss: 0.4418933391571045  (0.4596861807199625)
     | > postnet_loss: 0.29900234937667847  (0.312934452524552)
     | > stopnet_loss: 0.004578729160130024  (0.006266232248610602)
     | > loss: 0.1898026466369629  (0.19942138974483198)
     | > align_error: 0.5485166907310486  (0.5999413889188032)

   --> STEP: 27
     | > decoder_loss: 0.4384303092956543  (0.4588989262227659)
     | > postnet_loss: 0.2953263223171234  (0.31228229955390646)
     | > stopnet_loss: 0.004054660443216562  (0.006184322181744156)
     | > loss: 0.18749383091926575  (0.19897962830684804)
     | > align_error: 0.5424749255180359  (0.5978130013854416)

   --> STEP: 28
     | > decoder_loss: 0.44436752796173096  (0.4583799477134432)
     | > postnet_loss: 0.29909420013427734  (0.31181129600320545)
     | > stopnet_loss: 0.004049323499202728  (0.0061080722287962476)
     | > loss: 0.1899147629737854  (0.19865588311638152)
     | > align_error: 0.5670059323310852  (0.5967127489192146)

   --> STEP: 29
     | > decoder_loss: 0.4398963749408722  (0.4577425831350787)
     | > postnet_loss: 0.29498788714408875  (0.31123117845633935)
     | > stopnet_loss: 0.0036974733229726553  (0.006024948128595434)
     | > loss: 0.18741853535175323  (0.1982683883658771)
     | > align_error: 0.5414703786373138  (0.594807839599149)

   --> STEP: 30
     | > decoder_loss: 0.4402257800102234  (0.4571586896975835)
     | > postnet_loss: 0.2961489260196686  (0.3107284367084503)
     | > stopnet_loss: 0.003067366313189268  (0.005926362068081895)
     | > loss: 0.18716104328632355  (0.19789814352989196)
     | > align_error: 0.5346875786781311  (0.5928038309017817)

   --> STEP: 31
     | > decoder_loss: 0.4387813210487366  (0.45656587135407234)
     | > postnet_loss: 0.2973710298538208  (0.3102975526163655)
     | > stopnet_loss: 0.004081531893461943  (0.005866851417287704)
     | > loss: 0.18811962008476257  (0.19758270728972652)
     | > align_error: 0.5605137050151825  (0.5917622139376979)

   --> STEP: 32
     | > decoder_loss: 0.4467305839061737  (0.4562585186213255)
     | > postnet_loss: 0.30085262656211853  (0.3100023986771703)
     | > stopnet_loss: 0.004004437010735273  (0.00580865096708294)
     | > loss: 0.19090023636817932  (0.19737388007342815)
     | > align_error: 0.5321172177791595  (0.5898983078077435)

   --> STEP: 33
     | > decoder_loss: 0.44377806782722473  (0.45588032314271637)
     | > postnet_loss: 0.2990868389606476  (0.30967162414030597)
     | > stopnet_loss: 0.004193167667835951  (0.005759696927711819)
     | > loss: 0.18990939855575562  (0.19714768366380173)
     | > align_error: 0.546554684638977  (0.5885848646814172)

   --> STEP: 34
     | > decoder_loss: 0.4499633014202118  (0.45570629309205446)
     | > postnet_loss: 0.3012297749519348  (0.30942333445829506)
     | > stopnet_loss: 0.0034742262214422226  (0.005692477201056831)
     | > loss: 0.19127248227596283  (0.19697488362298293)
     | > align_error: 0.5640362501144409  (0.587862846605918)

   --> STEP: 35
     | > decoder_loss: 0.44785746932029724  (0.45548204098428996)
     | > postnet_loss: 0.29995036125183105  (0.30915267808096747)
     | > stopnet_loss: 0.0036469637416303158  (0.005634033959358931)
     | > loss: 0.19059893488883972  (0.19679271365915027)
     | > align_error: 0.5346291661262512  (0.5863418843064989)

   --> STEP: 36
     | > decoder_loss: 0.45378929376602173  (0.45543502022822696)
     | > postnet_loss: 0.3037780225276947  (0.3090033820933766)
     | > stopnet_loss: 0.0038245071191340685  (0.00558376932490824)
     | > loss: 0.19321632385253906  (0.1966933694978555)
     | > align_error: 0.6344801485538483  (0.5876790583133698)

   --> STEP: 37
     | > decoder_loss: 0.4462159276008606  (0.4551858555626225)
     | > postnet_loss: 0.3009147644042969  (0.3087847708044825)
     | > stopnet_loss: 0.003683104645460844  (0.005532400009247499)
     | > loss: 0.1904657781124115  (0.19652505621716782)
     | > align_error: 0.5197287797927856  (0.5858425642992999)

   --> STEP: 38
     | > decoder_loss: 0.43498727679252625  (0.454654314016041)
     | > postnet_loss: 0.2942807972431183  (0.3084030872897098)
     | > stopnet_loss: 0.00326701533049345  (0.005472784622964498)
     | > loss: 0.18558403849601746  (0.19623713469819015)
     | > align_error: 0.5516002178192139  (0.584941449918245)

   --> STEP: 39
     | > decoder_loss: 0.448498398065567  (0.4544964700173109)
     | > postnet_loss: 0.3029639422893524  (0.3082636220332904)
     | > stopnet_loss: 0.0035964648704975843  (0.005424673860080731)
     | > loss: 0.19146205484867096  (0.19611469675333068)
     | > align_error: 0.5467278361320496  (0.5839616136673169)

   --> STEP: 40
     | > decoder_loss: 0.44544023275375366  (0.45427006408572196)
     | > postnet_loss: 0.30139848589897156  (0.3080919936299324)
     | > stopnet_loss: 0.0031574771273881197  (0.005367993941763416)
     | > loss: 0.18986715376377106  (0.19595850817859167)
     | > align_error: 0.5847106277942657  (0.5839803390204906)

   --> STEP: 41
     | > decoder_loss: 0.43593311309814453  (0.4538228213787079)
     | > postnet_loss: 0.293741911649704  (0.30774199163041466)
     | > stopnet_loss: 0.003809703281149268  (0.005329986852480144)
     | > loss: 0.18622846901416779  (0.1957211901501911)
     | > align_error: 0.5044073760509491  (0.5820395350456238)

   --> STEP: 42
     | > decoder_loss: 0.4414880573749542  (0.45352913652147564)
     | > postnet_loss: 0.29697108268737793  (0.3074855414174852)
     | > stopnet_loss: 0.003379598492756486  (0.0052835490343914856)
     | > loss: 0.18799437582492828  (0.195537218380542)
     | > align_error: 0.5802299976348877  (0.5819964508215586)

   --> STEP: 43
     | > decoder_loss: 0.4393892288208008  (0.45320030145866924)
     | > postnet_loss: 0.29563194513320923  (0.3072098763876183)
     | > stopnet_loss: 0.0030618782620877028  (0.005231882272244886)
     | > loss: 0.18681716918945312  (0.19533442653888874)
     | > align_error: 0.5521470010280609  (0.5813022775705471)

   --> STEP: 44
     | > decoder_loss: 0.45758312940597534  (0.4532999111847444)
     | > postnet_loss: 0.30512043833732605  (0.3071623891592026)
     | > stopnet_loss: 0.002795751905068755  (0.005176515672990883)
     | > loss: 0.19347164034843445  (0.1952920904891057)
     | > align_error: 0.5515880286693573  (0.5806269537318837)

   --> STEP: 45
     | > decoder_loss: 0.45009177923202515  (0.45322861936357284)
     | > postnet_loss: 0.30401021242141724  (0.3070923407872518)
     | > stopnet_loss: 0.0034385507460683584  (0.005137894230170382)
     | > loss: 0.1919640451669693  (0.19521813392639156)
     | > align_error: 0.5531802475452423  (0.580017026927736)

   --> STEP: 46
     | > decoder_loss: 0.4411366879940033  (0.45296575129032135)
     | > postnet_loss: 0.2954770624637604  (0.3068398347367411)
     | > stopnet_loss: 0.003317715600132942  (0.005098325129517395)
     | > loss: 0.1874711513519287  (0.19504972126172931)

warning: audio amplitude out of range, auto clipped.

   --> TIME: 2025-12-28 10:45:36 -- STEP: 131/150 -- GLOBAL_STEP: 14325
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48963087797164917  (0.48607683068013374)
     | > postnet_loss: 0.3979906141757965  (0.4021621644496918)
     | > stopnet_loss: 0.0032721508760005236  (0.005218185928742622)
     | > loss: 0.22517752647399902  (0.2272779350062363)
     | > align_error: 0.5911178290843964  (0.6261784643617295)
     | > grad_norm: tensor(0.1234, device='cuda:0')  (tensor(0.2143, device='cuda:0'))
     | > step_time: 1.076  (1.3464740159857373)
     | > loader_time: 1.6887  (1.2902737319014455)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46512237191200256  (0.46512237191200256)
     | > postnet_loss: 0.33561331033706665  (0.33561331033706665)
     | > stopnet_loss: 0.012265474535524845  (0.012265474535524845)
     | > loss: 0.21244940161705017  (0.21244940161705017)
     | > align_error: 0.7189765572547913  (0.7189765572547913)

   --> STEP: 1
     | > decoder_loss: 0.4460633099079132  (0.4460633099079132)
     | > postnet_loss: 0.3237173557281494  (0.3237173557281494)
     | > stopnet_loss: 0.009654456749558449  (0.009654456749558449)
     | > loss: 0.20209962129592896  (0.20209962129592896)
     | > align_error: 0.6599473655223846  (0.6599473655223846)

   --> STEP: 2
     | > decoder_loss: 0.4410794675350189  (0.44357138872146606)
     | > postnet_loss: 0.31364238262176514  (0.3186798691749573)
     | > stopnet_loss: 0.011034278199076653  (0.01034436747431755)
     | > loss: 0.1997147500514984  (0.20090718567371368)
     | > align_error: 0.6563658714294434  (0.658156618475914)

   --> STEP: 3
     | > decoder_loss: 0.4444538652896881  (0.4438655475775401)
     | > postnet_loss: 0.31256261467933655  (0.3166407843430837)
     | > stopnet_loss: 0.00837698020040989  (0.00968857171634833)
     | > loss: 0.1976311057806015  (0.1998151590426763)
     | > align_error: 0.7347409725189209  (0.6836847364902496)

   --> STEP: 4
     | > decoder_loss: 0.45210954546928406  (0.4459265470504761)
     | > postnet_loss: 0.3224252164363861  (0.3180868923664093)
     | > stopnet_loss: 0.008233514614403248  (0.00932480744086206)
     | > loss: 0.2018672078847885  (0.20032817125320435)
     | > align_error: 0.6042131781578064  (0.6638168469071388)

   --> STEP: 5
     | > decoder_loss: 0.4312714636325836  (0.4429955303668976)
     | > postnet_loss: 0.30329734086990356  (0.31512898206710815)
     | > stopnet_loss: 0.008199164643883705  (0.00909967888146639)
     | > loss: 0.19184137880802155  (0.19863081276416777)
     | > align_error: 0.6424192786216736  (0.6595373332500458)

   --> STEP: 6
     | > decoder_loss: 0.44936612248420715  (0.44405729571978253)
     | > postnet_loss: 0.316202849149704  (0.31530795991420746)
     | > stopnet_loss: 0.007257731631398201  (0.00879268767312169)
     | > loss: 0.19864997267723083  (0.19863400608301163)
     | > align_error: 0.5947668850421906  (0.6487422585487366)

   --> STEP: 7
     | > decoder_loss: 0.45872029662132263  (0.44615201013428823)
     | > postnet_loss: 0.3142724335193634  (0.3151600275720869)
     | > stopnet_loss: 0.006350717972964048  (0.008443834858813457)
     | > loss: 0.19959889352321625  (0.198771847145898)
     | > align_error: 0.5797230899333954  (0.6388823773179736)

   --> STEP: 8
     | > decoder_loss: 0.4533396363258362  (0.44705046340823174)
     | > postnet_loss: 0.315311461687088  (0.315178956836462)
     | > stopnet_loss: 0.0075095901265740395  (0.008327054267283529)
     | > loss: 0.1996723711490631  (0.19888441264629364)
     | > align_error: 0.5767152905464172  (0.631111491471529)

   --> STEP: 9
     | > decoder_loss: 0.4516778588294983  (0.44756461845503914)
     | > postnet_loss: 0.31511300802230835  (0.31517162919044495)
     | > stopnet_loss: 0.006709866691380739  (0.008147366758849885)
     | > loss: 0.1984075903892517  (0.1988314323955112)
     | > align_error: 0.5927501916885376  (0.6268491248289744)

   --> STEP: 10
     | > decoder_loss: 0.479095458984375  (0.4507177025079727)
     | > postnet_loss: 0.33074745535850525  (0.316729211807251)
     | > stopnet_loss: 0.005627689883112907  (0.007895399071276187)
     | > loss: 0.20808842778205872  (0.19975713193416594)
     | > align_error: 0.5849628150463104  (0.622660493850708)

   --> STEP: 11
     | > decoder_loss: 0.46482643485069275  (0.4520003145391291)
     | > postnet_loss: 0.3202155828475952  (0.31704615462910046)
     | > stopnet_loss: 0.005853794049471617  (0.0077097986147485)
     | > loss: 0.2021142989397049  (0.1999714198437604)
     | > align_error: 0.5954061150550842  (0.6201828230511058)

   --> STEP: 12
     | > decoder_loss: 0.4554431736469269  (0.4522872194647789)
     | > postnet_loss: 0.3112034201622009  (0.31655926009019214)
     | > stopnet_loss: 0.007598742842674255  (0.007700543967075646)
     | > loss: 0.1992603987455368  (0.1999121680855751)
     | > align_error: 0.5856439471244812  (0.6173045833905538)

   --> STEP: 13
     | > decoder_loss: 0.44970762729644775  (0.4520887892979842)
     | > postnet_loss: 0.31329068541526794  (0.31630783126904416)
     | > stopnet_loss: 0.005650109611451626  (0.00754281824741226)
     | > loss: 0.19639968872070312  (0.19964197736520034)
     | > align_error: 0.5870168805122375  (0.6149747600922217)

   --> STEP: 14
     | > decoder_loss: 0.45620468258857727  (0.4523827816758837)
     | > postnet_loss: 0.31348052620887756  (0.31610588090760366)
     | > stopnet_loss: 0.004975857678800821  (0.0073594639210828715)
     | > loss: 0.1973971575498581  (0.1994816330926759)
     | > align_error: 0.5553436875343323  (0.6107153977666583)

   --> STEP: 15
     | > decoder_loss: 0.4576340317726135  (0.4527328650156657)
     | > postnet_loss: 0.31558170914649963  (0.31607093612353004)
     | > stopnet_loss: 0.0050102113746106625  (0.007202847084651391)
     | > loss: 0.19831416010856628  (0.1994038015604019)
     | > align_error: 0.5892527103424072  (0.6092845519383748)

   --> STEP: 16
     | > decoder_loss: 0.45906078815460205  (0.4531283602118492)
     | > postnet_loss: 0.3093481659889221  (0.3156507629901171)
     | > stopnet_loss: 0.005254559218883514  (0.0070810790930408984)
     | > loss: 0.19735679030418396  (0.1992758633568883)
     | > align_error: 0.6073243618011475  (0.6091620400547981)

   --> STEP: 17
     | > decoder_loss: 0.4654691517353058  (0.4538542891249937)
     | > postnet_loss: 0.3177957832813263  (0.31577694065430584)
     | > stopnet_loss: 0.004855085629969835  (0.0069501383010955415)
     | > loss: 0.20067131519317627  (0.19935794875902288)
     | > align_error: 0.5598244071006775  (0.6062598263516146)

   --> STEP: 18
     | > decoder_loss: 0.4597555696964264  (0.45418213804562885)
     | > postnet_loss: 0.31048956513404846  (0.3154831975698471)
     | > stopnet_loss: 0.0052822912111878395  (0.006857480129434003)
     | > loss: 0.19784358143806458  (0.19927381724119186)
     | > align_error: 0.6052155494689941  (0.6062018109692467)

   --> STEP: 19
     | > decoder_loss: 0.45584699511528015  (0.4542697621019263)
     | > postnet_loss: 0.3088720142841339  (0.31513524055480957)
     | > stopnet_loss: 0.004779719281941652  (0.006748124295355458)
     | > loss: 0.19595947861671448  (0.19909937836621938)
     | > align_error: 0.600859522819519  (0.6059206379087347)

   --> STEP: 20
     | > decoder_loss: 0.4542701542377472  (0.45426978170871735)
     | > postnet_loss: 0.3065031170845032  (0.31470363438129423)
     | > stopnet_loss: 0.0044997138902544975  (0.00663570377510041)
     | > loss: 0.19469304382801056  (0.19887906163930893)
     | > align_error: 0.6240834593772888  (0.6068287789821625)

   --> STEP: 21
     | > decoder_loss: 0.45172739028930664  (0.45414871545065016)
     | > postnet_loss: 0.305681437253952  (0.3142740059466589)
     | > stopnet_loss: 0.003990562632679939  (0.006509744673080388)
     | > loss: 0.19334277510643005  (0.19861542894726708)
     | > align_error: 0.5618079900741577  (0.6046849318913051)

   --> STEP: 22
     | > decoder_loss: 0.45172715187072754  (0.4540386443788355)
     | > postnet_loss: 0.30763518810272217  (0.3139722414992072)
     | > stopnet_loss: 0.004614069126546383  (0.006423577602783387)
     | > loss: 0.19445465505123138  (0.19842630286108365)
     | > align_error: 0.6257325410842896  (0.6056416414000771)

   --> STEP: 23
     | > decoder_loss: 0.4260638654232025  (0.4528223496416341)
     | > postnet_loss: 0.29618117213249207  (0.3131987167441327)
     | > stopnet_loss: 0.0045494195073843  (0.006342092468200818)
     | > loss: 0.1851106733083725  (0.19784736244574838)
     | > align_error: 0.5688051879405975  (0.6040400564670563)

   --> STEP: 24
     | > decoder_loss: 0.460265189409256  (0.453132467965285)
     | > postnet_loss: 0.3111807107925415  (0.3131146331628164)
     | > stopnet_loss: 0.0044175926595926285  (0.006261904976175477)
     | > loss: 0.19727906584739685  (0.19782368342081705)
     | > align_error: 0.5812155604362488  (0.603089035799106)

   --> STEP: 25
     | > decoder_loss: 0.45851972699165344  (0.45334795832633973)
     | > postnet_loss: 0.30797120928764343  (0.3129088962078095)
     | > stopnet_loss: 0.0037074231076985598  (0.006159725701436401)
     | > loss: 0.1953301578760147  (0.19772394239902497)
     | > align_error: 0.559441089630127  (0.6013431179523469)

   --> STEP: 26
     | > decoder_loss: 0.43519672751426697  (0.4526498340643369)
     | > postnet_loss: 0.29805517196655273  (0.31233759912160725)
     | > stopnet_loss: 0.00440125772729516  (0.006092092317815583)
     | > loss: 0.18771423399448395  (0.19733895361423492)
     | > align_error: 0.5485727488994598  (0.5993134883733897)

   --> STEP: 27
     | > decoder_loss: 0.4306001365184784  (0.4518331785996755)
     | > postnet_loss: 0.2918895184993744  (0.3115802628022653)
     | > stopnet_loss: 0.0036468133330345154  (0.006001526429490359)
     | > loss: 0.18426921963691711  (0.19685488939285278)
     | > align_error: 0.5417623519897461  (0.5971819648036252)

   --> STEP: 28
     | > decoder_loss: 0.43755513429641724  (0.4513232484459877)
     | > postnet_loss: 0.29726749658584595  (0.31106909258025034)
     | > stopnet_loss: 0.003926536533981562  (0.005927419647507902)
     | > loss: 0.18763218820095062  (0.1965255072074277)
     | > align_error: 0.5681061446666718  (0.5961435426558769)

   --> STEP: 29
     | > decoder_loss: 0.4333028495311737  (0.45070185537995966)
     | > postnet_loss: 0.294423371553421  (0.31049510220001486)
     | > stopnet_loss: 0.00359435030259192  (0.005846968980441834)
     | > loss: 0.18552590906620026  (0.19614621071979918)
     | > align_error: 0.5421301126480103  (0.5942810105866401)

   --> STEP: 30
     | > decoder_loss: 0.4331972301006317  (0.4501183678706487)
     | > postnet_loss: 0.2946151793003082  (0.3099657714366913)
     | > stopnet_loss: 0.0028688693419098854  (0.005747698992490768)
     | > loss: 0.1848219782114029  (0.19576873630285263)
     | > align_error: 0.5351093411445618  (0.5923086216052375)

   --> STEP: 31
     | > decoder_loss: 0.42611750960350037  (0.4493441466362246)
     | > postnet_loss: 0.29173707962036133  (0.30937774912003546)
     | > stopnet_loss: 0.003713153535500169  (0.005682068493878169)
     | > loss: 0.18317681550979614  (0.19536254530952823)
     | > align_error: 0.5566795468330383  (0.5911592966125858)

   --> STEP: 32
     | > decoder_loss: 0.4341471791267395  (0.44886924140155315)
     | > postnet_loss: 0.29654642939567566  (0.30897677037864923)
     | > stopnet_loss: 0.003655647858977318  (0.005618742849037517)
     | > loss: 0.18632903695106506  (0.19508024817332625)
     | > align_error: 0.5290386974811554  (0.5892180278897287)

   --> STEP: 33
     | > decoder_loss: 0.4378946125507355  (0.4485366768909223)
     | > postnet_loss: 0.2968854010105133  (0.3086103652462815)
     | > stopnet_loss: 0.004032279830425978  (0.005570668212109895)
     | > loss: 0.18772728741168976  (0.19485743118054938)
     | > align_error: 0.5480775237083435  (0.5879713459448382)

   --> STEP: 34
     | > decoder_loss: 0.4436604082584381  (0.448393257225261)
     | > postnet_loss: 0.29836341738700867  (0.3083089844268911)
     | > stopnet_loss: 0.003331535728648305  (0.005504811374361024)
     | > loss: 0.18883749842643738  (0.1946803743348402)
     | > align_error: 0.5655636191368103  (0.5873122951563667)

   --> STEP: 35
     | > decoder_loss: 0.4419703781604767  (0.4482097463948386)
     | > postnet_loss: 0.2984119653701782  (0.30802621245384215)
     | > stopnet_loss: 0.0035343642812222242  (0.00544851288598563)
     | > loss: 0.18862994015216827  (0.19450750478676387)
     | > align_error: 0.5353698134422302  (0.5858282242502485)

   --> STEP: 36
     | > decoder_loss: 0.44645047187805176  (0.4481608776582612)
     | > postnet_loss: 0.30164486169815063  (0.3078489527106285)
     | > stopnet_loss: 0.003683609887957573  (0.005399487802707073)
     | > loss: 0.19070744514465332  (0.19440194757448304)
     | > align_error: 0.6355915665626526  (0.587210539314482)

   --> STEP: 37
     | > decoder_loss: 0.43960803747177124  (0.4479297198153831)
     | > postnet_loss: 0.2988201379776001  (0.30760493069081696)
     | > stopnet_loss: 0.0035988662857562304  (0.0053508223563029965)
     | > loss: 0.18820591270923615  (0.1942344871727196)
     | > align_error: 0.5209375023841858  (0.5854193761542037)

   --> STEP: 38
     | > decoder_loss: 0.42736995220184326  (0.4473886732992373)
     | > postnet_loss: 0.29179540276527405  (0.30718889048225007)
     | > stopnet_loss: 0.003163412678986788  (0.005293258943742044)
     | > loss: 0.18295474350452423  (0.19393765181303024)
     | > align_error: 0.5535817444324493  (0.5845815437404733)

   --> STEP: 39
     | > decoder_loss: 0.4421273469924927  (0.44725376749650025)
     | > postnet_loss: 0.301726371049881  (0.3070488258814201)
     | > stopnet_loss: 0.0034968822728842497  (0.005247198003463639)
     | > loss: 0.18946030735969543  (0.19382284810909858)
     | > align_error: 0.5477921664714813  (0.5836382263746017)

   --> STEP: 40
     | > decoder_loss: 0.4396257698535919  (0.4470630675554276)
     | > postnet_loss: 0.3006018102169037  (0.30688765048980715)
     | > stopnet_loss: 0.003053667489439249  (0.005192359740613029)
     | > loss: 0.1881105601787567  (0.19368004091084004)
     | > align_error: 0.5857396125793457  (0.5836907610297203)

   --> STEP: 41
     | > decoder_loss: 0.4296582341194153  (0.44663855942284186)
     | > postnet_loss: 0.2924415171146393  (0.3065353057733396)
     | > stopnet_loss: 0.003740769810974598  (0.005156955108182823)
     | > loss: 0.18426571786403656  (0.19345042327555215)
     | > align_error: 0.5050437748432159  (0.5817725418544397)

   --> STEP: 42
     | > decoder_loss: 0.4349662959575653  (0.44636064838795436)
     | > postnet_loss: 0.29477259516716003  (0.30625524123509723)
     | > stopnet_loss: 0.003328504506498575  (0.0051134205700474845)
     | > loss: 0.18576322495937347  (0.19326739474421456)
     | > align_error: 0.5814019441604614  (0.5817637180998212)

   --> STEP: 43
     | > decoder_loss: 0.43310922384262085  (0.4460524757241094)
     | > postnet_loss: 0.2933381199836731  (0.3059548430664595)
     | > stopnet_loss: 0.002957441145554185  (0.005063281513663919)
     | > loss: 0.18456928431987762  (0.19306511310643928)
     | > align_error: 0.5532779693603516  (0.5811012588268103)

   --> STEP: 44
     | > decoder_loss: 0.4517083168029785  (0.44618101756681094)
     | > postnet_loss: 0.30416834354400635  (0.30591424080458557)
     | > stopnet_loss: 0.0027080692816525698  (0.005009753962936388)
     | > loss: 0.19167722761631012  (0.19303357025439088)
     | > align_error: 0.5531719923019409  (0.5804665027694269)

   --> STEP: 45
     | > decoder_loss: 0.44413521885871887  (0.4461355553732978)
     | > postnet_loss: 0.30257707834243774  (0.3058400816387601)
     | > stopnet_loss: 0.003309881780296564  (0.004971979025544393)
     | > loss: 0.18998795747756958  (0.19296588997046152)
     | > align_error: 0.5544255971908569  (0.579887815978792)

   --> STEP: 46
     | > decoder_loss: 0.4353587329387665  (0.445901276624721)
     | > postnet_loss: 0.29466497898101807  (0.30559714462446136)
     | > stopnet_loss: 0.0032025589607656  (0.0049335133719622445)
     | > loss: 0.18570849299430847  (0.19280812047097995)
     | > align_error: 0.5348808467388153  (0.57890940360401)

   --> STEP: 47
     | > decoder_loss: 0.4334821403026581  (0.44563703968169843)
     | > postnet_loss: 0.296835333108902  (0.3054107231028537)
     | > stopnet_loss: 0.003939450718462467  (0.0049123631027388455)
     | > loss: 0.1865188181400299  (0.19267430552776824)
     | > align_error: 0.5690293312072754  (0.5786991892976965)

   --> STEP: 48
     | > decoder_loss: 0.4319300055503845  (0.4453514764706294)
     | > postnet_loss: 0.29410988092422485  (0.305175288890799)
     | > stopnet_loss: 0.0033151349052786827  (0.004879087515291759)
     | > loss: 0.1848251074552536  (0.19251078056792417)
     | > align_error: 0.5430891215801239  (0.5779573128869137)

   --> STEP: 49
     | > decoder_loss: 0.4244450032711029  (0.44492481375227166)
     | > postnet_loss: 0.28996458649635315  (0.3048648663929531)
     | > stopnet_loss: 0.0030633360147476196  (0.00484203136221943)
     | > loss: 0.18166573345661163  (0.19228945307585657)
     | > align_error: 0.5741854906082153  (0.5778803369220422)

   --> STEP: 50
     | > decoder_loss: 0.43755248188972473  (0.44477736711502075)
     | > postnet_loss: 0.2978799343109131  (0.3047251677513123)
     | > stopnet_loss: 0.003259358461946249  (0.004810377904213966)
     | > loss: 0.18711745738983154  (0.19218601316213607)
     | > align_error: 0.557059645652771  (0.5774639230966568)

   --> STEP: 51
     | > decoder_loss: 0.44917452335357666  (0.44486358586479635)
     | > postnet_loss: 0.30456528067588806  (0.3047220327106177)
     | > stopnet_loss: 0.002717384835705161  (0.004769338824439284)
     | > loss: 0.19115234911441803  (0.1921657452396318)
     | > align_error: 0.5295712649822235  (0.5765248513689228)

   --> STEP: 52
     | > decoder_loss: 0.4292691946029663  (0.44456369372514576)
     | > postnet_loss: 0.292644739151001  (0.30448977706524044)
     | > stopnet_loss: 0.003715133760124445  (0.004749065650125537)
     | > loss: 0.18419361114501953  (0.19201243496858156)
     | > align_error: 0.5245646238327026  (0.5755256162239955)

   --> STEP: 53
     | > decoder_loss: 0.4246823787689209  (0.4441885745750283)
     | > postnet_loss: 0.2913844883441925  (0.3042425074667301)
     | > stopnet_loss: 0.003943321760743856  (0.0047338629352315425)
     | > loss: 0.18296003341674805  (0.19184163493930168)
     | > align_error: 0.5375640988349915  (0.5748093611789199)

   --> STEP: 54
     | > decoder_loss: 0.43539682030677795  (0.4440257643108015)
     | > postnet_loss: 0.29197821021080017  (0.30401539085087953)
     | > stopnet_loss: 0.00267471419647336  (0.004695730551180465)
     | > loss: 0.1845184713602066  (0.19170602079894808)
     | > align_error: 0.561873197555542  (0.5745698025933018)

   --> STEP: 55
     | > decoder_loss: 0.4258366525173187  (0.4436950531872836)
     | > postnet_loss: 0.29253894090652466  (0.3038067281246185)
     | > stopnet_loss: 0.0030725731048732996  (0.004666218597611244)
     | > loss: 0.18266646564006805  (0.19154166525060481)
     | > align_error: 0.5846319794654846  (0.5747527512637052)

   --> STEP: 56
     | > decoder_loss: 0.43794721364974976  (0.44359241319554193)
     | > postnet_loss: 0.2998666763305664  (0.3037363700568676)
     | > stopnet_loss: 0.003144612070173025  (0.004639047052478419)
     | > loss: 0.1875980794429779  (0.19147124407546862)
     | > align_error: 0.5408444404602051  (0.5741472457136426)

   --> STEP: 57
     | > decoder_loss: 0.4182294011116028  (0.4431474480712623)
     | > postnet_loss: 0.287611722946167  (0.3034534815110658)
     | > stopnet_loss: 0.0032022662926465273  (0.004613840372481368)
     | > loss: 0.1796625405550003  (0.1912640738382674)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3698738488284024 (+0.009195775696725528)
     | > avg_decoder_loss: 0.44193411505583563 (-0.0007636619336677253)
     | > avg_postnet_loss: 0.3025976144003146 (+0.0010255218455286208)
     | > avg_stopnet_loss: 0.004375591676569347 (-5.5268590310305656e-05)
     | > avg_loss: 0.19050852547992358 (+1.0198715961334814e-05)
     | > avg_align_error: 0.5730950164072441 (+0.002416972409595153)


 > EPOCH: 95/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 10:49:02)

   --> TIME: 2025-12-28 10:49:09 -- STEP: 5/150 -- GLOBAL_STEP: 14350
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4775397777557373  (0.4695730686187744)
     | > postnet_loss: 0.40689271688461304  (0.40412179231643675)
     | > stopnet_loss: 0.012902778573334217  (0.014193731546401977)
     | > loss: 0.23401090502738953  (0.23261744976043702)
     | > align_error: 0.7282097339630127  (0.7136074602603912)
     | > grad_norm: tensor(0.3777, device='cuda:0')  (tensor(0.2849, device='cuda:0'))
     | > step_time: 0.5833  (0.48797154426574707)
     | > loader_time: 0.6722  (0.6541562557220459)


   --> TIME: 2025-12-28 10:49:52 -- STEP: 30/150 -- GLOBAL_STEP: 14375
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.47905629873275757  (0.4755537360906601)
     | > postnet_loss: 0.39987805485725403  (0.40286205112934115)
     | > stopnet_loss: 0.005891242530196905  (0.009109534618134298)
     | > loss: 0.22562484443187714  (0.22871348162492117)
     | > align_error: 0.6122608780860901  (0.6669934590657552)
     | > grad_norm: tensor(0.1842, device='cuda:0')  (tensor(0.3099, device='cuda:0'))
     | > step_time: 0.9497  (0.7435418446858724)
     | > loader_time: 1.0578  (0.86955726146698)


   --> TIME: 2025-12-28 10:50:53 -- STEP: 55/150 -- GLOBAL_STEP: 14400
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48972779512405396  (0.48151290308345446)
     | > postnet_loss: 0.4021955728530884  (0.40394910357215186)
     | > stopnet_loss: 0.0041689760982990265  (0.007292842356996103)
     | > loss: 0.2271498143672943  (0.228658343445171)
     | > align_error: 0.6505787968635559  (0.64563733718612)
     | > grad_norm: tensor(0.3253, device='cuda:0')  (tensor(0.2881, device='cuda:0'))
     | > step_time: 1.259  (0.9288373426957564)
     | > loader_time: 1.253  (1.069229446757923)


   --> TIME: 2025-12-28 10:52:04 -- STEP: 80/150 -- GLOBAL_STEP: 14425
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48480403423309326  (0.4840896546840668)
     | > postnet_loss: 0.3984752595424652  (0.4035399291664362)
     | > stopnet_loss: 0.004140199162065983  (0.006299713952466845)
     | > loss: 0.22496002912521362  (0.2282071089372039)
     | > align_error: 0.5863496363162994  (0.6347149379551413)
     | > grad_norm: tensor(0.1718, device='cuda:0')  (tensor(0.2543, device='cuda:0'))
     | > step_time: 1.5131  (1.096435546875)
     | > loader_time: 1.4485  (1.1556739568710324)


   --> TIME: 2025-12-28 10:53:24 -- STEP: 105/150 -- GLOBAL_STEP: 14450
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4914229214191437  (0.48531382254191807)
     | > postnet_loss: 0.4002898931503296  (0.40289159757750376)
     | > stopnet_loss: 0.003634549444541335  (0.005673385506850623)
     | > loss: 0.2265627384185791  (0.22772473962534043)
     | > align_error: 0.6118325591087341  (0.6303132843403592)
     | > grad_norm: tensor(0.1244, device='cuda:0')  (tensor(0.2355, device='cuda:0'))
     | > step_time: 1.8649  (1.2365610690343947)
     | > loader_time: 1.5095  (1.2441892124357679)


   --> TIME: 2025-12-28 10:54:52 -- STEP: 130/150 -- GLOBAL_STEP: 14475
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49034634232521057  (0.4861657387935198)
     | > postnet_loss: 0.3997670114040375  (0.4022568922776442)
     | > stopnet_loss: 0.0031052767299115658  (0.005220188981351944)
     | > loss: 0.2256336212158203  (0.22732584591095265)
     | > align_error: 0.598671019077301  (0.6269713394916977)
     | > grad_norm: tensor(0.2455, device='cuda:0')  (tensor(0.2258, device='cuda:0'))
     | > step_time: 1.8804  (1.3554787782522348)
     | > loader_time: 1.8931  (1.3229980267011203)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4637037515640259  (0.4637037515640259)
     | > postnet_loss: 0.3312542736530304  (0.3312542736530304)
     | > stopnet_loss: 0.01223225798457861  (0.01223225798457861)
     | > loss: 0.21097175776958466  (0.21097175776958466)
     | > align_error: 0.7187753021717072  (0.7187753021717072)

   --> STEP: 1
     | > decoder_loss: 0.4449867010116577  (0.4449867010116577)
     | > postnet_loss: 0.3181758224964142  (0.3181758224964142)
     | > stopnet_loss: 0.009663079865276814  (0.009663079865276814)
     | > loss: 0.20045369863510132  (0.20045369863510132)
     | > align_error: 0.6593538522720337  (0.6593538522720337)

   --> STEP: 2
     | > decoder_loss: 0.44080281257629395  (0.44289475679397583)
     | > postnet_loss: 0.3111635446548462  (0.3146696835756302)
     | > stopnet_loss: 0.011200111359357834  (0.010431595612317324)
     | > loss: 0.19919170439243317  (0.19982270151376724)
     | > align_error: 0.6563012003898621  (0.6578275263309479)

   --> STEP: 3
     | > decoder_loss: 0.4445989429950714  (0.4434628188610077)
     | > postnet_loss: 0.30960509181022644  (0.3129814863204956)
     | > stopnet_loss: 0.008518419228494167  (0.009793870151042938)
     | > loss: 0.1970694214105606  (0.19890494147936502)
     | > align_error: 0.7351985573768616  (0.6836178700129191)

   --> STEP: 4
     | > decoder_loss: 0.4476214349269867  (0.44450247287750244)
     | > postnet_loss: 0.31625890731811523  (0.3138008415699005)
     | > stopnet_loss: 0.008329098112881184  (0.0094276771415025)
     | > loss: 0.1992991864681244  (0.19900350272655487)
     | > align_error: 0.6035766005516052  (0.6636075526475906)

   --> STEP: 5
     | > decoder_loss: 0.43013226985931396  (0.4416284322738647)
     | > postnet_loss: 0.30028966069221497  (0.3110986053943634)
     | > stopnet_loss: 0.008221441879868507  (0.0091864300891757)
     | > loss: 0.1908269226551056  (0.19736818671226503)
     | > align_error: 0.6417892575263977  (0.659243893623352)

   --> STEP: 6
     | > decoder_loss: 0.44576147198677063  (0.44231727222601575)
     | > postnet_loss: 0.3107912838459015  (0.31104738513628644)
     | > stopnet_loss: 0.007304774597287178  (0.008872820840527615)
     | > loss: 0.19644296169281006  (0.19721398254235586)
     | > align_error: 0.5944517850875854  (0.648445208867391)

   --> STEP: 7
     | > decoder_loss: 0.4542461037635803  (0.44402139101709637)
     | > postnet_loss: 0.30937299132347107  (0.31080818602016996)
     | > stopnet_loss: 0.006327712442725897  (0.00850923392655594)
     | > loss: 0.19723248481750488  (0.19721662572452)
     | > align_error: 0.5794097483158112  (0.6385830002171653)

   --> STEP: 8
     | > decoder_loss: 0.4547509253025055  (0.4453625828027725)
     | > postnet_loss: 0.31288161873817444  (0.3110673651099205)
     | > stopnet_loss: 0.007640454452484846  (0.008400636492297053)
     | > loss: 0.19954858720302582  (0.19750812090933323)
     | > align_error: 0.5757807493209839  (0.6307327188551426)

   --> STEP: 9
     | > decoder_loss: 0.4479010999202728  (0.44564464026027256)
     | > postnet_loss: 0.3100237250328064  (0.3109514051013523)
     | > stopnet_loss: 0.006649733986705542  (0.008206091769453552)
     | > loss: 0.1961309313774109  (0.19735509985023075)
     | > align_error: 0.591816246509552  (0.6264086663722992)

   --> STEP: 10
     | > decoder_loss: 0.47854048013687134  (0.44893422424793245)
     | > postnet_loss: 0.32638078927993774  (0.3124943435192108)
     | > stopnet_loss: 0.005860123783349991  (0.007971494970843197)
     | > loss: 0.20709043741226196  (0.19832863360643388)
     | > align_error: 0.5866056084632874  (0.622428360581398)

   --> STEP: 11
     | > decoder_loss: 0.46232494711875916  (0.45015156269073486)
     | > postnet_loss: 0.3164082467556  (0.3128501529043371)
     | > stopnet_loss: 0.005887437611818314  (0.007782035210931843)
     | > loss: 0.2005707323551178  (0.19853246076540512)
     | > align_error: 0.5950775146484375  (0.619941920042038)

   --> STEP: 12
     | > decoder_loss: 0.4570281207561493  (0.45072460919618607)
     | > postnet_loss: 0.30879199504852295  (0.31251197308301926)
     | > stopnet_loss: 0.007913672365248203  (0.00779300497379154)
     | > loss: 0.19936871528625488  (0.19860214864214262)
     | > align_error: 0.5881099700927734  (0.617289257546266)

   --> STEP: 13
     | > decoder_loss: 0.4477714002132416  (0.4504974392744211)
     | > postnet_loss: 0.30955538153648376  (0.312284542964055)
     | > stopnet_loss: 0.005657548550516367  (0.007628739095078065)
     | > loss: 0.19498924911022186  (0.19832423329353333)
     | > align_error: 0.5863191783428192  (0.6149069437613854)

   --> STEP: 14
     | > decoder_loss: 0.4581338167190552  (0.4510428948061807)
     | > postnet_loss: 0.31201666593551636  (0.31226540889058796)
     | > stopnet_loss: 0.004948032088577747  (0.007437260023185185)
     | > loss: 0.19748565554618835  (0.19826433488300868)
     | > align_error: 0.5555644929409027  (0.6106681972742081)

   --> STEP: 15
     | > decoder_loss: 0.4576359689235687  (0.4514824330806732)
     | > postnet_loss: 0.31446975469589233  (0.31241236527760824)
     | > stopnet_loss: 0.00500843208283186  (0.007275338160494963)
     | > loss: 0.1980348527431488  (0.1982490360736847)
     | > align_error: 0.5890366733074188  (0.6092260956764222)

   --> STEP: 16
     | > decoder_loss: 0.4574713706970215  (0.451856741681695)
     | > postnet_loss: 0.3069150447845459  (0.31206878274679184)
     | > stopnet_loss: 0.005250697955489159  (0.0071487981476821005)
     | > loss: 0.19634729623794556  (0.198130177333951)
     | > align_error: 0.606666624546051  (0.6090661287307739)

   --> STEP: 17
     | > decoder_loss: 0.46295130252838135  (0.45250936290797067)
     | > postnet_loss: 0.31578245759010315  (0.31228723420816307)
     | > stopnet_loss: 0.00482130516320467  (0.007011886795654017)
     | > loss: 0.19950473308563232  (0.19821103355463812)
     | > align_error: 0.5589473247528076  (0.6061179637908936)

   --> STEP: 18
     | > decoder_loss: 0.45794937014579773  (0.4528115855322944)
     | > postnet_loss: 0.30836600065231323  (0.3120693878995048)
     | > stopnet_loss: 0.005315552931278944  (0.006917646025410957)
     | > loss: 0.19689439237117767  (0.19813788682222366)
     | > align_error: 0.6044924557209015  (0.6060276577870051)

   --> STEP: 19
     | > decoder_loss: 0.45770639181137085  (0.45306920691540364)
     | > postnet_loss: 0.3081916868686676  (0.31186529837156596)
     | > stopnet_loss: 0.0048163034953176975  (0.006807049050142891)
     | > loss: 0.19629083573818207  (0.1980406736072741)
     | > align_error: 0.6008653044700623  (0.6057559549808502)

   --> STEP: 20
     | > decoder_loss: 0.4525793492794037  (0.4530447140336037)
     | > postnet_loss: 0.30513638257980347  (0.3115288525819778)
     | > stopnet_loss: 0.004533789120614529  (0.006693386053666472)
     | > loss: 0.1939627081155777  (0.19783677533268926)
     | > align_error: 0.6229656338691711  (0.6066164389252663)

   --> STEP: 21
     | > decoder_loss: 0.4509541094303131  (0.452945161433447)
     | > postnet_loss: 0.30376511812210083  (0.3111591509410313)
     | > stopnet_loss: 0.003998779691755772  (0.006565071465004058)
     | > loss: 0.19267860054969788  (0.19759114796207064)
     | > align_error: 0.5606435239315033  (0.6044272524969918)

   --> STEP: 22
     | > decoder_loss: 0.45261529088020325  (0.45293016731739044)
     | > postnet_loss: 0.30646541714668274  (0.31094579940492456)
     | > stopnet_loss: 0.004888868425041437  (0.00648888041773303)
     | > loss: 0.1946590393781662  (0.1974578702991659)
     | > align_error: 0.6257080435752869  (0.6053945611823689)

   --> STEP: 23
     | > decoder_loss: 0.4251170754432678  (0.45172090245329816)
     | > postnet_loss: 0.2947799563407898  (0.3102429366630057)
     | > stopnet_loss: 0.0045539215207099915  (0.006404751770036376)
     | > loss: 0.1845281720161438  (0.1968957095042519)
     | > align_error: 0.5674138069152832  (0.6037432240403217)

   --> STEP: 24
     | > decoder_loss: 0.4595389664173126  (0.4520466551184654)
     | > postnet_loss: 0.31042009592056274  (0.3102503182987372)
     | > stopnet_loss: 0.004429074004292488  (0.00632243186313038)
     | > loss: 0.19691884517669678  (0.19689667349060377)
     | > align_error: 0.5797508656978607  (0.6027435424427191)

   --> STEP: 25
     | > decoder_loss: 0.4592468738555908  (0.45233466386795046)
     | > postnet_loss: 0.3075654208660126  (0.3101429224014282)
     | > stopnet_loss: 0.0037069059908390045  (0.006217810828238726)
     | > loss: 0.19540998339653015  (0.1968372058868408)
     | > align_error: 0.5589929223060608  (0.6009935176372528)

   --> STEP: 26
     | > decoder_loss: 0.43496766686439514  (0.4516667024447368)
     | > postnet_loss: 0.29655715823173523  (0.3096203930102862)
     | > stopnet_loss: 0.004395876545459032  (0.006147736432747199)
     | > loss: 0.18727707862854004  (0.19646950868459848)
     | > align_error: 0.5474331378936768  (0.5989335030317307)

   --> STEP: 27
     | > decoder_loss: 0.4318122863769531  (0.4509313537014855)
     | > postnet_loss: 0.29195383191108704  (0.30896607593253805)
     | > stopnet_loss: 0.003929548431187868  (0.006065581321578335)
     | > loss: 0.18487107753753662  (0.19603993716063323)
     | > align_error: 0.5418331325054169  (0.5968186744937191)

   --> STEP: 28
     | > decoder_loss: 0.4374149441719055  (0.4504486247897148)
     | > postnet_loss: 0.2964109778404236  (0.3085176795721054)
     | > stopnet_loss: 0.0039621926844120026  (0.005990460298822394)
     | > loss: 0.18741866946220398  (0.19573203474283218)
     | > align_error: 0.5665834844112396  (0.5957388462764877)

   --> STEP: 29
     | > decoder_loss: 0.43313470482826233  (0.4498515930669061)
     | > postnet_loss: 0.2927875220775604  (0.3079752603481556)
     | > stopnet_loss: 0.0035943978000432253  (0.005907837454036906)
     | > loss: 0.18507495522499084  (0.19536454924221697)
     | > align_error: 0.5409905314445496  (0.5938509733512484)

   --> STEP: 30
     | > decoder_loss: 0.43389052152633667  (0.4493195573488871)
     | > postnet_loss: 0.2937881350517273  (0.307502356171608)
     | > stopnet_loss: 0.0029054770711809397  (0.005807758774608374)
     | > loss: 0.184825137257576  (0.1950132355093956)
     | > align_error: 0.5340731143951416  (0.5918583780527115)

   --> STEP: 31
     | > decoder_loss: 0.4320525527000427  (0.4487625571989244)
     | > postnet_loss: 0.2939317524433136  (0.30706459476101783)
     | > stopnet_loss: 0.003966279793530703  (0.005748356226831675)
     | > loss: 0.1854623705148697  (0.19470514309021733)
     | > align_error: 0.5598859190940857  (0.5908270084088848)

   --> STEP: 32
     | > decoder_loss: 0.4399680197238922  (0.44848772790282965)
     | > postnet_loss: 0.29731959104537964  (0.30676006339490414)
     | > stopnet_loss: 0.003884368808940053  (0.005690106620022561)
     | > loss: 0.188206285238266  (0.19450205378234386)
     | > align_error: 0.5313600599765778  (0.5889686662703753)

   --> STEP: 33
     | > decoder_loss: 0.43709248304367065  (0.4481424174525521)
     | > postnet_loss: 0.29611703753471375  (0.30643754745974683)
     | > stopnet_loss: 0.004047946073114872  (0.005640344179207177)
     | > loss: 0.1873503178358078  (0.19428533451123672)
     | > align_error: 0.5463846325874329  (0.5876782410072557)

   --> STEP: 34
     | > decoder_loss: 0.4422042667865753  (0.4479677659623763)
     | > postnet_loss: 0.29731661081314087  (0.3061692846171996)
     | > stopnet_loss: 0.0033406533766537905  (0.005572706214426195)
     | > loss: 0.18822087347507477  (0.19410696801017313)
     | > align_error: 0.5638414025306702  (0.5869771575226503)

   --> STEP: 35
     | > decoder_loss: 0.44033879041671753  (0.44774979523250036)
     | > postnet_loss: 0.29667428135871887  (0.30589799880981444)
     | > stopnet_loss: 0.0035330806858837605  (0.005514431199324983)
     | > loss: 0.18778635561466217  (0.1939263790845871)
     | > align_error: 0.5338259935379028  (0.5854585528373718)

   --> STEP: 36
     | > decoder_loss: 0.4462199807167053  (0.44770730038483936)
     | > postnet_loss: 0.3007190525531769  (0.3057541391915745)
     | > stopnet_loss: 0.0037138680927455425  (0.005464415557475555)
     | > loss: 0.19044862687587738  (0.19382977485656738)
     | > align_error: 0.6342978179454803  (0.5868151990903748)

   --> STEP: 37
     | > decoder_loss: 0.43916982412338257  (0.4474765577831784)
     | > postnet_loss: 0.2976745367050171  (0.30553577155680267)
     | > stopnet_loss: 0.003590099513530731  (0.005413758367098667)
     | > loss: 0.18780118227005005  (0.19366683992179665)
     | > align_error: 0.5191352367401123  (0.5849860109187461)

   --> STEP: 38
     | > decoder_loss: 0.4270189702510834  (0.4469382002165443)
     | > postnet_loss: 0.2906452417373657  (0.3051439155089227)
     | > stopnet_loss: 0.00315972906537354  (0.005354441806526953)
     | > loss: 0.1825757920742035  (0.19337497024159683)
     | > align_error: 0.5517151355743408  (0.5841104615675775)

   --> STEP: 39
     | > decoder_loss: 0.4421752691268921  (0.4468160737783481)
     | > postnet_loss: 0.30049780011177063  (0.30502478434489316)
     | > stopnet_loss: 0.003506784327328205  (0.005307065973726985)
     | > loss: 0.18917503952980042  (0.19326727971052513)
     | > align_error: 0.5463339686393738  (0.5831418335437774)

   --> STEP: 40
     | > decoder_loss: 0.439367413520813  (0.44662985727190974)
     | > postnet_loss: 0.2989860773086548  (0.30487381666898716)
     | > stopnet_loss: 0.0030655679292976856  (0.005251028522616252)
     | > loss: 0.18765394389629364  (0.19312694631516933)
     | > align_error: 0.5842623710632324  (0.5831698469817638)

   --> STEP: 41
     | > decoder_loss: 0.429203063249588  (0.4462048135152677)
     | > postnet_loss: 0.29111409187316895  (0.30453821362518674)
     | > stopnet_loss: 0.0037462525069713593  (0.005214326668576133)
     | > loss: 0.1838255375623703  (0.19290008268705228)
     | > align_error: 0.5037266612052917  (0.5812322083042888)

   --> STEP: 42
     | > decoder_loss: 0.43514445424079895  (0.44594147162778036)
     | > postnet_loss: 0.2941610515117645  (0.3042911383367719)
     | > stopnet_loss: 0.003315080888569355  (0.005169106530956924)
     | > loss: 0.18564145267009735  (0.19272725816283906)
     | > align_error: 0.5796716213226318  (0.5811950514713923)

   --> STEP: 43
     | > decoder_loss: 0.4326898455619812  (0.44563329427741294)
     | > postnet_loss: 0.29236534237861633  (0.3040137942447218)
     | > stopnet_loss: 0.002957503078505397  (0.005117673892527819)
     | > loss: 0.1842213124036789  (0.1925294454707656)
     | > align_error: 0.5517551302909851  (0.5805104021416154)

   --> STEP: 44
     | > decoder_loss: 0.4516157805919647  (0.44576925987547095)
     | > postnet_loss: 0.3030315339565277  (0.30399147014726285)
     | > stopnet_loss: 0.002692529931664467  (0.005062556984326379)
     | > loss: 0.19135436415672302  (0.19250273907726462)
     | > align_error: 0.5512303113937378  (0.5798449455337091)

   --> STEP: 45
     | > decoder_loss: 0.444833904504776  (0.4457484742005666)
     | > postnet_loss: 0.3023245334625244  (0.30395442710982423)
     | > stopnet_loss: 0.0033208189997822046  (0.005023851695780953)
     | > loss: 0.19011041522026062  (0.19244957632488674)
     | > align_error: 0.5526489913463593  (0.5792405909962124)

   --> STEP: 46
     | > decoder_loss: 0.4352448582649231  (0.4455201347237048)
     | > postnet_loss: 0.29341232776641846  (0.3037252510371415)
     | > stopnet_loss: 0.0032174200750887394  (0.004984581443157209)
     | > loss: 0.1853817105293274  (0.19229592706846155)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3671489014770045 (-0.0027249473513978884)
     | > avg_decoder_loss: 0.44194406270980835 (+9.947653972719461e-06)
     | > avg_postnet_loss: 0.300745077656977 (-0.001852536743337574)
     | > avg_stopnet_loss: 0.004414078056332514 (+3.8486379763166996e-05)
     | > avg_loss: 0.1900863629398924 (-0.00042216254003119014)
     | > avg_align_error: 0.5720084603085663 (-0.0010865560986778044)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_14496.pth

 > EPOCH: 96/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 10:58:20)

   --> TIME: 2025-12-28 10:58:25 -- STEP: 4/150 -- GLOBAL_STEP: 14500
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4686528742313385  (0.46397656947374344)
     | > postnet_loss: 0.4029671847820282  (0.40087781101465225)
     | > stopnet_loss: 0.014468889683485031  (0.014392580138519406)
     | > loss: 0.232373908162117  (0.23060617223381996)
     | > align_error: 0.688378632068634  (0.7078075483441353)
     | > grad_norm: tensor(0.3626, device='cuda:0')  (tensor(0.3239, device='cuda:0'))
     | > step_time: 0.4982  (0.4553205370903015)
     | > loader_time: 0.6961  (0.6897838115692139)


   --> TIME: 2025-12-28 10:59:08 -- STEP: 29/150 -- GLOBAL_STEP: 14525
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.483254998922348  (0.4744611331101122)
     | > postnet_loss: 0.40632426738739014  (0.40213445753886784)
     | > stopnet_loss: 0.006633536424487829  (0.009169587078664837)
     | > loss: 0.2290283590555191  (0.2283184862342374)
     | > align_error: 0.6742461323738098  (0.6675112011103794)
     | > grad_norm: tensor(0.3394, device='cuda:0')  (tensor(0.2762, device='cuda:0'))
     | > step_time: 1.0443  (0.7163841806609054)
     | > loader_time: 0.9554  (0.9019930855981235)


   --> TIME: 2025-12-28 11:00:03 -- STEP: 54/150 -- GLOBAL_STEP: 14550
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48720747232437134  (0.48098834741998603)
     | > postnet_loss: 0.3997642397880554  (0.4036066918461411)
     | > stopnet_loss: 0.004872089251875877  (0.007324930642628007)
     | > loss: 0.22661501169204712  (0.22847369120076852)
     | > align_error: 0.5758141279220581  (0.6444831733350403)
     | > grad_norm: tensor(0.1899, device='cuda:0')  (tensor(0.2674, device='cuda:0'))
     | > step_time: 1.3186  (0.920603248808119)
     | > loader_time: 1.1732  (0.9707142688609935)


   --> TIME: 2025-12-28 11:01:12 -- STEP: 79/150 -- GLOBAL_STEP: 14575
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4895440638065338  (0.48363693303699734)
     | > postnet_loss: 0.4012491703033447  (0.4032026329372503)
     | > stopnet_loss: 0.004059929400682449  (0.006311631941271923)
     | > loss: 0.2267582267522812  (0.2280215236205089)
     | > align_error: 0.5938533544540405  (0.6342613459387915)
     | > grad_norm: tensor(0.1373, device='cuda:0')  (tensor(0.2400, device='cuda:0'))
     | > step_time: 1.6235  (1.0882175240335588)
     | > loader_time: 1.5951  (1.0730794230593914)


   --> TIME: 2025-12-28 11:02:36 -- STEP: 104/150 -- GLOBAL_STEP: 14600
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49513426423072815  (0.4849514110157123)
     | > postnet_loss: 0.4046020209789276  (0.40257580320422465)
     | > stopnet_loss: 0.003452839097008109  (0.005671717089941152)
     | > loss: 0.22838690876960754  (0.2275535209247699)
     | > align_error: 0.614569216966629  (0.6297635851571193)
     | > grad_norm: tensor(0.1559, device='cuda:0')  (tensor(0.2289, device='cuda:0'))
     | > step_time: 1.7677  (1.2210953739973218)
     | > loader_time: 1.7678  (1.2318336986578433)


   --> TIME: 2025-12-28 11:04:07 -- STEP: 129/150 -- GLOBAL_STEP: 14625
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.490285187959671  (0.48579271403394003)
     | > postnet_loss: 0.39867866039276123  (0.4019307013629943)
     | > stopnet_loss: 0.0031438975129276514  (0.005213241966426835)
     | > loss: 0.22538484632968903  (0.22714409578678219)
     | > align_error: 0.6620084047317505  (0.626652985349182)
     | > grad_norm: tensor(0.1491, device='cuda:0')  (tensor(0.2173, device='cuda:0'))
     | > step_time: 1.9277  (1.340215553608976)
     | > loader_time: 1.7918  (1.341009803520617)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4644251763820648  (0.4644251763820648)
     | > postnet_loss: 0.33194732666015625  (0.33194732666015625)
     | > stopnet_loss: 0.012277629226446152  (0.012277629226446152)
     | > loss: 0.21137076616287231  (0.21137076616287231)
     | > align_error: 0.7181296348571777  (0.7181296348571777)

   --> STEP: 1
     | > decoder_loss: 0.4446157217025757  (0.4446157217025757)
     | > postnet_loss: 0.3180757761001587  (0.3180757761001587)
     | > stopnet_loss: 0.009695732034742832  (0.009695732034742832)
     | > loss: 0.20036861300468445  (0.20036861300468445)
     | > align_error: 0.6587555110454559  (0.6587555110454559)

   --> STEP: 2
     | > decoder_loss: 0.440032035112381  (0.44232387840747833)
     | > postnet_loss: 0.31072714924812317  (0.31440146267414093)
     | > stopnet_loss: 0.011215885169804096  (0.010455808602273464)
     | > loss: 0.19890567660331726  (0.19963714480400085)
     | > align_error: 0.6554723381996155  (0.6571139246225357)

   --> STEP: 3
     | > decoder_loss: 0.4433281719684601  (0.4426586429278056)
     | > postnet_loss: 0.3086966574192047  (0.31249986092249554)
     | > stopnet_loss: 0.008457879535853863  (0.009789832246800264)
     | > loss: 0.19646409153938293  (0.19857946038246155)
     | > align_error: 0.734375536441803  (0.6828677952289581)

   --> STEP: 4
     | > decoder_loss: 0.449634313583374  (0.4444025605916977)
     | > postnet_loss: 0.31748536229133606  (0.31374623626470566)
     | > stopnet_loss: 0.008278459310531616  (0.009411989012733102)
     | > loss: 0.20005837082862854  (0.1989491879940033)
     | > align_error: 0.6028338968753815  (0.662859320640564)

   --> STEP: 5
     | > decoder_loss: 0.4310949146747589  (0.44174103140830995)
     | > postnet_loss: 0.3007458448410034  (0.3111461579799652)
     | > stopnet_loss: 0.008251041173934937  (0.009179799444973468)
     | > loss: 0.19121122360229492  (0.19740159511566163)
     | > align_error: 0.6413513422012329  (0.6585577249526977)

   --> STEP: 6
     | > decoder_loss: 0.44661784172058105  (0.4425538331270218)
     | > postnet_loss: 0.31127864122390747  (0.31116823852062225)
     | > stopnet_loss: 0.00730560626834631  (0.008867433915535608)
     | > loss: 0.19677972793579102  (0.1972979505856832)
     | > align_error: 0.5935890972614288  (0.6477296203374863)

   --> STEP: 7
     | > decoder_loss: 0.4546147286891937  (0.44427681820733206)
     | > postnet_loss: 0.30968156456947327  (0.310955856527601)
     | > stopnet_loss: 0.006323494482785463  (0.008504013996571302)
     | > loss: 0.19739757478237152  (0.19731218261378153)
     | > align_error: 0.5785545110702515  (0.6378474618707385)

   --> STEP: 8
     | > decoder_loss: 0.45404353737831116  (0.44549765810370445)
     | > postnet_loss: 0.3121611475944519  (0.31110651791095734)
     | > stopnet_loss: 0.007588546723127365  (0.00838958058739081)
     | > loss: 0.19913972914218903  (0.19754062592983246)
     | > align_error: 0.5747843682765961  (0.6299645751714706)

   --> STEP: 9
     | > decoder_loss: 0.44821664690971375  (0.4457997679710388)
     | > postnet_loss: 0.31043487787246704  (0.31103189124001396)
     | > stopnet_loss: 0.0066495719365775585  (0.008196246292856004)
     | > loss: 0.19631244242191315  (0.1974041610956192)
     | > align_error: 0.5909680724143982  (0.6256316304206848)

   --> STEP: 10
     | > decoder_loss: 0.4790410101413727  (0.4491238921880722)
     | > postnet_loss: 0.3267505466938019  (0.31260375678539276)
     | > stopnet_loss: 0.0058723133988678455  (0.00796385300345719)
     | > loss: 0.2073201984167099  (0.19839576482772828)
     | > align_error: 0.5857113599777222  (0.6216396033763886)

   --> STEP: 11
     | > decoder_loss: 0.4620324969291687  (0.45029740170999005)
     | > postnet_loss: 0.3163596987724304  (0.31294520605694165)
     | > stopnet_loss: 0.005891179200261831  (0.00777542811225761)
     | > loss: 0.20048922300338745  (0.19858607920733365)
     | > align_error: 0.5938961207866669  (0.6191174685955048)

   --> STEP: 12
     | > decoder_loss: 0.45690518617630005  (0.4508480504155159)
     | > postnet_loss: 0.3086780607700348  (0.3125896106163661)
     | > stopnet_loss: 0.007863720878958702  (0.007782785842816035)
     | > loss: 0.19925953447818756  (0.1986422004799048)
     | > align_error: 0.5871478617191315  (0.6164533346891403)

   --> STEP: 13
     | > decoder_loss: 0.4477538764476776  (0.4506100370333745)
     | > postnet_loss: 0.3094276785850525  (0.3123463850754958)
     | > stopnet_loss: 0.005653206259012222  (0.00761897202867728)
     | > loss: 0.19494858384132385  (0.1983580761230909)
     | > align_error: 0.5854587256908417  (0.6140691339969635)

   --> STEP: 14
     | > decoder_loss: 0.4542824923992157  (0.4508723552737917)
     | > postnet_loss: 0.3098704516887665  (0.3121695326907294)
     | > stopnet_loss: 0.00495905801653862  (0.007428978170667376)
     | > loss: 0.19599729776382446  (0.198189449097429)
     | > align_error: 0.5543185472488403  (0.6098012349435261)

   --> STEP: 15
     | > decoder_loss: 0.45750802755355835  (0.45131473342577616)
     | > postnet_loss: 0.3142017126083374  (0.3123050113519033)
     | > stopnet_loss: 0.004976929631084204  (0.007265508268028497)
     | > loss: 0.19790436327457428  (0.19817044337590536)
     | > align_error: 0.5879755318164825  (0.6083461880683899)

   --> STEP: 16
     | > decoder_loss: 0.45792534947395325  (0.45172789692878723)
     | > postnet_loss: 0.3069617748260498  (0.31197105906903744)
     | > stopnet_loss: 0.0052584437653422356  (0.007140066736610606)
     | > loss: 0.19648021459579468  (0.19806480407714844)
     | > align_error: 0.6056067943572998  (0.6081749759614468)

   --> STEP: 17
     | > decoder_loss: 0.46307337284088135  (0.4523952778647928)
     | > postnet_loss: 0.3156706690788269  (0.31218868318726034)
     | > stopnet_loss: 0.004816317930817604  (0.007003375630387489)
     | > loss: 0.19950233399868011  (0.19814936466076793)
     | > align_error: 0.5579038858413696  (0.605217853013207)

   --> STEP: 18
     | > decoder_loss: 0.4575579762458801  (0.45268209444151986)
     | > postnet_loss: 0.30799323320388794  (0.31195560263262856)
     | > stopnet_loss: 0.005297444760799408  (0.0069086016931881504)
     | > loss: 0.19668525457382202  (0.19806802521149316)
     | > align_error: 0.6035037040710449  (0.6051226225164201)

   --> STEP: 19
     | > decoder_loss: 0.4557070732116699  (0.4528413038504751)
     | > postnet_loss: 0.30708491802215576  (0.31169925081102473)
     | > stopnet_loss: 0.004805934149771929  (0.0067979349803767705)
     | > loss: 0.19550393521785736  (0.19793307310656497)
     | > align_error: 0.5999157130718231  (0.604848574650915)

   --> STEP: 20
     | > decoder_loss: 0.45240518450737  (0.4528194978833199)
     | > postnet_loss: 0.30488279461860657  (0.3113584280014038)
     | > stopnet_loss: 0.004553445614874363  (0.00668571051210165)
     | > loss: 0.19387544691562653  (0.19773019179701806)
     | > align_error: 0.622270256280899  (0.6057196587324143)

   --> STEP: 21
     | > decoder_loss: 0.4507465362548828  (0.45272078542482286)
     | > postnet_loss: 0.30353501439094543  (0.3109858844961439)
     | > stopnet_loss: 0.0040012202225625515  (0.006557877641171217)
     | > loss: 0.19257159531116486  (0.19748454434531076)
     | > align_error: 0.5594748556613922  (0.6035175252528417)

   --> STEP: 22
     | > decoder_loss: 0.4525013864040375  (0.4527108127420599)
     | > postnet_loss: 0.30643969774246216  (0.3107792396437038)
     | > stopnet_loss: 0.004898755811154842  (0.006482463012534109)
     | > loss: 0.19463402032852173  (0.19735497507182034)
     | > align_error: 0.6247166991233826  (0.6044811240651391)

   --> STEP: 23
     | > decoder_loss: 0.4252033233642578  (0.451514834943025)
     | > postnet_loss: 0.29456496238708496  (0.3100742710673291)
     | > stopnet_loss: 0.00457574799656868  (0.006399562359666047)
     | > loss: 0.18451781570911407  (0.19679683770822443)
     | > align_error: 0.5664620995521545  (0.6028281229993572)

   --> STEP: 24
     | > decoder_loss: 0.45898178219795227  (0.45182595774531364)
     | > postnet_loss: 0.30986037850379944  (0.31006535887718206)
     | > stopnet_loss: 0.004420462995767593  (0.006317099886170278)
     | > loss: 0.19663099944591522  (0.1967899277806282)
     | > align_error: 0.5789192020893097  (0.6018319179614385)

   --> STEP: 25
     | > decoder_loss: 0.45868366956710815  (0.45210026621818544)
     | > postnet_loss: 0.3070807456970215  (0.3099459743499757)
     | > stopnet_loss: 0.0036995522677898407  (0.0062123979814350605)
     | > loss: 0.19514065980911255  (0.19672395706176757)
     | > align_error: 0.5568761229515076  (0.6000336861610412)

   --> STEP: 26
     | > decoder_loss: 0.4340866506099701  (0.45140743484863866)
     | > postnet_loss: 0.29578301310539246  (0.3094012450713378)
     | > stopnet_loss: 0.004403401631861925  (0.00614282119875917)
     | > loss: 0.18687081336975098  (0.19634498999669)
     | > align_error: 0.5462440848350525  (0.5979648553408109)

   --> STEP: 27
     | > decoder_loss: 0.43113940954208374  (0.4506567672446922)
     | > postnet_loss: 0.2914361357688904  (0.3087358706527287)
     | > stopnet_loss: 0.003924630582332611  (0.0060606659907433726)
     | > loss: 0.18456852436065674  (0.19590882460276285)
     | > align_error: 0.5406851470470428  (0.5958433846632639)

   --> STEP: 28
     | > decoder_loss: 0.43732693791389465  (0.45018070191144943)
     | > postnet_loss: 0.2960493564605713  (0.30828278086015165)
     | > stopnet_loss: 0.003961025271564722  (0.005985678822201278)
     | > loss: 0.18730509281158447  (0.19560154846736363)
     | > align_error: 0.5656673312187195  (0.594765668468816)

   --> STEP: 29
     | > decoder_loss: 0.4323573410511017  (0.4495661032610926)
     | > postnet_loss: 0.2923031747341156  (0.30773175995925384)
     | > stopnet_loss: 0.0035872880835086107  (0.005902975693280841)
     | > loss: 0.18475241959095  (0.19522744057507352)
     | > align_error: 0.53984335064888  (0.5928717954405422)

   --> STEP: 30
     | > decoder_loss: 0.43333443999290466  (0.4490250478188197)
     | > postnet_loss: 0.29339611530303955  (0.30725390513738005)
     | > stopnet_loss: 0.002893056720495224  (0.005802645060854653)
     | > loss: 0.18457570672035217  (0.19487238277991611)
     | > align_error: 0.5329859554767609  (0.5908756007750829)

   --> STEP: 31
     | > decoder_loss: 0.4309478998184204  (0.44844191401235517)
     | > postnet_loss: 0.29317784309387207  (0.3067998386198475)
     | > stopnet_loss: 0.00376196694560349  (0.005736816734556229)
     | > loss: 0.1847933977842331  (0.1945472542316683)
     | > align_error: 0.5585847496986389  (0.5898339604177782)

   --> STEP: 32
     | > decoder_loss: 0.4395401179790497  (0.4481637328863144)
     | > postnet_loss: 0.2970706820487976  (0.3064958024770022)
     | > stopnet_loss: 0.00388338346965611  (0.0056788969450281)
     | > loss: 0.18803606927394867  (0.19434377970173955)
     | > align_error: 0.5303469896316528  (0.5879749925807118)

   --> STEP: 33
     | > decoder_loss: 0.4363245368003845  (0.44780496936855896)
     | > postnet_loss: 0.29543691873550415  (0.3061606847878659)
     | > stopnet_loss: 0.004032538738101721  (0.005629007302393968)
     | > loss: 0.18697290122509003  (0.19412041974790167)
     | > align_error: 0.5451879799365997  (0.5866784164399812)

   --> STEP: 34
     | > decoder_loss: 0.44191452860832214  (0.44763172111090493)
     | > postnet_loss: 0.29684120416641235  (0.3058865824166467)
     | > stopnet_loss: 0.0033456026576459408  (0.00556184834225432)
     | > loss: 0.1880345344543457  (0.19394142312162063)
     | > align_error: 0.5627833604812622  (0.5859756206764895)

   --> STEP: 35
     | > decoder_loss: 0.4403689503669739  (0.44742421337536403)
     | > postnet_loss: 0.2963927090167999  (0.3056153288909368)
     | > stopnet_loss: 0.0035362474154680967  (0.005503974030060427)
     | > loss: 0.1877266764640808  (0.19376385893140521)
     | > align_error: 0.5326047539710999  (0.5844507387706211)

   --> STEP: 36
     | > decoder_loss: 0.4461629390716553  (0.4473891779780388)
     | > postnet_loss: 0.3005419075489044  (0.30547440052032476)
     | > stopnet_loss: 0.003702703397721052  (0.005453938734717667)
     | > loss: 0.19037890434265137  (0.19366983241505092)
     | > align_error: 0.6333813369274139  (0.5858099220527543)

   --> STEP: 37
     | > decoder_loss: 0.4387262761592865  (0.4471550454964509)
     | > postnet_loss: 0.29717838764190674  (0.3052501839560432)
     | > stopnet_loss: 0.003589197527617216  (0.0054035403237149525)
     | > loss: 0.1875653713941574  (0.1935048469820538)
     | > align_error: 0.5180231332778931  (0.5839778466804607)

   --> STEP: 38
     | > decoder_loss: 0.42688992619514465  (0.4466217528832586)
     | > postnet_loss: 0.2905232310295105  (0.3048626325632397)
     | > stopnet_loss: 0.003165763569995761  (0.005344651461774974)
     | > loss: 0.1825190633535385  (0.19321574741288236)
     | > align_error: 0.550710916519165  (0.5831024011499003)

   --> STEP: 39
     | > decoder_loss: 0.4418325424194336  (0.4464989526149554)
     | > postnet_loss: 0.30020979046821594  (0.30474332891977757)
     | > stopnet_loss: 0.0035074232146143913  (0.005297543045181113)
     | > loss: 0.18901799619197845  (0.1931081127661925)
     | > align_error: 0.5450347661972046  (0.5821263079459851)

   --> STEP: 40
     | > decoder_loss: 0.4392149746417999  (0.4463168531656265)
     | > postnet_loss: 0.29889559745788574  (0.30459713563323026)
     | > stopnet_loss: 0.003058601636439562  (0.0052415695099625745)
     | > loss: 0.1875862330198288  (0.1929700657725334)
     | > align_error: 0.5831109881401062  (0.5821509249508381)

   --> STEP: 41
     | > decoder_loss: 0.4294443428516388  (0.4459053285238219)
     | > postnet_loss: 0.29113587737083435  (0.3042688122609767)
     | > stopnet_loss: 0.003753470256924629  (0.005205274406229941)
     | > loss: 0.18389852344989777  (0.19274880864271302)
     | > align_error: 0.5025767087936401  (0.5802100904104186)

   --> STEP: 42
     | > decoder_loss: 0.4348869025707245  (0.4456429850487482)
     | > postnet_loss: 0.29377394914627075  (0.3040189345677694)
     | > stopnet_loss: 0.0033180525060743093  (0.005160340551464331)
     | > loss: 0.18548326194286346  (0.19257581943557375)
     | > align_error: 0.5787984728813171  (0.5801764804692495)

   --> STEP: 43
     | > decoder_loss: 0.43257489800453186  (0.4453390760477199)
     | > postnet_loss: 0.29208236932754517  (0.3037413400272991)
     | > stopnet_loss: 0.002950382884591818  (0.005108946187118459)
     | > loss: 0.1841147094964981  (0.1923790494369906)
     | > align_error: 0.5509527921676636  (0.5794968598110731)

   --> STEP: 44
     | > decoder_loss: 0.45156222581863403  (0.44548051126978616)
     | > postnet_loss: 0.30279284715652466  (0.30371978337114514)
     | > stopnet_loss: 0.0026899706572294235  (0.0050539694705300725)
     | > loss: 0.19127874076366425  (0.19235404242168774)
     | > align_error: 0.5499536395072937  (0.5788254229859873)

   --> STEP: 45
     | > decoder_loss: 0.4443865716457367  (0.4454562015003628)
     | > postnet_loss: 0.3020668923854828  (0.30368305246035265)
     | > stopnet_loss: 0.0033274840097874403  (0.005015603126958014)
     | > loss: 0.18994085490703583  (0.19230041603247325)
     | > align_error: 0.5517940819263458  (0.5782247265179952)

   --> STEP: 46
     | > decoder_loss: 0.4348597526550293  (0.4452258439167686)
     | > postnet_loss: 0.2929902672767639  (0.3034506006085355)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3499280322681774 (-0.017220869208827094)
     | > avg_decoder_loss: 0.44155078223257355 (-0.0003932804772348031)
     | > avg_postnet_loss: 0.3004304929213091 (-0.0003145847356679221)
     | > avg_stopnet_loss: 0.004408119362778963 (-5.95869355355088e-06)
     | > avg_loss: 0.18990343854282843 (-0.00018292439706396602)
     | > avg_align_error: 0.5709887183073795 (-0.0010197420011868186)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_14647.pth

 > EPOCH: 97/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 11:07:29)

   --> TIME: 2025-12-28 11:07:34 -- STEP: 3/150 -- GLOBAL_STEP: 14650
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45963311195373535  (0.463359276453654)
     | > postnet_loss: 0.39618250727653503  (0.4003813862800598)
     | > stopnet_loss: 0.012989598326385021  (0.014641666784882545)
     | > loss: 0.2269435077905655  (0.23057683308919272)
     | > align_error: 0.696565181016922  (0.7136415044466654)
     | > grad_norm: tensor(0.2692, device='cuda:0')  (tensor(0.2918, device='cuda:0'))
     | > step_time: 0.5079  (0.4368348916371663)
     | > loader_time: 0.6505  (0.6459057331085205)


   --> TIME: 2025-12-28 11:08:15 -- STEP: 28/150 -- GLOBAL_STEP: 14675
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.4856947064399719  (0.4741752701146262)
     | > postnet_loss: 0.40472859144210815  (0.40184467072997776)
     | > stopnet_loss: 0.006075609941035509  (0.009352478132184063)
     | > loss: 0.22868143022060394  (0.22835746513945715)
     | > align_error: 0.6452397108078003  (0.6669599094561168)
     | > grad_norm: tensor(0.4192, device='cuda:0')  (tensor(0.3087, device='cuda:0'))
     | > step_time: 0.8671  (0.675734783921923)
     | > loader_time: 0.9906  (0.9113469294139317)


   --> TIME: 2025-12-28 11:09:11 -- STEP: 53/150 -- GLOBAL_STEP: 14700
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48440447449684143  (0.4807555653014273)
     | > postnet_loss: 0.39978891611099243  (0.40342445362289)
     | > stopnet_loss: 0.0043089427053928375  (0.007395087135077085)
     | > loss: 0.2253572940826416  (0.2284400924196783)
     | > align_error: 0.581315666437149  (0.6457369085752737)
     | > grad_norm: tensor(0.1852, device='cuda:0')  (tensor(0.2818, device='cuda:0'))
     | > step_time: 1.2956  (0.9042136084358647)
     | > loader_time: 1.1638  (0.9875480004076688)


   --> TIME: 2025-12-28 11:10:18 -- STEP: 78/150 -- GLOBAL_STEP: 14725
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49230673909187317  (0.4836462491597885)
     | > postnet_loss: 0.40366166830062866  (0.4031569598576961)
     | > stopnet_loss: 0.0040550436824560165  (0.006354092175546938)
     | > loss: 0.22804714739322662  (0.22805489465976372)
     | > align_error: 0.6162319779396057  (0.6354106966501626)
     | > grad_norm: tensor(0.1837, device='cuda:0')  (tensor(0.2522, device='cuda:0'))
     | > step_time: 1.5755  (1.0651387006808553)
     | > loader_time: 1.536  (1.0824837745764317)


   --> TIME: 2025-12-28 11:11:37 -- STEP: 103/150 -- GLOBAL_STEP: 14750
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4987681806087494  (0.48484903139975466)
     | > postnet_loss: 0.4059736728668213  (0.4024510328630799)
     | > stopnet_loss: 0.0034145000390708447  (0.00571106250388819)
     | > loss: 0.2295999675989151  (0.22753607865097453)
     | > align_error: 0.5964712798595428  (0.6302926219204097)
     | > grad_norm: tensor(0.1416, device='cuda:0')  (tensor(0.2472, device='cuda:0'))
     | > step_time: 1.6887  (1.2038733519396738)
     | > loader_time: 1.5757  (1.1900398129398384)


   --> TIME: 2025-12-28 11:13:04 -- STEP: 128/150 -- GLOBAL_STEP: 14775
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4910145401954651  (0.48580047534778714)
     | > postnet_loss: 0.3990626335144043  (0.40187490708194673)
     | > stopnet_loss: 0.0034388455096632242  (0.0052508139378915075)
     | > loss: 0.22595813870429993  (0.22716965968720615)
     | > align_error: 0.6198993623256683  (0.6270821508951485)
     | > grad_norm: tensor(0.1549, device='cuda:0')  (tensor(0.2277, device='cuda:0'))
     | > step_time: 1.9777  (1.3236451521515846)
     | > loader_time: 1.6586  (1.2790222242474556)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4639653265476227  (0.4639653265476227)
     | > postnet_loss: 0.33260759711265564  (0.33260759711265564)
     | > stopnet_loss: 0.012144114822149277  (0.012144114822149277)
     | > loss: 0.21128734946250916  (0.21128734946250916)
     | > align_error: 0.7190576791763306  (0.7190576791763306)

   --> STEP: 1
     | > decoder_loss: 0.44583815336227417  (0.44583815336227417)
     | > postnet_loss: 0.3200787305831909  (0.3200787305831909)
     | > stopnet_loss: 0.009669962339103222  (0.009669962339103222)
     | > loss: 0.20114918053150177  (0.20114918053150177)
     | > align_error: 0.6598859429359436  (0.6598859429359436)

   --> STEP: 2
     | > decoder_loss: 0.4417736828327179  (0.44380591809749603)
     | > postnet_loss: 0.3123890161514282  (0.31623387336730957)
     | > stopnet_loss: 0.011152462102472782  (0.010411212220788002)
     | > loss: 0.19969312846660614  (0.20042115449905396)
     | > align_error: 0.6565384566783905  (0.658212199807167)

   --> STEP: 3
     | > decoder_loss: 0.44493839144706726  (0.4441834092140198)
     | > postnet_loss: 0.31034645438194275  (0.3142714003721873)
     | > stopnet_loss: 0.008320511318743229  (0.009714311920106411)
     | > loss: 0.19714172184467316  (0.19932801028092703)
     | > align_error: 0.7353645265102386  (0.6839296420415243)

   --> STEP: 4
     | > decoder_loss: 0.4511962831020355  (0.4459366276860237)
     | > postnet_loss: 0.31982120871543884  (0.3156588524580002)
     | > stopnet_loss: 0.00823107548058033  (0.00934350281022489)
     | > loss: 0.20098544657230377  (0.1997423693537712)
     | > align_error: 0.6042131781578064  (0.6640005260705948)

   --> STEP: 5
     | > decoder_loss: 0.43343642354011536  (0.44343658685684206)
     | > postnet_loss: 0.3022070825099945  (0.312968498468399)
     | > stopnet_loss: 0.008183876052498817  (0.009111577458679677)
     | > loss: 0.19209475815296173  (0.19821284711360931)
     | > align_error: 0.6431030035018921  (0.6598210215568543)

   --> STEP: 6
     | > decoder_loss: 0.4491698443889618  (0.444392129778862)
     | > postnet_loss: 0.31366148591041565  (0.3130839963754018)
     | > stopnet_loss: 0.007228636182844639  (0.00879775391270717)
     | > loss: 0.19793647527694702  (0.19816678514083227)
     | > align_error: 0.5946494340896606  (0.648959090312322)

   --> STEP: 7
     | > decoder_loss: 0.4586787223815918  (0.446433071579252)
     | > postnet_loss: 0.3130159080028534  (0.31307426946503775)
     | > stopnet_loss: 0.0062976740300655365  (0.008440599643758364)
     | > loss: 0.19922134280204773  (0.1983174362352916)
     | > align_error: 0.5799826383590698  (0.6391053114618573)

   --> STEP: 8
     | > decoder_loss: 0.45618677139282227  (0.44765228405594826)
     | > postnet_loss: 0.3146987557411194  (0.31327733024954796)
     | > stopnet_loss: 0.007535329554229975  (0.008327440882567316)
     | > loss: 0.20025670528411865  (0.198559844866395)
     | > align_error: 0.5762751698493958  (0.6312515437602997)

   --> STEP: 9
     | > decoder_loss: 0.4527970254421234  (0.4482239219877455)
     | > postnet_loss: 0.3145725727081299  (0.31342124607827926)
     | > stopnet_loss: 0.006719548255205154  (0.008148786146193743)
     | > loss: 0.19856195151805878  (0.1985600789388021)
     | > align_error: 0.5925013720989227  (0.6269459691312578)

   --> STEP: 10
     | > decoder_loss: 0.48093748092651367  (0.4514952778816223)
     | > postnet_loss: 0.3289680480957031  (0.3149759262800217)
     | > stopnet_loss: 0.005855095572769642  (0.007919417088851332)
     | > loss: 0.20833148062229156  (0.19953721910715103)
     | > align_error: 0.5870298743247986  (0.6229543596506119)

   --> STEP: 11
     | > decoder_loss: 0.46636298298835754  (0.4528468874367801)
     | > postnet_loss: 0.3198138177394867  (0.3154157345945185)
     | > stopnet_loss: 0.005893380381166935  (0.007735231933607297)
     | > loss: 0.20243757963180542  (0.19980088824575598)
     | > align_error: 0.5958357453346252  (0.6204890310764313)

   --> STEP: 12
     | > decoder_loss: 0.4603676199913025  (0.45347361514965695)
     | > postnet_loss: 0.3117024004459381  (0.3151062900821368)
     | > stopnet_loss: 0.007958742789924145  (0.007753857838300367)
     | > loss: 0.20097625255584717  (0.1998988352715969)
     | > align_error: 0.5887712240219116  (0.6178458804885546)

   --> STEP: 13
     | > decoder_loss: 0.45040541887283325  (0.4532376000514397)
     | > postnet_loss: 0.3120424151420593  (0.3148706073944385)
     | > stopnet_loss: 0.0056395516730844975  (0.007591218902514531)
     | > loss: 0.1962515115737915  (0.19961827191022727)
     | > align_error: 0.5868851244449615  (0.6154642838698167)

   --> STEP: 14
     | > decoder_loss: 0.4567527174949646  (0.45348867986883434)
     | > postnet_loss: 0.31220632791519165  (0.31468030171734945)
     | > stopnet_loss: 0.004923402797430754  (0.007400660609294262)
     | > loss: 0.1971631646156311  (0.1994429071034704)
     | > align_error: 0.5560259222984314  (0.6112186866147178)

   --> STEP: 15
     | > decoder_loss: 0.4608314633369446  (0.45397819876670836)
     | > postnet_loss: 0.3165561854839325  (0.31480536063512166)
     | > stopnet_loss: 0.004960360936820507  (0.007237973964462677)
     | > loss: 0.19930726289749146  (0.19943386415640513)
     | > align_error: 0.5897830724716187  (0.6097896456718445)

   --> STEP: 16
     | > decoder_loss: 0.4613247513771057  (0.4544373583048582)
     | > postnet_loss: 0.3101850748062134  (0.3145165927708149)
     | > stopnet_loss: 0.005219882819801569  (0.007111843267921358)
     | > loss: 0.1980973333120346  (0.19935033097863197)
     | > align_error: 0.6071355938911438  (0.6096237674355507)

   --> STEP: 17
     | > decoder_loss: 0.4659610390663147  (0.4551152218790615)
     | > postnet_loss: 0.3180639147758484  (0.31472525877111096)
     | > stopnet_loss: 0.004870975855737925  (0.006980027537792921)
     | > loss: 0.20087721943855286  (0.1994401479468626)
     | > align_error: 0.5593134760856628  (0.6066643385326161)

   --> STEP: 18
     | > decoder_loss: 0.46169596910476685  (0.45548081894715625)
     | > postnet_loss: 0.31097570061683655  (0.31451694998476243)
     | > stopnet_loss: 0.005334591958671808  (0.00688861445006397)
     | > loss: 0.19850251078605652  (0.1993880569934845)
     | > align_error: 0.6049190163612366  (0.6065673761897616)

   --> STEP: 19
     | > decoder_loss: 0.46122536063194275  (0.45578316324635554)
     | > postnet_loss: 0.3109346926212311  (0.3143284101235239)
     | > stopnet_loss: 0.004942933097481728  (0.006786210168349116)
     | > loss: 0.19798295199871063  (0.19931410409902273)
     | > align_error: 0.6013984084129333  (0.6062953252541391)

   --> STEP: 20
     | > decoder_loss: 0.45553863048553467  (0.4557709366083145)
     | > postnet_loss: 0.30723345279693604  (0.31397366225719453)
     | > stopnet_loss: 0.004507099743932486  (0.006672254647128284)
     | > loss: 0.195200115442276  (0.19910840466618537)
     | > align_error: 0.6234468221664429  (0.6071529000997542)

   --> STEP: 21
     | > decoder_loss: 0.4525297284126282  (0.4556165933609009)
     | > postnet_loss: 0.3050260543823242  (0.31354758569172453)
     | > stopnet_loss: 0.003986377734690905  (0.006544355746536027)
     | > loss: 0.19337531924247742  (0.19883540059838975)
     | > align_error: 0.5608590245246887  (0.6049484298342749)

   --> STEP: 22
     | > decoder_loss: 0.4546004831790924  (0.455570406534455)
     | > postnet_loss: 0.30842041969299316  (0.3133145326917822)
     | > stopnet_loss: 0.004872570745646954  (0.006468365519222888)
     | > loss: 0.19562779366970062  (0.19868960028344934)
     | > align_error: 0.626258134841919  (0.6059170527891677)

   --> STEP: 23
     | > decoder_loss: 0.4272468686103821  (0.4543389483638432)
     | > postnet_loss: 0.29625290632247925  (0.3125727228496386)
     | > stopnet_loss: 0.004528180230408907  (0.006384009637100541)
     | > loss: 0.18540312349796295  (0.19811192737973254)
     | > align_error: 0.5681224465370178  (0.6042738090390742)

   --> STEP: 24
     | > decoder_loss: 0.4625558853149414  (0.4546813207368056)
     | > postnet_loss: 0.3124719262123108  (0.31256852298974996)
     | > stopnet_loss: 0.004398114047944546  (0.006301263987552375)
     | > loss: 0.19815506041049957  (0.19811372458934784)
     | > align_error: 0.5805213451385498  (0.603284123043219)

   --> STEP: 25
     | > decoder_loss: 0.4611184597015381  (0.4549388062953949)
     | > postnet_loss: 0.3088952302932739  (0.31242159128189095)
     | > stopnet_loss: 0.00369289331138134  (0.006196929160505533)
     | > loss: 0.1961963176727295  (0.1980370283126831)
     | > align_error: 0.5585474371910095  (0.6014946556091306)

   --> STEP: 26
     | > decoder_loss: 0.43624693155288696  (0.45421988803606766)
     | > postnet_loss: 0.2974902391433716  (0.3118473085073325)
     | > stopnet_loss: 0.004421578720211983  (0.006128646451263473)
     | > loss: 0.18785586953163147  (0.19764544528264266)
     | > align_error: 0.5478818118572235  (0.5994326231571342)

   --> STEP: 27
     | > decoder_loss: 0.4341278076171875  (0.4534757369094425)
     | > postnet_loss: 0.2937345802783966  (0.31117646672107563)
     | > stopnet_loss: 0.003947353921830654  (0.006047857839062258)
     | > loss: 0.18591293692588806  (0.1972109079360962)
     | > align_error: 0.5423596799373627  (0.5973188104452908)

   --> STEP: 28
     | > decoder_loss: 0.4384908676147461  (0.45294056300606045)
     | > postnet_loss: 0.2973497807979584  (0.3106826565095357)
     | > stopnet_loss: 0.003937895409762859  (0.005972502038015851)
     | > loss: 0.18789806962013245  (0.19687830656766891)
     | > align_error: 0.5671691596508026  (0.5962420372026305)

   --> STEP: 29
     | > decoder_loss: 0.43391844630241394  (0.45228462794731406)
     | > postnet_loss: 0.2938019037246704  (0.3101005615859197)
     | > stopnet_loss: 0.003602442564442754  (0.005890775849271951)
     | > loss: 0.18553254008293152  (0.19648707324060902)
     | > align_error: 0.541516900062561  (0.5943549635081453)

   --> STEP: 30
     | > decoder_loss: 0.4346582889556885  (0.45169708331425984)
     | > postnet_loss: 0.2947187125682831  (0.3095878332853318)
     | > stopnet_loss: 0.0029256618581712246  (0.00579193871623526)
     | > loss: 0.18526992201805115  (0.19611316819985708)
     | > align_error: 0.5345837771892548  (0.592362590630849)

   --> STEP: 31
     | > decoder_loss: 0.43488091230392456  (0.4511546261848942)
     | > postnet_loss: 0.2959766387939453  (0.30914876249528705)
     | > stopnet_loss: 0.003995716106146574  (0.0057339960513936895)
     | > loss: 0.18671010434627533  (0.19580984355941897)
     | > align_error: 0.5599975287914276  (0.5913185563779644)

   --> STEP: 32
     | > decoder_loss: 0.44151002168655396  (0.45085323229432106)
     | > postnet_loss: 0.2992405593395233  (0.30883913114666944)
     | > stopnet_loss: 0.0038876247126609087  (0.00567629694705829)
     | > loss: 0.1890752613544464  (0.19559938786551356)
     | > align_error: 0.5320174992084503  (0.5894653983414171)

   --> STEP: 33
     | > decoder_loss: 0.43896767497062683  (0.45049306389057275)
     | > postnet_loss: 0.29749366641044617  (0.3084953291849657)
     | > stopnet_loss: 0.0040435572154819965  (0.005626819985495372)
     | > loss: 0.18815889954566956  (0.19537391852248798)
     | > align_error: 0.5469363331794739  (0.5881766387910552)

   --> STEP: 34
     | > decoder_loss: 0.4441232979297638  (0.4503057178329019)
     | > postnet_loss: 0.2986717224121094  (0.30820639957399937)
     | > stopnet_loss: 0.0033479188568890095  (0.005559793481712832)
     | > loss: 0.18904666602611542  (0.19518782286082997)
     | > align_error: 0.5645128190517426  (0.5874806440928401)

   --> STEP: 35
     | > decoder_loss: 0.44163209199905396  (0.4500578999519348)
     | > postnet_loss: 0.29769495129585266  (0.307906072480338)
     | > stopnet_loss: 0.003531179390847683  (0.005501833079116685)
     | > loss: 0.1883629411458969  (0.19499282624040332)
     | > align_error: 0.5343741774559021  (0.5859633164746418)

   --> STEP: 36
     | > decoder_loss: 0.44858863949775696  (0.450017087161541)
     | > postnet_loss: 0.3025625944137573  (0.3077576425340441)
     | > stopnet_loss: 0.0037153088487684727  (0.005452207406051457)
     | > loss: 0.19150310754776  (0.1948958896100521)
     | > align_error: 0.6347165703773499  (0.5873175735274949)

   --> STEP: 37
     | > decoder_loss: 0.4408247470855713  (0.4497686455378661)
     | > postnet_loss: 0.29895851016044617  (0.3075198281455685)
     | > stopnet_loss: 0.0036005936563014984  (0.00540216379119335)
     | > loss: 0.18854641914367676  (0.19472428230015007)
     | > align_error: 0.5197806656360626  (0.5854922516925913)

   --> STEP: 38
     | > decoder_loss: 0.4282618761062622  (0.44920267792124496)
     | > postnet_loss: 0.29196855425834656  (0.30711058409590475)
     | > stopnet_loss: 0.0031589760910719633  (0.005343132535926998)
     | > loss: 0.18321658670902252  (0.19442144820564672)
     | > align_error: 0.5521190166473389  (0.5846140086650846)

   --> STEP: 39
     | > decoder_loss: 0.4430846869945526  (0.4490458063590221)
     | > postnet_loss: 0.3016471266746521  (0.3069704954440778)
     | > stopnet_loss: 0.0035085463896393776  (0.005296091865509367)
     | > loss: 0.18969149887561798  (0.19430016745359469)
     | > align_error: 0.5466468036174774  (0.5836404905869409)

   --> STEP: 40
     | > decoder_loss: 0.44004517793655396  (0.44882079064846037)
     | > postnet_loss: 0.3002831041812897  (0.3068033106625081)
     | > stopnet_loss: 0.003050575265660882  (0.005239953950513155)
     | > loss: 0.1881326586008072  (0.19414597973227501)
     | > align_error: 0.5847792625427246  (0.5836689598858354)

   --> STEP: 41
     | > decoder_loss: 0.430431067943573  (0.44837226082639)
     | > postnet_loss: 0.2923322319984436  (0.3064503575243602)
     | > stopnet_loss: 0.003767451737076044  (0.0052040392623805415)
     | > loss: 0.18445827066898346  (0.19390969414536546)
     | > align_error: 0.5044025182723999  (0.5817356320416054)

   --> STEP: 42
     | > decoder_loss: 0.4356256425380707  (0.4480687699147633)
     | > postnet_loss: 0.29511722922325134  (0.30618052113623856)
     | > stopnet_loss: 0.003306867089122534  (0.00515886849635059)
     | > loss: 0.18599258363246918  (0.19372119151410602)
     | > align_error: 0.5804461240768433  (0.5817049294710158)

   --> STEP: 43
     | > decoder_loss: 0.43414217233657837  (0.4477448955524799)
     | > postnet_loss: 0.29387661814689636  (0.30589438385741663)
     | > stopnet_loss: 0.002943390980362892  (0.005107345763420643)
     | > loss: 0.18494808673858643  (0.19351716582165207)
     | > align_error: 0.5526229441165924  (0.5810286042302153)

   --> STEP: 44
     | > decoder_loss: 0.4528527855873108  (0.44786098396236246)
     | > postnet_loss: 0.30414438247680664  (0.3058546110987664)
     | > stopnet_loss: 0.002686325227841735  (0.005052322569430213)
     | > loss: 0.19193561375141144  (0.19348122145641933)
     | > align_error: 0.5517365634441376  (0.5803628760305317)

   --> STEP: 45
     | > decoder_loss: 0.44532325863838196  (0.447804590066274)
     | > postnet_loss: 0.30308136343955994  (0.3057929833730062)
     | > stopnet_loss: 0.003337555332109332  (0.005014216630823082)
     | > loss: 0.19043871760368347  (0.19341361025969186)
     | > align_error: 0.5531444549560547  (0.5797580222288766)

   --> STEP: 46
     | > decoder_loss: 0.43596351146698  (0.4475471753141154)
     | > postnet_loss: 0.2943216860294342  (0.3055436073437981)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3611534472667809 (+0.011225414998603467)
     | > avg_decoder_loss: 0.44304516640576447 (+0.0014943841731909213)
     | > avg_postnet_loss: 0.3020466674457897 (+0.0016161745244805958)
     | > avg_stopnet_loss: 0.004411333356983959 (+3.2139942049954143e-06)
     | > avg_loss: 0.1906842916752353 (+0.0007808531324068613)
     | > avg_align_error: 0.5726562602953476 (+0.0016675419879680353)


 > EPOCH: 98/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 11:16:35)

   --> TIME: 2025-12-28 11:16:38 -- STEP: 2/150 -- GLOBAL_STEP: 14800
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45581966638565063  (0.46151404082775116)
     | > postnet_loss: 0.39650315046310425  (0.40079696476459503)
     | > stopnet_loss: 0.015141374431550503  (0.015437196474522352)
     | > loss: 0.2282220721244812  (0.2310149446129799)
     | > align_error: 0.7313306927680969  (0.7230461984872818)
     | > grad_norm: tensor(0.3046, device='cuda:0')  (tensor(0.3194, device='cuda:0'))
     | > step_time: 0.451  (0.4241067171096802)
     | > loader_time: 0.6288  (0.5847266912460327)


   --> TIME: 2025-12-28 11:17:16 -- STEP: 27/150 -- GLOBAL_STEP: 14825
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.4814848303794861  (0.4740681935239721)
     | > postnet_loss: 0.4030606150627136  (0.40186324605235346)
     | > stopnet_loss: 0.005979349836707115  (0.009591688384750375)
     | > loss: 0.2271157056093216  (0.22857454860651935)
     | > align_error: 0.6589081883430481  (0.6686567686222218)
     | > grad_norm: tensor(0.1579, device='cuda:0')  (tensor(0.2411, device='cuda:0'))
     | > step_time: 0.9954  (0.6753759384155273)
     | > loader_time: 1.0022  (0.8192196510456227)


   --> TIME: 2025-12-28 11:18:11 -- STEP: 52/150 -- GLOBAL_STEP: 14850
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4844404458999634  (0.48062260907429916)
     | > postnet_loss: 0.4004994034767151  (0.40338285668538165)
     | > stopnet_loss: 0.00434530945494771  (0.0075400632340461024)
     | > loss: 0.22558027505874634  (0.22854143008589745)
     | > align_error: 0.6593913733959198  (0.6473432005597993)
     | > grad_norm: tensor(0.1965, device='cuda:0')  (tensor(0.2355, device='cuda:0'))
     | > step_time: 1.2361  (0.9115147453088027)
     | > loader_time: 1.1409  (0.918502885561723)


   --> TIME: 2025-12-28 11:19:18 -- STEP: 77/150 -- GLOBAL_STEP: 14875
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49148139357566833  (0.48339475362331835)
     | > postnet_loss: 0.40333834290504456  (0.4029817867588687)
     | > stopnet_loss: 0.004448071122169495  (0.006449087099595505)
     | > loss: 0.22815300524234772  (0.22804322316275014)
     | > align_error: 0.6108563542366028  (0.6355904998717369)
     | > grad_norm: tensor(0.1642, device='cuda:0')  (tensor(0.2181, device='cuda:0'))
     | > step_time: 1.4776  (1.0781409337923127)
     | > loader_time: 1.4197  (1.029490579258312)


   --> TIME: 2025-12-28 11:20:41 -- STEP: 102/150 -- GLOBAL_STEP: 14900
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49423491954803467  (0.48462867444636776)
     | > postnet_loss: 0.402522474527359  (0.40230491698956955)
     | > stopnet_loss: 0.003409417811781168  (0.005772450550769768)
     | > loss: 0.22759875655174255  (0.22750584883432762)
     | > align_error: 0.6061259806156158  (0.6308158817244508)
     | > grad_norm: tensor(0.2515, device='cuda:0')  (tensor(0.2171, device='cuda:0'))
     | > step_time: 1.7682  (1.2167983545976528)
     | > loader_time: 1.6121  (1.1825682859794764)


   --> TIME: 2025-12-28 11:22:11 -- STEP: 127/150 -- GLOBAL_STEP: 14925
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49465569853782654  (0.4855383350623874)
     | > postnet_loss: 0.40252843499183655  (0.40172514413285443)
     | > stopnet_loss: 0.0031279665417969227  (0.005298640036324818)
     | > loss: 0.2274239957332611  (0.22711451023113072)
     | > align_error: 0.5982523262500763  (0.6269071735735012)
     | > grad_norm: tensor(0.1918, device='cuda:0')  (tensor(0.2077, device='cuda:0'))
     | > step_time: 2.0732  (1.3440212095816304)
     | > loader_time: 1.7123  (1.2944409884805752)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4644860625267029  (0.4644860625267029)
     | > postnet_loss: 0.33299270272254944  (0.33299270272254944)
     | > stopnet_loss: 0.012281405739486217  (0.012281405739486217)
     | > loss: 0.21165110170841217  (0.21165110170841217)
     | > align_error: 0.7180908024311066  (0.7180908024311066)

   --> STEP: 1
     | > decoder_loss: 0.44550621509552  (0.44550621509552)
     | > postnet_loss: 0.3202786147594452  (0.3202786147594452)
     | > stopnet_loss: 0.009688390418887138  (0.009688390418887138)
     | > loss: 0.2011346071958542  (0.2011346071958542)
     | > align_error: 0.6587735414505005  (0.6587735414505005)

   --> STEP: 2
     | > decoder_loss: 0.4408648610115051  (0.4431855380535126)
     | > postnet_loss: 0.3119596540927887  (0.31611913442611694)
     | > stopnet_loss: 0.011073579080402851  (0.010380984749644995)
     | > loss: 0.19927971065044403  (0.2002071589231491)
     | > align_error: 0.6553739011287689  (0.6570737212896347)

   --> STEP: 3
     | > decoder_loss: 0.4435921907424927  (0.4433210889498393)
     | > postnet_loss: 0.30985742807388306  (0.3140318989753723)
     | > stopnet_loss: 0.008313030004501343  (0.009691666501263777)
     | > loss: 0.19667543470859528  (0.19902991751829782)
     | > align_error: 0.7341769337654114  (0.6827747921148936)

   --> STEP: 4
     | > decoder_loss: 0.45056062936782837  (0.44513097405433655)
     | > postnet_loss: 0.3194475769996643  (0.3153858184814453)
     | > stopnet_loss: 0.0082731693983078  (0.009337042225524783)
     | > loss: 0.20077522099018097  (0.19946624338626862)
     | > align_error: 0.6028879880905151  (0.662803091108799)

   --> STEP: 5
     | > decoder_loss: 0.43145835399627686  (0.4423964500427246)
     | > postnet_loss: 0.30158549547195435  (0.3126257538795471)
     | > stopnet_loss: 0.008272426202893257  (0.009124119020998477)
     | > loss: 0.1915333867073059  (0.19787967205047607)
     | > align_error: 0.6413882374763489  (0.658520120382309)

   --> STEP: 6
     | > decoder_loss: 0.4475356340408325  (0.4432529807090759)
     | > postnet_loss: 0.31291529536247253  (0.31267401079336804)
     | > stopnet_loss: 0.007282864302396774  (0.008817243234564861)
     | > loss: 0.19739560782909393  (0.19779899468024573)
     | > align_error: 0.593103438615799  (0.6476173400878906)

   --> STEP: 7
     | > decoder_loss: 0.4579591751098633  (0.4453538656234741)
     | > postnet_loss: 0.31242477893829346  (0.3126384062426431)
     | > stopnet_loss: 0.006353146396577358  (0.008465229400566645)
     | > loss: 0.19894912838935852  (0.19796329949583327)
     | > align_error: 0.5785388350486755  (0.6377489822251456)

   --> STEP: 8
     | > decoder_loss: 0.4527921974658966  (0.44628365710377693)
     | > postnet_loss: 0.3126741647720337  (0.3126428760588169)
     | > stopnet_loss: 0.007567145396023989  (0.008352968899998814)
     | > loss: 0.19893373548984528  (0.19808460399508476)
     | > align_error: 0.5746141970157623  (0.6298571340739727)

   --> STEP: 9
     | > decoder_loss: 0.4496363699436188  (0.44665618075264824)
     | > postnet_loss: 0.31248441338539124  (0.31262526909510296)
     | > stopnet_loss: 0.006680744234472513  (0.00816716615938478)
     | > loss: 0.19721093773841858  (0.1979875299665663)
     | > align_error: 0.5907416343688965  (0.6255109674400754)

   --> STEP: 10
     | > decoder_loss: 0.4789545238018036  (0.44988601505756376)
     | > postnet_loss: 0.32807913422584534  (0.3141706556081772)
     | > stopnet_loss: 0.005823273677378893  (0.007932776911184191)
     | > loss: 0.20758168399333954  (0.19894694536924362)
     | > align_error: 0.5856934189796448  (0.6215292125940323)

   --> STEP: 11
     | > decoder_loss: 0.4634213447570801  (0.4511164995757016)
     | > postnet_loss: 0.3178652822971344  (0.31450653076171875)
     | > stopnet_loss: 0.005910694133490324  (0.007748951204121113)
     | > loss: 0.20123234391212463  (0.1991547088731419)
     | > align_error: 0.5940681993961334  (0.6190327568487688)

   --> STEP: 12
     | > decoder_loss: 0.45865193009376526  (0.4517444521188736)
     | > postnet_loss: 0.3106391727924347  (0.3141842509309451)
     | > stopnet_loss: 0.007885872386395931  (0.007760361302644014)
     | > loss: 0.2002086490392685  (0.19924253722031912)
     | > align_error: 0.5869609415531158  (0.616360105574131)

   --> STEP: 13
     | > decoder_loss: 0.4485182464122772  (0.4514962824491354)
     | > postnet_loss: 0.31084132194519043  (0.3139271025474255)
     | > stopnet_loss: 0.00566793093457818  (0.007599405120485104)
     | > loss: 0.19550782442092896  (0.19895525162036604)
     | > align_error: 0.5854499042034149  (0.6139823977763836)

   --> STEP: 14
     | > decoder_loss: 0.4563744068145752  (0.4518447199038097)
     | > postnet_loss: 0.3116243779659271  (0.3137626222201756)
     | > stopnet_loss: 0.00497567281126976  (0.007411995669826865)
     | > loss: 0.19697538018226624  (0.19881383223193033)
     | > align_error: 0.5541394650936127  (0.6097079025847572)

   --> STEP: 15
     | > decoder_loss: 0.4569459557533264  (0.45218480229377744)
     | > postnet_loss: 0.31415238976478577  (0.3137886067231496)
     | > stopnet_loss: 0.0049926647916436195  (0.007250706944614649)
     | > loss: 0.1977672576904297  (0.19874406059583027)
     | > align_error: 0.5880750417709351  (0.6082657118638356)

   --> STEP: 16
     | > decoder_loss: 0.45781826972961426  (0.45253689400851727)
     | > postnet_loss: 0.30777275562286377  (0.31341261602938175)
     | > stopnet_loss: 0.005265118554234505  (0.00712660767021589)
     | > loss: 0.19666287302970886  (0.1986139863729477)
     | > align_error: 0.6057993769645691  (0.6081115659326315)

   --> STEP: 17
     | > decoder_loss: 0.46418020129203796  (0.45322179443695965)
     | > postnet_loss: 0.31654229760169983  (0.3135967149454005)
     | > stopnet_loss: 0.004853425547480583  (0.006992891074760872)
     | > loss: 0.20003405213356018  (0.1986975196529837)
     | > align_error: 0.558106392621994  (0.6051700851496529)

   --> STEP: 18
     | > decoder_loss: 0.45804867148399353  (0.453489954272906)
     | > postnet_loss: 0.30860623717308044  (0.31331946618027157)
     | > stopnet_loss: 0.005326468497514725  (0.0069003120426916415)
     | > loss: 0.19699019193649292  (0.19860266811317867)
     | > align_error: 0.603615403175354  (0.6050837139288584)

   --> STEP: 19
     | > decoder_loss: 0.45625782012939453  (0.4536356314232475)
     | > postnet_loss: 0.30808159708976746  (0.31304378885971873)
     | > stopnet_loss: 0.00477753859013319  (0.006788587124135934)
     | > loss: 0.19586239755153656  (0.19845844334677645)
     | > align_error: 0.5993157625198364  (0.6047801375389099)

   --> STEP: 20
     | > decoder_loss: 0.45233193039894104  (0.45357044637203214)
     | > postnet_loss: 0.3048239052295685  (0.3126327946782112)
     | > stopnet_loss: 0.004539701621979475  (0.00667614284902811)
     | > loss: 0.19382865726947784  (0.19822695404291152)
     | > align_error: 0.6224921345710754  (0.6056657373905182)

   --> STEP: 21
     | > decoder_loss: 0.4511491358280182  (0.45345514586993624)
     | > postnet_loss: 0.3038688004016876  (0.31221546161742436)
     | > stopnet_loss: 0.004011911805719137  (0.006549274704108636)
     | > loss: 0.19276639819145203  (0.19796692757379442)
     | > align_error: 0.5596616566181183  (0.6034750668775468)

   --> STEP: 22
     | > decoder_loss: 0.4511515498161316  (0.45335043695839966)
     | > postnet_loss: 0.3058755695819855  (0.3119272847067226)
     | > stopnet_loss: 0.004819893278181553  (0.006470666457475586)
     | > loss: 0.19407668709754944  (0.19779009846123782)
     | > align_error: 0.6252822875976562  (0.6044663041830064)

   --> STEP: 23
     | > decoder_loss: 0.42537060379981995  (0.452133922473244)
     | > postnet_loss: 0.29475393891334534  (0.3111806174983149)
     | > stopnet_loss: 0.004562816116958857  (0.006387716442670511)
     | > loss: 0.18459394574165344  (0.1972163526908211)
     | > align_error: 0.566748708486557  (0.6028264087179434)

   --> STEP: 24
     | > decoder_loss: 0.45934590697288513  (0.45243442182739574)
     | > postnet_loss: 0.31017863750457764  (0.3111388683319092)
     | > stopnet_loss: 0.004429436754435301  (0.006306121455660711)
     | > loss: 0.19681057333946228  (0.19719944521784782)
     | > align_error: 0.5790947079658508  (0.6018375878532728)

   --> STEP: 25
     | > decoder_loss: 0.4581890106201172  (0.45266460537910463)
     | > postnet_loss: 0.30686384439468384  (0.31096786737442017)
     | > stopnet_loss: 0.00374108599498868  (0.006203520037233829)
     | > loss: 0.19500429928302765  (0.197111639380455)
     | > align_error: 0.5573281943798065  (0.6000572121143342)

   --> STEP: 26
     | > decoder_loss: 0.4336511790752411  (0.45193331975203294)
     | > postnet_loss: 0.2956311106681824  (0.3103779921164879)
     | > stopnet_loss: 0.004391893744468689  (0.006133842102896709)
     | > loss: 0.18671245872974396  (0.19671167089388922)
     | > align_error: 0.5464160442352295  (0.5979940902728301)

   --> STEP: 27
     | > decoder_loss: 0.4308345317840576  (0.45115188316062643)
     | > postnet_loss: 0.2912348508834839  (0.30966898688563593)
     | > stopnet_loss: 0.003939920105040073  (0.006052585732605722)
     | > loss: 0.18445727229118347  (0.19625780427897419)
     | > align_error: 0.540945827960968  (0.595881191668687)

   --> STEP: 28
     | > decoder_loss: 0.43720105290412903  (0.4506536392228944)
     | > postnet_loss: 0.29603061079978943  (0.3091819020254271)
     | > stopnet_loss: 0.003955841064453125  (0.005977701994457415)
     | > loss: 0.18726375699043274  (0.1959365883043834)
     | > align_error: 0.5660495758056641  (0.5948157768164363)

   --> STEP: 29
     | > decoder_loss: 0.43228715658187866  (0.45002031223527317)
     | > postnet_loss: 0.29224342107772827  (0.3085978164755065)
     | > stopnet_loss: 0.0036013550125062466  (0.005895758995079789)
     | > loss: 0.18473400175571442  (0.19555029221649828)
     | > align_error: 0.5403552651405334  (0.5929378281379568)

   --> STEP: 30
     | > decoder_loss: 0.4328588545322418  (0.4494482636451721)
     | > postnet_loss: 0.2930925786495209  (0.3080809752146403)
     | > stopnet_loss: 0.002887433860450983  (0.005795481490592161)
     | > loss: 0.18437528610229492  (0.1951777920126915)
     | > align_error: 0.5330518484115601  (0.5909416288137436)

   --> STEP: 31
     | > decoder_loss: 0.43161267042160034  (0.4488729219282827)
     | > postnet_loss: 0.2934475243091583  (0.30760892841123766)
     | > stopnet_loss: 0.0039941370487213135  (0.0057373736053705215)
     | > loss: 0.18525919318199158  (0.1948578372117012)
     | > align_error: 0.5590670108795166  (0.5899134153319944)

   --> STEP: 32
     | > decoder_loss: 0.4401932656764984  (0.44860168267041445)
     | > postnet_loss: 0.29783159494400024  (0.3073033867403865)
     | > stopnet_loss: 0.0038775005377829075  (0.005679252572008409)
     | > loss: 0.18838371336460114  (0.1946555208414793)
     | > align_error: 0.5305175483226776  (0.5880572944879532)

   --> STEP: 33
     | > decoder_loss: 0.4363267123699188  (0.44822971387342975)
     | > postnet_loss: 0.29526689648628235  (0.30693864461147424)
     | > stopnet_loss: 0.004056967794895172  (0.005630092427247401)
     | > loss: 0.18695536255836487  (0.19442218271168796)
     | > align_error: 0.5456234812736511  (0.5867714213602471)

   --> STEP: 34
     | > decoder_loss: 0.4415442645549774  (0.4480330830111223)
     | > postnet_loss: 0.2966406047344208  (0.3066357610856785)
     | > stopnet_loss: 0.003363377880305052  (0.005563424352337332)
     | > loss: 0.1879095882177353  (0.19423063581480698)
     | > align_error: 0.5633694529533386  (0.5860831281718086)

   --> STEP: 35
     | > decoder_loss: 0.4405432939529419  (0.4478190890380314)
     | > postnet_loss: 0.2964180111885071  (0.3063438253743308)
     | > stopnet_loss: 0.003530307672917843  (0.005505335304353918)
     | > loss: 0.18777063488960266  (0.19404606435980115)
     | > align_error: 0.5331142544746399  (0.5845697317804609)

   --> STEP: 36
     | > decoder_loss: 0.4463462829589844  (0.4477781777580579)
     | > postnet_loss: 0.300514817237854  (0.3061819084816509)
     | > stopnet_loss: 0.0037101891357451677  (0.005455470133003675)
     | > loss: 0.19042547047138214  (0.19394549230734506)
     | > align_error: 0.6335188746452332  (0.5859294301933713)

   --> STEP: 37
     | > decoder_loss: 0.43828651309013367  (0.44752164628054647)
     | > postnet_loss: 0.2969060242176056  (0.30593120890694697)
     | > stopnet_loss: 0.0036003768909722567  (0.005405332477813637)
     | > loss: 0.1873985081911087  (0.19376854679069003)
     | > align_error: 0.5184530019760132  (0.5841057429442534)

   --> STEP: 38
     | > decoder_loss: 0.4263378381729126  (0.44696417764613505)
     | > postnet_loss: 0.29002952575683594  (0.3055127435608914)
     | > stopnet_loss: 0.003178452607244253  (0.005346730375956548)
     | > loss: 0.18227028846740723  (0.1934659610453405)
     | > align_error: 0.551050990819931  (0.583235881046245)

   --> STEP: 39
     | > decoder_loss: 0.4418163597583771  (0.44683218231567967)
     | > postnet_loss: 0.3001180589199066  (0.30537441831368667)
     | > stopnet_loss: 0.0035078402142971754  (0.0052995793461704105)
     | > loss: 0.18899144232273102  (0.19335122979604283)
     | > align_error: 0.5453596711158752  (0.5822646961762354)

   --> STEP: 40
     | > decoder_loss: 0.438524454832077  (0.44662448912858965)
     | > postnet_loss: 0.2983629107475281  (0.3051991306245327)
     | > stopnet_loss: 0.0030640566255897284  (0.005243691278155893)
     | > loss: 0.1872858852148056  (0.1931995961815119)
     | > align_error: 0.5835371017456055  (0.5822965063154697)

   --> STEP: 41
     | > decoder_loss: 0.4286666214466095  (0.4461864923558584)
     | > postnet_loss: 0.2905527651309967  (0.3048419021978611)
     | > stopnet_loss: 0.003761161584407091  (0.0052075320173327515)
     | > loss: 0.18356600403785706  (0.19296463051947152)
     | > align_error: 0.5026741623878479  (0.5803544979269911)

   --> STEP: 42
     | > decoder_loss: 0.4342666268348694  (0.4459026860339301)
     | > postnet_loss: 0.29343605041503906  (0.30457033429827013)
     | > stopnet_loss: 0.003321003867313266  (0.005162614680427525)
     | > loss: 0.18524667620658875  (0.1927808697024981)
     | > align_error: 0.5792255401611328  (0.5803276179801851)

   --> STEP: 43
     | > decoder_loss: 0.43291041254997253  (0.44560054013895434)
     | > postnet_loss: 0.2921992242336273  (0.3042826340642087)
     | > stopnet_loss: 0.0029732550028711557  (0.005111699339089005)
     | > loss: 0.18425066769123077  (0.19258249291153842)
     | > align_error: 0.5513858199119568  (0.579654552908831)

   --> STEP: 44
     | > decoder_loss: 0.4514201581478119  (0.4457328041846102)
     | > postnet_loss: 0.30255794525146484  (0.30424343659119174)
     | > stopnet_loss: 0.0026996673550456762  (0.005056880430360748)
     | > loss: 0.19119420647621155  (0.19255094094709915)
     | > align_error: 0.5504106283187866  (0.5789899182590572)

   --> STEP: 45
     | > decoder_loss: 0.4433269202709198  (0.4456793400976393)
     | > postnet_loss: 0.301207035779953  (0.30417596101760863)
     | > stopnet_loss: 0.0033143972977995872  (0.005018158582970499)
     | > loss: 0.18944787979125977  (0.19248198403252495)
     | > align_error: 0.5520123243331909  (0.5783904161718157)

   --> STEP: 46
     | > decoder_loss: 0.43447554111480713  (0.4454357792501864)
     | > postnet_loss: 0.2927817702293396  (0.30392826121786365)
     | > stopnet_loss: 0.0032241318840533495  (0.004979158002559257)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.360790769259135 (-0.0003626780076458891)
     | > avg_decoder_loss: 0.4416819309646433 (-0.0013632354411211578)
     | > avg_postnet_loss: 0.3006946512243964 (-0.0013520162213932485)
     | > avg_stopnet_loss: 0.004410496440179872 (-8.369168040872274e-07)
     | > avg_loss: 0.19000464248837848 (-0.0006796491868568122)
     | > avg_align_error: 0.5712772914857576 (-0.0013789688095899866)


 > EPOCH: 99/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 11:25:40)

   --> TIME: 2025-12-28 11:25:42 -- STEP: 1/150 -- GLOBAL_STEP: 14950
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46768447756767273  (0.46768447756767273)
     | > postnet_loss: 0.40403756499290466  (0.40403756499290466)
     | > stopnet_loss: 0.015047414228320122  (0.015047414228320122)
     | > loss: 0.23297792673110962  (0.23297792673110962)
     | > align_error: 0.7127873301506042  (0.7127873301506042)
     | > grad_norm: tensor(0.3044, device='cuda:0')  (tensor(0.3044, device='cuda:0'))
     | > step_time: 0.3623  (0.3623073101043701)
     | > loader_time: 0.6374  (0.6374075412750244)


   --> TIME: 2025-12-28 11:26:19 -- STEP: 26/150 -- GLOBAL_STEP: 14975
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.4840337932109833  (0.4720869717689661)
     | > postnet_loss: 0.4066097140312195  (0.4006595772046309)
     | > stopnet_loss: 0.006880508735775948  (0.009532286534802273)
     | > loss: 0.2295413762331009  (0.22771892410058242)
     | > align_error: 0.6203029751777649  (0.6679023584494224)
     | > grad_norm: tensor(0.1573, device='cuda:0')  (tensor(0.2536, device='cuda:0'))
     | > step_time: 0.8895  (0.6647824965990508)
     | > loader_time: 0.9156  (0.8156245488386887)


   --> TIME: 2025-12-28 11:27:14 -- STEP: 51/150 -- GLOBAL_STEP: 15000
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48875367641448975  (0.4793136359429827)
     | > postnet_loss: 0.4036513864994049  (0.4024982738728617)
     | > stopnet_loss: 0.004376222379505634  (0.007503450921207085)
     | > loss: 0.22747747600078583  (0.22795642824733958)
     | > align_error: 0.6118032038211823  (0.646181011316823)
     | > grad_norm: tensor(0.1598, device='cuda:0')  (tensor(0.2277, device='cuda:0'))
     | > step_time: 1.3844  (0.8904534601697734)
     | > loader_time: 1.1904  (0.922972090104047)


   --> TIME: 2025-12-28 11:28:20 -- STEP: 76/150 -- GLOBAL_STEP: 15025
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49390289187431335  (0.48230082502490595)
     | > postnet_loss: 0.4043126702308655  (0.40226298021642787)
     | > stopnet_loss: 0.0039020555559545755  (0.006395079324168988)
     | > loss: 0.22845594584941864  (0.22753603050583288)
     | > align_error: 0.6042240858078003  (0.6351365525471536)
     | > grad_norm: tensor(0.2657, device='cuda:0')  (tensor(0.2213, device='cuda:0'))
     | > step_time: 1.6247  (1.0651871499262364)
     | > loader_time: 1.3385  (1.0291413570705215)


   --> TIME: 2025-12-28 11:29:40 -- STEP: 101/150 -- GLOBAL_STEP: 15050
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48985207080841064  (0.48363495168119375)
     | > postnet_loss: 0.40124985575675964  (0.40161990971848516)
     | > stopnet_loss: 0.0037311885971575975  (0.00573889916246333)
     | > loss: 0.22650668025016785  (0.2270526148305081)
     | > align_error: 0.6068130135536194  (0.6305298899660015)
     | > grad_norm: tensor(0.2047, device='cuda:0')  (tensor(0.2128, device='cuda:0'))
     | > step_time: 1.7516  (1.2223530618271026)
     | > loader_time: 1.4801  (1.1454515433547523)


   --> TIME: 2025-12-28 11:31:08 -- STEP: 126/150 -- GLOBAL_STEP: 15075
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4929414987564087  (0.48466795020633274)
     | > postnet_loss: 0.4004605710506439  (0.4010824788184393)
     | > stopnet_loss: 0.002969910390675068  (0.005264821240589734)
     | > loss: 0.22632043063640594  (0.2267024287628749)
     | > align_error: 0.6106769442558289  (0.6267272865488415)
     | > grad_norm: tensor(0.2195, device='cuda:0')  (tensor(0.2017, device='cuda:0'))
     | > step_time: 1.896  (1.3553550678586204)
     | > loader_time: 1.6254  (1.2368667560910427)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4663138687610626  (0.4663138687610626)
     | > postnet_loss: 0.33905869722366333  (0.33905869722366333)
     | > stopnet_loss: 0.01222609169781208  (0.01222609169781208)
     | > loss: 0.21356923878192902  (0.21356923878192902)
     | > align_error: 0.7184798419475555  (0.7184798419475555)

   --> STEP: 1
     | > decoder_loss: 0.4487004280090332  (0.4487004280090332)
     | > postnet_loss: 0.3288572430610657  (0.3288572430610657)
     | > stopnet_loss: 0.009639359079301357  (0.009639359079301357)
     | > loss: 0.20402877032756805  (0.20402877032756805)
     | > align_error: 0.6591907143592834  (0.6591907143592834)

   --> STEP: 2
     | > decoder_loss: 0.4419332444667816  (0.4453168362379074)
     | > postnet_loss: 0.3164426386356354  (0.3226499408483505)
     | > stopnet_loss: 0.011150212027132511  (0.010394785553216934)
     | > loss: 0.20074418187141418  (0.20238647609949112)
     | > align_error: 0.6557369828224182  (0.6574638485908508)

   --> STEP: 3
     | > decoder_loss: 0.4456486105918884  (0.44542742768923443)
     | > postnet_loss: 0.3160051107406616  (0.3204349974791209)
     | > stopnet_loss: 0.008395842276513577  (0.009728471127649149)
     | > loss: 0.19880926609039307  (0.2011940727631251)
     | > align_error: 0.7344372868537903  (0.6831216613451639)

   --> STEP: 4
     | > decoder_loss: 0.45281490683555603  (0.4472742974758148)
     | > postnet_loss: 0.325843870639801  (0.3217872157692909)
     | > stopnet_loss: 0.008206394501030445  (0.009347951970994473)
     | > loss: 0.20287108421325684  (0.20161332562565804)
     | > align_error: 0.6033653318881989  (0.6631825789809227)

   --> STEP: 5
     | > decoder_loss: 0.4331635534763336  (0.4444521486759186)
     | > postnet_loss: 0.3067096471786499  (0.31877170205116273)
     | > stopnet_loss: 0.008273599669337273  (0.009133081510663032)
     | > loss: 0.1932418942451477  (0.19993903934955598)
     | > align_error: 0.6422173380851746  (0.658989530801773)

   --> STEP: 6
     | > decoder_loss: 0.4501921236515045  (0.44540881117184955)
     | > postnet_loss: 0.319398432970047  (0.3188761572043101)
     | > stopnet_loss: 0.007262063678354025  (0.008821245205278197)
     | > loss: 0.19965970516204834  (0.19989248365163803)
     | > align_error: 0.5934450030326843  (0.6480654428402582)

   --> STEP: 7
     | > decoder_loss: 0.4592781066894531  (0.4473901391029358)
     | > postnet_loss: 0.3168814778327942  (0.31859120300837923)
     | > stopnet_loss: 0.006333759054541588  (0.008465890040887254)
     | > loss: 0.20037364959716797  (0.1999612216438566)
     | > align_error: 0.578697144985199  (0.6381556860038212)

   --> STEP: 8
     | > decoder_loss: 0.45641276240348816  (0.44851796701550484)
     | > postnet_loss: 0.3197205364704132  (0.3187323696911335)
     | > stopnet_loss: 0.007573989685624838  (0.008354402496479452)
     | > loss: 0.20160731673240662  (0.20016698352992535)
     | > align_error: 0.5750334858894348  (0.6302654109895229)

   --> STEP: 9
     | > decoder_loss: 0.45150184631347656  (0.44884950915972394)
     | > postnet_loss: 0.3176756799221039  (0.3186149597167969)
     | > stopnet_loss: 0.006753481924533844  (0.00817652243292994)
     | > loss: 0.19904786348342896  (0.20004263685809243)
     | > align_error: 0.5911797285079956  (0.6259225573804643)

   --> STEP: 10
     | > decoder_loss: 0.4820728898048401  (0.45217184722423553)
     | > postnet_loss: 0.3351649343967438  (0.32026995718479156)
     | > stopnet_loss: 0.005848185159265995  (0.007943688705563546)
     | > loss: 0.21015764772891998  (0.20105413794517518)
     | > align_error: 0.5860020518302917  (0.621930506825447)

   --> STEP: 11
     | > decoder_loss: 0.4648278057575226  (0.45332238890907983)
     | > postnet_loss: 0.3222293555736542  (0.3204480843110518)
     | > stopnet_loss: 0.005897592753171921  (0.007757679982618852)
     | > loss: 0.2026618868112564  (0.20120029693300073)
     | > align_error: 0.5943965017795563  (0.6194274154576388)

   --> STEP: 12
     | > decoder_loss: 0.46076688170433044  (0.45394276330868405)
     | > postnet_loss: 0.31639814376831055  (0.32011058926582336)
     | > stopnet_loss: 0.007944369688630104  (0.00777323745811979)
     | > loss: 0.2022356390953064  (0.2012865754465262)
     | > align_error: 0.5873705446720123  (0.6167560095588366)

   --> STEP: 13
     | > decoder_loss: 0.4503411054611206  (0.4536657127050253)
     | > postnet_loss: 0.31578969955444336  (0.31977821313417876)
     | > stopnet_loss: 0.0056240432895720005  (0.00760791482976996)
     | > loss: 0.19715674221515656  (0.2009688959671901)
     | > align_error: 0.5859489142894745  (0.6143862329996549)

   --> STEP: 14
     | > decoder_loss: 0.4584358334541321  (0.4540064356156758)
     | > postnet_loss: 0.31632155179977417  (0.31953130875314983)
     | > stopnet_loss: 0.004953380208462477  (0.007418305213962283)
     | > loss: 0.19864273071289062  (0.20080274130616868)
     | > align_error: 0.5546106696128845  (0.6101165499005999)

   --> STEP: 15
     | > decoder_loss: 0.45831498503685  (0.45429367224375405)
     | > postnet_loss: 0.31713804602622986  (0.3193717579046885)
     | > stopnet_loss: 0.004990722052752972  (0.007256466336548329)
     | > loss: 0.1988539844751358  (0.20067282418409985)
     | > align_error: 0.5885239243507385  (0.6086770415306091)

   --> STEP: 16
     | > decoder_loss: 0.4594491720199585  (0.45461589097976685)
     | > postnet_loss: 0.3113974928855896  (0.31887336634099483)
     | > stopnet_loss: 0.005238846410065889  (0.007130365091143176)
     | > loss: 0.19795051217079163  (0.20050267968326807)
     | > align_error: 0.6060397922992706  (0.6085122134536505)

   --> STEP: 17
     | > decoder_loss: 0.46534445881843567  (0.4552469832055709)
     | > postnet_loss: 0.31941941380500793  (0.3189054867800544)
     | > stopnet_loss: 0.004845303483307362  (0.006995949702446952)
     | > loss: 0.201036274433136  (0.2005340676097309)
     | > align_error: 0.5583659410476685  (0.6055624327238869)

   --> STEP: 18
     | > decoder_loss: 0.4600314497947693  (0.4555127869049708)
     | > postnet_loss: 0.3122081458568573  (0.31853341228432125)
     | > stopnet_loss: 0.005318316165357828  (0.006902747839275334)
     | > loss: 0.19837820529937744  (0.20041429748137793)
     | > align_error: 0.603880375623703  (0.6054689851072099)

   --> STEP: 19
     | > decoder_loss: 0.4582696259021759  (0.4556578836942974)
     | > postnet_loss: 0.31190627813339233  (0.31818461575006185)
     | > stopnet_loss: 0.004751174710690975  (0.00678950714829721)
     | > loss: 0.1972951591014862  (0.20025013230348887)
     | > align_error: 0.5999922752380371  (0.6051807372193587)

   --> STEP: 20
     | > decoder_loss: 0.4532056748867035  (0.4555352732539177)
     | > postnet_loss: 0.3071765601634979  (0.31763421297073363)
     | > stopnet_loss: 0.004529166035354137  (0.006676490092650056)
     | > loss: 0.19462472200393677  (0.19996886178851128)
     | > align_error: 0.6225360631942749  (0.6060485035181046)

   --> STEP: 21
     | > decoder_loss: 0.452271044254303  (0.45537983377774555)
     | > postnet_loss: 0.30759865045547485  (0.3171563290414356)
     | > stopnet_loss: 0.003994195722043514  (0.006548761789287839)
     | > loss: 0.19396162033081055  (0.19968280267147792)
     | > align_error: 0.5598725080490112  (0.6038496465910048)

   --> STEP: 22
     | > decoder_loss: 0.4533064067363739  (0.4552855870940469)
     | > postnet_loss: 0.3098827302455902  (0.31682571091435174)
     | > stopnet_loss: 0.004891420714557171  (0.006473428104072809)
     | > loss: 0.19568870961666107  (0.19950125298716806)
     | > align_error: 0.6252685189247131  (0.6048232316970824)

   --> STEP: 23
     | > decoder_loss: 0.4264777600765228  (0.4540330728758936)
     | > postnet_loss: 0.29786187410354614  (0.31600119627040363)
     | > stopnet_loss: 0.004552206490188837  (0.006389896729556115)
     | > loss: 0.18563710153102875  (0.19889846379342285)
     | > align_error: 0.5670790076255798  (0.6031821784765823)

   --> STEP: 24
     | > decoder_loss: 0.4601537585258484  (0.45428810144464177)
     | > postnet_loss: 0.3123514652252197  (0.31584912414352095)
     | > stopnet_loss: 0.004427814390510321  (0.00630814329876254)
     | > loss: 0.19755412638187408  (0.19884244973460832)
     | > align_error: 0.5794621109962463  (0.6021938423315683)

   --> STEP: 25
     | > decoder_loss: 0.4599568247795105  (0.4545148503780365)
     | > postnet_loss: 0.31014207005500793  (0.3156208419799804)
     | > stopnet_loss: 0.003703023074194789  (0.00620393848977983)
     | > loss: 0.1962277591228485  (0.19873786211013794)
     | > align_error: 0.5577358603477478  (0.6004155230522155)

   --> STEP: 26
     | > decoder_loss: 0.4352295398712158  (0.4537731076662357)
     | > postnet_loss: 0.2996061146259308  (0.31500489092790157)
     | > stopnet_loss: 0.004412201698869467  (0.006135025536283278)
     | > loss: 0.18812111020088196  (0.19832952549824348)
     | > align_error: 0.5467550754547119  (0.5983516596830807)

   --> STEP: 27
     | > decoder_loss: 0.4315016567707062  (0.4529482391145494)
     | > postnet_loss: 0.29358330368995667  (0.31421149880797766)
     | > stopnet_loss: 0.003934246022254229  (0.006053515183911832)
     | > loss: 0.18520548939704895  (0.19784345008708812)
     | > align_error: 0.541160374879837  (0.5962334639496272)

   --> STEP: 28
     | > decoder_loss: 0.4379780888557434  (0.4524135908910206)
     | > postnet_loss: 0.29900261759757996  (0.3136683244790349)
     | > stopnet_loss: 0.003917825408279896  (0.005977240549067834)
     | > loss: 0.18816299736499786  (0.19749771963272775)
     | > align_error: 0.5662328004837036  (0.5951620116829871)

   --> STEP: 29
     | > decoder_loss: 0.4330008327960968  (0.45174418543947154)
     | > postnet_loss: 0.29576346278190613  (0.31305091545499597)
     | > stopnet_loss: 0.003599682357162237  (0.00589525578382971)
     | > loss: 0.1857907623052597  (0.19709403144902196)
     | > align_error: 0.5405912399291992  (0.5932802609328565)

   --> STEP: 30
     | > decoder_loss: 0.4343447685241699  (0.45116420487562814)
     | > postnet_loss: 0.2967817187309265  (0.312508608897527)
     | > stopnet_loss: 0.0029168669134378433  (0.005795976154816648)
     | > loss: 0.1856984943151474  (0.19671418021122614)
     | > align_error: 0.533573567867279  (0.5912900378306706)

   --> STEP: 31
     | > decoder_loss: 0.4323476254940033  (0.45055721844396285)
     | > postnet_loss: 0.2959778904914856  (0.31197535991668696)
     | > stopnet_loss: 0.003996001090854406  (0.00573791244307593)
     | > loss: 0.18607737123966217  (0.1963710573411757)
     | > align_error: 0.5592325925827026  (0.5902559266936394)

   --> STEP: 32
     | > decoder_loss: 0.4413883090019226  (0.4502706900238991)
     | > postnet_loss: 0.30116865038871765  (0.3116376502439379)
     | > stopnet_loss: 0.003875924274325371  (0.005679725312802475)
     | > loss: 0.18951515853405  (0.19615681050345302)
     | > align_error: 0.530910074710846  (0.588401368819177)

   --> STEP: 33
     | > decoder_loss: 0.4369421899318695  (0.44986679608171637)
     | > postnet_loss: 0.29740819334983826  (0.31120645458048035)
     | > stopnet_loss: 0.004047360736876726  (0.005630259719592604)
     | > loss: 0.18763495981693268  (0.19589857260386148)
     | > align_error: 0.5458093583583832  (0.5871107018355166)

   --> STEP: 34
     | > decoder_loss: 0.4431662857532501  (0.4496697222485262)
     | > postnet_loss: 0.2991652488708496  (0.31085230147137355)
     | > stopnet_loss: 0.0033364843111485243  (0.005562795736991307)
     | > loss: 0.18891936540603638  (0.19569330180392547)
     | > align_error: 0.5634510517120361  (0.5864148297730614)

   --> STEP: 35
     | > decoder_loss: 0.44131195545196533  (0.44943092891148156)
     | > postnet_loss: 0.29954805970191956  (0.31052932313510345)
     | > stopnet_loss: 0.003535767085850239  (0.0055048806326729914)
     | > loss: 0.188750758767128  (0.19549494343144552)
     | > align_error: 0.5331957340240479  (0.5848942841802325)

   --> STEP: 36
     | > decoder_loss: 0.44667676091194153  (0.4493544242448277)
     | > postnet_loss: 0.3029539883136749  (0.31031889716784156)
     | > stopnet_loss: 0.003698179963976145  (0.0054546945029869676)
     | > loss: 0.19110587239265442  (0.1953730247914791)
     | > align_error: 0.6337127685546875  (0.586250353190634)

   --> STEP: 37
     | > decoder_loss: 0.4399072527885437  (0.44909909528654973)
     | > postnet_loss: 0.30036798119544983  (0.31004995349291203)
     | > stopnet_loss: 0.0035940513480454683  (0.005404406850150711)
     | > loss: 0.18866287171840668  (0.1951916693030177)
     | > align_error: 0.5187687873840332  (0.5844265270877529)

   --> STEP: 38
     | > decoder_loss: 0.42744898796081543  (0.44852935562008306)
     | > postnet_loss: 0.2929634749889374  (0.3096003093217548)
     | > stopnet_loss: 0.0031544941011816263  (0.005345198619914682)
     | > loss: 0.18325762450695038  (0.19487761549259489)
     | > align_error: 0.5512344241142273  (0.5835530506937128)

   --> STEP: 39
     | > decoder_loss: 0.4428730309009552  (0.4483843216529259)
     | > postnet_loss: 0.30371278524398804  (0.30944934716591466)
     | > stopnet_loss: 0.0034955532755702734  (0.005297771816213543)
     | > loss: 0.19014202058315277  (0.19475618998209637)
     | > align_error: 0.545610785484314  (0.5825801720985999)

   --> STEP: 40
     | > decoder_loss: 0.44044384360313416  (0.44818580970168115)
     | > postnet_loss: 0.30234718322753906  (0.3092717930674552)
     | > stopnet_loss: 0.0030558493454009295  (0.005241723754443228)
     | > loss: 0.1887536197900772  (0.1946061257272959)
     | > align_error: 0.5836963653564453  (0.5826080769300461)

   --> STEP: 41
     | > decoder_loss: 0.4304698705673218  (0.44775371362523336)
     | > postnet_loss: 0.29435813426971436  (0.3089080452919005)
     | > stopnet_loss: 0.0037558134645223618  (0.005205482040054913)
     | > loss: 0.18496280908584595  (0.1943709228823825)
     | > align_error: 0.5029510855674744  (0.5806652234821785)

   --> STEP: 42
     | > decoder_loss: 0.4348280727863312  (0.4474459602719262)
     | > postnet_loss: 0.2957938015460968  (0.30859580139319087)
     | > stopnet_loss: 0.003310933243483305  (0.005160373735374636)
     | > loss: 0.1859664022922516  (0.19417081524928415)
     | > align_error: 0.5794491171836853  (0.5806362685703097)

   --> STEP: 43
     | > decoder_loss: 0.4335036277770996  (0.4471217199813488)
     | > postnet_loss: 0.29453423619270325  (0.30826878824899345)
     | > stopnet_loss: 0.0029544478747993708  (0.00510907313396591)
     | > loss: 0.1849639117717743  (0.19395670121492345)
     | > align_error: 0.5515228807926178  (0.5799592130405959)

   --> STEP: 44
     | > decoder_loss: 0.4515983462333679  (0.4472234614870765)
     | > postnet_loss: 0.30542701482772827  (0.30820420248941927)
     | > stopnet_loss: 0.0026920789387077093  (0.005054141447710042)
     | > loss: 0.19194841384887695  (0.19391105832024058)
     | > align_error: 0.5505339503288269  (0.5792904570698739)

   --> STEP: 45
     | > decoder_loss: 0.44405826926231384  (0.4471531238820818)
     | > postnet_loss: 0.3039274513721466  (0.30810916357570206)
     | > stopnet_loss: 0.0033357483334839344  (0.005015954934060572)
     | > loss: 0.19033217430114746  (0.19383152756426072)
     | > align_error: 0.5522083044052124  (0.5786886314551036)

   --> STEP: 46
     | > decoder_loss: 0.4355265498161316  (0.4469003722719524)
     | > postnet_loss: 0.29612576961517334  (0.30784865501134273)
     | > stopnet_loss: 0.0032219819258898497  (0.0049769555208394696)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3572814970305472 (-0.003509272228587823)
     | > avg_decoder_loss: 0.44306269829923456 (+0.0013807673345912486)
     | > avg_postnet_loss: 0.30491759921565187 (+0.0042229479912554435)
     | > avg_stopnet_loss: 0.004410469724627379 (-2.6715552492451167e-08)
     | > avg_loss: 0.19140554445259503 (+0.0014009019642165499)
     | > avg_align_error: 0.5715179294347763 (+0.00024063794901874047)


 > EPOCH: 100/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 11:34:36)

   --> TIME: 2025-12-28 11:34:38 -- STEP: 0/150 -- GLOBAL_STEP: 15100
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45408353209495544  (0.45408353209495544)
     | > postnet_loss: 0.39330294728279114  (0.39330294728279114)
     | > stopnet_loss: 0.019299061968922615  (0.019299061968922615)
     | > loss: 0.2311456799507141  (0.2311456799507141)
     | > align_error: 0.7497618198394775  (0.7497618198394775)
     | > grad_norm: tensor(0.5195, device='cuda:0')  (tensor(0.5195, device='cuda:0'))
     | > step_time: 0.5094  (0.5093715190887451)
     | > loader_time: 0.5685  (0.5684707164764404)


   --> TIME: 2025-12-28 11:35:15 -- STEP: 25/150 -- GLOBAL_STEP: 15125
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.47940343618392944  (0.47195141673088076)
     | > postnet_loss: 0.403658002614975  (0.40059560894966123)
     | > stopnet_loss: 0.00605409499257803  (0.009649107195436952)
     | > loss: 0.22681944072246552  (0.2277858603000641)
     | > align_error: 0.6166974306106567  (0.6702769768238067)
     | > grad_norm: tensor(0.2246, device='cuda:0')  (tensor(0.3263, device='cuda:0'))
     | > step_time: 0.8017  (0.6591741847991943)
     | > loader_time: 0.8902  (0.8426748466491699)


   --> TIME: 2025-12-28 11:36:07 -- STEP: 50/150 -- GLOBAL_STEP: 15150
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4944170415401459  (0.4794534319639206)
     | > postnet_loss: 0.4071729779243469  (0.4026769232749939)
     | > stopnet_loss: 0.004477339331060648  (0.007538685584440827)
     | > loss: 0.22987483441829681  (0.22807127326726914)
     | > align_error: 0.6350976228713989  (0.6474289071559906)
     | > grad_norm: tensor(0.1489, device='cuda:0')  (tensor(0.2832, device='cuda:0'))
     | > step_time: 1.3449  (0.872780933380127)
     | > loader_time: 1.1652  (0.9181960964202881)


   --> TIME: 2025-12-28 11:37:12 -- STEP: 75/150 -- GLOBAL_STEP: 15175
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4852505624294281  (0.48218735257784523)
     | > postnet_loss: 0.3995421230792999  (0.4022403315703074)
     | > stopnet_loss: 0.0033603517804294825  (0.006418418756996592)
     | > loss: 0.2245585173368454  (0.22752533932526905)
     | > align_error: 0.6132762432098389  (0.6358392906188964)
     | > grad_norm: tensor(0.1589, device='cuda:0')  (tensor(0.2452, device='cuda:0'))
     | > step_time: 1.5743  (1.0433435217539468)
     | > loader_time: 1.2112  (1.0172780577341718)


   --> TIME: 2025-12-28 11:38:32 -- STEP: 100/150 -- GLOBAL_STEP: 15200
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48454350233078003  (0.48359941720962524)
     | > postnet_loss: 0.39667388796806335  (0.401631281375885)
     | > stopnet_loss: 0.00347530678845942  (0.005767638382967562)
     | > loss: 0.22377964854240417  (0.22707531318068505)
     | > align_error: 0.5856443643569946  (0.6310151746869088)
     | > grad_norm: tensor(0.1541, device='cuda:0')  (tensor(0.2339, device='cuda:0'))
     | > step_time: 1.6888  (1.1781139326095584)
     | > loader_time: 1.6441  (1.1677186036109923)


   --> TIME: 2025-12-28 11:40:01 -- STEP: 125/150 -- GLOBAL_STEP: 15225
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48384541273117065  (0.48467796182632444)
     | > postnet_loss: 0.3932960629463196  (0.40111759543418884)
     | > stopnet_loss: 0.0031402367167174816  (0.005293595034629107)
     | > loss: 0.22242560982704163  (0.22674248468875885)
     | > align_error: 0.5903544425964355  (0.6270765042304993)
     | > grad_norm: tensor(0.2731, device='cuda:0')  (tensor(0.2223, device='cuda:0'))
     | > step_time: 1.8809  (1.3057227535247802)
     | > loader_time: 1.6302  (1.2820962982177735)


   --> TIME: 2025-12-28 11:41:52 -- STEP: 150/150 -- GLOBAL_STEP: 15250
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5040478110313416  (0.48647884408632913)
     | > postnet_loss: 0.40757980942726135  (0.40119834383328756)
     | > stopnet_loss: 0.0025994814932346344  (0.004915240635164082)
     | > loss: 0.23050639033317566  (0.22683453808228174)
     | > align_error: 0.5838765799999237  (0.6237277740240096)
     | > grad_norm: tensor(0.2666, device='cuda:0')  (tensor(0.2202, device='cuda:0'))
     | > step_time: 11.7249  (1.5256325848897296)
     | > loader_time: 0.7201  (1.3715475432078041)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46186205744743347  (0.46186205744743347)
     | > postnet_loss: 0.3321545422077179  (0.3321545422077179)
     | > stopnet_loss: 0.012331133708357811  (0.012331133708357811)
     | > loss: 0.2108352780342102  (0.2108352780342102)
     | > align_error: 0.7180966734886169  (0.7180966734886169)

   --> STEP: 1
     | > decoder_loss: 0.4431447982788086  (0.4431447982788086)
     | > postnet_loss: 0.31985709071159363  (0.31985709071159363)
     | > stopnet_loss: 0.009681012481451035  (0.009681012481451035)
     | > loss: 0.20043149590492249  (0.20043149590492249)
     | > align_error: 0.6586652994155884  (0.6586652994155884)

   --> STEP: 2
     | > decoder_loss: 0.44001105427742004  (0.4415779262781143)
     | > postnet_loss: 0.312015563249588  (0.3159363269805908)
     | > stopnet_loss: 0.011171644553542137  (0.010426328517496586)
     | > loss: 0.1991782933473587  (0.1998048946261406)
     | > align_error: 0.6549913883209229  (0.6568283438682556)

   --> STEP: 3
     | > decoder_loss: 0.44270485639572144  (0.44195356965065)
     | > postnet_loss: 0.31029072403907776  (0.3140544593334198)
     | > stopnet_loss: 0.008419468998908997  (0.009757375344634056)
     | > loss: 0.1966683715581894  (0.19875938693682352)
     | > align_error: 0.7338079214096069  (0.682488203048706)

   --> STEP: 4
     | > decoder_loss: 0.4481654167175293  (0.44350653141736984)
     | > postnet_loss: 0.3183949291706085  (0.315139576792717)
     | > stopnet_loss: 0.008289513178169727  (0.009390409803017974)
     | > loss: 0.1999295949935913  (0.19905193895101547)
     | > align_error: 0.602506160736084  (0.6624926924705505)

   --> STEP: 5
     | > decoder_loss: 0.4305862784385681  (0.4409224808216095)
     | > postnet_loss: 0.30184733867645264  (0.31248112916946413)
     | > stopnet_loss: 0.008264170959591866  (0.009165162034332753)
     | > loss: 0.1913725733757019  (0.19751606583595277)
     | > align_error: 0.6412453651428223  (0.6582432270050049)

   --> STEP: 6
     | > decoder_loss: 0.44564396142959595  (0.4417093942562739)
     | > postnet_loss: 0.3126266300678253  (0.312505379319191)
     | > stopnet_loss: 0.007321202661842108  (0.008857835472250978)
     | > loss: 0.19688886404037476  (0.19741153220335642)
     | > align_error: 0.5925901532173157  (0.64730104804039)

   --> STEP: 7
     | > decoder_loss: 0.45481160283088684  (0.4435811383383615)
     | > postnet_loss: 0.31098461151123047  (0.31228812677519663)
     | > stopnet_loss: 0.006300375331193209  (0.00849248402352844)
     | > loss: 0.19774942100048065  (0.19745980203151703)
     | > align_error: 0.5780503749847412  (0.6374080947467259)

   --> STEP: 8
     | > decoder_loss: 0.45061659812927246  (0.44446057081222534)
     | > postnet_loss: 0.3123932182788849  (0.31230126321315765)
     | > stopnet_loss: 0.007592527661472559  (0.008379989478271455)
     | > loss: 0.19834497570991516  (0.1975704487413168)
     | > align_error: 0.5743535757064819  (0.6295262798666954)

   --> STEP: 9
     | > decoder_loss: 0.44811803102493286  (0.44486695528030396)
     | > postnet_loss: 0.31153106689453125  (0.3122156858444214)
     | > stopnet_loss: 0.006720593199133873  (0.008195612113922834)
     | > loss: 0.19663286209106445  (0.1974662724468443)
     | > align_error: 0.5905511379241943  (0.6251957085397508)

   --> STEP: 10
     | > decoder_loss: 0.4781585931777954  (0.4481961190700531)
     | > postnet_loss: 0.32794174551963806  (0.31378829181194307)
     | > stopnet_loss: 0.005904081743210554  (0.007966459076851607)
     | > loss: 0.2074291706085205  (0.19846256226301193)
     | > align_error: 0.5851715207099915  (0.6211932897567749)

   --> STEP: 11
     | > decoder_loss: 0.46162956953048706  (0.44941734183918347)
     | > postnet_loss: 0.3170824944972992  (0.31408776478333905)
     | > stopnet_loss: 0.005923235323280096  (0.00778071146289056)
     | > loss: 0.2006012499332428  (0.1986569884148511)
     | > align_error: 0.59355428814888  (0.6186806532469663)

   --> STEP: 12
     | > decoder_loss: 0.45689886808395386  (0.450040802359581)
     | > postnet_loss: 0.31031566858291626  (0.31377342343330383)
     | > stopnet_loss: 0.007911519147455692  (0.007791612103270988)
     | > loss: 0.19971515238285065  (0.19874516874551773)
     | > align_error: 0.5862101018428802  (0.6159747739632925)

   --> STEP: 13
     | > decoder_loss: 0.44759273529052734  (0.44985248950811535)
     | > postnet_loss: 0.310751736164093  (0.31354098595105684)
     | > stopnet_loss: 0.00563810532912612  (0.0076259577360290745)
     | > loss: 0.19522422552108765  (0.19847432695902312)
     | > align_error: 0.5849349796772003  (0.6135870974797469)

   --> STEP: 14
     | > decoder_loss: 0.45631304383277893  (0.4503139576741627)
     | > postnet_loss: 0.31215599179267883  (0.313442057796887)
     | > stopnet_loss: 0.004967578686773777  (0.007436073518225125)
     | > loss: 0.19708484411239624  (0.19837507818426406)
     | > align_error: 0.5535709261894226  (0.6093002281018666)

   --> STEP: 15
     | > decoder_loss: 0.4568098783493042  (0.45074701905250547)
     | > postnet_loss: 0.31448522210121155  (0.31351160208384193)
     | > stopnet_loss: 0.004994310438632965  (0.007273289312918981)
     | > loss: 0.1978180706501007  (0.19833794434865315)
     | > align_error: 0.5874165892601013  (0.6078413188457489)

   --> STEP: 16
     | > decoder_loss: 0.45722994208335876  (0.4511522017419338)
     | > postnet_loss: 0.307594358921051  (0.3131417743861675)
     | > stopnet_loss: 0.005258550401777029  (0.007147368130972609)
     | > loss: 0.19646461308002472  (0.19822086114436388)
     | > align_error: 0.6050293147563934  (0.6076655685901642)

   --> STEP: 17
     | > decoder_loss: 0.46408650279045105  (0.4519130429800819)
     | > postnet_loss: 0.3166859447956085  (0.31335025499848757)
     | > stopnet_loss: 0.004862839821726084  (0.007012984112781637)
     | > loss: 0.20005595684051514  (0.19832880795001984)
     | > align_error: 0.5573968589305878  (0.6047085856690126)

   --> STEP: 18
     | > decoder_loss: 0.45768049359321594  (0.4522334569030338)
     | > postnet_loss: 0.30879727005958557  (0.3130973113907708)
     | > stopnet_loss: 0.005316110793501139  (0.0069187133728216095)
     | > loss: 0.19693554937839508  (0.1982514046960407)
     | > align_error: 0.6030588150024414  (0.6046169317430921)

   --> STEP: 19
     | > decoder_loss: 0.4565752148628235  (0.4524619704798648)
     | > postnet_loss: 0.3086654841899872  (0.31286405732757167)
     | > stopnet_loss: 0.0048310463316738605  (0.006808836160129623)
     | > loss: 0.19614121317863464  (0.19814034198459826)
     | > align_error: 0.599415510892868  (0.6043431727509749)

   --> STEP: 20
     | > decoder_loss: 0.45250388979911804  (0.4524640664458275)
     | > postnet_loss: 0.3054322600364685  (0.3124924674630165)
     | > stopnet_loss: 0.004519748035818338  (0.006694381753914058)
     | > loss: 0.19400377571582794  (0.19793351367115974)
     | > align_error: 0.6219333112239838  (0.6052226796746254)

   --> STEP: 21
     | > decoder_loss: 0.4507432281970978  (0.45238212176731657)
     | > postnet_loss: 0.30442896485328674  (0.3121084911482675)
     | > stopnet_loss: 0.004017643630504608  (0.006566918033751703)
     | > loss: 0.19281068444252014  (0.19768956942217691)
     | > align_error: 0.5590859651565552  (0.603025693269003)

   --> STEP: 22
     | > decoder_loss: 0.4520034193992615  (0.452364908023314)
     | > postnet_loss: 0.3070365786552429  (0.3118779496713118)
     | > stopnet_loss: 0.004903995431959629  (0.006491330642761154)
     | > loss: 0.19466400146484375  (0.19755204360593448)
     | > align_error: 0.6245783567428589  (0.6040053597905419)

   --> STEP: 23
     | > decoder_loss: 0.42541784048080444  (0.451193296391031)
     | > postnet_loss: 0.29546216130256653  (0.3111642197422359)
     | > stopnet_loss: 0.004556844476610422  (0.0064072225485806876)
     | > loss: 0.18477685749530792  (0.19699660073155942)
     | > align_error: 0.5661807358264923  (0.6023608109225398)

   --> STEP: 24
     | > decoder_loss: 0.4597070813179016  (0.4515480374296506)
     | > postnet_loss: 0.3108226954936981  (0.3111499895652135)
     | > stopnet_loss: 0.004413597751408815  (0.006324154848698527)
     | > loss: 0.19704604148864746  (0.19699866076310477)
     | > align_error: 0.5786053240299225  (0.6013709989686807)

   --> STEP: 25
     | > decoder_loss: 0.4592786729335785  (0.45185726284980776)
     | > postnet_loss: 0.3081253468990326  (0.3110290038585663)
     | > stopnet_loss: 0.0037343858275562525  (0.006220564087852836)
     | > loss: 0.19558538496494293  (0.19694212973117828)
     | > align_error: 0.5571447610855103  (0.5996019494533539)

   --> STEP: 26
     | > decoder_loss: 0.43424466252326965  (0.4511798551449409)
     | > postnet_loss: 0.2969827950000763  (0.3104887650563167)
     | > stopnet_loss: 0.00439097685739398  (0.006150195348219803)
     | > loss: 0.18719783425331116  (0.1965673491358757)
     | > align_error: 0.5458498001098633  (0.5975345590939889)

   --> STEP: 27
     | > decoder_loss: 0.4314500093460083  (0.4504491201153508)
     | > postnet_loss: 0.2921753227710724  (0.30981048941612244)
     | > stopnet_loss: 0.003936873283237219  (0.006068220456924151)
     | > loss: 0.18484319746494293  (0.19613312129621152)
     | > align_error: 0.5403779745101929  (0.5954176485538483)

   --> STEP: 28
     | > decoder_loss: 0.43640372157096863  (0.4499474987387657)
     | > postnet_loss: 0.29642391204833984  (0.3093323973672731)
     | > stopnet_loss: 0.003944316413253546  (0.005992366741078773)
     | > loss: 0.187151238322258  (0.19581233976142748)
     | > align_error: 0.5652890801429749  (0.5943416282534599)

   --> STEP: 29
     | > decoder_loss: 0.4315401017665863  (0.44931276091213884)
     | > postnet_loss: 0.29286670684814453  (0.308764614935579)
     | > stopnet_loss: 0.0036089327186346054  (0.005910179360994491)
     | > loss: 0.18471063673496246  (0.19542952241568728)
     | > align_error: 0.5395854711532593  (0.5924534849051771)

   --> STEP: 30
     | > decoder_loss: 0.43375593423843384  (0.44879420002301534)
     | > postnet_loss: 0.2943713963031769  (0.30828484098116554)
     | > stopnet_loss: 0.0029250243678689003  (0.005810674194556971)
     | > loss: 0.1849568635225296  (0.19508043378591539)
     | > align_error: 0.5327678322792053  (0.590463963150978)

   --> STEP: 31
     | > decoder_loss: 0.4313778877258301  (0.4482323834972997)
     | > postnet_loss: 0.294239342212677  (0.30783176037573046)
     | > stopnet_loss: 0.0039817290380597115  (0.005751675963702221)
     | > loss: 0.1853860318660736  (0.19476771114333982)
     | > align_error: 0.5583630204200745  (0.589428448869336)

   --> STEP: 32
     | > decoder_loss: 0.43931615352630615  (0.44795375131070614)
     | > postnet_loss: 0.297728031873703  (0.3075160188600421)
     | > stopnet_loss: 0.003872106783092022  (0.005692939426808152)
     | > loss: 0.18813316524028778  (0.19456038158386946)
     | > align_error: 0.5298994183540344  (0.5875681666657329)

   --> STEP: 33
     | > decoder_loss: 0.4361104369163513  (0.4475948629957257)
     | > postnet_loss: 0.2959083616733551  (0.3071642716725667)
     | > stopnet_loss: 0.004058948718011379  (0.005643424556844614)
     | > loss: 0.18706364929676056  (0.1943332078781995)
     | > align_error: 0.544987291097641  (0.5862778371030634)

   --> STEP: 34
     | > decoder_loss: 0.4418089687824249  (0.44742468963651094)
     | > postnet_loss: 0.2972787618637085  (0.3068735213840709)
     | > stopnet_loss: 0.0033392803743481636  (0.0055756556103006005)
     | > loss: 0.18811120092868805  (0.1941502076738021)
     | > align_error: 0.5627305507659912  (0.5855852698578554)

   --> STEP: 35
     | > decoder_loss: 0.4397839903831482  (0.4472063839435577)
     | > postnet_loss: 0.297067791223526  (0.3065933576651982)
     | > stopnet_loss: 0.0035312436521053314  (0.00551724384006645)
     | > loss: 0.18774420022964478  (0.19396717888968332)
     | > align_error: 0.5323566794395447  (0.5840644529887609)

   --> STEP: 36
     | > decoder_loss: 0.4455015957355499  (0.4471590287155575)
     | > postnet_loss: 0.3007883131504059  (0.3064321064286762)
     | > stopnet_loss: 0.0037042382173240185  (0.005466882572768049)
     | > loss: 0.19027671217918396  (0.19386466592550278)
     | > align_error: 0.6328861713409424  (0.585420611831877)

   --> STEP: 37
     | > decoder_loss: 0.4389881491661072  (0.44693819413313995)
     | > postnet_loss: 0.29822787642478943  (0.30621037048262517)
     | > stopnet_loss: 0.0035777706652879715  (0.005415825494187507)
     | > loss: 0.18788176774978638  (0.19370296597480774)
     | > align_error: 0.5179704427719116  (0.5835976342897158)

   --> STEP: 38
     | > decoder_loss: 0.4263823330402374  (0.4463972504201688)
     | > postnet_loss: 0.2908955514431  (0.30580734892895345)
     | > stopnet_loss: 0.003174977144226432  (0.005356855800767479)
     | > loss: 0.18249444663524628  (0.19340800493955612)
     | > align_error: 0.5502923727035522  (0.5827211800374483)

   --> STEP: 39
     | > decoder_loss: 0.44167715311050415  (0.4462762222840236)
     | > postnet_loss: 0.3010120093822479  (0.30568439150467897)
     | > stopnet_loss: 0.003505663014948368  (0.00530938931907981)
     | > loss: 0.18917794525623322  (0.19329954187075296)
     | > align_error: 0.5447246730327606  (0.5817469106270716)

   --> STEP: 40
     | > decoder_loss: 0.43860721588134766  (0.4460844971239567)
     | > postnet_loss: 0.2995914816856384  (0.30553206875920297)
     | > stopnet_loss: 0.0030632270500063896  (0.005253235262352974)
     | > loss: 0.18761290609836578  (0.19315737597644328)
     | > align_error: 0.5827568173408508  (0.581772158294916)

   --> STEP: 41
     | > decoder_loss: 0.42911389470100403  (0.4456705799916895)
     | > postnet_loss: 0.2915860414505005  (0.30519192175167364)
     | > stopnet_loss: 0.0037459286395460367  (0.005216471686186951)
     | > loss: 0.18392090499401093  (0.19293209619638396)
     | > align_error: 0.5020814538002014  (0.5798284825755327)

   --> STEP: 42
     | > decoder_loss: 0.4339803159236908  (0.44539224037102293)
     | > postnet_loss: 0.29410845041275024  (0.3049280295769374)
     | > stopnet_loss: 0.0033196089789271355  (0.00517130828839505)
     | > loss: 0.18534179031848907  (0.19275137462786265)
     | > align_error: 0.5784527957439423  (0.5797957281271615)

   --> STEP: 43
     | > decoder_loss: 0.43291887640953064  (0.44510216213936027)
     | > postnet_loss: 0.29299694299697876  (0.30465056244717087)
     | > stopnet_loss: 0.002956736134365201  (0.005119806610394356)
     | > loss: 0.1844356805086136  (0.19255798639253127)
     | > align_error: 0.5505337417125702  (0.5791152168151943)

   --> STEP: 44
     | > decoder_loss: 0.45143547654151917  (0.44524610110304574)
     | > postnet_loss: 0.30351534485816956  (0.30462476204742084)
     | > stopnet_loss: 0.0026907336432486773  (0.00506460040659559)
     | > loss: 0.19142843782901764  (0.1925323148342696)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3523483673731486 (-0.004933129657398561)
     | > avg_decoder_loss: 0.44129550186070526 (-0.0017671964385292949)
     | > avg_postnet_loss: 0.30148570691094245 (-0.0034318923047094163)
     | > avg_stopnet_loss: 0.004418285172009333 (+7.815447381953958e-06)
     | > avg_loss: 0.19011358600674252 (-0.0012919584458525035)
     | > avg_align_error: 0.5706786093386736 (-0.0008393200961026581)


 > EPOCH: 101/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 11:43:38)

   --> TIME: 2025-12-28 11:44:14 -- STEP: 24/150 -- GLOBAL_STEP: 15275
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4821646809577942  (0.47116265694300336)
     | > postnet_loss: 0.4049952030181885  (0.400068952391545)
     | > stopnet_loss: 0.006703502964228392  (0.009835602676806351)
     | > loss: 0.22849346697330475  (0.22764350660145283)
     | > align_error: 0.6942193806171417  (0.6726520707209905)
     | > grad_norm: tensor(0.4294, device='cuda:0')  (tensor(0.2738, device='cuda:0'))
     | > step_time: 0.9321  (0.6546678642431895)
     | > loader_time: 0.9554  (0.8288821578025818)


   --> TIME: 2025-12-28 11:45:06 -- STEP: 49/150 -- GLOBAL_STEP: 15300
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4877849221229553  (0.4795041108617977)
     | > postnet_loss: 0.40249043703079224  (0.4027093089356714)
     | > stopnet_loss: 0.005122118629515171  (0.007619887343322744)
     | > loss: 0.22769096493721008  (0.2281732431479863)
     | > align_error: 0.5843164324760437  (0.648423148053033)
     | > grad_norm: tensor(0.2147, device='cuda:0')  (tensor(0.2858, device='cuda:0'))
     | > step_time: 1.2353  (0.8745666572025844)
     | > loader_time: 1.0975  (0.9186213065166863)


   --> TIME: 2025-12-28 11:46:13 -- STEP: 74/150 -- GLOBAL_STEP: 15325
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4892719089984894  (0.48257429978332006)
     | > postnet_loss: 0.401792049407959  (0.4024855232722051)
     | > stopnet_loss: 0.0037145025562494993  (0.006457810516695719)
     | > loss: 0.22648048400878906  (0.22772276602886818)
     | > align_error: 0.6025820970535278  (0.6366349112343141)
     | > grad_norm: tensor(0.1523, device='cuda:0')  (tensor(0.2637, device='cuda:0'))
     | > step_time: 1.5351  (1.0520860601115876)
     | > loader_time: 1.2563  (1.0297517712051805)


   --> TIME: 2025-12-28 11:47:32 -- STEP: 99/150 -- GLOBAL_STEP: 15350
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49322888255119324  (0.4837918501309674)
     | > postnet_loss: 0.40211811661720276  (0.4017677379376961)
     | > stopnet_loss: 0.003297459101304412  (0.005780843244112953)
     | > loss: 0.22713421285152435  (0.2271707398120803)
     | > align_error: 0.6029036939144135  (0.6317312076236264)
     | > grad_norm: tensor(0.2124, device='cuda:0')  (tensor(0.2485, device='cuda:0'))
     | > step_time: 1.8292  (1.2112340445470329)
     | > loader_time: 1.5858  (1.1414702685192386)


   --> TIME: 2025-12-28 11:48:58 -- STEP: 124/150 -- GLOBAL_STEP: 15375
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4852537214756012  (0.48496363239903606)
     | > postnet_loss: 0.3955884277820587  (0.40129564822681496)
     | > stopnet_loss: 0.0034664436243474483  (0.005295542915607051)
     | > loss: 0.22367697954177856  (0.22686036279605282)
     | > align_error: 0.6129868030548096  (0.6275875635685462)
     | > grad_norm: tensor(0.1535, device='cuda:0')  (tensor(0.2307, device='cuda:0'))
     | > step_time: 1.9135  (1.333765681712858)
     | > loader_time: 1.5764  (1.240880675854222)


   --> TIME: 2025-12-28 11:50:54 -- STEP: 149/150 -- GLOBAL_STEP: 15400
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5160736441612244  (0.4865263740488347)
     | > postnet_loss: 0.41579103469848633  (0.4012042049993605)
     | > stopnet_loss: 0.002510660095140338  (0.004917913285277832)
     | > loss: 0.23547683656215668  (0.22685055804732662)
     | > align_error: 0.624915599822998  (0.6242232660719215)
     | > grad_norm: tensor(0.1672, device='cuda:0')  (tensor(0.2233, device='cuda:0'))
     | > step_time: 14.1461  (1.558896952827505)
     | > loader_time: 2.2112  (1.3598006859721758)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46580013632774353  (0.46580013632774353)
     | > postnet_loss: 0.33333519101142883  (0.33333519101142883)
     | > stopnet_loss: 0.012203259393572807  (0.012203259393572807)
     | > loss: 0.21198709309101105  (0.21198709309101105)
     | > align_error: 0.7191575765609741  (0.7191575765609741)

   --> STEP: 1
     | > decoder_loss: 0.44779807329177856  (0.44779807329177856)
     | > postnet_loss: 0.3210102319717407  (0.3210102319717407)
     | > stopnet_loss: 0.009628323838114738  (0.009628323838114738)
     | > loss: 0.2018304020166397  (0.2018304020166397)
     | > align_error: 0.6599266529083252  (0.6599266529083252)

   --> STEP: 2
     | > decoder_loss: 0.4437118172645569  (0.4457549452781677)
     | > postnet_loss: 0.31321650743484497  (0.31711336970329285)
     | > stopnet_loss: 0.011188367381691933  (0.010408345609903336)
     | > loss: 0.20042045414447784  (0.20112542808055878)
     | > align_error: 0.656343400478363  (0.6581350266933441)

   --> STEP: 3
     | > decoder_loss: 0.4453542232513428  (0.4456213712692261)
     | > postnet_loss: 0.31033334136009216  (0.31485336025555927)
     | > stopnet_loss: 0.008255382999777794  (0.009690691406528154)
     | > loss: 0.19717727601528168  (0.1998093773921331)
     | > align_error: 0.7348178625106812  (0.6836959719657898)

   --> STEP: 4
     | > decoder_loss: 0.4528079032897949  (0.4474180042743683)
     | > postnet_loss: 0.3200513422489166  (0.3161528557538986)
     | > stopnet_loss: 0.008217470720410347  (0.009322386234998703)
     | > loss: 0.2014322727918625  (0.20021510124206543)
     | > align_error: 0.603865921497345  (0.6637384593486786)

   --> STEP: 5
     | > decoder_loss: 0.43424880504608154  (0.44478416442871094)
     | > postnet_loss: 0.3027561902999878  (0.31347352266311646)
     | > stopnet_loss: 0.008252102881669998  (0.009108329564332962)
     | > loss: 0.19250334799289703  (0.19867275059223174)
     | > align_error: 0.6428641974925995  (0.6595636069774627)

   --> STEP: 6
     | > decoder_loss: 0.44966694712638855  (0.44559796154499054)
     | > postnet_loss: 0.3137609362602234  (0.31352142492930096)
     | > stopnet_loss: 0.007287495769560337  (0.008804857265204191)
     | > loss: 0.19814446568489075  (0.19858470310767493)
     | > align_error: 0.5941195487976074  (0.6486562639474869)

   --> STEP: 7
     | > decoder_loss: 0.45885372161865234  (0.44749164155551363)
     | > postnet_loss: 0.3125024139881134  (0.31337585193770273)
     | > stopnet_loss: 0.006339666899293661  (0.008452687212931258)
     | > loss: 0.19917869567871094  (0.1986695591892515)
     | > align_error: 0.5798433423042297  (0.6388258465698787)

   --> STEP: 8
     | > decoder_loss: 0.4554798901081085  (0.448490172624588)
     | > postnet_loss: 0.3135666847229004  (0.31339970603585243)
     | > stopnet_loss: 0.007459560409188271  (0.008328546362463385)
     | > loss: 0.19972120225429535  (0.19880101457238197)
     | > align_error: 0.5759018063545227  (0.6309603415429592)

   --> STEP: 9
     | > decoder_loss: 0.4511786699295044  (0.4487888945473565)
     | > postnet_loss: 0.31320521235466003  (0.31337809562683105)
     | > stopnet_loss: 0.006774843670427799  (0.008155912730014987)
     | > loss: 0.19787082076072693  (0.1986976597044203)
     | > align_error: 0.5919378697872162  (0.6266245113478767)

   --> STEP: 10
     | > decoder_loss: 0.4812871217727661  (0.45203871726989747)
     | > postnet_loss: 0.3288159668445587  (0.31492188274860383)
     | > stopnet_loss: 0.005661871284246445  (0.007906508585438132)
     | > loss: 0.20818763971328735  (0.199646657705307)
     | > align_error: 0.5863999724388123  (0.6226020574569702)

   --> STEP: 11
     | > decoder_loss: 0.46469956636428833  (0.45318970355120575)
     | > postnet_loss: 0.31831201910972595  (0.3152300769632513)
     | > stopnet_loss: 0.005907642655074596  (0.007724793500859629)
     | > loss: 0.20166052877902985  (0.19982973689382727)
     | > align_error: 0.595132052898407  (0.6201047843152826)

   --> STEP: 12
     | > decoder_loss: 0.46055054664611816  (0.4538031071424484)
     | > postnet_loss: 0.31126874685287476  (0.3148999661207199)
     | > stopnet_loss: 0.007960381917655468  (0.007744425868925949)
     | > loss: 0.20091520249843597  (0.199920192360878)
     | > align_error: 0.5880453586578369  (0.6174331655104954)

   --> STEP: 13
     | > decoder_loss: 0.4500369131565094  (0.4535133999127608)
     | > postnet_loss: 0.3113628625869751  (0.31462788123350877)
     | > stopnet_loss: 0.0056334612891077995  (0.007582043978170707)
     | > loss: 0.1959833949804306  (0.19961736179315126)
     | > align_error: 0.5863469243049622  (0.6150419161869929)

   --> STEP: 14
     | > decoder_loss: 0.45823103189468384  (0.4538503736257553)
     | > postnet_loss: 0.3123834431171417  (0.31446756422519684)
     | > stopnet_loss: 0.004960469901561737  (0.007394788686984352)
     | > loss: 0.19761410355567932  (0.19947427191904613)
     | > align_error: 0.5553266704082489  (0.6107765414885112)

   --> STEP: 15
     | > decoder_loss: 0.45803606510162354  (0.4541294197241465)
     | > postnet_loss: 0.314517617225647  (0.3144709010918935)
     | > stopnet_loss: 0.005002800840884447  (0.0072353228305776915)
     | > loss: 0.1981412172317505  (0.19938540160655976)
     | > align_error: 0.5889056026935577  (0.6093184789021809)

   --> STEP: 16
     | > decoder_loss: 0.4592995345592499  (0.4544525519013405)
     | > postnet_loss: 0.3082507848739624  (0.3140821438282728)
     | > stopnet_loss: 0.005242893006652594  (0.007110795966582373)
     | > loss: 0.197130486369133  (0.19924446940422058)
     | > align_error: 0.6061416268348694  (0.609119925647974)

   --> STEP: 17
     | > decoder_loss: 0.4653637707233429  (0.45509438830263477)
     | > postnet_loss: 0.31690579652786255  (0.31424824104589577)
     | > stopnet_loss: 0.004856156185269356  (0.006978170097093372)
     | > loss: 0.20042355358600616  (0.1993138272972668)
     | > align_error: 0.558841347694397  (0.60616236223894)

   --> STEP: 18
     | > decoder_loss: 0.4593214690685272  (0.4553292261229621)
     | > postnet_loss: 0.3089657127857208  (0.3139547672536638)
     | > stopnet_loss: 0.005293766502290964  (0.006884592119604349)
     | > loss: 0.19736556708812714  (0.19920559061898124)
     | > align_error: 0.6043452024459839  (0.6060614089171091)

   --> STEP: 19
     | > decoder_loss: 0.4585438668727875  (0.45549841774137395)
     | > postnet_loss: 0.308806836605072  (0.3136838235353169)
     | > stopnet_loss: 0.004744225647300482  (0.006771941252640988)
     | > loss: 0.1965819001197815  (0.19906750164533915)
     | > align_error: 0.6005053520202637  (0.6057689848699068)

   --> STEP: 20
     | > decoder_loss: 0.4531775712966919  (0.45538237541913984)
     | > postnet_loss: 0.3050520420074463  (0.31325223445892336)
     | > stopnet_loss: 0.004540263209491968  (0.006660357350483537)
     | > loss: 0.19409766793251038  (0.19881900995969773)
     | > align_error: 0.6229940950870514  (0.606630240380764)

   --> STEP: 21
     | > decoder_loss: 0.4521471858024597  (0.4552283187707265)
     | > postnet_loss: 0.30388930439949036  (0.3128063806465694)
     | > stopnet_loss: 0.003990624565631151  (0.0065332272178715185)
     | > loss: 0.19299975037574768  (0.198541902360462)
     | > align_error: 0.5604243874549866  (0.6044299616700127)

   --> STEP: 22
     | > decoder_loss: 0.4517340064048767  (0.45506948639046063)
     | > postnet_loss: 0.3057626783847809  (0.31248621236194263)
     | > stopnet_loss: 0.004605650901794434  (0.006445610112595287)
     | > loss: 0.19397982954978943  (0.19833453541452234)
     | > align_error: 0.6259027719497681  (0.6054059985009107)

   --> STEP: 23
     | > decoder_loss: 0.42644962668418884  (0.45382514466410095)
     | > postnet_loss: 0.2950177490711212  (0.3117267139579939)
     | > stopnet_loss: 0.004546813666820526  (0.006363053745387689)
     | > loss: 0.18491366505622864  (0.19775101931198782)
     | > align_error: 0.5676465332508087  (0.6037642826204714)

   --> STEP: 24
     | > decoder_loss: 0.46027475595474243  (0.4540938784678777)
     | > postnet_loss: 0.31022047996520996  (0.31166395420829457)
     | > stopnet_loss: 0.00440962752327323  (0.00628166098613292)
     | > loss: 0.19703343510627747  (0.19772111997008324)
     | > align_error: 0.5801913738250732  (0.6027820780873299)

   --> STEP: 25
     | > decoder_loss: 0.45923280715942383  (0.45429943561553954)
     | > postnet_loss: 0.3072150945663452  (0.3114859998226166)
     | > stopnet_loss: 0.0037121695932000875  (0.006178881330415606)
     | > loss: 0.1953241378068924  (0.1976252406835556)
     | > align_error: 0.5580185055732727  (0.6009915351867676)

   --> STEP: 26
     | > decoder_loss: 0.43518853187561035  (0.4535644008563115)
     | > postnet_loss: 0.2959935665130615  (0.3108901370030183)
     | > stopnet_loss: 0.004398570861667395  (0.0061104078508483674)
     | > loss: 0.1871940940618515  (0.197224042736567)
     | > align_error: 0.5474033355712891  (0.5989304505861723)

   --> STEP: 27
     | > decoder_loss: 0.43174847960472107  (0.45275640377291926)
     | > postnet_loss: 0.29153671860694885  (0.31017334372908983)
     | > stopnet_loss: 0.003921222873032093  (0.006029326925744061)
     | > loss: 0.1847425252199173  (0.1967617643100244)
     | > align_error: 0.5417127907276154  (0.5968112779988183)

   --> STEP: 28
     | > decoder_loss: 0.43723371624946594  (0.4522020220756531)
     | > postnet_loss: 0.29572340846061707  (0.30965727461235865)
     | > stopnet_loss: 0.003943542949855328  (0.0059548346408908924)
     | > loss: 0.18718282878398895  (0.19641965946980885)
     | > align_error: 0.5667482614517212  (0.595737598836422)

   --> STEP: 29
     | > decoder_loss: 0.43277549743652344  (0.4515321419156831)
     | > postnet_loss: 0.2920049726963043  (0.3090485745462878)
     | > stopnet_loss: 0.0036055762320756912  (0.005873825730242092)
     | > loss: 0.18480068445205688  (0.1960190051588519)
     | > align_error: 0.5409097075462341  (0.593846981895381)

   --> STEP: 30
     | > decoder_loss: 0.43361687660217285  (0.45093496640523273)
     | > postnet_loss: 0.29308611154556274  (0.3085164924462636)
     | > stopnet_loss: 0.0029073066543787718  (0.005774941761046648)
     | > loss: 0.18458305299282074  (0.19563780675331752)
     | > align_error: 0.5340984463691711  (0.5918553640445073)

   --> STEP: 31
     | > decoder_loss: 0.4319852292537689  (0.4503236845616371)
     | > postnet_loss: 0.29327937960624695  (0.30802497267723083)
     | > stopnet_loss: 0.0039805639535188675  (0.005717058605965107)
     | > loss: 0.18529671430587769  (0.19530422312598075)
     | > align_error: 0.5596646666526794  (0.5908169544512226)

   --> STEP: 32
     | > decoder_loss: 0.4404567778110504  (0.4500153437256813)
     | > postnet_loss: 0.2975357174873352  (0.3076971834525466)
     | > stopnet_loss: 0.0038884063251316547  (0.005659913222189061)
     | > loss: 0.18838654458522797  (0.19508804567158222)
     | > align_error: 0.5315839350223541  (0.5889659225940704)

   --> STEP: 33
     | > decoder_loss: 0.4367239773273468  (0.4496125750469439)
     | > postnet_loss: 0.2952252924442291  (0.30731924736138544)
     | > stopnet_loss: 0.004038610495626926  (0.005610782836535664)
     | > loss: 0.18702593445777893  (0.19484373927116394)
     | > align_error: 0.5464583337306976  (0.5876778138406349)

   --> STEP: 34
     | > decoder_loss: 0.4424014389514923  (0.44940048280884237)
     | > postnet_loss: 0.29679355025291443  (0.30700966803466573)
     | > stopnet_loss: 0.003338949754834175  (0.0055439642164856195)
     | > loss: 0.1881376951932907  (0.19464650268063827)
     | > align_error: 0.5639934539794922  (0.5869812150211895)

   --> STEP: 35
     | > decoder_loss: 0.4413408637046814  (0.4491702079772949)
     | > postnet_loss: 0.2964250147342682  (0.30670724936894006)
     | > stopnet_loss: 0.003537375247105956  (0.005486633103074772)
     | > loss: 0.1879788488149643  (0.19445599828447616)
     | > align_error: 0.5337861776351929  (0.5854613568101611)

   --> STEP: 36
     | > decoder_loss: 0.4468109905719757  (0.4491046741604805)
     | > postnet_loss: 0.3003145158290863  (0.3065296734372775)
     | > stopnet_loss: 0.003713430603966117  (0.0054373774780995315)
     | > loss: 0.19049480557441711  (0.19434596515364116)
     | > align_error: 0.6341608762741089  (0.5868141212397151)

   --> STEP: 37
     | > decoder_loss: 0.43913164734840393  (0.44883513289528926)
     | > postnet_loss: 0.2969273030757904  (0.30627014991399404)
     | > stopnet_loss: 0.0035958513617515564  (0.005387606501982019)
     | > loss: 0.18761059641838074  (0.1941639281607963)
     | > align_error: 0.5192463994026184  (0.5849879665954693)

   --> STEP: 38
     | > decoder_loss: 0.42679113149642944  (0.44825502759531927)
     | > postnet_loss: 0.28995978832244873  (0.30584092987211126)
     | > stopnet_loss: 0.0031715461518615484  (0.0053292891243472695)
     | > loss: 0.18235927820205688  (0.1938532794776716)
     | > align_error: 0.5519704222679138  (0.5841190838500073)

   --> STEP: 39
     | > decoder_loss: 0.442178875207901  (0.44809922881615466)
     | > postnet_loss: 0.299865186214447  (0.3056877056757609)
     | > stopnet_loss: 0.0034936044830828905  (0.0052822202873917725)
     | > loss: 0.18900462985038757  (0.19372895512825405)
     | > align_error: 0.5463206768035889  (0.5831498939257401)

   --> STEP: 40
     | > decoder_loss: 0.43957722187042236  (0.44788617864251135)
     | > postnet_loss: 0.29852697253227234  (0.3055086873471737)
     | > stopnet_loss: 0.0030601441394537687  (0.005226668383693322)
     | > loss: 0.1875862032175064  (0.19357538633048538)
     | > align_error: 0.5841944217681885  (0.5831760071218014)

   --> STEP: 41
     | > decoder_loss: 0.4292885959148407  (0.4474325790637877)
     | > postnet_loss: 0.29053133726119995  (0.3051433861255646)
     | > stopnet_loss: 0.0037495361175388098  (0.005190640767445651)
     | > loss: 0.18370451033115387  (0.19333463325733097)
     | > align_error: 0.5037345290184021  (0.5812384100948892)

   --> STEP: 42
     | > decoder_loss: 0.43462494015693665  (0.44712763528029126)
     | > postnet_loss: 0.2934012711048126  (0.30486381195840384)
     | > stopnet_loss: 0.003315555863082409  (0.0051459958887703355)
     | > loss: 0.185322105884552  (0.19314385879607432)
     | > align_error: 0.579865038394928  (0.5812057107686996)

   --> STEP: 43
     | > decoder_loss: 0.43294665217399597  (0.4467978449754937)
     | > postnet_loss: 0.29170626401901245  (0.30455782247144125)
     | > stopnet_loss: 0.0029527791775763035  (0.005094990848975125)
     | > loss: 0.18411600589752197  (0.19293390872866611)
     | > align_error: 0.5521610379219055  (0.5805302532606347)

   --> STEP: 44
     | > decoder_loss: 0.45098981261253357  (0.4468931169672446)
     | > postnet_loss: 0.3019316792488098  (0.30449813739819964)
     | > stopnet_loss: 0.0026946880389004946  (0.0050404385123825205)
     | > loss: 0.19092504680156708  (0.1928882527757775)
     | > align_error: 0.5513446927070618  (0.5798669450662353)

   --> STEP: 45
     | > decoder_loss: 0.44452324509620667  (0.4468404531478882)
     | > postnet_loss: 0.3015556037425995  (0.30443274776140855)
     | > stopnet_loss: 0.003329390659928322  (0.005002415226772427)
     | > loss: 0.1898491084575653  (0.1928207162353728)
     | > align_error: 0.5529341101646423  (0.5792684376239776)

   --> STEP: 46
     | > decoder_loss: 0.43463531136512756  (0.44657512397869775)
     | > postnet_loss: 0.29234981536865234  (0.30417007531808776)
     | > stopnet_loss: 0.0032222948502749205  (0.004963716957718133)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3601868983471032 (+0.007838530973954594)
     | > avg_decoder_loss: 0.44245220630457904 (+0.0011567044438737795)
     | > avg_postnet_loss: 0.30062096769159496 (-0.0008647392193474879)
     | > avg_stopnet_loss: 0.004397961049989769 (-2.0324122019564107e-05)
     | > avg_loss: 0.19016625528985806 (+5.26692831155362e-05)
     | > avg_align_error: 0.5720721131021326 (+0.0013935037634589253)


 > EPOCH: 102/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 11:52:42)

   --> TIME: 2025-12-28 11:53:17 -- STEP: 23/150 -- GLOBAL_STEP: 15425
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48168623447418213  (0.47098601771437604)
     | > postnet_loss: 0.4057310223579407  (0.3998800904854484)
     | > stopnet_loss: 0.00667924340814352  (0.010045779949944952)
     | > loss: 0.2285335510969162  (0.22776230521824048)
     | > align_error: 0.6383931338787079  (0.6720633584520092)
     | > grad_norm: tensor(0.4334, device='cuda:0')  (tensor(0.3101, device='cuda:0'))
     | > step_time: 0.8817  (0.6383295784825864)
     | > loader_time: 0.8917  (0.8329519603563391)


   --> TIME: 2025-12-28 11:54:08 -- STEP: 48/150 -- GLOBAL_STEP: 15450
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48362675309181213  (0.4785686998317639)
     | > postnet_loss: 0.3999735116958618  (0.40210086045165855)
     | > stopnet_loss: 0.004474536515772343  (0.007718382257735356)
     | > loss: 0.22537459433078766  (0.22788577154278755)
     | > align_error: 0.6240082681179047  (0.6494541733215252)
     | > grad_norm: tensor(0.1371, device='cuda:0')  (tensor(0.2804, device='cuda:0'))
     | > step_time: 1.1175  (0.8481197506189346)
     | > loader_time: 1.0711  (0.9150174508492152)


   --> TIME: 2025-12-28 11:55:13 -- STEP: 73/150 -- GLOBAL_STEP: 15475
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48809337615966797  (0.48199755974011876)
     | > postnet_loss: 0.39997702836990356  (0.40202330073265186)
     | > stopnet_loss: 0.003835030598565936  (0.006532571868562737)
     | > loss: 0.22585263848304749  (0.22753778589914922)
     | > align_error: 0.6473791003227234  (0.6368210634140119)
     | > grad_norm: tensor(0.1572, device='cuda:0')  (tensor(0.2499, device='cuda:0'))
     | > step_time: 1.573  (1.0298935550532928)
     | > loader_time: 1.2311  (1.017656780269048)


   --> TIME: 2025-12-28 11:56:40 -- STEP: 98/150 -- GLOBAL_STEP: 15500
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4924774765968323  (0.4833684104437731)
     | > postnet_loss: 0.4043135344982147  (0.4014049181524588)
     | > stopnet_loss: 0.003932365216314793  (0.005822997506973997)
     | > loss: 0.22813011705875397  (0.22701632915710918)
     | > align_error: 0.6089144349098206  (0.6317938055310931)
     | > grad_norm: tensor(0.2145, device='cuda:0')  (tensor(0.2374, device='cuda:0'))
     | > step_time: 1.6238  (1.1736612733529543)
     | > loader_time: 2.3919  (1.2442967015869766)


   --> TIME: 2025-12-28 11:58:15 -- STEP: 123/150 -- GLOBAL_STEP: 15525
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48902207612991333  (0.4845603188363517)
     | > postnet_loss: 0.3971618115901947  (0.40095710899771714)
     | > stopnet_loss: 0.0032519022934138775  (0.005323403626604656)
     | > loss: 0.22479785978794098  (0.22670275990555927)
     | > align_error: 0.6021298766136169  (0.6273366554481227)
     | > grad_norm: tensor(0.1587, device='cuda:0')  (tensor(0.2233, device='cuda:0'))
     | > step_time: 1.9931  (1.3015782367892383)
     | > loader_time: 1.719  (1.3977985130092965)


   --> TIME: 2025-12-28 11:59:55 -- STEP: 148/150 -- GLOBAL_STEP: 15550
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5077109336853027  (0.4859584104773161)
     | > postnet_loss: 0.4084796607494354  (0.400750649740567)
     | > stopnet_loss: 0.002596486359834671  (0.004945023781368256)
     | > loss: 0.2316441386938095  (0.2266222880901517)
     | > align_error: 0.6122179925441742  (0.6239032354709265)
     | > grad_norm: tensor(0.2062, device='cuda:0')  (tensor(0.2189, device='cuda:0'))
     | > step_time: 2.789  (1.4455517659316193)
     | > loader_time: 2.0715  (1.4696282261126747)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4657362401485443  (0.4657362401485443)
     | > postnet_loss: 0.33670371770858765  (0.33670371770858765)
     | > stopnet_loss: 0.012253005057573318  (0.012253005057573318)
     | > loss: 0.2128629833459854  (0.2128629833459854)
     | > align_error: 0.7184957563877106  (0.7184957563877106)

   --> STEP: 1
     | > decoder_loss: 0.4469653367996216  (0.4469653367996216)
     | > postnet_loss: 0.3247803747653961  (0.3247803747653961)
     | > stopnet_loss: 0.009739079512655735  (0.009739079512655735)
     | > loss: 0.20267550647258759  (0.20267550647258759)
     | > align_error: 0.659425675868988  (0.659425675868988)

   --> STEP: 2
     | > decoder_loss: 0.44121068716049194  (0.44408801198005676)
     | > postnet_loss: 0.31419315934181213  (0.3194867670536041)
     | > stopnet_loss: 0.011085176840424538  (0.010412128176540136)
     | > loss: 0.1999361515045166  (0.2013058289885521)
     | > align_error: 0.6555835008621216  (0.6575045883655548)

   --> STEP: 3
     | > decoder_loss: 0.4452659785747528  (0.44448066751162213)
     | > postnet_loss: 0.3133636713027954  (0.3174457351366679)
     | > stopnet_loss: 0.008402170613408089  (0.009742142322162787)
     | > loss: 0.1980595886707306  (0.2002237488826116)
     | > align_error: 0.7349231243133545  (0.6833107670148214)

   --> STEP: 4
     | > decoder_loss: 0.45180147886276245  (0.4463108703494072)
     | > postnet_loss: 0.3225284516811371  (0.3187164142727852)
     | > stopnet_loss: 0.00826574582606554  (0.009373043198138475)
     | > loss: 0.20184822380542755  (0.20062986761331558)
     | > align_error: 0.6036149263381958  (0.663386806845665)

   --> STEP: 5
     | > decoder_loss: 0.43243029713630676  (0.44353475570678713)
     | > postnet_loss: 0.3042261302471161  (0.31581835746765136)
     | > stopnet_loss: 0.008223134092986584  (0.009143061377108097)
     | > loss: 0.19238723814487457  (0.1989813417196274)
     | > align_error: 0.6420210003852844  (0.6591136455535889)

   --> STEP: 6
     | > decoder_loss: 0.4485805928707123  (0.4443757285674413)
     | > postnet_loss: 0.31601324677467346  (0.3158508390188217)
     | > stopnet_loss: 0.007267973851412535  (0.00883054678949217)
     | > loss: 0.19841642677783966  (0.19888718922932944)
     | > align_error: 0.5936992764472961  (0.64821125070254)

   --> STEP: 7
     | > decoder_loss: 0.4593579173088074  (0.44651604124477934)
     | > postnet_loss: 0.3148896396160126  (0.3157135248184204)
     | > stopnet_loss: 0.006299538537859917  (0.008468974182116134)
     | > loss: 0.19986142218112946  (0.19902636536530086)
     | > align_error: 0.5789995789527893  (0.6383238690240043)

   --> STEP: 8
     | > decoder_loss: 0.45380035042762756  (0.44742657989263535)
     | > postnet_loss: 0.31539782881736755  (0.3156740628182888)
     | > stopnet_loss: 0.007557999342679977  (0.008355102327186614)
     | > loss: 0.19985754787921906  (0.19913026317954063)
     | > align_error: 0.5756452977657318  (0.6304890476167202)

   --> STEP: 9
     | > decoder_loss: 0.44996562600135803  (0.44770869612693787)
     | > postnet_loss: 0.3149172067642212  (0.3155899677011702)
     | > stopnet_loss: 0.006725408136844635  (0.008174025194926394)
     | > loss: 0.19794610142707825  (0.19899868965148926)
     | > align_error: 0.5914412438869476  (0.6261504027578566)

   --> STEP: 10
     | > decoder_loss: 0.47822868824005127  (0.4507606953382492)
     | > postnet_loss: 0.3304543197154999  (0.31707640290260314)
     | > stopnet_loss: 0.005573390517383814  (0.007913961727172136)
     | > loss: 0.20774415135383606  (0.19987323582172395)
     | > align_error: 0.5842797160148621  (0.6219633340835571)

   --> STEP: 11
     | > decoder_loss: 0.46466824412345886  (0.45202501795508643)
     | > postnet_loss: 0.3203293979167938  (0.317372129722075)
     | > stopnet_loss: 0.005889928434044123  (0.007729958700524135)
     | > loss: 0.20213933289051056  (0.2000792446461591)
     | > align_error: 0.5946595966815948  (0.6194811761379242)

   --> STEP: 12
     | > decoder_loss: 0.4594462513923645  (0.4526434540748596)
     | > postnet_loss: 0.31320804357528687  (0.317025122543176)
     | > stopnet_loss: 0.007938620634377003  (0.007747347195011874)
     | > loss: 0.20110219717025757  (0.20016449068983397)
     | > align_error: 0.587568998336792  (0.6168218279878298)

   --> STEP: 13
     | > decoder_loss: 0.44907984137535095  (0.4523693300210513)
     | > postnet_loss: 0.31295713782310486  (0.3167122006416321)
     | > stopnet_loss: 0.005629685707390308  (0.007584450157502523)
     | > loss: 0.19613893330097198  (0.19985483242915228)
     | > align_error: 0.5859450101852417  (0.6144466881568615)

   --> STEP: 14
     | > decoder_loss: 0.4588496685028076  (0.45283221134117674)
     | > postnet_loss: 0.31483063101768494  (0.3165778028113501)
     | > stopnet_loss: 0.004987241700291634  (0.007398935267701745)
     | > loss: 0.19840732216835022  (0.199751438839095)
     | > align_error: 0.5548384487628937  (0.6101889567715781)

   --> STEP: 15
     | > decoder_loss: 0.4580475091934204  (0.4531798978646596)
     | > postnet_loss: 0.3156282603740692  (0.3165144999821981)
     | > stopnet_loss: 0.004970027599483728  (0.007237008089820544)
     | > loss: 0.1983889788389206  (0.19966060817241668)
     | > align_error: 0.5886121094226837  (0.6087505002816518)

   --> STEP: 16
     | > decoder_loss: 0.45920228958129883  (0.4535562973469496)
     | > postnet_loss: 0.3095661699771881  (0.31608022935688496)
     | > stopnet_loss: 0.00524513004347682  (0.007112515711924061)
     | > loss: 0.19743724167346954  (0.1995216477662325)
     | > align_error: 0.6059986352920532  (0.6085785087198019)

   --> STEP: 17
     | > decoder_loss: 0.46509334444999695  (0.4542349471765406)
     | > postnet_loss: 0.3179571032524109  (0.3161906337036806)
     | > stopnet_loss: 0.004859059117734432  (0.006979959441677612)
     | > loss: 0.20062166452407837  (0.19958635463434107)
     | > align_error: 0.558479517698288  (0.6056315092479482)

   --> STEP: 18
     | > decoder_loss: 0.45945972204208374  (0.45452521244684857)
     | > postnet_loss: 0.31022879481315613  (0.3158594204319848)
     | > stopnet_loss: 0.005276427138596773  (0.006885318758173121)
     | > loss: 0.19769854843616486  (0.19948147651222017)
     | > align_error: 0.6039890348911285  (0.6055402606725693)

   --> STEP: 19
     | > decoder_loss: 0.45860084891319275  (0.4547397196292877)
     | > postnet_loss: 0.31024137139320374  (0.31556373364047)
     | > stopnet_loss: 0.004781787283718586  (0.0067746065753070935)
     | > loss: 0.19699233770370483  (0.19935046920650884)
     | > align_error: 0.6003377437591553  (0.605266443992916)

   --> STEP: 20
     | > decoder_loss: 0.45288920402526855  (0.45464719384908675)
     | > postnet_loss: 0.3059042692184448  (0.3150807604193687)
     | > stopnet_loss: 0.004533006343990564  (0.0066625265637412666)
     | > loss: 0.19423137605190277  (0.19909451454877852)
     | > align_error: 0.6227704882621765  (0.606141646206379)

   --> STEP: 21
     | > decoder_loss: 0.4509485960006714  (0.4544710701420194)
     | > postnet_loss: 0.3050098121166229  (0.3146011914525713)
     | > stopnet_loss: 0.003998332656919956  (0.006535660187225966)
     | > loss: 0.19298794865608215  (0.19880372569674537)
     | > align_error: 0.5600907504558563  (0.6039487464087351)

   --> STEP: 22
     | > decoder_loss: 0.45269137620925903  (0.4543901749632575)
     | > postnet_loss: 0.30792564153671265  (0.3142977573654868)
     | > stopnet_loss: 0.004878693260252476  (0.006460343508727171)
     | > loss: 0.19503295421600342  (0.1986323269930753)
     | > align_error: 0.6254631876945496  (0.6049266755580903)

   --> STEP: 23
     | > decoder_loss: 0.4261395335197449  (0.45316188620484393)
     | > postnet_loss: 0.2961258292198181  (0.31350767353306647)
     | > stopnet_loss: 0.0045462301932275295  (0.006377121190661969)
     | > loss: 0.18511256575584412  (0.1980445112871087)
     | > align_error: 0.5672303736209869  (0.603287705908651)

   --> STEP: 24
     | > decoder_loss: 0.46078047156333923  (0.4534793272614479)
     | > postnet_loss: 0.3115912675857544  (0.3134278232852618)
     | > stopnet_loss: 0.004391814116388559  (0.006294400062567244)
     | > loss: 0.19748476147651672  (0.19802118837833405)
     | > align_error: 0.5797128677368164  (0.6023054209848245)

   --> STEP: 25
     | > decoder_loss: 0.4590175151824951  (0.4537008547782898)
     | > postnet_loss: 0.30819591879844666  (0.31321854710578917)
     | > stopnet_loss: 0.0037153540179133415  (0.006191238220781088)
     | > loss: 0.19551871716976166  (0.19792108952999116)
     | > align_error: 0.5576223731040955  (0.6005180990695953)

   --> STEP: 26
     | > decoder_loss: 0.4349486231803894  (0.45297961510144746)
     | > postnet_loss: 0.29767823219299316  (0.31262084268606627)
     | > stopnet_loss: 0.00440345611423254  (0.0061224773705292205)
     | > loss: 0.18756017088890076  (0.19752259265917999)
     | > align_error: 0.5468407869338989  (0.5984535870643762)

   --> STEP: 27
     | > decoder_loss: 0.43146854639053345  (0.4521829088528951)
     | > postnet_loss: 0.29241272807121277  (0.31187239399662725)
     | > stopnet_loss: 0.003937377594411373  (0.006041547749191523)
     | > loss: 0.1849076896905899  (0.1970553740307137)
     | > align_error: 0.5412647426128387  (0.5963354817143193)

   --> STEP: 28
     | > decoder_loss: 0.43704015016555786  (0.45164209604263306)
     | > postnet_loss: 0.2969813048839569  (0.31134056938546045)
     | > stopnet_loss: 0.003940477967262268  (0.0059665095426940495)
     | > loss: 0.18744583427906036  (0.19671217618244036)
     | > align_error: 0.5663341283798218  (0.5952640048095158)

   --> STEP: 29
     | > decoder_loss: 0.43256133794784546  (0.4509841388669507)
     | > postnet_loss: 0.29380732774734497  (0.31073597484621507)
     | > stopnet_loss: 0.0036093222443014383  (0.005885227222059821)
     | > loss: 0.185201495885849  (0.19631525617221307)
     | > align_error: 0.5405827462673187  (0.5933784441701297)

   --> STEP: 30
     | > decoder_loss: 0.4328857958316803  (0.45038086076577505)
     | > postnet_loss: 0.2942849099636078  (0.31018760601679485)
     | > stopnet_loss: 0.0028804056346416473  (0.0057850665024792155)
     | > loss: 0.18467308580875397  (0.1959271838267644)
     | > align_error: 0.5335031747817993  (0.5913826018571854)

   --> STEP: 31
     | > decoder_loss: 0.428181916475296  (0.4496647657886628)
     | > postnet_loss: 0.29283425211906433  (0.3096278204071906)
     | > stopnet_loss: 0.0037026943173259497  (0.005717893206183949)
     | > loss: 0.18395674228668213  (0.1955410405512779)
     | > align_error: 0.5560674071311951  (0.5902434020273147)

   --> STEP: 32
     | > decoder_loss: 0.44062086939811707  (0.44938214402645826)
     | > postnet_loss: 0.29908618330955505  (0.3092983942478895)
     | > stopnet_loss: 0.0038683719467371702  (0.005660095666826237)
     | > loss: 0.18879513442516327  (0.19533023098483682)
     | > align_error: 0.531060516834259  (0.5883939368650317)

   --> STEP: 33
     | > decoder_loss: 0.43712982535362244  (0.4490108616424329)
     | > postnet_loss: 0.29636111855506897  (0.3089063555905313)
     | > stopnet_loss: 0.004054947290569544  (0.0056114548069396706)
     | > loss: 0.18742768466472626  (0.19509075988422742)
     | > align_error: 0.5462145805358887  (0.5871157745520273)

   --> STEP: 34
     | > decoder_loss: 0.44248852133750916  (0.44881902810405283)
     | > postnet_loss: 0.29777002334594727  (0.3085788164068671)
     | > stopnet_loss: 0.003317829454317689  (0.005543995237744907)
     | > loss: 0.18838247656822205  (0.19489345743375666)
     | > align_error: 0.5635842680931091  (0.5864236714208827)

   --> STEP: 35
     | > decoder_loss: 0.43996167182922363  (0.44856596078191485)
     | > postnet_loss: 0.2972300946712494  (0.30825456721442085)
     | > stopnet_loss: 0.0035337775480002165  (0.005486560446609344)
     | > loss: 0.18783172965049744  (0.1946916937828064)
     | > align_error: 0.5331442356109619  (0.5849014018263136)

   --> STEP: 36
     | > decoder_loss: 0.4465302526950836  (0.44850941333505845)
     | > postnet_loss: 0.30158907175064087  (0.3080694145626492)
     | > stopnet_loss: 0.0036863991990685463  (0.005436555967510988)
     | > loss: 0.1907162368297577  (0.1945812644229995)
     | > align_error: 0.6337057948112488  (0.5862570794092284)

   --> STEP: 37
     | > decoder_loss: 0.43853721022605896  (0.4482398943321125)
     | > postnet_loss: 0.2981589734554291  (0.3078015648029946)
     | > stopnet_loss: 0.003582561621442437  (0.005386448012211839)
     | > loss: 0.18775661289691925  (0.19439681438175407)
     | > align_error: 0.5188110172748566  (0.5844342128650563)

   --> STEP: 38
     | > decoder_loss: 0.426577091217041  (0.4476698205659264)
     | > postnet_loss: 0.2912057638168335  (0.3073648331980956)
     | > stopnet_loss: 0.003166558686643839  (0.005328029872065312)
     | > loss: 0.18261227011680603  (0.1940866947958344)
     | > align_error: 0.5512363314628601  (0.5835605844071037)

   --> STEP: 39
     | > decoder_loss: 0.44202929735183716  (0.44752519176556516)
     | > postnet_loss: 0.3016928732395172  (0.30721939832736284)
     | > stopnet_loss: 0.003483447479084134  (0.005280732887629897)
     | > loss: 0.18941399455070496  (0.1939668819690362)
     | > align_error: 0.5458331108093262  (0.582593213289212)

   --> STEP: 40
     | > decoder_loss: 0.4393875002861023  (0.44732174947857856)
     | > postnet_loss: 0.30031198263168335  (0.3070467129349709)
     | > stopnet_loss: 0.0030397712253034115  (0.005224708846071735)
     | > loss: 0.18796464800834656  (0.19381682612001896)
     | > align_error: 0.5837249755859375  (0.5826215073466301)

   --> STEP: 41
     | > decoder_loss: 0.4289371073246002  (0.44687334357238395)
     | > postnet_loss: 0.29207682609558105  (0.30668159374376625)
     | > stopnet_loss: 0.0037328884936869144  (0.005188322983818446)
     | > loss: 0.1839863657951355  (0.1935770587950218)
     | > align_error: 0.5029253661632538  (0.5806776990250844)

   --> STEP: 42
     | > decoder_loss: 0.4344555139541626  (0.44657768096242634)
     | > postnet_loss: 0.2944825291633606  (0.3063911398251851)
     | > stopnet_loss: 0.0033076477702707052  (0.0051435450025435)
     | > loss: 0.18554215133190155  (0.19338575147447132)
     | > align_error: 0.5793681144714355  (0.5806465184404737)

   --> STEP: 43
     | > decoder_loss: 0.43314129114151  (0.44626520678054454)
     | > postnet_loss: 0.29312676191329956  (0.30608266592025757)
     | > stopnet_loss: 0.002947357250377536  (0.005092470868772199)
     | > loss: 0.1845143735408783  (0.1931794403597366)
     | > align_error: 0.5514351725578308  (0.5799671848152959)

   --> STEP: 44
     | > decoder_loss: 0.4507414400577545  (0.4463669393550266)
     | > postnet_loss: 0.3033316433429718  (0.3060201426798647)
     | > stopnet_loss: 0.0026896113995462656  (0.005037860426289792)
     | > loss: 0.1912078857421875  (0.19313463230024686)
     | > align_error: 0.5508696436882019  (0.5793058770624073)

   --> STEP: 45
     | > decoder_loss: 0.4439535140991211  (0.44631330768267313)
     | > postnet_loss: 0.30268895626068115  (0.30594611631499397)
     | > stopnet_loss: 0.0033198934979736805  (0.004999683383438322)
     | > loss: 0.18998050689697266  (0.19306454062461853)
     | > align_error: 0.5522733628749847  (0.578705154524909)

   --> STEP: 46
     | > decoder_loss: 0.4350031316280365  (0.44606743429018103)
     | > postnet_loss: 0.29430514574050903  (0.3056930517372878)
     | > stopnet_loss: 0.0032122477423399687  (0.0049608260868927055)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34517796473069623 (-0.015008933616406983)
     | > avg_decoder_loss: 0.4419020703344634 (-0.0005501359701156616)
     | > avg_postnet_loss: 0.30245778506452387 (+0.0018368173729289006)
     | > avg_stopnet_loss: 0.004397033025849272 (-9.280241404967596e-07)
     | > avg_loss: 0.1904869978175019 (+0.00032074252764383027)
     | > avg_align_error: 0.571543304306088 (-0.0005288087960445553)


 > EPOCH: 103/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 12:01:59)

   --> TIME: 2025-12-28 12:02:32 -- STEP: 22/150 -- GLOBAL_STEP: 15575
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4799105226993561  (0.469759075479074)
     | > postnet_loss: 0.4034959673881531  (0.39904696020213043)
     | > stopnet_loss: 0.006575810257345438  (0.010041639378125017)
     | > loss: 0.2274274379014969  (0.2272431498224085)
     | > align_error: 0.6306020021438599  (0.6728338517925956)
     | > grad_norm: tensor(0.1971, device='cuda:0')  (tensor(0.2850, device='cuda:0'))
     | > step_time: 0.8683  (0.6197117025201971)
     | > loader_time: 0.8446  (0.8361821716481989)


   --> TIME: 2025-12-28 12:03:23 -- STEP: 47/150 -- GLOBAL_STEP: 15600
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48602166771888733  (0.47788615429655035)
     | > postnet_loss: 0.4023302495479584  (0.40167823877740416)
     | > stopnet_loss: 0.004463302902877331  (0.00769881393879335)
     | > loss: 0.22655127942562103  (0.22758991382223495)
     | > align_error: 0.6584877669811249  (0.6494152057678142)
     | > grad_norm: tensor(0.1657, device='cuda:0')  (tensor(0.2500, device='cuda:0'))
     | > step_time: 1.2489  (0.8506250787288585)
     | > loader_time: 1.1136  (0.9237233070617027)


   --> TIME: 2025-12-28 12:04:28 -- STEP: 72/150 -- GLOBAL_STEP: 15625
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48412203788757324  (0.4811885824633969)
     | > postnet_loss: 0.3972734808921814  (0.4015283083750142)
     | > stopnet_loss: 0.0036650788970291615  (0.006509598254019188)
     | > loss: 0.22401395440101624  (0.22718882208897007)
     | > align_error: 0.5964516997337341  (0.6362709489961466)
     | > grad_norm: tensor(0.1395, device='cuda:0')  (tensor(0.2196, device='cuda:0'))
     | > step_time: 1.4443  (1.022513445880678)
     | > loader_time: 1.2563  (1.0254851380983987)


   --> TIME: 2025-12-28 12:05:44 -- STEP: 97/150 -- GLOBAL_STEP: 15650
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4859285354614258  (0.48269267579943864)
     | > postnet_loss: 0.3976089656352997  (0.4009045927794938)
     | > stopnet_loss: 0.0033621115144342184  (0.005795363252790474)
     | > loss: 0.22424648702144623  (0.22669468082718014)
     | > align_error: 0.5763734877109528  (0.6315501949836297)
     | > grad_norm: tensor(0.2161, device='cuda:0')  (tensor(0.2101, device='cuda:0'))
     | > step_time: 1.7512  (1.1805951374093282)
     | > loader_time: 1.4167  (1.1283750017893683)


   --> TIME: 2025-12-28 12:07:09 -- STEP: 122/150 -- GLOBAL_STEP: 15675
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48647767305374146  (0.48397813639679893)
     | > postnet_loss: 0.39669322967529297  (0.400566359523867)
     | > stopnet_loss: 0.0033515661489218473  (0.005303366600199925)
     | > loss: 0.22414429485797882  (0.2264394911586261)
     | > align_error: 0.5946329832077026  (0.6272929415839618)
     | > grad_norm: tensor(0.1503, device='cuda:0')  (tensor(0.2053, device='cuda:0'))
     | > step_time: 2.0224  (1.3115114227670135)
     | > loader_time: 1.7689  (1.220091022428919)


   --> TIME: 2025-12-28 12:08:53 -- STEP: 147/150 -- GLOBAL_STEP: 15700
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49631983041763306  (0.48533878257485474)
     | > postnet_loss: 0.4010239541530609  (0.40032304346966907)
     | > stopnet_loss: 0.002752576256170869  (0.004933346560237563)
     | > loss: 0.22708851099014282  (0.22634880346100347)
     | > align_error: 0.6284850835800171  (0.6238229187572893)
     | > grad_norm: tensor(0.1494, device='cuda:0')  (tensor(0.2004, device='cuda:0'))
     | > step_time: 2.503  (1.4498052953862817)
     | > loader_time: 2.1477  (1.360357852209182)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46631136536598206  (0.46631136536598206)
     | > postnet_loss: 0.3372415006160736  (0.3372415006160736)
     | > stopnet_loss: 0.012207118794322014  (0.012207118794322014)
     | > loss: 0.21309533715248108  (0.21309533715248108)
     | > align_error: 0.7189702689647675  (0.7189702689647675)

   --> STEP: 1
     | > decoder_loss: 0.4475991725921631  (0.4475991725921631)
     | > postnet_loss: 0.32556694746017456  (0.32556694746017456)
     | > stopnet_loss: 0.009692779742181301  (0.009692779742181301)
     | > loss: 0.2029843032360077  (0.2029843032360077)
     | > align_error: 0.6597166955471039  (0.6597166955471039)

   --> STEP: 2
     | > decoder_loss: 0.4428664445877075  (0.4452328085899353)
     | > postnet_loss: 0.3153419494628906  (0.3204544484615326)
     | > stopnet_loss: 0.011113518849015236  (0.010403149295598269)
     | > loss: 0.20066562294960022  (0.20182496309280396)
     | > align_error: 0.6561436653137207  (0.6579301804304123)

   --> STEP: 3
     | > decoder_loss: 0.44460585713386536  (0.4450238247712453)
     | > postnet_loss: 0.3134681284427643  (0.3181256751219432)
     | > stopnet_loss: 0.008420283906161785  (0.009742194165786108)
     | > loss: 0.19793878495693207  (0.20052957038084665)
     | > align_error: 0.7350185811519623  (0.6836263140042623)

   --> STEP: 4
     | > decoder_loss: 0.45272886753082275  (0.4469500854611397)
     | > postnet_loss: 0.3236386179924011  (0.31950391083955765)
     | > stopnet_loss: 0.008221317082643509  (0.009361974895000458)
     | > loss: 0.20231318473815918  (0.2009754739701748)
     | > align_error: 0.6039659380912781  (0.6637112200260162)

   --> STEP: 5
     | > decoder_loss: 0.4329993426799774  (0.44415993690490724)
     | > postnet_loss: 0.3048458993434906  (0.31657230854034424)
     | > stopnet_loss: 0.00822143442928791  (0.009133866801857949)
     | > loss: 0.19268274307250977  (0.19931692779064178)
     | > align_error: 0.642626017332077  (0.6594941794872284)

   --> STEP: 6
     | > decoder_loss: 0.4506157338619232  (0.4452359030644099)
     | > postnet_loss: 0.3179164230823517  (0.31679632763067883)
     | > stopnet_loss: 0.007309688255190849  (0.008829837044080099)
     | > loss: 0.19944272935390472  (0.19933789471785227)
     | > align_error: 0.5942926406860352  (0.6486272563536962)

   --> STEP: 7
     | > decoder_loss: 0.4597456455230713  (0.44730872341564726)
     | > postnet_loss: 0.31560784578323364  (0.3166265445096152)
     | > stopnet_loss: 0.0063331956043839455  (0.008473173981266362)
     | > loss: 0.2001715749502182  (0.19945699189390456)
     | > align_error: 0.5795230269432068  (0.6387552235807691)

   --> STEP: 8
     | > decoder_loss: 0.45461905002593994  (0.4482225142419338)
     | > postnet_loss: 0.31711146235466003  (0.3166871592402458)
     | > stopnet_loss: 0.007602558471262455  (0.008364347042515874)
     | > loss: 0.20053519308567047  (0.1995917670428753)
     | > align_error: 0.5759521126747131  (0.6309048347175121)

   --> STEP: 9
     | > decoder_loss: 0.4535455107688904  (0.44881395830048454)
     | > postnet_loss: 0.3178856074810028  (0.31682032015588546)
     | > stopnet_loss: 0.006710842251777649  (0.008180624287989404)
     | > loss: 0.19956861436367035  (0.19958919452296364)
     | > align_error: 0.5918049216270447  (0.6265603999296824)

   --> STEP: 10
     | > decoder_loss: 0.4821181297302246  (0.45214437544345853)
     | > postnet_loss: 0.3331449329853058  (0.3184527814388275)
     | > stopnet_loss: 0.005805698223412037  (0.007943131681531667)
     | > loss: 0.20962145924568176  (0.20059242099523544)
     | > align_error: 0.5864906311035156  (0.6225534230470657)

   --> STEP: 11
     | > decoder_loss: 0.4661630690097809  (0.45341880213130603)
     | > postnet_loss: 0.3216792345046997  (0.3187460953539068)
     | > stopnet_loss: 0.0058919996954500675  (0.007756665137342431)
     | > loss: 0.20285256206989288  (0.20079788836565884)
     | > align_error: 0.5951773524284363  (0.620064689354463)

   --> STEP: 12
     | > decoder_loss: 0.4616158604621887  (0.45410189032554626)
     | > postnet_loss: 0.31578192114830017  (0.3184990808367729)
     | > stopnet_loss: 0.007908593863248825  (0.0077693258645012975)
     | > loss: 0.20225803554058075  (0.20091956729690233)
     | > align_error: 0.5879887938499451  (0.6173916980624199)

   --> STEP: 13
     | > decoder_loss: 0.451724112033844  (0.4539189843031076)
     | > postnet_loss: 0.31502199172973633  (0.31823161244392395)
     | > stopnet_loss: 0.005656298715621233  (0.007606785314587446)
     | > loss: 0.19734282791614532  (0.20064443349838257)
     | > align_error: 0.5866190195083618  (0.6150245689428769)

   --> STEP: 14
     | > decoder_loss: 0.45956453680992126  (0.45432223805359434)
     | > postnet_loss: 0.3158867359161377  (0.3180641212633678)
     | > stopnet_loss: 0.004961126949638128  (0.007417809717091066)
     | > loss: 0.1988239586353302  (0.2005143995795931)
     | > align_error: 0.555304765701294  (0.6107588687113353)

   --> STEP: 15
     | > decoder_loss: 0.45883873105049133  (0.4546233375867208)
     | > postnet_loss: 0.3161231577396393  (0.3179347236951192)
     | > stopnet_loss: 0.005011697765439749  (0.007257402253647645)
     | > loss: 0.19875216484069824  (0.2003969172636668)
     | > align_error: 0.5889986455440521  (0.6093081871668498)

   --> STEP: 16
     | > decoder_loss: 0.4601277709007263  (0.45496736466884613)
     | > postnet_loss: 0.3103714883327484  (0.31746202148497105)
     | > stopnet_loss: 0.005245990119874477  (0.007131688995286822)
     | > loss: 0.19787079095840454  (0.2002390343695879)
     | > align_error: 0.6066679954528809  (0.6091431751847267)

   --> STEP: 17
     | > decoder_loss: 0.4665560722351074  (0.45564905334921446)
     | > postnet_loss: 0.31897857785224915  (0.31755123068304625)
     | > stopnet_loss: 0.00487715657800436  (0.006999069441329031)
     | > loss: 0.20126080513000488  (0.20029913853196538)
     | > align_error: 0.5590962767601013  (0.6061992399832782)

   --> STEP: 18
     | > decoder_loss: 0.4600910544395447  (0.4558958311875661)
     | > postnet_loss: 0.3108287453651428  (0.31717775927649605)
     | > stopnet_loss: 0.005317876115441322  (0.006905669812113047)
     | > loss: 0.19804783165454865  (0.20017406592766443)
     | > align_error: 0.6044537425041199  (0.6061022679011027)

   --> STEP: 19
     | > decoder_loss: 0.4595929980278015  (0.45609041891599955)
     | > postnet_loss: 0.3113842308521271  (0.31687283672784505)
     | > stopnet_loss: 0.00479562021791935  (0.006794614570313378)
     | > loss: 0.19753994047641754  (0.20003542774601987)
     | > align_error: 0.6007965505123138  (0.6058230196174822)

   --> STEP: 20
     | > decoder_loss: 0.4536930024623871  (0.45597054809331894)
     | > postnet_loss: 0.30619513988494873  (0.3163389518857002)
     | > stopnet_loss: 0.004546157084405422  (0.006682191696017981)
     | > loss: 0.19451819360256195  (0.19975956603884698)
     | > align_error: 0.6231001019477844  (0.6066868737339973)

   --> STEP: 21
     | > decoder_loss: 0.453100323677063  (0.4558338707401639)
     | > postnet_loss: 0.30711832642555237  (0.315899874482836)
     | > stopnet_loss: 0.004002346657216549  (0.006554580027503627)
     | > loss: 0.19405700266361237  (0.19948801540193103)
     | > align_error: 0.5607767701148987  (0.604500678323564)

   --> STEP: 22
     | > decoder_loss: 0.4548078179359436  (0.4557872319763357)
     | > postnet_loss: 0.30938979983329773  (0.31560396199876606)
     | > stopnet_loss: 0.004918014630675316  (0.006480190691284158)
     | > loss: 0.1959674060344696  (0.19932798770341006)
     | > align_error: 0.6259604096412659  (0.6054761206561868)

   --> STEP: 23
     | > decoder_loss: 0.42661526799201965  (0.45451888571614807)
     | > postnet_loss: 0.2965312898159027  (0.3147747153821198)
     | > stopnet_loss: 0.004565749783068895  (0.006396954130057407)
     | > loss: 0.1853523850440979  (0.1987203528051791)
     | > align_error: 0.5678360462188721  (0.6038395956806514)

   --> STEP: 24
     | > decoder_loss: 0.4609817862510681  (0.4547881732384364)
     | > postnet_loss: 0.31153732538223267  (0.3146398241321245)
     | > stopnet_loss: 0.0044257729314267635  (0.006314821580114464)
     | > loss: 0.1975555568933487  (0.19867181964218616)
     | > align_error: 0.5801085233688354  (0.6028508010009924)

   --> STEP: 25
     | > decoder_loss: 0.45980721712112427  (0.4549889349937439)
     | > postnet_loss: 0.3087596893310547  (0.31440461874008174)
     | > stopnet_loss: 0.0037393502425402403  (0.006211802726611495)
     | > loss: 0.19588108360767365  (0.19856019020080568)
     | > align_error: 0.5586744546890259  (0.6010837471485138)

   --> STEP: 26
     | > decoder_loss: 0.43484824895858765  (0.454214293223161)
     | > postnet_loss: 0.29771971702575684  (0.3137628917510693)
     | > stopnet_loss: 0.004406763240695  (0.006142378130999322)
     | > loss: 0.18754875659942627  (0.19813667352382952)
     | > align_error: 0.5473740696907043  (0.5990179903232135)

   --> STEP: 27
     | > decoder_loss: 0.4322502911090851  (0.45340081166338037)
     | > postnet_loss: 0.2930313050746918  (0.31299505520749976)
     | > stopnet_loss: 0.00395103357732296  (0.006061217221603902)
     | > loss: 0.18527142703533173  (0.19766018291314444)
     | > align_error: 0.5418447852134705  (0.5969004642080378)

   --> STEP: 28
     | > decoder_loss: 0.4378449618816376  (0.4528452455997467)
     | > postnet_loss: 0.2975139319896698  (0.31244215794972013)
     | > stopnet_loss: 0.003952598664909601  (0.005985909416007676)
     | > loss: 0.1877923160791397  (0.19730775909764425)
     | > align_error: 0.5669171214103699  (0.5958296305366925)

   --> STEP: 29
     | > decoder_loss: 0.43390506505966187  (0.4521921359259507)
     | > postnet_loss: 0.29513242840766907  (0.31184527072413215)
     | > stopnet_loss: 0.003603855613619089  (0.005903769629718414)
     | > loss: 0.18586324155330658  (0.19691312056163263)
     | > align_error: 0.5410678088665009  (0.59394129185841)

   --> STEP: 30
     | > decoder_loss: 0.43414515256881714  (0.4515905698140462)
     | > postnet_loss: 0.29513442516326904  (0.31128824253877)
     | > stopnet_loss: 0.0029324241913855076  (0.005804724781773985)
     | > loss: 0.1852523237466812  (0.19652442733446757)
     | > align_error: 0.5339860916137695  (0.5919427851835887)

   --> STEP: 31
     | > decoder_loss: 0.428285151720047  (0.45083878213359463)
     | > postnet_loss: 0.2926979064941406  (0.31068855427926584)
     | > stopnet_loss: 0.0037591580767184496  (0.005738738759030257)
     | > loss: 0.18400491774082184  (0.19612057218628545)
     | > align_error: 0.5564472079277039  (0.5907977665624311)

   --> STEP: 32
     | > decoder_loss: 0.4411085546016693  (0.45053471252322197)
     | > postnet_loss: 0.2994233965873718  (0.3103365181013942)
     | > stopnet_loss: 0.0038890948053449392  (0.005680937385477591)
     | > loss: 0.18902207911014557  (0.19589874427765608)
     | > align_error: 0.5317331254482269  (0.5889519965276122)

   --> STEP: 33
     | > decoder_loss: 0.4377874433994293  (0.4501484316406828)
     | > postnet_loss: 0.29668065905570984  (0.3099227041909189)
     | > stopnet_loss: 0.004036178812384605  (0.0056310962165959854)
     | > loss: 0.18765319883823395  (0.19564887926434027)
     | > align_error: 0.5464602708816528  (0.5876643684777346)

   --> STEP: 34
     | > decoder_loss: 0.4428022503852844  (0.44993236748611226)
     | > postnet_loss: 0.29781374335289  (0.30956655828391805)
     | > stopnet_loss: 0.003354331711307168  (0.005564132554675727)
     | > loss: 0.1885083168745041  (0.19543886272346273)
     | > align_error: 0.5639956295490265  (0.5869682290974785)

   --> STEP: 35
     | > decoder_loss: 0.44069328904151917  (0.4496683938162667)
     | > postnet_loss: 0.29773715138435364  (0.30922857522964475)
     | > stopnet_loss: 0.0035409843549132347  (0.005506328320396798)
     | > loss: 0.1881485879421234  (0.1952305691582816)
     | > align_error: 0.533653736114502  (0.5854449578693934)

   --> STEP: 36
     | > decoder_loss: 0.4474043548107147  (0.4496055038438903)
     | > postnet_loss: 0.3019445538520813  (0.30902624130249023)
     | > stopnet_loss: 0.003715283004567027  (0.005456577061623748)
     | > loss: 0.19105249643325806  (0.1951145115825865)
     | > align_error: 0.6342356204986572  (0.5868002540535397)

   --> STEP: 37
     | > decoder_loss: 0.4392034709453583  (0.44932436781960566)
     | > postnet_loss: 0.2985604405403137  (0.3087433818224314)
     | > stopnet_loss: 0.0035972425248473883  (0.005406324776846009)
     | > loss: 0.18803821504116058  (0.19492326032471013)
     | > align_error: 0.5193605422973633  (0.5849775591412106)

   --> STEP: 38
     | > decoder_loss: 0.42682376503944397  (0.4487322466938119)
     | > postnet_loss: 0.29120945930480957  (0.30828196280880976)
     | > stopnet_loss: 0.003175570862367749  (0.005347620726465003)
     | > loss: 0.18268387019634247  (0.19460117111080572)
     | > align_error: 0.5518076717853546  (0.584104667368688)

   --> STEP: 39
     | > decoder_loss: 0.4426373541355133  (0.44857596739744526)
     | > postnet_loss: 0.3019099533557892  (0.30811857795104003)
     | > stopnet_loss: 0.003516387427225709  (0.005300666026484508)
     | > loss: 0.189653217792511  (0.1944743005129007)
     | > align_error: 0.5463045835494995  (0.5831354344502474)

   --> STEP: 40
     | > decoder_loss: 0.43938353657722473  (0.4483461566269398)
     | > postnet_loss: 0.30026787519454956  (0.30792231038212775)
     | > stopnet_loss: 0.003066672245040536  (0.005244816181948409)
     | > loss: 0.1879795342683792  (0.19431193135678768)
     | > align_error: 0.5843333899974823  (0.5831653833389283)

   --> STEP: 41
     | > decoder_loss: 0.429807186126709  (0.447893986614739)
     | > postnet_loss: 0.29248046875  (0.3075456800984173)
     | > stopnet_loss: 0.003755275160074234  (0.0052084859131222095)
     | > loss: 0.18432718515396118  (0.1940684009615968)
     | > align_error: 0.5036287903785706  (0.5812254664374562)

   --> STEP: 42
     | > decoder_loss: 0.4348744750022888  (0.44758399824301404)
     | > postnet_loss: 0.29448994994163513  (0.3072348293803987)
     | > stopnet_loss: 0.0033063790760934353  (0.005163197655097715)
     | > loss: 0.18564747273921967  (0.19386790267058782)
     | > align_error: 0.5798415541648865  (0.5811925161452521)

   --> STEP: 43
     | > decoder_loss: 0.43349194526672363  (0.44725627608077473)
     | > postnet_loss: 0.2932106852531433  (0.30690868649371833)
     | > stopnet_loss: 0.00295805255882442  (0.005111915210998336)
     | > loss: 0.18463371694087982  (0.19365315416524576)
     | > align_error: 0.5520077049732208  (0.5805137996063677)

   --> STEP: 44
     | > decoder_loss: 0.4517867863178253  (0.4473592422225259)
     | > postnet_loss: 0.30411189794540405  (0.3068451231176203)
     | > stopnet_loss: 0.002696614945307374  (0.0050570220231417225)
     | > loss: 0.19167129695415497  (0.1936081119559028)
     | > align_error: 0.5513445138931274  (0.5798508612947032)

   --> STEP: 45
     | > decoder_loss: 0.44479861855506897  (0.44730233947436016)
     | > postnet_loss: 0.3029777407646179  (0.3067591812875536)
     | > stopnet_loss: 0.003325756872072816  (0.00501854946422908)
     | > loss: 0.1902698576450348  (0.1935339285267724)
     | > align_error: 0.552800327539444  (0.5792497383223641)

   --> STEP: 46
     | > decoder_loss: 0.43560564517974854  (0.44704806351143384)
     | > postnet_loss: 0.29463598132133484  (0.306495633462201)
     | > stopnet_loss: 0.0032385962549597025  (0.004979854829244963)
     | > loss: 0.1857990175485611  (0.19336577828811563)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3435004768949566 (-0.008094740636421016)
     | > avg_decoder_loss: 0.4415353166334557 (-0.0012457501707655028)
     | > avg_postnet_loss: 0.301552175120874 (-0.0016180556831936754)
     | > avg_stopnet_loss: 0.004403942373976336 (-8.79777750621355e-06)
     | > avg_loss: 0.19017581461053903 (-0.0007247484543106975)
     | > avg_align_error: 0.5712627172470094 (-0.0007647447513809968)


 > EPOCH: 105/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 12:19:59)

   --> TIME: 2025-12-28 12:20:28 -- STEP: 20/150 -- GLOBAL_STEP: 15875
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4746067225933075  (0.4705068841576576)
     | > postnet_loss: 0.3991158604621887  (0.3995930626988411)
     | > stopnet_loss: 0.007416763808578253  (0.01045601072255522)
     | > loss: 0.22584740817546844  (0.22798099666833876)
     | > align_error: 0.6292767226696014  (0.6777757838368416)
     | > grad_norm: tensor(0.1987, device='cuda:0')  (tensor(0.2655, device='cuda:0'))
     | > step_time: 0.8249  (0.6228617548942565)
     | > loader_time: 1.0173  (0.8001102209091187)


   --> TIME: 2025-12-28 12:21:20 -- STEP: 45/150 -- GLOBAL_STEP: 15900
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48471033573150635  (0.4780642052491506)
     | > postnet_loss: 0.4017278850078583  (0.4018499818113115)
     | > stopnet_loss: 0.004906269256025553  (0.007877101376652717)
     | > loss: 0.22651582956314087  (0.2278556489282184)
     | > align_error: 0.6312827467918396  (0.648807774649726)
     | > grad_norm: tensor(0.1533, device='cuda:0')  (tensor(0.2370, device='cuda:0'))
     | > step_time: 1.2508  (0.8556194729275174)
     | > loader_time: 1.2575  (0.9244309902191162)


   --> TIME: 2025-12-28 12:22:25 -- STEP: 70/150 -- GLOBAL_STEP: 15925
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4897820055484772  (0.4814069428614208)
     | > postnet_loss: 0.4011712074279785  (0.4017044012035642)
     | > stopnet_loss: 0.003908168058842421  (0.006622916912393909)
     | > loss: 0.22664646804332733  (0.22740075375352586)
     | > align_error: 0.5948036015033722  (0.6370112035955702)
     | > grad_norm: tensor(0.1576, device='cuda:0')  (tensor(0.2126, device='cuda:0'))
     | > step_time: 1.5158  (1.0326354128973825)
     | > loader_time: 1.2959  (1.0356598581586565)


   --> TIME: 2025-12-28 12:23:41 -- STEP: 95/150 -- GLOBAL_STEP: 15950
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4862096905708313  (0.48272494956066736)
     | > postnet_loss: 0.3975594639778137  (0.4009212277437511)
     | > stopnet_loss: 0.0034483904018998146  (0.005885342814910569)
     | > loss: 0.2243906855583191  (0.22679688836398879)
     | > align_error: 0.6011139750480652  (0.6322937243863157)
     | > grad_norm: tensor(0.1091, device='cuda:0')  (tensor(0.2045, device='cuda:0'))
     | > step_time: 1.6391  (1.1855889872500767)
     | > loader_time: 1.6362  (1.145438071301109)


   --> TIME: 2025-12-28 12:25:06 -- STEP: 120/150 -- GLOBAL_STEP: 15975
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4884200394153595  (0.48398560906449956)
     | > postnet_loss: 0.3967272937297821  (0.4005289370814959)
     | > stopnet_loss: 0.00324604962952435  (0.0053682616931231076)
     | > loss: 0.22453288733959198  (0.2264968991279602)
     | > align_error: 0.6215709745883942  (0.6272243656218052)
     | > grad_norm: tensor(0.1306, device='cuda:0')  (tensor(0.1935, device='cuda:0'))
     | > step_time: 1.9263  (1.3133416434129075)
     | > loader_time: 1.5789  (1.2345272401968637)


   --> TIME: 2025-12-28 12:26:45 -- STEP: 145/150 -- GLOBAL_STEP: 16000
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49364832043647766  (0.485127159233751)
     | > postnet_loss: 0.39927738904953003  (0.4001594021402556)
     | > stopnet_loss: 0.0027415286749601364  (0.004984573310176873)
     | > loss: 0.2259729653596878  (0.22630621441479387)
     | > align_error: 0.6360081732273102  (0.6236876356190648)
     | > grad_norm: tensor(0.2054, device='cuda:0')  (tensor(0.1883, device='cuda:0'))
     | > step_time: 2.314  (1.4418558466023408)
     | > loader_time: 2.1892  (1.3532491355106742)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4648429751396179  (0.4648429751396179)
     | > postnet_loss: 0.3344864249229431  (0.3344864249229431)
     | > stopnet_loss: 0.012222399935126305  (0.012222399935126305)
     | > loss: 0.21205474436283112  (0.21205474436283112)
     | > align_error: 0.7181783616542816  (0.7181783616542816)

   --> STEP: 1
     | > decoder_loss: 0.44565799832344055  (0.44565799832344055)
     | > postnet_loss: 0.321665495634079  (0.321665495634079)
     | > stopnet_loss: 0.009623005986213684  (0.009623005986213684)
     | > loss: 0.20145387947559357  (0.20145387947559357)
     | > align_error: 0.6589793264865875  (0.6589793264865875)

   --> STEP: 2
     | > decoder_loss: 0.44116878509521484  (0.4434133917093277)
     | > postnet_loss: 0.3132588565349579  (0.31746217608451843)
     | > stopnet_loss: 0.01113808248192072  (0.010380544234067202)
     | > loss: 0.19974499940872192  (0.20059943944215775)
     | > align_error: 0.6552659571170807  (0.6571226418018341)

   --> STEP: 3
     | > decoder_loss: 0.4450313448905945  (0.4439527094364166)
     | > postnet_loss: 0.3118230104446411  (0.3155824542045593)
     | > stopnet_loss: 0.008424408733844757  (0.009728499067326387)
     | > loss: 0.19763800501823425  (0.19961229463418326)
     | > align_error: 0.734935462474823  (0.6830602486928304)

   --> STEP: 4
     | > decoder_loss: 0.4502350986003876  (0.44552330672740936)
     | > postnet_loss: 0.3201243579387665  (0.3167179301381111)
     | > stopnet_loss: 0.0082398084923625  (0.009356326423585415)
     | > loss: 0.2008296698331833  (0.19991663843393326)
     | > align_error: 0.6032843589782715  (0.6631162762641907)

   --> STEP: 5
     | > decoder_loss: 0.4311065673828125  (0.44263995885849)
     | > postnet_loss: 0.30261290073394775  (0.31389692425727844)
     | > stopnet_loss: 0.008255479857325554  (0.009136157110333443)
     | > loss: 0.19168534874916077  (0.19827038049697876)
     | > align_error: 0.6418679058551788  (0.6588666021823884)

   --> STEP: 6
     | > decoder_loss: 0.4472599923610687  (0.4434099644422531)
     | > postnet_loss: 0.31413134932518005  (0.3139359951019287)
     | > stopnet_loss: 0.007297030184417963  (0.008829635956014195)
     | > loss: 0.19764485955238342  (0.19816612700621286)
     | > align_error: 0.5933513343334198  (0.6479473908742269)

   --> STEP: 7
     | > decoder_loss: 0.4584590494632721  (0.44555983373097013)
     | > postnet_loss: 0.31388378143310547  (0.31392853600638254)
     | > stopnet_loss: 0.006307911593466997  (0.008469389618507453)
     | > loss: 0.1993936151266098  (0.19834148245198385)
     | > align_error: 0.5788631439208984  (0.6380782127380371)

   --> STEP: 8
     | > decoder_loss: 0.45485401153564453  (0.4467216059565544)
     | > postnet_loss: 0.31527912616729736  (0.3140973597764969)
     | > stopnet_loss: 0.0075806207023561  (0.008358293503988534)
     | > loss: 0.200113907456398  (0.19856303557753563)
     | > align_error: 0.5751952230930328  (0.6302178390324116)

   --> STEP: 9
     | > decoder_loss: 0.45059671998023987  (0.44715217418140835)
     | > postnet_loss: 0.31415754556655884  (0.31410404708650375)
     | > stopnet_loss: 0.006691394839435816  (0.008173082541260455)
     | > loss: 0.19787997007369995  (0.19848713941044277)
     | > align_error: 0.5909603834152222  (0.6258558995193906)

   --> STEP: 10
     | > decoder_loss: 0.47846752405166626  (0.45028370916843413)
     | > postnet_loss: 0.3289884328842163  (0.315592485666275)
     | > stopnet_loss: 0.005737972445785999  (0.007929571531713009)
     | > loss: 0.20760196447372437  (0.19939862191677094)
     | > align_error: 0.5860084295272827  (0.6218711525201798)

   --> STEP: 11
     | > decoder_loss: 0.4634399712085724  (0.4514797329902649)
     | > postnet_loss: 0.3189156949520111  (0.3158945956013419)
     | > stopnet_loss: 0.0058951121754944324  (0.007744620681147684)
     | > loss: 0.20148402452468872  (0.1995882039720362)
     | > align_error: 0.5945863425731659  (0.6193907152522694)

   --> STEP: 12
     | > decoder_loss: 0.4584982395172119  (0.4520646085341771)
     | > postnet_loss: 0.31180718541145325  (0.3155539780855179)
     | > stopnet_loss: 0.007912139408290386  (0.007758580575076242)
     | > loss: 0.20048849284648895  (0.19966322804490724)
     | > align_error: 0.5872406959533691  (0.6167115469773611)

   --> STEP: 13
     | > decoder_loss: 0.44927218556404114  (0.4518498067672436)
     | > postnet_loss: 0.31241902709007263  (0.31531282800894517)
     | > stopnet_loss: 0.0056155091151595116  (0.007593728924313417)
     | > loss: 0.19603830575942993  (0.19938438786910131)
     | > align_error: 0.5858457386493683  (0.6143372540290539)

   --> STEP: 14
     | > decoder_loss: 0.4595324993133545  (0.4523985705205372)
     | > postnet_loss: 0.31461286544799805  (0.31526283068316324)
     | > stopnet_loss: 0.004956359509378672  (0.007405345394675221)
     | > loss: 0.19849270582199097  (0.1993206962943077)
     | > align_error: 0.5546995997428894  (0.6100774215800422)

   --> STEP: 15
     | > decoder_loss: 0.4570468068122864  (0.4527084529399872)
     | > postnet_loss: 0.31518158316612244  (0.3152574141820272)
     | > stopnet_loss: 0.004978900775313377  (0.007243582420051098)
     | > loss: 0.19803598523139954  (0.19923504889011384)
     | > align_error: 0.5880367159843445  (0.6086080412069956)

   --> STEP: 16
     | > decoder_loss: 0.4582204818725586  (0.4530529547482729)
     | > postnet_loss: 0.3088861107826233  (0.31485920771956444)
     | > stopnet_loss: 0.00525585375726223  (0.007119349378626794)
     | > loss: 0.19703249633312225  (0.19909738935530186)
     | > align_error: 0.6057736873626709  (0.6084308940917253)

   --> STEP: 17
     | > decoder_loss: 0.46462637186050415  (0.45373374399016886)
     | > postnet_loss: 0.31768521666526794  (0.3150254435398999)
     | > stopnet_loss: 0.00484756613150239  (0.006985715069972417)
     | > loss: 0.20042546093463898  (0.1991755112129099)
     | > align_error: 0.5584540963172913  (0.6054910824579351)

   --> STEP: 18
     | > decoder_loss: 0.45897379517555237  (0.4540248579449124)
     | > postnet_loss: 0.3100797235965729  (0.31475068132082623)
     | > stopnet_loss: 0.00527919502928853  (0.006890908401045535)
     | > loss: 0.19754257798194885  (0.19908479270007876)
     | > align_error: 0.6038752496242523  (0.605401313967175)

   --> STEP: 19
     | > decoder_loss: 0.4585556387901306  (0.4542633200946607)
     | > postnet_loss: 0.31036561727523804  (0.31451988847632156)
     | > stopnet_loss: 0.004910509567707777  (0.0067866768835014414)
     | > loss: 0.19714082777500153  (0.19898247875665365)
     | > align_error: 0.6001149713993073  (0.6051230854109714)

   --> STEP: 20
     | > decoder_loss: 0.4528660774230957  (0.45419345796108246)
     | > postnet_loss: 0.30622726678848267  (0.3141052573919296)
     | > stopnet_loss: 0.004538624547421932  (0.006674274266697466)
     | > loss: 0.1943119615316391  (0.1987489528954029)
     | > align_error: 0.6222520470619202  (0.6059795334935189)

   --> STEP: 21
     | > decoder_loss: 0.4509910047054291  (0.45404096018700374)
     | > postnet_loss: 0.3051440715789795  (0.31367853425797965)
     | > stopnet_loss: 0.003999022301286459  (0.006546881315963609)
     | > loss: 0.19303280115127563  (0.1984767551933016)
     | > align_error: 0.5598384141921997  (0.6037823373363131)

   --> STEP: 22
     | > decoder_loss: 0.4527597725391388  (0.45398272438482806)
     | > postnet_loss: 0.3080921471118927  (0.3134246075695212)
     | > stopnet_loss: 0.004905755165964365  (0.006472284672781825)
     | > loss: 0.1951187402009964  (0.19832411814819684)
     | > align_error: 0.6250927448272705  (0.6047509922222658)

   --> STEP: 23
     | > decoder_loss: 0.4259836971759796  (0.4527653753757477)
     | > postnet_loss: 0.2961682677268982  (0.31267433192418975)
     | > stopnet_loss: 0.004543927498161793  (0.006388443056493998)
     | > loss: 0.18508192896842957  (0.19774837079255478)
     | > align_error: 0.5669556558132172  (0.6031077167262202)

   --> STEP: 24
     | > decoder_loss: 0.4607885181903839  (0.45309967299302417)
     | > postnet_loss: 0.3120890259742737  (0.3126499441762766)
     | > stopnet_loss: 0.004417798016220331  (0.0063063328464825945)
     | > loss: 0.1976371854543686  (0.19774373807013035)
     | > align_error: 0.5790954232215881  (0.6021072044968605)

   --> STEP: 25
     | > decoder_loss: 0.459865540266037  (0.4533703076839447)
     | > postnet_loss: 0.3090333044528961  (0.3125052785873414)
     | > stopnet_loss: 0.0037267892621457577  (0.0062031511031091216)
     | > loss: 0.19595150649547577  (0.19767204880714417)
     | > align_error: 0.557880699634552  (0.6003381443023682)

   --> STEP: 26
     | > decoder_loss: 0.43526625633239746  (0.4526739980165775)
     | > postnet_loss: 0.29797324538230896  (0.3119463542333017)
     | > stopnet_loss: 0.004418733064085245  (0.006134519640069742)
     | > loss: 0.187728613615036  (0.19728960899206308)
     | > align_error: 0.5464733242988586  (0.5982664204560794)

   --> STEP: 27
     | > decoder_loss: 0.4318712055683136  (0.4519035242221974)
     | > postnet_loss: 0.29305970668792725  (0.31124684876865816)
     | > stopnet_loss: 0.003941629081964493  (0.006053301471251028)
     | > loss: 0.1851743459701538  (0.19684089554680717)
     | > align_error: 0.5410015285015106  (0.5961454985318361)

   --> STEP: 28
     | > decoder_loss: 0.4371090829372406  (0.45137515131916317)
     | > postnet_loss: 0.29725825786590576  (0.310747256236417)
     | > stopnet_loss: 0.00396777642890811  (0.0059788184340244955)
     | > loss: 0.18755961954593658  (0.19650942140391894)
     | > align_error: 0.565910279750824  (0.5950656692896571)

   --> STEP: 29
     | > decoder_loss: 0.4324996769428253  (0.4507242728923929)
     | > postnet_loss: 0.29383912682533264  (0.3101642172912072)
     | > stopnet_loss: 0.0036092482041567564  (0.0058971091157531946)
     | > loss: 0.1851939558982849  (0.19611923293820743)
     | > align_error: 0.5401199758052826  (0.593170990203989)

   --> STEP: 30
     | > decoder_loss: 0.433459609746933  (0.4501487841208776)
     | > postnet_loss: 0.2948479950428009  (0.3096536765495937)
     | > stopnet_loss: 0.0029062603134661913  (0.005797414155676961)
     | > loss: 0.18498316407203674  (0.1957480306426684)
     | > align_error: 0.5330873727798462  (0.5911682029565175)

   --> STEP: 31
     | > decoder_loss: 0.42908912897109985  (0.4494694404063686)
     | > postnet_loss: 0.29367873072624207  (0.3091383557165823)
     | > stopnet_loss: 0.003710990073159337  (0.005730110153015102)
     | > loss: 0.1844029426574707  (0.19538206006250075)
     | > align_error: 0.555873692035675  (0.5900296703461678)

   --> STEP: 32
     | > decoder_loss: 0.4403815269470215  (0.449185443110764)
     | > postnet_loss: 0.29911234974861145  (0.30882504303008323)
     | > stopnet_loss: 0.003874890971928835  (0.005672134553606156)
     | > loss: 0.18874835968017578  (0.19517475692555308)
     | > align_error: 0.5305199921131134  (0.5881699929013848)

   --> STEP: 33
     | > decoder_loss: 0.4375298023223877  (0.4488322418747526)
     | > postnet_loss: 0.29721495509147644  (0.3084732221834588)
     | > stopnet_loss: 0.004036187659949064  (0.0056225604053135175)
     | > loss: 0.18772238492965698  (0.194948927471132)
     | > align_error: 0.5455688238143921  (0.5868790483835972)

   --> STEP: 34
     | > decoder_loss: 0.44299280643463135  (0.4486604937735726)
     | > postnet_loss: 0.29857560992240906  (0.3081821159404867)
     | > stopnet_loss: 0.0033252546563744545  (0.0055549925891682506)
     | > loss: 0.18871736526489258  (0.194765646229772)
     | > align_error: 0.563154399394989  (0.5861812645898146)

   --> STEP: 35
     | > decoder_loss: 0.4403250217437744  (0.4484223374298641)
     | > postnet_loss: 0.29773783683776855  (0.30788370796612335)
     | > stopnet_loss: 0.0035469105932861567  (0.005497618817857333)
     | > loss: 0.1880626231431961  (0.19457413128444126)
     | > align_error: 0.5328034460544586  (0.584656184060233)

   --> STEP: 36
     | > decoder_loss: 0.44680237770080566  (0.4483773385485013)
     | > postnet_loss: 0.3022095859050751  (0.3077260934644276)
     | > stopnet_loss: 0.003695454215630889  (0.00544755869001771)
     | > loss: 0.1909484565258026  (0.1944734180967013)
     | > align_error: 0.6334597766399384  (0.5860118394096693)

   --> STEP: 37
     | > decoder_loss: 0.43938466906547546  (0.44813429342733846)
     | > postnet_loss: 0.29882359504699707  (0.3074854853990916)
     | > stopnet_loss: 0.0035969906020909548  (0.00539754333628996)
     | > loss: 0.18814906477928162  (0.19430248962866292)
     | > align_error: 0.5183609426021576  (0.58418343679325)

   --> STEP: 38
     | > decoder_loss: 0.4270750880241394  (0.4475801038114648)
     | > postnet_loss: 0.29174986481666565  (0.30707139012060675)
     | > stopnet_loss: 0.003157566534355283  (0.005338596578344311)
     | > loss: 0.18286381661891937  (0.1940014719178802)
     | > align_error: 0.5509735345840454  (0.583309491998271)

   --> STEP: 39
     | > decoder_loss: 0.4424072206020355  (0.4474474657804538)
     | > postnet_loss: 0.3019629120826721  (0.30694040350424945)
     | > stopnet_loss: 0.0034887760411947966  (0.0052911652825199645)
     | > loss: 0.18958130478858948  (0.19388813429918045)
     | > align_error: 0.5453656911849976  (0.5823365740286999)

   --> STEP: 40
     | > decoder_loss: 0.4394392669200897  (0.4472472608089447)
     | > postnet_loss: 0.3005337119102478  (0.3067802362143994)
     | > stopnet_loss: 0.0030613369308412075  (0.0052354195737279955)
     | > loss: 0.18805457651615143  (0.19374229535460472)
     | > align_error: 0.5834589600563049  (0.58236463367939)

   --> STEP: 41
     | > decoder_loss: 0.4293888211250305  (0.44681168910933705)
     | > postnet_loss: 0.29238465428352356  (0.3064291244599878)
     | > stopnet_loss: 0.003739352570846677  (0.005198930134633329)
     | > loss: 0.18418273329734802  (0.19350913530442773)
     | > align_error: 0.5027790069580078  (0.580423520832527)

   --> STEP: 42
     | > decoder_loss: 0.43480318784713745  (0.446525772412618)
     | > postnet_loss: 0.29502955079078674  (0.30615770603929254)
     | > stopnet_loss: 0.0033103921450674534  (0.00515396494440557)
     | > loss: 0.18576858937740326  (0.19332483659187952)
     | > align_error: 0.5789496004581451  (0.5803884274902797)

   --> STEP: 43
     | > decoder_loss: 0.4333585202693939  (0.44621955724649653)
     | > postnet_loss: 0.29380398988723755  (0.30587041031482615)
     | > stopnet_loss: 0.0029519316740334034  (0.005102754868350403)
     | > loss: 0.18474255502223969  (0.19312524864839953)
     | > align_error: 0.5509590208530426  (0.5797040226847626)

   --> STEP: 44
     | > decoder_loss: 0.4513150155544281  (0.44633536311713135)
     | > postnet_loss: 0.3040204346179962  (0.3058283654126255)
     | > stopnet_loss: 0.0026977623347193003  (0.0050480959471315145)
     | > loss: 0.19153162837028503  (0.19308903000571512)
     | > align_error: 0.5504122972488403  (0.579038301652128)

   --> STEP: 45
     | > decoder_loss: 0.4447507858276367  (0.44630015028847586)
     | > postnet_loss: 0.3034471273422241  (0.305775449011061)
     | > stopnet_loss: 0.003314938396215439  (0.005009581334888935)
     | > loss: 0.19036442041397095  (0.19302848312589857)
     | > align_error: 0.5518376529216766  (0.5784338427914513)

   --> STEP: 46
     | > decoder_loss: 0.43545567989349365  (0.44606440093206323)
     | > postnet_loss: 0.2947829067707062  (0.3055364807014881)
     | > stopnet_loss: 0.003214381169527769  (0.0049705552443376055)
     | > loss: 0.18577401340007782  (0.19287077726229376)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35911282626065344 (+0.015612349365696832)
     | > avg_decoder_loss: 0.4420486878265034 (+0.0005133711930477292)
     | > avg_postnet_loss: 0.30244383035284106 (+0.0008916552319670479)
     | > avg_stopnet_loss: 0.004404589371529944 (+6.469975536082737e-07)
     | > avg_loss: 0.1905277202075178 (+0.0003519055969787577)
     | > avg_align_error: 0.571210297219681 (-5.2420027328414776e-05)


 > EPOCH: 106/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 12:29:00)

   --> TIME: 2025-12-28 12:29:27 -- STEP: 19/150 -- GLOBAL_STEP: 16025
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.477241575717926  (0.46879144248209503)
     | > postnet_loss: 0.4004913568496704  (0.3983537727280667)
     | > stopnet_loss: 0.008776559494435787  (0.010551608314639643)
     | > loss: 0.22820979356765747  (0.22733791015650096)
     | > align_error: 0.6355080306529999  (0.6795438402577451)
     | > grad_norm: tensor(0.2947, device='cuda:0')  (tensor(0.2593, device='cuda:0'))
     | > step_time: 0.7821  (0.5772331764823512)
     | > loader_time: 0.9551  (0.7764221743533486)


   --> TIME: 2025-12-28 12:30:16 -- STEP: 44/150 -- GLOBAL_STEP: 16050
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48759183287620544  (0.4776104553179307)
     | > postnet_loss: 0.4027673304080963  (0.4015978669578379)
     | > stopnet_loss: 0.004869350232183933  (0.007934140189635482)
     | > loss: 0.2274591475725174  (0.2277362204410813)
     | > align_error: 0.5888446271419525  (0.6491937291893092)
     | > grad_norm: tensor(0.2355, device='cuda:0')  (tensor(0.2635, device='cuda:0'))
     | > step_time: 1.1238  (0.8207145062359896)
     | > loader_time: 1.0672  (0.884729266166687)


   --> TIME: 2025-12-28 12:31:18 -- STEP: 69/150 -- GLOBAL_STEP: 16075
     | > current_lr: 1e-05  (1.0000000000000016e-05)
     | > decoder_loss: 0.4914674162864685  (0.4813811377338741)
     | > postnet_loss: 0.4034729599952698  (0.40166853994563007)
     | > stopnet_loss: 0.00475296238437295  (0.006654387262339393)
     | > loss: 0.22848805785179138  (0.22741680581500565)
     | > align_error: 0.6103399991989136  (0.6379530809927678)
     | > grad_norm: tensor(0.2068, device='cuda:0')  (tensor(0.2324, device='cuda:0'))
     | > step_time: 1.3948  (1.0001886478368787)
     | > loader_time: 1.2226  (0.9895956101624862)


   --> TIME: 2025-12-28 12:32:35 -- STEP: 94/150 -- GLOBAL_STEP: 16100
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48643651604652405  (0.48266203352745546)
     | > postnet_loss: 0.39842623472213745  (0.4008508822385301)
     | > stopnet_loss: 0.0036631831899285316  (0.0058911180277255925)
     | > loss: 0.22487887740135193  (0.2267693466645606)
     | > align_error: 0.6149487495422363  (0.6329049474381386)
     | > grad_norm: tensor(0.1109, device='cuda:0')  (tensor(0.2241, device='cuda:0'))
     | > step_time: 1.9095  (1.1515655669760192)
     | > loader_time: 1.7891  (1.130494110127713)


   --> TIME: 2025-12-28 12:34:02 -- STEP: 119/150 -- GLOBAL_STEP: 16125
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4831133782863617  (0.48388671799868094)
     | > postnet_loss: 0.39581531286239624  (0.40042901514958934)
     | > stopnet_loss: 0.003407048527151346  (0.005380214749592817)
     | > loss: 0.2231392115354538  (0.2264591474242571)
     | > align_error: 0.6132584810256958  (0.6273949071138845)
     | > grad_norm: tensor(0.1171, device='cuda:0')  (tensor(0.2117, device='cuda:0'))
     | > step_time: 1.835  (1.279020792295953)
     | > loader_time: 1.6608  (1.2501619984121883)


   --> TIME: 2025-12-28 12:35:36 -- STEP: 144/150 -- GLOBAL_STEP: 16150
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49223053455352783  (0.48499459876782364)
     | > postnet_loss: 0.39846333861351013  (0.4000253933999274)
     | > stopnet_loss: 0.002877722028642893  (0.004993647623147504)
     | > loss: 0.22555120289325714  (0.22624864522367716)
     | > align_error: 0.5948944687843323  (0.623786432875527)
     | > grad_norm: tensor(0.1503, device='cuda:0')  (tensor(0.2094, device='cuda:0'))
     | > step_time: 2.3023  (1.4029477453894086)
     | > loader_time: 3.1128  (1.33947368297312)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46340155601501465  (0.46340155601501465)
     | > postnet_loss: 0.3366040587425232  (0.3366040587425232)
     | > stopnet_loss: 0.0121415751054883  (0.0121415751054883)
     | > loss: 0.2121429741382599  (0.2121429741382599)
     | > align_error: 0.718977689743042  (0.718977689743042)

   --> STEP: 1
     | > decoder_loss: 0.44529443979263306  (0.44529443979263306)
     | > postnet_loss: 0.3256368935108185  (0.3256368935108185)
     | > stopnet_loss: 0.009598459117114544  (0.009598459117114544)
     | > loss: 0.2023313045501709  (0.2023313045501709)
     | > align_error: 0.6595650315284729  (0.6595650315284729)

   --> STEP: 2
     | > decoder_loss: 0.44034668803215027  (0.44282056391239166)
     | > postnet_loss: 0.3150268793106079  (0.3203318864107132)
     | > stopnet_loss: 0.01112409308552742  (0.010361276101320982)
     | > loss: 0.19996748864650726  (0.20114939659833908)
     | > align_error: 0.6560553312301636  (0.6578101813793182)

   --> STEP: 3
     | > decoder_loss: 0.4431517422199249  (0.4429309566815694)
     | > postnet_loss: 0.3137259781360626  (0.31812991698582965)
     | > stopnet_loss: 0.008305931463837624  (0.009676161222159863)
     | > loss: 0.19752536714076996  (0.19994138677914938)
     | > align_error: 0.7346482872962952  (0.6834228833516439)

   --> STEP: 4
     | > decoder_loss: 0.4509648382663727  (0.44493942707777023)
     | > postnet_loss: 0.3241081237792969  (0.31962446868419647)
     | > stopnet_loss: 0.008241184987127781  (0.009317417163401842)
     | > loss: 0.2020094245672226  (0.20045839622616768)
     | > align_error: 0.603888213634491  (0.6635392159223557)

   --> STEP: 5
     | > decoder_loss: 0.43137267231941223  (0.44222607612609866)
     | > postnet_loss: 0.3052425682544708  (0.3167480885982513)
     | > stopnet_loss: 0.008194630034267902  (0.009092859737575055)
     | > loss: 0.1923484355211258  (0.1988364040851593)
     | > align_error: 0.6422953009605408  (0.6592904329299927)

   --> STEP: 6
     | > decoder_loss: 0.4481077790260315  (0.4432063599427541)
     | > postnet_loss: 0.317686527967453  (0.31690449515978497)
     | > stopnet_loss: 0.007228014525026083  (0.008782052202150226)
     | > loss: 0.19867658615112305  (0.19880976776281992)
     | > align_error: 0.5940840542316437  (0.6484227031469345)

   --> STEP: 7
     | > decoder_loss: 0.4582664370536804  (0.4453577995300293)
     | > postnet_loss: 0.31592270731925964  (0.31676423975399565)
     | > stopnet_loss: 0.006305386312305927  (0.008428242789315326)
     | > loss: 0.19985266029834747  (0.19895875241075242)
     | > align_error: 0.5794037580490112  (0.6385628538472312)

   --> STEP: 8
     | > decoder_loss: 0.4537827670574188  (0.446410920470953)
     | > postnet_loss: 0.31796708703041077  (0.3169145956635475)
     | > stopnet_loss: 0.007554537151008844  (0.008319029584527016)
     | > loss: 0.2004919946193695  (0.19915040768682957)
     | > align_error: 0.5758485198020935  (0.630723562091589)

   --> STEP: 9
     | > decoder_loss: 0.45096930861473083  (0.44691740804248387)
     | > postnet_loss: 0.3172849118709564  (0.31695574190881515)
     | > stopnet_loss: 0.006685236934572458  (0.008137497067865398)
     | > loss: 0.19874879717826843  (0.19910578429698944)
     | > align_error: 0.5917734503746033  (0.6263957719008127)

   --> STEP: 10
     | > decoder_loss: 0.4798943102359772  (0.4502150982618332)
     | > postnet_loss: 0.33338093757629395  (0.318598261475563)
     | > stopnet_loss: 0.005796508863568306  (0.007903398247435689)
     | > loss: 0.20911531150341034  (0.20010673701763154)
     | > align_error: 0.5863267779350281  (0.6223888725042344)

   --> STEP: 11
     | > decoder_loss: 0.46466392278671265  (0.45152862776409497)
     | > postnet_loss: 0.32188916206359863  (0.3188974342562936)
     | > stopnet_loss: 0.0058877961710095406  (0.007720161695033312)
     | > loss: 0.2025260627269745  (0.2003266757184809)
     | > align_error: 0.5950524508953094  (0.6199037432670593)

   --> STEP: 12
     | > decoder_loss: 0.4600984752178192  (0.45224278171857196)
     | > postnet_loss: 0.3155847489833832  (0.3186213771502177)
     | > stopnet_loss: 0.007898724637925625  (0.007735041940274338)
     | > loss: 0.2018195241689682  (0.2004510797560215)
     | > align_error: 0.5878649950027466  (0.6172338475783666)

   --> STEP: 13
     | > decoder_loss: 0.4482429325580597  (0.4519351010139172)
     | > postnet_loss: 0.3141404092311859  (0.3182766873102922)
     | > stopnet_loss: 0.005532857961952686  (0.007565643172711134)
     | > loss: 0.1961286962032318  (0.20011858871349922)
     | > align_error: 0.5861440896987915  (0.6148423277414762)

   --> STEP: 14
     | > decoder_loss: 0.46112143993377686  (0.45259126807962147)
     | > postnet_loss: 0.31806835532188416  (0.31826180645397734)
     | > stopnet_loss: 0.004929730668663979  (0.007377363708136337)
     | > loss: 0.19972719252109528  (0.20009063184261322)
     | > align_error: 0.5551615059375763  (0.6105794118983405)

   --> STEP: 15
     | > decoder_loss: 0.4575285315513611  (0.45292041897773744)
     | > postnet_loss: 0.3166595995426178  (0.31815499265988667)
     | > stopnet_loss: 0.0049928720109164715  (0.0072183975949883464)
     | > loss: 0.19853991270065308  (0.19998725056648253)
     | > align_error: 0.5888248682022095  (0.6091291089852651)

   --> STEP: 16
     | > decoder_loss: 0.458793580532074  (0.45328749157488346)
     | > postnet_loss: 0.31074777245521545  (0.3176920413970947)
     | > stopnet_loss: 0.0052492013201117516  (0.007095322827808559)
     | > loss: 0.19763454794883728  (0.19984020665287971)
     | > align_error: 0.6065088212490082  (0.608965341001749)

   --> STEP: 17
     | > decoder_loss: 0.46457046270370483  (0.4539511957589318)
     | > postnet_loss: 0.318807452917099  (0.31775765383944793)
     | > stopnet_loss: 0.004853228572756052  (0.006963434930452529)
     | > loss: 0.20069770514965057  (0.19989064774092505)
     | > align_error: 0.5591145753860474  (0.6060329430243548)

   --> STEP: 18
     | > decoder_loss: 0.45935407280921936  (0.45425135559505886)
     | > postnet_loss: 0.3116593062877655  (0.31741885675324333)
     | > stopnet_loss: 0.005280026700347662  (0.006869912251002259)
     | > loss: 0.1980333775281906  (0.1997874660624398)
     | > align_error: 0.60439333319664  (0.6059418535894818)

   --> STEP: 19
     | > decoder_loss: 0.4596097767353058  (0.45453337776033503)
     | > postnet_loss: 0.3122895359992981  (0.3171488925030357)
     | > stopnet_loss: 0.004795004613697529  (0.0067607065858809575)
     | > loss: 0.19776983559131622  (0.19968127498501226)
     | > align_error: 0.6007948517799377  (0.6056709587574005)

   --> STEP: 20
     | > decoder_loss: 0.4537202715873718  (0.45449272245168687)
     | > postnet_loss: 0.3074693977832794  (0.31666491776704786)
     | > stopnet_loss: 0.00454346276819706  (0.006649844394996762)
     | > loss: 0.19484089314937592  (0.19943925589323044)
     | > align_error: 0.6230446696281433  (0.6065396443009377)

   --> STEP: 21
     | > decoder_loss: 0.45110324025154114  (0.4543313185373942)
     | > postnet_loss: 0.30708950757980347  (0.31620894585336956)
     | > stopnet_loss: 0.003996097017079592  (0.006523475472238802)
     | > loss: 0.19354429841041565  (0.19915854363214403)
     | > align_error: 0.5606037378311157  (0.6043522201833271)

   --> STEP: 22
     | > decoder_loss: 0.4524391293525696  (0.454245309938084)
     | > postnet_loss: 0.30947914719581604  (0.3159030459143899)
     | > stopnet_loss: 0.0046252962201833725  (0.006437194597145373)
     | > loss: 0.19510486721992493  (0.1989742856134068)
     | > align_error: 0.6255582869052887  (0.6053161323070526)

   --> STEP: 23
     | > decoder_loss: 0.42588138580322266  (0.4530120958452639)
     | > postnet_loss: 0.2972932457923889  (0.315093924169955)
     | > stopnet_loss: 0.00451999343931675  (0.0063538380250658675)
     | > loss: 0.1853136569261551  (0.1983803452357002)
     | > align_error: 0.5677791833877563  (0.6036840910496919)

   --> STEP: 24
     | > decoder_loss: 0.46014490723609924  (0.4533092963198821)
     | > postnet_loss: 0.31272438168525696  (0.3149951932330926)
     | > stopnet_loss: 0.004427900537848473  (0.006273590629765143)
     | > loss: 0.19764521718025208  (0.1983497149000565)
     | > align_error: 0.5797728896141052  (0.6026877909898758)

   --> STEP: 25
     | > decoder_loss: 0.45920923352241516  (0.4535452938079834)
     | > postnet_loss: 0.30973848700523376  (0.31478492498397825)
     | > stopnet_loss: 0.003719224128872156  (0.006171415969729424)
     | > loss: 0.19595615565776825  (0.198253972530365)
     | > align_error: 0.5586690306663513  (0.6009270405769348)

   --> STEP: 26
     | > decoder_loss: 0.4343201518058777  (0.4528058652694409)
     | > postnet_loss: 0.2989419996738434  (0.31417558170281923)
     | > stopnet_loss: 0.004393219016492367  (0.006103023779220306)
     | > loss: 0.1877087652683258  (0.19784838763567117)
     | > align_error: 0.5473107993602753  (0.5988648774532171)

   --> STEP: 27
     | > decoder_loss: 0.4317176640033722  (0.452024820778105)
     | > postnet_loss: 0.29385536909103394  (0.3134229812357161)
     | > stopnet_loss: 0.0039202068001031876  (0.006022178705919672)
     | > loss: 0.18531347811222076  (0.19738413172739525)
     | > align_error: 0.541608989238739  (0.5967442890008291)

   --> STEP: 28
     | > decoder_loss: 0.4369291663169861  (0.4514856902616365)
     | > postnet_loss: 0.298417329788208  (0.3128870651125908)
     | > stopnet_loss: 0.0039490340277552605  (0.005948137824556657)
     | > loss: 0.18778565526008606  (0.1970413289964199)
     | > align_error: 0.566736102104187  (0.5956725680402347)

   --> STEP: 29
     | > decoder_loss: 0.4329119324684143  (0.4508452158549736)
     | > postnet_loss: 0.29568055272102356  (0.3122937370990885)
     | > stopnet_loss: 0.003614989807829261  (0.005867684444669506)
     | > loss: 0.18576312065124512  (0.1966524252603794)
     | > align_error: 0.5410283803939819  (0.5937882857076053)

   --> STEP: 30
     | > decoder_loss: 0.43327954411506653  (0.4502596934636434)
     | > postnet_loss: 0.2961503863334656  (0.31175562540690105)
     | > stopnet_loss: 0.002884433837607503  (0.005768242757767439)
     | > loss: 0.1852419227361679  (0.196272075176239)
     | > align_error: 0.5340359807014465  (0.5917965422074)

   --> STEP: 31
     | > decoder_loss: 0.429375559091568  (0.44958601170970547)
     | > postnet_loss: 0.2947517931461334  (0.31120711468881174)
     | > stopnet_loss: 0.003720392705872655  (0.005702183078674059)
     | > loss: 0.1847522258758545  (0.19590046713429113)
     | > align_error: 0.5569490790367126  (0.5906724304922165)

   --> STEP: 32
     | > decoder_loss: 0.4405767023563385  (0.44930447079241276)
     | > postnet_loss: 0.3005320131778717  (0.3108735177665949)
     | > stopnet_loss: 0.0038826805539429188  (0.005645323624776211)
     | > loss: 0.18915985524654388  (0.19568982301279902)
     | > align_error: 0.5315515995025635  (0.5888249045237899)

   --> STEP: 33
     | > decoder_loss: 0.4378223121166229  (0.4489565265901161)
     | > postnet_loss: 0.298076331615448  (0.31048572424686316)
     | > stopnet_loss: 0.004032956436276436  (0.00559646401300349)
     | > loss: 0.18800760805606842  (0.19545702862017084)
     | > align_error: 0.54646435379982  (0.5875412514715483)

   --> STEP: 34
     | > decoder_loss: 0.4433581531047821  (0.44879186854642983)
     | > postnet_loss: 0.29956889152526855  (0.31016464093152213)
     | > stopnet_loss: 0.0033321764785796404  (0.005529867320814554)
     | > loss: 0.18906395137310028  (0.19526899693643346)
     | > align_error: 0.5640856623649597  (0.5868513812037075)

   --> STEP: 35
     | > decoder_loss: 0.4407959580421448  (0.44856341396059307)
     | > postnet_loss: 0.29920923709869385  (0.30985162939344135)
     | > stopnet_loss: 0.0035286778584122658  (0.005472690479031631)
     | > loss: 0.18852998316287994  (0.1950764536857605)
     | > align_error: 0.5337429642677307  (0.5853339978626796)

   --> STEP: 36
     | > decoder_loss: 0.44711029529571533  (0.44852304955323535)
     | > postnet_loss: 0.30364444851875305  (0.30967920770247775)
     | > stopnet_loss: 0.0036855079233646393  (0.005423046519151992)
     | > loss: 0.19137418270111084  (0.19497361282507578)
     | > align_error: 0.634293258190155  (0.5866939773162206)

   --> STEP: 37
     | > decoder_loss: 0.4388881027698517  (0.4482626455861169)
     | > postnet_loss: 0.2999294698238373  (0.30941570127332535)
     | > stopnet_loss: 0.0035954031627625227  (0.005373650752763088)
     | > loss: 0.18829979002475739  (0.194793239235878)
     | > align_error: 0.5194548666477203  (0.5848767040549098)

   --> STEP: 38
     | > decoder_loss: 0.42707231640815735  (0.4477050053445916)
     | > postnet_loss: 0.2929452657699585  (0.30898226876007884)
     | > stopnet_loss: 0.003163071582093835  (0.005315477616692844)
     | > loss: 0.1831674575805664  (0.1944872976133698)
     | > align_error: 0.5519444942474365  (0.5840100669547131)

   --> STEP: 39
     | > decoder_loss: 0.4421197474002838  (0.4475617936024299)
     | > postnet_loss: 0.30348441004753113  (0.3088412980238597)
     | > stopnet_loss: 0.0034880833700299263  (0.005268621353957898)
     | > loss: 0.1898891180753708  (0.19436939557393393)
     | > align_error: 0.5461490154266357  (0.5830392707616855)

   --> STEP: 40
     | > decoder_loss: 0.43944668769836426  (0.44735891595482824)
     | > postnet_loss: 0.3022456467151642  (0.3086764067411423)
     | > stopnet_loss: 0.003044527256861329  (0.005213019001530484)
     | > loss: 0.1884676069021225  (0.19422185085713864)
     | > align_error: 0.5842535197734833  (0.5830696269869804)

   --> STEP: 41
     | > decoder_loss: 0.429364949464798  (0.4469200387233641)
     | > postnet_loss: 0.29408708214759827  (0.3083205695559339)
     | > stopnet_loss: 0.0037441570311784744  (0.005177193099814581)
     | > loss: 0.18460716307163239  (0.19398734627700434)
     | > align_error: 0.5036525130271912  (0.5811326242074734)

   --> STEP: 42
     | > decoder_loss: 0.4349103569984436  (0.44663409392038983)
     | > postnet_loss: 0.29618051648139954  (0.3080315206732069)
     | > stopnet_loss: 0.0033037501852959394  (0.005132587316135566)
     | > loss: 0.18607647716999054  (0.19379899225064687)
     | > align_error: 0.5797623991966248  (0.5810999998024532)

   --> STEP: 43
     | > decoder_loss: 0.4336470663547516  (0.4463320700235145)
     | > postnet_loss: 0.29509052634239197  (0.3077305673166763)
     | > stopnet_loss: 0.0029524650890380144  (0.00508188679922632)
     | > loss: 0.18513686954975128  (0.19359754753667255)
     | > align_error: 0.5519928932189941  (0.5804230903470239)

   --> STEP: 44
     | > decoder_loss: 0.4516863226890564  (0.446453757584095)
     | > postnet_loss: 0.305483341217041  (0.30767949399623)
     | > stopnet_loss: 0.0026929927989840508  (0.005027593753766269)
     | > loss: 0.19198541343212128  (0.19356090812520546)
     | > align_error: 0.551398366689682  (0.5797634375366297)

   --> STEP: 45
     | > decoder_loss: 0.4444097876548767  (0.4464083360301124)
     | > postnet_loss: 0.30440106987953186  (0.30760664012697003)
     | > stopnet_loss: 0.00331455422565341  (0.0049895262086970945)
     | > loss: 0.19051727652549744  (0.19349327186743417)
     | > align_error: 0.5527569055557251  (0.5791632923814986)

   --> STEP: 46
     | > decoder_loss: 0.43556275963783264  (0.4461725626302802)
     | > postnet_loss: 0.2964552342891693  (0.3073642182609309)
     | > stopnet_loss: 0.0032182487193495035  (0.004951020176319973)
     | > loss: 0.18622274696826935  (0.1933352169783219)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35519061305306177 (-0.003922213207591674)
     | > avg_decoder_loss: 0.44218618309859076 (+0.00013749527208734014)
     | > avg_postnet_loss: 0.30448733134703204 (+0.002043500994190983)
     | > avg_stopnet_loss: 0.004390188503417779 (-1.4400868112164969e-05)
     | > avg_loss: 0.1910585682048942 (+0.0005308479973764046)
     | > avg_align_error: 0.5720062666770186 (+0.0007959694573376197)


 > EPOCH: 107/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 12:38:06)

   --> TIME: 2025-12-28 12:38:35 -- STEP: 18/150 -- GLOBAL_STEP: 16175
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47616755962371826  (0.46838123930825126)
     | > postnet_loss: 0.4009318947792053  (0.39834309617678326)
     | > stopnet_loss: 0.0080314502120018  (0.010779606023182472)
     | > loss: 0.2273063063621521  (0.22746068984270096)
     | > align_error: 0.7042354345321655  (0.6820079816712273)
     | > grad_norm: tensor(0.3247, device='cuda:0')  (tensor(0.2772, device='cuda:0'))
     | > step_time: 0.8301  (0.609230743514167)
     | > loader_time: 1.1285  (0.9255926211675009)


   --> TIME: 2025-12-28 12:39:25 -- STEP: 43/150 -- GLOBAL_STEP: 16200
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4874344766139984  (0.4771227067293123)
     | > postnet_loss: 0.4039115905761719  (0.40141200395517573)
     | > stopnet_loss: 0.0054431273601949215  (0.008037854408368812)
     | > loss: 0.22827965021133423  (0.22767153070416563)
     | > align_error: 0.6080445647239685  (0.6506685898747556)
     | > grad_norm: tensor(0.1494, device='cuda:0')  (tensor(0.2483, device='cuda:0'))
     | > step_time: 1.0794  (0.8356321911479152)
     | > loader_time: 1.0979  (0.9631197341652804)


   --> TIME: 2025-12-28 12:40:28 -- STEP: 68/150 -- GLOBAL_STEP: 16225
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.49135124683380127  (0.48091907317147536)
     | > postnet_loss: 0.40319690108299255  (0.40141724050045013)
     | > stopnet_loss: 0.0038732923567295074  (0.006705210013452039)
     | > loss: 0.22751033306121826  (0.22728928770212567)
     | > align_error: 0.6134421825408936  (0.6381621316951865)
     | > grad_norm: tensor(0.1992, device='cuda:0')  (tensor(0.2192, device='cuda:0'))
     | > step_time: 1.4371  (1.0204090020235848)
     | > loader_time: 1.2525  (1.0428783332600313)


   --> TIME: 2025-12-28 12:41:43 -- STEP: 93/150 -- GLOBAL_STEP: 16250
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4834035634994507  (0.4823837927592698)
     | > postnet_loss: 0.39799201488494873  (0.40071305728727774)
     | > stopnet_loss: 0.003531043417751789  (0.005925366156784596)
     | > loss: 0.22387993335723877  (0.22669957770455268)
     | > align_error: 0.6027572751045227  (0.6329942009141369)
     | > grad_norm: tensor(0.1768, device='cuda:0')  (tensor(0.2060, device='cuda:0'))
     | > step_time: 1.5746  (1.176130133290445)
     | > loader_time: 1.4477  (1.144874380480859)


   --> TIME: 2025-12-28 12:43:00 -- STEP: 118/150 -- GLOBAL_STEP: 16275
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4983406662940979  (0.4836376195741912)
     | > postnet_loss: 0.40451812744140625  (0.40031944038504264)
     | > stopnet_loss: 0.00324687035754323  (0.005402235740448458)
     | > loss: 0.22896157205104828  (0.2263914993253805)
     | > align_error: 0.6023151576519012  (0.6275137099674194)
     | > grad_norm: tensor(0.1642, device='cuda:0')  (tensor(0.2021, device='cuda:0'))
     | > step_time: 1.9723  (1.2788512444092057)
     | > loader_time: 1.606  (1.201676744525716)


   --> TIME: 2025-12-28 12:44:42 -- STEP: 143/150 -- GLOBAL_STEP: 16300
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48654502630233765  (0.484735935092806)
     | > postnet_loss: 0.39490920305252075  (0.39990164329122)
     | > stopnet_loss: 0.0030451100319623947  (0.0050111541726424545)
     | > loss: 0.22340866923332214  (0.22617054777545528)
     | > align_error: 0.5743415057659149  (0.6237031361023029)
     | > grad_norm: tensor(0.1391, device='cuda:0')  (tensor(0.2010, device='cuda:0'))
     | > step_time: 2.3185  (1.4209042595816657)
     | > loader_time: 2.1185  (1.340120882421107)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4634406566619873  (0.4634406566619873)
     | > postnet_loss: 0.3319973051548004  (0.3319973051548004)
     | > stopnet_loss: 0.012174800038337708  (0.012174800038337708)
     | > loss: 0.21103428304195404  (0.21103428304195404)
     | > align_error: 0.7184136509895325  (0.7184136509895325)

   --> STEP: 1
     | > decoder_loss: 0.4452851712703705  (0.4452851712703705)
     | > postnet_loss: 0.31933173537254333  (0.31933173537254333)
     | > stopnet_loss: 0.00961363036185503  (0.00961363036185503)
     | > loss: 0.2007678598165512  (0.2007678598165512)
     | > align_error: 0.6589323878288269  (0.6589323878288269)

   --> STEP: 2
     | > decoder_loss: 0.4406818151473999  (0.4429834932088852)
     | > postnet_loss: 0.31201624870300293  (0.31567399203777313)
     | > stopnet_loss: 0.01117702480405569  (0.01039532758295536)
     | > loss: 0.19935153424739838  (0.2000596970319748)
     | > align_error: 0.6555723249912262  (0.6572523564100266)

   --> STEP: 3
     | > decoder_loss: 0.44312620162963867  (0.44303106268246967)
     | > postnet_loss: 0.3094016909599304  (0.31358322501182556)
     | > stopnet_loss: 0.008382946252822876  (0.009724533806244532)
     | > loss: 0.19651491940021515  (0.1988781044880549)
     | > align_error: 0.7343376874923706  (0.6829474667708079)

   --> STEP: 4
     | > decoder_loss: 0.449711412191391  (0.4447011500597)
     | > postnet_loss: 0.31872978806495667  (0.31486986577510834)
     | > stopnet_loss: 0.008238263428211212  (0.009352966211736202)
     | > loss: 0.20034855604171753  (0.19924571737647057)
     | > align_error: 0.6033034920692444  (0.663036473095417)

   --> STEP: 5
     | > decoder_loss: 0.43170949816703796  (0.4421028196811676)
     | > postnet_loss: 0.3015110194683075  (0.3121980965137482)
     | > stopnet_loss: 0.008266812190413475  (0.009135735407471656)
     | > loss: 0.1915719360113144  (0.19771096110343933)
     | > align_error: 0.6420147120952606  (0.6588321208953858)

   --> STEP: 6
     | > decoder_loss: 0.44711849093437195  (0.442938764890035)
     | > postnet_loss: 0.312574565410614  (0.31226084132989246)
     | > stopnet_loss: 0.0073236133903265  (0.008833715071280798)
     | > loss: 0.19724686443805695  (0.19763361165920892)
     | > align_error: 0.5938516855239868  (0.648002048333486)

   --> STEP: 7
     | > decoder_loss: 0.4567016065120697  (0.44490488512175425)
     | > postnet_loss: 0.31201693415641785  (0.31222599744796753)
     | > stopnet_loss: 0.006314953323453665  (0.00847389196444835)
     | > loss: 0.1984945833683014  (0.1977566076176507)
     | > align_error: 0.5790283381938934  (0.638148661170687)

   --> STEP: 8
     | > decoder_loss: 0.4553074240684509  (0.4462052024900913)
     | > postnet_loss: 0.3141748011112213  (0.31246959790587425)
     | > stopnet_loss: 0.007580234669148922  (0.008362184802535921)
     | > loss: 0.19995079934597015  (0.19803088158369064)
     | > align_error: 0.5755121409893036  (0.6303190961480141)

   --> STEP: 9
     | > decoder_loss: 0.4506502151489258  (0.4466990927855174)
     | > postnet_loss: 0.3134723901748657  (0.31258101926909554)
     | > stopnet_loss: 0.006652225274592638  (0.008172189299431112)
     | > loss: 0.19768287241458893  (0.1979922138982349)
     | > align_error: 0.5911601483821869  (0.6259681019518111)

   --> STEP: 10
     | > decoder_loss: 0.47993674874305725  (0.4500228583812714)
     | > postnet_loss: 0.3287259638309479  (0.31419551372528076)
     | > stopnet_loss: 0.005848774220794439  (0.007939847791567445)
     | > loss: 0.20801445841789246  (0.19899443835020064)
     | > align_error: 0.5858432054519653  (0.6219556123018265)

   --> STEP: 11
     | > decoder_loss: 0.4638923406600952  (0.45128372040661896)
     | > postnet_loss: 0.31859827041625977  (0.3145957643335516)
     | > stopnet_loss: 0.005959265399724245  (0.007759794846854426)
     | > loss: 0.2015819251537323  (0.199229664423249)
     | > align_error: 0.59451824426651  (0.6194613061167977)

   --> STEP: 12
     | > decoder_loss: 0.45827779173851013  (0.4518665596842766)
     | > postnet_loss: 0.3107486963272095  (0.31427517533302307)
     | > stopnet_loss: 0.007856711745262146  (0.00776787125505507)
     | > loss: 0.20011334121227264  (0.19930330415566763)
     | > align_error: 0.587206095457077  (0.6167733718951544)

   --> STEP: 13
     | > decoder_loss: 0.44863441586494446  (0.4516179332366356)
     | > postnet_loss: 0.31095606088638306  (0.3140198588371277)
     | > stopnet_loss: 0.005643087904900312  (0.0076044263819662426)
     | > loss: 0.19554071128368378  (0.1990138739347458)
     | > align_error: 0.585830807685852  (0.6143931746482849)

   --> STEP: 14
     | > decoder_loss: 0.4595738351345062  (0.4521862119436264)
     | > postnet_loss: 0.3140845000743866  (0.3140244760683605)
     | > stopnet_loss: 0.004953946452587843  (0.007415106387010643)
     | > loss: 0.19836853444576263  (0.19896777825696127)
     | > align_error: 0.5547260642051697  (0.6101312381880624)

   --> STEP: 15
     | > decoder_loss: 0.4574854075908661  (0.45253949165344237)
     | > postnet_loss: 0.31505823135375977  (0.3140933930873871)
     | > stopnet_loss: 0.005019832868129015  (0.007255421485751867)
     | > loss: 0.1981557458639145  (0.1989136427640915)
     | > align_error: 0.5884210467338562  (0.6086838920911153)

   --> STEP: 16
     | > decoder_loss: 0.45789065957069397  (0.4528739396482706)
     | > postnet_loss: 0.3083598017692566  (0.31373504363000393)
     | > stopnet_loss: 0.005270142108201981  (0.007131341524654999)
     | > loss: 0.19683276116847992  (0.19878358766436577)
     | > align_error: 0.6059757173061371  (0.6085146311670542)

   --> STEP: 17
     | > decoder_loss: 0.46485635638237  (0.45357878769145293)
     | > postnet_loss: 0.3178689181804657  (0.3139782127212076)
     | > stopnet_loss: 0.004865899682044983  (0.0069980802397955864)
     | > loss: 0.2005472183227539  (0.19888733064427094)
     | > align_error: 0.5585154891014099  (0.6055735051631927)

   --> STEP: 18
     | > decoder_loss: 0.45906496047973633  (0.4538835750685798)
     | > postnet_loss: 0.30967214703559875  (0.31373898684978485)
     | > stopnet_loss: 0.005336028058081865  (0.006905744007478158)
     | > loss: 0.19752030074596405  (0.19881138453880945)
     | > align_error: 0.6038128733634949  (0.6054756922854317)

   --> STEP: 19
     | > decoder_loss: 0.45868024230003357  (0.4541360312386563)
     | > postnet_loss: 0.3099507987499237  (0.3135396085287395)
     | > stopnet_loss: 0.004885413683950901  (0.006799410832555671)
     | > loss: 0.19704318046569824  (0.19871832116654045)
     | > align_error: 0.60035440325737  (0.6052061507576391)

   --> STEP: 20
     | > decoder_loss: 0.4534742832183838  (0.45410294383764266)
     | > postnet_loss: 0.3063741624355316  (0.3131813362240791)
     | > stopnet_loss: 0.004548040218651295  (0.006686842301860452)
     | > loss: 0.19451016187667847  (0.19850791320204736)
     | > align_error: 0.6225836873054504  (0.6060750275850296)

   --> STEP: 21
     | > decoder_loss: 0.45112520456314087  (0.4539611467293331)
     | > postnet_loss: 0.3047177195549011  (0.3127783068588802)
     | > stopnet_loss: 0.0040181283839046955  (0.0065597606867197015)
     | > loss: 0.1929788589477539  (0.19824462490422384)
     | > align_error: 0.5601924061775208  (0.6038901408513387)

   --> STEP: 22
     | > decoder_loss: 0.4530869424343109  (0.45392141017046844)
     | > postnet_loss: 0.3079722225666046  (0.31255984848195856)
     | > stopnet_loss: 0.0049326918087899685  (0.006485803010450168)
     | > loss: 0.1951974779367447  (0.19810611822388388)
     | > align_error: 0.62541863322258  (0.6048687086863951)

   --> STEP: 23
     | > decoder_loss: 0.42588919401168823  (0.45270261816356494)
     | > postnet_loss: 0.2955184578895569  (0.31181891845620197)
     | > stopnet_loss: 0.004551127087324858  (0.006401686665966459)
     | > loss: 0.18490304052829742  (0.19753207136755405)
     | > align_error: 0.567274272441864  (0.6032341679801112)

   --> STEP: 24
     | > decoder_loss: 0.4600845277309418  (0.4530101977288723)
     | > postnet_loss: 0.31154516339302063  (0.3118075119952361)
     | > stopnet_loss: 0.00444180890917778  (0.00632002509276693)
     | > loss: 0.19734923541545868  (0.1975244532028834)
     | > align_error: 0.5794814825057983  (0.6022444727520148)

   --> STEP: 25
     | > decoder_loss: 0.4602094888687134  (0.45329816937446593)
     | > postnet_loss: 0.30862775444984436  (0.3116803216934204)
     | > stopnet_loss: 0.0037441598251461983  (0.0062169904820621015)
     | > loss: 0.19595345854759216  (0.19746161341667176)
     | > align_error: 0.5584007799625397  (0.6004907250404358)

   --> STEP: 26
     | > decoder_loss: 0.4340547025203705  (0.4525580360339238)
     | > postnet_loss: 0.296559602022171  (0.3110987555522185)
     | > stopnet_loss: 0.004386139567941427  (0.006146573139211306)
     | > loss: 0.18703971803188324  (0.19706077128648758)
     | > align_error: 0.5467752814292908  (0.5984247464400071)

   --> STEP: 27
     | > decoder_loss: 0.4319310486316681  (0.45179407353754397)
     | > postnet_loss: 0.2929166555404663  (0.31042534444067216)
     | > stopnet_loss: 0.003957862034440041  (0.006065509764960519)
     | > loss: 0.1851697862148285  (0.1966203644319817)
     | > align_error: 0.5411863625049591  (0.5963048062942646)

   --> STEP: 28
     | > decoder_loss: 0.4370831549167633  (0.4512686835868018)
     | > postnet_loss: 0.2967613637447357  (0.30993734513010296)
     | > stopnet_loss: 0.003965259063988924  (0.00599050081135439)
     | > loss: 0.1874263882637024  (0.19629200814025743)
     | > align_error: 0.5663750469684601  (0.595235886318343)

   --> STEP: 29
     | > decoder_loss: 0.4326673746109009  (0.4506272591393569)
     | > postnet_loss: 0.2933133840560913  (0.3093641050930681)
     | > stopnet_loss: 0.0036040109116584063  (0.005908208056192459)
     | > loss: 0.18509919941425323  (0.19590604921867108)
     | > align_error: 0.5403251349925995  (0.5933424121346967)

   --> STEP: 30
     | > decoder_loss: 0.43359896540641785  (0.450059649348259)
     | > postnet_loss: 0.2942827641963959  (0.30886139372984567)
     | > stopnet_loss: 0.0029593463987112045  (0.005809912667609751)
     | > loss: 0.1849297732114792  (0.19554017335176468)
     | > align_error: 0.533818244934082  (0.5913582732280095)

   --> STEP: 31
     | > decoder_loss: 0.4304427206516266  (0.4494268451967547)
     | > postnet_loss: 0.2939196527004242  (0.3083794020837353)
     | > stopnet_loss: 0.0037372519727796316  (0.005743052645195876)
     | > loss: 0.18482784926891327  (0.19519461451038236)
     | > align_error: 0.5581207871437073  (0.5902860962575481)

   --> STEP: 32
     | > decoder_loss: 0.44015783071517944  (0.4491371884942055)
     | > postnet_loss: 0.29842087626457214  (0.30806819815188646)
     | > stopnet_loss: 0.0038945109117776155  (0.005685285716026556)
     | > loss: 0.18853917717933655  (0.1949866320937872)
     | > align_error: 0.530788391828537  (0.5884267929941416)

   --> STEP: 33
     | > decoder_loss: 0.43784621357917786  (0.44879503773920465)
     | > postnet_loss: 0.2972768247127533  (0.3077411868355491)
     | > stopnet_loss: 0.004031028598546982  (0.005635156712466569)
     | > loss: 0.18781179189682007  (0.1947692126938791)
     | > align_error: 0.5457928776741028  (0.5871348561662616)

   --> STEP: 34
     | > decoder_loss: 0.442505419254303  (0.44861004896023693)
     | > postnet_loss: 0.29808560013771057  (0.30745719899149504)
     | > stopnet_loss: 0.0033565901685506105  (0.005568140049410217)
     | > loss: 0.18850435316562653  (0.19458495211951873)
     | > align_error: 0.5631479620933533  (0.5864293592817643)

   --> STEP: 35
     | > decoder_loss: 0.4400172233581543  (0.4483645396573203)
     | > postnet_loss: 0.2971304953098297  (0.30716215031487604)
     | > stopnet_loss: 0.0035428409464657307  (0.00551027436075466)
     | > loss: 0.18782976269721985  (0.19439194670745305)
     | > align_error: 0.5329962372779846  (0.5849026986530849)

   --> STEP: 36
     | > decoder_loss: 0.4473733901977539  (0.44833700772788787)
     | > postnet_loss: 0.30247947573661804  (0.3070320760210355)
     | > stopnet_loss: 0.003707082010805607  (0.005460185684367186)
     | > loss: 0.19117030501365662  (0.19430245666040313)
     | > align_error: 0.6337365508079529  (0.5862591945462756)

   --> STEP: 37
     | > decoder_loss: 0.43910717964172363  (0.44808755291474833)
     | > postnet_loss: 0.2982161343097687  (0.3067938073261364)
     | > stopnet_loss: 0.003603068646043539  (0.005409993331980061)
     | > loss: 0.18793389201164246  (0.19413033329151771)
     | > align_error: 0.518712043762207  (0.584433595876436)

   --> STEP: 38
     | > decoder_loss: 0.42677542567253113  (0.44752670746100576)
     | > postnet_loss: 0.29133501648902893  (0.30638699704094935)
     | > stopnet_loss: 0.0031728006433695555  (0.005351119840174522)
     | > loss: 0.18270041048526764  (0.19382954584924797)
     | > align_error: 0.5510876178741455  (0.5835560701395336)

   --> STEP: 39
     | > decoder_loss: 0.44204995036125183  (0.4473862777917813)
     | > postnet_loss: 0.3013209104537964  (0.3062570973848685)
     | > stopnet_loss: 0.0035033191088587046  (0.005303740334243347)
     | > loss: 0.189346045255661  (0.19371458429556623)
     | > align_error: 0.5455994606018066  (0.5825828237411304)

   --> STEP: 40
     | > decoder_loss: 0.4392212927341461  (0.44718215316534043)
     | > postnet_loss: 0.3002152740955353  (0.30610605180263517)
     | > stopnet_loss: 0.0030736385378986597  (0.00524798778933473)
     | > loss: 0.18793277442455292  (0.19357003904879092)
     | > align_error: 0.5836613178253174  (0.582609786093235)

   --> STEP: 41
     | > decoder_loss: 0.4297349750995636  (0.4467566122369068)
     | > postnet_loss: 0.292347252368927  (0.3057704713286423)
     | > stopnet_loss: 0.0037552143912762403  (0.005211578682065012)
     | > loss: 0.1842757761478424  (0.19334334970974337)
     | > align_error: 0.50298672914505  (0.580667760314011)

   --> STEP: 42
     | > decoder_loss: 0.4349011480808258  (0.44647433928080965)
     | > postnet_loss: 0.2950018644332886  (0.305514075926372)
     | > stopnet_loss: 0.0033047168981283903  (0.005166177211018902)
     | > loss: 0.18578046560287476  (0.1931632810405322)
     | > align_error: 0.5792621076107025  (0.5806342923925036)

   --> STEP: 43
     | > decoder_loss: 0.43354952335357666  (0.44617376216622284)
     | > postnet_loss: 0.29380595684051514  (0.305241794087166)
     | > stopnet_loss: 0.002959500066936016  (0.0051148591379006954)
     | > loss: 0.18479837477207184  (0.1929687483366145)
     | > align_error: 0.5514812171459198  (0.5799563138983971)

   --> STEP: 44
     | > decoder_loss: 0.45152518153190613  (0.44629538533362473)
     | > postnet_loss: 0.3038375675678253  (0.30520987984809006)
     | > stopnet_loss: 0.0026963476557284594  (0.005059892967851327)
     | > loss: 0.1915370374917984  (0.1929362094537778)
     | > align_error: 0.5506465435028076  (0.5792901827530428)

   --> STEP: 45
     | > decoder_loss: 0.44432634115219116  (0.44625162879625957)
     | > postnet_loss: 0.3030237853527069  (0.30516129997041486)
     | > stopnet_loss: 0.0033473700750619173  (0.005021836903567118)
     | > loss: 0.19018489122390747  (0.19287506904866955)
     | > align_error: 0.5521925687789917  (0.5786880135536194)

   --> STEP: 46
     | > decoder_loss: 0.43545299768447876  (0.4460168759460035)
     | > postnet_loss: 0.2944953739643097  (0.3049294320137604)
     | > stopnet_loss: 0.0032365398947149515  (0.004983026099026853)
     | > loss: 0.18572364747524261  (0.19271960336229071)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3627876260063866 (+0.007597012953324822)
     | > avg_decoder_loss: 0.44213899879744556 (-4.718430114519778e-05)
     | > avg_postnet_loss: 0.301908733718323 (-0.002578597628709045)
     | > avg_stopnet_loss: 0.0044136557650441945 (+2.3467261626415083e-05)
     | > avg_loss: 0.19042558900334616 (-0.000632979201548034)
     | > avg_align_error: 0.571493978301684 (-0.0005122883753345686)


 > EPOCH: 108/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 12:47:11)

   --> TIME: 2025-12-28 12:47:37 -- STEP: 17/150 -- GLOBAL_STEP: 16325
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46183472871780396  (0.4667524870704202)
     | > postnet_loss: 0.39150649309158325  (0.39723140351912556)
     | > stopnet_loss: 0.007389836944639683  (0.010831417378914706)
     | > loss: 0.2207251489162445  (0.22682739093023188)
     | > align_error: 0.6934838891029358  (0.681473598760717)
     | > grad_norm: tensor(0.1979, device='cuda:0')  (tensor(0.2529, device='cuda:0'))
     | > step_time: 0.7608  (0.5791136376998004)
     | > loader_time: 1.0969  (0.8596364890827852)


   --> TIME: 2025-12-28 12:48:26 -- STEP: 42/150 -- GLOBAL_STEP: 16350
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4845719039440155  (0.4757830720572245)
     | > postnet_loss: 0.4012579321861267  (0.40048653809797197)
     | > stopnet_loss: 0.0052665844559669495  (0.008079199087140814)
     | > loss: 0.2267240285873413  (0.22714660068353018)
     | > align_error: 0.60061115026474  (0.652494667541413)
     | > grad_norm: tensor(0.1326, device='cuda:0')  (tensor(0.2385, device='cuda:0'))
     | > step_time: 1.2347  (0.8146840901601882)
     | > loader_time: 1.0369  (0.9275065774009341)


   --> TIME: 2025-12-28 12:49:27 -- STEP: 67/150 -- GLOBAL_STEP: 16375
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48873382806777954  (0.48005600206887544)
     | > postnet_loss: 0.40167537331581116  (0.4008753668906084)
     | > stopnet_loss: 0.004163231700658798  (0.0067347644501602015)
     | > loss: 0.22676554322242737  (0.22696760608189143)
     | > align_error: 0.6147968173027039  (0.6393406720303776)
     | > grad_norm: tensor(0.1437, device='cuda:0')  (tensor(0.2149, device='cuda:0'))
     | > step_time: 1.3883  (1.0023334239845845)
     | > loader_time: 1.2362  (1.0116680913896703)


   --> TIME: 2025-12-28 12:50:48 -- STEP: 92/150 -- GLOBAL_STEP: 16400
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4842592775821686  (0.48200051324523013)
     | > postnet_loss: 0.39640820026397705  (0.4004159806215245)
     | > stopnet_loss: 0.003735614474862814  (0.005956439513956073)
     | > loss: 0.22390247881412506  (0.22656056301101393)
     | > align_error: 0.6603088676929474  (0.6340475914918858)
     | > grad_norm: tensor(0.1719, device='cuda:0')  (tensor(0.2131, device='cuda:0'))
     | > step_time: 1.6872  (1.1654932913572895)
     | > loader_time: 1.7081  (1.179993595765984)


   --> TIME: 2025-12-28 12:52:14 -- STEP: 117/150 -- GLOBAL_STEP: 16425
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4862753748893738  (0.48327667616371417)
     | > postnet_loss: 0.3961345851421356  (0.4000335190540705)
     | > stopnet_loss: 0.003261357545852661  (0.005426512241092883)
     | > loss: 0.22386384010314941  (0.22625406137388995)
     | > align_error: 0.6222403645515442  (0.6283856574286762)
     | > grad_norm: tensor(0.1733, device='cuda:0')  (tensor(0.2102, device='cuda:0'))
     | > step_time: 1.8787  (1.2893675209110624)
     | > loader_time: 1.6257  (1.2873643850668872)


   --> TIME: 2025-12-28 12:53:49 -- STEP: 142/150 -- GLOBAL_STEP: 16450
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49907562136650085  (0.4845796231652649)
     | > postnet_loss: 0.4044457972049713  (0.3997759185206723)
     | > stopnet_loss: 0.0030597192235291004  (0.005031457641424323)
     | > loss: 0.22894006967544556  (0.22612034330065822)
     | > align_error: 0.5915073752403259  (0.6247703164396152)
     | > grad_norm: tensor(0.2392, device='cuda:0')  (tensor(0.2105, device='cuda:0'))
     | > step_time: 2.1833  (1.423378820150671)
     | > loader_time: 1.7221  (1.3650663688149243)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46417129039764404  (0.46417129039764404)
     | > postnet_loss: 0.33700084686279297  (0.33700084686279297)
     | > stopnet_loss: 0.012115784920752048  (0.012115784920752048)
     | > loss: 0.21240882575511932  (0.21240882575511932)
     | > align_error: 0.7188277542591095  (0.7188277542591095)

   --> STEP: 1
     | > decoder_loss: 0.4457686245441437  (0.4457686245441437)
     | > postnet_loss: 0.32606810331344604  (0.32606810331344604)
     | > stopnet_loss: 0.009643960744142532  (0.009643960744142532)
     | > loss: 0.20260314643383026  (0.20260314643383026)
     | > align_error: 0.6592046618461609  (0.6592046618461609)

   --> STEP: 2
     | > decoder_loss: 0.4417196810245514  (0.44374415278434753)
     | > postnet_loss: 0.31558459997177124  (0.32082635164260864)
     | > stopnet_loss: 0.011186686344444752  (0.010415323544293642)
     | > loss: 0.20051276683807373  (0.201557956635952)
     | > align_error: 0.6556215882301331  (0.657413125038147)

   --> STEP: 3
     | > decoder_loss: 0.44391104578971863  (0.4437997837861379)
     | > postnet_loss: 0.31452083587646484  (0.31872451305389404)
     | > stopnet_loss: 0.008317925035953522  (0.00971619070818027)
     | > loss: 0.1979258954524994  (0.20034726957480112)
     | > align_error: 0.7347151041030884  (0.6831804513931274)

   --> STEP: 4
     | > decoder_loss: 0.4501282870769501  (0.44538190960884094)
     | > postnet_loss: 0.32365354895591736  (0.31995677202939987)
     | > stopnet_loss: 0.008207021281123161  (0.009338898351415992)
     | > loss: 0.20165248215198517  (0.20067357271909714)
     | > align_error: 0.6034115552902222  (0.6632382273674011)

   --> STEP: 5
     | > decoder_loss: 0.4312952756881714  (0.442564582824707)
     | > postnet_loss: 0.3049792945384979  (0.31696127653121947)
     | > stopnet_loss: 0.008256103843450546  (0.009122339449822903)
     | > loss: 0.19232475757598877  (0.19900380969047546)
     | > align_error: 0.6419283151626587  (0.6589762449264527)

   --> STEP: 6
     | > decoder_loss: 0.44794726371765137  (0.44346169630686444)
     | > postnet_loss: 0.31715846061706543  (0.31699414054552716)
     | > stopnet_loss: 0.007262121886014938  (0.008812303189188242)
     | > loss: 0.19853855669498444  (0.1989262675245603)
     | > align_error: 0.5938758254051208  (0.6481261750062307)

   --> STEP: 7
     | > decoder_loss: 0.45823732018470764  (0.4455724997179849)
     | > postnet_loss: 0.31577056646347046  (0.3168193442480905)
     | > stopnet_loss: 0.00625672098249197  (0.00844722001680306)
     | > loss: 0.19975869357585907  (0.19904518553188869)
     | > align_error: 0.5791880786418915  (0.6382778755256108)

   --> STEP: 8
     | > decoder_loss: 0.4549340605735779  (0.446742694824934)
     | > postnet_loss: 0.3183915615081787  (0.3170158714056015)
     | > stopnet_loss: 0.0075403908267617226  (0.008333866368047893)
     | > loss: 0.2008717954158783  (0.1992735117673874)
     | > align_error: 0.5754959583282471  (0.6304301358759403)

   --> STEP: 9
     | > decoder_loss: 0.45207497477531433  (0.4473351703749763)
     | > postnet_loss: 0.3175245523452759  (0.31707239151000977)
     | > stopnet_loss: 0.006674751173704863  (0.008149520235343112)
     | > loss: 0.1990746408700943  (0.1992514150010215)
     | > align_error: 0.5912531018257141  (0.6260771320925819)

   --> STEP: 10
     | > decoder_loss: 0.476764053106308  (0.45027805864810944)
     | > postnet_loss: 0.3316839039325714  (0.3185335427522659)
     | > stopnet_loss: 0.005561781581491232  (0.007890746369957924)
     | > loss: 0.20767377316951752  (0.2000936508178711)
     | > align_error: 0.5842108428478241  (0.6218905031681061)

   --> STEP: 11
     | > decoder_loss: 0.4638154208660126  (0.45150872794064606)
     | > postnet_loss: 0.32114377617836  (0.31877083670009265)
     | > stopnet_loss: 0.005916735623031855  (0.007711290847510099)
     | > loss: 0.20215652883052826  (0.2002811851826581)
     | > align_error: 0.5947324633598328  (0.6194215904582631)

   --> STEP: 12
     | > decoder_loss: 0.4590120017528534  (0.45213400075833005)
     | > postnet_loss: 0.314335435628891  (0.3184012199441592)
     | > stopnet_loss: 0.007889783941209316  (0.0077261652719850344)
     | > loss: 0.2012266367673874  (0.20035997281471887)
     | > align_error: 0.5877325236797333  (0.6167808348933855)

   --> STEP: 13
     | > decoder_loss: 0.4487383961677551  (0.4518728004052089)
     | > postnet_loss: 0.3140937387943268  (0.3180698752403259)
     | > stopnet_loss: 0.005622916854918003  (0.0075643769322106475)
     | > loss: 0.1963309645652771  (0.20005004910322335)
     | > align_error: 0.5859681665897369  (0.6144106296392587)

   --> STEP: 14
     | > decoder_loss: 0.46178561449050903  (0.4525808585541589)
     | > postnet_loss: 0.31832045316696167  (0.31808777366365704)
     | > stopnet_loss: 0.004942556377500296  (0.007377104035445622)
     | > loss: 0.1999690681695938  (0.20004426475082124)
     | > align_error: 0.5548941493034363  (0.6101594524724143)

   --> STEP: 15
     | > decoder_loss: 0.45716243982315063  (0.452886297305425)
     | > postnet_loss: 0.31626567244529724  (0.3179663002490997)
     | > stopnet_loss: 0.005000917240977287  (0.007218691582481066)
     | > loss: 0.1983579397201538  (0.1999318430821101)
     | > align_error: 0.5887556672096252  (0.608732533454895)

   --> STEP: 16
     | > decoder_loss: 0.4580059349536896  (0.45320627465844154)
     | > postnet_loss: 0.3100718557834625  (0.3174728974699974)
     | > stopnet_loss: 0.005245234817266464  (0.007095350534655154)
     | > loss: 0.1972646862268448  (0.199765145778656)
     | > align_error: 0.6061604022979736  (0.6085717752575874)

   --> STEP: 17
     | > decoder_loss: 0.46407604217529297  (0.45384567274766807)
     | > postnet_loss: 0.3183493912220001  (0.31752445592599754)
     | > stopnet_loss: 0.004852287471294403  (0.006963405648575109)
     | > loss: 0.20045864582061768  (0.1998059398987714)
     | > align_error: 0.558504194021225  (0.6056266234201544)

   --> STEP: 18
     | > decoder_loss: 0.45924562215805054  (0.4541456699371338)
     | > postnet_loss: 0.3112197816371918  (0.31717419624328613)
     | > stopnet_loss: 0.005302013363689184  (0.006871106077192558)
     | > loss: 0.1979183554649353  (0.1997010740968916)
     | > align_error: 0.6041118502616882  (0.6055424693557951)

   --> STEP: 19
     | > decoder_loss: 0.45884254574775696  (0.4543928739271666)
     | > postnet_loss: 0.3117309808731079  (0.31688771122380305)
     | > stopnet_loss: 0.004821676295250654  (0.006763241351827195)
     | > loss: 0.19746504724025726  (0.19958338847285823)
     | > align_error: 0.6004613041877747  (0.6052750396101099)

   --> STEP: 20
     | > decoder_loss: 0.4527921974658966  (0.4543128401041031)
     | > postnet_loss: 0.30651307106018066  (0.31636897921562196)
     | > stopnet_loss: 0.004522649105638266  (0.006651211739517748)
     | > loss: 0.19434896111488342  (0.1993216671049595)
     | > align_error: 0.6229360401630402  (0.6061580896377563)

   --> STEP: 21
     | > decoder_loss: 0.45109784603118896  (0.45415974514825)
     | > postnet_loss: 0.3067982792854309  (0.3159132315998986)
     | > stopnet_loss: 0.004006525501608849  (0.006525274299617324)
     | > loss: 0.19348055124282837  (0.1990435187305723)
     | > align_error: 0.5600867867469788  (0.6039642180715289)

   --> STEP: 22
     | > decoder_loss: 0.45212796330451965  (0.45406739142808045)
     | > postnet_loss: 0.30880048871040344  (0.31558992510492156)
     | > stopnet_loss: 0.004876339342445135  (0.006450322710654952)
     | > loss: 0.19510845839977264  (0.19886465235189957)
     | > align_error: 0.6254865527153015  (0.6049425060098822)

   --> STEP: 23
     | > decoder_loss: 0.42566221952438354  (0.4528323839540067)
     | > postnet_loss: 0.29688504338264465  (0.314776669377866)
     | > stopnet_loss: 0.004531971178948879  (0.006366916122319905)
     | > loss: 0.1851687878370285  (0.1982691799816878)
     | > align_error: 0.5674765706062317  (0.60331355229668)

   --> STEP: 24
     | > decoder_loss: 0.4600122272968292  (0.453131544093291)
     | > postnet_loss: 0.31205570697784424  (0.3146632959445318)
     | > stopnet_loss: 0.004412832669913769  (0.00628549597846965)
     | > loss: 0.1974298059940338  (0.19823420606553555)
     | > align_error: 0.5796809196472168  (0.6023288592696191)

   --> STEP: 25
     | > decoder_loss: 0.45856761932373047  (0.45334898710250854)
     | > postnet_loss: 0.3090056777000427  (0.3144369912147522)
     | > stopnet_loss: 0.00372106209397316  (0.006182918623089791)
     | > loss: 0.19561438262462616  (0.19812941312789917)
     | > align_error: 0.5581931173801422  (0.6005634295940401)

   --> STEP: 26
     | > decoder_loss: 0.43359851837158203  (0.4525893536897806)
     | > postnet_loss: 0.29826751351356506  (0.313815088226245)
     | > stopnet_loss: 0.004392711445689201  (0.006114064500882075)
     | > loss: 0.18735921382904053  (0.1977151746933277)
     | > align_error: 0.5470261573791504  (0.5985043037396213)

   --> STEP: 27
     | > decoder_loss: 0.43070441484451294  (0.45177880039921514)
     | > postnet_loss: 0.2929847836494446  (0.3130435954641413)
     | > stopnet_loss: 0.003926350735127926  (0.0060330380651134035)
     | > loss: 0.18484865128993988  (0.19723863678949852)
     | > align_error: 0.5415092408657074  (0.5963933754850319)

   --> STEP: 28
     | > decoder_loss: 0.4364573657512665  (0.45123160630464554)
     | > postnet_loss: 0.297743558883667  (0.3124971655862672)
     | > stopnet_loss: 0.003964693285524845  (0.0059591686086995265)
     | > loss: 0.18751493096351624  (0.1968913615814277)
     | > align_error: 0.5666625797748566  (0.5953315613525257)

   --> STEP: 29
     | > decoder_loss: 0.4313846826553345  (0.4505472296270831)
     | > postnet_loss: 0.2945748567581177  (0.3118791549370207)
     | > stopnet_loss: 0.003595345187932253  (0.005877657456259276)
     | > loss: 0.1850852370262146  (0.1964842538381445)
     | > align_error: 0.5405870079994202  (0.593443818133453)

   --> STEP: 30
     | > decoder_loss: 0.4321582615375519  (0.4499342640240987)
     | > postnet_loss: 0.29523879289627075  (0.311324476202329)
     | > stopnet_loss: 0.002869624877348542  (0.005777389703628917)
     | > loss: 0.18471889197826385  (0.19609207510948182)
     | > align_error: 0.5337505638599396  (0.5914540429910027)

   --> STEP: 31
     | > decoder_loss: 0.4292786121368408  (0.4492679526728968)
     | > postnet_loss: 0.29429498314857483  (0.31077513771672405)
     | > stopnet_loss: 0.0037039080634713173  (0.005710503199107705)
     | > loss: 0.18459729850292206  (0.19572127586410892)
     | > align_error: 0.5576511323451996  (0.5903636265185573)

   --> STEP: 32
     | > decoder_loss: 0.4398905634880066  (0.448974909260869)
     | > postnet_loss: 0.29988014698028564  (0.3104346692562103)
     | > stopnet_loss: 0.0038666261825710535  (0.005652882042340934)
     | > loss: 0.18880930542945862  (0.1955052767880261)
     | > align_error: 0.530918151140213  (0.5885059554129841)

   --> STEP: 33
     | > decoder_loss: 0.4367973804473877  (0.4486058932362181)
     | > postnet_loss: 0.2970799207687378  (0.3100299799081051)
     | > stopnet_loss: 0.004018914885818958  (0.005603367886082692)
     | > loss: 0.18748824298381805  (0.19526233636971677)
     | > align_error: 0.5460408329963684  (0.5872191335215715)

   --> STEP: 34
     | > decoder_loss: 0.4424644410610199  (0.4484252622898887)
     | > postnet_loss: 0.29857316613197327  (0.3096930147970424)
     | > stopnet_loss: 0.0033207775559276342  (0.005536232876372249)
     | > loss: 0.18858018517494202  (0.1950658025110469)
     | > align_error: 0.5636722147464752  (0.5865265770870098)

   --> STEP: 35
     | > decoder_loss: 0.4393593668937683  (0.4481662367071424)
     | > postnet_loss: 0.297980934381485  (0.30935838392802645)
     | > stopnet_loss: 0.0035369833931326866  (0.005479111462565405)
     | > loss: 0.18787206709384918  (0.19486026721341268)
     | > align_error: 0.5333287715911865  (0.5850066397871292)

   --> STEP: 36
     | > decoder_loss: 0.4458913505077362  (0.44810304542382556)
     | > postnet_loss: 0.302320271730423  (0.3091628808114264)
     | > stopnet_loss: 0.0036912003997713327  (0.005429447266376681)
     | > loss: 0.19074410200119019  (0.19474592929085094)
     | > align_error: 0.6339224278926849  (0.5863654116789502)

   --> STEP: 37
     | > decoder_loss: 0.4380701184272766  (0.44783188523472967)
     | > postnet_loss: 0.29900696873664856  (0.30888839670129725)
     | > stopnet_loss: 0.0035823117941617966  (0.005379524686046549)
     | > loss: 0.18785159289836884  (0.1945595958748379)
     | > align_error: 0.5189165771007538  (0.5845424702038639)

   --> STEP: 38
     | > decoder_loss: 0.4261001646518707  (0.4472599978509702)
     | > postnet_loss: 0.2919139564037323  (0.3084417009039929)
     | > stopnet_loss: 0.0031578342895954847  (0.005321059149297837)
     | > loss: 0.18266136944293976  (0.19424648465294583)
     | > align_error: 0.5516445934772491  (0.5836767366057951)

   --> STEP: 39
     | > decoder_loss: 0.4415232539176941  (0.4471129018526811)
     | > postnet_loss: 0.30256175994873047  (0.3082909331871913)
     | > stopnet_loss: 0.003479212522506714  (0.005273832312713449)
     | > loss: 0.18950046598911285  (0.1941247918666937)
     | > align_error: 0.5458767414093018  (0.5827075059597312)

   --> STEP: 40
     | > decoder_loss: 0.43808597326278687  (0.44688722863793373)
     | > postnet_loss: 0.3007310926914215  (0.30810193717479706)
     | > stopnet_loss: 0.0030547610949724913  (0.005218355532269925)
     | > loss: 0.18775904178619385  (0.19396564811468123)
     | > align_error: 0.5840102136135101  (0.5827400736510756)

   --> STEP: 41
     | > decoder_loss: 0.42938798666000366  (0.44646041785798424)
     | > postnet_loss: 0.2934568524360657  (0.3077447399860475)
     | > stopnet_loss: 0.003730572760105133  (0.005182068147582979)
     | > loss: 0.18444177508354187  (0.19373335852855586)
     | > align_error: 0.5032175779342651  (0.5808005005848119)

   --> STEP: 42
     | > decoder_loss: 0.43429481983184814  (0.4461707607621238)
     | > postnet_loss: 0.2952730655670166  (0.307447795357023)
     | > stopnet_loss: 0.0032967079896479845  (0.005137178620013098)
     | > loss: 0.18568867444992065  (0.1935418184314455)
     | > align_error: 0.5795473456382751  (0.5807706635622754)

   --> STEP: 43
     | > decoder_loss: 0.4322415292263031  (0.4458468251450117)
     | > postnet_loss: 0.2936038076877594  (0.3071258421554122)
     | > stopnet_loss: 0.0029293575789779425  (0.005085833944640187)
     | > loss: 0.18439069390296936  (0.19332900158194605)
     | > align_error: 0.5517130792140961  (0.5800949057867363)

   --> STEP: 44
     | > decoder_loss: 0.450869083404541  (0.44596096737818286)
     | > postnet_loss: 0.3046489953994751  (0.30706955018368637)
     | > stopnet_loss: 0.002670604968443513  (0.005030942376999353)
     | > loss: 0.1915501207113266  (0.19328857247125014)
     | > align_error: 0.5510357618331909  (0.579434470696883)

   --> STEP: 45
     | > decoder_loss: 0.4440044164657593  (0.44591748846901785)
     | > postnet_loss: 0.30371636152267456  (0.3069950348801083)
     | > stopnet_loss: 0.0033092296216636896  (0.004992682093547449)
     | > loss: 0.19023942947387695  (0.1932208137379752)
     | > align_error: 0.5526652336120605  (0.5788395987616647)

   --> STEP: 46
     | > decoder_loss: 0.43348950147628784  (0.44564731483874115)
     | > postnet_loss: 0.29475218057632446  (0.30672888587350433)
     | > stopnet_loss: 0.003209424437955022  (0.004953915622773701)
     | > loss: 0.18526984751224518  (0.19304796664611149)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.25914287928378954 (-0.10364474672259705)
     | > avg_decoder_loss: 0.44137373295697296 (-0.0007652658404725954)
     | > avg_postnet_loss: 0.3035693227341681 (+0.001660589015845093)
     | > avg_stopnet_loss: 0.004391363973616424 (-2.2291791427770345e-05)
     | > avg_loss: 0.1906271283373688 (+0.00020153933402264346)
     | > avg_align_error: 0.5717166156479809 (+0.00022263734629690557)


 > EPOCH: 109/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 12:56:09)

   --> TIME: 2025-12-28 12:56:30 -- STEP: 16/150 -- GLOBAL_STEP: 16475
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47059205174446106  (0.4692812170833349)
     | > postnet_loss: 0.39751866459846497  (0.39924962259829044)
     | > stopnet_loss: 0.008648569695651531  (0.010987307294271886)
     | > loss: 0.2256762534379959  (0.22812001686543226)
     | > align_error: 0.6766720116138458  (0.6810459736734629)
     | > grad_norm: tensor(0.1875, device='cuda:0')  (tensor(0.2898, device='cuda:0'))
     | > step_time: 0.7152  (0.5741992294788361)
     | > loader_time: 0.9698  (0.7165357321500778)


   --> TIME: 2025-12-28 12:57:22 -- STEP: 41/150 -- GLOBAL_STEP: 16500
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.488912433385849  (0.4774433650621554)
     | > postnet_loss: 0.4065476059913635  (0.40178338129345964)
     | > stopnet_loss: 0.004967038985341787  (0.008129825349897146)
     | > loss: 0.22883203625679016  (0.22793651390366437)
     | > align_error: 0.5942174196243286  (0.6537343183668648)
     | > grad_norm: tensor(0.1646, device='cuda:0')  (tensor(0.2787, device='cuda:0'))
     | > step_time: 1.0799  (0.7964007505556434)
     | > loader_time: 1.0292  (0.9615770200403725)


   --> TIME: 2025-12-28 12:58:29 -- STEP: 66/150 -- GLOBAL_STEP: 16525
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.4899444282054901  (0.48129403952396277)
     | > postnet_loss: 0.4018186032772064  (0.4018041468930967)
     | > stopnet_loss: 0.003862678073346615  (0.006754226199435917)
     | > loss: 0.22680343687534332  (0.22752877257087015)
     | > align_error: 0.6174819469451904  (0.6402519765225324)
     | > grad_norm: tensor(0.1946, device='cuda:0')  (tensor(0.2667, device='cuda:0'))
     | > step_time: 1.5371  (0.9951870441436768)
     | > loader_time: 1.3825  (1.1179617390488132)


   --> TIME: 2025-12-28 12:59:48 -- STEP: 91/150 -- GLOBAL_STEP: 16550
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48703905940055847  (0.4830650923016307)
     | > postnet_loss: 0.39763563871383667  (0.4011805139400147)
     | > stopnet_loss: 0.003817747812718153  (0.0059641226998192595)
     | > loss: 0.22498641908168793  (0.22702552460052156)
     | > align_error: 0.596443235874176  (0.6343749931880405)
     | > grad_norm: tensor(0.1506, device='cuda:0')  (tensor(0.2565, device='cuda:0'))
     | > step_time: 1.6688  (1.1420165916065594)
     | > loader_time: 1.6104  (1.258087126763312)


   --> TIME: 2025-12-28 13:01:20 -- STEP: 116/150 -- GLOBAL_STEP: 16575
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48729053139686584  (0.48418324800400897)
     | > postnet_loss: 0.3981420695781708  (0.40067332931633654)
     | > stopnet_loss: 0.0030304298270493746  (0.005432247011601154)
     | > loss: 0.22438858449459076  (0.2266463914821888)
     | > align_error: 0.5899945199489594  (0.6291407565104548)
     | > grad_norm: tensor(0.1655, device='cuda:0')  (tensor(0.2402, device='cuda:0'))
     | > step_time: 1.7875  (1.3077061669579868)
     | > loader_time: 2.9332  (1.3683976387155465)


   --> TIME: 2025-12-28 13:03:05 -- STEP: 141/150 -- GLOBAL_STEP: 16600
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4927837550640106  (0.4852555958514518)
     | > postnet_loss: 0.3983023762702942  (0.40025389257897714)
     | > stopnet_loss: 0.0029466296546161175  (0.005030629109485564)
     | > loss: 0.225718155503273  (0.22640800137891837)
     | > align_error: 0.6038329601287842  (0.6254574056212782)
     | > grad_norm: tensor(0.1975, device='cuda:0')  (tensor(0.2316, device='cuda:0'))
     | > step_time: 2.1592  (1.4574812777498933)
     | > loader_time: 2.5759  (1.4894602603100715)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46260207891464233  (0.46260207891464233)
     | > postnet_loss: 0.33407312631607056  (0.33407312631607056)
     | > stopnet_loss: 0.012198717333376408  (0.012198717333376408)
     | > loss: 0.21136751770973206  (0.21136751770973206)
     | > align_error: 0.7185537219047546  (0.7185537219047546)

   --> STEP: 1
     | > decoder_loss: 0.4431198537349701  (0.4431198537349701)
     | > postnet_loss: 0.32164692878723145  (0.32164692878723145)
     | > stopnet_loss: 0.009686212055385113  (0.009686212055385113)
     | > loss: 0.20087791979312897  (0.20087791979312897)
     | > align_error: 0.6594756841659546  (0.6594756841659546)

   --> STEP: 2
     | > decoder_loss: 0.4405544400215149  (0.4418371468782425)
     | > postnet_loss: 0.3131434917449951  (0.3173952102661133)
     | > stopnet_loss: 0.011160669848322868  (0.01042344095185399)
     | > loss: 0.19958515465259552  (0.20023153722286224)
     | > align_error: 0.6556340456008911  (0.6575548648834229)

   --> STEP: 3
     | > decoder_loss: 0.44139376282691956  (0.4416893521944682)
     | > postnet_loss: 0.3106742799282074  (0.31515490015347797)
     | > stopnet_loss: 0.00813064631074667  (0.009659176071484884)
     | > loss: 0.19614765048027039  (0.1988702416419983)
     | > align_error: 0.733801543712616  (0.6829704244931539)

   --> STEP: 4
     | > decoder_loss: 0.4491884410381317  (0.44356412440538406)
     | > postnet_loss: 0.3205386698246002  (0.31650084257125854)
     | > stopnet_loss: 0.008256372064352036  (0.009308475069701672)
     | > loss: 0.20068815350532532  (0.19932471960783005)
     | > align_error: 0.6033601760864258  (0.6630678623914719)

   --> STEP: 5
     | > decoder_loss: 0.4312087595462799  (0.44109305143356325)
     | > postnet_loss: 0.30260929465293884  (0.3137225329875946)
     | > stopnet_loss: 0.008225761353969574  (0.009091932326555252)
     | > loss: 0.19168028235435486  (0.197795832157135)
     | > align_error: 0.6418503820896149  (0.6588243663311004)

   --> STEP: 6
     | > decoder_loss: 0.44604727625846863  (0.4419187555710475)
     | > postnet_loss: 0.31393763422966003  (0.31375838319460553)
     | > stopnet_loss: 0.007274806499481201  (0.00878907802204291)
     | > loss: 0.19727103412151337  (0.19770836581786475)
     | > align_error: 0.5939422249794006  (0.6480106761058172)

   --> STEP: 7
     | > decoder_loss: 0.45554521679878235  (0.44386539288929533)
     | > postnet_loss: 0.3125545084476471  (0.31358640108789715)
     | > stopnet_loss: 0.006302529014647007  (0.008433856735272067)
     | > loss: 0.1983274668455124  (0.1977968088218144)
     | > align_error: 0.5787013173103333  (0.6381093391350338)

   --> STEP: 8
     | > decoder_loss: 0.4488406181335449  (0.4444872960448265)
     | > postnet_loss: 0.3123307526111603  (0.31342944502830505)
     | > stopnet_loss: 0.007053127512335777  (0.00826126558240503)
     | > loss: 0.19734595715999603  (0.1977404523640871)
     | > align_error: 0.5733894109725952  (0.6300193481147289)

   --> STEP: 9
     | > decoder_loss: 0.44819900393486023  (0.44489970803260803)
     | > postnet_loss: 0.31341552734375  (0.3134278986189101)
     | > stopnet_loss: 0.006681437138468027  (0.008085729088634253)
     | > loss: 0.19708508253097534  (0.19766763349374136)
     | > align_error: 0.5912966132164001  (0.6257168220149146)

   --> STEP: 10
     | > decoder_loss: 0.4737675189971924  (0.4477864891290665)
     | > postnet_loss: 0.3276134729385376  (0.3148464560508728)
     | > stopnet_loss: 0.005598027259111404  (0.007836958905681968)
     | > loss: 0.2059432715177536  (0.19849519729614257)
     | > align_error: 0.5830803513526917  (0.6214531749486923)

   --> STEP: 11
     | > decoder_loss: 0.46277251839637756  (0.44914885542609473)
     | > postnet_loss: 0.31874603033065796  (0.31520096280358056)
     | > stopnet_loss: 0.005883381236344576  (0.007659360935742205)
     | > loss: 0.20126302540302277  (0.19874681803313168)
     | > align_error: 0.5946653485298157  (0.6190179180015217)

   --> STEP: 12
     | > decoder_loss: 0.45263051986694336  (0.4494389941294988)
     | > postnet_loss: 0.3095760643482208  (0.3147322212656339)
     | > stopnet_loss: 0.007609053980559111  (0.007655168689476947)
     | > loss: 0.19816069304943085  (0.19869797428448996)
     | > align_error: 0.5847393572330475  (0.6161613712708155)

   --> STEP: 13
     | > decoder_loss: 0.4476771652698517  (0.44930346883260286)
     | > postnet_loss: 0.31204062700271606  (0.3145251755531018)
     | > stopnet_loss: 0.005644957069307566  (0.007500537026386995)
     | > loss: 0.19557441771030426  (0.19845770070186028)
     | > align_error: 0.586017370223999  (0.613842601959522)

   --> STEP: 14
     | > decoder_loss: 0.4558278024196625  (0.44976949266024996)
     | > postnet_loss: 0.3132670223712921  (0.3144353074686868)
     | > stopnet_loss: 0.004941167775541544  (0.007317724937040891)
     | > loss: 0.19721487164497375  (0.19836892719779695)
     | > align_error: 0.5542503595352173  (0.6095860132149288)

   --> STEP: 15
     | > decoder_loss: 0.45645955204963684  (0.45021549661954247)
     | > postnet_loss: 0.31504011154174805  (0.3144756277402242)
     | > stopnet_loss: 0.005001767538487911  (0.007163327777137359)
     | > loss: 0.1978766769170761  (0.19833611051241556)
     | > align_error: 0.588340550661087  (0.6081696490446726)

   --> STEP: 16
     | > decoder_loss: 0.4576224684715271  (0.4506784323602915)
     | > postnet_loss: 0.3089434802532196  (0.3141298685222864)
     | > stopnet_loss: 0.005241009872406721  (0.007043182908091694)
     | > loss: 0.1968824863433838  (0.19824525900185108)
     | > align_error: 0.6060174107551575  (0.608035134151578)

   --> STEP: 17
     | > decoder_loss: 0.4635993242263794  (0.45143848482300253)
     | > postnet_loss: 0.3173854351043701  (0.3143213724388796)
     | > stopnet_loss: 0.004854205995798111  (0.0069144195603097185)
     | > loss: 0.2001003921031952  (0.19835438447840073)
     | > align_error: 0.5590472519397736  (0.6051534940214718)

   --> STEP: 18
     | > decoder_loss: 0.4589000642299652  (0.45185301701227826)
     | > postnet_loss: 0.31025707721710205  (0.3140955782598919)
     | > stopnet_loss: 0.005277345888316631  (0.006823471022976769)
     | > loss: 0.19756664335727692  (0.19831062108278275)
     | > align_error: 0.604625940322876  (0.6051241854826609)

   --> STEP: 19
     | > decoder_loss: 0.45450559258461  (0.4519926262529273)
     | > postnet_loss: 0.30860674381256104  (0.3138066922363482)
     | > stopnet_loss: 0.0047256615944206715  (0.0067130600004211855)
     | > loss: 0.19550374150276184  (0.19816289057857112)
     | > align_error: 0.599216103553772  (0.6048132338021931)

   --> STEP: 20
     | > decoder_loss: 0.45387476682662964  (0.4520867332816124)
     | > postnet_loss: 0.30674782395362854  (0.3134537488222122)
     | > stopnet_loss: 0.004519531968981028  (0.006603383598849178)
     | > loss: 0.19467519223690033  (0.19798850566148757)
     | > align_error: 0.6234332025051117  (0.605744232237339)

   --> STEP: 21
     | > decoder_loss: 0.4503294825553894  (0.45200305467560176)
     | > postnet_loss: 0.3051374852657318  (0.31305773627190364)
     | > stopnet_loss: 0.003997351974248886  (0.006479286854820592)
     | > loss: 0.1928640902042389  (0.19774448587780907)
     | > align_error: 0.5604537129402161  (0.603587540842238)

   --> STEP: 22
     | > decoder_loss: 0.44995611906051636  (0.45191001214764337)
     | > postnet_loss: 0.3070228397846222  (0.31278342279520904)
     | > stopnet_loss: 0.004574492108076811  (0.006392705275423147)
     | > loss: 0.19381923973560333  (0.1975660655986179)
     | > align_error: 0.6245999336242676  (0.6045426496050575)

   --> STEP: 23
     | > decoder_loss: 0.42568737268447876  (0.4507698973883753)
     | > postnet_loss: 0.2961321175098419  (0.3120594530001931)
     | > stopnet_loss: 0.004513344261795282  (0.006310993927004544)
     | > loss: 0.18496821820735931  (0.1970183331033458)
     | > align_error: 0.5678081512451172  (0.6029454975024514)

   --> STEP: 24
     | > decoder_loss: 0.45999231934547424  (0.4511541649699211)
     | > postnet_loss: 0.3118341863155365  (0.3120500668883324)
     | > stopnet_loss: 0.0043683601543307304  (0.006230050853143136)
     | > loss: 0.1973249912261963  (0.19703111052513123)
     | > align_error: 0.5799934267997742  (0.6019891612231733)

   --> STEP: 25
     | > decoder_loss: 0.4584018886089325  (0.4514440739154816)
     | > postnet_loss: 0.30856531858444214  (0.3119106769561768)
     | > stopnet_loss: 0.003716516774147749  (0.00612950948998332)
     | > loss: 0.1954583078622818  (0.19696819841861724)
     | > align_error: 0.5582627356052399  (0.600240104198456)

   --> STEP: 26
     | > decoder_loss: 0.4339795708656311  (0.45077236225971806)
     | > postnet_loss: 0.2975296974182129  (0.31135756235856277)
     | > stopnet_loss: 0.004379941616207361  (0.0060622184179150145)
     | > loss: 0.18725726008415222  (0.1965947007903686)
     | > align_error: 0.5474869906902313  (0.5982111382942935)

   --> STEP: 27
     | > decoder_loss: 0.4299771785736084  (0.45000217027134365)
     | > postnet_loss: 0.2922486960887909  (0.31064982657079343)
     | > stopnet_loss: 0.003623463911935687  (0.005971894176952817)
     | > loss: 0.18417994678020477  (0.19613489508628845)
     | > align_error: 0.5412168204784393  (0.5961002376344472)

   --> STEP: 28
     | > decoder_loss: 0.43668195605278015  (0.4495264483349664)
     | > postnet_loss: 0.29733040928840637  (0.31017413309642244)
     | > stopnet_loss: 0.003916111774742603  (0.005898473376873881)
     | > loss: 0.18741920590400696  (0.19582362047263555)
     | > align_error: 0.5672274827957153  (0.5950690678187781)

   --> STEP: 29
     | > decoder_loss: 0.4315055012702942  (0.44890503636721907)
     | > postnet_loss: 0.29375630617141724  (0.30960800113349124)
     | > stopnet_loss: 0.0035806919913738966  (0.005818549880822157)
     | > loss: 0.18489614129066467  (0.19544681084567103)
     | > align_error: 0.5412404537200928  (0.5932129087119269)

   --> STEP: 30
     | > decoder_loss: 0.4318884015083313  (0.4483378152052561)
     | > postnet_loss: 0.2943243980407715  (0.30909854769706724)
     | > stopnet_loss: 0.0028218310326337814  (0.005718659252549211)
     | > loss: 0.18437503278255463  (0.1950777515769005)
     | > align_error: 0.5340193808078766  (0.5912397911151253)

   --> STEP: 31
     | > decoder_loss: 0.4286373257637024  (0.44770231554585116)
     | > postnet_loss: 0.29367098212242126  (0.3086008842914335)
     | > stopnet_loss: 0.0036788606084883213  (0.005652859296289182)
     | > loss: 0.1842559278011322  (0.19472866048735957)
     | > align_error: 0.5563934445381165  (0.5901157154190927)

   --> STEP: 32
     | > decoder_loss: 0.433002769947052  (0.4472429547458887)
     | > postnet_loss: 0.2960304021835327  (0.3082080567255616)
     | > stopnet_loss: 0.0036286136601120234  (0.005589601620158646)
     | > loss: 0.1858869045972824  (0.19445235561579466)
     | > align_error: 0.5278596878051758  (0.5881702145561578)

   --> STEP: 33
     | > decoder_loss: 0.4374226927757263  (0.4469453710498232)
     | > postnet_loss: 0.2973771095275879  (0.3078798462044109)
     | > stopnet_loss: 0.004011101555079222  (0.0055417682848532095)
     | > loss: 0.18771104514598846  (0.19424807348034598)
     | > align_error: 0.5470994412899017  (0.5869256456693016)

   --> STEP: 34
     | > decoder_loss: 0.44322431087493896  (0.44683592810350303)
     | > postnet_loss: 0.2988787591457367  (0.30761510834974404)
     | > stopnet_loss: 0.0032997559756040573  (0.005475826746345881)
     | > loss: 0.18882553279399872  (0.19408858698957107)
     | > align_error: 0.5646341145038605  (0.5862700123997298)

   --> STEP: 35
     | > decoder_loss: 0.4410257637500763  (0.44666992340769085)
     | > postnet_loss: 0.29830554127693176  (0.3073491207190922)
     | > stopnet_loss: 0.0035414020530879498  (0.005420557469395655)
     | > loss: 0.18837422132492065  (0.19392531939915247)
     | > align_error: 0.5344621539115906  (0.5847897878714973)

   --> STEP: 36
     | > decoder_loss: 0.44626298546791077  (0.4466586195760303)
     | > postnet_loss: 0.302214652299881  (0.3072064965963363)
     | > stopnet_loss: 0.003661633236333728  (0.0053716984629217125)
     | > loss: 0.19078104197978973  (0.19383797835972574)
     | > align_error: 0.6346179246902466  (0.5861739027831292)

   --> STEP: 37
     | > decoder_loss: 0.4390416145324707  (0.446452754574853)
     | > postnet_loss: 0.2990575134754181  (0.30698625380928446)
     | > stopnet_loss: 0.0035596219822764397  (0.005322723422904272)
     | > loss: 0.18808439373970032  (0.19368247607269803)
     | > align_error: 0.5200703144073486  (0.5843873193135135)

   --> STEP: 38
     | > decoder_loss: 0.42661041021347046  (0.44593058761797455)
     | > postnet_loss: 0.29193392395973206  (0.3065901398658752)
     | > stopnet_loss: 0.003162209177389741  (0.005265867784864416)
     | > loss: 0.18279829621315002  (0.19339605028692045)
     | > align_error: 0.5528925955295563  (0.5835585107928831)

   --> STEP: 39
     | > decoder_loss: 0.4412313401699066  (0.4458100940936651)
     | > postnet_loss: 0.30172213912010193  (0.3064653193339323)
     | > stopnet_loss: 0.0034425470512360334  (0.005219115971181638)
     | > loss: 0.1891809105873108  (0.19328796978180224)
     | > align_error: 0.5470271110534668  (0.5826218082354622)

   --> STEP: 40
     | > decoder_loss: 0.43863537907600403  (0.4456307262182236)
     | > postnet_loss: 0.3006613850593567  (0.3063202209770679)
     | > stopnet_loss: 0.0030293299350887537  (0.005164371320279316)
     | > loss: 0.18785353004932404  (0.19315210878849026)
     | > align_error: 0.5847947001457214  (0.5826761305332187)

   --> STEP: 41
     | > decoder_loss: 0.4292125403881073  (0.4452302826613915)
     | > postnet_loss: 0.29257088899612427  (0.30598487141655706)
     | > stopnet_loss: 0.003716875333338976  (0.00512906654011004)
     | > loss: 0.18416272103786469  (0.1929328554287189)
     | > align_error: 0.5038288831710815  (0.5807530269390202)

   --> STEP: 42
     | > decoder_loss: 0.43334171175956726  (0.44494722144944326)
     | > postnet_loss: 0.2944830656051636  (0.3057110188972382)
     | > stopnet_loss: 0.003295558039098978  (0.005085411575800253)
     | > loss: 0.18525175750255585  (0.19274997214476267)
     | > align_error: 0.5803499221801758  (0.5807434292066668)

   --> STEP: 43
     | > decoder_loss: 0.43346065282821655  (0.44468009194662406)
     | > postnet_loss: 0.29413580894470215  (0.3054418279681094)
     | > stopnet_loss: 0.0029278011061251163  (0.005035234588133389)
     | > loss: 0.18482691049575806  (0.1925657148971114)
     | > align_error: 0.5528690814971924  (0.5800951885622604)

   --> STEP: 44
     | > decoder_loss: 0.4507594108581543  (0.44481825828552246)
     | > postnet_loss: 0.30406010150909424  (0.3054104250940409)
     | > stopnet_loss: 0.0026730303652584553  (0.004981548128522595)
     | > loss: 0.1913779079914093  (0.19253871928561817)
     | > align_error: 0.5523256659507751  (0.579464063048363)

   --> STEP: 45
     | > decoder_loss: 0.44395628571510315  (0.44479910333951317)
     | > postnet_loss: 0.3032708764076233  (0.3053628795676761)
     | > stopnet_loss: 0.00327416998334229  (0.004943606391963033)
     | > loss: 0.19008097052574158  (0.1924841026465098)
     | > align_error: 0.5537292957305908  (0.5788921793301902)

   --> STEP: 46
     | > decoder_loss: 0.4342530369758606  (0.4445698410272598)
     | > postnet_loss: 0.2946811616420746  (0.3051306683084239)
     | > stopnet_loss: 0.003192467847838998  (0.004905538162742945)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35594413497231225 (+0.09680125568852271)
     | > avg_decoder_loss: 0.4406362722317378 (-0.0007374607252351728)
     | > avg_postnet_loss: 0.30216052947622357 (-0.0014087932579445184)
     | > avg_stopnet_loss: 0.0043524255143534965 (-3.893845926292768e-05)
     | > avg_loss: 0.19005162675272336 (-0.0005755015846454492)
     | > avg_align_error: 0.5721550461920827 (+0.0004384305441017533)


 > EPOCH: 110/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 13:05:48)

   --> TIME: 2025-12-28 13:06:09 -- STEP: 15/150 -- GLOBAL_STEP: 16625
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47190389037132263  (0.46870222290356955)
     | > postnet_loss: 0.3984510898590088  (0.3990540365378062)
     | > stopnet_loss: 0.008220593445003033  (0.011232980464895567)
     | > loss: 0.22580935060977936  (0.22817204693953197)
     | > align_error: 0.661986768245697  (0.6815400342146556)
     | > grad_norm: tensor(0.2433, device='cuda:0')  (tensor(0.3238, device='cuda:0'))
     | > step_time: 0.6184  (0.5668840408325195)
     | > loader_time: 0.8793  (0.7602799256642659)


   --> TIME: 2025-12-28 13:06:57 -- STEP: 40/150 -- GLOBAL_STEP: 16650
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4922352135181427  (0.47686261385679246)
     | > postnet_loss: 0.40738311409950256  (0.4014909088611603)
     | > stopnet_loss: 0.005045643541961908  (0.008162778103724124)
     | > loss: 0.2299502193927765  (0.2277511578053236)
     | > align_error: 0.620985209941864  (0.6547767385840416)
     | > grad_norm: tensor(0.3534, device='cuda:0')  (tensor(0.3016, device='cuda:0'))
     | > step_time: 1.1416  (0.77749662399292)
     | > loader_time: 1.0344  (0.9065590262413025)


   --> TIME: 2025-12-28 13:07:58 -- STEP: 65/150 -- GLOBAL_STEP: 16675
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48828521370887756  (0.48094174861907957)
     | > postnet_loss: 0.4003295302391052  (0.40161931147942176)
     | > stopnet_loss: 0.0039848024025559425  (0.006764189067941447)
     | > loss: 0.22613850235939026  (0.22740445343347696)
     | > align_error: 0.6617971062660217  (0.639257188485219)
     | > grad_norm: tensor(0.1266, device='cuda:0')  (tensor(0.2584, device='cuda:0'))
     | > step_time: 1.437  (0.9810050120720497)
     | > loader_time: 1.3405  (1.0055157661437988)


   --> TIME: 2025-12-28 13:09:16 -- STEP: 90/150 -- GLOBAL_STEP: 16700
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4860118329524994  (0.48266372879346214)
     | > postnet_loss: 0.39802321791648865  (0.40092451572418214)
     | > stopnet_loss: 0.003461036365479231  (0.005956742444282605)
     | > loss: 0.22446979582309723  (0.22685380280017853)
     | > align_error: 0.6652216911315918  (0.633335643013318)
     | > grad_norm: tensor(0.1781, device='cuda:0')  (tensor(0.2411, device='cuda:0'))
     | > step_time: 1.6162  (1.1352478981018066)
     | > loader_time: 2.2561  (1.1599417633480493)


   --> TIME: 2025-12-28 13:10:40 -- STEP: 115/150 -- GLOBAL_STEP: 16725
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4846740961074829  (0.48376012625901593)
     | > postnet_loss: 0.395220011472702  (0.4003965318202972)
     | > stopnet_loss: 0.0032804920338094234  (0.005426071519437044)
     | > loss: 0.2232540249824524  (0.22646523532660112)
     | > align_error: 0.6595674157142639  (0.6281849874102547)
     | > grad_norm: tensor(0.1476, device='cuda:0')  (tensor(0.2271, device='cuda:0'))
     | > step_time: 1.7515  (1.2637102666108504)
     | > loader_time: 1.5609  (1.261675745507945)


   --> TIME: 2025-12-28 13:12:14 -- STEP: 140/150 -- GLOBAL_STEP: 16750
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4973427653312683  (0.4848165914416313)
     | > postnet_loss: 0.4014633297920227  (0.39995204231568743)
     | > stopnet_loss: 0.0030383458361029625  (0.005022949154954404)
     | > loss: 0.2277398705482483  (0.22621510720678742)
     | > align_error: 0.5937483906745911  (0.6247380597250799)
     | > grad_norm: tensor(0.2911, device='cuda:0')  (tensor(0.2236, device='cuda:0'))
     | > step_time: 2.3479  (1.3944764358656747)
     | > loader_time: 2.107  (1.353328469821385)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.463626503944397  (0.463626503944397)
     | > postnet_loss: 0.336231529712677  (0.336231529712677)
     | > stopnet_loss: 0.01227144431322813  (0.01227144431322813)
     | > loss: 0.2122359573841095  (0.2122359573841095)
     | > align_error: 0.7183635830879211  (0.7183635830879211)

   --> STEP: 1
     | > decoder_loss: 0.4452521800994873  (0.4452521800994873)
     | > postnet_loss: 0.32505714893341064  (0.32505714893341064)
     | > stopnet_loss: 0.009674022905528545  (0.009674022905528545)
     | > loss: 0.2022513598203659  (0.2022513598203659)
     | > align_error: 0.6588287949562073  (0.6588287949562073)

   --> STEP: 2
     | > decoder_loss: 0.44113463163375854  (0.4431934058666229)
     | > postnet_loss: 0.3149186372756958  (0.3199878931045532)
     | > stopnet_loss: 0.01110856793820858  (0.010391295421868563)
     | > loss: 0.20012187957763672  (0.2011866196990013)
     | > align_error: 0.6552550792694092  (0.6570419371128082)

   --> STEP: 3
     | > decoder_loss: 0.4433717727661133  (0.4432528614997864)
     | > postnet_loss: 0.3135736584663391  (0.3178498148918152)
     | > stopnet_loss: 0.008376792073249817  (0.009719794305662314)
     | > loss: 0.19761314988136292  (0.19999546309312186)
     | > align_error: 0.7346576452255249  (0.6829138398170471)

   --> STEP: 4
     | > decoder_loss: 0.44997483491897583  (0.44493335485458374)
     | > postnet_loss: 0.32293233275413513  (0.31912044435739517)
     | > stopnet_loss: 0.008219726383686066  (0.009344777325168252)
     | > loss: 0.2014465034008026  (0.20035822317004204)
     | > align_error: 0.6029840111732483  (0.6629313826560974)

   --> STEP: 5
     | > decoder_loss: 0.4309644103050232  (0.44213956594467163)
     | > postnet_loss: 0.3041042685508728  (0.3161172091960907)
     | > stopnet_loss: 0.008210382424294949  (0.009117898344993592)
     | > loss: 0.19197754561901093  (0.1986820876598358)
     | > align_error: 0.6416705548763275  (0.6586792171001434)

   --> STEP: 6
     | > decoder_loss: 0.44740334153175354  (0.44301686187585193)
     | > postnet_loss: 0.31644028425216675  (0.31617105503877)
     | > stopnet_loss: 0.007279612589627504  (0.00881151738576591)
     | > loss: 0.19824053347110748  (0.19860849529504776)
     | > align_error: 0.5935365259647369  (0.647822101910909)

   --> STEP: 7
     | > decoder_loss: 0.45870479941368103  (0.44525799580982756)
     | > postnet_loss: 0.3156188428401947  (0.31609216758183073)
     | > stopnet_loss: 0.006277899257838726  (0.00844957193891917)
     | > loss: 0.19985881447792053  (0.19878711232117244)
     | > align_error: 0.5785354971885681  (0.6379240155220032)

   --> STEP: 8
     | > decoder_loss: 0.45281413197517395  (0.44620251283049583)
     | > postnet_loss: 0.31653571128845215  (0.3161476105451584)
     | > stopnet_loss: 0.007538659032434225  (0.008335707825608552)
     | > loss: 0.1998761147260666  (0.1989232376217842)
     | > align_error: 0.5749699473381042  (0.6300547569990158)

   --> STEP: 9
     | > decoder_loss: 0.4509425163269043  (0.4467291798856523)
     | > postnet_loss: 0.31661343574523926  (0.3161993689007229)
     | > stopnet_loss: 0.006665864493697882  (0.008150169677618477)
     | > loss: 0.1985548585653305  (0.19888230661551157)
     | > align_error: 0.5908425450325012  (0.6256978445582919)

   --> STEP: 10
     | > decoder_loss: 0.4756176173686981  (0.4496180236339569)
     | > postnet_loss: 0.3306393325328827  (0.3176433652639389)
     | > stopnet_loss: 0.005570909008383751  (0.007892243610695005)
     | > loss: 0.2071351408958435  (0.19970759004354477)
     | > align_error: 0.5828089416027069  (0.6214089542627335)

   --> STEP: 11
     | > decoder_loss: 0.4641023576259613  (0.4509347812695937)
     | > postnet_loss: 0.32090291380882263  (0.31793968785892834)
     | > stopnet_loss: 0.005925471894443035  (0.007713446181944825)
     | > loss: 0.2021767944097519  (0.19993206316774542)
     | > align_error: 0.5943653583526611  (0.618950445543636)

   --> STEP: 12
     | > decoder_loss: 0.4588507115840912  (0.45159444212913513)
     | > postnet_loss: 0.3139525055885315  (0.3176074226697286)
     | > stopnet_loss: 0.007868886925280094  (0.0077263995772227645)
     | > loss: 0.2010696828365326  (0.200026864806811)
     | > align_error: 0.5872460007667542  (0.6163084084788958)

   --> STEP: 13
     | > decoder_loss: 0.44843634963035583  (0.45135151193692136)
     | > postnet_loss: 0.3136308491230011  (0.3173015323969034)
     | > stopnet_loss: 0.005649174097925425  (0.0075666130018922)
     | > loss: 0.19616597890853882  (0.199729873583867)
     | > align_error: 0.5855547487735748  (0.6139427423477173)

   --> STEP: 14
     | > decoder_loss: 0.4594491720199585  (0.4519299162285669)
     | > postnet_loss: 0.3164757788181305  (0.3172425499984196)
     | > stopnet_loss: 0.004964785650372505  (0.0073807681910693645)
     | > loss: 0.198946014046669  (0.19967388361692429)
     | > align_error: 0.553963303565979  (0.6096584967204502)

   --> STEP: 15
     | > decoder_loss: 0.4569702446460724  (0.4522659381230672)
     | > postnet_loss: 0.3158678710460663  (0.3171509047349294)
     | > stopnet_loss: 0.005019487347453833  (0.007223349468161663)
     | > loss: 0.19822901487350464  (0.19957755903402966)
     | > align_error: 0.5882115960121155  (0.6082287033398946)

   --> STEP: 16
     | > decoder_loss: 0.45768973231315613  (0.4526049252599478)
     | > postnet_loss: 0.3096310496330261  (0.31668091379106045)
     | > stopnet_loss: 0.005257213022559881  (0.007100465940311551)
     | > loss: 0.19708740711212158  (0.1994219245389104)
     | > align_error: 0.6056541204452515  (0.6080677919089794)

   --> STEP: 17
     | > decoder_loss: 0.46486204862594604  (0.4533259325167712)
     | > postnet_loss: 0.3186866343021393  (0.3167988973505357)
     | > stopnet_loss: 0.004846245050430298  (0.006967864711495007)
     | > loss: 0.20073342323303223  (0.19949907152091756)
     | > align_error: 0.5580081939697266  (0.6051231096772587)

   --> STEP: 18
     | > decoder_loss: 0.4589560627937317  (0.4536387175321579)
     | > postnet_loss: 0.3110024631023407  (0.31647687322563595)
     | > stopnet_loss: 0.005297218449413776  (0.0068750510302682715)
     | > loss: 0.1977868378162384  (0.19940394742621315)
     | > align_error: 0.6037617921829224  (0.6050474809275733)

   --> STEP: 19
     | > decoder_loss: 0.4577794373035431  (0.4538566501517045)
     | > postnet_loss: 0.3109590411186218  (0.31618646100947734)
     | > stopnet_loss: 0.00479085510596633  (0.0067653565079365905)
     | > loss: 0.1969754844903946  (0.19927613358748586)
     | > align_error: 0.6001327037811279  (0.6047888084461814)

   --> STEP: 20
     | > decoder_loss: 0.4526819884777069  (0.4537979170680046)
     | > postnet_loss: 0.3063115179538727  (0.31569271385669706)
     | > stopnet_loss: 0.004533281549811363  (0.006653752760030329)
     | > loss: 0.1942816525697708  (0.1990264095366001)
     | > align_error: 0.622513085603714  (0.6056750223040581)

   --> STEP: 21
     | > decoder_loss: 0.45075035095214844  (0.45365279487201143)
     | > postnet_loss: 0.3061595857143402  (0.3152387553737277)
     | > stopnet_loss: 0.004015833139419556  (0.006528137540001245)
     | > loss: 0.19324332475662231  (0.19875102454707735)
     | > align_error: 0.5597986876964569  (0.6034904349417913)

   --> STEP: 22
     | > decoder_loss: 0.45008179545402527  (0.45349047671664844)
     | > postnet_loss: 0.3074682354927063  (0.3148855499245904)
     | > stopnet_loss: 0.0046022990718483925  (0.006440599427812479)
     | > loss: 0.1939897984266281  (0.19853460517796603)
     | > align_error: 0.6244032680988312  (0.6044410182671114)

   --> STEP: 23
     | > decoder_loss: 0.42548051476478577  (0.45227265228395874)
     | > postnet_loss: 0.2965567409992218  (0.3140886451887048)
     | > stopnet_loss: 0.004534929525107145  (0.006357744214651378)
     | > loss: 0.18504424393177032  (0.19794806773247925)
     | > align_error: 0.5669256448745728  (0.6028099150761314)

   --> STEP: 24
     | > decoder_loss: 0.459869384765625  (0.4525891828040282)
     | > postnet_loss: 0.31195080280303955  (0.3139995684226354)
     | > stopnet_loss: 0.004395589232444763  (0.006275987757059435)
     | > loss: 0.1973506361246109  (0.19792317474881807)
     | > align_error: 0.5789535939693451  (0.6018159016966819)

   --> STEP: 25
     | > decoder_loss: 0.45830217003822327  (0.452817702293396)
     | > postnet_loss: 0.30874863266944885  (0.31378953099250795)
     | > stopnet_loss: 0.0037212148308753967  (0.006173796840012073)
     | > loss: 0.19548392295837402  (0.1978256046772003)
     | > align_error: 0.557045042514801  (0.6000250673294066)

   --> STEP: 26
     | > decoder_loss: 0.43356889486312866  (0.452077363546078)
     | > postnet_loss: 0.29800736904144287  (0.3131825247636208)
     | > stopnet_loss: 0.004391171503812075  (0.006105234327081304)
     | > loss: 0.18728524446487427  (0.19742020620749548)
     | > align_error: 0.5463948249816895  (0.5979623657006483)

   --> STEP: 27
     | > decoder_loss: 0.4299868047237396  (0.4512591947008062)
     | > postnet_loss: 0.2925688326358795  (0.31241905468481557)
     | > stopnet_loss: 0.0036595663987100124  (0.006014654033437923)
     | > loss: 0.18429847061634064  (0.19693421600041566)
     | > align_error: 0.5401046276092529  (0.5958194865120782)

   --> STEP: 28
     | > decoder_loss: 0.4365898668766022  (0.4507352901356561)
     | > postnet_loss: 0.2978074252605438  (0.3118972107768059)
     | > stopnet_loss: 0.003962913993746042  (0.005941377603448927)
     | > loss: 0.1875622421503067  (0.19659950264862605)
     | > align_error: 0.5660220384597778  (0.5947552919387817)

   --> STEP: 29
     | > decoder_loss: 0.43150970339775085  (0.45007233886883175)
     | > postnet_loss: 0.29434436559677124  (0.3112919402533564)
     | > stopnet_loss: 0.0035847178660333157  (0.005860113474572527)
     | > loss: 0.18504822254180908  (0.1962011826449427)
     | > align_error: 0.5402319133281708  (0.5928751754349676)

   --> STEP: 30
     | > decoder_loss: 0.43205714225769043  (0.44947183231512705)
     | > postnet_loss: 0.29488345980644226  (0.3107449909051259)
     | > stopnet_loss: 0.0028296078089624643  (0.0057590966190521915)
     | > loss: 0.1845647692680359  (0.19581330219904583)
     | > align_error: 0.5329387784004211  (0.5908772955338161)

   --> STEP: 31
     | > decoder_loss: 0.428861141204834  (0.4488069713115692)
     | > postnet_loss: 0.29394295811653137  (0.31020298984742933)
     | > stopnet_loss: 0.0036952125374227762  (0.005692519713193178)
     | > loss: 0.18439623713493347  (0.19544500977762283)
     | > align_error: 0.5550996661186218  (0.5897231784559065)

   --> STEP: 32
     | > decoder_loss: 0.4400070011615753  (0.4485319722443819)
     | > postnet_loss: 0.29972708225250244  (0.30987561773508787)
     | > stopnet_loss: 0.0038693686947226524  (0.005635546243865974)
     | > loss: 0.18880288302898407  (0.19523744331672788)
     | > align_error: 0.5305027365684509  (0.5878725396469235)

   --> STEP: 33
     | > decoder_loss: 0.4371162950992584  (0.44818604263392364)
     | > postnet_loss: 0.29720059037208557  (0.30949152599681506)
     | > stopnet_loss: 0.0040253521874547005  (0.005586752484580784)
     | > loss: 0.18760457634925842  (0.19500614431771365)
     | > align_error: 0.5456400811672211  (0.5865927681778417)

   --> STEP: 34
     | > decoder_loss: 0.4427046775817871  (0.44802482601474314)
     | > postnet_loss: 0.29863327741622925  (0.3091721657444449)
     | > stopnet_loss: 0.0033255484886467457  (0.005520246484700371)
     | > loss: 0.18866004049777985  (0.19481949420536265)
     | > align_error: 0.5631589889526367  (0.5859035393771004)

   --> STEP: 35
     | > decoder_loss: 0.43943729996681213  (0.4477794681276594)
     | > postnet_loss: 0.2979341447353363  (0.3088510794298989)
     | > stopnet_loss: 0.003521538805216551  (0.0054631405510008335)
     | > loss: 0.18786439299583435  (0.19462077702794756)
     | > align_error: 0.5328715145587921  (0.5843883386680058)

   --> STEP: 36
     | > decoder_loss: 0.44648805260658264  (0.44774359547429615)
     | > postnet_loss: 0.30258700251579285  (0.308677077293396)
     | > stopnet_loss: 0.0036838811356574297  (0.005413716678352405)
     | > loss: 0.19095264375209808  (0.19451888443695176)
     | > align_error: 0.6335896253585815  (0.5857550410760773)

   --> STEP: 37
     | > decoder_loss: 0.4383228123188019  (0.44748897971333684)
     | > postnet_loss: 0.2990613281726837  (0.3084171921820254)
     | > stopnet_loss: 0.0035703913308680058  (0.005363897074366341)
     | > loss: 0.18791642785072327  (0.19434043966435097)
     | > align_error: 0.518386960029602  (0.5839342821288753)

   --> STEP: 38
     | > decoder_loss: 0.4263935387134552  (0.44693383652912944)
     | > postnet_loss: 0.2919600009918213  (0.3079841082033358)
     | > stopnet_loss: 0.0031665172427892685  (0.005306071289324839)
     | > loss: 0.18275488913059235  (0.19403555675556786)
     | > align_error: 0.55096036195755  (0.5830665473875246)

   --> STEP: 39
     | > decoder_loss: 0.44140028953552246  (0.4467919507087805)
     | > postnet_loss: 0.30237358808517456  (0.30784024871312654)
     | > stopnet_loss: 0.0034709814935922623  (0.0052590177048188755)
     | > loss: 0.18941445648670197  (0.1939170670050841)
     | > align_error: 0.5454124212265015  (0.5821010569731394)

   --> STEP: 40
     | > decoder_loss: 0.4386768341064453  (0.4465890727937222)
     | > postnet_loss: 0.3009471893310547  (0.30766792222857475)
     | > stopnet_loss: 0.003053890308365226  (0.005203889519907534)
     | > loss: 0.18795989453792572  (0.19376813769340512)
     | > align_error: 0.5834226310253143  (0.5821340963244438)

   --> STEP: 41
     | > decoder_loss: 0.4298357665538788  (0.4461804555683601)
     | > postnet_loss: 0.29333630204200745  (0.30731837051670724)
     | > stopnet_loss: 0.003738915082067251  (0.0051681584360577714)
     | > loss: 0.18453192710876465  (0.19354286426451145)
     | > align_error: 0.5027480125427246  (0.5801978503785482)

   --> STEP: 42
     | > decoder_loss: 0.4334684908390045  (0.4458777897414707)
     | > postnet_loss: 0.29470527172088623  (0.30701805864061626)
     | > stopnet_loss: 0.0032898166682571173  (0.0051234360130148985)
     | > loss: 0.185333251953125  (0.19334739730471656)
     | > align_error: 0.5790220499038696  (0.5801698551291511)

   --> STEP: 43
     | > decoder_loss: 0.43267807364463806  (0.4455708195996839)
     | > postnet_loss: 0.29381808638572693  (0.30671108254166535)
     | > stopnet_loss: 0.0029522827826440334  (0.005072944077424878)
     | > loss: 0.18457631766796112  (0.19314341870851295)
     | > align_error: 0.5512176752090454  (0.5794965486193813)

   --> STEP: 44
     | > decoder_loss: 0.4505680799484253  (0.4456843936985189)
     | > postnet_loss: 0.3042885363101959  (0.3066560246727683)
     | > stopnet_loss: 0.002670047339051962  (0.005018332787916403)
     | > loss: 0.1913841962814331  (0.19310343638062477)
     | > align_error: 0.5503058433532715  (0.578833123499697)

   --> STEP: 45
     | > decoder_loss: 0.4437513053417206  (0.445641436179479)
     | > postnet_loss: 0.3033779263496399  (0.3065831780433655)
     | > stopnet_loss: 0.0032738803420215845  (0.004979567178007629)
     | > loss: 0.19005617499351501  (0.19303571946091122)
     | > align_error: 0.5520815849304199  (0.5782386448648241)

   --> STEP: 46
     | > decoder_loss: 0.4342203736305237  (0.44539315221102344)
     | > postnet_loss: 0.2950032949447632  (0.30633144145426544)
     | > stopnet_loss: 0.0032132870983332396  (0.004941169784971229)
     | > loss: 0.18551920354366302  (0.19287231694097104)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3573475498141665 (+0.0014034148418542447)
     | > avg_decoder_loss: 0.4413002115307432 (+0.0006639392990054338)
     | > avg_postnet_loss: 0.3032683070861932 (+0.0011077776099696068)
     | > avg_stopnet_loss: 0.00437882332004268 (+2.6397805689183824e-05)
     | > avg_loss: 0.19052095214525858 (+0.0004693253925352192)
     | > avg_align_error: 0.5711151226000353 (-0.0010399235920474093)


 > EPOCH: 111/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 13:14:59)

   --> TIME: 2025-12-28 13:15:20 -- STEP: 14/150 -- GLOBAL_STEP: 16775
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47406625747680664  (0.47027143836021423)
     | > postnet_loss: 0.40058618783950806  (0.39995633917195456)
     | > stopnet_loss: 0.009151301346719265  (0.011339092094983374)
     | > loss: 0.22781440615653992  (0.2288960346153804)
     | > align_error: 0.6413464546203613  (0.6818095977817263)
     | > grad_norm: tensor(0.4363, device='cuda:0')  (tensor(0.3282, device='cuda:0'))
     | > step_time: 0.6011  (0.5420650243759156)
     | > loader_time: 1.0174  (0.8639727319989886)


   --> TIME: 2025-12-28 13:16:07 -- STEP: 39/150 -- GLOBAL_STEP: 16800
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4838584363460541  (0.47702901944136006)
     | > postnet_loss: 0.4020307958126068  (0.4015825597139505)
     | > stopnet_loss: 0.0050923945382237434  (0.008225669750036338)
     | > loss: 0.2265647053718567  (0.2278785648254248)
     | > align_error: 0.5914525091648102  (0.6552599592086594)
     | > grad_norm: tensor(0.2299, device='cuda:0')  (tensor(0.3127, device='cuda:0'))
     | > step_time: 1.1133  (0.7706238123086783)
     | > loader_time: 0.9834  (0.93397262157538)


   --> TIME: 2025-12-28 13:17:08 -- STEP: 64/150 -- GLOBAL_STEP: 16825
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.4870832562446594  (0.48131867684423923)
     | > postnet_loss: 0.4006260335445404  (0.4018528857268393)
     | > stopnet_loss: 0.004053767770528793  (0.006802364776376635)
     | > loss: 0.22598108649253845  (0.22759525594301522)
     | > align_error: 0.6135218441486359  (0.6388057093136011)
     | > grad_norm: tensor(0.1714, device='cuda:0')  (tensor(0.2723, device='cuda:0'))
     | > step_time: 1.4949  (0.9689072109758854)
     | > loader_time: 1.209  (1.0202515609562395)


   --> TIME: 2025-12-28 13:18:22 -- STEP: 89/150 -- GLOBAL_STEP: 16850
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48367926478385925  (0.48291401380903265)
     | > postnet_loss: 0.39559704065322876  (0.40110775593961223)
     | > stopnet_loss: 0.0035111831966787577  (0.005975121184869596)
     | > loss: 0.22333025932312012  (0.22698056413216539)
     | > align_error: 0.6580250263214111  (0.6332910730597677)
     | > grad_norm: tensor(0.2318, device='cuda:0')  (tensor(0.2471, device='cuda:0'))
     | > step_time: 1.7191  (1.1318231298682393)
     | > loader_time: 1.4817  (1.129644774319081)


   --> TIME: 2025-12-28 13:19:46 -- STEP: 114/150 -- GLOBAL_STEP: 16875
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48889899253845215  (0.48402545352776843)
     | > postnet_loss: 0.39803552627563477  (0.40056920574422467)
     | > stopnet_loss: 0.0033834679052233696  (0.005427272108040358)
     | > loss: 0.22511710226535797  (0.2265759374488864)
     | > align_error: 0.6095505952835083  (0.627998814509626)
     | > grad_norm: tensor(0.1759, device='cuda:0')  (tensor(0.2293, device='cuda:0'))
     | > step_time: 1.9763  (1.2695851995233904)
     | > loader_time: 2.0262  (1.2360211213429775)


   --> TIME: 2025-12-28 13:21:25 -- STEP: 139/150 -- GLOBAL_STEP: 16900
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4970698952674866  (0.48516924754321145)
     | > postnet_loss: 0.40229472517967224  (0.40019981252203735)
     | > stopnet_loss: 0.003155965358018875  (0.005026158173200039)
     | > loss: 0.22799710929393768  (0.22636842363172296)
     | > align_error: 0.6486160755157471  (0.624797248797451)
     | > grad_norm: tensor(0.1805, device='cuda:0')  (tensor(0.2313, device='cuda:0'))
     | > step_time: 2.121  (1.4008371246804436)
     | > loader_time: 2.2219  (1.3664905133007246)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.464974969625473  (0.464974969625473)
     | > postnet_loss: 0.33296999335289  (0.33296999335289)
     | > stopnet_loss: 0.012241970747709274  (0.012241970747709274)
     | > loss: 0.21172821521759033  (0.21172821521759033)
     | > align_error: 0.7201836109161377  (0.7201836109161377)

   --> STEP: 1
     | > decoder_loss: 0.44671034812927246  (0.44671034812927246)
     | > postnet_loss: 0.3202381432056427  (0.3202381432056427)
     | > stopnet_loss: 0.009571980684995651  (0.009571980684995651)
     | > loss: 0.20130909979343414  (0.20130909979343414)
     | > align_error: 0.6615433096885681  (0.6615433096885681)

   --> STEP: 2
     | > decoder_loss: 0.44404202699661255  (0.4453761875629425)
     | > postnet_loss: 0.3135078251361847  (0.3168729841709137)
     | > stopnet_loss: 0.010977023281157017  (0.010274501983076334)
     | > loss: 0.20036450028419495  (0.20083680003881454)
     | > align_error: 0.6581591069698334  (0.6598512083292007)

   --> STEP: 3
     | > decoder_loss: 0.44746851921081543  (0.44607363144556683)
     | > postnet_loss: 0.31209471821784973  (0.3152802288532257)
     | > stopnet_loss: 0.008465707302093506  (0.009671570422748724)
     | > loss: 0.1983565092086792  (0.20001003642876944)
     | > align_error: 0.7379048764705658  (0.6858690977096558)

   --> STEP: 4
     | > decoder_loss: 0.4520322382450104  (0.4475632831454277)
     | > postnet_loss: 0.3197454512119293  (0.3163965344429016)
     | > stopnet_loss: 0.008264467120170593  (0.009319794597104192)
     | > loss: 0.20120888948440552  (0.20030974969267845)
     | > align_error: 0.6070096790790558  (0.6661542430520058)

   --> STEP: 5
     | > decoder_loss: 0.43263500928878784  (0.44457762837409975)
     | > postnet_loss: 0.3018936216831207  (0.3134959518909454)
     | > stopnet_loss: 0.00814793724566698  (0.00908542312681675)
     | > loss: 0.19178010523319244  (0.19860382080078126)
     | > align_error: 0.6450439393520355  (0.6619321823120117)

   --> STEP: 6
     | > decoder_loss: 0.44794970750808716  (0.44513964156309765)
     | > postnet_loss: 0.31273871660232544  (0.3133697460095088)
     | > stopnet_loss: 0.007222120650112629  (0.00877487271403273)
     | > loss: 0.1973942220211029  (0.19840222100416818)
     | > align_error: 0.5973169207572937  (0.6511629720528921)

   --> STEP: 7
     | > decoder_loss: 0.4623505175113678  (0.44759833812713623)
     | > postnet_loss: 0.31459179520606995  (0.3135443244661604)
     | > stopnet_loss: 0.006259236950427294  (0.00841549617637481)
     | > loss: 0.20049481093883514  (0.19870116242340632)
     | > align_error: 0.581999659538269  (0.6412824988365173)

   --> STEP: 8
     | > decoder_loss: 0.45591142773628235  (0.4486374743282795)
     | > postnet_loss: 0.3142315745353699  (0.31363023072481155)
     | > stopnet_loss: 0.007501073647290468  (0.008301193360239267)
     | > loss: 0.20003683865070343  (0.19886812195181847)
     | > align_error: 0.5781755745410919  (0.6333941332995892)

   --> STEP: 9
     | > decoder_loss: 0.4533542990684509  (0.4491615659660763)
     | > postnet_loss: 0.31484657526016235  (0.31376538011762833)
     | > stopnet_loss: 0.006692006718367338  (0.00812239484447572)
     | > loss: 0.19874222576618195  (0.19885413348674774)
     | > align_error: 0.5953639149665833  (0.6291685534848107)

   --> STEP: 10
     | > decoder_loss: 0.4816816747188568  (0.45241357684135436)
     | > postnet_loss: 0.32964181900024414  (0.3153530240058899)
     | > stopnet_loss: 0.005822171922773123  (0.00789237255230546)
     | > loss: 0.2086530476808548  (0.19983402490615845)
     | > align_error: 0.5893680155277252  (0.6251884996891022)

   --> STEP: 11
     | > decoder_loss: 0.4648984372615814  (0.4535485641522841)
     | > postnet_loss: 0.3190348148345947  (0.31568773226304486)
     | > stopnet_loss: 0.0059159197844564915  (0.007712695027955554)
     | > loss: 0.20189924538135529  (0.20002177222208542)
     | > align_error: 0.5980456471443176  (0.6227209676395763)

   --> STEP: 12
     | > decoder_loss: 0.4609085023403168  (0.4541618923346202)
     | > postnet_loss: 0.31219959259033203  (0.3153970539569855)
     | > stopnet_loss: 0.007957042194902897  (0.007733057291867833)
     | > loss: 0.20123407244682312  (0.20012279724081358)
     | > align_error: 0.5911472737789154  (0.6200898264845213)

   --> STEP: 13
     | > decoder_loss: 0.45156142115592957  (0.4539618560901055)
     | > postnet_loss: 0.31216344237327576  (0.3151483146043924)
     | > stopnet_loss: 0.0056577385403215885  (0.007573417387902737)
     | > loss: 0.19658894836902618  (0.19985096271221453)
     | > align_error: 0.5893970131874084  (0.6177288408462818)

   --> STEP: 14
     | > decoder_loss: 0.4679861068725586  (0.45496358828885214)
     | > postnet_loss: 0.3186678886413574  (0.3153997127498899)
     | > stopnet_loss: 0.005284570157527924  (0.007409928300018821)
     | > loss: 0.20194807648658752  (0.20000075655324118)
     | > align_error: 0.5601078271865845  (0.6136130541563034)

   --> STEP: 15
     | > decoder_loss: 0.46295154094696045  (0.45549611846605936)
     | > postnet_loss: 0.31723320484161377  (0.3155219455560048)
     | > stopnet_loss: 0.0050617665983736515  (0.00725338418657581)
     | > loss: 0.20010794699192047  (0.20000790258248646)
     | > align_error: 0.5941919088363647  (0.6123183111349741)

   --> STEP: 16
     | > decoder_loss: 0.45860326290130615  (0.4556903149932623)
     | > postnet_loss: 0.3088023364543915  (0.315101969987154)
     | > stopnet_loss: 0.005272697191685438  (0.007129591249395162)
     | > loss: 0.19712410867214203  (0.19982766546308994)
     | > align_error: 0.609399676322937  (0.6121358964592218)

   --> STEP: 17
     | > decoder_loss: 0.464774489402771  (0.4562246781938216)
     | > postnet_loss: 0.31766149401664734  (0.31525253022418304)
     | > stopnet_loss: 0.004858571570366621  (0.00699600185651113)
     | > loss: 0.2004675716161728  (0.1998653070015066)
     | > align_error: 0.5618139505386353  (0.609175781993305)

   --> STEP: 18
     | > decoder_loss: 0.45786601305007935  (0.45631586346361375)
     | > postnet_loss: 0.30910801887512207  (0.3149111684825685)
     | > stopnet_loss: 0.005333644803613424  (0.006903648686905702)
     | > loss: 0.19707715511322021  (0.19971040967437956)
     | > align_error: 0.6068524122238159  (0.609046705895)

   --> STEP: 19
     | > decoder_loss: 0.46136221289634705  (0.45658146080217865)
     | > postnet_loss: 0.3114299774169922  (0.3147279479001698)
     | > stopnet_loss: 0.004934158641844988  (0.0067999913161130325)
     | > loss: 0.1981322169303894  (0.19962734689838008)
     | > align_error: 0.6029390692710876  (0.6087252513358468)

   --> STEP: 20
     | > decoder_loss: 0.4525342583656311  (0.45637910068035126)
     | > postnet_loss: 0.30569764971733093  (0.3142764329910278)
     | > stopnet_loss: 0.004524932708591223  (0.006686238385736942)
     | > loss: 0.19408290088176727  (0.19935012459754944)
     | > align_error: 0.62504443526268  (0.6095412105321885)

   --> STEP: 21
     | > decoder_loss: 0.4508252441883087  (0.4561146313235873)
     | > postnet_loss: 0.3043156862258911  (0.3138021117164975)
     | > stopnet_loss: 0.003990722354501486  (0.006557880479487635)
     | > loss: 0.19277594983577728  (0.19903706865651266)
     | > align_error: 0.5630192756652832  (0.607325880300431)

   --> STEP: 22
     | > decoder_loss: 0.4532425105571747  (0.4559840803796595)
     | > postnet_loss: 0.3073182702064514  (0.31350739164785907)
     | > stopnet_loss: 0.0050471872091293335  (0.006489212603562258)
     | > loss: 0.19518737494945526  (0.19886208257891916)
     | > align_error: 0.6285059452056885  (0.6082886105233972)

   --> STEP: 23
     | > decoder_loss: 0.4251803457736969  (0.4546447875707046)
     | > postnet_loss: 0.2951454818248749  (0.3127090477425119)
     | > stopnet_loss: 0.004481588955968618  (0.0064019246188842735)
     | > loss: 0.1845630407333374  (0.19824038510737213)
     | > align_error: 0.5700215697288513  (0.6066248261410256)

   --> STEP: 24
     | > decoder_loss: 0.4592755436897278  (0.45483773574233055)
     | > postnet_loss: 0.3107556402683258  (0.3126276557644208)
     | > stopnet_loss: 0.004408769775182009  (0.006318876500396679)
     | > loss: 0.1969165802001953  (0.19818522656957308)
     | > align_error: 0.5822915136814117  (0.605610938121875)

   --> STEP: 25
     | > decoder_loss: 0.45741090178489685  (0.4549406623840332)
     | > postnet_loss: 0.30728673934936523  (0.31241401910781863)
     | > stopnet_loss: 0.0036982691381126642  (0.006214052205905318)
     | > loss: 0.1948726922273636  (0.1980527251958847)
     | > align_error: 0.5600770115852356  (0.6037895810604095)

   --> STEP: 26
     | > decoder_loss: 0.4337044060230255  (0.45412388329322523)
     | > postnet_loss: 0.29591286182403564  (0.3117793592122885)
     | > stopnet_loss: 0.004373122472316027  (0.006143247216151884)
     | > loss: 0.18677742779254913  (0.19761905991114104)
     | > align_error: 0.5496243238449097  (0.6017063019367364)

   --> STEP: 27
     | > decoder_loss: 0.43135344982147217  (0.45328053390538253)
     | > postnet_loss: 0.29250654578208923  (0.31106555130746627)
     | > stopnet_loss: 0.00391624728217721  (0.006060765737115785)
     | > loss: 0.18488125503063202  (0.19714728936001105)
     | > align_error: 0.5439813733100891  (0.5995683416172309)

   --> STEP: 28
     | > decoder_loss: 0.43618243932724  (0.45266988767044886)
     | > postnet_loss: 0.29615235328674316  (0.31053293709244045)
     | > stopnet_loss: 0.003941392991691828  (0.005985073853350643)
     | > loss: 0.18702508509159088  (0.19678578206471034)
     | > align_error: 0.568815141916275  (0.5984700130564825)

   --> STEP: 29
     | > decoder_loss: 0.43130990862846375  (0.4519333366690011)
     | > postnet_loss: 0.292508602142334  (0.3099114083010575)
     | > stopnet_loss: 0.003620167262852192  (0.005903525350230007)
     | > loss: 0.18457479774951935  (0.1963647136400486)
     | > align_error: 0.5431995391845703  (0.5965641346471062)

   --> STEP: 30
     | > decoder_loss: 0.43196210265159607  (0.4512676288684209)
     | > postnet_loss: 0.29326093196868896  (0.30935639242331187)
     | > stopnet_loss: 0.0028099599294364452  (0.005800406502870222)
     | > loss: 0.1841157227754593  (0.19595641394456229)
     | > align_error: 0.536238431930542  (0.5945532778898873)

   --> STEP: 31
     | > decoder_loss: 0.4312465190887451  (0.45062178661746366)
     | > postnet_loss: 0.29399895668029785  (0.3088609912703114)
     | > stopnet_loss: 0.003949164878576994  (0.005740689031118827)
     | > loss: 0.18526053428649902  (0.19561138556849572)
     | > align_error: 0.5618010461330414  (0.5934967542848278)

   --> STEP: 32
     | > decoder_loss: 0.44042283296585083  (0.45030306931585073)
     | > postnet_loss: 0.2987560033798218  (0.3085452103987336)
     | > stopnet_loss: 0.003861387260258198  (0.005681960850779433)
     | > loss: 0.18865609169006348  (0.1953940326347947)
     | > align_error: 0.5342473387718201  (0.5916452100500463)

   --> STEP: 33
     | > decoder_loss: 0.43555915355682373  (0.44985628398981964)
     | > postnet_loss: 0.29586225748062134  (0.30816087849212415)
     | > stopnet_loss: 0.004021991044282913  (0.005631658735431053)
     | > loss: 0.18687734007835388  (0.1951359510421753)
     | > align_error: 0.5488558411598206  (0.5903485625079182)

   --> STEP: 34
     | > decoder_loss: 0.44050872325897217  (0.44958135573303)
     | > postnet_loss: 0.2970536947250366  (0.3078341966166216)
     | > stopnet_loss: 0.0033197856973856688  (0.0055636624696061895)
     | > loss: 0.18771038949489594  (0.19491755217313766)
     | > align_error: 0.5661336481571198  (0.5896363591446595)

   --> STEP: 35
     | > decoder_loss: 0.4386400878429413  (0.44926874807902745)
     | > postnet_loss: 0.2961547374725342  (0.30750049778393335)
     | > stopnet_loss: 0.003526952350512147  (0.005505470751917788)
     | > loss: 0.18722566962242126  (0.19469778410026006)
     | > align_error: 0.5358299016952515  (0.5880990317889622)

   --> STEP: 36
     | > decoder_loss: 0.445955365896225  (0.44917670968506074)
     | > postnet_loss: 0.3012615740299225  (0.30732719434632194)
     | > stopnet_loss: 0.0036697338800877333  (0.00545447806103362)
     | > loss: 0.19047397375106812  (0.19458045603500473)
     | > align_error: 0.636415421962738  (0.5894411537382337)

   --> STEP: 37
     | > decoder_loss: 0.4375569522380829  (0.44886266218649373)
     | > postnet_loss: 0.2972348928451538  (0.30705442944088496)
     | > stopnet_loss: 0.0036025880835950375  (0.005404426980562307)
     | > loss: 0.18730056285858154  (0.19438370216537165)
     | > align_error: 0.5219711065292358  (0.5876176389488013)

   --> STEP: 38
     | > decoder_loss: 0.42546889185905457  (0.4482470366515611)
     | > postnet_loss: 0.2904103994369507  (0.3066164286513078)
     | > stopnet_loss: 0.0031846219208091497  (0.005346011057937224)
     | > loss: 0.18215444684028625  (0.1940618796568168)
     | > align_error: 0.5542926788330078  (0.5867406663141751)

   --> STEP: 39
     | > decoder_loss: 0.4401410222053528  (0.44803919012729937)
     | > postnet_loss: 0.2999814748764038  (0.30644630163143843)
     | > stopnet_loss: 0.0035002853255718946  (0.0052986847571073435)
     | > loss: 0.18853090703487396  (0.19392005984599775)
     | > align_error: 0.5486997067928314  (0.5857652570956791)

   --> STEP: 40
     | > decoder_loss: 0.43765199184417725  (0.44777951017022133)
     | > postnet_loss: 0.29876211285591125  (0.30625419691205025)
     | > stopnet_loss: 0.003049973864108324  (0.005242466984782368)
     | > loss: 0.18715348839759827  (0.19375089555978778)
     | > align_error: 0.5865069627761841  (0.5857837997376917)

   --> STEP: 41
     | > decoder_loss: 0.4291585385799408  (0.447325340131434)
     | > postnet_loss: 0.29159417748451233  (0.3058966354625981)
     | > stopnet_loss: 0.003729725955054164  (0.00520557086210607)
     | > loss: 0.18391790986061096  (0.19351106664029566)
     | > align_error: 0.5061229467391968  (0.583840852103582)

   --> STEP: 42
     | > decoder_loss: 0.43292656540870667  (0.44698251216184526)
     | > postnet_loss: 0.29381704330444336  (0.3056090261254992)
     | > stopnet_loss: 0.003300794865936041  (0.00516021905267345)
     | > loss: 0.18498669564723969  (0.19330810542617524)
     | > align_error: 0.5820893347263336  (0.5837991493088857)

   --> STEP: 43
     | > decoder_loss: 0.4323575496673584  (0.44664239675499673)
     | > postnet_loss: 0.2928944528102875  (0.3053133383739826)
     | > stopnet_loss: 0.002939460100606084  (0.005108573495648628)
     | > loss: 0.18425247073173523  (0.1930975092704906)
     | > align_error: 0.5546935796737671  (0.583122275596441)

   --> STEP: 44
     | > decoder_loss: 0.45009517669677734  (0.44672086902640085)
     | > postnet_loss: 0.30290380120277405  (0.3052585761655461)
     | > stopnet_loss: 0.002669258276000619  (0.0050531345133839)
     | > loss: 0.19091899693012238  (0.19304799762639133)
     | > align_error: 0.5542164742946625  (0.5824653255668552)

   --> STEP: 45
     | > decoder_loss: 0.4426571726799011  (0.44663056466314527)
     | > postnet_loss: 0.3018452525138855  (0.3051827245288425)
     | > stopnet_loss: 0.003318085800856352  (0.005014577875327733)
     | > loss: 0.1894436925649643  (0.1929679019583596)
     | > align_error: 0.5554550588130951  (0.5818650974167716)

   --> STEP: 46
     | > decoder_loss: 0.43355920910835266  (0.4463464047597802)
     | > postnet_loss: 0.29324713349342346  (0.3049232551585073)
     | > stopnet_loss: 0.0032373135909438133  (0.00497594169523243)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.352314551671346 (-0.005032998142820488)
     | > avg_decoder_loss: 0.44195252205386304 (+0.0006523105231198145)
     | > avg_postnet_loss: 0.30145053339726996 (-0.0018177736889232188)
     | > avg_stopnet_loss: 0.0044120762066802745 (+3.325288663759418e-05)
     | > avg_loss: 0.19026284123008902 (-0.0002581109151695571)
     | > avg_align_error: 0.574695617863626 (+0.0035804952635907217)


 > EPOCH: 112/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 13:24:16)

   --> TIME: 2025-12-28 13:24:34 -- STEP: 13/150 -- GLOBAL_STEP: 16925
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.467739999294281  (0.4692485768061418)
     | > postnet_loss: 0.3960859179496765  (0.39970916280379665)
     | > stopnet_loss: 0.009282070212066174  (0.011690976886221996)
     | > loss: 0.22523854672908783  (0.22893041372299194)
     | > align_error: 0.6581597924232483  (0.6864020022062155)
     | > grad_norm: tensor(0.3157, device='cuda:0')  (tensor(0.2970, device='cuda:0'))
     | > step_time: 0.7007  (0.5259063977461594)
     | > loader_time: 0.8205  (0.7650584440964919)


   --> TIME: 2025-12-28 13:25:20 -- STEP: 38/150 -- GLOBAL_STEP: 16950
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.48929232358932495  (0.47674791671727834)
     | > postnet_loss: 0.4059453010559082  (0.40150970926410273)
     | > stopnet_loss: 0.0053428765386343  (0.008361316898739651)
     | > loss: 0.22915227711200714  (0.2279257244969669)
     | > align_error: 0.6091892123222351  (0.6576081067323686)
     | > grad_norm: tensor(0.3457, device='cuda:0')  (tensor(0.2663, device='cuda:0'))
     | > step_time: 1.1227  (0.7522839872460616)
     | > loader_time: 1.0031  (0.8979860857913369)


   --> TIME: 2025-12-28 13:26:21 -- STEP: 63/150 -- GLOBAL_STEP: 16975
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.49115052819252014  (0.48074009872618173)
     | > postnet_loss: 0.4034990668296814  (0.4015612616425469)
     | > stopnet_loss: 0.004205591045320034  (0.006883908754273775)
     | > loss: 0.227867990732193  (0.2274592492788557)
     | > align_error: 0.5677446722984314  (0.6398146218723721)
     | > grad_norm: tensor(0.1230, device='cuda:0')  (tensor(0.2474, device='cuda:0'))
     | > step_time: 1.4287  (0.959113185367887)
     | > loader_time: 1.2689  (1.0054289689139713)


   --> TIME: 2025-12-28 13:27:40 -- STEP: 88/150 -- GLOBAL_STEP: 17000
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48831304907798767  (0.48261228102174675)
     | > postnet_loss: 0.399631530046463  (0.4009593996134671)
     | > stopnet_loss: 0.0036561836022883654  (0.006034543285336854)
     | > loss: 0.22564232349395752  (0.22692746398123828)
     | > align_error: 0.6078714728355408  (0.633449313315478)
     | > grad_norm: tensor(0.1874, device='cuda:0')  (tensor(0.2363, device='cuda:0'))
     | > step_time: 1.5712  (1.135784517634999)
     | > loader_time: 1.8909  (1.1654155254364014)


   --> TIME: 2025-12-28 13:29:04 -- STEP: 113/150 -- GLOBAL_STEP: 17025
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4912624955177307  (0.48366278330836676)
     | > postnet_loss: 0.3999577760696411  (0.40035339187731783)
     | > stopnet_loss: 0.0034688657615333796  (0.00547706494643559)
     | > loss: 0.22627393901348114  (0.22648110933008447)
     | > align_error: 0.6107269823551178  (0.6286937995294554)
     | > grad_norm: tensor(0.1318, device='cuda:0')  (tensor(0.2277, device='cuda:0'))
     | > step_time: 1.8156  (1.26912502693919)
     | > loader_time: 1.6435  (1.2696471298690393)


   --> TIME: 2025-12-28 13:30:40 -- STEP: 138/150 -- GLOBAL_STEP: 17050
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49262502789497375  (0.48459655348805414)
     | > postnet_loss: 0.3992762863636017  (0.39981885707896686)
     | > stopnet_loss: 0.003247269429266453  (0.005064405453647824)
     | > loss: 0.22622260451316833  (0.22616825857456183)
     | > align_error: 0.5850915908813477  (0.6251397975113081)
     | > grad_norm: tensor(0.1264, device='cuda:0')  (tensor(0.2171, device='cuda:0'))
     | > step_time: 2.0047  (1.409441725067471)
     | > loader_time: 1.7567  (1.3619636366332788)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4617176949977875  (0.4617176949977875)
     | > postnet_loss: 0.3331886827945709  (0.3331886827945709)
     | > stopnet_loss: 0.012194325216114521  (0.012194325216114521)
     | > loss: 0.21092091500759125  (0.21092091500759125)
     | > align_error: 0.7187793850898743  (0.7187793850898743)

   --> STEP: 1
     | > decoder_loss: 0.44416385889053345  (0.44416385889053345)
     | > postnet_loss: 0.32144248485565186  (0.32144248485565186)
     | > stopnet_loss: 0.009626084007322788  (0.009626084007322788)
     | > loss: 0.20102767646312714  (0.20102767646312714)
     | > align_error: 0.6589468121528625  (0.6589468121528625)

   --> STEP: 2
     | > decoder_loss: 0.4395463466644287  (0.4418551027774811)
     | > postnet_loss: 0.31275808811187744  (0.31710028648376465)
     | > stopnet_loss: 0.011056404560804367  (0.010341244284063578)
     | > loss: 0.1991325169801712  (0.20008009672164917)
     | > align_error: 0.6555051505565643  (0.6572259813547134)

   --> STEP: 3
     | > decoder_loss: 0.44237425923347473  (0.44202815492947894)
     | > postnet_loss: 0.3109660744667053  (0.3150555491447449)
     | > stopnet_loss: 0.008394592441618443  (0.009692360336581865)
     | > loss: 0.19672968983650208  (0.19896329442660013)
     | > align_error: 0.7350016236305237  (0.6831511954466502)

   --> STEP: 4
     | > decoder_loss: 0.4476480185985565  (0.44343312084674835)
     | > postnet_loss: 0.31959599256515503  (0.3161906599998474)
     | > stopnet_loss: 0.008233612403273582  (0.009327673353254795)
     | > loss: 0.20004460215568542  (0.19923362135887146)
     | > align_error: 0.6031520962715149  (0.6631514206528664)

   --> STEP: 5
     | > decoder_loss: 0.42883291840553284  (0.4405130803585052)
     | > postnet_loss: 0.3019411563873291  (0.31334075927734373)
     | > stopnet_loss: 0.008194999769330025  (0.00910113863646984)
     | > loss: 0.19088850915431976  (0.19756459891796113)
     | > align_error: 0.6416375041007996  (0.658848637342453)

   --> STEP: 6
     | > decoder_loss: 0.44502896070480347  (0.4412657270828883)
     | > postnet_loss: 0.3136102259159088  (0.31338567038377124)
     | > stopnet_loss: 0.007282514590770006  (0.008798034628853202)
     | > loss: 0.1969423145055771  (0.19746088484923044)
     | > align_error: 0.5936081409454346  (0.6479752212762833)

   --> STEP: 7
     | > decoder_loss: 0.4556252658367157  (0.4433170897620065)
     | > postnet_loss: 0.3131099045276642  (0.31334627526147024)
     | > stopnet_loss: 0.006295423489063978  (0.008440518751740456)
     | > loss: 0.19847922027111053  (0.19760636133807047)
     | > align_error: 0.5787692666053772  (0.6380886563232967)

   --> STEP: 8
     | > decoder_loss: 0.45186617970466614  (0.44438572600483894)
     | > postnet_loss: 0.3143816888332367  (0.31347570195794106)
     | > stopnet_loss: 0.007040697615593672  (0.008265541109722108)
     | > loss: 0.19860266149044037  (0.1977308988571167)
     | > align_error: 0.5739943087100983  (0.6300768628716469)

   --> STEP: 9
     | > decoder_loss: 0.44859176874160767  (0.4448530640867021)
     | > postnet_loss: 0.3137584924697876  (0.313507123125924)
     | > stopnet_loss: 0.0066022565588355064  (0.008080731715179153)
     | > loss: 0.1971898227930069  (0.19767077929443783)
     | > align_error: 0.5910907983779907  (0.6257450779279073)

   --> STEP: 10
     | > decoder_loss: 0.47365033626556396  (0.4477327913045883)
     | > postnet_loss: 0.32796311378479004  (0.3149527221918106)
     | > stopnet_loss: 0.005612134002149105  (0.007833871943876147)
     | > loss: 0.20601549744606018  (0.19850525110960007)
     | > align_error: 0.5831443667411804  (0.6214850068092346)

   --> STEP: 11
     | > decoder_loss: 0.4618385136127472  (0.44901512969623913)
     | > postnet_loss: 0.31898146867752075  (0.3153189718723297)
     | > stopnet_loss: 0.005917019210755825  (0.007659612604501573)
     | > loss: 0.20112201571464539  (0.19874313880096783)
     | > align_error: 0.5947303473949432  (0.6190527650442991)

   --> STEP: 12
     | > decoder_loss: 0.4567195475101471  (0.4496571645140648)
     | > postnet_loss: 0.3114994764328003  (0.31500068058570224)
     | > stopnet_loss: 0.007874920964241028  (0.007677554967813194)
     | > loss: 0.19992966949939728  (0.1988420163591703)
     | > align_error: 0.5876630544662476  (0.6164369558294615)

   --> STEP: 13
     | > decoder_loss: 0.4467644691467285  (0.44943464948580814)
     | > postnet_loss: 0.31177037954330444  (0.3147521958901332)
     | > stopnet_loss: 0.0056259771808981895  (0.007519741291896655)
     | > loss: 0.195259690284729  (0.19856645281498247)
     | > align_error: 0.5862388014793396  (0.614114020879452)

   --> STEP: 14
     | > decoder_loss: 0.4582538902759552  (0.4500645952565329)
     | > postnet_loss: 0.3150571286678314  (0.3147739768028259)
     | > stopnet_loss: 0.004954152274876833  (0.0073364849335380965)
     | > loss: 0.1982819139957428  (0.19854612861360824)
     | > align_error: 0.5543957352638245  (0.6098484290497643)

   --> STEP: 15
     | > decoder_loss: 0.45491495728492737  (0.4503879527250926)
     | > postnet_loss: 0.314936101436615  (0.3147847851117452)
     | > stopnet_loss: 0.004971118178218603  (0.007178793816516797)
     | > loss: 0.19743388891220093  (0.19847197930018107)
     | > align_error: 0.5885698199272156  (0.6084298551082611)

   --> STEP: 16
     | > decoder_loss: 0.4544307291507721  (0.45064062625169754)
     | > postnet_loss: 0.3080005943775177  (0.314360773190856)
     | > stopnet_loss: 0.005281367339193821  (0.007060204661684111)
     | > loss: 0.1958892047405243  (0.19831055589020252)
     | > align_error: 0.606105387210846  (0.6082845758646727)

   --> STEP: 17
     | > decoder_loss: 0.46255555748939514  (0.4513415045597974)
     | > postnet_loss: 0.317558616399765  (0.31454888161490946)
     | > stopnet_loss: 0.004851441364735365  (0.00693027740892242)
     | > loss: 0.199879989027977  (0.1984028754865422)
     | > align_error: 0.5586850047111511  (0.6053669540321126)

   --> STEP: 18
     | > decoder_loss: 0.45647773146629333  (0.45162685049904716)
     | > postnet_loss: 0.3097268044948578  (0.31428098844157326)
     | > stopnet_loss: 0.0052878037095069885  (0.006839028870066007)
     | > loss: 0.19683894515037537  (0.19831599046786627)
     | > align_error: 0.6042776107788086  (0.6053064349624846)

   --> STEP: 19
     | > decoder_loss: 0.45568689703941345  (0.45184053715906647)
     | > postnet_loss: 0.30991220474243164  (0.3140510524574079)
     | > stopnet_loss: 0.004741349723190069  (0.006728624704440958)
     | > loss: 0.19614113867282867  (0.1982015245839169)
     | > align_error: 0.6002748012542725  (0.6050416121357366)

   --> STEP: 20
     | > decoder_loss: 0.4505174160003662  (0.45177438110113144)
     | > postnet_loss: 0.3056398928165436  (0.3136304944753647)
     | > stopnet_loss: 0.004517482593655586  (0.006618067598901689)
     | > loss: 0.1935568004846573  (0.19796928837895394)
     | > align_error: 0.6231765151023865  (0.605948357284069)

   --> STEP: 21
     | > decoder_loss: 0.44838300347328186  (0.4516128869283767)
     | > postnet_loss: 0.30463939905166626  (0.31320234707423616)
     | > stopnet_loss: 0.0039846510626375675  (0.0064926668114605405)
     | > loss: 0.19224025309085846  (0.1976964771747589)
     | > align_error: 0.5603803098201752  (0.6037784502619788)

   --> STEP: 22
     | > decoder_loss: 0.4506719410419464  (0.4515701166608117)
     | > postnet_loss: 0.3079199492931366  (0.31296223808418616)
     | > stopnet_loss: 0.004875727463513613  (0.006419169568372044)
     | > loss: 0.19452370703220367  (0.19755226035009732)
     | > align_error: 0.6256402730941772  (0.6047721694816243)

   --> STEP: 23
     | > decoder_loss: 0.423602819442749  (0.4503541472165481)
     | > postnet_loss: 0.2955746650695801  (0.3122062566487685)
     | > stopnet_loss: 0.004507885780185461  (0.006336070273233497)
     | > loss: 0.18430225551128387  (0.19697617318319238)
     | > align_error: 0.567568302154541  (0.6031546100326206)

   --> STEP: 24
     | > decoder_loss: 0.45792168378829956  (0.45066946124037105)
     | > postnet_loss: 0.31133222579956055  (0.31216983869671816)
     | > stopnet_loss: 0.0044268714264035225  (0.006256520321282248)
     | > loss: 0.19674034416675568  (0.19696634697417417)
     | > align_error: 0.5796796381473541  (0.6021764862040678)

   --> STEP: 25
     | > decoder_loss: 0.4560573995113373  (0.4508849787712097)
     | > postnet_loss: 0.30774742364883423  (0.31199294209480277)
     | > stopnet_loss: 0.003695862600579858  (0.006154094012454152)
     | > loss: 0.19464705884456635  (0.19687357544898987)
     | > align_error: 0.5577600598335266  (0.6003998291492462)

   --> STEP: 26
     | > decoder_loss: 0.43190571665763855  (0.45015500715145695)
     | > postnet_loss: 0.2969009578227997  (0.3114124811612642)
     | > stopnet_loss: 0.0043489388190209866  (0.006084664966552877)
     | > loss: 0.18655060231685638  (0.1964765380208309)
     | > align_error: 0.5469969511032104  (0.5983458723013217)

   --> STEP: 27
     | > decoder_loss: 0.4286007881164551  (0.4493567027427532)
     | > postnet_loss: 0.2921254634857178  (0.310698147173281)
     | > stopnet_loss: 0.003643675008788705  (0.005994257931080129)
     | > loss: 0.18382523953914642  (0.19600797141039814)
     | > align_error: 0.5406963527202606  (0.5962107049094306)

   --> STEP: 28
     | > decoder_loss: 0.4350849390029907  (0.44884699689490454)
     | > postnet_loss: 0.29688599705696106  (0.31020485609769816)
     | > stopnet_loss: 0.003952167462557554  (0.0059213261286328945)
     | > loss: 0.1869448870420456  (0.19568428982581412)
     | > align_error: 0.5666653513908386  (0.595155513712338)

   --> STEP: 29
     | > decoder_loss: 0.430582195520401  (0.4482171761578527)
     | > postnet_loss: 0.29356318712234497  (0.30963100544337563)
     | > stopnet_loss: 0.0035943430848419666  (0.005841085334019414)
     | > loss: 0.18463069200515747  (0.19530313128027424)
     | > align_error: 0.5409236550331116  (0.5932854496199509)

   --> STEP: 30
     | > decoder_loss: 0.43074166774749756  (0.44763465921084084)
     | > postnet_loss: 0.29411524534225464  (0.30911381344000494)
     | > stopnet_loss: 0.0028144291136413813  (0.0057401967933401465)
     | > loss: 0.18402865529060364  (0.19492731541395186)
     | > align_error: 0.5333953201770782  (0.5912891119718552)

   --> STEP: 31
     | > decoder_loss: 0.4283939599990845  (0.4470139914943326)
     | > postnet_loss: 0.2938050627708435  (0.3086199827732578)
     | > stopnet_loss: 0.00371158542111516  (0.0056747577168167595)
     | > loss: 0.18426133692264557  (0.19458325159165166)
     | > align_error: 0.5587310194969177  (0.5902388509242765)

   --> STEP: 32
     | > decoder_loss: 0.4388650357723236  (0.4467593366280198)
     | > postnet_loss: 0.2991425395011902  (0.30832381267100567)
     | > stopnet_loss: 0.003860244993120432  (0.00561805419420125)
     | > loss: 0.18836213648319244  (0.19438884174451232)
     | > align_error: 0.5315038561820984  (0.5884033823385835)

   --> STEP: 33
     | > decoder_loss: 0.4349084794521332  (0.44640021974390204)
     | > postnet_loss: 0.29650720953941345  (0.30796573378823017)
     | > stopnet_loss: 0.0040273647755384445  (0.005569851484544801)
     | > loss: 0.18688128888607025  (0.19416134014274133)
     | > align_error: 0.5462174415588379  (0.587125020496773)

   --> STEP: 34
     | > decoder_loss: 0.44073665142059326  (0.4462336442049812)
     | > postnet_loss: 0.29791688919067383  (0.30767017953536085)
     | > stopnet_loss: 0.0033222713973373175  (0.005503746187862228)
     | > loss: 0.18798565864562988  (0.19397970245164983)
     | > align_error: 0.5640451312065125  (0.58644620022353)

   --> STEP: 35
     | > decoder_loss: 0.4376501739025116  (0.4459884021963392)
     | > postnet_loss: 0.2971383035182953  (0.3073692687920161)
     | > stopnet_loss: 0.0035267272032797337  (0.005447259931159871)
     | > loss: 0.18722385168075562  (0.19378667814391)
     | > align_error: 0.533441960811615  (0.5849317933831896)

   --> STEP: 36
     | > decoder_loss: 0.44450685381889343  (0.4459472480747435)
     | > postnet_loss: 0.30192628502845764  (0.30721807479858393)
     | > stopnet_loss: 0.0036798291839659214  (0.005398164632626706)
     | > loss: 0.19028811156749725  (0.19368949573900968)
     | > align_error: 0.6341835260391235  (0.5862998970680766)

   --> STEP: 37
     | > decoder_loss: 0.43677836656570435  (0.4456994404663911)
     | > postnet_loss: 0.2982425093650818  (0.30697549194902984)
     | > stopnet_loss: 0.0035657770931720734  (0.005348640645073878)
     | > loss: 0.1873209923505783  (0.19351737402580882)
     | > align_error: 0.5192712545394897  (0.5844883121348716)

   --> STEP: 38
     | > decoder_loss: 0.424837201833725  (0.44515043418658407)
     | > postnet_loss: 0.2913804054260254  (0.30656509493526657)
     | > stopnet_loss: 0.003158796112984419  (0.005291013157387313)
     | > loss: 0.1822132021188736  (0.19321989581773158)
     | > align_error: 0.5519537031650543  (0.5836321382146132)

   --> STEP: 39
     | > decoder_loss: 0.44050756096839905  (0.44503138615534854)
     | > postnet_loss: 0.3016842305660248  (0.30643994456682444)
     | > stopnet_loss: 0.0034805506002157927  (0.005244591040536761)
     | > loss: 0.18902850151062012  (0.1931124241688313)
     | > align_error: 0.5460758805274963  (0.582669157248277)

   --> STEP: 40
     | > decoder_loss: 0.43718621134757996  (0.44483525678515434)
     | > postnet_loss: 0.3002806603908539  (0.3062859624624252)
     | > stopnet_loss: 0.003048030426725745  (0.005189677025191486)
     | > loss: 0.18741475045681  (0.19296998232603074)
     | > align_error: 0.5842896401882172  (0.5827096693217755)

   --> STEP: 41
     | > decoder_loss: 0.4281088411808014  (0.4444272954289506)
     | > postnet_loss: 0.2925499677658081  (0.3059509382015321)
     | > stopnet_loss: 0.003728712210431695  (0.005154043737026613)
     | > loss: 0.18389341235160828  (0.192748602570557)
     | > align_error: 0.5034795999526978  (0.5807772286054564)

   --> STEP: 42
     | > decoder_loss: 0.43297484517097473  (0.44415461804185596)
     | > postnet_loss: 0.2949330508708954  (0.3056886075508026)
     | > stopnet_loss: 0.00328789371997118  (0.005109611593763388)
     | > loss: 0.18526487052440643  (0.1925704184742201)
     | > align_error: 0.5799298286437988  (0.5807570524158931)

   --> STEP: 43
     | > decoder_loss: 0.4312095046043396  (0.4438535688921463)
     | > postnet_loss: 0.29344844818115234  (0.30540395268174103)
     | > stopnet_loss: 0.0029404801316559315  (0.005059166676039959)
     | > loss: 0.18410496413707733  (0.19237354744312374)
     | > align_error: 0.5520289838314056  (0.5800889577976492)

   --> STEP: 44
     | > decoder_loss: 0.44921037554740906  (0.4439753144979477)
     | > postnet_loss: 0.3037782311439514  (0.3053670044649731)
     | > stopnet_loss: 0.0026775894220918417  (0.00500503992026841)
     | > loss: 0.190924733877182  (0.19234061986207962)
     | > align_error: 0.5511237680912018  (0.5794306580315935)

   --> STEP: 45
     | > decoder_loss: 0.4429643452167511  (0.4439528485139211)
     | > postnet_loss: 0.3032285273075104  (0.3053194827503628)
     | > stopnet_loss: 0.0032857805490493774  (0.004966834156463543)
     | > loss: 0.18983399868011475  (0.19228491716914706)
     | > align_error: 0.5528969764709473  (0.5788410206635791)

   --> STEP: 46
     | > decoder_loss: 0.4325537085533142  (0.44370504112347314)
     | > postnet_loss: 0.29431039094924927  (0.3050801546677299)
     | > stopnet_loss: 0.003221246413886547  (0.004928886596842304)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3849063208608916 (+0.032591769189545594)
     | > avg_decoder_loss: 0.4398626811576612 (-0.0020898408962018444)
     | > avg_postnet_loss: 0.302113672097524 (+0.000663138700254029)
     | > avg_stopnet_loss: 0.004373481648861234 (-3.859455781904039e-05)
     | > avg_loss: 0.18986756986740863 (-0.0003952713626803883)
     | > avg_align_error: 0.571847706581607 (-0.002847911282019)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_17063.pth

 > EPOCH: 113/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 13:33:41)

   --> TIME: 2025-12-28 13:33:57 -- STEP: 12/150 -- GLOBAL_STEP: 17075
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48097795248031616  (0.46842202295859653)
     | > postnet_loss: 0.40782830119132996  (0.39875568449497223)
     | > stopnet_loss: 0.009666009806096554  (0.011999169519792)
     | > loss: 0.23186756670475006  (0.2287935974697272)
     | > align_error: 0.6687896251678467  (0.6884161780277888)
     | > grad_norm: tensor(0.4705, device='cuda:0')  (tensor(0.3173, device='cuda:0'))
     | > step_time: 0.627  (0.581258714199066)
     | > loader_time: 0.8473  (0.7244148651758829)


   --> TIME: 2025-12-28 13:34:44 -- STEP: 37/150 -- GLOBAL_STEP: 17100
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4858095943927765  (0.47619158915571264)
     | > postnet_loss: 0.40548020601272583  (0.4011469080641463)
     | > stopnet_loss: 0.005819038953632116  (0.008458879134441549)
     | > loss: 0.22864149510860443  (0.2277935038547258)
     | > align_error: 0.6240946650505066  (0.659026945764954)
     | > grad_norm: tensor(0.2935, device='cuda:0')  (tensor(0.3348, device='cuda:0'))
     | > step_time: 1.1789  (0.8143150162052464)
     | > loader_time: 1.0107  (0.8814159148448223)


   --> TIME: 2025-12-28 13:35:47 -- STEP: 62/150 -- GLOBAL_STEP: 17125
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.481302410364151  (0.4806478379234191)
     | > postnet_loss: 0.3957781195640564  (0.40148493166892757)
     | > stopnet_loss: 0.0038804500363767147  (0.00694640535831211)
     | > loss: 0.2231505960226059  (0.22747959869523202)
     | > align_error: 0.5783365666866302  (0.6410305403893993)
     | > grad_norm: tensor(0.1501, device='cuda:0')  (tensor(0.2846, device='cuda:0'))
     | > step_time: 1.4346  (1.0233294425472135)
     | > loader_time: 1.2171  (0.99601387593054)


   --> TIME: 2025-12-28 13:37:00 -- STEP: 87/150 -- GLOBAL_STEP: 17150
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4779002070426941  (0.4825190422178685)
     | > postnet_loss: 0.39104780554771423  (0.400833524849223)
     | > stopnet_loss: 0.0034877359867095947  (0.006072873158658716)
     | > loss: 0.22072473168373108  (0.22691101520911025)
     | > align_error: 0.6042365729808807  (0.6336270426881726)
     | > grad_norm: tensor(0.1353, device='cuda:0')  (tensor(0.2576, device='cuda:0'))
     | > step_time: 1.7115  (1.1712523109611421)
     | > loader_time: 1.486  (1.1038315652430744)


   --> TIME: 2025-12-28 13:38:28 -- STEP: 112/150 -- GLOBAL_STEP: 17175
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48148882389068604  (0.4835358592016356)
     | > postnet_loss: 0.39368709921836853  (0.40023601587329594)
     | > stopnet_loss: 0.0034540086053311825  (0.005496991243230046)
     | > loss: 0.22224800288677216  (0.22643996070006062)
     | > align_error: 0.638905942440033  (0.628751699413572)
     | > grad_norm: tensor(0.1221, device='cuda:0')  (tensor(0.2380, device='cuda:0'))
     | > step_time: 1.8926  (1.3128570509808404)
     | > loader_time: 1.5709  (1.2401082984038763)


   --> TIME: 2025-12-28 13:40:08 -- STEP: 137/150 -- GLOBAL_STEP: 17200
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4975646138191223  (0.48456936639590853)
     | > postnet_loss: 0.40293142199516296  (0.39976164154762767)
     | > stopnet_loss: 0.003233278403058648  (0.005081773196843311)
     | > loss: 0.22835728526115417  (0.22616452566028508)
     | > align_error: 0.5971638262271881  (0.6253673173215267)
     | > grad_norm: tensor(0.1965, device='cuda:0')  (tensor(0.2290, device='cuda:0'))
     | > step_time: 2.1126  (1.4421450830724118)
     | > loader_time: 2.0638  (1.373051625968766)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46131178736686707  (0.46131178736686707)
     | > postnet_loss: 0.33104628324508667  (0.33104628324508667)
     | > stopnet_loss: 0.012240421958267689  (0.012240421958267689)
     | > loss: 0.21032993495464325  (0.21032993495464325)
     | > align_error: 0.7186234593391418  (0.7186234593391418)

   --> STEP: 1
     | > decoder_loss: 0.4447699189186096  (0.4447699189186096)
     | > postnet_loss: 0.31936290860176086  (0.31936290860176086)
     | > stopnet_loss: 0.009591511450707912  (0.009591511450707912)
     | > loss: 0.2006247192621231  (0.2006247192621231)
     | > align_error: 0.6588748693466187  (0.6588748693466187)

   --> STEP: 2
     | > decoder_loss: 0.4387846887111664  (0.441777303814888)
     | > postnet_loss: 0.3110390305519104  (0.31520096957683563)
     | > stopnet_loss: 0.011091656982898712  (0.010341584216803312)
     | > loss: 0.1985475718975067  (0.1995861455798149)
     | > align_error: 0.6554312705993652  (0.6571530699729919)

   --> STEP: 3
     | > decoder_loss: 0.44256019592285156  (0.44203826785087585)
     | > postnet_loss: 0.3092314302921295  (0.3132111231486003)
     | > stopnet_loss: 0.008248694241046906  (0.00964395422488451)
     | > loss: 0.19619658589363098  (0.19845629235108694)
     | > align_error: 0.7346459627151489  (0.6829840342203776)

   --> STEP: 4
     | > decoder_loss: 0.44867679476737976  (0.44369789958000183)
     | > postnet_loss: 0.31843775510787964  (0.3145177811384201)
     | > stopnet_loss: 0.008177224546670914  (0.009277271805331111)
     | > loss: 0.19995585083961487  (0.19883118197321892)
     | > align_error: 0.6028956770896912  (0.662961944937706)

   --> STEP: 5
     | > decoder_loss: 0.4294930696487427  (0.44085693359375)
     | > postnet_loss: 0.30061957240104675  (0.3117381393909454)
     | > stopnet_loss: 0.008193940855562687  (0.009060605615377425)
     | > loss: 0.19072210788726807  (0.19720936715602874)
     | > align_error: 0.6418247520923615  (0.6587345063686371)

   --> STEP: 6
     | > decoder_loss: 0.44641387462615967  (0.4417830904324849)
     | > postnet_loss: 0.31257301568984985  (0.3118772854407628)
     | > stopnet_loss: 0.007269361522048712  (0.008762064933155974)
     | > loss: 0.19701609015464783  (0.19717715432246527)
     | > align_error: 0.5936456918716431  (0.6478863706191381)

   --> STEP: 7
     | > decoder_loss: 0.4566822946071625  (0.44391154817172457)
     | > postnet_loss: 0.31216245889663696  (0.31191802450588774)
     | > stopnet_loss: 0.006256832275539637  (0.008404174553496497)
     | > loss: 0.19846801459789276  (0.19736156293324061)
     | > align_error: 0.5789393484592438  (0.6380367960248675)

   --> STEP: 8
     | > decoder_loss: 0.4531681537628174  (0.4450686238706112)
     | > postnet_loss: 0.3131246268749237  (0.3120688498020172)
     | > stopnet_loss: 0.007132077123969793  (0.008245162374805659)
     | > loss: 0.1987052857875824  (0.19752952829003334)
     | > align_error: 0.574419379234314  (0.6300846189260483)

   --> STEP: 9
     | > decoder_loss: 0.4487926959991455  (0.44548240966267055)
     | > postnet_loss: 0.31248539686203003  (0.3121151328086853)
     | > stopnet_loss: 0.006653688848018646  (0.008068331982940435)
     | > loss: 0.19697320461273193  (0.19746771454811096)
     | > align_error: 0.5909129977226257  (0.6257322165701125)

   --> STEP: 10
     | > decoder_loss: 0.47521933913230896  (0.4484561026096344)
     | > postnet_loss: 0.3266367018222809  (0.3135672897100449)
     | > stopnet_loss: 0.005583563819527626  (0.007819855166599155)
     | > loss: 0.20604757964611053  (0.19832570105791092)
     | > align_error: 0.5829551815986633  (0.6214545130729675)

   --> STEP: 11
     | > decoder_loss: 0.463113397359848  (0.4497885839505629)
     | > postnet_loss: 0.3182355463504791  (0.31399167667735706)
     | > stopnet_loss: 0.0059055788442492485  (0.007645830046385527)
     | > loss: 0.2012428194284439  (0.1985908936370503)
     | > align_error: 0.5944926738739014  (0.6190034367821433)

   --> STEP: 12
     | > decoder_loss: 0.4576396346092224  (0.4504428381721179)
     | > postnet_loss: 0.3105672597885132  (0.31370630860328674)
     | > stopnet_loss: 0.007879221811890602  (0.007665279360177617)
     | > loss: 0.19993095099925995  (0.19870256508390108)
     | > align_error: 0.5874176323413849  (0.6163712864120802)

   --> STEP: 13
     | > decoder_loss: 0.4469853341579437  (0.4501768763248737)
     | > postnet_loss: 0.31028416752815247  (0.31344306698212254)
     | > stopnet_loss: 0.005584686528891325  (0.007505233757770979)
     | > loss: 0.19490206241607666  (0.19841021872483766)
     | > align_error: 0.5858231484889984  (0.6140214296487662)

   --> STEP: 14
     | > decoder_loss: 0.4578405022621155  (0.45072427817753385)
     | > postnet_loss: 0.313487708568573  (0.313446255666869)
     | > stopnet_loss: 0.004942580591887236  (0.007322187103064997)
     | > loss: 0.19777463376522064  (0.19836481979915074)
     | > align_error: 0.5541090965270996  (0.6097419772829328)

   --> STEP: 15
     | > decoder_loss: 0.4551238715648651  (0.45101758440335593)
     | > postnet_loss: 0.3139435350894928  (0.3134794076283773)
     | > stopnet_loss: 0.004970712121576071  (0.007165422104299069)
     | > loss: 0.19723756611347198  (0.19828966955343882)
     | > align_error: 0.5881620049476624  (0.6083033124605814)

   --> STEP: 16
     | > decoder_loss: 0.4561818540096283  (0.45134035125374794)
     | > postnet_loss: 0.3077378273010254  (0.3131205588579178)
     | > stopnet_loss: 0.005262494552880526  (0.0070464891323354095)
     | > loss: 0.19624242186546326  (0.19816171657294035)
     | > align_error: 0.605540931224823  (0.6081306636333466)

   --> STEP: 17
     | > decoder_loss: 0.4630698561668396  (0.45203032213098865)
     | > postnet_loss: 0.317137211561203  (0.31335683254634633)
     | > stopnet_loss: 0.004866252187639475  (0.006918239900294472)
     | > loss: 0.1999180167913437  (0.19826502835049348)
     | > align_error: 0.5580853819847107  (0.605186823536368)

   --> STEP: 18
     | > decoder_loss: 0.45714396238327026  (0.4523144132561154)
     | > postnet_loss: 0.3089272677898407  (0.31311074561542934)
     | > stopnet_loss: 0.005280477460473776  (0.006827253098082211)
     | > loss: 0.19679827988147736  (0.19818354232443702)
     | > align_error: 0.6037803888320923  (0.6051086882750193)

   --> STEP: 19
     | > decoder_loss: 0.45688778162002563  (0.4525551168542159)
     | > postnet_loss: 0.3092060983181  (0.31290523786293833)
     | > stopnet_loss: 0.004908768925815821  (0.006726280246910296)
     | > loss: 0.1964322328567505  (0.1980913681419272)
     | > align_error: 0.6000603437423706  (0.6048429859311957)

   --> STEP: 20
     | > decoder_loss: 0.4515140950679779  (0.452503065764904)
     | > postnet_loss: 0.3054027557373047  (0.3125301137566566)
     | > stopnet_loss: 0.0045153917744755745  (0.00661573582328856)
     | > loss: 0.19374461472034454  (0.1978740304708481)
     | > align_error: 0.6227877736091614  (0.605740225315094)

   --> STEP: 21
     | > decoder_loss: 0.448688268661499  (0.45232140875997995)
     | > postnet_loss: 0.3032330274581909  (0.3120873953614916)
     | > stopnet_loss: 0.003975712228566408  (0.006490020414016077)
     | > loss: 0.1919560432434082  (0.19759222155525571)
     | > align_error: 0.5597841143608093  (0.6035518390791756)

   --> STEP: 22
     | > decoder_loss: 0.45155975222587585  (0.4522867880084298)
     | > postnet_loss: 0.3071201741695404  (0.3118616125800393)
     | > stopnet_loss: 0.004869956057518721  (0.006416381125084378)
     | > loss: 0.19453993439674377  (0.1974534812298688)
     | > align_error: 0.625279575586319  (0.604539463465864)

   --> STEP: 23
     | > decoder_loss: 0.4240533113479614  (0.45105924554493115)
     | > postnet_loss: 0.294790655374527  (0.3111193970493648)
     | > stopnet_loss: 0.004515874199569225  (0.006333750389192415)
     | > loss: 0.184226855635643  (0.19687841055185898)
     | > align_error: 0.5670656859874725  (0.6029101687928904)

   --> STEP: 24
     | > decoder_loss: 0.4586668312549591  (0.451376228282849)
     | > postnet_loss: 0.31085845828056335  (0.31110852460066474)
     | > stopnet_loss: 0.0044190590269863605  (0.00625397158243383)
     | > loss: 0.1968003809452057  (0.19687515931824842)
     | > align_error: 0.5791133642196655  (0.601918635269006)

   --> STEP: 25
     | > decoder_loss: 0.4565991163253784  (0.45158514380455017)
     | > postnet_loss: 0.3070708215236664  (0.3109470164775848)
     | > stopnet_loss: 0.003708744654431939  (0.0061521625053137545)
     | > loss: 0.19462624192237854  (0.19678520262241364)
     | > align_error: 0.5570904314517975  (0.6001255071163176)

   --> STEP: 26
     | > decoder_loss: 0.4323272705078125  (0.45084445637006026)
     | > postnet_loss: 0.29572129249572754  (0.31036141170905185)
     | > stopnet_loss: 0.004357237368822098  (0.006083126923140998)
     | > loss: 0.1863693743944168  (0.19638459384441376)
     | > align_error: 0.546675056219101  (0.5980697205433477)

   --> STEP: 27
     | > decoder_loss: 0.42964062094688416  (0.45005912913216484)
     | > postnet_loss: 0.29180148243904114  (0.30967400692127367)
     | > stopnet_loss: 0.0039192624390125275  (0.006002983794099203)
     | > loss: 0.18427978456020355  (0.1959362675746282)
     | > align_error: 0.541085422039032  (0.5959591909691139)

   --> STEP: 28
     | > decoder_loss: 0.43541041016578674  (0.44953596059765133)
     | > postnet_loss: 0.2960449755191803  (0.30918725579977036)
     | > stopnet_loss: 0.003933246247470379  (0.005929064596005317)
     | > loss: 0.186797097325325  (0.19560986863715307)
     | > align_error: 0.5660414695739746  (0.5948907009192874)

   --> STEP: 29
     | > decoder_loss: 0.4309253990650177  (0.44889421709652605)
     | > postnet_loss: 0.292382150888443  (0.3086077694235177)
     | > stopnet_loss: 0.003591216867789626  (0.005848449157101327)
     | > loss: 0.18441809713840485  (0.19522394548202382)
     | > align_error: 0.5401663184165955  (0.5930036532467808)

   --> STEP: 30
     | > decoder_loss: 0.43058234453201294  (0.4482838213443756)
     | > postnet_loss: 0.2928923964500427  (0.3080839236577352)
     | > stopnet_loss: 0.0028263775166124105  (0.005747713435751697)
     | > loss: 0.18369506299495697  (0.1948396493991216)
     | > align_error: 0.5328652858734131  (0.5909990410010019)

   --> STEP: 31
     | > decoder_loss: 0.43124255537986755  (0.447734103087456)
     | > postnet_loss: 0.2942120432853699  (0.3076364436457234)
     | > stopnet_loss: 0.003958465531468391  (0.005689995761419977)
     | > loss: 0.185322105884552  (0.19453263186639355)
     | > align_error: 0.5586286187171936  (0.5899548338305565)

   --> STEP: 32
     | > decoder_loss: 0.43897292017936707  (0.4474603161215782)
     | > postnet_loss: 0.2980377674102783  (0.30733648501336575)
     | > stopnet_loss: 0.0038564482238143682  (0.005632697400869802)
     | > loss: 0.1881091296672821  (0.19433189742267132)
     | > align_error: 0.5308024287223816  (0.588106321170926)

   --> STEP: 33
     | > decoder_loss: 0.4354657530784607  (0.447096844514211)
     | > postnet_loss: 0.29593998193740845  (0.30699113643530646)
     | > stopnet_loss: 0.004028469789773226  (0.005584084442957785)
     | > loss: 0.18687990307807922  (0.19410607941222913)
     | > align_error: 0.5456721186637878  (0.5868204362464673)

   --> STEP: 34
     | > decoder_loss: 0.4413703978061676  (0.44692841961103325)
     | > postnet_loss: 0.29758042097091675  (0.3067143506863538)
     | > stopnet_loss: 0.00331764854490757  (0.005517424563603366)
     | > loss: 0.1880553662776947  (0.19392811726121342)
     | > align_error: 0.5636614561080933  (0.5861392897718092)

   --> STEP: 35
     | > decoder_loss: 0.4387356638908386  (0.44669434087617055)
     | > postnet_loss: 0.2964584231376648  (0.3064213241849627)
     | > stopnet_loss: 0.003543569939211011  (0.005461028717192156)
     | > loss: 0.1873420923948288  (0.19373994512217385)
     | > align_error: 0.5329404175281525  (0.584619321993419)

   --> STEP: 36
     | > decoder_loss: 0.44458967447280884  (0.4466358779205216)
     | > postnet_loss: 0.3008710741996765  (0.3062671505742603)
     | > stopnet_loss: 0.003680791240185499  (0.005411577676164193)
     | > loss: 0.19004598259925842  (0.19363733505209288)
     | > align_error: 0.6336419582366943  (0.5859810618890655)

   --> STEP: 37
     | > decoder_loss: 0.43746769428253174  (0.44638808917354894)
     | > postnet_loss: 0.2972998023033142  (0.30602478981018066)
     | > stopnet_loss: 0.0035651247017085552  (0.005361673541719446)
     | > loss: 0.18725699186325073  (0.19346489334428632)
     | > align_error: 0.5185903906822205  (0.5841596923969886)

   --> STEP: 38
     | > decoder_loss: 0.42476898431777954  (0.445819165361555)
     | > postnet_loss: 0.29030364751815796  (0.305611075539338)
     | > stopnet_loss: 0.0031560829374939203  (0.005303631683713512)
     | > loss: 0.1819242388010025  (0.19316119190893674)
     | > align_error: 0.5514111816883087  (0.5832978894836023)

   --> STEP: 39
     | > decoder_loss: 0.44029322266578674  (0.44567747452320194)
     | > postnet_loss: 0.3002724349498749  (0.3054741873190953)
     | > stopnet_loss: 0.003475278615951538  (0.005256750835822179)
     | > loss: 0.18861669301986694  (0.1930446662963965)
     | > align_error: 0.5454139113426208  (0.5823265054287052)

   --> STEP: 40
     | > decoder_loss: 0.4376707971096039  (0.445477307587862)
     | > postnet_loss: 0.2991284132003784  (0.3053155429661274)
     | > stopnet_loss: 0.0030515361577272415  (0.0052016204688698055)
     | > loss: 0.18725134432315826  (0.19289983324706556)
     | > align_error: 0.5836545526981354  (0.582359706610441)

   --> STEP: 41
     | > decoder_loss: 0.4284137487411499  (0.4450611232257471)
     | > postnet_loss: 0.29148346185684204  (0.3049781751341936)
     | > stopnet_loss: 0.003717056242749095  (0.005165411585305885)
     | > loss: 0.1836913526058197  (0.19267523615825466)
     | > align_error: 0.5029548704624176  (0.5804230032897575)

   --> STEP: 42
     | > decoder_loss: 0.4333406388759613  (0.4447820640745617)
     | > postnet_loss: 0.2942225933074951  (0.30472208985260557)
     | > stopnet_loss: 0.003281431272625923  (0.005120554911194458)
     | > loss: 0.18517224490642548  (0.1924965935094016)
     | > align_error: 0.5792266726493835  (0.5803945192268914)

   --> STEP: 43
     | > decoder_loss: 0.43179160356521606  (0.4444799603417862)
     | > postnet_loss: 0.2927464246749878  (0.30444358601126564)
     | > stopnet_loss: 0.002934250747784972  (0.0050697106283244696)
     | > loss: 0.18406875431537628  (0.19230059724907542)
     | > align_error: 0.551467776298523  (0.5797218042750689)

   --> STEP: 44
     | > decoder_loss: 0.44969499111175537  (0.44459848376837646)
     | > postnet_loss: 0.3027946650981903  (0.3044061105359685)
     | > stopnet_loss: 0.0026725511997938156  (0.005015229732221501)
     | > loss: 0.19079497456550598  (0.19226637855172157)
     | > align_error: 0.5503524243831635  (0.5790543183684348)

   --> STEP: 45
     | > decoder_loss: 0.44310829043388367  (0.4445653683609433)
     | > postnet_loss: 0.3022981286048889  (0.3043592664930556)
     | > stopnet_loss: 0.00329418433830142  (0.004976984279023277)
     | > loss: 0.18964578211307526  (0.1922081430753072)
     | > align_error: 0.552381306886673  (0.5784615847799512)

   --> STEP: 46
     | > decoder_loss: 0.43316423892974854  (0.4443175177211347)
     | > postnet_loss: 0.2931320071220398  (0.30411519563716394)
     | > stopnet_loss: 0.0032239726278930902  (0.004938875330085664)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3621350346189557 (-0.022771286241935917)
     | > avg_decoder_loss: 0.44036394222216174 (+0.0005012610645005466)
     | > avg_postnet_loss: 0.30086680524276965 (-0.001246866854754336)
     | > avg_stopnet_loss: 0.004382785265051732 (+9.3036161904975e-06)
     | > avg_loss: 0.18969047250169696 (-0.00017709736571167034)
     | > avg_align_error: 0.5713653866991851 (-0.00048231988242186663)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_17214.pth

 > EPOCH: 114/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 13:43:04)

   --> TIME: 2025-12-28 13:43:17 -- STEP: 11/150 -- GLOBAL_STEP: 17225
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47124186158180237  (0.46647918495264923)
     | > postnet_loss: 0.39976590871810913  (0.3976151807741685)
     | > stopnet_loss: 0.010410084389150143  (0.012017154727469791)
     | > loss: 0.2281620353460312  (0.22804074802181937)
     | > align_error: 0.6715754270553589  (0.6891836361451582)
     | > grad_norm: tensor(0.2955, device='cuda:0')  (tensor(0.3506, device='cuda:0'))
     | > step_time: 0.648  (0.5127866918390448)
     | > loader_time: 0.8708  (0.5959839604117654)


   --> TIME: 2025-12-28 13:44:03 -- STEP: 36/150 -- GLOBAL_STEP: 17250
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.48905235528945923  (0.4751136435402764)
     | > postnet_loss: 0.40641823410987854  (0.4004843077725834)
     | > stopnet_loss: 0.005360834300518036  (0.008508186968457367)
     | > loss: 0.22922849655151367  (0.2274076756503847)
     | > align_error: 0.6172482073307037  (0.6606950660546621)
     | > grad_norm: tensor(0.3127, device='cuda:0')  (tensor(0.3033, device='cuda:0'))
     | > step_time: 0.991  (0.7205087343851724)
     | > loader_time: 1.6142  (0.8688026865323385)


   --> TIME: 2025-12-28 13:45:04 -- STEP: 61/150 -- GLOBAL_STEP: 17275
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48958486318588257  (0.47989796468468965)
     | > postnet_loss: 0.40157732367515564  (0.4010842032119876)
     | > stopnet_loss: 0.004053083714097738  (0.006956334057890001)
     | > loss: 0.22684362530708313  (0.22720187584884832)
     | > align_error: 0.6041737198829651  (0.642438486462734)
     | > grad_norm: tensor(0.1742, device='cuda:0')  (tensor(0.2544, device='cuda:0'))
     | > step_time: 1.4353  (0.934178129571383)
     | > loader_time: 1.373  (1.0144479470174819)


   --> TIME: 2025-12-28 13:46:17 -- STEP: 86/150 -- GLOBAL_STEP: 17300
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48076480627059937  (0.48211302105770554)
     | > postnet_loss: 0.3948425352573395  (0.4006581195565157)
     | > stopnet_loss: 0.0036988279316574335  (0.0060845028479085414)
     | > loss: 0.22260066866874695  (0.22677728793648785)
     | > align_error: 0.5821108520030975  (0.6342893991359444)
     | > grad_norm: tensor(0.1046, device='cuda:0')  (tensor(0.2263, device='cuda:0'))
     | > step_time: 1.5909  (1.0934140321820278)
     | > loader_time: 1.5641  (1.1294134882993474)


   --> TIME: 2025-12-28 13:47:40 -- STEP: 111/150 -- GLOBAL_STEP: 17325
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47927314043045044  (0.4832021242326444)
     | > postnet_loss: 0.3917819559574127  (0.40006120382128535)
     | > stopnet_loss: 0.003267105668783188  (0.0055077856171641265)
     | > loss: 0.22103089094161987  (0.2263236172027416)
     | > align_error: 0.5806078612804413  (0.628857522934407)
     | > grad_norm: tensor(0.1654, device='cuda:0')  (tensor(0.2171, device='cuda:0'))
     | > step_time: 1.6876  (1.2312586865983566)
     | > loader_time: 1.6063  (1.2370880852948438)


   --> TIME: 2025-12-28 13:49:11 -- STEP: 136/150 -- GLOBAL_STEP: 17350
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49085524678230286  (0.48404065147042274)
     | > postnet_loss: 0.39855891466140747  (0.39944187968092804)
     | > stopnet_loss: 0.0032176380045711994  (0.005088934002046967)
     | > loss: 0.2255711853504181  (0.22595956691485994)
     | > align_error: 0.5984600484371185  (0.6257903505774107)
     | > grad_norm: tensor(0.2090, device='cuda:0')  (tensor(0.2152, device='cuda:0'))
     | > step_time: 2.0261  (1.3596090551684887)
     | > loader_time: 1.8325  (1.330014367313946)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46067342162132263  (0.46067342162132263)
     | > postnet_loss: 0.33331891894340515  (0.33331891894340515)
     | > stopnet_loss: 0.012235259637236595  (0.012235259637236595)
     | > loss: 0.2107333391904831  (0.2107333391904831)
     | > align_error: 0.7188190221786499  (0.7188190221786499)

   --> STEP: 1
     | > decoder_loss: 0.4435400366783142  (0.4435400366783142)
     | > postnet_loss: 0.3224593698978424  (0.3224593698978424)
     | > stopnet_loss: 0.009660637937486172  (0.009660637937486172)
     | > loss: 0.2011604905128479  (0.2011604905128479)
     | > align_error: 0.658998966217041  (0.658998966217041)

   --> STEP: 2
     | > decoder_loss: 0.4388445317745209  (0.44119228422641754)
     | > postnet_loss: 0.3126949369907379  (0.31757715344429016)
     | > stopnet_loss: 0.011078826151788235  (0.010369732044637203)
     | > loss: 0.1989636868238449  (0.2000620886683464)
     | > align_error: 0.6555832624435425  (0.6572911143302917)

   --> STEP: 3
     | > decoder_loss: 0.44224920868873596  (0.4415445923805237)
     | > postnet_loss: 0.3114561140537262  (0.31553680698076886)
     | > stopnet_loss: 0.008265269920229912  (0.009668244669834772)
     | > loss: 0.1966916024684906  (0.19893859326839447)
     | > align_error: 0.7344985604286194  (0.683026929696401)

   --> STEP: 4
     | > decoder_loss: 0.4472217857837677  (0.4429638907313347)
     | > postnet_loss: 0.31968697905540466  (0.3165743499994278)
     | > stopnet_loss: 0.008247548714280128  (0.009313070680946112)
     | > loss: 0.19997474551200867  (0.19919763132929802)
     | > align_error: 0.603088915348053  (0.663042426109314)

   --> STEP: 5
     | > decoder_loss: 0.4293273985385895  (0.44023659229278567)
     | > postnet_loss: 0.3023635447025299  (0.31373218894004823)
     | > stopnet_loss: 0.008199901320040226  (0.009090436808764934)
     | > loss: 0.1911226361989975  (0.19758263230323792)
     | > align_error: 0.6420596837997437  (0.6588458776473999)

   --> STEP: 6
     | > decoder_loss: 0.4447622299194336  (0.4409908652305603)
     | > postnet_loss: 0.3138926029205322  (0.3137589246034622)
     | > stopnet_loss: 0.007264392916113138  (0.008786096159989635)
     | > loss: 0.19692809879779816  (0.1974735433856646)
     | > align_error: 0.5936719179153442  (0.6479835510253906)

   --> STEP: 7
     | > decoder_loss: 0.455339640378952  (0.44304069025175913)
     | > postnet_loss: 0.31290391087532043  (0.31363677978515625)
     | > stopnet_loss: 0.0062599582597613335  (0.008425219317099877)
     | > loss: 0.19832085072994232  (0.19759458729199)
     | > align_error: 0.5786282420158386  (0.6380756497383118)

   --> STEP: 8
     | > decoder_loss: 0.45059826970100403  (0.44398538768291473)
     | > postnet_loss: 0.3139580190181732  (0.31367693468928337)
     | > stopnet_loss: 0.007294564042240381  (0.00828388740774244)
     | > loss: 0.19843363761901855  (0.19769946858286858)
     | > align_error: 0.5745887458324432  (0.6301397867500782)

   --> STEP: 9
     | > decoder_loss: 0.44716405868530273  (0.4443385733498467)
     | > postnet_loss: 0.31286805868148804  (0.3135870595773061)
     | > stopnet_loss: 0.006698340177536011  (0.00810771549327506)
     | > loss: 0.1967063695192337  (0.1975891242424647)
     | > align_error: 0.5907508730888367  (0.6257632407877181)

   --> STEP: 10
     | > decoder_loss: 0.4742761254310608  (0.4473323285579681)
     | > postnet_loss: 0.32828253507614136  (0.31505660712718964)
     | > stopnet_loss: 0.00555724510923028  (0.007852668454870582)
     | > loss: 0.20619690418243408  (0.19844990223646164)
     | > align_error: 0.582937628030777  (0.6214806795120239)

   --> STEP: 11
     | > decoder_loss: 0.46121272444725037  (0.44859418272972107)
     | > postnet_loss: 0.31817516684532166  (0.3153401125561107)
     | > stopnet_loss: 0.0058764684945344925  (0.007673013913021846)
     | > loss: 0.20072343945503235  (0.19865658743814987)
     | > align_error: 0.5943648219108582  (0.6190156015482816)

   --> STEP: 12
     | > decoder_loss: 0.4565995931625366  (0.44926130026578903)
     | > postnet_loss: 0.3116372227668762  (0.31503153840700787)
     | > stopnet_loss: 0.007839382626116276  (0.007686877972446382)
     | > loss: 0.1998985856771469  (0.19876008729139963)
     | > align_error: 0.5870973467826843  (0.6163557469844818)

   --> STEP: 13
     | > decoder_loss: 0.44650962948799133  (0.4490496332828815)
     | > postnet_loss: 0.3115614950656891  (0.3147646119961372)
     | > stopnet_loss: 0.005537037272006273  (0.007521505610874066)
     | > loss: 0.1950548142194748  (0.19847506628586695)
     | > align_error: 0.5855733752250671  (0.6139878722337576)

   --> STEP: 14
     | > decoder_loss: 0.45813286304473877  (0.44969843540872845)
     | > postnet_loss: 0.31457433104515076  (0.31475102049963816)
     | > stopnet_loss: 0.00493624247610569  (0.007336843958390611)
     | > loss: 0.19811305403709412  (0.19844920826809748)
     | > align_error: 0.5541311204433441  (0.6097123899630138)

   --> STEP: 15
     | > decoder_loss: 0.45542818307876587  (0.450080418586731)
     | > postnet_loss: 0.31435781717300415  (0.3147248069445292)
     | > stopnet_loss: 0.0050081657245755196  (0.007181598742802938)
     | > loss: 0.19745466113090515  (0.198382905125618)
     | > align_error: 0.5882313549518585  (0.6082803209622701)

   --> STEP: 16
     | > decoder_loss: 0.4560758173465729  (0.4504551310092211)
     | > postnet_loss: 0.308171808719635  (0.3143152445554733)
     | > stopnet_loss: 0.005245011765509844  (0.0070605620567221195)
     | > loss: 0.19630692899227142  (0.19825315661728382)
     | > align_error: 0.6054407358169556  (0.6081028468906879)

   --> STEP: 17
     | > decoder_loss: 0.4620988070964813  (0.4511400531320011)
     | > postnet_loss: 0.31633272767066956  (0.3144339200328378)
     | > stopnet_loss: 0.004859705921262503  (0.0069310999311068475)
     | > loss: 0.19946758449077606  (0.19832459355101867)
     | > align_error: 0.5581415891647339  (0.6051639493773965)

   --> STEP: 18
     | > decoder_loss: 0.45693960785865784  (0.45146225061681533)
     | > postnet_loss: 0.30911535024642944  (0.3141384439335929)
     | > stopnet_loss: 0.005250982008874416  (0.006837760046538379)
     | > loss: 0.1967647224664688  (0.19823793404632145)
     | > align_error: 0.6036573052406311  (0.605080246925354)

   --> STEP: 19
     | > decoder_loss: 0.453693687915802  (0.45157969468518305)
     | > postnet_loss: 0.3081037700176239  (0.31382082951696294)
     | > stopnet_loss: 0.004739445634186268  (0.006727322445888268)
     | > loss: 0.19518880546092987  (0.19807745359445872)
     | > align_error: 0.5995705127716064  (0.6047902609172621)

   --> STEP: 20
     | > decoder_loss: 0.4510801136493683  (0.45155471563339233)
     | > postnet_loss: 0.3051221966743469  (0.3133858978748322)
     | > stopnet_loss: 0.004510454833507538  (0.006616479065269232)
     | > loss: 0.19356104731559753  (0.19785163328051567)
     | > align_error: 0.6226295828819275  (0.6056822270154953)

   --> STEP: 21
     | > decoder_loss: 0.44872984290122986  (0.45142019788424176)
     | > postnet_loss: 0.304272323846817  (0.31295191815921236)
     | > stopnet_loss: 0.003971872851252556  (0.006490545436030342)
     | > loss: 0.19222241640090942  (0.19758357533386775)
     | > align_error: 0.5595422685146332  (0.6034850861345019)

   --> STEP: 22
     | > decoder_loss: 0.4516667127609253  (0.4514314031059092)
     | > postnet_loss: 0.30773618817329407  (0.3127148395234888)
     | > stopnet_loss: 0.004890895914286375  (0.00641783409413289)
     | > loss: 0.1947416067123413  (0.1974543949419802)
     | > align_error: 0.6252562999725342  (0.6044746867635035)

   --> STEP: 23
     | > decoder_loss: 0.4238359034061432  (0.4502315987711367)
     | > postnet_loss: 0.29506367444992065  (0.31194739756376844)
     | > stopnet_loss: 0.00451869610697031  (0.006335262877299734)
     | > loss: 0.1842436045408249  (0.1968800127506256)
     | > align_error: 0.5667730569839478  (0.6028354854687402)

   --> STEP: 24
     | > decoder_loss: 0.45888185501098633  (0.4505920261144638)
     | > postnet_loss: 0.31100115180015564  (0.31190797065695125)
     | > stopnet_loss: 0.004399652127176523  (0.006254612429377933)
     | > loss: 0.19687041640281677  (0.19687961290280023)
     | > align_error: 0.5790064632892609  (0.6018426095445952)

   --> STEP: 25
     | > decoder_loss: 0.4566599130630493  (0.4508347415924072)
     | > postnet_loss: 0.30737313628196716  (0.3117265772819519)
     | > stopnet_loss: 0.0036939193960279226  (0.006152184708043933)
     | > loss: 0.19470219314098358  (0.19679251611232756)
     | > align_error: 0.5569577515125275  (0.6000472152233125)

   --> STEP: 26
     | > decoder_loss: 0.43243294954299927  (0.4501269803597377)
     | > postnet_loss: 0.2966507077217102  (0.31114673614501953)
     | > stopnet_loss: 0.00436518806964159  (0.006083454068105381)
     | > loss: 0.18663610517978668  (0.19640188492261446)
     | > align_error: 0.5462875962257385  (0.5979795375695597)

   --> STEP: 27
     | > decoder_loss: 0.42986589670181274  (0.44937656985388863)
     | > postnet_loss: 0.29185596108436584  (0.31043226299462495)
     | > stopnet_loss: 0.003912463318556547  (0.006003047003307276)
     | > loss: 0.18434293568134308  (0.19595525717293774)
     | > align_error: 0.5405880510807037  (0.5958539269588613)

   --> STEP: 28
     | > decoder_loss: 0.43565109372138977  (0.44888637427772793)
     | > postnet_loss: 0.2964521050453186  (0.30993297163929256)
     | > stopnet_loss: 0.003930669277906418  (0.005929033513114389)
     | > loss: 0.1869564801454544  (0.19563387227909906)
     | > align_error: 0.5658562183380127  (0.5947825802224024)

   --> STEP: 29
     | > decoder_loss: 0.43126657605171204  (0.448278795028555)
     | > postnet_loss: 0.2933812737464905  (0.3093622234360925)
     | > stopnet_loss: 0.003595029003918171  (0.0058485505990041745)
     | > loss: 0.18475699424743652  (0.19525880751938657)
     | > align_error: 0.5399972796440125  (0.5928934319265958)

   --> STEP: 30
     | > decoder_loss: 0.43106314539909363  (0.4477049400409063)
     | > postnet_loss: 0.2936547100543976  (0.30883863965670266)
     | > stopnet_loss: 0.002843452151864767  (0.0057483806507661935)
     | > loss: 0.184022918343544  (0.1948842778801918)
     | > align_error: 0.532990038394928  (0.590896652142207)

   --> STEP: 31
     | > decoder_loss: 0.4308387339115143  (0.447160868875442)
     | > postnet_loss: 0.2941024601459503  (0.3083632790273236)
     | > stopnet_loss: 0.003955940715968609  (0.005690560007708207)
     | > loss: 0.18519124388694763  (0.1945715993642807)
     | > align_error: 0.5581980645656586  (0.5898418589945763)

   --> STEP: 32
     | > decoder_loss: 0.4389025568962097  (0.446902796626091)
     | > postnet_loss: 0.29831463098526  (0.3080492587760091)
     | > stopnet_loss: 0.0038588037714362144  (0.0056333176253247075)
     | > loss: 0.18816310167312622  (0.19437133381143212)
     | > align_error: 0.5305418372154236  (0.5879887333139778)

   --> STEP: 33
     | > decoder_loss: 0.4351770877838135  (0.44654747211571894)
     | > postnet_loss: 0.2956591248512268  (0.3076738001722278)
     | > stopnet_loss: 0.004039244260638952  (0.0055850123718493815)
     | > loss: 0.18674829602241516  (0.1941403326663104)
     | > align_error: 0.5455141663551331  (0.5867016252243159)

   --> STEP: 34
     | > decoder_loss: 0.4404875338077545  (0.4463692386360729)
     | > postnet_loss: 0.2969534695148468  (0.30735849632936363)
     | > stopnet_loss: 0.003316354239359498  (0.005518287132658502)
     | > loss: 0.18767660856246948  (0.1939502231338445)
     | > align_error: 0.5633678734302521  (0.5860153384068434)

   --> STEP: 35
     | > decoder_loss: 0.4382982552051544  (0.44613863910947527)
     | > postnet_loss: 0.2966625690460205  (0.3070528984069824)
     | > stopnet_loss: 0.0035394555889070034  (0.005461749088551317)
     | > loss: 0.18727965652942657  (0.1937596355165754)
     | > align_error: 0.5326508283615112  (0.5844906381198339)

   --> STEP: 36
     | > decoder_loss: 0.4446033239364624  (0.4460959914657805)
     | > postnet_loss: 0.30073046684265137  (0.3068772753079732)
     | > stopnet_loss: 0.003676255000755191  (0.0054121520305569805)
     | > loss: 0.1900096982717514  (0.19365547059310806)
     | > align_error: 0.6334220767021179  (0.5858498447471195)

   --> STEP: 37
     | > decoder_loss: 0.43754255771636963  (0.44586481758066127)
     | > postnet_loss: 0.29783302545547485  (0.3066328361227706)
     | > stopnet_loss: 0.003578628646209836  (0.005362597344493544)
     | > loss: 0.18742252886295319  (0.1934870127085093)
     | > align_error: 0.5184302628040314  (0.5840276938837928)

   --> STEP: 38
     | > decoder_loss: 0.4251275658607483  (0.4453191004301372)
     | > postnet_loss: 0.29052528738975525  (0.3062089532613754)
     | > stopnet_loss: 0.0031583458185195923  (0.005304590725388966)
     | > loss: 0.18207155168056488  (0.19318660583935285)
     | > align_error: 0.5511450171470642  (0.5831623602854579)

   --> STEP: 39
     | > decoder_loss: 0.44018790125846863  (0.4451875312206073)
     | > postnet_loss: 0.30079415440559387  (0.30607011226507336)
     | > stopnet_loss: 0.0034582247026264668  (0.005257248006856594)
     | > loss: 0.1887037456035614  (0.1930716607051018)
     | > align_error: 0.5450795888900757  (0.5821858789676276)

   --> STEP: 40
     | > decoder_loss: 0.437384694814682  (0.44499246031045914)
     | > postnet_loss: 0.29931533336639404  (0.30590124279260633)
     | > stopnet_loss: 0.003038055496290326  (0.005201768194092437)
     | > loss: 0.18721306324005127  (0.19292519576847553)
     | > align_error: 0.5832780003547668  (0.5822131820023061)

   --> STEP: 41
     | > decoder_loss: 0.4286326467990875  (0.44459344046871835)
     | > postnet_loss: 0.2919381260871887  (0.30556067897052297)
     | > stopnet_loss: 0.0037130662240087986  (0.005165458389944057)
     | > loss: 0.18385577201843262  (0.19270399031115742)
     | > align_error: 0.5024772882461548  (0.5802684041058146)

   --> STEP: 42
     | > decoder_loss: 0.4331781268119812  (0.4443216472864151)
     | > postnet_loss: 0.29387524724006653  (0.3052824544055121)
     | > stopnet_loss: 0.0032917067874222994  (0.0051208452565506815)
     | > loss: 0.18505506217479706  (0.1925218729745774)
     | > align_error: 0.5788852572441101  (0.5802354720376788)

   --> STEP: 43
     | > decoder_loss: 0.43222373723983765  (0.44404030054114585)
     | > postnet_loss: 0.2926958501338959  (0.3049897426782652)
     | > stopnet_loss: 0.002934196265414357  (0.0050699929544312326)
     | > loss: 0.18416409194469452  (0.19232750597388246)
     | > align_error: 0.5513167083263397  (0.579562942649043)

   --> STEP: 44
     | > decoder_loss: 0.4496198892593384  (0.44416710937565024)
     | > postnet_loss: 0.3030667304992676  (0.3049460378560152)
     | > stopnet_loss: 0.0026706194039434195  (0.005015461737374691)
     | > loss: 0.19084227085113525  (0.19229375063018364)
     | > align_error: 0.5501009225845337  (0.5788933512839405)

   --> STEP: 45
     | > decoder_loss: 0.4425258934497833  (0.44413063791063095)
     | > postnet_loss: 0.3019753396511078  (0.3048800223403506)
     | > stopnet_loss: 0.0033231808338314295  (0.00497785549507373)
     | > loss: 0.1894484907388687  (0.19223052263259888)
     | > align_error: 0.5521160662174225  (0.5782983005046846)

   --> STEP: 46
     | > decoder_loss: 0.4330941438674927  (0.4438907141270845)
     | > postnet_loss: 0.29350119829177856  (0.30463265660016425)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.36308154554078076 (+0.0009465109218250722)
     | > avg_decoder_loss: 0.4400581162084233 (-0.00030582601373846385)
     | > avg_postnet_loss: 0.3015563804091829 (+0.0006895751664132699)
     | > avg_stopnet_loss: 0.0043816341891546135 (-1.151075897118034e-06)
     | > avg_loss: 0.18978525946537653 (+9.478696367956618e-05)
     | > avg_align_error: 0.5711458731781354 (-0.0002195135210497634)


 > EPOCH: 115/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 13:52:04)

   --> TIME: 2025-12-28 13:52:16 -- STEP: 10/150 -- GLOBAL_STEP: 17375
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47188320755958557  (0.46648109555244444)
     | > postnet_loss: 0.39825963973999023  (0.39791599214076995)
     | > stopnet_loss: 0.009283693507313728  (0.012235266529023648)
     | > loss: 0.22681939601898193  (0.22833453714847565)
     | > align_error: 0.6525365710258484  (0.6915120899677276)
     | > grad_norm: tensor(0.2076, device='cuda:0')  (tensor(0.2809, device='cuda:0'))
     | > step_time: 0.6151  (0.4918236494064331)
     | > loader_time: 0.6506  (0.6497162818908692)


   --> TIME: 2025-12-28 13:53:01 -- STEP: 35/150 -- GLOBAL_STEP: 17400
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4915117919445038  (0.4751307938780103)
     | > postnet_loss: 0.40724989771842957  (0.40046998177255905)
     | > stopnet_loss: 0.005612853914499283  (0.008582962078175374)
     | > loss: 0.23030327260494232  (0.22748315504619054)
     | > align_error: 0.6109143495559692  (0.661230011497225)
     | > grad_norm: tensor(0.2546, device='cuda:0')  (tensor(0.2613, device='cuda:0'))
     | > step_time: 1.1498  (0.747509867804391)
     | > loader_time: 0.9604  (0.8559665748051235)


   --> TIME: 2025-12-28 13:54:00 -- STEP: 60/150 -- GLOBAL_STEP: 17425
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48479828238487244  (0.47978539069493614)
     | > postnet_loss: 0.3995222747325897  (0.4010026896993319)
     | > stopnet_loss: 0.004316436126828194  (0.006999668797167639)
     | > loss: 0.22539657354354858  (0.2271966889500618)
     | > align_error: 0.6244550049304962  (0.6427086894710858)
     | > grad_norm: tensor(0.1738, device='cuda:0')  (tensor(0.2447, device='cuda:0'))
     | > step_time: 1.4628  (0.9652048707008362)
     | > loader_time: 1.3089  (0.9545494318008423)


   --> TIME: 2025-12-28 13:55:12 -- STEP: 85/150 -- GLOBAL_STEP: 17450
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48520520329475403  (0.4820246843730702)
     | > postnet_loss: 0.3978497385978699  (0.4005725562572479)
     | > stopnet_loss: 0.003978564403951168  (0.006117567496702951)
     | > loss: 0.22474230825901031  (0.22676687731462367)
     | > align_error: 0.5855632424354553  (0.6342990009223712)
     | > grad_norm: tensor(0.1298, device='cuda:0')  (tensor(0.2234, device='cuda:0'))
     | > step_time: 1.7425  (1.1335935508503634)
     | > loader_time: 1.5131  (1.0706718332627239)


   --> TIME: 2025-12-28 13:56:38 -- STEP: 110/150 -- GLOBAL_STEP: 17475
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48885640501976013  (0.48309677893465214)
     | > postnet_loss: 0.39807724952697754  (0.3999647568572651)
     | > stopnet_loss: 0.003262864425778389  (0.005533251841552555)
     | > loss: 0.22499628365039825  (0.22629863511432302)
     | > align_error: 0.6031829714775085  (0.6287398313934153)
     | > grad_norm: tensor(0.1561, device='cuda:0')  (tensor(0.2215, device='cuda:0'))
     | > step_time: 1.8779  (1.2736897490241306)
     | > loader_time: 1.7465  (1.2090849529613148)


   --> TIME: 2025-12-28 13:58:14 -- STEP: 135/150 -- GLOBAL_STEP: 17500
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.491554319858551  (0.4838762634330326)
     | > postnet_loss: 0.3982671797275543  (0.3993160049120585)
     | > stopnet_loss: 0.0029539589304476976  (0.0051054955994779315)
     | > loss: 0.2254093438386917  (0.2259035627047221)
     | > align_error: 0.614313155412674  (0.6253602551089392)
     | > grad_norm: tensor(0.1584, device='cuda:0')  (tensor(0.2133, device='cuda:0'))
     | > step_time: 2.2682  (1.40549710061815)
     | > loader_time: 1.6415  (1.3287781061949553)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46137508749961853  (0.46137508749961853)
     | > postnet_loss: 0.33167755603790283  (0.33167755603790283)
     | > stopnet_loss: 0.012212859466671944  (0.012212859466671944)
     | > loss: 0.21047602593898773  (0.21047602593898773)
     | > align_error: 0.7186045050621033  (0.7186045050621033)

   --> STEP: 1
     | > decoder_loss: 0.4437664747238159  (0.4437664747238159)
     | > postnet_loss: 0.31935033202171326  (0.31935033202171326)
     | > stopnet_loss: 0.009658425115048885  (0.009658425115048885)
     | > loss: 0.20043763518333435  (0.20043763518333435)
     | > align_error: 0.6591295301914215  (0.6591295301914215)

   --> STEP: 2
     | > decoder_loss: 0.4393264055252075  (0.4415464401245117)
     | > postnet_loss: 0.3116132318973541  (0.3154817819595337)
     | > stopnet_loss: 0.010999980382621288  (0.010329202748835087)
     | > loss: 0.19873487949371338  (0.19958625733852386)
     | > align_error: 0.6555518209934235  (0.6573406755924225)

   --> STEP: 3
     | > decoder_loss: 0.4418823719024658  (0.44165841738382977)
     | > postnet_loss: 0.3093736469745636  (0.31344573696454364)
     | > stopnet_loss: 0.008252348750829697  (0.00963691808283329)
     | > loss: 0.19606634974479675  (0.1984129548072815)
     | > align_error: 0.7346000075340271  (0.683093786239624)

   --> STEP: 4
     | > decoder_loss: 0.4484950304031372  (0.4433675706386566)
     | > postnet_loss: 0.31829899549484253  (0.3146590515971184)
     | > stopnet_loss: 0.008233518339693546  (0.009286068147048354)
     | > loss: 0.1999320238828659  (0.1987927220761776)
     | > align_error: 0.6032984256744385  (0.6631449460983276)

   --> STEP: 5
     | > decoder_loss: 0.429579496383667  (0.4406099557876587)
     | > postnet_loss: 0.30119097232818604  (0.3119654357433319)
     | > stopnet_loss: 0.008198752999305725  (0.009068605117499828)
     | > loss: 0.19089137017726898  (0.19721245169639587)
     | > align_error: 0.6416884362697601  (0.6588536441326142)

   --> STEP: 6
     | > decoder_loss: 0.4452975392341614  (0.4413912196954091)
     | > postnet_loss: 0.3119402527809143  (0.31196123858292896)
     | > stopnet_loss: 0.007277839817106724  (0.008770144234100977)
     | > loss: 0.19658729434013367  (0.19710825880368552)
     | > align_error: 0.5936336517333984  (0.6479836453994116)

   --> STEP: 7
     | > decoder_loss: 0.45553988218307495  (0.44341245719364714)
     | > postnet_loss: 0.31174996495246887  (0.3119310566357204)
     | > stopnet_loss: 0.006256738677620888  (0.008411086297460965)
     | > loss: 0.1980792135000229  (0.19724696661744798)
     | > align_error: 0.5788283348083496  (0.6381043153149741)

   --> STEP: 8
     | > decoder_loss: 0.4524121582508087  (0.4445374198257923)
     | > postnet_loss: 0.31288737058639526  (0.31205059587955475)
     | > stopnet_loss: 0.007203999441117048  (0.008260200440417975)
     | > loss: 0.19852888584136963  (0.1974072065204382)
     | > align_error: 0.5744532942771912  (0.6301479376852512)

   --> STEP: 9
     | > decoder_loss: 0.4476923644542694  (0.44488796922895646)
     | > postnet_loss: 0.31193801760673523  (0.3120380871825748)
     | > stopnet_loss: 0.006634859833866358  (0.008079607039690018)
     | > loss: 0.19654245674610138  (0.19731112321217856)
     | > align_error: 0.5911422967910767  (0.6258139775858985)

   --> STEP: 10
     | > decoder_loss: 0.47465628385543823  (0.4478648006916046)
     | > postnet_loss: 0.32656097412109375  (0.3134903758764267)
     | > stopnet_loss: 0.005612593609839678  (0.007832905696704983)
     | > loss: 0.20591691136360168  (0.19817170202732087)
     | > align_error: 0.5832626819610596  (0.6215588480234147)

   --> STEP: 11
     | > decoder_loss: 0.46157246828079224  (0.44911095229062165)
     | > postnet_loss: 0.31755340099334717  (0.31385974179614673)
     | > stopnet_loss: 0.00587090291082859  (0.007654541807079857)
     | > loss: 0.2006523758172989  (0.19839721782640976)
     | > align_error: 0.5947051644325256  (0.6191176040606066)

   --> STEP: 12
     | > decoder_loss: 0.4573359787464142  (0.4497963711619377)
     | > postnet_loss: 0.31041282415390015  (0.3135724986592929)
     | > stopnet_loss: 0.007884273305535316  (0.007673686098617812)
     | > loss: 0.19982148706912994  (0.1985159069299698)
     | > align_error: 0.5873584151268005  (0.6164710049827894)

   --> STEP: 13
     | > decoder_loss: 0.44677743315696716  (0.44956414516155535)
     | > postnet_loss: 0.3103714883327484  (0.31332626709571254)
     | > stopnet_loss: 0.0054042465053498745  (0.007499113822212586)
     | > loss: 0.1946914792060852  (0.19822172018197867)
     | > align_error: 0.585491269826889  (0.6140879484323355)

   --> STEP: 14
     | > decoder_loss: 0.4586125612258911  (0.4502104605947222)
     | > postnet_loss: 0.31399253010749817  (0.31337385731084005)
     | > stopnet_loss: 0.0049256980419158936  (0.007315298409334251)
     | > loss: 0.19807696342468262  (0.19821138041360037)
     | > align_error: 0.5542525053024292  (0.6098139882087708)

   --> STEP: 15
     | > decoder_loss: 0.45541152358055115  (0.4505571981271108)
     | > postnet_loss: 0.31379222869873047  (0.3134017487366994)
     | > stopnet_loss: 0.004981295205652714  (0.007159698195755482)
     | > loss: 0.19728223979473114  (0.19814943770567575)
     | > align_error: 0.5883477926254272  (0.6083829085032145)

   --> STEP: 16
     | > decoder_loss: 0.45627179741859436  (0.4509143605828285)
     | > postnet_loss: 0.30766916275024414  (0.31304346211254597)
     | > stopnet_loss: 0.005266192834824324  (0.007041354110697284)
     | > loss: 0.19625142216682434  (0.19803081173449755)
     | > align_error: 0.6061227917671204  (0.6082416512072086)

   --> STEP: 17
     | > decoder_loss: 0.462775856256485  (0.45161209562245536)
     | > postnet_loss: 0.31651803851127625  (0.3132478489595301)
     | > stopnet_loss: 0.004853095393627882  (0.006912633009693202)
     | > loss: 0.19967657327651978  (0.19812762123696945)
     | > align_error: 0.5585821568965912  (0.6053205044830546)

   --> STEP: 18
     | > decoder_loss: 0.45636746287345886  (0.45187628269195557)
     | > postnet_loss: 0.30837011337280273  (0.31297686364915633)
     | > stopnet_loss: 0.005228414200246334  (0.006819065298057265)
     | > loss: 0.1964128166437149  (0.19803235431512198)
     | > align_error: 0.6037400364875793  (0.6052327007055283)

   --> STEP: 19
     | > decoder_loss: 0.45600634813308716  (0.4520936545572783)
     | > postnet_loss: 0.3086185157299042  (0.3127474769165641)
     | > stopnet_loss: 0.004763532895594835  (0.0067108793821381895)
     | > loss: 0.19591973721981049  (0.19792116394168452)
     | > align_error: 0.5998823344707489  (0.6049511024826452)

   --> STEP: 20
     | > decoder_loss: 0.45121708512306213  (0.4520498260855675)
     | > postnet_loss: 0.30480343103408813  (0.31235027462244036)
     | > stopnet_loss: 0.004527104552835226  (0.006601690640673041)
     | > loss: 0.19353224337100983  (0.19770171791315078)
     | > align_error: 0.6228780150413513  (0.6058474481105804)

   --> STEP: 21
     | > decoder_loss: 0.44953644275665283  (0.45193014116514296)
     | > postnet_loss: 0.3035354018211365  (0.3119305187747592)
     | > stopnet_loss: 0.003977591171860695  (0.006476733523110549)
     | > loss: 0.19224555790424347  (0.19744190076986948)
     | > align_error: 0.5601979494094849  (0.6036736624581474)

   --> STEP: 22
     | > decoder_loss: 0.45218148827552795  (0.4519415660337968)
     | > postnet_loss: 0.3071521520614624  (0.31171332028779114)
     | > stopnet_loss: 0.00499922689050436  (0.006409574130719358)
     | > loss: 0.19483262300491333  (0.19732329723509875)
     | > align_error: 0.6255125403404236  (0.6046663387255236)

   --> STEP: 23
     | > decoder_loss: 0.4239959716796875  (0.45072654019231384)
     | > postnet_loss: 0.29437488317489624  (0.31095947519592615)
     | > stopnet_loss: 0.0045127226039767265  (0.006327102325208809)
     | > loss: 0.18410544097423553  (0.19674860783245252)
     | > align_error: 0.5670152604579926  (0.6030293353225874)

   --> STEP: 24
     | > decoder_loss: 0.4578915536403656  (0.451025082419316)
     | > postnet_loss: 0.3098292648792267  (0.310912383099397)
     | > stopnet_loss: 0.004399826284497976  (0.006246799156845857)
     | > loss: 0.1963300257921219  (0.19673116691410542)
     | > align_error: 0.5794649124145508  (0.6020474843680859)

   --> STEP: 25
     | > decoder_loss: 0.456249862909317  (0.451234073638916)
     | > postnet_loss: 0.30645066499710083  (0.3107339143753052)
     | > stopnet_loss: 0.0036901182029396296  (0.006144531918689609)
     | > loss: 0.1943652629852295  (0.19663653075695037)
     | > align_error: 0.5572791993618011  (0.6002567529678344)

   --> STEP: 26
     | > decoder_loss: 0.4330432713031769  (0.45053442739523375)
     | > postnet_loss: 0.2955763339996338  (0.31015093051470244)
     | > stopnet_loss: 0.004378849174827337  (0.006076621043925675)
     | > loss: 0.18653374910354614  (0.19624796223181945)
     | > align_error: 0.5466867387294769  (0.5981963678048207)

   --> STEP: 27
     | > decoder_loss: 0.4300024211406708  (0.4497739827191388)
     | > postnet_loss: 0.2914266586303711  (0.3094574389634309)
     | > stopnet_loss: 0.003913607448339462  (0.005996509429274334)
     | > loss: 0.18427088856697083  (0.1958043669108991)
     | > align_error: 0.5410417914390564  (0.5960795316431258)

   --> STEP: 28
     | > decoder_loss: 0.4353085160255432  (0.44925735890865326)
     | > postnet_loss: 0.29537487030029297  (0.30895449008260456)
     | > stopnet_loss: 0.003945358097553253  (0.005923254024570009)
     | > loss: 0.1866162121295929  (0.19547621852585248)
     | > align_error: 0.566015899181366  (0.5950058304837772)

   --> STEP: 29
     | > decoder_loss: 0.43108049035072327  (0.44863057033769016)
     | > postnet_loss: 0.29230523109436035  (0.3083803777036996)
     | > stopnet_loss: 0.003598627168685198  (0.005843094477815361)
     | > loss: 0.18444505333900452  (0.19509583351940946)
     | > align_error: 0.5403206050395966  (0.5931201330546675)

   --> STEP: 30
     | > decoder_loss: 0.43092864751815796  (0.4480405062437057)
     | > postnet_loss: 0.29262518882751465  (0.30785520474116007)
     | > stopnet_loss: 0.002835692837834358  (0.005742847756482661)
     | > loss: 0.18372415006160736  (0.19471677740414936)
     | > align_error: 0.533147931098938  (0.5911210596561431)

   --> STEP: 31
     | > decoder_loss: 0.4305782914161682  (0.4474772089912045)
     | > postnet_loss: 0.2932879328727722  (0.3073852927454056)
     | > stopnet_loss: 0.00395597517490387  (0.00568520670546399)
     | > loss: 0.18492253124713898  (0.19440083397972968)
     | > align_error: 0.5589522123336792  (0.5900833549038056)

   --> STEP: 32
     | > decoder_loss: 0.4393292963504791  (0.44722258672118187)
     | > postnet_loss: 0.29770874977111816  (0.30708290077745914)
     | > stopnet_loss: 0.0038693896494805813  (0.0056284624224645086)
     | > loss: 0.18812888860702515  (0.19420483568683267)
     | > align_error: 0.5309000611305237  (0.5882338769733906)

   --> STEP: 33
     | > decoder_loss: 0.4354149103164673  (0.44686477834528143)
     | > postnet_loss: 0.2953261733055115  (0.30672663630861224)
     | > stopnet_loss: 0.004025438334792852  (0.005579885934959307)
     | > loss: 0.18671071529388428  (0.19397774112947058)
     | > align_error: 0.5460456609725952  (0.5869554461854877)

   --> STEP: 34
     | > decoder_loss: 0.4405180513858795  (0.446678109905299)
     | > postnet_loss: 0.2965337932109833  (0.3064268468057408)
     | > stopnet_loss: 0.0033260327763855457  (0.005513596136177725)
     | > loss: 0.18758898973464966  (0.19378983667668173)
     | > align_error: 0.5634735226631165  (0.5862648013760062)

   --> STEP: 35
     | > decoder_loss: 0.4384256899356842  (0.44644232647759574)
     | > postnet_loss: 0.29570725560188293  (0.30612057277134486)
     | > stopnet_loss: 0.003541361540555954  (0.005457246576302818)
     | > loss: 0.18707460165023804  (0.19359797281878335)
     | > align_error: 0.5329587161540985  (0.584741770369666)

   --> STEP: 36
     | > decoder_loss: 0.4449470341205597  (0.4464007905787892)
     | > postnet_loss: 0.30044251680374146  (0.305962848994467)
     | > stopnet_loss: 0.003682282753288746  (0.005407942025663538)
     | > loss: 0.19002968072891235  (0.1934988535940647)
     | > align_error: 0.633699893951416  (0.5861017182469368)

   --> STEP: 37
     | > decoder_loss: 0.43738770484924316  (0.4461571936671798)
     | > postnet_loss: 0.29686689376831055  (0.30571701236673304)
     | > stopnet_loss: 0.0035738463047891855  (0.005358371871045312)
     | > loss: 0.18713749945163727  (0.19332692510372884)
     | > align_error: 0.5184551477432251  (0.5842734325576473)

   --> STEP: 38
     | > decoder_loss: 0.42500731348991394  (0.4456006178730412)
     | > postnet_loss: 0.28973785042762756  (0.3052965081051776)
     | > stopnet_loss: 0.003161335363984108  (0.005300555120859491)
     | > loss: 0.18184763193130493  (0.19302483844129661)
     | > align_error: 0.551249772310257  (0.5834043888669265)

   --> STEP: 39
     | > decoder_loss: 0.4404601454734802  (0.44546881088843715)
     | > postnet_loss: 0.299817830324173  (0.30515602918771595)
     | > stopnet_loss: 0.003471153788268566  (0.005253647394382801)
     | > loss: 0.18854065239429474  (0.1929098593118863)
     | > align_error: 0.5455532670021057  (0.5824338472806491)

   --> STEP: 40
     | > decoder_loss: 0.4376911520957947  (0.4452743694186211)
     | > postnet_loss: 0.29845550656318665  (0.30498851612210276)
     | > stopnet_loss: 0.0030283776577562094  (0.005198015650967136)
     | > loss: 0.18706505000591278  (0.192763739079237)
     | > align_error: 0.5834819078445435  (0.5824600487947464)

   --> STEP: 41
     | > decoder_loss: 0.42745885252952576  (0.444839844616448)
     | > postnet_loss: 0.29041534662246704  (0.30463307296357506)
     | > stopnet_loss: 0.003727525006979704  (0.005162150025504028)
     | > loss: 0.1831960678100586  (0.19253038124340335)
     | > align_error: 0.5028855800628662  (0.5805192080939688)

   --> STEP: 42
     | > decoder_loss: 0.4326368272304535  (0.44454929658344816)
     | > postnet_loss: 0.2930033504962921  (0.3043561748095921)
     | > stopnet_loss: 0.0032891028095036745  (0.005117553663218305)
     | > loss: 0.184699147939682  (0.19234392330760047)
     | > align_error: 0.5791460275650024  (0.5804865133194697)

   --> STEP: 43
     | > decoder_loss: 0.4322936236858368  (0.44426428093466647)
     | > postnet_loss: 0.2921191155910492  (0.30407159203706785)
     | > stopnet_loss: 0.0029327727388590574  (0.005066744804512276)
     | > loss: 0.18403595685958862  (0.19215071478555368)
     | > align_error: 0.5514061748981476  (0.5798102263794389)

   --> STEP: 44
     | > decoder_loss: 0.4500884413719177  (0.44439664821733127)
     | > postnet_loss: 0.3024083077907562  (0.30403379012237897)
     | > stopnet_loss: 0.0026779223699122667  (0.005012453385544094)
     | > loss: 0.19080209732055664  (0.19212006438862195)
     | > align_error: 0.5506941676139832  (0.5791484977711331)

   --> STEP: 45
     | > decoder_loss: 0.44269511103630066  (0.444358836279975)
     | > postnet_loss: 0.30143916606903076  (0.3039761318100823)
     | > stopnet_loss: 0.003287170547991991  (0.004974113766931825)
     | > loss: 0.18932074308395386  (0.1920578572485182)
     | > align_error: 0.5521003305912018  (0.5785474273893568)

   --> STEP: 46
     | > decoder_loss: 0.43349912762641907  (0.44412275565707166)
     | > postnet_loss: 0.2927081882953644  (0.3037311765162841)
     | > stopnet_loss: 0.003209430491551757  (0.0049357510870322585)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35237428275021637 (-0.010707262790564387)
     | > avg_decoder_loss: 0.44026165749087476 (+0.0002035412824514804)
     | > avg_postnet_loss: 0.3004359991261453 (-0.001120381283037597)
     | > avg_stopnet_loss: 0.004378006486645477 (-3.627702509136771e-06)
     | > avg_loss: 0.1895524218226924 (-0.0002328376426841139)
     | > avg_align_error: 0.5714438923380591 (+0.00029801915992377914)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_17516.pth

 > EPOCH: 116/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 14:01:18)

   --> TIME: 2025-12-28 14:01:31 -- STEP: 9/150 -- GLOBAL_STEP: 17525
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47105294466018677  (0.46733803550402325)
     | > postnet_loss: 0.39797818660736084  (0.3984624875916375)
     | > stopnet_loss: 0.009976731613278389  (0.01259817307194074)
     | > loss: 0.22723451256752014  (0.2290483017762502)
     | > align_error: 0.645969808101654  (0.6958655450079176)
     | > grad_norm: tensor(0.5101, device='cuda:0')  (tensor(0.3607, device='cuda:0'))
     | > step_time: 0.6513  (0.5180788040161133)
     | > loader_time: 0.7994  (0.7950679461161295)


   --> TIME: 2025-12-28 14:02:16 -- STEP: 34/150 -- GLOBAL_STEP: 17550
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4772273600101471  (0.47467461228370667)
     | > postnet_loss: 0.39824819564819336  (0.4002434541197384)
     | > stopnet_loss: 0.005452386569231749  (0.008653759641353698)
     | > loss: 0.22432126104831696  (0.22738327568068223)
     | > align_error: 0.6213115453720093  (0.6624880003578523)
     | > grad_norm: tensor(0.1521, device='cuda:0')  (tensor(0.2835, device='cuda:0'))
     | > step_time: 1.4285  (0.7677314982694736)
     | > loader_time: 0.987  (0.9082235518623801)


   --> TIME: 2025-12-28 14:03:15 -- STEP: 59/150 -- GLOBAL_STEP: 17575
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48606473207473755  (0.4798153456995043)
     | > postnet_loss: 0.4000634551048279  (0.4010478950152963)
     | > stopnet_loss: 0.004361568950116634  (0.007065437505242682)
     | > loss: 0.22589361667633057  (0.22728124740770309)
     | > align_error: 0.6041823029518127  (0.6430490269499312)
     | > grad_norm: tensor(0.1867, device='cuda:0')  (tensor(0.2561, device='cuda:0'))
     | > step_time: 1.3158  (0.9694493584713693)
     | > loader_time: 1.2213  (0.997066934229964)


   --> TIME: 2025-12-28 14:04:26 -- STEP: 84/150 -- GLOBAL_STEP: 17600
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4836203157901764  (0.48195558360644747)
     | > postnet_loss: 0.39659422636032104  (0.4005375312907355)
     | > stopnet_loss: 0.0033242437057197094  (0.006135692933596493)
     | > loss: 0.22337788343429565  (0.22675897163294612)
     | > align_error: 0.6687125861644745  (0.6348319287811007)
     | > grad_norm: tensor(0.1397, device='cuda:0')  (tensor(0.2460, device='cuda:0'))
     | > step_time: 1.4694  (1.117963824953352)
     | > loader_time: 1.5321  (1.1079338448388238)


   --> TIME: 2025-12-28 14:05:47 -- STEP: 109/150 -- GLOBAL_STEP: 17625
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48515957593917847  (0.4830340037652112)
     | > postnet_loss: 0.39586979150772095  (0.3998969722231594)
     | > stopnet_loss: 0.0035579120740294456  (0.005539815388021803)
     | > loss: 0.22381524741649628  (0.22627255881051406)
     | > align_error: 0.6335560083389282  (0.6291249725249929)
     | > grad_norm: tensor(0.1698, device='cuda:0')  (tensor(0.2300, device='cuda:0'))
     | > step_time: 1.6861  (1.243861764942834)
     | > loader_time: 1.5913  (1.2089880015871939)


   --> TIME: 2025-12-28 14:07:17 -- STEP: 134/150 -- GLOBAL_STEP: 17650
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48648130893707275  (0.48372817261895135)
     | > postnet_loss: 0.39460691809654236  (0.3991894161523278)
     | > stopnet_loss: 0.0033759064972400665  (0.005110881291329861)
     | > loss: 0.22364796698093414  (0.2258402779698372)
     | > align_error: 0.631386399269104  (0.6255804558298481)
     | > grad_norm: tensor(0.1469, device='cuda:0')  (tensor(0.2237, device='cuda:0'))
     | > step_time: 2.0327  (1.360176025931515)
     | > loader_time: 1.8323  (1.3053526771602344)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4615035653114319  (0.4615035653114319)
     | > postnet_loss: 0.33479881286621094  (0.33479881286621094)
     | > stopnet_loss: 0.012216996401548386  (0.012216996401548386)
     | > loss: 0.2112925946712494  (0.2112925946712494)
     | > align_error: 0.7190807461738586  (0.7190807461738586)

   --> STEP: 1
     | > decoder_loss: 0.44339486956596375  (0.44339486956596375)
     | > postnet_loss: 0.3229523003101349  (0.3229523003101349)
     | > stopnet_loss: 0.009633250534534454  (0.009633250534534454)
     | > loss: 0.20122003555297852  (0.20122003555297852)
     | > align_error: 0.6594959795475006  (0.6594959795475006)

   --> STEP: 2
     | > decoder_loss: 0.4388335347175598  (0.4411142021417618)
     | > postnet_loss: 0.31317153573036194  (0.3180619180202484)
     | > stopnet_loss: 0.011044708080589771  (0.010338979307562113)
     | > loss: 0.19904598593711853  (0.20013301074504852)
     | > align_error: 0.6557669043540955  (0.657631441950798)

   --> STEP: 3
     | > decoder_loss: 0.4418191611766815  (0.44134918848673504)
     | > postnet_loss: 0.3122037947177887  (0.31610921025276184)
     | > stopnet_loss: 0.008282159455120564  (0.009653372690081596)
     | > loss: 0.19678789377212524  (0.1990179717540741)
     | > align_error: 0.7345613837242126  (0.6832747558752695)

   --> STEP: 4
     | > decoder_loss: 0.44669651985168457  (0.4426860213279724)
     | > postnet_loss: 0.32023850083351135  (0.3171415328979492)
     | > stopnet_loss: 0.00825460348278284  (0.009303680388256907)
     | > loss: 0.19998835027217865  (0.19926056638360023)
     | > align_error: 0.6033056974411011  (0.6632824912667274)

   --> STEP: 5
     | > decoder_loss: 0.42832672595977783  (0.4398141622543335)
     | > postnet_loss: 0.3027724027633667  (0.3142677068710327)
     | > stopnet_loss: 0.008202197961509228  (0.00908338390290737)
     | > loss: 0.19097697734832764  (0.19760384857654573)
     | > align_error: 0.6419602632522583  (0.6590180456638336)

   --> STEP: 6
     | > decoder_loss: 0.4451450705528259  (0.4407026469707489)
     | > postnet_loss: 0.31472378969192505  (0.31434372067451477)
     | > stopnet_loss: 0.00727448146790266  (0.00878190016373992)
     | > loss: 0.19724169373512268  (0.19754348943630853)
     | > align_error: 0.5937469005584717  (0.6481395214796066)

   --> STEP: 7
     | > decoder_loss: 0.4557921886444092  (0.4428582957812718)
     | > postnet_loss: 0.31374210119247437  (0.3142577750342233)
     | > stopnet_loss: 0.006270445417612791  (0.008423120914293187)
     | > loss: 0.19865401089191437  (0.19770213535853795)
     | > align_error: 0.5789263844490051  (0.638251930475235)

   --> STEP: 8
     | > decoder_loss: 0.45284369587898254  (0.44410647079348564)
     | > postnet_loss: 0.31603553891181946  (0.3144799955189228)
     | > stopnet_loss: 0.007288485765457153  (0.008281291520688683)
     | > loss: 0.19950829446315765  (0.1979279052466154)
     | > align_error: 0.5745574831962585  (0.6302901245653629)

   --> STEP: 9
     | > decoder_loss: 0.44749775528907776  (0.44448328018188477)
     | > postnet_loss: 0.31366556882858276  (0.3143895036644406)
     | > stopnet_loss: 0.006608951836824417  (0.00809547600025932)
     | > loss: 0.19689978659152985  (0.19781366984049478)
     | > align_error: 0.5912504494190216  (0.6259523828824362)

   --> STEP: 10
     | > decoder_loss: 0.4742587208747864  (0.44746082425117495)
     | > postnet_loss: 0.32889100909233093  (0.3158396542072296)
     | > stopnet_loss: 0.005556452088057995  (0.007841573609039188)
     | > loss: 0.206343874335289  (0.19866669028997422)
     | > align_error: 0.5835800766944885  (0.6217151522636414)

   --> STEP: 11
     | > decoder_loss: 0.46148523688316345  (0.44873577085408295)
     | > postnet_loss: 0.31907549500465393  (0.31613382155245)
     | > stopnet_loss: 0.005912144202739  (0.00766617093573917)
     | > loss: 0.20105232298374176  (0.19888356598940762)
     | > align_error: 0.5948228240013123  (0.6192703951488842)

   --> STEP: 12
     | > decoder_loss: 0.45755207538604736  (0.44947046289841336)
     | > postnet_loss: 0.31303104758262634  (0.3158752570549647)
     | > stopnet_loss: 0.007851257920265198  (0.00768159485111634)
     | > loss: 0.20049704611301422  (0.19901802266637483)
     | > align_error: 0.5874831676483154  (0.6166214595238367)

   --> STEP: 13
     | > decoder_loss: 0.44703641533851624  (0.44928322847072893)
     | > postnet_loss: 0.31272029876708984  (0.3156325679558974)
     | > stopnet_loss: 0.005576950032263994  (0.007519699095820005)
     | > loss: 0.19551612436771393  (0.19874864587417015)
     | > align_error: 0.5858435034751892  (0.6142539244431716)

   --> STEP: 14
     | > decoder_loss: 0.4599456489086151  (0.450044829930578)
     | > postnet_loss: 0.31671401858329773  (0.31570981442928314)
     | > stopnet_loss: 0.004938664846122265  (0.007335339506555881)
     | > loss: 0.19910357892513275  (0.1987739982349532)
     | > align_error: 0.5544915199279785  (0.609985181263515)

   --> STEP: 15
     | > decoder_loss: 0.45490211248397827  (0.4503686487674713)
     | > postnet_loss: 0.3147532641887665  (0.31564604441324867)
     | > stopnet_loss: 0.005014976020902395  (0.007180648607512315)
     | > loss: 0.19742880761623383  (0.1986843188603719)
     | > align_error: 0.5882148146629333  (0.6085338234901428)

   --> STEP: 16
     | > decoder_loss: 0.4553275406360626  (0.45067857950925827)
     | > postnet_loss: 0.30857759714126587  (0.31520426645874977)
     | > stopnet_loss: 0.005264071747660637  (0.007060862553771585)
     | > loss: 0.1962403655052185  (0.19853157177567482)
     | > align_error: 0.6059179604053497  (0.6083703320473433)

   --> STEP: 17
     | > decoder_loss: 0.46257245540618896  (0.4513782192679012)
     | > postnet_loss: 0.3172451853752136  (0.3153243205126594)
     | > stopnet_loss: 0.004843907430768013  (0.006930453428889022)
     | > loss: 0.1997983157634735  (0.19860608612789826)
     | > align_error: 0.5584307014942169  (0.6054327067206887)

   --> STEP: 18
     | > decoder_loss: 0.457222044467926  (0.45170287622345817)
     | > postnet_loss: 0.31022319197654724  (0.3150409244828754)
     | > stopnet_loss: 0.005262264981865883  (0.006837776292943292)
     | > loss: 0.19712357223033905  (0.19852372424470055)
     | > align_error: 0.6039769351482391  (0.6053518305222193)

   --> STEP: 19
     | > decoder_loss: 0.45419344305992126  (0.4518339586885352)
     | > postnet_loss: 0.3088997006416321  (0.31471770217544154)
     | > stopnet_loss: 0.004743256140500307  (0.006727538390183135)
     | > loss: 0.19551654160022736  (0.1983654514739388)
     | > align_error: 0.5997057259082794  (0.6050546671214857)

   --> STEP: 20
     | > decoder_loss: 0.451240211725235  (0.45180427134037016)
     | > postnet_loss: 0.305735319852829  (0.31426858305931094)
     | > stopnet_loss: 0.0045176781713962555  (0.006617045379243791)
     | > loss: 0.19376155734062195  (0.19813525676727295)
     | > align_error: 0.6227860450744629  (0.6059412360191345)

   --> STEP: 21
     | > decoder_loss: 0.44935378432273865  (0.45168758148238775)
     | > postnet_loss: 0.305189847946167  (0.3138362623396374)
     | > stopnet_loss: 0.0039938283152878284  (0.006492130280960174)
     | > loss: 0.19262973964214325  (0.19787308928512393)
     | > align_error: 0.560118705034256  (0.6037592107341403)

   --> STEP: 22
     | > decoder_loss: 0.4512903094291687  (0.45166952366178686)
     | > postnet_loss: 0.3079375624656677  (0.3135681396180933)
     | > stopnet_loss: 0.004866005852818489  (0.0064182155342264605)
     | > loss: 0.19467297196388245  (0.19772762940688568)
     | > align_error: 0.6254892349243164  (0.6047469391064211)

   --> STEP: 23
     | > decoder_loss: 0.4246752858161926  (0.45049586114676105)
     | > postnet_loss: 0.29607897996902466  (0.31280774137248163)
     | > stopnet_loss: 0.004510591272264719  (0.006335275348923777)
     | > loss: 0.1846991628408432  (0.19716117433879687)
     | > align_error: 0.5671228170394897  (0.6031111077122067)

   --> STEP: 24
     | > decoder_loss: 0.4588821530342102  (0.45084528997540474)
     | > postnet_loss: 0.31145668029785156  (0.3127514471610387)
     | > stopnet_loss: 0.004404199775308371  (0.006254813866689801)
     | > loss: 0.19698891043663025  (0.1971539966762066)
     | > align_error: 0.5792162418365479  (0.6021154883007208)

   --> STEP: 25
     | > decoder_loss: 0.45687925815582275  (0.45108664870262144)
     | > postnet_loss: 0.30794647336006165  (0.3125592482089996)
     | > stopnet_loss: 0.0037197296041995287  (0.00615341049619019)
     | > loss: 0.1949261575937271  (0.1970648831129074)
     | > align_error: 0.5573297739028931  (0.6003240597248077)

   --> STEP: 26
     | > decoder_loss: 0.43350985646247864  (0.45041061823184675)
     | > postnet_loss: 0.2977714538574219  (0.3119904868877851)
     | > stopnet_loss: 0.004378017503768206  (0.006085126150327806)
     | > loss: 0.18719834089279175  (0.19668540071982604)
     | > align_error: 0.5467956364154816  (0.5982652742129105)

   --> STEP: 27
     | > decoder_loss: 0.4297070801258087  (0.4496438205242157)
     | > postnet_loss: 0.29229044914245605  (0.3112608558601803)
     | > stopnet_loss: 0.003941004164516926  (0.006005714224927404)
     | > loss: 0.18444037437438965  (0.1962318812255506)
     | > align_error: 0.5410201549530029  (0.5961450846106918)

   --> STEP: 28
     | > decoder_loss: 0.43585482239723206  (0.4491513563053949)
     | > postnet_loss: 0.2972307503223419  (0.3107597806624004)
     | > stopnet_loss: 0.003944026306271553  (0.005932082513546837)
     | > loss: 0.1872154176235199  (0.19590986466833524)
     | > align_error: 0.566076248884201  (0.59507119762046)

   --> STEP: 29
     | > decoder_loss: 0.4308566749095917  (0.448520505222781)
     | > postnet_loss: 0.29376232624053955  (0.3101736615444052)
     | > stopnet_loss: 0.0036027668975293636  (0.005851761285408303)
     | > loss: 0.1847575306892395  (0.19552530142767677)
     | > align_error: 0.5403750240802765  (0.5931851226707985)

   --> STEP: 30
     | > decoder_loss: 0.4312162399291992  (0.4479436963796616)
     | > postnet_loss: 0.2942783832550049  (0.3096438189347585)
     | > stopnet_loss: 0.002845616079866886  (0.0057515564452235894)
     | > loss: 0.18421927094459534  (0.19514843374490737)
     | > align_error: 0.5330437421798706  (0.5911804099877676)

   --> STEP: 31
     | > decoder_loss: 0.4312525689601898  (0.4474052729145173)
     | > postnet_loss: 0.2947649657726288  (0.3091638559295285)
     | > stopnet_loss: 0.003935279790312052  (0.005692966875710314)
     | > loss: 0.18543966114521027  (0.19483524753201392)
     | > align_error: 0.5590607523918152  (0.5901442920008013)

   --> STEP: 32
     | > decoder_loss: 0.4399351477622986  (0.4471718315035105)
     | > postnet_loss: 0.2996355891227722  (0.3088660975918174)
     | > stopnet_loss: 0.003885540645569563  (0.005636484806018416)
     | > loss: 0.18877822160720825  (0.19464596547186375)
     | > align_error: 0.5309413075447083  (0.5882941987365484)

   --> STEP: 33
     | > decoder_loss: 0.43570882081985474  (0.4468244675433997)
     | > postnet_loss: 0.29631632566452026  (0.30848580147280835)
     | > stopnet_loss: 0.004050650168210268  (0.00558842921093332)
     | > loss: 0.18705694377422333  (0.1944159951173898)
     | > align_error: 0.5455726087093353  (0.5869996050993601)

   --> STEP: 34
     | > decoder_loss: 0.4411247968673706  (0.44665683017057534)
     | > postnet_loss: 0.2977534830570221  (0.3081701450488147)
     | > stopnet_loss: 0.003329402068629861  (0.005521987236159689)
     | > loss: 0.18804895877838135  (0.19422872934271307)
     | > align_error: 0.5635072886943817  (0.5863086546168608)

   --> STEP: 35
     | > decoder_loss: 0.43843555450439453  (0.446421936580113)
     | > postnet_loss: 0.29725873470306396  (0.3078583904675075)
     | > stopnet_loss: 0.0035423715598881245  (0.005465426788266216)
     | > loss: 0.18746595084667206  (0.19403550709996906)
     | > align_error: 0.5328480303287506  (0.5847812082086291)

   --> STEP: 36
     | > decoder_loss: 0.44522592425346375  (0.44638871401548386)
     | > postnet_loss: 0.30161407589912415  (0.3076849372850524)
     | > stopnet_loss: 0.0036853982601314783  (0.005415981551373584)
     | > loss: 0.19039539992809296  (0.19393439301186138)
     | > align_error: 0.6335396766662598  (0.58613561011023)

   --> STEP: 37
     | > decoder_loss: 0.43813058733940125  (0.4461655214026168)
     | > postnet_loss: 0.29877549409866333  (0.3074441415232581)
     | > stopnet_loss: 0.0035740407183766365  (0.005366199366697991)
     | > loss: 0.1878005564212799  (0.19376861364454837)
     | > align_error: 0.5186306834220886  (0.584311152632172)

   --> STEP: 38
     | > decoder_loss: 0.4252668023109436  (0.44561555511073064)
     | > postnet_loss: 0.29108119010925293  (0.30701353753867905)
     | > stopnet_loss: 0.0031654047779738903  (0.005308283719626304)
     | > loss: 0.1822524070739746  (0.19346555557690168)
     | > align_error: 0.5513493716716766  (0.583443737343738)

   --> STEP: 39
     | > decoder_loss: 0.44038626551628113  (0.445481470762155)
     | > postnet_loss: 0.3014286756515503  (0.3068703359518296)
     | > stopnet_loss: 0.0034783121664077044  (0.005261361372107878)
     | > loss: 0.18893206119537354  (0.19334931213122147)
     | > align_error: 0.5452616810798645  (0.5824647102600489)

   --> STEP: 40
     | > decoder_loss: 0.4378964900970459  (0.44529184624552726)
     | > postnet_loss: 0.30012571811676025  (0.3067017205059529)
     | > stopnet_loss: 0.003034500405192375  (0.005205689847934991)
     | > loss: 0.18754005432128906  (0.19320408068597317)
     | > align_error: 0.5835433602333069  (0.5824916765093804)

   --> STEP: 41
     | > decoder_loss: 0.4288683235645294  (0.4448912725216005)
     | > postnet_loss: 0.2925107777118683  (0.3063555999499996)
     | > stopnet_loss: 0.0037368726916611195  (0.005169865039245385)
     | > loss: 0.18408164381980896  (0.19298158222582282)
     | > align_error: 0.5028958022594452  (0.5805503137227965)

   --> STEP: 42
     | > decoder_loss: 0.4336013197898865  (0.44462246412322637)
     | > postnet_loss: 0.2944643199443817  (0.30607247423558015)
     | > stopnet_loss: 0.0032974507194012403  (0.005125283745915762)
     | > loss: 0.1853138506412506  (0.19279901718809492)
     | > align_error: 0.5792641639709473  (0.5805196911096573)

   --> STEP: 43
     | > decoder_loss: 0.43247219920158386  (0.44433989982272304)
     | > postnet_loss: 0.2933427393436432  (0.30577643388925607)
     | > stopnet_loss: 0.0029320840258151293  (0.005074279101262259)
     | > loss: 0.18438582122325897  (0.19260336146798246)
     | > align_error: 0.5513281226158142  (0.5798408174237539)

   --> STEP: 44
     | > decoder_loss: 0.4495882987976074  (0.4444591816176068)
     | > postnet_loss: 0.3035880923271179  (0.305726698853753)
     | > stopnet_loss: 0.002684203675016761  (0.005019959205211225)
     | > loss: 0.1909783035516739  (0.1925664283335209)
     | > align_error: 0.550561785697937  (0.5791753848845308)

   --> STEP: 45
     | > decoder_loss: 0.44347432255744934  (0.4444372958607144)
     | > postnet_loss: 0.30294668674468994  (0.3056649208068849)
     | > stopnet_loss: 0.003318693023175001  (0.004982153290054864)
     | > loss: 0.1899239420890808  (0.1925077064169778)
     | > align_error: 0.5522276163101196  (0.5785765455828772)

   --> STEP: 46
     | > decoder_loss: 0.4330601990222931  (0.44418996766857477)
     | > postnet_loss: 0.29403045773506165  (0.30541199769662786)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.39418281208385114 (+0.04180852933363477)
     | > avg_decoder_loss: 0.4403200415950833 (+5.838410420855311e-05)
     | > avg_postnet_loss: 0.30228829158074927 (+0.0018522924546039432)
     | > avg_stopnet_loss: 0.004383755459760626 (+5.748973115149089e-06)
     | > avg_loss: 0.19003583784356262 (+0.00048341602087020874)
     | > avg_align_error: 0.5713702349951773 (-7.36573428818943e-05)


 > EPOCH: 117/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 14:10:16)

   --> TIME: 2025-12-28 14:10:28 -- STEP: 8/150 -- GLOBAL_STEP: 17675
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4681822657585144  (0.46311885491013527)
     | > postnet_loss: 0.39597105979919434  (0.3962680920958519)
     | > stopnet_loss: 0.010531961917877197  (0.013035018229857087)
     | > loss: 0.22657029330730438  (0.22788175754249096)
     | > align_error: 0.6883566379547119  (0.7022069208323956)
     | > grad_norm: tensor(0.3535, device='cuda:0')  (tensor(0.3061, device='cuda:0'))
     | > step_time: 0.5156  (0.5052938461303711)
     | > loader_time: 0.779  (0.7759791910648346)


   --> TIME: 2025-12-28 14:11:10 -- STEP: 33/150 -- GLOBAL_STEP: 17700
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.48158296942710876  (0.4729767586245681)
     | > postnet_loss: 0.40116485953330994  (0.39915731278332794)
     | > stopnet_loss: 0.005196480546146631  (0.008898626025201695)
     | > loss: 0.22588343918323517  (0.22693214317162833)
     | > align_error: 0.6531075239181519  (0.6636163845206752)
     | > grad_norm: tensor(0.4472, device='cuda:0')  (tensor(0.2804, device='cuda:0'))
     | > step_time: 1.0684  (0.7252352526693633)
     | > loader_time: 1.0147  (0.8781130024881074)


   --> TIME: 2025-12-28 14:12:09 -- STEP: 58/150 -- GLOBAL_STEP: 17725
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48697882890701294  (0.4790110685702028)
     | > postnet_loss: 0.40049874782562256  (0.40051790969125156)
     | > stopnet_loss: 0.0039792750030756  (0.00718314265671732)
     | > loss: 0.22584867477416992  (0.22706538644330254)
     | > align_error: 0.5977665781974792  (0.644342992840142)
     | > grad_norm: tensor(0.1549, device='cuda:0')  (tensor(0.2620, device='cuda:0'))
     | > step_time: 1.5539  (0.9372183701087689)
     | > loader_time: 1.2816  (0.9933060736491762)


   --> TIME: 2025-12-28 14:13:20 -- STEP: 83/150 -- GLOBAL_STEP: 17750
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48232030868530273  (0.4816669911505228)
     | > postnet_loss: 0.39492595195770264  (0.40034371219485637)
     | > stopnet_loss: 0.0037932374980300665  (0.0062225863354347915)
     | > loss: 0.2231048047542572  (0.22672526143401503)
     | > align_error: 0.6219567656517029  (0.6350173849657357)
     | > grad_norm: tensor(0.1319, device='cuda:0')  (tensor(0.2526, device='cuda:0'))
     | > step_time: 1.5134  (1.1020088339426428)
     | > loader_time: 1.7704  (1.0982787092048)


   --> TIME: 2025-12-28 14:14:47 -- STEP: 108/150 -- GLOBAL_STEP: 17775
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4873276352882385  (0.48268329324545683)
     | > postnet_loss: 0.39781004190444946  (0.3996579235902539)
     | > stopnet_loss: 0.003298931522294879  (0.005612138486294834)
     | > loss: 0.22458335757255554  (0.22619744155693938)
     | > align_error: 0.5827412903308868  (0.6294954173542835)
     | > grad_norm: tensor(0.1240, device='cuda:0')  (tensor(0.2357, device='cuda:0'))
     | > step_time: 1.7664  (1.2435577710469563)
     | > loader_time: 1.763  (1.2482449566876446)


   --> TIME: 2025-12-28 14:16:21 -- STEP: 133/150 -- GLOBAL_STEP: 17800
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48709067702293396  (0.483548329961031)
     | > postnet_loss: 0.39587247371673584  (0.39904676904355674)
     | > stopnet_loss: 0.003283134428784251  (0.005176560993523414)
     | > loss: 0.22402392327785492  (0.2258253344019553)
     | > align_error: 0.5602769255638123  (0.6258184103141153)
     | > grad_norm: tensor(0.1987, device='cuda:0')  (tensor(0.2319, device='cuda:0'))
     | > step_time: 2.0124  (1.3673765533848812)
     | > loader_time: 1.7588  (1.3635785310788262)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4634307026863098  (0.4634307026863098)
     | > postnet_loss: 0.3335125744342804  (0.3335125744342804)
     | > stopnet_loss: 0.012150239199399948  (0.012150239199399948)
     | > loss: 0.2113860696554184  (0.2113860696554184)
     | > align_error: 0.7197604775428772  (0.7197604775428772)

   --> STEP: 1
     | > decoder_loss: 0.446088582277298  (0.446088582277298)
     | > postnet_loss: 0.3213002681732178  (0.3213002681732178)
     | > stopnet_loss: 0.009629223495721817  (0.009629223495721817)
     | > loss: 0.20147642493247986  (0.20147642493247986)
     | > align_error: 0.6602892875671387  (0.6602892875671387)

   --> STEP: 2
     | > decoder_loss: 0.44008129835128784  (0.4430849403142929)
     | > postnet_loss: 0.3121982216835022  (0.31674924492836)
     | > stopnet_loss: 0.011119198054075241  (0.010374210774898529)
     | > loss: 0.19918908178806305  (0.20033275336027145)
     | > align_error: 0.6567643582820892  (0.658526822924614)

   --> STEP: 3
     | > decoder_loss: 0.44215449690818787  (0.4427747925122579)
     | > postnet_loss: 0.31015869975090027  (0.3145523965358734)
     | > stopnet_loss: 0.0084117716178298  (0.009720064389208952)
     | > loss: 0.1964900642633438  (0.1990518569946289)
     | > align_error: 0.7355501651763916  (0.6842012703418732)

   --> STEP: 4
     | > decoder_loss: 0.4509819746017456  (0.4448265880346298)
     | > postnet_loss: 0.32021430134773254  (0.3159678727388382)
     | > stopnet_loss: 0.008268313482403755  (0.009357126662507653)
     | > loss: 0.20106737315654755  (0.19955573603510857)
     | > align_error: 0.6051173210144043  (0.664430283010006)

   --> STEP: 5
     | > decoder_loss: 0.4300686717033386  (0.4418750047683716)
     | > postnet_loss: 0.3017101287841797  (0.3131163239479065)
     | > stopnet_loss: 0.008144986815750599  (0.009114698693156242)
     | > loss: 0.1910896897315979  (0.19786252677440644)
     | > align_error: 0.6424943208694458  (0.6600430905818939)

   --> STEP: 6
     | > decoder_loss: 0.4474482834339142  (0.44280388454596203)
     | > postnet_loss: 0.31375935673713684  (0.3132234960794449)
     | > stopnet_loss: 0.007261484861373901  (0.008805829721192518)
     | > loss: 0.19756339490413666  (0.1978126714626948)
     | > align_error: 0.5949743390083313  (0.6491982986529669)

   --> STEP: 7
     | > decoder_loss: 0.4581686854362488  (0.44499885610171724)
     | > postnet_loss: 0.313667356967926  (0.31328690477779936)
     | > stopnet_loss: 0.006265110336244106  (0.008442869809057032)
     | > loss: 0.19922411441802979  (0.1980143061705998)
     | > align_error: 0.5800985097885132  (0.6393269002437592)

   --> STEP: 8
     | > decoder_loss: 0.4550732970237732  (0.44625816121697426)
     | > postnet_loss: 0.3147512674331665  (0.31346995010972023)
     | > stopnet_loss: 0.0072883195243775845  (0.0082985510234721)
     | > loss: 0.19974446296691895  (0.1982305757701397)
     | > align_error: 0.5760151147842407  (0.6314129270613194)

   --> STEP: 9
     | > decoder_loss: 0.44968169927597046  (0.4466385543346405)
     | > postnet_loss: 0.3133603036403656  (0.31345776716868085)
     | > stopnet_loss: 0.006671135313808918  (0.008117727055731747)
     | > loss: 0.19743162393569946  (0.1981418033440908)
     | > align_error: 0.5927363336086273  (0.627115527788798)

   --> STEP: 10
     | > decoder_loss: 0.48022621870040894  (0.44999732077121735)
     | > postnet_loss: 0.3298344016075134  (0.31509543061256406)
     | > stopnet_loss: 0.005786039866507053  (0.007884558336809278)
     | > loss: 0.20830120146274567  (0.19915774315595627)
     | > align_error: 0.5873440206050873  (0.623138377070427)

   --> STEP: 11
     | > decoder_loss: 0.4622892439365387  (0.4511147683317011)
     | > postnet_loss: 0.3181576728820801  (0.3153738162734292)
     | > stopnet_loss: 0.005912057124078274  (0.007705240044742823)
     | > loss: 0.20102377235889435  (0.19932738217440518)
     | > align_error: 0.5961125493049622  (0.6206814836372029)

   --> STEP: 12
     | > decoder_loss: 0.4591582715511322  (0.4517850602666537)
     | > postnet_loss: 0.3119097054004669  (0.31508514036734897)
     | > stopnet_loss: 0.007905920967459679  (0.007721963454969227)
     | > loss: 0.200672909617424  (0.1994395094613234)
     | > align_error: 0.58901047706604  (0.6180422330896059)

   --> STEP: 13
     | > decoder_loss: 0.44844865798950195  (0.45152841393764204)
     | > postnet_loss: 0.3117430806159973  (0.31482805884801424)
     | > stopnet_loss: 0.005627617239952087  (0.007560859899967909)
     | > loss: 0.1956755518913269  (0.19914997426363137)
     | > align_error: 0.5875881016254425  (0.6156996075923626)

   --> STEP: 14
     | > decoder_loss: 0.4605775773525238  (0.4521747827529907)
     | > postnet_loss: 0.31543639302253723  (0.3148715112890516)
     | > stopnet_loss: 0.004937169142067432  (0.007373453417260732)
     | > loss: 0.19894066452980042  (0.19913502356835774)
     | > align_error: 0.5578666925430298  (0.6115686850888389)

   --> STEP: 15
     | > decoder_loss: 0.4550085961818695  (0.4523637036482493)
     | > postnet_loss: 0.31410661339759827  (0.314820518096288)
     | > stopnet_loss: 0.005031687673181295  (0.00721733570098877)
     | > loss: 0.19731049239635468  (0.19901338815689087)
     | > align_error: 0.5894547402858734  (0.6100944221019745)

   --> STEP: 16
     | > decoder_loss: 0.4557124972343445  (0.45257300324738026)
     | > postnet_loss: 0.3077681362628937  (0.3143797442317009)
     | > stopnet_loss: 0.005261493381112814  (0.007095095555996522)
     | > loss: 0.1961316615343094  (0.19883328024297953)
     | > align_error: 0.6072414517402649  (0.6099161114543676)

   --> STEP: 17
     | > decoder_loss: 0.46261706948280334  (0.4531638306729934)
     | > postnet_loss: 0.3167540729045868  (0.3145194106242236)
     | > stopnet_loss: 0.00485541857779026  (0.006963349851396154)
     | > loss: 0.19969820976257324  (0.19888415845001445)
     | > align_error: 0.5598418712615967  (0.6069705679136164)

   --> STEP: 18
     | > decoder_loss: 0.45739027857780457  (0.4533986333343718)
     | > postnet_loss: 0.3093222379684448  (0.31423067881001365)
     | > stopnet_loss: 0.0053237564861774445  (0.006872261331106226)
     | > loss: 0.1970018893480301  (0.19877958794434866)
     | > align_error: 0.6052009463310242  (0.6068722556034724)

   --> STEP: 19
     | > decoder_loss: 0.456642210483551  (0.4535693479211707)
     | > postnet_loss: 0.3096725344657898  (0.3139907764761071)
     | > stopnet_loss: 0.004873719997704029  (0.006767074945137689)
     | > loss: 0.19645240902900696  (0.19865710484354118)
     | > align_error: 0.6016320586204529  (0.6065964557622608)

   --> STEP: 20
     | > decoder_loss: 0.45102575421333313  (0.4534421682357788)
     | > postnet_loss: 0.3053703010082245  (0.313559752702713)
     | > stopnet_loss: 0.0045091076754033566  (0.0066541765816509725)
     | > loss: 0.1936081200838089  (0.19840465560555456)
     | > align_error: 0.6239056885242462  (0.6074619174003602)

   --> STEP: 21
     | > decoder_loss: 0.45010972023010254  (0.4532834802355085)
     | > postnet_loss: 0.30460208654403687  (0.31313319717134747)
     | > stopnet_loss: 0.004004083573818207  (0.006527981676516079)
     | > loss: 0.19268202781677246  (0.19813214952037447)
     | > align_error: 0.5618097186088562  (0.6052880031721932)

   --> STEP: 22
     | > decoder_loss: 0.4517444372177124  (0.4532135237346996)
     | > postnet_loss: 0.3075316846370697  (0.31287858296524396)
     | > stopnet_loss: 0.004868033807724714  (0.006452529500661926)
     | > loss: 0.19468706846237183  (0.19797555492682892)
     | > align_error: 0.626730740070343  (0.6062626730312001)

   --> STEP: 23
     | > decoder_loss: 0.42471936345100403  (0.45197464720062586)
     | > postnet_loss: 0.29505297541618347  (0.3121035565500674)
     | > stopnet_loss: 0.004522322677075863  (0.006368607464853836)
     | > loss: 0.1844654083251953  (0.197388157248497)
     | > align_error: 0.5686438679695129  (0.6046270728111267)

   --> STEP: 24
     | > decoder_loss: 0.458442747592926  (0.4522441513836384)
     | > postnet_loss: 0.31083858013153076  (0.31205084919929504)
     | > stopnet_loss: 0.004408603999763727  (0.006286940653808415)
     | > loss: 0.1967289298772812  (0.197360689441363)
     | > align_error: 0.5808758437633514  (0.6036374382674694)

   --> STEP: 25
     | > decoder_loss: 0.45713984966278076  (0.45243997931480406)
     | > postnet_loss: 0.3073505461215973  (0.3118628370761871)
     | > stopnet_loss: 0.003722850698977709  (0.0061843770556151865)
     | > loss: 0.19484543800354004  (0.1972600793838501)
     | > align_error: 0.5586341619491577  (0.6018373072147369)

   --> STEP: 26
     | > decoder_loss: 0.4338566064834595  (0.4517252342059062)
     | > postnet_loss: 0.29671210050582886  (0.31128011643886566)
     | > stopnet_loss: 0.004398314747959375  (0.0061156823514745785)
     | > loss: 0.18704049289226532  (0.196867018364943)
     | > align_error: 0.5482872128486633  (0.5997776882006571)

   --> STEP: 27
     | > decoder_loss: 0.43069517612457275  (0.4509463431658568)
     | > postnet_loss: 0.29237091541290283  (0.3105797756601263)
     | > stopnet_loss: 0.003946749493479729  (0.006035351504882176)
     | > loss: 0.18471327424049377  (0.19641687969366708)
     | > align_error: 0.542578399181366  (0.5976591960147575)

   --> STEP: 28
     | > decoder_loss: 0.4363129138946533  (0.45042372069188524)
     | > postnet_loss: 0.2965777814388275  (0.31007970443793703)
     | > stopnet_loss: 0.003951163496822119  (0.005960916218880031)
     | > loss: 0.18717384338378906  (0.1960867712540286)
     | > align_error: 0.5673381686210632  (0.5965763021792684)

   --> STEP: 29
     | > decoder_loss: 0.43122345209121704  (0.449761642464276)
     | > postnet_loss: 0.29297614097595215  (0.30948992638752376)
     | > stopnet_loss: 0.0035958464723080397  (0.005879362089687894)
     | > loss: 0.18464574217796326  (0.19569225301002635)
     | > align_error: 0.542054146528244  (0.5946962278464745)

   --> STEP: 30
     | > decoder_loss: 0.4319733679294586  (0.4491686999797821)
     | > postnet_loss: 0.2937803268432617  (0.30896627306938174)
     | > stopnet_loss: 0.002892262302339077  (0.005779792096776267)
     | > loss: 0.18433067202568054  (0.1953135336438815)
     | > align_error: 0.535088986158371  (0.5927093197902044)

   --> STEP: 31
     | > decoder_loss: 0.4308018684387207  (0.44857622154297366)
     | > postnet_loss: 0.2941223084926605  (0.3084874355023907)
     | > stopnet_loss: 0.003896374022588134  (0.005719036675028263)
     | > loss: 0.18512742221355438  (0.1949849494041935)
     | > align_error: 0.5608989000320435  (0.5916831772173604)

   --> STEP: 32
     | > decoder_loss: 0.4390266239643097  (0.4482777966186404)
     | > postnet_loss: 0.2982536256313324  (0.30816762894392014)
     | > stopnet_loss: 0.003885852172970772  (0.005661749659338966)
     | > loss: 0.18820591270923615  (0.1947731045074761)
     | > align_error: 0.5322559773921967  (0.5898260772228241)

   --> STEP: 33
     | > decoder_loss: 0.4356957972049713  (0.4478965239091353)
     | > postnet_loss: 0.2960689961910248  (0.3078010037089839)
     | > stopnet_loss: 0.004028056748211384  (0.005612243813547221)
     | > loss: 0.18696925044059753  (0.19453662408120703)
     | > align_error: 0.5471658706665039  (0.5885333436908144)

   --> STEP: 34
     | > decoder_loss: 0.4406611919403076  (0.4476837200276992)
     | > postnet_loss: 0.2971956431865692  (0.3074890813406776)
     | > stopnet_loss: 0.003323029028251767  (0.005544913966920884)
     | > loss: 0.1877872496843338  (0.1943381130695343)
     | > align_error: 0.5644491612911224  (0.5878249853849411)

   --> STEP: 35
     | > decoder_loss: 0.43876275420188904  (0.4474288352898189)
     | > postnet_loss: 0.2966412901878357  (0.3071791444505964)
     | > stopnet_loss: 0.0035353389102965593  (0.0054874975367316175)
     | > loss: 0.18738634884357452  (0.19413949123450688)
     | > align_error: 0.5344716608524323  (0.5863006046840122)

   --> STEP: 36
     | > decoder_loss: 0.44517457485198975  (0.44736621694432366)
     | > postnet_loss: 0.30112141370773315  (0.30701087415218353)
     | > stopnet_loss: 0.0036841649562120438  (0.0054374049650505185)
     | > loss: 0.19025816023349762  (0.19403167648447883)
     | > align_error: 0.6347784101963043  (0.5876472103926871)

   --> STEP: 37
     | > decoder_loss: 0.4384159445762634  (0.4471243176911328)
     | > postnet_loss: 0.2981112599372864  (0.3067703440382674)
     | > stopnet_loss: 0.0035754390992224216  (0.005387081563271381)
     | > loss: 0.18770724534988403  (0.19386074591327357)
     | > align_error: 0.5203888416290283  (0.5858294166423179)

   --> STEP: 38
     | > decoder_loss: 0.42596498131752014  (0.446567493049722)
     | > postnet_loss: 0.29090097546577454  (0.3063527290758334)
     | > stopnet_loss: 0.0031764430459588766  (0.005328906865447368)
     | > loss: 0.1823929250240326  (0.1935589611530304)
     | > align_error: 0.5529162287712097  (0.584963280119394)

   --> STEP: 39
     | > decoder_loss: 0.44070926308631897  (0.44641728202501935)
     | > postnet_loss: 0.3007151782512665  (0.30620817649058807)
     | > stopnet_loss: 0.003466928843408823  (0.005281163839241251)
     | > loss: 0.18882304430007935  (0.1934375273875701)
     | > align_error: 0.5467044413089752  (0.5839822842524602)

   --> STEP: 40
     | > decoder_loss: 0.43805423378944397  (0.44620820581912995)
     | > postnet_loss: 0.2994934618473053  (0.306040308624506)
     | > stopnet_loss: 0.0030188588425517082  (0.005224606214324012)
     | > loss: 0.1874057799577713  (0.19328673370182514)
     | > align_error: 0.5849809646606445  (0.5840072512626648)

   --> STEP: 41
     | > decoder_loss: 0.4287184774875641  (0.44578162707933566)
     | > postnet_loss: 0.29169708490371704  (0.3056904738996087)
     | > stopnet_loss: 0.0037276120856404305  (0.005188094162404901)
     | > loss: 0.18383151292800903  (0.19305611856100036)
     | > align_error: 0.5045722126960754  (0.582069811297626)

   --> STEP: 42
     | > decoder_loss: 0.43330395221710205  (0.4454845395826158)
     | > postnet_loss: 0.2941220700740814  (0.30541503571328665)
     | > stopnet_loss: 0.003295458620414138  (0.005143031411405121)
     | > loss: 0.18515196442604065  (0.1928679244149299)
     | > align_error: 0.5805526971817017  (0.5820336895329612)

   --> STEP: 43
     | > decoder_loss: 0.4320049285888672  (0.4451710602571798)
     | > postnet_loss: 0.2926894724369049  (0.30511909238127777)
     | > stopnet_loss: 0.0029409269336611032  (0.005091819679364563)
     | > loss: 0.1841145157814026  (0.1926643567722897)
     | > align_error: 0.5526838600635529  (0.581351135359254)

   --> STEP: 44
     | > decoder_loss: 0.45022356510162354  (0.4452858899127353)
     | > postnet_loss: 0.30313605070114136  (0.30507402325218375)
     | > stopnet_loss: 0.002673850394785404  (0.005036865831987764)
     | > loss: 0.19101375341415405  (0.1926268430596048)
     | > align_error: 0.5521517395973206  (0.580687512728301)

   --> STEP: 45
     | > decoder_loss: 0.4437059760093689  (0.4452507807148827)
     | > postnet_loss: 0.3026071786880493  (0.30501920448409187)
     | > stopnet_loss: 0.003310329047963023  (0.004998498347898325)
     | > loss: 0.1898886114358902  (0.1925659934679667)
     | > align_error: 0.5538003146648407  (0.5800900194380019)

   --> STEP: 46
     | > decoder_loss: 0.433076411485672  (0.44498612051424774)
     | > postnet_loss: 0.2933593988418579  (0.3047657304483911)
     | > stopnet_loss: 0.003198181511834264  (0.004959361025375194)
     | > loss: 0.18480712175369263  (0.19239732234374338)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3519455302845347 (-0.04223728179931646)
     | > avg_decoder_loss: 0.4410166821696542 (+0.0006966405745708615)
     | > avg_postnet_loss: 0.30152700525341614 (-0.0007612863273331327)
     | > avg_stopnet_loss: 0.004396988234172266 (+1.3232774411640023e-05)
     | > avg_loss: 0.19003290886228735 (-2.9289812752686384e-06)
     | > avg_align_error: 0.572960778619304 (+0.0015905436241266946)


 > EPOCH: 118/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 14:19:33)

   --> TIME: 2025-12-28 14:19:43 -- STEP: 7/150 -- GLOBAL_STEP: 17825
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47399377822875977  (0.4651562486376081)
     | > postnet_loss: 0.40166154503822327  (0.3975974108491625)
     | > stopnet_loss: 0.011053726077079773  (0.013226329748119627)
     | > loss: 0.22996754944324493  (0.22891474621636526)
     | > align_error: 0.6713687777519226  (0.7046874761581421)
     | > grad_norm: tensor(0.2511, device='cuda:0')  (tensor(0.3759, device='cuda:0'))
     | > step_time: 0.4822  (0.47357187952314106)
     | > loader_time: 0.858  (0.7742774827139718)


   --> TIME: 2025-12-28 14:20:26 -- STEP: 32/150 -- GLOBAL_STEP: 17850
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.48358315229415894  (0.47340865805745125)
     | > postnet_loss: 0.40329620242118835  (0.39942128770053387)
     | > stopnet_loss: 0.0054921056143939495  (0.008921880871639587)
     | > loss: 0.22721193730831146  (0.2271293681114912)
     | > align_error: 0.6334718465805054  (0.6645997883751988)
     | > grad_norm: tensor(0.4006, device='cuda:0')  (tensor(0.3328, device='cuda:0'))
     | > step_time: 0.9544  (0.7213169634342194)
     | > loader_time: 1.0395  (0.8993485644459724)


   --> TIME: 2025-12-28 14:21:26 -- STEP: 57/150 -- GLOBAL_STEP: 17875
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4864496886730194  (0.4790798498873125)
     | > postnet_loss: 0.39990460872650146  (0.40060131225669593)
     | > stopnet_loss: 0.004587307572364807  (0.0071806818524604325)
     | > loss: 0.22617588937282562  (0.22710097332795462)
     | > align_error: 0.6573014855384827  (0.644790032976552)
     | > grad_norm: tensor(0.2240, device='cuda:0')  (tensor(0.3000, device='cuda:0'))
     | > step_time: 1.4048  (0.9311047144103468)
     | > loader_time: 1.2208  (1.0272666571433084)


   --> TIME: 2025-12-28 14:22:37 -- STEP: 82/150 -- GLOBAL_STEP: 17900
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4871944189071655  (0.4815307117816878)
     | > postnet_loss: 0.3992001712322235  (0.40032060008223463)
     | > stopnet_loss: 0.003609912469983101  (0.006219849887690169)
     | > loss: 0.2252085655927658  (0.22668267822847132)
     | > align_error: 0.6449377238750458  (0.634998388043264)
     | > grad_norm: tensor(0.2400, device='cuda:0')  (tensor(0.2789, device='cuda:0'))
     | > step_time: 1.5331  (1.0987209779460259)
     | > loader_time: 1.4489  (1.1288505065731882)


   --> TIME: 2025-12-28 14:23:58 -- STEP: 107/150 -- GLOBAL_STEP: 17925
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4892559051513672  (0.4825235563460912)
     | > postnet_loss: 0.3997250199317932  (0.3995948364244443)
     | > stopnet_loss: 0.0035629419144243  (0.005600128453398978)
     | > loss: 0.22580817341804504  (0.22612972696807898)
     | > align_error: 0.6037522256374359  (0.6299626155991424)
     | > grad_norm: tensor(0.2301, device='cuda:0')  (tensor(0.2543, device='cuda:0'))
     | > step_time: 1.7551  (1.2262373126555834)
     | > loader_time: 1.6737  (1.2433110754066534)


   --> TIME: 2025-12-28 14:25:28 -- STEP: 132/150 -- GLOBAL_STEP: 17950
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4876549541950226  (0.48339425162835553)
     | > postnet_loss: 0.3949521481990814  (0.39896142527912604)
     | > stopnet_loss: 0.003287576837465167  (0.005158791838877018)
     | > loss: 0.22393935918807983  (0.22574771161783824)
     | > align_error: 0.5906012654304504  (0.6265223778106952)
     | > grad_norm: tensor(0.1518, device='cuda:0')  (tensor(0.2407, device='cuda:0'))
     | > step_time: 2.1134  (1.3513578302932514)
     | > loader_time: 1.7161  (1.3294940337990264)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46155592799186707  (0.46155592799186707)
     | > postnet_loss: 0.33562442660331726  (0.33562442660331726)
     | > stopnet_loss: 0.012243622913956642  (0.012243622913956642)
     | > loss: 0.21153871715068817  (0.21153871715068817)
     | > align_error: 0.7187669277191162  (0.7187669277191162)

   --> STEP: 1
     | > decoder_loss: 0.44281092286109924  (0.44281092286109924)
     | > postnet_loss: 0.3237850069999695  (0.3237850069999695)
     | > stopnet_loss: 0.009603588841855526  (0.009603588841855526)
     | > loss: 0.20125257968902588  (0.20125257968902588)
     | > align_error: 0.6590904891490936  (0.6590904891490936)

   --> STEP: 2
     | > decoder_loss: 0.43834590911865234  (0.4405784159898758)
     | > postnet_loss: 0.31362825632095337  (0.3187066316604614)
     | > stopnet_loss: 0.01107046939432621  (0.010337029118090868)
     | > loss: 0.19906401634216309  (0.20015829801559448)
     | > align_error: 0.6555055379867554  (0.6572980135679245)

   --> STEP: 3
     | > decoder_loss: 0.44186288118362427  (0.4410065710544586)
     | > postnet_loss: 0.31297820806503296  (0.3167971571286519)
     | > stopnet_loss: 0.00833044108003378  (0.009668166438738504)
     | > loss: 0.19704070687294006  (0.199119100968043)
     | > align_error: 0.7344483137130737  (0.6830147802829742)

   --> STEP: 4
     | > decoder_loss: 0.448070228099823  (0.4427724853157997)
     | > postnet_loss: 0.3215593993663788  (0.31798771768808365)
     | > stopnet_loss: 0.008223616518080235  (0.009307028958573937)
     | > loss: 0.2006310224533081  (0.19949708133935928)
     | > align_error: 0.6031749844551086  (0.6630548313260078)

   --> STEP: 5
     | > decoder_loss: 0.42958152294158936  (0.4401342928409576)
     | > postnet_loss: 0.30404168367385864  (0.31519851088523865)
     | > stopnet_loss: 0.008206883445382118  (0.009086999855935574)
     | > loss: 0.19161269068717957  (0.19792020320892334)
     | > align_error: 0.6417351365089417  (0.6587908923625946)

   --> STEP: 6
     | > decoder_loss: 0.4457859396934509  (0.44107623398303986)
     | > postnet_loss: 0.3158569037914276  (0.31530824303627014)
     | > stopnet_loss: 0.007267228793352842  (0.008783704678838452)
     | > loss: 0.19767792522907257  (0.19787982354561487)
     | > align_error: 0.5933875441551208  (0.6478903343280157)

   --> STEP: 7
     | > decoder_loss: 0.4583861827850342  (0.44354908381189617)
     | > postnet_loss: 0.3159119188785553  (0.3153944824423109)
     | > stopnet_loss: 0.006312383804470301  (0.008430658839643002)
     | > loss: 0.19988690316677094  (0.19816654920578003)
     | > align_error: 0.5784017443656921  (0.6379633929048266)

   --> STEP: 8
     | > decoder_loss: 0.4527972936630249  (0.4447051100432873)
     | > postnet_loss: 0.316658616065979  (0.3155524991452694)
     | > stopnet_loss: 0.007194915786385536  (0.008276190957985818)
     | > loss: 0.19955889880657196  (0.19834059290587902)
     | > align_error: 0.5746020078659058  (0.6300432197749615)

   --> STEP: 9
     | > decoder_loss: 0.4481021463871002  (0.44508255852593315)
     | > postnet_loss: 0.31458109617233276  (0.31544456548160976)
     | > stopnet_loss: 0.006669984199106693  (0.008097723540332582)
     | > loss: 0.19734080135822296  (0.19822950495613945)
     | > align_error: 0.5909595191478729  (0.6257005863719516)

   --> STEP: 10
     | > decoder_loss: 0.4747070074081421  (0.44804500341415404)
     | > postnet_loss: 0.3300822079181671  (0.3169083297252655)
     | > stopnet_loss: 0.0055528548546135426  (0.007843236671760678)
     | > loss: 0.20675015449523926  (0.19908156991004944)
     | > align_error: 0.5833544135093689  (0.6214659690856934)

   --> STEP: 11
     | > decoder_loss: 0.46137991547584534  (0.4492572681470351)
     | > postnet_loss: 0.3192479610443115  (0.3171210234815424)
     | > stopnet_loss: 0.005901705473661423  (0.007666733835569837)
     | > loss: 0.20105867087841034  (0.1992613063617186)
     | > align_error: 0.5944544970989227  (0.6190103807232596)

   --> STEP: 12
     | > decoder_loss: 0.45694500207901  (0.4498979126413663)
     | > postnet_loss: 0.3129950165748596  (0.31677718957265216)
     | > stopnet_loss: 0.007899255491793156  (0.007686110640255113)
     | > loss: 0.200384259223938  (0.19935488576690355)
     | > align_error: 0.5871489346027374  (0.6163552602132162)

   --> STEP: 13
     | > decoder_loss: 0.44701260328292847  (0.44967596576764035)
     | > postnet_loss: 0.31322136521339417  (0.31650366462194)
     | > stopnet_loss: 0.005603115074336529  (0.00752588021210753)
     | > loss: 0.19566161930561066  (0.1990707883468041)
     | > align_error: 0.5858786106109619  (0.6140109025515043)

   --> STEP: 14
     | > decoder_loss: 0.4583165943622589  (0.4502931535243988)
     | > postnet_loss: 0.31627094745635986  (0.31648704196725574)
     | > stopnet_loss: 0.004951809998601675  (0.007342018053999969)
     | > loss: 0.1985986828804016  (0.19903706652777536)
     | > align_error: 0.5546425580978394  (0.6097703065190997)

   --> STEP: 15
     | > decoder_loss: 0.45474258065223694  (0.450589781999588)
     | > postnet_loss: 0.3147890567779541  (0.3163738429546356)
     | > stopnet_loss: 0.005008832085877657  (0.007186472322791815)
     | > loss: 0.19739173352718353  (0.19892737766106924)
     | > align_error: 0.5882031917572021  (0.6083324988683064)

   --> STEP: 16
     | > decoder_loss: 0.4556351602077484  (0.45090511813759804)
     | > postnet_loss: 0.30900537967681885  (0.31591331399977207)
     | > stopnet_loss: 0.005249770823866129  (0.0070654284791089594)
     | > loss: 0.1964099109172821  (0.19877003598958254)
     | > align_error: 0.6058146357536316  (0.6081751324236393)

   --> STEP: 17
     | > decoder_loss: 0.4612581133842468  (0.4515141178579891)
     | > postnet_loss: 0.3167782127857208  (0.3159641903989455)
     | > stopnet_loss: 0.004843283910304308  (0.006934714092708686)
     | > loss: 0.19935236871242523  (0.19880429085563212)
     | > align_error: 0.5583685338497162  (0.6052453325075262)

   --> STEP: 18
     | > decoder_loss: 0.4566749036312103  (0.45180082817872363)
     | > postnet_loss: 0.3100581169128418  (0.3156360752052731)
     | > stopnet_loss: 0.005256905220448971  (0.006841502488694257)
     | > loss: 0.19694016873836517  (0.19870072851578394)
     | > align_error: 0.6039959192276001  (0.6051759206586413)

   --> STEP: 19
     | > decoder_loss: 0.453616201877594  (0.4518963741628747)
     | > postnet_loss: 0.3090997636318207  (0.31529205880667033)
     | > stopnet_loss: 0.004732859320938587  (0.006730521269338696)
     | > loss: 0.19541184604167938  (0.1985276294381995)
     | > align_error: 0.5995039343833923  (0.6048773950652072)

   --> STEP: 20
     | > decoder_loss: 0.45091959834098816  (0.4518475353717804)
     | > postnet_loss: 0.30589863657951355  (0.3148223876953125)
     | > stopnet_loss: 0.004511487204581499  (0.006619569566100836)
     | > loss: 0.19371604919433594  (0.1982870504260063)
     | > align_error: 0.6228134036064148  (0.6057741954922676)

   --> STEP: 21
     | > decoder_loss: 0.44891831278800964  (0.451708048582077)
     | > postnet_loss: 0.3054921329021454  (0.31437808984801885)
     | > stopnet_loss: 0.003990279510617256  (0.006494365277744475)
     | > loss: 0.19259288907051086  (0.19801589988526844)
     | > align_error: 0.5602216124534607  (0.603605024871372)

   --> STEP: 22
     | > decoder_loss: 0.4512135684490204  (0.45168557221239264)
     | > postnet_loss: 0.30842670798301697  (0.31410757249051874)
     | > stopnet_loss: 0.004863109439611435  (0.006420217285102064)
     | > loss: 0.19477318227291107  (0.19786850363016129)
     | > align_error: 0.6254844069480896  (0.6045995422384955)

   --> STEP: 23
     | > decoder_loss: 0.42399704456329346  (0.45048172318417096)
     | > postnet_loss: 0.2961920499801636  (0.313328636729199)
     | > stopnet_loss: 0.004499785136431456  (0.0063367202351598635)
     | > loss: 0.1845470517873764  (0.19728931007177933)
     | > align_error: 0.5674384832382202  (0.6029838440210923)

   --> STEP: 24
     | > decoder_loss: 0.45759862661361694  (0.4507782608270645)
     | > postnet_loss: 0.31094130873680115  (0.31322916472951573)
     | > stopnet_loss: 0.004414611961692572  (0.00625663239043206)
     | > loss: 0.19654959440231323  (0.1972584885855516)
     | > align_error: 0.5796903371810913  (0.6020132812360922)

   --> STEP: 25
     | > decoder_loss: 0.45639294385910034  (0.45100284814834596)
     | > postnet_loss: 0.3082256317138672  (0.3130290234088898)
     | > stopnet_loss: 0.003708354663103819  (0.00615470128133893)
     | > loss: 0.1948629915714264  (0.19716266870498658)
     | > align_error: 0.5575980246067047  (0.6002366709709167)

   --> STEP: 26
     | > decoder_loss: 0.4328162968158722  (0.45030336540478927)
     | > postnet_loss: 0.2979751527309418  (0.3124500283828148)
     | > stopnet_loss: 0.0043678563088178635  (0.006085976474703505)
     | > loss: 0.1870657205581665  (0.19677432454549348)
     | > align_error: 0.5468265414237976  (0.5981824352191044)

   --> STEP: 27
     | > decoder_loss: 0.42836353182792664  (0.4494907789760166)
     | > postnet_loss: 0.29190054535865784  (0.3116889364189572)
     | > stopnet_loss: 0.003648475045338273  (0.005995698643986274)
     | > loss: 0.18371449410915375  (0.19629062712192535)
     | > align_error: 0.540483146905899  (0.5960454245408376)

   --> STEP: 28
     | > decoder_loss: 0.43535763025283813  (0.4489860236644745)
     | > postnet_loss: 0.2973393201828003  (0.3111764501248087)
     | > stopnet_loss: 0.003925149794667959  (0.005921750470796334)
     | > loss: 0.1870993822813034  (0.19596236837761744)
     | > align_error: 0.5664955675601959  (0.5949900725058147)

   --> STEP: 29
     | > decoder_loss: 0.4310181438922882  (0.44836644160336464)
     | > postnet_loss: 0.2943841814994812  (0.31059740637910777)
     | > stopnet_loss: 0.003574961796402931  (0.005840826723403458)
     | > loss: 0.18492555618286133  (0.19558178864676376)
     | > align_error: 0.5406676530838013  (0.5931168856291935)

   --> STEP: 30
     | > decoder_loss: 0.43102413415908813  (0.4477883646885554)
     | > postnet_loss: 0.294758141040802  (0.3100694308678309)
     | > stopnet_loss: 0.0028250503819435835  (0.005740300845354795)
     | > loss: 0.18427062034606934  (0.1952047497034073)
     | > align_error: 0.5334687232971191  (0.5911286135514577)

   --> STEP: 31
     | > decoder_loss: 0.42701777815818787  (0.44711834576822096)
     | > postnet_loss: 0.293165385723114  (0.3095241390889691)
     | > stopnet_loss: 0.0036873063072562218  (0.005674075215093551)
     | > loss: 0.18373309075832367  (0.19483469618904975)
     | > align_error: 0.5559377372264862  (0.5899934239925877)

   --> STEP: 32
     | > decoder_loss: 0.4380883574485779  (0.4468361586332321)
     | > postnet_loss: 0.29893943667411804  (0.309193367138505)
     | > stopnet_loss: 0.0038521140813827515  (0.005617138929665089)
     | > loss: 0.18810905516147614  (0.19462451990693808)
     | > align_error: 0.5309495329856873  (0.588148302398622)

   --> STEP: 33
     | > decoder_loss: 0.43531322479248047  (0.446486978819876)
     | > postnet_loss: 0.29651984572410583  (0.30880932103503833)
     | > stopnet_loss: 0.00403217040002346  (0.005569109580282009)
     | > loss: 0.18699043989181519  (0.19439318414890405)
     | > align_error: 0.5461378693580627  (0.5868752589731505)

   --> STEP: 34
     | > decoder_loss: 0.4411846697330475  (0.44633102855261636)
     | > postnet_loss: 0.2980508804321289  (0.30849289631142335)
     | > stopnet_loss: 0.003309389343485236  (0.005502647220376222)
     | > loss: 0.18811826407909393  (0.19420862767626257)
     | > align_error: 0.5638478994369507  (0.5861979836926741)

   --> STEP: 35
     | > decoder_loss: 0.4385750889778137  (0.44610943027905053)
     | > postnet_loss: 0.29767778515815735  (0.3081838931356158)
     | > stopnet_loss: 0.0035244293976575136  (0.005446126711155687)
     | > loss: 0.1875876486301422  (0.19401945684637342)
     | > align_error: 0.5331012606620789  (0.5846809344632286)

   --> STEP: 36
     | > decoder_loss: 0.4440833032131195  (0.4460531489716636)
     | > postnet_loss: 0.30137038230895996  (0.30799462894598645)
     | > stopnet_loss: 0.003663209266960621  (0.005396601226594713)
     | > loss: 0.1900266408920288  (0.19390854529208607)
     | > align_error: 0.6339970827102661  (0.5860508274700907)

   --> STEP: 37
     | > decoder_loss: 0.43743765354156494  (0.4458202977438231)
     | > postnet_loss: 0.29882869124412537  (0.3077469008999902)
     | > stopnet_loss: 0.003561333753168583  (0.0053469994029886015)
     | > loss: 0.18762792646884918  (0.193738798837404)
     | > align_error: 0.5191949009895325  (0.5842439105381838)

   --> STEP: 38
     | > decoder_loss: 0.4246017336845398  (0.44526191447910507)
     | > postnet_loss: 0.291133314371109  (0.3073097012544933)
     | > stopnet_loss: 0.0031401067972183228  (0.00528892328178412)
     | > loss: 0.18207387626171112  (0.19343182719067523)
     | > align_error: 0.5517588257789612  (0.5833890398866253)

   --> STEP: 39
     | > decoder_loss: 0.4393470585346222  (0.4451102515061696)
     | > postnet_loss: 0.3014495372772217  (0.3071594406396915)
     | > stopnet_loss: 0.0034745337907224894  (0.005242400474321001)
     | > loss: 0.18867367506027222  (0.19330982328989568)
     | > align_error: 0.5456537008285522  (0.5824214670902644)

   --> STEP: 40
     | > decoder_loss: 0.4372955560684204  (0.4449148841202259)
     | > postnet_loss: 0.3002357482910156  (0.3069863483309746)
     | > stopnet_loss: 0.0030292461160570383  (0.0051870716153644015)
     | > loss: 0.1874120682477951  (0.19316237941384318)
     | > align_error: 0.5839860141277313  (0.5824605807662011)

   --> STEP: 41
     | > decoder_loss: 0.4279807507991791  (0.44450185647824914)
     | > postnet_loss: 0.29270535707473755  (0.3066380314710664)
     | > stopnet_loss: 0.003729235613718629  (0.005151514639714504)
     | > loss: 0.18390075862407684  (0.19293648622384887)
     | > align_error: 0.5033957660198212  (0.5805321706504357)

   --> STEP: 42
     | > decoder_loss: 0.4319417178630829  (0.44420280555884045)
     | > postnet_loss: 0.2940313518047333  (0.3063378724313918)
     | > stopnet_loss: 0.0032862506341189146  (0.0051071035919622275)
     | > loss: 0.18477952480316162  (0.19274227285668963)
     | > align_error: 0.579836368560791  (0.5805156039340156)

   --> STEP: 43
     | > decoder_loss: 0.43188339471817017  (0.4439163076323132)
     | > postnet_loss: 0.29324600100517273  (0.30603341030520065)
     | > stopnet_loss: 0.002927629742771387  (0.005056418153608952)
     | > loss: 0.18420997262001038  (0.19254384726979012)
     | > align_error: 0.5516673624515533  (0.5798447145972141)

   --> STEP: 44
     | > decoder_loss: 0.44923505187034607  (0.4440371881831776)
     | > postnet_loss: 0.30401307344436646  (0.3059874935583635)
     | > stopnet_loss: 0.0026708997320383787  (0.005002201825845984)
     | > loss: 0.19098292291164398  (0.1925083717161959)
     | > align_error: 0.5510703921318054  (0.5791907527230002)

   --> STEP: 45
     | > decoder_loss: 0.4423111379146576  (0.4439988315105438)
     | > postnet_loss: 0.30286651849746704  (0.3059181385570103)
     | > stopnet_loss: 0.003302104538306594  (0.004964421886122886)
     | > loss: 0.1895965039730072  (0.19244366354412504)
     | > align_error: 0.5529133677482605  (0.5786068108346727)

   --> STEP: 46
     | > decoder_loss: 0.4327833950519562  (0.44375501767448755)
     | > postnet_loss: 0.29439839720726013  (0.3056677093972331)
     | > stopnet_loss: 0.0031897486187517643  (0.004925842032484383)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3691107323675445 (+0.017165202083009812)
     | > avg_decoder_loss: 0.4398606970454707 (-0.0011559851241834673)
     | > avg_postnet_loss: 0.3026612893198476 (+0.0011342840664314568)
     | > avg_stopnet_loss: 0.004365877710480354 (-3.1110523691911876e-05)
     | > avg_loss: 0.1899963736985669 (-3.6535163720458064e-05)
     | > avg_align_error: 0.5715470034064669 (-0.0014137752128370318)


 > EPOCH: 119/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 14:28:47)

   --> TIME: 2025-12-28 14:28:55 -- STEP: 6/150 -- GLOBAL_STEP: 17975
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4566669762134552  (0.4619741241137187)
     | > postnet_loss: 0.3894343078136444  (0.39541221658388775)
     | > stopnet_loss: 0.011970148421823978  (0.013683961549152931)
     | > loss: 0.2234954684972763  (0.22803054501612982)
     | > align_error: 0.7008399963378906  (0.7094381749629974)
     | > grad_norm: tensor(0.3158, device='cuda:0')  (tensor(0.3361, device='cuda:0'))
     | > step_time: 0.5074  (0.4654009739557902)
     | > loader_time: 0.8208  (0.6681124369303385)


   --> TIME: 2025-12-28 14:29:38 -- STEP: 31/150 -- GLOBAL_STEP: 18000
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.4833903908729553  (0.4724441218760706)
     | > postnet_loss: 0.4036521315574646  (0.39889723158651785)
     | > stopnet_loss: 0.006496325135231018  (0.00904235664394594)
     | > loss: 0.228256955742836  (0.22687769657181156)
     | > align_error: 0.6470300555229187  (0.6656279515835547)
     | > grad_norm: tensor(0.2164, device='cuda:0')  (tensor(0.2985, device='cuda:0'))
     | > step_time: 0.9869  (0.7181582143229823)
     | > loader_time: 1.0101  (0.8854334508219073)


   --> TIME: 2025-12-28 14:30:35 -- STEP: 56/150 -- GLOBAL_STEP: 18025
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48291274905204773  (0.4783053094787257)
     | > postnet_loss: 0.39790078997612  (0.4002126944916589)
     | > stopnet_loss: 0.004634773824363947  (0.007227017968294343)
     | > loss: 0.22483815252780914  (0.22685652013335908)
     | > align_error: 0.6141595542430878  (0.644395359392677)
     | > grad_norm: tensor(0.2528, device='cuda:0')  (tensor(0.2776, device='cuda:0'))
     | > step_time: 1.3672  (0.9324212074279785)
     | > loader_time: 1.2697  (0.9796241351536342)


   --> TIME: 2025-12-28 14:31:47 -- STEP: 81/150 -- GLOBAL_STEP: 18050
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4950467348098755  (0.4811742044525382)
     | > postnet_loss: 0.40341493487358093  (0.40006750343758374)
     | > stopnet_loss: 0.0036409609019756317  (0.006245030124706249)
     | > loss: 0.22825638949871063  (0.2265554580055637)
     | > align_error: 0.693637490272522  (0.6348354680302702)
     | > grad_norm: tensor(0.2332, device='cuda:0')  (tensor(0.2573, device='cuda:0'))
     | > step_time: 1.6637  (1.107497403651108)
     | > loader_time: 1.6354  (1.0949196697753152)


   --> TIME: 2025-12-28 14:33:17 -- STEP: 106/150 -- GLOBAL_STEP: 18075
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4838062822818756  (0.48236577634541494)
     | > postnet_loss: 0.39539945125579834  (0.39946514874134414)
     | > stopnet_loss: 0.003265176899731159  (0.005621900000029576)
     | > loss: 0.22306659817695618  (0.22607963152651517)
     | > align_error: 0.6243157982826233  (0.6299534313521296)
     | > grad_norm: tensor(0.1480, device='cuda:0')  (tensor(0.2398, device='cuda:0'))
     | > step_time: 1.7203  (1.2581253569081148)
     | > loader_time: 1.9344  (1.27335509039321)


   --> TIME: 2025-12-28 14:34:50 -- STEP: 131/150 -- GLOBAL_STEP: 18100
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48831039667129517  (0.4832940235847735)
     | > postnet_loss: 0.3961828052997589  (0.3988810955113126)
     | > stopnet_loss: 0.003131067380309105  (0.005168627881807566)
     | > loss: 0.22425436973571777  (0.2257124078637771)
     | > align_error: 0.5927757620811462  (0.6266030933110769)
     | > grad_norm: tensor(0.2409, device='cuda:0')  (tensor(0.2290, device='cuda:0'))
     | > step_time: 2.1169  (1.3854310366943594)
     | > loader_time: 1.8693  (1.3715584241706904)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4608668386936188  (0.4608668386936188)
     | > postnet_loss: 0.3327937424182892  (0.3327937424182892)
     | > stopnet_loss: 0.012186571955680847  (0.012186571955680847)
     | > loss: 0.21060171723365784  (0.21060171723365784)
     | > align_error: 0.719103991985321  (0.719103991985321)

   --> STEP: 1
     | > decoder_loss: 0.4429423213005066  (0.4429423213005066)
     | > postnet_loss: 0.3206593990325928  (0.3206593990325928)
     | > stopnet_loss: 0.009644459933042526  (0.009644459933042526)
     | > loss: 0.20054489374160767  (0.20054489374160767)
     | > align_error: 0.659555971622467  (0.659555971622467)

   --> STEP: 2
     | > decoder_loss: 0.4389742314815521  (0.44095827639102936)
     | > postnet_loss: 0.3122120797634125  (0.3164357393980026)
     | > stopnet_loss: 0.011049517430365086  (0.010346988681703806)
     | > loss: 0.19884610176086426  (0.19969549775123596)
     | > align_error: 0.655799925327301  (0.657677948474884)

   --> STEP: 3
     | > decoder_loss: 0.4412410855293274  (0.44105254610379535)
     | > postnet_loss: 0.3103611469268799  (0.31441087524096173)
     | > stopnet_loss: 0.008260708302259445  (0.009651561888555685)
     | > loss: 0.19616127014160156  (0.19851742188135782)
     | > align_error: 0.734470397233963  (0.683275431394577)

   --> STEP: 4
     | > decoder_loss: 0.4473896920681  (0.4426368325948715)
     | > postnet_loss: 0.31915202736854553  (0.31559616327285767)
     | > stopnet_loss: 0.008198832161724567  (0.009288379456847906)
     | > loss: 0.19983425736427307  (0.19884663075208664)
     | > align_error: 0.6034948229789734  (0.6633302792906761)

   --> STEP: 5
     | > decoder_loss: 0.42911678552627563  (0.43993282318115234)
     | > postnet_loss: 0.30197301506996155  (0.31287153363227843)
     | > stopnet_loss: 0.008150794543325901  (0.009060862474143505)
     | > loss: 0.19092325866222382  (0.19726195633411409)
     | > align_error: 0.6419144868850708  (0.6590471208095551)

   --> STEP: 6
     | > decoder_loss: 0.4454984962940216  (0.44086043536663055)
     | > postnet_loss: 0.31365707516670227  (0.31300245722134906)
     | > stopnet_loss: 0.007237453944981098  (0.008756961052616438)
     | > loss: 0.1970263421535492  (0.19722268730401993)
     | > align_error: 0.5938073396682739  (0.6481738239526749)

   --> STEP: 7
     | > decoder_loss: 0.4564858078956604  (0.44309263144220623)
     | > postnet_loss: 0.31333109736442566  (0.31304940581321716)
     | > stopnet_loss: 0.006262973882257938  (0.008400677171136652)
     | > loss: 0.19871719181537628  (0.1974361879484994)
     | > align_error: 0.5788654685020447  (0.6382726303168705)

   --> STEP: 8
     | > decoder_loss: 0.4532064199447632  (0.44435685500502586)
     | > postnet_loss: 0.31503602862358093  (0.31329773366451263)
     | > stopnet_loss: 0.007282515987753868  (0.008260907023213804)
     | > loss: 0.19934312999248505  (0.1976745557039976)
     | > align_error: 0.5754175186157227  (0.6304157413542271)

   --> STEP: 9
     | > decoder_loss: 0.4494076371192932  (0.44491805301772225)
     | > postnet_loss: 0.3138587474822998  (0.3133600685331557)
     | > stopnet_loss: 0.006631850264966488  (0.00807990071674188)
     | > loss: 0.19744844734668732  (0.19764943255318534)
     | > align_error: 0.5912662744522095  (0.6260658005873362)

   --> STEP: 10
     | > decoder_loss: 0.4745907783508301  (0.447885325551033)
     | > postnet_loss: 0.32800665497779846  (0.31482472717761995)
     | > stopnet_loss: 0.005554410628974438  (0.007827351707965136)
     | > loss: 0.20620375871658325  (0.19850486516952515)
     | > align_error: 0.5836061239242554  (0.6218198329210282)

   --> STEP: 11
     | > decoder_loss: 0.4610084593296051  (0.4490783377127214)
     | > postnet_loss: 0.3183782994747162  (0.31514777920462866)
     | > stopnet_loss: 0.005870281718671322  (0.007649436254392971)
     | > loss: 0.20071697235107422  (0.19870596582239325)
     | > align_error: 0.5947673320770264  (0.6193605146624825)

   --> STEP: 12
     | > decoder_loss: 0.4570566713809967  (0.44974319885174435)
     | > postnet_loss: 0.311588853597641  (0.31485120207071304)
     | > stopnet_loss: 0.007892336696386337  (0.007669677957892418)
     | > loss: 0.20005372166633606  (0.1988182788093885)
     | > align_error: 0.5875504612922668  (0.6167096768816313)

   --> STEP: 13
     | > decoder_loss: 0.4473232924938202  (0.4495570522088271)
     | > postnet_loss: 0.3119129240512848  (0.31462518068460316)
     | > stopnet_loss: 0.005575917661190033  (0.007508619473530696)
     | > loss: 0.19538497924804688  (0.19855417884313142)
     | > align_error: 0.5862367153167725  (0.6143656029151037)

   --> STEP: 14
     | > decoder_loss: 0.45728814601898193  (0.4501092731952667)
     | > postnet_loss: 0.31441956758499146  (0.3146104940346309)
     | > stopnet_loss: 0.0049519785679876804  (0.007326002265991909)
     | > loss: 0.1978789120912552  (0.1985059455037117)
     | > align_error: 0.5548403859138489  (0.6101138017007283)

   --> STEP: 15
     | > decoder_loss: 0.45514506101608276  (0.45044499238332114)
     | > postnet_loss: 0.3145725429058075  (0.314607963959376)
     | > stopnet_loss: 0.004987923428416252  (0.007170130343486865)
     | > loss: 0.19741731882095337  (0.1984333703915278)
     | > align_error: 0.5886971056461334  (0.6086860219637553)

   --> STEP: 16
     | > decoder_loss: 0.4555591642856598  (0.4507646281272173)
     | > postnet_loss: 0.3082320988178253  (0.3142094723880291)
     | > stopnet_loss: 0.005265955347567797  (0.007051119406241924)
     | > loss: 0.1962137669324875  (0.1982946451753378)
     | > align_error: 0.6062203347682953  (0.608531916514039)

   --> STEP: 17
     | > decoder_loss: 0.4631454050540924  (0.45149290912291584)
     | > postnet_loss: 0.31762850284576416  (0.3144105918267194)
     | > stopnet_loss: 0.004853323567658663  (0.006921837298089967)
     | > loss: 0.20004679262638092  (0.19839771267245798)
     | > align_error: 0.5586853921413422  (0.6055997680215275)

   --> STEP: 18
     | > decoder_loss: 0.457053005695343  (0.45180180337693954)
     | > postnet_loss: 0.3097688555717468  (0.31415271759033203)
     | > stopnet_loss: 0.005251611582934856  (0.00682904698058135)
     | > loss: 0.1969570815563202  (0.19831767761045033)
     | > align_error: 0.6042557656764984  (0.6055251012245814)

   --> STEP: 19
     | > decoder_loss: 0.4531063437461853  (0.45187046339637355)
     | > postnet_loss: 0.3082501292228699  (0.3138420550446761)
     | > stopnet_loss: 0.004731396678835154  (0.006718644333121024)
     | > loss: 0.1950705200433731  (0.19814677458060415)
     | > align_error: 0.599589616060257  (0.6052127072685644)

   --> STEP: 20
     | > decoder_loss: 0.45088523626327515  (0.45182120203971865)
     | > postnet_loss: 0.30556491017341614  (0.31342819780111314)
     | > stopnet_loss: 0.004496361594647169  (0.006607530196197331)
     | > loss: 0.19360890984535217  (0.19791988134384156)
     | > align_error: 0.6231492459774017  (0.6061095342040062)

   --> STEP: 21
     | > decoder_loss: 0.4492998719215393  (0.45170113870075773)
     | > postnet_loss: 0.30486828088760376  (0.3130205827099936)
     | > stopnet_loss: 0.00396637711673975  (0.006481761001937446)
     | > loss: 0.19250841438770294  (0.19766219244116828)
     | > align_error: 0.5605444610118866  (0.6039397688139052)

   --> STEP: 22
     | > decoder_loss: 0.4502030909061432  (0.4516330456191843)
     | > postnet_loss: 0.3071463704109192  (0.31275357306003565)
     | > stopnet_loss: 0.004884304013103247  (0.0064091493206268006)
     | > loss: 0.19422167539596558  (0.19750580530274997)
     | > align_error: 0.6257020533084869  (0.6049289635636589)

   --> STEP: 23
     | > decoder_loss: 0.4238252639770508  (0.4504240116347437)
     | > postnet_loss: 0.29522743821144104  (0.3119915671970533)
     | > stopnet_loss: 0.004537178203463554  (0.006327759272054485)
     | > loss: 0.18430034816265106  (0.19693165499231088)
     | > align_error: 0.5679028034210205  (0.603319130513979)

   --> STEP: 24
     | > decoder_loss: 0.4579077661037445  (0.45073583473761875)
     | > postnet_loss: 0.31078040599823  (0.3119411021471023)
     | > stopnet_loss: 0.004412014503031969  (0.006247936573345214)
     | > loss: 0.1965840607881546  (0.19691717190047106)
     | > align_error: 0.5800527930259705  (0.602349699785312)

   --> STEP: 25
     | > decoder_loss: 0.4565815031528473  (0.4509696614742279)
     | > postnet_loss: 0.3077961504459381  (0.31177530407905574)
     | > stopnet_loss: 0.003716586623340845  (0.0061466825753450395)
     | > loss: 0.19481100142002106  (0.19683292508125305)
     | > align_error: 0.5579016208648682  (0.6005717766284943)

   --> STEP: 26
     | > decoder_loss: 0.43292781710624695  (0.4502757443831517)
     | > postnet_loss: 0.2969898283481598  (0.3112066319355598)
     | > stopnet_loss: 0.004369761794805527  (0.006078339468401212)
     | > loss: 0.1868491768836975  (0.19644893476596245)
     | > align_error: 0.5474019050598145  (0.5985267815681604)

   --> STEP: 27
     | > decoder_loss: 0.428718239068985  (0.4494773182604048)
     | > postnet_loss: 0.29168224334716797  (0.310483506432286)
     | > stopnet_loss: 0.003648885292932391  (0.005988359684124589)
     | > loss: 0.1837490051984787  (0.1959785670042038)
     | > align_error: 0.5406918525695801  (0.5963847471608056)

   --> STEP: 28
     | > decoder_loss: 0.43510371446609497  (0.4489639752677509)
     | > postnet_loss: 0.29662463068962097  (0.30998854658433367)
     | > stopnet_loss: 0.003927275072783232  (0.005914749519433826)
     | > loss: 0.1868593543767929  (0.1956528808389391)
     | > align_error: 0.5669364631175995  (0.5953330227306911)

   --> STEP: 29
     | > decoder_loss: 0.43060752749443054  (0.4483309943100502)
     | > postnet_loss: 0.2933539152145386  (0.3094149386060649)
     | > stopnet_loss: 0.0035732705146074295  (0.005834008864094985)
     | > loss: 0.18456363677978516  (0.1952704931127614)
     | > align_error: 0.5411067605018616  (0.5934631516193521)

   --> STEP: 30
     | > decoder_loss: 0.43110379576683044  (0.4477567543586095)
     | > postnet_loss: 0.29393067955970764  (0.30889879663785297)
     | > stopnet_loss: 0.0028123718220740557  (0.005733287629360954)
     | > loss: 0.18407098948955536  (0.1948971763253212)
     | > align_error: 0.5338806509971619  (0.5914770682652791)

   --> STEP: 31
     | > decoder_loss: 0.42747753858566284  (0.4471025861078693)
     | > postnet_loss: 0.2931884527206421  (0.308392011350201)
     | > stopnet_loss: 0.0037141141947358847  (0.0056681530024375645)
     | > loss: 0.18388061225414276  (0.19454180329076706)
     | > align_error: 0.5567809045314789  (0.590357837177092)

   --> STEP: 32
     | > decoder_loss: 0.4381864070892334  (0.44682395551353693)
     | > postnet_loss: 0.29844173789024353  (0.30808106530457735)
     | > stopnet_loss: 0.0038542619440704584  (0.0056114689068635926)
     | > loss: 0.1880113035440445  (0.19433772517368197)
     | > align_error: 0.5317362546920776  (0.5885259127244353)

   --> STEP: 33
     | > decoder_loss: 0.4358315169811249  (0.446490851315585)
     | > postnet_loss: 0.29667988419532776  (0.3077355749679334)
     | > stopnet_loss: 0.0040317317470908165  (0.005563598083840175)
     | > loss: 0.18715958297252655  (0.1941202057130409)
     | > align_error: 0.5465519428253174  (0.5872539742426439)

   --> STEP: 34
     | > decoder_loss: 0.4407872259616852  (0.44632309762870565)
     | > postnet_loss: 0.29760298132896423  (0.30743755750796375)
     | > stopnet_loss: 0.00331177469342947  (0.005497367984122213)
     | > loss: 0.1879093199968338  (0.1939375326037407)
     | > align_error: 0.5641477704048157  (0.5865743800121195)

   --> STEP: 35
     | > decoder_loss: 0.4382951259613037  (0.446093727009637)
     | > postnet_loss: 0.29711273312568665  (0.30714256252561295)
     | > stopnet_loss: 0.0035244424361735582  (0.005440998682752251)
     | > loss: 0.18737639486789703  (0.19375007152557372)
     | > align_error: 0.5335500538349152  (0.5850593992641994)

   --> STEP: 36
     | > decoder_loss: 0.4448731243610382  (0.44605982138050926)
     | > postnet_loss: 0.3016268312931061  (0.30698934776915443)
     | > stopnet_loss: 0.003660766175016761  (0.005391547779759599)
     | > loss: 0.19028575718402863  (0.19365384057164192)
     | > align_error: 0.6343762874603271  (0.5864293128252029)

   --> STEP: 37
     | > decoder_loss: 0.4374672770500183  (0.4458275904526582)
     | > postnet_loss: 0.2982631325721741  (0.306753504115182)
     | > stopnet_loss: 0.0035639642737805843  (0.005342153630949356)
     | > loss: 0.18749657273292542  (0.1934874279273523)
     | > align_error: 0.5194091200828552  (0.584617956264599)

   --> STEP: 38
     | > decoder_loss: 0.4248795211315155  (0.4452763254705228)
     | > postnet_loss: 0.2909553647041321  (0.3063377636043649)
     | > stopnet_loss: 0.003141803666949272  (0.005284249684528301)
     | > loss: 0.18210051953792572  (0.19318777244342)
     | > align_error: 0.5521714091300964  (0.5837640997610595)

   --> STEP: 39
     | > decoder_loss: 0.44015946984291077  (0.4451451240441738)
     | > postnet_loss: 0.30116257071495056  (0.30620506635079014)
     | > stopnet_loss: 0.003487755311653018  (0.005238185726249447)
     | > loss: 0.18881826102733612  (0.19307573368916145)
     | > align_error: 0.5462578535079956  (0.582802401139186)

   --> STEP: 40
     | > decoder_loss: 0.43697038292884827  (0.44494075551629064)
     | > postnet_loss: 0.2996089458465576  (0.3060401633381843)
     | > stopnet_loss: 0.0030275534372776747  (0.005182919919025153)
     | > loss: 0.18717238306999207  (0.1929281499236822)
     | > align_error: 0.5842147469520569  (0.5828377097845078)

   --> STEP: 41
     | > decoder_loss: 0.4279932677745819  (0.4445274021567368)
     | > postnet_loss: 0.29208865761756897  (0.3056998827108522)
     | > stopnet_loss: 0.0037264623679220676  (0.0051473965641202)
     | > loss: 0.18374694883823395  (0.19270421818989078)
     | > align_error: 0.5037139654159546  (0.5809078623608845)

   --> STEP: 42
     | > decoder_loss: 0.4317510426044464  (0.4442232031197775)
     | > postnet_loss: 0.2936633825302124  (0.30541329937321793)
     | > stopnet_loss: 0.0032906357664614916  (0.005103187973699754)
     | > loss: 0.18464423716068268  (0.19251231387967155)
     | > align_error: 0.5801564455032349  (0.5808899714833214)

   --> STEP: 43
     | > decoder_loss: 0.4316302239894867  (0.4439303431400033)
     | > postnet_loss: 0.29308608174324036  (0.30512661989345097)
     | > stopnet_loss: 0.0029342183843255043  (0.005052746820458492)
     | > loss: 0.1841132938861847  (0.1923169878333114)
     | > align_error: 0.5519958734512329  (0.5802180157151333)

   --> STEP: 44
     | > decoder_loss: 0.4493653476238251  (0.44405386596918106)
     | > postnet_loss: 0.30347365140914917  (0.3050890524278987)
     | > stopnet_loss: 0.0026674363762140274  (0.004998535219452937)
     | > loss: 0.19087718427181244  (0.19228426502509552)
     | > align_error: 0.5514219999313354  (0.5795635608109561)

   --> STEP: 45
     | > decoder_loss: 0.44316238164901733  (0.44403405520651074)
     | > postnet_loss: 0.3030472993850708  (0.30504368013805805)
     | > stopnet_loss: 0.0033091939985752106  (0.004960994303433432)
     | > loss: 0.18986161053180695  (0.19223042825857797)
     | > align_error: 0.5531473159790039  (0.5789765331480238)

   --> STEP: 46
     | > decoder_loss: 0.43298375606536865  (0.4437938313121381)
     | > postnet_loss: 0.2939552366733551  (0.30480262701926014)
     | > stopnet_loss: 0.0032056416384875774  (0.004922834462891131)
     | > loss: 0.1849403828382492  (0.19207194901030997)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3527614672978719 (-0.016349265069672603)
     | > avg_decoder_loss: 0.43981621346690436 (-4.448357856634555e-05)
     | > avg_postnet_loss: 0.301695656595808 (-0.0009656327240396001)
     | > avg_stopnet_loss: 0.004365945425392552 (+6.771491219831338e-08)
     | > avg_loss: 0.18974391280701666 (-0.00025246089155023244)
     | > avg_align_error: 0.5719264718619259 (+0.00037946845545899777)


 > EPOCH: 120/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 14:38:09)

   --> TIME: 2025-12-28 14:38:16 -- STEP: 5/150 -- GLOBAL_STEP: 18125
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46926403045654297  (0.463627552986145)
     | > postnet_loss: 0.39908406138420105  (0.3977022171020508)
     | > stopnet_loss: 0.013221691362559795  (0.014118041843175888)
     | > loss: 0.23030872642993927  (0.22945048809051513)
     | > align_error: 0.7251414954662323  (0.7121536433696747)
     | > grad_norm: tensor(0.4465, device='cuda:0')  (tensor(0.3126, device='cuda:0'))
     | > step_time: 0.4952  (0.46398329734802246)
     | > loader_time: 0.8587  (0.7045982837677002)


   --> TIME: 2025-12-28 14:38:58 -- STEP: 30/150 -- GLOBAL_STEP: 18150
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.47932830452919006  (0.47284480432669324)
     | > postnet_loss: 0.39805033802986145  (0.399085475007693)
     | > stopnet_loss: 0.005815185606479645  (0.009089356226225696)
     | > loss: 0.22515985369682312  (0.22707192401091258)
     | > align_error: 0.6115591824054718  (0.6659927288691203)
     | > grad_norm: tensor(0.2692, device='cuda:0')  (tensor(0.2888, device='cuda:0'))
     | > step_time: 0.8897  (0.6911069393157959)
     | > loader_time: 1.0103  (0.8945799430211385)


   --> TIME: 2025-12-28 14:39:57 -- STEP: 55/150 -- GLOBAL_STEP: 18175
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48520925641059875  (0.47849395816976376)
     | > postnet_loss: 0.39804258942604065  (0.4002944686196067)
     | > stopnet_loss: 0.004279404878616333  (0.007280753696845341)
     | > loss: 0.22509236633777618  (0.22697785903107037)
     | > align_error: 0.6486046314239502  (0.6446815165606412)
     | > grad_norm: tensor(0.2130, device='cuda:0')  (tensor(0.2613, device='cuda:0'))
     | > step_time: 1.3049  (0.9143431490117854)
     | > loader_time: 1.2888  (1.011780071258545)


   --> TIME: 2025-12-28 14:41:06 -- STEP: 80/150 -- GLOBAL_STEP: 18200
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4784855842590332  (0.4808433637022972)
     | > postnet_loss: 0.39326199889183044  (0.39985255710780615)
     | > stopnet_loss: 0.004211490508168936  (0.006289131543599074)
     | > loss: 0.22214838862419128  (0.22646311055868865)
     | > align_error: 0.5865809917449951  (0.6337050378322602)
     | > grad_norm: tensor(0.1526, device='cuda:0')  (tensor(0.2434, device='cuda:0'))
     | > step_time: 1.4386  (1.0777689486742017)
     | > loader_time: 1.367  (1.1100252360105518)


   --> TIME: 2025-12-28 14:42:27 -- STEP: 105/150 -- GLOBAL_STEP: 18225
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4869079887866974  (0.4821048330693018)
     | > postnet_loss: 0.3971633315086365  (0.3992631835596902)
     | > stopnet_loss: 0.0034071761183440685  (0.00565129247094904)
     | > loss: 0.22442501783370972  (0.22599329607827323)
     | > align_error: 0.6116417050361633  (0.6295398442518143)
     | > grad_norm: tensor(0.1958, device='cuda:0')  (tensor(0.2281, device='cuda:0'))
     | > step_time: 1.7173  (1.223406880242484)
     | > loader_time: 1.6004  (1.2137274560474216)


   --> TIME: 2025-12-28 14:43:59 -- STEP: 130/150 -- GLOBAL_STEP: 18250
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48679229617118835  (0.48295175089285924)
     | > postnet_loss: 0.39632341265678406  (0.3986323409355604)
     | > stopnet_loss: 0.003087206743657589  (0.005195299256592991)
     | > loss: 0.22386613488197327  (0.22559132220653388)
     | > align_error: 0.5984517633914948  (0.6263160224144275)
     | > grad_norm: tensor(0.1320, device='cuda:0')  (tensor(0.2129, device='cuda:0'))
     | > step_time: 2.008  (1.3587686465336726)
     | > loader_time: 1.9773  (1.3184133988160354)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46090081334114075  (0.46090081334114075)
     | > postnet_loss: 0.3340098559856415  (0.3340098559856415)
     | > stopnet_loss: 0.012194403447210789  (0.012194403447210789)
     | > loss: 0.21092207729816437  (0.21092207729816437)
     | > align_error: 0.7186636626720428  (0.7186636626720428)

   --> STEP: 1
     | > decoder_loss: 0.44219937920570374  (0.44219937920570374)
     | > postnet_loss: 0.3214797377586365  (0.3214797377586365)
     | > stopnet_loss: 0.00961635448038578  (0.00961635448038578)
     | > loss: 0.20053614675998688  (0.20053614675998688)
     | > align_error: 0.6590799391269684  (0.6590799391269684)

   --> STEP: 2
     | > decoder_loss: 0.43951892852783203  (0.4408591538667679)
     | > postnet_loss: 0.31300094723701477  (0.3172403424978256)
     | > stopnet_loss: 0.010992946103215218  (0.010304650291800499)
     | > loss: 0.19912290573120117  (0.19982952624559402)
     | > align_error: 0.655247688293457  (0.6571638137102127)

   --> STEP: 3
     | > decoder_loss: 0.4419562518596649  (0.4412248531977336)
     | > postnet_loss: 0.31158721446990967  (0.3153559664885203)
     | > stopnet_loss: 0.008322826586663723  (0.00964404239008824)
     | > loss: 0.19670869410037994  (0.198789248863856)
     | > align_error: 0.7343412637710571  (0.6828896303971609)

   --> STEP: 4
     | > decoder_loss: 0.4477921426296234  (0.442866675555706)
     | > postnet_loss: 0.3204370439052582  (0.3166262358427048)
     | > stopnet_loss: 0.008208763785660267  (0.009285222738981247)
     | > loss: 0.2002660632133484  (0.1991584524512291)
     | > align_error: 0.6028858423233032  (0.6628886833786964)

   --> STEP: 5
     | > decoder_loss: 0.42907950282096863  (0.44010924100875853)
     | > postnet_loss: 0.30265915393829346  (0.3138328194618225)
     | > stopnet_loss: 0.008158676326274872  (0.009059913456439972)
     | > loss: 0.1910933554172516  (0.1975454330444336)
     | > align_error: 0.641750693321228  (0.6586610853672028)

   --> STEP: 6
     | > decoder_loss: 0.44532477855682373  (0.4409784972667694)
     | > postnet_loss: 0.31433016061782837  (0.31391570965449017)
     | > stopnet_loss: 0.007262449245899916  (0.00876033608801663)
     | > loss: 0.19717618823051453  (0.19748389224211374)
     | > align_error: 0.5931289792060852  (0.6477390676736832)

   --> STEP: 7
     | > decoder_loss: 0.45675531029701233  (0.44323232769966125)
     | > postnet_loss: 0.313757061958313  (0.3138930456978934)
     | > stopnet_loss: 0.006276196800172329  (0.008405459046896015)
     | > loss: 0.19890427589416504  (0.19768680419240678)
     | > align_error: 0.578220933675766  (0.6378079056739807)

   --> STEP: 8
     | > decoder_loss: 0.4544549584388733  (0.44463515654206276)
     | > postnet_loss: 0.31638869643211365  (0.31420500203967094)
     | > stopnet_loss: 0.0075402818620204926  (0.008297311898786575)
     | > loss: 0.20025119185447693  (0.19800735265016556)
     | > align_error: 0.574926108121872  (0.6299476809799671)

   --> STEP: 9
     | > decoder_loss: 0.45067328214645386  (0.4453060593869951)
     | > postnet_loss: 0.3152678310871124  (0.3143230941560533)
     | > stopnet_loss: 0.006567126139998436  (0.008105069036699004)
     | > loss: 0.19805240631103516  (0.1980123586124844)
     | > align_error: 0.5907927751541138  (0.6255971358882056)

   --> STEP: 10
     | > decoder_loss: 0.4742927551269531  (0.4482047289609909)
     | > postnet_loss: 0.3285406231880188  (0.3157448470592499)
     | > stopnet_loss: 0.005531943403184414  (0.007847756473347544)
     | > loss: 0.20624028146266937  (0.1988351508975029)
     | > align_error: 0.5827814340591431  (0.6213155657052993)

   --> STEP: 11
     | > decoder_loss: 0.4604467749595642  (0.4493176422335885)
     | > postnet_loss: 0.31816041469573975  (0.3159644441171126)
     | > stopnet_loss: 0.005901345517486334  (0.007670810022814708)
     | > loss: 0.20055314898490906  (0.19899133254181256)
     | > align_error: 0.5942581593990326  (0.6188558014956388)

   --> STEP: 12
     | > decoder_loss: 0.45658940076828003  (0.44992362211147946)
     | > postnet_loss: 0.31153950095176697  (0.3155956988533338)
     | > stopnet_loss: 0.007891496643424034  (0.007689200574532151)
     | > loss: 0.19992370903491974  (0.19906903058290482)
     | > align_error: 0.5871879756450653  (0.616216816008091)

   --> STEP: 13
     | > decoder_loss: 0.4469456374645233  (0.44969454636940587)
     | > postnet_loss: 0.3120001256465912  (0.31531911629896897)
     | > stopnet_loss: 0.005605984944850206  (0.007528953218402771)
     | > loss: 0.19534242153167725  (0.19878236834819502)
     | > align_error: 0.5855469703674316  (0.6138575971126556)

   --> STEP: 14
     | > decoder_loss: 0.45624586939811707  (0.45016249801431385)
     | > postnet_loss: 0.3137251138687134  (0.31520525898252216)
     | > stopnet_loss: 0.004969790577888489  (0.007346155886937465)
     | > loss: 0.1974625438451767  (0.19868809516940797)
     | > align_error: 0.5544202029705048  (0.6096120689596448)

   --> STEP: 15
     | > decoder_loss: 0.455357164144516  (0.4505088090896606)
     | > postnet_loss: 0.31441304087638855  (0.31515244444211327)
     | > stopnet_loss: 0.005020264536142349  (0.007191096463551124)
     | > loss: 0.19746281206607819  (0.198606409629186)
     | > align_error: 0.587919294834137  (0.6081658840179444)

   --> STEP: 16
     | > decoder_loss: 0.45609167218208313  (0.45085773803293705)
     | > postnet_loss: 0.3085632622241974  (0.3147406205534935)
     | > stopnet_loss: 0.005286838859319687  (0.007072080363286659)
     | > loss: 0.19645057618618011  (0.19847167003899813)
     | > align_error: 0.6055601239204407  (0.6080030240118504)

   --> STEP: 17
     | > decoder_loss: 0.4635494351387024  (0.45160430845092325)
     | > postnet_loss: 0.31735923886299133  (0.3148946569246404)
     | > stopnet_loss: 0.004825590178370476  (0.006939933881821001)
     | > loss: 0.20005276799201965  (0.19856467580094056)
     | > align_error: 0.5577611327171326  (0.6050476186415729)

   --> STEP: 18
     | > decoder_loss: 0.4573269486427307  (0.4519222329060237)
     | > postnet_loss: 0.30944573879241943  (0.31459193925062817)
     | > stopnet_loss: 0.0052663241513073444  (0.006846955563459132)
     | > loss: 0.1969594955444336  (0.19847549912002352)
     | > align_error: 0.6035577654838562  (0.6049648490216997)

   --> STEP: 19
     | > decoder_loss: 0.4545131325721741  (0.45205859604634735)
     | > postnet_loss: 0.30860358476638794  (0.31427676269882604)
     | > stopnet_loss: 0.00477317301556468  (0.0067378091135699494)
     | > loss: 0.19555234909057617  (0.19832164911847366)
     | > align_error: 0.599866509437561  (0.6046965153593766)

   --> STEP: 20
     | > decoder_loss: 0.4502457082271576  (0.4519679516553879)
     | > postnet_loss: 0.3046378195285797  (0.31379481554031374)
     | > stopnet_loss: 0.004513281397521496  (0.0066265827277675275)
     | > loss: 0.1932341605424881  (0.1980672746896744)
     | > align_error: 0.6222931146621704  (0.6055763453245163)

   --> STEP: 21
     | > decoder_loss: 0.44836872816085815  (0.45179656006041025)
     | > postnet_loss: 0.3040463328361511  (0.31333060207821073)
     | > stopnet_loss: 0.0039824978448450565  (0.006500673923818838)
     | > loss: 0.19208626449108124  (0.19778246468021757)
     | > align_error: 0.5597090721130371  (0.603392189457303)

   --> STEP: 22
     | > decoder_loss: 0.45026859641075134  (0.45172710716724396)
     | > postnet_loss: 0.3067420721054077  (0.3130311234430833)
     | > stopnet_loss: 0.004919590428471565  (0.006428806492212144)
     | > loss: 0.19417226314544678  (0.19761836461045526)
     | > align_error: 0.6248286366462708  (0.6043665734204379)

   --> STEP: 23
     | > decoder_loss: 0.42399659752845764  (0.4505214328351228)
     | > postnet_loss: 0.29508399963378906  (0.31225081371224445)
     | > stopnet_loss: 0.004523704759776592  (0.00634597598210625)
     | > loss: 0.18429385125637054  (0.19703903794288635)
     | > align_error: 0.5667052268981934  (0.6027291235716447)

   --> STEP: 24
     | > decoder_loss: 0.45832356810569763  (0.4508465218047301)
     | > postnet_loss: 0.3104068338871002  (0.3121739812195301)
     | > stopnet_loss: 0.004400440026074648  (0.0062649119839382665)
     | > loss: 0.19658304750919342  (0.1970200383414825)
     | > align_error: 0.5791057348251343  (0.6017448157072067)

   --> STEP: 25
     | > decoder_loss: 0.45747098326683044  (0.4511115002632141)
     | > postnet_loss: 0.30756261944770813  (0.3119895267486572)
     | > stopnet_loss: 0.003707432420924306  (0.006162612801417709)
     | > loss: 0.19496583938598633  (0.19693787038326263)
     | > align_error: 0.5573660731315613  (0.5999696660041809)

   --> STEP: 26
     | > decoder_loss: 0.4323112964630127  (0.4503884155016679)
     | > postnet_loss: 0.2963965833187103  (0.31138979815519774)
     | > stopnet_loss: 0.004343560431152582  (0.006092649248715203)
     | > loss: 0.1865205317735672  (0.19653720351365897)
     | > align_error: 0.5463188588619232  (0.5979061734217864)

   --> STEP: 27
     | > decoder_loss: 0.42960771918296814  (0.4496187600824568)
     | > postnet_loss: 0.29146647453308105  (0.3106518972803045)
     | > stopnet_loss: 0.00392937334254384  (0.0060125279188570045)
     | > loss: 0.18419793248176575  (0.1960801934754407)
     | > align_error: 0.5405209958553314  (0.5957807964748807)

   --> STEP: 28
     | > decoder_loss: 0.4353266954421997  (0.44910832920244764)
     | > postnet_loss: 0.2961926758289337  (0.31013549651418415)
     | > stopnet_loss: 0.003953116945922375  (0.005938977526966482)
     | > loss: 0.1868329495191574  (0.1957499347627163)
     | > align_error: 0.5655738413333893  (0.5947019766483989)

   --> STEP: 29
     | > decoder_loss: 0.43029457330703735  (0.4484595789991576)
     | > postnet_loss: 0.2928357720375061  (0.30953895429085043)
     | > stopnet_loss: 0.0035807806998491287  (0.005857660394996919)
     | > loss: 0.18436336517333984  (0.19535729443204813)
     | > align_error: 0.5397684574127197  (0.5928077173644098)

   --> STEP: 30
     | > decoder_loss: 0.4305811822414398  (0.44786363244056704)
     | > postnet_loss: 0.2933020293712616  (0.30899772346019744)
     | > stopnet_loss: 0.0028266410809010267  (0.005756626417860389)
     | > loss: 0.1837974488735199  (0.19497196624676386)
     | > align_error: 0.5326980948448181  (0.5908040632804235)

   --> STEP: 31
     | > decoder_loss: 0.4302371144294739  (0.44729503508537044)
     | > postnet_loss: 0.2933981418609619  (0.3084945111505447)
     | > stopnet_loss: 0.003796287579461932  (0.005693389681137858)
     | > loss: 0.18470510840415955  (0.1946407772840992)
     | > align_error: 0.5587809681892395  (0.5897710602129659)

   --> STEP: 32
     | > decoder_loss: 0.4394187927246094  (0.4470489025115967)
     | > postnet_loss: 0.2986025810241699  (0.3081853883340955)
     | > stopnet_loss: 0.003851634217426181  (0.005635834822896868)
     | > loss: 0.18835698068141937  (0.19444440864026546)
     | > align_error: 0.5303760170936584  (0.5879149651154876)

   --> STEP: 33
     | > decoder_loss: 0.4352131485939026  (0.4466902433019696)
     | > postnet_loss: 0.2954285144805908  (0.3077988163991408)
     | > stopnet_loss: 0.004026675596833229  (0.0055870724221070605)
     | > loss: 0.18668709695339203  (0.1942093385891481)
     | > align_error: 0.5453782081604004  (0.586625972480485)

   --> STEP: 34
     | > decoder_loss: 0.44046419858932495  (0.446507124339833)
     | > postnet_loss: 0.29674917459487915  (0.3074738269343096)
     | > stopnet_loss: 0.0033259426709264517  (0.0055205686058958665)
     | > loss: 0.18762928247451782  (0.19401580752695308)
     | > align_error: 0.5629030466079712  (0.5859282393665874)

   --> STEP: 35
     | > decoder_loss: 0.43772488832473755  (0.44625620331083027)
     | > postnet_loss: 0.29596975445747375  (0.3071451391492571)
     | > stopnet_loss: 0.0035276722628623247  (0.005463628710380622)
     | > loss: 0.18695133924484253  (0.19381396557603564)
     | > align_error: 0.5323701500892639  (0.5843980082443783)

   --> STEP: 36
     | > decoder_loss: 0.4444543123245239  (0.44620615078343284)
     | > postnet_loss: 0.300668329000473  (0.30696522775623536)
     | > stopnet_loss: 0.00365961785428226  (0.005413517297711223)
     | > loss: 0.18994028866291046  (0.19370636343955994)
     | > align_error: 0.6331421136856079  (0.5857520111733012)

   --> STEP: 37
     | > decoder_loss: 0.43682265281677246  (0.44595254273027984)
     | > postnet_loss: 0.29719191789627075  (0.30670108424650655)
     | > stopnet_loss: 0.003564919112250209  (0.005363555184590655)
     | > loss: 0.18706856667995453  (0.19352696352713816)
     | > align_error: 0.5180251002311707  (0.5839215541208113)

   --> STEP: 38
     | > decoder_loss: 0.4245063364505768  (0.445388168880814)
     | > postnet_loss: 0.2899949550628662  (0.3062614492679897)
     | > stopnet_loss: 0.0031500577460974455  (0.005305305251998729)
     | > loss: 0.18177537620067596  (0.19321771122907339)
     | > align_error: 0.5506234169006348  (0.5830452873518592)

   --> STEP: 39
     | > decoder_loss: 0.4396446645259857  (0.44524089953838253)
     | > postnet_loss: 0.30044424533843994  (0.30611229019287306)
     | > stopnet_loss: 0.0034785091411322355  (0.005258464326079075)
     | > loss: 0.18850074708461761  (0.1930967634304976)
     | > align_error: 0.5449662506580353  (0.5820689017956073)

   --> STEP: 40
     | > decoder_loss: 0.4367908239364624  (0.4450296476483345)
     | > postnet_loss: 0.2989046573638916  (0.3059320993721485)
     | > stopnet_loss: 0.003040216164663434  (0.0052030081220436845)
     | > loss: 0.18696407973766327  (0.19294344633817673)
     | > align_error: 0.5829691886901855  (0.5820914089679718)

   --> STEP: 41
     | > decoder_loss: 0.4281689524650574  (0.4446184111804497)
     | > postnet_loss: 0.29144909977912903  (0.30557885547963587)
     | > stopnet_loss: 0.003733152523636818  (0.0051671579854971755)
     | > loss: 0.18363767862319946  (0.192716476393909)
     | > align_error: 0.5022633671760559  (0.5801443835584129)

   --> STEP: 42
     | > decoder_loss: 0.4330144226551056  (0.4443421257393701)
     | > postnet_loss: 0.2934994101524353  (0.30529124963851206)
     | > stopnet_loss: 0.003290048334747553  (0.005122464898574565)
     | > loss: 0.18491850793361664  (0.19253081047818774)
     | > align_error: 0.5786649286746979  (0.580109158442134)

   --> STEP: 43
     | > decoder_loss: 0.4315589368343353  (0.4440448422764623)
     | > postnet_loss: 0.29196038842201233  (0.3049812296102214)
     | > stopnet_loss: 0.0029383401852101088  (0.005071671300589345)
     | > loss: 0.18381817638874054  (0.19232819108075874)
     | > align_error: 0.5506315231323242  (0.5794236320395802)

   --> STEP: 44
     | > decoder_loss: 0.4490189552307129  (0.4441578902981498)
     | > postnet_loss: 0.30265843868255615  (0.3049284389073199)
     | > stopnet_loss: 0.0026669513899832964  (0.005017018575348298)
     | > loss: 0.19058629870414734  (0.19228860261765393)
     | > align_error: 0.549954891204834  (0.5787538879296996)

   --> STEP: 45
     | > decoder_loss: 0.4423445463180542  (0.4441175937652588)
     | > postnet_loss: 0.301827996969223  (0.30485954019758443)
     | > stopnet_loss: 0.003301256103441119  (0.004978890520417028)
     | > loss: 0.1893444061279297  (0.1922231760289934)
     | > align_error: 0.5516184568405151  (0.57815087834994)

   --> STEP: 46
     | > decoder_loss: 0.4328882694244385  (0.44387347801871924)
     | > postnet_loss: 0.29321885108947754  (0.3046064817387126)
     | > stopnet_loss: 0.003204826032742858  (0.004940323901119764)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3530151555032442 (+0.0002536882053723044)
     | > avg_decoder_loss: 0.4397564720023762 (-5.974146452814022e-05)
     | > avg_postnet_loss: 0.3013297287803709 (-0.00036592781543709485)
     | > avg_stopnet_loss: 0.0043805499285967525 (+1.460450320420019e-05)
     | > avg_loss: 0.18965210110852213 (-9.181169849453719e-05)
     | > avg_align_error: 0.5709141565091684 (-0.0010123153527574758)


 > EPOCH: 121/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 14:47:24)

   --> TIME: 2025-12-28 14:47:29 -- STEP: 4/150 -- GLOBAL_STEP: 18275
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4648374915122986  (0.46318014711141586)
     | > postnet_loss: 0.3976491391658783  (0.39761944860219955)
     | > stopnet_loss: 0.014231186360120773  (0.014415354933589697)
     | > loss: 0.2298528403043747  (0.2296152524650097)
     | > align_error: 0.6876596808433533  (0.7075508087873459)
     | > grad_norm: tensor(0.3147, device='cuda:0')  (tensor(0.2792, device='cuda:0'))
     | > step_time: 0.4797  (0.43015599250793457)
     | > loader_time: 0.5518  (0.6094633340835571)


   --> TIME: 2025-12-28 14:48:09 -- STEP: 29/150 -- GLOBAL_STEP: 18300
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.4820251762866974  (0.4719446003437042)
     | > postnet_loss: 0.4036535620689392  (0.39860447316334163)
     | > stopnet_loss: 0.006138189230114222  (0.009146223310381174)
     | > loss: 0.22755788266658783  (0.22678349192800193)
     | > align_error: 0.6751852631568909  (0.6673837417158587)
     | > grad_norm: tensor(0.2968, device='cuda:0')  (tensor(0.3157, device='cuda:0'))
     | > step_time: 0.969  (0.7021430771926354)
     | > loader_time: 0.9731  (0.8328740925624453)


   --> TIME: 2025-12-28 14:49:06 -- STEP: 54/150 -- GLOBAL_STEP: 18325
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4818567931652069  (0.47815949387020534)
     | > postnet_loss: 0.3964913785457611  (0.40021420684125686)
     | > stopnet_loss: 0.004816937260329723  (0.007296538101164279)
     | > loss: 0.224403977394104  (0.2268899621235)
     | > align_error: 0.5768562257289886  (0.6446244948440127)
     | > grad_norm: tensor(0.1731, device='cuda:0')  (tensor(0.3085, device='cuda:0'))
     | > step_time: 1.322  (0.9203447059348777)
     | > loader_time: 1.2134  (0.9455653075818662)


   --> TIME: 2025-12-28 14:50:19 -- STEP: 79/150 -- GLOBAL_STEP: 18350
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4882541000843048  (0.4810443558270418)
     | > postnet_loss: 0.39917486906051636  (0.40007107129579855)
     | > stopnet_loss: 0.004058020189404488  (0.006280989960849849)
     | > loss: 0.22591526806354523  (0.22655984589570685)
     | > align_error: 0.5941720008850098  (0.6345009818861757)
     | > grad_norm: tensor(0.2196, device='cuda:0')  (tensor(0.2896, device='cuda:0'))
     | > step_time: 1.6329  (1.100561223452604)
     | > loader_time: 2.0475  (1.1019479232498364)


   --> TIME: 2025-12-28 14:51:51 -- STEP: 104/150 -- GLOBAL_STEP: 18375
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4906345009803772  (0.48203019998394525)
     | > postnet_loss: 0.4001706540584564  (0.3992669014976575)
     | > stopnet_loss: 0.003491496667265892  (0.005646074947435407)
     | > loss: 0.22619277238845825  (0.2259703497760571)
     | > align_error: 0.6156772375106812  (0.6303511207493452)
     | > grad_norm: tensor(0.1299, device='cuda:0')  (tensor(0.2645, device='cuda:0'))
     | > step_time: 1.6847  (1.2434218525886538)
     | > loader_time: 1.4754  (1.3156827917465803)


   --> TIME: 2025-12-28 14:53:23 -- STEP: 129/150 -- GLOBAL_STEP: 18400
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4834216237068176  (0.4829097059808036)
     | > postnet_loss: 0.39396193623542786  (0.39866762290629304)
     | > stopnet_loss: 0.0031192689202725887  (0.005190028244080815)
     | > loss: 0.2224651724100113  (0.22558435982511948)
     | > align_error: 0.661003977060318  (0.627247714719107)
     | > grad_norm: tensor(0.1125, device='cuda:0')  (tensor(0.2556, device='cuda:0'))
     | > step_time: 2.1563  (1.382474174795225)
     | > loader_time: 1.782  (1.388425045235213)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4606257975101471  (0.4606257975101471)
     | > postnet_loss: 0.33330845832824707  (0.33330845832824707)
     | > stopnet_loss: 0.012184632942080498  (0.012184632942080498)
     | > loss: 0.2106681913137436  (0.2106681913137436)
     | > align_error: 0.7192797064781189  (0.7192797064781189)

   --> STEP: 1
     | > decoder_loss: 0.4420565664768219  (0.4420565664768219)
     | > postnet_loss: 0.32080236077308655  (0.32080236077308655)
     | > stopnet_loss: 0.009623522870242596  (0.009623522870242596)
     | > loss: 0.20033825933933258  (0.20033825933933258)
     | > align_error: 0.659807026386261  (0.659807026386261)

   --> STEP: 2
     | > decoder_loss: 0.4399465322494507  (0.4410015493631363)
     | > postnet_loss: 0.3131549656391144  (0.31697866320610046)
     | > stopnet_loss: 0.01107834093272686  (0.010350931901484728)
     | > loss: 0.19935370981693268  (0.19984598457813263)
     | > align_error: 0.6558635830879211  (0.6578353047370911)

   --> STEP: 3
     | > decoder_loss: 0.44178593158721924  (0.44126301010449726)
     | > postnet_loss: 0.3111780881881714  (0.3150451382001241)
     | > stopnet_loss: 0.008220872841775417  (0.009640912214914957)
     | > loss: 0.19646187126636505  (0.19871794680754343)
     | > align_error: 0.7350077629089355  (0.6835594574610392)

   --> STEP: 4
     | > decoder_loss: 0.4474765956401825  (0.4428164064884186)
     | > postnet_loss: 0.3196147680282593  (0.3161875456571579)
     | > stopnet_loss: 0.00821631122380495  (0.009284761967137456)
     | > loss: 0.19998915493488312  (0.19903574883937836)
     | > align_error: 0.6037335991859436  (0.6636029928922653)

   --> STEP: 5
     | > decoder_loss: 0.42849746346473694  (0.43995261788368223)
     | > postnet_loss: 0.30218958854675293  (0.3133879542350769)
     | > stopnet_loss: 0.0082105016335845  (0.009069909900426864)
     | > loss: 0.19088225066661835  (0.19740504920482635)
     | > align_error: 0.6421785652637482  (0.6593181073665619)

   --> STEP: 6
     | > decoder_loss: 0.44495561718940735  (0.4407864511013031)
     | > postnet_loss: 0.313697874546051  (0.31343960762023926)
     | > stopnet_loss: 0.007288962136954069  (0.0087730852731814)
     | > loss: 0.19695234298706055  (0.19732959816853204)
     | > align_error: 0.5939358174800873  (0.6484210590521494)

   --> STEP: 7
     | > decoder_loss: 0.45680952072143555  (0.4430754610470363)
     | > postnet_loss: 0.31364572048187256  (0.3134690523147583)
     | > stopnet_loss: 0.0062548574060201645  (0.008413338435015507)
     | > loss: 0.19886866211891174  (0.19754946444715774)
     | > align_error: 0.5789899528026581  (0.6385023295879364)

   --> STEP: 8
     | > decoder_loss: 0.45042505860328674  (0.4439941607415676)
     | > postnet_loss: 0.31339597702026367  (0.31345991790294647)
     | > stopnet_loss: 0.007302508689463139  (0.008274484716821462)
     | > loss: 0.19825775921344757  (0.19763800129294395)
     | > align_error: 0.575262188911438  (0.6305973120033741)

   --> STEP: 9
     | > decoder_loss: 0.4489195644855499  (0.44454142782423234)
     | > postnet_loss: 0.31359028816223145  (0.3134744034873115)
     | > stopnet_loss: 0.006563734728842974  (0.008084401384823851)
     | > loss: 0.19719119369983673  (0.19758835600482094)
     | > align_error: 0.5913289785385132  (0.6262341638406118)

   --> STEP: 10
     | > decoder_loss: 0.4725947678089142  (0.4473467618227005)
     | > postnet_loss: 0.32713982462882996  (0.3148409456014633)
     | > stopnet_loss: 0.005588038358837366  (0.007834765082225203)
     | > loss: 0.20552168786525726  (0.19838168919086457)
     | > align_error: 0.5832188725471497  (0.6219326347112656)

   --> STEP: 11
     | > decoder_loss: 0.45988690853118896  (0.4484867751598358)
     | > postnet_loss: 0.3175017833709717  (0.3150828399441459)
     | > stopnet_loss: 0.005871579982340336  (0.007656293709508397)
     | > loss: 0.20021875202655792  (0.19854869490320032)
     | > align_error: 0.5947205424308777  (0.6194588081403212)

   --> STEP: 12
     | > decoder_loss: 0.4559485912322998  (0.4491085931658745)
     | > postnet_loss: 0.31090986728668213  (0.3147350922226906)
     | > stopnet_loss: 0.007904264144599438  (0.007676957912432651)
     | > loss: 0.1996188759803772  (0.19863787665963173)
     | > align_error: 0.5881476402282715  (0.6168495441476504)

   --> STEP: 13
     | > decoder_loss: 0.446611225605011  (0.448916487968885)
     | > postnet_loss: 0.3115440607070923  (0.31448962825995225)
     | > stopnet_loss: 0.005608619190752506  (0.00751785493384187)
     | > loss: 0.19514743983745575  (0.19836938151946434)
     | > align_error: 0.5863919258117676  (0.6145066504295056)

   --> STEP: 14
     | > decoder_loss: 0.45739731192588806  (0.44952226110867094)
     | > postnet_loss: 0.31461167335510254  (0.3144983457667487)
     | > stopnet_loss: 0.004953243304044008  (0.007334668388856309)
     | > loss: 0.19795550405979156  (0.19833981884377344)
     | > align_error: 0.5549927353858948  (0.6102556564978191)

   --> STEP: 15
     | > decoder_loss: 0.4542192816734314  (0.44983539581298826)
     | > postnet_loss: 0.31393709778785706  (0.3144609292348226)
     | > stopnet_loss: 0.005008304491639137  (0.007179577462375164)
     | > loss: 0.1970474123954773  (0.19825365841388704)
     | > align_error: 0.588839590549469  (0.6088279187679291)

   --> STEP: 16
     | > decoder_loss: 0.4552830755710602  (0.4501758757978678)
     | > postnet_loss: 0.3079603910446167  (0.3140546455979347)
     | > stopnet_loss: 0.00522651569917798  (0.00705751110217534)
     | > loss: 0.1960373818874359  (0.19811514113098383)
     | > align_error: 0.6065836846828461  (0.6086876541376114)

   --> STEP: 17
     | > decoder_loss: 0.46183037757873535  (0.4508614347261541)
     | > postnet_loss: 0.3163622319698334  (0.3141903859727523)
     | > stopnet_loss: 0.004826921503990889  (0.00692629994934096)
     | > loss: 0.19937507808208466  (0.19818925506928387)
     | > align_error: 0.5590173602104187  (0.6057658721418941)

   --> STEP: 18
     | > decoder_loss: 0.4557008445262909  (0.4511302908261617)
     | > postnet_loss: 0.3086101710796356  (0.3138803740342458)
     | > stopnet_loss: 0.005206780508160591  (0.006830771091497607)
     | > loss: 0.19628453254699707  (0.19808343715137905)
     | > align_error: 0.6045626401901245  (0.6056990259223514)

   --> STEP: 19
     | > decoder_loss: 0.45186054706573486  (0.4511687253650866)
     | > postnet_loss: 0.30726128816604614  (0.31353200109381424)
     | > stopnet_loss: 0.0047187660820782185  (0.006719612933107112)
     | > loss: 0.19449922442436218  (0.19789479437627291)
     | > align_error: 0.6000930070877075  (0.6054039722994754)

   --> STEP: 20
     | > decoder_loss: 0.44982975721359253  (0.4511017769575119)
     | > postnet_loss: 0.3045206367969513  (0.3130814328789711)
     | > stopnet_loss: 0.004528864286839962  (0.006610075500793755)
     | > loss: 0.1931164711713791  (0.1976558782160282)
     | > align_error: 0.6232175529003143  (0.6062946513295173)

   --> STEP: 21
     | > decoder_loss: 0.44791939854621887  (0.4509502351284027)
     | > postnet_loss: 0.30391427874565125  (0.3126449017297654)
     | > stopnet_loss: 0.003975735045969486  (0.006484630717230695)
     | > loss: 0.19193415343761444  (0.19738341513134183)
     | > align_error: 0.5606058835983276  (0.6041189957232702)

   --> STEP: 22
     | > decoder_loss: 0.4478342533111572  (0.4508085995912552)
     | > postnet_loss: 0.3054705262184143  (0.3123187937519767)
     | > stopnet_loss: 0.004587254021316767  (0.00639838632196188)
     | > loss: 0.19291344285011292  (0.19718023457310416)
     | > align_error: 0.6254490613937378  (0.605088544162837)

   --> STEP: 23
     | > decoder_loss: 0.42344483733177185  (0.4496188707973646)
     | > postnet_loss: 0.2948831021785736  (0.311560720205307)
     | > stopnet_loss: 0.004514172673225403  (0.00631646398940812)
     | > loss: 0.18409615755081177  (0.19661136165909146)
     | > align_error: 0.5677587985992432  (0.6034655117470286)

   --> STEP: 24
     | > decoder_loss: 0.45735761523246765  (0.44994131848216057)
     | > postnet_loss: 0.3100407123565674  (0.31149738654494286)
     | > stopnet_loss: 0.004382176324725151  (0.0062358686700463295)
     | > loss: 0.19623176753520966  (0.19659554523726305)
     | > align_error: 0.5800854563713074  (0.6024913427730402)

   --> STEP: 25
     | > decoder_loss: 0.4561011493206024  (0.45018771171569827)
     | > postnet_loss: 0.3070950210094452  (0.3113212919235229)
     | > stopnet_loss: 0.0037039793096482754  (0.006134593095630407)
     | > loss: 0.1945030242204666  (0.1965118443965912)
     | > align_error: 0.5579800009727478  (0.6007108891010284)

   --> STEP: 26
     | > decoder_loss: 0.43188419938087463  (0.4494837304720512)
     | > postnet_loss: 0.29632994532585144  (0.31074470166976637)
     | > stopnet_loss: 0.004349434748291969  (0.006065933159194314)
     | > loss: 0.18640297651290894  (0.19612304178568032)
     | > align_error: 0.5475130677223206  (0.5986648190480012)

   --> STEP: 27
     | > decoder_loss: 0.429231733083725  (0.44873365649470576)
     | > postnet_loss: 0.2914392650127411  (0.31002968549728394)
     | > stopnet_loss: 0.003919081762433052  (0.0059864201444994524)
     | > loss: 0.18408682942390442  (0.1956772561426516)
     | > align_error: 0.541690319776535  (0.5965546524083173)

   --> STEP: 28
     | > decoder_loss: 0.43419820070266724  (0.4482145330735615)
     | > postnet_loss: 0.29572954773902893  (0.30951896629163195)
     | > stopnet_loss: 0.003949918318539858  (0.005913687936429467)
     | > loss: 0.1864318698644638  (0.19534706377557345)
     | > align_error: 0.5667243599891663  (0.595489284821919)

   --> STEP: 29
     | > decoder_loss: 0.42950400710105896  (0.4475693425227856)
     | > postnet_loss: 0.29232046008110046  (0.30892591435333777)
     | > stopnet_loss: 0.0035796116571873426  (0.005833202547490083)
     | > loss: 0.18403573334217072  (0.19495701789855957)
     | > align_error: 0.5409291684627533  (0.5936079014991892)

   --> STEP: 30
     | > decoder_loss: 0.4302203953266144  (0.4469910442829132)
     | > postnet_loss: 0.2932969033718109  (0.30840494732062024)
     | > stopnet_loss: 0.002831100020557642  (0.005733132463259002)
     | > loss: 0.18371042609214783  (0.19458213150501252)
     | > align_error: 0.533670961856842  (0.5916100035111109)

   --> STEP: 31
     | > decoder_loss: 0.4250091016292572  (0.4462819493586017)
     | > postnet_loss: 0.2911745309829712  (0.3078491274387606)
     | > stopnet_loss: 0.0036993755493313074  (0.005667527401519399)
     | > loss: 0.1827452927827835  (0.19420029799784383)
     | > align_error: 0.5560259819030762  (0.5904621318463357)

   --> STEP: 32
     | > decoder_loss: 0.43789198994636536  (0.44601976312696934)
     | > postnet_loss: 0.29780012369155884  (0.3075350960716605)
     | > stopnet_loss: 0.0038408739492297173  (0.005610444481135346)
     | > loss: 0.18776391446590424  (0.19399916101247072)
     | > align_error: 0.5318347215652466  (0.5886300252750516)

   --> STEP: 33
     | > decoder_loss: 0.4341604709625244  (0.4456603906371377)
     | > postnet_loss: 0.29505664110183716  (0.30715696107257495)
     | > stopnet_loss: 0.0040225135162472725  (0.005562325360987223)
     | > loss: 0.1863267868757248  (0.19376666482650873)
     | > align_error: 0.5464348196983337  (0.5873513826818177)

   --> STEP: 34
     | > decoder_loss: 0.4398668706417084  (0.4454899929902133)
     | > postnet_loss: 0.29656970500946045  (0.3068455711883657)
     | > stopnet_loss: 0.0033118389546871185  (0.005496134584331337)
     | > loss: 0.18742099404335022  (0.1935800274505335)
     | > align_error: 0.5641109943389893  (0.5866678418482051)

   --> STEP: 35
     | > decoder_loss: 0.43727385997772217  (0.4452552463327135)
     | > postnet_loss: 0.2959837317466736  (0.3065352329186031)
     | > stopnet_loss: 0.0035352667327970266  (0.005440109788573214)
     | > loss: 0.1868496686220169  (0.19338773148400443)
     | > align_error: 0.5336270928382874  (0.5851523918764931)

   --> STEP: 36
     | > decoder_loss: 0.4438779354095459  (0.44521698769595885)
     | > postnet_loss: 0.30030766129493713  (0.3063622448179457)
     | > stopnet_loss: 0.0036645368672907352  (0.005390788318537589)
     | > loss: 0.18971092998981476  (0.19328559810916582)
     | > align_error: 0.6343942284584045  (0.5865202206704352)

   --> STEP: 37
     | > decoder_loss: 0.436064749956131  (0.4449696299192068)
     | > postnet_loss: 0.2969306707382202  (0.30610733741038554)
     | > stopnet_loss: 0.0035544803831726313  (0.005341158374338536)
     | > loss: 0.18680332601070404  (0.19311040156596415)
     | > align_error: 0.519419252872467  (0.5847066810002198)

   --> STEP: 38
     | > decoder_loss: 0.42424970865249634  (0.4444243688332407)
     | > postnet_loss: 0.2899778485298157  (0.30568287717668635)
     | > stopnet_loss: 0.0031557974871248007  (0.005283648877306596)
     | > loss: 0.18171268701553345  (0.19281046170937388)
     | > align_error: 0.5521103143692017  (0.5838488818783509)

   --> STEP: 39
     | > decoder_loss: 0.43941956758499146  (0.4442960405961061)
     | > postnet_loss: 0.30017217993736267  (0.3055415772474729)
     | > stopnet_loss: 0.0034768073819577694  (0.005237319608195087)
     | > loss: 0.18837474286556244  (0.19269672532876334)
     | > align_error: 0.5461893677711487  (0.5828832533114996)

   --> STEP: 40
     | > decoder_loss: 0.43675196170806885  (0.44410743862390517)
     | > postnet_loss: 0.2987765371799469  (0.3053724512457847)
     | > stopnet_loss: 0.003046199679374695  (0.0051825416099745775)
     | > loss: 0.18692831695079803  (0.1925525151193142)
     | > align_error: 0.5842050313949585  (0.582916297763586)

   --> STEP: 41
     | > decoder_loss: 0.426720529794693  (0.44368336767685124)
     | > postnet_loss: 0.29063400626182556  (0.30501297697788327)
     | > stopnet_loss: 0.0037154050078243017  (0.005146757790409936)
     | > loss: 0.18305404484272003  (0.192320845112568)
     | > align_error: 0.5035994052886963  (0.58098173941054)

   --> STEP: 42
     | > decoder_loss: 0.43281036615371704  (0.44342448668820517)
     | > postnet_loss: 0.2936156392097473  (0.30474161179292764)
     | > stopnet_loss: 0.0032780810724943876  (0.005102265487602424)
     | > loss: 0.18488457798957825  (0.1921437911334492)
     | > align_error: 0.5800167918205261  (0.5809587644679206)

   --> STEP: 43
     | > decoder_loss: 0.43067386746406555  (0.4431279606597368)
     | > postnet_loss: 0.29174280166625977  (0.30443931388300516)
     | > stopnet_loss: 0.0029326595831662416  (0.005051809536336466)
     | > loss: 0.1835368126630783  (0.19194362884344057)
     | > align_error: 0.5519473552703857  (0.5802840805330942)

   --> STEP: 44
     | > decoder_loss: 0.4484383761882782  (0.4432486519217491)
     | > postnet_loss: 0.30238091945648193  (0.30439253219149326)
     | > stopnet_loss: 0.0026525354478508234  (0.004997280579779974)
     | > loss: 0.19035737216472626  (0.19190757755528798)
     | > align_error: 0.5513866543769836  (0.5796273208477281)

   --> STEP: 45
     | > decoder_loss: 0.44161927700042725  (0.4432124435901642)
     | > postnet_loss: 0.3015291392803192  (0.3043289012379116)
     | > stopnet_loss: 0.003294699126854539  (0.004959445436381631)
     | > loss: 0.1890818178653717  (0.19184478289551204)
     | > align_error: 0.5528177917003632  (0.5790315535333421)

   --> STEP: 46
     | > decoder_loss: 0.4321673512458801  (0.4429723328870276)
     | > postnet_loss: 0.29290929436683655  (0.3040806489146274)
     | > stopnet_loss: 0.0031964390072971582  (0.004921119209662404)
     | > loss: 0.18446560204029083  (0.19168436592039856)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35407904061404144 (-0.0023577321659434824)
     | > avg_decoder_loss: 0.439038177782839 (-4.1459545944699805e-05)
     | > avg_postnet_loss: 0.302584584012176 (+0.0017000942519217466)
     | > avg_stopnet_loss: 0.004376012997729985 (+1.3714857314797019e-05)
     | > avg_loss: 0.18978170305490494 (+0.0004283722602959894)
     | > avg_align_error: 0.5711248517036438 (-0.0007644882707885658)


 > EPOCH: 123/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 15:05:58)

   --> TIME: 2025-12-28 15:06:02 -- STEP: 2/150 -- GLOBAL_STEP: 18575
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45503708720207214  (0.46148450672626495)
     | > postnet_loss: 0.3924719989299774  (0.39659905433654785)
     | > stopnet_loss: 0.014341862872242928  (0.014938673935830593)
     | > loss: 0.22621913254261017  (0.22945956885814667)
     | > align_error: 0.730735182762146  (0.722755491733551)
     | > grad_norm: tensor(0.2550, device='cuda:0')  (tensor(0.3112, device='cuda:0'))
     | > step_time: 0.5256  (0.44517791271209717)
     | > loader_time: 0.6756  (0.7324137687683105)


   --> TIME: 2025-12-28 15:06:40 -- STEP: 27/150 -- GLOBAL_STEP: 18600
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.47614991664886475  (0.4704969139010818)
     | > postnet_loss: 0.39794570207595825  (0.39782169461250305)
     | > stopnet_loss: 0.006486203987151384  (0.00937020283675304)
     | > loss: 0.22501011192798615  (0.2264498566035871)
     | > align_error: 0.6590241193771362  (0.6682828035619524)
     | > grad_norm: tensor(0.3076, device='cuda:0')  (tensor(0.3262, device='cuda:0'))
     | > step_time: 0.8401  (0.6660550082171405)
     | > loader_time: 0.8689  (0.8419281200126365)


   --> TIME: 2025-12-28 15:07:34 -- STEP: 52/150 -- GLOBAL_STEP: 18625
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4853598177433014  (0.4774307688841453)
     | > postnet_loss: 0.40036284923553467  (0.3998672836101972)
     | > stopnet_loss: 0.0044378722086548805  (0.007395012769848107)
     | > loss: 0.22586853802204132  (0.2267195270038568)
     | > align_error: 0.6596822142601013  (0.6470538601279259)
     | > grad_norm: tensor(0.1769, device='cuda:0')  (tensor(0.2943, device='cuda:0'))
     | > step_time: 1.2921  (0.8749743975125827)
     | > loader_time: 1.2028  (0.9438579082489014)


   --> TIME: 2025-12-28 15:08:44 -- STEP: 77/150 -- GLOBAL_STEP: 18650
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48893120884895325  (0.4802999302938387)
     | > postnet_loss: 0.3993593454360962  (0.3995815140086334)
     | > stopnet_loss: 0.004138784948736429  (0.006328771208328281)
     | > loss: 0.22621141374111176  (0.2262991326195853)
     | > align_error: 0.6115773320198059  (0.6354599358973566)
     | > grad_norm: tensor(0.2536, device='cuda:0')  (tensor(0.2768, device='cuda:0'))
     | > step_time: 1.5127  (1.0428436452692207)
     | > loader_time: 1.9816  (1.0899186846497773)


   --> TIME: 2025-12-28 15:10:07 -- STEP: 102/150 -- GLOBAL_STEP: 18675
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49020466208457947  (0.4815853717280369)
     | > postnet_loss: 0.3992297053337097  (0.398948631158062)
     | > stopnet_loss: 0.0034109395928680897  (0.005680231733576341)
     | > loss: 0.2257695198059082  (0.22581373242770925)
     | > align_error: 0.6052062511444092  (0.6305426791602491)
     | > grad_norm: tensor(0.1706, device='cuda:0')  (tensor(0.2625, device='cuda:0'))
     | > step_time: 1.6985  (1.1874166680317308)
     | > loader_time: 1.5623  (1.239589784659592)


   --> TIME: 2025-12-28 15:11:34 -- STEP: 127/150 -- GLOBAL_STEP: 18700
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49158579111099243  (0.48252751062235494)
     | > postnet_loss: 0.3987932801246643  (0.3983620508449284)
     | > stopnet_loss: 0.0031734067015349865  (0.005215024395926497)
     | > loss: 0.22576817870140076  (0.22543741492774544)
     | > align_error: 0.5982031226158142  (0.6265889600975308)
     | > grad_norm: tensor(0.1481, device='cuda:0')  (tensor(0.2453, device='cuda:0'))
     | > step_time: 1.9166  (1.3105221677014216)
     | > loader_time: 1.8542  (1.3196692710786357)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45966634154319763  (0.45966634154319763)
     | > postnet_loss: 0.3323415219783783  (0.3323415219783783)
     | > stopnet_loss: 0.012222597375512123  (0.012222597375512123)
     | > loss: 0.21022456884384155  (0.21022456884384155)
     | > align_error: 0.7187694311141968  (0.7187694311141968)

   --> STEP: 1
     | > decoder_loss: 0.44248053431510925  (0.44248053431510925)
     | > postnet_loss: 0.3204728066921234  (0.3204728066921234)
     | > stopnet_loss: 0.009605275467038155  (0.009605275467038155)
     | > loss: 0.20034360885620117  (0.20034360885620117)
     | > align_error: 0.6593694090843201  (0.6593694090843201)

   --> STEP: 2
     | > decoder_loss: 0.4377709925174713  (0.4401257634162903)
     | > postnet_loss: 0.31193259358406067  (0.31620270013809204)
     | > stopnet_loss: 0.011120224371552467  (0.010362749919295311)
     | > loss: 0.1985461264848709  (0.19944486767053604)
     | > align_error: 0.6553018093109131  (0.6573356091976166)

   --> STEP: 3
     | > decoder_loss: 0.44198858737945557  (0.4407467047373454)
     | > postnet_loss: 0.3112519085407257  (0.3145524362723033)
     | > stopnet_loss: 0.008282828144729137  (0.009669442661106586)
     | > loss: 0.19659294188022614  (0.19849422574043274)
     | > align_error: 0.734750896692276  (0.6831407050291697)

   --> STEP: 4
     | > decoder_loss: 0.4452020227909088  (0.44186053425073624)
     | > postnet_loss: 0.3179267346858978  (0.3153960108757019)
     | > stopnet_loss: 0.008231152780354023  (0.009309870190918446)
     | > loss: 0.1990133374929428  (0.19862400367856026)
     | > align_error: 0.6029870212078094  (0.6631022840738297)

   --> STEP: 5
     | > decoder_loss: 0.4279705882072449  (0.439082545042038)
     | > postnet_loss: 0.30152636766433716  (0.31262208223342897)
     | > stopnet_loss: 0.008166800253093243  (0.009081256203353405)
     | > loss: 0.19054104387760162  (0.19700741171836852)
     | > align_error: 0.6417278945446014  (0.658827406167984)

   --> STEP: 6
     | > decoder_loss: 0.44347190856933594  (0.43981410562992096)
     | > postnet_loss: 0.3122107982635498  (0.3125535349051158)
     | > stopnet_loss: 0.007302773185074329  (0.008784842366973558)
     | > loss: 0.1962234526872635  (0.19687675187985101)
     | > align_error: 0.5935288965702057  (0.647944321235021)

   --> STEP: 7
     | > decoder_loss: 0.4545033872127533  (0.44191257442746845)
     | > postnet_loss: 0.31221726536750793  (0.31250549639974323)
     | > stopnet_loss: 0.006252001505345106  (0.008423007958169495)
     | > loss: 0.197932168841362  (0.19702752573149546)
     | > align_error: 0.5783340036869049  (0.6379999901567187)

   --> STEP: 8
     | > decoder_loss: 0.45146748423576355  (0.4431069381535053)
     | > postnet_loss: 0.31390807032585144  (0.31268081814050674)
     | > stopnet_loss: 0.0071503035724163055  (0.008263919909950346)
     | > loss: 0.19849419593811035  (0.1972108595073223)
     | > align_error: 0.5744930803775787  (0.6300616264343262)

   --> STEP: 9
     | > decoder_loss: 0.44824594259262085  (0.4436779386467404)
     | > postnet_loss: 0.3129587471485138  (0.3127116991413964)
     | > stopnet_loss: 0.006616080645471811  (0.00808082665834162)
     | > loss: 0.19691726565361023  (0.19717823796802098)
     | > align_error: 0.590735673904419  (0.6256920761532254)

   --> STEP: 10
     | > decoder_loss: 0.47124096751213074  (0.44643424153327943)
     | > postnet_loss: 0.32568544149398804  (0.31400907337665557)
     | > stopnet_loss: 0.005559150595217943  (0.007828659052029252)
     | > loss: 0.20479074120521545  (0.1979394882917404)
     | > align_error: 0.5827783644199371  (0.6214007049798965)

   --> STEP: 11
     | > decoder_loss: 0.46053585410118103  (0.44771620631217957)
     | > postnet_loss: 0.3175520598888397  (0.3143311630595814)
     | > stopnet_loss: 0.00589441554620862  (0.007652818733318286)
     | > loss: 0.20041640102863312  (0.19816466217691248)
     | > align_error: 0.594437301158905  (0.6189494864507155)

   --> STEP: 12
     | > decoder_loss: 0.45523515343666077  (0.44834278523921967)
     | > postnet_loss: 0.31041863560676575  (0.3140051191051801)
     | > stopnet_loss: 0.00788899976760149  (0.0076725004861752195)
     | > loss: 0.19930244982242584  (0.1982594778140386)
     | > align_error: 0.5870176553726196  (0.6162885005275408)

   --> STEP: 13
     | > decoder_loss: 0.4457254707813263  (0.4481414533578433)
     | > postnet_loss: 0.3107069730758667  (0.3137514155644637)
     | > stopnet_loss: 0.005561803933233023  (0.007510139212871973)
     | > loss: 0.1946699023246765  (0.1979833566225492)
     | > align_error: 0.5854708552360535  (0.6139179124281957)

   --> STEP: 14
     | > decoder_loss: 0.45765745639801025  (0.4488211678607123)
     | > postnet_loss: 0.31440964341163635  (0.31379843183926176)
     | > stopnet_loss: 0.004921287763863802  (0.007325221252228532)
     | > loss: 0.19793805480003357  (0.1979801207780838)
     | > align_error: 0.5543746948242188  (0.609664825456483)

   --> STEP: 15
     | > decoder_loss: 0.4543912708759308  (0.4491925080617269)
     | > postnet_loss: 0.3142053484916687  (0.3138255596160889)
     | > stopnet_loss: 0.004982171580195427  (0.007169017940759659)
     | > loss: 0.19713133573532104  (0.19792353510856628)
     | > align_error: 0.5881035923957825  (0.608227409919103)

   --> STEP: 16
     | > decoder_loss: 0.4546968340873718  (0.4495365284383297)
     | > postnet_loss: 0.3077007234096527  (0.3134427573531866)
     | > stopnet_loss: 0.005240296944975853  (0.007048472878523171)
     | > loss: 0.19583967328071594  (0.19779329374432564)
     | > align_error: 0.6058841943740845  (0.6080809589475393)

   --> STEP: 17
     | > decoder_loss: 0.4614936411380768  (0.4502398880089031)
     | > postnet_loss: 0.3164485991001129  (0.31361957157359405)
     | > stopnet_loss: 0.004840171430259943  (0.006918572793331216)
     | > loss: 0.19932572543621063  (0.19788343678502476)
     | > align_error: 0.5582277178764343  (0.6051484153551214)

   --> STEP: 18
     | > decoder_loss: 0.4556392729282379  (0.45053985383775497)
     | > postnet_loss: 0.30866485834121704  (0.3133443097273509)
     | > stopnet_loss: 0.00523655628785491  (0.006825127431915866)
     | > loss: 0.19631259143352509  (0.19779616759883034)
     | > align_error: 0.6038484573364258  (0.6050761954651939)

   --> STEP: 19
     | > decoder_loss: 0.4518464505672455  (0.45060862208667557)
     | > postnet_loss: 0.3072530925273895  (0.31302371934840556)
     | > stopnet_loss: 0.004711017943918705  (0.006713858511494963)
     | > loss: 0.19448590278625488  (0.19762194313501058)
     | > align_error: 0.5994479954242706  (0.6047799744104084)

   --> STEP: 20
     | > decoder_loss: 0.4494393765926361  (0.45055015981197355)
     | > postnet_loss: 0.30465638637542725  (0.31260535269975664)
     | > stopnet_loss: 0.004498290363699198  (0.006603080104105175)
     | > loss: 0.1930222362279892  (0.1973919577896595)
     | > align_error: 0.6225766241550446  (0.6056698068976403)

   --> STEP: 21
     | > decoder_loss: 0.44709134101867676  (0.4503854541551499)
     | > postnet_loss: 0.30339136719703674  (0.31216659148534137)
     | > stopnet_loss: 0.0040045687928795815  (0.006479341470237289)
     | > loss: 0.19162523746490479  (0.19711735205990927)
     | > align_error: 0.5597881972789764  (0.6034849683443705)

   --> STEP: 22
     | > decoder_loss: 0.4497130513191223  (0.4503548903898759)
     | > postnet_loss: 0.3066294491291046  (0.3119149031964215)
     | > stopnet_loss: 0.004857715684920549  (0.006405631207268347)
     | > loss: 0.1939433515071869  (0.19697307930751282)
     | > align_error: 0.6252964735031128  (0.6044764003970406)

   --> STEP: 23
     | > decoder_loss: 0.42326220870018005  (0.44917694770771527)
     | > postnet_loss: 0.29490911960601807  (0.3111755213011866)
     | > stopnet_loss: 0.004489697050303221  (0.006322329722182906)
     | > loss: 0.18403252959251404  (0.1964104467112085)
     | > align_error: 0.5673651397228241  (0.6028628673242487)

   --> STEP: 24
     | > decoder_loss: 0.45684826374053955  (0.4494965858757496)
     | > postnet_loss: 0.3102846145629883  (0.311138400187095)
     | > stopnet_loss: 0.004391973372548819  (0.0062418982076148195)
     | > loss: 0.19617518782615662  (0.19640064425766468)
     | > align_error: 0.5793865621089935  (0.6018846879402797)

   --> STEP: 25
     | > decoder_loss: 0.45598509907722473  (0.4497561264038086)
     | > postnet_loss: 0.3071954846382141  (0.31098068356513975)
     | > stopnet_loss: 0.0037068866658955812  (0.00614049774594605)
     | > loss: 0.19450204074382782  (0.1963247001171112)
     | > align_error: 0.5575802028179169  (0.6001125085353852)

   --> STEP: 26
     | > decoder_loss: 0.43110814690589905  (0.4490388964231198)
     | > postnet_loss: 0.29617446660995483  (0.31041121368224805)
     | > stopnet_loss: 0.004356123972684145  (0.006071867985435977)
     | > loss: 0.18617679178714752  (0.19593439595057413)
     | > align_error: 0.5466868877410889  (0.5980576769663738)

   --> STEP: 27
     | > decoder_loss: 0.4276188611984253  (0.4482455617851681)
     | > postnet_loss: 0.2909303605556488  (0.3096897006034851)
     | > stopnet_loss: 0.0037911245599389076  (0.005987396006713863)
     | > loss: 0.18342843651771545  (0.19547121226787567)
     | > align_error: 0.5406213998794556  (0.595930407444636)

   --> STEP: 28
     | > decoder_loss: 0.43399354815483093  (0.44773656129837036)
     | > postnet_loss: 0.29592010378837585  (0.3091979292886598)
     | > stopnet_loss: 0.003941643517464399  (0.0059143334178120965)
     | > loss: 0.18642005324363708  (0.1951479565884386)
     | > align_error: 0.5663387775421143  (0.594873563519546)

   --> STEP: 29
     | > decoder_loss: 0.42885279655456543  (0.44708539699685984)
     | > postnet_loss: 0.292273610830307  (0.3086143321004407)
     | > stopnet_loss: 0.003574279835447669  (0.005833641914971943)
     | > loss: 0.18385589122772217  (0.19475857502427593)
     | > align_error: 0.5404072999954224  (0.5929954165014727)

   --> STEP: 30
     | > decoder_loss: 0.429951012134552  (0.4465142508347829)
     | > postnet_loss: 0.2932577431201935  (0.30810244580109913)
     | > stopnet_loss: 0.0028269998729228973  (0.005733420513570309)
     | > loss: 0.18362919986248016  (0.19438759585221607)
     | > align_error: 0.5330938100814819  (0.590998696287473)

   --> STEP: 31
     | > decoder_loss: 0.4267432987689972  (0.4458764781874995)
     | > postnet_loss: 0.29246437549591064  (0.3075979919202866)
     | > stopnet_loss: 0.0037284856662154198  (0.0056687451959136995)
     | > loss: 0.18353039026260376  (0.1940373634138415)
     | > align_error: 0.5557699799537659  (0.5898622860831599)

   --> STEP: 32
     | > decoder_loss: 0.4375878572463989  (0.4456174587830901)
     | > postnet_loss: 0.2976187765598297  (0.30728614144027233)
     | > stopnet_loss: 0.0038429556880146265  (0.005611689273791853)
     | > loss: 0.1876446008682251  (0.19383758958429098)
     | > align_error: 0.5309737622737885  (0.588022019714117)

   --> STEP: 33
     | > decoder_loss: 0.433713436126709  (0.44525673082380585)
     | > postnet_loss: 0.2953632175922394  (0.3069248407176047)
     | > stopnet_loss: 0.004032839089632034  (0.005563845328817313)
     | > loss: 0.18630199134349823  (0.1936092381224488)
     | > align_error: 0.5460646152496338  (0.5867505832151934)

   --> STEP: 34
     | > decoder_loss: 0.4397783577442169  (0.44509560220381794)
     | > postnet_loss: 0.29703307151794434  (0.30663390632937937)
     | > stopnet_loss: 0.003310465719550848  (0.005497569457956535)
     | > loss: 0.1875133216381073  (0.19342994646114461)
     | > align_error: 0.5637329816818237  (0.5860735949348)

   --> STEP: 35
     | > decoder_loss: 0.4370724558830261  (0.4448663694517953)
     | > postnet_loss: 0.2962082326412201  (0.3063360299382891)
     | > stopnet_loss: 0.003503210376948118  (0.005440587769927723)
     | > loss: 0.18682336807250977  (0.19324118707861218)
     | > align_error: 0.5329189896583557  (0.5845548919269017)

   --> STEP: 36
     | > decoder_loss: 0.4426456391811371  (0.44480468249983257)
     | > postnet_loss: 0.30013588070869446  (0.30616380357080036)
     | > stopnet_loss: 0.003679861780256033  (0.005391678714659065)
     | > loss: 0.18937523663043976  (0.19313379956616294)
     | > align_error: 0.6337480843067169  (0.5859213694930077)

   --> STEP: 37
     | > decoder_loss: 0.4357140064239502  (0.44455898855183573)
     | > postnet_loss: 0.29710590839385986  (0.3059189955930452)
     | > stopnet_loss: 0.003550567664206028  (0.005341918956538713)
     | > loss: 0.18675555288791656  (0.19296141452080495)
     | > align_error: 0.5187398493289948  (0.5841056527318181)

   --> STEP: 38
     | > decoder_loss: 0.423534631729126  (0.44400571600386973)
     | > postnet_loss: 0.2899926006793976  (0.3054998799374229)
     | > stopnet_loss: 0.0031458125449717045  (0.005284126682550107)
     | > loss: 0.18152761459350586  (0.19266052504903391)
     | > align_error: 0.551385223865509  (0.5832445888142836)

   --> STEP: 39
     | > decoder_loss: 0.4390534460544586  (0.44387873472311556)
     | > postnet_loss: 0.30041277408599854  (0.3053694413258479)
     | > stopnet_loss: 0.0034968992695212364  (0.00523830033862629)
     | > loss: 0.1883634477853775  (0.19255034358073503)
     | > align_error: 0.5456693172454834  (0.5822811203125196)

   --> STEP: 40
     | > decoder_loss: 0.43619799613952637  (0.44368671625852585)
     | > postnet_loss: 0.2990261912345886  (0.30521086007356646)
     | > stopnet_loss: 0.0030456853564828634  (0.005183484964072704)
     | > loss: 0.18685172498226166  (0.1924078781157732)
     | > align_error: 0.5838097333908081  (0.5823193356394768)

   --> STEP: 41
     | > decoder_loss: 0.42826947569847107  (0.4433106860009635)
     | > postnet_loss: 0.29196682572364807  (0.3048878348455196)
     | > stopnet_loss: 0.0037207906134426594  (0.005147809492106118)
     | > loss: 0.18377986550331116  (0.19219743878376194)
     | > align_error: 0.5028682351112366  (0.5803815039192758)

   --> STEP: 42
     | > decoder_loss: 0.4327225089073181  (0.44305858654635294)
     | > postnet_loss: 0.2941320836544037  (0.3046317455314454)
     | > stopnet_loss: 0.0032799160107970238  (0.005103335837789234)
     | > loss: 0.18499355018138885  (0.19202591762656257)
     | > align_error: 0.5794792771339417  (0.5803600223291487)

   --> STEP: 43
     | > decoder_loss: 0.4303121864795685  (0.44276215863782303)
     | > postnet_loss: 0.2921447455883026  (0.3043413501839305)
     | > stopnet_loss: 0.0029287785291671753  (0.005052764737588721)
     | > loss: 0.18354301154613495  (0.19182864074097122)
     | > align_error: 0.5515588819980621  (0.5796902283679607)

   --> STEP: 44
     | > decoder_loss: 0.44800183176994324  (0.44288124211809854)
     | > postnet_loss: 0.30258506536483765  (0.3043014346198602)
     | > stopnet_loss: 0.0026535652577877045  (0.004998237476684153)
     | > loss: 0.19030028581619263  (0.1917939054017717)
     | > align_error: 0.5508586168289185  (0.5790349644693461)

   --> STEP: 45
     | > decoder_loss: 0.44076108932495117  (0.44283412761158414)
     | > postnet_loss: 0.30152085423469543  (0.3042396439446343)
     | > stopnet_loss: 0.0033072568476200104  (0.004960660129371616)
     | > loss: 0.18887773156166077  (0.19172910153865813)
     | > align_error: 0.5525752305984497  (0.5784469703833263)

   --> STEP: 46
     | > decoder_loss: 0.43179816007614136  (0.4425942152738571)
     | > postnet_loss: 0.2932581901550293  (0.30400091668833856)
     | > stopnet_loss: 0.0032052993774414062  (0.004922500113025308)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.39500885298757843 (+0.04092981237353699)
     | > avg_decoder_loss: 0.43866270012927777 (-0.0003754776535612181)
     | > avg_postnet_loss: 0.3009008769736145 (-0.0016837070385615216)
     | > avg_stopnet_loss: 0.0043664152917423935 (-9.597705987591382e-06)
     | > avg_loss: 0.18925730884075165 (-0.0005243942141532898)
     | > avg_align_error: 0.5713942064480348 (+0.00026935474439104823)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_18724.pth

 > EPOCH: 124/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 15:15:11)

   --> TIME: 2025-12-28 15:15:14 -- STEP: 1/150 -- GLOBAL_STEP: 18725
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4689996540546417  (0.4689996540546417)
     | > postnet_loss: 0.40242329239845276  (0.40242329239845276)
     | > stopnet_loss: 0.015545511618256569  (0.015545511618256569)
     | > loss: 0.23340125381946564  (0.23340125381946564)
     | > align_error: 0.7146046161651611  (0.7146046161651611)
     | > grad_norm: tensor(0.3295, device='cuda:0')  (tensor(0.3295, device='cuda:0'))
     | > step_time: 0.4622  (0.4621593952178955)
     | > loader_time: 0.8564  (0.8563632965087891)


   --> TIME: 2025-12-28 15:15:53 -- STEP: 26/150 -- GLOBAL_STEP: 18750
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.48366597294807434  (0.4706048426719812)
     | > postnet_loss: 0.40370550751686096  (0.3978646844625473)
     | > stopnet_loss: 0.006720142904669046  (0.009677714757764569)
     | > loss: 0.22856301069259644  (0.22679509681004745)
     | > align_error: 0.6199513077735901  (0.6683468646728076)
     | > grad_norm: tensor(0.2050, device='cuda:0')  (tensor(0.2900, device='cuda:0'))
     | > step_time: 0.9916  (0.6870982555242685)
     | > loader_time: 0.9916  (0.8803287194325373)


   --> TIME: 2025-12-28 15:16:48 -- STEP: 51/150 -- GLOBAL_STEP: 18775
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48818081617355347  (0.47696958043996024)
     | > postnet_loss: 0.40161094069480896  (0.39949568171127164)
     | > stopnet_loss: 0.004026805516332388  (0.007543289604797666)
     | > loss: 0.22647473216056824  (0.22665960502390767)
     | > align_error: 0.6107698082923889  (0.646774980951758)
     | > grad_norm: tensor(0.3537, device='cuda:0')  (tensor(0.2926, device='cuda:0'))
     | > step_time: 1.3059  (0.9099169151455748)
     | > loader_time: 1.2538  (0.9636240800221761)


   --> TIME: 2025-12-28 15:17:55 -- STEP: 76/150 -- GLOBAL_STEP: 18800
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4912014901638031  (0.479840393129148)
     | > postnet_loss: 0.4015786945819855  (0.3992826620999135)
     | > stopnet_loss: 0.003821068676188588  (0.006411605122450151)
     | > loss: 0.2270161211490631  (0.22619236888069855)
     | > align_error: 0.6042428016662598  (0.6353384562228855)
     | > grad_norm: tensor(0.1718, device='cuda:0')  (tensor(0.2812, device='cuda:0'))
     | > step_time: 1.5146  (1.083442044885535)
     | > loader_time: 1.3404  (1.0595432582654454)


   --> TIME: 2025-12-28 15:19:15 -- STEP: 101/150 -- GLOBAL_STEP: 18825
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48663848638534546  (0.4810190717182537)
     | > postnet_loss: 0.3975442051887512  (0.3985639285333085)
     | > stopnet_loss: 0.003750888630747795  (0.005753733770977152)
     | > loss: 0.22479656338691711  (0.22564948401828805)
     | > align_error: 0.6052177846431732  (0.6307205835191332)
     | > grad_norm: tensor(0.2221, device='cuda:0')  (tensor(0.2612, device='cuda:0'))
     | > step_time: 1.7785  (1.2304568810038043)
     | > loader_time: 1.5452  (1.169012289236088)


   --> TIME: 2025-12-28 15:20:56 -- STEP: 126/150 -- GLOBAL_STEP: 18850
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48951661586761475  (0.4821648685232041)
     | > postnet_loss: 0.39707374572753906  (0.39808977880175145)
     | > stopnet_loss: 0.0030785989947617054  (0.005275498057479068)
     | > loss: 0.22472618520259857  (0.2253391599607846)
     | > align_error: 0.6091447472572327  (0.6266498738338078)
     | > grad_norm: tensor(0.1386, device='cuda:0')  (tensor(0.2737, device='cuda:0'))
     | > step_time: 2.1174  (1.3582486576504178)
     | > loader_time: 2.4306  (1.363409108585782)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4603365361690521  (0.4603365361690521)
     | > postnet_loss: 0.3362254798412323  (0.3362254798412323)
     | > stopnet_loss: 0.012259230948984623  (0.012259230948984623)
     | > loss: 0.21139973402023315  (0.21139973402023315)
     | > align_error: 0.7188958525657654  (0.7188958525657654)

   --> STEP: 1
     | > decoder_loss: 0.44145041704177856  (0.44145041704177856)
     | > postnet_loss: 0.32488518953323364  (0.32488518953323364)
     | > stopnet_loss: 0.009597532451152802  (0.009597532451152802)
     | > loss: 0.20118144154548645  (0.20118144154548645)
     | > align_error: 0.6593145728111267  (0.6593145728111267)

   --> STEP: 2
     | > decoder_loss: 0.43708017468452454  (0.43926529586315155)
     | > postnet_loss: 0.3140721619129181  (0.31947867572307587)
     | > stopnet_loss: 0.011157941073179245  (0.010377736762166023)
     | > loss: 0.1989460289478302  (0.20006373524665833)
     | > align_error: 0.655516654253006  (0.6574156135320663)

   --> STEP: 3
     | > decoder_loss: 0.4402179419994354  (0.43958284457524616)
     | > postnet_loss: 0.31399238109588623  (0.317649910847346)
     | > stopnet_loss: 0.008249971084296703  (0.009668481536209583)
     | > loss: 0.19680255651474  (0.1989766756693522)
     | > align_error: 0.7347035706043243  (0.6831782658894857)

   --> STEP: 4
     | > decoder_loss: 0.447273850440979  (0.4415055960416794)
     | > postnet_loss: 0.32333534955978394  (0.3190712705254555)
     | > stopnet_loss: 0.008172079920768738  (0.009294381132349372)
     | > loss: 0.20082437992095947  (0.19943860173225403)
     | > align_error: 0.6031554341316223  (0.6631725579500198)

   --> STEP: 5
     | > decoder_loss: 0.4284072816371918  (0.43888593316078184)
     | > postnet_loss: 0.304962694644928  (0.31624955534934995)
     | > stopnet_loss: 0.008180356584489346  (0.009071576222777367)
     | > loss: 0.19152283668518066  (0.19785544872283936)
     | > align_error: 0.6420199275016785  (0.6589420318603516)

   --> STEP: 6
     | > decoder_loss: 0.4445110559463501  (0.4398234536250432)
     | > postnet_loss: 0.317023903131485  (0.3163786133130391)
     | > stopnet_loss: 0.007258910685777664  (0.008769465299944082)
     | > loss: 0.19764263927936554  (0.19781998048226038)
     | > align_error: 0.5936382710933685  (0.6480580717325211)

   --> STEP: 7
     | > decoder_loss: 0.4556613564491272  (0.44208601117134094)
     | > postnet_loss: 0.3157211244106293  (0.3162846863269806)
     | > stopnet_loss: 0.00629524327814579  (0.008416005011115755)
     | > loss: 0.19914086163043976  (0.19800867778914316)
     | > align_error: 0.5783686637878418  (0.6381024420261383)

   --> STEP: 8
     | > decoder_loss: 0.4494761824607849  (0.44300978258252144)
     | > postnet_loss: 0.3164767920970917  (0.3163086995482445)
     | > stopnet_loss: 0.007371013052761555  (0.00828538101632148)
     | > loss: 0.19885924458503723  (0.1981149986386299)
     | > align_error: 0.5750510990619659  (0.6302210241556168)

   --> STEP: 9
     | > decoder_loss: 0.44860026240348816  (0.4436309470070733)
     | > postnet_loss: 0.3166712820529938  (0.31634898649321663)
     | > stopnet_loss: 0.006645900197327137  (0.008103216480877664)
     | > loss: 0.19796378910541534  (0.19809819757938385)
     | > align_error: 0.591194212436676  (0.6258847117424011)

   --> STEP: 10
     | > decoder_loss: 0.4730696976184845  (0.4465748220682144)
     | > postnet_loss: 0.3311823308467865  (0.3178323209285736)
     | > stopnet_loss: 0.005575185175985098  (0.007850413350388408)
     | > loss: 0.2066381871700287  (0.19895219653844834)
     | > align_error: 0.5828902721405029  (0.6215852677822113)

   --> STEP: 11
     | > decoder_loss: 0.4606610834598541  (0.44785539128563623)
     | > postnet_loss: 0.32048606872558594  (0.318073570728302)
     | > stopnet_loss: 0.005913302768021822  (0.007674312388355082)
     | > loss: 0.20120008289813995  (0.19915654984387485)
     | > align_error: 0.5946536958217621  (0.6191369430585341)

   --> STEP: 12
     | > decoder_loss: 0.4547628164291382  (0.4484310100475947)
     | > postnet_loss: 0.31310129165649414  (0.3176592141389847)
     | > stopnet_loss: 0.00789602193981409  (0.0076927881843099994)
     | > loss: 0.1998620480298996  (0.1992153413593769)
     | > align_error: 0.5870802998542786  (0.6164655561248461)

   --> STEP: 13
     | > decoder_loss: 0.44575950503349304  (0.44822550966189456)
     | > postnet_loss: 0.3141903579235077  (0.31739237904548645)
     | > stopnet_loss: 0.005605258978903294  (0.007532209014663329)
     | > loss: 0.1955927312374115  (0.19893667904230264)
     | > align_error: 0.585797905921936  (0.6141065061092377)

   --> STEP: 14
     | > decoder_loss: 0.45413753390312195  (0.44864779710769653)
     | > postnet_loss: 0.31494852900505066  (0.3172178183283125)
     | > stopnet_loss: 0.004934235941618681  (0.007346639509445855)
     | > loss: 0.19720575213432312  (0.19881304140601838)
     | > align_error: 0.5545252561569214  (0.6098507025412151)

   --> STEP: 15
     | > decoder_loss: 0.45500579476356506  (0.44907166361808776)
     | > postnet_loss: 0.3155241906642914  (0.3171049098173777)
     | > stopnet_loss: 0.004962605889886618  (0.007187703934808572)
     | > loss: 0.19759510457515717  (0.19873184561729432)
     | > align_error: 0.5882523357868195  (0.6084108114242553)

   --> STEP: 16
     | > decoder_loss: 0.45411211252212524  (0.4493866916745901)
     | > postnet_loss: 0.3090393543243408  (0.3166008125990629)
     | > stopnet_loss: 0.005238687619566917  (0.007065890415105969)
     | > loss: 0.19602654874324799  (0.19856276456266642)
     | > align_error: 0.6060336828231812  (0.6082622408866882)

   --> STEP: 17
     | > decoder_loss: 0.46094539761543274  (0.4500666155534632)
     | > postnet_loss: 0.3175666928291321  (0.3166576290831846)
     | > stopnet_loss: 0.004844715353101492  (0.00693523305851747)
     | > loss: 0.19947274029254913  (0.19861629254677715)
     | > align_error: 0.5582968890666962  (0.6053231025443357)

   --> STEP: 18
     | > decoder_loss: 0.4557467997074127  (0.45038218133979374)
     | > postnet_loss: 0.3102194666862488  (0.316299953394466)
     | > stopnet_loss: 0.005250795744359493  (0.006841653207730915)
     | > loss: 0.19674237072467804  (0.19851218577888277)
     | > align_error: 0.6038219928741455  (0.6052397075626585)

   --> STEP: 19
     | > decoder_loss: 0.4546155631542206  (0.4506049909089741)
     | > postnet_loss: 0.3106338679790497  (0.316001738372602)
     | > stopnet_loss: 0.004746390040963888  (0.006731376198953704)
     | > loss: 0.1960587501525879  (0.19838305758802513)
     | > align_error: 0.5995516777038574  (0.60494033757009)

   --> STEP: 20
     | > decoder_loss: 0.44913360476493835  (0.4505314216017723)
     | > postnet_loss: 0.30545634031295776  (0.31547446846961974)
     | > stopnet_loss: 0.004542444366961718  (0.006621929607354105)
     | > loss: 0.19318991899490356  (0.19812340065836903)
     | > align_error: 0.6223981976509094  (0.6058132305741311)

   --> STEP: 21
     | > decoder_loss: 0.4476161301136017  (0.4503925981975737)
     | > postnet_loss: 0.30565908551216125  (0.31500706928116934)
     | > stopnet_loss: 0.004004731774330139  (0.006497301139114868)
     | > loss: 0.19232353568077087  (0.19784721661181673)
     | > align_error: 0.5597471594810486  (0.6036196081411271)

   --> STEP: 22
     | > decoder_loss: 0.45071977376937866  (0.45040746981447394)
     | > postnet_loss: 0.3091590404510498  (0.3147412497888912)
     | > stopnet_loss: 0.004911583382636309  (0.006425223059274934)
     | > loss: 0.19488129019737244  (0.19771240177479654)
     | > align_error: 0.6254348456859589  (0.6046112098477104)

   --> STEP: 23
     | > decoder_loss: 0.4230658710002899  (0.44921870464863983)
     | > postnet_loss: 0.2963241636753082  (0.3139405069143876)
     | > stopnet_loss: 0.004505245015025139  (0.006341745753003203)
     | > loss: 0.18435275554656982  (0.19713154759096058)
     | > align_error: 0.5671075284481049  (0.6029806150042493)

   --> STEP: 24
     | > decoder_loss: 0.4561208486557007  (0.4495062939822674)
     | > postnet_loss: 0.31080755591392517  (0.31380996728936833)
     | > stopnet_loss: 0.004397103097289801  (0.006260718975681812)
     | > loss: 0.1961292177438736  (0.19708978384733197)
     | > align_error: 0.5793576240539551  (0.6019963237146536)

   --> STEP: 25
     | > decoder_loss: 0.45585763454437256  (0.4497603476047516)
     | > postnet_loss: 0.3083896338939667  (0.31359315395355225)
     | > stopnet_loss: 0.003722390392795205  (0.006159185832366347)
     | > loss: 0.19478420913219452  (0.19699756085872647)
     | > align_error: 0.5577639937400818  (0.6002270305156707)

   --> STEP: 26
     | > decoder_loss: 0.4313593804836273  (0.44905261810009295)
     | > postnet_loss: 0.2980758249759674  (0.3129963336082605)
     | > stopnet_loss: 0.004365777131170034  (0.006090208574628027)
     | > loss: 0.18672457337379456  (0.19660244595545986)
     | > align_error: 0.5464590191841125  (0.5981590300798415)

   --> STEP: 27
     | > decoder_loss: 0.42847540974617004  (0.4482904992721699)
     | > postnet_loss: 0.29248568415641785  (0.31223667992485893)
     | > stopnet_loss: 0.0039275395683944225  (0.006010109722545302)
     | > loss: 0.18416781723499298  (0.1961419041509981)
     | > align_error: 0.5408226251602173  (0.5960354595272628)

   --> STEP: 28
     | > decoder_loss: 0.4338013529777527  (0.447773029761655)
     | > postnet_loss: 0.2971727252006531  (0.3116986815418516)
     | > stopnet_loss: 0.003954994026571512  (0.005936712733403381)
     | > loss: 0.18669851124286652  (0.19580464011856485)
     | > align_error: 0.5662141740322113  (0.5949704136167252)

   --> STEP: 29
     | > decoder_loss: 0.4303368031978607  (0.4471717805698)
     | > postnet_loss: 0.295245498418808  (0.31113133039967766)
     | > stopnet_loss: 0.0035941957030445337  (0.005855936284080662)
     | > loss: 0.18498976528644562  (0.1954317134002159)
     | > align_error: 0.5404305458068848  (0.5930897285198342)

   --> STEP: 30
     | > decoder_loss: 0.4300210475921631  (0.44660008947054547)
     | > postnet_loss: 0.29489606618881226  (0.31059015492598213)
     | > stopnet_loss: 0.002832280471920967  (0.005755147757008671)
     | > loss: 0.18406155705451965  (0.1950527081886927)
     | > align_error: 0.5329299867153168  (0.591084403793017)

   --> STEP: 31
     | > decoder_loss: 0.42686623334884644  (0.44596351346661967)
     | > postnet_loss: 0.29341834783554077  (0.31003622566500016)
     | > stopnet_loss: 0.003712782170623541  (0.005689264996157539)
     | > loss: 0.18378393352031708  (0.19468919932842252)
     | > align_error: 0.5572331547737122  (0.5899924280182006)

   --> STEP: 32
     | > decoder_loss: 0.43726855516433716  (0.44569179601967335)
     | > postnet_loss: 0.29915258288383484  (0.30969611182808876)
     | > stopnet_loss: 0.0038543485570698977  (0.00563192385743605)
     | > loss: 0.18795962631702423  (0.19447890017181632)
     | > align_error: 0.5309226512908936  (0.5881464974954723)

   --> STEP: 33
     | > decoder_loss: 0.4342438578605652  (0.44534488880273065)
     | > postnet_loss: 0.2963997423648834  (0.30929319154132495)
     | > stopnet_loss: 0.004036769270896912  (0.005583585839662136)
     | > loss: 0.18669767677783966  (0.194243105523514)
     | > align_error: 0.5456236004829407  (0.5868579248587289)

   --> STEP: 34
     | > decoder_loss: 0.4407682716846466  (0.4452102824169047)
     | > postnet_loss: 0.2984086573123932  (0.3089730581816505)
     | > stopnet_loss: 0.0033176715951412916  (0.005516941303058583)
     | > loss: 0.18811190128326416  (0.19406277598703606)
     | > align_error: 0.5634784698486328  (0.5861702938290202)

   --> STEP: 35
     | > decoder_loss: 0.438245952129364  (0.4450113015515464)
     | > postnet_loss: 0.2981386184692383  (0.30866350276129584)
     | > stopnet_loss: 0.003506965469568968  (0.005459513422101736)
     | > loss: 0.18760310113430023  (0.19387821384838647)
     | > align_error: 0.5325727462768555  (0.5846389353275298)

   --> STEP: 36
     | > decoder_loss: 0.4443301558494568  (0.44499238083759945)
     | > postnet_loss: 0.30227410793304443  (0.3084860195716222)
     | > stopnet_loss: 0.003694746410474181  (0.005410492116223193)
     | > loss: 0.19034580886363983  (0.19378009148769906)
     | > align_error: 0.6336126327514648  (0.5859993158115279)

   --> STEP: 37
     | > decoder_loss: 0.4365845322608948  (0.4447651416868777)
     | > postnet_loss: 0.2989710867404938  (0.30822885922483495)
     | > stopnet_loss: 0.0035594424698501825  (0.005360463747402301)
     | > loss: 0.18744835257530212  (0.19360896340898562)
     | > align_error: 0.518429696559906  (0.5841731098858084)

   --> STEP: 38
     | > decoder_loss: 0.4241172671318054  (0.44422177656700734)
     | > postnet_loss: 0.291403204202652  (0.30778607882951436)
     | > stopnet_loss: 0.003144050482660532  (0.005302137082540675)
     | > loss: 0.18202418088912964  (0.1933041007110947)
     | > align_error: 0.5511226058006287  (0.5833033597783036)

   --> STEP: 39
     | > decoder_loss: 0.4401197135448456  (0.444116595463875)
     | > postnet_loss: 0.3026416003704071  (0.3076541691254347)
     | > stopnet_loss: 0.003499902319163084  (0.005255925934761763)
     | > loss: 0.18919022381305695  (0.19319861668806806)
     | > align_error: 0.5453748404979706  (0.5823308336429104)

   --> STEP: 40
     | > decoder_loss: 0.437324583530426  (0.4439467951655388)
     | > postnet_loss: 0.30120614171028137  (0.30749296844005586)
     | > stopnet_loss: 0.003047453472390771  (0.005200714123202488)
     | > loss: 0.18768014013767242  (0.19306065477430817)
     | > align_error: 0.5837467312812805  (0.5823662310838696)

   --> STEP: 41
     | > decoder_loss: 0.42802664637565613  (0.44355849885359044)
     | > postnet_loss: 0.2937059700489044  (0.3071567001866131)
     | > stopnet_loss: 0.00372099201194942  (0.005164623340001193)
     | > loss: 0.18415415287017822  (0.19284342302054888)
     | > align_error: 0.5027899742126465  (0.5804253467699374)

   --> STEP: 42
     | > decoder_loss: 0.43208345770835876  (0.4432852835882278)
     | > postnet_loss: 0.2946346402168274  (0.30685855590161826)
     | > stopnet_loss: 0.003290236461907625  (0.005119995080998965)
     | > loss: 0.18496975302696228  (0.1926559546873682)
     | > align_error: 0.5793091058731079  (0.5803987696057271)

   --> STEP: 43
     | > decoder_loss: 0.4316651523113251  (0.44301504797713703)
     | > postnet_loss: 0.29377835988998413  (0.30655436529669655)
     | > stopnet_loss: 0.0029512380715459585  (0.005069558871476802)
     | > loss: 0.184312105178833  (0.19246191167554183)
     | > align_error: 0.55116206407547  (0.5797188462213025)

   --> STEP: 44
     | > decoder_loss: 0.4485054612159729  (0.44313983009620145)
     | > postnet_loss: 0.30438369512557983  (0.30650503188371664)
     | > stopnet_loss: 0.0026755821891129017  (0.005015150310513986)
     | > loss: 0.1908978670835495  (0.192426365207542)
     | > align_error: 0.5505392551422119  (0.5790556736967777)

   --> STEP: 45
     | > decoder_loss: 0.4419836103916168  (0.4431141363249885)
     | > postnet_loss: 0.30339881777763367  (0.30643600490358147)
     | > stopnet_loss: 0.0032992803025990725  (0.004977019865893655)
     | > loss: 0.18964488804340363  (0.19236455460389448)
     | > align_error: 0.5521160662174225  (0.5784570157527921)

   --> STEP: 46
     | > decoder_loss: 0.43316760659217834  (0.4428979074177535)
     | > postnet_loss: 0.29542291164398193  (0.30619658983272063)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35875351139993383 (-0.036255341587644596)
     | > avg_decoder_loss: 0.439370386076696 (+0.0007076859474182129)
     | > avg_postnet_loss: 0.3034973736062194 (+0.0025964966326049166)
     | > avg_stopnet_loss: 0.004379429476984748 (+1.301418524235487e-05)
     | > avg_loss: 0.1900963683923085 (+0.0008390595515568589)
     | > avg_align_error: 0.5713328172763187 (-6.138917171616409e-05)


 > EPOCH: 125/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 15:24:30)

   --> TIME: 2025-12-28 15:24:31 -- STEP: 0/150 -- GLOBAL_STEP: 18875
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4510766863822937  (0.4510766863822937)
     | > postnet_loss: 0.388927698135376  (0.388927698135376)
     | > stopnet_loss: 0.018893824890255928  (0.018893824890255928)
     | > loss: 0.2288949191570282  (0.2288949191570282)
     | > align_error: 0.7495777308940887  (0.7495777308940887)
     | > grad_norm: tensor(0.3450, device='cuda:0')  (tensor(0.3450, device='cuda:0'))
     | > step_time: 0.4717  (0.47167086601257324)
     | > loader_time: 0.4475  (0.4475083351135254)


   --> TIME: 2025-12-28 15:25:08 -- STEP: 25/150 -- GLOBAL_STEP: 18900
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.4777470827102661  (0.46929266571998596)
     | > postnet_loss: 0.40030282735824585  (0.3970795953273773)
     | > stopnet_loss: 0.005909496918320656  (0.009580444265156984)
     | > loss: 0.2254219800233841  (0.2261735099554062)
     | > align_error: 0.6177034378051758  (0.6697375535964966)
     | > grad_norm: tensor(0.3420, device='cuda:0')  (tensor(0.2901, device='cuda:0'))
     | > step_time: 0.8094  (0.6384880924224855)
     | > loader_time: 0.9128  (0.837800235748291)


   --> TIME: 2025-12-28 15:26:01 -- STEP: 50/150 -- GLOBAL_STEP: 18925
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48892834782600403  (0.47673273921012876)
     | > postnet_loss: 0.40326783061027527  (0.3994196683168411)
     | > stopnet_loss: 0.004366821143776178  (0.007509835716336965)
     | > loss: 0.22741585969924927  (0.22654793798923492)
     | > align_error: 0.6360497176647186  (0.6469109189510348)
     | > grad_norm: tensor(0.1455, device='cuda:0')  (tensor(0.2887, device='cuda:0'))
     | > step_time: 1.2268  (0.8600793933868409)
     | > loader_time: 1.2817  (0.9468421697616577)


   --> TIME: 2025-12-28 15:27:10 -- STEP: 75/150 -- GLOBAL_STEP: 18950
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4834110140800476  (0.47957868059476216)
     | > postnet_loss: 0.3965480923652649  (0.39909595489501953)
     | > stopnet_loss: 0.0035405890084803104  (0.00639511678678294)
     | > loss: 0.2235303670167923  (0.22606377601623534)
     | > align_error: 0.6119740307331085  (0.6356847631931307)
     | > grad_norm: tensor(0.4244, device='cuda:0')  (tensor(0.2634, device='cuda:0'))
     | > step_time: 1.6201  (1.0469092718760173)
     | > loader_time: 1.4388  (1.079074697494507)


   --> TIME: 2025-12-28 15:28:31 -- STEP: 100/150 -- GLOBAL_STEP: 18975
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48164767026901245  (0.4808593663573265)
     | > postnet_loss: 0.3933814764022827  (0.3983935484290123)
     | > stopnet_loss: 0.0033232320565730333  (0.005720476047135889)
     | > loss: 0.2220805138349533  (0.22553370431065559)
     | > align_error: 0.5854212045669556  (0.6309411662817004)
     | > grad_norm: tensor(0.1458, device='cuda:0')  (tensor(0.2483, device='cuda:0'))
     | > step_time: 1.6448  (1.186020152568817)
     | > loader_time: 1.4935  (1.2132048511505127)


   --> TIME: 2025-12-28 15:30:00 -- STEP: 125/150 -- GLOBAL_STEP: 19000
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4784996509552002  (0.48194256067276003)
     | > postnet_loss: 0.3897550106048584  (0.3979593789577484)
     | > stopnet_loss: 0.0031963021028786898  (0.005245767192915082)
     | > loss: 0.22025996446609497  (0.22522125124931336)
     | > align_error: 0.5916228890419006  (0.6270319669246676)
     | > grad_norm: tensor(0.1450, device='cuda:0')  (tensor(0.2355, device='cuda:0'))
     | > step_time: 1.8955  (1.3153573341369627)
     | > loader_time: 1.8561  (1.315793264389038)


   --> TIME: 2025-12-28 15:31:54 -- STEP: 150/150 -- GLOBAL_STEP: 19025
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5020944476127625  (0.4836037826538086)
     | > postnet_loss: 0.40566447377204895  (0.39798001110553743)
     | > stopnet_loss: 0.00246504507958889  (0.0048772636288777)
     | > loss: 0.2294047772884369  (0.22527321139971415)
     | > align_error: 0.5845411717891693  (0.6236262587706249)
     | > grad_norm: tensor(0.2543, device='cuda:0')  (tensor(0.2271, device='cuda:0'))
     | > step_time: 10.4278  (1.5437016391754146)
     | > loader_time: 0.7103  (1.4091357453664142)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4589465856552124  (0.4589465856552124)
     | > postnet_loss: 0.33427903056144714  (0.33427903056144714)
     | > stopnet_loss: 0.012178895995020866  (0.012178895995020866)
     | > loss: 0.2104853093624115  (0.2104853093624115)
     | > align_error: 0.7184940576553345  (0.7184940576553345)

   --> STEP: 1
     | > decoder_loss: 0.4401252269744873  (0.4401252269744873)
     | > postnet_loss: 0.322327196598053  (0.322327196598053)
     | > stopnet_loss: 0.009639505296945572  (0.009639505296945572)
     | > loss: 0.20025260746479034  (0.20025260746479034)
     | > align_error: 0.6587508320808411  (0.6587508320808411)

   --> STEP: 2
     | > decoder_loss: 0.4368785321712494  (0.43850187957286835)
     | > postnet_loss: 0.31298330426216125  (0.3176552504301071)
     | > stopnet_loss: 0.011120845563709736  (0.010380175430327654)
     | > loss: 0.19858630001544952  (0.19941945374011993)
     | > align_error: 0.655080109834671  (0.656915470957756)

   --> STEP: 3
     | > decoder_loss: 0.439814954996109  (0.43893957138061523)
     | > postnet_loss: 0.3123839497566223  (0.3158981502056122)
     | > stopnet_loss: 0.00817482266575098  (0.00964505784213543)
     | > loss: 0.19622455537319183  (0.19835448761781058)
     | > align_error: 0.7342862486839294  (0.6827057301998138)

   --> STEP: 4
     | > decoder_loss: 0.4455060064792633  (0.44058118015527725)
     | > postnet_loss: 0.3205600678920746  (0.3170636296272278)
     | > stopnet_loss: 0.008189624175429344  (0.009281199425458908)
     | > loss: 0.19970613718032837  (0.19869240000844002)
     | > align_error: 0.6025129556655884  (0.6626575365662575)

   --> STEP: 5
     | > decoder_loss: 0.4286843538284302  (0.43820181488990784)
     | > postnet_loss: 0.30353742837905884  (0.31435838937759397)
     | > stopnet_loss: 0.00812408048659563  (0.009049775637686252)
     | > loss: 0.1911795288324356  (0.19718982577323912)
     | > align_error: 0.6413693726062775  (0.6583999037742615)

   --> STEP: 6
     | > decoder_loss: 0.4446181356906891  (0.439271201690038)
     | > postnet_loss: 0.31549879908561707  (0.3145484576622645)
     | > stopnet_loss: 0.007275658193975687  (0.008754089397067824)
     | > loss: 0.1973048895597458  (0.19720900307099024)
     | > align_error: 0.5929606556892395  (0.6474933624267578)

   --> STEP: 7
     | > decoder_loss: 0.4565489590167999  (0.44173945273671833)
     | > postnet_loss: 0.3149947226047516  (0.3146122097969055)
     | > stopnet_loss: 0.006301719229668379  (0.008403750801725047)
     | > loss: 0.19918763637542725  (0.1974916649716241)
     | > align_error: 0.5780618488788605  (0.6375745747770581)

   --> STEP: 8
     | > decoder_loss: 0.4515298306941986  (0.44296324998140335)
     | > postnet_loss: 0.316270112991333  (0.31481944769620895)
     | > stopnet_loss: 0.007417422253638506  (0.00828045973321423)
     | > loss: 0.19936741888523102  (0.19772613421082497)
     | > align_error: 0.5745684504508972  (0.6296988092362881)

   --> STEP: 9
     | > decoder_loss: 0.44761985540390015  (0.443480650583903)
     | > postnet_loss: 0.31480634212493896  (0.3148179915216234)
     | > stopnet_loss: 0.006617753300815821  (0.008095714574058851)
     | > loss: 0.19722430408000946  (0.19767037530740103)
     | > align_error: 0.5902897715568542  (0.6253200272719065)

   --> STEP: 10
     | > decoder_loss: 0.47241920232772827  (0.4463745057582855)
     | > postnet_loss: 0.32872211933135986  (0.31620840430259706)
     | > stopnet_loss: 0.005577948875725269  (0.007843938004225493)
     | > loss: 0.20586328208446503  (0.19848966598510742)
     | > align_error: 0.5824631750583649  (0.6210343420505524)

   --> STEP: 11
     | > decoder_loss: 0.46147122979164124  (0.44774693521586334)
     | > postnet_loss: 0.31939491629600525  (0.3164980872110887)
     | > stopnet_loss: 0.005913003347814083  (0.007668398490006273)
     | > loss: 0.20112954080104828  (0.1987296546047384)
     | > align_error: 0.5937889814376831  (0.6185574910857461)

   --> STEP: 12
     | > decoder_loss: 0.45526382327079773  (0.44837334255377453)
     | > postnet_loss: 0.31229591369628906  (0.3161479060848554)
     | > stopnet_loss: 0.007918957620859146  (0.007689278417577346)
     | > loss: 0.19980889558792114  (0.19881959135333696)
     | > align_error: 0.5865563750267029  (0.6158907314141592)

   --> STEP: 13
     | > decoder_loss: 0.446593314409256  (0.44823641731188846)
     | > postnet_loss: 0.31287139654159546  (0.31589586688922)
     | > stopnet_loss: 0.005608926061540842  (0.0075292513132668454)
     | > loss: 0.19547511637210846  (0.19856232404708862)
     | > align_error: 0.5848222374916077  (0.6135008472662705)

   --> STEP: 14
     | > decoder_loss: 0.4560534358024597  (0.4487947757755007)
     | > postnet_loss: 0.3146713078022003  (0.31580839838300434)
     | > stopnet_loss: 0.004938106052577496  (0.0073441695089318925)
     | > loss: 0.19761930406093597  (0.19849496547664916)
     | > align_error: 0.5537012815475464  (0.6092294497149331)

   --> STEP: 15
     | > decoder_loss: 0.45612064003944397  (0.44928316672643026)
     | > postnet_loss: 0.3150569796562195  (0.31575830380121866)
     | > stopnet_loss: 0.00500414939597249  (0.007188168168067932)
     | > loss: 0.19779856503009796  (0.1984485387802124)
     | > align_error: 0.5876989960670471  (0.6077940861384074)

   --> STEP: 16
     | > decoder_loss: 0.45675599575042725  (0.44975021854043007)
     | > postnet_loss: 0.30937740206718445  (0.31535949744284153)
     | > stopnet_loss: 0.005260127130895853  (0.007067665603244677)
     | > loss: 0.19679348170757294  (0.19834509771317244)
     | > align_error: 0.6054398417472839  (0.6076469458639622)

   --> STEP: 17
     | > decoder_loss: 0.46370288729667664  (0.4505709637613857)
     | > postnet_loss: 0.31782254576683044  (0.3155043826383703)
     | > stopnet_loss: 0.004847171250730753  (0.0069370482883909165)
     | > loss: 0.2002285271883011  (0.19845588768229766)
     | > align_error: 0.5577687919139862  (0.6047129368080812)

   --> STEP: 18
     | > decoder_loss: 0.45819905400276184  (0.4509947465525733)
     | > postnet_loss: 0.3106311857700348  (0.31523364947901833)
     | > stopnet_loss: 0.0052858516573905945  (0.006845315142224233)
     | > loss: 0.19749340415000916  (0.1984024163749483)
     | > align_error: 0.6034543514251709  (0.6046430153979195)

   --> STEP: 19
     | > decoder_loss: 0.45508909225463867  (0.4512102384316294)
     | > postnet_loss: 0.30960679054260254  (0.3149374990086806)
     | > stopnet_loss: 0.00472809886559844  (0.0067338827066123486)
     | > loss: 0.19590206444263458  (0.1982708189048265)
     | > align_error: 0.5990054905414581  (0.6043463035633689)

   --> STEP: 20
     | > decoder_loss: 0.4515751302242279  (0.4512284830212593)
     | > postnet_loss: 0.3056703805923462  (0.3144741430878639)
     | > stopnet_loss: 0.004534175153821707  (0.006623897328972816)
     | > loss: 0.19384555518627167  (0.19804955571889876)
     | > align_error: 0.6221990585327148  (0.6052389413118362)

   --> STEP: 21
     | > decoder_loss: 0.4484114944934845  (0.4510943407104129)
     | > postnet_loss: 0.3048902750015259  (0.3140177684170859)
     | > stopnet_loss: 0.003981491085141897  (0.006498068460218963)
     | > loss: 0.19230692088603973  (0.19777609691733405)
     | > align_error: 0.5591490268707275  (0.6030441834813073)

   --> STEP: 22
     | > decoder_loss: 0.45182332396507263  (0.4511274763128974)
     | > postnet_loss: 0.3083987832069397  (0.3137623599984429)
     | > stopnet_loss: 0.004880916327238083  (0.0064245615450834685)
     | > loss: 0.19493643939495087  (0.19764702157540756)
     | > align_error: 0.624697208404541  (0.6040284118869088)

   --> STEP: 23
     | > decoder_loss: 0.42455270886421204  (0.44997205164121545)
     | > postnet_loss: 0.2959912419319153  (0.3129897026912025)
     | > stopnet_loss: 0.004510162863880396  (0.006341326819813769)
     | > loss: 0.18464615941047668  (0.19708176669867142)
     | > align_error: 0.5667332410812378  (0.6024068827214448)

   --> STEP: 24
     | > decoder_loss: 0.45899802446365356  (0.4503481338421504)
     | > postnet_loss: 0.31141120195388794  (0.3129239318271477)
     | > stopnet_loss: 0.004396684002131224  (0.006260300035743664)
     | > loss: 0.1969989836215973  (0.19707831740379333)
     | > align_error: 0.5790037214756012  (0.601431751002868)

   --> STEP: 25
     | > decoder_loss: 0.4583077132701874  (0.45066651701927185)
     | > postnet_loss: 0.3086608052253723  (0.3127534067630767)
     | > stopnet_loss: 0.00373566010966897  (0.0061593144387006755)
     | > loss: 0.19547778367996216  (0.19701429605484008)
     | > align_error: 0.5571585297584534  (0.5996608221530915)

   --> STEP: 26
     | > decoder_loss: 0.4326191842556  (0.4499723888360537)
     | > postnet_loss: 0.2973320186138153  (0.31216027644964356)
     | > stopnet_loss: 0.004381433129310608  (0.0060909343883395195)
     | > loss: 0.18686923384666443  (0.19662410135452563)
     | > align_error: 0.5462075471878052  (0.5976049269621189)

   --> STEP: 27
     | > decoder_loss: 0.42988917231559753  (0.44922856600196276)
     | > postnet_loss: 0.2922042906284332  (0.3114211658636728)
     | > stopnet_loss: 0.003935449756681919  (0.006011101624204053)
     | > loss: 0.18445882201194763  (0.1961735354529487)
     | > align_error: 0.5406184792518616  (0.5954943177876649)

   --> STEP: 28
     | > decoder_loss: 0.43554848432540894  (0.4487399916563715)
     | > postnet_loss: 0.29699650406837463  (0.3109059993709836)
     | > stopnet_loss: 0.003945849370211363  (0.005937342615132886)
     | > loss: 0.18708209693431854  (0.19584884122014046)
     | > align_error: 0.5657540261745453  (0.5944321645157677)

   --> STEP: 29
     | > decoder_loss: 0.4305485486984253  (0.4481127005198906)
     | > postnet_loss: 0.2938001751899719  (0.31031614336474184)
     | > stopnet_loss: 0.003584005869925022  (0.005856193072194683)
     | > loss: 0.18467119336128235  (0.19546340508707638)
     | > align_error: 0.539781928062439  (0.5925476736035841)

   --> STEP: 30
     | > decoder_loss: 0.4308404326438904  (0.4475369582573573)
     | > postnet_loss: 0.2941409945487976  (0.3097769717375437)
     | > stopnet_loss: 0.0028524952940642834  (0.00575606981292367)
     | > loss: 0.18409785628318787  (0.1950845534602801)
     | > align_error: 0.5326675772666931  (0.5905516703923543)

   --> STEP: 31
     | > decoder_loss: 0.4295838177204132  (0.4469578246916494)
     | > postnet_loss: 0.29388147592544556  (0.30926421380812114)
     | > stopnet_loss: 0.0036837714724242687  (0.005689221479359173)
     | > loss: 0.18455010652542114  (0.19474473259141367)
     | > align_error: 0.5565629601478577  (0.5894552603844674)

   --> STEP: 32
     | > decoder_loss: 0.4392791986465454  (0.4467178676277399)
     | > postnet_loss: 0.29910197854042053  (0.3089466439560055)
     | > stopnet_loss: 0.0038591111078858376  (0.005632030530250631)
     | > loss: 0.18845440447330475  (0.19454815983772278)
     | > align_error: 0.5303425192832947  (0.5876079872250557)

   --> STEP: 33
     | > decoder_loss: 0.4366012215614319  (0.44641130259542755)
     | > postnet_loss: 0.29659098386764526  (0.30857223001393397)
     | > stopnet_loss: 0.004031584598124027  (0.005583532168671038)
     | > loss: 0.18732963502407074  (0.1943294166615515)
     | > align_error: 0.5454631447792053  (0.5863308707873026)

   --> STEP: 34
     | > decoder_loss: 0.442268043756485  (0.446289442041341)
     | > postnet_loss: 0.298188716173172  (0.30826683254802917)
     | > stopnet_loss: 0.0033228767570108175  (0.005517042303622207)
     | > loss: 0.1884370595216751  (0.19415611203979044)
     | > align_error: 0.5629839897155762  (0.5856441978146049)

   --> STEP: 35
     | > decoder_loss: 0.43934422731399536  (0.4460910073348454)
     | > postnet_loss: 0.29745978116989136  (0.30795805965151096)
     | > stopnet_loss: 0.0035091927275061607  (0.0054596751728760344)
     | > loss: 0.18771019577980042  (0.19397194300379073)
     | > align_error: 0.532557487487793  (0.5841274346624102)

   --> STEP: 36
     | > decoder_loss: 0.445281445980072  (0.44606851951943505)
     | > postnet_loss: 0.30151599645614624  (0.3077791134516397)
     | > stopnet_loss: 0.003685460891574621  (0.005410391442839884)
     | > loss: 0.19038482010364532  (0.19387230070100891)
     | > align_error: 0.6331484615802765  (0.5854891298545731)

   --> STEP: 37
     | > decoder_loss: 0.4375857710838318  (0.4458392560482025)
     | > postnet_loss: 0.2983129322528839  (0.3075232707165382)
     | > stopnet_loss: 0.00356544042006135  (0.005360527901683707)
     | > loss: 0.18754012882709503  (0.19370116092063286)
     | > align_error: 0.5180459320545197  (0.5836663407248419)

   --> STEP: 38
     | > decoder_loss: 0.4249727427959442  (0.4452901372784062)
     | > postnet_loss: 0.29075753688812256  (0.30708206719473774)
     | > stopnet_loss: 0.00316034397110343  (0.005302628324563174)
     | > loss: 0.18209291994571686  (0.19339568089497716)
     | > align_error: 0.5508393347263336  (0.5828024721459337)

   --> STEP: 39
     | > decoder_loss: 0.4408314526081085  (0.44517581203044987)
     | > postnet_loss: 0.301563560962677  (0.3069405670349413)
     | > stopnet_loss: 0.0034929481334984303  (0.005256226268382028)
     | > loss: 0.18909171223640442  (0.19328532272424453)
     | > align_error: 0.5451012253761292  (0.5818357735108106)

   --> STEP: 40
     | > decoder_loss: 0.43776455521583557  (0.44499053061008453)
     | > postnet_loss: 0.29996395111083984  (0.3067661516368388)
     | > stopnet_loss: 0.003053048625588417  (0.005201146827312188)
     | > loss: 0.18748517334461212  (0.19314031898975373)
     | > align_error: 0.5832679867744446  (0.5818715788424015)

   --> STEP: 41
     | > decoder_loss: 0.42830029129981995  (0.4445834516025171)
     | > postnet_loss: 0.2923388183116913  (0.3064142654581766)
     | > stopnet_loss: 0.0037320114206522703  (0.005165314256418044)
     | > loss: 0.18389178812503815  (0.19291474506622408)
     | > align_error: 0.5021769404411316  (0.5799278071740779)

   --> STEP: 42
     | > decoder_loss: 0.4335425794124603  (0.44432057369323)
     | > postnet_loss: 0.2941015362739563  (0.30612110523950475)
     | > stopnet_loss: 0.0032832676079124212  (0.005120503621929814)
     | > loss: 0.18519428372383118  (0.19273092455807186)
     | > align_error: 0.5788973271846771  (0.5799032719362349)

   --> STEP: 43
     | > decoder_loss: 0.43309667706489563  (0.4440595528414083)
     | > postnet_loss: 0.2932816743850708  (0.3058225138242854)
     | > stopnet_loss: 0.0029467688873410225  (0.005069951651357982)
     | > loss: 0.18454134464263916  (0.19254046921120133)
     | > align_error: 0.5509505867958069  (0.5792299536771551)

   --> STEP: 44
     | > decoder_loss: 0.4495541453361511  (0.44418442994356155)
     | > postnet_loss: 0.3034634590148926  (0.30576889894225373)
     | > stopnet_loss: 0.0026732562109827995  (0.005015481300440364)
     | > loss: 0.190927654504776  (0.19250381433150984)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.38528492595210223 (+0.026531414552168398)
     | > avg_decoder_loss: 0.4398526151974996 (+0.00048222912080359004)
     | > avg_postnet_loss: 0.3022192630803946 (-0.001278110525824827)
     | > avg_stopnet_loss: 0.004376265523729453 (-3.1639532552954833e-06)
     | > avg_loss: 0.18989423526958985 (-0.0002021331227186618)
     | > avg_align_error: 0.5708575664144572 (-0.0004752508618615092)


 > EPOCH: 126/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 15:33:43)

   --> TIME: 2025-12-28 15:34:20 -- STEP: 24/150 -- GLOBAL_STEP: 19050
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48023927211761475  (0.46873562783002853)
     | > postnet_loss: 0.4039210081100464  (0.39688006043434143)
     | > stopnet_loss: 0.0063575804233551025  (0.009719061917470146)
     | > loss: 0.22739765048027039  (0.22612298342088857)
     | > align_error: 0.6933436393737793  (0.6728741104404131)
     | > grad_norm: tensor(0.4964, device='cuda:0')  (tensor(0.3276, device='cuda:0'))
     | > step_time: 0.8673  (0.6489152113596598)
     | > loader_time: 0.9235  (0.848363866408666)


   --> TIME: 2025-12-28 15:35:14 -- STEP: 49/150 -- GLOBAL_STEP: 19075
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4826909899711609  (0.47647885096316434)
     | > postnet_loss: 0.3984436094760895  (0.3993178374913274)
     | > stopnet_loss: 0.004952212329953909  (0.007547221707218155)
     | > loss: 0.22523586452007294  (0.2264963935832588)
     | > align_error: 0.5832042098045349  (0.6475292827401843)
     | > grad_norm: tensor(0.1814, device='cuda:0')  (tensor(0.3157, device='cuda:0'))
     | > step_time: 1.2905  (0.8726177750801554)
     | > loader_time: 1.154  (0.942909454812809)


   --> TIME: 2025-12-28 15:36:22 -- STEP: 74/150 -- GLOBAL_STEP: 19100
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4825921356678009  (0.47974149963340246)
     | > postnet_loss: 0.3959406018257141  (0.3993147760629654)
     | > stopnet_loss: 0.0035983428824692965  (0.006404276251339832)
     | > loss: 0.22323153913021088  (0.22616834616338885)
     | > align_error: 0.6030716001987457  (0.6360535569287635)
     | > grad_norm: tensor(0.1718, device='cuda:0')  (tensor(0.2909, device='cuda:0'))
     | > step_time: 1.4878  (1.060049211656725)
     | > loader_time: 1.33  (1.0648388218235325)


   --> TIME: 2025-12-28 15:37:42 -- STEP: 99/150 -- GLOBAL_STEP: 19125
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4895703196525574  (0.480981689811957)
     | > postnet_loss: 0.3986058235168457  (0.39859076340993244)
     | > stopnet_loss: 0.003372090170159936  (0.005734992110066944)
     | > loss: 0.2254161238670349  (0.225628106130494)
     | > align_error: 0.6036867797374725  (0.6311776008870866)
     | > grad_norm: tensor(0.2994, device='cuda:0')  (tensor(0.2774, device='cuda:0'))
     | > step_time: 1.8767  (1.2144793019150242)
     | > loader_time: 1.6232  (1.1865081136876878)


   --> TIME: 2025-12-28 15:39:19 -- STEP: 124/150 -- GLOBAL_STEP: 19150
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4827452003955841  (0.48197157008032643)
     | > postnet_loss: 0.3930763602256775  (0.39800342749203405)
     | > stopnet_loss: 0.0034332512877881527  (0.005250978490127431)
     | > loss: 0.22238865494728088  (0.22524472866808215)
     | > align_error: 0.6134291291236877  (0.6270265389353998)
     | > grad_norm: tensor(0.2457, device='cuda:0')  (tensor(0.2605, device='cuda:0'))
     | > step_time: 1.8911  (1.3561583795855123)
     | > loader_time: 2.1803  (1.3372140469089624)


   --> TIME: 2025-12-28 15:41:16 -- STEP: 149/150 -- GLOBAL_STEP: 19175
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5139756202697754  (0.48349175957225315)
     | > postnet_loss: 0.41276809573173523  (0.3979103373201101)
     | > stopnet_loss: 0.0024808812886476517  (0.004879557402591978)
     | > loss: 0.23416681587696075  (0.22523008276952194)
     | > align_error: 0.6254083514213562  (0.6238436038862138)
     | > grad_norm: tensor(0.2017, device='cuda:0')  (tensor(0.2482, device='cuda:0'))
     | > step_time: 13.811  (1.583956315213402)
     | > loader_time: 2.5511  (1.4471415929346272)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4594970941543579  (0.4594970941543579)
     | > postnet_loss: 0.33287954330444336  (0.33287954330444336)
     | > stopnet_loss: 0.012233728542923927  (0.012233728542923927)
     | > loss: 0.2103278934955597  (0.2103278934955597)
     | > align_error: 0.7186039090156555  (0.7186039090156555)

   --> STEP: 1
     | > decoder_loss: 0.4400523900985718  (0.4400523900985718)
     | > postnet_loss: 0.31969770789146423  (0.31969770789146423)
     | > stopnet_loss: 0.00967058353126049  (0.00967058353126049)
     | > loss: 0.19960811734199524  (0.19960811734199524)
     | > align_error: 0.6591354608535767  (0.6591354608535767)

   --> STEP: 2
     | > decoder_loss: 0.4364790618419647  (0.43826572597026825)
     | > postnet_loss: 0.311665415763855  (0.3156815618276596)
     | > stopnet_loss: 0.011101363226771355  (0.010385973379015923)
     | > loss: 0.19813749194145203  (0.19887280464172363)
     | > align_error: 0.6554181277751923  (0.6572767943143845)

   --> STEP: 3
     | > decoder_loss: 0.4391602575778961  (0.43856390317281085)
     | > postnet_loss: 0.3102681636810303  (0.31387709577878314)
     | > stopnet_loss: 0.008228860795497894  (0.00966693585117658)
     | > loss: 0.1955859661102295  (0.19777719179789224)
     | > align_error: 0.7339967787265778  (0.6828501224517822)

   --> STEP: 4
     | > decoder_loss: 0.4442002773284912  (0.43997299671173096)
     | > postnet_loss: 0.3181723356246948  (0.3149509057402611)
     | > stopnet_loss: 0.008171841502189636  (0.009293162263929844)
     | > loss: 0.19876499474048615  (0.19802414253354073)
     | > align_error: 0.6029254794120789  (0.6628689616918564)

   --> STEP: 5
     | > decoder_loss: 0.42725545167922974  (0.4374294877052307)
     | > postnet_loss: 0.3018014430999756  (0.31232101321220396)
     | > stopnet_loss: 0.008060026913881302  (0.009046535193920135)
     | > loss: 0.19032424688339233  (0.19648416340351105)
     | > align_error: 0.6416191756725311  (0.6586190044879914)

   --> STEP: 6
     | > decoder_loss: 0.4441382586956024  (0.438547616203626)
     | > postnet_loss: 0.3134903311729431  (0.31251589953899384)
     | > stopnet_loss: 0.007253563497215509  (0.008747706577802697)
     | > loss: 0.19666069746017456  (0.1965135857462883)
     | > align_error: 0.5932941734790802  (0.6477315326531728)

   --> STEP: 7
     | > decoder_loss: 0.4552563726902008  (0.44093458141599384)
     | > postnet_loss: 0.3134244978427887  (0.3126456992966788)
     | > stopnet_loss: 0.006250718142837286  (0.008390993944236211)
     | > loss: 0.1984209418296814  (0.19678606518677302)
     | > align_error: 0.57846999168396  (0.6378370268004281)

   --> STEP: 8
     | > decoder_loss: 0.44950902462005615  (0.4420063868165016)
     | > postnet_loss: 0.3136007785797119  (0.31276508420705795)
     | > stopnet_loss: 0.007238158956170082  (0.008246889570727944)
     | > loss: 0.19801561534404755  (0.19693975895643234)
     | > align_error: 0.5749052166938782  (0.6299705505371094)

   --> STEP: 9
     | > decoder_loss: 0.4477609694004059  (0.44264578488137984)
     | > postnet_loss: 0.31385567784309387  (0.3128862612777286)
     | > stopnet_loss: 0.006663466338068247  (0.008070953655987978)
     | > loss: 0.19706763327121735  (0.19695396721363068)
     | > align_error: 0.5907424986362457  (0.6256118781036801)

   --> STEP: 10
     | > decoder_loss: 0.4716641306877136  (0.44554761946201327)
     | > postnet_loss: 0.32712316513061523  (0.3143099516630173)
     | > stopnet_loss: 0.005613712593913078  (0.007825229549780488)
     | > loss: 0.20531053841114044  (0.19778962433338165)
     | > align_error: 0.5833286643028259  (0.6213835567235947)

   --> STEP: 11
     | > decoder_loss: 0.45969632267951965  (0.44683386520905927)
     | > postnet_loss: 0.31815358996391296  (0.31465937332673505)
     | > stopnet_loss: 0.005878503900021315  (0.0076482544907114725)
     | > loss: 0.20034098625183105  (0.19802156632596796)
     | > align_error: 0.5942578315734863  (0.6189175817099485)

   --> STEP: 12
     | > decoder_loss: 0.4552040100097656  (0.4475313772757848)
     | > postnet_loss: 0.3114332854747772  (0.31439053267240524)
     | > stopnet_loss: 0.007916719652712345  (0.007670626587544878)
     | > loss: 0.19957605004310608  (0.19815110663572946)
     | > align_error: 0.5870348215103149  (0.6162606850266457)

   --> STEP: 13
     | > decoder_loss: 0.44543397426605225  (0.44737003858272845)
     | > postnet_loss: 0.31163692474365234  (0.31417871667788577)
     | > stopnet_loss: 0.00557490810751915  (0.007509417473696745)
     | > loss: 0.1948426365852356  (0.19789660893953764)
     | > align_error: 0.5851631760597229  (0.6138685689522669)

   --> STEP: 14
     | > decoder_loss: 0.453066885471344  (0.4477769562176296)
     | > postnet_loss: 0.31247764825820923  (0.314057211790766)
     | > stopnet_loss: 0.004923087079077959  (0.007324679588366832)
     | > loss: 0.19630922377109528  (0.1977832242846489)
     | > align_error: 0.5543316602706909  (0.6096159326178687)

   --> STEP: 15
     | > decoder_loss: 0.45458465814590454  (0.4482308030128479)
     | > postnet_loss: 0.3150724768638611  (0.3141248961289724)
     | > stopnet_loss: 0.004993653856217861  (0.007169277872890234)
     | > loss: 0.19740793108940125  (0.19775820473829905)
     | > align_error: 0.5880553722381592  (0.608178561925888)

   --> STEP: 16
     | > decoder_loss: 0.4552176892757416  (0.44866748340427876)
     | > postnet_loss: 0.3087603747844696  (0.31378961354494095)
     | > stopnet_loss: 0.005280615296214819  (0.0070512364618480206)
     | > loss: 0.19627512991428375  (0.1976655125617981)
     | > align_error: 0.6059034168720245  (0.6080363653600216)

   --> STEP: 17
     | > decoder_loss: 0.4622940421104431  (0.44946904568111196)
     | > postnet_loss: 0.3175521790981293  (0.3140109409304226)
     | > stopnet_loss: 0.004853269085288048  (0.006921944263226846)
     | > loss: 0.1998148113489151  (0.19779194190221674)
     | > align_error: 0.5583702325820923  (0.6051148281377905)

   --> STEP: 18
     | > decoder_loss: 0.4568198323249817  (0.44987742271688247)
     | > postnet_loss: 0.31020042300224304  (0.3137992454899682)
     | > stopnet_loss: 0.0052475095726549625  (0.00682892011375063)
     | > loss: 0.1970025599002838  (0.1977480873465538)
     | > align_error: 0.603888750076294  (0.6050467126899295)

   --> STEP: 19
     | > decoder_loss: 0.45253801345825195  (0.45001745380853353)
     | > postnet_loss: 0.30876341462135315  (0.3135342017600411)
     | > stopnet_loss: 0.004712400026619434  (0.006717524319691093)
     | > loss: 0.19503775238990784  (0.19760543813830928)
     | > align_error: 0.599994957447052  (0.6047808308350412)

   --> STEP: 20
     | > decoder_loss: 0.45069271326065063  (0.45005121678113935)
     | > postnet_loss: 0.30627205967903137  (0.3131710946559906)
     | > stopnet_loss: 0.004496575333178043  (0.006606476870365441)
     | > loss: 0.19373777508735657  (0.19741205498576164)
     | > align_error: 0.6227279305458069  (0.6056781858205794)

   --> STEP: 21
     | > decoder_loss: 0.44763216376304626  (0.4499360237802778)
     | > postnet_loss: 0.3048202693462372  (0.3127734363079071)
     | > stopnet_loss: 0.003979180008172989  (0.006481367495975324)
     | > loss: 0.19209228456020355  (0.19715873258454458)
     | > align_error: 0.5600125193595886  (0.603503630274818)

   --> STEP: 22
     | > decoder_loss: 0.4511805474758148  (0.44999259303916583)
     | > postnet_loss: 0.30875593423843384  (0.3125908225774765)
     | > stopnet_loss: 0.004842640366405249  (0.006406879899176684)
     | > loss: 0.19482675194740295  (0.19705273346467453)
     | > align_error: 0.6253561079502106  (0.6044969247146086)

   --> STEP: 23
     | > decoder_loss: 0.42345383763313293  (0.44883873410846875)
     | > postnet_loss: 0.2958057224750519  (0.3118610356165015)
     | > stopnet_loss: 0.004509373102337122  (0.0063243796036619206)
     | > loss: 0.1843242645263672  (0.19649932177170462)
     | > align_error: 0.567423015832901  (0.6028850156327953)

   --> STEP: 24
     | > decoder_loss: 0.45801377296447754  (0.4492210273941358)
     | > postnet_loss: 0.31201881170272827  (0.3118676096200943)
     | > stopnet_loss: 0.004380299709737301  (0.006243376274748395)
     | > loss: 0.19688844680786133  (0.19651553531487784)
     | > align_error: 0.5798301696777344  (0.6019243970513344)

   --> STEP: 25
     | > decoder_loss: 0.4571603238582611  (0.4495385992527008)
     | > postnet_loss: 0.3089675009250641  (0.31175160527229306)
     | > stopnet_loss: 0.003707088530063629  (0.006141924764961004)
     | > loss: 0.19523903727531433  (0.19646447539329528)
     | > align_error: 0.5582859516143799  (0.6001788592338562)

   --> STEP: 26
     | > decoder_loss: 0.4321008324623108  (0.4488679159146089)
     | > postnet_loss: 0.29770028591156006  (0.3112111699122649)
     | > stopnet_loss: 0.004354893695563078  (0.006073192800753391)
     | > loss: 0.18680517375469208  (0.19609296379181054)
     | > align_error: 0.5469539761543274  (0.598131748346182)

   --> STEP: 27
     | > decoder_loss: 0.4286942780017853  (0.44812074414005987)
     | > postnet_loss: 0.29255783557891846  (0.3105203056776965)
     | > stopnet_loss: 0.003919786307960749  (0.005993437004724034)
     | > loss: 0.18423280119895935  (0.19565369851059383)
     | > align_error: 0.5413760542869568  (0.5960296856032478)

   --> STEP: 28
     | > decoder_loss: 0.4349057972431183  (0.44764878175088335)
     | > postnet_loss: 0.2973400056362152  (0.310049580676215)
     | > stopnet_loss: 0.003928066231310368  (0.005919673762816403)
     | > loss: 0.18698951601982117  (0.19534426342163766)
     | > align_error: 0.5664947032928467  (0.5949748648064477)

   --> STEP: 29
     | > decoder_loss: 0.42952072620391846  (0.4470236763871949)
     | > postnet_loss: 0.29387304186820984  (0.30949176899318037)
     | > stopnet_loss: 0.003580414690077305  (0.005839009656859883)
     | > loss: 0.184428870677948  (0.194967870568407)
     | > align_error: 0.5404897928237915  (0.5930960692208389)

   --> STEP: 30
     | > decoder_loss: 0.4307263493537903  (0.44648043215274813)
     | > postnet_loss: 0.29489368200302124  (0.3090051660935084)
     | > stopnet_loss: 0.002832806436344981  (0.005738802882842719)
     | > loss: 0.18423780798912048  (0.1946102018157641)
     | > align_error: 0.5335395336151123  (0.5911108513673147)

   --> STEP: 31
     | > decoder_loss: 0.4265282452106476  (0.445836813219132)
     | > postnet_loss: 0.29350796341896057  (0.3085052563298133)
     | > stopnet_loss: 0.003683600341901183  (0.005672506026683315)
     | > loss: 0.18369264900684357  (0.19425802269289572)
     | > align_error: 0.5554854273796082  (0.5899616441419048)

   --> STEP: 32
     | > decoder_loss: 0.43845468759536743  (0.4456061217933893)
     | > postnet_loss: 0.29943403601646423  (0.30822178069502115)
     | > stopnet_loss: 0.003843319835141301  (0.005615343958197627)
     | > loss: 0.1883154958486557  (0.1940723187290132)
     | > align_error: 0.5311101973056793  (0.5881225364282727)

   --> STEP: 33
     | > decoder_loss: 0.43508943915367126  (0.4452874344406706)
     | > postnet_loss: 0.2971954941749573  (0.30788765080047376)
     | > stopnet_loss: 0.004011005163192749  (0.005566727631076267)
     | > loss: 0.1870822310447693  (0.1938604978900967)
     | > align_error: 0.5461296439170837  (0.5868500245339943)

   --> STEP: 34
     | > decoder_loss: 0.4411257207393646  (0.4451650310965145)
     | > postnet_loss: 0.2987979054450989  (0.3076203053488451)
     | > stopnet_loss: 0.0032904106192290783  (0.005499777130727821)
     | > loss: 0.18827131390571594  (0.19369611012585022)
     | > align_error: 0.5639047920703888  (0.5861751647556529)

   --> STEP: 35
     | > decoder_loss: 0.43895775079727173  (0.44498768023082186)
     | > postnet_loss: 0.29821306467056274  (0.3073515270437513)
     | > stopnet_loss: 0.003509700298309326  (0.005442917792658721)
     | > loss: 0.18780240416526794  (0.19352771852697645)
     | > align_error: 0.5334657728672028  (0.5846691821302686)

   --> STEP: 36
     | > decoder_loss: 0.4441717863082886  (0.4449650165107515)
     | > postnet_loss: 0.30228790640830994  (0.30721087091498905)
     | > stopnet_loss: 0.0036573742982000113  (0.0053933193622570895)
     | > loss: 0.19027230143547058  (0.19343729027443463)
     | > align_error: 0.6337841153144836  (0.5860334858298302)

   --> STEP: 37
     | > decoder_loss: 0.43665844202041626  (0.4447405144974992)
     | > postnet_loss: 0.29866740107536316  (0.3069799663247289)
     | > stopnet_loss: 0.0035648758057504892  (0.005343901968837992)
     | > loss: 0.1873963326215744  (0.19327402114868164)
     | > align_error: 0.5190613269805908  (0.5842234274825534)

   --> STEP: 38
     | > decoder_loss: 0.42437154054641724  (0.4442044888672076)
     | > postnet_loss: 0.291573703289032  (0.3065745383501053)
     | > stopnet_loss: 0.0031453196424990892  (0.005286044539197495)
     | > loss: 0.18213163316249847  (0.19298080041220314)
     | > align_error: 0.5516552627086639  (0.5833663705148195)

   --> STEP: 39
     | > decoder_loss: 0.43996357917785645  (0.44409574759312165)
     | > postnet_loss: 0.30213525891304016  (0.3064607106722318)
     | > stopnet_loss: 0.0034720192197710276  (0.005239531069468611)
     | > loss: 0.18899671733379364  (0.19287864443583366)
     | > align_error: 0.5458249449729919  (0.5824037698599008)

   --> STEP: 40
     | > decoder_loss: 0.4367060363292694  (0.44391100481152534)
     | > postnet_loss: 0.3006707429885864  (0.3063159614801406)
     | > stopnet_loss: 0.003027093131095171  (0.0051842201210092744)
     | > loss: 0.18737129867076874  (0.19274096079170705)
     | > align_error: 0.5839995443820953  (0.5824436642229557)

   --> STEP: 41
     | > decoder_loss: 0.4278370440006256  (0.4435189569868693)
     | > postnet_loss: 0.2930198907852173  (0.30599166707294734)
     | > stopnet_loss: 0.0037163894157856703  (0.005148419372101382)
     | > loss: 0.18393062055110931  (0.1925260744443754)
     | > align_error: 0.5031351447105408  (0.5805093100885066)

   --> STEP: 42
     | > decoder_loss: 0.4325178265571594  (0.4432570253099714)
     | > postnet_loss: 0.2951355278491974  (0.30573318756761997)
     | > stopnet_loss: 0.0032905007246881723  (0.00510418321382964)
     | > loss: 0.18520385026931763  (0.19235173577354067)
     | > align_error: 0.5794872045516968  (0.5804849742423921)

   --> STEP: 43
     | > decoder_loss: 0.4315114915370941  (0.442983873361765)
     | > postnet_loss: 0.2940528690814972  (0.3054615522539892)
     | > stopnet_loss: 0.0029328186064958572  (0.005053686362496296)
     | > loss: 0.18432390689849854  (0.19216504207877225)
     | > align_error: 0.5517186522483826  (0.5798159900099733)

   --> STEP: 44
     | > decoder_loss: 0.44912710785865784  (0.44312349232760345)
     | > postnet_loss: 0.30448129773139954  (0.30543927374211216)
     | > stopnet_loss: 0.002652578754350543  (0.004999115735038437)
     | > loss: 0.19105468690395355  (0.19213980673389)
     | > align_error: 0.5507550835609436  (0.5791555148634044)

   --> STEP: 45
     | > decoder_loss: 0.44214150309562683  (0.44310167034467063)
     | > postnet_loss: 0.30348774790763855  (0.30539590650134607)
     | > stopnet_loss: 0.003301918273791671  (0.0049614002358996205)
     | > loss: 0.18970923125743866  (0.19208579394552444)
     | > align_error: 0.5525451302528381  (0.5785641729831696)

   --> STEP: 46
     | > decoder_loss: 0.43244510889053345  (0.44287000596523285)
     | > postnet_loss: 0.29488909244537354  (0.3051674975001293)
     | > stopnet_loss: 0.00319548393599689  (0.004923010751119126)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3700250820680098 (-0.015259843884092406)
     | > avg_decoder_loss: 0.4390376449534387 (-0.0008149702440608531)
     | > avg_postnet_loss: 0.3023509992794556 (+0.00013173619906098333)
     | > avg_stopnet_loss: 0.0043635487408292565 (-1.2716782900196351e-05)
     | > avg_loss: 0.18971070918169888 (-0.0001835260878909617)
     | > avg_align_error: 0.5715153628226483 (+0.0006577964081910803)


 > EPOCH: 127/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 15:43:06)

   --> TIME: 2025-12-28 15:43:42 -- STEP: 23/150 -- GLOBAL_STEP: 19200
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4781738817691803  (0.46858206391334534)
     | > postnet_loss: 0.4019024074077606  (0.3966511669366256)
     | > stopnet_loss: 0.006609216798096895  (0.009925981781081013)
     | > loss: 0.22662828862667084  (0.2262342896150506)
     | > align_error: 0.6374799013137817  (0.6711602534936822)
     | > grad_norm: tensor(0.3900, device='cuda:0')  (tensor(0.2884, device='cuda:0'))
     | > step_time: 0.8577  (0.6519793634829314)
     | > loader_time: 1.1216  (0.8858699280282726)


   --> TIME: 2025-12-28 15:44:37 -- STEP: 48/150 -- GLOBAL_STEP: 19225
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48094409704208374  (0.4761850566913684)
     | > postnet_loss: 0.3972912132740021  (0.3991195385654767)
     | > stopnet_loss: 0.004538124427199364  (0.0076231384203614035)
     | > loss: 0.22409695386886597  (0.2264492871860663)
     | > align_error: 0.6234122216701508  (0.6492126192897558)
     | > grad_norm: tensor(0.2573, device='cuda:0')  (tensor(0.2825, device='cuda:0'))
     | > step_time: 1.2028  (0.8956546435753504)
     | > loader_time: 1.0616  (0.9781300773223242)


   --> TIME: 2025-12-28 15:45:46 -- STEP: 73/150 -- GLOBAL_STEP: 19250
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4840564727783203  (0.4792186360653133)
     | > postnet_loss: 0.39598268270492554  (0.3988948407238477)
     | > stopnet_loss: 0.0039024234283715487  (0.006457725003974077)
     | > loss: 0.22391220927238464  (0.22598609348682508)
     | > align_error: 0.648117184638977  (0.6366515424970078)
     | > grad_norm: tensor(0.3530, device='cuda:0')  (tensor(0.2641, device='cuda:0'))
     | > step_time: 1.5117  (1.0803531751240767)
     | > loader_time: 1.2857  (1.091184047803487)


   --> TIME: 2025-12-28 15:47:06 -- STEP: 98/150 -- GLOBAL_STEP: 19275
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49279162287712097  (0.4804092274636638)
     | > postnet_loss: 0.40217825770378113  (0.398126484788194)
     | > stopnet_loss: 0.003888874314725399  (0.005770102271582095)
     | > loss: 0.2276313453912735  (0.22540402990214678)
     | > align_error: 0.6078567504882812  (0.6315374651125498)
     | > grad_norm: tensor(0.1504, device='cuda:0')  (tensor(0.2424, device='cuda:0'))
     | > step_time: 1.7546  (1.2351419852704417)
     | > loader_time: 1.5066  (1.198603148363075)


   --> TIME: 2025-12-28 15:48:34 -- STEP: 123/150 -- GLOBAL_STEP: 19300
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.481710284948349  (0.48158819815976833)
     | > postnet_loss: 0.3925073444843292  (0.3976987152080226)
     | > stopnet_loss: 0.0033029515761882067  (0.005277779159643422)
     | > loss: 0.22185735404491425  (0.22509950702267933)
     | > align_error: 0.6027660369873047  (0.6272525084697133)
     | > grad_norm: tensor(0.2227, device='cuda:0')  (tensor(0.2355, device='cuda:0'))
     | > step_time: 1.9552  (1.3668521962514737)
     | > loader_time: 1.7653  (1.2892671542439038)


   --> TIME: 2025-12-28 15:50:19 -- STEP: 148/150 -- GLOBAL_STEP: 19325
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5018835067749023  (0.48308824445750265)
     | > postnet_loss: 0.40458306670188904  (0.3976156083313194)
     | > stopnet_loss: 0.0027073530945926905  (0.004903778380311622)
     | > loss: 0.22932399809360504  (0.2250797409262206)
     | > align_error: 0.6129252910614014  (0.62389110350931)
     | > grad_norm: tensor(0.3372, device='cuda:0')  (tensor(0.2274, device='cuda:0'))
     | > step_time: 2.5745  (1.506662186738607)
     | > loader_time: 2.2474  (1.4117334468944653)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4611961841583252  (0.4611961841583252)
     | > postnet_loss: 0.3323032855987549  (0.3323032855987549)
     | > stopnet_loss: 0.012217726558446884  (0.012217726558446884)
     | > loss: 0.2105925977230072  (0.2105925977230072)
     | > align_error: 0.718795657157898  (0.718795657157898)

   --> STEP: 1
     | > decoder_loss: 0.4418545961380005  (0.4418545961380005)
     | > postnet_loss: 0.3189391791820526  (0.3189391791820526)
     | > stopnet_loss: 0.009654606692492962  (0.009654606692492962)
     | > loss: 0.1998530626296997  (0.1998530626296997)
     | > align_error: 0.6593964099884033  (0.6593964099884033)

   --> STEP: 2
     | > decoder_loss: 0.43640708923339844  (0.43913084268569946)
     | > postnet_loss: 0.3109329044818878  (0.3149360418319702)
     | > stopnet_loss: 0.011112401261925697  (0.01038350397720933)
     | > loss: 0.1979473978281021  (0.1989002302289009)
     | > align_error: 0.6554665267467499  (0.6574314683675766)

   --> STEP: 3
     | > decoder_loss: 0.4405394494533539  (0.4396003782749176)
     | > postnet_loss: 0.309704065322876  (0.31319204966227215)
     | > stopnet_loss: 0.008272027596831322  (0.009679678517083326)
     | > loss: 0.19583290815353394  (0.1978777895371119)
     | > align_error: 0.7340285778045654  (0.6829638381799062)

   --> STEP: 4
     | > decoder_loss: 0.4464587867259979  (0.4413149803876877)
     | > postnet_loss: 0.31812241673469543  (0.31442464143037796)
     | > stopnet_loss: 0.008139470592141151  (0.009294626535847783)
     | > loss: 0.19928477704524994  (0.19822953641414642)
     | > align_error: 0.6032262444496155  (0.6630294397473335)

   --> STEP: 5
     | > decoder_loss: 0.42808887362480164  (0.43866975903511046)
     | > postnet_loss: 0.30094873905181885  (0.31172946095466614)
     | > stopnet_loss: 0.008135329000651836  (0.009062767028808594)
     | > loss: 0.19039474427700043  (0.1966625779867172)
     | > align_error: 0.6415732800960541  (0.6587382078170776)

   --> STEP: 6
     | > decoder_loss: 0.4460122883319855  (0.439893513917923)
     | > postnet_loss: 0.31324735283851624  (0.3119824429353078)
     | > stopnet_loss: 0.007256567478179932  (0.008761733770370483)
     | > loss: 0.19707147777080536  (0.1967307279507319)
     | > align_error: 0.5934223830699921  (0.6478522370258967)

   --> STEP: 7
     | > decoder_loss: 0.4573490619659424  (0.4423871636390686)
     | > postnet_loss: 0.3134970963001251  (0.3121988219874246)
     | > stopnet_loss: 0.006256806664168835  (0.008403887040913105)
     | > loss: 0.1989683359861374  (0.19705038624150412)
     | > align_error: 0.5786875188350677  (0.6379715629986354)

   --> STEP: 8
     | > decoder_loss: 0.4534338414669037  (0.443767998367548)
     | > postnet_loss: 0.31471601128578186  (0.31251347064971924)
     | > stopnet_loss: 0.0072114672511816025  (0.008254834567196667)
     | > loss: 0.19924892485141754  (0.1973252035677433)
     | > align_error: 0.5745842456817627  (0.6300481483340263)

   --> STEP: 9
     | > decoder_loss: 0.44769707322120667  (0.44420456224017674)
     | > postnet_loss: 0.3129480183124542  (0.3125617537233565)
     | > stopnet_loss: 0.006704250816255808  (0.008082547483758794)
     | > loss: 0.1968655288219452  (0.19727412859598795)
     | > align_error: 0.5906575322151184  (0.6256714132097032)

   --> STEP: 10
     | > decoder_loss: 0.4737020432949066  (0.44715431034564973)
     | > postnet_loss: 0.3269674777984619  (0.314002326130867)
     | > stopnet_loss: 0.005619700066745281  (0.007836262742057443)
     | > loss: 0.20578709244728088  (0.19812542498111724)
     | > align_error: 0.5833233594894409  (0.621436607837677)

   --> STEP: 11
     | > decoder_loss: 0.460653692483902  (0.44838152690367267)
     | > postnet_loss: 0.31796029210090637  (0.3143621412190524)
     | > stopnet_loss: 0.005910767707973719  (0.007661217738958922)
     | > loss: 0.20056426525115967  (0.1983471377329393)
     | > align_error: 0.5946177244186401  (0.6189985275268555)

   --> STEP: 12
     | > decoder_loss: 0.4560825228691101  (0.4490232765674591)
     | > postnet_loss: 0.3108857572078705  (0.31407244255145395)
     | > stopnet_loss: 0.00788069050759077  (0.00767950713634491)
     | > loss: 0.1996227502822876  (0.19845343877871832)
     | > align_error: 0.5869781970977783  (0.6163301666577657)

   --> STEP: 13
     | > decoder_loss: 0.44642373919487  (0.44882331215418303)
     | > postnet_loss: 0.3111704885959625  (0.3138492153241084)
     | > stopnet_loss: 0.0055644032545387745  (0.007516806837744438)
     | > loss: 0.19496296346187592  (0.19818494067742273)
     | > align_error: 0.5856930613517761  (0.6139734662496127)

   --> STEP: 14
     | > decoder_loss: 0.4554123878479004  (0.44929396041802)
     | > postnet_loss: 0.3130190968513489  (0.3137899211474827)
     | > stopnet_loss: 0.004913102835416794  (0.00733082798043532)
     | > loss: 0.1970209777355194  (0.1981018004672868)
     | > align_error: 0.5544074773788452  (0.6097187527588436)

   --> STEP: 15
     | > decoder_loss: 0.4557707607746124  (0.4497257471084595)
     | > postnet_loss: 0.3151477575302124  (0.31388044357299805)
     | > stopnet_loss: 0.004988131579011679  (0.0071746482203404105)
     | > loss: 0.19771775603294373  (0.19807619750499725)
     | > align_error: 0.5882742702960968  (0.6082891205946604)

   --> STEP: 16
     | > decoder_loss: 0.45649534463882446  (0.4501488469541073)
     | > postnet_loss: 0.30905482172966003  (0.3135788422077894)
     | > stopnet_loss: 0.00526842987164855  (0.0070555095735471696)
     | > loss: 0.19665595889091492  (0.1979874325916171)
     | > align_error: 0.6059967875480652  (0.6081458497792482)

   --> STEP: 17
     | > decoder_loss: 0.46194466948509216  (0.4508427188676946)
     | > postnet_loss: 0.31701719760894775  (0.31378109840785756)
     | > stopnet_loss: 0.004841085989028215  (0.006925249362693113)
     | > loss: 0.1995815634727478  (0.1980812049963895)
     | > align_error: 0.5584801435470581  (0.6052243376479429)

   --> STEP: 18
     | > decoder_loss: 0.45704302191734314  (0.45118718014823067)
     | > postnet_loss: 0.30964604020118713  (0.3135513729519314)
     | > stopnet_loss: 0.005267976783216  (0.006833178663833274)
     | > loss: 0.19694024324417114  (0.19801781823237738)
     | > align_error: 0.6040606498718262  (0.6051596883270476)

   --> STEP: 19
     | > decoder_loss: 0.45317190885543823  (0.45129163955387314)
     | > postnet_loss: 0.30806204676628113  (0.3132624610474235)
     | > stopnet_loss: 0.004703910555690527  (0.006721111921299445)
     | > loss: 0.1950123906135559  (0.19785963783138677)
     | > align_error: 0.5995747745037079  (0.6048657454942402)

   --> STEP: 20
     | > decoder_loss: 0.45171305537223816  (0.4513127103447914)
     | > postnet_loss: 0.30631622672080994  (0.3129151493310928)
     | > stopnet_loss: 0.004522652365267277  (0.006611188943497837)
     | > loss: 0.19402997195720673  (0.19766815453767778)
     | > align_error: 0.6230282783508301  (0.6057738721370697)

   --> STEP: 21
     | > decoder_loss: 0.4486820101737976  (0.45118743890807744)
     | > postnet_loss: 0.3042789101600647  (0.31250389984675814)
     | > stopnet_loss: 0.003977970220148563  (0.0064857975757193)
     | > loss: 0.19221819937229156  (0.19740863286313556)
     | > align_error: 0.5602827072143555  (0.603607626188369)

   --> STEP: 22
     | > decoder_loss: 0.4514051377773285  (0.4511973343112252)
     | > postnet_loss: 0.30808597803115845  (0.3123030852187763)
     | > stopnet_loss: 0.004901893902570009  (0.006413801954212514)
     | > loss: 0.19477467238903046  (0.19728890738703989)
     | > align_error: 0.6256974637508392  (0.6046117097139359)

   --> STEP: 23
     | > decoder_loss: 0.4241403341293335  (0.45002094299896905)
     | > postnet_loss: 0.29543450474739075  (0.3115696686765422)
     | > stopnet_loss: 0.004508234094828367  (0.006330951177717551)
     | > loss: 0.18440192937850952  (0.19672860399536465)
     | > align_error: 0.5676177442073822  (0.6030032764310422)

   --> STEP: 24
     | > decoder_loss: 0.4586268365383148  (0.45037952189644176)
     | > postnet_loss: 0.31170573830604553  (0.3115753382444381)
     | > stopnet_loss: 0.004404976032674313  (0.006250702213340749)
     | > loss: 0.19698812067508698  (0.19673941719035307)
     | > align_error: 0.5798159837722778  (0.602037139236927)

   --> STEP: 25
     | > decoder_loss: 0.45802026987075806  (0.4506851518154144)
     | > postnet_loss: 0.30870282649993896  (0.31146043777465815)
     | > stopnet_loss: 0.003716067411005497  (0.006149316821247339)
     | > loss: 0.19539684057235718  (0.19668571412563324)
     | > align_error: 0.5583572089672089  (0.6002899420261383)

   --> STEP: 26
     | > decoder_loss: 0.43282124400138855  (0.4499980784379519)
     | > postnet_loss: 0.2970735728740692  (0.3109070968169432)
     | > stopnet_loss: 0.004372455645352602  (0.006080976006789849)
     | > loss: 0.18684616684913635  (0.19630726999961412)
     | > align_error: 0.5471883118152618  (0.5982475716334122)

   --> STEP: 27
     | > decoder_loss: 0.42872992157936096  (0.44921036892467076)
     | > postnet_loss: 0.29201045632362366  (0.3102072212431165)
     | > stopnet_loss: 0.0036508096382021904  (0.0059909698449903065)
     | > loss: 0.18383590877056122  (0.19584536773187142)
     | > align_error: 0.5403984189033508  (0.5961050104211878)

   --> STEP: 28
     | > decoder_loss: 0.43522217869758606  (0.4487107907022749)
     | > postnet_loss: 0.29684075713157654  (0.3097298475248472)
     | > stopnet_loss: 0.003946560900658369  (0.005917955239835594)
     | > loss: 0.18696229159832  (0.19552811501281603)
     | > align_error: 0.5664978623390198  (0.595047612275396)

   --> STEP: 29
     | > decoder_loss: 0.4303904175758362  (0.4480790536979149)
     | > postnet_loss: 0.2932731807231903  (0.3091623762558246)
     | > stopnet_loss: 0.0035889737773686647  (0.005837645534233287)
     | > loss: 0.18450486660003662  (0.19514800299858226)
     | > align_error: 0.5408266186714172  (0.5931779228407761)

   --> STEP: 30
     | > decoder_loss: 0.4310189187526703  (0.4475103825330734)
     | > postnet_loss: 0.29406580328941345  (0.3086591571569442)
     | > stopnet_loss: 0.0028353810776025057  (0.005737570052345594)
     | > loss: 0.18410655856132507  (0.19477995485067368)
     | > align_error: 0.5336468815803528  (0.591193554798762)

   --> STEP: 31
     | > decoder_loss: 0.42691493034362793  (0.44684601310760746)
     | > postnet_loss: 0.2930014133453369  (0.3081540686468924)
     | > stopnet_loss: 0.00370784942060709  (0.005672095193257255)
     | > loss: 0.18368694186210632  (0.1944221157220102)
     | > align_error: 0.555840015411377  (0.5900531180443302)

   --> STEP: 32
     | > decoder_loss: 0.4388203024864197  (0.4465952096506953)
     | > postnet_loss: 0.29885193705558777  (0.3078633770346641)
     | > stopnet_loss: 0.0038512195460498333  (0.005615192829282023)
     | > loss: 0.18826927244663239  (0.19422983936965466)
     | > align_error: 0.5312305688858032  (0.5882149133831263)

   --> STEP: 33
     | > decoder_loss: 0.43601182103157043  (0.44627450090466125)
     | > postnet_loss: 0.2969963848590851  (0.3075340742414647)
     | > stopnet_loss: 0.004017059225589037  (0.0055667645382610235)
     | > loss: 0.18726910650730133  (0.19401890807079547)
     | > align_error: 0.546301543712616  (0.5869448112718987)

   --> STEP: 34
     | > decoder_loss: 0.4420844316482544  (0.4461512635735905)
     | > postnet_loss: 0.2987368404865265  (0.30727533207220187)
     | > stopnet_loss: 0.003302141325548291  (0.005500157973181237)
     | > loss: 0.18850745260715485  (0.19385680643951192)
     | > align_error: 0.5639376044273376  (0.5862681287176469)

   --> STEP: 35
     | > decoder_loss: 0.43895086646080017  (0.4459455379417964)
     | > postnet_loss: 0.2972698509693146  (0.3069894611835479)
     | > stopnet_loss: 0.003512656781822443  (0.0054433722248567)
     | > loss: 0.1875678300857544  (0.19367712140083312)
     | > align_error: 0.5335026979446411  (0.5847605449812753)

   --> STEP: 36
     | > decoder_loss: 0.44495657086372375  (0.4459180666340722)
     | > postnet_loss: 0.30195191502571106  (0.3068495293458302)
     | > stopnet_loss: 0.0036656286101788282  (0.005393990457782315)
     | > loss: 0.19039274752140045  (0.19358588879307112)
     | > align_error: 0.6339874267578125  (0.5861279583639569)

   --> STEP: 37
     | > decoder_loss: 0.4378114938735962  (0.44569897007297826)
     | > postnet_loss: 0.29838263988494873  (0.3066206944955361)
     | > stopnet_loss: 0.003555289702489972  (0.005344295842774413)
     | > loss: 0.18760381639003754  (0.1934242111605567)
     | > align_error: 0.5192019939422607  (0.5843191485147219)

   --> STEP: 38
     | > decoder_loss: 0.4248897135257721  (0.4451513580585781)
     | > postnet_loss: 0.29108965396881104  (0.30621198290272755)
     | > stopnet_loss: 0.0031465841457247734  (0.005286461324431002)
     | > loss: 0.18214142322540283  (0.19312729568857895)
     | > align_error: 0.5518264174461365  (0.583464076644496)

   --> STEP: 39
     | > decoder_loss: 0.44022664427757263  (0.44502508334624463)
     | > postnet_loss: 0.3014081120491028  (0.30608880672699357)
     | > stopnet_loss: 0.0034818374551832676  (0.005240188917527214)
     | > loss: 0.1888905167579651  (0.19301866033138373)
     | > align_error: 0.5460081398487091  (0.5825036680087065)

   --> STEP: 40
     | > decoder_loss: 0.4376082420349121  (0.4448396623134613)
     | > postnet_loss: 0.3000379502773285  (0.30593753531575196)
     | > stopnet_loss: 0.003036932786926627  (0.005185107514262199)
     | > loss: 0.18744848668575287  (0.19287940599024295)
     | > align_error: 0.5840768218040466  (0.5825429968535899)

   --> STEP: 41
     | > decoder_loss: 0.4278131127357483  (0.4444243806164439)
     | > postnet_loss: 0.291917622089386  (0.30559558621266986)
     | > stopnet_loss: 0.00371969654224813  (0.005149365783237466)
     | > loss: 0.1836523860692978  (0.19265435672387843)
     | > align_error: 0.5031493902206421  (0.580606567423518)

   --> STEP: 42
     | > decoder_loss: 0.4321143925189972  (0.4441312856617428)
     | > postnet_loss: 0.2940647006034851  (0.30532104131721305)
     | > stopnet_loss: 0.0032903621904551983  (0.005105103792933126)
     | > loss: 0.18483513593673706  (0.1924681848003751)
     | > align_error: 0.5797734260559082  (0.5805867307242892)

   --> STEP: 43
     | > decoder_loss: 0.43217143416404724  (0.44385314958040106)
     | > postnet_loss: 0.2936914563179016  (0.3050505858521128)
     | > stopnet_loss: 0.002946177963167429  (0.005054896215496715)
     | > loss: 0.1844118982553482  (0.19228082929932794)
     | > align_error: 0.5519935786724091  (0.5799217736998269)

   --> STEP: 44
     | > decoder_loss: 0.44974133372306824  (0.4439869719472798)
     | > postnet_loss: 0.3038262724876404  (0.3050227605483748)
     | > stopnet_loss: 0.0026659935247153044  (0.00500060297252441)
     | > loss: 0.19105789065361023  (0.19225303523919798)
     | > align_error: 0.5510926246643066  (0.5792665657672015)

   --> STEP: 45
     | > decoder_loss: 0.4426092207431793  (0.4439563552538554)
     | > postnet_loss: 0.30293208360671997  (0.30497630106078244)
     | > stopnet_loss: 0.0032888157293200493  (0.004962563256008757)
     | > loss: 0.18967415392398834  (0.19219572676552665)
     | > align_error: 0.5528378486633301  (0.5786792609426711)

   --> STEP: 46
     | > decoder_loss: 0.4334423542022705  (0.4437277900136035)
     | > postnet_loss: 0.2944062352180481  (0.30474651702072303)
     | > stopnet_loss: 0.0032042465172708035  (0.004924338979079672)
     | > loss: 0.1851663887500763  (0.1920429150695386)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.38296918435530225 (+0.012944102287292425)
     | > avg_decoder_loss: 0.43979119351415924 (+0.0007535485607205183)
     | > avg_postnet_loss: 0.30167683281681756 (-0.000674166462638015)
     | > avg_stopnet_loss: 0.004366159029869419 (+2.6102890401625764e-06)
     | > avg_loss: 0.1897331659089435 (+2.245672724462966e-05)
     | > avg_align_error: 0.5716199716835311 (+0.00010460886088281551)


 > EPOCH: 128/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 15:52:29)

   --> TIME: 2025-12-28 15:53:03 -- STEP: 22/150 -- GLOBAL_STEP: 19350
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4780047535896301  (0.46880596334284)
     | > postnet_loss: 0.40143170952796936  (0.3965921970930966)
     | > stopnet_loss: 0.006337988190352917  (0.010043134764683518)
     | > loss: 0.22619710862636566  (0.22639267688447778)
     | > align_error: 0.6332005858421326  (0.6737115545706315)
     | > grad_norm: tensor(0.2110, device='cuda:0')  (tensor(0.2482, device='cuda:0'))
     | > step_time: 0.8861  (0.6465405550870028)
     | > loader_time: 0.8497  (0.8352584080262617)


   --> TIME: 2025-12-28 15:53:55 -- STEP: 47/150 -- GLOBAL_STEP: 19375
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4830871820449829  (0.47610119365631265)
     | > postnet_loss: 0.399088591337204  (0.3990676377681976)
     | > stopnet_loss: 0.004322089720517397  (0.007691507931164606)
     | > loss: 0.22486604750156403  (0.22648371724372215)
     | > align_error: 0.6582960188388824  (0.6502887796848374)
     | > grad_norm: tensor(0.2920, device='cuda:0')  (tensor(0.2396, device='cuda:0'))
     | > step_time: 1.2538  (0.8748295510068853)
     | > loader_time: 1.0751  (0.9319086987921532)


   --> TIME: 2025-12-28 15:55:02 -- STEP: 72/150 -- GLOBAL_STEP: 19400
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48294445872306824  (0.4793647871249252)
     | > postnet_loss: 0.3956155776977539  (0.39902290205160784)
     | > stopnet_loss: 0.003874401329085231  (0.006503090139530186)
     | > loss: 0.22351442277431488  (0.22610001390179002)
     | > align_error: 0.5976452827453613  (0.6368612154490416)
     | > grad_norm: tensor(0.2600, device='cuda:0')  (tensor(0.2369, device='cuda:0'))
     | > step_time: 1.5176  (1.0649876594543457)
     | > loader_time: 1.3106  (1.0380466447936163)


   --> TIME: 2025-12-28 15:56:24 -- STEP: 97/150 -- GLOBAL_STEP: 19425
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4789509177207947  (0.4804471556058864)
     | > postnet_loss: 0.3924442231655121  (0.3981642320598525)
     | > stopnet_loss: 0.003372838720679283  (0.0057904791811807564)
     | > loss: 0.22122161090373993  (0.2254433266280853)
     | > align_error: 0.5773496925830841  (0.63212904149724)
     | > grad_norm: tensor(0.3000, device='cuda:0')  (tensor(0.2401, device='cuda:0'))
     | > step_time: 1.755  (1.2191210063462405)
     | > loader_time: 1.9201  (1.1882026613373111)


   --> TIME: 2025-12-28 15:57:57 -- STEP: 122/150 -- GLOBAL_STEP: 19450
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48281949758529663  (0.48166261442372055)
     | > postnet_loss: 0.3934226632118225  (0.39775858453062723)
     | > stopnet_loss: 0.0032865216489881277  (0.005301889738251195)
     | > loss: 0.22234706580638885  (0.22515718968676743)
     | > align_error: 0.5945278406143188  (0.6277638048422137)
     | > grad_norm: tensor(0.1807, device='cuda:0')  (tensor(0.2337, device='cuda:0'))
     | > step_time: 2.0533  (1.3534518030823255)
     | > loader_time: 1.7232  (1.3248696639889568)


   --> TIME: 2025-12-28 15:59:41 -- STEP: 147/150 -- GLOBAL_STEP: 19475
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49394917488098145  (0.4829319634405123)
     | > postnet_loss: 0.39824554324150085  (0.39747262365964003)
     | > stopnet_loss: 0.0026775943115353584  (0.004929609191255504)
     | > loss: 0.22572627663612366  (0.22503075591560934)
     | > align_error: 0.6277849078178406  (0.6242038447435208)
     | > grad_norm: tensor(0.1799, device='cuda:0')  (tensor(0.2222, device='cuda:0'))
     | > step_time: 2.5992  (1.5007133970455246)
     | > loader_time: 2.157  (1.4275728066762283)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4625256359577179  (0.4625256359577179)
     | > postnet_loss: 0.33434703946113586  (0.33434703946113586)
     | > stopnet_loss: 0.012161459773778915  (0.012161459773778915)
     | > loss: 0.21137963235378265  (0.21137963235378265)
     | > align_error: 0.7193030714988708  (0.7193030714988708)

   --> STEP: 1
     | > decoder_loss: 0.44323572516441345  (0.44323572516441345)
     | > postnet_loss: 0.32152101397514343  (0.32152101397514343)
     | > stopnet_loss: 0.009613980539143085  (0.009613980539143085)
     | > loss: 0.20080316066741943  (0.20080316066741943)
     | > align_error: 0.6599295139312744  (0.6599295139312744)

   --> STEP: 2
     | > decoder_loss: 0.4383251667022705  (0.440780445933342)
     | > postnet_loss: 0.31228625774383545  (0.31690363585948944)
     | > stopnet_loss: 0.011144384741783142  (0.010379182640463114)
     | > loss: 0.19879724085330963  (0.19980020076036453)
     | > align_error: 0.6560246646404266  (0.6579770892858505)

   --> STEP: 3
     | > decoder_loss: 0.4435749053955078  (0.4417119324207306)
     | > postnet_loss: 0.3123519718647003  (0.31538641452789307)
     | > stopnet_loss: 0.008319295942783356  (0.009692553741236528)
     | > loss: 0.1973010003566742  (0.19896713395913443)
     | > align_error: 0.7352864742279053  (0.6837468842665354)

   --> STEP: 4
     | > decoder_loss: 0.4475589394569397  (0.44317368417978287)
     | > postnet_loss: 0.31978216767311096  (0.31648535281419754)
     | > stopnet_loss: 0.008134330622851849  (0.009302997961640358)
     | > loss: 0.19996961951255798  (0.1992177553474903)
     | > align_error: 0.603693813085556  (0.6637336164712906)

   --> STEP: 5
     | > decoder_loss: 0.4285719394683838  (0.44025333523750304)
     | > postnet_loss: 0.3019505739212036  (0.31357839703559875)
     | > stopnet_loss: 0.008099785074591637  (0.009062355384230614)
     | > loss: 0.19073040783405304  (0.19752028584480286)
     | > align_error: 0.6421334743499756  (0.6594135880470275)

   --> STEP: 6
     | > decoder_loss: 0.4466054439544678  (0.4413120200236638)
     | > postnet_loss: 0.3144817650318146  (0.3137289583683014)
     | > stopnet_loss: 0.007258588448166847  (0.00876172756155332)
     | > loss: 0.19753038883209229  (0.19752196967601776)
     | > align_error: 0.5942007601261139  (0.6485447833935419)

   --> STEP: 7
     | > decoder_loss: 0.4577857255935669  (0.44366540653365)
     | > postnet_loss: 0.314235121011734  (0.3138012673173632)
     | > stopnet_loss: 0.006227710749953985  (0.008399725159896272)
     | > loss: 0.19923292100429535  (0.19776639129434312)
     | > align_error: 0.5793028473854065  (0.6386530782495227)

   --> STEP: 8
     | > decoder_loss: 0.45179274678230286  (0.4446813240647316)
     | > postnet_loss: 0.31433823704719543  (0.3138683885335922)
     | > stopnet_loss: 0.007525889668613672  (0.008290495723485947)
     | > loss: 0.1990586370229721  (0.19792792201042175)
     | > align_error: 0.5757569670677185  (0.6307910643517971)

   --> STEP: 9
     | > decoder_loss: 0.4498977065086365  (0.4452609221140544)
     | > postnet_loss: 0.31449753046035767  (0.31393829319212174)
     | > stopnet_loss: 0.006713585928082466  (0.008115283523996672)
     | > loss: 0.19781239330768585  (0.19791508548789555)
     | > align_error: 0.5914526879787445  (0.6264201336436801)

   --> STEP: 10
     | > decoder_loss: 0.47369256615638733  (0.44810408651828765)
     | > postnet_loss: 0.3277856111526489  (0.31532302498817444)
     | > stopnet_loss: 0.005578925367444754  (0.007861647708341479)
     | > loss: 0.20594845712184906  (0.1987184226512909)
     | > align_error: 0.5836872458457947  (0.6221468448638916)

   --> STEP: 11
     | > decoder_loss: 0.4607996642589569  (0.44925822994925757)
     | > postnet_loss: 0.3179473578929901  (0.31556160070679407)
     | > stopnet_loss: 0.005895582027733326  (0.007682914464649829)
     | > loss: 0.2005823403596878  (0.1988878697156906)
     | > align_error: 0.5951099991798401  (0.6196889498017051)

   --> STEP: 12
     | > decoder_loss: 0.4570833742618561  (0.4499103253086408)
     | > postnet_loss: 0.3117908537387848  (0.3152473717927933)
     | > stopnet_loss: 0.007907264865934849  (0.007701610331423581)
     | > loss: 0.2001258283853531  (0.19899103293816248)
     | > align_error: 0.5879424214363098  (0.6170434057712555)

   --> STEP: 13
     | > decoder_loss: 0.4463004767894745  (0.4496326446533203)
     | > postnet_loss: 0.311326801776886  (0.3149457894838773)
     | > stopnet_loss: 0.005575864110141993  (0.007538091391324997)
     | > loss: 0.19498267769813538  (0.19868269791969886)
     | > align_error: 0.586037278175354  (0.6146583190331092)

   --> STEP: 14
     | > decoder_loss: 0.45636844635009766  (0.45011377334594727)
     | > postnet_loss: 0.3139285743236542  (0.3148731312581471)
     | > stopnet_loss: 0.00490453140810132  (0.007349979963951877)
     | > loss: 0.19747880101203918  (0.19859670528343745)
     | > align_error: 0.5554675757884979  (0.6104304088013512)

   --> STEP: 15
     | > decoder_loss: 0.45474910736083984  (0.45042279561360676)
     | > postnet_loss: 0.3140689730644226  (0.3148195207118988)
     | > stopnet_loss: 0.0049832481890916824  (0.007192197845627865)
     | > loss: 0.19718776643276215  (0.19850277602672578)
     | > align_error: 0.588724672794342  (0.6089833597342174)

   --> STEP: 16
     | > decoder_loss: 0.4548605978488922  (0.4507001582533121)
     | > postnet_loss: 0.30777499079704285  (0.3143792375922203)
     | > stopnet_loss: 0.005263540893793106  (0.007071656786138192)
     | > loss: 0.19592243432998657  (0.19834150467067957)
     | > align_error: 0.6063889861106873  (0.6088212113827467)

   --> STEP: 17
     | > decoder_loss: 0.4632802903652191  (0.45144016602460074)
     | > postnet_loss: 0.31738683581352234  (0.31455615513464985)
     | > stopnet_loss: 0.004839081317186356  (0.006940328817376319)
     | > loss: 0.20000585913658142  (0.19843940787455616)
     | > align_error: 0.558880627155304  (0.605883529957603)

   --> STEP: 18
     | > decoder_loss: 0.4559544622898102  (0.45169096026155686)
     | > postnet_loss: 0.30873894691467285  (0.3142329769002067)
     | > stopnet_loss: 0.005253097508102655  (0.006846593744638894)
     | > loss: 0.19642643630504608  (0.1983275761206945)
     | > align_error: 0.6043590307235718  (0.6057988355557123)

   --> STEP: 19
     | > decoder_loss: 0.4548763334751129  (0.45185861148332296)
     | > postnet_loss: 0.3089512586593628  (0.3139549917296359)
     | > stopnet_loss: 0.004845976363867521  (0.006741298093019347)
     | > loss: 0.19580286741256714  (0.19819469671500356)
     | > align_error: 0.6008036136627197  (0.6055359291402918)

   --> STEP: 20
     | > decoder_loss: 0.4498440623283386  (0.4517578840255737)
     | > postnet_loss: 0.30455532670021057  (0.3134850084781647)
     | > stopnet_loss: 0.004512161016464233  (0.006629841239191592)
     | > loss: 0.19311201572418213  (0.1979405626654625)
     | > align_error: 0.6230577230453491  (0.6064120188355446)

   --> STEP: 21
     | > decoder_loss: 0.4474359452724457  (0.4515520774182819)
     | > postnet_loss: 0.3034880757331848  (0.31300896406173706)
     | > stopnet_loss: 0.003956309985369444  (0.006502530227104823)
     | > loss: 0.19168730080127716  (0.19764278829097748)
     | > align_error: 0.5605515837669373  (0.6042281885941824)

   --> STEP: 22
     | > decoder_loss: 0.45025724172592163  (0.4514932212504474)
     | > postnet_loss: 0.3069716989994049  (0.31273454292254016)
     | > stopnet_loss: 0.004870348144322634  (0.006428340132432905)
     | > loss: 0.19417759776115417  (0.19748527963053097)
     | > align_error: 0.6258408725261688  (0.6052105833183635)

   --> STEP: 23
     | > decoder_loss: 0.42339709401130676  (0.4502716505009195)
     | > postnet_loss: 0.294739693403244  (0.3119521581608316)
     | > stopnet_loss: 0.004504965618252754  (0.006344715153555508)
     | > loss: 0.1840391606092453  (0.19690066576004028)
     | > align_error: 0.5677300095558167  (0.6035809931547745)

   --> STEP: 24
     | > decoder_loss: 0.45664891600608826  (0.4505373698969682)
     | > postnet_loss: 0.30989643931388855  (0.31186650320887566)
     | > stopnet_loss: 0.004400834906846285  (0.006263720143275957)
     | > loss: 0.1960371732711792  (0.19686468690633774)
     | > align_error: 0.5800594091415405  (0.6026009271542231)

   --> STEP: 25
     | > decoder_loss: 0.4558699429035187  (0.45075067281723025)
     | > postnet_loss: 0.3070184290409088  (0.311672580242157)
     | > stopnet_loss: 0.0036979541182518005  (0.0061610895022749905)
     | > loss: 0.19442003965377808  (0.19676690101623534)
     | > align_error: 0.5578710436820984  (0.6008117318153381)

   --> STEP: 26
     | > decoder_loss: 0.43180397152900696  (0.45002195353691393)
     | > postnet_loss: 0.2962340712547302  (0.31107879143494827)
     | > stopnet_loss: 0.004378259647637606  (0.006092519123250475)
     | > loss: 0.1863877773284912  (0.1963677039513221)
     | > align_error: 0.5474376678466797  (0.5987588832011589)

   --> STEP: 27
     | > decoder_loss: 0.4284135401248932  (0.44922164192906133)
     | > postnet_loss: 0.29113537073135376  (0.31034014622370404)
     | > stopnet_loss: 0.003928414545953274  (0.006012367101869098)
     | > loss: 0.18381564319133759  (0.19590281281206343)
     | > align_error: 0.5413225889205933  (0.5966316130426195)

   --> STEP: 28
     | > decoder_loss: 0.43431398272514343  (0.4486892255289214)
     | > postnet_loss: 0.2957511246204376  (0.3098191097378731)
     | > stopnet_loss: 0.003929009661078453  (0.0059379614789837176)
     | > loss: 0.18644528090953827  (0.19556504381554468)
     | > align_error: 0.5666331648826599  (0.5955602398940495)

   --> STEP: 29
     | > decoder_loss: 0.4299948513507843  (0.44804459193657187)
     | > postnet_loss: 0.292723685503006  (0.30922961235046387)
     | > stopnet_loss: 0.0035805734805762768  (0.005856672237659323)
     | > loss: 0.18426020443439484  (0.19517522176791882)
     | > align_error: 0.5410387516021729  (0.59368018857364)

   --> STEP: 30
     | > decoder_loss: 0.4302908778190613  (0.44745280146598815)
     | > postnet_loss: 0.29321619868278503  (0.3086958318948746)
     | > stopnet_loss: 0.002830252517014742  (0.005755791580304504)
     | > loss: 0.18370701372623444  (0.19479294816652934)
     | > align_error: 0.5338394045829773  (0.5916854957739512)

   --> STEP: 31
     | > decoder_loss: 0.4247382879257202  (0.4467200752227537)
     | > postnet_loss: 0.2910582721233368  (0.3081268783538572)
     | > stopnet_loss: 0.0037058445159345865  (0.005689664255647409)
     | > loss: 0.1826549917459488  (0.19440140118522029)
     | > align_error: 0.555422842502594  (0.5905157327651978)

   --> STEP: 32
     | > decoder_loss: 0.43831247091293335  (0.4464573375880718)
     | > postnet_loss: 0.29813218116760254  (0.30781454406678677)
     | > stopnet_loss: 0.0038289204239845276  (0.005631516010907944)
     | > loss: 0.1879400908946991  (0.1941994852386415)
     | > align_error: 0.5313628911972046  (0.588667206466198)

   --> STEP: 33
     | > decoder_loss: 0.43398740887641907  (0.446079460960446)
     | > postnet_loss: 0.295030415058136  (0.3074271462180398)
     | > stopnet_loss: 0.004005915019661188  (0.005582255374809558)
     | > loss: 0.1862603724002838  (0.19395890606172156)
     | > align_error: 0.5463398098945618  (0.5873845580852393)

   --> STEP: 34
     | > decoder_loss: 0.439894437789917  (0.44589754851425395)
     | > postnet_loss: 0.29677414894104004  (0.30711382276871624)
     | > stopnet_loss: 0.0032958651427179575  (0.0055150086032774515)
     | > loss: 0.18746301531791687  (0.19376785045160966)
     | > align_error: 0.5638450384140015  (0.5866922192713794)

   --> STEP: 35
     | > decoder_loss: 0.43755537271499634  (0.44565920063427517)
     | > postnet_loss: 0.29607006907463074  (0.3067982869488852)
     | > stopnet_loss: 0.0035088134463876486  (0.005457688741652029)
     | > loss: 0.18691515922546387  (0.1935720592737198)
     | > align_error: 0.5332793593406677  (0.5851661375590733)

   --> STEP: 36
     | > decoder_loss: 0.443074107170105  (0.4455873924824927)
     | > postnet_loss: 0.30017226934432983  (0.3066142309043143)
     | > stopnet_loss: 0.0036545563489198685  (0.005407601730742803)
     | > loss: 0.18946614861488342  (0.19345800619986322)
     | > align_error: 0.6339972019195557  (0.5865225560135312)

   --> STEP: 37
     | > decoder_loss: 0.4365057647228241  (0.4453419430835827)
     | > postnet_loss: 0.29720115661621094  (0.3063598234911223)
     | > stopnet_loss: 0.0035556762013584375  (0.00535754968940809)
     | > loss: 0.1869824081659317  (0.19328299003678398)
     | > align_error: 0.5191312432289124  (0.5847011691815144)

   --> STEP: 38
     | > decoder_loss: 0.4241310954093933  (0.44478376288163035)
     | > postnet_loss: 0.28994056582450867  (0.3059277377630535)
     | > stopnet_loss: 0.00313787953928113  (0.005299137317036328)
     | > loss: 0.18165579438209534  (0.19297701120376587)
     | > align_error: 0.551647961139679  (0.5838313479172555)

   --> STEP: 39
     | > decoder_loss: 0.43930816650390625  (0.44464336297450924)
     | > postnet_loss: 0.3003828227519989  (0.3057855604550777)
     | > stopnet_loss: 0.00346978846937418  (0.005252230936327042)
     | > loss: 0.1883925497531891  (0.19285946091016135)
     | > align_error: 0.5460700392723083  (0.5828631092340517)

   --> STEP: 40
     | > decoder_loss: 0.4369170367717743  (0.44445020481944086)
     | > postnet_loss: 0.29905253648757935  (0.3056172348558902)
     | > stopnet_loss: 0.0030206169467419386  (0.005196440586587414)
     | > loss: 0.18701300024986267  (0.19271329939365386)
     | > align_error: 0.5840539336204529  (0.5828928798437117)

   --> STEP: 41
     | > decoder_loss: 0.4271913766860962  (0.4440292577917983)
     | > postnet_loss: 0.29116690158843994  (0.30526478770302556)
     | > stopnet_loss: 0.0037356698885560036  (0.005160812032976892)
     | > loss: 0.18332524597644806  (0.19248432248103908)
     | > align_error: 0.5034801661968231  (0.5809559843889096)

   --> STEP: 42
     | > decoder_loss: 0.43265488743782043  (0.4437584394500369)
     | > postnet_loss: 0.2936639189720154  (0.3049885765427634)
     | > stopnet_loss: 0.0032668644562363625  (0.005115718043054498)
     | > loss: 0.18484658002853394  (0.19230247147026516)
     | > align_error: 0.5796441733837128  (0.5809247507935478)

   --> STEP: 43
     | > decoder_loss: 0.4309796094894409  (0.44346125735793)
     | > postnet_loss: 0.2919837236404419  (0.3046861381031745)
     | > stopnet_loss: 0.0029399206396192312  (0.005065118103439725)
     | > loss: 0.18368075788021088  (0.19210196650305458)
     | > align_error: 0.5519399046897888  (0.5802506846050882)

   --> STEP: 44
     | > decoder_loss: 0.4493350684642792  (0.4435947530648925)
     | > postnet_loss: 0.3029949367046356  (0.3046477017077532)
     | > stopnet_loss: 0.0026582679711282253  (0.00501041696406901)
     | > loss: 0.19074076414108276  (0.19207103008573706)
     | > align_error: 0.5510845184326172  (0.5795878171920775)

   --> STEP: 45
     | > decoder_loss: 0.4416140913963318  (0.4435507383611467)
     | > postnet_loss: 0.30168837308883667  (0.30458193884955503)
     | > stopnet_loss: 0.003288067877292633  (0.004972142539918423)
     | > loss: 0.18911367654800415  (0.19200531111823188)
     | > align_error: 0.5526323020458221  (0.5789888057443829)

   --> STEP: 46
     | > decoder_loss: 0.43213266134262085  (0.4433025192955266)
     | > postnet_loss: 0.2930864691734314  (0.3043320373348567)
     | > stopnet_loss: 0.003203182714059949  (0.004933686891530196)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35601528485616046 (-0.026953899499141787)
     | > avg_decoder_loss: 0.4395087478738843 (-0.0002824456402749642)
     | > avg_postnet_loss: 0.3012156626491835 (-0.00046117016763408403)
     | > avg_stopnet_loss: 0.004373486905189401 (+7.327875319981976e-06)
     | > avg_loss: 0.18955458881277026 (-0.00017857709617324913)
     | > avg_align_error: 0.571828103426731 (+0.0002081317431998908)


 > EPOCH: 129/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 16:01:51)

   --> TIME: 2025-12-28 16:02:21 -- STEP: 21/150 -- GLOBAL_STEP: 19500
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4788796305656433  (0.4673192089512235)
     | > postnet_loss: 0.4014577865600586  (0.3958902784756252)
     | > stopnet_loss: 0.006955661810934544  (0.01032938291540458)
     | > loss: 0.22704002261161804  (0.22613175213336945)
     | > align_error: 0.6253683865070343  (0.675321136202131)
     | > grad_norm: tensor(0.2079, device='cuda:0')  (tensor(0.2733, device='cuda:0'))
     | > step_time: 0.7917  (0.6070425964537121)
     | > loader_time: 0.9523  (0.7924773806617373)


   --> TIME: 2025-12-28 16:03:14 -- STEP: 46/150 -- GLOBAL_STEP: 19525
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48883771896362305  (0.475294278367706)
     | > postnet_loss: 0.40335750579833984  (0.3986703539672105)
     | > stopnet_loss: 0.005068057682365179  (0.007822015332867917)
     | > loss: 0.22811686992645264  (0.2263131718272748)
     | > align_error: 0.6597529053688049  (0.6496762587972309)
     | > grad_norm: tensor(0.3900, device='cuda:0')  (tensor(0.2689, device='cuda:0'))
     | > step_time: 1.2332  (0.8622545003890991)
     | > loader_time: 1.0327  (0.9306555571763412)


   --> TIME: 2025-12-28 16:04:21 -- STEP: 71/150 -- GLOBAL_STEP: 19550
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48179134726524353  (0.47857436369842205)
     | > postnet_loss: 0.395214706659317  (0.3985282837505072)
     | > stopnet_loss: 0.0039703985676169395  (0.006572079415183881)
     | > loss: 0.22322191298007965  (0.22584774040840042)
     | > align_error: 0.6046301424503326  (0.6372693097087699)
     | > grad_norm: tensor(0.1885, device='cuda:0')  (tensor(0.2523, device='cuda:0'))
     | > step_time: 1.5353  (1.0548132171093578)
     | > loader_time: 1.3329  (1.0464386369141054)


   --> TIME: 2025-12-28 16:05:40 -- STEP: 96/150 -- GLOBAL_STEP: 19575
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.49023550748825073  (0.48005531417826813)
     | > postnet_loss: 0.4002533257007599  (0.39789545598129433)
     | > stopnet_loss: 0.0036712298169732094  (0.0058326067495121)
     | > loss: 0.2262934446334839  (0.22532029900078973)
     | > align_error: 0.6061422228813171  (0.6326531342541181)
     | > grad_norm: tensor(0.1384, device='cuda:0')  (tensor(0.2327, device='cuda:0'))
     | > step_time: 1.6411  (1.2111124744017918)
     | > loader_time: 1.5225  (1.1668257688482606)


   --> TIME: 2025-12-28 16:07:09 -- STEP: 121/150 -- GLOBAL_STEP: 19600
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48507165908813477  (0.4813555602199775)
     | > postnet_loss: 0.3943016529083252  (0.39754599899299875)
     | > stopnet_loss: 0.0030828998424112797  (0.00532550125744594)
     | > loss: 0.22292622923851013  (0.22505089123386982)
     | > align_error: 0.6499000191688538  (0.6279902795622174)
     | > grad_norm: tensor(0.1864, device='cuda:0')  (tensor(0.2194, device='cuda:0'))
     | > step_time: 2.0956  (1.3557780852987744)
     | > loader_time: 1.7437  (1.2645337089034157)


   --> TIME: 2025-12-28 16:08:56 -- STEP: 146/150 -- GLOBAL_STEP: 19625
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4960295557975769  (0.48253605912809505)
     | > postnet_loss: 0.39979591965675354  (0.39724136827743217)
     | > stopnet_loss: 0.0031103927176445723  (0.004944033750128767)
     | > loss: 0.227066770195961  (0.22488839097627222)
     | > align_error: 0.6248832046985626  (0.6240236561184062)
     | > grad_norm: tensor(0.1727, device='cuda:0')  (tensor(0.2100, device='cuda:0'))
     | > step_time: 2.958  (1.499536821286972)
     | > loader_time: 2.0726  (1.4002899699015163)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4608139097690582  (0.4608139097690582)
     | > postnet_loss: 0.33592525124549866  (0.33592525124549866)
     | > stopnet_loss: 0.012148689478635788  (0.012148689478635788)
     | > loss: 0.2113334834575653  (0.2113334834575653)
     | > align_error: 0.719120591878891  (0.719120591878891)

   --> STEP: 1
     | > decoder_loss: 0.44174230098724365  (0.44174230098724365)
     | > postnet_loss: 0.3238345980644226  (0.3238345980644226)
     | > stopnet_loss: 0.009604842402040958  (0.009604842402040958)
     | > loss: 0.20099906623363495  (0.20099906623363495)
     | > align_error: 0.6596652865409851  (0.6596652865409851)

   --> STEP: 2
     | > decoder_loss: 0.43717160820961  (0.4394569545984268)
     | > postnet_loss: 0.3135940432548523  (0.31871432065963745)
     | > stopnet_loss: 0.011133549734950066  (0.010369196068495512)
     | > loss: 0.19882497191429138  (0.19991201907396317)
     | > align_error: 0.6559270620346069  (0.657796174287796)

   --> STEP: 3
     | > decoder_loss: 0.44212543964385986  (0.44034644961357117)
     | > postnet_loss: 0.3143453001976013  (0.3172579805056254)
     | > stopnet_loss: 0.008282390423119068  (0.009673594186703363)
     | > loss: 0.1974000781774521  (0.19907470544179282)
     | > align_error: 0.7353062331676483  (0.6836328605810801)

   --> STEP: 4
     | > decoder_loss: 0.44679000973701477  (0.44195733964443207)
     | > postnet_loss: 0.32194897532463074  (0.31843072921037674)
     | > stopnet_loss: 0.00812199804931879  (0.00928569515235722)
     | > loss: 0.2003067433834076  (0.1993827149271965)
     | > align_error: 0.6036381721496582  (0.6636341884732246)

   --> STEP: 5
     | > decoder_loss: 0.4284970164299011  (0.4392652750015259)
     | > postnet_loss: 0.3041389286518097  (0.3155723690986633)
     | > stopnet_loss: 0.008150474168360233  (0.009058650955557824)
     | > loss: 0.19130946695804596  (0.19776806533336638)
     | > align_error: 0.6423570513725281  (0.6593787610530853)

   --> STEP: 6
     | > decoder_loss: 0.44527921080589294  (0.44026759763558704)
     | > postnet_loss: 0.31631895899772644  (0.3156968007485072)
     | > stopnet_loss: 0.007264725863933563  (0.008759663440287113)
     | > loss: 0.1976642608642578  (0.19775076458851495)
     | > align_error: 0.5938026905059814  (0.6484494159619013)

   --> STEP: 7
     | > decoder_loss: 0.4562223255634308  (0.4425468444824219)
     | > postnet_loss: 0.3153761625289917  (0.3156509952885764)
     | > stopnet_loss: 0.0062326998449862  (0.008398668640958411)
     | > loss: 0.1991323083639145  (0.1979481279850006)
     | > align_error: 0.5791086554527283  (0.6385435930320195)

   --> STEP: 8
     | > decoder_loss: 0.4513646364212036  (0.4436490684747696)
     | > postnet_loss: 0.316816508769989  (0.315796684473753)
     | > stopnet_loss: 0.007217227015644312  (0.008250988437794149)
     | > loss: 0.19926251471042633  (0.19811242632567883)
     | > align_error: 0.5751132369041443  (0.6306147985160351)

   --> STEP: 9
     | > decoder_loss: 0.4483473598957062  (0.44417110085487366)
     | > postnet_loss: 0.31573575735092163  (0.3157899147934384)
     | > stopnet_loss: 0.0066703991033136845  (0.008075367400629653)
     | > loss: 0.1976911872625351  (0.1980656219853295)
     | > align_error: 0.5914563536643982  (0.6262638601991866)

   --> STEP: 10
     | > decoder_loss: 0.47421059012413025  (0.44717504978179934)
     | > postnet_loss: 0.3308766186237335  (0.3172985851764679)
     | > stopnet_loss: 0.005521034821867943  (0.007819934142753482)
     | > loss: 0.20679283142089844  (0.1989383429288864)
     | > align_error: 0.5837452113628387  (0.6220119953155517)

   --> STEP: 11
     | > decoder_loss: 0.46017757058143616  (0.4483570971272208)
     | > postnet_loss: 0.31970247626304626  (0.3175171207297932)
     | > stopnet_loss: 0.0058976029977202415  (0.007645176765932279)
     | > loss: 0.20086760818958282  (0.19911373067985882)
     | > align_error: 0.595146656036377  (0.6195696917447177)

   --> STEP: 12
     | > decoder_loss: 0.45709630846977234  (0.44908536473910016)
     | > postnet_loss: 0.3139561116695404  (0.31722036997477215)
     | > stopnet_loss: 0.007920490577816963  (0.007668119583589335)
     | > loss: 0.20068359375  (0.1992445526023706)
     | > align_error: 0.5878922343254089  (0.616929903626442)

   --> STEP: 13
     | > decoder_loss: 0.44619515538215637  (0.44886304094241214)
     | > postnet_loss: 0.3135831654071808  (0.31694058500803435)
     | > stopnet_loss: 0.005559380631893873  (0.007505908894997377)
     | > loss: 0.19550396502017975  (0.1989568150960482)
     | > align_error: 0.5860329866409302  (0.6145532177044795)

   --> STEP: 14
     | > decoder_loss: 0.45559316873550415  (0.44934376435620443)
     | > postnet_loss: 0.3153432011604309  (0.31682648616177694)
     | > stopnet_loss: 0.004883524961769581  (0.007318595756909677)
     | > loss: 0.19761762022972107  (0.198861158319882)
     | > align_error: 0.5550741255283356  (0.6103047111204692)

   --> STEP: 15
     | > decoder_loss: 0.45511969923973083  (0.4497288266817729)
     | > postnet_loss: 0.31565263867378235  (0.3167482296625773)
     | > stopnet_loss: 0.004974788520485163  (0.007162341941148042)
     | > loss: 0.19766786694526672  (0.1987816055615743)
     | > align_error: 0.5885627567768097  (0.6088552474975586)

   --> STEP: 16
     | > decoder_loss: 0.45597273111343384  (0.4501190707087517)
     | > postnet_loss: 0.3099275529384613  (0.31632193736732006)
     | > stopnet_loss: 0.005239542573690414  (0.007042166980681941)
     | > loss: 0.1967146098613739  (0.19865241833031178)
     | > align_error: 0.6064444184303284  (0.6087045706808567)

   --> STEP: 17
     | > decoder_loss: 0.46312469244003296  (0.45088410728118)
     | > postnet_loss: 0.3186950981616974  (0.31646153506110697)
     | > stopnet_loss: 0.004828685894608498  (0.0069119622109129145)
     | > loss: 0.20028364658355713  (0.19874837293344386)
     | > align_error: 0.5588833689689636  (0.6057739117566276)

   --> STEP: 18
     | > decoder_loss: 0.4571406841278076  (0.4512316948837704)
     | > postnet_loss: 0.31090888381004333  (0.31615305443604785)
     | > stopnet_loss: 0.005257703363895416  (0.006820058941634165)
     | > loss: 0.19727009534835815  (0.1986662464009391)
     | > align_error: 0.6044082343578339  (0.6056980407900281)

   --> STEP: 19
     | > decoder_loss: 0.4547796845436096  (0.4514184311816567)
     | > postnet_loss: 0.3106420040130615  (0.31586299915062754)
     | > stopnet_loss: 0.004761926829814911  (0.006711736198906836)
     | > loss: 0.1961173415184021  (0.19853209351238452)
     | > align_error: 0.6006667912006378  (0.6054332381800601)

   --> STEP: 20
     | > decoder_loss: 0.45106351375579834  (0.45140068531036376)
     | > postnet_loss: 0.30660247802734375  (0.3153999730944633)
     | > stopnet_loss: 0.004512242041528225  (0.006601761491037905)
     | > loss: 0.19392873346805573  (0.19830192551016806)
     | > align_error: 0.6230663657188416  (0.6063148945569992)

   --> STEP: 21
     | > decoder_loss: 0.4486212134361267  (0.45126832950682866)
     | > postnet_loss: 0.30629125237464905  (0.3149662244887579)
     | > stopnet_loss: 0.003983544185757637  (0.00647708447650075)
     | > loss: 0.19271166622638702  (0.19803572268713088)
     | > align_error: 0.5605286359786987  (0.6041345965294611)

   --> STEP: 22
     | > decoder_loss: 0.4491027295589447  (0.4511698931455612)
     | > postnet_loss: 0.30811604857444763  (0.31465485285628925)
     | > stopnet_loss: 0.004628393333405256  (0.0063930530609054995)
     | > loss: 0.19393308460712433  (0.19784923913803967)
     | > align_error: 0.6253156065940857  (0.6050973697142168)

   --> STEP: 23
     | > decoder_loss: 0.4238540232181549  (0.44998224662697833)
     | > postnet_loss: 0.2966003715991974  (0.31386987541032874)
     | > stopnet_loss: 0.004485480021685362  (0.006310115102678537)
     | > loss: 0.18459907174110413  (0.1972731449033903)
     | > align_error: 0.5676552057266235  (0.6034694495408431)

   --> STEP: 24
     | > decoder_loss: 0.4582882225513458  (0.4503283289571603)
     | > postnet_loss: 0.3121505677700043  (0.3137982375919819)
     | > stopnet_loss: 0.004398714285343885  (0.00623047340195626)
     | > loss: 0.197008416056633  (0.1972621145347754)
     | > align_error: 0.5798894166946411  (0.6024869481722513)

   --> STEP: 25
     | > decoder_loss: 0.45699742436408997  (0.4505950927734375)
     | > postnet_loss: 0.3092299699783325  (0.3136155068874359)
     | > stopnet_loss: 0.0036890513729304075  (0.006128816520795226)
     | > loss: 0.1952458918094635  (0.19718146562576294)
     | > align_error: 0.5579192340373993  (0.6007042396068573)

   --> STEP: 26
     | > decoder_loss: 0.4327715337276459  (0.4499095712716763)
     | > postnet_loss: 0.2986522912979126  (0.31303999859553117)
     | > stopnet_loss: 0.004360101651400328  (0.006060789025818499)
     | > loss: 0.18721605837345123  (0.19679818073144326)
     | > align_error: 0.5472268164157867  (0.5986474156379699)

   --> STEP: 27
     | > decoder_loss: 0.4295484721660614  (0.44915545648998684)
     | > postnet_loss: 0.2932395339012146  (0.3123066480512972)
     | > stopnet_loss: 0.003911907784640789  (0.005981200831700806)
     | > loss: 0.18460890650749207  (0.19634672613055618)
     | > align_error: 0.5413888990879059  (0.5965267298398194)

   --> STEP: 28
     | > decoder_loss: 0.434777170419693  (0.44864194627319065)
     | > postnet_loss: 0.29773393273353577  (0.31178619393280577)
     | > stopnet_loss: 0.003923824988305569  (0.0059077231230081195)
     | > loss: 0.18705159425735474  (0.1960147571350847)
     | > align_error: 0.5667116641998291  (0.5954619060669625)

   --> STEP: 29
     | > decoder_loss: 0.4309302866458893  (0.4480311993894906)
     | > postnet_loss: 0.2953636348247528  (0.31121989879114875)
     | > stopnet_loss: 0.0035963275004178286  (0.00582801982567742)
     | > loss: 0.18516980111598969  (0.19564079313442626)
     | > align_error: 0.5408542454242706  (0.59357888328618)

   --> STEP: 30
     | > decoder_loss: 0.43112510442733765  (0.4474676628907522)
     | > postnet_loss: 0.2958059310913086  (0.3107060998678207)
     | > stopnet_loss: 0.0028330436907708645  (0.005728187287847201)
     | > loss: 0.18456579744815826  (0.19527162661155065)
     | > align_error: 0.5337406992912292  (0.591584277153015)

   --> STEP: 31
     | > decoder_loss: 0.4268587827682495  (0.4468028603061553)
     | > postnet_loss: 0.29372769594192505  (0.3101584094185983)
     | > stopnet_loss: 0.0037133684381842613  (0.005663193131406461)
     | > loss: 0.18385998904705048  (0.19490350927076033)
     | > align_error: 0.556149959564209  (0.5904412346501503)

   --> STEP: 32
     | > decoder_loss: 0.4385959208011627  (0.4465463934466243)
     | > postnet_loss: 0.2999567985534668  (0.30983960907906294)
     | > stopnet_loss: 0.003843757091090083  (0.005606335755146574)
     | > loss: 0.18848192691802979  (0.1947028348222375)
     | > align_error: 0.5315284729003906  (0.5886002108454703)

   --> STEP: 33
     | > decoder_loss: 0.43561509251594543  (0.4462151419032704)
     | > postnet_loss: 0.29748910665512085  (0.3094653514298526)
     | > stopnet_loss: 0.0040040286257863045  (0.005557780993650808)
     | > loss: 0.1872800886631012  (0.1944779031204455)
     | > align_error: 0.5463840961456299  (0.5873209346424448)

   --> STEP: 34
     | > decoder_loss: 0.4417383372783661  (0.4460834711790085)
     | > postnet_loss: 0.2991536259651184  (0.30916206538677216)
     | > stopnet_loss: 0.003294039284810424  (0.005491200355155503)
     | > loss: 0.1885170191526413  (0.19430258300374537)
     | > align_error: 0.563840240240097  (0.5866303259835522)

   --> STEP: 35
     | > decoder_loss: 0.4387354254722595  (0.4458735270159585)
     | > postnet_loss: 0.29849672317504883  (0.30885734132358006)
     | > stopnet_loss: 0.0034966885577887297  (0.005434214303802166)
     | > loss: 0.18780472874641418  (0.19411693002496447)
     | > align_error: 0.5333846211433411  (0.5851090201309748)

   --> STEP: 36
     | > decoder_loss: 0.4444914162158966  (0.4458351350492901)
     | > postnet_loss: 0.3025628924369812  (0.30868249552117455)
     | > stopnet_loss: 0.003671465441584587  (0.005385249057629456)
     | > loss: 0.19043505191802979  (0.19401465563310516)
     | > align_error: 0.6340476870536804  (0.5864684275454944)

   --> STEP: 37
     | > decoder_loss: 0.43749845027923584  (0.44560981924469406)
     | > postnet_loss: 0.2996349632740021  (0.3084379676226023)
     | > stopnet_loss: 0.003559013130143285  (0.0053358913298595595)
     | > loss: 0.18784235417842865  (0.19384783667487068)
     | > align_error: 0.5190084874629974  (0.5846451859216432)

   --> STEP: 38
     | > decoder_loss: 0.4249977171421051  (0.44506739550515223)
     | > postnet_loss: 0.2922101318836212  (0.3080109193136817)
     | > stopnet_loss: 0.003148391842842102  (0.005278325553885416)
     | > loss: 0.18245035409927368  (0.19354790292288127)
     | > align_error: 0.5515324771404266  (0.5837737988484533)

   --> STEP: 39
     | > decoder_loss: 0.44016844034194946  (0.44494178127019834)
     | > postnet_loss: 0.30281567573547363  (0.3078777079398815)
     | > stopnet_loss: 0.0034823366440832615  (0.0052322745561981816)
     | > loss: 0.1892283707857132  (0.1934371456885949)
     | > align_error: 0.546119749546051  (0.5828083104048019)

   --> STEP: 40
     | > decoder_loss: 0.4374777674674988  (0.44475518092513083)
     | > postnet_loss: 0.30136728286743164  (0.30771494731307025)
     | > stopnet_loss: 0.0030177016742527485  (0.005176910234149545)
     | > loss: 0.18772897124290466  (0.19329444132745266)
     | > align_error: 0.5837748050689697  (0.582832472771406)

   --> STEP: 41
     | > decoder_loss: 0.4283522963523865  (0.44435511056969806)
     | > postnet_loss: 0.29392826557159424  (0.30737868678279034)
     | > stopnet_loss: 0.003729029558598995  (0.0051415960713312395)
     | > loss: 0.18429917097091675  (0.19307504448948837)
     | > align_error: 0.5032913684844971  (0.5808924458375789)

   --> STEP: 42
     | > decoder_loss: 0.43205738067626953  (0.4440623074769974)
     | > postnet_loss: 0.29483652114868164  (0.30708006379150204)
     | > stopnet_loss: 0.0032869146671146154  (0.005097436990278463)
     | > loss: 0.1850103884935379  (0.19288302887053715)
     | > align_error: 0.5795277059078217  (0.5808599520297276)

   --> STEP: 43
     | > decoder_loss: 0.43196824193000793  (0.4437810501386953)
     | > postnet_loss: 0.29434266686439514  (0.30678384525831354)
     | > stopnet_loss: 0.002925465116277337  (0.005046926016464483)
     | > loss: 0.1845031976699829  (0.19268814907517545)
     | > align_error: 0.5517395436763763  (0.5801827332308125)

   --> STEP: 44
     | > decoder_loss: 0.44982126355171204  (0.4439183277162639)
     | > postnet_loss: 0.3053020238876343  (0.30675016749988904)
     | > stopnet_loss: 0.0026576085947453976  (0.004992623347789049)
     | > loss: 0.19143842160701752  (0.19265974617817186)
     | > align_error: 0.5509856641292572  (0.5795191634785044)

   --> STEP: 45
     | > decoder_loss: 0.4425647556781769  (0.4438882483376397)
     | > postnet_loss: 0.30403825640678406  (0.30668990280893116)
     | > stopnet_loss: 0.003289236919954419  (0.00495477031605939)
     | > loss: 0.18993999063968658  (0.19259930716620552)
     | > align_error: 0.5524407923221588  (0.5789174218972523)

   --> STEP: 46
     | > decoder_loss: 0.43337470293045044  (0.4436596930027008)
     | > postnet_loss: 0.29584506154060364  (0.30645414539005444)
     | > stopnet_loss: 0.0032041033264249563  (0.004916712338023859)
     | > loss: 0.18550905585289001  (0.19244517126808997)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3674331506093343 (+0.011417865753173828)
     | > avg_decoder_loss: 0.43978940311706427 (+0.0002806552431799947)
     | > avg_postnet_loss: 0.3036304671656002 (+0.0024148045164167353)
     | > avg_stopnet_loss: 0.004361634167391016 (-1.185273779838545e-05)
     | > avg_loss: 0.19021660179802866 (+0.0006620129852583923)
     | > avg_align_error: 0.5717673184293689 (-6.078499736206222e-05)


 > EPOCH: 130/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 16:11:11)

   --> TIME: 2025-12-28 16:11:40 -- STEP: 20/150 -- GLOBAL_STEP: 19650
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4691954553127289  (0.4668274983763695)
     | > postnet_loss: 0.39471015334129333  (0.39558145999908445)
     | > stopnet_loss: 0.007519561797380447  (0.010205381154082715)
     | > loss: 0.2234959602355957  (0.2258076198399067)
     | > align_error: 0.6308676600456238  (0.6780346602201461)
     | > grad_norm: tensor(0.3443, device='cuda:0')  (tensor(0.2792, device='cuda:0'))
     | > step_time: 0.8733  (0.6383126497268676)
     | > loader_time: 0.7863  (0.7758739471435547)


   --> TIME: 2025-12-28 16:12:31 -- STEP: 45/150 -- GLOBAL_STEP: 19675
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48663678765296936  (0.47512253920237224)
     | > postnet_loss: 0.4023670554161072  (0.3985611379146575)
     | > stopnet_loss: 0.005005745682865381  (0.00780271812238627)
     | > loss: 0.22725671529769897  (0.2262236369980706)
     | > align_error: 0.6319302916526794  (0.6491516417927213)
     | > grad_norm: tensor(0.1970, device='cuda:0')  (tensor(0.2622, device='cuda:0'))
     | > step_time: 1.2905  (0.8612953027089437)
     | > loader_time: 1.071  (0.8905477258894179)


   --> TIME: 2025-12-28 16:13:37 -- STEP: 70/150 -- GLOBAL_STEP: 19700
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48757240176200867  (0.478735882469586)
     | > postnet_loss: 0.3988499343395233  (0.39873578292982914)
     | > stopnet_loss: 0.003925494384020567  (0.006568908249028027)
     | > loss: 0.22553107142448425  (0.22593682408332824)
     | > align_error: 0.596351683139801  (0.6378534576722554)
     | > grad_norm: tensor(0.2597, device='cuda:0')  (tensor(0.2424, device='cuda:0'))
     | > step_time: 1.4689  (1.055757645198277)
     | > loader_time: 1.5026  (1.011119362286159)


   --> TIME: 2025-12-28 16:15:00 -- STEP: 95/150 -- GLOBAL_STEP: 19725
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48133084177970886  (0.47992935870823106)
     | > postnet_loss: 0.39324820041656494  (0.3978380777333912)
     | > stopnet_loss: 0.0032132042106240988  (0.005837013957237727)
     | > loss: 0.2218579649925232  (0.22527887240836494)
     | > align_error: 0.6022365987300873  (0.6330667141236753)
     | > grad_norm: tensor(0.1619, device='cuda:0')  (tensor(0.2246, device='cuda:0'))
     | > step_time: 1.7953  (1.2133164179952525)
     | > loader_time: 1.6046  (1.187124282435367)


   --> TIME: 2025-12-28 16:16:29 -- STEP: 120/150 -- GLOBAL_STEP: 19750
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48360881209373474  (0.4811835303902626)
     | > postnet_loss: 0.3928828239440918  (0.39744032646218935)
     | > stopnet_loss: 0.0031359477434307337  (0.005322821562488874)
     | > loss: 0.22225886583328247  (0.224978785465161)
     | > align_error: 0.6213087141513824  (0.6279694346090154)
     | > grad_norm: tensor(0.1323, device='cuda:0')  (tensor(0.2141, device='cuda:0'))
     | > step_time: 1.9985  (1.348237307866415)
     | > loader_time: 1.6035  (1.2952542801698048)


   --> TIME: 2025-12-28 16:18:10 -- STEP: 145/150 -- GLOBAL_STEP: 19775
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49204021692276  (0.4822970110794594)
     | > postnet_loss: 0.3975066840648651  (0.39706524096686263)
     | > stopnet_loss: 0.00275768362917006  (0.004942730157475533)
     | > loss: 0.2251444011926651  (0.22478329333765754)
     | > align_error: 0.63558429479599  (0.6241757914937773)
     | > grad_norm: tensor(0.1470, device='cuda:0')  (tensor(0.2099, device='cuda:0'))
     | > step_time: 2.6007  (1.4863093655684902)
     | > loader_time: 2.0166  (1.3976109504699712)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4589479863643646  (0.4589479863643646)
     | > postnet_loss: 0.33295440673828125  (0.33295440673828125)
     | > stopnet_loss: 0.012112683616578579  (0.012112683616578579)
     | > loss: 0.21008828282356262  (0.21008828282356262)
     | > align_error: 0.7185671031475067  (0.7185671031475067)

   --> STEP: 1
     | > decoder_loss: 0.4387253522872925  (0.4387253522872925)
     | > postnet_loss: 0.3197278082370758  (0.3197278082370758)
     | > stopnet_loss: 0.009638413786888123  (0.009638413786888123)
     | > loss: 0.1992516964673996  (0.1992516964673996)
     | > align_error: 0.6588442027568817  (0.6588442027568817)

   --> STEP: 2
     | > decoder_loss: 0.4361210763454437  (0.4374232143163681)
     | > postnet_loss: 0.3117115795612335  (0.31571969389915466)
     | > stopnet_loss: 0.011089899577200413  (0.010364156682044268)
     | > loss: 0.19804807007312775  (0.19864988327026367)
     | > align_error: 0.6551912426948547  (0.6570177227258682)

   --> STEP: 3
     | > decoder_loss: 0.44027942419052124  (0.43837528427441913)
     | > postnet_loss: 0.3115446865558624  (0.31432802478472394)
     | > stopnet_loss: 0.008331634104251862  (0.009686649156113466)
     | > loss: 0.19628766179084778  (0.19786247611045837)
     | > align_error: 0.7349327802658081  (0.6829894085725149)

   --> STEP: 4
     | > decoder_loss: 0.4433532655239105  (0.439619779586792)
     | > postnet_loss: 0.3183146119117737  (0.31532467156648636)
     | > stopnet_loss: 0.008132314309477806  (0.00929806544445455)
     | > loss: 0.1985492706298828  (0.19803417474031448)
     | > align_error: 0.6029115319252014  (0.6629699394106865)

   --> STEP: 5
     | > decoder_loss: 0.42687851190567017  (0.43707152605056765)
     | > postnet_loss: 0.3017427325248718  (0.31260828375816346)
     | > stopnet_loss: 0.008169279433786869  (0.009072308242321015)
     | > loss: 0.1903245896100998  (0.19649225771427153)
     | > align_error: 0.641346663236618  (0.6586452841758728)

   --> STEP: 6
     | > decoder_loss: 0.4433405101299286  (0.4381163567304611)
     | > postnet_loss: 0.3135530352592468  (0.31276574234167737)
     | > stopnet_loss: 0.0072828312404453754  (0.00877406207534174)
     | > loss: 0.19650621712207794  (0.1964945842822393)
     | > align_error: 0.5934311151504517  (0.6477762560049692)

   --> STEP: 7
     | > decoder_loss: 0.45600029826164246  (0.4406712055206299)
     | > postnet_loss: 0.31407126784324646  (0.3129522459847586)
     | > stopnet_loss: 0.006251044105738401  (0.008413630936826979)
     | > loss: 0.19876892864704132  (0.19681949062006815)
     | > align_error: 0.5784141719341278  (0.637867386851992)

   --> STEP: 8
     | > decoder_loss: 0.451355904340744  (0.44200679287314415)
     | > postnet_loss: 0.3155388832092285  (0.3132755756378174)
     | > stopnet_loss: 0.007529973052442074  (0.008303173701278865)
     | > loss: 0.19925367832183838  (0.19712376408278942)
     | > align_error: 0.5748867094516754  (0.6299948021769524)

   --> STEP: 9
     | > decoder_loss: 0.446839839220047  (0.44254379802280003)
     | > postnet_loss: 0.31362617015838623  (0.3133145305845473)
     | > stopnet_loss: 0.006688123568892479  (0.008123723686569266)
     | > loss: 0.19680461287498474  (0.1970883028374778)
     | > align_error: 0.5907114744186401  (0.6256299879815843)

   --> STEP: 10
     | > decoder_loss: 0.4719501733779907  (0.44548443555831907)
     | > postnet_loss: 0.32775235176086426  (0.31475831270217897)
     | > stopnet_loss: 0.005561046302318573  (0.007867455948144197)
     | > loss: 0.20548668503761292  (0.1979281410574913)
     | > align_error: 0.5841370522975922  (0.6214806944131851)

   --> STEP: 11
     | > decoder_loss: 0.4591864347457886  (0.44673007184808905)
     | > postnet_loss: 0.31793493032455444  (0.3150470961223949)
     | > stopnet_loss: 0.005929003935307264  (0.007691233037886294)
     | > loss: 0.2002093493938446  (0.1981355236335234)
     | > align_error: 0.5942138433456421  (0.6190018897706812)

   --> STEP: 12
     | > decoder_loss: 0.4539719223976135  (0.44733355939388275)
     | > postnet_loss: 0.3111245930194855  (0.3147202208638191)
     | > stopnet_loss: 0.007855142466723919  (0.007704892156956096)
     | > loss: 0.19912928342819214  (0.1982183369497458)
     | > align_error: 0.587026059627533  (0.6163372372587521)

   --> STEP: 13
     | > decoder_loss: 0.4447422921657562  (0.44713423114556533)
     | > postnet_loss: 0.31134530901908875  (0.3144606122603783)
     | > stopnet_loss: 0.00558198057115078  (0.007541591265740303)
     | > loss: 0.19460387527942657  (0.19794030143664434)
     | > align_error: 0.5853139460086823  (0.613950830239516)

   --> STEP: 14
     | > decoder_loss: 0.4549259543418884  (0.44769078280244556)
     | > postnet_loss: 0.3139232099056244  (0.3144222263778959)
     | > stopnet_loss: 0.004917729180306196  (0.007354172545352152)
     | > loss: 0.1971300095319748  (0.19788242344345366)
     | > align_error: 0.5546377897262573  (0.609714184488569)

   --> STEP: 15
     | > decoder_loss: 0.4549174904823303  (0.4481725633144379)
     | > postnet_loss: 0.31491580605506897  (0.31445513168970746)
     | > stopnet_loss: 0.005017356481403112  (0.0071983848077555495)
     | > loss: 0.19747568666934967  (0.1978553076585134)
     | > align_error: 0.5880333781242371  (0.6082687973976135)

   --> STEP: 16
     | > decoder_loss: 0.4555095434188843  (0.44863112457096577)
     | > postnet_loss: 0.3089117109775543  (0.31410866789519787)
     | > stopnet_loss: 0.005236461758613586  (0.007075764617184177)
     | > loss: 0.19634176790714264  (0.19776071142405272)
     | > align_error: 0.6058124303817749  (0.6081152744591236)

   --> STEP: 17
     | > decoder_loss: 0.462058961391449  (0.4494209973251118)
     | > postnet_loss: 0.31746816635131836  (0.31430628545144024)
     | > stopnet_loss: 0.004831523168832064  (0.006943750414339935)
     | > loss: 0.1997133046388626  (0.1978755698484533)
     | > align_error: 0.5580262541770935  (0.6051688615013572)

   --> STEP: 18
     | > decoder_loss: 0.4554618299007416  (0.44975659913486904)
     | > postnet_loss: 0.30945444107055664  (0.31403673854139114)
     | > stopnet_loss: 0.005277474410831928  (0.006851179525256157)
     | > loss: 0.1965065449476242  (0.19779951290951836)
     | > align_error: 0.6037135422229767  (0.605088010430336)

   --> STEP: 19
     | > decoder_loss: 0.4540270268917084  (0.44998135849049214)
     | > postnet_loss: 0.3092801570892334  (0.3137863921491723)
     | > stopnet_loss: 0.004834532737731934  (0.006745040220649619)
     | > loss: 0.19566133618354797  (0.197686977292362)
     | > align_error: 0.5999438762664795  (0.6048172665269751)

   --> STEP: 20
     | > decoder_loss: 0.4499223828315735  (0.4499784097075462)
     | > postnet_loss: 0.30558961629867554  (0.3133765533566475)
     | > stopnet_loss: 0.004513481631875038  (0.00663346229121089)
     | > loss: 0.19339148700237274  (0.19747220277786254)
     | > align_error: 0.6224561333656311  (0.6056992098689079)

   --> STEP: 21
     | > decoder_loss: 0.4471479058265686  (0.44984362380845205)
     | > postnet_loss: 0.304703027009964  (0.3129635282925197)
     | > stopnet_loss: 0.003989376127719879  (0.006507553426282746)
     | > loss: 0.19195210933685303  (0.1972093411854335)
     | > align_error: 0.5597474575042725  (0.6035110311848777)

   --> STEP: 22
     | > decoder_loss: 0.4496539831161499  (0.44983500377698377)
     | > postnet_loss: 0.30780327320098877  (0.31272897124290466)
     | > stopnet_loss: 0.004900243133306503  (0.006434493867511099)
     | > loss: 0.19426456093788147  (0.19707548753781753)
     | > align_error: 0.6249639987945557  (0.6044861660762266)

   --> STEP: 23
     | > decoder_loss: 0.4231173098087311  (0.4486733649087989)
     | > postnet_loss: 0.29570576548576355  (0.3119888318621594)
     | > stopnet_loss: 0.004488518927246332  (0.006349886261412631)
     | > loss: 0.18419428169727325  (0.19651543510996777)
     | > align_error: 0.5668608844280243  (0.6028502842654353)

   --> STEP: 24
     | > decoder_loss: 0.45795518159866333  (0.4490601072708766)
     | > postnet_loss: 0.311708003282547  (0.31197713067134225)
     | > stopnet_loss: 0.004413997754454613  (0.00626922424028938)
     | > loss: 0.19682979583740234  (0.19652853347361088)
     | > align_error: 0.5790472626686096  (0.6018584916989008)

   --> STEP: 25
     | > decoder_loss: 0.4569830894470215  (0.4493770265579224)
     | > postnet_loss: 0.30871206521987915  (0.3118465280532837)
     | > stopnet_loss: 0.0037281636614352465  (0.006167581817135215)
     | > loss: 0.19515195488929749  (0.19647347033023835)
     | > align_error: 0.557633101940155  (0.600089476108551)

   --> STEP: 26
     | > decoder_loss: 0.4314943552017212  (0.4486892315057608)
     | > postnet_loss: 0.297210693359375  (0.3112836113342872)
     | > stopnet_loss: 0.004369213245809078  (0.006098413795161133)
     | > loss: 0.1865454763174057  (0.19609162440666786)
     | > align_error: 0.5462801456451416  (0.598019886475343)

   --> STEP: 27
     | > decoder_loss: 0.42911964654922485  (0.44796443206292613)
     | > postnet_loss: 0.2925856411457062  (0.3105910939198953)
     | > stopnet_loss: 0.003923387732356787  (0.0060178572743165275)
     | > loss: 0.18434971570968628  (0.19565673889937224)
     | > align_error: 0.5405974984169006  (0.5958931313620673)

   --> STEP: 28
     | > decoder_loss: 0.43416231870651245  (0.4474714994430542)
     | > postnet_loss: 0.2968359589576721  (0.3100998390998159)
     | > stopnet_loss: 0.003937821369618177  (0.005943570277720157)
     | > loss: 0.1866873949766159  (0.19533640518784523)
     | > align_error: 0.5658437013626099  (0.5948199374335152)

   --> STEP: 29
     | > decoder_loss: 0.42960458993911743  (0.44685539911533223)
     | > postnet_loss: 0.29379329085350037  (0.3095375443327016)
     | > stopnet_loss: 0.003580935299396515  (0.005862100106053825)
     | > loss: 0.18443039059638977  (0.19496033571917434)
     | > align_error: 0.5401445627212524  (0.5929345796848166)

   --> STEP: 30
     | > decoder_loss: 0.4304335117340088  (0.4463080028692881)
     | > postnet_loss: 0.29475563764572144  (0.3090448141098022)
     | > stopnet_loss: 0.0028784656897187233  (0.005762645625509322)
     | > loss: 0.1841757595539093  (0.19460084984699885)
     | > align_error: 0.5331571698188782  (0.5909419993559519)

   --> STEP: 31
     | > decoder_loss: 0.4295289218425751  (0.44576674219100704)
     | > postnet_loss: 0.2946225702762604  (0.3085795804377525)
     | > stopnet_loss: 0.0037224753759801388  (0.005696833681976122)
     | > loss: 0.18476034700870514  (0.19428341427157003)
     | > align_error: 0.5584861636161804  (0.5898950369127335)

   --> STEP: 32
     | > decoder_loss: 0.43770864605903625  (0.445514926686883)
     | > postnet_loss: 0.2988709509372711  (0.30827618576586246)
     | > stopnet_loss: 0.003856765106320381  (0.00563933153898688)
     | > loss: 0.18800166249275208  (0.19408710952848196)
     | > align_error: 0.5305050015449524  (0.5880390983074903)

   --> STEP: 33
     | > decoder_loss: 0.4354914724826813  (0.445211185650392)
     | > postnet_loss: 0.2971798777580261  (0.30793993400804925)
     | > stopnet_loss: 0.0040196627378463745  (0.005590250666225047)
     | > loss: 0.18718750774860382  (0.19387803068666748)
     | > align_error: 0.5455338358879089  (0.5867510600523516)

   --> STEP: 34
     | > decoder_loss: 0.4404864013195038  (0.4450722214053659)
     | > postnet_loss: 0.29829615354537964  (0.30765629340620604)
     | > stopnet_loss: 0.0033227226231247187  (0.00552355866495739)
     | > loss: 0.18801835179328918  (0.1937056871898034)
     | > align_error: 0.5631872415542603  (0.5860580065671135)

   --> STEP: 35
     | > decoder_loss: 0.43801021575927734  (0.44487044981547763)
     | > postnet_loss: 0.2975299656391144  (0.3073669697557177)
     | > stopnet_loss: 0.0035080474335700274  (0.005465972629774894)
     | > loss: 0.18739308416843414  (0.19352532710347856)
     | > align_error: 0.5326588451862335  (0.5845323162419456)

   --> STEP: 36
     | > decoder_loss: 0.4443303048610687  (0.4448554457889663)
     | > postnet_loss: 0.3021722137928009  (0.30722267097897)
     | > stopnet_loss: 0.003675174666568637  (0.005416228241908054)
     | > loss: 0.1903008073568344  (0.19343575711051622)
     | > align_error: 0.633335292339325  (0.5858879544668727)

   --> STEP: 37
     | > decoder_loss: 0.4370029866695404  (0.4446432171641169)
     | > postnet_loss: 0.2988772690296173  (0.3069971195749334)
     | > stopnet_loss: 0.0035591223277151585  (0.00536603619017311)
     | > loss: 0.18752919137477875  (0.19327612019873955)
     | > align_error: 0.5181494653224945  (0.5840571844899977)

   --> STEP: 38
     | > decoder_loss: 0.424385130405426  (0.4441101096178356)
     | > postnet_loss: 0.2914930582046509  (0.306589117959926)
     | > stopnet_loss: 0.003152337623760104  (0.0053077809647411895)
     | > loss: 0.1821218878030777  (0.19298258776727475)
     | > align_error: 0.5509857833385468  (0.5831868844596964)

   --> STEP: 39
     | > decoder_loss: 0.4401462972164154  (0.44400847340241456)
     | > postnet_loss: 0.30214276909828186  (0.30647510901475566)
     | > stopnet_loss: 0.00347976409830153  (0.005260908737396583)
     | > loss: 0.1890520304441452  (0.19288180424616888)
     | > align_error: 0.5452634692192078  (0.5822144891971197)

   --> STEP: 40
     | > decoder_loss: 0.4363027811050415  (0.44381583109498024)
     | > postnet_loss: 0.30023106932640076  (0.3063190080225468)
     | > stopnet_loss: 0.003027111990377307  (0.005205063818721101)
     | > loss: 0.18716058135032654  (0.19273877367377282)
     | > align_error: 0.5831384062767029  (0.5822375871241092)

   --> STEP: 41
     | > decoder_loss: 0.4283437728881836  (0.44343846382164376)
     | > postnet_loss: 0.2933800220489502  (0.30600342299880057)
     | > stopnet_loss: 0.003743778681382537  (0.005169422717810404)
     | > loss: 0.18417473137378693  (0.19252989459328534)
     | > align_error: 0.5025773346424103  (0.5802946541367507)

   --> STEP: 42
     | > decoder_loss: 0.4325834810733795  (0.44318001185144695)
     | > postnet_loss: 0.29487043619155884  (0.3057383518843424)
     | > stopnet_loss: 0.003286499995738268  (0.005124591224427734)
     | > loss: 0.18514998257160187  (0.19235418240229288)
     | > align_error: 0.578818678855896  (0.5802595118681589)

   --> STEP: 43
     | > decoder_loss: 0.4313570261001587  (0.44290505869444025)
     | > postnet_loss: 0.293803870677948  (0.3054608058097751)
     | > stopnet_loss: 0.0029454007744789124  (0.005073912376754505)
     | > loss: 0.18423563241958618  (0.19216537891432298)
     | > align_error: 0.5511932969093323  (0.5795835533807444)

   --> STEP: 44
     | > decoder_loss: 0.4492793679237366  (0.44304992935874243)
     | > postnet_loss: 0.3045703172683716  (0.3054405674338341)
     | > stopnet_loss: 0.0026632279623299837  (0.005019124094608494)
     | > loss: 0.19112564623355865  (0.19214174862612377)
     | > align_error: 0.5500025749206543  (0.5789112584157423)

   --> STEP: 45
     | > decoder_loss: 0.4424822926521301  (0.44303731520970663)
     | > postnet_loss: 0.3036426305770874  (0.30540061328146195)
     | > stopnet_loss: 0.003298372495919466  (0.0049808851701931825)
     | > loss: 0.18982960283756256  (0.19209036760860018)
     | > align_error: 0.5519104301929474  (0.5783112400107914)

   --> STEP: 46
     | > decoder_loss: 0.43316730856895447  (0.44282274984795117)
     | > postnet_loss: 0.295125812292099  (0.3051772480425628)
     | > stopnet_loss: 0.0032062376849353313  (0.004942305877035404)
     | > loss: 0.18527951836585999  (0.19194230566854062)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3519167972333503 (-0.015516353375984004)
     | > avg_decoder_loss: 0.4389844884475072 (-0.0008049146695570664)
     | > avg_postnet_loss: 0.30234033998214843 (-0.0012901271834517836)
     | > avg_stopnet_loss: 0.004381480101129098 (+1.984593373808262e-05)
     | > avg_loss: 0.18971268719795978 (-0.0005039146000688777)
     | > avg_align_error: 0.5711222503221396 (-0.0006450681072293074)


 > EPOCH: 131/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 16:20:29)

   --> TIME: 2025-12-28 16:20:58 -- STEP: 19/150 -- GLOBAL_STEP: 19800
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47936421632766724  (0.46687304659893636)
     | > postnet_loss: 0.4002540707588196  (0.3955867133642498)
     | > stopnet_loss: 0.007917596958577633  (0.0105099255023034)
     | > loss: 0.2278221696615219  (0.22612486701262624)
     | > align_error: 0.6357323527336121  (0.6801270168078574)
     | > grad_norm: tensor(0.3491, device='cuda:0')  (tensor(0.2937, device='cuda:0'))
     | > step_time: 0.7035  (0.6117267357675653)
     | > loader_time: 0.9764  (0.8485873623898155)


   --> TIME: 2025-12-28 16:21:49 -- STEP: 44/150 -- GLOBAL_STEP: 19825
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48594143986701965  (0.475119143047116)
     | > postnet_loss: 0.4007951319217682  (0.39865526827898895)
     | > stopnet_loss: 0.0051405541598796844  (0.0078968179454519)
     | > loss: 0.22682470083236694  (0.22634042189879852)
     | > align_error: 0.5889244377613068  (0.6500482240861113)
     | > grad_norm: tensor(0.2095, device='cuda:0')  (tensor(0.2806, device='cuda:0'))
     | > step_time: 1.1137  (0.8429039229046215)
     | > loader_time: 1.028  (0.9443308277563616)


   --> TIME: 2025-12-28 16:22:55 -- STEP: 69/150 -- GLOBAL_STEP: 19850
     | > current_lr: 1e-05  (1.0000000000000016e-05)
     | > decoder_loss: 0.48562031984329224  (0.47850407983945764)
     | > postnet_loss: 0.3981291949748993  (0.3985902831174325)
     | > stopnet_loss: 0.004494206048548222  (0.006643882439728232)
     | > loss: 0.22543157637119293  (0.2259174730034842)
     | > align_error: 0.6099883317947388  (0.6383132938889492)
     | > grad_norm: tensor(0.1351, device='cuda:0')  (tensor(0.2399, device='cuda:0'))
     | > step_time: 1.6062  (1.0373780105424963)
     | > loader_time: 1.3128  (1.0468895297119583)


   --> TIME: 2025-12-28 16:24:12 -- STEP: 94/150 -- GLOBAL_STEP: 19875
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4812977910041809  (0.47964790590265965)
     | > postnet_loss: 0.39410921931266785  (0.3976398069173731)
     | > stopnet_loss: 0.0037144157104194164  (0.005880489162704412)
     | > loss: 0.222566157579422  (0.22520241712002045)
     | > align_error: 0.6159390211105347  (0.6335232324422676)
     | > grad_norm: tensor(0.1627, device='cuda:0')  (tensor(0.2246, device='cuda:0'))
     | > step_time: 1.7165  (1.1996601109809064)
     | > loader_time: 1.512  (1.1564056416775321)


   --> TIME: 2025-12-28 16:25:40 -- STEP: 119/150 -- GLOBAL_STEP: 19900
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48051175475120544  (0.480876842466723)
     | > postnet_loss: 0.3921327292919159  (0.39721263682141017)
     | > stopnet_loss: 0.0032193607185035944  (0.005355391238557817)
     | > loss: 0.22138048708438873  (0.22487776031514176)
     | > align_error: 0.614576131105423  (0.6280065877597876)
     | > grad_norm: tensor(0.1544, device='cuda:0')  (tensor(0.2097, device='cuda:0'))
     | > step_time: 1.901  (1.342885939013057)
     | > loader_time: 1.9419  (1.2546436526194342)


   --> TIME: 2025-12-28 16:27:25 -- STEP: 144/150 -- GLOBAL_STEP: 19925
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48879292607307434  (0.4819763569782178)
     | > postnet_loss: 0.39475926756858826  (0.3968179188668728)
     | > stopnet_loss: 0.0029001578222960234  (0.004967949847923591)
     | > loss: 0.22378820180892944  (0.22466651795225012)
     | > align_error: 0.5938739478588104  (0.6241771686408256)
     | > grad_norm: tensor(0.2276, device='cuda:0')  (tensor(0.2028, device='cuda:0'))
     | > step_time: 2.3133  (1.4782015499141485)
     | > loader_time: 2.1985  (1.3969330175055399)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46096184849739075  (0.46096184849739075)
     | > postnet_loss: 0.3328086733818054  (0.3328086733818054)
     | > stopnet_loss: 0.012093407101929188  (0.012093407101929188)
     | > loss: 0.21053604781627655  (0.21053604781627655)
     | > align_error: 0.7184917032718658  (0.7184917032718658)

   --> STEP: 1
     | > decoder_loss: 0.4426289498806  (0.4426289498806)
     | > postnet_loss: 0.32034018635749817  (0.32034018635749817)
     | > stopnet_loss: 0.009669473394751549  (0.009669473394751549)
     | > loss: 0.20041175186634064  (0.20041175186634064)
     | > align_error: 0.6589076519012451  (0.6589076519012451)

   --> STEP: 2
     | > decoder_loss: 0.4380131959915161  (0.44032107293605804)
     | > postnet_loss: 0.3117982745170593  (0.31606923043727875)
     | > stopnet_loss: 0.011058229021728039  (0.010363851208239794)
     | > loss: 0.19851109385490417  (0.1994614228606224)
     | > align_error: 0.6551043689250946  (0.6570060104131699)

   --> STEP: 3
     | > decoder_loss: 0.4424619674682617  (0.4410347044467926)
     | > postnet_loss: 0.3112829625606537  (0.31447380781173706)
     | > stopnet_loss: 0.008272167295217514  (0.009666623237232367)
     | > loss: 0.19670841097831726  (0.19854375223318735)
     | > align_error: 0.7346604466438293  (0.6828908224900564)

   --> STEP: 4
     | > decoder_loss: 0.44614872336387634  (0.44231320917606354)
     | > postnet_loss: 0.31845614314079285  (0.315469391644001)
     | > stopnet_loss: 0.008101074956357479  (0.009275236167013645)
     | > loss: 0.19925229251384735  (0.19872088730335236)
     | > align_error: 0.603283554315567  (0.662989005446434)

   --> STEP: 5
     | > decoder_loss: 0.42806166410446167  (0.43946290016174316)
     | > postnet_loss: 0.30145299434661865  (0.31266611218452456)
     | > stopnet_loss: 0.008147045038640499  (0.009049597941339017)
     | > loss: 0.19052571058273315  (0.1970818519592285)
     | > align_error: 0.6418308615684509  (0.6587573766708374)

   --> STEP: 6
     | > decoder_loss: 0.4459701180458069  (0.4405474364757538)
     | > postnet_loss: 0.3136700689792633  (0.312833438316981)
     | > stopnet_loss: 0.007247434929013252  (0.008749237439284721)
     | > loss: 0.19715748727321625  (0.19709445784489313)
     | > align_error: 0.5931370854377747  (0.6478206614653269)

   --> STEP: 7
     | > decoder_loss: 0.457756906747818  (0.44300593222890583)
     | > postnet_loss: 0.313972145318985  (0.3129961107458387)
     | > stopnet_loss: 0.006213972810655832  (0.008387056778052024)
     | > loss: 0.19914624094963074  (0.1973875697169985)
     | > align_error: 0.5783487558364868  (0.6378961035183498)

   --> STEP: 8
     | > decoder_loss: 0.451289564371109  (0.4440413862466812)
     | > postnet_loss: 0.3138103783130646  (0.31309789419174194)
     | > stopnet_loss: 0.007054065354168415  (0.008220432850066572)
     | > loss: 0.19832904636859894  (0.19750525429844856)
     | > align_error: 0.5737998485565186  (0.6298840716481209)

   --> STEP: 9
     | > decoder_loss: 0.44714146852493286  (0.4443858398331536)
     | > postnet_loss: 0.31257209181785583  (0.3130394717057546)
     | > stopnet_loss: 0.006700364872813225  (0.008051536408149533)
     | > loss: 0.19662874937057495  (0.19740786486201817)
     | > align_error: 0.5910215973854065  (0.6255660189522637)

   --> STEP: 10
     | > decoder_loss: 0.4733879566192627  (0.44728605151176454)
     | > postnet_loss: 0.327285498380661  (0.31446407437324525)
     | > stopnet_loss: 0.005585665348917246  (0.007804949302226305)
     | > loss: 0.20575404167175293  (0.19824248254299165)
     | > align_error: 0.5829554796218872  (0.621304965019226)

   --> STEP: 11
     | > decoder_loss: 0.46038034558296204  (0.4484764418818734)
     | > postnet_loss: 0.3178510069847107  (0.3147719773379239)
     | > stopnet_loss: 0.00586373545229435  (0.0076284753158688545)
     | > loss: 0.20042158663272858  (0.19844058291478592)
     | > align_error: 0.5944691300392151  (0.6188653436574069)

   --> STEP: 12
     | > decoder_loss: 0.45711204409599304  (0.4491960753997167)
     | > postnet_loss: 0.31162121891975403  (0.3145094141364097)
     | > stopnet_loss: 0.007904408499598503  (0.007651469747846325)
     | > loss: 0.20008772611618042  (0.19857784484823546)
     | > align_error: 0.5870454907417297  (0.6162136892477671)

   --> STEP: 13
     | > decoder_loss: 0.4463176429271698  (0.4489746575172131)
     | > postnet_loss: 0.3110961318016052  (0.31424685395680935)
     | > stopnet_loss: 0.00551257049664855  (0.007486939036215727)
     | > loss: 0.19486600160598755  (0.1982923184449856)
     | > align_error: 0.5856287479400635  (0.6138610014548669)

   --> STEP: 14
     | > decoder_loss: 0.4596043825149536  (0.44973392358848024)
     | > postnet_loss: 0.31574878096580505  (0.3143541344574519)
     | > stopnet_loss: 0.0048746406100690365  (0.007300346291490963)
     | > loss: 0.19871294498443604  (0.1983223631978035)
     | > align_error: 0.5542649626731873  (0.6096041415418897)

   --> STEP: 15
     | > decoder_loss: 0.45433509349823  (0.45004066824913025)
     | > postnet_loss: 0.3139131963253021  (0.31432473858197524)
     | > stopnet_loss: 0.004986497573554516  (0.007146089710295201)
     | > loss: 0.19704857468605042  (0.19823744396368662)
     | > align_error: 0.5882951021194458  (0.6081835389137268)

   --> STEP: 16
     | > decoder_loss: 0.4545655846595764  (0.45032347552478313)
     | > postnet_loss: 0.30771470069885254  (0.3139116112142801)
     | > stopnet_loss: 0.005231184884905815  (0.007026408158708364)
     | > loss: 0.1958012580871582  (0.1980851823464036)
     | > align_error: 0.6058285534381866  (0.6080363523215055)

   --> STEP: 17
     | > decoder_loss: 0.46280840039253235  (0.45105788286994486)
     | > postnet_loss: 0.31740400195121765  (0.3141170459635117)
     | > stopnet_loss: 0.004816750530153513  (0.006896428298205137)
     | > loss: 0.19986985623836517  (0.19819016316357782)
     | > align_error: 0.5583234131336212  (0.6051120617810417)

   --> STEP: 18
     | > decoder_loss: 0.45570796728134155  (0.4513162208928002)
     | > postnet_loss: 0.3088022470474243  (0.3138217793570624)
     | > stopnet_loss: 0.005246930290013552  (0.006804789519972271)
     | > loss: 0.19637449085712433  (0.19808929247988594)
     | > align_error: 0.6038992702960968  (0.6050446844763226)

   --> STEP: 19
     | > decoder_loss: 0.452457994222641  (0.45137631422594976)
     | > postnet_loss: 0.3076200485229492  (0.31349537247105647)
     | > stopnet_loss: 0.004711545072495937  (0.00669461875957878)
     | > loss: 0.19473105669021606  (0.19791254322779805)
     | > align_error: 0.5994341373443604  (0.6047493925220088)

   --> STEP: 20
     | > decoder_loss: 0.4501360356807709  (0.4513143002986908)
     | > postnet_loss: 0.30497297644615173  (0.3130692526698112)
     | > stopnet_loss: 0.004499427042901516  (0.006584859173744917)
     | > loss: 0.19327667355537415  (0.19768074974417688)
     | > align_error: 0.6226958930492401  (0.6056467175483704)

   --> STEP: 21
     | > decoder_loss: 0.44752323627471924  (0.45113377344040645)
     | > postnet_loss: 0.30353331565856934  (0.3126151604311807)
     | > stopnet_loss: 0.003953887149691582  (0.006459574791647139)
     | > loss: 0.19171802699565887  (0.197396810565676)
     | > align_error: 0.5601203739643097  (0.6034787964253199)

   --> STEP: 22
     | > decoder_loss: 0.4497278034687042  (0.45106986571442)
     | > postnet_loss: 0.306524395942688  (0.3123383074998856)
     | > stopnet_loss: 0.004897087346762419  (0.00638855263506147)
     | > loss: 0.19396013021469116  (0.19724059782244943)
     | > align_error: 0.6251701414585114  (0.6044647666541013)

   --> STEP: 23
     | > decoder_loss: 0.4231240451335907  (0.4498548300369926)
     | > postnet_loss: 0.2944820821285248  (0.3115619498750438)
     | > stopnet_loss: 0.004473861772567034  (0.006305305206257364)
     | > loss: 0.18387539684772491  (0.19665950212789618)
     | > align_error: 0.5670714974403381  (0.6028389723404594)

   --> STEP: 24
     | > decoder_loss: 0.45738911628723145  (0.45016875863075256)
     | > postnet_loss: 0.31037524342536926  (0.31151250377297407)
     | > stopnet_loss: 0.0043917493894696236  (0.006225573713891208)
     | > loss: 0.19633282721042633  (0.19664589067300162)
     | > align_error: 0.5793402194976807  (0.6018598576386769)

   --> STEP: 25
     | > decoder_loss: 0.4564618766307831  (0.4504204833507538)
     | > postnet_loss: 0.30744194984436035  (0.31134968161582954)
     | > stopnet_loss: 0.003687135176733136  (0.006124036172404885)
     | > loss: 0.19466309249401093  (0.196566578745842)
     | > align_error: 0.5579022467136383  (0.6001015532016754)

   --> STEP: 26
     | > decoder_loss: 0.4315476417541504  (0.4496946048278075)
     | > postnet_loss: 0.29590144753456116  (0.31075551876655)
     | > stopnet_loss: 0.004343847278505564  (0.006055567368793373)
     | > loss: 0.18620611727237701  (0.19616809945840102)
     | > align_error: 0.5465823411941528  (0.5980431219706168)

   --> STEP: 27
     | > decoder_loss: 0.4283786118030548  (0.4489051236046685)
     | > postnet_loss: 0.2911832928657532  (0.31003062151096494)
     | > stopnet_loss: 0.0036660432815551758  (0.0059670664766734395)
     | > loss: 0.18355652689933777  (0.19570100417843572)
     | > align_error: 0.5402352809906006  (0.5959020908232089)

   --> STEP: 28
     | > decoder_loss: 0.4341844618320465  (0.4483793856842177)
     | > postnet_loss: 0.2957006096839905  (0.30951883537428726)
     | > stopnet_loss: 0.003921680152416229  (0.005894016965092825)
     | > loss: 0.18639296293258667  (0.1953685741339411)
     | > align_error: 0.5661419332027435  (0.5948392280510494)

   --> STEP: 29
     | > decoder_loss: 0.4294094741344452  (0.4477252508031911)
     | > postnet_loss: 0.2922881841659546  (0.308924674987793)
     | > stopnet_loss: 0.0035739410668611526  (0.005814014347912422)
     | > loss: 0.18399836122989655  (0.1949764978269051)
     | > align_error: 0.5402967035770416  (0.5929584513450491)

   --> STEP: 30
     | > decoder_loss: 0.430482417345047  (0.4471504896879196)
     | > postnet_loss: 0.2932558059692383  (0.3084023793538412)
     | > stopnet_loss: 0.0028132833540439606  (0.005713989981450141)
     | > loss: 0.18374782800674438  (0.19460220883289972)
     | > align_error: 0.5332269668579102  (0.5909674018621445)

   --> STEP: 31
     | > decoder_loss: 0.42524856328964233  (0.4464439759331365)
     | > postnet_loss: 0.29149726033210754  (0.3078570529337853)
     | > stopnet_loss: 0.0036874294746667147  (0.005648617061876481)
     | > loss: 0.1828738898038864  (0.19422387596099608)
     | > align_error: 0.5553780496120453  (0.5898193582411735)

   --> STEP: 32
     | > decoder_loss: 0.43952473998069763  (0.44622774980962276)
     | > postnet_loss: 0.2987145185470581  (0.30757134873420006)
     | > stopnet_loss: 0.0038416183087974787  (0.005592148350842763)
     | > loss: 0.18840144574642181  (0.19404192501679063)
     | > align_error: 0.5309984385967255  (0.5879812045022845)

   --> STEP: 33
     | > decoder_loss: 0.4343011975288391  (0.4458663391344475)
     | > postnet_loss: 0.29549694061279297  (0.3072054575790059)
     | > stopnet_loss: 0.004018768202513456  (0.005544470164529754)
     | > loss: 0.18646830320358276  (0.1938124213254813)
     | > align_error: 0.545985609292984  (0.5867086107080633)

   --> STEP: 34
     | > decoder_loss: 0.43997904658317566  (0.4456931834711748)
     | > postnet_loss: 0.29695141315460205  (0.30690386803711167)
     | > stopnet_loss: 0.0032987785525619984  (0.005478420411236584)
     | > loss: 0.18753139674663544  (0.19362768530845642)
     | > align_error: 0.5635040402412415  (0.586026123341392)

   --> STEP: 35
     | > decoder_loss: 0.437042772769928  (0.44544602887971063)
     | > postnet_loss: 0.2957760989665985  (0.3065859317779542)
     | > stopnet_loss: 0.0035186021123081446  (0.005422425602695772)
     | > loss: 0.18672330677509308  (0.19343041735036032)
     | > align_error: 0.5329246520996094  (0.5845089384487697)

   --> STEP: 36
     | > decoder_loss: 0.4431467056274414  (0.4453821587893698)
     | > postnet_loss: 0.30025413632392883  (0.30641004857089793)
     | > stopnet_loss: 0.003649723483249545  (0.005373183877155598)
     | > loss: 0.18949992954730988  (0.19332123713360894)
     | > align_error: 0.6335878372192383  (0.5858722411923938)

   --> STEP: 37
     | > decoder_loss: 0.436372309923172  (0.44513864936055364)
     | > postnet_loss: 0.29706335067749023  (0.30615743511431937)
     | > stopnet_loss: 0.003564890008419752  (0.005324311069892468)
     | > loss: 0.1869238018989563  (0.19314833347861832)
     | > align_error: 0.5187033414840698  (0.5840568655246013)

   --> STEP: 38
     | > decoder_loss: 0.42361167073249817  (0.4445721499229732)
     | > postnet_loss: 0.28983867168426514  (0.3057279939714232)
     | > stopnet_loss: 0.003141348948702216  (0.005266864698282198)
     | > loss: 0.18150392174720764  (0.1928419015909496)
     | > align_error: 0.5512829720973969  (0.5831943946449382)

   --> STEP: 39
     | > decoder_loss: 0.43931254744529724  (0.44443728832098156)
     | > postnet_loss: 0.30022940039634705  (0.3055870043925751)
     | > stopnet_loss: 0.0034770627971738577  (0.005220972341843522)
     | > loss: 0.18836255371570587  (0.19272704651722541)
     | > align_error: 0.5457151532173157  (0.5822333884544864)

   --> STEP: 40
     | > decoder_loss: 0.43604516983032227  (0.44422748535871504)
     | > postnet_loss: 0.2985859215259552  (0.3054119773209096)
     | > stopnet_loss: 0.0030232055578380823  (0.005166028172243387)
     | > loss: 0.18668097257614136  (0.19257589466869832)
     | > align_error: 0.5834636390209198  (0.5822641447186472)

   --> STEP: 41
     | > decoder_loss: 0.4266504645347595  (0.44379877753374053)
     | > postnet_loss: 0.2906428575515747  (0.3050517548875112)
     | > stopnet_loss: 0.003718434600159526  (0.005130721011948659)
     | > loss: 0.1830417662858963  (0.1923433549520446)
     | > align_error: 0.5025002360343933  (0.5803186835312264)

   --> STEP: 42
     | > decoder_loss: 0.43178051710128784  (0.443512628475825)
     | > postnet_loss: 0.2932284474372864  (0.3047702475672677)
     | > stopnet_loss: 0.0032888008281588554  (0.005086865769477473)
     | > loss: 0.18454104661941528  (0.19215758570602962)
     | > align_error: 0.579190731048584  (0.5802918275197348)

   --> STEP: 43
     | > decoder_loss: 0.4307968318462372  (0.4432169122751369)
     | > postnet_loss: 0.29215431213378906  (0.3044768537199775)
     | > stopnet_loss: 0.002927350113168359  (0.005036644475144703)
     | > loss: 0.18366514146327972  (0.19196008700270986)
     | > align_error: 0.5512273013591766  (0.5796159083066986)

   --> STEP: 44
     | > decoder_loss: 0.44858816266059875  (0.44333898614753375)
     | > postnet_loss: 0.30254024267196655  (0.30443283983252273)
     | > stopnet_loss: 0.0026542835403233767  (0.004982499908444218)
     | > loss: 0.19043639302253723  (0.19192545759406957)
     | > align_error: 0.5505031943321228  (0.5789542557163674)

   --> STEP: 45
     | > decoder_loss: 0.4416918158531189  (0.44330238236321345)
     | > postnet_loss: 0.3018365800380707  (0.3043751451704238)
     | > stopnet_loss: 0.0032622739672660828  (0.004944272665306925)
     | > loss: 0.18914437294006348  (0.19186365571286942)
     | > align_error: 0.552029013633728  (0.5783559170034198)

   --> STEP: 46
     | > decoder_loss: 0.43219199776649475  (0.4430608522632848)
     | > postnet_loss: 0.29306963086128235  (0.3041293731202251)
     | > stopnet_loss: 0.0031939309556037188  (0.0049062217585742465)
     | > loss: 0.18450933694839478  (0.19170377921798956)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3602809761509751 (+0.00836417891762481)
     | > avg_decoder_loss: 0.4389806326591607 (-3.855788346496247e-06)
     | > avg_postnet_loss: 0.3007806954961836 (-0.0015596444859648506)
     | > avg_stopnet_loss: 0.004352075675728194 (-2.9404425400903975e-05)
     | > avg_loss: 0.18929240942904443 (-0.00042027776891534474)
     | > avg_align_error: 0.5712515129284426 (+0.00012926260630297115)


 > EPOCH: 132/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 16:29:46)

   --> TIME: 2025-12-28 16:30:12 -- STEP: 18/150 -- GLOBAL_STEP: 19950
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.471168577671051  (0.4651895546250873)
     | > postnet_loss: 0.39699888229370117  (0.39481164183881545)
     | > stopnet_loss: 0.008018308319151402  (0.010691056079748604)
     | > loss: 0.22506017982959747  (0.22569135410918129)
     | > align_error: 0.7029665112495422  (0.6827586508459516)
     | > grad_norm: tensor(0.2620, device='cuda:0')  (tensor(0.2744, device='cuda:0'))
     | > step_time: 0.6895  (0.5980919731987847)
     | > loader_time: 0.9163  (0.781572077009413)


   --> TIME: 2025-12-28 16:31:02 -- STEP: 43/150 -- GLOBAL_STEP: 19975
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4845442771911621  (0.4734724801640178)
     | > postnet_loss: 0.4000707268714905  (0.39760527638501897)
     | > stopnet_loss: 0.005211218725889921  (0.007992571858732506)
     | > loss: 0.22636497020721436  (0.2257620116998983)
     | > align_error: 0.6085659861564636  (0.6512255024078278)
     | > grad_norm: tensor(0.1691, device='cuda:0')  (tensor(0.2289, device='cuda:0'))
     | > step_time: 1.1318  (0.8329793741536695)
     | > loader_time: 1.1223  (0.8983058818550997)


   --> TIME: 2025-12-28 16:32:07 -- STEP: 68/150 -- GLOBAL_STEP: 20000
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.49131259322166443  (0.47728987564058867)
     | > postnet_loss: 0.4023800790309906  (0.39776014361311407)
     | > stopnet_loss: 0.003965538926422596  (0.0066417313988923156)
     | > loss: 0.22738870978355408  (0.22540423712309668)
     | > align_error: 0.6148839592933655  (0.6387277499717823)
     | > grad_norm: tensor(0.1375, device='cuda:0')  (tensor(0.2140, device='cuda:0'))
     | > step_time: 1.5175  (1.024944091544432)
     | > loader_time: 1.3789  (1.0200859273181242)


 > CHECKPOINT : train_data\run-December-27-2025_08+25PM-0000000\checkpoint_20000.pth

warning: audio amplitude out of range, auto clipped.

   --> TIME: 2025-12-28 16:33:34 -- STEP: 93/150 -- GLOBAL_STEP: 20025
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48157498240470886  (0.47896665398792554)
     | > postnet_loss: 0.3957429826259613  (0.3971468370447876)
     | > stopnet_loss: 0.0037703404668718576  (0.005880151737621556)
     | > loss: 0.22309982776641846  (0.22490852494393626)
     | > align_error: 0.6027886271476746  (0.6334089809848414)
     | > grad_norm: tensor(0.1619, device='cuda:0')  (tensor(0.2102, device='cuda:0'))
     | > step_time: 1.6496  (1.199308431276711)
     | > loader_time: 1.8971  (1.1785329823852868)


   --> TIME: 2025-12-28 16:35:02 -- STEP: 118/150 -- GLOBAL_STEP: 20050
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4932836592197418  (0.4803202323994394)
     | > postnet_loss: 0.40044015645980835  (0.3968092915365251)
     | > stopnet_loss: 0.003105847630649805  (0.005358343857135309)
     | > loss: 0.2265368103981018  (0.22464072527521747)
     | > align_error: 0.6030293703079224  (0.6278038024902343)
     | > grad_norm: tensor(0.1448, device='cuda:0')  (tensor(0.2034, device='cuda:0'))
     | > step_time: 1.9277  (1.3345840947102696)
     | > loader_time: 1.7563  (1.2865166946993036)


   --> TIME: 2025-12-28 16:36:41 -- STEP: 143/150 -- GLOBAL_STEP: 20075
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4886631965637207  (0.4814773645851162)
     | > postnet_loss: 0.39499619603157043  (0.3964854758102576)
     | > stopnet_loss: 0.0031143780797719955  (0.004969940629911486)
     | > loss: 0.22402921319007874  (0.22446065109509689)
     | > align_error: 0.5731762051582336  (0.6240035141264642)
     | > grad_norm: tensor(0.2249, device='cuda:0')  (tensor(0.2003, device='cuda:0'))
     | > step_time: 2.2328  (1.461824203704621)
     | > loader_time: 1.9086  (1.3934429475477528)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4622465968132019  (0.4622465968132019)
     | > postnet_loss: 0.333829402923584  (0.333829402923584)
     | > stopnet_loss: 0.012143519707024097  (0.012143519707024097)
     | > loss: 0.2111625224351883  (0.2111625224351883)
     | > align_error: 0.7178003191947937  (0.7178003191947937)

   --> STEP: 1
     | > decoder_loss: 0.44428086280822754  (0.44428086280822754)
     | > postnet_loss: 0.32178452610969543  (0.32178452610969543)
     | > stopnet_loss: 0.009636876173317432  (0.009636876173317432)
     | > loss: 0.2011532187461853  (0.2011532187461853)
     | > align_error: 0.6577452421188354  (0.6577452421188354)

   --> STEP: 2
     | > decoder_loss: 0.4385986626148224  (0.44143976271152496)
     | > postnet_loss: 0.31253257393836975  (0.3171585500240326)
     | > stopnet_loss: 0.011001890525221825  (0.010319383349269629)
     | > loss: 0.1987846940755844  (0.19996895641088486)
     | > align_error: 0.6544137597084045  (0.65607950091362)

   --> STEP: 3
     | > decoder_loss: 0.44232770800590515  (0.44173574447631836)
     | > postnet_loss: 0.31169605255126953  (0.3153377175331116)
     | > stopnet_loss: 0.0082828588783741  (0.009640541858971119)
     | > loss: 0.19678880274295807  (0.19890890518824259)
     | > align_error: 0.7338642179965973  (0.6820077399412791)

   --> STEP: 4
     | > decoder_loss: 0.44669046998023987  (0.44297442585229874)
     | > postnet_loss: 0.3197305500507355  (0.31643592566251755)
     | > stopnet_loss: 0.008149441331624985  (0.009267766727134585)
     | > loss: 0.19975470006465912  (0.19912035390734673)
     | > align_error: 0.6019909083843231  (0.6620035320520401)

   --> STEP: 5
     | > decoder_loss: 0.42864665389060974  (0.4401088714599609)
     | > postnet_loss: 0.302145779132843  (0.3135778963565826)
     | > stopnet_loss: 0.008161756210029125  (0.009046564623713494)
     | > loss: 0.190859854221344  (0.19746825397014617)
     | > align_error: 0.6409279704093933  (0.6577884197235108)

   --> STEP: 6
     | > decoder_loss: 0.446103572845459  (0.44110798835754395)
     | > postnet_loss: 0.3144643008708954  (0.31372563044230145)
     | > stopnet_loss: 0.007282290607690811  (0.008752518954376379)
     | > loss: 0.1974242627620697  (0.19746092210213342)
     | > align_error: 0.5922196507453918  (0.646860291560491)

   --> STEP: 7
     | > decoder_loss: 0.45812830328941345  (0.4435394619192396)
     | > postnet_loss: 0.3150286078453064  (0.31391177007130217)
     | > stopnet_loss: 0.00621004356071353  (0.008389308183853115)
     | > loss: 0.19949926435947418  (0.19775211385318212)
     | > align_error: 0.5772850513458252  (0.6369209715298244)

   --> STEP: 8
     | > decoder_loss: 0.45259547233581543  (0.44467146322131157)
     | > postnet_loss: 0.315428763628006  (0.3141013942658901)
     | > stopnet_loss: 0.007373837288469076  (0.00826237432193011)
     | > loss: 0.19937989115715027  (0.19795558601617813)
     | > align_error: 0.5738207399845123  (0.6290334425866604)

   --> STEP: 9
     | > decoder_loss: 0.45152342319488525  (0.4454327921072642)
     | > postnet_loss: 0.3161623775959015  (0.31433039241366917)
     | > stopnet_loss: 0.006583865731954575  (0.008075873367488384)
     | > loss: 0.19850531220436096  (0.198016666703754)
     | > align_error: 0.5896270871162415  (0.6246549586455027)

   --> STEP: 10
     | > decoder_loss: 0.4748876392841339  (0.4483782768249512)
     | > postnet_loss: 0.329060822725296  (0.31580343544483186)
     | > stopnet_loss: 0.00555055495351553  (0.007823341526091099)
     | > loss: 0.206537663936615  (0.1988687664270401)
     | > align_error: 0.5824574530124664  (0.6204352080821991)

   --> STEP: 11
     | > decoder_loss: 0.46047478914260864  (0.44947795976292004)
     | > postnet_loss: 0.3188425600528717  (0.3160797195001082)
     | > stopnet_loss: 0.005899702664464712  (0.007648465265943246)
     | > loss: 0.20072904229164124  (0.1990378824147311)
     | > align_error: 0.5932976305484772  (0.6179681555791334)

   --> STEP: 12
     | > decoder_loss: 0.4571482539176941  (0.45011715094248456)
     | > postnet_loss: 0.3124982714653015  (0.31578126549720764)
     | > stopnet_loss: 0.007895154878497124  (0.007669022733656068)
     | > loss: 0.20030678808689117  (0.19914362455407777)
     | > align_error: 0.5857799351215363  (0.6152858038743337)

   --> STEP: 13
     | > decoder_loss: 0.44594502449035645  (0.4497962181384747)
     | > postnet_loss: 0.3117739260196686  (0.31547300861432004)
     | > stopnet_loss: 0.005560714285820723  (0.007506845160745657)
     | > loss: 0.19499044120311737  (0.19882414891169622)
     | > align_error: 0.58445143699646  (0.6129139294991126)

   --> STEP: 14
     | > decoder_loss: 0.4587457776069641  (0.45043547238622395)
     | > postnet_loss: 0.3160151541233063  (0.3155117332935333)
     | > stopnet_loss: 0.004896844737231731  (0.007320416559066091)
     | > loss: 0.1985870897769928  (0.19880721611636026)
     | > align_error: 0.5530461072921753  (0.6086376564843314)

   --> STEP: 15
     | > decoder_loss: 0.45392584800720215  (0.45066816409428917)
     | > postnet_loss: 0.3144227862358093  (0.3154391368230184)
     | > stopnet_loss: 0.00499365059658885  (0.007165298828234275)
     | > loss: 0.1970808058977127  (0.19869212210178375)
     | > align_error: 0.5868119299411774  (0.6071826080481212)

   --> STEP: 16
     | > decoder_loss: 0.4535391330718994  (0.4508475996553898)
     | > postnet_loss: 0.3079846203327179  (0.3149732295423746)
     | > stopnet_loss: 0.005248372443020344  (0.0070454909291584045)
     | > loss: 0.1956292986869812  (0.1985006956383586)
     | > align_error: 0.6044244766235352  (0.6070102248340845)

   --> STEP: 17
     | > decoder_loss: 0.462772011756897  (0.4515490356613608)
     | > postnet_loss: 0.3180197775363922  (0.31515243824790506)
     | > stopnet_loss: 0.004791520535945892  (0.006912904435440022)
     | > loss: 0.1999894678592682  (0.1985882704748827)
     | > align_error: 0.5570665001869202  (0.604072358678369)

   --> STEP: 18
     | > decoder_loss: 0.4545357823371887  (0.45171496603224015)
     | > postnet_loss: 0.3088841140270233  (0.31480419801341164)
     | > stopnet_loss: 0.005257659591734409  (0.006820946388567488)
     | > loss: 0.19611263275146484  (0.1984507350458039)
     | > align_error: 0.6026598215103149  (0.6039938843912549)

   --> STEP: 19
     | > decoder_loss: 0.45531409978866577  (0.4519043941246836)
     | > postnet_loss: 0.31039562821388245  (0.3145721680239627)
     | > stopnet_loss: 0.004826619755476713  (0.0067159818289311305)
     | > loss: 0.19625405967235565  (0.19833512055246452)
     | > align_error: 0.5989498496055603  (0.6037284088762183)

   --> STEP: 20
     | > decoder_loss: 0.4483487606048584  (0.45172661244869233)
     | > postnet_loss: 0.3046809434890747  (0.3140776067972183)
     | > stopnet_loss: 0.0044908649288117886  (0.006604725983925164)
     | > loss: 0.1927482932806015  (0.19805577918887135)
     | > align_error: 0.6217708587646484  (0.6046305313706398)

   --> STEP: 21
     | > decoder_loss: 0.4471564292907715  (0.45150898467926753)
     | > postnet_loss: 0.30418628454208374  (0.31360659145173575)
     | > stopnet_loss: 0.00397309847176075  (0.00647941038810781)
     | > loss: 0.1918087750673294  (0.19775830280213125)
     | > align_error: 0.5586206316947937  (0.6024395837670281)

   --> STEP: 22
     | > decoder_loss: 0.44810277223587036  (0.4513541568409313)
     | > postnet_loss: 0.3065037727355957  (0.3132837360555476)
     | > stopnet_loss: 0.004860011860728264  (0.006405801364136013)
     | > loss: 0.19351164996623993  (0.19756527312777256)
     | > align_error: 0.6242132484912872  (0.603429295799949)

   --> STEP: 23
     | > decoder_loss: 0.4216046631336212  (0.45006070059278735)
     | > postnet_loss: 0.2943992614746094  (0.31246267194333294)
     | > stopnet_loss: 0.004461843986064196  (0.006321281478132891)
     | > loss: 0.18346281349658966  (0.19695212270902546)
     | > align_error: 0.5659402310848236  (0.6017993364645087)

   --> STEP: 24
     | > decoder_loss: 0.455148845911026  (0.45027270664771396)
     | > postnet_loss: 0.3099084496498108  (0.3123562460144362)
     | > stopnet_loss: 0.0043891542591154575  (0.006240776177340497)
     | > loss: 0.19565348327159882  (0.19689801273246602)
     | > align_error: 0.5783359408378601  (0.600821694980065)

   --> STEP: 25
     | > decoder_loss: 0.4542277455329895  (0.450430908203125)
     | > postnet_loss: 0.30691227316856384  (0.31213848710060127)
     | > stopnet_loss: 0.0036843789275735617  (0.00613852028734982)
     | > loss: 0.19396936893463135  (0.19678086698055264)
     | > align_error: 0.5561655461788177  (0.5990354490280151)

   --> STEP: 26
     | > decoder_loss: 0.4301934242248535  (0.44965254343472993)
     | > postnet_loss: 0.2959323227405548  (0.3115151730867533)
     | > stopnet_loss: 0.004331822507083416  (0.0060690319111857275)
     | > loss: 0.18586325645446777  (0.19636095888339553)
     | > align_error: 0.5453066229820251  (0.5969689557185539)

   --> STEP: 27
     | > decoder_loss: 0.4273689389228821  (0.44882722474910597)
     | > postnet_loss: 0.29140347242355347  (0.3107702952844126)
     | > stopnet_loss: 0.003903113305568695  (0.005988812703570282)
     | > loss: 0.18359622359275818  (0.19588819090966822)
     | > align_error: 0.5397263169288635  (0.5948488579856025)

   --> STEP: 28
     | > decoder_loss: 0.43253591656684875  (0.4482453923140253)
     | > postnet_loss: 0.2956298589706421  (0.31022956541606367)
     | > stopnet_loss: 0.003921816125512123  (0.005914991397211062)
     | > loss: 0.18596325814723969  (0.19553372902529578)
     | > align_error: 0.5650725364685059  (0.5937854179314205)

   --> STEP: 29
     | > decoder_loss: 0.42826831340789795  (0.44755652752415886)
     | > postnet_loss: 0.2926044762134552  (0.309621803719422)
     | > stopnet_loss: 0.0035673840902745724  (0.005834039421109804)
     | > loss: 0.1837855726480484  (0.19512862018470103)
     | > align_error: 0.5391401648521423  (0.5919010988597212)

   --> STEP: 30
     | > decoder_loss: 0.42947375774383545  (0.44695376853148144)
     | > postnet_loss: 0.29338353872299194  (0.30908052821954096)
     | > stopnet_loss: 0.0028418314177542925  (0.0057342991543312865)
     | > loss: 0.18355615437030792  (0.19474287132422127)
     | > align_error: 0.5322238206863403  (0.5899118562539418)

   --> STEP: 31
     | > decoder_loss: 0.4244428873062134  (0.44622761107260184)
     | > postnet_loss: 0.2917381525039673  (0.30852109674484507)
     | > stopnet_loss: 0.00371584203094244  (0.005669187634221969)
     | > loss: 0.18276110291481018  (0.19435636266585316)
     | > align_error: 0.5539329051971436  (0.588751244929529)

   --> STEP: 32
     | > decoder_loss: 0.43742093443870544  (0.44595240242779255)
     | > postnet_loss: 0.2983427345752716  (0.3082030229270459)
     | > stopnet_loss: 0.003835042705759406  (0.005611870605207514)
     | > loss: 0.18777595460414886  (0.1941507249139249)
     | > align_error: 0.5295354127883911  (0.5869007501751184)

   --> STEP: 33
     | > decoder_loss: 0.43241259455680847  (0.44554210521958093)
     | > postnet_loss: 0.29520201683044434  (0.3078090530453307)
     | > stopnet_loss: 0.004001278430223465  (0.005563064781723149)
     | > loss: 0.18590493500232697  (0.19390085249236133)
     | > align_error: 0.5448334813117981  (0.5856259844519875)

   --> STEP: 34
     | > decoder_loss: 0.4375338554382324  (0.44530656846130595)
     | > postnet_loss: 0.2962055802345276  (0.30746777443324824)
     | > stopnet_loss: 0.0032757658045738935  (0.0054957912823952295)
     | > loss: 0.18671062588691711  (0.19368937523926003)
     | > align_error: 0.5622546076774597  (0.5849385910174426)

   --> STEP: 35
     | > decoder_loss: 0.435808926820755  (0.4450352072715759)
     | > postnet_loss: 0.29591765999794006  (0.307137771163668)
     | > stopnet_loss: 0.003508742665871978  (0.00543901846478028)
     | > loss: 0.1864403933286667  (0.19348226147038594)
     | > align_error: 0.5315312147140503  (0.5834126659802028)

   --> STEP: 36
     | > decoder_loss: 0.44194650650024414  (0.4449494100279278)
     | > postnet_loss: 0.3004645109176636  (0.3069524028235013)
     | > stopnet_loss: 0.0036531961522996426  (0.005389412289433595)
     | > loss: 0.189255952835083  (0.1933648640082942)
     | > align_error: 0.6325413882732391  (0.584777352710565)

   --> STEP: 37
     | > decoder_loss: 0.435359388589859  (0.44469022025933136)
     | > postnet_loss: 0.2972484529018402  (0.30669013390669964)
     | > stopnet_loss: 0.003561713732779026  (0.005340015031145634)
     | > loss: 0.18671368062496185  (0.19318510229523114)
     | > align_error: 0.5173714458942413  (0.5829555714452589)

   --> STEP: 38
     | > decoder_loss: 0.4225943684577942  (0.4441087504750804)
     | > postnet_loss: 0.289984792470932  (0.30625051965838995)
     | > stopnet_loss: 0.003129338612779975  (0.005281839335925485)
     | > loss: 0.18127411603927612  (0.19287165528849548)
     | > align_error: 0.5502139925956726  (0.5820939509492171)

   --> STEP: 39
     | > decoder_loss: 0.43840348720550537  (0.4439624616732964)
     | > postnet_loss: 0.30057740211486816  (0.30610505510599195)
     | > stopnet_loss: 0.0034559816122055054  (0.005235022471214716)
     | > loss: 0.1882012039422989  (0.19275190012577248)
     | > align_error: 0.5443885326385498  (0.5811271453515078)

   --> STEP: 40
     | > decoder_loss: 0.4351944327354431  (0.44374326094985006)
     | > postnet_loss: 0.2989139258861542  (0.305925276875496)
     | > stopnet_loss: 0.0030279606580734253  (0.005179845925886184)
     | > loss: 0.18655504286289215  (0.19259697869420048)
     | > align_error: 0.5822872519493103  (0.5811561480164529)

   --> STEP: 41
     | > decoder_loss: 0.4250715672969818  (0.443287853787585)
     | > postnet_loss: 0.29070547223091125  (0.3055540621280671)
     | > stopnet_loss: 0.0037316030357033014  (0.00514452292856465)
     | > loss: 0.18267586827278137  (0.19235500039123904)
     | > align_error: 0.5013992786407471  (0.5792108585194844)

   --> STEP: 42
     | > decoder_loss: 0.4315873384475708  (0.44300927008901325)
     | > postnet_loss: 0.29392480850219727  (0.305277175136975)
     | > stopnet_loss: 0.003288694191724062  (0.005100336530068446)
     | > loss: 0.1846667379140854  (0.19217194652273537)
     | > align_error: 0.5779845118522644  (0.5791816597893125)

   --> STEP: 43
     | > decoder_loss: 0.4290494918823242  (0.4426846240842065)
     | > postnet_loss: 0.2919062376022339  (0.30496622310128335)
     | > stopnet_loss: 0.002915819874033332  (0.005049533817137397)
     | > loss: 0.18315474689006805  (0.1919622442056966)
     | > align_error: 0.5502934157848358  (0.5785098401613014)

   --> STEP: 44
     | > decoder_loss: 0.4480315148830414  (0.44280614432963455)
     | > postnet_loss: 0.303152471780777  (0.3049250014803628)
     | > stopnet_loss: 0.0026377555914223194  (0.004994720675643873)
     | > loss: 0.19043375551700592  (0.19192750582640816)
     | > align_error: 0.5491424202919006  (0.5778423988006332)

   --> STEP: 45
     | > decoder_loss: 0.44016408920288086  (0.4427474319934845)
     | > postnet_loss: 0.30171865224838257  (0.3048537492752077)
     | > stopnet_loss: 0.003270647721365094  (0.0049564079433265665)
     | > loss: 0.18874132633209229  (0.1918567018376456)
     | > align_error: 0.5511535406112671  (0.5772493130630917)

   --> STEP: 46
     | > decoder_loss: 0.43123456835746765  (0.44249715234922327)
     | > postnet_loss: 0.2933817505836487  (0.30460435799930424)
     | > stopnet_loss: 0.003180491039529443  (0.004917801054113585)
     | > loss: 0.18433456122875214  (0.19169317704180008)
     | > align_error: 0.5312545299530029  (0.576249426473742)

   --> STEP: 47
     | > decoder_loss: 0.42941808700561523  (0.4422188743631891)
     | > postnet_loss: 0.29522427916526794  (0.30440478185389924)
     | > stopnet_loss: 0.003933899104595184  (0.004896866970081279)
     | > loss: 0.18509450554847717  (0.1915527797759847)
     | > align_error: 0.5650308728218079  (0.5760107338428498)

   --> STEP: 48
     | > decoder_loss: 0.4284849464893341  (0.44193275086581707)
     | > postnet_loss: 0.2922288477420807  (0.304151116559903)
     | > stopnet_loss: 0.003270092885941267  (0.004862975843328361)
     | > loss: 0.18344853818416595  (0.19138394140948847)
     | > align_error: 0.5390688478946686  (0.5752411112189294)

   --> STEP: 49
     | > decoder_loss: 0.42073893547058105  (0.44150022402101635)
     | > postnet_loss: 0.28839796781539917  (0.3038296237283825)
     | > stopnet_loss: 0.0030155580025166273  (0.004825273438413836)
     | > loss: 0.1802997887134552  (0.19115773421161025)
     | > align_error: 0.5709275305271149  (0.5751530789599129)

   --> STEP: 50
     | > decoder_loss: 0.4337697923183441  (0.4413456153869629)
     | > postnet_loss: 0.29650893807411194  (0.30368321001529713)
     | > stopnet_loss: 0.0034573848824948072  (0.004797915667295456)
     | > loss: 0.18602706491947174  (0.19105512082576748)
     | > align_error: 0.5543118417263031  (0.5747362542152407)

   --> STEP: 51
     | > decoder_loss: 0.44507312774658203  (0.44141870386460247)
     | > postnet_loss: 0.30290690064430237  (0.3036679882629247)
     | > stopnet_loss: 0.0026582754217088223  (0.004755961936989836)
     | > loss: 0.18965327739715576  (0.19102763369971626)
     | > align_error: 0.5253459811210632  (0.5737678174879038)

   --> STEP: 52
     | > decoder_loss: 0.4269647002220154  (0.4411407422560912)
     | > postnet_loss: 0.29193931818008423  (0.30344243691517775)
     | > stopnet_loss: 0.003705915529280901  (0.004735768736841587)
     | > loss: 0.18343192338943481  (0.19088156234759548)
     | > align_error: 0.5209352970123291  (0.5727518074787581)

   --> STEP: 53
     | > decoder_loss: 0.42067697644233704  (0.44075463346715243)
     | > postnet_loss: 0.28926488757133484  (0.3031749359841618)
     | > stopnet_loss: 0.003958794753998518  (0.00472110885037285)
     | > loss: 0.18144425749778748  (0.19070349999193872)
     | > align_error: 0.5340239703655243  (0.5720210935709612)

   --> STEP: 54

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.37208458510312165 (+0.01180360895214655)
     | > avg_decoder_loss: 0.4386197102792335 (-0.00036092237992718657)
     | > avg_postnet_loss: 0.30140229111368017 (+0.0006215956174965842)
     | > avg_stopnet_loss: 0.0043620169903575015 (+9.941314629307273e-06)
     | > avg_loss: 0.1893675164742903 (+7.510704524585354e-05)
     | > avg_align_error: 0.5700907657543818 (-0.0011607471740607833)


 > EPOCH: 133/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 16:39:12)

   --> TIME: 2025-12-28 16:39:36 -- STEP: 17/150 -- GLOBAL_STEP: 20100
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4658324122428894  (0.46603621630107656)
     | > postnet_loss: 0.3927805721759796  (0.3954085795318379)
     | > stopnet_loss: 0.007569203618913889  (0.010762142921414445)
     | > loss: 0.2222224622964859  (0.22612334261922276)
     | > align_error: 0.6930106580257416  (0.6814032775514266)
     | > grad_norm: tensor(0.1812, device='cuda:0')  (tensor(0.3050, device='cuda:0'))
     | > step_time: 0.7181  (0.5963850021362305)
     | > loader_time: 0.827  (0.7624299946953269)


   --> TIME: 2025-12-28 16:40:26 -- STEP: 42/150 -- GLOBAL_STEP: 20125
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4807800054550171  (0.4735712224528903)
     | > postnet_loss: 0.3975849747657776  (0.3977792568150021)
     | > stopnet_loss: 0.005513553507626057  (0.008007996416251575)
     | > loss: 0.22510479390621185  (0.22584561648822965)
     | > align_error: 0.6002990007400513  (0.6522175584520613)
     | > grad_norm: tensor(0.2040, device='cuda:0')  (tensor(0.2805, device='cuda:0'))
     | > step_time: 1.2119  (0.8329944213231405)
     | > loader_time: 1.1069  (0.9059167362394787)


   --> TIME: 2025-12-28 16:41:30 -- STEP: 67/150 -- GLOBAL_STEP: 20150
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48919937014579773  (0.47760307299557014)
     | > postnet_loss: 0.40066906809806824  (0.39809719795611365)
     | > stopnet_loss: 0.004216764587908983  (0.006680431278811684)
     | > loss: 0.2266838699579239  (0.22560549938856667)
     | > align_error: 0.6163073182106018  (0.6390060987045516)
     | > grad_norm: tensor(0.1710, device='cuda:0')  (tensor(0.2533, device='cuda:0'))
     | > step_time: 0.7085  (1.0230740255384303)
     | > loader_time: 1.0296  (1.0211357821279496)


   --> TIME: 2025-12-28 16:42:44 -- STEP: 92/150 -- GLOBAL_STEP: 20175
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4800873100757599  (0.47916482518548553)
     | > postnet_loss: 0.3925829827785492  (0.39738348255986755)
     | > stopnet_loss: 0.0037496185395866632  (0.005919360834092874)
     | > loss: 0.22191719710826874  (0.22505643834238467)
     | > align_error: 0.6602301597595215  (0.6336564360105471)
     | > grad_norm: tensor(0.2010, device='cuda:0')  (tensor(0.2378, device='cuda:0'))
     | > step_time: 1.649  (1.1661264689072321)
     | > loader_time: 1.6149  (1.1311602100082065)


   --> TIME: 2025-12-28 16:44:18 -- STEP: 117/150 -- GLOBAL_STEP: 20200
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48404744267463684  (0.4804197050567366)
     | > postnet_loss: 0.39338043332099915  (0.396996297642716)
     | > stopnet_loss: 0.003194322343915701  (0.0053916763629700635)
     | > loss: 0.22255128622055054  (0.22474567770448506)
     | > align_error: 0.6219037473201752  (0.6280224947338429)
     | > grad_norm: tensor(0.1532, device='cuda:0')  (tensor(0.2279, device='cuda:0'))
     | > step_time: 1.9707  (1.3046855865380702)
     | > loader_time: 2.1161  (1.3047402740543728)


   --> TIME: 2025-12-28 16:46:11 -- STEP: 142/150 -- GLOBAL_STEP: 20225
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49250707030296326  (0.48156431988931037)
     | > postnet_loss: 0.3988187313079834  (0.3966410942900349)
     | > stopnet_loss: 0.0030449607875198126  (0.004997998426838869)
     | > loss: 0.22587642073631287  (0.22454935270296017)
     | > align_error: 0.5910881161689758  (0.6243778175451384)
     | > grad_norm: tensor(0.1407, device='cuda:0')  (tensor(0.2197, device='cuda:0'))
     | > step_time: 2.4146  (1.4532485612681216)
     | > loader_time: 2.4188  (1.4870547089778203)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4601568281650543  (0.4601568281650543)
     | > postnet_loss: 0.3346678614616394  (0.3346678614616394)
     | > stopnet_loss: 0.012190563604235649  (0.012190563604235649)
     | > loss: 0.21089674532413483  (0.21089674532413483)
     | > align_error: 0.7184576988220215  (0.7184576988220215)

   --> STEP: 1
     | > decoder_loss: 0.44126299023628235  (0.44126299023628235)
     | > postnet_loss: 0.3223017454147339  (0.3223017454147339)
     | > stopnet_loss: 0.009671138599514961  (0.009671138599514961)
     | > loss: 0.20056231319904327  (0.20056231319904327)
     | > align_error: 0.6589144766330719  (0.6589144766330719)

   --> STEP: 2
     | > decoder_loss: 0.4373486340045929  (0.4393058121204376)
     | > postnet_loss: 0.3130852282047272  (0.31769348680973053)
     | > stopnet_loss: 0.011040897108614445  (0.010356017854064703)
     | > loss: 0.1986493617296219  (0.19960583746433258)
     | > align_error: 0.6552519202232361  (0.657083198428154)

   --> STEP: 3
     | > decoder_loss: 0.4413573145866394  (0.4399896462758382)
     | > postnet_loss: 0.31287506222724915  (0.31608734528223675)
     | > stopnet_loss: 0.008272453211247921  (0.009661496306459108)
     | > loss: 0.19683055579662323  (0.19868074357509613)
     | > align_error: 0.7345434129238129  (0.6829032699267069)

   --> STEP: 4
     | > decoder_loss: 0.4452529549598694  (0.441305473446846)
     | > postnet_loss: 0.3200092315673828  (0.31706781685352325)
     | > stopnet_loss: 0.008159696124494076  (0.00928604626096785)
     | > loss: 0.1994752436876297  (0.19887936860322952)
     | > align_error: 0.6029771566390991  (0.662921741604805)

   --> STEP: 5
     | > decoder_loss: 0.4265632927417755  (0.4383570373058319)
     | > postnet_loss: 0.30242112278938293  (0.31413847804069517)
     | > stopnet_loss: 0.008166475221514702  (0.00906213205307722)
     | > loss: 0.19041258096694946  (0.1971860110759735)
     | > align_error: 0.641392171382904  (0.6586158275604248)

   --> STEP: 6
     | > decoder_loss: 0.4453980028629303  (0.4395305315653483)
     | > postnet_loss: 0.31554320454597473  (0.31437259912490845)
     | > stopnet_loss: 0.007262626197189093  (0.0087622144104292)
     | > loss: 0.19749793410301208  (0.1972379982471466)
     | > align_error: 0.5932069718837738  (0.6477143516143163)

   --> STEP: 7
     | > decoder_loss: 0.4581143856048584  (0.44218536785670687)
     | > postnet_loss: 0.3157641589641571  (0.31457139338765827)
     | > stopnet_loss: 0.00618718471378088  (0.008394353025193726)
     | > loss: 0.19965682923793793  (0.19758354553154536)
     | > align_error: 0.5784876942634583  (0.6378248291356223)

   --> STEP: 8
     | > decoder_loss: 0.45252811908721924  (0.44347821176052094)
     | > postnet_loss: 0.31661030650138855  (0.31482625752687454)
     | > stopnet_loss: 0.007273281924426556  (0.008254219137597829)
     | > loss: 0.19955790042877197  (0.1978303398936987)
     | > align_error: 0.5743776559829712  (0.6298939324915409)

   --> STEP: 9
     | > decoder_loss: 0.44963330030441284  (0.44416211048762005)
     | > postnet_loss: 0.3156096637248993  (0.3149133026599884)
     | > stopnet_loss: 0.006689087953418493  (0.008080315672689013)
     | > loss: 0.19799982011318207  (0.19784917102919686)
     | > align_error: 0.5906825065612793  (0.6255371073881785)

   --> STEP: 10
     | > decoder_loss: 0.4720536470413208  (0.44695126414299013)
     | > postnet_loss: 0.32894256711006165  (0.31631622910499574)
     | > stopnet_loss: 0.005570505280047655  (0.007829334633424879)
     | > loss: 0.20581954717636108  (0.19864620864391327)
     | > align_error: 0.5830053091049194  (0.6212839275598526)

   --> STEP: 11
     | > decoder_loss: 0.4598067104816437  (0.44811994108286773)
     | > postnet_loss: 0.3185638189315796  (0.316520555452867)
     | > stopnet_loss: 0.005920906085520983  (0.007655841129069979)
     | > loss: 0.20051352679729462  (0.1988159648396752)
     | > align_error: 0.5943029820919037  (0.6188311143354936)

   --> STEP: 12
     | > decoder_loss: 0.45676273107528687  (0.448840173582236)
     | > postnet_loss: 0.31310945749282837  (0.31623629728953045)
     | > stopnet_loss: 0.007859492674469948  (0.007672812091186643)
     | > loss: 0.2003275454044342  (0.19894192988673845)
     | > align_error: 0.5869017243385315  (0.6161703318357468)

   --> STEP: 13
     | > decoder_loss: 0.44619348645210266  (0.4486365822645334)
     | > postnet_loss: 0.3129311203956604  (0.3159820529130789)
     | > stopnet_loss: 0.005565113388001919  (0.0075106814217108945)
     | > loss: 0.19534626603126526  (0.19866534035939437)
     | > align_error: 0.5853855013847351  (0.6138022679548997)

   --> STEP: 14
     | > decoder_loss: 0.4615032970905304  (0.4495556333235332)
     | > postnet_loss: 0.31854483485221863  (0.3161651087658746)
     | > stopnet_loss: 0.004881048575043678  (0.007322850504091808)
     | > loss: 0.19989308714866638  (0.19875303655862808)
     | > align_error: 0.5543009042739868  (0.6095521705491203)

   --> STEP: 15
     | > decoder_loss: 0.45373770594596863  (0.4498344381650289)
     | > postnet_loss: 0.3145473003387451  (0.3160572548707326)
     | > stopnet_loss: 0.004972928669303656  (0.007166189048439265)
     | > loss: 0.19704419374465942  (0.19863911370436352)
     | > align_error: 0.5878519415855408  (0.6081054886182149)

   --> STEP: 16
     | > decoder_loss: 0.45362043380737305  (0.4500710628926754)
     | > postnet_loss: 0.3082525134086609  (0.31556945852935314)
     | > stopnet_loss: 0.005254643969237804  (0.007046717480989173)
     | > loss: 0.19572287797927856  (0.1984568489715457)
     | > align_error: 0.6053445935249329  (0.6079329326748848)

   --> STEP: 17
     | > decoder_loss: 0.4633490741252899  (0.45085212237694683)
     | > postnet_loss: 0.31863996386528015  (0.31575007649029)
     | > stopnet_loss: 0.004814366810023785  (0.0069154027356382675)
     | > loss: 0.20031163096427917  (0.19856595379464767)
     | > align_error: 0.5583005547523499  (0.6050133810323828)

   --> STEP: 18
     | > decoder_loss: 0.4552341103553772  (0.4510955661535263)
     | > postnet_loss: 0.3094775974750519  (0.3154016054338879)
     | > stopnet_loss: 0.005265133921056986  (0.006823721134828197)
     | > loss: 0.19644306600093842  (0.19844801558388603)
     | > align_error: 0.6035519242286682  (0.6049321889877319)

   --> STEP: 19
     | > decoder_loss: 0.4543013274669647  (0.45126429043318095)
     | > postnet_loss: 0.3099583089351654  (0.31511511614448146)
     | > stopnet_loss: 0.00482815969735384  (0.006718691585487441)
     | > loss: 0.1958930641412735  (0.19831354445532748)
     | > align_error: 0.5997879505157471  (0.6046614395944696)

   --> STEP: 20
     | > decoder_loss: 0.44977256655693054  (0.45118970423936844)
     | > postnet_loss: 0.3054642677307129  (0.31463257372379305)
     | > stopnet_loss: 0.0044851843267679214  (0.006607016222551465)
     | > loss: 0.19329440593719482  (0.19806258752942085)
     | > align_error: 0.6225396990776062  (0.6055553525686264)

   --> STEP: 21
     | > decoder_loss: 0.4472483694553375  (0.45100202163060504)
     | > postnet_loss: 0.3049919903278351  (0.3141734983239855)
     | > stopnet_loss: 0.003975115716457367  (0.006481687627023175)
     | > loss: 0.19203519821166992  (0.19777556899048032)
     | > align_error: 0.5598013699054718  (0.6033765914894286)

   --> STEP: 22
     | > decoder_loss: 0.44913890957832336  (0.4509173347191377)
     | > postnet_loss: 0.307341992855072  (0.3138629753481258)
     | > stopnet_loss: 0.0048333932645618916  (0.006406765156002207)
     | > loss: 0.19395363330841064  (0.19760184464129535)
     | > align_error: 0.6251527369022369  (0.6043664162809198)

   --> STEP: 23
     | > decoder_loss: 0.4226822257041931  (0.4496897212837053)
     | > postnet_loss: 0.29550859332084656  (0.3130649587382441)
     | > stopnet_loss: 0.004476235248148441  (0.006322829073052044)
     | > loss: 0.1840239316225052  (0.19701150059700012)
     | > align_error: 0.5670187473297119  (0.602742604587389)

   --> STEP: 24
     | > decoder_loss: 0.4564615786075592  (0.44997188200553256)
     | > postnet_loss: 0.3105917274951935  (0.3129619074364503)
     | > stopnet_loss: 0.004369255155324936  (0.006241430159813414)
     | > loss: 0.1961325854063034  (0.1969748791307211)
     | > align_error: 0.5790697038173676  (0.6017562337219715)

   --> STEP: 25
     | > decoder_loss: 0.4550350606441498  (0.45017440915107726)
     | > postnet_loss: 0.30778768658638  (0.3127549386024475)
     | > stopnet_loss: 0.003687250427901745  (0.006139262970536947)
     | > loss: 0.19439293444156647  (0.1968716013431549)
     | > align_error: 0.5572179853916168  (0.5999747037887573)

   --> STEP: 26
     | > decoder_loss: 0.43180274963378906  (0.4494678068619508)
     | > postnet_loss: 0.2976217269897461  (0.31217289200195897)
     | > stopnet_loss: 0.004343415144830942  (0.0060701919003174854)
     | > loss: 0.1866995394229889  (0.1964803681923793)
     | > align_error: 0.5464150905609131  (0.5979147186646094)

   --> STEP: 27
     | > decoder_loss: 0.42823317646980286  (0.448681339069649)
     | > postnet_loss: 0.2920803427696228  (0.31142872351187245)
     | > stopnet_loss: 0.0038983274716883898  (0.005989752477034926)
     | > loss: 0.18397670984268188  (0.1960172697349831)
     | > align_error: 0.5405735969543457  (0.5957909734160812)

   --> STEP: 28
     | > decoder_loss: 0.433605432510376  (0.4481429138353893)
     | > postnet_loss: 0.29664376378059387  (0.31090068923575537)
     | > stopnet_loss: 0.0039400761015713215  (0.005916549749339798)
     | > loss: 0.1865023672580719  (0.19567745178937912)
     | > align_error: 0.566013902425766  (0.5947275065949985)

   --> STEP: 29
     | > decoder_loss: 0.42884743213653564  (0.44747755239749776)
     | > postnet_loss: 0.29346874356269836  (0.3102995876608224)
     | > stopnet_loss: 0.0035740912426263094  (0.005835775318073815)
     | > loss: 0.18415312469005585  (0.19528006119974728)
     | > align_error: 0.5400377213954926  (0.5928416519329466)

   --> STEP: 30
     | > decoder_loss: 0.43034207820892334  (0.4469063699245453)
     | > postnet_loss: 0.2946048974990845  (0.30977643132209776)
     | > stopnet_loss: 0.0027961048763245344  (0.0057344529700155055)
     | > loss: 0.1840328425168991  (0.194905153910319)
     | > align_error: 0.5329670608043671  (0.5908458322286606)

   --> STEP: 31
     | > decoder_loss: 0.42911669611930847  (0.44633250947921504)
     | > postnet_loss: 0.2940658628940582  (0.309269638792161)
     | > stopnet_loss: 0.0039185588248074055  (0.005675875739524922)
     | > loss: 0.1847141981124878  (0.19457641340071155)
     | > align_error: 0.5589008331298828  (0.5898153483867645)

   --> STEP: 32
     | > decoder_loss: 0.43812352418899536  (0.4460759786888957)
     | > postnet_loss: 0.2990778982639313  (0.30895114690065384)
     | > stopnet_loss: 0.0038433847948908806  (0.005618610397505108)
     | > loss: 0.1881437450647354  (0.1943753925152123)
     | > align_error: 0.5307429730892181  (0.5879693366587162)

   --> STEP: 33
     | > decoder_loss: 0.4333626329898834  (0.44569072578892566)
     | > postnet_loss: 0.2957369387149811  (0.3085507163495729)
     | > stopnet_loss: 0.00402676360681653  (0.0055703726159690905)
     | > loss: 0.18630166351795197  (0.19413073406074988)
     | > align_error: 0.5456488728523254  (0.5866868983615529)

   --> STEP: 34
     | > decoder_loss: 0.43932101130485535  (0.4455033812452765)
     | > postnet_loss: 0.29740840196609497  (0.30822300122064705)
     | > stopnet_loss: 0.003275513183325529  (0.005502876750303104)
     | > loss: 0.1874578595161438  (0.19393447304473205)
     | > align_error: 0.5632311105728149  (0.5859970222501194)

   --> STEP: 35
     | > decoder_loss: 0.43722766637802124  (0.4452669322490692)
     | > postnet_loss: 0.29707372188568115  (0.30790445038250513)
     | > stopnet_loss: 0.003503895364701748  (0.00544576299642878)
     | > loss: 0.18707923591136932  (0.19373860912663596)
     | > align_error: 0.5329358875751495  (0.5844809898308345)

   --> STEP: 36
     | > decoder_loss: 0.4428092837333679  (0.4451986642347442)
     | > postnet_loss: 0.30093905329704285  (0.3077109671301312)
     | > stopnet_loss: 0.0036678898613899946  (0.005396377631566591)
     | > loss: 0.1896049678325653  (0.19362378575735623)
     | > align_error: 0.6333441138267517  (0.5858382988307211)

   --> STEP: 37
     | > decoder_loss: 0.43574246764183044  (0.4449430913538546)
     | > postnet_loss: 0.2979764938354492  (0.30744787325730194)
     | > stopnet_loss: 0.003565658815205097  (0.005346898744637902)
     | > loss: 0.18699540197849274  (0.19344464024981936)
     | > align_error: 0.5182302594184875  (0.5840110545222824)

   --> STEP: 38
     | > decoder_loss: 0.42314305901527405  (0.44436940629231303)
     | > postnet_loss: 0.29052066802978516  (0.3070024204881568)
     | > stopnet_loss: 0.003128396114334464  (0.005288517096472022)
     | > loss: 0.18154431879520416  (0.19313147389575056)
     | > align_error: 0.5511046648025513  (0.5831450968980789)

   --> STEP: 39
     | > decoder_loss: 0.4385891854763031  (0.44422119550215894)
     | > postnet_loss: 0.3011791706085205  (0.3068531063886789)
     | > stopnet_loss: 0.003477848833426833  (0.005242089705111889)
     | > loss: 0.18841993808746338  (0.19301066528528166)
     | > align_error: 0.5454379022121429  (0.5821782457522857)

   --> STEP: 40
     | > decoder_loss: 0.4358423054218292  (0.4440117232501507)
     | > postnet_loss: 0.2996663451194763  (0.30667343735694885)
     | > stopnet_loss: 0.003027311060577631  (0.005186720238998533)
     | > loss: 0.18690447509288788  (0.1928580105304718)
     | > align_error: 0.583259105682373  (0.5822052672505379)

   --> STEP: 41
     | > decoder_loss: 0.4260249137878418  (0.44357302058033826)
     | > postnet_loss: 0.29158374667167664  (0.3063053961207227)
     | > stopnet_loss: 0.003715988015756011  (0.0051508487213584725)
     | > loss: 0.18311816453933716  (0.19262045331117583)
     | > align_error: 0.5023263096809387  (0.5802569999927427)

   --> STEP: 42
     | > decoder_loss: 0.43286553025245667  (0.4433180803344363)
     | > postnet_loss: 0.2949209213256836  (0.30603433719703127)
     | > stopnet_loss: 0.003287743544206023  (0.005106489074283414)
     | > loss: 0.18523435294628143  (0.19244459377867834)
     | > align_error: 0.5789569020271301  (0.5802260452792757)

   --> STEP: 43
     | > decoder_loss: 0.4298475384712219  (0.44300481191901275)
     | > postnet_loss: 0.2925025522708893  (0.30571964452433026)
     | > stopnet_loss: 0.0029138957615941763  (0.00505549853212785)
     | > loss: 0.18350142240524292  (0.19223661304906356)
     | > align_error: 0.551133394241333  (0.5795494719993236)

   --> STEP: 44
     | > decoder_loss: 0.4481264352798462  (0.4431212124499408)
     | > postnet_loss: 0.30365893244743347  (0.30567281015894626)
     | > stopnet_loss: 0.0026495936326682568  (0.00500081887532195)
     | > loss: 0.19059593975543976  (0.19219932501966303)
     | > align_error: 0.5501770675182343  (0.5788819173520262)

   --> STEP: 45
     | > decoder_loss: 0.4410739243030548  (0.44307571715778776)
     | > postnet_loss: 0.3024630844593048  (0.30560148292117645)
     | > stopnet_loss: 0.003260566620156169  (0.0049621466029849326)
     | > loss: 0.1891448199748993  (0.1921314471297794)
     | > align_error: 0.551845133304596  (0.57828109992875)

   --> STEP: 46
     | > decoder_loss: 0.43132954835891724  (0.44282036566216015)
     | > postnet_loss: 0.29400232434272766  (0.3053493272999058)
     | > stopnet_loss: 0.0031873045954853296  (0.004923563081082767)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3999364773432414 (+0.027851892240119747)
     | > avg_decoder_loss: 0.4388080704392809 (+0.00018836016004736278)
     | > avg_postnet_loss: 0.3022403653823968 (+0.0008380742687166265)
     | > avg_stopnet_loss: 0.004364428900633799 (+2.411910276297821e-06)
     | > avg_loss: 0.18962653839226926 (+0.0002590219179789688)
     | > avg_align_error: 0.5711389716827509 (+0.0010482059283690726)


 > EPOCH: 134/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 16:48:58)

   --> TIME: 2025-12-28 16:49:22 -- STEP: 16/150 -- GLOBAL_STEP: 20250
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47383394837379456  (0.46464292891323566)
     | > postnet_loss: 0.39855891466140747  (0.3944952990859747)
     | > stopnet_loss: 0.008441020734608173  (0.011016291799023747)
     | > loss: 0.2265392392873764  (0.22580085042864084)
     | > align_error: 0.676069438457489  (0.68064527772367)
     | > grad_norm: tensor(0.1849, device='cuda:0')  (tensor(0.2644, device='cuda:0'))
     | > step_time: 0.6966  (0.6455887705087662)
     | > loader_time: 1.2367  (0.8146440386772156)


   --> TIME: 2025-12-28 16:50:15 -- STEP: 41/150 -- GLOBAL_STEP: 20275
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48499244451522827  (0.4727195392294628)
     | > postnet_loss: 0.4025409519672394  (0.3972863489534797)
     | > stopnet_loss: 0.0050694989040493965  (0.008153804271232067)
     | > loss: 0.22695285081863403  (0.2256552773277934)
     | > align_error: 0.5936280786991119  (0.653135746717453)
     | > grad_norm: tensor(0.1893, device='cuda:0')  (tensor(0.2526, device='cuda:0'))
     | > step_time: 1.2017  (0.8358462612803389)
     | > loader_time: 0.9939  (1.0229330469922324)


   --> TIME: 2025-12-28 16:51:19 -- STEP: 66/150 -- GLOBAL_STEP: 20300
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.4840366840362549  (0.47695896616487793)
     | > postnet_loss: 0.3964952826499939  (0.3976497952685212)
     | > stopnet_loss: 0.003670949023216963  (0.006743938267005213)
     | > loss: 0.22380393743515015  (0.22539612966956515)
     | > align_error: 0.6139693856239319  (0.6390737931836734)
     | > grad_norm: tensor(0.2060, device='cuda:0')  (tensor(0.2267, device='cuda:0'))
     | > step_time: 1.4939  (1.0465932073015156)
     | > loader_time: 1.2295  (1.0796866091814912)


   --> TIME: 2025-12-28 16:52:35 -- STEP: 91/150 -- GLOBAL_STEP: 20325
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.483153760433197  (0.47897116594262173)
     | > postnet_loss: 0.3950301706790924  (0.39722813551242536)
     | > stopnet_loss: 0.003985229879617691  (0.005958598613698077)
     | > loss: 0.22353121638298035  (0.22500842498553977)
     | > align_error: 0.5943248271942139  (0.6328540572098323)
     | > grad_norm: tensor(0.2505, device='cuda:0')  (tensor(0.2139, device='cuda:0'))
     | > step_time: 1.5942  (1.19597397007785)
     | > loader_time: 1.5791  (1.1814872668339658)


   --> TIME: 2025-12-28 16:54:00 -- STEP: 116/150 -- GLOBAL_STEP: 20350
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4845580458641052  (0.4802220417507764)
     | > postnet_loss: 0.39402469992637634  (0.39679229850399084)
     | > stopnet_loss: 0.0030788688454777002  (0.005420997584286821)
     | > loss: 0.2227245420217514  (0.22467458286675915)
     | > align_error: 0.5884009003639221  (0.6275744438171386)
     | > grad_norm: tensor(0.1276, device='cuda:0')  (tensor(0.2134, device='cuda:0'))
     | > step_time: 1.892  (1.3199177610463109)
     | > loader_time: 1.8231  (1.2778859898961819)


   --> TIME: 2025-12-28 16:55:35 -- STEP: 141/150 -- GLOBAL_STEP: 20375
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4915766716003418  (0.4814172697828171)
     | > postnet_loss: 0.39674457907676697  (0.39646480269465884)
     | > stopnet_loss: 0.0030905678868293762  (0.005015459144487977)
     | > loss: 0.22517088055610657  (0.22448597732165182)
     | > align_error: 0.604266345500946  (0.6242040144213548)
     | > grad_norm: tensor(0.1652, device='cuda:0')  (tensor(0.2110, device='cuda:0'))
     | > step_time: 2.1675  (1.442996598304586)
     | > loader_time: 1.7984  (1.3661769417160787)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4606969654560089  (0.4606969654560089)
     | > postnet_loss: 0.3366398215293884  (0.3366398215293884)
     | > stopnet_loss: 0.01211292389780283  (0.01211292389780283)
     | > loss: 0.21144713461399078  (0.21144713461399078)
     | > align_error: 0.7186207175254822  (0.7186207175254822)

   --> STEP: 1
     | > decoder_loss: 0.4412805736064911  (0.4412805736064911)
     | > postnet_loss: 0.324069082736969  (0.324069082736969)
     | > stopnet_loss: 0.009639402851462364  (0.009639402851462364)
     | > loss: 0.20097680389881134  (0.20097680389881134)
     | > align_error: 0.6589862108230591  (0.6589862108230591)

   --> STEP: 2
     | > decoder_loss: 0.43732455372810364  (0.43930256366729736)
     | > postnet_loss: 0.314059317111969  (0.319064199924469)
     | > stopnet_loss: 0.011138254776597023  (0.010388828814029694)
     | > loss: 0.19898423552513123  (0.19998051971197128)
     | > align_error: 0.6551468968391418  (0.6570665538311005)

   --> STEP: 3
     | > decoder_loss: 0.44184958934783936  (0.440151572227478)
     | > postnet_loss: 0.31442636251449585  (0.3175182541211446)
     | > stopnet_loss: 0.008260674774646759  (0.009679444134235382)
     | > loss: 0.19732967019081116  (0.1990969032049179)
     | > align_error: 0.7350559532642365  (0.6830630203088125)

   --> STEP: 4
     | > decoder_loss: 0.4459473490715027  (0.4416005164384842)
     | > postnet_loss: 0.3218924105167389  (0.3186117932200432)
     | > stopnet_loss: 0.008178692311048508  (0.009304256178438663)
     | > loss: 0.2001386433839798  (0.19935733824968338)
     | > align_error: 0.6028872728347778  (0.6630190834403038)

   --> STEP: 5
     | > decoder_loss: 0.42694091796875  (0.43866859674453734)
     | > postnet_loss: 0.3037930428981781  (0.3156480431556702)
     | > stopnet_loss: 0.008185865357518196  (0.00908057801425457)
     | > loss: 0.19086936116218567  (0.19765974283218385)
     | > align_error: 0.6412485837936401  (0.658664983510971)

   --> STEP: 6
     | > decoder_loss: 0.44458600878715515  (0.43965483208497363)
     | > postnet_loss: 0.31639382243156433  (0.3157723397016525)
     | > stopnet_loss: 0.007244494277983904  (0.008774564058209458)
     | > loss: 0.19748945534229279  (0.19763136158386865)
     | > align_error: 0.5935389995574951  (0.6478106528520584)

   --> STEP: 7
     | > decoder_loss: 0.4548647999763489  (0.4418276846408844)
     | > postnet_loss: 0.3148195743560791  (0.3156362303665706)
     | > stopnet_loss: 0.006208574399352074  (0.008407994106944119)
     | > loss: 0.19862966239452362  (0.1977739759853908)
     | > align_error: 0.578568696975708  (0.6379189448697227)

   --> STEP: 8
     | > decoder_loss: 0.45025932788848877  (0.44288164004683495)
     | > postnet_loss: 0.31633955240249634  (0.3157241456210613)
     | > stopnet_loss: 0.007123307324945927  (0.008247408259194344)
     | > loss: 0.19877302646636963  (0.19789885729551315)
     | > align_error: 0.5741645693778992  (0.6299496479332447)

   --> STEP: 9
     | > decoder_loss: 0.4479234218597412  (0.44344183802604675)
     | > postnet_loss: 0.31562137603759766  (0.31571272677845424)
     | > stopnet_loss: 0.006700273137539625  (0.008075504356788265)
     | > loss: 0.19758647680282593  (0.19786414835188124)
     | > align_error: 0.5908383131027222  (0.6256039440631866)

   --> STEP: 10
     | > decoder_loss: 0.4716995656490326  (0.4462676107883453)
     | > postnet_loss: 0.32978594303131104  (0.3171200484037399)
     | > stopnet_loss: 0.005564832128584385  (0.007824437133967877)
     | > loss: 0.2059362232685089  (0.198671355843544)
     | > align_error: 0.5824830532073975  (0.6212918549776077)

   --> STEP: 11
     | > decoder_loss: 0.4612376391887665  (0.4476285224611109)
     | > postnet_loss: 0.3204696476459503  (0.31742455742575904)
     | > stopnet_loss: 0.005901997443288565  (0.007649669889360666)
     | > loss: 0.2013288140296936  (0.1989129429513758)
     | > align_error: 0.5943372845649719  (0.6188414394855499)

   --> STEP: 12
     | > decoder_loss: 0.4559643864631653  (0.44832317779461545)
     | > postnet_loss: 0.3134348690509796  (0.31709208339452744)
     | > stopnet_loss: 0.007924027740955353  (0.0076725330436602235)
     | > loss: 0.20027384161949158  (0.19902635117371878)
     | > align_error: 0.5869303643703461  (0.6161821832259496)

   --> STEP: 13
     | > decoder_loss: 0.446171373128891  (0.44815765435879046)
     | > postnet_loss: 0.31374719738960266  (0.31683478447107166)
     | > stopnet_loss: 0.0055815791711211205  (0.007511690438080292)
     | > loss: 0.1955612152814865  (0.19875980225893167)
     | > align_error: 0.5854135155677795  (0.6138153626368597)

   --> STEP: 14
     | > decoder_loss: 0.45894306898117065  (0.44892804111753193)
     | > postnet_loss: 0.31788572669029236  (0.3169098517724446)
     | > stopnet_loss: 0.004910449963063002  (0.007325887547007629)
     | > loss: 0.19911764562129974  (0.1987853624991008)
     | > align_error: 0.5546744763851166  (0.6095910136188779)

   --> STEP: 15
     | > decoder_loss: 0.454715371131897  (0.4493138631184896)
     | > postnet_loss: 0.31564176082611084  (0.31682531237602235)
     | > stopnet_loss: 0.004997516982257366  (0.007170662842690944)
     | > loss: 0.1975868046283722  (0.19870545864105224)
     | > align_error: 0.5881607532501221  (0.6081623295942943)

   --> STEP: 16
     | > decoder_loss: 0.45469987392425537  (0.44965048879384995)
     | > postnet_loss: 0.30945661664009094  (0.3163647688925266)
     | > stopnet_loss: 0.005290504079312086  (0.007053152919979766)
     | > loss: 0.19632962346076965  (0.19855696894228458)
     | > align_error: 0.6053561270236969  (0.6079869419336319)

   --> STEP: 17
     | > decoder_loss: 0.46237611770629883  (0.4503990552004646)
     | > postnet_loss: 0.318340003490448  (0.31648095916299257)
     | > stopnet_loss: 0.004837596323341131  (0.0069228260613539636)
     | > loss: 0.20001663267612457  (0.1986428315148634)
     | > align_error: 0.5582004189491272  (0.6050583229345434)

   --> STEP: 18
     | > decoder_loss: 0.4561558961868286  (0.45071887969970703)
     | > postnet_loss: 0.31061896681785583  (0.3161552929215961)
     | > stopnet_loss: 0.005283653270453215  (0.006831760906303923)
     | > loss: 0.1969773769378662  (0.19855030626058578)
     | > align_error: 0.6035129427909851  (0.6049724684821235)

   --> STEP: 19
     | > decoder_loss: 0.45482954382896423  (0.45093523044335215)
     | > postnet_loss: 0.3107471764087677  (0.3158706552103946)
     | > stopnet_loss: 0.004883644171059132  (0.006729228446554197)
     | > loss: 0.19627782702445984  (0.19843070209026337)
     | > align_error: 0.5998998284339905  (0.6047054874269586)

   --> STEP: 20
     | > decoder_loss: 0.4501487910747528  (0.45089590847492217)
     | > postnet_loss: 0.306267112493515  (0.3153904780745506)
     | > stopnet_loss: 0.004525095224380493  (0.006619021785445512)
     | > loss: 0.19362907111644745  (0.19819062054157258)
     | > align_error: 0.6224560737609863  (0.60559301674366)

   --> STEP: 21
     | > decoder_loss: 0.4470589756965637  (0.45071319739023846)
     | > postnet_loss: 0.3054751455783844  (0.314918319384257)
     | > stopnet_loss: 0.003984035458415747  (0.006493546246063141)
     | > loss: 0.1921175718307495  (0.1979014277458191)
     | > align_error: 0.5596393942832947  (0.6034047490074521)

   --> STEP: 22
     | > decoder_loss: 0.44983482360839844  (0.4506732713092457)
     | > postnet_loss: 0.30861127376556396  (0.31463163549249823)
     | > stopnet_loss: 0.004856704734265804  (0.006419144359163262)
     | > loss: 0.19446823000907898  (0.19774537330324)
     | > align_error: 0.6251281499862671  (0.604392176324671)

   --> STEP: 23
     | > decoder_loss: 0.4228276014328003  (0.44946259001026984)
     | > postnet_loss: 0.29610881209373474  (0.3138262953447259)
     | > stopnet_loss: 0.004476337227970362  (0.006334674483894006)
     | > loss: 0.18421044945716858  (0.1971568983534108)
     | > align_error: 0.5668050646781921  (0.602757954079172)

   --> STEP: 24
     | > decoder_loss: 0.4575473368167877  (0.4497994544605414)
     | > postnet_loss: 0.3119423985481262  (0.3137477996448676)
     | > stopnet_loss: 0.0043841078877449036  (0.006253400875721127)
     | > loss: 0.1967565417289734  (0.19714021682739258)
     | > align_error: 0.5792688131332397  (0.6017792398730915)

   --> STEP: 25
     | > decoder_loss: 0.4558408260345459  (0.4500411093235016)
     | > postnet_loss: 0.30870211124420166  (0.31354597210884094)
     | > stopnet_loss: 0.003711961442604661  (0.0061517432983964684)
     | > loss: 0.1948477029800415  (0.19704851627349854)
     | > align_error: 0.5570493042469025  (0.5999900424480439)

   --> STEP: 26
     | > decoder_loss: 0.43154680728912354  (0.44932979001448703)
     | > postnet_loss: 0.29810717701911926  (0.3129521722976978)
     | > stopnet_loss: 0.0043692076578736305  (0.006083184235299436)
     | > loss: 0.18678270280361176  (0.1966536772938875)
     | > align_error: 0.546318918466568  (0.5979257684487563)

   --> STEP: 27
     | > decoder_loss: 0.4291212260723114  (0.44858132468329537)
     | > postnet_loss: 0.29316064715385437  (0.31221915284792584)
     | > stopnet_loss: 0.003926447592675686  (0.006003305100387445)
     | > loss: 0.1844969093799591  (0.19620342663040868)
     | > align_error: 0.5405852496623993  (0.5958020455307431)

   --> STEP: 28
     | > decoder_loss: 0.4341205060482025  (0.44806486687489916)
     | > postnet_loss: 0.2975965142250061  (0.3116969157542501)
     | > stopnet_loss: 0.003938052337616682  (0.005929546073145632)
     | > loss: 0.18686729669570923  (0.19586999341845512)
     | > align_error: 0.5660900771617889  (0.5947409038032804)

   --> STEP: 29
     | > decoder_loss: 0.429716020822525  (0.44743214804550696)
     | > postnet_loss: 0.2944023311138153  (0.31110055076664894)
     | > stopnet_loss: 0.0036048528272658587  (0.0058493842370808125)
     | > loss: 0.18463444709777832  (0.19548256078670764)
     | > align_error: 0.5401198863983154  (0.5928574204444885)

   --> STEP: 30
     | > decoder_loss: 0.4299749433994293  (0.44685024122397105)
     | > postnet_loss: 0.29495877027511597  (0.31056249141693115)
     | > stopnet_loss: 0.002851225668564439  (0.005749445618130266)
     | > loss: 0.1840846687555313  (0.1951026310523351)
     | > align_error: 0.5331790745258331  (0.5908681422472)

   --> STEP: 31
     | > decoder_loss: 0.43000662326812744  (0.44630689870926643)
     | > postnet_loss: 0.2951936423778534  (0.31006672209308994)
     | > stopnet_loss: 0.003915514796972275  (0.005690286559383234)
     | > loss: 0.18521559238433838  (0.1947836943211094)
     | > align_error: 0.5585532188415527  (0.5898257253631469)

   --> STEP: 32
     | > decoder_loss: 0.43822699785232544  (0.446054401807487)
     | > postnet_loss: 0.299763023853302  (0.30974473152309656)
     | > stopnet_loss: 0.0038461305666714907  (0.005632656684610993)
     | > loss: 0.18834362924098969  (0.19458244228735566)
     | > align_error: 0.5306934714317322  (0.5879778424277902)

   --> STEP: 33
     | > decoder_loss: 0.43489760160446167  (0.44571631695284986)
     | > postnet_loss: 0.29709264636039734  (0.30936133500301477)
     | > stopnet_loss: 0.004027826711535454  (0.005584025473305674)
     | > loss: 0.18702538311481476  (0.19435344049424835)
     | > align_error: 0.5455594658851624  (0.5866924370780136)

   --> STEP: 34
     | > decoder_loss: 0.44024816155433655  (0.4455554888528936)
     | > postnet_loss: 0.2983209490776062  (0.30903661776991453)
     | > stopnet_loss: 0.003288141218945384  (0.005516499465824489)
     | > loss: 0.1879304200410843  (0.19416452812797882)
     | > align_error: 0.5631794333457947  (0.586000878144713)

   --> STEP: 35
     | > decoder_loss: 0.43780484795570374  (0.4453340419701168)
     | > postnet_loss: 0.29790928959846497  (0.3087186941078731)
     | > stopnet_loss: 0.003506828797981143  (0.005459080303886107)
     | > loss: 0.1874353587627411  (0.1939722661461149)
     | > align_error: 0.5325800776481628  (0.5844745695590973)

   --> STEP: 36
     | > decoder_loss: 0.44361576437950134  (0.4452863120370441)
     | > postnet_loss: 0.30200648307800293  (0.3085322438014878)
     | > stopnet_loss: 0.0036554790567606688  (0.005408980269243734)
     | > loss: 0.1900610476732254  (0.19386362118853462)
     | > align_error: 0.6333416998386383  (0.5858319898446401)

   --> STEP: 37
     | > decoder_loss: 0.43623441457748413  (0.4450416661597587)
     | > postnet_loss: 0.2988680303096771  (0.3082710488422497)
     | > stopnet_loss: 0.003579019336029887  (0.00535952186564336)
     | > loss: 0.18735462427139282  (0.1936877023529362)
     | > align_error: 0.5182021856307983  (0.58400415729832)

   --> STEP: 38
     | > decoder_loss: 0.4237305521965027  (0.444480847371252)
     | > postnet_loss: 0.2915503680706024  (0.3078310309272063)
     | > stopnet_loss: 0.00313925975933671  (0.005301093915477395)
     | > loss: 0.18195948004722595  (0.19337906492383858)
     | > align_error: 0.5509310364723206  (0.5831338120134253)

   --> STEP: 39
     | > decoder_loss: 0.43946829438209534  (0.44435232037153)
     | > postnet_loss: 0.30243948101997375  (0.3076927860577901)
     | > stopnet_loss: 0.0034644182305783033  (0.005253999667146649)
     | > loss: 0.1889413595199585  (0.19326527760579038)
     | > align_error: 0.5453770756721497  (0.5821656905687772)

   --> STEP: 40
     | > decoder_loss: 0.43638986349105835  (0.4441532589495182)
     | > postnet_loss: 0.3008137345314026  (0.3075208097696304)
     | > stopnet_loss: 0.0030314000323414803  (0.00519843467627652)
     | > loss: 0.18733230233192444  (0.19311695322394373)
     | > align_error: 0.5831820964813232  (0.5821911007165909)

   --> STEP: 41
     | > decoder_loss: 0.42652443051338196  (0.4437232875242466)
     | > postnet_loss: 0.29292911291122437  (0.30716491472430346)
     | > stopnet_loss: 0.0037188127171248198  (0.005162346335809405)
     | > loss: 0.18358220160007477  (0.1928843983062884)
     | > align_error: 0.5024341940879822  (0.5802458103110151)

   --> STEP: 42
     | > decoder_loss: 0.43181923031806946  (0.4434398575907662)
     | > postnet_loss: 0.29464858770370483  (0.3068669069380987)
     | > stopnet_loss: 0.003286626422777772  (0.0051176863378800804)
     | > loss: 0.1849035918712616  (0.1926943791054544)
     | > align_error: 0.578919380903244  (0.5802142286584491)

   --> STEP: 43
     | > decoder_loss: 0.43093931674957275  (0.4431491473386454)
     | > postnet_loss: 0.29375436902046204  (0.3065619641958281)
     | > stopnet_loss: 0.002925836481153965  (0.005066713085398078)
     | > loss: 0.1840992569923401  (0.1924944925446843)
     | > align_error: 0.5511918067932129  (0.5795392886150715)

   --> STEP: 44
     | > decoder_loss: 0.4485819637775421  (0.4432726204395294)
     | > postnet_loss: 0.30448561906814575  (0.3065147745338353)
     | > stopnet_loss: 0.0026557764504104853  (0.005011919070966542)
     | > loss: 0.19092267751693726  (0.19245876947587187)
     | > align_error: 0.550147533416748  (0.5788712941787459)

   --> STEP: 45
     | > decoder_loss: 0.4421100616455078  (0.44324678579966226)
     | > postnet_loss: 0.30383795499801636  (0.30645528965526153)
     | > stopnet_loss: 0.003308524377644062  (0.004974065855559376)
     | > loss: 0.18979552388191223  (0.19239958624045053)
     | > align_error: 0.5520209074020386  (0.5782746189170413)

   --> STEP: 46
     | > decoder_loss: 0.4321207106113434  (0.4430049145999162)
     | > postnet_loss: 0.2951405346393585  (0.3062093167201332)
     | > stopnet_loss: 0.0031984488014131784  (0.004935465484817067)
     | > loss: 0.1850137561559677  (0.19223902471687482)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.36512873389504175 (-0.034807743448199646)
     | > avg_decoder_loss: 0.4389952624386007 (+0.00018719199931982455)
     | > avg_postnet_loss: 0.30319164286960254 (+0.0009512774872057483)
     | > avg_stopnet_loss: 0.004376684714136927 (+1.2255813503127787e-05)
     | > avg_loss: 0.18992341219475775 (+0.0002968738024884954)
     | > avg_align_error: 0.5710949039820468 (-4.406770070408683e-05)


 > EPOCH: 135/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 16:58:14)

   --> TIME: 2025-12-28 16:58:37 -- STEP: 15/150 -- GLOBAL_STEP: 20400
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4640618562698364  (0.46281497875849403)
     | > postnet_loss: 0.3911881148815155  (0.39309810996055605)
     | > stopnet_loss: 0.008114566095173359  (0.011219619338711103)
     | > loss: 0.22192706167697906  (0.22519789238770802)
     | > align_error: 0.6613578200340271  (0.6806795457998912)
     | > grad_norm: tensor(0.2594, device='cuda:0')  (tensor(0.3017, device='cuda:0'))
     | > step_time: 0.7105  (0.5740764617919922)
     | > loader_time: 1.0265  (0.8324329535166423)


   --> TIME: 2025-12-28 16:59:24 -- STEP: 40/150 -- GLOBAL_STEP: 20425
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.48851722478866577  (0.47157041281461715)
     | > postnet_loss: 0.4029955565929413  (0.396379242837429)
     | > stopnet_loss: 0.005208320450037718  (0.00822696064133197)
     | > loss: 0.22808650135993958  (0.22521437369287015)
     | > align_error: 0.6198177337646484  (0.6544491030275821)
     | > grad_norm: tensor(0.2477, device='cuda:0')  (tensor(0.2788, device='cuda:0'))
     | > step_time: 1.1407  (0.7999462008476257)
     | > loader_time: 1.0181  (0.9114797830581665)


   --> TIME: 2025-12-28 17:00:26 -- STEP: 65/150 -- GLOBAL_STEP: 20450
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48762986063957214  (0.476083897627317)
     | > postnet_loss: 0.39920270442962646  (0.3969817908910604)
     | > stopnet_loss: 0.004174890462309122  (0.006803818172417009)
     | > loss: 0.22588303685188293  (0.225070240176641)
     | > align_error: 0.6619089841842651  (0.6395412234159615)
     | > grad_norm: tensor(0.2090, device='cuda:0')  (tensor(0.2513, device='cuda:0'))
     | > step_time: 1.4131  (0.999845079275278)
     | > loader_time: 1.2061  (0.9993239219372089)


   --> TIME: 2025-12-28 17:01:40 -- STEP: 90/150 -- GLOBAL_STEP: 20475
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48555588722229004  (0.4782638096147113)
     | > postnet_loss: 0.3958108425140381  (0.396698597073555)
     | > stopnet_loss: 0.0034740129485726357  (0.0059779039454749905)
     | > loss: 0.2238156944513321  (0.22471850514411926)
     | > align_error: 0.6652312278747559  (0.6337884836726718)
     | > grad_norm: tensor(0.2411, device='cuda:0')  (tensor(0.2363, device='cuda:0'))
     | > step_time: 1.6878  (1.1513534016079376)
     | > loader_time: 1.877  (1.1199978166156346)


   --> TIME: 2025-12-28 17:03:19 -- STEP: 115/150 -- GLOBAL_STEP: 20500
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4800439476966858  (0.47957262189491934)
     | > postnet_loss: 0.3912687599658966  (0.3963181322035582)
     | > stopnet_loss: 0.0035144498106092215  (0.005435549320005205)
     | > loss: 0.22134263813495636  (0.22440823796002762)
     | > align_error: 0.6594254374504089  (0.6282819512097735)
     | > grad_norm: tensor(0.2859, device='cuda:0')  (tensor(0.2224, device='cuda:0'))
     | > step_time: 1.9613  (1.2850958927817966)
     | > loader_time: 2.3432  (1.352598839220794)


   --> TIME: 2025-12-28 17:04:58 -- STEP: 140/150 -- GLOBAL_STEP: 20525
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49248671531677246  (0.4808583221265248)
     | > postnet_loss: 0.3976139724254608  (0.3960862655724798)
     | > stopnet_loss: 0.0029452042654156685  (0.005031395523941944)
     | > loss: 0.2254703789949417  (0.22426754268152374)
     | > align_error: 0.5921873152256012  (0.6246167097772872)
     | > grad_norm: tensor(0.2427, device='cuda:0')  (tensor(0.2152, device='cuda:0'))
     | > step_time: 2.2394  (1.4194968870707922)
     | > loader_time: 1.8466  (1.4535127980368483)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4603714346885681  (0.4603714346885681)
     | > postnet_loss: 0.33629605174064636  (0.33629605174064636)
     | > stopnet_loss: 0.012115651741623878  (0.012115651741623878)
     | > loss: 0.21128252148628235  (0.21128252148628235)
     | > align_error: 0.718532145023346  (0.718532145023346)

   --> STEP: 1
     | > decoder_loss: 0.4408992826938629  (0.4408992826938629)
     | > postnet_loss: 0.3238604664802551  (0.3238604664802551)
     | > stopnet_loss: 0.009677636437118053  (0.009677636437118053)
     | > loss: 0.20086757838726044  (0.20086757838726044)
     | > align_error: 0.658792644739151  (0.658792644739151)

   --> STEP: 2
     | > decoder_loss: 0.4373309314250946  (0.43911510705947876)
     | > postnet_loss: 0.3141557276248932  (0.31900809705257416)
     | > stopnet_loss: 0.011086523532867432  (0.010382079984992743)
     | > loss: 0.19895818829536438  (0.1999128833413124)
     | > align_error: 0.6551067531108856  (0.6569496989250183)

   --> STEP: 3
     | > decoder_loss: 0.4413062334060669  (0.4398454825083415)
     | > postnet_loss: 0.31424808502197266  (0.31742142637570697)
     | > stopnet_loss: 0.008264079689979553  (0.009676079886655012)
     | > loss: 0.19715265929698944  (0.19899280865987143)
     | > align_error: 0.7347113490104675  (0.6828702489535013)

   --> STEP: 4
     | > decoder_loss: 0.44595304131507874  (0.4413723722100258)
     | > postnet_loss: 0.3220551013946533  (0.3185798451304436)
     | > stopnet_loss: 0.008131570182740688  (0.009289952460676432)
     | > loss: 0.20013359189033508  (0.19927800446748734)
     | > align_error: 0.6029046773910522  (0.6628788560628891)

   --> STEP: 5
     | > decoder_loss: 0.4294954836368561  (0.43899699449539187)
     | > postnet_loss: 0.30498015880584717  (0.3158599078655243)
     | > stopnet_loss: 0.008109614253044128  (0.009053884819149972)
     | > loss: 0.19172851741313934  (0.19776810705661774)
     | > align_error: 0.6422377824783325  (0.6587506413459778)

   --> STEP: 6
     | > decoder_loss: 0.4453762173652649  (0.44006019830703735)
     | > postnet_loss: 0.3169715106487274  (0.31604517499605816)
     | > stopnet_loss: 0.0072190361097455025  (0.008748076700915893)
     | > loss: 0.1978059560060501  (0.19777441521485647)
     | > align_error: 0.5932955145835876  (0.6478414535522461)

   --> STEP: 7
     | > decoder_loss: 0.4566665589809418  (0.44243253554616657)
     | > postnet_loss: 0.3158299922943115  (0.3160144346100943)
     | > stopnet_loss: 0.006218204274773598  (0.008386666354324137)
     | > loss: 0.19934235513210297  (0.19799840663160598)
     | > align_error: 0.5785169303417206  (0.6379379502364567)

   --> STEP: 8
     | > decoder_loss: 0.45133745670318604  (0.443545650690794)
     | > postnet_loss: 0.31740665435791016  (0.3161884620785713)
     | > stopnet_loss: 0.007289515342563391  (0.008249522477854043)
     | > loss: 0.19947554171085358  (0.19818304851651192)
     | > align_error: 0.5742692351341248  (0.6299793608486652)

   --> STEP: 9
     | > decoder_loss: 0.44675591588020325  (0.4439023468229506)
     | > postnet_loss: 0.31520479917526245  (0.31607916620042587)
     | > stopnet_loss: 0.00671828119084239  (0.008079384557074971)
     | > loss: 0.1972084641456604  (0.19807476136419508)
     | > align_error: 0.5908355712890625  (0.6256300508975983)

   --> STEP: 10
     | > decoder_loss: 0.4720310568809509  (0.4467152178287506)
     | > postnet_loss: 0.33015358448028564  (0.3174866080284119)
     | > stopnet_loss: 0.005611463915556669  (0.007832592492923141)
     | > loss: 0.2061576247215271  (0.1988830476999283)
     | > align_error: 0.5822296738624573  (0.6212900131940842)

   --> STEP: 11
     | > decoder_loss: 0.460946261882782  (0.44800894910638983)
     | > postnet_loss: 0.3204703629016876  (0.31775785847143695)
     | > stopnet_loss: 0.005880821030586958  (0.007655158723619851)
     | > loss: 0.20123498141765594  (0.19909685985608536)
     | > align_error: 0.5944249629974365  (0.6188477359034799)

   --> STEP: 12
     | > decoder_loss: 0.4561827778816223  (0.44869010150432587)
     | > postnet_loss: 0.31380733847618103  (0.3174286484718323)
     | > stopnet_loss: 0.00793840829282999  (0.0076787628543873625)
     | > loss: 0.20043593645095825  (0.19920844957232475)
     | > align_error: 0.5871170163154602  (0.6162035092711449)

   --> STEP: 13
     | > decoder_loss: 0.4457358717918396  (0.44846285306490385)
     | > postnet_loss: 0.31359630823135376  (0.31713385306871855)
     | > stopnet_loss: 0.005601517390459776  (0.0075189747417775486)
     | > loss: 0.1954345554113388  (0.19891815002147967)
     | > align_error: 0.5851935744285583  (0.613818129667869)

   --> STEP: 14
     | > decoder_loss: 0.4578908681869507  (0.4491362827164786)
     | > postnet_loss: 0.31721368432044983  (0.3171395553009851)
     | > stopnet_loss: 0.004932098090648651  (0.007334197838125485)
     | > loss: 0.19870823621749878  (0.19890315617833818)
     | > align_error: 0.5543408393859863  (0.6095697517905917)

   --> STEP: 15
     | > decoder_loss: 0.4542047679424286  (0.44947418173154197)
     | > postnet_loss: 0.315412700176239  (0.31702443162600197)
     | > stopnet_loss: 0.005006727762520313  (0.007179033166418473)
     | > loss: 0.19741109013557434  (0.1988036851088206)
     | > align_error: 0.5880216360092163  (0.6081332107384999)

   --> STEP: 16
     | > decoder_loss: 0.4546736180782318  (0.44979914650321007)
     | > postnet_loss: 0.3094892203807831  (0.3165534809231758)
     | > stopnet_loss: 0.005256589036434889  (0.007058880408294499)
     | > loss: 0.1962973028421402  (0.19864703621715307)
     | > align_error: 0.6052506268024445  (0.6079530492424965)

   --> STEP: 17
     | > decoder_loss: 0.46216779947280884  (0.45052671432495117)
     | > postnet_loss: 0.3184741139411926  (0.31666645933600035)
     | > stopnet_loss: 0.004822247661650181  (0.006927313776138951)
     | > loss: 0.19998273253440857  (0.19872560658875635)
     | > align_error: 0.5580683350563049  (0.6050186542903676)

   --> STEP: 18
     | > decoder_loss: 0.4557887315750122  (0.45081904861662125)
     | > postnet_loss: 0.31037136912345886  (0.31631673210197025)
     | > stopnet_loss: 0.005269252695143223  (0.006835199271639188)
     | > loss: 0.1968092918395996  (0.19861914465824762)
     | > align_error: 0.6035848259925842  (0.6049389971627129)

   --> STEP: 19
     | > decoder_loss: 0.45344793796539307  (0.450957411213925)
     | > postnet_loss: 0.31006911396980286  (0.3159879100950141)
     | > stopnet_loss: 0.004736257717013359  (0.006724728663500987)
     | > loss: 0.1956155151128769  (0.1984610588927018)
     | > align_error: 0.5996809601783752  (0.6046622583740636)

   --> STEP: 20
     | > decoder_loss: 0.44985854625701904  (0.4509024679660797)
     | > postnet_loss: 0.3059350848197937  (0.31548526883125305)
     | > stopnet_loss: 0.004517226945608854  (0.00661435357760638)
     | > loss: 0.19346563518047333  (0.19821128770709037)
     | > align_error: 0.622407853603363  (0.6055495381355286)

   --> STEP: 21
     | > decoder_loss: 0.44710245728492737  (0.45072151507650104)
     | > postnet_loss: 0.3054932951927185  (0.3150094605627514)
     | > stopnet_loss: 0.003966381307691336  (0.006488259659991378)
     | > loss: 0.19211532175540924  (0.19792100361415318)
     | > align_error: 0.5595853328704834  (0.6033607664562407)

   --> STEP: 22
     | > decoder_loss: 0.44969791173934937  (0.450674987652085)
     | > postnet_loss: 0.30842435359954834  (0.3147101375189694)
     | > stopnet_loss: 0.004853847436606884  (0.006413968195292083)
     | > loss: 0.1943844109773636  (0.19776024940339001)
     | > align_error: 0.6251699328422546  (0.6043520922010596)

   --> STEP: 23
     | > decoder_loss: 0.42324572801589966  (0.44948241114616394)
     | > postnet_loss: 0.29625439643859863  (0.3139077139937359)
     | > stopnet_loss: 0.004474111367017031  (0.006329626594062733)
     | > loss: 0.1843491494655609  (0.19717715810174527)
     | > align_error: 0.5668641328811646  (0.6027221809262816)

   --> STEP: 24
     | > decoder_loss: 0.45720764994621277  (0.44980429609616596)
     | > postnet_loss: 0.3115285336971283  (0.31380858148137725)
     | > stopnet_loss: 0.004402906633913517  (0.006249346595723182)
     | > loss: 0.1965869516134262  (0.19715256616473198)
     | > align_error: 0.5791860222816467  (0.6017415076494218)

   --> STEP: 25
     | > decoder_loss: 0.4564500153064728  (0.45007012486457826)
     | > postnet_loss: 0.3089844882488251  (0.31361561775207514)
     | > stopnet_loss: 0.0037282765842974186  (0.006148503795266151)
     | > loss: 0.19508689641952515  (0.1970699393749237)
     | > align_error: 0.5575582981109619  (0.5999741792678834)

   --> STEP: 26
     | > decoder_loss: 0.4315476417541504  (0.44935772166802335)
     | > postnet_loss: 0.2980044484138489  (0.31301518816214335)
     | > stopnet_loss: 0.004339964594691992  (0.006078944595244069)
     | > loss: 0.18672798573970795  (0.1966721719274154)
     | > align_error: 0.5461642146110535  (0.5979045652426207)

   --> STEP: 27
     | > decoder_loss: 0.42826005816459656  (0.448576326723452)
     | > postnet_loss: 0.2925697863101959  (0.31225795105651566)
     | > stopnet_loss: 0.003944476135075092  (0.005999890207830403)
     | > loss: 0.18415193259716034  (0.1962084593596282)
     | > align_error: 0.5405218601226807  (0.595779279867808)

   --> STEP: 28
     | > decoder_loss: 0.4337460696697235  (0.4480466746858188)
     | > postnet_loss: 0.2972380518913269  (0.31172152608633036)
     | > stopnet_loss: 0.00393398804590106  (0.0059261079877614975)
     | > loss: 0.18668000400066376  (0.1958681573825223)
     | > align_error: 0.5659649074077606  (0.5947144808513778)

   --> STEP: 29
     | > decoder_loss: 0.4293598234653473  (0.44740230050580254)
     | > postnet_loss: 0.2944031059741974  (0.311124339185912)
     | > stopnet_loss: 0.0035791094414889812  (0.005845177003407273)
     | > loss: 0.18451984226703644  (0.1954768361716435)
     | > align_error: 0.539878785610199  (0.5928235948085785)

   --> STEP: 30
     | > decoder_loss: 0.4298967719078064  (0.44681878288586935)
     | > postnet_loss: 0.2951173782348633  (0.310590773820877)
     | > stopnet_loss: 0.0028413371182978153  (0.005745049007236958)
     | > loss: 0.1840948760509491  (0.19509743750095368)
     | > align_error: 0.5329689681529999  (0.5908284405867259)

   --> STEP: 31
     | > decoder_loss: 0.4285140335559845  (0.44622830710103434)
     | > postnet_loss: 0.2945707142353058  (0.31007399770521343)
     | > stopnet_loss: 0.0036733062006533146  (0.005678218594121356)
     | > loss: 0.18444448709487915  (0.1947537939394674)
     | > align_error: 0.5576963722705841  (0.5897596641894309)

   --> STEP: 32
     | > decoder_loss: 0.43816810846328735  (0.44597642589360476)
     | > postnet_loss: 0.29982420802116394  (0.3097536917775869)
     | > stopnet_loss: 0.0038393628783524036  (0.005620754353003576)
     | > loss: 0.18833743035793304  (0.19455328257754445)
     | > align_error: 0.5306467115879059  (0.5879123844206333)

   --> STEP: 33
     | > decoder_loss: 0.434481680393219  (0.4456281002723809)
     | > postnet_loss: 0.29688316583633423  (0.30936367583997315)
     | > stopnet_loss: 0.004022314213216305  (0.005572316773010023)
     | > loss: 0.18686352670192719  (0.19432025967222272)
     | > align_error: 0.5454092025756836  (0.5866244092132106)

   --> STEP: 34
     | > decoder_loss: 0.4401320815086365  (0.44546645266168255)
     | > postnet_loss: 0.2982728183269501  (0.30903747414841365)
     | > stopnet_loss: 0.0032975277863442898  (0.005505411214578678)
     | > loss: 0.18789874017238617  (0.1941313914516393)
     | > align_error: 0.5631875395774841  (0.5859350895180422)

   --> STEP: 35
     | > decoder_loss: 0.4374033212661743  (0.4452360774789538)
     | > postnet_loss: 0.2978239059448242  (0.308717086485454)
     | > stopnet_loss: 0.003524299245327711  (0.005448808015457222)
     | > loss: 0.18733111023902893  (0.19393709770270756)
     | > align_error: 0.5324543118476868  (0.5844070672988891)

   --> STEP: 36
     | > decoder_loss: 0.4433223605155945  (0.445182918674416)
     | > postnet_loss: 0.30195072293281555  (0.3085291319423251)
     | > stopnet_loss: 0.003663423238322139  (0.005399213993870135)
     | > loss: 0.18998169898986816  (0.1938272255162398)
     | > align_error: 0.6332549154758453  (0.5857639519704713)

   --> STEP: 37
     | > decoder_loss: 0.4365364909172058  (0.4449492314377347)
     | > postnet_loss: 0.29897308349609375  (0.30827086036269724)
     | > stopnet_loss: 0.0035689284559339285  (0.005349746817169157)
     | > loss: 0.18744632601737976  (0.19365476877302737)
     | > align_error: 0.5183943808078766  (0.5839431527498606)

   --> STEP: 38
     | > decoder_loss: 0.4235561192035675  (0.44438625479999344)
     | > postnet_loss: 0.29152387380599976  (0.3078301501901526)
     | > stopnet_loss: 0.0031332578510046005  (0.005291418160164826)
     | > loss: 0.18190325796604156  (0.19334551848863302)
     | > align_error: 0.5509559512138367  (0.5830750684989127)

   --> STEP: 39
     | > decoder_loss: 0.43845465779304504  (0.444234162569046)
     | > postnet_loss: 0.3019649088382721  (0.3076797593862582)
     | > stopnet_loss: 0.003470896976068616  (0.005244738129803385)
     | > loss: 0.18857578933238983  (0.19322321774103704)
     | > align_error: 0.5450915098190308  (0.5821011310968645)

   --> STEP: 40
     | > decoder_loss: 0.4359527826309204  (0.44402712807059286)
     | > postnet_loss: 0.3007001578807831  (0.3075052693486213)
     | > stopnet_loss: 0.0030315483454614878  (0.005189408385194837)
     | > loss: 0.1871947944164276  (0.19307250715792182)
     | > align_error: 0.5831878185272217  (0.5821282982826234)

   --> STEP: 41
     | > decoder_loss: 0.4269881248474121  (0.44361154262612507)
     | > postnet_loss: 0.29308459162712097  (0.30715354550175544)
     | > stopnet_loss: 0.0037237510550767183  (0.005153660645435858)
     | > loss: 0.18374194204807281  (0.19284493239914502)
     | > align_error: 0.5021907389163971  (0.5801786017127154)

   --> STEP: 42
     | > decoder_loss: 0.4320683181285858  (0.4433367039476122)
     | > postnet_loss: 0.2949388027191162  (0.306862718292645)
     | > stopnet_loss: 0.003281376091763377  (0.005109082441776989)
     | > loss: 0.1850331574678421  (0.19265893775792353)
     | > align_error: 0.5788612961769104  (0.5801472372951962)

   --> STEP: 43
     | > decoder_loss: 0.4307873845100403  (0.44304485930952914)
     | > postnet_loss: 0.293578177690506  (0.3065537754879441)
     | > stopnet_loss: 0.0029312444385141134  (0.005058435046352271)
     | > loss: 0.18402263522148132  (0.19245809351289)
     | > align_error: 0.551041841506958  (0.5794703676257024)

   --> STEP: 44
     | > decoder_loss: 0.4478875398635864  (0.4431549202312123)
     | > postnet_loss: 0.3041418492794037  (0.30649895898320456)
     | > stopnet_loss: 0.0026516076177358627  (0.005003734422974625)
     | > loss: 0.19065895676612854  (0.1924172040413727)
     | > align_error: 0.5501270592212677  (0.5788034742528743)

   --> STEP: 45
     | > decoder_loss: 0.44203847646713257  (0.4431301103697883)
     | > postnet_loss: 0.30364683270454407  (0.30643557839923435)
     | > stopnet_loss: 0.003303183475509286  (0.00496594440191984)
     | > loss: 0.18972451984882355  (0.1923573666148716)
     | > align_error: 0.5518667995929718  (0.5782048814826543)

   --> STEP: 46
     | > decoder_loss: 0.43243950605392456  (0.44289770592813904)
     | > postnet_loss: 0.2952713072299957  (0.30619287685207697)
     | > stopnet_loss: 0.003187952097505331  (0.004927292395302133)
     | > loss: 0.18511566519737244  (0.19219993832318683)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3450264388864691 (-0.020102295008572635)
     | > avg_decoder_loss: 0.43884953811313165 (-0.00014572432546905434)
     | > avg_postnet_loss: 0.30322878514275414 (+3.7142273151602456e-05)
     | > avg_stopnet_loss: 0.0043675948893933565 (-9.089824743570632e-06)
     | > avg_loss: 0.1898871750542612 (-3.6237140496553355e-05)
     | > avg_align_error: 0.5710100603826118 (-8.484359943494724e-05)


 > EPOCH: 136/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 17:07:37)

   --> TIME: 2025-12-28 17:07:57 -- STEP: 14/150 -- GLOBAL_STEP: 20550
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4685952961444855  (0.46512702320303234)
     | > postnet_loss: 0.39487728476524353  (0.3946688877684729)
     | > stopnet_loss: 0.008634877391159534  (0.011423219460994005)
     | > loss: 0.2245030254125595  (0.22637219727039337)
     | > align_error: 0.641319215297699  (0.6820998340845108)
     | > grad_norm: tensor(0.2561, device='cuda:0')  (tensor(0.3180, device='cuda:0'))
     | > step_time: 0.8057  (0.5920537539890834)
     | > loader_time: 1.1172  (0.8043000016893659)


   --> TIME: 2025-12-28 17:08:45 -- STEP: 39/150 -- GLOBAL_STEP: 20575
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4769136905670166  (0.4726325854276999)
     | > postnet_loss: 0.39624154567718506  (0.39722264959261966)
     | > stopnet_loss: 0.0053880843333899975  (0.008230200634361839)
     | > loss: 0.2236768901348114  (0.22569400874467996)
     | > align_error: 0.5930107235908508  (0.6549888658217894)
     | > grad_norm: tensor(0.1851, device='cuda:0')  (tensor(0.2998, device='cuda:0'))
     | > step_time: 1.1884  (0.8053021858900022)
     | > loader_time: 1.0322  (0.9198513153271798)


   --> TIME: 2025-12-28 17:09:47 -- STEP: 64/150 -- GLOBAL_STEP: 20600
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48540279269218445  (0.47699712635949254)
     | > postnet_loss: 0.39913174510002136  (0.3976790448650718)
     | > stopnet_loss: 0.004024331457912922  (0.006795150598918552)
     | > loss: 0.2251579612493515  (0.2254641940817237)
     | > align_error: 0.6135179698467255  (0.6387576032429932)
     | > grad_norm: tensor(0.2459, device='cuda:0')  (tensor(0.2660, device='cuda:0'))
     | > step_time: 1.4292  (1.001284882426262)
     | > loader_time: 1.2107  (1.0106721818447113)


   --> TIME: 2025-12-28 17:11:01 -- STEP: 89/150 -- GLOBAL_STEP: 20625
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4786807894706726  (0.47902972845548997)
     | > postnet_loss: 0.39112451672554016  (0.39725259046876027)
     | > stopnet_loss: 0.00351967616006732  (0.005973667989411714)
     | > loss: 0.2209710031747818  (0.22504424797684958)
     | > align_error: 0.6578717231750488  (0.6328366552845816)
     | > grad_norm: tensor(0.2948, device='cuda:0')  (tensor(0.2578, device='cuda:0'))
     | > step_time: 1.6531  (1.1686497484700065)
     | > loader_time: 1.4658  (1.1159286927641112)


   --> TIME: 2025-12-28 17:12:24 -- STEP: 114/150 -- GLOBAL_STEP: 20650
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48246607184410095  (0.4801959816301078)
     | > postnet_loss: 0.3929648995399475  (0.39675318593518777)
     | > stopnet_loss: 0.003354760818183422  (0.005425236459511021)
     | > loss: 0.22221249341964722  (0.2246625288798098)
     | > align_error: 0.6085610687732697  (0.6275392702797006)
     | > grad_norm: tensor(0.1495, device='cuda:0')  (tensor(0.2355, device='cuda:0'))
     | > step_time: 1.8318  (1.297858963932908)
     | > loader_time: 1.5423  (1.2140309977949717)


   --> TIME: 2025-12-28 17:14:01 -- STEP: 139/150 -- GLOBAL_STEP: 20675
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49277666211128235  (0.4811978458071784)
     | > postnet_loss: 0.3983103930950165  (0.39629758283388694)
     | > stopnet_loss: 0.003101752605289221  (0.005021117265811927)
     | > loss: 0.22587351500988007  (0.22439497505589354)
     | > align_error: 0.647906482219696  (0.6244902246289976)
     | > grad_norm: tensor(0.1496, device='cuda:0')  (tensor(0.2236, device='cuda:0'))
     | > step_time: 2.2676  (1.429320246195622)
     | > loader_time: 2.2923  (1.3263243959962039)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4606725573539734  (0.4606725573539734)
     | > postnet_loss: 0.3333304524421692  (0.3333304524421692)
     | > stopnet_loss: 0.01214405708014965  (0.01214405708014965)
     | > loss: 0.21064481139183044  (0.21064481139183044)
     | > align_error: 0.7189831435680389  (0.7189831435680389)

   --> STEP: 1
     | > decoder_loss: 0.44102543592453003  (0.44102543592453003)
     | > postnet_loss: 0.3199600875377655  (0.3199600875377655)
     | > stopnet_loss: 0.009673579595983028  (0.009673579595983028)
     | > loss: 0.1999199539422989  (0.1999199539422989)
     | > align_error: 0.6596324443817139  (0.6596324443817139)

   --> STEP: 2
     | > decoder_loss: 0.4384196102619171  (0.43972252309322357)
     | > postnet_loss: 0.3126586079597473  (0.3163093477487564)
     | > stopnet_loss: 0.011068862862884998  (0.010371221229434013)
     | > loss: 0.19883842766284943  (0.19937919080257416)
     | > align_error: 0.6553951501846313  (0.6575137972831726)

   --> STEP: 3
     | > decoder_loss: 0.44122636318206787  (0.4402238031228383)
     | > postnet_loss: 0.31135010719299316  (0.314656267563502)
     | > stopnet_loss: 0.008099613711237907  (0.009614018723368645)
     | > loss: 0.19624373316764832  (0.19833403825759888)
     | > align_error: 0.735016256570816  (0.6833479503790537)

   --> STEP: 4
     | > decoder_loss: 0.44485995173454285  (0.44138284027576447)
     | > postnet_loss: 0.318311870098114  (0.315570168197155)
     | > stopnet_loss: 0.00816098228096962  (0.009250759612768888)
     | > loss: 0.19895392656326294  (0.1984890103340149)
     | > align_error: 0.6033918857574463  (0.6633589342236519)

   --> STEP: 5
     | > decoder_loss: 0.42696502804756165  (0.4384992778301239)
     | > postnet_loss: 0.3012097477912903  (0.31269808411598204)
     | > stopnet_loss: 0.008051606826484203  (0.009010929055511952)
     | > loss: 0.19009530544281006  (0.19681026935577392)
     | > align_error: 0.6421710252761841  (0.6591213524341584)

   --> STEP: 6
     | > decoder_loss: 0.444745808839798  (0.43954036633173627)
     | > postnet_loss: 0.3132924735546112  (0.31279714902242023)
     | > stopnet_loss: 0.007222351618111134  (0.008712832815945148)
     | > loss: 0.19673192501068115  (0.19679721196492514)
     | > align_error: 0.5938392877578735  (0.6482410083214442)

   --> STEP: 7
     | > decoder_loss: 0.4577242434024811  (0.44213806305612835)
     | > postnet_loss: 0.3142363727092743  (0.3130027524062565)
     | > stopnet_loss: 0.006213173270225525  (0.00835573859512806)
     | > loss: 0.19920332729816437  (0.19714094272681645)
     | > align_error: 0.5790754556655884  (0.6383602150848934)

   --> STEP: 8
     | > decoder_loss: 0.4524213373661041  (0.44342347234487534)
     | > postnet_loss: 0.3150792419910431  (0.31326231360435486)
     | > stopnet_loss: 0.0070905378088355064  (0.00819758849684149)
     | > loss: 0.19896568357944489  (0.197369035333395)
     | > align_error: 0.5746289491653442  (0.6303938068449497)

   --> STEP: 9
     | > decoder_loss: 0.44792693853378296  (0.44392385747697616)
     | > postnet_loss: 0.3136304020881653  (0.31330321232477826)
     | > stopnet_loss: 0.00676311319693923  (0.008038202352407906)
     | > loss: 0.19715245068073273  (0.1973449703719881)
     | > align_error: 0.5914487540721893  (0.6260665787590874)

   --> STEP: 10
     | > decoder_loss: 0.4708399474620819  (0.4466154664754868)
     | > postnet_loss: 0.32633817195892334  (0.31460670828819276)
     | > stopnet_loss: 0.005632392596453428  (0.007797621376812458)
     | > loss: 0.20492692291736603  (0.19810316562652588)
     | > align_error: 0.5828638076782227  (0.621746301651001)

   --> STEP: 11
     | > decoder_loss: 0.4603078365325928  (0.4478602273897691)
     | > postnet_loss: 0.3182067275047302  (0.3149339827624234)
     | > stopnet_loss: 0.005855605937540531  (0.007621074518696828)
     | > loss: 0.2004842460155487  (0.1983196274800734)
     | > align_error: 0.5949233770370483  (0.6193078539588235)

   --> STEP: 12
     | > decoder_loss: 0.45620453357696533  (0.4485555862387021)
     | > postnet_loss: 0.31137052178382874  (0.3146370276808738)
     | > stopnet_loss: 0.007920503616333008  (0.007646026943499844)
     | > loss: 0.19981426000595093  (0.1984441801905632)
     | > align_error: 0.5872936248779297  (0.6166400015354156)

   --> STEP: 13
     | > decoder_loss: 0.4456942081451416  (0.44833548023150516)
     | > postnet_loss: 0.31117573380470276  (0.3143707743057837)
     | > stopnet_loss: 0.0056077903136610985  (0.007489239510435324)
     | > loss: 0.19482526183128357  (0.198165801855234)
     | > align_error: 0.5856643915176392  (0.614257262303279)

   --> STEP: 14
     | > decoder_loss: 0.4612438380718231  (0.4492575057915279)
     | > postnet_loss: 0.3172793686389923  (0.31457853104387007)
     | > stopnet_loss: 0.004900954198092222  (0.007304361988125103)
     | > loss: 0.19953174889087677  (0.19826336950063705)
     | > align_error: 0.5549817383289337  (0.6100232963051114)

   --> STEP: 15
     | > decoder_loss: 0.4543346166610718  (0.44959597984949745)
     | > postnet_loss: 0.31440648436546326  (0.3145670612653096)
     | > stopnet_loss: 0.005008768290281296  (0.007151322408268849)
     | > loss: 0.19719405472278595  (0.19819208184878032)
     | > align_error: 0.5885191559791565  (0.6085896869500478)

   --> STEP: 16
     | > decoder_loss: 0.4546351730823517  (0.44991092942655087)
     | > postnet_loss: 0.3083231449127197  (0.3141768164932727)
     | > stopnet_loss: 0.005233168136328459  (0.007031437766272575)
     | > loss: 0.195972740650177  (0.1980533730238676)
     | > align_error: 0.6059478521347046  (0.6084245722740889)

   --> STEP: 17
     | > decoder_loss: 0.46269944310188293  (0.4506631949368645)
     | > postnet_loss: 0.3177870810031891  (0.31438918499385604)
     | > stopnet_loss: 0.004813301842659712  (0.0069009591825306416)
     | > loss: 0.1999349296092987  (0.1981640528230106)
     | > align_error: 0.5585247278213501  (0.6054892873062807)

   --> STEP: 18
     | > decoder_loss: 0.45624881982803345  (0.4509735074308183)
     | > postnet_loss: 0.3094564378261566  (0.3141151434845394)
     | > stopnet_loss: 0.0052367690950632095  (0.006808504177671339)
     | > loss: 0.19666308164596558  (0.198080665535397)
     | > align_error: 0.6042186617851257  (0.6054186969995499)

   --> STEP: 19
     | > decoder_loss: 0.45261842012405396  (0.4510600817830939)
     | > postnet_loss: 0.3082832992076874  (0.3138082043120735)
     | > stopnet_loss: 0.004719656892120838  (0.006698564846852892)
     | > loss: 0.1949450820684433  (0.19791563482660995)
     | > align_error: 0.5996737480163574  (0.6051163312635923)

   --> STEP: 20
     | > decoder_loss: 0.45078179240226746  (0.45104616731405256)
     | > postnet_loss: 0.3057072162628174  (0.3134031549096107)
     | > stopnet_loss: 0.0044983383268117905  (0.006588553520850837)
     | > loss: 0.19362059235572815  (0.19770088270306588)
     | > align_error: 0.6231551766395569  (0.6060182735323906)

   --> STEP: 21
     | > decoder_loss: 0.44722509384155273  (0.45086421143440975)
     | > postnet_loss: 0.3037338852882385  (0.3129427134990691)
     | > stopnet_loss: 0.003948749043047428  (0.006462848545717341)
     | > loss: 0.19168849289417267  (0.1974145784264519)
     | > align_error: 0.5601159632205963  (0.603832449231829)

   --> STEP: 22
     | > decoder_loss: 0.44918689131736755  (0.45078796961090783)
     | > postnet_loss: 0.3065727949142456  (0.31265317174521345)
     | > stopnet_loss: 0.004826681688427925  (0.006388477324931459)
     | > loss: 0.19376660883426666  (0.19724876162680713)
     | > align_error: 0.6255466639995575  (0.6048194589939985)

   --> STEP: 23
     | > decoder_loss: 0.4226375222206116  (0.44956403711567755)
     | > postnet_loss: 0.2946244478225708  (0.3118693141833594)
     | > stopnet_loss: 0.00444114999845624  (0.006303810919432536)
     | > loss: 0.18375664949417114  (0.19666214805582297)
     | > align_error: 0.5673822462558746  (0.6031917540923409)

   --> STEP: 24
     | > decoder_loss: 0.4576030671596527  (0.44989899670084316)
     | > postnet_loss: 0.3109658360481262  (0.31183166926105804)
     | > stopnet_loss: 0.004377906210720539  (0.00622356488990287)
     | > loss: 0.1965201199054718  (0.196656230216225)
     | > align_error: 0.579922080039978  (0.6022221843401592)

   --> STEP: 25
     | > decoder_loss: 0.4560149908065796  (0.4501436364650726)
     | > postnet_loss: 0.3075762987136841  (0.31166145443916304)
     | > stopnet_loss: 0.003718365216627717  (0.006123356902971864)
     | > loss: 0.1946161836385727  (0.1965746283531189)
     | > align_error: 0.5580891370773315  (0.600456862449646)

   --> STEP: 26
     | > decoder_loss: 0.431602418422699  (0.4494305126942121)
     | > postnet_loss: 0.29632776975631714  (0.31107169733597667)
     | > stopnet_loss: 0.004349484108388424  (0.006055131026257116)
     | > loss: 0.18633203208446503  (0.19618068234278604)
     | > align_error: 0.5470672249794006  (0.5984034148546366)

   --> STEP: 27
     | > decoder_loss: 0.4281230568885803  (0.4486413476643739)
     | > postnet_loss: 0.29150596261024475  (0.3103470404942829)
     | > stopnet_loss: 0.00392635352909565  (0.005976287415251136)
     | > loss: 0.18383361399173737  (0.19572338351496943)
     | > align_error: 0.5413426458835602  (0.596290053040893)

   --> STEP: 28
     | > decoder_loss: 0.4337884783744812  (0.4481108880468777)
     | > postnet_loss: 0.2960631549358368  (0.3098369017243384)
     | > stopnet_loss: 0.003919428680092096  (0.005902828174709741)
     | > loss: 0.18638232350349426  (0.19538977422884532)
     | > align_error: 0.5666692852973938  (0.5952321684786251)

   --> STEP: 29
     | > decoder_loss: 0.4287634789943695  (0.44744373601058435)
     | > postnet_loss: 0.292400062084198  (0.3092356313919198)
     | > stopnet_loss: 0.00356988119892776  (0.0058223817272689835)
     | > loss: 0.18386076390743256  (0.1949922221487966)
     | > align_error: 0.5406773090362549  (0.5933509664288883)

   --> STEP: 30
     | > decoder_loss: 0.4302250146865845  (0.44686977863311766)
     | > postnet_loss: 0.2935495376586914  (0.3087127616008122)
     | > stopnet_loss: 0.002844341332092881  (0.005723113714096447)
     | > loss: 0.1837879866361618  (0.19461874763170878)
     | > align_error: 0.5336419939994812  (0.591360667347908)

   --> STEP: 31
     | > decoder_loss: 0.42602378129959106  (0.4461973271062297)
     | > postnet_loss: 0.2923845648765564  (0.30818604557744905)
     | > stopnet_loss: 0.003671344369649887  (0.005656927606211074)
     | > loss: 0.18327343463897705  (0.19425276979323355)
     | > align_error: 0.5553953051567078  (0.5902004943739984)

   --> STEP: 32
     | > decoder_loss: 0.43845483660697937  (0.44595537427812815)
     | > postnet_loss: 0.2986920475959778  (0.3078893581405281)
     | > stopnet_loss: 0.00382279884070158  (0.005599611082288902)
     | > loss: 0.18810951709747314  (0.19406079314649105)
     | > align_error: 0.5311245620250702  (0.5883543714880943)

   --> STEP: 33
     | > decoder_loss: 0.4342239201068878  (0.4455998756668784)
     | > postnet_loss: 0.2958955764770508  (0.3075259102113318)
     | > stopnet_loss: 0.004005221650004387  (0.005551296251007553)
     | > loss: 0.1865350902080536  (0.193832741542296)
     | > align_error: 0.5461529493331909  (0.5870755405137034)

   --> STEP: 34
     | > decoder_loss: 0.43965527415275574  (0.44542503444587483)
     | > postnet_loss: 0.297254741191864  (0.3072238170048769)
     | > stopnet_loss: 0.0032774971332401037  (0.005484419806367334)
     | > loss: 0.18750499188899994  (0.1936466312583755)
     | > align_error: 0.5637896060943604  (0.5863906600896049)

   --> STEP: 35
     | > decoder_loss: 0.4373698830604553  (0.44519488726343426)
     | > postnet_loss: 0.29636046290397644  (0.30691343545913685)
     | > stopnet_loss: 0.0035153203643858433  (0.0054281598223107205)
     | > loss: 0.18694789707660675  (0.1934552388531821)
     | > align_error: 0.5331135392189026  (0.5848684566361564)

   --> STEP: 36
     | > decoder_loss: 0.4437977373600006  (0.44515607754389447)
     | > postnet_loss: 0.30109673738479614  (0.3067518605126274)
     | > stopnet_loss: 0.0036445765290409327  (0.005378615841942115)
     | > loss: 0.18986819684505463  (0.1933555987974008)
     | > align_error: 0.6337363719940186  (0.5862258987294303)

   --> STEP: 37
     | > decoder_loss: 0.4359987676143646  (0.4449085826809342)
     | > postnet_loss: 0.29735124111175537  (0.30649778971800923)
     | > stopnet_loss: 0.003570015076547861  (0.005329734740174703)
     | > loss: 0.18690752983093262  (0.19318132666317192)
     | > align_error: 0.5191086530685425  (0.5844119191169739)

   --> STEP: 38
     | > decoder_loss: 0.4229763448238373  (0.4443314185268001)
     | > postnet_loss: 0.28982895612716675  (0.3060591362024607)
     | > stopnet_loss: 0.003135473234578967  (0.005271991016343236)
     | > loss: 0.18133679032325745  (0.19286962833843732)
     | > align_error: 0.5517275333404541  (0.5835518037018023)

   --> STEP: 39
     | > decoder_loss: 0.438609778881073  (0.4441847098179353)
     | > postnet_loss: 0.30028045177459717  (0.3059109648068745)
     | > stopnet_loss: 0.003458755323663354  (0.005225497793454008)
     | > loss: 0.1881813108921051  (0.19274941507058266)
     | > align_error: 0.5459373295307159  (0.5825873300051078)

   --> STEP: 40
     | > decoder_loss: 0.4355892241001129  (0.4439698226749897)
     | > postnet_loss: 0.29874664545059204  (0.30573185682296744)
     | > stopnet_loss: 0.0030290684662759304  (0.005170587060274556)
     | > loss: 0.1866130381822586  (0.19259600564837456)
     | > align_error: 0.5839722156524658  (0.5826219521462918)

   --> STEP: 41
     | > decoder_loss: 0.4266083240509033  (0.44354637148903636)
     | > postnet_loss: 0.2912452220916748  (0.30537852426854567)
     | > stopnet_loss: 0.003716632490977645  (0.005135124753706339)
     | > loss: 0.18318001925945282  (0.1923663474437667)
     | > align_error: 0.5029162764549255  (0.5806779112757706)

   --> STEP: 42
     | > decoder_loss: 0.43220335245132446  (0.44327629960718606)
     | > postnet_loss: 0.2940492033958435  (0.30510877853348134)
     | > stopnet_loss: 0.0032764459028840065  (0.005090870495353427)
     | > loss: 0.18483959138393402  (0.19218713896615164)
     | > align_error: 0.5795799493789673  (0.5806517693258467)

   --> STEP: 43
     | > decoder_loss: 0.4304932653903961  (0.44297901974167936)
     | > postnet_loss: 0.2924657166004181  (0.30481475383736356)
     | > stopnet_loss: 0.002940971637144685  (0.0050408728474881075)
     | > loss: 0.1836807131767273  (0.19198931511058365)
     | > align_error: 0.5517256855964661  (0.5799790697042332)

   --> STEP: 44
     | > decoder_loss: 0.44802379608154297  (0.4430936737494035)
     | > postnet_loss: 0.30282679200172424  (0.3047695728865536)
     | > stopnet_loss: 0.002643836662173271  (0.004986394752367316)
     | > loss: 0.19035647809505463  (0.19195220517841252)
     | > align_error: 0.5510990023612976  (0.5793227045373484)

   --> STEP: 45
     | > decoder_loss: 0.440858393907547  (0.44304400086402895)
     | > postnet_loss: 0.3017149269580841  (0.30470169186592094)
     | > stopnet_loss: 0.0032921007368713617  (0.004948743774245184)
     | > loss: 0.18893542885780334  (0.19188516570462122)
     | > align_error: 0.5525604486465454  (0.578727987739775)

   --> STEP: 46
     | > decoder_loss: 0.43142029643058777  (0.44279131163721497)
     | > postnet_loss: 0.29313787817955017  (0.3044503046118694)
     | > stopnet_loss: 0.0031899036839604378  (0.004910508120108559)
     | > loss: 0.18432945013046265  (0.19172091101822647)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.36147135315519396 (+0.016444914268724853)
     | > avg_decoder_loss: 0.43854799911831366 (-0.00030153899481799584)
     | > avg_postnet_loss: 0.3010234403790849 (-0.002205344763669237)
     | > avg_stopnet_loss: 0.004353277445206364 (-1.4317444186992545e-05)
     | > avg_loss: 0.1892461363564838 (-0.0006410386977774019)
     | > avg_align_error: 0.5716237272277023 (+0.0006136668450904548)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_20687.pth

 > EPOCH: 137/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 17:16:48)

   --> TIME: 2025-12-28 17:17:06 -- STEP: 13/150 -- GLOBAL_STEP: 20700
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46204814314842224  (0.46263726628743684)
     | > postnet_loss: 0.39158374071121216  (0.3933643905016092)
     | > stopnet_loss: 0.00961100123822689  (0.01179472772547832)
     | > loss: 0.22301895916461945  (0.2257951429257026)
     | > align_error: 0.6580085754394531  (0.6851532528033624)
     | > grad_norm: tensor(0.1816, device='cuda:0')  (tensor(0.2678, device='cuda:0'))
     | > step_time: 0.6949  (0.5715199800638052)
     | > loader_time: 0.7798  (0.7585342663985032)


   --> TIME: 2025-12-28 17:17:54 -- STEP: 38/150 -- GLOBAL_STEP: 20725
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.48677369952201843  (0.4715539287579687)
     | > postnet_loss: 0.40312984585762024  (0.3968115864615691)
     | > stopnet_loss: 0.005489576607942581  (0.00844596056757789)
     | > loss: 0.22796545922756195  (0.22553733853917374)
     | > align_error: 0.6078912317752838  (0.6567735460243727)
     | > grad_norm: tensor(0.2025, device='cuda:0')  (tensor(0.2604, device='cuda:0'))
     | > step_time: 1.091  (0.8109176723580611)
     | > loader_time: 1.0011  (0.9023550686083341)


   --> TIME: 2025-12-28 17:18:54 -- STEP: 63/150 -- GLOBAL_STEP: 20750
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48755186796188354  (0.4764785369237264)
     | > postnet_loss: 0.39997702836990356  (0.3974856597090524)
     | > stopnet_loss: 0.003975437488406897  (0.006924451986652992)
     | > loss: 0.2258576601743698  (0.22541550062005483)
     | > align_error: 0.5650543570518494  (0.6389660475746035)
     | > grad_norm: tensor(0.1347, device='cuda:0')  (tensor(0.2409, device='cuda:0'))
     | > step_time: 1.424  (0.9971232868376232)
     | > loader_time: 1.195  (0.9859195663815453)


   --> TIME: 2025-12-28 17:20:08 -- STEP: 88/150 -- GLOBAL_STEP: 20775
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48687270283699036  (0.4786833677102219)
     | > postnet_loss: 0.39755377173423767  (0.3971230634911494)
     | > stopnet_loss: 0.0039216699078679085  (0.006063279206335378)
     | > loss: 0.22502829134464264  (0.225014886056835)
     | > align_error: 0.6074044108390808  (0.6324664096940648)
     | > grad_norm: tensor(0.2056, device='cuda:0')  (tensor(0.2291, device='cuda:0'))
     | > step_time: 1.6404  (1.163917460224845)
     | > loader_time: 1.6383  (1.1037646911361)


   --> TIME: 2025-12-28 17:21:39 -- STEP: 113/150 -- GLOBAL_STEP: 20800
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4927050769329071  (0.4799128301375735)
     | > postnet_loss: 0.40005165338516235  (0.3966641365426832)
     | > stopnet_loss: 0.0031745987944304943  (0.005493106130939143)
     | > loss: 0.22636377811431885  (0.22463734685319714)
     | > align_error: 0.6107852458953857  (0.6279042463387008)
     | > grad_norm: tensor(0.2244, device='cuda:0')  (tensor(0.2201, device='cuda:0'))
     | > step_time: 1.8913  (1.298938590868385)
     | > loader_time: 1.6776  (1.2647752698543857)


   --> TIME: 2025-12-28 17:23:13 -- STEP: 138/150 -- GLOBAL_STEP: 20825
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48865312337875366  (0.4809010953143023)
     | > postnet_loss: 0.3956129252910614  (0.3961994768916697)
     | > stopnet_loss: 0.003221983090043068  (0.005078242437077175)
     | > loss: 0.22428849339485168  (0.2243533846044886)
     | > align_error: 0.5842374265193939  (0.6243569902751757)
     | > grad_norm: tensor(0.2153, device='cuda:0')  (tensor(0.2179, device='cuda:0'))
     | > step_time: 2.0857  (1.4249148524325832)
     | > loader_time: 1.9074  (1.3596440760985669)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46067145466804504  (0.46067145466804504)
     | > postnet_loss: 0.333721399307251  (0.333721399307251)
     | > stopnet_loss: 0.012209955602884293  (0.012209955602884293)
     | > loss: 0.2108081579208374  (0.2108081579208374)
     | > align_error: 0.718017190694809  (0.718017190694809)

   --> STEP: 1
     | > decoder_loss: 0.441591739654541  (0.441591739654541)
     | > postnet_loss: 0.3209974467754364  (0.3209974467754364)
     | > stopnet_loss: 0.009652851149439812  (0.009652851149439812)
     | > loss: 0.2003001570701599  (0.2003001570701599)
     | > align_error: 0.6582014858722687  (0.6582014858722687)

   --> STEP: 2
     | > decoder_loss: 0.43686172366142273  (0.4392267316579819)
     | > postnet_loss: 0.31205183267593384  (0.3165246397256851)
     | > stopnet_loss: 0.011120151728391647  (0.01038650143891573)
     | > loss: 0.1983485370874405  (0.1993243470788002)
     | > align_error: 0.6544189155101776  (0.6563102006912231)

   --> STEP: 3
     | > decoder_loss: 0.442588746547699  (0.4403474032878876)
     | > postnet_loss: 0.3123184144496918  (0.3151225646336873)
     | > stopnet_loss: 0.008285384625196457  (0.009686129167675972)
     | > loss: 0.19701217114925385  (0.19855362176895142)
     | > align_error: 0.7343042492866516  (0.6823082168896993)

   --> STEP: 4
     | > decoder_loss: 0.4454484283924103  (0.44162265956401825)
     | > postnet_loss: 0.31922322511672974  (0.31614772975444794)
     | > stopnet_loss: 0.008198924362659454  (0.009314327966421843)
     | > loss: 0.19936683773994446  (0.19875692576169968)
     | > align_error: 0.6020427942276001  (0.6622418612241745)

   --> STEP: 5
     | > decoder_loss: 0.43089550733566284  (0.4394772291183472)
     | > postnet_loss: 0.30360788106918335  (0.313639760017395)
     | > stopnet_loss: 0.00811117421835661  (0.009073697216808795)
     | > loss: 0.19173702597618103  (0.19735294580459595)
     | > align_error: 0.6424227356910706  (0.6582780361175538)

   --> STEP: 6
     | > decoder_loss: 0.44467371702194214  (0.440343310435613)
     | > postnet_loss: 0.31380224227905273  (0.31366684039433795)
     | > stopnet_loss: 0.007291508838534355  (0.008776665820429722)
     | > loss: 0.19691050052642822  (0.19727920492490134)
     | > align_error: 0.5925152897834778  (0.6473175783952078)

   --> STEP: 7
     | > decoder_loss: 0.4549407660961151  (0.44242866124425617)
     | > postnet_loss: 0.313305526971817  (0.3136152241911207)
     | > stopnet_loss: 0.006251041777431965  (0.008415862385715758)
     | > loss: 0.19831261038780212  (0.1974268342767443)
     | > align_error: 0.5777463614940643  (0.6373788331236158)

   --> STEP: 8
     | > decoder_loss: 0.44796469807624817  (0.44312066584825516)
     | > postnet_loss: 0.3130013644695282  (0.31353849172592163)
     | > stopnet_loss: 0.007330430205911398  (0.008280183363240212)
     | > loss: 0.19757194817066193  (0.197444973513484)
     | > align_error: 0.5731805264949799  (0.6293540447950363)

   --> STEP: 9
     | > decoder_loss: 0.4476434886455536  (0.44362320171462166)
     | > postnet_loss: 0.3138512969017029  (0.313573247856564)
     | > stopnet_loss: 0.006672232877463102  (0.008101522198153866)
     | > loss: 0.1970459222793579  (0.19740063448747)
     | > align_error: 0.589812695980072  (0.6249605615933737)

   --> STEP: 10
     | > decoder_loss: 0.47288644313812256  (0.4465495258569717)
     | > postnet_loss: 0.3280324637889862  (0.31501916944980624)
     | > stopnet_loss: 0.0055535780265927315  (0.007846727780997754)
     | > loss: 0.20578330755233765  (0.19823890179395676)
     | > align_error: 0.5830467343330383  (0.6207691788673401)

   --> STEP: 11
     | > decoder_loss: 0.46053168177604675  (0.447820630940524)
     | > postnet_loss: 0.31885308027267456  (0.3153677067973397)
     | > stopnet_loss: 0.005939256399869919  (0.007673321291804314)
     | > loss: 0.20078544318675995  (0.19847040555693887)
     | > align_error: 0.593528538942337  (0.6182927570559762)

   --> STEP: 12
     | > decoder_loss: 0.45588040351867676  (0.44849227865537006)
     | > postnet_loss: 0.31161266565322876  (0.3150547867019971)
     | > stopnet_loss: 0.007869682274758816  (0.007689684707050522)
     | > loss: 0.19974294304847717  (0.1985764503479004)
     | > align_error: 0.5858414471149445  (0.6155884812275568)

   --> STEP: 13
     | > decoder_loss: 0.44498857855796814  (0.4482227632632622)
     | > postnet_loss: 0.31151583790779114  (0.3147825598716736)
     | > stopnet_loss: 0.005638845264911652  (0.007531927826885994)
     | > loss: 0.19476494193077087  (0.19828325739273658)
     | > align_error: 0.5843409299850464  (0.6131848234396714)

   --> STEP: 14
     | > decoder_loss: 0.4597584903240204  (0.4490467437676021)
     | > postnet_loss: 0.31694990396499634  (0.31493737016405376)
     | > stopnet_loss: 0.0049735368229448795  (0.0073491856123187715)
     | > loss: 0.19915062189102173  (0.19834521199975694)
     | > align_error: 0.5535577535629272  (0.608925747019904)

   --> STEP: 15
     | > decoder_loss: 0.4537568688392639  (0.4493607521057129)
     | > postnet_loss: 0.31448814272880554  (0.31490742166837055)
     | > stopnet_loss: 0.005017621908336878  (0.007193748032053312)
     | > loss: 0.1970788687467575  (0.19826078911622366)
     | > align_error: 0.5872714519500732  (0.607482127348582)

   --> STEP: 16
     | > decoder_loss: 0.45336994528770447  (0.44961132667958736)
     | > postnet_loss: 0.30802956223487854  (0.3144775554537773)
     | > stopnet_loss: 0.0052674636244773865  (0.007073355256579816)
     | > loss: 0.19561734795570374  (0.19809557404369116)
     | > align_error: 0.6044874787330627  (0.607294961810112)

   --> STEP: 17
     | > decoder_loss: 0.4618986248970032  (0.4503341089276707)
     | > postnet_loss: 0.3178354501724243  (0.31467507867252126)
     | > stopnet_loss: 0.004804308991879225  (0.006939881946891546)
     | > loss: 0.19973783195018768  (0.19819217744995565)
     | > align_error: 0.5570610761642456  (0.6043400273603552)

   --> STEP: 18
     | > decoder_loss: 0.4547523260116577  (0.45057956543233657)
     | > postnet_loss: 0.3090972304344177  (0.3143651982148488)
     | > stopnet_loss: 0.005296317860484123  (0.0068485728309800225)
     | > loss: 0.19625870883464813  (0.198084762526883)
     | > align_error: 0.6027200222015381  (0.6042500270737542)

   --> STEP: 19
     | > decoder_loss: 0.45263364911079407  (0.4506876750996238)
     | > postnet_loss: 0.30865275859832764  (0.31406454349818985)
     | > stopnet_loss: 0.004741949960589409  (0.006737697943064727)
     | > loss: 0.1950635462999344  (0.1979257511465173)
     | > align_error: 0.598697155714035  (0.6039577706864006)

   --> STEP: 20
     | > decoder_loss: 0.44890543818473816  (0.45059856325387954)
     | > postnet_loss: 0.3052661120891571  (0.3136246219277382)
     | > stopnet_loss: 0.004544123541563749  (0.0066280192229896786)
     | > loss: 0.19308701157569885  (0.19768381416797637)
     | > align_error: 0.6217264831066132  (0.6048462063074111)

   --> STEP: 21
     | > decoder_loss: 0.44687676429748535  (0.4504213347321465)
     | > postnet_loss: 0.3041987717151642  (0.31317577191761564)
     | > stopnet_loss: 0.003974070772528648  (0.006501640725348677)
     | > loss: 0.191742941737175  (0.19740091548079536)
     | > align_error: 0.5585255324840546  (0.6026404599348704)

   --> STEP: 22
     | > decoder_loss: 0.449307382106781  (0.4503707005219026)
     | > postnet_loss: 0.30734020471572876  (0.31291051886298443)
     | > stopnet_loss: 0.004957019817084074  (0.006431430684063922)
     | > loss: 0.1941189169883728  (0.1972517337311398)
     | > align_error: 0.6243945956230164  (0.6036292842843316)

   --> STEP: 23
     | > decoder_loss: 0.4216998517513275  (0.4491241418797037)
     | > postnet_loss: 0.29466062784194946  (0.31211704534033075)
     | > stopnet_loss: 0.004511539358645678  (0.006347957148176172)
     | > loss: 0.18360164761543274  (0.19665825172610904)
     | > align_error: 0.5657681822776794  (0.6019831494144772)

   --> STEP: 24
     | > decoder_loss: 0.4564075171947479  (0.44942761585116386)
     | > postnet_loss: 0.3108851909637451  (0.3120657180746397)
     | > stopnet_loss: 0.00441313860937953  (0.0062673397090596454)
     | > loss: 0.19623632729053497  (0.19664067154129347)
     | > align_error: 0.5784193873405457  (0.60100132599473)

   --> STEP: 25
     | > decoder_loss: 0.4556272625923157  (0.44967560172080995)
     | > postnet_loss: 0.30789706110954285  (0.3118989717960358)
     | > stopnet_loss: 0.0037351513747125864  (0.006166052175685764)
     | > loss: 0.19461622834205627  (0.19655969381332397)
     | > align_error: 0.5568414330482483  (0.5992349302768707)

   --> STEP: 26
     | > decoder_loss: 0.4303603768348694  (0.44893270845596606)
     | > postnet_loss: 0.2963392436504364  (0.3113005207135127)
     | > stopnet_loss: 0.004336049314588308  (0.0060956674502589386)
     | > loss: 0.18601094186306  (0.19615397258446768)
     | > align_error: 0.5452739596366882  (0.5971595083291714)

   --> STEP: 27
     | > decoder_loss: 0.4275120198726654  (0.44813934961954754)
     | > postnet_loss: 0.29168209433555603  (0.31057391232914394)
     | > stopnet_loss: 0.003931684419512749  (0.006015519930601672)
     | > loss: 0.18373021483421326  (0.19569383340853233)
     | > align_error: 0.5396239161491394  (0.5950285604706517)

   --> STEP: 28
     | > decoder_loss: 0.43307259678840637  (0.4476012513041496)
     | > postnet_loss: 0.2961798310279846  (0.3100598379969597)
     | > stopnet_loss: 0.003961631096899509  (0.0059421667579694516)
     | > loss: 0.18627475202083588  (0.19535743764468602)
     | > align_error: 0.5650311708450317  (0.5939572251268795)

   --> STEP: 29
     | > decoder_loss: 0.42834118008613586  (0.4469371109173216)
     | > postnet_loss: 0.2927345931529999  (0.30946241576096106)
     | > stopnet_loss: 0.0035769727546721697  (0.005860608344062649)
     | > loss: 0.18384592235088348  (0.19496048884145145)
     | > align_error: 0.5389507710933685  (0.5920604508498619)

   --> STEP: 30
     | > decoder_loss: 0.4298148453235626  (0.44636636873086294)
     | > postnet_loss: 0.2939985692501068  (0.30894695421059926)
     | > stopnet_loss: 0.002868098672479391  (0.0057608580216765405)
     | > loss: 0.18382145464420319  (0.19458918770154318)
     | > align_error: 0.5322896838188171  (0.5900680919488271)

   --> STEP: 31
     | > decoder_loss: 0.4289206862449646  (0.44580360477970493)
     | > postnet_loss: 0.2940516173839569  (0.30846645947425594)
     | > stopnet_loss: 0.00394624937325716  (0.005702322258824302)
     | > loss: 0.18468931317329407  (0.19426983691030933)
     | > align_error: 0.5572175979614258  (0.5890083985943948)

   --> STEP: 32
     | > decoder_loss: 0.4374876022338867  (0.4455437297001481)
     | > postnet_loss: 0.29855218529701233  (0.3081566384062171)
     | > stopnet_loss: 0.003843641374260187  (0.005644238481181674)
     | > loss: 0.18785357475280762  (0.1940693287178874)
     | > align_error: 0.5290864706039429  (0.5871358383446932)

   --> STEP: 33
     | > decoder_loss: 0.4331936836242676  (0.44516948587966687)
     | > postnet_loss: 0.2960355877876282  (0.30778933384201745)
     | > stopnet_loss: 0.0040206597186625  (0.005595039124741699)
     | > loss: 0.1863279789686203  (0.193834742361849)
     | > align_error: 0.5444117188453674  (0.5858411680568348)

   --> STEP: 34
     | > decoder_loss: 0.4390493929386139  (0.4449894831461065)
     | > postnet_loss: 0.2974962294101715  (0.3074865954763749)
     | > stopnet_loss: 0.003307555103674531  (0.005527760182945605)
     | > loss: 0.18744395673274994  (0.1936467780786402)
     | > align_error: 0.5622363090515137  (0.5851469074978548)

   --> STEP: 35
     | > decoder_loss: 0.43700820207595825  (0.44476144654410227)
     | > postnet_loss: 0.29683324694633484  (0.30718221408980234)
     | > stopnet_loss: 0.0035232403315603733  (0.005470488187191742)
     | > loss: 0.1869836002588272  (0.1934564015695027)
     | > align_error: 0.5314940512180328  (0.5836139687470028)

   --> STEP: 36
     | > decoder_loss: 0.4425157606601715  (0.44469906638065976)
     | > postnet_loss: 0.30116337537765503  (0.307015024125576)
     | > stopnet_loss: 0.0036722125951200724  (0.005420536087411974)
     | > loss: 0.18959200382232666  (0.1933490571876367)
     | > align_error: 0.6323781311511993  (0.584968528813786)

   --> STEP: 37
     | > decoder_loss: 0.43550264835357666  (0.44445051454208995)
     | > postnet_loss: 0.2976973354816437  (0.30676319470276703)
     | > stopnet_loss: 0.0035787243396043777  (0.005370757391525281)
     | > loss: 0.18687871098518372  (0.19317418296594877)
     | > align_error: 0.5172289609909058  (0.5831377296834379)

   --> STEP: 38
     | > decoder_loss: 0.4224284887313843  (0.4438709875470714)
     | > postnet_loss: 0.29020434617996216  (0.3063274355311143)
     | > stopnet_loss: 0.003170768963173032  (0.0053128629592002225)
     | > loss: 0.18132898211479187  (0.19286246715407623)
     | > align_error: 0.5499982833862305  (0.582265638991406)

   --> STEP: 39
     | > decoder_loss: 0.4389306306838989  (0.44374431173006695)
     | > postnet_loss: 0.3010641038417816  (0.30619247830831087)
     | > stopnet_loss: 0.0034660096280276775  (0.005265507745580413)
     | > loss: 0.1884647011756897  (0.19274970392386118)
     | > align_error: 0.5442376732826233  (0.5812905629475912)

   --> STEP: 40
     | > decoder_loss: 0.4359602928161621  (0.4435497112572193)
     | > postnet_loss: 0.29972025752067566  (0.30603067278862)
     | > stopnet_loss: 0.0030405267607420683  (0.005209883220959455)
     | > loss: 0.18696066737174988  (0.1926049780100584)
     | > align_error: 0.5824100077152252  (0.581318549066782)

   --> STEP: 41
     | > decoder_loss: 0.4261050820350647  (0.4431242324957034)
     | > postnet_loss: 0.29177939891815186  (0.3056830807429988)
     | > stopnet_loss: 0.003719167085364461  (0.005173524290822991)
     | > loss: 0.18319028615951538  (0.19237535137955736)
     | > align_error: 0.5013327896595001  (0.5793676768861166)

   --> STEP: 42
     | > decoder_loss: 0.4323565661907196  (0.4428678594884418)
     | > postnet_loss: 0.29482585191726685  (0.30542457529476713)
     | > stopnet_loss: 0.003275634255260229  (0.005128336432833402)
     | > loss: 0.18507122993469238  (0.1922014437261082)
     | > align_error: 0.5778369903564453  (0.5793312319687435)

   --> STEP: 43
     | > decoder_loss: 0.4305533170700073  (0.4425814747810364)
     | > postnet_loss: 0.29318928718566895  (0.30514003371083465)
     | > stopnet_loss: 0.0029579591937363148  (0.005077862543552075)
     | > loss: 0.1838936060667038  (0.19200823819914528)
     | > align_error: 0.5501145124435425  (0.5786517733751342)

   --> STEP: 44
     | > decoder_loss: 0.4486289322376251  (0.44271891699595883)
     | > postnet_loss: 0.30389896035194397  (0.3051118274981326)
     | > stopnet_loss: 0.0026512600015848875  (0.005022712485780094)
     | > loss: 0.19078323245048523  (0.19198039715940302)
     | > align_error: 0.5492044389247894  (0.5779825157739901)

   --> STEP: 45
     | > decoder_loss: 0.4412514567375183  (0.4426863067679935)
     | > postnet_loss: 0.3028091788291931  (0.3050606575277117)
     | > stopnet_loss: 0.003300387877970934  (0.004984438605606557)
     | > loss: 0.1893155425786972  (0.19192117816872067)
     | > align_error: 0.5507556200027466  (0.5773774736457402)

   --> STEP: 46
     | > decoder_loss: 0.4311576783657074  (0.44243568441142206)
     | > postnet_loss: 0.293699711561203  (0.30481368044148327)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34464296427640045 (-0.01682838887879351)
     | > avg_decoder_loss: 0.4386731164925026 (+0.0001251173741889655)
     | > avg_postnet_loss: 0.3017851732897036 (+0.0007617329106187065)
     | > avg_stopnet_loss: 0.004383010119481972 (+2.9732674275607766e-05)
     | > avg_loss: 0.18949758193709634 (+0.00025144558061254707)
     | > avg_align_error: 0.5701609940239879 (-0.0014627332037143725)


 > EPOCH: 138/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 17:25:52)

   --> TIME: 2025-12-28 17:26:08 -- STEP: 12/150 -- GLOBAL_STEP: 20850
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.47907310724258423  (0.4646283561984698)
     | > postnet_loss: 0.40437471866607666  (0.39453185846408206)
     | > stopnet_loss: 0.009231642819941044  (0.01166432537138462)
     | > loss: 0.2300935983657837  (0.22645437841614088)
     | > align_error: 0.669149249792099  (0.6871544147531191)
     | > grad_norm: tensor(0.2501, device='cuda:0')  (tensor(0.3123, device='cuda:0'))
     | > step_time: 0.5867  (0.5284238855044048)
     | > loader_time: 0.7636  (0.7386413216590881)


   --> TIME: 2025-12-28 17:26:54 -- STEP: 37/150 -- GLOBAL_STEP: 20875
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.478746235370636  (0.4717586217699824)
     | > postnet_loss: 0.39885708689689636  (0.3967384075796282)
     | > stopnet_loss: 0.005728922318667173  (0.008370271984588456)
     | > loss: 0.22512973845005035  (0.22549452854169383)
     | > align_error: 0.6218328475952148  (0.6578808426856995)
     | > grad_norm: tensor(0.2594, device='cuda:0')  (tensor(0.2640, device='cuda:0'))
     | > step_time: 1.0674  (0.7782937707127752)
     | > loader_time: 0.9906  (0.8788525542697391)


   --> TIME: 2025-12-28 17:27:55 -- STEP: 62/150 -- GLOBAL_STEP: 20900
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.47898197174072266  (0.47603939473629)
     | > postnet_loss: 0.394273966550827  (0.39711967495179945)
     | > stopnet_loss: 0.004075981210917234  (0.00688415831480656)
     | > loss: 0.22238996624946594  (0.225173924959475)
     | > align_error: 0.5766152739524841  (0.6400950089577706)
     | > grad_norm: tensor(0.2115, device='cuda:0')  (tensor(0.2366, device='cuda:0'))
     | > step_time: 1.4641  (0.9857290060289444)
     | > loader_time: 1.2563  (0.986419189360834)


   --> TIME: 2025-12-28 17:29:08 -- STEP: 87/150 -- GLOBAL_STEP: 20925
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4736383259296417  (0.4781460162551924)
     | > postnet_loss: 0.38689401745796204  (0.3966930799785702)
     | > stopnet_loss: 0.0034593017771840096  (0.006037396191480173)
     | > loss: 0.21859239041805267  (0.2247471696343915)
     | > align_error: 0.6020561158657074  (0.6325418085887516)
     | > grad_norm: tensor(0.1436, device='cuda:0')  (tensor(0.2187, device='cuda:0'))
     | > step_time: 1.7367  (1.1483895751251567)
     | > loader_time: 1.496  (1.0932364683041627)


   --> TIME: 2025-12-28 17:30:32 -- STEP: 112/150 -- GLOBAL_STEP: 20950
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47847980260849  (0.479243186169437)
     | > postnet_loss: 0.3906020224094391  (0.3961246002997671)
     | > stopnet_loss: 0.0035511068999767303  (0.005476692622843464)
     | > loss: 0.2208215743303299  (0.22431863924222334)
     | > align_error: 0.6384782791137695  (0.6276683972350191)
     | > grad_norm: tensor(0.1104, device='cuda:0')  (tensor(0.2070, device='cuda:0'))
     | > step_time: 1.7849  (1.2918371068579806)
     | > loader_time: 1.6083  (1.1984740155083788)


   --> TIME: 2025-12-28 17:32:08 -- STEP: 137/150 -- GLOBAL_STEP: 20975
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4950517416000366  (0.4803140335274439)
     | > postnet_loss: 0.40069475769996643  (0.39572324543973825)
     | > stopnet_loss: 0.0030250900890678167  (0.005056455770480263)
     | > loss: 0.22696170210838318  (0.22406577563633884)
     | > align_error: 0.596863329410553  (0.6244388916631687)
     | > grad_norm: tensor(0.1913, device='cuda:0')  (tensor(0.2001, device='cuda:0'))
     | > step_time: 2.2829  (1.4159423400015723)
     | > loader_time: 2.4428  (1.3163000023278002)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46131035685539246  (0.46131035685539246)
     | > postnet_loss: 0.33562034368515015  (0.33562034368515015)
     | > stopnet_loss: 0.012174592353403568  (0.012174592353403568)
     | > loss: 0.21140725910663605  (0.21140725910663605)
     | > align_error: 0.719422310590744  (0.719422310590744)

   --> STEP: 1
     | > decoder_loss: 0.4424768090248108  (0.4424768090248108)
     | > postnet_loss: 0.32389962673187256  (0.32389962673187256)
     | > stopnet_loss: 0.009676488116383553  (0.009676488116383553)
     | > loss: 0.20127059519290924  (0.20127059519290924)
     | > align_error: 0.6599840819835663  (0.6599840819835663)

   --> STEP: 2
     | > decoder_loss: 0.437173992395401  (0.4398254007101059)
     | > postnet_loss: 0.3133266866207123  (0.3186131566762924)
     | > stopnet_loss: 0.011025107465684414  (0.010350797791033983)
     | > loss: 0.1986502707004547  (0.19996043294668198)
     | > align_error: 0.656126856803894  (0.6580554693937302)

   --> STEP: 3
     | > decoder_loss: 0.4424377679824829  (0.44069618980089825)
     | > postnet_loss: 0.31364792585372925  (0.31695807973543805)
     | > stopnet_loss: 0.008277288638055325  (0.00965962807337443)
     | > loss: 0.19729870557785034  (0.19907319049040476)
     | > align_error: 0.735497772693634  (0.6838695704936981)

   --> STEP: 4
     | > decoder_loss: 0.44632068276405334  (0.442102313041687)
     | > postnet_loss: 0.32086241245269775  (0.31793416291475296)
     | > stopnet_loss: 0.008155369199812412  (0.009283563354983926)
     | > loss: 0.1999511420726776  (0.19929267838597298)
     | > align_error: 0.603968471288681  (0.6638942956924438)

   --> STEP: 5
     | > decoder_loss: 0.4325312376022339  (0.4401880979537964)
     | > postnet_loss: 0.3055553734302521  (0.31545840501785277)
     | > stopnet_loss: 0.008085088804364204  (0.009043868444859982)
     | > loss: 0.19260673224925995  (0.19795548915863037)
     | > align_error: 0.644304096698761  (0.6599762558937072)

   --> STEP: 6
     | > decoder_loss: 0.4454048275947571  (0.4410575528939565)
     | > postnet_loss: 0.3156145513057709  (0.3154844293991725)
     | > stopnet_loss: 0.0072514633648097515  (0.00874513426485161)
     | > loss: 0.19750629365444183  (0.19788062324126562)
     | > align_error: 0.5944364070892334  (0.6490529477596283)

   --> STEP: 7
     | > decoder_loss: 0.45632243156433105  (0.44323824984686716)
     | > postnet_loss: 0.3149181604385376  (0.3154035338333675)
     | > stopnet_loss: 0.006237223278731108  (0.008386861266834396)
     | > loss: 0.19904737174510956  (0.19804730159895761)
     | > align_error: 0.5797456502914429  (0.6391519052641732)

   --> STEP: 8
     | > decoder_loss: 0.4499184489250183  (0.44407327473163605)
     | > postnet_loss: 0.3152015805244446  (0.3153782896697521)
     | > stopnet_loss: 0.0072914911434054375  (0.008249940001405776)
     | > loss: 0.19857150316238403  (0.1981128267943859)
     | > align_error: 0.5756397247314453  (0.6312128826975822)

   --> STEP: 9
     | > decoder_loss: 0.44759848713874817  (0.44446496499909294)
     | > postnet_loss: 0.31458333134651184  (0.3152899609671699)
     | > stopnet_loss: 0.006704346276819706  (0.008078207365340657)
     | > loss: 0.19724979996681213  (0.1980169349246555)
     | > align_error: 0.5920225381851196  (0.6268583999739753)

   --> STEP: 10
     | > decoder_loss: 0.4733635187149048  (0.44735482037067414)
     | > postnet_loss: 0.329413503408432  (0.3167023152112961)
     | > stopnet_loss: 0.0055548809468746185  (0.007825874723494053)
     | > loss: 0.2062491476535797  (0.1988401561975479)
     | > align_error: 0.584671139717102  (0.622639673948288)

   --> STEP: 11
     | > decoder_loss: 0.45980745553970337  (0.44848687811331317)
     | > postnet_loss: 0.3188987672328949  (0.31690199266780505)
     | > stopnet_loss: 0.005931403487920761  (0.007653650065714663)
     | > loss: 0.20060795545578003  (0.19900086522102356)
     | > align_error: 0.5956592559814453  (0.620186908678575)

   --> STEP: 12
     | > decoder_loss: 0.4577959179878235  (0.449262631436189)
     | > postnet_loss: 0.3136814534664154  (0.3166336144010226)
     | > stopnet_loss: 0.007903107441961765  (0.007674438180401921)
     | > loss: 0.2007724493741989  (0.19914849723378816)
     | > align_error: 0.5881136059761047  (0.6175141334533691)

   --> STEP: 13
     | > decoder_loss: 0.4470697343349457  (0.4490939470437857)
     | > postnet_loss: 0.31352514028549194  (0.31639450100752026)
     | > stopnet_loss: 0.00559741398319602  (0.0075146670883091595)
     | > loss: 0.19574612379074097  (0.19888677619970763)
     | > align_error: 0.586415022611618  (0.6151218941578498)

   --> STEP: 14
     | > decoder_loss: 0.45844942331314087  (0.4497621953487396)
     | > postnet_loss: 0.316425085067749  (0.31639668558325085)
     | > stopnet_loss: 0.004938094411045313  (0.007330626182790313)
     | > loss: 0.19865672290325165  (0.19887034382138932)
     | > align_error: 0.5557149052619934  (0.6108785378081458)

   --> STEP: 15
     | > decoder_loss: 0.45627453923225403  (0.4501963516076406)
     | > postnet_loss: 0.3157535195350647  (0.31635380784670514)
     | > stopnet_loss: 0.004992916248738766  (0.007174778853853544)
     | > loss: 0.19799993932247162  (0.1988123168547948)
     | > align_error: 0.5893624424934387  (0.609444131453832)

   --> STEP: 16
     | > decoder_loss: 0.4564877152442932  (0.4505895618349314)
     | > postnet_loss: 0.3097163438796997  (0.3159389663487673)
     | > stopnet_loss: 0.005261657293885946  (0.007055208756355569)
     | > loss: 0.1968126744031906  (0.19868733920156956)
     | > align_error: 0.6067229509353638  (0.6092740576714277)

   --> STEP: 17
     | > decoder_loss: 0.46282675862312317  (0.4513093969401191)
     | > postnet_loss: 0.3177512586116791  (0.3160455717759974)
     | > stopnet_loss: 0.004838910885155201  (0.006924838293343782)
     | > loss: 0.1999834179878235  (0.19876357913017273)
     | > align_error: 0.5590607523918152  (0.6063203338314506)

   --> STEP: 18
     | > decoder_loss: 0.45751819014549255  (0.4516543298959732)
     | > postnet_loss: 0.3105931282043457  (0.31574265824423897)
     | > stopnet_loss: 0.0052462415769696236  (0.006831582920211885)
     | > loss: 0.1972740739583969  (0.19868082884285185)
     | > align_error: 0.6045684516429901  (0.6062230070432028)

   --> STEP: 19
     | > decoder_loss: 0.4544302821159363  (0.4518004326443923)
     | > postnet_loss: 0.30964285135269165  (0.31542161577626276)
     | > stopnet_loss: 0.004779885523021221  (0.006723598846675534)
     | > loss: 0.19579817354679108  (0.19852911014305918)
     | > align_error: 0.6008534133434296  (0.6059403968484778)

   --> STEP: 20
     | > decoder_loss: 0.4512103199958801  (0.4517709270119667)
     | > postnet_loss: 0.3060168921947479  (0.31495137959718705)
     | > stopnet_loss: 0.004517537076026201  (0.006613295758143067)
     | > loss: 0.19382433593273163  (0.1982938714325428)
     | > align_error: 0.6234195828437805  (0.606814356148243)

   --> STEP: 21
     | > decoder_loss: 0.44820404052734375  (0.4516010752746037)
     | > postnet_loss: 0.30536285042762756  (0.31449478297006517)
     | > stopnet_loss: 0.003971451427787542  (0.006487493647173757)
     | > loss: 0.1923631727695465  (0.19801145721049535)
     | > align_error: 0.5605872273445129  (0.6046130643004463)

   --> STEP: 22
     | > decoder_loss: 0.4509410858154297  (0.4515710757537322)
     | > postnet_loss: 0.30812573432922363  (0.3142052807591178)
     | > stopnet_loss: 0.004867063835263252  (0.00641383774663237)
     | > loss: 0.19463376700878143  (0.19785792583769019)
     | > align_error: 0.6262514591217041  (0.6055966277014125)

   --> STEP: 23
     | > decoder_loss: 0.4241463243961334  (0.4503786952599235)
     | > postnet_loss: 0.2961210608482361  (0.3134190103282099)
     | > stopnet_loss: 0.004484421107918024  (0.006329950066688268)
     | > loss: 0.18455126881599426  (0.19727937553239905)
     | > align_error: 0.5680935382843018  (0.6039660585963208)

   --> STEP: 24
     | > decoder_loss: 0.45890742540359497  (0.45073405901590985)
     | > postnet_loss: 0.31167706847190857  (0.3133464294175307)
     | > stopnet_loss: 0.004394390620291233  (0.006249301756421725)
     | > loss: 0.19704051315784454  (0.19726942293345928)
     | > align_error: 0.5804463624954224  (0.6029860712587833)

   --> STEP: 25
     | > decoder_loss: 0.4575652480125427  (0.45100730657577515)
     | > postnet_loss: 0.30885258316993713  (0.31316667556762695)
     | > stopnet_loss: 0.003703468479216099  (0.0061474684253335)
     | > loss: 0.19530794024467468  (0.1971909636259079)
     | > align_error: 0.558853417634964  (0.6012207651138306)

   --> STEP: 26
     | > decoder_loss: 0.4326876401901245  (0.4503027040224809)
     | > postnet_loss: 0.29780709743499756  (0.3125759225625258)
     | > stopnet_loss: 0.00433521019294858  (0.006077766185626388)
     | > loss: 0.1869588941335678  (0.19679742249158713)
     | > align_error: 0.5474730134010315  (0.5991535438941076)

   --> STEP: 27
     | > decoder_loss: 0.4288250803947449  (0.4495072364807129)
     | > postnet_loss: 0.29208242893218994  (0.3118169042799208)
     | > stopnet_loss: 0.003912233281880617  (0.005997561263265433)
     | > loss: 0.18413911759853363  (0.196328596384437)
     | > align_error: 0.5418470799922943  (0.5970310822681144)

   --> STEP: 28
     | > decoder_loss: 0.4347679018974304  (0.4489808316741671)
     | > postnet_loss: 0.2970597445964813  (0.3112898628626551)
     | > stopnet_loss: 0.003933231346309185  (0.00592383519480271)
     | > loss: 0.1868901401758194  (0.19599150866270065)
     | > align_error: 0.567115068435669  (0.59596265320267)

   --> STEP: 29
     | > decoder_loss: 0.4301890730857849  (0.44833283999870566)
     | > postnet_loss: 0.293954998254776  (0.31069210891065924)
     | > stopnet_loss: 0.0035835278686136007  (0.005843134942175499)
     | > loss: 0.18461954593658447  (0.1955993720169725)
     | > align_error: 0.5410738587379456  (0.5940699361521622)

   --> STEP: 30
     | > decoder_loss: 0.4305649995803833  (0.44774057865142824)
     | > postnet_loss: 0.29452285170555115  (0.31015313367048897)
     | > stopnet_loss: 0.0028153888415545225  (0.0057422100721548)
     | > loss: 0.1840873658657074  (0.195215638478597)
     | > align_error: 0.5340461730957031  (0.5920691440502802)

   --> STEP: 31
     | > decoder_loss: 0.4304111897945404  (0.44718156610765764)
     | > postnet_loss: 0.29448744654655457  (0.30964778892455563)
     | > stopnet_loss: 0.0037091050762683153  (0.00567662604002943)
     | > loss: 0.18493376672267914  (0.19488396519614803)
     | > align_error: 0.559909999370575  (0.5910317522864188)

   --> STEP: 32
     | > decoder_loss: 0.4395242929458618  (0.44694227632135153)
     | > postnet_loss: 0.2996870279312134  (0.3093365151435137)
     | > stopnet_loss: 0.003831700887531042  (0.005618972129013855)
     | > loss: 0.18863452970981598  (0.19468867033720016)
     | > align_error: 0.531983345746994  (0.5891864895820618)

   --> STEP: 33
     | > decoder_loss: 0.43564003705978394  (0.44659978422251617)
     | > postnet_loss: 0.29668545722961426  (0.3089531497521834)
     | > stopnet_loss: 0.0040087322704494  (0.005570176981784629)
     | > loss: 0.18709009885787964  (0.1944584105954026)
     | > align_error: 0.5466218590736389  (0.5878966522939277)

   --> STEP: 34
     | > decoder_loss: 0.4416216313838959  (0.44645336796255675)
     | > postnet_loss: 0.2983880937099457  (0.3086424128097646)
     | > stopnet_loss: 0.003286539576947689  (0.005503011175760013)
     | > loss: 0.18828897178173065  (0.1942769565126475)
     | > align_error: 0.564312607049942  (0.5872030039043987)

   --> STEP: 35
     | > decoder_loss: 0.43899059295654297  (0.44624014581952776)
     | > postnet_loss: 0.297604501247406  (0.308327043907983)
     | > stopnet_loss: 0.003506939159706235  (0.005445980546729905)
     | > loss: 0.1876557171344757  (0.19408777824469975)
     | > align_error: 0.5336568355560303  (0.5856731133801597)

   --> STEP: 36
     | > decoder_loss: 0.4443639814853668  (0.44618803014357883)
     | > postnet_loss: 0.30158230662345886  (0.308139690094524)
     | > stopnet_loss: 0.0036619710735976696  (0.005396424728031787)
     | > loss: 0.19014854729175568  (0.19397835516267353)
     | > align_error: 0.6342879831790924  (0.5870235264301301)

   --> STEP: 37
     | > decoder_loss: 0.43715351819992065  (0.4459438541451016)
     | > postnet_loss: 0.2983648478984833  (0.3078755051703067)
     | > stopnet_loss: 0.0035731380339711905  (0.005347146709273392)
     | > loss: 0.18745271861553192  (0.19380198660734538)
     | > align_error: 0.519436240196228  (0.585196843018403)

   --> STEP: 38
     | > decoder_loss: 0.4246949851512909  (0.4453846733821066)
     | > postnet_loss: 0.29100537300109863  (0.3074315543237486)
     | > stopnet_loss: 0.0031489392276853323  (0.005289299143968443)
     | > loss: 0.18207404017448425  (0.19349335643805957)
     | > align_error: 0.5523140132427216  (0.5843315053927272)

   --> STEP: 39
     | > decoder_loss: 0.44018542766571045  (0.4452513593893785)
     | > postnet_loss: 0.30176010727882385  (0.30728613260464793)
     | > stopnet_loss: 0.003482051892206073  (0.005242959470846331)
     | > loss: 0.18896843492984772  (0.19337733280964386)
     | > align_error: 0.5464820861816406  (0.5833610074642378)

   --> STEP: 40
     | > decoder_loss: 0.437125027179718  (0.44504820108413695)
     | > postnet_loss: 0.3001023530960083  (0.30710653811693195)
     | > stopnet_loss: 0.0030337630305439234  (0.00518772955983877)
     | > loss: 0.1873406022787094  (0.19322641454637052)
     | > align_error: 0.5843835473060608  (0.5833865709602833)

   --> STEP: 41
     | > decoder_loss: 0.42838117480278015  (0.4446416882480063)
     | > postnet_loss: 0.29277709126472473  (0.3067570394132196)
     | > stopnet_loss: 0.003711964702233672  (0.005151735295019134)
     | > loss: 0.18400153517723083  (0.19300141748858662)
     | > align_error: 0.5037024021148682  (0.5814430546469805)

   --> STEP: 42
     | > decoder_loss: 0.4327194094657898  (0.44435782446747735)
     | > postnet_loss: 0.294208824634552  (0.3064582723946799)
     | > stopnet_loss: 0.0032678109128028154  (0.005106879952585412)
     | > loss: 0.18499986827373505  (0.19281090441204252)
     | > align_error: 0.5798997282981873  (0.5814063087815331)

   --> STEP: 43
     | > decoder_loss: 0.43156951665878296  (0.4440604219602984)
     | > postnet_loss: 0.2930682599544525  (0.30614687675653507)
     | > stopnet_loss: 0.0029223996680229902  (0.005056078085502565)
     | > loss: 0.18408183753490448  (0.19260790285676024)
     | > align_error: 0.5521681308746338  (0.5807263511557913)

   --> STEP: 44
     | > decoder_loss: 0.4489164352416992  (0.44417078589851205)
     | > postnet_loss: 0.3037640154361725  (0.30609272081743594)
     | > stopnet_loss: 0.0026519710663706064  (0.005001439289613203)
     | > loss: 0.1908220797777176  (0.1925673159686002)
     | > align_error: 0.5514517426490784  (0.5800610191442751)

   --> STEP: 45
     | > decoder_loss: 0.4429164528846741  (0.44414291183153787)
     | > postnet_loss: 0.3033803105354309  (0.3060324450333914)
     | > stopnet_loss: 0.0032823707442730665  (0.0049632377663834226)
     | > loss: 0.18985655903816223  (0.19250707692570157)
     | > align_error: 0.5529675483703613  (0.5794589420159659)

   --> STEP: 46
     | > decoder_loss: 0.4327259659767151  (0.44389471735643304)
     | > postnet_loss: 0.2943078875541687  (0.3057775633490605)
     | > stopnet_loss: 0.0031996257603168488  (0.004924898374947193)
     | > loss: 0.1849580854177475  (0.1923429684146591)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3617118922146884 (+0.01706892793828796)
     | > avg_decoder_loss: 0.4397388339945764 (+0.001065717502073793)
     | > avg_postnet_loss: 0.3025424832647497 (+0.0007573099750460832)
     | > avg_stopnet_loss: 0.004365916490893471 (-1.7093628588500838e-05)
     | > avg_loss: 0.1899362454811732 (+0.00043866354407684494)
     | > avg_align_error: 0.5722576452024055 (+0.002096651178417619)


 > EPOCH: 139/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 17:35:00)

   --> TIME: 2025-12-28 17:35:15 -- STEP: 11/150 -- GLOBAL_STEP: 21000
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46897709369659424  (0.4629240875894373)
     | > postnet_loss: 0.3972919285297394  (0.3934368274428628)
     | > stopnet_loss: 0.009901389479637146  (0.011994768780740824)
     | > loss: 0.22646863758563995  (0.22608499770814722)
     | > align_error: 0.6737316250801086  (0.6904715868559751)
     | > grad_norm: tensor(0.2134, device='cuda:0')  (tensor(0.3140, device='cuda:0'))
     | > step_time: 0.5586  (0.5187331763180819)
     | > loader_time: 0.6036  (0.7925902279940519)


   --> TIME: 2025-12-28 17:36:00 -- STEP: 36/150 -- GLOBAL_STEP: 21025
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.48925521969795227  (0.47160740362273323)
     | > postnet_loss: 0.4067709445953369  (0.39662451379828983)
     | > stopnet_loss: 0.005816606339067221  (0.008449678386872014)
     | > loss: 0.22982314229011536  (0.22550765756103727)
     | > align_error: 0.6165908873081207  (0.6599315421448815)
     | > grad_norm: tensor(0.3982, device='cuda:0')  (tensor(0.2876, device='cuda:0'))
     | > step_time: 1.0779  (0.7540125714408027)
     | > loader_time: 0.9681  (0.8995811144510905)


   --> TIME: 2025-12-28 17:37:00 -- STEP: 61/150 -- GLOBAL_STEP: 21050
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.4852024018764496  (0.47628763611199426)
     | > postnet_loss: 0.3985525667667389  (0.397340761344941)
     | > stopnet_loss: 0.004243231378495693  (0.006930574484658046)
     | > loss: 0.2251819670200348  (0.2253376731618506)
     | > align_error: 0.6034256815910339  (0.6420938006190006)
     | > grad_norm: tensor(0.2960, device='cuda:0')  (tensor(0.2542, device='cuda:0'))
     | > step_time: 1.387  (0.9615803468422811)
     | > loader_time: 1.3519  (0.9865966937581047)


   --> TIME: 2025-12-28 17:38:15 -- STEP: 86/150 -- GLOBAL_STEP: 21075
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4821500778198242  (0.478664139329001)
     | > postnet_loss: 0.3943074941635132  (0.397106995416242)
     | > stopnet_loss: 0.0037097155582159758  (0.006034142267348808)
     | > loss: 0.2228241115808487  (0.22497692582912224)
     | > align_error: 0.582981139421463  (0.6338884431955426)
     | > grad_norm: tensor(0.1998, device='cuda:0')  (tensor(0.2376, device='cuda:0'))
     | > step_time: 1.5751  (1.1340247891670048)
     | > loader_time: 1.5287  (1.126168519951577)


   --> TIME: 2025-12-28 17:39:43 -- STEP: 111/150 -- GLOBAL_STEP: 21100
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4790339469909668  (0.4797708327705796)
     | > postnet_loss: 0.39015650749206543  (0.39651500292726466)
     | > stopnet_loss: 0.0033511549700051546  (0.0054620111734514035)
     | > loss: 0.22064876556396484  (0.22453347049854896)
     | > align_error: 0.5805829167366028  (0.628623321518168)
     | > grad_norm: tensor(0.1455, device='cuda:0')  (tensor(0.2222, device='cuda:0'))
     | > step_time: 1.7199  (1.2639419710313953)
     | > loader_time: 1.6705  (1.276436068990209)


   --> TIME: 2025-12-28 17:41:16 -- STEP: 136/150 -- GLOBAL_STEP: 21125
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4892369508743286  (0.4806541197878473)
     | > postnet_loss: 0.39677321910858154  (0.39597299234832034)
     | > stopnet_loss: 0.003228449961170554  (0.005043119062012171)
     | > loss: 0.22473099827766418  (0.22419989711659796)
     | > align_error: 0.5997294485569  (0.6255563418654837)
     | > grad_norm: tensor(0.2547, device='cuda:0')  (tensor(0.2154, device='cuda:0'))
     | > step_time: 1.9603  (1.3918203606325037)
     | > loader_time: 1.8496  (1.3656233759487377)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45930662751197815  (0.45930662751197815)
     | > postnet_loss: 0.33410364389419556  (0.33410364389419556)
     | > stopnet_loss: 0.012112877331674099  (0.012112877331674099)
     | > loss: 0.2104654461145401  (0.2104654461145401)
     | > align_error: 0.7185719907283783  (0.7185719907283783)

   --> STEP: 1
     | > decoder_loss: 0.44143959879875183  (0.44143959879875183)
     | > postnet_loss: 0.32265999913215637  (0.32265999913215637)
     | > stopnet_loss: 0.009687216021120548  (0.009687216021120548)
     | > loss: 0.20071211457252502  (0.20071211457252502)
     | > align_error: 0.659712940454483  (0.659712940454483)

   --> STEP: 2
     | > decoder_loss: 0.43626025319099426  (0.43884992599487305)
     | > postnet_loss: 0.3121289908885956  (0.317394495010376)
     | > stopnet_loss: 0.011039734818041325  (0.010363475419580936)
     | > loss: 0.1981370449066162  (0.19942457973957062)
     | > align_error: 0.6554668247699738  (0.6575898826122284)

   --> STEP: 3
     | > decoder_loss: 0.4394918978214264  (0.4390639166037242)
     | > postnet_loss: 0.31154006719589233  (0.3154430190722148)
     | > stopnet_loss: 0.008107384666800499  (0.009611445168654123)
     | > loss: 0.19586537778377533  (0.19823817908763885)
     | > align_error: 0.7335956394672394  (0.6829251348972321)

   --> STEP: 4
     | > decoder_loss: 0.444978266954422  (0.4405425041913986)
     | > postnet_loss: 0.3199896812438965  (0.3165796846151352)
     | > stopnet_loss: 0.008116981014609337  (0.009237829130142927)
     | > loss: 0.1993589550256729  (0.19851837307214737)
     | > align_error: 0.6033214330673218  (0.6630242094397545)

   --> STEP: 5
     | > decoder_loss: 0.4269295036792755  (0.437819904088974)
     | > postnet_loss: 0.30220139026641846  (0.31370402574539186)
     | > stopnet_loss: 0.008050256408751011  (0.009000314585864543)
     | > loss: 0.19033297896385193  (0.19688129425048828)
     | > align_error: 0.6423270106315613  (0.6588847696781158)

   --> STEP: 6
     | > decoder_loss: 0.4449109733104706  (0.43900174895922345)
     | > postnet_loss: 0.31507807970046997  (0.31393303473790485)
     | > stopnet_loss: 0.0072352271527051926  (0.008706133347004652)
     | > loss: 0.19723248481750488  (0.19693982601165771)
     | > align_error: 0.5933778285980225  (0.6479669461647669)

   --> STEP: 7
     | > decoder_loss: 0.4552789330482483  (0.44132706097194124)
     | > postnet_loss: 0.31405359506607056  (0.3139502576419285)
     | > stopnet_loss: 0.006168453022837639  (0.008343607586409365)
     | > loss: 0.1985015869140625  (0.19716293471200125)
     | > align_error: 0.5788007378578186  (0.6380860592637744)

   --> STEP: 8
     | > decoder_loss: 0.4489949643611908  (0.44228554889559746)
     | > postnet_loss: 0.3145168125629425  (0.3140210770070553)
     | > stopnet_loss: 0.0070791095495224  (0.008185545331798494)
     | > loss: 0.19795705378055573  (0.19726219959557056)
     | > align_error: 0.5731730461120605  (0.6299719326198101)

   --> STEP: 9
     | > decoder_loss: 0.4471948444843292  (0.44283102618323433)
     | > postnet_loss: 0.31449294090270996  (0.3140735063287947)
     | > stopnet_loss: 0.0066026053391397  (0.008009663110391961)
     | > loss: 0.19702453911304474  (0.19723579287528992)
     | > align_error: 0.5907563865184784  (0.6256146497196622)

   --> STEP: 10
     | > decoder_loss: 0.4722796380519867  (0.44577588737010954)
     | > postnet_loss: 0.32870376110076904  (0.3155365318059921)
     | > stopnet_loss: 0.005494200624525547  (0.00775811686180532)
     | > loss: 0.2057400643825531  (0.19808622002601622)
     | > align_error: 0.5842854678630829  (0.6214817315340042)

   --> STEP: 11
     | > decoder_loss: 0.45961329340934753  (0.44703383337367664)
     | > postnet_loss: 0.3189741373062134  (0.3158490413969213)
     | > stopnet_loss: 0.00587995070964098  (0.0075873744843358345)
     | > loss: 0.20052681863307953  (0.19830809262665836)
     | > align_error: 0.5942608714103699  (0.6190071078864011)

   --> STEP: 12
     | > decoder_loss: 0.4546040892601013  (0.4476646880308787)
     | > postnet_loss: 0.3118051588535309  (0.3155120511849721)
     | > stopnet_loss: 0.00791967287659645  (0.007615066017024219)
     | > loss: 0.1995219886302948  (0.19840925062696138)
     | > align_error: 0.5867023169994354  (0.616315041979154)

   --> STEP: 13
     | > decoder_loss: 0.4444041848182678  (0.4474138800914471)
     | > postnet_loss: 0.3120741844177246  (0.31524759989518386)
     | > stopnet_loss: 0.005566488951444626  (0.007457483165825789)
     | > loss: 0.19468608498573303  (0.19812285326994383)
     | > align_error: 0.5854192972183228  (0.6139384462283208)

   --> STEP: 14
     | > decoder_loss: 0.4554376006126404  (0.44798700298581806)
     | > postnet_loss: 0.31448855996131897  (0.31519338275705067)
     | > stopnet_loss: 0.004897956736385822  (0.0072746598494372195)
     | > loss: 0.19737949967384338  (0.19806975658450807)
     | > align_error: 0.554722249507904  (0.6097087178911481)

   --> STEP: 15
     | > decoder_loss: 0.45377594232559204  (0.4483729322751363)
     | > postnet_loss: 0.31432950496673584  (0.315135790904363)
     | > stopnet_loss: 0.005006350576877594  (0.0071234392312665784)
     | > loss: 0.19703271985054016  (0.19800062080224354)
     | > align_error: 0.5886137783527374  (0.6083023885885874)

   --> STEP: 16
     | > decoder_loss: 0.45492762327194214  (0.4487826004624367)
     | > postnet_loss: 0.3086704909801483  (0.3147317096590996)
     | > stopnet_loss: 0.005227166693657637  (0.007004922197666019)
     | > loss: 0.19612668454647064  (0.19788349978625774)
     | > align_error: 0.6058464050292969  (0.6081488896161318)

   --> STEP: 17
     | > decoder_loss: 0.46206364035606384  (0.4495638381032383)
     | > postnet_loss: 0.3176162838935852  (0.31490139049642224)
     | > stopnet_loss: 0.004811346065253019  (0.006875888307524078)
     | > loss: 0.19973132014274597  (0.19799219510134528)
     | > align_error: 0.5585000514984131  (0.6052283697268542)

   --> STEP: 18
     | > decoder_loss: 0.45518913865089417  (0.4498763548003303)
     | > postnet_loss: 0.3091658353805542  (0.3145827485455407)
     | > stopnet_loss: 0.005260423291474581  (0.006786140251076884)
     | > loss: 0.1963491588830948  (0.1979009153114425)
     | > align_error: 0.6040328741073608  (0.605161953303549)

   --> STEP: 19
     | > decoder_loss: 0.4506330192089081  (0.449916179242887)
     | > postnet_loss: 0.30771636962890625  (0.3142213601815073)
     | > stopnet_loss: 0.0046736919321119785  (0.006674958760605047)
     | > loss: 0.19426104426383972  (0.19770934315104233)
     | > align_error: 0.5990018248558044  (0.6048377360168257)

   --> STEP: 20
     | > decoder_loss: 0.4493975043296814  (0.4498902454972267)
     | > postnet_loss: 0.30522391200065613  (0.3137714877724648)
     | > stopnet_loss: 0.004493970889598131  (0.006565909367054701)
     | > loss: 0.19314931333065033  (0.19748134166002274)
     | > align_error: 0.6231098473072052  (0.6057513415813446)

   --> STEP: 21
     | > decoder_loss: 0.44777658581733704  (0.4497895950362796)
     | > postnet_loss: 0.30485522747039795  (0.3133469039485568)
     | > stopnet_loss: 0.003983617760241032  (0.006442943100063573)
     | > loss: 0.1921415627002716  (0.19722706647146315)
     | > align_error: 0.5598413646221161  (0.6035651522023338)

   --> STEP: 22
     | > decoder_loss: 0.4503526985645294  (0.4498151906512)
     | > postnet_loss: 0.30791327357292175  (0.3130999207496643)
     | > stopnet_loss: 0.004958268254995346  (0.0063754578798331995)
     | > loss: 0.19452476501464844  (0.1971042345870625)
     | > align_error: 0.6257312297821045  (0.6045727011832324)

   --> STEP: 23
     | > decoder_loss: 0.42275893688201904  (0.4486388317916704)
     | > postnet_loss: 0.29513823986053467  (0.31231897810231085)
     | > stopnet_loss: 0.004449869971722364  (0.0062917366664370766)
     | > loss: 0.18392416834831238  (0.19653118822885596)
     | > align_error: 0.5675048828125  (0.602961056906244)

   --> STEP: 24
     | > decoder_loss: 0.4570271968841553  (0.4489883470038573)
     | > postnet_loss: 0.3108692765235901  (0.31225857386986416)
     | > stopnet_loss: 0.004397695418447256  (0.006212818281104167)
     | > loss: 0.19637180864810944  (0.19652454741299152)
     | > align_error: 0.5798993110656738  (0.6020001508295536)

   --> STEP: 25
     | > decoder_loss: 0.4569172263145447  (0.4493055021762848)
     | > postnet_loss: 0.30838853120803833  (0.31210377216339114)
     | > stopnet_loss: 0.0037049909587949514  (0.006112505188211798)
     | > loss: 0.19503143429756165  (0.19646482288837433)
     | > align_error: 0.5585155785083771  (0.6002607679367066)

   --> STEP: 26
     | > decoder_loss: 0.4316728413105011  (0.4486273229122162)
     | > postnet_loss: 0.2971240282058716  (0.311527628165025)
     | > stopnet_loss: 0.004330026917159557  (0.0060439483316328665)
     | > loss: 0.1865292340517044  (0.1960826848561947)
     | > align_error: 0.547147810459137  (0.598217961879877)

   --> STEP: 27
     | > decoder_loss: 0.4287465512752533  (0.4478909980367731)
     | > postnet_loss: 0.292036235332489  (0.3108057247267829)
     | > stopnet_loss: 0.0039068832993507385  (0.005964797774881676)
     | > loss: 0.18410256505012512  (0.19563897671522917)
     | > align_error: 0.5414931774139404  (0.5961170439366941)

   --> STEP: 28
     | > decoder_loss: 0.43338656425476074  (0.4473729825445584)
     | > postnet_loss: 0.29627925157546997  (0.31028692211423603)
     | > stopnet_loss: 0.003924807533621788  (0.005891940980550966)
     | > loss: 0.18634125590324402  (0.19530691525765828)
     | > align_error: 0.5665174126625061  (0.5950599142483303)

   --> STEP: 29
     | > decoder_loss: 0.4291298985481262  (0.44674391068261243)
     | > postnet_loss: 0.2934598922729492  (0.30970667970591576)
     | > stopnet_loss: 0.0035765718203037977  (0.005812100664680374)
     | > loss: 0.18422402441501617  (0.194924746607912)
     | > align_error: 0.5405609607696533  (0.5931806399904448)

   --> STEP: 30
     | > decoder_loss: 0.43036916851997375  (0.44619808594385785)
     | > postnet_loss: 0.2944006025791168  (0.30919647713502246)
     | > stopnet_loss: 0.0028603312093764544  (0.005713708349503577)
     | > loss: 0.18405278027057648  (0.1945623477300008)
     | > align_error: 0.5341048240661621  (0.591211446126302)

   --> STEP: 31
     | > decoder_loss: 0.4259966313838959  (0.4455464261193429)
     | > postnet_loss: 0.2925710380077362  (0.3086601726470455)
     | > stopnet_loss: 0.003700681496411562  (0.005648771999403834)
     | > loss: 0.1833426058292389  (0.19420042057191172)
     | > align_error: 0.5564020872116089  (0.5900885635806669)

   --> STEP: 32
     | > decoder_loss: 0.4372393488883972  (0.4452868299558759)
     | > postnet_loss: 0.29830580949783325  (0.3083365987986326)
     | > stopnet_loss: 0.0038258605636656284  (0.005591806017037015)
     | > loss: 0.1877121478319168  (0.19399766204878688)
     | > align_error: 0.531194806098938  (0.5882481336593628)

   --> STEP: 33
     | > decoder_loss: 0.43445664644241333  (0.44495864257668005)
     | > postnet_loss: 0.29628786444664  (0.30797148563645105)
     | > stopnet_loss: 0.003991947043687105  (0.005543325442087018)
     | > loss: 0.18667806684970856  (0.1937758561336633)
     | > align_error: 0.5460401773452759  (0.5869691046801481)

   --> STEP: 34
     | > decoder_loss: 0.4403080940246582  (0.4448218617369147)
     | > postnet_loss: 0.2977527976036072  (0.3076709359884262)
     | > stopnet_loss: 0.003276074305176735  (0.005476641585119069)
     | > loss: 0.18779130280017853  (0.19359983985914903)
     | > align_error: 0.5637916922569275  (0.5862874160794651)

   --> STEP: 35
     | > decoder_loss: 0.4383208155632019  (0.4446361175605229)
     | > postnet_loss: 0.29744890332221985  (0.3073788779122489)
     | > stopnet_loss: 0.0034981623757630587  (0.005420113607708897)
     | > loss: 0.18744060397148132  (0.19342386169092995)
     | > align_error: 0.5336033701896667  (0.5847821576254708)

   --> STEP: 36
     | > decoder_loss: 0.4437272846698761  (0.4446108722024494)
     | > postnet_loss: 0.3016858696937561  (0.3072207387950685)
     | > stopnet_loss: 0.0036608418449759483  (0.0053712449476329815)
     | > loss: 0.19001413881778717  (0.19332914716667599)
     | > align_error: 0.6339139640331268  (0.5861469300256835)

   --> STEP: 37
     | > decoder_loss: 0.4360829293727875  (0.4443803872611072)
     | > postnet_loss: 0.2979394495487213  (0.30696989313976186)
     | > stopnet_loss: 0.00355337536893785  (0.005322113337397978)
     | > loss: 0.1870589703321457  (0.1931596829279049)
     | > align_error: 0.5191285610198975  (0.5843356227552569)

   --> STEP: 38
     | > decoder_loss: 0.4238045811653137  (0.4438389186796389)
     | > postnet_loss: 0.29080498218536377  (0.3065445007462251)
     | > stopnet_loss: 0.0031395936384797096  (0.005264678608479076)
     | > loss: 0.1817919909954071  (0.1928605331402076)
     | > align_error: 0.5517699122428894  (0.5834786303733525)

   --> STEP: 39
     | > decoder_loss: 0.43955135345458984  (0.4437289811097659)
     | > postnet_loss: 0.30160000920295715  (0.30641771891178227)
     | > stopnet_loss: 0.0034714138600975275  (0.005218697461084678)
     | > loss: 0.18875925242900848  (0.1927553720963307)
     | > align_error: 0.5460432171821594  (0.5825187479838346)

   --> STEP: 40
     | > decoder_loss: 0.43648651242256165  (0.44354791939258575)
     | > postnet_loss: 0.3000606596469879  (0.3062587924301624)
     | > stopnet_loss: 0.0030304149258881807  (0.005163990397704765)
     | > loss: 0.1871672123670578  (0.19261566810309888)
     | > align_error: 0.58399897813797  (0.582555753737688)

   --> STEP: 41
     | > decoder_loss: 0.42768949270248413  (0.4431611284977052)
     | > postnet_loss: 0.29259490966796875  (0.3059255269969382)
     | > stopnet_loss: 0.0037135726306587458  (0.005128614354606082)
     | > loss: 0.18378467857837677  (0.19240027811469101)
     | > align_error: 0.50320103764534  (0.5806202728573868)

   --> STEP: 42
     | > decoder_loss: 0.4320603907108307  (0.44289682521706536)
     | > postnet_loss: 0.2942233085632324  (0.30564690274851664)
     | > stopnet_loss: 0.0032654283568263054  (0.005084252783230373)
     | > loss: 0.18483634293079376  (0.19222018441983632)
     | > align_error: 0.5792838931083679  (0.580588454291934)

   --> STEP: 43
     | > decoder_loss: 0.43098530173301697  (0.44261981304301773)
     | > postnet_loss: 0.2930850088596344  (0.3053547656813333)
     | > stopnet_loss: 0.0029152536299079657  (0.005033810942455433)
     | > loss: 0.183932825922966  (0.19202745515246725)
     | > align_error: 0.5519761741161346  (0.5799230524273805)

   --> STEP: 44
     | > decoder_loss: 0.44879046082496643  (0.442760055038062)
     | > postnet_loss: 0.3037855923175812  (0.3053191026503389)
     | > stopnet_loss: 0.002644794760271907  (0.00497951512013308)
     | > loss: 0.19078880548477173  (0.19199930402365598)
     | > align_error: 0.5510384440422058  (0.5792665840549902)

   --> STEP: 45
     | > decoder_loss: 0.4416969120502472  (0.4427364296383328)
     | > postnet_loss: 0.30288276076316833  (0.3052649617195129)
     | > stopnet_loss: 0.003305655438452959  (0.004942318238317966)
     | > loss: 0.18945057690143585  (0.1919426656431622)
     | > align_error: 0.5525650978088379  (0.5786732176939646)

   --> STEP: 46
     | > decoder_loss: 0.43236762285232544  (0.4425110207951587)
     | > postnet_loss: 0.2943395674228668  (0.3050274531478467)
     | > stopnet_loss: 0.0031966245733201504  (0.004904368376035405)
     | > loss: 0.18487343192100525  (0.19178898664920227)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.348936008684563 (-0.012775883530125431)
     | > avg_decoder_loss: 0.43870313014044904 (-0.0010357038541273789)
     | > avg_postnet_loss: 0.30210619035995373 (-0.00043629290479596516)
     | > avg_stopnet_loss: 0.004351759689267386 (-1.41568016260845e-05)
     | > avg_loss: 0.18955408984964545 (-0.0003821556315277419)
     | > avg_align_error: 0.5716132878354101 (-0.0006443573669954183)


 > EPOCH: 140/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 17:44:13)

   --> TIME: 2025-12-28 17:44:27 -- STEP: 10/150 -- GLOBAL_STEP: 21150
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.465472936630249  (0.46406497061252594)
     | > postnet_loss: 0.393627792596817  (0.3940430819988251)
     | > stopnet_loss: 0.00936655979603529  (0.012203570082783699)
     | > loss: 0.22414173185825348  (0.2267305836081505)
     | > align_error: 0.6516643762588501  (0.6919225871562957)
     | > grad_norm: tensor(0.2867, device='cuda:0')  (tensor(0.2802, device='cuda:0'))
     | > step_time: 0.5701  (0.531716251373291)
     | > loader_time: 0.7413  (0.7584920883178711)


   --> TIME: 2025-12-28 17:45:12 -- STEP: 35/150 -- GLOBAL_STEP: 21175
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4885806739330292  (0.47127111639295305)
     | > postnet_loss: 0.40392130613327026  (0.3962468581540244)
     | > stopnet_loss: 0.005636426620185375  (0.00852831910763468)
     | > loss: 0.22876191139221191  (0.22540781199932097)
     | > align_error: 0.6092197299003601  (0.661370700597763)
     | > grad_norm: tensor(0.1997, device='cuda:0')  (tensor(0.2470, device='cuda:0'))
     | > step_time: 1.0282  (0.7660940102168492)
     | > loader_time: 1.1121  (0.8908440930502756)


   --> TIME: 2025-12-28 17:46:11 -- STEP: 60/150 -- GLOBAL_STEP: 21200
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.4806630611419678  (0.47614397754271826)
     | > postnet_loss: 0.3951405882835388  (0.3971749077240626)
     | > stopnet_loss: 0.004148907493799925  (0.006954429997131229)
     | > loss: 0.22309981286525726  (0.22528415123621623)
     | > align_error: 0.6226916015148163  (0.6425678998231886)
     | > grad_norm: tensor(0.1293, device='cuda:0')  (tensor(0.2248, device='cuda:0'))
     | > step_time: 1.3083  (0.9624976754188538)
     | > loader_time: 1.2069  (0.9928301056226094)


   --> TIME: 2025-12-28 17:47:22 -- STEP: 85/150 -- GLOBAL_STEP: 21225
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4835767149925232  (0.4783919667496401)
     | > postnet_loss: 0.39504390954971313  (0.3968259923598346)
     | > stopnet_loss: 0.004098291043192148  (0.006077922182157636)
     | > loss: 0.2237534523010254  (0.22488241230740266)
     | > align_error: 0.5851673781871796  (0.6340266490683839)
     | > grad_norm: tensor(0.2747, device='cuda:0')  (tensor(0.2230, device='cuda:0'))
     | > step_time: 1.5453  (1.1184424764969774)
     | > loader_time: 1.6121  (1.0985753395978144)


   --> TIME: 2025-12-28 17:48:47 -- STEP: 110/150 -- GLOBAL_STEP: 21250
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4852904975414276  (0.47964561473239553)
     | > postnet_loss: 0.39451783895492554  (0.39635579450563957)
     | > stopnet_loss: 0.0033071727957576513  (0.005492515057664026)
     | > loss: 0.22325925529003143  (0.22449286742643876)
     | > align_error: 0.6029196083545685  (0.6286623537540439)
     | > grad_norm: tensor(0.3354, device='cuda:0')  (tensor(0.2159, device='cuda:0'))
     | > step_time: 1.8123  (1.2592875155535614)
     | > loader_time: 1.6442  (1.2191247441551898)


   --> TIME: 2025-12-28 17:50:20 -- STEP: 135/150 -- GLOBAL_STEP: 21275
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49115681648254395  (0.4804803960853153)
     | > postnet_loss: 0.3974352478981018  (0.3957869953579373)
     | > stopnet_loss: 0.0029168196488171816  (0.005068308299545337)
     | > loss: 0.22506482899188995  (0.22413515636214504)
     | > align_error: 0.6183142364025116  (0.6255896391691987)
     | > grad_norm: tensor(0.1228, device='cuda:0')  (tensor(0.2043, device='cuda:0'))
     | > step_time: 2.2346  (1.38696217890139)
     | > loader_time: 2.0418  (1.3277211100966837)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4604616165161133  (0.4604616165161133)
     | > postnet_loss: 0.33407801389694214  (0.33407801389694214)
     | > stopnet_loss: 0.012128880247473717  (0.012128880247473717)
     | > loss: 0.21076378226280212  (0.21076378226280212)
     | > align_error: 0.7190845906734467  (0.7190845906734467)

   --> STEP: 1
     | > decoder_loss: 0.44274529814720154  (0.44274529814720154)
     | > postnet_loss: 0.32271432876586914  (0.32271432876586914)
     | > stopnet_loss: 0.00964095164090395  (0.00964095164090395)
     | > loss: 0.20100586116313934  (0.20100586116313934)
     | > align_error: 0.6596949100494385  (0.6596949100494385)

   --> STEP: 2
     | > decoder_loss: 0.4381450414657593  (0.4404451698064804)
     | > postnet_loss: 0.3128948509693146  (0.31780458986759186)
     | > stopnet_loss: 0.01093614287674427  (0.01028854725882411)
     | > loss: 0.198696106672287  (0.19985098391771317)
     | > align_error: 0.6555701196193695  (0.657632514834404)

   --> STEP: 3
     | > decoder_loss: 0.44009071588516235  (0.4403270184993744)
     | > postnet_loss: 0.31146901845932007  (0.3156927327315013)
     | > stopnet_loss: 0.008132518269121647  (0.009569870928923288)
     | > loss: 0.19602245092391968  (0.19857480625311533)
     | > align_error: 0.7349412739276886  (0.6834021011988322)

   --> STEP: 4
     | > decoder_loss: 0.4461948275566101  (0.4417939707636833)
     | > postnet_loss: 0.32060298323631287  (0.31692029535770416)
     | > stopnet_loss: 0.00817549042403698  (0.009221275802701712)
     | > loss: 0.19987493753433228  (0.19889983907341957)
     | > align_error: 0.603500247001648  (0.6634266376495361)

   --> STEP: 5
     | > decoder_loss: 0.42705225944519043  (0.43884562849998476)
     | > postnet_loss: 0.302385151386261  (0.31401326656341555)
     | > stopnet_loss: 0.008074197918176651  (0.0089918602257967)
     | > loss: 0.1904335469007492  (0.1972065806388855)
     | > align_error: 0.64215487241745  (0.6591722846031189)

   --> STEP: 6
     | > decoder_loss: 0.4458247125148773  (0.4400088091691335)
     | > postnet_loss: 0.31531229615211487  (0.3142297714948654)
     | > stopnet_loss: 0.007265974767506123  (0.008704212649414936)
     | > loss: 0.1975502222776413  (0.1972638542453448)
     | > align_error: 0.5937522649765015  (0.6482689479986826)

   --> STEP: 7
     | > decoder_loss: 0.45808371901512146  (0.44259093914713177)
     | > postnet_loss: 0.3155997097492218  (0.31442547695977346)
     | > stopnet_loss: 0.006166475359350443  (0.008341678750834294)
     | > loss: 0.19958733022212982  (0.1975957793848855)
     | > align_error: 0.5792223215103149  (0.6384051442146301)

   --> STEP: 8
     | > decoder_loss: 0.4540913701057434  (0.44402849301695824)
     | > postnet_loss: 0.317454993724823  (0.31480416655540466)
     | > stopnet_loss: 0.007041633129119873  (0.008179173048119992)
     | > loss: 0.19992822408676147  (0.19788733497262)
     | > align_error: 0.5740207135677338  (0.6303570903837681)

   --> STEP: 9
     | > decoder_loss: 0.4523966610431671  (0.44495828946431476)
     | > postnet_loss: 0.3186168074607849  (0.31522779332266915)
     | > stopnet_loss: 0.006639264058321714  (0.008008072049253516)
     | > loss: 0.199392631649971  (0.19805459015899235)
     | > align_error: 0.5911267697811127  (0.6259981658723619)

   --> STEP: 10
     | > decoder_loss: 0.47346368432044983  (0.4478088289499283)
     | > postnet_loss: 0.3293847143650055  (0.3166434854269028)
     | > stopnet_loss: 0.005570933222770691  (0.007764358166605234)
     | > loss: 0.20628303289413452  (0.19887743443250655)
     | > align_error: 0.5834852457046509  (0.6217468738555908)

   --> STEP: 11
     | > decoder_loss: 0.46136167645454407  (0.44904090599580243)
     | > postnet_loss: 0.3203371465206146  (0.3169792727990584)
     | > stopnet_loss: 0.005934371147304773  (0.007597995710305192)
     | > loss: 0.2013590782880783  (0.1991030384193767)
     | > align_error: 0.5948636531829834  (0.6193029447035356)

   --> STEP: 12
     | > decoder_loss: 0.4573703408241272  (0.4497350255648295)
     | > postnet_loss: 0.3133651614189148  (0.3166780968507131)
     | > stopnet_loss: 0.007879984565079212  (0.00762149478153636)
     | > loss: 0.20056386291980743  (0.1992247737944126)
     | > align_error: 0.5872733891010284  (0.6166338150699934)

   --> STEP: 13
     | > decoder_loss: 0.44658806920051575  (0.4494929519983438)
     | > postnet_loss: 0.3128291070461273  (0.3163820207118988)
     | > stopnet_loss: 0.005501255858689547  (0.007458399479778914)
     | > loss: 0.19535554945468903  (0.19892714115289542)
     | > align_error: 0.5857785642147064  (0.6142603342349713)

   --> STEP: 14
     | > decoder_loss: 0.45961514115333557  (0.4502159655094147)
     | > postnet_loss: 0.31738826632499695  (0.3164538953985487)
     | > stopnet_loss: 0.0048994948156178  (0.007275620575195977)
     | > loss: 0.19915035367012024  (0.19894308490412577)
     | > align_error: 0.5553373098373413  (0.6100515467779977)

   --> STEP: 15
     | > decoder_loss: 0.4548165202140808  (0.45052266915639244)
     | > postnet_loss: 0.3155195415019989  (0.3163916051387787)
     | > stopnet_loss: 0.005024886690080166  (0.007125571649521589)
     | > loss: 0.19760888814926147  (0.19885413845380148)
     | > align_error: 0.5885920524597168  (0.6086209138234456)

   --> STEP: 16
     | > decoder_loss: 0.45464280247688293  (0.4507801774889231)
     | > postnet_loss: 0.30915510654449463  (0.31593932397663593)
     | > stopnet_loss: 0.005271506495773792  (0.007009692577412352)
     | > loss: 0.1962209790945053  (0.19868956599384546)
     | > align_error: 0.6059038043022156  (0.6084510944783688)

   --> STEP: 17
     | > decoder_loss: 0.46369728446006775  (0.4515400073107551)
     | > postnet_loss: 0.3188561201095581  (0.316110900219749)
     | > stopnet_loss: 0.00481204129755497  (0.006880418972714859)
     | > loss: 0.20045040547847748  (0.19879314478705912)
     | > align_error: 0.5586724877357483  (0.6055229411405676)

   --> STEP: 18
     | > decoder_loss: 0.45588454604148865  (0.45178137057357365)
     | > postnet_loss: 0.3097679018974304  (0.31575851142406464)
     | > stopnet_loss: 0.005256435833871365  (0.006790197687223554)
     | > loss: 0.1966695338487625  (0.19867516640159819)
     | > align_error: 0.6040285527706146  (0.6054399195644591)

   --> STEP: 19
     | > decoder_loss: 0.4527835547924042  (0.4518341171114068)
     | > postnet_loss: 0.30924707651138306  (0.31541580432339716)
     | > stopnet_loss: 0.0047331517562270164  (0.006681932111907946)
     | > loss: 0.1952407956123352  (0.19849441004426857)
     | > align_error: 0.5991314351558685  (0.6051078940692701)

   --> STEP: 20
     | > decoder_loss: 0.449745774269104  (0.4517296999692917)
     | > postnet_loss: 0.3054986000061035  (0.3149199441075325)
     | > stopnet_loss: 0.0044999439269304276  (0.0065728327026590705)
     | > loss: 0.19331103563308716  (0.1982352413237095)
     | > align_error: 0.6230045557022095  (0.6060027271509171)

   --> STEP: 21
     | > decoder_loss: 0.44843295216560364  (0.45157271197863985)
     | > postnet_loss: 0.3054783344268799  (0.314470343646549)
     | > stopnet_loss: 0.003960056696087122  (0.006448414797584216)
     | > loss: 0.19243787229061127  (0.1979591761316572)
     | > align_error: 0.5603024363517761  (0.6038265228271484)

   --> STEP: 22
     | > decoder_loss: 0.449246346950531  (0.45146696811372583)
     | > postnet_loss: 0.30737993121147156  (0.31414805217222735)
     | > stopnet_loss: 0.004811435472220182  (0.006374006646431305)
     | > loss: 0.1939679980278015  (0.1977777589451183)
     | > align_error: 0.625623494386673  (0.6048172942616723)

   --> STEP: 23
     | > decoder_loss: 0.42245399951934814  (0.450205534696579)
     | > postnet_loss: 0.2947240471839905  (0.31330353021621704)
     | > stopnet_loss: 0.004447468556463718  (0.0062902441207805405)
     | > loss: 0.1837419867515564  (0.19716750798018082)
     | > align_error: 0.5675747394561768  (0.6031980527483899)

   --> STEP: 24
     | > decoder_loss: 0.45674315094947815  (0.4504779353737831)
     | > postnet_loss: 0.31070438027381897  (0.31319523230195045)
     | > stopnet_loss: 0.004397619981318712  (0.006211384781636298)
     | > loss: 0.1962594985961914  (0.19712967425584793)
     | > align_error: 0.5799189805984497  (0.6022280914088091)

   --> STEP: 25
     | > decoder_loss: 0.4564951956272125  (0.4507186257839203)
     | > postnet_loss: 0.3080361485481262  (0.3129888689517975)
     | > stopnet_loss: 0.003697602776810527  (0.006110833501443267)
     | > loss: 0.19483044743537903  (0.19703770518302918)
     | > align_error: 0.5585929751396179  (0.6004826867580414)

   --> STEP: 26
     | > decoder_loss: 0.4308324158191681  (0.4499537715545067)
     | > postnet_loss: 0.2963806092739105  (0.3123500897334172)
     | > stopnet_loss: 0.00434158043935895  (0.006042785306747716)
     | > loss: 0.1861448436975479  (0.19661874897204912)
     | > align_error: 0.5470422804355621  (0.5984272865148691)

   --> STEP: 27
     | > decoder_loss: 0.42813730239868164  (0.44914575417836505)
     | > postnet_loss: 0.2921428382396698  (0.31160167301142655)
     | > stopnet_loss: 0.0036283719819039106  (0.005953362591012761)
     | > loss: 0.18369841575622559  (0.1961402181122038)
     | > align_error: 0.5406613349914551  (0.5962878068288168)

   --> STEP: 28
     | > decoder_loss: 0.4338388442993164  (0.4485990788255419)
     | > postnet_loss: 0.29630401730537415  (0.3110553281647818)
     | > stopnet_loss: 0.003925006836652756  (0.005880921314071331)
     | > loss: 0.1864607185125351  (0.19579452169792994)
     | > align_error: 0.5667519569396973  (0.5952329550470624)

   --> STEP: 29
     | > decoder_loss: 0.42943644523620605  (0.4479382983569441)
     | > postnet_loss: 0.29364264011383057  (0.3104548906457835)
     | > stopnet_loss: 0.003571552224457264  (0.005801287897188088)
     | > loss: 0.18434132635593414  (0.19539958392751627)
     | > align_error: 0.5408360362052917  (0.5933571992249325)

   --> STEP: 30
     | > decoder_loss: 0.4292762577533722  (0.44731623033682505)
     | > postnet_loss: 0.29331400990486145  (0.3098835279544195)
     | > stopnet_loss: 0.0028188112191855907  (0.005701872007921338)
     | > loss: 0.183466374874115  (0.1950018102924029)
     | > align_error: 0.5337619185447693  (0.591370689868927)

   --> STEP: 31
     | > decoder_loss: 0.42503756284713745  (0.4465975636436093)
     | > postnet_loss: 0.2918906807899475  (0.3093031135297591)
     | > stopnet_loss: 0.0036798217333853245  (0.005636644579710499)
     | > loss: 0.18291188776493073  (0.1946118127915167)
     | > align_error: 0.5558455288410187  (0.5902247169325429)

   --> STEP: 32
     | > decoder_loss: 0.43830692768096924  (0.4463384812697768)
     | > postnet_loss: 0.2988603711128235  (0.30897677782922983)
     | > stopnet_loss: 0.0038257944397628307  (0.005580055512837134)
     | > loss: 0.1881176233291626  (0.19440886937081814)
     | > align_error: 0.5313411056995392  (0.5883846040815115)

   --> STEP: 33
     | > decoder_loss: 0.43390128016471863  (0.44596159638780536)
     | > postnet_loss: 0.29599443078041077  (0.308583373373205)
     | > stopnet_loss: 0.004013947211205959  (0.0055325976855149775)
     | > loss: 0.18648786842823029  (0.19416883903922458)
     | > align_error: 0.546506404876709  (0.587115567741972)

   --> STEP: 34
     | > decoder_loss: 0.43941065669059753  (0.44576892169082866)
     | > postnet_loss: 0.2971931993961334  (0.3082483682562323)
     | > stopnet_loss: 0.0032857402693480253  (0.005466513643863008)
     | > loss: 0.18743669986724854  (0.19397083494593115)
     | > align_error: 0.5640923976898193  (0.5864384156816146)

   --> STEP: 35
     | > decoder_loss: 0.4368346035480499  (0.44551365545817784)
     | > postnet_loss: 0.29645997285842896  (0.30791155695915223)
     | > stopnet_loss: 0.0035045775584876537  (0.005410458327137998)
     | > loss: 0.18682822585105896  (0.19376676040036336)
     | > align_error: 0.533270001411438  (0.5849193181310381)

   --> STEP: 36
     | > decoder_loss: 0.4433324635028839  (0.445453066792753)
     | > postnet_loss: 0.30137282609939575  (0.30772992554638123)
     | > stopnet_loss: 0.003649342805147171  (0.005361538451527142)
     | > loss: 0.18982566893100739  (0.19365728563732568)
     | > align_error: 0.6340957880020142  (0.5862853311830096)

   --> STEP: 37
     | > decoder_loss: 0.43577447533607483  (0.4451914832398698)
     | > postnet_loss: 0.2974182069301605  (0.30745123044864553)
     | > stopnet_loss: 0.0035606890451163054  (0.00531286684594847)
     | > loss: 0.1868588626384735  (0.19347354447519455)
     | > align_error: 0.5190327763557434  (0.5844676945660565)

   --> STEP: 38
     | > decoder_loss: 0.4227873980998993  (0.44460190205197586)
     | > postnet_loss: 0.2899913489818573  (0.30699175988373)
     | > stopnet_loss: 0.0031334427185356617  (0.005255513579437607)
     | > loss: 0.18132813274860382  (0.19315392837712636)
     | > align_error: 0.5520452857017517  (0.5836144732801538)

   --> STEP: 39
     | > decoder_loss: 0.4385714828968048  (0.444447275919792)
     | > postnet_loss: 0.30067238211631775  (0.30682972455636043)
     | > stopnet_loss: 0.0034733356442302465  (0.005209816709304085)
     | > loss: 0.18828430771827698  (0.19302906630895075)
     | > align_error: 0.5460315942764282  (0.5826508097159557)

   --> STEP: 40
     | > decoder_loss: 0.43548086285591125  (0.44422311559319494)
     | > postnet_loss: 0.2993258535861969  (0.30664212778210637)
     | > stopnet_loss: 0.003017918672412634  (0.005155019258381799)
     | > loss: 0.1867195963859558  (0.19287132956087588)
     | > align_error: 0.5839940309524536  (0.5826843902468681)

   --> STEP: 41
     | > decoder_loss: 0.42710864543914795  (0.44380568949187676)
     | > postnet_loss: 0.291914165019989  (0.30628290917815226)
     | > stopnet_loss: 0.003711130702868104  (0.005119802464344879)
     | > loss: 0.183466836810112  (0.19264195168890605)
     | > align_error: 0.5034348368644714  (0.5807514743107122)

   --> STEP: 42
     | > decoder_loss: 0.4325735867023468  (0.44353825847307843)
     | > postnet_loss: 0.29456156492233276  (0.3060038295530137)
     | > stopnet_loss: 0.0032670763321220875  (0.0050756899373871935)
     | > loss: 0.1850508749485016  (0.19246121176651546)
     | > align_error: 0.5798653662204742  (0.5807303764990399)

   --> STEP: 43
     | > decoder_loss: 0.43006372451782227  (0.443224897218305)
     | > postnet_loss: 0.2926326096057892  (0.3056928709495899)
     | > stopnet_loss: 0.002931305905804038  (0.005025820541303864)
     | > loss: 0.1836053878068924  (0.19225526237210563)
     | > align_error: 0.5518830418586731  (0.5800595082515896)

   --> STEP: 44
     | > decoder_loss: 0.4480348229408264  (0.44333421371199866)
     | > postnet_loss: 0.3030738830566406  (0.3056333484974774)
     | > stopnet_loss: 0.002642507664859295  (0.004971654339566488)
     | > loss: 0.19041968882083893  (0.19221354479139502)
     | > align_error: 0.5514630675315857  (0.5794095891443167)

   --> STEP: 45
     | > decoder_loss: 0.4414277970790863  (0.44329184889793394)
     | > postnet_loss: 0.3025763928890228  (0.3055654161506229)
     | > stopnet_loss: 0.0032851321157068014  (0.004934176067925161)
     | > loss: 0.18928617238998413  (0.19214849207136367)
     | > align_error: 0.5528862774372101  (0.5788201822174922)

   --> STEP: 46
     | > decoder_loss: 0.4311155080795288  (0.4430271458366643)
     | > postnet_loss: 0.29341503977775574  (0.3053012775338214)
     | > stopnet_loss: 0.0031731741037219763  (0.0048958934165294395)
     | > loss: 0.1843058168888092  (0.1919779991326125)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3492580688360966 (+0.0003220601515336319)
     | > avg_decoder_loss: 0.438792037692937 (+8.890755248797122e-05)
     | > avg_postnet_loss: 0.3018539981408553 (-0.000252192219098446)
     | > avg_stopnet_loss: 0.004343910329749412 (-7.849359517974296e-06)
     | > avg_loss: 0.18950541904478363 (-4.867080486181674e-05)
     | > avg_align_error: 0.5717535050529424 (+0.00014021721753232352)


 > EPOCH: 141/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 17:53:19)

   --> TIME: 2025-12-28 17:53:30 -- STEP: 9/150 -- GLOBAL_STEP: 21300
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4674358665943146  (0.46196796496709186)
     | > postnet_loss: 0.3951186239719391  (0.3935338788562351)
     | > stopnet_loss: 0.009993663989007473  (0.012613826431334019)
     | > loss: 0.22563228011131287  (0.22648928562800089)
     | > align_error: 0.6464343667030334  (0.6956572300857968)
     | > grad_norm: tensor(0.4683, device='cuda:0')  (tensor(0.3212, device='cuda:0'))
     | > step_time: 0.6788  (0.511944956249661)
     | > loader_time: 0.7124  (0.6553454664018419)


   --> TIME: 2025-12-28 17:54:13 -- STEP: 34/150 -- GLOBAL_STEP: 21325
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.4772053360939026  (0.4704151337637621)
     | > postnet_loss: 0.39726176857948303  (0.39619123234468345)
     | > stopnet_loss: 0.005570072680711746  (0.00861328060957877)
     | > loss: 0.22418685257434845  (0.22526487050687566)
     | > align_error: 0.6204771101474762  (0.6626391428358415)
     | > grad_norm: tensor(0.1584, device='cuda:0')  (tensor(0.2758, device='cuda:0'))
     | > step_time: 1.1069  (0.744421404950759)
     | > loader_time: 0.9401  (0.8222789413788739)


   --> TIME: 2025-12-28 17:55:11 -- STEP: 59/150 -- GLOBAL_STEP: 21350
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4867576062679291  (0.4757504377324702)
     | > postnet_loss: 0.39880985021591187  (0.3971581494404098)
     | > stopnet_loss: 0.004270934499800205  (0.007008394088311974)
     | > loss: 0.22566279768943787  (0.22523553997783338)
     | > align_error: 0.6037442982196808  (0.6428563574613149)
     | > grad_norm: tensor(0.1303, device='cuda:0')  (tensor(0.2443, device='cuda:0'))
     | > step_time: 1.4128  (0.952797849299544)
     | > loader_time: 1.1771  (0.932533785448236)


   --> TIME: 2025-12-28 17:56:24 -- STEP: 84/150 -- GLOBAL_STEP: 21375
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4821852743625641  (0.478314754154001)
     | > postnet_loss: 0.39439141750335693  (0.39696158717075986)
     | > stopnet_loss: 0.003598429262638092  (0.006092126777816918)
     | > loss: 0.22274258732795715  (0.22491121079240525)
     | > align_error: 0.668526828289032  (0.6347145785888036)
     | > grad_norm: tensor(0.1935, device='cuda:0')  (tensor(0.2572, device='cuda:0'))
     | > step_time: 1.6708  (1.118653013592675)
     | > loader_time: 1.5945  (1.0700466150329226)


   --> TIME: 2025-12-28 17:57:49 -- STEP: 109/150 -- GLOBAL_STEP: 21400
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4805508852005005  (0.4796955730390111)
     | > postnet_loss: 0.3913308084011078  (0.39650615010786494)
     | > stopnet_loss: 0.0035994478967040777  (0.005504273192170973)
     | > loss: 0.22156988084316254  (0.22455470304970349)
     | > align_error: 0.632826566696167  (0.6298487837161493)
     | > grad_norm: tensor(0.1400, device='cuda:0')  (tensor(0.2467, device='cuda:0'))
     | > step_time: 1.8665  (1.2590835160071707)
     | > loader_time: 1.4977  (1.2108356208976256)


   --> TIME: 2025-12-28 17:59:20 -- STEP: 134/150 -- GLOBAL_STEP: 21425
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48191002011299133  (0.4805148072651963)
     | > postnet_loss: 0.3900684714317322  (0.3958844615897135)
     | > stopnet_loss: 0.003119649365544319  (0.005078350371027838)
     | > loss: 0.22111427783966064  (0.22417816686541286)
     | > align_error: 0.6325920820236206  (0.6264025998204502)
     | > grad_norm: tensor(0.1713, device='cuda:0')  (tensor(0.2307, device='cuda:0'))
     | > step_time: 1.987  (1.3839604961338337)
     | > loader_time: 1.7683  (1.3030080457231892)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45922794938087463  (0.45922794938087463)
     | > postnet_loss: 0.33223164081573486  (0.33223164081573486)
     | > stopnet_loss: 0.012086397036910057  (0.012086397036910057)
     | > loss: 0.2099512815475464  (0.2099512815475464)
     | > align_error: 0.718732625246048  (0.718732625246048)

   --> STEP: 1
     | > decoder_loss: 0.43856754899024963  (0.43856754899024963)
     | > postnet_loss: 0.3183063864707947  (0.3183063864707947)
     | > stopnet_loss: 0.009629650972783566  (0.009629650972783566)
     | > loss: 0.19884814321994781  (0.19884814321994781)
     | > align_error: 0.6593128144741058  (0.6593128144741058)

   --> STEP: 2
     | > decoder_loss: 0.436166375875473  (0.43736696243286133)
     | > postnet_loss: 0.3113340139389038  (0.31482020020484924)
     | > stopnet_loss: 0.01108437031507492  (0.010357010643929243)
     | > loss: 0.19795948266983032  (0.19840381294488907)
     | > align_error: 0.6551251709461212  (0.6572189927101135)

   --> STEP: 3
     | > decoder_loss: 0.4390900135040283  (0.437941312789917)
     | > postnet_loss: 0.30975106358528137  (0.3131304879983266)
     | > stopnet_loss: 0.008059230633080006  (0.009591083973646164)
     | > loss: 0.19526949524879456  (0.19735904037952423)
     | > align_error: 0.7341079413890839  (0.6828486422697703)

   --> STEP: 4
     | > decoder_loss: 0.44307270646095276  (0.43922416120767593)
     | > postnet_loss: 0.3172875642776489  (0.3141697570681572)
     | > stopnet_loss: 0.008113331161439419  (0.009221645770594478)
     | > loss: 0.19820338487625122  (0.19757012650370598)
     | > align_error: 0.60291588306427  (0.6628654524683952)

   --> STEP: 5
     | > decoder_loss: 0.42537418007850647  (0.43645416498184203)
     | > postnet_loss: 0.3005128502845764  (0.31143837571144106)
     | > stopnet_loss: 0.008066711947321892  (0.00899065900593996)
     | > loss: 0.18953847885131836  (0.19596379697322847)
     | > align_error: 0.6409080028533936  (0.6584739625453949)

   --> STEP: 6
     | > decoder_loss: 0.44279780983924866  (0.43751143912474316)
     | > postnet_loss: 0.3120914101600647  (0.31154721478621167)
     | > stopnet_loss: 0.007145091891288757  (0.008683064486831427)
     | > loss: 0.1958674043416977  (0.19594773153463999)
     | > align_error: 0.5932871997356415  (0.6476095020771027)

   --> STEP: 7
     | > decoder_loss: 0.453126460313797  (0.4397421564374651)
     | > postnet_loss: 0.3118519186973572  (0.3115907439163753)
     | > stopnet_loss: 0.006125031039118767  (0.00831763113715819)
     | > loss: 0.19736963510513306  (0.196150860616139)
     | > align_error: 0.5784704685211182  (0.6377324972833905)

   --> STEP: 8
     | > decoder_loss: 0.44859781861305237  (0.44084911420941353)
     | > postnet_loss: 0.3127538561820984  (0.3117361329495907)
     | > stopnet_loss: 0.007034752052277327  (0.008157271251548082)
     | > loss: 0.1973726749420166  (0.1963035874068737)
     | > align_error: 0.573368489742279  (0.6296869963407516)

   --> STEP: 9
     | > decoder_loss: 0.4452398121356964  (0.4413369695345561)
     | > postnet_loss: 0.31221652030944824  (0.31178950932290816)
     | > stopnet_loss: 0.006677231285721064  (0.00799282236645619)
     | > loss: 0.1960413008928299  (0.19627444446086884)
     | > align_error: 0.5906314849853516  (0.6253474950790405)

   --> STEP: 10
     | > decoder_loss: 0.46946486830711365  (0.44414975941181184)
     | > postnet_loss: 0.32553595304489136  (0.31316415369510653)
     | > stopnet_loss: 0.005562721751630306  (0.007749812304973602)
     | > loss: 0.20431292057037354  (0.19707829207181932)
     | > align_error: 0.5827091634273529  (0.6210836619138718)

   --> STEP: 11
     | > decoder_loss: 0.4585147798061371  (0.4454556703567505)
     | > postnet_loss: 0.3174164295196533  (0.3135507242246108)
     | > stopnet_loss: 0.005875586066395044  (0.00757942810146646)
     | > loss: 0.1998583972454071  (0.19733102890578183)
     | > align_error: 0.5943135917186737  (0.6186500191688538)

   --> STEP: 12
     | > decoder_loss: 0.4537351429462433  (0.4461456264058749)
     | > postnet_loss: 0.3103376626968384  (0.3132829690972964)
     | > stopnet_loss: 0.007961295545101166  (0.007611250388436019)
     | > loss: 0.19897949695587158  (0.19746840124328932)
     | > align_error: 0.5865994691848755  (0.6159791400035223)

   --> STEP: 13
     | > decoder_loss: 0.4445250332355499  (0.446020965392773)
     | > postnet_loss: 0.3109796643257141  (0.3131057918071747)
     | > stopnet_loss: 0.005555639509111643  (0.007453126474641836)
     | > loss: 0.1944318264722824  (0.19723481856859648)
     | > align_error: 0.5853219032287598  (0.6136208910208482)

   --> STEP: 14
     | > decoder_loss: 0.45447632670402527  (0.44662491977214813)
     | > postnet_loss: 0.3134377896785736  (0.31312950594084604)
     | > stopnet_loss: 0.004898121114820242  (0.007270626091797437)
     | > loss: 0.1968766450881958  (0.19720923474856786)
     | > align_error: 0.5547774434089661  (0.6094177876199994)

   --> STEP: 15
     | > decoder_loss: 0.4519771635532379  (0.4469817360242208)
     | > postnet_loss: 0.3135858476161957  (0.3131599287192027)
     | > stopnet_loss: 0.004960992839187384  (0.007116650541623433)
     | > loss: 0.19635175168514252  (0.19715206921100617)
     | > align_error: 0.5881472826004028  (0.6079997539520263)

   --> STEP: 16
     | > decoder_loss: 0.4525957703590393  (0.44733261317014694)
     | > postnet_loss: 0.3074910640716553  (0.31280562467873096)
     | > stopnet_loss: 0.005225707311183214  (0.00699846658972092)
     | > loss: 0.19524741172790527  (0.19703302811831236)
     | > align_error: 0.6054798364639282  (0.6078422591090202)

   --> STEP: 17
     | > decoder_loss: 0.4592965543270111  (0.44803637441466837)
     | > postnet_loss: 0.3160095810890198  (0.3129940927028656)
     | > stopnet_loss: 0.004809344653040171  (0.0068696947110926405)
     | > loss: 0.19863587617874146  (0.1971273132983376)
     | > align_error: 0.5584886074066162  (0.6049391031265259)

   --> STEP: 18
     | > decoder_loss: 0.45386335253715515  (0.4483600954214732)
     | > postnet_loss: 0.30855095386505127  (0.31274725165632034)
     | > stopnet_loss: 0.005227190908044577  (0.006778444499812192)
     | > loss: 0.19583077728748322  (0.1970552835199568)
     | > align_error: 0.6036964654922485  (0.6048700677023994)

   --> STEP: 19
     | > decoder_loss: 0.44902050495147705  (0.44839485381778915)
     | > postnet_loss: 0.30661460757255554  (0.3124244809150696)
     | > stopnet_loss: 0.0046987878158688545  (0.0066689888848678065)
     | > loss: 0.19360756874084473  (0.19687382484737195)
     | > align_error: 0.5983590483665466  (0.6045273824741966)

   --> STEP: 20
     | > decoder_loss: 0.4483930766582489  (0.4483947649598122)
     | > postnet_loss: 0.3049624562263489  (0.31205137968063357)
     | > stopnet_loss: 0.004481256939470768  (0.0065596022875979544)
     | > loss: 0.19282013177871704  (0.19667114019393922)
     | > align_error: 0.6226974725723267  (0.6054358869791031)

   --> STEP: 21
     | > decoder_loss: 0.4460824131965637  (0.44828465297108605)
     | > postnet_loss: 0.3037089407444  (0.31165412068367004)
     | > stopnet_loss: 0.00394419627264142  (0.006435059144028595)
     | > loss: 0.19139204919338226  (0.1964197549081984)
     | > align_error: 0.5596708953380585  (0.6032566016628629)

   --> STEP: 22
     | > decoder_loss: 0.4485040009021759  (0.44829462333159015)
     | > postnet_loss: 0.30709224939346313  (0.31144676289775153)
     | > stopnet_loss: 0.0047894129529595375  (0.006360257044434547)
     | > loss: 0.19368848204612732  (0.19629560614174063)
     | > align_error: 0.6252995729446411  (0.6042585549029437)

   --> STEP: 23
     | > decoder_loss: 0.42138418555259705  (0.4471246042977209)
     | > postnet_loss: 0.2942490577697754  (0.31069903658783954)
     | > stopnet_loss: 0.0044340407475829124  (0.006276508509788824)
     | > loss: 0.1833423525094986  (0.19573242120120837)
     | > align_error: 0.5671359300613403  (0.6026445277359175)

   --> STEP: 24
     | > decoder_loss: 0.4555805027484894  (0.44747693339983624)
     | > postnet_loss: 0.31035730242729187  (0.31068479766448337)
     | > stopnet_loss: 0.004377697594463825  (0.006197391388316949)
     | > loss: 0.19586214423179626  (0.19573782632748285)
     | > align_error: 0.5796023309230804  (0.6016844362020493)

   --> STEP: 25
     | > decoder_loss: 0.4555886387825012  (0.4478014016151428)
     | > postnet_loss: 0.30779674649238586  (0.3105692756175995)
     | > stopnet_loss: 0.0036459823604673147  (0.006095335027202964)
     | > loss: 0.19449234008789062  (0.19568800687789917)
     | > align_error: 0.5581162869930267  (0.5999417102336884)

   --> STEP: 26
     | > decoder_loss: 0.42937490344047546  (0.4470926901468864)
     | > postnet_loss: 0.29559943079948425  (0.30999351235536426)
     | > stopnet_loss: 0.004332087468355894  (0.006027517813401153)
     | > loss: 0.1855756640434265  (0.19529907061503485)
     | > align_error: 0.5465846061706543  (0.5978895139235717)

   --> STEP: 27
     | > decoder_loss: 0.42754271626472473  (0.44636861704013964)
     | > postnet_loss: 0.2917308509349823  (0.3093171174879427)
     | > stopnet_loss: 0.0038654159288853407  (0.005947439965826494)
     | > loss: 0.18368381261825562  (0.19486887587441337)
     | > align_error: 0.5411909222602844  (0.5957895660841906)

   --> STEP: 28
     | > decoder_loss: 0.4325289726257324  (0.4458743440253394)
     | > postnet_loss: 0.29573822021484375  (0.3088321568710463)
     | > stopnet_loss: 0.003898677183315158  (0.0058742698664510885)
     | > loss: 0.18596547842025757  (0.19455089739390782)
     | > align_error: 0.5659984350204468  (0.5947255971176284)

   --> STEP: 29
     | > decoder_loss: 0.42790335416793823  (0.44525465471991177)
     | > postnet_loss: 0.2924015522003174  (0.3082655842961936)
     | > stopnet_loss: 0.0035729645751416683  (0.00579491451157835)
     | > loss: 0.1836491972208023  (0.19417497669828349)
     | > align_error: 0.5402029156684875  (0.5928455046538649)

   --> STEP: 30
     | > decoder_loss: 0.4284211993217468  (0.4446935395399729)
     | > postnet_loss: 0.29319748282432556  (0.3077633142471313)
     | > stopnet_loss: 0.002761340932920575  (0.005693795392289758)
     | > loss: 0.1831659972667694  (0.19380801071723303)
     | > align_error: 0.5331547558307648  (0.5908558130264282)

   --> STEP: 31
     | > decoder_loss: 0.4242410957813263  (0.444033783289694)
     | > postnet_loss: 0.2917158901691437  (0.3072456554059059)
     | > stopnet_loss: 0.0036757350899279118  (0.00562869667285873)
     | > loss: 0.18266497552394867  (0.19344855796906255)
     | > align_error: 0.5553450882434845  (0.5897103057753655)

   --> STEP: 32
     | > decoder_loss: 0.4362892806529999  (0.4437917675822973)
     | > postnet_loss: 0.2977879047393799  (0.306950100697577)
     | > stopnet_loss: 0.003800145583227277  (0.0055715544513077475)
     | > loss: 0.18731944262981415  (0.19325702311471105)
     | > align_error: 0.5306597352027893  (0.5878649754449725)

   --> STEP: 33
     | > decoder_loss: 0.43338221311569214  (0.44347632653785474)
     | > postnet_loss: 0.2959018051624298  (0.3066153038631786)
     | > stopnet_loss: 0.003981768619269133  (0.005523379123064153)
     | > loss: 0.1863027811050415  (0.19304628850835742)
     | > align_error: 0.5460079610347748  (0.5865965810689059)

   --> STEP: 34
     | > decoder_loss: 0.4384419023990631  (0.44332825523965497)
     | > postnet_loss: 0.2970001697540283  (0.3063325058011448)
     | > stopnet_loss: 0.0032553004566580057  (0.005456670926993384)
     | > loss: 0.18711581826210022  (0.19287186291287928)
     | > align_error: 0.5637209117412567  (0.5859237672651515)

   --> STEP: 35
     | > decoder_loss: 0.43543240427970886  (0.44310265949794225)
     | > postnet_loss: 0.29590344429016113  (0.30603453261511665)
     | > stopnet_loss: 0.0035095715429633856  (0.005401039516021098)
     | > loss: 0.18634353578090668  (0.1926853392805372)
     | > align_error: 0.5327615141868591  (0.5844048457486289)

   --> STEP: 36
     | > decoder_loss: 0.4422363042831421  (0.4430785940753089)
     | > postnet_loss: 0.30091607570648193  (0.30589235325654346)
     | > stopnet_loss: 0.0036370286252349615  (0.005352039213499261)
     | > loss: 0.18942512571811676  (0.19259477779269218)
     | > align_error: 0.6336569786071777  (0.5857729605502553)

   --> STEP: 37
     | > decoder_loss: 0.43508708477020264  (0.44286260733733307)
     | > postnet_loss: 0.2972811460494995  (0.3056596179266234)
     | > stopnet_loss: 0.0035353368148207664  (0.005302939148670113)
     | > loss: 0.18662738800048828  (0.19243349698749748)
     | > align_error: 0.5186110734939575  (0.5839577744135985)

   --> STEP: 38
     | > decoder_loss: 0.42197293043136597  (0.44231287899770233)
     | > postnet_loss: 0.29003870487213135  (0.3052485412672946)
     | > stopnet_loss: 0.003112680045887828  (0.005245300751228474)
     | > loss: 0.18111558258533478  (0.19213565713480898)
     | > align_error: 0.5517823696136475  (0.5831110532346525)

   --> STEP: 39
     | > decoder_loss: 0.4370934069156647  (0.4421790463802142)
     | > postnet_loss: 0.30003848671913147  (0.30511495012503403)
     | > stopnet_loss: 0.003426983254030347  (0.005198677225659291)
     | > loss: 0.1877099573612213  (0.19202217765343496)
     | > align_error: 0.5453686118125916  (0.5821432983263944)

   --> STEP: 40
     | > decoder_loss: 0.4350208342075348  (0.4420000910758972)
     | > postnet_loss: 0.29926565289497375  (0.3049687176942825)
     | > stopnet_loss: 0.0030199673492461443  (0.005144209478748963)
     | > loss: 0.18659159541130066  (0.1918864130973816)
     | > align_error: 0.5836975574493408  (0.5821821548044681)

   --> STEP: 41
     | > decoder_loss: 0.42640748620033264  (0.44161978363990784)
     | > postnet_loss: 0.2917935252189636  (0.3046473715363479)
     | > stopnet_loss: 0.0037052282132208347  (0.005109112374711691)
     | > loss: 0.18325549364089966  (0.19167590286673572)
     | > align_error: 0.5028184652328491  (0.5802464550588189)

   --> STEP: 42
     | > decoder_loss: 0.43126413226127625  (0.4413732205118452)
     | > postnet_loss: 0.29389792680740356  (0.304391432376135)
     | > stopnet_loss: 0.0032649682834744453  (0.005065204182063185)
     | > loss: 0.18455547094345093  (0.19150636877332414)
     | > align_error: 0.5792375206947327  (0.580222432812055)

   --> STEP: 43
     | > decoder_loss: 0.43001505732536316  (0.441109077181927)
     | > postnet_loss: 0.29285478591918945  (0.30412313827248505)
     | > stopnet_loss: 0.0028949968982487917  (0.0050147342452302925)
     | > loss: 0.18361246585845947  (0.19132278963576915)
     | > align_error: 0.5515777170658112  (0.5795562766319098)

   --> STEP: 44
     | > decoder_loss: 0.4475448429584503  (0.4412553445859389)
     | > postnet_loss: 0.3031381368637085  (0.30410075187683105)
     | > stopnet_loss: 0.0026265361811965704  (0.004960457016502253)
     | > loss: 0.19029727578163147  (0.19129948250272058)
     | > align_error: 0.550998330116272  (0.578907232392918)

   --> STEP: 45
     | > decoder_loss: 0.44070443511009216  (0.4412431021531423)
     | > postnet_loss: 0.3024360239505768  (0.3040637579229143)
     | > stopnet_loss: 0.003258761717006564  (0.004922641565402349)
     | > loss: 0.18904387950897217  (0.1912493579917484)
     | > align_error: 0.552384078502655  (0.5783178289731343)

   --> STEP: 46
     | > decoder_loss: 0.4311739206314087  (0.4410242069026698)
     | > postnet_loss: 0.2936869263648987  (0.3038381746281748)
     | > stopnet_loss: 0.0031609341967850924  (0.004884343579128062)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3231700442054055 (-0.019711631717103828)
     | > avg_decoder_loss: 0.4380564061981259 (+0.00018894943324004876)
     | > avg_postnet_loss: 0.3011187667196449 (+1.3068769917523593e-05)
     | > avg_stopnet_loss: 0.004348057205788791 (+6.191443059255092e-06)
     | > avg_loss: 0.1891418517087445 (+5.6697112141235184e-05)
     | > avg_align_error: 0.5717899135567925 (+0.0008037957278161922)


 > EPOCH: 144/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 18:20:40)

   --> TIME: 2025-12-28 18:20:47 -- STEP: 6/150 -- GLOBAL_STEP: 21750
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4555836319923401  (0.45897118250528973)
     | > postnet_loss: 0.38675469160079956  (0.39213819801807404)
     | > stopnet_loss: 0.011700689792633057  (0.013323886630435785)
     | > loss: 0.22228527069091797  (0.2261012320717176)
     | > align_error: 0.70203498005867  (0.7101588100194931)
     | > grad_norm: tensor(0.3114, device='cuda:0')  (tensor(0.3051, device='cuda:0'))
     | > step_time: 0.5466  (0.47433312733968097)
     | > loader_time: 0.7604  (0.6718164682388306)


   --> TIME: 2025-12-28 18:21:30 -- STEP: 31/150 -- GLOBAL_STEP: 21775
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.4798489809036255  (0.4687823547470954)
     | > postnet_loss: 0.3996117413043976  (0.39488802994451216)
     | > stopnet_loss: 0.0065000662580132484  (0.008873727082485149)
     | > loss: 0.22636523842811584  (0.22479132202363783)
     | > align_error: 0.6474304795265198  (0.6655337762448096)
     | > grad_norm: tensor(0.2206, device='cuda:0')  (tensor(0.2517, device='cuda:0'))
     | > step_time: 1.0593  (0.697612424050608)
     | > loader_time: 1.062  (0.8799241819689351)


   --> TIME: 2025-12-28 18:22:26 -- STEP: 56/150 -- GLOBAL_STEP: 21800
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.47910207509994507  (0.47460973635315895)
     | > postnet_loss: 0.39385032653808594  (0.3963711793933596)
     | > stopnet_loss: 0.004435532260686159  (0.007128236432825878)
     | > loss: 0.22267363965511322  (0.2248734650867326)
     | > align_error: 0.6146041750907898  (0.6444011782961232)
     | > grad_norm: tensor(0.1801, device='cuda:0')  (tensor(0.2315, device='cuda:0'))
     | > step_time: 1.218  (0.8974378492150988)
     | > loader_time: 1.211  (0.9892161020210811)


   --> TIME: 2025-12-28 18:23:36 -- STEP: 81/150 -- GLOBAL_STEP: 21825
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.487522155046463  (0.4772749392338741)
     | > postnet_loss: 0.39822936058044434  (0.39624445342723225)
     | > stopnet_loss: 0.003767529269680381  (0.006163062099482357)
     | > loss: 0.2252054065465927  (0.22454290956626705)
     | > align_error: 0.6920695900917053  (0.6344695495970455)
     | > grad_norm: tensor(0.1344, device='cuda:0')  (tensor(0.2119, device='cuda:0'))
     | > step_time: 1.5262  (1.0680769166828674)
     | > loader_time: 1.3899  (1.0939795441097684)


   --> TIME: 2025-12-28 18:24:57 -- STEP: 106/150 -- GLOBAL_STEP: 21850
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48185282945632935  (0.4785718979700556)
     | > postnet_loss: 0.39348873496055603  (0.3956980269472553)
     | > stopnet_loss: 0.0033779023215174675  (0.005553984302886813)
     | > loss: 0.2222132831811905  (0.22412146473268293)
     | > align_error: 0.6235606074333191  (0.6294097270605699)
     | > grad_norm: tensor(0.2151, device='cuda:0')  (tensor(0.2070, device='cuda:0'))
     | > step_time: 1.7251  (1.2138198119289465)
     | > loader_time: 1.4848  (1.2055324158578546)


   --> TIME: 2025-12-28 18:26:31 -- STEP: 131/150 -- GLOBAL_STEP: 21875
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4818113148212433  (0.47947548341205104)
     | > postnet_loss: 0.39059069752693176  (0.3951315684172943)
     | > stopnet_loss: 0.003061196068301797  (0.005117361892355989)
     | > loss: 0.22116169333457947  (0.22376912388637776)
     | > align_error: 0.59181347489357  (0.6261001056387224)
     | > grad_norm: tensor(0.1188, device='cuda:0')  (tensor(0.1995, device='cuda:0'))
     | > step_time: 2.0306  (1.3404828282712975)
     | > loader_time: 1.9852  (1.3297583692856416)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4578145742416382  (0.4578145742416382)
     | > postnet_loss: 0.33151403069496155  (0.33151403069496155)
     | > stopnet_loss: 0.012161236256361008  (0.012161236256361008)
     | > loss: 0.20949338376522064  (0.20949338376522064)
     | > align_error: 0.718888521194458  (0.718888521194458)

   --> STEP: 1
     | > decoder_loss: 0.4376208186149597  (0.4376208186149597)
     | > postnet_loss: 0.3177083134651184  (0.3177083134651184)
     | > stopnet_loss: 0.009679669514298439  (0.009679669514298439)
     | > loss: 0.19851195812225342  (0.19851195812225342)
     | > align_error: 0.6596401929855347  (0.6596401929855347)

   --> STEP: 2
     | > decoder_loss: 0.4350525140762329  (0.4363366663455963)
     | > postnet_loss: 0.3106329143047333  (0.31417061388492584)
     | > stopnet_loss: 0.011087444610893726  (0.010383557062596083)
     | > loss: 0.1975088119506836  (0.1980103850364685)
     | > align_error: 0.6551798582077026  (0.6574100255966187)

   --> STEP: 3
     | > decoder_loss: 0.4379136264324188  (0.4368623197078705)
     | > postnet_loss: 0.3089925944805145  (0.31244460741678876)
     | > stopnet_loss: 0.008118633180856705  (0.009628582435349623)
     | > loss: 0.19484518468379974  (0.19695531825224558)
     | > align_error: 0.734268307685852  (0.6830294529596964)

   --> STEP: 4
     | > decoder_loss: 0.4437059462070465  (0.4385732263326645)
     | > postnet_loss: 0.3176148235797882  (0.3137371614575386)
     | > stopnet_loss: 0.008127579465508461  (0.009253331692889333)
     | > loss: 0.1984577775001526  (0.19733093306422234)
     | > align_error: 0.6030735969543457  (0.6630404889583588)

   --> STEP: 5
     | > decoder_loss: 0.4259326159954071  (0.43604510426521303)
     | > postnet_loss: 0.30068325996398926  (0.31112638115882874)
     | > stopnet_loss: 0.008089132606983185  (0.009020491875708104)
     | > loss: 0.18974310159683228  (0.19581336677074432)
     | > align_error: 0.6417101323604584  (0.6587744176387786)

   --> STEP: 6
     | > decoder_loss: 0.4426858723163605  (0.43715189894040424)
     | > postnet_loss: 0.3120708167552948  (0.31128378709157306)
     | > stopnet_loss: 0.007235005032271147  (0.008722910735135278)
     | > loss: 0.19592417776584625  (0.19583183526992798)
     | > align_error: 0.5936833620071411  (0.647925908366839)

   --> STEP: 7
     | > decoder_loss: 0.4542213976383209  (0.4395903987543924)
     | > postnet_loss: 0.3124454617500305  (0.3114497406142099)
     | > stopnet_loss: 0.006235883105546236  (0.008367621073765414)
     | > loss: 0.1979026049375534  (0.1961276595081602)
     | > align_error: 0.5784591436386108  (0.638002084834235)

   --> STEP: 8
     | > decoder_loss: 0.44763118028640747  (0.44059549644589424)
     | > postnet_loss: 0.31234511733055115  (0.3115616627037525)
     | > stopnet_loss: 0.007059330120682716  (0.008204084704630077)
     | > loss: 0.19705340266227722  (0.1962433774024248)
     | > align_error: 0.5737579762935638  (0.6299715712666512)

   --> STEP: 9
     | > decoder_loss: 0.44566428661346436  (0.441158695353402)
     | > postnet_loss: 0.31236839294433594  (0.3116512993971507)
     | > stopnet_loss: 0.00669744610786438  (0.008036680416100554)
     | > loss: 0.19620561599731445  (0.1962391816907459)
     | > align_error: 0.5908395946025848  (0.6256235738595327)

   --> STEP: 10
     | > decoder_loss: 0.47002506256103516  (0.44404533207416536)
     | > postnet_loss: 0.32587677240371704  (0.3130738466978073)
     | > stopnet_loss: 0.005595009308308363  (0.007792513305321336)
     | > loss: 0.204570472240448  (0.1970723107457161)
     | > align_error: 0.5829143226146698  (0.6213526487350464)

   --> STEP: 11
     | > decoder_loss: 0.458274781703949  (0.4453389184041457)
     | > postnet_loss: 0.31702882051467896  (0.31343338977206836)
     | > stopnet_loss: 0.005878240801393986  (0.007618488532237031)
     | > loss: 0.1997041404247284  (0.19731156798926267)
     | > align_error: 0.5944346189498901  (0.618905555118214)

   --> STEP: 12
     | > decoder_loss: 0.453838586807251  (0.44604722410440445)
     | > postnet_loss: 0.30990365147590637  (0.31313924491405487)
     | > stopnet_loss: 0.007862384431064129  (0.007638813190472622)
     | > loss: 0.19879794120788574  (0.19743543242414793)
     | > align_error: 0.5872592926025391  (0.6162683665752411)

   --> STEP: 13
     | > decoder_loss: 0.44379714131355286  (0.44587414081280047)
     | > postnet_loss: 0.3100690245628357  (0.31290307411780727)
     | > stopnet_loss: 0.005520098842680454  (0.007475835163719379)
     | > loss: 0.1939866542816162  (0.19717014179779932)
     | > align_error: 0.5854296982288361  (0.6138961613178253)

   --> STEP: 14
     | > decoder_loss: 0.4546695351600647  (0.4465023832661765)
     | > postnet_loss: 0.3133935332298279  (0.312938106911523)
     | > stopnet_loss: 0.004901601932942867  (0.007291961361521057)
     | > loss: 0.1969173699617386  (0.19715208666665213)
     | > align_error: 0.5547244548797607  (0.6096696108579636)

   --> STEP: 15
     | > decoder_loss: 0.4532613456249237  (0.44695298075675965)
     | > postnet_loss: 0.31376519799232483  (0.3129932463169098)
     | > stopnet_loss: 0.005011795554310083  (0.007139950307706992)
     | > loss: 0.19676843285560608  (0.19712650974591572)
     | > align_error: 0.5884218215942383  (0.6082530915737152)

   --> STEP: 16
     | > decoder_loss: 0.4544513523578644  (0.4474216289818287)
     | > postnet_loss: 0.3080510199069977  (0.3126843571662903)
     | > stopnet_loss: 0.005260303616523743  (0.007022472389508039)
     | > loss: 0.19588589668273926  (0.1970489714294672)
     | > align_error: 0.6058839857578278  (0.6081050224602222)

   --> STEP: 17
     | > decoder_loss: 0.46071895956993103  (0.44820382489877586)
     | > postnet_loss: 0.316394180059433  (0.3129025820423575)
     | > stopnet_loss: 0.0048138974234461784  (0.006892556215033811)
     | > loss: 0.19909217953681946  (0.19716916014166438)
     | > align_error: 0.5585214495658875  (0.605188341701732)

   --> STEP: 18
     | > decoder_loss: 0.4549200236797333  (0.4485769470532735)
     | > postnet_loss: 0.30862170457839966  (0.31266475551658207)
     | > stopnet_loss: 0.005239597987383604  (0.006800725202386578)
     | > loss: 0.19612501561641693  (0.19711115211248398)
     | > align_error: 0.6040281057357788  (0.605123884148068)

   --> STEP: 19
     | > decoder_loss: 0.45009729266166687  (0.44865696524318893)
     | > postnet_loss: 0.30690160393714905  (0.31236143174924347)
     | > stopnet_loss: 0.0047065336257219315  (0.0066905045930884385)
     | > loss: 0.19395625591278076  (0.19694510494407855)
     | > align_error: 0.5989585220813751  (0.6047993914077157)

   --> STEP: 20
     | > decoder_loss: 0.45017674565315247  (0.44873295426368714)
     | > postnet_loss: 0.3054935336112976  (0.3120180368423462)
     | > stopnet_loss: 0.004509252496063709  (0.0065814419882372025)
     | > loss: 0.19342683255672455  (0.19676919132471085)
     | > align_error: 0.6229318380355835  (0.605706013739109)

   --> STEP: 21
     | > decoder_loss: 0.4460926949977875  (0.44860722763197763)
     | > postnet_loss: 0.30347055196762085  (0.31161101375307354)
     | > stopnet_loss: 0.003984789364039898  (0.006457791863275426)
     | > loss: 0.19137559831142426  (0.1965123535621734)
     | > align_error: 0.5599024891853333  (0.6035248935222626)

   --> STEP: 22
     | > decoder_loss: 0.44977623224258423  (0.448660364205187)
     | > postnet_loss: 0.30726009607315063  (0.3114132447676225)
     | > stopnet_loss: 0.0048168315552175045  (0.006383202758363702)
     | > loss: 0.19407591223716736  (0.19640160622921857)
     | > align_error: 0.6255238950252533  (0.6045248481360349)

   --> STEP: 23
     | > decoder_loss: 0.4227096736431122  (0.4475320733111838)
     | > postnet_loss: 0.29468512535095215  (0.3106859352277673)
     | > stopnet_loss: 0.004438864532858133  (0.0062986663137765036)
     | > loss: 0.18378756940364838  (0.19585316984549814)
     | > align_error: 0.567477285861969  (0.6029140845589016)

   --> STEP: 24
     | > decoder_loss: 0.45777788758277893  (0.4479589822391669)
     | > postnet_loss: 0.31125372648239136  (0.31070959319670993)
     | > stopnet_loss: 0.004384000785648823  (0.00621888858343785)
     | > loss: 0.19664190709590912  (0.1958860338975986)
     | > align_error: 0.5799325406551361  (0.601956520229578)

   --> STEP: 25
     | > decoder_loss: 0.4562181532382965  (0.4482893490791321)
     | > postnet_loss: 0.30798786878585815  (0.3106007242202759)
     | > stopnet_loss: 0.003684548893943429  (0.006117514995858073)
     | > loss: 0.1947360634803772  (0.19584003508090972)
     | > align_error: 0.5579039454460144  (0.6001944172382355)

   --> STEP: 26
     | > decoder_loss: 0.4309559464454651  (0.447622679747068)
     | > postnet_loss: 0.2961280047893524  (0.31004408116524035)
     | > stopnet_loss: 0.004339155275374651  (0.00604911654507025)
     | > loss: 0.18611013889312744  (0.19546580830445656)
     | > align_error: 0.54701828956604  (0.5981491815585357)

   --> STEP: 27
     | > decoder_loss: 0.4283788502216339  (0.44690994532020006)
     | > postnet_loss: 0.2917395532131195  (0.3093661356855322)
     | > stopnet_loss: 0.003904419718310237  (0.005969683329264323)
     | > loss: 0.1839340180158615  (0.19503870496043452)
     | > align_error: 0.5411973595619202  (0.5960398548179202)

   --> STEP: 28
     | > decoder_loss: 0.43383464217185974  (0.4464429702077593)
     | > postnet_loss: 0.296129047870636  (0.3088933825492859)
     | > stopnet_loss: 0.00391498813405633  (0.005896301358006895)
     | > loss: 0.18640589714050293  (0.19473039039543696)
     | > align_error: 0.5665533542633057  (0.5949867655123983)

   --> STEP: 29
     | > decoder_loss: 0.42859652638435364  (0.4458275755931591)
     | > postnet_loss: 0.29260551929473877  (0.3083317320922325)
     | > stopnet_loss: 0.0035698995925486088  (0.00581608060747385)
     | > loss: 0.18387040495872498  (0.1943559081389986)
     | > align_error: 0.5406496822834015  (0.5931130729872605)

   --> STEP: 30
     | > decoder_loss: 0.42872747778892517  (0.445257572333018)
     | > postnet_loss: 0.2932296097278595  (0.3078283280134201)
     | > stopnet_loss: 0.0028011079411953688  (0.005715581518597901)
     | > loss: 0.18329037725925446  (0.19398705710967382)
     | > align_error: 0.5335613489151001  (0.5911280155181885)

   --> STEP: 31
     | > decoder_loss: 0.42713573575019836  (0.4446729969593786)
     | > postnet_loss: 0.2929700016975403  (0.3073490271645208)
     | > stopnet_loss: 0.0036681003402918577  (0.0056495337386525445)
     | > loss: 0.18369454145431519  (0.19365504047562998)
     | > align_error: 0.5558343529701233  (0.5899895102747025)

   --> STEP: 32
     | > decoder_loss: 0.4375227391719818  (0.4444495514035225)
     | > postnet_loss: 0.2977500259876251  (0.30704905837774277)
     | > stopnet_loss: 0.003830696688964963  (0.005592695080849808)
     | > loss: 0.18764889240264893  (0.19346734834834933)
     | > align_error: 0.5312558114528656  (0.5881540821865201)

   --> STEP: 33
     | > decoder_loss: 0.4348851442337036  (0.444159720883225)
     | > postnet_loss: 0.29635822772979736  (0.3067250938126535)
     | > stopnet_loss: 0.003996178042143583  (0.005544315776646588)
     | > loss: 0.18680702149868011  (0.19326552026199573)
     | > align_error: 0.5462038815021515  (0.5868828639839635)

   --> STEP: 34
     | > decoder_loss: 0.4404989182949066  (0.4440520502188626)
     | > postnet_loss: 0.2977338433265686  (0.3064606452689451)
     | > stopnet_loss: 0.0032865710090845823  (0.005477911518777118)
     | > loss: 0.18784475326538086  (0.19310608593856587)
     | > align_error: 0.5639049410820007  (0.5862070427221411)

   --> STEP: 35
     | > decoder_loss: 0.43754419684410095  (0.4438661115510123)
     | > postnet_loss: 0.296465665102005  (0.30617507440703257)
     | > stopnet_loss: 0.003475801320746541  (0.005420708370261959)
     | > loss: 0.1869782656431198  (0.19293100535869598)
     | > align_error: 0.533381998538971  (0.584697755745479)

   --> STEP: 36
     | > decoder_loss: 0.4437631666660309  (0.44386325197087395)
     | > postnet_loss: 0.3014043867588043  (0.3060425553056929)
     | > stopnet_loss: 0.003644105978310108  (0.005371358303818852)
     | > loss: 0.18993599712848663  (0.1928478106856346)
     | > align_error: 0.6339658200740814  (0.5860663130879402)

   --> STEP: 37
     | > decoder_loss: 0.4363361597061157  (0.4436598170447994)
     | > postnet_loss: 0.2976917624473572  (0.3058168582014135)
     | > stopnet_loss: 0.003541048849001527  (0.005321890480715681)
     | > loss: 0.1870480328798294  (0.19269105993412636)
     | > align_error: 0.5193183720111847  (0.5842623146804603)

   --> STEP: 38
     | > decoder_loss: 0.4234306216239929  (0.44312746979688344)
     | > postnet_loss: 0.2903006076812744  (0.3054085358193046)
     | > stopnet_loss: 0.003129667602479458  (0.005264200404972622)
     | > loss: 0.18156246840953827  (0.19239820226242668)
     | > align_error: 0.5518869161605835  (0.5834103305088846)

   --> STEP: 39
     | > decoder_loss: 0.438843697309494  (0.443017629476694)
     | > postnet_loss: 0.30065667629241943  (0.3052866932673332)
     | > stopnet_loss: 0.0034523094072937965  (0.005217741661442396)
     | > loss: 0.18832741677761078  (0.1922938231474314)
     | > align_error: 0.5459067821502686  (0.5824487010637919)

   --> STEP: 40
     | > decoder_loss: 0.43624141812324524  (0.44284822419285774)
     | > postnet_loss: 0.2993873655796051  (0.30513921007514)
     | > stopnet_loss: 0.003017655573785305  (0.005162739509250969)
     | > loss: 0.18692484498023987  (0.1921595986932516)
     | > align_error: 0.5840634405612946  (0.5824890695512295)

   --> STEP: 41
     | > decoder_loss: 0.42707905173301697  (0.4424636102304226)
     | > postnet_loss: 0.29179489612579346  (0.30481373900320474)
     | > stopnet_loss: 0.003693642793223262  (0.005126907882030781)
     | > loss: 0.18341213464736938  (0.19194624591164472)
     | > align_error: 0.5032187700271606  (0.580555647611618)

   --> STEP: 42
     | > decoder_loss: 0.4316656291484833  (0.44220651544275735)
     | > postnet_loss: 0.2937563359737396  (0.3045504675025032)
     | > stopnet_loss: 0.003267120337113738  (0.005082627226199422)
     | > loss: 0.1846226155757904  (0.19177187376079105)
     | > align_error: 0.5796255469322205  (0.5805335023573467)

   --> STEP: 43
     | > decoder_loss: 0.43142157793045044  (0.44195570294247116)
     | > postnet_loss: 0.29312488436698914  (0.3042847562667936)
     | > stopnet_loss: 0.0029262350872159004  (0.005032478571804456)
     | > loss: 0.18406283855438232  (0.19159259387226993)
     | > align_error: 0.5519797801971436  (0.5798694623071093)

   --> STEP: 44
     | > decoder_loss: 0.4483143389225006  (0.44210021739656274)
     | > postnet_loss: 0.30313992500305176  (0.3042587373744358)
     | > stopnet_loss: 0.002653132425621152  (0.004978402523027563)
     | > loss: 0.19051669538021088  (0.19156814163381403)
     | > align_error: 0.5512793064117432  (0.5792196860367601)

   --> STEP: 45
     | > decoder_loss: 0.4422890245914459  (0.4421044131120046)
     | > postnet_loss: 0.3028990626335144  (0.3042285223801931)
     | > stopnet_loss: 0.003287805709987879  (0.004940833704960014)
     | > loss: 0.18958483636379242  (0.19152406818336912)
     | > align_error: 0.5527499914169312  (0.5786314706007639)

   --> STEP: 46
     | > decoder_loss: 0.4317656457424164  (0.44187965729962225)
     | > postnet_loss: 0.2936442196369171  (0.30399842884229583)
     | > stopnet_loss: 0.0031989016570150852  (0.004902965616961212)
     | > loss: 0.18455137312412262  (0.19137248785599417)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3489645286039873 (+0.025794484398581785)
     | > avg_decoder_loss: 0.437960323510748 (-9.608268737792969e-05)
     | > avg_postnet_loss: 0.30093678109573596 (-0.00018198562390892015)
     | > avg_stopnet_loss: 0.004348366641241944 (+3.0943545315312293e-07)
     | > avg_loss: 0.18907264349135486 (-6.920821738964911e-05)
     | > avg_align_error: 0.5715580320719517 (-0.000231881484840879)


 > EPOCH: 145/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 18:29:50)

   --> TIME: 2025-12-28 18:29:57 -- STEP: 5/150 -- GLOBAL_STEP: 21900
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4605075418949127  (0.45924475193023684)
     | > postnet_loss: 0.3912302553653717  (0.3927981913089752)
     | > stopnet_loss: 0.01241330336779356  (0.013744036667048931)
     | > loss: 0.22534775733947754  (0.22675477266311644)
     | > align_error: 0.7253649830818176  (0.7109076917171478)
     | > grad_norm: tensor(0.2985, device='cuda:0')  (tensor(0.2787, device='cuda:0'))
     | > step_time: 0.507  (0.4579566478729248)
     | > loader_time: 0.7487  (0.7489874839782715)


   --> TIME: 2025-12-28 18:30:39 -- STEP: 30/150 -- GLOBAL_STEP: 21925
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.47124090790748596  (0.46801788608233136)
     | > postnet_loss: 0.391545832157135  (0.3945852667093277)
     | > stopnet_loss: 0.005634302739053965  (0.009016107084850471)
     | > loss: 0.22133100032806396  (0.22466689497232437)
     | > align_error: 0.6117454469203949  (0.6661263932784398)
     | > grad_norm: tensor(0.2451, device='cuda:0')  (tensor(0.2358, device='cuda:0'))
     | > step_time: 0.995  (0.7003851095835368)
     | > loader_time: 0.9882  (0.8911503076553344)


   --> TIME: 2025-12-28 18:31:35 -- STEP: 55/150 -- GLOBAL_STEP: 21950
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4821769893169403  (0.4741713507608934)
     | > postnet_loss: 0.3952847719192505  (0.3962744815783067)
     | > stopnet_loss: 0.004254764411598444  (0.00721593365411867)
     | > loss: 0.22362020611763  (0.22482739172198557)
     | > align_error: 0.6473856866359711  (0.6447798344221982)
     | > grad_norm: tensor(0.1639, device='cuda:0')  (tensor(0.2337, device='cuda:0'))
     | > step_time: 1.3969  (0.9176836794072931)
     | > loader_time: 1.1645  (0.9655555508353494)


   --> TIME: 2025-12-28 18:32:47 -- STEP: 80/150 -- GLOBAL_STEP: 21975
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4782125949859619  (0.4769803874194622)
     | > postnet_loss: 0.391371488571167  (0.39616453535854823)
     | > stopnet_loss: 0.004279422573745251  (0.0062346547085326155)
     | > loss: 0.22167544066905975  (0.2245208853855729)
     | > align_error: 0.5856479704380035  (0.6335741080343723)
     | > grad_norm: tensor(0.2516, device='cuda:0')  (tensor(0.2214, device='cuda:0'))
     | > step_time: 1.4775  (1.0959526032209397)
     | > loader_time: 1.6581  (1.0970833241939546)


   --> TIME: 2025-12-28 18:34:10 -- STEP: 105/150 -- GLOBAL_STEP: 22000
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4828120470046997  (0.47817883888880414)
     | > postnet_loss: 0.39367014169692993  (0.39548420253254124)
     | > stopnet_loss: 0.003482365282252431  (0.005604278717544816)
     | > loss: 0.22260291874408722  (0.2240200387580054)
     | > align_error: 0.6113998591899872  (0.6294142294497714)
     | > grad_norm: tensor(0.1596, device='cuda:0')  (tensor(0.2106, device='cuda:0'))
     | > step_time: 1.7856  (1.2329272497267953)
     | > loader_time: 1.4672  (1.2315150033859974)


   --> TIME: 2025-12-28 18:35:40 -- STEP: 130/150 -- GLOBAL_STEP: 22025
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4815596342086792  (0.47913189415748303)
     | > postnet_loss: 0.3917863965034485  (0.39496364776904774)
     | > stopnet_loss: 0.003068020334467292  (0.00515130918759566)
     | > loss: 0.2214045226573944  (0.22367519438266753)
     | > align_error: 0.5973665118217468  (0.626298933304273)
     | > grad_norm: tensor(0.1542, device='cuda:0')  (tensor(0.2012, device='cuda:0'))
     | > step_time: 1.9787  (1.3588932055693408)
     | > loader_time: 1.6895  (1.3249468179849473)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4600759744644165  (0.4600759744644165)
     | > postnet_loss: 0.33409383893013  (0.33409383893013)
     | > stopnet_loss: 0.012218788266181946  (0.012218788266181946)
     | > loss: 0.21076123416423798  (0.21076123416423798)
     | > align_error: 0.7186365723609924  (0.7186365723609924)

   --> STEP: 1
     | > decoder_loss: 0.43994271755218506  (0.43994271755218506)
     | > postnet_loss: 0.32073378562927246  (0.32073378562927246)
     | > stopnet_loss: 0.00958319567143917  (0.00958319567143917)
     | > loss: 0.1997523158788681  (0.1997523158788681)
     | > align_error: 0.6594237685203552  (0.6594237685203552)

   --> STEP: 2
     | > decoder_loss: 0.4369107186794281  (0.4384267181158066)
     | > postnet_loss: 0.3125177323818207  (0.31662575900554657)
     | > stopnet_loss: 0.01102596614509821  (0.01030458090826869)
     | > loss: 0.19838307797908783  (0.19906769692897797)
     | > align_error: 0.655336320400238  (0.6573800444602966)

   --> STEP: 3
     | > decoder_loss: 0.44088149070739746  (0.43924497564633685)
     | > postnet_loss: 0.3121335208415985  (0.31512834628423053)
     | > stopnet_loss: 0.008260495029389858  (0.009623218948642412)
     | > loss: 0.19651424884796143  (0.19821654756863913)
     | > align_error: 0.7346072494983673  (0.6831224461396536)

   --> STEP: 4
     | > decoder_loss: 0.4452965259552002  (0.4407578632235527)
     | > postnet_loss: 0.31999123096466064  (0.3163440674543381)
     | > stopnet_loss: 0.008168374188244343  (0.009259507758542895)
     | > loss: 0.19949030876159668  (0.1985349878668785)
     | > align_error: 0.603021502494812  (0.6630972102284431)

   --> STEP: 5
     | > decoder_loss: 0.42621636390686035  (0.43784956336021424)
     | > postnet_loss: 0.3022247552871704  (0.31352020502090455)
     | > stopnet_loss: 0.008129877969622612  (0.009033581800758838)
     | > loss: 0.19024015963077545  (0.1968760222196579)
     | > align_error: 0.6415013074874878  (0.6587780296802521)

   --> STEP: 6
     | > decoder_loss: 0.44499337673187256  (0.4390401989221573)
     | > postnet_loss: 0.31458085775375366  (0.3136969804763794)
     | > stopnet_loss: 0.007257203105837107  (0.00873751868493855)
     | > loss: 0.19715076684951782  (0.1969218129913012)
     | > align_error: 0.5935358703136444  (0.6479043364524841)

   --> STEP: 7
     | > decoder_loss: 0.4565200209617615  (0.44153731635638643)
     | > postnet_loss: 0.3147260844707489  (0.3138439953327179)
     | > stopnet_loss: 0.006244771648198366  (0.008381411965404238)
     | > loss: 0.19905629754066467  (0.197226739355496)
     | > align_error: 0.5785295367240906  (0.6379936507769993)

   --> STEP: 8
     | > decoder_loss: 0.4521862268447876  (0.4428684301674366)
     | > postnet_loss: 0.316182404756546  (0.3141362965106964)
     | > stopnet_loss: 0.00758156506344676  (0.008281431102659553)
     | > loss: 0.19967371225357056  (0.19753261096775532)
     | > align_error: 0.5750986933708191  (0.6301317811012268)

   --> STEP: 9
     | > decoder_loss: 0.4462164342403412  (0.44324043061998153)
     | > postnet_loss: 0.3137231171131134  (0.31409038768874276)
     | > stopnet_loss: 0.006641856394708157  (0.008099256135109398)
     | > loss: 0.19662673771381378  (0.19743195838398403)
     | > align_error: 0.5909055173397064  (0.6257733073499467)

   --> STEP: 10
     | > decoder_loss: 0.4756285846233368  (0.4464792460203171)
     | > postnet_loss: 0.3301936984062195  (0.31570071876049044)
     | > stopnet_loss: 0.005825533997267485  (0.007871883921325207)
     | > loss: 0.20728109776973724  (0.19841687232255936)
     | > align_error: 0.5857931077480316  (0.6217752873897553)

   --> STEP: 11
     | > decoder_loss: 0.4586122930049896  (0.44758225029165094)
     | > postnet_loss: 0.318045437335968  (0.31591387499462475)
     | > stopnet_loss: 0.005891940090805292  (0.007691889027641578)
     | > loss: 0.20005635917186737  (0.19856591658158737)
     | > align_error: 0.5942288339138031  (0.6192710643464868)

   --> STEP: 12
     | > decoder_loss: 0.4557513892650604  (0.4482630118727684)
     | > postnet_loss: 0.31231820583343506  (0.3156142358978589)
     | > stopnet_loss: 0.007878528907895088  (0.007707442350996037)
     | > loss: 0.1998959332704544  (0.19867675130565962)
     | > align_error: 0.5871259868144989  (0.6165923078854878)

   --> STEP: 13
     | > decoder_loss: 0.4450753927230835  (0.4480178103997157)
     | > postnet_loss: 0.31217172741889954  (0.3153494275533236)
     | > stopnet_loss: 0.005569549277424812  (0.007542989037644405)
     | > loss: 0.19488131999969482  (0.19838479505135462)
     | > align_error: 0.5852941870689392  (0.6141847601303687)

   --> STEP: 14
     | > decoder_loss: 0.45921581983566284  (0.4488176682165691)
     | > postnet_loss: 0.31739136576652527  (0.315495280282838)
     | > stopnet_loss: 0.004913590382784605  (0.007355174848011562)
     | > loss: 0.19906537234783173  (0.1984334077153887)
     | > align_error: 0.5547623634338379  (0.6099403032234737)

   --> STEP: 15
     | > decoder_loss: 0.45396509766578674  (0.44916083017985026)
     | > postnet_loss: 0.31487587094306946  (0.31545398632685345)
     | > stopnet_loss: 0.005016929470002651  (0.007199291822810968)
     | > loss: 0.19722716510295868  (0.1983529915412267)
     | > align_error: 0.5883576273918152  (0.6085014581680298)

   --> STEP: 16
     | > decoder_loss: 0.453254759311676  (0.44941670075058937)
     | > postnet_loss: 0.3084107041358948  (0.3150137811899185)
     | > stopnet_loss: 0.005267653614282608  (0.007078564434777945)
     | > loss: 0.195684015750885  (0.19818618055433035)
     | > align_error: 0.6055292785167694  (0.608315696939826)

   --> STEP: 17
     | > decoder_loss: 0.46185240149497986  (0.45014821255908294)
     | > postnet_loss: 0.3179605305194855  (0.31518711938577537)
     | > stopnet_loss: 0.0048131258226931095  (0.006945303339949425)
     | > loss: 0.1997663527727127  (0.198279131861294)
     | > align_error: 0.5581766366958618  (0.6053663404548869)

   --> STEP: 18
     | > decoder_loss: 0.4549194574356079  (0.4504132817188899)
     | > postnet_loss: 0.3095335066318512  (0.31487302978833515)
     | > stopnet_loss: 0.005225702188909054  (0.006849769942669405)
     | > loss: 0.1963389366865158  (0.198171343240473)
     | > align_error: 0.6036844849586487  (0.6052729040384293)

   --> STEP: 19
     | > decoder_loss: 0.45367297530174255  (0.45058484453904)
     | > postnet_loss: 0.30981186032295227  (0.31460665244805186)
     | > stopnet_loss: 0.004781180992722511  (0.006740896840040621)
     | > loss: 0.19565239548683167  (0.19803876704291293)
     | > align_error: 0.5997746884822845  (0.6049835242723164)

   --> STEP: 20
     | > decoder_loss: 0.44923391938209534  (0.4505172982811928)
     | > postnet_loss: 0.305706650018692  (0.3141616523265839)
     | > stopnet_loss: 0.0045156329870224  (0.00662963364738971)
     | > loss: 0.19325077533721924  (0.19779936745762824)
     | > align_error: 0.6224112510681152  (0.6058549106121063)

   --> STEP: 21
     | > decoder_loss: 0.4466123580932617  (0.45033134874843417)
     | > postnet_loss: 0.3049011826515198  (0.31372067758015226)
     | > stopnet_loss: 0.003989722114056349  (0.006503923574373836)
     | > loss: 0.1918681114912033  (0.1975169266973223)
     | > align_error: 0.5593172907829285  (0.6036388334773836)

   --> STEP: 22
     | > decoder_loss: 0.4491892158985138  (0.45027943361889233)
     | > postnet_loss: 0.30769655108451843  (0.3134468536485326)
     | > stopnet_loss: 0.004843388218432665  (0.006428444694558328)
     | > loss: 0.19406482577323914  (0.1973600130189549)
     | > align_error: 0.625156432390213  (0.6046169061552394)

   --> STEP: 23
     | > decoder_loss: 0.42239201068878174  (0.4490669369697571)
     | > postnet_loss: 0.29531264305114746  (0.31265840970951586)
     | > stopnet_loss: 0.004452477674931288  (0.006342533085009326)
     | > loss: 0.18387864530086517  (0.19677386659642923)
     | > align_error: 0.5668631494045258  (0.6029754384704258)

   --> STEP: 24
     | > decoder_loss: 0.45645979046821594  (0.4493749725321929)
     | > postnet_loss: 0.3109900653362274  (0.31258889536062884)
     | > stopnet_loss: 0.0044169011525809765  (0.006262298421158145)
     | > loss: 0.1962793618440628  (0.1967532622317473)
     | > align_error: 0.5792960524559021  (0.6019887973864874)

   --> STEP: 25
     | > decoder_loss: 0.4551548361778259  (0.4496061670780182)
     | > postnet_loss: 0.3081231713294983  (0.31241026639938363)
     | > stopnet_loss: 0.003682689042761922  (0.006159114046022296)
     | > loss: 0.19450218975543976  (0.196663219332695)
     | > align_error: 0.5570572912693024  (0.6001915371418)

   --> STEP: 26
     | > decoder_loss: 0.4311271011829376  (0.44889543377436125)
     | > postnet_loss: 0.2973504662513733  (0.3118310433167678)
     | > stopnet_loss: 0.004320915322750807  (0.006088414095127239)
     | > loss: 0.18644031882286072  (0.19627003085154754)
     | > align_error: 0.5462607443332672  (0.5981172758799332)

   --> STEP: 27
     | > decoder_loss: 0.42722123861312866  (0.4480926858054267)
     | > postnet_loss: 0.2919313907623291  (0.31109401914808493)
     | > stopnet_loss: 0.003919533919543028  (0.006008085199735231)
     | > loss: 0.18370768427848816  (0.19580475875624903)
     | > align_error: 0.5405648946762085  (0.5959857062057212)

   --> STEP: 28
     | > decoder_loss: 0.4337758719921112  (0.44758137102637974)
     | > postnet_loss: 0.2969779074192047  (0.3105898723006249)
     | > stopnet_loss: 0.003927461802959442  (0.005933777221278953)
     | > loss: 0.18661591410636902  (0.19547658573303903)
     | > align_error: 0.5659334361553192  (0.5949124108467784)

   --> STEP: 29
     | > decoder_loss: 0.42843666672706604  (0.44692120880916203)
     | > postnet_loss: 0.29344502091407776  (0.309998670528675)
     | > stopnet_loss: 0.003564374754205346  (0.005852073687931587)
     | > loss: 0.1840347945690155  (0.19508204121014167)
     | > align_error: 0.5398926138877869  (0.593015176468882)

   --> STEP: 30
     | > decoder_loss: 0.428695946931839  (0.4463137000799179)
     | > postnet_loss: 0.2941887080669403  (0.3094716717799505)
     | > stopnet_loss: 0.0028066711965948343  (0.005750560271553695)
     | > loss: 0.1835278421640396  (0.19469690124193828)
     | > align_error: 0.5327699184417725  (0.5910070012013118)

   --> STEP: 31
     | > decoder_loss: 0.42994141578674316  (0.44578556187691226)
     | > postnet_loss: 0.29491671919822693  (0.3090021571805401)
     | > stopnet_loss: 0.0038906342815607786  (0.005690562658973278)
     | > loss: 0.18510517477989197  (0.19438749071090453)
     | > align_error: 0.5586904287338257  (0.5899645311217154)

   --> STEP: 32
     | > decoder_loss: 0.4383687376976013  (0.4455537861213088)
     | > postnet_loss: 0.2994758188724518  (0.3087044591084123)
     | > stopnet_loss: 0.003827737644314766  (0.0056323493772652)
     | > loss: 0.1882888823747635  (0.19419690920040011)
     | > align_error: 0.5303874015808105  (0.5881027458235621)

   --> STEP: 33
     | > decoder_loss: 0.43350324034690857  (0.4451886180675391)
     | > postnet_loss: 0.2963058650493622  (0.30832874413692596)
     | > stopnet_loss: 0.004012325778603554  (0.005583257753063332)
     | > loss: 0.1864646077156067  (0.19396259703419425)
     | > align_error: 0.54521244764328  (0.586803039818099)

   --> STEP: 34
     | > decoder_loss: 0.43936243653297424  (0.4450172597871107)
     | > postnet_loss: 0.2977274954319  (0.3080169427044252)
     | > stopnet_loss: 0.0032744668424129486  (0.005515352138044203)
     | > loss: 0.18754695355892181  (0.1937739016378627)
     | > align_error: 0.5631905794143677  (0.5861085556885776)

   --> STEP: 35
     | > decoder_loss: 0.43705230951309204  (0.4447896897792816)
     | > postnet_loss: 0.29702821373939514  (0.30770297901971005)
     | > stopnet_loss: 0.003481351537629962  (0.005457237835175224)
     | > loss: 0.18700149655342102  (0.1935804043497358)
     | > align_error: 0.5324702262878418  (0.5845760319914136)

   --> STEP: 36
     | > decoder_loss: 0.4424792230129242  (0.4447255101468828)
     | > postnet_loss: 0.3014075756072998  (0.30752810670269864)
     | > stopnet_loss: 0.0036507886834442616  (0.005407058692071587)
     | > loss: 0.18962249159812927  (0.19347046232885784)
     | > align_error: 0.6332776248455048  (0.5859288540151384)

   --> STEP: 37
     | > decoder_loss: 0.4357301890850067  (0.4444823933614267)
     | > postnet_loss: 0.2982386350631714  (0.30727703990163036)
     | > stopnet_loss: 0.0035513858310878277  (0.005356905371504459)
     | > loss: 0.18704359233379364  (0.19329676313980207)
     | > align_error: 0.5180380940437317  (0.5840939686105058)

   --> STEP: 38
     | > decoder_loss: 0.42240670323371887  (0.4439014541475396)
     | > postnet_loss: 0.29054659605026245  (0.30683676506343643)
     | > stopnet_loss: 0.0031339970882982016  (0.005298407785104295)
     | > loss: 0.18137232959270477  (0.19298296225698372)
     | > align_error: 0.5508306622505188  (0.5832186184431377)

   --> STEP: 39
     | > decoder_loss: 0.4381829500198364  (0.4437548258365729)
     | > postnet_loss: 0.3011922836303711  (0.30669203477028095)
     | > stopnet_loss: 0.0034651218447834253  (0.005251400453301196)
     | > loss: 0.1883089244365692  (0.19286311513338336)
     | > align_error: 0.5453114807605743  (0.5822466405538412)

   --> STEP: 40
     | > decoder_loss: 0.4351578950881958  (0.44353990256786346)
     | > postnet_loss: 0.29963600635528564  (0.30651563405990606)
     | > stopnet_loss: 0.003032498760148883  (0.005195927910972388)
     | > loss: 0.1867309808731079  (0.19270981177687646)
     | > align_error: 0.5829572081565857  (0.5822644047439098)

   --> STEP: 41
     | > decoder_loss: 0.4265177845954895  (0.4431247289587812)
     | > postnet_loss: 0.2923920750617981  (0.3061711570111717)
     | > stopnet_loss: 0.0037113013677299023  (0.005159717507478669)
     | > loss: 0.1834387630224228  (0.19248368863652393)
     | > align_error: 0.5025488436222076  (0.5803201227653317)

   --> STEP: 42
     | > decoder_loss: 0.4315322935581207  (0.4428487185920988)
     | > postnet_loss: 0.2945905029773712  (0.3058954271532241)
     | > stopnet_loss: 0.0032663182355463505  (0.005114636572432661)
     | > loss: 0.1847970187664032  (0.19230067268723533)
     | > align_error: 0.5787513852119446  (0.5802827718712035)

   --> STEP: 43
     | > decoder_loss: 0.42983028292655945  (0.44254596427429554)
     | > postnet_loss: 0.2928137183189392  (0.30559120136638024)
     | > stopnet_loss: 0.002927053952589631  (0.005063762558017706)
     | > loss: 0.18358804285526276  (0.19209805338881736)
     | > align_error: 0.5509426891803741  (0.5796004443667656)

   --> STEP: 44
     | > decoder_loss: 0.4482470750808716  (0.442675534974445)
     | > postnet_loss: 0.3041583001613617  (0.3055586354299025)
     | > stopnet_loss: 0.0026452173478901386  (0.005008795621423898)
     | > loss: 0.19074657559394836  (0.19206733798438852)
     | > align_error: 0.5503169298171997  (0.5789349099451845)

   --> STEP: 45
     | > decoder_loss: 0.44065040349960327  (0.44263053205278186)
     | > postnet_loss: 0.3028375804424286  (0.305498167541292)
     | > stopnet_loss: 0.0032857581973075867  (0.004970505900887981)
     | > loss: 0.18915775418281555  (0.1920026805665758)
     | > align_error: 0.5518784523010254  (0.5783336553308698)

   --> STEP: 46
     | > decoder_loss: 0.4307529926300049  (0.4423723246740258)
     | > postnet_loss: 0.2939189374446869  (0.3052464451478875)
     | > stopnet_loss: 0.003196599893271923  (0.00493194272680937)
     | > loss: 0.18436458706855774  (0.1918366350557493)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35725951917243726 (+0.008294990568449956)
     | > avg_decoder_loss: 0.4382288839780923 (+0.00026856046734430317)
     | > avg_postnet_loss: 0.3021243079142137 (+0.0011875268184777243)
     | > avg_stopnet_loss: 0.004371224316965901 (+2.2857675723957083e-05)
     | > avg_loss: 0.18945952166210522 (+0.00038687817075036546)
     | > avg_align_error: 0.5710709126609744 (-0.00048711941097723255)


 > EPOCH: 146/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 18:38:58)

   --> TIME: 2025-12-28 18:39:03 -- STEP: 4/150 -- GLOBAL_STEP: 22050
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4613315165042877  (0.4575928822159767)
     | > postnet_loss: 0.394295334815979  (0.39189213514328003)
     | > stopnet_loss: 0.013281278312206268  (0.014352382393553853)
     | > loss: 0.22718799114227295  (0.22672363743185997)
     | > align_error: 0.686455488204956  (0.7076042294502258)
     | > grad_norm: tensor(0.3623, device='cuda:0')  (tensor(0.3290, device='cuda:0'))
     | > step_time: 0.4608  (0.40962523221969604)
     | > loader_time: 0.6049  (0.5731620192527771)


   --> TIME: 2025-12-28 18:39:43 -- STEP: 29/150 -- GLOBAL_STEP: 22075
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.4808104634284973  (0.46718845182451707)
     | > postnet_loss: 0.4016399383544922  (0.39414361735870096)
     | > stopnet_loss: 0.0062009054236114025  (0.009180419050670904)
     | > loss: 0.22681351006031036  (0.2245134356720694)
     | > align_error: 0.6735185980796814  (0.6671945216326878)
     | > grad_norm: tensor(0.1979, device='cuda:0')  (tensor(0.2506, device='cuda:0'))
     | > step_time: 1.0049  (0.6875416245953789)
     | > loader_time: 0.8825  (0.8234266412669214)


   --> TIME: 2025-12-28 18:40:38 -- STEP: 54/150 -- GLOBAL_STEP: 22100
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4790697991847992  (0.47365689277648926)
     | > postnet_loss: 0.3926798403263092  (0.3959271389025229)
     | > stopnet_loss: 0.004749265965074301  (0.0072778951273196274)
     | > loss: 0.22268667817115784  (0.22467390254691796)
     | > align_error: 0.5777601003646851  (0.6440974540180632)
     | > grad_norm: tensor(0.1306, device='cuda:0')  (tensor(0.2296, device='cuda:0'))
     | > step_time: 1.2535  (0.9142236930352671)
     | > loader_time: 1.1824  (0.9235756927066379)


   --> TIME: 2025-12-28 18:41:48 -- STEP: 79/150 -- GLOBAL_STEP: 22125
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48610302805900574  (0.47664435415328305)
     | > postnet_loss: 0.396305650472641  (0.3959017543098594)
     | > stopnet_loss: 0.004036202561110258  (0.006247488327937412)
     | > loss: 0.22463837265968323  (0.22438401587401766)
     | > align_error: 0.5940536260604858  (0.6347281457502633)
     | > grad_norm: tensor(0.1430, device='cuda:0')  (tensor(0.2277, device='cuda:0'))
     | > step_time: 1.6727  (1.1061006135578397)
     | > loader_time: 1.4773  (1.0352011813393123)


   --> TIME: 2025-12-28 18:43:09 -- STEP: 104/150 -- GLOBAL_STEP: 22150
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4899216294288635  (0.47795535079561746)
     | > postnet_loss: 0.398048460483551  (0.39533346662154567)
     | > stopnet_loss: 0.0032845742534846067  (0.005610761353566956)
     | > loss: 0.2252770960330963  (0.22393296644664729)
     | > align_error: 0.6132419109344482  (0.6299002683506563)
     | > grad_norm: tensor(0.1268, device='cuda:0')  (tensor(0.2166, device='cuda:0'))
     | > step_time: 1.7521  (1.2475370535483739)
     | > loader_time: 1.5573  (1.1530316036481125)


   --> TIME: 2025-12-28 18:44:42 -- STEP: 129/150 -- GLOBAL_STEP: 22175
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48352527618408203  (0.4790264472018841)
     | > postnet_loss: 0.3934558033943176  (0.3948763241601545)
     | > stopnet_loss: 0.0031303181312978268  (0.0051556695324852485)
     | > loss: 0.22237558662891388  (0.22363136327543923)
     | > align_error: 0.6604067385196686  (0.6264616054619929)
     | > grad_norm: tensor(0.2061, device='cuda:0')  (tensor(0.2085, device='cuda:0'))
     | > step_time: 1.9316  (1.3690034955046906)
     | > loader_time: 2.2781  (1.2849568599878356)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46009546518325806  (0.46009546518325806)
     | > postnet_loss: 0.334676593542099  (0.334676593542099)
     | > stopnet_loss: 0.01204637624323368  (0.01204637624323368)
     | > loss: 0.2107393890619278  (0.2107393890619278)
     | > align_error: 0.7185087203979492  (0.7185087203979492)

   --> STEP: 1
     | > decoder_loss: 0.4411746561527252  (0.4411746561527252)
     | > postnet_loss: 0.32259401679039  (0.32259401679039)
     | > stopnet_loss: 0.009619930759072304  (0.009619930759072304)
     | > loss: 0.20056210458278656  (0.20056210458278656)
     | > align_error: 0.6586388945579529  (0.6586388945579529)

   --> STEP: 2
     | > decoder_loss: 0.438239187002182  (0.4397069215774536)
     | > postnet_loss: 0.3134569525718689  (0.31802548468112946)
     | > stopnet_loss: 0.010995328426361084  (0.010307629592716694)
     | > loss: 0.1989193558692932  (0.1997407302260399)
     | > align_error: 0.6548460125923157  (0.6567424535751343)

   --> STEP: 3
     | > decoder_loss: 0.44141387939453125  (0.4402759075164795)
     | > postnet_loss: 0.3126753866672516  (0.3162421186765035)
     | > stopnet_loss: 0.008076387457549572  (0.009563882214327654)
     | > loss: 0.19659869372844696  (0.19869338472684225)
     | > align_error: 0.7344885468482971  (0.6826578179995219)

   --> STEP: 4
     | > decoder_loss: 0.4455062747001648  (0.4415834993124008)
     | > postnet_loss: 0.32058969140052795  (0.3173290118575096)
     | > stopnet_loss: 0.008071494288742542  (0.009190785232931376)
     | > loss: 0.19959549605846405  (0.1989189125597477)
     | > align_error: 0.6025175154209137  (0.6626227423548698)

   --> STEP: 5
     | > decoder_loss: 0.4263870120048523  (0.4385442018508911)
     | > postnet_loss: 0.3020200729370117  (0.31426722407341)
     | > stopnet_loss: 0.008028829470276833  (0.008958394080400467)
     | > loss: 0.19013060629367828  (0.1971612513065338)
     | > align_error: 0.6409940719604492  (0.6582970082759857)

   --> STEP: 6
     | > decoder_loss: 0.4450056552886963  (0.43962111075719196)
     | > postnet_loss: 0.3150516748428345  (0.3143979658683141)
     | > stopnet_loss: 0.007178337313234806  (0.008661717952539524)
     | > loss: 0.19719266891479492  (0.19716648757457733)
     | > align_error: 0.5926637351512909  (0.6473581294218699)

   --> STEP: 7
     | > decoder_loss: 0.4562094509601593  (0.4419908736433302)
     | > postnet_loss: 0.3146866261959076  (0.3144392030579703)
     | > stopnet_loss: 0.006197620648890734  (0.008309704052018268)
     | > loss: 0.19892163574695587  (0.19741722302777426)
     | > align_error: 0.577936202287674  (0.6374407112598419)

   --> STEP: 8
     | > decoder_loss: 0.44955283403396606  (0.44293611869215965)
     | > postnet_loss: 0.3150578439235687  (0.3145165331661701)
     | > stopnet_loss: 0.007291295100003481  (0.00818240293301642)
     | > loss: 0.1984439641237259  (0.19754556566476822)
     | > align_error: 0.5742321908473969  (0.6295396462082863)

   --> STEP: 9
     | > decoder_loss: 0.4472843408584595  (0.4434192544884152)
     | > postnet_loss: 0.3148631155490875  (0.3145550423198276)
     | > stopnet_loss: 0.006604601629078388  (0.008007091677023305)
     | > loss: 0.19714145362377167  (0.1975006643268797)
     | > align_error: 0.590034157037735  (0.6251501474115584)

   --> STEP: 10
     | > decoder_loss: 0.47233065962791443  (0.44631039500236513)
     | > postnet_loss: 0.32897618412971497  (0.31599715650081633)
     | > stopnet_loss: 0.0055388170294463634  (0.007760264212265611)
     | > loss: 0.2058655321598053  (0.19833715111017228)
     | > align_error: 0.5825387537479401  (0.6208890080451965)

   --> STEP: 11
     | > decoder_loss: 0.4593857228755951  (0.44749906117265875)
     | > postnet_loss: 0.31872162222862244  (0.3162448352033442)
     | > stopnet_loss: 0.0058628106489777565  (0.007587768433784897)
     | > loss: 0.20038965344429016  (0.19852374223145572)
     | > align_error: 0.5937995910644531  (0.6184263337742198)

   --> STEP: 12
     | > decoder_loss: 0.4564148187637329  (0.44824204097191495)
     | > postnet_loss: 0.31321480870246887  (0.3159923329949379)
     | > stopnet_loss: 0.00792367197573185  (0.007615760395613809)
     | > loss: 0.20033107697963715  (0.19867435346047083)
     | > align_error: 0.5863441526889801  (0.6157528186837832)

   --> STEP: 13
     | > decoder_loss: 0.4448147416114807  (0.44797840255957383)
     | > postnet_loss: 0.3122654855251312  (0.3157056524203374)
     | > stopnet_loss: 0.005346706137061119  (0.007441217760340526)
     | > loss: 0.19461674988269806  (0.19836223010833448)
     | > align_error: 0.5841195285320282  (0.6133194886721097)

   --> STEP: 14
     | > decoder_loss: 0.4551912546157837  (0.44849360627787455)
     | > postnet_loss: 0.31487593054771423  (0.3156463865722929)
     | > stopnet_loss: 0.004884832073003054  (0.007258618782673564)
     | > loss: 0.19740164279937744  (0.19829361672912324)
     | > align_error: 0.5535701513290405  (0.6090516788618905)

   --> STEP: 15
     | > decoder_loss: 0.45451778173446655  (0.44889521797498066)
     | > postnet_loss: 0.3149779736995697  (0.31560182571411133)
     | > stopnet_loss: 0.004961458500474691  (0.007105474763860305)
     | > loss: 0.1973353922367096  (0.19822973509629568)
     | > align_error: 0.5876641273498535  (0.6076258420944214)

   --> STEP: 16
     | > decoder_loss: 0.45415717363357544  (0.44922409020364285)
     | > postnet_loss: 0.3087168037891388  (0.31517151184380054)
     | > stopnet_loss: 0.00523607712239027  (0.006988637411268428)
     | > loss: 0.1959545761346817  (0.1980875376611948)
     | > align_error: 0.6049313545227051  (0.6074574366211891)

   --> STEP: 17
     | > decoder_loss: 0.4620879888534546  (0.44998079012422)
     | > postnet_loss: 0.3179728388786316  (0.3153362957870259)
     | > stopnet_loss: 0.004788480699062347  (0.006859216428197482)
     | > loss: 0.1998036801815033  (0.19818848722121296)
     | > align_error: 0.5577743649482727  (0.6045349029933705)

   --> STEP: 18
     | > decoder_loss: 0.4553210735321045  (0.45027747253576916)
     | > postnet_loss: 0.3096281588077545  (0.3150191770659553)
     | > stopnet_loss: 0.005178743973374367  (0.0067658568473739755)
     | > loss: 0.19641605019569397  (0.19809001849757302)
     | > align_error: 0.6031367778778076  (0.6044572293758392)

   --> STEP: 19
     | > decoder_loss: 0.4519159495830536  (0.45036370816983673)
     | > postnet_loss: 0.30908823013305664  (0.3147070219642238)
     | > stopnet_loss: 0.004694896284490824  (0.006656858923011704)
     | > loss: 0.19494594633579254  (0.19792454101537404)
     | > align_error: 0.5981728136539459  (0.6041264706536343)

   --> STEP: 20
     | > decoder_loss: 0.4493018388748169  (0.45031061470508577)
     | > postnet_loss: 0.3052058815956116  (0.3142319649457932)
     | > stopnet_loss: 0.004481600131839514  (0.006548095983453095)
     | > loss: 0.19310852885246277  (0.19768374040722847)
     | > align_error: 0.6220507621765137  (0.6050226852297783)

   --> STEP: 21
     | > decoder_loss: 0.44647321105003357  (0.4501278811977023)
     | > postnet_loss: 0.3045591115951538  (0.31377135288147706)
     | > stopnet_loss: 0.003942457493394613  (0.006424017960116977)
     | > loss: 0.1917005479335785  (0.1973988264799118)
     | > align_error: 0.5587880611419678  (0.6028210364636921)

   --> STEP: 22
     | > decoder_loss: 0.4471603035926819  (0.449992991306565)
     | > postnet_loss: 0.30654647946357727  (0.3134429495442998)
     | > stopnet_loss: 0.004531417973339558  (0.00633799068799073)
     | > loss: 0.19295811653137207  (0.19719697602770545)
     | > align_error: 0.6237788498401642  (0.6037736643444408)

   --> STEP: 23
     | > decoder_loss: 0.4223271608352661  (0.4487901291121607)
     | > postnet_loss: 0.2948821187019348  (0.3126359568989796)
     | > stopnet_loss: 0.0044281273148953915  (0.006254953150030064)
     | > loss: 0.18373045325279236  (0.19661147503749185)
     | > align_error: 0.5663513541221619  (0.6021466073782548)

   --> STEP: 24
     | > decoder_loss: 0.4562930464744568  (0.4491027506689231)
     | > postnet_loss: 0.310605525970459  (0.31255135561029124)
     | > stopnet_loss: 0.004398508463054895  (0.006177601288072765)
     | > loss: 0.1961231529712677  (0.1965911282847325)
     | > align_error: 0.5787520408630371  (0.6011718337734541)

   --> STEP: 25
     | > decoder_loss: 0.45524609088897705  (0.4493484842777252)
     | > postnet_loss: 0.3079450726509094  (0.31236710429191594)
     | > stopnet_loss: 0.0036425450816750526  (0.006076199039816856)
     | > loss: 0.1944403350353241  (0.19650509655475618)
     | > align_error: 0.5563703775405884  (0.5993797755241395)

   --> STEP: 26
     | > decoder_loss: 0.43026766180992126  (0.448614606490502)
     | > postnet_loss: 0.2963968515396118  (0.3117528638014427)
     | > stopnet_loss: 0.004315064754337072  (0.006008463105759942)
     | > loss: 0.18598119914531708  (0.19610033126977774)
     | > align_error: 0.545687347650528  (0.5973146821443852)

   --> STEP: 27
     | > decoder_loss: 0.4275331497192383  (0.44783381179527)
     | > postnet_loss: 0.29183146357536316  (0.31101503416343973)
     | > stopnet_loss: 0.003879416501149535  (0.005929609527811408)
     | > loss: 0.18372057378292084  (0.19564182173322747)
     | > align_error: 0.5399402379989624  (0.5951897027315917)

   --> STEP: 28
     | > decoder_loss: 0.4333985447883606  (0.4473182665450232)
     | > postnet_loss: 0.2964490056037903  (0.31049481885773794)
     | > stopnet_loss: 0.003895663656294346  (0.005856968603828656)
     | > loss: 0.1863575577735901  (0.19531024087752616)
     | > align_error: 0.5655732750892639  (0.5941319731729371)

   --> STEP: 29
     | > decoder_loss: 0.42872729897499084  (0.4466771986977807)
     | > postnet_loss: 0.2935130298137665  (0.3099092399251872)
     | > stopnet_loss: 0.0035510649904608727  (0.0057774546861263185)
     | > loss: 0.18411114811897278  (0.19492406526516223)
     | > align_error: 0.5395039319992065  (0.5922482476152223)

   --> STEP: 30
     | > decoder_loss: 0.42849037051200867  (0.44607097109158833)
     | > postnet_loss: 0.2935698926448822  (0.30936459501584374)
     | > stopnet_loss: 0.0027768465224653482  (0.005677434414004286)
     | > loss: 0.18329191207885742  (0.19453632682561875)
     | > align_error: 0.5326022207736969  (0.5902600467205048)

   --> STEP: 31
     | > decoder_loss: 0.42388901114463806  (0.44535542399652545)
     | > postnet_loss: 0.2916775941848755  (0.3087940466019415)
     | > stopnet_loss: 0.0036654151044785976  (0.005612530565309909)
     | > loss: 0.18255707621574402  (0.19414989938659052)
     | > align_error: 0.5534757971763611  (0.5890734580255323)

   --> STEP: 32
     | > decoder_loss: 0.4375365376472473  (0.4451110837981105)
     | > postnet_loss: 0.29882150888442993  (0.30848240479826927)
     | > stopnet_loss: 0.003819645382463932  (0.005556502903345972)
     | > loss: 0.18790915608406067  (0.19395487615838647)
     | > align_error: 0.5299124717712402  (0.5872246772050858)

   --> STEP: 33
     | > decoder_loss: 0.43338581919670105  (0.44475577274958294)
     | > postnet_loss: 0.29586538672447205  (0.3081000709172451)
     | > stopnet_loss: 0.003995962906628847  (0.005509213812536363)
     | > loss: 0.18630877137184143  (0.19372317601333966)
     | > align_error: 0.5449708998203278  (0.5859442597085779)

   --> STEP: 34
     | > decoder_loss: 0.43948855996131897  (0.4446008547263987)
     | > postnet_loss: 0.2974688410758972  (0.30778738768661723)
     | > stopnet_loss: 0.0032335123978555202  (0.005442281417986926)
     | > loss: 0.187472864985466  (0.19353934333604925)
     | > align_error: 0.5626285672187805  (0.5852585040471133)

   --> STEP: 35
     | > decoder_loss: 0.43663033843040466  (0.4443731256893703)
     | > postnet_loss: 0.2966200113296509  (0.30746831979070394)
     | > stopnet_loss: 0.003478853963315487  (0.005386183490710599)
     | > loss: 0.18679144978523254  (0.1933465463774545)
     | > align_error: 0.5321688055992126  (0.5837416555200304)

   --> STEP: 36
     | > decoder_loss: 0.4428369700908661  (0.444330454700523)
     | > postnet_loss: 0.3012465238571167  (0.3072954921258821)
     | > stopnet_loss: 0.0036175313871353865  (0.005337054265611287)
     | > loss: 0.1896384060382843  (0.19324354247914421)
     | > align_error: 0.6329223215579987  (0.5851077851321962)

   --> STEP: 37
     | > decoder_loss: 0.43535315990448  (0.44408782511144074)
     | > postnet_loss: 0.29769793152809143  (0.30703609859621206)
     | > stopnet_loss: 0.0035307323560118675  (0.005288234754541033)
     | > loss: 0.1867934912443161  (0.19306921677009478)
     | > align_error: 0.517780601978302  (0.5832881315334423)

   --> STEP: 38
     | > decoder_loss: 0.4222639203071594  (0.4435135118271175)
     | > postnet_loss: 0.2901309132575989  (0.3065912252978275)
     | > stopnet_loss: 0.0031145887915045023  (0.00523103354498744)
     | > loss: 0.18121330440044403  (0.1927572190761566)
     | > align_error: 0.5506330132484436  (0.5824287863154161)

   --> STEP: 39
     | > decoder_loss: 0.4382420778274536  (0.44337834685276717)
     | > postnet_loss: 0.30088549852371216  (0.30644492461131173)
     | > stopnet_loss: 0.00343680870719254  (0.005185027779915776)
     | > loss: 0.18821869790554047  (0.19264084673844847)
     | > align_error: 0.5449877977371216  (0.5814687609672546)

   --> STEP: 40
     | > decoder_loss: 0.43527624011039734  (0.44317579418420794)
     | > postnet_loss: 0.299363911151886  (0.3062678992748261)
     | > stopnet_loss: 0.002998020965605974  (0.005130352609558031)
     | > loss: 0.18665805459022522  (0.19249127693474288)
     | > align_error: 0.5827203392982483  (0.5815000504255294)

   --> STEP: 41
     | > decoder_loss: 0.42644253373146057  (0.4427676658804824)
     | > postnet_loss: 0.29199638962745667  (0.30591981367367077)
     | > stopnet_loss: 0.0037277396768331528  (0.005096142538028156)
     | > loss: 0.18333746492862701  (0.19226801322727663)
     | > align_error: 0.5020354390144348  (0.5795618891716003)

   --> STEP: 42
     | > decoder_loss: 0.43037450313568115  (0.4424725905770347)
     | > postnet_loss: 0.2933661937713623  (0.30562091796171104)
     | > stopnet_loss: 0.0032559470273554325  (0.005052328359202615)
     | > loss: 0.18419112265110016  (0.1920757063087962)
     | > align_error: 0.5784650444984436  (0.5795357738222394)

   --> STEP: 43
     | > decoder_loss: 0.43001216650009155  (0.44218281327291975)
     | > postnet_loss: 0.2925831973552704  (0.3053177151569101)
     | > stopnet_loss: 0.0029058861546218395  (0.005002411098630969)
     | > loss: 0.1835547238588333  (0.19187754392623893)
     | > align_error: 0.5508471131324768  (0.5788685956666635)

   --> STEP: 44
     | > decoder_loss: 0.4478631615638733  (0.44231191209771414)
     | > postnet_loss: 0.3034779727458954  (0.305275902829387)
     | > stopnet_loss: 0.00264191091991961  (0.0049487633672966195)
     | > loss: 0.190477192401886  (0.1918457177552309)
     | > align_error: 0.5498658418655396  (0.5782094421711834)

   --> STEP: 45
     | > decoder_loss: 0.4411226212978363  (0.44228548341327245)
     | > postnet_loss: 0.30263957381248474  (0.30521731774012245)
     | > stopnet_loss: 0.0032542338594794273  (0.0049111071560117925)
     | > loss: 0.18919478356838226  (0.19178680810663426)
     | > align_error: 0.551462322473526  (0.5776150617334577)

   --> STEP: 46
     | > decoder_loss: 0.43129420280456543  (0.44204654253047443)
     | > postnet_loss: 0.2938414514064789  (0.30497001629808673)
     | > stopnet_loss: 0.0031658236403018236  (0.0048731662100180975)
     | > loss: 0.18444974720478058  (0.19162730678268095)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3553844148462469 (-0.0018751043261903688)
     | > avg_decoder_loss: 0.43805123188278894 (-0.0001776520953033489)
     | > avg_postnet_loss: 0.301850627317573 (-0.0002736805966406797)
     | > avg_stopnet_loss: 0.004326060844698189 (-4.516347226771276e-05)
     | > avg_loss: 0.18930152668194333 (-0.00015799498016189073)
     | > avg_align_error: 0.5704748874360864 (-0.0005960252248879971)


 > EPOCH: 147/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 18:48:01)

   --> TIME: 2025-12-28 18:48:06 -- STEP: 3/150 -- GLOBAL_STEP: 22200
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45716115832328796  (0.45498982071876526)
     | > postnet_loss: 0.3918618857860565  (0.3907039264837901)
     | > stopnet_loss: 0.013819827698171139  (0.014713622940083345)
     | > loss: 0.22607558965682983  (0.22613705694675446)
     | > align_error: 0.6978035271167755  (0.7140065630276998)
     | > grad_norm: tensor(0.3217, device='cuda:0')  (tensor(0.3021, device='cuda:0'))
     | > step_time: 0.4571  (0.4153281052907308)
     | > loader_time: 0.778  (0.7547874450683594)


   --> TIME: 2025-12-28 18:48:47 -- STEP: 28/150 -- GLOBAL_STEP: 22225
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.4778710603713989  (0.46680738564048496)
     | > postnet_loss: 0.3977399468421936  (0.39394185692071915)
     | > stopnet_loss: 0.005792782176285982  (0.009124724393976586)
     | > loss: 0.22469553351402283  (0.224312034036432)
     | > align_error: 0.644324779510498  (0.6668672944818225)
     | > grad_norm: tensor(0.2510, device='cuda:0')  (tensor(0.2651, device='cuda:0'))
     | > step_time: 0.8914  (0.6822732090950012)
     | > loader_time: 0.898  (0.9138685890606472)


   --> TIME: 2025-12-28 18:49:42 -- STEP: 53/150 -- GLOBAL_STEP: 22250
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48084479570388794  (0.4736909534571306)
     | > postnet_loss: 0.3954140543937683  (0.3960318216737711)
     | > stopnet_loss: 0.004290884826332331  (0.007262109752463284)
     | > loss: 0.22335559129714966  (0.22469280266536856)
     | > align_error: 0.5800338387489319  (0.6454847668701748)
     | > grad_norm: tensor(0.1978, device='cuda:0')  (tensor(0.2422, device='cuda:0'))
     | > step_time: 1.2675  (0.8939582806713178)
     | > loader_time: 1.5631  (0.981527899796108)


   --> TIME: 2025-12-28 18:50:52 -- STEP: 78/150 -- GLOBAL_STEP: 22275
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4850340187549591  (0.47660687527595424)
     | > postnet_loss: 0.3969089388847351  (0.3959139184309886)
     | > stopnet_loss: 0.003991916310042143  (0.006244378922602689)
     | > loss: 0.22447766363620758  (0.22437457606578484)
     | > align_error: 0.6162442266941071  (0.6349930419371678)
     | > grad_norm: tensor(0.1899, device='cuda:0')  (tensor(0.2346, device='cuda:0'))
     | > step_time: 1.5102  (1.0736285050710044)
     | > loader_time: 1.9019  (1.1023572041438172)


   --> TIME: 2025-12-28 18:52:14 -- STEP: 103/150 -- GLOBAL_STEP: 22300
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48861241340637207  (0.47792091907806766)
     | > postnet_loss: 0.39733603596687317  (0.39528435613345175)
     | > stopnet_loss: 0.0033934656530618668  (0.005611365631638657)
     | > loss: 0.22488057613372803  (0.22391268350545643)
     | > align_error: 0.5952085852622986  (0.6299801980986182)
     | > grad_norm: tensor(0.1672, device='cuda:0')  (tensor(0.2179, device='cuda:0'))
     | > step_time: 1.7046  (1.2106750867899185)
     | > loader_time: 1.6409  (1.2349819859254705)


   --> TIME: 2025-12-28 18:53:43 -- STEP: 128/150 -- GLOBAL_STEP: 22325
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4855078160762787  (0.47891730279661715)
     | > postnet_loss: 0.3932107090950012  (0.3947954778559506)
     | > stopnet_loss: 0.0033627694938331842  (0.0051504146995284845)
     | > loss: 0.22304239869117737  (0.22357860894408077)
     | > align_error: 0.6182839572429657  (0.626318524591625)
     | > grad_norm: tensor(0.1590, device='cuda:0')  (tensor(0.2078, device='cuda:0'))
     | > step_time: 1.9932  (1.3399487230926757)
     | > loader_time: 2.195  (1.3241373561322687)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4613914489746094  (0.4613914489746094)
     | > postnet_loss: 0.3343799412250519  (0.3343799412250519)
     | > stopnet_loss: 0.012269610539078712  (0.012269610539078712)
     | > loss: 0.21121245622634888  (0.21121245622634888)
     | > align_error: 0.71837517619133  (0.71837517619133)

   --> STEP: 1
     | > decoder_loss: 0.442493736743927  (0.442493736743927)
     | > postnet_loss: 0.32210564613342285  (0.32210564613342285)
     | > stopnet_loss: 0.009600932709872723  (0.009600932709872723)
     | > loss: 0.20075078308582306  (0.20075078308582306)
     | > align_error: 0.658780574798584  (0.658780574798584)

   --> STEP: 2
     | > decoder_loss: 0.435115784406662  (0.4388047605752945)
     | > postnet_loss: 0.3114185035228729  (0.3167620748281479)
     | > stopnet_loss: 0.010938909836113453  (0.010269921272993088)
     | > loss: 0.1975724846124649  (0.19916163384914398)
     | > align_error: 0.654752790927887  (0.6567666828632355)

   --> STEP: 3
     | > decoder_loss: 0.4403536915779114  (0.4393210709095001)
     | > postnet_loss: 0.3112976551055908  (0.31494060158729553)
     | > stopnet_loss: 0.00819912739098072  (0.009579656645655632)
     | > loss: 0.19611196219921112  (0.1981450766324997)
     | > align_error: 0.7342901527881622  (0.6826078395048777)

   --> STEP: 4
     | > decoder_loss: 0.44544366002082825  (0.44085171818733215)
     | > postnet_loss: 0.3192474842071533  (0.31601732224226)
     | > stopnet_loss: 0.008167843334376812  (0.009226703317835927)
     | > loss: 0.19934062659740448  (0.1984439641237259)
     | > align_error: 0.602609395980835  (0.662608228623867)

   --> STEP: 5
     | > decoder_loss: 0.4268510341644287  (0.43805158138275146)
     | > postnet_loss: 0.30171120166778564  (0.3131560981273651)
     | > stopnet_loss: 0.008123980835080147  (0.009006158821284771)
     | > loss: 0.1902645379304886  (0.19680807888507842)
     | > align_error: 0.6410245299339294  (0.6582914888858795)

   --> STEP: 6
     | > decoder_loss: 0.44417518377304077  (0.439072181781133)
     | > postnet_loss: 0.3136593699455261  (0.3132399767637253)
     | > stopnet_loss: 0.007237561978399754  (0.008711392680803934)
     | > loss: 0.1966962069272995  (0.19678943355878195)
     | > align_error: 0.5932051837444305  (0.6474437713623047)

   --> STEP: 7
     | > decoder_loss: 0.45477327704429626  (0.44131519539015635)
     | > postnet_loss: 0.3130357563495636  (0.313210802418845)
     | > stopnet_loss: 0.006243878975510597  (0.008358890722904886)
     | > loss: 0.198196142911911  (0.1969903920378004)
     | > align_error: 0.5782183706760406  (0.6375544284071241)

   --> STEP: 8
     | > decoder_loss: 0.4469083249568939  (0.44201433658599854)
     | > postnet_loss: 0.3122785687446594  (0.31309427320957184)
     | > stopnet_loss: 0.007078976836055517  (0.008198901487048715)
     | > loss: 0.1968756914138794  (0.19697605445981026)
     | > align_error: 0.5730451941490173  (0.6294907741248608)

   --> STEP: 9
     | > decoder_loss: 0.44582459330558777  (0.44243769844373065)
     | > postnet_loss: 0.31304290890693665  (0.3130885660648346)
     | > stopnet_loss: 0.006555196829140186  (0.00801626763616999)
     | > loss: 0.196272075176239  (0.19689783453941345)
     | > align_error: 0.5904722213745117  (0.625155379374822)

   --> STEP: 10
     | > decoder_loss: 0.47291430830955505  (0.4454853594303131)
     | > postnet_loss: 0.3279300630092621  (0.31457271575927737)
     | > stopnet_loss: 0.005557572934776545  (0.007770398166030645)
     | > loss: 0.2057686597108841  (0.1977849170565605)
     | > align_error: 0.5828891396522522  (0.620928755402565)

   --> STEP: 11
     | > decoder_loss: 0.45852404832839966  (0.44667069478468463)
     | > postnet_loss: 0.31738629937171936  (0.31482849608768115)
     | > stopnet_loss: 0.005890334956347942  (0.007599483328786763)
     | > loss: 0.19986793398857117  (0.19797428223219785)
     | > align_error: 0.5939380824565887  (0.6184750578620217)

   --> STEP: 12
     | > decoder_loss: 0.455919474363327  (0.44744142641623813)
     | > postnet_loss: 0.31175464391708374  (0.3145723417401314)
     | > stopnet_loss: 0.007837335579097271  (0.007619304349645972)
     | > loss: 0.19975586235523224  (0.19812274724245071)
     | > align_error: 0.5865268707275391  (0.6158127089341482)

   --> STEP: 13
     | > decoder_loss: 0.4441269636154175  (0.44718646773925197)
     | > postnet_loss: 0.31086599826812744  (0.3142872383961311)
     | > stopnet_loss: 0.005363308824598789  (0.00744576623233465)
     | > loss: 0.19411155581474304  (0.19781419405570397)
     | > align_error: 0.5844188630580902  (0.6133977977129129)

   --> STEP: 14
     | > decoder_loss: 0.4555911123752594  (0.44778679949896677)
     | > postnet_loss: 0.3146441578865051  (0.3143127326454435)
     | > stopnet_loss: 0.004923372529447079  (0.007265595253556967)
     | > loss: 0.19748219847679138  (0.19779048008578165)
     | > align_error: 0.5541194677352905  (0.6091636312859399)

   --> STEP: 15
     | > decoder_loss: 0.45232734084129333  (0.44808950225512184)
     | > postnet_loss: 0.31330806016921997  (0.31424575448036196)
     | > stopnet_loss: 0.005039246287196875  (0.007117171989132961)
     | > loss: 0.19644808769226074  (0.1977009872595469)
     | > align_error: 0.5878430604934692  (0.6077422598997752)

   --> STEP: 16
     | > decoder_loss: 0.45273908972740173  (0.44838010147213936)
     | > postnet_loss: 0.30723515152931213  (0.3138075917959213)
     | > stopnet_loss: 0.005267816595733166  (0.0070015872770454735)
     | > loss: 0.1952613741159439  (0.19754851143807173)
     | > align_error: 0.6051658391952515  (0.6075812336057425)

   --> STEP: 17
     | > decoder_loss: 0.4601828157901764  (0.4490743787849651)
     | > postnet_loss: 0.3163049519062042  (0.3139544953318203)
     | > stopnet_loss: 0.004798696842044592  (0.006872005486751304)
     | > loss: 0.19892063736915588  (0.1976292247281355)
     | > align_error: 0.5579893589019775  (0.604664064505521)

   --> STEP: 18
     | > decoder_loss: 0.4528443217277527  (0.44928382005956435)
     | > postnet_loss: 0.30746951699256897  (0.31359421875741744)
     | > stopnet_loss: 0.005241840146481991  (0.006781440745625231)
     | > loss: 0.19532030820846558  (0.19750095158815384)
     | > align_error: 0.6033686399459839  (0.6045920964744356)

   --> STEP: 19
     | > decoder_loss: 0.45047542452812195  (0.4493465360842253)
     | > postnet_loss: 0.3072492182254791  (0.31326027136099965)
     | > stopnet_loss: 0.004729984328150749  (0.0066734693552318375)
     | > loss: 0.19416114687919617  (0.19732517239294553)
     | > align_error: 0.5982944965362549  (0.6042606438461103)

   --> STEP: 20
     | > decoder_loss: 0.4473545551300049  (0.4492469370365143)
     | > postnet_loss: 0.303587943315506  (0.312776654958725)
     | > stopnet_loss: 0.004512320272624493  (0.00656541190110147)
     | > loss: 0.19224794209003448  (0.1970713108778)
     | > align_error: 0.6223319172859192  (0.6051642075181007)

   --> STEP: 21
     | > decoder_loss: 0.4462449252605438  (0.4491039840948014)
     | > postnet_loss: 0.3035906255245209  (0.31233922498566763)
     | > stopnet_loss: 0.003966240212321281  (0.006441641820683366)
     | > loss: 0.1914251297712326  (0.1968024451108206)
     | > align_error: 0.5591402053833008  (0.6029725883688245)

   --> STEP: 22
     | > decoder_loss: 0.44590309262275696  (0.4489584890278903)
     | > postnet_loss: 0.30502820014953613  (0.3120069056749344)
     | > stopnet_loss: 0.004546874202787876  (0.006355516019869934)
     | > loss: 0.19227969646453857  (0.19659686562689868)
     | > align_error: 0.6245088279247284  (0.6039515083486383)

   --> STEP: 23
     | > decoder_loss: 0.4209156036376953  (0.44773923314136005)
     | > postnet_loss: 0.2937091588973999  (0.3112113514672155)
     | > stopnet_loss: 0.004456027410924435  (0.006272929558611434)
     | > loss: 0.1831122189760208  (0.1960105766420779)
     | > align_error: 0.5663824677467346  (0.6023180718007294)

   --> STEP: 24
     | > decoder_loss: 0.4545097351074219  (0.448021337389946)
     | > postnet_loss: 0.30891409516334534  (0.31111563245455426)
     | > stopnet_loss: 0.004413614049553871  (0.006195458079067369)
     | > loss: 0.19526956975460052  (0.19597970135509968)
     | > align_error: 0.5789781808853149  (0.6013455763459205)

   --> STEP: 25
     | > decoder_loss: 0.4533328711986542  (0.4482337987422943)
     | > postnet_loss: 0.30624550580978394  (0.3109208273887634)
     | > stopnet_loss: 0.0036792713217437267  (0.006094810608774423)
     | > loss: 0.19357386231422424  (0.19588346779346466)
     | > align_error: 0.556678295135498  (0.5995588850975035)

   --> STEP: 26
     | > decoder_loss: 0.43001747131347656  (0.44753317076426286)
     | > postnet_loss: 0.2953318655490875  (0.3103212519333913)
     | > stopnet_loss: 0.004301557783037424  (0.006025839346246078)
     | > loss: 0.185638889670372  (0.1954894455579611)
     | > align_error: 0.5461325943470001  (0.5975040277609457)

   --> STEP: 27
     | > decoder_loss: 0.4264305531978607  (0.4467515923358776)
     | > postnet_loss: 0.29044637084007263  (0.3095851452262313)
     | > stopnet_loss: 0.003905873978510499  (0.005947322110404019)
     | > loss: 0.1831251084804535  (0.19503150714768303)
     | > align_error: 0.5402753949165344  (0.5953844487667083)

   --> STEP: 28
     | > decoder_loss: 0.43213939666748047  (0.4462297282048634)
     | > postnet_loss: 0.2949953079223633  (0.30906407960823606)
     | > stopnet_loss: 0.003931210841983557  (0.00587531813653186)
     | > loss: 0.18571488559246063  (0.19469877066356794)
     | > align_error: 0.5658387243747711  (0.594329244324139)

   --> STEP: 29
     | > decoder_loss: 0.4278682768344879  (0.4455965747093332)
     | > postnet_loss: 0.2919134497642517  (0.30847267857913313)
     | > stopnet_loss: 0.003546349471434951  (0.0057950088722181735)
     | > loss: 0.1834917813539505  (0.19431232275633975)
     | > align_error: 0.5396885871887207  (0.5924450837332625)

   --> STEP: 30
     | > decoder_loss: 0.42832231521606445  (0.4450207660595576)
     | > postnet_loss: 0.2926604151725769  (0.30794560313224795)
     | > stopnet_loss: 0.0028267623856663704  (0.0056960673226664465)
     | > loss: 0.18307244777679443  (0.19393766025702158)
     | > align_error: 0.5329610407352448  (0.5904622822999953)

   --> STEP: 31
     | > decoder_loss: 0.4236178696155548  (0.4443303500452349)
     | > postnet_loss: 0.2906307578086853  (0.30738705973471364)
     | > stopnet_loss: 0.0036724861711263657  (0.005630790511326444)
     | > loss: 0.18223464488983154  (0.19356014363227353)
     | > align_error: 0.5544478297233582  (0.589300525765265)

   --> STEP: 32
     | > decoder_loss: 0.4356345236301422  (0.4440586054697633)
     | > postnet_loss: 0.29664596915245056  (0.3070514006540179)
     | > stopnet_loss: 0.0038250735960900784  (0.005574361857725307)
     | > loss: 0.1868951916694641  (0.19335186388343573)
     | > align_error: 0.5302690267562866  (0.5874557914212345)

   --> STEP: 33
     | > decoder_loss: 0.4317196309566498  (0.4436846971511841)
     | > postnet_loss: 0.29402294754981995  (0.3066565990447998)
     | > stopnet_loss: 0.003998946864157915  (0.005526622009435387)
     | > loss: 0.18543459475040436  (0.19311194663698023)
     | > align_error: 0.545364648103714  (0.5861803022297944)

   --> STEP: 34
     | > decoder_loss: 0.4380318820476532  (0.44351843788343315)
     | > postnet_loss: 0.29604431986808777  (0.3063444731866612)
     | > stopnet_loss: 0.003268716624006629  (0.005460213027511011)
     | > loss: 0.18678776919841766  (0.19292594141819897)
     | > align_error: 0.5629376471042633  (0.5854966947261024)

   --> STEP: 35
     | > decoder_loss: 0.4358995854854584  (0.4433007563863482)
     | > postnet_loss: 0.2954433858394623  (0.3060330135481698)
     | > stopnet_loss: 0.003476781537756324  (0.005403543556375163)
     | > loss: 0.18631252646446228  (0.19273698670523506)
     | > align_error: 0.5322223007678986  (0.5839745691844396)

   --> STEP: 36
     | > decoder_loss: 0.44163060188293457  (0.4432543632056978)
     | > postnet_loss: 0.2994101941585541  (0.3058490463429027)
     | > stopnet_loss: 0.003639817237854004  (0.005354551158638464)
     | > loss: 0.18890002369880676  (0.19263040439950097)
     | > align_error: 0.6332096457481384  (0.5853422102000978)

   --> STEP: 37
     | > decoder_loss: 0.43451154232025146  (0.4430180707493344)
     | > postnet_loss: 0.29618769884109497  (0.30558792884285385)
     | > stopnet_loss: 0.003538492601364851  (0.005305468494928366)
     | > loss: 0.18621329963207245  (0.1924569691355164)
     | > align_error: 0.5181066393852234  (0.5835250326105066)

   --> STEP: 38
     | > decoder_loss: 0.4212956428527832  (0.4424464279099515)
     | > postnet_loss: 0.2886113226413727  (0.30514117604807806)
     | > stopnet_loss: 0.0031408851500600576  (0.005248505775326569)
     | > loss: 0.18061761558055878  (0.19214540719985962)
     | > align_error: 0.5509448051452637  (0.5826676582035265)

   --> STEP: 39
     | > decoder_loss: 0.4369818866252899  (0.44230631146675503)
     | > postnet_loss: 0.2990623116493225  (0.30498530773016125)
     | > stopnet_loss: 0.0034438958391547203  (0.005202233725681136)
     | > loss: 0.1874549388885498  (0.19202513878162092)
     | > align_error: 0.5451890230178833  (0.5817066675577408)

   --> STEP: 40
     | > decoder_loss: 0.4345947206020355  (0.442113521695137)
     | > postnet_loss: 0.2978282570838928  (0.3048063814640045)
     | > stopnet_loss: 0.0030219771433621645  (0.0051477273111231615)
     | > loss: 0.186127707362175  (0.19187770299613477)
     | > align_error: 0.5830411911010742  (0.5817400306463242)

   --> STEP: 41
     | > decoder_loss: 0.4257759153842926  (0.4417150434924335)
     | > postnet_loss: 0.2907409369945526  (0.3044633218427984)
     | > stopnet_loss: 0.0037181403022259474  (0.0051128593352964)
     | > loss: 0.18284735083580017  (0.1916574505044193)
     | > align_error: 0.5021705627441406  (0.5797993119170026)

   --> STEP: 42
     | > decoder_loss: 0.4296751916408539  (0.44142838035311016)
     | > postnet_loss: 0.29205140471458435  (0.30416780000641236)
     | > stopnet_loss: 0.003259290475398302  (0.005068726743394064)
     | > loss: 0.18369093537330627  (0.19146777157272613)
     | > align_error: 0.5787672996520996  (0.5797747401964097)

   --> STEP: 43
     | > decoder_loss: 0.42933017015457153  (0.4411470266275628)
     | > postnet_loss: 0.2910979688167572  (0.30386385044386227)
     | > stopnet_loss: 0.0029398815240710974  (0.005019218715037716)
     | > loss: 0.18304690718650818  (0.19127193751723268)
     | > align_error: 0.5510295033454895  (0.5791062463161558)

   --> STEP: 44
     | > decoder_loss: 0.4471646547317505  (0.44128379090265796)
     | > postnet_loss: 0.3020589053630829  (0.30382282896475366)
     | > stopnet_loss: 0.002631646115332842  (0.00496495570140806)
     | > loss: 0.1899375468492508  (0.1912416104565967)
     | > align_error: 0.5503452122211456  (0.5784525864503601)

   --> STEP: 45
     | > decoder_loss: 0.4402633607387543  (0.4412611146767934)
     | > postnet_loss: 0.30130735039711  (0.30376692944102823)
     | > stopnet_loss: 0.0032603349536657333  (0.004927075240347119)
     | > loss: 0.18865300714969635  (0.1911840859386656)
     | > align_error: 0.5518087446689606  (0.5778605010774401)

   --> STEP: 46
     | > decoder_loss: 0.4307354688644409  (0.44103229628956836)
     | > postnet_loss: 0.29230424761772156  (0.30351774070573895)
     | > stopnet_loss: 0.003175727091729641  (0.0048890024545076086)
     | > loss: 0.18393565714359283  (0.19102651139964227)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.37280679832805275 (+0.01742238348180586)
     | > avg_decoder_loss: 0.4373858254967314 (-0.0006654063860575543)
     | > avg_postnet_loss: 0.3003201322122054 (-0.0015304951053676241)
     | > avg_stopnet_loss: 0.004336328129284082 (+1.0267284585893481e-05)
     | > avg_loss: 0.18876281809626203 (-0.0005387085856813079)
     | > avg_align_error: 0.5707427954131907 (+0.00026790797710429803)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_22348.pth

 > EPOCH: 148/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 18:57:10)

   --> TIME: 2025-12-28 18:57:13 -- STEP: 2/150 -- GLOBAL_STEP: 22350
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45326220989227295  (0.4575292468070984)
     | > postnet_loss: 0.38885918259620667  (0.392625167965889)
     | > stopnet_loss: 0.014599443413317204  (0.014671626966446638)
     | > loss: 0.22512978315353394  (0.22721022367477417)
     | > align_error: 0.7301828265190125  (0.7221962660551071)
     | > grad_norm: tensor(0.2317, device='cuda:0')  (tensor(0.2903, device='cuda:0'))
     | > step_time: 0.3988  (0.41683101654052734)
     | > loader_time: 0.793  (0.7583317756652832)


   --> TIME: 2025-12-28 18:57:53 -- STEP: 27/150 -- GLOBAL_STEP: 22375
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.47551289200782776  (0.4665043663095545)
     | > postnet_loss: 0.3960486352443695  (0.39376174962079086)
     | > stopnet_loss: 0.0061392695643007755  (0.009397668005139744)
     | > loss: 0.22402964532375336  (0.22446419684975236)
     | > align_error: 0.6575358510017395  (0.6679231215406349)
     | > grad_norm: tensor(0.1614, device='cuda:0')  (tensor(0.2640, device='cuda:0'))
     | > step_time: 0.8806  (0.672174886420921)
     | > loader_time: 0.8909  (0.8805849198941831)


   --> TIME: 2025-12-28 18:58:48 -- STEP: 52/150 -- GLOBAL_STEP: 22400
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4799272119998932  (0.4730262647454555)
     | > postnet_loss: 0.3957252502441406  (0.39568444112172496)
     | > stopnet_loss: 0.004224689677357674  (0.00738502303675677)
     | > loss: 0.22313779592514038  (0.2245626994050466)
     | > align_error: 0.6582651138305664  (0.6467526503480399)
     | > grad_norm: tensor(0.1476, device='cuda:0')  (tensor(0.2200, device='cuda:0'))
     | > step_time: 1.4099  (0.9065553408402663)
     | > loader_time: 1.1638  (0.9604703050393325)


   --> TIME: 2025-12-28 18:59:55 -- STEP: 77/150 -- GLOBAL_STEP: 22425
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4841521680355072  (0.4760661113571811)
     | > postnet_loss: 0.395111620426178  (0.3955643707281583)
     | > stopnet_loss: 0.004680214449763298  (0.006313214051331601)
     | > loss: 0.22449615597724915  (0.22422083593034126)
     | > align_error: 0.6099804639816284  (0.6347546345227725)
     | > grad_norm: tensor(0.1939, device='cuda:0')  (tensor(0.2082, device='cuda:0'))
     | > step_time: 1.5481  (1.0707177961027465)
     | > loader_time: 1.4738  (1.0585114863011749)


   --> TIME: 2025-12-28 19:01:16 -- STEP: 102/150 -- GLOBAL_STEP: 22450
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4842038154602051  (0.47721610262113456)
     | > postnet_loss: 0.3939720094203949  (0.3948368456433801)
     | > stopnet_loss: 0.003442893736064434  (0.005670070778304603)
     | > loss: 0.2229868620634079  (0.22368330888304055)
     | > align_error: 0.6042870879173279  (0.6297667315777608)
     | > grad_norm: tensor(0.1843, device='cuda:0')  (tensor(0.1989, device='cuda:0'))
     | > step_time: 1.8605  (1.2245739160799516)
     | > loader_time: 1.5467  (1.1823374056348614)


   --> TIME: 2025-12-28 19:02:49 -- STEP: 127/150 -- GLOBAL_STEP: 22475
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4874500632286072  (0.4783649338981298)
     | > postnet_loss: 0.3952960968017578  (0.3944418517154033)
     | > stopnet_loss: 0.0030700345523655415  (0.005199293657315999)
     | > loss: 0.2237565815448761  (0.22340099067669214)
     | > align_error: 0.5965889096260071  (0.6257532649622186)
     | > grad_norm: tensor(0.1526, device='cuda:0')  (tensor(0.2025, device='cuda:0'))
     | > step_time: 2.0409  (1.3483674713945768)
     | > loader_time: 1.6275  (1.3140065163139283)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.459882527589798  (0.459882527589798)
     | > postnet_loss: 0.3351719379425049  (0.3351719379425049)
     | > stopnet_loss: 0.01214233972132206  (0.01214233972132206)
     | > loss: 0.21090595424175262  (0.21090595424175262)
     | > align_error: 0.7191952466964722  (0.7191952466964722)

   --> STEP: 1
     | > decoder_loss: 0.43953728675842285  (0.43953728675842285)
     | > postnet_loss: 0.322367787361145  (0.322367787361145)
     | > stopnet_loss: 0.009695151820778847  (0.009695151820778847)
     | > loss: 0.20017142593860626  (0.20017142593860626)
     | > align_error: 0.660007894039154  (0.660007894039154)

   --> STEP: 2
     | > decoder_loss: 0.4373028576374054  (0.4384200721979141)
     | > postnet_loss: 0.31360042095184326  (0.31798410415649414)
     | > stopnet_loss: 0.01102279033511877  (0.010358971077948809)
     | > loss: 0.1987486034631729  (0.1994600147008896)
     | > align_error: 0.6556851267814636  (0.6578465104103088)

   --> STEP: 3
     | > decoder_loss: 0.4401848018169403  (0.43900831540425617)
     | > postnet_loss: 0.31322380900382996  (0.3163973391056061)
     | > stopnet_loss: 0.008161722682416439  (0.009626554946104685)
     | > loss: 0.19651387631893158  (0.19847796857357025)
     | > align_error: 0.7356077432632446  (0.6837669213612875)

   --> STEP: 4
     | > decoder_loss: 0.44394588470458984  (0.4402427077293396)
     | > postnet_loss: 0.3198755085468292  (0.31726688146591187)
     | > stopnet_loss: 0.00812813825905323  (0.009251950774341822)
     | > loss: 0.19908347725868225  (0.19862934574484825)
     | > align_error: 0.6039867103099823  (0.6638218685984612)

   --> STEP: 5
     | > decoder_loss: 0.42723241448402405  (0.4376406490802765)
     | > postnet_loss: 0.30328574776649475  (0.3144706547260284)
     | > stopnet_loss: 0.007994884625077248  (0.009000537544488907)
     | > loss: 0.1906244307756424  (0.19702836275100707)
     | > align_error: 0.6420311331748962  (0.6594637215137482)

   --> STEP: 6
     | > decoder_loss: 0.4429697096347809  (0.43852882583936054)
     | > postnet_loss: 0.3144306540489197  (0.3144639879465103)
     | > stopnet_loss: 0.007204107008874416  (0.008701132455219826)
     | > loss: 0.19655419886112213  (0.19694933543602625)
     | > align_error: 0.5943504869937897  (0.6486115157604218)

   --> STEP: 7
     | > decoder_loss: 0.454372376203537  (0.44079219017710003)
     | > postnet_loss: 0.3139495849609375  (0.3143905018057142)
     | > stopnet_loss: 0.006170372944325209  (0.00833959538223488)
     | > loss: 0.198250874876976  (0.19713526964187622)
     | > align_error: 0.5795363485813141  (0.638743634734835)

   --> STEP: 8
     | > decoder_loss: 0.4465208649635315  (0.441508274525404)
     | > postnet_loss: 0.31388136744499207  (0.31432686001062393)
     | > stopnet_loss: 0.007112553343176842  (0.008186215127352625)
     | > loss: 0.1972130984067917  (0.19714499823749065)
     | > align_error: 0.5742447972297668  (0.6306812800467014)

   --> STEP: 9
     | > decoder_loss: 0.4448644518852234  (0.4418811831209395)
     | > postnet_loss: 0.31345975399017334  (0.3142305148972405)
     | > stopnet_loss: 0.006744470912963152  (0.008026021325753795)
     | > loss: 0.19632552564144135  (0.1970539457268185)
     | > align_error: 0.5918050408363342  (0.6263616979122162)

   --> STEP: 10
     | > decoder_loss: 0.4696789085865021  (0.44466095566749575)
     | > postnet_loss: 0.327792227268219  (0.3155866861343384)
     | > stopnet_loss: 0.005672212224453688  (0.007790640415623784)
     | > loss: 0.20504000782966614  (0.19785255193710327)
     | > align_error: 0.5835345089435577  (0.6220789790153504)

   --> STEP: 11
     | > decoder_loss: 0.45820191502571106  (0.445891951972788)
     | > postnet_loss: 0.31795573234558105  (0.31580205397172406)
     | > stopnet_loss: 0.005847201682627201  (0.007613964167169549)
     | > loss: 0.19988660514354706  (0.1980374658649618)
     | > align_error: 0.5958586931228638  (0.6196953166614879)

   --> STEP: 12
     | > decoder_loss: 0.45535051822662354  (0.4466801658272743)
     | > postnet_loss: 0.3124072551727295  (0.31551915407180786)
     | > stopnet_loss: 0.007912402041256428  (0.007638833990010123)
     | > loss: 0.1998518407344818  (0.19818866377075514)
     | > align_error: 0.588484138250351  (0.6170943851272265)

   --> STEP: 13
     | > decoder_loss: 0.4437984824180603  (0.4464584978727194)
     | > postnet_loss: 0.31176382303237915  (0.31523028245339024)
     | > stopnet_loss: 0.005268432665616274  (0.007456495426595211)
     | > loss: 0.19415901601314545  (0.19787869086632362)
     | > align_error: 0.5853720903396606  (0.6146542086051061)

   --> STEP: 14
     | > decoder_loss: 0.45434263348579407  (0.44702165041651043)
     | > postnet_loss: 0.31480172276496887  (0.31519967104707447)
     | > stopnet_loss: 0.004889726638793945  (0.007273154798895121)
     | > loss: 0.19717581570148468  (0.19782848549740656)
     | > align_error: 0.5556356012821198  (0.6104385937963214)

   --> STEP: 15
     | > decoder_loss: 0.4540335536003113  (0.44748911062876384)
     | > postnet_loss: 0.31492817401885986  (0.31518157124519347)
     | > stopnet_loss: 0.004974717274308205  (0.0071199256305893265)
     | > loss: 0.19721515476703644  (0.19778759678204855)
     | > align_error: 0.5894866585731506  (0.6090417981147767)

   --> STEP: 16
     | > decoder_loss: 0.4550294876098633  (0.44796038419008255)
     | > postnet_loss: 0.3091825842857361  (0.3148066345602274)
     | > stopnet_loss: 0.005254348739981651  (0.0070033270749263465)
     | > loss: 0.19630736112594604  (0.19769508205354214)
     | > align_error: 0.6068849861621857  (0.6089069973677397)

   --> STEP: 17
     | > decoder_loss: 0.4600743055343628  (0.44867296779856963)
     | > postnet_loss: 0.31647443771362305  (0.3149047406280742)
     | > stopnet_loss: 0.00479308795183897  (0.006873313008862383)
     | > loss: 0.1989302784204483  (0.19776774066336014)
     | > align_error: 0.5595546662807465  (0.6060039190685048)

   --> STEP: 18
     | > decoder_loss: 0.45421966910362244  (0.44898111787107253)
     | > postnet_loss: 0.30915334820747375  (0.31458521882692975)
     | > stopnet_loss: 0.005192374810576439  (0.006779927553402053)
     | > loss: 0.19603562355041504  (0.1976715119348632)
     | > align_error: 0.6047537326812744  (0.6059344642692142)

   --> STEP: 19
     | > decoder_loss: 0.4513823091983795  (0.44910749636198344)
     | > postnet_loss: 0.3084695339202881  (0.31426334067394857)
     | > stopnet_loss: 0.004723495803773403  (0.0066716943034215975)
     | > loss: 0.19468644261360168  (0.19751440302321785)
     | > align_error: 0.6001653969287872  (0.6056308291460338)

   --> STEP: 20
     | > decoder_loss: 0.44935697317123413  (0.449119970202446)
     | > postnet_loss: 0.3055414855480194  (0.31382724791765215)
     | > stopnet_loss: 0.004513629712164402  (0.006563791073858738)
     | > loss: 0.1932382434606552  (0.19730059504508973)
     | > align_error: 0.6234390139579773  (0.606521238386631)

   --> STEP: 21
     | > decoder_loss: 0.4464559853076935  (0.44899311377888634)
     | > postnet_loss: 0.3049747943878174  (0.31340570251146954)
     | > stopnet_loss: 0.003947768826037645  (0.0064392185858672575)
     | > loss: 0.19180545210838318  (0.19703892157191322)
     | > align_error: 0.5605853796005249  (0.6043338165396736)

   --> STEP: 22
     | > decoder_loss: 0.44685983657836914  (0.44889614663340827)
     | > postnet_loss: 0.30663639307022095  (0.3130980066277764)
     | > stopnet_loss: 0.004509203601628542  (0.006351490632038225)
     | > loss: 0.19288326799869537  (0.19685002822767605)
     | > align_error: 0.6254918575286865  (0.6052955456755378)

   --> STEP: 23
     | > decoder_loss: 0.42227378487586975  (0.4477386526439501)
     | > postnet_loss: 0.2953290343284607  (0.3123254426147627)
     | > stopnet_loss: 0.004423799924552441  (0.006267677992582321)
     | > loss: 0.18382450938224792  (0.1962837013213531)
     | > align_error: 0.5682108402252197  (0.6036831671776979)

   --> STEP: 24
     | > decoder_loss: 0.4566502869129181  (0.4481099707384904)
     | > postnet_loss: 0.31114307045936584  (0.3122761771082878)
     | > stopnet_loss: 0.004380495753139257  (0.006189045399272193)
     | > loss: 0.19632883369922638  (0.1962855818370978)
     | > align_error: 0.5803988575935364  (0.6027129876116911)

   --> STEP: 25
     | > decoder_loss: 0.45460501313209534  (0.4483697724342346)
     | > postnet_loss: 0.30791226029396057  (0.3121016204357147)
     | > stopnet_loss: 0.0036439120303839445  (0.0060872400645166636)
     | > loss: 0.1942732334136963  (0.19620508790016175)
     | > align_error: 0.5581426024436951  (0.6009301722049714)

   --> STEP: 26
     | > decoder_loss: 0.4308348596096039  (0.4476953527102104)
     | > postnet_loss: 0.2973612844944  (0.31153468443797183)
     | > stopnet_loss: 0.004335816949605942  (0.006019877637020097)
     | > loss: 0.18638485670089722  (0.19582738670019004)
     | > align_error: 0.5477438271045685  (0.5988845435472636)

   --> STEP: 27
     | > decoder_loss: 0.4261932373046875  (0.4468989780655614)
     | > postnet_loss: 0.29118335247039795  (0.31078093140213575)
     | > stopnet_loss: 0.003588666208088398  (0.005929832769281886)
     | > loss: 0.1829328089952469  (0.1953498097481551)
     | > align_error: 0.5410037040710449  (0.5967408087518481)

   --> STEP: 28
     | > decoder_loss: 0.43268516659736633  (0.4463913419416973)
     | > postnet_loss: 0.29643189907073975  (0.3102684659617288)
     | > stopnet_loss: 0.0039045042358338833  (0.005857499607373029)
     | > loss: 0.18618376553058624  (0.19502245102609908)
     | > align_error: 0.5674280524253845  (0.5956939245973316)

   --> STEP: 29
     | > decoder_loss: 0.42923229932785034  (0.44579965081708184)
     | > postnet_loss: 0.29380103945732117  (0.30970062366847334)
     | > stopnet_loss: 0.0035552142653614283  (0.005778110457648491)
     | > loss: 0.18431353569030762  (0.19465317808348556)
     | > align_error: 0.5411744713783264  (0.5938139434518487)

   --> STEP: 30
     | > decoder_loss: 0.4282473921775818  (0.4452145755290985)
     | > postnet_loss: 0.29398202896118164  (0.3091766705115636)
     | > stopnet_loss: 0.0027580680325627327  (0.005677442376812299)
     | > loss: 0.1833154261112213  (0.19427525301774343)
     | > align_error: 0.5338965356349945  (0.5918166965246202)

   --> STEP: 31
     | > decoder_loss: 0.4245551526546478  (0.4445481425331485)
     | > postnet_loss: 0.2922210693359375  (0.3086297156349305)
     | > stopnet_loss: 0.00364092574454844  (0.005611748291900562)
     | > loss: 0.18283498287200928  (0.1939062120453004)
     | > align_error: 0.5554629564285278  (0.5906439952311978)

   --> STEP: 32
     | > decoder_loss: 0.436502605676651  (0.44429671950638294)
     | > postnet_loss: 0.298083633184433  (0.30830015055835247)
     | > stopnet_loss: 0.003804375184699893  (0.005555267882300541)
     | > loss: 0.18745093047618866  (0.19370448449626565)
     | > align_error: 0.5321325361728668  (0.588815512135625)

   --> STEP: 33
     | > decoder_loss: 0.433650940656662  (0.4439741201473005)
     | > postnet_loss: 0.296064555644989  (0.30792937495491723)
     | > stopnet_loss: 0.003979520406574011  (0.005507517958793676)
     | > loss: 0.1864083856344223  (0.1934833905913613)
     | > align_error: 0.547037273645401  (0.5875495049086485)

   --> STEP: 34
     | > decoder_loss: 0.4401654899120331  (0.4438621016109691)
     | > postnet_loss: 0.2979394793510437  (0.30763555449597974)
     | > stopnet_loss: 0.0032520145177841187  (0.005441179622293395)
     | > loss: 0.18777824938297272  (0.19331559232052634)
     | > align_error: 0.5645504593849182  (0.5868730623932447)

   --> STEP: 35
     | > decoder_loss: 0.4370378851890564  (0.44366712399891445)
     | > postnet_loss: 0.2970941364765167  (0.3073343711239951)
     | > stopnet_loss: 0.0034810970537364483  (0.005385177263191768)
     | > loss: 0.18701410293579102  (0.19313554976667677)
     | > align_error: 0.5338990688323975  (0.5853595197200776)

   --> STEP: 36
     | > decoder_loss: 0.44324663281440735  (0.4436554436882337)
     | > postnet_loss: 0.3014167547225952  (0.30716999289062286)
     | > stopnet_loss: 0.0036089851055294275  (0.005335838592145592)
     | > loss: 0.18977482616901398  (0.19304219633340836)
     | > align_error: 0.6343858242034912  (0.5867213615112835)

   --> STEP: 37
     | > decoder_loss: 0.43455010652542114  (0.44340935349464417)
     | > postnet_loss: 0.2977309226989746  (0.3069148828854432)
     | > stopnet_loss: 0.0035262543242424726  (0.005286930909229291)
     | > loss: 0.18659651279449463  (0.19286798867019447)
     | > align_error: 0.5195183157920837  (0.5849050629783322)

   --> STEP: 38
     | > decoder_loss: 0.42186659574508667  (0.44284243881702423)
     | > postnet_loss: 0.2900744676589966  (0.3064717140636946)
     | > stopnet_loss: 0.003103547962382436  (0.005229473463259637)
     | > loss: 0.18108882009983063  (0.19255801054992175)
     | > align_error: 0.5526919066905975  (0.5840573483391813)

   --> STEP: 39
     | > decoder_loss: 0.4379861056804657  (0.44271791745454836)
     | > postnet_loss: 0.3011114001274109  (0.3063342701166104)
     | > stopnet_loss: 0.003445159876719117  (0.0051837218328355215)
     | > loss: 0.18821953237056732  (0.19244676751968187)
     | > align_error: 0.5466757416725159  (0.5830988456041386)

   --> STEP: 40
     | > decoder_loss: 0.435000479221344  (0.4425249814987183)
     | > postnet_loss: 0.29945504665374756  (0.3061622895300388)
     | > stopnet_loss: 0.00298512470908463  (0.005128756904741749)
     | > loss: 0.186599001288414  (0.1923005733639002)
     | > align_error: 0.5843855142593384  (0.5831310123205186)

   --> STEP: 41
     | > decoder_loss: 0.42561647295951843  (0.4421125788514207)
     | > postnet_loss: 0.29181039333343506  (0.30581224328134116)
     | > stopnet_loss: 0.003701911075040698  (0.0050939557869441624)
     | > loss: 0.18305863440036774  (0.19207516021844817)
     | > align_error: 0.5036184191703796  (0.5811916807802713)

   --> STEP: 42
     | > decoder_loss: 0.43006381392478943  (0.44182570349602474)
     | > postnet_loss: 0.2932063341140747  (0.30551210258688244)
     | > stopnet_loss: 0.003248828463256359  (0.0050500241839992145)
     | > loss: 0.18406637012958527  (0.19188447474014192)
     | > align_error: 0.5803012251853943  (0.5811704794565837)

   --> STEP: 43
     | > decoder_loss: 0.4299478530883789  (0.44154947441677717)
     | > postnet_loss: 0.2926520109176636  (0.3052130306875983)
     | > stopnet_loss: 0.0029025168623775244  (0.005000082153263826)
     | > loss: 0.18355248868465424  (0.19169070762257243)
     | > align_error: 0.5523122549057007  (0.5804993579554004)

   --> STEP: 44
     | > decoder_loss: 0.44746190309524536  (0.44168384779583325)
     | > postnet_loss: 0.30345913767814636  (0.305173169482838)
     | > stopnet_loss: 0.0026282009202986956  (0.004946175761605528)
     | > loss: 0.1903584599494934  (0.1916604292663661)
     | > align_error: 0.552240639925003  (0.5798571143638005)

   --> STEP: 45
     | > decoder_loss: 0.44157305359840393  (0.44168138570255705)
     | > postnet_loss: 0.3031398057937622  (0.3051279836230808)
     | > stopnet_loss: 0.0032342304475605488  (0.004908132532404528)
     | > loss: 0.1894124448299408  (0.19161047405666776)
     | > align_error: 0.5532186031341553  (0.5792651474475862)

   --> STEP: 46
     | > decoder_loss: 0.4316301941871643  (0.44146288153917895)
     | > postnet_loss: 0.2942231297492981  (0.3048909215823464)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34195646733948676 (-0.030850330988565988)
     | > avg_decoder_loss: 0.43748243153095245 (+9.66060342210695e-05)
     | > avg_postnet_loss: 0.3018243529579856 (+0.001504220745780216)
     | > avg_stopnet_loss: 0.0043207131587251115 (-1.5614970558970598e-05)
     | > avg_loss: 0.18914740803566846 (+0.00038458993940643227)
     | > avg_align_error: 0.5722200057723306 (+0.0014772103591398356)


 > EPOCH: 149/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 19:06:14)

   --> TIME: 2025-12-28 19:06:16 -- STEP: 1/150 -- GLOBAL_STEP: 22500
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4626975357532501  (0.4626975357532501)
     | > postnet_loss: 0.39618945121765137  (0.39618945121765137)
     | > stopnet_loss: 0.015380454249680042  (0.015380454249680042)
     | > loss: 0.23010219633579254  (0.23010219633579254)
     | > align_error: 0.714683473110199  (0.714683473110199)
     | > grad_norm: tensor(0.3197, device='cuda:0')  (tensor(0.3197, device='cuda:0'))
     | > step_time: 0.3977  (0.3977468013763428)
     | > loader_time: 0.8698  (0.8698430061340332)


   --> TIME: 2025-12-28 19:06:55 -- STEP: 26/150 -- GLOBAL_STEP: 22525
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.4771519601345062  (0.46510859292287093)
     | > postnet_loss: 0.39914050698280334  (0.39301094527427965)
     | > stopnet_loss: 0.006602410692721605  (0.00954303123916571)
     | > loss: 0.2256755232810974  (0.2240729137108876)
     | > align_error: 0.6184561252593994  (0.6675698206974909)
     | > grad_norm: tensor(0.1817, device='cuda:0')  (tensor(0.2721, device='cuda:0'))
     | > step_time: 0.9912  (0.6617289506472074)
     | > loader_time: 0.8916  (0.8690796265235314)


   --> TIME: 2025-12-28 19:07:47 -- STEP: 51/150 -- GLOBAL_STEP: 22550
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48155638575553894  (0.4729928976180507)
     | > postnet_loss: 0.39734935760498047  (0.395772575747733)
     | > stopnet_loss: 0.0045104301534593105  (0.007459670496994959)
     | > loss: 0.2242368757724762  (0.2246510368936202)
     | > align_error: 0.6107398271560669  (0.6462426805028728)
     | > grad_norm: tensor(0.1382, device='cuda:0')  (tensor(0.2701, device='cuda:0'))
     | > step_time: 1.2161  (0.8776885154200535)
     | > loader_time: 1.2464  (0.9386554278579413)


   --> TIME: 2025-12-28 19:08:55 -- STEP: 76/150 -- GLOBAL_STEP: 22575
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48782479763031006  (0.4761939186014627)
     | > postnet_loss: 0.39819639921188354  (0.39575052104498204)
     | > stopnet_loss: 0.0037606286350637674  (0.006365396967770435)
     | > loss: 0.22526593506336212  (0.22435150511170687)
     | > align_error: 0.6027827560901642  (0.634810303386889)
     | > grad_norm: tensor(0.2062, device='cuda:0')  (tensor(0.2414, device='cuda:0'))
     | > step_time: 1.609  (1.0533447359737595)
     | > loader_time: 2.0255  (1.0528421433348403)


   --> TIME: 2025-12-28 19:10:20 -- STEP: 101/150 -- GLOBAL_STEP: 22600
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4803834557533264  (0.47739562333220303)
     | > postnet_loss: 0.39294347167015076  (0.39502900130677926)
     | > stopnet_loss: 0.0036764719989150763  (0.005704098690006107)
     | > loss: 0.22200819849967957  (0.22381025346198885)
     | > align_error: 0.6047395467758179  (0.6300075930534023)
     | > grad_norm: tensor(0.1245, device='cuda:0')  (tensor(0.2236, device='cuda:0'))
     | > step_time: 1.7192  (1.2054182586103384)
     | > loader_time: 1.4905  (1.2180429449175845)


   --> TIME: 2025-12-28 19:11:49 -- STEP: 126/150 -- GLOBAL_STEP: 22625
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48503535985946655  (0.47849035475935253)
     | > postnet_loss: 0.3932330906391144  (0.3945951296223534)
     | > stopnet_loss: 0.002879196312278509  (0.005227154224283165)
     | > loss: 0.22244632244110107  (0.2234985244179529)
     | > align_error: 0.609283983707428  (0.6262829464579386)
     | > grad_norm: tensor(0.4572, device='cuda:0')  (tensor(0.2207, device='cuda:0'))
     | > step_time: 1.9779  (1.3367887527223616)
     | > loader_time: 2.0387  (1.3096758165056743)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45851221680641174  (0.45851221680641174)
     | > postnet_loss: 0.3355957865715027  (0.3355957865715027)
     | > stopnet_loss: 0.012060959823429585  (0.012060959823429585)
     | > loss: 0.21058796346187592  (0.21058796346187592)
     | > align_error: 0.7191448509693146  (0.7191448509693146)

   --> STEP: 1
     | > decoder_loss: 0.4413844347000122  (0.4413844347000122)
     | > postnet_loss: 0.32466942071914673  (0.32466942071914673)
     | > stopnet_loss: 0.00960172712802887  (0.00960172712802887)
     | > loss: 0.2011151909828186  (0.2011151909828186)
     | > align_error: 0.6596602499485016  (0.6596602499485016)

   --> STEP: 2
     | > decoder_loss: 0.43734094500541687  (0.43936268985271454)
     | > postnet_loss: 0.31441980600357056  (0.31954461336135864)
     | > stopnet_loss: 0.011055820621550083  (0.010328773874789476)
     | > loss: 0.19899600744247437  (0.20005559921264648)
     | > align_error: 0.6561600565910339  (0.6579101532697678)

   --> STEP: 3
     | > decoder_loss: 0.4400191605091095  (0.4395815134048462)
     | > postnet_loss: 0.3138872981071472  (0.31765884160995483)
     | > stopnet_loss: 0.008117731660604477  (0.009591759803394476)
     | > loss: 0.19659435749053955  (0.19890185197194418)
     | > align_error: 0.7348819077014923  (0.6835674047470093)

   --> STEP: 4
     | > decoder_loss: 0.4437007009983063  (0.4406113103032112)
     | > postnet_loss: 0.3210645020008087  (0.3185102567076683)
     | > stopnet_loss: 0.008079036138951778  (0.009213578887283802)
     | > loss: 0.1992703378200531  (0.1989939734339714)
     | > align_error: 0.6036843359470367  (0.6635966375470161)

   --> STEP: 5
     | > decoder_loss: 0.4255605936050415  (0.43760116696357726)
     | > postnet_loss: 0.30334532260894775  (0.3154772698879242)
     | > stopnet_loss: 0.00804712250828743  (0.008980287611484528)
     | > loss: 0.19027359783649445  (0.197249898314476)
     | > align_error: 0.6422104835510254  (0.659319406747818)

   --> STEP: 6
     | > decoder_loss: 0.44341859221458435  (0.4385707378387451)
     | > postnet_loss: 0.316040575504303  (0.3155711541573207)
     | > stopnet_loss: 0.0071677896194159985  (0.00867820461280644)
     | > loss: 0.19703257083892822  (0.1972136770685514)
     | > align_error: 0.5943599939346313  (0.6484928379456202)

   --> STEP: 7
     | > decoder_loss: 0.4534744322299957  (0.4406998370374952)
     | > postnet_loss: 0.31486019492149353  (0.3154695885522025)
     | > stopnet_loss: 0.0061544980853796005  (0.00831767510888832)
     | > loss: 0.19823814928531647  (0.19736003024237497)
     | > align_error: 0.5791929364204407  (0.6385928520134517)

   --> STEP: 8
     | > decoder_loss: 0.4497780203819275  (0.44183460995554924)
     | > postnet_loss: 0.31703197956085205  (0.3156648874282837)
     | > stopnet_loss: 0.007082295138388872  (0.008163252612575889)
     | > loss: 0.19878479838371277  (0.1975381262600422)
     | > align_error: 0.5751241445541382  (0.6306592635810375)

   --> STEP: 9
     | > decoder_loss: 0.44943317770957947  (0.4426788952615526)
     | > postnet_loss: 0.3174550533294678  (0.31586379475063747)
     | > stopnet_loss: 0.006639243569225073  (0.007993918274425797)
     | > loss: 0.19836130738258362  (0.19762959082921347)
     | > align_error: 0.5913332104682922  (0.6262897021240659)

   --> STEP: 10
     | > decoder_loss: 0.4720398783683777  (0.4456149935722351)
     | > postnet_loss: 0.3304930329322815  (0.3173267185688019)
     | > stopnet_loss: 0.005555806215852499  (0.007750107068568468)
     | > loss: 0.20618903636932373  (0.1984855353832245)
     | > align_error: 0.5847887396812439  (0.6221396058797837)

   --> STEP: 11
     | > decoder_loss: 0.45848074555397034  (0.44678460738875647)
     | > postnet_loss: 0.31940802931785583  (0.3175159286368977)
     | > stopnet_loss: 0.0058911023661494255  (0.007581106641075828)
     | > loss: 0.20036329329013824  (0.19865624064748938)
     | > align_error: 0.5957545638084412  (0.6197409656914797)

   --> STEP: 12
     | > decoder_loss: 0.4549133777618408  (0.44746200491984683)
     | > postnet_loss: 0.3137468099594116  (0.31720183541377384)
     | > stopnet_loss: 0.007913428358733654  (0.007608800117547314)
     | > loss: 0.20007847249507904  (0.19877475996812186)
     | > align_error: 0.5881037712097168  (0.6171045328179995)

   --> STEP: 13
     | > decoder_loss: 0.44342052936553955  (0.44715112218490016)
     | > postnet_loss: 0.3128249943256378  (0.3168651553300711)
     | > stopnet_loss: 0.005261031910777092  (0.007428202563180373)
     | > loss: 0.194322407245636  (0.1984322712971614)
     | > align_error: 0.5855438709259033  (0.6146767895955306)

   --> STEP: 14
     | > decoder_loss: 0.4569767117500305  (0.44785295001098085)
     | > postnet_loss: 0.3174993395805359  (0.3169104542051043)
     | > stopnet_loss: 0.004878823179751635  (0.0072461040357926065)
     | > loss: 0.19849783182144165  (0.19843695419175283)
     | > align_error: 0.5551963746547699  (0.6104281885283334)

   --> STEP: 15
     | > decoder_loss: 0.4531268775463104  (0.44820454518000286)
     | > postnet_loss: 0.31520208716392517  (0.31679656306902565)
     | > stopnet_loss: 0.005025841295719147  (0.0070980865197877085)
     | > loss: 0.19710808992385864  (0.1983483632405599)
     | > align_error: 0.5893410444259644  (0.6090223789215088)

   --> STEP: 16
     | > decoder_loss: 0.4534112215042114  (0.4485299624502659)
     | > postnet_loss: 0.3093312382698059  (0.31632998026907444)
     | > stopnet_loss: 0.005241681821644306  (0.006982061226153746)
     | > loss: 0.19592729210853577  (0.1981970462948084)
     | > align_error: 0.606316089630127  (0.6088532358407974)

   --> STEP: 17
     | > decoder_loss: 0.4615580439567566  (0.4492963201859418)
     | > postnet_loss: 0.31860196590423584  (0.3164636264829075)
     | > stopnet_loss: 0.004794476553797722  (0.006853379774838686)
     | > loss: 0.19983448088169098  (0.19829336597638972)
     | > align_error: 0.5591898262500763  (0.6059318588060492)

   --> STEP: 18
     | > decoder_loss: 0.453738808631897  (0.449543125099606)
     | > postnet_loss: 0.3096003532409668  (0.31608233352502185)
     | > stopnet_loss: 0.005234101787209511  (0.0067634198866370655)
     | > loss: 0.1960688978433609  (0.19816978441344368)
     | > align_error: 0.6047489047050476  (0.6058661391337713)

   --> STEP: 19
     | > decoder_loss: 0.4497731626033783  (0.4495552323366466)
     | > postnet_loss: 0.3088097870349884  (0.31569956792028325)
     | > stopnet_loss: 0.0047041685320436954  (0.006655038236395309)
     | > loss: 0.19434989988803864  (0.197968737859475)
     | > align_error: 0.5994725227355957  (0.6055296330075515)

   --> STEP: 20
     | > decoder_loss: 0.44765371084213257  (0.44946015626192093)
     | > postnet_loss: 0.3054966926574707  (0.31518942415714263)
     | > stopnet_loss: 0.0044824169017374516  (0.006546407169662416)
     | > loss: 0.19277001917362213  (0.19770880192518234)
     | > align_error: 0.6234849691390991  (0.6064273998141289)

   --> STEP: 21
     | > decoder_loss: 0.4448547065258026  (0.4492408491316296)
     | > postnet_loss: 0.3053630292415619  (0.314721500589734)
     | > stopnet_loss: 0.003955850377678871  (0.006423047322425104)
     | > loss: 0.19151028990745544  (0.19741363468624296)
     | > align_error: 0.5603991448879242  (0.6042355781509763)

   --> STEP: 22
     | > decoder_loss: 0.44616997241973877  (0.44910126382654364)
     | > postnet_loss: 0.30719295144081116  (0.31437929381023755)
     | > stopnet_loss: 0.004514789674431086  (0.006336308338425376)
     | > loss: 0.19285550713539124  (0.19720644707029517)
     | > align_error: 0.6253359615802765  (0.6051946864886717)

   --> STEP: 23
     | > decoder_loss: 0.4215066730976105  (0.4479014990122422)
     | > postnet_loss: 0.2957814633846283  (0.31357069248738495)
     | > stopnet_loss: 0.004434775095432997  (0.006253632980034403)
     | > loss: 0.18375681340694427  (0.1966216803892799)
     | > align_error: 0.5681595206260681  (0.6035844618859498)

   --> STEP: 24
     | > decoder_loss: 0.455886572599411  (0.4482342104117076)
     | > postnet_loss: 0.31144148111343384  (0.31348197534680367)
     | > stopnet_loss: 0.004405421204864979  (0.0061766241560690105)
     | > loss: 0.19623742997646332  (0.19660566995541254)
     | > align_error: 0.5803646445274353  (0.6026169694960117)

   --> STEP: 25
     | > decoder_loss: 0.45416274666786194  (0.44847135186195375)
     | > postnet_loss: 0.3084927201271057  (0.31328240513801575)
     | > stopnet_loss: 0.0036590152885764837  (0.006075919801369309)
     | > loss: 0.1943228840827942  (0.1965143585205078)
     | > align_error: 0.5584884881973267  (0.6008518302440643)

   --> STEP: 26
     | > decoder_loss: 0.4291759133338928  (0.4477292196108745)
     | > postnet_loss: 0.2974816858768463  (0.3126746851664323)
     | > stopnet_loss: 0.004300132859498262  (0.006007620303605039)
     | > loss: 0.18596453964710236  (0.19610859625614607)
     | > align_error: 0.5475450456142426  (0.5988015692967635)

   --> STEP: 27
     | > decoder_loss: 0.4266165494918823  (0.4469472688657266)
     | > postnet_loss: 0.2922913432121277  (0.3119197465755321)
     | > stopnet_loss: 0.003838940057903528  (0.005927298813023501)
     | > loss: 0.1835659146308899  (0.1956440524922477)
     | > align_error: 0.541597992181778  (0.5966829182925047)

   --> STEP: 28
     | > decoder_loss: 0.43220704793930054  (0.44642083240406855)
     | > postnet_loss: 0.29715460538864136  (0.31139242010457174)
     | > stopnet_loss: 0.003914870787411928  (0.005855426383537373)
     | > loss: 0.1862552911043167  (0.19530873958553588)
     | > align_error: 0.5672468841075897  (0.5956316313573292)

   --> STEP: 29
     | > decoder_loss: 0.42763155698776245  (0.4457729263552304)
     | > postnet_loss: 0.29427891969680786  (0.31080229940085574)
     | > stopnet_loss: 0.0035419887863099575  (0.005775652673288152)
     | > loss: 0.18401961028575897  (0.1949194592648539)
     | > align_error: 0.5411624610424042  (0.5937533841050905)

   --> STEP: 30
     | > decoder_loss: 0.42831557989120483  (0.44519101480642953)
     | > postnet_loss: 0.294914573431015  (0.3102727085351944)
     | > stopnet_loss: 0.00277156219817698  (0.00567551632411778)
     | > loss: 0.18357908725738525  (0.19454144686460495)
     | > align_error: 0.5340973138809204  (0.5917648484309515)

   --> STEP: 31
     | > decoder_loss: 0.4233609437942505  (0.444486818967327)
     | > postnet_loss: 0.2924228012561798  (0.30969690507458103)
     | > stopnet_loss: 0.003705741139128804  (0.005611975189118135)
     | > loss: 0.18265166878700256  (0.1941579056362952)
     | > align_error: 0.5558666586875916  (0.5906068423101979)

   --> STEP: 32
     | > decoder_loss: 0.4367566704750061  (0.44424525182694197)
     | > postnet_loss: 0.29959943890571594  (0.309381359256804)
     | > stopnet_loss: 0.0038119424134492874  (0.005555724164878484)
     | > loss: 0.18790097534656525  (0.19396237656474113)
     | > align_error: 0.5318034589290619  (0.5887692365795374)

   --> STEP: 33
     | > decoder_loss: 0.4333649277687073  (0.44391554503729846)
     | > postnet_loss: 0.29686716198921204  (0.30900214115778607)
     | > stopnet_loss: 0.003995661623775959  (0.005508449542420832)
     | > loss: 0.1865536868572235  (0.19373787081602847)
     | > align_error: 0.5468166470527649  (0.587497945987817)

   --> STEP: 34
     | > decoder_loss: 0.4391494691371918  (0.44377536633435416)
     | > postnet_loss: 0.29843759536743164  (0.30869141922277565)
     | > stopnet_loss: 0.0032615968957543373  (0.005442365641048288)
     | > loss: 0.1876583695411682  (0.19355906195500316)
     | > align_error: 0.5644011795520782  (0.5868186293279424)

   --> STEP: 35
     | > decoder_loss: 0.436294287443161  (0.4435616212231772)
     | > postnet_loss: 0.2978338897228241  (0.3083812040942056)
     | > stopnet_loss: 0.0034746089950203896  (0.005386144022590348)
     | > loss: 0.1870066523551941  (0.19337185025215148)
     | > align_error: 0.5340374708175659  (0.5853105962276459)

   --> STEP: 36
     | > decoder_loss: 0.4421432912349701  (0.44352222316794926)
     | > postnet_loss: 0.3018997609615326  (0.3082011640071869)
     | > stopnet_loss: 0.0036483872681856155  (0.005337873001634661)
     | > loss: 0.18965914845466614  (0.19326871964666578)
     | > align_error: 0.6342980861663818  (0.5866713598370552)

   --> STEP: 37
     | > decoder_loss: 0.4344179928302765  (0.4432761628885527)
     | > postnet_loss: 0.2984170615673065  (0.30793672880610906)
     | > stopnet_loss: 0.0035336094442754984  (0.005289109121706034)
     | > loss: 0.1867423802614212  (0.19309233209571322)
     | > align_error: 0.5195375084877014  (0.5848569314222078)

   --> STEP: 38
     | > decoder_loss: 0.4213714599609375  (0.442699723337826)
     | > postnet_loss: 0.2908240854740143  (0.3074863960868434)
     | > stopnet_loss: 0.003118993481621146  (0.005232000815388011)
     | > loss: 0.181167870759964  (0.19277853048161456)
     | > align_error: 0.5525827705860138  (0.5840076114002027)

   --> STEP: 39
     | > decoder_loss: 0.437935471534729  (0.4425775630351825)
     | > postnet_loss: 0.3022352457046509  (0.30735175120524877)
     | > stopnet_loss: 0.0034497978631407022  (0.005186303303791926)
     | > loss: 0.18849247694015503  (0.1926686316728592)
     | > align_error: 0.5467075109481812  (0.5830511985680996)

   --> STEP: 40
     | > decoder_loss: 0.4350222051143646  (0.442388679087162)
     | > postnet_loss: 0.3007220923900604  (0.30718600973486904)
     | > stopnet_loss: 0.0030167566146701574  (0.005132064636563882)
     | > loss: 0.18695282936096191  (0.19252573661506175)
     | > align_error: 0.584619402885437  (0.583090403676033)

   --> STEP: 41
     | > decoder_loss: 0.42620518803596497  (0.44199395979323036)
     | > postnet_loss: 0.29342323541641235  (0.30685033231246767)
     | > stopnet_loss: 0.0037363055162131786  (0.005098021731189475)
     | > loss: 0.1836434155702591  (0.19230909463835927)
     | > align_error: 0.503803551197052  (0.581156578005814)

   --> STEP: 42
     | > decoder_loss: 0.43126022815704346  (0.44173839475427357)
     | > postnet_loss: 0.29522258043289185  (0.3065734810772397)
     | > stopnet_loss: 0.003252302762120962  (0.005054076041449748)
     | > loss: 0.18487299978733063  (0.1921320447609538)
     | > align_error: 0.5801128149032593  (0.5811317265033722)

   --> STEP: 43
     | > decoder_loss: 0.42997869849205017  (0.44146491344584976)
     | > postnet_loss: 0.2937981188297272  (0.3062763796296231)
     | > stopnet_loss: 0.0029057227075099945  (0.005004114336009289)
     | > loss: 0.18384993076324463  (0.1919394374586815)
     | > align_error: 0.5523720979690552  (0.5804628979328067)

   --> STEP: 44
     | > decoder_loss: 0.44747301936149597  (0.441601461307569)
     | > postnet_loss: 0.3047238290309906  (0.3062410943887451)
     | > stopnet_loss: 0.0026435470208525658  (0.004950465078846635)
     | > loss: 0.1906927525997162  (0.19191110371188683)
     | > align_error: 0.5517710447311401  (0.5798108103600416)

   --> STEP: 45
     | > decoder_loss: 0.4402894973754883  (0.44157230655352275)
     | > postnet_loss: 0.3034731149673462  (0.3061795837349362)
     | > stopnet_loss: 0.0032329782843589783  (0.004912298705635798)
     | > loss: 0.1891736388206482  (0.1918502711587482)
     | > align_error: 0.5532894134521484  (0.5792214459843106)

   --> STEP: 46
     | > decoder_loss: 0.431020051240921  (0.44134290969890094)
     | > postnet_loss: 0.2952326536178589  (0.3059416069932606)
     | > stopnet_loss: 0.0031887940131127834  (0.00487483121232008)
     | > loss: 0.184751957654953  (0.19169595999562222)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3590979865103057 (+0.017141519170818964)
     | > avg_decoder_loss: 0.4375173490155827 (+3.491748463024802e-05)
     | > avg_postnet_loss: 0.30314817392464843 (+0.0013238209666628364)
     | > avg_stopnet_loss: 0.00432765118735419 (+6.938028629078878e-06)
     | > avg_loss: 0.18949403071945364 (+0.000346622683785186)
     | > avg_align_error: 0.5721239285035566 (-9.607726877391976e-05)


 > EPOCH: 150/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 19:15:25)

   --> TIME: 2025-12-28 19:15:26 -- STEP: 0/150 -- GLOBAL_STEP: 22650
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4455457627773285  (0.4455457627773285)
     | > postnet_loss: 0.3831055164337158  (0.3831055164337158)
     | > stopnet_loss: 0.020113911479711533  (0.020113911479711533)
     | > loss: 0.2272767424583435  (0.2272767424583435)
     | > align_error: 0.7501559257507324  (0.7501559257507324)
     | > grad_norm: tensor(0.3276, device='cuda:0')  (tensor(0.3276, device='cuda:0'))
     | > step_time: 0.4879  (0.48786067962646484)
     | > loader_time: 0.6395  (0.6394524574279785)


   --> TIME: 2025-12-28 19:16:03 -- STEP: 25/150 -- GLOBAL_STEP: 22675
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.47607946395874023  (0.4652011513710022)
     | > postnet_loss: 0.39917346835136414  (0.393158974647522)
     | > stopnet_loss: 0.0069107599556446075  (0.009598401188850404)
     | > loss: 0.225723996758461  (0.2241884332895279)
     | > align_error: 0.6183593273162842  (0.6704756414890289)
     | > grad_norm: tensor(0.2522, device='cuda:0')  (tensor(0.2715, device='cuda:0'))
     | > step_time: 0.787  (0.6668201351165773)
     | > loader_time: 0.9395  (0.7995623779296875)


   --> TIME: 2025-12-28 19:16:57 -- STEP: 50/150 -- GLOBAL_STEP: 22700
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.487997829914093  (0.47299921154975894)
     | > postnet_loss: 0.4019884765148163  (0.3958273738622665)
     | > stopnet_loss: 0.004360249266028404  (0.007489238576963542)
     | > loss: 0.22685681283473969  (0.2246958854794502)
     | > align_error: 0.6339199244976044  (0.647466748356819)
     | > grad_norm: tensor(0.2129, device='cuda:0')  (tensor(0.3410, device='cuda:0'))
     | > step_time: 1.2681  (0.9115510463714602)
     | > loader_time: 1.0978  (0.9019607257843018)


   --> TIME: 2025-12-28 19:18:03 -- STEP: 75/150 -- GLOBAL_STEP: 22725
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4801652133464813  (0.47605085174242656)
     | > postnet_loss: 0.39260900020599365  (0.39573281367619834)
     | > stopnet_loss: 0.003392792074009776  (0.006374169966826835)
     | > loss: 0.22158634662628174  (0.22432008703549702)
     | > align_error: 0.6132339835166931  (0.6364252301057178)
     | > grad_norm: tensor(0.2030, device='cuda:0')  (tensor(0.3070, device='cuda:0'))
     | > step_time: 1.5906  (1.0906940174102786)
     | > loader_time: 1.2423  (1.0028683026631673)


   --> TIME: 2025-12-28 19:19:22 -- STEP: 100/150 -- GLOBAL_STEP: 22750
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47778820991516113  (0.47745073020458223)
     | > postnet_loss: 0.38998863101005554  (0.3951026841998101)
     | > stopnet_loss: 0.003191141877323389  (0.005694453543983399)
     | > loss: 0.22013536095619202  (0.22383280813694)
     | > align_error: 0.5830243825912476  (0.631363009214401)
     | > grad_norm: tensor(0.1533, device='cuda:0')  (tensor(0.2751, device='cuda:0'))
     | > step_time: 1.6652  (1.231749951839448)
     | > loader_time: 1.5785  (1.123141255378723)


   --> TIME: 2025-12-28 19:20:54 -- STEP: 125/150 -- GLOBAL_STEP: 22775
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.47775954008102417  (0.4786184957027435)
     | > postnet_loss: 0.3879498541355133  (0.3947053384780884)
     | > stopnet_loss: 0.0029730151873081923  (0.005214535759761929)
     | > loss: 0.21940037608146667  (0.22354549503326415)
     | > align_error: 0.5908830165863037  (0.6272756416797636)
     | > grad_norm: tensor(0.1945, device='cuda:0')  (tensor(0.2707, device='cuda:0'))
     | > step_time: 1.9092  (1.3583672523498544)
     | > loader_time: 1.8836  (1.2618998241424555)


   --> TIME: 2025-12-28 19:22:52 -- STEP: 150/150 -- GLOBAL_STEP: 22800
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4956040382385254  (0.4802307842175166)
     | > postnet_loss: 0.40119487047195435  (0.39472815334796907)
     | > stopnet_loss: 0.002276690909639001  (0.004840981238521636)
     | > loss: 0.22647641599178314  (0.22358071664969126)
     | > align_error: 0.5833835303783417  (0.6237921947240828)
     | > grad_norm: tensor(0.2367, device='cuda:0')  (tensor(0.2593, device='cuda:0'))
     | > step_time: 3.1889  (1.5874179951349903)
     | > loader_time: 0.7133  (1.383307223320007)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4570252001285553  (0.4570252001285553)
     | > postnet_loss: 0.3315713405609131  (0.3315713405609131)
     | > stopnet_loss: 0.012124127708375454  (0.012124127708375454)
     | > loss: 0.20927324891090393  (0.20927324891090393)
     | > align_error: 0.7185699939727783  (0.7185699939727783)

   --> STEP: 1
     | > decoder_loss: 0.4380947947502136  (0.4380947947502136)
     | > postnet_loss: 0.31886136531829834  (0.31886136531829834)
     | > stopnet_loss: 0.00956478901207447  (0.00956478901207447)
     | > loss: 0.1988038271665573  (0.1988038271665573)
     | > align_error: 0.6588474810123444  (0.6588474810123444)

   --> STEP: 2
     | > decoder_loss: 0.4342665672302246  (0.4361806809902191)
     | > postnet_loss: 0.3105107247829437  (0.31468604505062103)
     | > stopnet_loss: 0.011048352345824242  (0.010306570678949356)
     | > loss: 0.19724267721176147  (0.1980232521891594)
     | > align_error: 0.6550651788711548  (0.6569563299417496)

   --> STEP: 3
     | > decoder_loss: 0.4384351074695587  (0.43693215648333233)
     | > postnet_loss: 0.31013232469558716  (0.31316813826560974)
     | > stopnet_loss: 0.008130929432809353  (0.009581356930236021)
     | > loss: 0.1952727884054184  (0.19710643092791238)
     | > align_error: 0.7347458004951477  (0.682886153459549)

   --> STEP: 4
     | > decoder_loss: 0.44119498133659363  (0.43799786269664764)
     | > postnet_loss: 0.31684941053390503  (0.31408845633268356)
     | > stopnet_loss: 0.008113158866763115  (0.009214307414367795)
     | > loss: 0.19762425124645233  (0.19723588600754738)
     | > align_error: 0.6027208566665649  (0.662844829261303)

   --> STEP: 5
     | > decoder_loss: 0.42438724637031555  (0.4352757394313812)
     | > postnet_loss: 0.30023059248924255  (0.31131688356399534)
     | > stopnet_loss: 0.008068107068538666  (0.008985067345201969)
     | > loss: 0.1892225742340088  (0.19563322365283967)
     | > align_error: 0.6414791941642761  (0.6585717022418975)

   --> STEP: 6
     | > decoder_loss: 0.4409743845462799  (0.4362255136171977)
     | > postnet_loss: 0.31160223484039307  (0.31136444211006165)
     | > stopnet_loss: 0.007194359786808491  (0.008686616085469723)
     | > loss: 0.19533850252628326  (0.19558410346508026)
     | > align_error: 0.5933573246002197  (0.647702639301618)

   --> STEP: 7
     | > decoder_loss: 0.4523008465766907  (0.4385219897542681)
     | > postnet_loss: 0.3119029998779297  (0.3114413789340428)
     | > stopnet_loss: 0.006178875919431448  (0.008328367490321398)
     | > loss: 0.19722983241081238  (0.19581920760018484)
     | > align_error: 0.5782277882099152  (0.6377776605742318)

   --> STEP: 8
     | > decoder_loss: 0.44842392206192017  (0.4397597312927246)
     | > postnet_loss: 0.3133560121059418  (0.31168070808053017)
     | > stopnet_loss: 0.00702884653583169  (0.008165927371010184)
     | > loss: 0.19747382402420044  (0.1960260346531868)
     | > align_error: 0.5734320878982544  (0.6297344639897346)

   --> STEP: 9
     | > decoder_loss: 0.44532138109207153  (0.44037769238154095)
     | > postnet_loss: 0.31267184019088745  (0.3117908338705699)
     | > stopnet_loss: 0.00666235014796257  (0.007998863235116005)
     | > loss: 0.19616065919399261  (0.19604099293549856)
     | > align_error: 0.5905316770076752  (0.6253785987695059)

   --> STEP: 10
     | > decoder_loss: 0.4698660671710968  (0.44332652986049653)
     | > postnet_loss: 0.32633039355278015  (0.3132447898387909)
     | > stopnet_loss: 0.005537165328860283  (0.007752693444490433)
     | > loss: 0.20458628237247467  (0.19689552187919618)
     | > align_error: 0.5829957723617554  (0.6211403161287308)

   --> STEP: 11
     | > decoder_loss: 0.456770658493042  (0.4445487233725461)
     | > postnet_loss: 0.3164185583591461  (0.3135333142497323)
     | > stopnet_loss: 0.0058783902786672115  (0.007582302247597413)
     | > loss: 0.19917568564414978  (0.19710280949419196)
     | > align_error: 0.5944130122661591  (0.6187105612321333)

   --> STEP: 12
     | > decoder_loss: 0.45323532819747925  (0.4452726071079572)
     | > postnet_loss: 0.3101164400577545  (0.31324857473373413)
     | > stopnet_loss: 0.007864267565310001  (0.007605799357406795)
     | > loss: 0.19870221614837646  (0.19723609338204065)
     | > align_error: 0.5867273807525635  (0.6160452961921692)

   --> STEP: 13
     | > decoder_loss: 0.44337397813796997  (0.4451265587256505)
     | > postnet_loss: 0.31037819385528564  (0.3130277762046227)
     | > stopnet_loss: 0.005264987703412771  (0.007425736922484178)
     | > loss: 0.19370302557945251  (0.19696431893568772)
     | > align_error: 0.5844119787216187  (0.6136119640790499)

   --> STEP: 14
     | > decoder_loss: 0.45476314425468445  (0.4458148862634386)
     | > postnet_loss: 0.3138420581817627  (0.3130859392029898)
     | > stopnet_loss: 0.004901279229670763  (0.007245418515854648)
     | > loss: 0.19705258309841156  (0.19697062351873942)
     | > align_error: 0.5541345477104187  (0.6093635771955762)

   --> STEP: 15
     | > decoder_loss: 0.452363520860672  (0.4462514619032542)
     | > postnet_loss: 0.31357941031455994  (0.3131188372770945)
     | > stopnet_loss: 0.004997872747480869  (0.007095582131296396)
     | > loss: 0.19648361206054688  (0.19693815608819326)
     | > align_error: 0.5881320238113403  (0.6079481403032939)

   --> STEP: 16
     | > decoder_loss: 0.45292535424232483  (0.4466685801744461)
     | > postnet_loss: 0.3077180087566376  (0.31278128549456596)
     | > stopnet_loss: 0.005248468369245529  (0.006980137521168217)
     | > loss: 0.19540931284427643  (0.19684260338544846)
     | > align_error: 0.6052228212356567  (0.6077778078615665)

   --> STEP: 17
     | > decoder_loss: 0.45944926142692566  (0.4474203849540037)
     | > postnet_loss: 0.31609994173049927  (0.31297650056726795)
     | > stopnet_loss: 0.004764964804053307  (0.006849833243690869)
     | > loss: 0.1986522525548935  (0.1969490533365923)
     | > align_error: 0.5580087304115295  (0.6048502150703879)

   --> STEP: 18
     | > decoder_loss: 0.45402491092681885  (0.4477873030636046)
     | > postnet_loss: 0.3084694445133209  (0.31272610856427085)
     | > stopnet_loss: 0.005206627305597067  (0.0067585440249078805)
     | > loss: 0.19583021104335785  (0.19688689543141258)
     | > align_error: 0.603575587272644  (0.6047794024149576)

   --> STEP: 19
     | > decoder_loss: 0.4491095542907715  (0.44785689523345545)
     | > postnet_loss: 0.3067106306552887  (0.3124095044637981)
     | > stopnet_loss: 0.004699532873928547  (0.0066501750169616)
     | > loss: 0.19365456700325012  (0.19671677288256192)
     | > align_error: 0.5985611379146576  (0.6044521253359946)

   --> STEP: 20
     | > decoder_loss: 0.4481326639652252  (0.44787068367004396)
     | > postnet_loss: 0.3046800196170807  (0.31202303022146227)
     | > stopnet_loss: 0.0044725374318659306  (0.0065412931377068165)
     | > loss: 0.19267570972442627  (0.19651471972465515)
     | > align_error: 0.622447669506073  (0.6053519025444986)

   --> STEP: 21
     | > decoder_loss: 0.4449617564678192  (0.4477321633270809)
     | > postnet_loss: 0.3031446635723114  (0.311600250857217)
     | > stopnet_loss: 0.003944858442991972  (0.006417653390339443)
     | > loss: 0.1909714639186859  (0.19625075516246615)
     | > align_error: 0.5591617226600647  (0.6031523701690493)

   --> STEP: 22
     | > decoder_loss: 0.4467454254627228  (0.4476873116059737)
     | > postnet_loss: 0.3058509826660156  (0.31133892048488965)
     | > stopnet_loss: 0.004777763970196247  (0.006343112962151115)
     | > loss: 0.19292685389518738  (0.1960996687412262)
     | > align_error: 0.6249463260173798  (0.6041430045257916)

   --> STEP: 23
     | > decoder_loss: 0.42123711109161377  (0.446537302887958)
     | > postnet_loss: 0.2941221296787262  (0.3105903643628825)
     | > stopnet_loss: 0.004402474965900183  (0.006258737397096727)
     | > loss: 0.18324227631092072  (0.195540651679039)
     | > align_error: 0.5666079521179199  (0.6025110457254493)

   --> STEP: 24
     | > decoder_loss: 0.45629629492759705  (0.4469439275562763)
     | > postnet_loss: 0.3106570243835449  (0.3105931418637434)
     | > stopnet_loss: 0.004384082742035389  (0.006180626786469172)
     | > loss: 0.1961224228143692  (0.1955648921430111)
     | > align_error: 0.5792620778083801  (0.6015423387289048)

   --> STEP: 25
     | > decoder_loss: 0.4554741084575653  (0.4472851347923279)
     | > postnet_loss: 0.3076862096786499  (0.31047686457633966)
     | > stopnet_loss: 0.003646917873993516  (0.006079278429970145)
     | > loss: 0.19443701207637787  (0.19551977694034575)
     | > align_error: 0.5576034188270569  (0.5997847819328309)

   --> STEP: 26
     | > decoder_loss: 0.4297097325325012  (0.44660915778233456)
     | > postnet_loss: 0.29580172896385193  (0.30991243628355164)
     | > stopnet_loss: 0.004307896830141544  (0.0060111483684382756)
     | > loss: 0.18568575382232666  (0.19514154528196043)
     | > align_error: 0.5462504625320435  (0.5977257696481852)

   --> STEP: 27
     | > decoder_loss: 0.42584049701690674  (0.44583994812435573)
     | > postnet_loss: 0.29065319895744324  (0.3091991311973995)
     | > stopnet_loss: 0.003598268609493971  (0.005921782451440339)
     | > loss: 0.18272170424461365  (0.1946815511694661)
     | > align_error: 0.5396999716758728  (0.5955766660195811)

   --> STEP: 28
     | > decoder_loss: 0.432574599981308  (0.4453661856906755)
     | > postnet_loss: 0.2957550585269928  (0.308718985744885)
     | > stopnet_loss: 0.003891973290592432  (0.005849289267124342)
     | > loss: 0.1859743893146515  (0.19437058110322272)
     | > align_error: 0.5659017860889435  (0.5945168488792012)

   --> STEP: 29
     | > decoder_loss: 0.4272605776786804  (0.44474185437991703)
     | > postnet_loss: 0.29209622740745544  (0.30814578718152535)
     | > stopnet_loss: 0.0035538910888135433  (0.00577013760580328)
     | > loss: 0.18339309096336365  (0.19399204696046896)
     | > align_error: 0.5396995544433594  (0.5926265973469308)

   --> STEP: 30
     | > decoder_loss: 0.42825889587402344  (0.44419242242972057)
     | > postnet_loss: 0.29315438866615295  (0.30764607389767956)
     | > stopnet_loss: 0.002772615058347583  (0.005670220187554757)
     | > loss: 0.18312592804431915  (0.1936298429965973)
     | > align_error: 0.5326262712478638  (0.5906265864769619)

   --> STEP: 31
     | > decoder_loss: 0.4241412580013275  (0.443545610673966)
     | > postnet_loss: 0.29163458943367004  (0.3071295743988406)
     | > stopnet_loss: 0.0036622146144509315  (0.005605445814228827)
     | > loss: 0.18260617554187775  (0.1932742408206386)
     | > align_error: 0.5536927878856659  (0.5894351736191782)

   --> STEP: 32
     | > decoder_loss: 0.43727684020996094  (0.4433497115969658)
     | > postnet_loss: 0.29830947518348694  (0.30685394629836077)
     | > stopnet_loss: 0.0037981667555868626  (0.005548968343646266)
     | > loss: 0.1876947432756424  (0.19309988152235746)
     | > align_error: 0.5303843021392822  (0.5875898338854314)

   --> STEP: 33
     | > decoder_loss: 0.4332079589366913  (0.44304238575877564)
     | > postnet_loss: 0.2958201766014099  (0.3065195896408774)
     | > stopnet_loss: 0.003985906485468149  (0.005501602832792383)
     | > loss: 0.186242938041687  (0.19289209535627655)
     | > align_error: 0.5453240871429443  (0.5863090536811136)

   --> STEP: 34
     | > decoder_loss: 0.43989360332489014  (0.4429497745107202)
     | > postnet_loss: 0.29768598079681396  (0.306259777616052)
     | > stopnet_loss: 0.0032527733128517866  (0.005435460788088248)
     | > loss: 0.18764767050743103  (0.19273784756660461)
     | > align_error: 0.5630611479282379  (0.5856252917472055)

   --> STEP: 35
     | > decoder_loss: 0.4357415437698364  (0.44274382506098064)
     | > postnet_loss: 0.2958604097366333  (0.3059626528194972)
     | > stopnet_loss: 0.0034702427219599485  (0.005379311700484582)
     | > loss: 0.18637073040008545  (0.1925559299332755)
     | > align_error: 0.5325158536434174  (0.5841078792299544)

   --> STEP: 36
     | > decoder_loss: 0.4421160817146301  (0.44272638774580425)
     | > postnet_loss: 0.3006587028503418  (0.30581532087590957)
     | > stopnet_loss: 0.00361206429079175  (0.0053302214946597815)
     | > loss: 0.18930576741695404  (0.19246564764115545)
     | > align_error: 0.6330382525920868  (0.5854670562677914)

   --> STEP: 37
     | > decoder_loss: 0.43455737829208374  (0.44250560370651454)
     | > postnet_loss: 0.2969958186149597  (0.305576955949938)
     | > stopnet_loss: 0.0035235031973570585  (0.005281391270408356)
     | > loss: 0.1864117980003357  (0.19230203008329547)
     | > align_error: 0.5180896818637848  (0.5836460461487643)

   --> STEP: 38
     | > decoder_loss: 0.4219968914985657  (0.44196590075367376)
     | > postnet_loss: 0.28966638445854187  (0.30515825670016444)
     | > stopnet_loss: 0.0031100688502192497  (0.00522425120671917)
     | > loss: 0.18102587759494781  (0.19200528922833895)
     | > align_error: 0.5508453249931335  (0.5827828692762477)

   --> STEP: 39
     | > decoder_loss: 0.4379160404205322  (0.4418620581810291)
     | > postnet_loss: 0.3004244863986969  (0.3050368779744858)
     | > stopnet_loss: 0.003433638485148549  (0.005178338060012231)
     | > loss: 0.1880187690258026  (0.19190307076160723)
     | > align_error: 0.545382022857666  (0.5818238732142328)

   --> STEP: 40
     | > decoder_loss: 0.4352394640445709  (0.4416964933276176)
     | > postnet_loss: 0.29905039072036743  (0.3048872157931329)
     | > stopnet_loss: 0.0030005781445652246  (0.0051238940621260555)
     | > loss: 0.18657304346561432  (0.1917698200792074)
     | > align_error: 0.583186149597168  (0.5818579301238062)

   --> STEP: 41
     | > decoder_loss: 0.4251736104488373  (0.44129349618423275)
     | > postnet_loss: 0.2910288870334625  (0.3045492077746043)
     | > stopnet_loss: 0.0037083749193698168  (0.005089369204985659)
     | > loss: 0.18275900185108185  (0.19155004402486286)
     | > align_error: 0.5021650791168213  (0.5799142020504651)

   --> STEP: 42
     | > decoder_loss: 0.430376261472702  (0.4410335620244344)
     | > postnet_loss: 0.29338619112968445  (0.304283421664011)
     | > stopnet_loss: 0.003257616190239787  (0.005045756037967901)
     | > loss: 0.18419823050498962  (0.1913750008458183)
     | > align_error: 0.578840434551239  (0.5798886361576263)

   --> STEP: 43
     | > decoder_loss: 0.43005746603012085  (0.440778303978055)
     | > postnet_loss: 0.29254475235939026  (0.3040104293546012)
     | > stopnet_loss: 0.0028937619645148516  (0.004995709664166667)
     | > loss: 0.18354432284832  (0.1911928920551788)
     | > align_error: 0.5510640144348145  (0.5792182961175609)

   --> STEP: 44
     | > decoder_loss: 0.44773054122924805  (0.44093630937012757)
     | > postnet_loss: 0.3031696677207947  (0.3039913211356511)
     | > stopnet_loss: 0.002632458694279194  (0.004941999414851042)
     | > loss: 0.190357506275177  (0.1911739060147242)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3427530057502515 (-0.016344980760054195)
     | > avg_decoder_loss: 0.4368341285170931 (-0.0006832204984896229)
     | > avg_postnet_loss: 0.3006657488418348 (-0.002482425082813655)
     | > avg_stopnet_loss: 0.004318897524199477 (-8.753663154713667e-06)
     | > avg_loss: 0.18869386635946506 (-0.0008001643599885866)
     | > avg_align_error: 0.5707933803399404 (-0.0013305481636162186)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_22801.pth

 > EPOCH: 151/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 19:24:37)

   --> TIME: 2025-12-28 19:25:15 -- STEP: 24/150 -- GLOBAL_STEP: 22825
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.48121410608291626  (0.4652125823001067)
     | > postnet_loss: 0.4017617702484131  (0.39342014988263446)
     | > stopnet_loss: 0.006363104563206434  (0.009776178456377236)
     | > loss: 0.22710707783699036  (0.2244343621035417)
     | > align_error: 0.6941232681274414  (0.6723228432238102)
     | > grad_norm: tensor(0.3947, device='cuda:0')  (tensor(0.2763, device='cuda:0'))
     | > step_time: 0.9144  (0.6557009716828663)
     | > loader_time: 0.8596  (0.8671947419643402)


   --> TIME: 2025-12-28 19:26:08 -- STEP: 49/150 -- GLOBAL_STEP: 22850
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4799431562423706  (0.4725074245005238)
     | > postnet_loss: 0.39548733830451965  (0.3956634189401354)
     | > stopnet_loss: 0.004717864096164703  (0.007594182925792981)
     | > loss: 0.22357547283172607  (0.22463689409956641)
     | > align_error: 0.5826058089733124  (0.6475501978883937)
     | > grad_norm: tensor(0.1472, device='cuda:0')  (tensor(0.2663, device='cuda:0'))
     | > step_time: 1.3161  (0.8839684943763577)
     | > loader_time: 1.1127  (0.9315322467258998)


   --> TIME: 2025-12-28 19:27:14 -- STEP: 74/150 -- GLOBAL_STEP: 22875
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4824165999889374  (0.47578328807611725)
     | > postnet_loss: 0.3937360644340515  (0.3955937539403503)
     | > stopnet_loss: 0.003669707104563713  (0.006424977768187386)
     | > loss: 0.2227078676223755  (0.22426923827545062)
     | > align_error: 0.6009647846221924  (0.6356973201036453)
     | > grad_norm: tensor(0.2489, device='cuda:0')  (tensor(0.2367, device='cuda:0'))
     | > step_time: 1.54  (1.0641773133664518)
     | > loader_time: 1.3041  (1.0287690613720868)


   --> TIME: 2025-12-28 19:28:33 -- STEP: 99/150 -- GLOBAL_STEP: 22900
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48995575308799744  (0.47718999512267835)
     | > postnet_loss: 0.39712637662887573  (0.39496737417548594)
     | > stopnet_loss: 0.003287398722022772  (0.005732487536722211)
     | > loss: 0.2250579297542572  (0.22377182964724723)
     | > align_error: 0.6019752621650696  (0.6307850564369049)
     | > grad_norm: tensor(0.5101, device='cuda:0')  (tensor(0.2254, device='cuda:0'))
     | > step_time: 1.7334  (1.2105802213302763)
     | > loader_time: 1.6089  (1.1581292296900891)


   --> TIME: 2025-12-28 19:30:00 -- STEP: 124/150 -- GLOBAL_STEP: 22925
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4801294207572937  (0.4782725125551224)
     | > postnet_loss: 0.3899371325969696  (0.39447118438059287)
     | > stopnet_loss: 0.003533792681992054  (0.005249794747214764)
     | > loss: 0.221050426363945  (0.22343571880652058)
     | > align_error: 0.6139408648014069  (0.6266913293830811)
     | > grad_norm: tensor(0.1493, device='cuda:0')  (tensor(0.2147, device='cuda:0'))
     | > step_time: 2.4427  (1.343730613108604)
     | > loader_time: 1.6769  (1.2438723752575531)


   --> TIME: 2025-12-28 19:31:45 -- STEP: 149/150 -- GLOBAL_STEP: 22950
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5130449533462524  (0.47981982963197184)
     | > postnet_loss: 0.41117340326309204  (0.3944278405416731)
     | > stopnet_loss: 0.002406024606898427  (0.004873717425628599)
     | > loss: 0.23346062004566193  (0.22343563503467)
     | > align_error: 0.6242403984069824  (0.6232921909165864)
     | > grad_norm: tensor(0.3119, device='cuda:0')  (tensor(0.2085, device='cuda:0'))
     | > step_time: 10.0385  (1.5171080883717376)
     | > loader_time: 2.7953  (1.3438580212177043)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45871302485466003  (0.45871302485466003)
     | > postnet_loss: 0.33205553889274597  (0.33205553889274597)
     | > stopnet_loss: 0.01219381857663393  (0.01219381857663393)
     | > loss: 0.20988595485687256  (0.20988595485687256)
     | > align_error: 0.7187962532043457  (0.7187962532043457)

   --> STEP: 1
     | > decoder_loss: 0.4396950602531433  (0.4396950602531433)
     | > postnet_loss: 0.31924331188201904  (0.31924331188201904)
     | > stopnet_loss: 0.009645388461649418  (0.009645388461649418)
     | > loss: 0.19937998056411743  (0.19937998056411743)
     | > align_error: 0.658847987651825  (0.658847987651825)

   --> STEP: 2
     | > decoder_loss: 0.4364667534828186  (0.43808090686798096)
     | > postnet_loss: 0.31161683797836304  (0.31543007493019104)
     | > stopnet_loss: 0.010950752533972263  (0.01029807049781084)
     | > loss: 0.1979716569185257  (0.19867581874132156)
     | > align_error: 0.6550711989402771  (0.656959593296051)

   --> STEP: 3
     | > decoder_loss: 0.4398905038833618  (0.4386841058731079)
     | > postnet_loss: 0.3104330897331238  (0.31376441319783527)
     | > stopnet_loss: 0.008217459544539452  (0.009604533513387045)
     | > loss: 0.1957983523607254  (0.19771666328112283)
     | > align_error: 0.7348618507385254  (0.6829270124435425)

   --> STEP: 4
     | > decoder_loss: 0.4429950714111328  (0.43976184725761414)
     | > postnet_loss: 0.3175640106201172  (0.31471431255340576)
     | > stopnet_loss: 0.008173574693500996  (0.009246793808415532)
     | > loss: 0.19831334054470062  (0.1978658325970173)
     | > align_error: 0.6026130020618439  (0.6628485098481178)

   --> STEP: 5
     | > decoder_loss: 0.4258134067058563  (0.43697215914726256)
     | > postnet_loss: 0.30056101083755493  (0.3118836522102356)
     | > stopnet_loss: 0.008049432188272476  (0.009007321484386922)
     | > loss: 0.1896430253982544  (0.1962212711572647)
     | > align_error: 0.6412187218666077  (0.6585225522518158)

   --> STEP: 6
     | > decoder_loss: 0.4423191249370575  (0.4378633201122284)
     | > postnet_loss: 0.3121173679828644  (0.3119226048390071)
     | > stopnet_loss: 0.007278089411556721  (0.00871911613891522)
     | > loss: 0.19588720798492432  (0.19616559396187463)
     | > align_error: 0.593421459197998  (0.6476723700761795)

   --> STEP: 7
     | > decoder_loss: 0.4527565836906433  (0.4399909291948591)
     | > postnet_loss: 0.31198376417160034  (0.3119313418865204)
     | > stopnet_loss: 0.006227141711860895  (0.008363119792193174)
     | > loss: 0.19741222262382507  (0.1963436837707247)
     | > align_error: 0.5783354640007019  (0.6377670977796827)

   --> STEP: 8
     | > decoder_loss: 0.44911184906959534  (0.4411310441792011)
     | > postnet_loss: 0.31318122148513794  (0.3120875768363476)
     | > stopnet_loss: 0.007207851856946945  (0.008218711300287396)
     | > loss: 0.19778113067150116  (0.19652336463332176)
     | > align_error: 0.5742043852806091  (0.6298217587172985)

   --> STEP: 9
     | > decoder_loss: 0.4452994167804718  (0.4415941966904534)
     | > postnet_loss: 0.3124045431613922  (0.3121227953169081)
     | > stopnet_loss: 0.006600131746381521  (0.008038869127631187)
     | > loss: 0.19602611660957336  (0.19646811485290527)
     | > align_error: 0.5903918147087097  (0.6254406538274553)

   --> STEP: 10
     | > decoder_loss: 0.4714977443218231  (0.4445845514535904)
     | > postnet_loss: 0.32673177123069763  (0.313583692908287)
     | > stopnet_loss: 0.005599418189376593  (0.007794924033805728)
     | > loss: 0.20515680313110352  (0.1973369836807251)
     | > align_error: 0.583111584186554  (0.6212077468633652)

   --> STEP: 11
     | > decoder_loss: 0.4576147198677063  (0.44576911221851)
     | > postnet_loss: 0.31657132506370544  (0.3138552958315069)
     | > stopnet_loss: 0.005944156087934971  (0.007626672402362932)
     | > loss: 0.19949066638946533  (0.1975327730178833)
     | > align_error: 0.594524621963501  (0.6187820082361047)

   --> STEP: 12
     | > decoder_loss: 0.45398369431495667  (0.44645366072654724)
     | > postnet_loss: 0.3100331723690033  (0.31353678554296494)
     | > stopnet_loss: 0.007876508869230747  (0.00764749210793525)
     | > loss: 0.19888073205947876  (0.19764510293801626)
     | > align_error: 0.5868842601776123  (0.6161238625645636)

   --> STEP: 13
     | > decoder_loss: 0.44431906938552856  (0.4462894613926227)
     | > postnet_loss: 0.31056663393974304  (0.3133083123427171)
     | > stopnet_loss: 0.005303730722516775  (0.007467202770595367)
     | > loss: 0.19402514398097992  (0.19736664455670577)
     | > align_error: 0.5843496918678284  (0.6136796955878917)

   --> STEP: 14
     | > decoder_loss: 0.4553149342536926  (0.4469341380255563)
     | > postnet_loss: 0.31396716833114624  (0.31335537348474773)
     | > stopnet_loss: 0.004938630387187004  (0.007286590457494769)
     | > loss: 0.19725915789604187  (0.1973589669380869)
     | > align_error: 0.5542374551296234  (0.609433821269444)

   --> STEP: 15
     | > decoder_loss: 0.4532746374607086  (0.44735683798789977)
     | > postnet_loss: 0.3138410747051239  (0.31338775356610615)
     | > stopnet_loss: 0.005037552211433649  (0.007136654574424028)
     | > loss: 0.19681647419929504  (0.1973228007555008)
     | > align_error: 0.5882440209388733  (0.6080211679140727)

   --> STEP: 16
     | > decoder_loss: 0.4543367624282837  (0.4477930832654238)
     | > postnet_loss: 0.30817973613739014  (0.3130622524768114)
     | > stopnet_loss: 0.005300519522279501  (0.007021896133664995)
     | > loss: 0.1959296464920044  (0.19723572861403227)
     | > align_error: 0.6050890684127808  (0.6078379116952419)

   --> STEP: 17
     | > decoder_loss: 0.46038708090782166  (0.44853390665615306)
     | > postnet_loss: 0.31637924909591675  (0.3132573699249941)
     | > stopnet_loss: 0.004788474179804325  (0.006890518371673191)
     | > loss: 0.19898004829883575  (0.19733833565431483)
     | > align_error: 0.5580435991287231  (0.6049088344854467)

   --> STEP: 18
     | > decoder_loss: 0.4549131691455841  (0.4488883101277881)
     | > postnet_loss: 0.30862003564834595  (0.31299974024295807)
     | > stopnet_loss: 0.005257787648588419  (0.0067998111092795925)
     | > loss: 0.1961410939693451  (0.19727182222737205)
     | > align_error: 0.603638768196106  (0.60483827524715)

   --> STEP: 19
     | > decoder_loss: 0.4499545097351074  (0.4489444258965944)
     | > postnet_loss: 0.3068031668663025  (0.31267360480208145)
     | > stopnet_loss: 0.004706303123384714  (0.00668962647844302)
     | > loss: 0.19389572739601135  (0.1970941330257215)
     | > align_error: 0.5985925793647766  (0.6045095544112357)

   --> STEP: 20
     | > decoder_loss: 0.4487260580062866  (0.448933507502079)
     | > postnet_loss: 0.3046799600124359  (0.31227392256259917)
     | > stopnet_loss: 0.004494700115174055  (0.006579880160279572)
     | > loss: 0.19284620881080627  (0.19688173681497576)
     | > align_error: 0.6226640939712524  (0.6054172813892366)

   --> STEP: 21
     | > decoder_loss: 0.4454672038555145  (0.44876844542367117)
     | > postnet_loss: 0.30296581983566284  (0.31183067957560223)
     | > stopnet_loss: 0.003964956849813461  (0.006455360002638329)
     | > loss: 0.1910732090473175  (0.19660514025461107)
     | > align_error: 0.5594671964645386  (0.6032291821071081)

   --> STEP: 22
     | > decoder_loss: 0.44689443707466125  (0.4486832632259889)
     | > postnet_loss: 0.3055347204208374  (0.311544499614022)
     | > stopnet_loss: 0.004545076750218868  (0.006368528945710172)
     | > loss: 0.1926523596048355  (0.19642546840689398)
     | > align_error: 0.6245903372764587  (0.604200143705715)

   --> STEP: 23
     | > decoder_loss: 0.42161825299263  (0.4475065236506255)
     | > postnet_loss: 0.29395565390586853  (0.31077976719192835)
     | > stopnet_loss: 0.004456569906324148  (0.006285400291823823)
     | > loss: 0.18335004150867462  (0.19585697158523227)
     | > align_error: 0.5667937397956848  (0.6025737783183224)

   --> STEP: 24
     | > decoder_loss: 0.4567401111125946  (0.4478912564615409)
     | > postnet_loss: 0.3104402720928192  (0.3107656215627988)
     | > stopnet_loss: 0.0044000218622386456  (0.006206842857257773)
     | > loss: 0.1961951106786728  (0.19587106071412563)
     | > align_error: 0.5792159140110016  (0.601600533972184)

   --> STEP: 25
     | > decoder_loss: 0.4554661214351654  (0.4481942510604858)
     | > postnet_loss: 0.3075043261051178  (0.31063516974449157)
     | > stopnet_loss: 0.003690594108775258  (0.006106192907318473)
     | > loss: 0.19443321228027344  (0.19581354677677154)
     | > align_error: 0.5575616359710693  (0.5998389780521394)

   --> STEP: 26
     | > decoder_loss: 0.43041643500328064  (0.4475104889044395)
     | > postnet_loss: 0.2958318293094635  (0.3100658104969905)
     | > stopnet_loss: 0.004319956060498953  (0.006037491490133107)
     | > loss: 0.18588201701641083  (0.19543156486291152)
     | > align_error: 0.5464920401573181  (0.5977871727484924)

   --> STEP: 27
     | > decoder_loss: 0.42653176188468933  (0.4467334990148191)
     | > postnet_loss: 0.2907108664512634  (0.3093489607175191)
     | > stopnet_loss: 0.0036306376568973064  (0.005948348755568818)
     | > loss: 0.1829412877559662  (0.19496896200709873)
     | > align_error: 0.5400164425373077  (0.595647516074004)

   --> STEP: 28
     | > decoder_loss: 0.4331989884376526  (0.4462501236370632)
     | > postnet_loss: 0.29562291502952576  (0.3088587448000908)
     | > stopnet_loss: 0.003932254388928413  (0.0058763453853316605)
     | > loss: 0.18613772094249725  (0.1946535605405058)
     | > align_error: 0.5660846829414368  (0.5945917006049838)

   --> STEP: 29
     | > decoder_loss: 0.42786258459091187  (0.4456160705665062)
     | > postnet_loss: 0.29193004965782166  (0.3082749966917367)
     | > stopnet_loss: 0.0035406702663749456  (0.005795804863988325)
     | > loss: 0.18348881602287292  (0.19426856935024261)
     | > align_error: 0.5400388538837433  (0.5927105679594237)

   --> STEP: 30
     | > decoder_loss: 0.42897871136665344  (0.4450614919265111)
     | > postnet_loss: 0.2930866479873657  (0.307768718401591)
     | > stopnet_loss: 0.002793091582134366  (0.0056957144212598605)
     | > loss: 0.1833094209432602  (0.1939032644033432)
     | > align_error: 0.5328697264194489  (0.5907158732414246)

   --> STEP: 31
     | > decoder_loss: 0.42567211389541626  (0.44443602811905647)
     | > postnet_loss: 0.292034775018692  (0.30726117184085233)
     | > stopnet_loss: 0.0036814045161008835  (0.005630736682383764)
     | > loss: 0.1831081360578537  (0.19355503445671451)
     | > align_error: 0.5550113320350647  (0.589564113847671)

   --> STEP: 32
     | > decoder_loss: 0.43763330578804016  (0.4442234430462122)
     | > postnet_loss: 0.2979448437690735  (0.3069700365886092)
     | > stopnet_loss: 0.0038126236759126186  (0.005573920650931541)
     | > loss: 0.18770717084407806  (0.19337228871881962)
     | > align_error: 0.5303919017314911  (0.5877149822190404)

   --> STEP: 33
     | > decoder_loss: 0.4335472285747528  (0.4438999213955619)
     | > postnet_loss: 0.29559776186943054  (0.30662542220317957)
     | > stopnet_loss: 0.004015042912214994  (0.005526681931576494)
     | > loss: 0.18630129098892212  (0.1931580160603379)
     | > align_error: 0.5454453825950623  (0.586434085260738)

   --> STEP: 34
     | > decoder_loss: 0.4396621584892273  (0.4437752813100815)
     | > postnet_loss: 0.29714688658714294  (0.3063466417438844)
     | > stopnet_loss: 0.003269531764090061  (0.00546029516194454)
     | > loss: 0.18747179210186005  (0.19299077417920618)
     | > align_error: 0.5632225275039673  (0.5857513923855389)

   --> STEP: 35
     | > decoder_loss: 0.4364464581012726  (0.4435658863612584)
     | > postnet_loss: 0.29577451944351196  (0.3060445811067309)
     | > stopnet_loss: 0.003473797347396612  (0.005403538081528885)
     | > loss: 0.18652905523777008  (0.19280615363802228)
     | > align_error: 0.5327175855636597  (0.5842361407620567)

   --> STEP: 36
     | > decoder_loss: 0.4425542950630188  (0.44353778660297394)
     | > postnet_loss: 0.30035287141799927  (0.30588647805982166)
     | > stopnet_loss: 0.0036302206572145224  (0.005354279264186818)
     | > loss: 0.18935701251029968  (0.19271034416225222)
     | > align_error: 0.6332782208919525  (0.5855984207656648)

   --> STEP: 37
     | > decoder_loss: 0.4354082942008972  (0.443318070592107)
     | > postnet_loss: 0.2968823313713074  (0.30564312274391586)
     | > stopnet_loss: 0.0035328473895788193  (0.005305051375683899)
     | > loss: 0.18660549819469452  (0.1925453483252912)
     | > align_error: 0.5181904435157776  (0.5837765835426949)

   --> STEP: 38
     | > decoder_loss: 0.422507107257843  (0.44277041366225794)
     | > postnet_loss: 0.28956443071365356  (0.30521999926943527)
     | > stopnet_loss: 0.00312560866586864  (0.005247697620162445)
     | > loss: 0.18114349246025085  (0.1922452994867375)
     | > align_error: 0.5510826110839844  (0.5829162158464131)

   --> STEP: 39
     | > decoder_loss: 0.4381244480609894  (0.4426512863391485)
     | > postnet_loss: 0.29989850521087646  (0.3050835507038312)
     | > stopnet_loss: 0.0034515445586293936  (0.005201642413456469)
     | > loss: 0.1879572719335556  (0.19213535006229693)
     | > align_error: 0.545525848865509  (0.5819574884879284)

   --> STEP: 40
     | > decoder_loss: 0.4352906346321106  (0.44246727004647257)
     | > postnet_loss: 0.29845818877220154  (0.30491791665554047)
     | > stopnet_loss: 0.0030080415308475494  (0.0051468023913912465)
     | > loss: 0.1864452362060547  (0.19199309721589086)
     | > align_error: 0.5833662450313568  (0.5819927074015141)

   --> STEP: 41
     | > decoder_loss: 0.4260757565498352  (0.44206747703435945)
     | > postnet_loss: 0.2908823490142822  (0.304575585737461)
     | > stopnet_loss: 0.00370864593423903  (0.005111725404631436)
     | > loss: 0.18294817209243774  (0.19177248928605053)
     | > align_error: 0.5026133954524994  (0.5800566266222698)

   --> STEP: 42
     | > decoder_loss: 0.43086978793144226  (0.4418008653890519)
     | > postnet_loss: 0.2931932806968689  (0.30430457847458975)
     | > stopnet_loss: 0.0032561810221523046  (0.005067545776477171)
     | > loss: 0.1842719465494156  (0.1915939049351783)
     | > align_error: 0.5789616107940674  (0.5800305548168364)

   --> STEP: 43
     | > decoder_loss: 0.43014612793922424  (0.44152982498324195)
     | > postnet_loss: 0.2920883297920227  (0.30402047966801843)
     | > stopnet_loss: 0.002926658606156707  (0.005017757702748788)
     | > loss: 0.18348528444766998  (0.19140533236570137)
     | > align_error: 0.5511245429515839  (0.5793583219827607)

   --> STEP: 44
     | > decoder_loss: 0.44826725125312805  (0.44168294830755755)
     | > postnet_loss: 0.3029611110687256  (0.3039964031089436)
     | > stopnet_loss: 0.002645817818120122  (0.0049638499780981366)
     | > loss: 0.19045290350914001  (0.19138368625532498)
     | > align_error: 0.5503027439117432  (0.5786979679356921)

   --> STEP: 45
     | > decoder_loss: 0.4401860237121582  (0.4416496833165487)
     | > postnet_loss: 0.3014630377292633  (0.30394010610050626)
     | > stopnet_loss: 0.0032427962869405746  (0.004925604340516857)
     | > loss: 0.1886550486087799  (0.19132304986317952)
     | > align_error: 0.5518985092639923  (0.5781024244096542)

   --> STEP: 46
     | > decoder_loss: 0.43102797865867615  (0.44141877669355145)
     | > postnet_loss: 0.29280728101730347  (0.3036980881639149)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3959654930866126 (+0.05321248733636108)
     | > avg_decoder_loss: 0.4374917005047654 (+0.0006575719876723007)
     | > avg_postnet_loss: 0.30047600106759514 (-0.00018974777423963474)
     | > avg_stopnet_loss: 0.004334860463683124 (+1.596293948364757e-05)
     | > avg_loss: 0.18882678471731418 (+0.0001329183578491211)
     | > avg_align_error: 0.5709324528773626 (+0.00013907253742218018)


 > EPOCH: 152/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 19:33:49)

   --> TIME: 2025-12-28 19:34:24 -- STEP: 23/150 -- GLOBAL_STEP: 22975
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4715893566608429  (0.4644560904606529)
     | > postnet_loss: 0.3969844579696655  (0.3928088455096535)
     | > stopnet_loss: 0.006982819177210331  (0.009924233729100746)
     | > loss: 0.22412626445293427  (0.2242404676002005)
     | > align_error: 0.640577495098114  (0.671730303246042)
     | > grad_norm: tensor(0.3770, device='cuda:0')  (tensor(0.2851, device='cuda:0'))
     | > step_time: 0.8367  (0.641139673150104)
     | > loader_time: 0.8855  (0.8539472662884257)


   --> TIME: 2025-12-28 19:35:17 -- STEP: 48/150 -- GLOBAL_STEP: 23000
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.478475958108902  (0.4719059504568577)
     | > postnet_loss: 0.39413556456565857  (0.3952852878719568)
     | > stopnet_loss: 0.004469105042517185  (0.007632251285637419)
     | > loss: 0.22262199223041534  (0.22443006125589213)
     | > align_error: 0.6212540864944458  (0.6494767988721529)
     | > grad_norm: tensor(0.2138, device='cuda:0')  (tensor(0.2766, device='cuda:0'))
     | > step_time: 1.3167  (0.8844172408183416)
     | > loader_time: 1.0516  (0.9297249515851339)


   --> TIME: 2025-12-28 19:36:24 -- STEP: 73/150 -- GLOBAL_STEP: 23025
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48184990882873535  (0.47521196734415344)
     | > postnet_loss: 0.3927067518234253  (0.3951856653167777)
     | > stopnet_loss: 0.0037876307033002377  (0.006466498930160314)
     | > loss: 0.22242680191993713  (0.22406590760570683)
     | > align_error: 0.6470099687576294  (0.6366160732426055)
     | > grad_norm: tensor(0.3141, device='cuda:0')  (tensor(0.2494, device='cuda:0'))
     | > step_time: 1.6374  (1.075735520010125)
     | > loader_time: 1.416  (1.0394651465219995)


   --> TIME: 2025-12-28 19:37:45 -- STEP: 98/150 -- GLOBAL_STEP: 23050
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48452746868133545  (0.4766529053449631)
     | > postnet_loss: 0.39472493529319763  (0.3945827143532889)
     | > stopnet_loss: 0.0039811632595956326  (0.005758829165383109)
     | > loss: 0.22379426658153534  (0.22356773411132852)
     | > align_error: 0.606980562210083  (0.6314129251606612)
     | > grad_norm: tensor(0.1308, device='cuda:0')  (tensor(0.2316, device='cuda:0'))
     | > step_time: 1.7869  (1.2314440133620284)
     | > loader_time: 1.7489  (1.165274651683107)


   --> TIME: 2025-12-28 19:39:18 -- STEP: 123/150 -- GLOBAL_STEP: 23075
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48121756315231323  (0.47786671625889415)
     | > postnet_loss: 0.3908281624317169  (0.3941733064205666)
     | > stopnet_loss: 0.003255943302065134  (0.005260965531328466)
     | > loss: 0.22126738727092743  (0.22327097208519292)
     | > align_error: 0.6027295589447021  (0.6270182769957597)
     | > grad_norm: tensor(0.3563, device='cuda:0')  (tensor(0.2255, device='cuda:0'))
     | > step_time: 2.0872  (1.3629857020649485)
     | > loader_time: 1.738  (1.3001612841598391)


   --> TIME: 2025-12-28 19:41:01 -- STEP: 148/150 -- GLOBAL_STEP: 23100
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4953519403934479  (0.4793448887161306)
     | > postnet_loss: 0.39845356345176697  (0.3940707749208888)
     | > stopnet_loss: 0.002753784414380789  (0.004888425397095145)
     | > loss: 0.22620515525341034  (0.22324234176729177)
     | > align_error: 0.6120615601539612  (0.6235290298590791)
     | > grad_norm: tensor(0.1773, device='cuda:0')  (tensor(0.2198, device='cuda:0'))
     | > step_time: 2.8884  (1.5083783655553253)
     | > loader_time: 2.182  (1.3996038114702383)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45825526118278503  (0.45825526118278503)
     | > postnet_loss: 0.3330552577972412  (0.3330552577972412)
     | > stopnet_loss: 0.012088846415281296  (0.012088846415281296)
     | > loss: 0.20991648733615875  (0.20991648733615875)
     | > align_error: 0.7190589606761932  (0.7190589606761932)

   --> STEP: 1
     | > decoder_loss: 0.44152596592903137  (0.44152596592903137)
     | > postnet_loss: 0.3221101760864258  (0.3221101760864258)
     | > stopnet_loss: 0.009686565957963467  (0.009686565957963467)
     | > loss: 0.20059558749198914  (0.20059558749198914)
     | > align_error: 0.6596193611621857  (0.6596193611621857)

   --> STEP: 2
     | > decoder_loss: 0.4362988770008087  (0.43891242146492004)
     | > postnet_loss: 0.31233805418014526  (0.3172241151332855)
     | > stopnet_loss: 0.01100374385714531  (0.010345154907554388)
     | > loss: 0.1981629878282547  (0.19937928766012192)
     | > align_error: 0.6555346548557281  (0.6575770080089569)

   --> STEP: 3
     | > decoder_loss: 0.4393365681171417  (0.43905380368232727)
     | > postnet_loss: 0.3113514184951782  (0.31526654958724976)
     | > stopnet_loss: 0.008078869432210922  (0.009589726415773233)
     | > loss: 0.1957508623600006  (0.19816981256008148)
     | > align_error: 0.7348368167877197  (0.6833302776018778)

   --> STEP: 4
     | > decoder_loss: 0.44459906220436096  (0.4404401183128357)
     | > postnet_loss: 0.3197769820690155  (0.3163941577076912)
     | > stopnet_loss: 0.008168758824467659  (0.00923448451794684)
     | > loss: 0.19926276803016663  (0.19844305142760277)
     | > align_error: 0.603037416934967  (0.6632570624351501)

   --> STEP: 5
     | > decoder_loss: 0.4263353943824768  (0.43761917352676394)
     | > postnet_loss: 0.3018805980682373  (0.3134914457798004)
     | > stopnet_loss: 0.008007530122995377  (0.008989093638956547)
     | > loss: 0.1900615245103836  (0.19676674604415895)
     | > align_error: 0.6414904594421387  (0.6589037418365479)

   --> STEP: 6
     | > decoder_loss: 0.4441579580307007  (0.43870897094408673)
     | > postnet_loss: 0.3145739734172821  (0.31367186705271405)
     | > stopnet_loss: 0.007195104844868183  (0.008690095506608486)
     | > loss: 0.1968780905008316  (0.19678530345360437)
     | > align_error: 0.5939516127109528  (0.648078386982282)

   --> STEP: 7
     | > decoder_loss: 0.4532943367958069  (0.4407925946371896)
     | > postnet_loss: 0.3133623003959656  (0.3136276432446071)
     | > stopnet_loss: 0.006144257262349129  (0.008326404328857149)
     | > loss: 0.1978084146976471  (0.19693146220275334)
     | > align_error: 0.5789943337440491  (0.6382092365196773)

   --> STEP: 8
     | > decoder_loss: 0.4497818946838379  (0.44191625714302063)
     | > postnet_loss: 0.3152267038822174  (0.3138275258243084)
     | > stopnet_loss: 0.007194366306066513  (0.00818489957600832)
     | > loss: 0.19844651222229004  (0.19712084345519543)
     | > align_error: 0.5749321579933167  (0.6302996017038822)

   --> STEP: 9
     | > decoder_loss: 0.4481353163719177  (0.4426072637240092)
     | > postnet_loss: 0.3155958652496338  (0.3140240079826779)
     | > stopnet_loss: 0.006592880934476852  (0.008008008615838157)
     | > loss: 0.19752568006515503  (0.1971658253007465)
     | > align_error: 0.5910410284996033  (0.6259375380145179)

   --> STEP: 10
     | > decoder_loss: 0.47330552339553833  (0.4456770896911621)
     | > postnet_loss: 0.32959234714508057  (0.31558084189891816)
     | > stopnet_loss: 0.005559655372053385  (0.007763173291459679)
     | > loss: 0.20628412067890167  (0.19807765483856202)
     | > align_error: 0.5836541056632996  (0.621709194779396)

   --> STEP: 11
     | > decoder_loss: 0.45939376950263977  (0.4469240605831146)
     | > postnet_loss: 0.3191136419773102  (0.3159020055424083)
     | > stopnet_loss: 0.005854276940226555  (0.007589637259529395)
     | > loss: 0.2004811316728592  (0.19829615273258902)
     | > align_error: 0.5950950384140015  (0.6192897260189056)

   --> STEP: 12
     | > decoder_loss: 0.45576080679893494  (0.44766045610109967)
     | > postnet_loss: 0.31268975138664246  (0.3156343176960945)
     | > stopnet_loss: 0.00785915832966566  (0.007612097348707418)
     | > loss: 0.19997179508209229  (0.19843578959504762)
     | > align_error: 0.5874178409576416  (0.6166337355971336)

   --> STEP: 13
     | > decoder_loss: 0.44411665201187134  (0.4473878557865436)
     | > postnet_loss: 0.31167638301849365  (0.3153298611824329)
     | > stopnet_loss: 0.005258094985038042  (0.007431020243809774)
     | > loss: 0.1942063570022583  (0.19811044862637153)
     | > align_error: 0.5852717161178589  (0.6142212725602664)

   --> STEP: 14
     | > decoder_loss: 0.45475053787231445  (0.44791376164981295)
     | > postnet_loss: 0.314583957195282  (0.31527658232620787)
     | > stopnet_loss: 0.00488764513283968  (0.007249350593026195)
     | > loss: 0.19722126424312592  (0.1980469354561397)
     | > align_error: 0.555016964673996  (0.6099923934255328)

   --> STEP: 15
     | > decoder_loss: 0.4518899917602539  (0.4481788436571757)
     | > postnet_loss: 0.31388017535209656  (0.31518348852793376)
     | > stopnet_loss: 0.00498601607978344  (0.007098461625476679)
     | > loss: 0.1964285671710968  (0.19793904423713685)
     | > align_error: 0.5886147618293762  (0.6085672179857889)

   --> STEP: 16
     | > decoder_loss: 0.45250219106674194  (0.4484490528702736)
     | > postnet_loss: 0.307894229888916  (0.31472790986299515)
     | > stopnet_loss: 0.005243208725005388  (0.006982508319197223)
     | > loss: 0.1953423172235489  (0.1977767487987876)
     | > align_error: 0.6056552231311798  (0.6083852183073759)

   --> STEP: 17
     | > decoder_loss: 0.4597408175468445  (0.44911327432183656)
     | > postnet_loss: 0.3167183995246887  (0.3148449974901536)
     | > stopnet_loss: 0.004763311706483364  (0.00685196734197876)
     | > loss: 0.19887810945510864  (0.19784153471974766)
     | > align_error: 0.558792769908905  (0.6054680154604071)

   --> STEP: 18
     | > decoder_loss: 0.4530870020389557  (0.4493340369727876)
     | > postnet_loss: 0.3081449866294861  (0.314472774664561)
     | > stopnet_loss: 0.005195651203393936  (0.006759949778724048)
     | > loss: 0.19550365209579468  (0.19771165235175026)
     | > align_error: 0.6041149497032166  (0.6053928451405631)

   --> STEP: 19
     | > decoder_loss: 0.45115941762924194  (0.44943010963891683)
     | > postnet_loss: 0.30848437547683716  (0.3141575957599439)
     | > stopnet_loss: 0.004681865219026804  (0.006650576907161035)
     | > loss: 0.19459281861782074  (0.19754750320785924)
     | > align_error: 0.5992152690887451  (0.6050677095588884)

   --> STEP: 20
     | > decoder_loss: 0.44706404209136963  (0.44931180626153944)
     | > postnet_loss: 0.3039778470993042  (0.31364860832691194)
     | > stopnet_loss: 0.004445758182555437  (0.0065403359709307555)
     | > loss: 0.1922062337398529  (0.1972804397344589)
     | > align_error: 0.6231293678283691  (0.6059707924723625)

   --> STEP: 21
     | > decoder_loss: 0.4462936818599701  (0.4491680860519409)
     | > postnet_loss: 0.30431705713272095  (0.31320424874623615)
     | > stopnet_loss: 0.003939127549529076  (0.006416468903244961)
     | > loss: 0.1915917992591858  (0.19700955209277926)
     | > align_error: 0.5599526166915894  (0.6037794507685161)

   --> STEP: 22
     | > decoder_loss: 0.44753849506378174  (0.4490940137342973)
     | > postnet_loss: 0.30670061707496643  (0.3129086291248148)
     | > stopnet_loss: 0.0047674160450696945  (0.006341511955146085)
     | > loss: 0.1933271884918213  (0.19684217192909934)
     | > align_error: 0.6255737543106079  (0.6047701009295203)

   --> STEP: 23
     | > decoder_loss: 0.4208052456378937  (0.44786406729532324)
     | > postnet_loss: 0.29395532608032227  (0.3120845724707064)
     | > stopnet_loss: 0.004422171972692013  (0.00625806239069156)
     | > loss: 0.18311230838298798  (0.19624522134013797)
     | > align_error: 0.5672901272773743  (0.6031405368576879)

   --> STEP: 24
     | > decoder_loss: 0.45480671525001526  (0.4481533442934354)
     | > postnet_loss: 0.30962809920310974  (0.3119822194178899)
     | > stopnet_loss: 0.004387684166431427  (0.006180129964680721)
     | > loss: 0.19549638032913208  (0.19621401963134608)
     | > align_error: 0.5798484683036804  (0.6021700340012709)

   --> STEP: 25
     | > decoder_loss: 0.4535646438598633  (0.4483697962760925)
     | > postnet_loss: 0.30664440989494324  (0.31176870703697207)
     | > stopnet_loss: 0.003633504267781973  (0.006078264936804772)
     | > loss: 0.19368577003479004  (0.19611288964748383)
     | > align_error: 0.5581774115562439  (0.6004103291034698)

   --> STEP: 26
     | > decoder_loss: 0.4292166829109192  (0.4476331380697397)
     | > postnet_loss: 0.29553815722465515  (0.3111444551211137)
     | > stopnet_loss: 0.004304156173020601  (0.006010029984351534)
     | > loss: 0.1854928582906723  (0.19570442690299109)
     | > align_error: 0.5469675362110138  (0.5983548370691445)

   --> STEP: 27
     | > decoder_loss: 0.42604249715805054  (0.4468334847026401)
     | > postnet_loss: 0.2906668782234192  (0.31038602634712503)
     | > stopnet_loss: 0.003872378496453166  (0.005930857707021965)
     | > loss: 0.18304972350597382  (0.19523573418458304)
     | > align_error: 0.5413578748703003  (0.5962438384691873)

   --> STEP: 28
     | > decoder_loss: 0.43242713809013367  (0.446318972323622)
     | > postnet_loss: 0.2955656945705414  (0.3098567287836756)
     | > stopnet_loss: 0.003909311722964048  (0.005858659636162754)
     | > loss: 0.1859075129032135  (0.19490258342453412)
     | > align_error: 0.5667058527469635  (0.5951889104076793)

   --> STEP: 29
     | > decoder_loss: 0.42723849415779114  (0.44566102480066233)
     | > postnet_loss: 0.29216259717941284  (0.3092465863145631)
     | > stopnet_loss: 0.0035396593157202005  (0.005778694107871631)
     | > loss: 0.18338994681835175  (0.1945055959553554)
     | > align_error: 0.5408261120319366  (0.5933143311533433)

   --> STEP: 30
     | > decoder_loss: 0.4279462695121765  (0.4450705329577128)
     | > postnet_loss: 0.29296037554740906  (0.3087037126223246)
     | > stopnet_loss: 0.0027386294677853584  (0.005677358619868756)
     | > loss: 0.18296527862548828  (0.19412091871102652)
     | > align_error: 0.5334056615829468  (0.5913173755009968)

   --> STEP: 31
     | > decoder_loss: 0.4233610928058624  (0.4443702284366854)
     | > postnet_loss: 0.2908284068107605  (0.30812708985420967)
     | > stopnet_loss: 0.0036840883549302816  (0.005613059579064289)
     | > loss: 0.18223147094249725  (0.19373738813784816)
     | > align_error: 0.5555460453033447  (0.5901634616236532)

   --> STEP: 32
     | > decoder_loss: 0.43628227710723877  (0.44411747995764017)
     | > postnet_loss: 0.29762205481529236  (0.3077988075092435)
     | > stopnet_loss: 0.003780303057283163  (0.005555785937758628)
     | > loss: 0.18725639581680298  (0.19353485712781549)
     | > align_error: 0.5311804413795471  (0.5883202422410249)

   --> STEP: 33
     | > decoder_loss: 0.43167921900749207  (0.4437405629591508)
     | > postnet_loss: 0.2946246564388275  (0.30739959081013996)
     | > stopnet_loss: 0.00400445144623518  (0.005508775801651857)
     | > loss: 0.18558041751384735  (0.19329381350314978)
     | > align_error: 0.5462097525596619  (0.587044166796135)

   --> STEP: 34
     | > decoder_loss: 0.4380376636981964  (0.4435728306279463)
     | > postnet_loss: 0.296505868434906  (0.3070791872108684)
     | > stopnet_loss: 0.0032312923576682806  (0.00544179099447587)
     | > loss: 0.18686717748641968  (0.19310479479677536)
     | > align_error: 0.5639288425445557  (0.5863643043181475)

   --> STEP: 35
     | > decoder_loss: 0.4350452423095703  (0.44332918524742126)
     | > postnet_loss: 0.29536864161491394  (0.30674460019384114)
     | > stopnet_loss: 0.0034737635869532824  (0.005385561639975224)
     | > loss: 0.18607723712921143  (0.19290400743484498)
     | > align_error: 0.5332683324813843  (0.5848472765513828)

   --> STEP: 36
     | > decoder_loss: 0.4413509666919708  (0.44327423473199207)
     | > postnet_loss: 0.29998907446861267  (0.3065569467014737)
     | > stopnet_loss: 0.0036154433619230986  (0.005336391687807109)
     | > loss: 0.18895044922828674  (0.1927941863735517)
     | > align_error: 0.6339377760887146  (0.5862109015385308)

   --> STEP: 37
     | > decoder_loss: 0.4345468580722809  (0.443038359687135)
     | > postnet_loss: 0.2966555655002594  (0.3062893418041436)
     | > stopnet_loss: 0.0035221658181399107  (0.005287358556194483)
     | > loss: 0.18632277846336365  (0.19261928345706011)
     | > align_error: 0.5187867879867554  (0.5843886281992936)

   --> STEP: 38
     | > decoder_loss: 0.4218292534351349  (0.44248022531208236)
     | > postnet_loss: 0.2893867790699005  (0.3058445375216635)
     | > stopnet_loss: 0.0031022457405924797  (0.005229855587362851)
     | > loss: 0.1809062510728836  (0.1923110457627397)
     | > align_error: 0.551811158657074  (0.5835313263692352)

   --> STEP: 39
     | > decoder_loss: 0.43714192509651184  (0.44234334581937546)
     | > postnet_loss: 0.2998451888561249  (0.30569070806870097)
     | > stopnet_loss: 0.003438519313931465  (0.0051839238880440975)
     | > loss: 0.1876852959394455  (0.19219243679291162)
     | > align_error: 0.5462522208690643  (0.5825754518692309)

   --> STEP: 40
     | > decoder_loss: 0.4346839487552643  (0.4421518608927727)
     | > postnet_loss: 0.2985170781612396  (0.30551136732101447)
     | > stopnet_loss: 0.002988845342770219  (0.005129046924412251)
     | > loss: 0.18628910183906555  (0.19204485341906546)
     | > align_error: 0.5841242671012878  (0.5826141722500323)

   --> STEP: 41
     | > decoder_loss: 0.42608851194381714  (0.44176007189401767)
     | > postnet_loss: 0.29122480750083923  (0.30516291464247364)
     | > stopnet_loss: 0.003706915769726038  (0.005094360798688196)
     | > loss: 0.1830352395772934  (0.19182510673999786)
     | > align_error: 0.5036025047302246  (0.5806870584080858)

   --> STEP: 42
     | > decoder_loss: 0.4292542040348053  (0.44146231313546497)
     | > postnet_loss: 0.292428582906723  (0.3048597162678129)
     | > stopnet_loss: 0.003251094138249755  (0.005050473497249186)
     | > loss: 0.18367178738117218  (0.19163098008859725)
     | > align_error: 0.5798565745353699  (0.5806672849825449)

   --> STEP: 43
     | > decoder_loss: 0.42877814173698425  (0.4411673324052678)
     | > postnet_loss: 0.2914573848247528  (0.3045480341412301)
     | > stopnet_loss: 0.0028739378321915865  (0.004999856388759475)
     | > loss: 0.18293282389640808  (0.19142869738645332)
     | > align_error: 0.5520672798156738  (0.5800021685833154)

   --> STEP: 44
     | > decoder_loss: 0.44668227434158325  (0.4412926719947295)
     | > postnet_loss: 0.30236268043518066  (0.30449836701154714)
     | > stopnet_loss: 0.002620808547362685  (0.0049457871196368205)
     | > loss: 0.1898820400238037  (0.19139354608275674)
     | > align_error: 0.5512896180152893  (0.5793496106158603)

   --> STEP: 45
     | > decoder_loss: 0.4394172132015228  (0.4412509951326582)
     | > postnet_loss: 0.3011111617088318  (0.3044230957825979)
     | > stopnet_loss: 0.0032429329585283995  (0.004907945916056634)
     | > loss: 0.18837502598762512  (0.19132646785842047)
     | > align_error: 0.5526289939880371  (0.578755819135242)

   --> STEP: 46
     | > decoder_loss: 0.4304352104663849  (0.4410158693790436)
     | > postnet_loss: 0.2928418815135956  (0.3041713302550109)
     | > stopnet_loss: 0.0031601188238710165  (0.0048699496749221634)
     | > loss: 0.18397939205169678  (0.1911667488191439)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3587907588843143 (-0.03717473420229833)
     | > avg_decoder_loss: 0.4371504770083861 (-0.00034122349637927263)
     | > avg_postnet_loss: 0.30091474092367926 (+0.0004387398560841138)
     | > avg_stopnet_loss: 0.004320832466791299 (-1.4027996891824955e-05)
     | > avg_loss: 0.18883713650884051 (+1.0351791526336251e-05)
     | > avg_align_error: 0.571692299210664 (+0.000759846333301395)


 > EPOCH: 153/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 19:43:08)

   --> TIME: 2025-12-28 19:43:41 -- STEP: 22/150 -- GLOBAL_STEP: 23125
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4729699194431305  (0.4640586782585491)
     | > postnet_loss: 0.39627015590667725  (0.39251955530860205)
     | > stopnet_loss: 0.006697026081383228  (0.010054808893156323)
     | > loss: 0.2240070402622223  (0.22419936684044925)
     | > align_error: 0.631912887096405  (0.6734633459286257)
     | > grad_norm: tensor(0.1996, device='cuda:0')  (tensor(0.2937, device='cuda:0'))
     | > step_time: 0.76  (0.621858065778559)
     | > loader_time: 0.9016  (0.844284176826477)


   --> TIME: 2025-12-28 19:44:33 -- STEP: 47/150 -- GLOBAL_STEP: 23150
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4813583195209503  (0.4728533834853071)
     | > postnet_loss: 0.3967421054840088  (0.39597411675656097)
     | > stopnet_loss: 0.0045152828097343445  (0.007698198958755808)
     | > loss: 0.22404038906097412  (0.2249050742768227)
     | > align_error: 0.659109354019165  (0.6495397414298769)
     | > grad_norm: tensor(0.3186, device='cuda:0')  (tensor(0.3512, device='cuda:0'))
     | > step_time: 1.232  (0.8662211083351299)
     | > loader_time: 1.1156  (0.9343507492795904)


   --> TIME: 2025-12-28 19:45:41 -- STEP: 72/150 -- GLOBAL_STEP: 23175
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47793999314308167  (0.47592009521192974)
     | > postnet_loss: 0.3912278115749359  (0.39579715124434894)
     | > stopnet_loss: 0.0037686536088585854  (0.006486615085224103)
     | > loss: 0.2210606038570404  (0.22441592667665747)
     | > align_error: 0.5972431898117065  (0.6368637283643088)
     | > grad_norm: tensor(0.1455, device='cuda:0')  (tensor(0.2988, device='cuda:0'))
     | > step_time: 1.4589  (1.0682208206918504)
     | > loader_time: 1.3252  (1.0455630189842648)


   --> TIME: 2025-12-28 19:47:01 -- STEP: 97/150 -- GLOBAL_STEP: 23200
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47540155053138733  (0.4772192562363811)
     | > postnet_loss: 0.3894707262516022  (0.3950322494678891)
     | > stopnet_loss: 0.0031719421967864037  (0.005778998203729231)
     | > loss: 0.21939000487327576  (0.2238418742553475)
     | > align_error: 0.5761936008930206  (0.6320023819343336)
     | > grad_norm: tensor(0.2013, device='cuda:0')  (tensor(0.2730, device='cuda:0'))
     | > step_time: 1.9332  (1.2309052354281709)
     | > loader_time: 1.5704  (1.1638776543214149)


   --> TIME: 2025-12-28 19:48:30 -- STEP: 122/150 -- GLOBAL_STEP: 23225
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4816752076148987  (0.47849537749759485)
     | > postnet_loss: 0.3916690945625305  (0.3946709430120031)
     | > stopnet_loss: 0.0031699195969849825  (0.005275601013487235)
     | > loss: 0.2215059995651245  (0.2235671807019437)
     | > align_error: 0.5941244959831238  (0.6275251270806206)
     | > grad_norm: tensor(0.2223, device='cuda:0')  (tensor(0.2678, device='cuda:0'))
     | > step_time: 1.9767  (1.3619506320015329)
     | > loader_time: 1.6071  (1.2668027408787461)


   --> TIME: 2025-12-28 19:50:14 -- STEP: 147/150 -- GLOBAL_STEP: 23250
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4913471043109894  (0.47970972499068903)
     | > postnet_loss: 0.39461708068847656  (0.3943854835974117)
     | > stopnet_loss: 0.0025724656879901886  (0.00490593335584921)
     | > loss: 0.22406350076198578  (0.22342973501503874)
     | > align_error: 0.627865195274353  (0.6238914130090858)
     | > grad_norm: tensor(0.1724, device='cuda:0')  (tensor(0.2530, device='cuda:0'))
     | > step_time: 2.7782  (1.509065139861334)
     | > loader_time: 2.1165  (1.3861802954252074)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46000558137893677  (0.46000558137893677)
     | > postnet_loss: 0.3341470956802368  (0.3341470956802368)
     | > stopnet_loss: 0.012099585495889187  (0.012099585495889187)
     | > loss: 0.21063774824142456  (0.21063774824142456)
     | > align_error: 0.7184228897094727  (0.7184228897094727)

   --> STEP: 1
     | > decoder_loss: 0.44140881299972534  (0.44140881299972534)
     | > postnet_loss: 0.32227328419685364  (0.32227328419685364)
     | > stopnet_loss: 0.009698260575532913  (0.009698260575532913)
     | > loss: 0.20061878859996796  (0.20061878859996796)
     | > align_error: 0.6586664617061615  (0.6586664617061615)

   --> STEP: 2
     | > decoder_loss: 0.43959537148475647  (0.4405020922422409)
     | > postnet_loss: 0.31403669714927673  (0.3181549906730652)
     | > stopnet_loss: 0.010941305197775364  (0.010319782886654139)
     | > loss: 0.1993493288755417  (0.19998405873775482)
     | > align_error: 0.6551249027252197  (0.6568956822156906)

   --> STEP: 3
     | > decoder_loss: 0.44265562295913696  (0.4412199358145396)
     | > postnet_loss: 0.31357336044311523  (0.3166277805964152)
     | > stopnet_loss: 0.008092382922768593  (0.009577316232025623)
     | > loss: 0.1971496343612671  (0.1990392506122589)
     | > align_error: 0.7353124618530273  (0.6830346087614695)

   --> STEP: 4
     | > decoder_loss: 0.4446794390678406  (0.44208481162786484)
     | > postnet_loss: 0.32011139392852783  (0.31749868392944336)
     | > stopnet_loss: 0.008114410564303398  (0.009211589815095067)
     | > loss: 0.19931212067604065  (0.19910746812820435)
     | > align_error: 0.6028027534484863  (0.6629766449332237)

   --> STEP: 5
     | > decoder_loss: 0.42599722743034363  (0.4388672947883606)
     | > postnet_loss: 0.3018393814563751  (0.3143668234348297)
     | > stopnet_loss: 0.008093577809631824  (0.008987987414002419)
     | > loss: 0.19005273282527924  (0.19729652106761933)
     | > align_error: 0.6408912539482117  (0.6585595667362213)

   --> STEP: 6
     | > decoder_loss: 0.4449262320995331  (0.43987711767355603)
     | > postnet_loss: 0.3149760663509369  (0.3144683639208476)
     | > stopnet_loss: 0.007183167617768049  (0.008687184114630023)
     | > loss: 0.19715873897075653  (0.19727355738480887)
     | > align_error: 0.5935077667236328  (0.6477176000674566)

   --> STEP: 7
     | > decoder_loss: 0.4561746120452881  (0.44220533115523203)
     | > postnet_loss: 0.3152462840080261  (0.3145794953618731)
     | > stopnet_loss: 0.00615907134488225  (0.0083260251475232)
     | > loss: 0.19901429116725922  (0.19752223363944463)
     | > align_error: 0.5785563886165619  (0.637837427003043)

   --> STEP: 8
     | > decoder_loss: 0.45023491978645325  (0.4432090297341347)
     | > postnet_loss: 0.31554412841796875  (0.31470007449388504)
     | > stopnet_loss: 0.007249824237078428  (0.008191500033717602)
     | > loss: 0.19869457185268402  (0.19766877591609955)
     | > align_error: 0.5745265483856201  (0.6299235671758652)

   --> STEP: 9
     | > decoder_loss: 0.45032763481140137  (0.443999985853831)
     | > postnet_loss: 0.3170119822025299  (0.3149569531281789)
     | > stopnet_loss: 0.006555177271366119  (0.008009686393456327)
     | > loss: 0.19839006662368774  (0.1977489193280538)
     | > align_error: 0.5907557010650635  (0.6255715820524428)

   --> STEP: 10
     | > decoder_loss: 0.4730398654937744  (0.4469039738178253)
     | > postnet_loss: 0.3295905292034149  (0.31642031073570254)
     | > stopnet_loss: 0.00550994835793972  (0.007759712589904666)
     | > loss: 0.2061675488948822  (0.19859078228473664)
     | > align_error: 0.584552526473999  (0.6214696764945984)

   --> STEP: 11
     | > decoder_loss: 0.45864057540893555  (0.44797093759883533)
     | > postnet_loss: 0.3188320994377136  (0.31663956425406714)
     | > stopnet_loss: 0.005877533927559853  (0.007588605438782411)
     | > loss: 0.2002457082271576  (0.198741230097684)
     | > align_error: 0.5944349765777588  (0.6190119765021584)

   --> STEP: 12
     | > decoder_loss: 0.4559793174266815  (0.44863830258448917)
     | > postnet_loss: 0.31307581067085266  (0.3163425847887993)
     | > stopnet_loss: 0.007850324735045433  (0.007610415380137662)
     | > loss: 0.20011410117149353  (0.19885563602050146)
     | > align_error: 0.5872915089130402  (0.6163686042030653)

   --> STEP: 13
     | > decoder_loss: 0.4447409212589264  (0.44833850402098435)
     | > postnet_loss: 0.3120514452457428  (0.3160124971316411)
     | > stopnet_loss: 0.00552941532805562  (0.007450338453054428)
     | > loss: 0.19472751021385193  (0.1985380878815284)
     | > align_error: 0.585045337677002  (0.6139591221625988)

   --> STEP: 14
     | > decoder_loss: 0.45904961228370667  (0.4491035831826074)
     | > postnet_loss: 0.31770527362823486  (0.31613340973854065)
     | > stopnet_loss: 0.00487554119899869  (0.007266424363479018)
     | > loss: 0.1990642547607422  (0.1985756712300437)
     | > align_error: 0.5546787083148956  (0.6097248068877629)

   --> STEP: 15
     | > decoder_loss: 0.4526882767677307  (0.44934256275494894)
     | > postnet_loss: 0.3143961727619171  (0.3160175939400991)
     | > stopnet_loss: 0.004949655383825302  (0.007111973098168771)
     | > loss: 0.19672077894210815  (0.1984520117441813)
     | > align_error: 0.5879947245121002  (0.6082761347293854)

   --> STEP: 16
     | > decoder_loss: 0.4520658254623413  (0.44951276667416096)
     | > postnet_loss: 0.3079349994659424  (0.3155124317854643)
     | > stopnet_loss: 0.005245692562311888  (0.006995330564677715)
     | > loss: 0.1952458918094635  (0.19825162924826145)
     | > align_error: 0.6047275364398956  (0.6080543473362923)

   --> STEP: 17
     | > decoder_loss: 0.4614996612071991  (0.45021787811728087)
     | > postnet_loss: 0.31819114089012146  (0.31567000290926767)
     | > stopnet_loss: 0.0047621820122003555  (0.0068639688851202234)
     | > loss: 0.19968488812446594  (0.19833593859392054)
     | > align_error: 0.5577490627765656  (0.605095212950426)

   --> STEP: 18
     | > decoder_loss: 0.4527328908443451  (0.4503576010465622)
     | > postnet_loss: 0.3083791732788086  (0.3152649568186866)
     | > stopnet_loss: 0.00516450684517622  (0.006769554327345557)
     | > loss: 0.19544252753257751  (0.19817519353495705)
     | > align_error: 0.6031383275985718  (0.6049864970975452)

   --> STEP: 19
     | > decoder_loss: 0.45202741026878357  (0.45044548574246857)
     | > postnet_loss: 0.3091190755367279  (0.31494148938279404)
     | > stopnet_loss: 0.00467775110155344  (0.006659459420724919)
     | > loss: 0.19496437907218933  (0.19800620330007454)
     | > align_error: 0.5985843539237976  (0.6046495421936637)

   --> STEP: 20
     | > decoder_loss: 0.44703003764152527  (0.4502747133374214)
     | > postnet_loss: 0.30459100008010864  (0.3144239649176598)
     | > stopnet_loss: 0.004494518972933292  (0.006551212398335338)
     | > loss: 0.1923997700214386  (0.19772588163614274)
     | > align_error: 0.6221575736999512  (0.6055249437689781)

   --> STEP: 21
     | > decoder_loss: 0.44562578201293945  (0.45005333565530325)
     | > postnet_loss: 0.3045576810836792  (0.3139541418779464)
     | > stopnet_loss: 0.003934341017156839  (0.006426599475422076)
     | > loss: 0.19148020446300507  (0.1974284684374219)
     | > align_error: 0.5589548945426941  (0.6033073223772503)

   --> STEP: 22
     | > decoder_loss: 0.4476211667060852  (0.44994278252124786)
     | > postnet_loss: 0.30706074833869934  (0.31364080580798065)
     | > stopnet_loss: 0.004764839541167021  (0.006351064932955937)
     | > loss: 0.19343532621860504  (0.1972469619729302)
     | > align_error: 0.6245313882827759  (0.6042720526456833)

   --> STEP: 23
     | > decoder_loss: 0.4201841950416565  (0.44864893089170044)
     | > postnet_loss: 0.29407432675361633  (0.31279008932735614)
     | > stopnet_loss: 0.004416011273860931  (0.006266932165169198)
     | > loss: 0.18298065662384033  (0.1966266878273176)
     | > align_error: 0.5661680996417999  (0.6026153590368188)

   --> STEP: 24
     | > decoder_loss: 0.4544687569141388  (0.44889142364263535)
     | > postnet_loss: 0.31005704402923584  (0.31267621243993443)
     | > stopnet_loss: 0.00441513117402792  (0.006189773790538311)
     | > loss: 0.19554656744003296  (0.19658168281118074)
     | > align_error: 0.5786121487617493  (0.6016152252753576)

   --> STEP: 25
     | > decoder_loss: 0.45297637581825256  (0.44905482172966005)
     | > postnet_loss: 0.30694276094436646  (0.3124468743801117)
     | > stopnet_loss: 0.003635966219007969  (0.006087621487677097)
     | > loss: 0.19361576437950134  (0.19646304607391357)
     | > align_error: 0.5562961399555206  (0.5998024618625641)

   --> STEP: 26
     | > decoder_loss: 0.4290238320827484  (0.44828439905093265)
     | > postnet_loss: 0.2959911823272705  (0.31181396314731014)
     | > stopnet_loss: 0.004297623410820961  (0.0060187754077980155)
     | > loss: 0.18555139005184174  (0.19604336699614158)
     | > align_error: 0.5457617938518524  (0.5977239746313829)

   --> STEP: 27
     | > decoder_loss: 0.42608046531677246  (0.44746203113485267)
     | > postnet_loss: 0.29136595129966736  (0.3110566293751752)
     | > stopnet_loss: 0.0038684515748173  (0.005939133784354285)
     | > loss: 0.18323005735874176  (0.19556879997253418)
     | > align_error: 0.539932906627655  (0.5955835647053189)

   --> STEP: 28
     | > decoder_loss: 0.4315352439880371  (0.44689321730818066)
     | > postnet_loss: 0.29590141773223877  (0.3105153718164989)
     | > stopnet_loss: 0.003903918666765094  (0.005866447530154671)
     | > loss: 0.18576309084892273  (0.19521859607526235)
     | > align_error: 0.5652113258838654  (0.5944988418902669)

   --> STEP: 29
     | > decoder_loss: 0.4272872805595398  (0.4462171505237448)
     | > postnet_loss: 0.2930184006690979  (0.3099120279838299)
     | > stopnet_loss: 0.003539122175425291  (0.005786194931715727)
     | > loss: 0.1836155354976654  (0.19481849053810382)
     | > align_error: 0.5394696593284607  (0.5926012838708943)

   --> STEP: 30
     | > decoder_loss: 0.4278675615787506  (0.44560549755891166)
     | > postnet_loss: 0.2935554087162018  (0.3093668073415756)
     | > stopnet_loss: 0.0027528335340321064  (0.005685082885126273)
     | > loss: 0.18310858309268951  (0.19442816028992335)
     | > align_error: 0.5322161316871643  (0.59058844546477)

   --> STEP: 31
     | > decoder_loss: 0.4223499000072479  (0.44485531699272896)
     | > postnet_loss: 0.29121774435043335  (0.30878135369670007)
     | > stopnet_loss: 0.003679408226162195  (0.005620383702579045)
     | > loss: 0.18207131326198578  (0.1940295523212802)
     | > align_error: 0.553208589553833  (0.5893826436611914)

   --> STEP: 32
     | > decoder_loss: 0.43712615966796875  (0.4446137808263302)
     | > postnet_loss: 0.2990594506263733  (0.30847754422575235)
     | > stopnet_loss: 0.003793301060795784  (0.005563287370023318)
     | > loss: 0.18783970177173615  (0.19383611949160695)
     | > align_error: 0.5297597050666809  (0.5875194268301129)

   --> STEP: 33
     | > decoder_loss: 0.43162113428115845  (0.4442200642643553)
     | > postnet_loss: 0.29542112350463867  (0.30808189511299133)
     | > stopnet_loss: 0.003991182427853346  (0.0055156478263211975)
     | > loss: 0.1857517510652542  (0.19359113863020233)
     | > align_error: 0.5449225008487701  (0.5862286108912844)

   --> STEP: 34
     | > decoder_loss: 0.43719854950904846  (0.4440135491244933)
     | > postnet_loss: 0.2966928482055664  (0.3077469231451259)
     | > stopnet_loss: 0.0032299249432981014  (0.005448420682702871)
     | > loss: 0.18670277297496796  (0.1933885396403425)
     | > align_error: 0.562512993812561  (0.5855310927419102)

   --> STEP: 35
     | > decoder_loss: 0.4352218806743622  (0.4437623585973467)
     | > postnet_loss: 0.2962244153022766  (0.3074177086353302)
     | > stopnet_loss: 0.00348127749748528  (0.005392216591696654)
     | > loss: 0.18634285032749176  (0.1931872342314039)
     | > align_error: 0.5324648022651672  (0.5840149130140032)

   --> STEP: 36
     | > decoder_loss: 0.4410761296749115  (0.44368774112727905)
     | > postnet_loss: 0.3008699417114258  (0.3072358262207773)
     | > stopnet_loss: 0.0036053331568837166  (0.005342580940729628)
     | > loss: 0.18909186124801636  (0.19307347387075427)
     | > align_error: 0.632518857717514  (0.5853622448113229)

   --> STEP: 37
     | > decoder_loss: 0.43370169401168823  (0.44341784796199285)
     | > postnet_loss: 0.2971123456954956  (0.3069622186390129)
     | > stopnet_loss: 0.003527351887896657  (0.005293520696058466)
     | > loss: 0.18623086810112  (0.19288853857968308)
     | > align_error: 0.5172287821769714  (0.5835207998752594)

   --> STEP: 38
     | > decoder_loss: 0.42129629850387573  (0.4428357019236213)
     | > postnet_loss: 0.2897879183292389  (0.3065102633677031)
     | > stopnet_loss: 0.0030991609673947096  (0.00523577438740942)
     | > loss: 0.18087022006511688  (0.19257226703982608)
     | > align_error: 0.5505452752113342  (0.5826530229104193)

   --> STEP: 39
     | > decoder_loss: 0.4363953471183777  (0.44267056462092275)
     | > postnet_loss: 0.30025404691696167  (0.3063498475612738)
     | > stopnet_loss: 0.0034444723278284073  (0.005189843565368881)
     | > loss: 0.1876068264245987  (0.19244494804969206)
     | > align_error: 0.5450846552848816  (0.5816897314328414)

   --> STEP: 40
     | > decoder_loss: 0.4336491525173187  (0.4424450293183327)
     | > postnet_loss: 0.29887279868125916  (0.3061629213392735)
     | > stopnet_loss: 0.0030052296351641417  (0.005135228217113762)
     | > loss: 0.18613572418689728  (0.1922872174531222)
     | > align_error: 0.5826734602451324  (0.5817143246531487)

   --> STEP: 41
     | > decoder_loss: 0.42577269673347473  (0.4420383870601654)
     | > postnet_loss: 0.2918824553489685  (0.30581461729072945)
     | > stopnet_loss: 0.003719186643138528  (0.005100690617748513)
     | > loss: 0.18313297629356384  (0.19206394327849882)
     | > align_error: 0.5020956993103027  (0.5797724069618597)

   --> STEP: 42
     | > decoder_loss: 0.4300990402698517  (0.44175411689849126)
     | > postnet_loss: 0.2938202917575836  (0.30552903811136883)
     | > stopnet_loss: 0.003258639248088002  (0.005056832251804215)
     | > loss: 0.1842384785413742  (0.1918776226895197)
     | > align_error: 0.5782988667488098  (0.5797373226710728)

   --> STEP: 43
     | > decoder_loss: 0.4284026622772217  (0.4414436179538106)
     | > postnet_loss: 0.2921735644340515  (0.3052184457002684)
     | > stopnet_loss: 0.0028781546279788017  (0.005006165330319903)
     | > loss: 0.18302221596240997  (0.19167168299819157)
     | > align_error: 0.5503286123275757  (0.5790533991747124)

   --> STEP: 44
     | > decoder_loss: 0.44675347208976746  (0.4415642964569005)
     | > postnet_loss: 0.3033624589443207  (0.3051762641830878)
     | > stopnet_loss: 0.0026159221306443214  (0.004951841621236367)
     | > loss: 0.19014491140842438  (0.19163698364387868)
     | > align_error: 0.5494847297668457  (0.5783813839608972)

   --> STEP: 45
     | > decoder_loss: 0.4391178786754608  (0.44150993161731295)
     | > postnet_loss: 0.30187633633613586  (0.3051029324531555)
     | > stopnet_loss: 0.003239238169044256  (0.004913783766743209)
     | > loss: 0.18848779797554016  (0.19156700174013783)
     | > align_error: 0.5510070025920868  (0.5777730643749236)

   --> STEP: 46
     | > decoder_loss: 0.43043050169944763  (0.4412690744451854)
     | > postnet_loss: 0.29382380843162537  (0.3048577341048614)
     | > stopnet_loss: 0.00317359808832407  (0.0048759536432993154)
     | > loss: 0.18423718214035034  (0.1914076578357946)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.36503527019963133 (+0.006244511315317058)
     | > avg_decoder_loss: 0.43733241883191193 (+0.0001819418235258219)
     | > avg_postnet_loss: 0.3017943885290261 (+0.0008796476053468671)
     | > avg_stopnet_loss: 0.0043289599460408544 (+8.127479249555106e-06)
     | > avg_loss: 0.18911066267526516 (+0.000273526166424648)
     | > avg_align_error: 0.5705490974765836 (-0.0011432017340804457)


 > EPOCH: 154/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 19:52:27)

   --> TIME: 2025-12-28 19:53:00 -- STEP: 21/150 -- GLOBAL_STEP: 23275
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4707159101963043  (0.46399474427813575)
     | > postnet_loss: 0.3953869342803955  (0.3925825158754985)
     | > stopnet_loss: 0.007029700092971325  (0.010190839879214762)
     | > loss: 0.22355540096759796  (0.22433515247844515)
     | > align_error: 0.6265131831169128  (0.6750520737398238)
     | > grad_norm: tensor(0.3582, device='cuda:0')  (tensor(0.3030, device='cuda:0'))
     | > step_time: 0.8747  (0.612881966999599)
     | > loader_time: 0.8365  (0.8944871425628662)


   --> TIME: 2025-12-28 19:53:52 -- STEP: 46/150 -- GLOBAL_STEP: 23300
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4898305833339691  (0.47242089393346204)
     | > postnet_loss: 0.402341365814209  (0.3957279032987097)
     | > stopnet_loss: 0.005030583590269089  (0.0077490594400011995)
     | > loss: 0.2280735820531845  (0.22478625826213672)
     | > align_error: 0.6583829522132874  (0.6492609420548314)
     | > grad_norm: tensor(0.3491, device='cuda:0')  (tensor(0.2792, device='cuda:0'))
     | > step_time: 1.3481  (0.8631774549898894)
     | > loader_time: 1.0998  (0.9626696161601854)


   --> TIME: 2025-12-28 19:54:58 -- STEP: 71/150 -- GLOBAL_STEP: 23325
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4814516603946686  (0.4756312059684539)
     | > postnet_loss: 0.39383918046951294  (0.3955803286861366)
     | > stopnet_loss: 0.0039683496579527855  (0.006511688527559311)
     | > loss: 0.22279106080532074  (0.224314572105945)
     | > align_error: 0.6051379442214966  (0.6365932310131234)
     | > grad_norm: tensor(0.1428, device='cuda:0')  (tensor(0.2623, device='cuda:0'))
     | > step_time: 1.6594  (1.0558522855731802)
     | > loader_time: 1.2898  (1.051513373012274)


   --> TIME: 2025-12-28 19:56:21 -- STEP: 96/150 -- GLOBAL_STEP: 23350
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48476293683052063  (0.4768840229759614)
     | > postnet_loss: 0.39498868584632874  (0.39476749394088984)
     | > stopnet_loss: 0.003400391200557351  (0.005781055723976656)
     | > loss: 0.2233382910490036  (0.2236939345796903)
     | > align_error: 0.6034374535083771  (0.6318076296399037)
     | > grad_norm: tensor(0.1348, device='cuda:0')  (tensor(0.2429, device='cuda:0'))
     | > step_time: 1.671  (1.2182553435365362)
     | > loader_time: 2.1051  (1.2031779984633122)


   --> TIME: 2025-12-28 19:57:55 -- STEP: 121/150 -- GLOBAL_STEP: 23375
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48479342460632324  (0.4780891633723393)
     | > postnet_loss: 0.3933938145637512  (0.39438032266522244)
     | > stopnet_loss: 0.003207205096259713  (0.005278213459551951)
     | > loss: 0.22275401651859283  (0.22339558490544312)
     | > align_error: 0.6493719220161438  (0.6270566306823542)
     | > grad_norm: tensor(0.1289, device='cuda:0')  (tensor(0.2367, device='cuda:0'))
     | > step_time: 2.0844  (1.358549023462721)
     | > loader_time: 1.8856  (1.335582122329837)


   --> TIME: 2025-12-28 19:59:37 -- STEP: 146/150 -- GLOBAL_STEP: 23400
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4939991533756256  (0.4793609174555295)
     | > postnet_loss: 0.3976130187511444  (0.39415410018130526)
     | > stopnet_loss: 0.003199210623279214  (0.00490495365604197)
     | > loss: 0.22610224783420563  (0.22328370809555054)
     | > align_error: 0.6245356798171997  (0.6232129176185556)
     | > grad_norm: tensor(0.1263, device='cuda:0')  (tensor(0.2353, device='cuda:0'))
     | > step_time: 2.6622  (1.4995974024681196)
     | > loader_time: 1.8558  (1.4368165225198817)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45944225788116455  (0.45944225788116455)
     | > postnet_loss: 0.3338775336742401  (0.3338775336742401)
     | > stopnet_loss: 0.012058942578732967  (0.012058942578732967)
     | > loss: 0.2103888988494873  (0.2103888988494873)
     | > align_error: 0.7182839512825012  (0.7182839512825012)

   --> STEP: 1
     | > decoder_loss: 0.44031545519828796  (0.44031545519828796)
     | > postnet_loss: 0.3212395906448364  (0.3212395906448364)
     | > stopnet_loss: 0.009620518423616886  (0.009620518423616886)
     | > loss: 0.200009286403656  (0.200009286403656)
     | > align_error: 0.6585038006305695  (0.6585038006305695)

   --> STEP: 2
     | > decoder_loss: 0.43666595220565796  (0.43849070370197296)
     | > postnet_loss: 0.3125591278076172  (0.3168993592262268)
     | > stopnet_loss: 0.0109769431874156  (0.010298730805516243)
     | > loss: 0.19828321039676666  (0.19914624840021133)
     | > align_error: 0.6546332836151123  (0.6565685421228409)

   --> STEP: 3
     | > decoder_loss: 0.4409395754337311  (0.43930699427922565)
     | > postnet_loss: 0.31279388070106506  (0.3155308663845062)
     | > stopnet_loss: 0.008111980743706226  (0.009569814118246237)
     | > loss: 0.19654534757137299  (0.19827928145726523)
     | > align_error: 0.7349080443382263  (0.6826817095279694)

   --> STEP: 4
     | > decoder_loss: 0.44332006573677063  (0.4403102621436119)
     | > postnet_loss: 0.31889045238494873  (0.31637076288461685)
     | > stopnet_loss: 0.008151069283485413  (0.009215127909556031)
     | > loss: 0.19870369136333466  (0.19838538393378258)
     | > align_error: 0.6022719144821167  (0.6625792607665062)

   --> STEP: 5
     | > decoder_loss: 0.42595043778419495  (0.4374382972717285)
     | > postnet_loss: 0.30204546451568604  (0.3135057032108307)
     | > stopnet_loss: 0.00804818794131279  (0.008981739915907384)
     | > loss: 0.19004715979099274  (0.1967177391052246)
     | > align_error: 0.6406248211860657  (0.6581883728504181)

   --> STEP: 6
     | > decoder_loss: 0.4439692795276642  (0.43852679431438446)
     | > postnet_loss: 0.3142038583755493  (0.31362206240495044)
     | > stopnet_loss: 0.007197834551334381  (0.008684422355145216)
     | > loss: 0.19674110412597656  (0.19672163327534994)
     | > align_error: 0.5930252075195312  (0.6473278452952703)

   --> STEP: 7
     | > decoder_loss: 0.4546765983104706  (0.4408339091709682)
     | > postnet_loss: 0.31424883008003235  (0.31371160064424786)
     | > stopnet_loss: 0.006142055615782738  (0.008321227106664861)
     | > loss: 0.19837340712547302  (0.19695760096822465)
     | > align_error: 0.5781221985816956  (0.6374413243361882)

   --> STEP: 8
     | > decoder_loss: 0.45127859711647034  (0.44213949516415596)
     | > postnet_loss: 0.3160631060600281  (0.3140055388212204)
     | > stopnet_loss: 0.007227497640997171  (0.0081845109234564)
     | > loss: 0.19906292855739594  (0.19722076691687107)
     | > align_error: 0.5738534927368164  (0.6294928453862667)

   --> STEP: 9
     | > decoder_loss: 0.44738465547561646  (0.44272229075431824)
     | > postnet_loss: 0.3149566650390625  (0.31411121951209175)
     | > stopnet_loss: 0.0065790992230176926  (0.008006131845629878)
     | > loss: 0.19716443121433258  (0.1972145073943668)
     | > align_error: 0.5903899073600769  (0.6251480744944679)

   --> STEP: 10
     | > decoder_loss: 0.47096139192581177  (0.44554620087146757)
     | > postnet_loss: 0.3281698226928711  (0.3155170798301697)
     | > stopnet_loss: 0.00559561513364315  (0.0077650801744312044)
     | > loss: 0.20537841320037842  (0.19803089797496795)
     | > align_error: 0.5826571583747864  (0.6208989828824997)

   --> STEP: 11
     | > decoder_loss: 0.4585473835468292  (0.4467281265692277)
     | > postnet_loss: 0.31860774755477905  (0.315798049623316)
     | > stopnet_loss: 0.0058744498528540134  (0.00759320469065146)
     | > loss: 0.20016324520111084  (0.19822474772279913)
     | > align_error: 0.5943465232849121  (0.6184851229190826)

   --> STEP: 12
     | > decoder_loss: 0.45526570081710815  (0.44743959108988446)
     | > postnet_loss: 0.31237557530403137  (0.31551284343004227)
     | > stopnet_loss: 0.007901912555098534  (0.00761893034602205)
     | > loss: 0.19981223344802856  (0.19835703819990158)
     | > align_error: 0.5866301357746124  (0.6158305406570435)

   --> STEP: 13
     | > decoder_loss: 0.4444548487663269  (0.44720999552653384)
     | > postnet_loss: 0.31190282106399536  (0.3152351494018848)
     | > stopnet_loss: 0.005230171140283346  (0.007435179637888303)
     | > loss: 0.19431959092617035  (0.1980464653326915)
     | > align_error: 0.5840926766395569  (0.6133891665018522)

   --> STEP: 14
     | > decoder_loss: 0.4563542306423187  (0.44786315517766134)
     | > postnet_loss: 0.31566980481147766  (0.31526619621685575)
     | > stopnet_loss: 0.004870289471000433  (0.007251973197396312)
     | > loss: 0.19787630438804626  (0.19803431097950255)
     | > align_error: 0.5541022419929504  (0.6091543861797878)

   --> STEP: 15
     | > decoder_loss: 0.4527103304862976  (0.4481863001982371)
     | > postnet_loss: 0.31427133083343506  (0.315199871857961)
     | > stopnet_loss: 0.004956440068781376  (0.00709893765548865)
     | > loss: 0.19670185446739197  (0.19794548054536185)
     | > align_error: 0.5878259837627411  (0.607732492685318)

   --> STEP: 16
     | > decoder_loss: 0.45318838953971863  (0.4484989307820797)
     | > postnet_loss: 0.3086308538913727  (0.31478930823504925)
     | > stopnet_loss: 0.005241896025836468  (0.006982872553635389)
     | > loss: 0.19569671154022217  (0.1978049324825406)
     | > align_error: 0.6047002971172333  (0.6075429804623127)

   --> STEP: 17
     | > decoder_loss: 0.4609391987323761  (0.4492307112497442)
     | > postnet_loss: 0.31753775477409363  (0.31495098156087536)
     | > stopnet_loss: 0.0047507453709840775  (0.0068515709546559)
     | > loss: 0.19936998188495636  (0.19789699421209447)
     | > align_error: 0.5576850771903992  (0.6046101626227883)

   --> STEP: 18
     | > decoder_loss: 0.45280513167381287  (0.44942929016219246)
     | > postnet_loss: 0.30833277106285095  (0.31458330319987404)
     | > stopnet_loss: 0.005211454350501299  (0.0067604533655362)
     | > loss: 0.19549593329429626  (0.19776360193888345)
     | > align_error: 0.6030510663986206  (0.6045235461658902)

   --> STEP: 19
     | > decoder_loss: 0.45103657245635986  (0.44951388396714864)
     | > postnet_loss: 0.3087027072906494  (0.3142737981520201)
     | > stopnet_loss: 0.004672141280025244  (0.006650542203140886)
     | > loss: 0.1946069598197937  (0.197597462879984)
     | > align_error: 0.5987920761108398  (0.6042218898472033)

   --> STEP: 20
     | > decoder_loss: 0.44689857959747314  (0.4493831187486649)
     | > postnet_loss: 0.304370254278183  (0.31377862095832826)
     | > stopnet_loss: 0.004470589570701122  (0.006541544571518898)
     | > loss: 0.19228780269622803  (0.1973319798707962)
     | > align_error: 0.6221358776092529  (0.6051175892353058)

   --> STEP: 21
     | > decoder_loss: 0.4452926218509674  (0.4491883331821078)
     | > postnet_loss: 0.3038983643054962  (0.31330813254628864)
     | > stopnet_loss: 0.003918288741260767  (0.006416627627220892)
     | > loss: 0.19121603667736053  (0.1970407444806326)
     | > align_error: 0.558877170085907  (0.6029156645139059)

   --> STEP: 22
     | > decoder_loss: 0.44731664657592773  (0.44910325651819055)
     | > postnet_loss: 0.30664363503456116  (0.3130052008412101)
     | > stopnet_loss: 0.0047825477086007595  (0.006342351267283613)
     | > loss: 0.19327260553836823  (0.1968694654378024)
     | > align_error: 0.6245948672294617  (0.6039010828191583)

   --> STEP: 23
     | > decoder_loss: 0.4202768802642822  (0.4478499358114989)
     | > postnet_loss: 0.2941476106643677  (0.31218530561613)
     | > stopnet_loss: 0.004406474996358156  (0.006258182733765115)
     | > loss: 0.18301260471343994  (0.19626699323239533)
     | > align_error: 0.5660476684570312  (0.602255282194718)

   --> STEP: 24
     | > decoder_loss: 0.4547651708126068  (0.4481380706032117)
     | > postnet_loss: 0.3102226257324219  (0.3121035272876422)
     | > stopnet_loss: 0.004414248745888472  (0.006181352150936921)
     | > loss: 0.19566120207309723  (0.19624175193409124)
     | > align_error: 0.5782597661018372  (0.6012554690241813)

   --> STEP: 25
     | > decoder_loss: 0.4531886875629425  (0.44834009528160096)
     | > postnet_loss: 0.30712324380874634  (0.31190431594848633)
     | > stopnet_loss: 0.003622264601290226  (0.006078988648951054)
     | > loss: 0.19370025396347046  (0.19614009201526642)
     | > align_error: 0.5564594864845276  (0.599463629722595)

   --> STEP: 26
     | > decoder_loss: 0.42946261167526245  (0.4476140382198187)
     | > postnet_loss: 0.29631686210632324  (0.3113047984930185)
     | > stopnet_loss: 0.004279650282114744  (0.0060097833271496575)
     | > loss: 0.18572451174259186  (0.1957394927740097)
     | > align_error: 0.5455685257911682  (0.5973907411098479)

   --> STEP: 27
     | > decoder_loss: 0.42615383863449097  (0.4468192160129547)
     | > postnet_loss: 0.29128792881965637  (0.3105634329495607)
     | > stopnet_loss: 0.003866369603201747  (0.005930397633670105)
     | > loss: 0.1832268238067627  (0.1952760605900376)
     | > align_error: 0.5399358868598938  (0.5952627835450348)

   --> STEP: 28
     | > decoder_loss: 0.43146222829818726  (0.4462707521659987)
     | > postnet_loss: 0.2956438660621643  (0.3100305912750108)
     | > stopnet_loss: 0.0038854314479976892  (0.005857363127038947)
     | > loss: 0.18566195666790009  (0.19493269973567554)
     | > align_error: 0.5652886629104614  (0.5941922792366572)

   --> STEP: 29
     | > decoder_loss: 0.4269983768463135  (0.4456061874998027)
     | > postnet_loss: 0.292643278837204  (0.3094310287771554)
     | > stopnet_loss: 0.0035373580176383257  (0.005777362950852719)
     | > loss: 0.18344777822494507  (0.19453666795944347)
     | > align_error: 0.5393494963645935  (0.5923011487927929)

   --> STEP: 30
     | > decoder_loss: 0.42788752913475037  (0.44501556555430094)
     | > postnet_loss: 0.2934786081314087  (0.30889928142229717)
     | > stopnet_loss: 0.0027382506523281336  (0.005676059207568566)
     | > loss: 0.183079794049263  (0.19415477216243743)
     | > align_error: 0.5319893658161163  (0.5902907560269036)

   --> STEP: 31
     | > decoder_loss: 0.4235163629055023  (0.44432204288821064)
     | > postnet_loss: 0.2916591167449951  (0.3083431470778681)
     | > stopnet_loss: 0.00367439235560596  (0.00561148930911816)
     | > loss: 0.1824682652950287  (0.1937777880699404)
     | > align_error: 0.5539976358413696  (0.5891200102144671)

   --> STEP: 32
     | > decoder_loss: 0.43636199831962585  (0.4440732914954424)
     | > postnet_loss: 0.2984435260295868  (0.30803378392010927)
     | > stopnet_loss: 0.0037870195228606462  (0.005554474628297612)
     | > loss: 0.1874884068965912  (0.19358124490827322)
     | > align_error: 0.5295813679695129  (0.5872594276443123)

   --> STEP: 33
     | > decoder_loss: 0.4315985143184662  (0.44369526794462494)
     | > postnet_loss: 0.29535603523254395  (0.30764960971745575)
     | > stopnet_loss: 0.003976957406848669  (0.005506671076132493)
     | > loss: 0.18571560084819794  (0.1933428920579679)
     | > align_error: 0.5448547601699829  (0.5859744377208478)

   --> STEP: 34
     | > decoder_loss: 0.4374278485774994  (0.44351093208088593)
     | > postnet_loss: 0.2967709004878998  (0.30732964768129234)
     | > stopnet_loss: 0.0032346276566386223  (0.00543984626967679)
     | > loss: 0.1867843121290207  (0.193149992648293)
     | > align_error: 0.5624830722808838  (0.5852835152079077)

   --> STEP: 35
     | > decoder_loss: 0.4350421726703644  (0.44326896752629963)
     | > postnet_loss: 0.2960006296634674  (0.30700596145221165)
     | > stopnet_loss: 0.0034850367810577154  (0.00538399457000196)
     | > loss: 0.18624573945999146  (0.19295272827148438)
     | > align_error: 0.5319947600364685  (0.5837609793458665)

   --> STEP: 36
     | > decoder_loss: 0.4409819543361664  (0.44320543938212925)
     | > postnet_loss: 0.3004451394081116  (0.3068237163954311)
     | > stopnet_loss: 0.003610788844525814  (0.0053347388554054005)
     | > loss: 0.18896755576133728  (0.1928420290350914)
     | > align_error: 0.6325296461582184  (0.5851156645350984)

   --> STEP: 37
     | > decoder_loss: 0.43396010994911194  (0.44295556561366933)
     | > postnet_loss: 0.29712975025177  (0.3065617173104673)
     | > stopnet_loss: 0.0035208140034228563  (0.005285713859405872)
     | > loss: 0.18629327416419983  (0.19266503566020243)
     | > align_error: 0.5172139406204224  (0.5832804828076747)

   --> STEP: 38
     | > decoder_loss: 0.4210248589515686  (0.4423784417541404)
     | > postnet_loss: 0.28957661986351013  (0.30611474106186315)
     | > stopnet_loss: 0.003095838474109769  (0.005228085559792817)
     | > loss: 0.1807461977005005  (0.19235138202968396)
     | > align_error: 0.5502471327781677  (0.5824111841226877)

   --> STEP: 39
     | > decoder_loss: 0.4376784563064575  (0.4422579293067639)
     | > postnet_loss: 0.3008635640144348  (0.3059800954965445)
     | > stopnet_loss: 0.003439544001594186  (0.0051822255198390055)
     | > loss: 0.18807505071163177  (0.19224173250870827)
     | > align_error: 0.5447544753551483  (0.5814456274876226)

   --> STEP: 40
     | > decoder_loss: 0.43409231305122375  (0.4420537889003754)
     | > postnet_loss: 0.29901158809661865  (0.3058058828115463)
     | > stopnet_loss: 0.0030021618586033583  (0.005127723928308114)
     | > loss: 0.18627813458442688  (0.19209264256060124)
     | > align_error: 0.5825798511505127  (0.5814739830791948)

   --> STEP: 41
     | > decoder_loss: 0.42533329129219055  (0.4416459718855416)
     | > postnet_loss: 0.291608989238739  (0.3054596171146486)
     | > stopnet_loss: 0.0037156359758228064  (0.005093282758735302)
     | > loss: 0.1829512119293213  (0.19186968083788708)
     | > align_error: 0.5018961727619171  (0.5795330608763344)

   --> STEP: 42
     | > decoder_loss: 0.4296683073043823  (0.441360789395514)
     | > postnet_loss: 0.2933844327926636  (0.3051721127260299)
     | > stopnet_loss: 0.0032526946160942316  (0.005049459231529562)
     | > loss: 0.1840158849954605  (0.1916826856987817)
     | > align_error: 0.5781171917915344  (0.5794993497076487)

   --> STEP: 43
     | > decoder_loss: 0.4284627139568329  (0.441060834152754)
     | > postnet_loss: 0.2920508086681366  (0.3048669661200324)
     | > stopnet_loss: 0.0028812121599912643  (0.004999034881028671)
     | > loss: 0.18300959467887878  (0.19148098590762117)
     | > align_error: 0.5505346059799194  (0.5788257510163062)

   --> STEP: 44
     | > decoder_loss: 0.4472074806690216  (0.44120053066448733)
     | > postnet_loss: 0.3033483326435089  (0.3048324517228387)
     | > stopnet_loss: 0.0026135302614420652  (0.004944818866947157)
     | > loss: 0.19025248289108276  (0.191453065384518)
     | > align_error: 0.5495190024375916  (0.5781596885486081)

   --> STEP: 45
     | > decoder_loss: 0.4398414194583893  (0.4411703281932407)
     | > postnet_loss: 0.3023514747619629  (0.30477731890148585)
     | > stopnet_loss: 0.0032317843288183212  (0.004906751432766516)
     | > loss: 0.18877999484539032  (0.19139366381698183)
     | > align_error: 0.5508971512317657  (0.5775538543860116)

   --> STEP: 46
     | > decoder_loss: 0.42991387844085693  (0.44092562276384106)
     | > postnet_loss: 0.2933560311794281  (0.3045290300379629)
     | > stopnet_loss: 0.003162227338179946  (0.004868826995927678)
     | > loss: 0.18397970497608185  (0.19123249079870142)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3545102495135683 (-0.010525020686063036)
     | > avg_decoder_loss: 0.4371267995147994 (-0.00020561931711254866)
     | > avg_postnet_loss: 0.3014831393957138 (-0.00031124913331231907)
     | > avg_stopnet_loss: 0.0043220626980517846 (-6.897247989069884e-06)
     | > avg_loss: 0.18897454779256473 (-0.00013611488270043326)
     | > avg_align_error: 0.5703346891836685 (-0.00021440829291508035)


 > EPOCH: 155/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 20:01:50)

   --> TIME: 2025-12-28 20:02:20 -- STEP: 20/150 -- GLOBAL_STEP: 23425
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46633967757225037  (0.46436925828456876)
     | > postnet_loss: 0.39152252674102783  (0.3926935210824013)
     | > stopnet_loss: 0.006826966069638729  (0.010313280439004303)
     | > loss: 0.22129252552986145  (0.22457897812128066)
     | > align_error: 0.6285269558429718  (0.6769806861877441)
     | > grad_norm: tensor(0.3114, device='cuda:0')  (tensor(0.3471, device='cuda:0'))
     | > step_time: 0.847  (0.6200835227966308)
     | > loader_time: 1.1191  (0.8048603296279907)


   --> TIME: 2025-12-28 20:03:13 -- STEP: 45/150 -- GLOBAL_STEP: 23450
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4805639088153839  (0.4724013388156891)
     | > postnet_loss: 0.396573007106781  (0.39578305747773906)
     | > stopnet_loss: 0.004662199877202511  (0.00777735992645224)
     | > loss: 0.2239464372396469  (0.22482346097628275)
     | > align_error: 0.6304628551006317  (0.6484281943904028)
     | > grad_norm: tensor(0.1764, device='cuda:0')  (tensor(0.3210, device='cuda:0'))
     | > step_time: 1.2517  (0.8786467764112683)
     | > loader_time: 1.0804  (0.9254515277014839)


   --> TIME: 2025-12-28 20:04:18 -- STEP: 70/150 -- GLOBAL_STEP: 23475
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48189786076545715  (0.47573238611221313)
     | > postnet_loss: 0.3946751654148102  (0.39571199119091033)
     | > stopnet_loss: 0.003848422085866332  (0.006527309894694813)
     | > loss: 0.2229916751384735  (0.22438840461628778)
     | > align_error: 0.5951196551322937  (0.636817043168204)
     | > grad_norm: tensor(0.2456, device='cuda:0')  (tensor(0.2976, device='cuda:0'))
     | > step_time: 1.6373  (1.0653079645974295)
     | > loader_time: 1.3102  (1.0282891409737722)


   --> TIME: 2025-12-28 20:05:37 -- STEP: 95/150 -- GLOBAL_STEP: 23500
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4793749749660492  (0.47691721226039685)
     | > postnet_loss: 0.3908839225769043  (0.39481034906286944)
     | > stopnet_loss: 0.003296845592558384  (0.005806004841762938)
     | > loss: 0.22086158394813538  (0.223737895488739)
     | > align_error: 0.600013941526413  (0.6318774828785341)
     | > grad_norm: tensor(0.2492, device='cuda:0')  (tensor(0.2723, device='cuda:0'))
     | > step_time: 1.8473  (1.2187857326708342)
     | > loader_time: 1.8321  (1.1546671415630136)


   --> TIME: 2025-12-28 20:07:05 -- STEP: 120/150 -- GLOBAL_STEP: 23525
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4807661473751068  (0.4779348115126292)
     | > postnet_loss: 0.39048710465431213  (0.3943051531910896)
     | > stopnet_loss: 0.003260040655732155  (0.005302380017625789)
     | > loss: 0.22107335925102234  (0.22336237107714016)
     | > align_error: 0.6195322275161743  (0.6266583802799379)
     | > grad_norm: tensor(0.1672, device='cuda:0')  (tensor(0.2514, device='cuda:0'))
     | > step_time: 2.0413  (1.3592192848523463)
     | > loader_time: 1.7147  (1.2547354360421494)


   --> TIME: 2025-12-28 20:08:50 -- STEP: 145/150 -- GLOBAL_STEP: 23550
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4868803024291992  (0.4790678813539702)
     | > postnet_loss: 0.39289918541908264  (0.39396710498579623)
     | > stopnet_loss: 0.002805193653330207  (0.004916033603186752)
     | > loss: 0.22275005280971527  (0.22317478029892363)
     | > align_error: 0.6345824897289276  (0.6229944919717719)
     | > grad_norm: tensor(0.2357, device='cuda:0')  (tensor(0.2386, device='cuda:0'))
     | > step_time: 2.4088  (1.4989430772847148)
     | > loader_time: 2.0427  (1.3862198698109591)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.458651602268219  (0.458651602268219)
     | > postnet_loss: 0.33199605345726013  (0.33199605345726013)
     | > stopnet_loss: 0.012208259664475918  (0.012208259664475918)
     | > loss: 0.20987015962600708  (0.20987015962600708)
     | > align_error: 0.7183924913406372  (0.7183924913406372)

   --> STEP: 1
     | > decoder_loss: 0.4384712278842926  (0.4384712278842926)
     | > postnet_loss: 0.31849321722984314  (0.31849321722984314)
     | > stopnet_loss: 0.009628425352275372  (0.009628425352275372)
     | > loss: 0.19886954128742218  (0.19886954128742218)
     | > align_error: 0.6584194898605347  (0.6584194898605347)

   --> STEP: 2
     | > decoder_loss: 0.4359647035598755  (0.43721796572208405)
     | > postnet_loss: 0.31139254570007324  (0.3149428814649582)
     | > stopnet_loss: 0.010983310639858246  (0.010305867996066809)
     | > loss: 0.19782263040542603  (0.1983460858464241)
     | > align_error: 0.654512345790863  (0.6564659178256989)

   --> STEP: 3
     | > decoder_loss: 0.4386841356754303  (0.43770668903986615)
     | > postnet_loss: 0.30967608094215393  (0.3131872812906901)
     | > stopnet_loss: 0.008210983127355576  (0.009607573039829731)
     | > loss: 0.19530104100704193  (0.19733107089996338)
     | > align_error: 0.7340427339076996  (0.6823248565196991)

   --> STEP: 4
     | > decoder_loss: 0.4431287944316864  (0.4390622153878212)
     | > postnet_loss: 0.3169858753681183  (0.31413692981004715)
     | > stopnet_loss: 0.008209066465497017  (0.009257946396246552)
     | > loss: 0.19823773205280304  (0.1975577361881733)
     | > align_error: 0.6021558046340942  (0.6622825935482979)

   --> STEP: 5
     | > decoder_loss: 0.4259730279445648  (0.4364443778991699)
     | > postnet_loss: 0.30061671137809753  (0.3114328861236572)
     | > stopnet_loss: 0.00805021170526743  (0.009016399458050727)
     | > loss: 0.18969765305519104  (0.19598571956157684)
     | > align_error: 0.6407197713851929  (0.6579700291156769)

   --> STEP: 6
     | > decoder_loss: 0.44365501403808594  (0.43764615058898926)
     | > postnet_loss: 0.3125945031642914  (0.31162648896376294)
     | > stopnet_loss: 0.007278020028024912  (0.008726669553046426)
     | > loss: 0.196340411901474  (0.1960448349515597)
     | > align_error: 0.5929706692695618  (0.6471368024746577)

   --> STEP: 7
     | > decoder_loss: 0.4541202187538147  (0.43999958889825)
     | > postnet_loss: 0.312696248292923  (0.3117793117250715)
     | > stopnet_loss: 0.0062144058756530285  (0.008367774741990226)
     | > loss: 0.19791853427886963  (0.19631250628403255)
     | > align_error: 0.5778121054172516  (0.6372332743235997)

   --> STEP: 8
     | > decoder_loss: 0.44703370332717896  (0.44087885320186615)
     | > postnet_loss: 0.31186050176620483  (0.31178946048021317)
     | > stopnet_loss: 0.007065558340400457  (0.008204997691791505)
     | > loss: 0.19678911566734314  (0.19637208245694637)
     | > align_error: 0.5729138851165771  (0.6291933506727219)

   --> STEP: 9
     | > decoder_loss: 0.44546690583229065  (0.44138863682746887)
     | > postnet_loss: 0.3125515878200531  (0.3118741412957509)
     | > stopnet_loss: 0.006594323553144932  (0.008026033898608552)
     | > loss: 0.1960989534854889  (0.1963417347934511)
     | > align_error: 0.5902552008628845  (0.62486688958274)

   --> STEP: 10
     | > decoder_loss: 0.4700254201889038  (0.44425231516361235)
     | > postnet_loss: 0.3259442448616028  (0.3132811516523361)
     | > stopnet_loss: 0.0056176334619522095  (0.007785193854942918)
     | > loss: 0.20461004972457886  (0.19716856628656387)
     | > align_error: 0.5822075605392456  (0.6206009566783905)

   --> STEP: 11
     | > decoder_loss: 0.45739632844924927  (0.44544722546230664)
     | > postnet_loss: 0.31662243604660034  (0.3135849047790874)
     | > stopnet_loss: 0.005923828110098839  (0.007615978787229819)
     | > loss: 0.1994285136461258  (0.19737401604652405)
     | > align_error: 0.5939048528671265  (0.6181740381500938)

   --> STEP: 12
     | > decoder_loss: 0.4543682038784027  (0.44619064033031464)
     | > postnet_loss: 0.31066784262657166  (0.31334181626637775)
     | > stopnet_loss: 0.007858785800635815  (0.007636212705013652)
     | > loss: 0.19911779463291168  (0.197519330928723)
     | > align_error: 0.5866745710372925  (0.6155490825573603)

   --> STEP: 13
     | > decoder_loss: 0.4438978135585785  (0.4460142690401811)
     | > postnet_loss: 0.31036505103111267  (0.31311283432520354)
     | > stopnet_loss: 0.005305589642375708  (0.007456934007887657)
     | > loss: 0.19387130439281464  (0.1972387135028839)
     | > align_error: 0.5839574933052063  (0.6131189603071946)

   --> STEP: 14
     | > decoder_loss: 0.45683103799819946  (0.44678689539432526)
     | > postnet_loss: 0.3149895668029785  (0.3132468866450446)
     | > stopnet_loss: 0.004910161718726158  (0.007275021701518979)
     | > loss: 0.1978653073310852  (0.19728347020489828)
     | > align_error: 0.5539836883544922  (0.6088950123105731)

   --> STEP: 15
     | > decoder_loss: 0.45275557041168213  (0.447184807062149)
     | > postnet_loss: 0.31360524892807007  (0.31327077746391296)
     | > stopnet_loss: 0.00497670192271471  (0.007121800382932027)
     | > loss: 0.19656690955162048  (0.19723569949467976)
     | > align_error: 0.5874849557876587  (0.6074676752090454)

   --> STEP: 16
     | > decoder_loss: 0.45399585366249084  (0.4476104974746704)
     | > postnet_loss: 0.30814385414123535  (0.3129503447562456)
     | > stopnet_loss: 0.005264077801257372  (0.007005692721577361)
     | > loss: 0.19579899311065674  (0.19714590534567833)
     | > align_error: 0.6047880053520203  (0.6073001958429813)

   --> STEP: 17
     | > decoder_loss: 0.4598747789859772  (0.44833192579886494)
     | > postnet_loss: 0.3159435987472534  (0.31312641852042256)
     | > stopnet_loss: 0.00478567136451602  (0.006875103229985517)
     | > loss: 0.19874025881290436  (0.19723969084375045)
     | > align_error: 0.5576581358909607  (0.6043800746693331)

   --> STEP: 18
     | > decoder_loss: 0.4534745216369629  (0.44861762556764817)
     | > postnet_loss: 0.3079166114330292  (0.31283698479334515)
     | > stopnet_loss: 0.005217157304286957  (0.006782995123002265)
     | > loss: 0.19556495547294617  (0.19714664998981687)
     | > align_error: 0.603011280298233  (0.6043040305376053)

   --> STEP: 19
     | > decoder_loss: 0.450562983751297  (0.44872001284047175)
     | > postnet_loss: 0.3074377775192261  (0.3125528159894441)
     | > stopnet_loss: 0.004687332548201084  (0.00667269709274957)
     | > loss: 0.19418752193450928  (0.19699090640795858)
     | > align_error: 0.5981311798095703  (0.6039791436571824)

   --> STEP: 20
     | > decoder_loss: 0.4483388364315033  (0.44870095402002336)
     | > postnet_loss: 0.3045564889907837  (0.3121529996395111)
     | > stopnet_loss: 0.004516851156949997  (0.0065649047959595915)
     | > loss: 0.19274069368839264  (0.19677839577198028)
     | > align_error: 0.6219348907470703  (0.6048769310116768)

   --> STEP: 21
     | > decoder_loss: 0.44617193937301636  (0.44858052475111826)
     | > postnet_loss: 0.3034783601760864  (0.3117399215698242)
     | > stopnet_loss: 0.003961500711739063  (0.006440933172901471)
     | > loss: 0.19137407839298248  (0.19652104732536135)
     | > align_error: 0.558916300535202  (0.6026883295604161)

   --> STEP: 22
     | > decoder_loss: 0.4484473466873169  (0.44857447120276367)
     | > postnet_loss: 0.3066196143627167  (0.3115071803331375)
     | > stopnet_loss: 0.00482866121456027  (0.0063676480838859625)
     | > loss: 0.19359540939331055  (0.1963880637829954)
     | > align_error: 0.624458372592926  (0.6036778769709847)

   --> STEP: 23
     | > decoder_loss: 0.42142266035079956  (0.4473939576874609)
     | > postnet_loss: 0.29395440220832825  (0.31074401606684143)
     | > stopnet_loss: 0.004464139696210623  (0.006284886849639209)
     | > loss: 0.183308407664299  (0.19581938308218252)
     | > align_error: 0.5660155713558197  (0.6020403854224993)

   --> STEP: 24
     | > decoder_loss: 0.45579907298088074  (0.4477441708246867)
     | > postnet_loss: 0.3101615607738495  (0.31071974709630007)
     | > stopnet_loss: 0.004421955440193415  (0.006207264707578967)
     | > loss: 0.19591210782527924  (0.19582324661314487)
     | > align_error: 0.5785520076751709  (0.6010617030163606)

   --> STEP: 25
     | > decoder_loss: 0.4545632600784302  (0.4480169343948364)
     | > postnet_loss: 0.30703815817832947  (0.3105724835395812)
     | > stopnet_loss: 0.003678788896650076  (0.006106125675141811)
     | > loss: 0.19407914578914642  (0.19575348258018493)
     | > align_error: 0.5563359260559082  (0.5992726719379425)

   --> STEP: 26
     | > decoder_loss: 0.4303272068500519  (0.44733656025849855)
     | > postnet_loss: 0.2957661747932434  (0.3100030101262605)
     | > stopnet_loss: 0.004324542358517647  (0.0060376032398870355)
     | > loss: 0.18584789335727692  (0.19537249837930387)
     | > align_error: 0.5456634163856506  (0.5972107774936236)

   --> STEP: 27
     | > decoder_loss: 0.42702430486679077  (0.4465842545032501)
     | > postnet_loss: 0.2911498248577118  (0.3093047440052032)
     | > stopnet_loss: 0.0038865620736032724  (0.005957935048543193)
     | > loss: 0.18343009054660797  (0.1949301869780929)
     | > align_error: 0.5397418439388275  (0.5950822984730756)

   --> STEP: 28
     | > decoder_loss: 0.43269088864326477  (0.4460880628653935)
     | > postnet_loss: 0.29560211300849915  (0.30881536432674944)
     | > stopnet_loss: 0.003931455779820681  (0.00588556078894596)
     | > loss: 0.18600471317768097  (0.1946114200566496)
     | > align_error: 0.5654501616954803  (0.5940240078738758)

   --> STEP: 29
     | > decoder_loss: 0.42787328362464905  (0.44545996702950574)
     | > postnet_loss: 0.2920968234539032  (0.308238862917341)
     | > stopnet_loss: 0.0035602031275629997  (0.00580537604200172)
     | > loss: 0.18355272710323334  (0.19423008581687665)
     | > align_error: 0.5395088493824005  (0.5921441748224455)

   --> STEP: 30
     | > decoder_loss: 0.4282971918582916  (0.44488787452379863)
     | > postnet_loss: 0.2928485870361328  (0.3077258537213007)
     | > stopnet_loss: 0.002794010331854224  (0.005704997184996803)
     | > loss: 0.18308044970035553  (0.19385843127965927)
     | > align_error: 0.5320889949798584  (0.5901423354943593)

   --> STEP: 31
     | > decoder_loss: 0.4230152368545532  (0.44418230556672617)
     | > postnet_loss: 0.29076871275901794  (0.3071788491741303)
     | > stopnet_loss: 0.003672822844237089  (0.005639443174004555)
     | > loss: 0.18211881816387177  (0.19347973408237581)
     | > align_error: 0.5533414781093597  (0.5889552110625852)

   --> STEP: 32
     | > decoder_loss: 0.43694084882736206  (0.44395601004362106)
     | > postnet_loss: 0.29775264859199524  (0.30688428040593857)
     | > stopnet_loss: 0.003801812184974551  (0.005582017205597367)
     | > loss: 0.18747518956661224  (0.1932920920662582)
     | > align_error: 0.5297351479530334  (0.5871045840904117)

   --> STEP: 33
     | > decoder_loss: 0.43325597047805786  (0.4436317664204222)
     | > postnet_loss: 0.295551061630249  (0.306540849533948)
     | > stopnet_loss: 0.003994176164269447  (0.005533900810405612)
     | > loss: 0.18619593977928162  (0.193077057148471)
     | > align_error: 0.5448396503925323  (0.5858238285238092)

   --> STEP: 34
     | > decoder_loss: 0.4391157329082489  (0.44349894190535827)
     | > postnet_loss: 0.2971457540988922  (0.3062645231976228)
     | > stopnet_loss: 0.0032802107743918896  (0.0054676158093463845)
     | > loss: 0.18734557926654816  (0.19290848426959095)
     | > align_error: 0.5627007484436035  (0.585143737933215)

   --> STEP: 35
     | > decoder_loss: 0.43600910902023315  (0.44328494668006896)
     | > postnet_loss: 0.29573023319244385  (0.3059635434831891)
     | > stopnet_loss: 0.0034928962122648954  (0.005411195249429771)
     | > loss: 0.18642772734165192  (0.19272331978593554)
     | > align_error: 0.531755805015564  (0.5836183684212821)

   --> STEP: 36
     | > decoder_loss: 0.4419739842414856  (0.443248531056775)
     | > postnet_loss: 0.3003901541233063  (0.3058087271120813)
     | > stopnet_loss: 0.0036241491325199604  (0.00536155507951561)
     | > loss: 0.18921519815921783  (0.19262587196297115)
     | > align_error: 0.6324458420276642  (0.5849746871325705)

   --> STEP: 37
     | > decoder_loss: 0.4347093999385834  (0.4430177437292563)
     | > postnet_loss: 0.29671230912208557  (0.30556287797721654)
     | > stopnet_loss: 0.0035337384324520826  (0.005312154629594974)
     | > loss: 0.18638916313648224  (0.19245731226495794)
     | > align_error: 0.5171923041343689  (0.5831427308353218)

   --> STEP: 38
     | > decoder_loss: 0.4221090078353882  (0.4424675138373124)
     | > postnet_loss: 0.2894338369369507  (0.30513842952878845)
     | > stopnet_loss: 0.0031382706947624683  (0.0052549471576256975)
     | > loss: 0.1810239851474762  (0.19215643523555054)
     | > align_error: 0.5502877831459045  (0.5822781269487581)

   --> STEP: 39
     | > decoder_loss: 0.4372026324272156  (0.4423325168780791)
     | > postnet_loss: 0.2997337877750397  (0.304999848971)
     | > stopnet_loss: 0.003453314770013094  (0.00520875145537922)
     | > loss: 0.18768742680549622  (0.19204184527580553)
     | > align_error: 0.5448247790336609  (0.5813177846945249)

   --> STEP: 40
     | > decoder_loss: 0.43474122881889343  (0.4421427346765995)
     | > postnet_loss: 0.29842761158943176  (0.3048355430364608)
     | > stopnet_loss: 0.0030172369442880154  (0.005153963592601939)
     | > loss: 0.18630944192409515  (0.19189853519201278)
     | > align_error: 0.5826631188392639  (0.5813514180481434)

   --> STEP: 41
     | > decoder_loss: 0.4255256950855255  (0.44173744102803675)
     | > postnet_loss: 0.2906917333602905  (0.30449057206874935)
     | > stopnet_loss: 0.0037051073741167784  (0.0051186256360535205)
     | > loss: 0.18275946378707886  (0.19167563101140464)
     | > align_error: 0.5017675757408142  (0.5794103487235743)

   --> STEP: 42
     | > decoder_loss: 0.4299768805503845  (0.44145742768333074)
     | > postnet_loss: 0.29275432229042053  (0.3042111375502177)
     | > stopnet_loss: 0.0032520918175578117  (0.005074184354660766)
     | > loss: 0.18393489718437195  (0.19149132782504671)
     | > align_error: 0.5782045125961304  (0.5793816383395876)

   --> STEP: 43
     | > decoder_loss: 0.42960408329963684  (0.4411817685116169)
     | > postnet_loss: 0.29201748967170715  (0.30392756434374074)
     | > stopnet_loss: 0.0029171877540647984  (0.005024021643018999)
     | > loss: 0.18332257866859436  (0.19130135691443154)
     | > align_error: 0.5503165125846863  (0.5787057051824968)

   --> STEP: 44
     | > decoder_loss: 0.44754743576049805  (0.4413264427672733)
     | > postnet_loss: 0.30261486768722534  (0.30389773032881995)
     | > stopnet_loss: 0.002640379359945655  (0.004969847954767332)
     | > loss: 0.1901809573173523  (0.1912758932872252)
     | > align_error: 0.5496846437454224  (0.5780461356043815)

   --> STEP: 45
     | > decoder_loss: 0.44050511717796326  (0.44130819108751085)
     | > postnet_loss: 0.30182698369026184  (0.303851713736852)
     | > stopnet_loss: 0.0032559377141296864  (0.00493176106053094)
     | > loss: 0.18883895874023438  (0.19122173918618096)
     | > align_error: 0.5509060025215149  (0.5774430215358733)

   --> STEP: 46
     | > decoder_loss: 0.43119463324546814  (0.441088331134423)
     | > postnet_loss: 0.29322919249534607  (0.3036207893620367)
     | > stopnet_loss: 0.0031923153437674046  (0.004893947023209994)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3541264497872554 (-0.0003837997263129167)
     | > avg_decoder_loss: 0.4372701161738598 (+0.0001433166590604218)
     | > avg_postnet_loss: 0.30050764165141364 (-0.0009754977443001689)
     | > avg_stopnet_loss: 0.0043397264971369596 (+1.7663799085174993e-05)
     | > avg_loss: 0.1887841678478501 (-0.00019037994471463038)
     | > avg_align_error: 0.5702664201909844 (-6.826899268408404e-05)


 > EPOCH: 156/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 20:11:10)

   --> TIME: 2025-12-28 20:11:39 -- STEP: 19/150 -- GLOBAL_STEP: 23575
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46925994753837585  (0.46169672514262955)
     | > postnet_loss: 0.39370405673980713  (0.39085487942946584)
     | > stopnet_loss: 0.007930374704301357  (0.010589650317438339)
     | > loss: 0.22367137670516968  (0.22372754780869736)
     | > align_error: 0.6349410712718964  (0.6797481728227515)
     | > grad_norm: tensor(0.2440, device='cuda:0')  (tensor(0.2621, device='cuda:0'))
     | > step_time: 0.7225  (0.6109512228714792)
     | > loader_time: 0.9401  (0.8304243966152793)


   --> TIME: 2025-12-28 20:12:29 -- STEP: 44/150 -- GLOBAL_STEP: 23600
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48278048634529114  (0.47025099328973075)
     | > postnet_loss: 0.39746958017349243  (0.39423352954062546)
     | > stopnet_loss: 0.005084758158773184  (0.007908596001057462)
     | > loss: 0.2251472771167755  (0.2240297245708379)
     | > align_error: 0.5866952538490295  (0.6495035954497077)
     | > grad_norm: tensor(0.1777, device='cuda:0')  (tensor(0.2496, device='cuda:0'))
     | > step_time: 1.2118  (0.856334003535184)
     | > loader_time: 1.0294  (0.9104098786007274)


   --> TIME: 2025-12-28 20:13:33 -- STEP: 69/150 -- GLOBAL_STEP: 23625
     | > current_lr: 1e-05  (1.0000000000000016e-05)
     | > decoder_loss: 0.4845168888568878  (0.4742851019769475)
     | > postnet_loss: 0.39597707986831665  (0.3946587503820226)
     | > stopnet_loss: 0.004311068914830685  (0.00660154979635516)
     | > loss: 0.22443456947803497  (0.2238375112630319)
     | > align_error: 0.6084018647670746  (0.6374085165452266)
     | > grad_norm: tensor(0.2216, device='cuda:0')  (tensor(0.2364, device='cuda:0'))
     | > step_time: 1.5414  (1.051048593244691)
     | > loader_time: 1.2706  (1.005277875540913)


   --> TIME: 2025-12-28 20:14:56 -- STEP: 94/150 -- GLOBAL_STEP: 23650
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4778892397880554  (0.47578618818141044)
     | > postnet_loss: 0.3910580277442932  (0.39402691607779644)
     | > stopnet_loss: 0.0038520339876413345  (0.005851221501212962)
     | > loss: 0.22108885645866394  (0.22330449680064587)
     | > align_error: 0.6152376532554626  (0.6324283350655375)
     | > grad_norm: tensor(0.2120, device='cuda:0')  (tensor(0.2279, device='cuda:0'))
     | > step_time: 1.9591  (1.2156525419113486)
     | > loader_time: 1.7526  (1.1679189179805998)


   --> TIME: 2025-12-28 20:16:25 -- STEP: 119/150 -- GLOBAL_STEP: 23675
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.47882169485092163  (0.4771464018761611)
     | > postnet_loss: 0.3900547921657562  (0.39370906653524446)
     | > stopnet_loss: 0.0030743146780878305  (0.00532556273739691)
     | > loss: 0.22029343247413635  (0.223039429227845)
     | > align_error: 0.6118572354316711  (0.6272372994102352)
     | > grad_norm: tensor(0.1317, device='cuda:0')  (tensor(0.2172, device='cuda:0'))
     | > step_time: 1.8934  (1.348937499422987)
     | > loader_time: 1.8814  (1.2836621288491898)


   --> TIME: 2025-12-28 20:18:04 -- STEP: 144/150 -- GLOBAL_STEP: 23700
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4823225736618042  (0.47836142695612377)
     | > postnet_loss: 0.3900700807571411  (0.39344812784757877)
     | > stopnet_loss: 0.0028295652009546757  (0.004944678814758338)
     | > loss: 0.22092773020267487  (0.22289706663125092)
     | > align_error: 0.5935625731945038  (0.6232792716473344)
     | > grad_norm: tensor(0.1754, device='cuda:0')  (tensor(0.2136, device='cuda:0'))
     | > step_time: 2.4417  (1.4892183889945347)
     | > loader_time: 2.0557  (1.3758235971132915)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4600275754928589  (0.4600275754928589)
     | > postnet_loss: 0.33568722009658813  (0.33568722009658813)
     | > stopnet_loss: 0.012156830169260502  (0.012156830169260502)
     | > loss: 0.21108552813529968  (0.21108552813529968)
     | > align_error: 0.7188083231449127  (0.7188083231449127)

   --> STEP: 1
     | > decoder_loss: 0.4416004419326782  (0.4416004419326782)
     | > postnet_loss: 0.323937326669693  (0.323937326669693)
     | > stopnet_loss: 0.009586859494447708  (0.009586859494447708)
     | > loss: 0.20097129046916962  (0.20097129046916962)
     | > align_error: 0.6590321660041809  (0.6590321660041809)

   --> STEP: 2
     | > decoder_loss: 0.4368281662464142  (0.4392143040895462)
     | > postnet_loss: 0.31361454725265503  (0.318775936961174)
     | > stopnet_loss: 0.010945658199489117  (0.010266258846968412)
     | > loss: 0.1985563486814499  (0.19976381957530975)
     | > align_error: 0.6551162600517273  (0.6570742130279541)

   --> STEP: 3
     | > decoder_loss: 0.43967780470848083  (0.43936880429585773)
     | > postnet_loss: 0.3132566809654236  (0.3169361849625905)
     | > stopnet_loss: 0.00816415436565876  (0.009565557353198528)
     | > loss: 0.19639776647090912  (0.19864180187384287)
     | > align_error: 0.7345631718635559  (0.6829038659731547)

   --> STEP: 4
     | > decoder_loss: 0.446149080991745  (0.44106387346982956)
     | > postnet_loss: 0.3220510184764862  (0.31821489334106445)
     | > stopnet_loss: 0.008147799409925938  (0.00921111786738038)
     | > loss: 0.20019783079624176  (0.1990308091044426)
     | > align_error: 0.6028024554252625  (0.6628785133361816)

   --> STEP: 5
     | > decoder_loss: 0.4270583987236023  (0.4382627785205841)
     | > postnet_loss: 0.3036990761756897  (0.3153117299079895)
     | > stopnet_loss: 0.008048144169151783  (0.008978523127734662)
     | > loss: 0.1907375156879425  (0.1973721504211426)
     | > align_error: 0.6415507793426514  (0.6586129665374756)

   --> STEP: 6
     | > decoder_loss: 0.44459497928619385  (0.4393181453148524)
     | > postnet_loss: 0.31618741154670715  (0.31545767684777576)
     | > stopnet_loss: 0.007225233130156994  (0.008686308128138384)
     | > loss: 0.19742082059383392  (0.19738026211659113)
     | > align_error: 0.5934979617595673  (0.6477604657411575)

   --> STEP: 7
     | > decoder_loss: 0.4551740884780884  (0.44158328005245756)
     | > postnet_loss: 0.31539398431777954  (0.31544857791491915)
     | > stopnet_loss: 0.006180396769195795  (0.008328320791146584)
     | > loss: 0.19882240891456604  (0.1975862830877304)
     | > align_error: 0.5784223675727844  (0.6378550231456757)

   --> STEP: 8
     | > decoder_loss: 0.4477737545967102  (0.4423570893704891)
     | > postnet_loss: 0.3154047131538391  (0.31544309481978416)
     | > stopnet_loss: 0.007028530351817608  (0.008165846986230463)
     | > loss: 0.1978231519460678  (0.19761589169502258)
     | > align_error: 0.5740637481212616  (0.6298811137676239)

   --> STEP: 9
     | > decoder_loss: 0.4481354057788849  (0.44299912452697754)
     | > postnet_loss: 0.31649351119995117  (0.31555980775091386)
     | > stopnet_loss: 0.00651912484318018  (0.007982877859224876)
     | > loss: 0.19767634570598602  (0.19762260880735186)
     | > align_error: 0.5909009873867035  (0.6255499886141883)

   --> STEP: 10
     | > decoder_loss: 0.4723246991634369  (0.4459316819906235)
     | > postnet_loss: 0.3302467465400696  (0.31702850162982943)
     | > stopnet_loss: 0.005564191844314337  (0.007741009257733822)
     | > loss: 0.2062070518732071  (0.19848105311393738)
     | > align_error: 0.5832536816596985  (0.6213203579187393)

   --> STEP: 11
     | > decoder_loss: 0.4582943022251129  (0.44705555655739526)
     | > postnet_loss: 0.31931233406066895  (0.3172361227599057)
     | > stopnet_loss: 0.005904145073145628  (0.00757402160458944)
     | > loss: 0.2003057897090912  (0.19864693825895136)
     | > align_error: 0.5945912301540375  (0.6188904372128573)

   --> STEP: 12
     | > decoder_loss: 0.45542386174201965  (0.4477529153227806)
     | > postnet_loss: 0.3135703504085541  (0.3169306417306264)
     | > stopnet_loss: 0.007804553024470806  (0.007593232556246221)
     | > loss: 0.2000531107187271  (0.198764119297266)
     | > align_error: 0.5869864821434021  (0.6162317742904028)

   --> STEP: 13
     | > decoder_loss: 0.44484132528305054  (0.447528946858186)
     | > postnet_loss: 0.31311389803886414  (0.3166370460620293)
     | > stopnet_loss: 0.005362663418054581  (0.007421650314846864)
     | > loss: 0.19485145807266235  (0.19846314535691187)
     | > align_error: 0.5850627422332764  (0.6138341564398545)

   --> STEP: 14
     | > decoder_loss: 0.4574364721775055  (0.4482366272381374)
     | > postnet_loss: 0.31751367449760437  (0.3166996623788561)
     | > stopnet_loss: 0.004898634273558855  (0.007241434883326292)
     | > loss: 0.19863617420196533  (0.19847550456013)
     | > align_error: 0.5547987222671509  (0.6096173397132328)

   --> STEP: 15
     | > decoder_loss: 0.45236366987228394  (0.44851176341374716)
     | > postnet_loss: 0.3146034777164459  (0.3165599167346954)
     | > stopnet_loss: 0.004982933402061462  (0.007090868117908637)
     | > loss: 0.19672472774982452  (0.19835878610610963)
     | > align_error: 0.5882624089717865  (0.6081936776638031)

   --> STEP: 16
     | > decoder_loss: 0.4526336193084717  (0.44876937940716743)
     | > postnet_loss: 0.3088248074054718  (0.31607647240161896)
     | > stopnet_loss: 0.005253723822534084  (0.006976046599447727)
     | > loss: 0.19561831653118134  (0.1981875067576766)
     | > align_error: 0.6055517494678497  (0.608028557151556)

   --> STEP: 17
     | > decoder_loss: 0.46066153049468994  (0.4494689177064335)
     | > postnet_loss: 0.31774917244911194  (0.3161748665220597)
     | > stopnet_loss: 0.004766800906509161  (0.006846090970451341)
     | > loss: 0.19936947524547577  (0.19825703431578243)
     | > align_error: 0.5582743585109711  (0.6051018395844627)

   --> STEP: 18
     | > decoder_loss: 0.45240625739097595  (0.4496321032444636)
     | > postnet_loss: 0.3087692856788635  (0.3157634453641044)
     | > stopnet_loss: 0.0052140685729682446  (0.006755423059480058)
     | > loss: 0.1955079436302185  (0.19810430705547333)
     | > align_error: 0.6037853062152863  (0.6050286988417307)

   --> STEP: 19
     | > decoder_loss: 0.4506042003631592  (0.44968326625071076)
     | > postnet_loss: 0.30916011333465576  (0.31541590157308075)
     | > stopnet_loss: 0.004694991745054722  (0.006646979306089251)
     | > loss: 0.19463607668876648  (0.19792176861512034)
     | > align_error: 0.5990117192268372  (0.6047120157041048)

   --> STEP: 20
     | > decoder_loss: 0.446533739566803  (0.4495257899165154)
     | > postnet_loss: 0.30439743399620056  (0.31486497819423676)
     | > stopnet_loss: 0.0044733574613928795  (0.006538298213854432)
     | > loss: 0.19220614433288574  (0.1976359874010086)
     | > align_error: 0.622621089220047  (0.6056074693799018)

   --> STEP: 21
     | > decoder_loss: 0.4454491436481476  (0.4493316639037359)
     | > postnet_loss: 0.3047449290752411  (0.3143830710933322)
     | > stopnet_loss: 0.003940027207136154  (0.0064145710230583235)
     | > loss: 0.19148854911327362  (0.1973432522444498)
     | > align_error: 0.5594936013221741  (0.6034115709009624)

   --> STEP: 22
     | > decoder_loss: 0.4471220076084137  (0.4492312249812213)
     | > postnet_loss: 0.30710411071777344  (0.31405220925807953)
     | > stopnet_loss: 0.004807352554053068  (0.0063415156381035395)
     | > loss: 0.19336387515068054  (0.1971623714674603)
     | > align_error: 0.6251628994941711  (0.6044002676551993)

   --> STEP: 23
     | > decoder_loss: 0.42021843791007996  (0.44796979945638904)
     | > postnet_loss: 0.29459381103515625  (0.31320619194403937)
     | > stopnet_loss: 0.0044298311695456505  (0.006258398922079284)
     | > loss: 0.18313290178775787  (0.19655239452486453)
     | > align_error: 0.5668928623199463  (0.6027695109014927)

   --> STEP: 24
     | > decoder_loss: 0.45381924510002136  (0.44821352635820705)
     | > postnet_loss: 0.3099827766418457  (0.31307188297311467)
     | > stopnet_loss: 0.004407912027090788  (0.006181295301454763)
     | > loss: 0.19535842537879944  (0.19650264581044516)
     | > align_error: 0.5793740749359131  (0.6017947010695935)

   --> STEP: 25
     | > decoder_loss: 0.4533420205116272  (0.4484186661243439)
     | > postnet_loss: 0.3074820041656494  (0.31284828782081603)
     | > stopnet_loss: 0.00366388657130301  (0.006080598952248693)
     | > loss: 0.19386988878250122  (0.1963973355293274)
     | > align_error: 0.5574294030666351  (0.6000200891494752)

   --> STEP: 26
     | > decoder_loss: 0.42873987555503845  (0.44766178956398595)
     | > postnet_loss: 0.2964005768299103  (0.3122156835519351)
     | > stopnet_loss: 0.0043071722611784935  (0.006012390233361377)
     | > loss: 0.18559227883815765  (0.19598175642582086)
     | > align_error: 0.5464499592781067  (0.5979596995390379)

   --> STEP: 27
     | > decoder_loss: 0.42573556303977966  (0.4468497071001265)
     | > postnet_loss: 0.29131439328193665  (0.31144156169008325)
     | > stopnet_loss: 0.0038738080766052008  (0.005933183486814852)
     | > loss: 0.18313629925251007  (0.19550599875273528)
     | > align_error: 0.5405880510807037  (0.5958348236702107)

   --> STEP: 28
     | > decoder_loss: 0.43165862560272217  (0.4463071684752192)
     | > postnet_loss: 0.29626160860061646  (0.3108994205083166)
     | > stopnet_loss: 0.003897256450727582  (0.0058604718069545925)
     | > loss: 0.18587730824947357  (0.19516211694904737)
     | > align_error: 0.566110223531723  (0.5947732308081218)

   --> STEP: 29
     | > decoder_loss: 0.4268566966056824  (0.44563646254868344)
     | > postnet_loss: 0.2929987907409668  (0.3102821574128907)
     | > stopnet_loss: 0.0035451131407171488  (0.005780631852946405)
     | > loss: 0.1835089921951294  (0.19476028506098123)
     | > align_error: 0.5400678217411041  (0.5928868373920178)

   --> STEP: 30
     | > decoder_loss: 0.4280904233455658  (0.4450515945752462)
     | > postnet_loss: 0.29411983489990234  (0.3097434133291245)
     | > stopnet_loss: 0.002783178584650159  (0.0056807167440031964)
     | > loss: 0.18333575129508972  (0.19437946726878483)
     | > align_error: 0.5331704616546631  (0.5908962915341059)

   --> STEP: 31
     | > decoder_loss: 0.4230145812034607  (0.4443407231761563)
     | > postnet_loss: 0.29156920313835144  (0.3091571484842608)
     | > stopnet_loss: 0.00366015313193202  (0.005615537272646061)
     | > loss: 0.18230609595775604  (0.19399000367810648)
     | > align_error: 0.5548160076141357  (0.5897324114076553)

   --> STEP: 32
     | > decoder_loss: 0.43600139021873474  (0.4440801190212369)
     | > postnet_loss: 0.29847607016563416  (0.3088233647868037)
     | > stopnet_loss: 0.0037848171778023243  (0.005558327269682195)
     | > loss: 0.18740418553352356  (0.19378419686108828)
     | > align_error: 0.5306669473648071  (0.5878866156563163)

   --> STEP: 33
     | > decoder_loss: 0.43175196647644043  (0.44370653864109155)
     | > postnet_loss: 0.2955264747142792  (0.30842042872399994)
     | > stopnet_loss: 0.003987333737313747  (0.005510721405064969)
     | > loss: 0.18580694496631622  (0.1935424619551861)
     | > align_error: 0.5458081960678101  (0.5866115120324221)

   --> STEP: 34
     | > decoder_loss: 0.43688276410102844  (0.4435058393899132)
     | > postnet_loss: 0.29660558700561523  (0.30807293337934155)
     | > stopnet_loss: 0.0032529886811971664  (0.005444317501421799)
     | > loss: 0.18662506341934204  (0.19333900905707302)
     | > align_error: 0.5635371804237366  (0.585932855220402)

   --> STEP: 35
     | > decoder_loss: 0.43504849076271057  (0.44326420085770746)
     | > postnet_loss: 0.29642999172210693  (0.30774027790342057)
     | > stopnet_loss: 0.0034998757764697075  (0.005388762023566025)
     | > loss: 0.18636949360370636  (0.1931398800441197)
     | > align_error: 0.5325861573219299  (0.5844086638518742)

   --> STEP: 36
     | > decoder_loss: 0.440679132938385  (0.44319239341550404)
     | > postnet_loss: 0.3005387783050537  (0.3075402362479104)
     | > stopnet_loss: 0.003626180114224553  (0.005339801414973207)
     | > loss: 0.1889306604862213  (0.1930229572786225)
     | > align_error: 0.6332580149173737  (0.5857655902703603)

   --> STEP: 37
     | > decoder_loss: 0.43389347195625305  (0.44294107121390264)
     | > postnet_loss: 0.2974832057952881  (0.30726842461405574)
     | > stopnet_loss: 0.00352386268787086  (0.005290721989916387)
     | > loss: 0.18636801838874817  (0.19284309406538266)
     | > align_error: 0.5183889865875244  (0.583944600981635)

   --> STEP: 38
     | > decoder_loss: 0.4210546910762787  (0.4423651138418599)
     | > postnet_loss: 0.28981685638427734  (0.30680917281853526)
     | > stopnet_loss: 0.003119241213425994  (0.005233577758956113)
     | > loss: 0.18083713948726654  (0.19252714789227435)
     | > align_error: 0.5514125525951385  (0.5830884944451483)

   --> STEP: 39
     | > decoder_loss: 0.43704459071159363  (0.44222869017185307)
     | > postnet_loss: 0.3008419871330261  (0.30665616805736834)
     | > stopnet_loss: 0.0034378855489194393  (0.0051875343689551726)
     | > loss: 0.18790952861309052  (0.1924087473979363)
     | > align_error: 0.5457693338394165  (0.5821315928911552)

   --> STEP: 40
     | > decoder_loss: 0.4341542422771454  (0.4420268289744854)
     | > postnet_loss: 0.29932883381843567  (0.30647298470139506)
     | > stopnet_loss: 0.0030115360859781504  (0.0051331344118807475)
     | > loss: 0.18638230860233307  (0.19225808642804623)
     | > align_error: 0.5833389163017273  (0.5821617759764195)

   --> STEP: 41
     | > decoder_loss: 0.4247358739376068  (0.44160509836382983)
     | > postnet_loss: 0.29160913825035095  (0.3061104518611257)
     | > stopnet_loss: 0.0037051797844469547  (0.0050983062502360215)
     | > loss: 0.18279142677783966  (0.19202719229023632)
     | > align_error: 0.5026200413703918  (0.5802217336689554)

   --> STEP: 42
     | > decoder_loss: 0.4294639229774475  (0.44131602275939213)
     | > postnet_loss: 0.2933689057826996  (0.30580708171640125)
     | > stopnet_loss: 0.003255576128140092  (0.005054431723519452)
     | > loss: 0.18396377563476562  (0.19183520617939176)
     | > align_error: 0.5789743065834045  (0.5801920330240613)

   --> STEP: 43
     | > decoder_loss: 0.428352415561676  (0.44101454352223596)
     | > postnet_loss: 0.2921493947505951  (0.3054894610892895)
     | > stopnet_loss: 0.0029014761094003916  (0.00500436298830738)
     | > loss: 0.18302692472934723  (0.19163036242473958)
     | > align_error: 0.5511499345302582  (0.5795166353846706)

   --> STEP: 44
     | > decoder_loss: 0.4471292793750763  (0.4411535147916187)
     | > postnet_loss: 0.30358806252479553  (0.305446247485551)
     | > stopnet_loss: 0.002622759435325861  (0.0049502356348305274)
     | > loss: 0.19030208885669708  (0.19160017438910223)
     | > align_error: 0.5506317019462585  (0.5788601596247067)

   --> STEP: 45
     | > decoder_loss: 0.43992719054222107  (0.44112626314163206)
     | > postnet_loss: 0.3025420606136322  (0.30538170999950837)
     | > stopnet_loss: 0.0032555353827774525  (0.004912575629229348)
     | > loss: 0.18887284398078918  (0.19153956704669528)
     | > align_error: 0.5520617365837097  (0.5782646391126846)

   --> STEP: 46
     | > decoder_loss: 0.43018096685409546  (0.44088832191799)
     | > postnet_loss: 0.2937750816345215  (0.30512939199157385)
     | > stopnet_loss: 0.003182449610903859  (0.004874964194048359)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3445747368263476 (-0.009551712960907788)
     | > avg_decoder_loss: 0.4371153034947135 (-0.00015481267914629893)
     | > avg_postnet_loss: 0.3020363933209217 (+0.001528751669508055)
     | > avg_stopnet_loss: 0.004324623288332737 (-1.5103208804222862e-05)
     | > avg_loss: 0.18911254586595477 (+0.0003283780181046747)
     | > avg_align_error: 0.5711343776095997 (+0.0008679574186153394)


 > EPOCH: 157/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 20:20:27)

   --> TIME: 2025-12-28 20:20:53 -- STEP: 18/150 -- GLOBAL_STEP: 23725
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4711018204689026  (0.461824001537429)
     | > postnet_loss: 0.3975808024406433  (0.391195696261194)
     | > stopnet_loss: 0.008058946579694748  (0.010460354646460878)
     | > loss: 0.22522960603237152  (0.2237152788374159)
     | > align_error: 0.703826367855072  (0.6832914037836922)
     | > grad_norm: tensor(0.2229, device='cuda:0')  (tensor(0.2802, device='cuda:0'))
     | > step_time: 0.7498  (0.6013702419069078)
     | > loader_time: 0.8115  (0.8143622477849325)


   --> TIME: 2025-12-28 20:21:44 -- STEP: 43/150 -- GLOBAL_STEP: 23750
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4841236174106598  (0.4705063970976098)
     | > postnet_loss: 0.39962485432624817  (0.3944603752258212)
     | > stopnet_loss: 0.005316901486366987  (0.007858907164962485)
     | > loss: 0.22625401616096497  (0.22410060014835623)
     | > align_error: 0.6090263426303864  (0.6515579438486764)
     | > grad_norm: tensor(0.2968, device='cuda:0')  (tensor(0.2375, device='cuda:0'))
     | > step_time: 1.2033  (0.8326296362766)
     | > loader_time: 1.0456  (0.9296803585318631)


   --> TIME: 2025-12-28 20:22:48 -- STEP: 68/150 -- GLOBAL_STEP: 23775
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.4866780936717987  (0.4741481976474033)
     | > postnet_loss: 0.3987671434879303  (0.3946179594187176)
     | > stopnet_loss: 0.004233607556670904  (0.00657256187268478)
     | > loss: 0.2255949229001999  (0.22376410137204564)
     | > align_error: 0.6134200096130371  (0.6385000146487178)
     | > grad_norm: tensor(0.2273, device='cuda:0')  (tensor(0.2195, device='cuda:0'))
     | > step_time: 1.5819  (1.030640794950373)
     | > loader_time: 1.2484  (1.021627871429219)


   --> TIME: 2025-12-28 20:24:06 -- STEP: 93/150 -- GLOBAL_STEP: 23800
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47657355666160583  (0.4758008788990718)
     | > postnet_loss: 0.39059123396873474  (0.3940577619178321)
     | > stopnet_loss: 0.0038108413573354483  (0.005826570176249068)
     | > loss: 0.22060203552246094  (0.22329123013763016)
     | > align_error: 0.6022818088531494  (0.6330955150306862)
     | > grad_norm: tensor(0.1681, device='cuda:0')  (tensor(0.2151, device='cuda:0'))
     | > step_time: 1.6862  (1.2019442512143044)
     | > loader_time: 1.5716  (1.1369322346102806)


   --> TIME: 2025-12-28 20:25:32 -- STEP: 118/150 -- GLOBAL_STEP: 23825
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4906194806098938  (0.4772340339624276)
     | > postnet_loss: 0.3984910547733307  (0.39378697488267544)
     | > stopnet_loss: 0.0030961933080106974  (0.005311748456857088)
     | > loss: 0.22537383437156677  (0.22306700088715148)
     | > align_error: 0.6030334830284119  (0.6273994880207512)
     | > grad_norm: tensor(0.1933, device='cuda:0')  (tensor(0.2108, device='cuda:0'))
     | > step_time: 2.0181  (1.3398640721531239)
     | > loader_time: 1.5917  (1.235318432419987)


   --> TIME: 2025-12-28 20:27:16 -- STEP: 143/150 -- GLOBAL_STEP: 23850
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4853064715862274  (0.47845289048615036)
     | > postnet_loss: 0.39301303029060364  (0.3935347735048174)
     | > stopnet_loss: 0.003009841311722994  (0.004923502159129071)
     | > loss: 0.22258971631526947  (0.22292041820246022)
     | > align_error: 0.5726656019687653  (0.623523815528496)
     | > grad_norm: tensor(0.2940, device='cuda:0')  (tensor(0.2087, device='cuda:0'))
     | > step_time: 2.4099  (1.4771102825244824)
     | > loader_time: 2.3256  (1.3745255453603251)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.46044519543647766  (0.46044519543647766)
     | > postnet_loss: 0.3373700678348541  (0.3373700678348541)
     | > stopnet_loss: 0.012058430351316929  (0.012058430351316929)
     | > loss: 0.2115122526884079  (0.2115122526884079)
     | > align_error: 0.7184547781944275  (0.7184547781944275)

   --> STEP: 1
     | > decoder_loss: 0.4425295293331146  (0.4425295293331146)
     | > postnet_loss: 0.3262394368648529  (0.3262394368648529)
     | > stopnet_loss: 0.009672997519373894  (0.009672997519373894)
     | > loss: 0.20186524093151093  (0.20186524093151093)
     | > align_error: 0.6584484577178955  (0.6584484577178955)

   --> STEP: 2
     | > decoder_loss: 0.4379347860813141  (0.44023215770721436)
     | > postnet_loss: 0.3155054748058319  (0.3208724558353424)
     | > stopnet_loss: 0.010946131311357021  (0.010309564415365458)
     | > loss: 0.1993061900138855  (0.2005857154726982)
     | > align_error: 0.6548710465431213  (0.6566597521305084)

   --> STEP: 3
     | > decoder_loss: 0.44295331835746765  (0.44113921125729877)
     | > postnet_loss: 0.31623879075050354  (0.3193279008070628)
     | > stopnet_loss: 0.008148604072630405  (0.00958924430112044)
     | > loss: 0.19794663786888123  (0.19970602293809256)
     | > align_error: 0.7348152101039886  (0.6827115714550018)

   --> STEP: 4
     | > decoder_loss: 0.4463754892349243  (0.44244828075170517)
     | > postnet_loss: 0.323679119348526  (0.3204157054424286)
     | > stopnet_loss: 0.008164106868207455  (0.009232959942892194)
     | > loss: 0.200677752494812  (0.19994895532727242)
     | > align_error: 0.6026177108287811  (0.6626881062984467)

   --> STEP: 5
     | > decoder_loss: 0.42762288451194763  (0.43948320150375364)
     | > postnet_loss: 0.3050049841403961  (0.3173335611820221)
     | > stopnet_loss: 0.007983881048858166  (0.008983144164085388)
     | > loss: 0.19114084541797638  (0.19818733334541322)
     | > align_error: 0.6409987211227417  (0.6583502292633057)

   --> STEP: 6
     | > decoder_loss: 0.4451504945755005  (0.4404277503490448)
     | > postnet_loss: 0.3177759349346161  (0.3174072901407878)
     | > stopnet_loss: 0.0071503943763673306  (0.008677685866132379)
     | > loss: 0.1978820115327835  (0.1981364463766416)
     | > align_error: 0.5931360721588135  (0.6474812030792236)

   --> STEP: 7
     | > decoder_loss: 0.45498234033584595  (0.4425069774900164)
     | > postnet_loss: 0.3165634572505951  (0.31728674258504597)
     | > stopnet_loss: 0.0061678714118897915  (0.008319140944097723)
     | > loss: 0.1990543156862259  (0.19826757056372507)
     | > align_error: 0.5780382752418518  (0.6375607848167419)

   --> STEP: 8
     | > decoder_loss: 0.45127010345458984  (0.4436023682355881)
     | > postnet_loss: 0.31894662976264954  (0.3174942284822464)
     | > stopnet_loss: 0.007503906264901161  (0.008217236609198153)
     | > loss: 0.20005808770656586  (0.19849138520658016)
     | > align_error: 0.5743855834007263  (0.62966388463974)

   --> STEP: 9
     | > decoder_loss: 0.4467815160751343  (0.44395560688442653)
     | > postnet_loss: 0.31681060791015625  (0.31741827064090306)
     | > stopnet_loss: 0.006612544879317284  (0.008038937528100278)
     | > loss: 0.19751057028770447  (0.19838240577114952)
     | > align_error: 0.5901898741722107  (0.6252778834766812)

   --> STEP: 10
     | > decoder_loss: 0.47685927152633667  (0.44724597334861754)
     | > postnet_loss: 0.3341040313243866  (0.3190868467092514)
     | > stopnet_loss: 0.005809369962662458  (0.007815980771556496)
     | > loss: 0.20855018496513367  (0.19939918369054793)
     | > align_error: 0.5854395031929016  (0.6212940454483032)

   --> STEP: 11
     | > decoder_loss: 0.4595337212085724  (0.44836304133588617)
     | > postnet_loss: 0.3210769295692444  (0.31926776333288714)
     | > stopnet_loss: 0.005886461585760117  (0.0076405699364840984)
     | > loss: 0.2010391354560852  (0.19954827021468768)
     | > align_error: 0.5942271947860718  (0.6188334226608276)

   --> STEP: 12
     | > decoder_loss: 0.4558067321777344  (0.4489833489060402)
     | > postnet_loss: 0.31504637002944946  (0.3189159805576007)
     | > stopnet_loss: 0.007881944067776203  (0.0076606844474251075)
     | > loss: 0.2005952149629593  (0.19963551561037698)
     | > align_error: 0.5865689218044281  (0.6161447142561277)

   --> STEP: 13
     | > decoder_loss: 0.4459346532821655  (0.4487488338580498)
     | > postnet_loss: 0.31510427594184875  (0.31862277251023513)
     | > stopnet_loss: 0.0055666337721049786  (0.007499603626246636)
     | > loss: 0.19582635164260864  (0.19934250299747175)
     | > align_error: 0.5851477384567261  (0.6137603315023276)

   --> STEP: 14
     | > decoder_loss: 0.45892807841300964  (0.44947592275483267)
     | > postnet_loss: 0.31937146186828613  (0.31867625032152447)
     | > stopnet_loss: 0.004883570596575737  (0.007312744124127286)
     | > loss: 0.19945846498012543  (0.1993507859962327)
     | > align_error: 0.5541641116142273  (0.6095034586531776)

   --> STEP: 15
     | > decoder_loss: 0.45435163378715515  (0.4498009701569875)
     | > postnet_loss: 0.3163779377937317  (0.3185230294863383)
     | > stopnet_loss: 0.004970246460288763  (0.007156577613204718)
     | > loss: 0.1976526379585266  (0.1992375761270523)
     | > align_error: 0.5879450142383575  (0.6080662290255229)

   --> STEP: 16
     | > decoder_loss: 0.4553773105144501  (0.4501494914293289)
     | > postnet_loss: 0.3111448287963867  (0.3180618919432163)
     | > stopnet_loss: 0.0052305250428617  (0.007036199327558279)
     | > loss: 0.19686107337474823  (0.1990890447050333)
     | > align_error: 0.6048954129219055  (0.6078680530190468)

   --> STEP: 17
     | > decoder_loss: 0.46044838428497314  (0.4507553086561315)
     | > postnet_loss: 0.3183807134628296  (0.3180806461502524)
     | > stopnet_loss: 0.0047775148414075375  (0.0069033355342552945)
     | > loss: 0.19948479533195496  (0.19911232415367575)
     | > align_error: 0.5574848055839539  (0.6049043325816884)

   --> STEP: 18
     | > decoder_loss: 0.4545782208442688  (0.4509676926665836)
     | > postnet_loss: 0.3107348382472992  (0.31767254571119946)
     | > stopnet_loss: 0.005185676272958517  (0.006807910019738806)
     | > loss: 0.19651393592357635  (0.19896796925200355)
     | > align_error: 0.6029629409313202  (0.6047964774900012)

   --> STEP: 19
     | > decoder_loss: 0.4540855884552002  (0.45113179244493185)
     | > postnet_loss: 0.3117663860321045  (0.3173616952017734)
     | > stopnet_loss: 0.004857953172177076  (0.0067052807119723995)
     | > loss: 0.19632095098495483  (0.19882865250110626)
     | > align_error: 0.5991811454296112  (0.6045009336973491)

   --> STEP: 20
     | > decoder_loss: 0.44850319623947144  (0.4510003626346588)
     | > postnet_loss: 0.3063451945781708  (0.3168108701705933)
     | > stopnet_loss: 0.004441986326128244  (0.006592115992680192)
     | > loss: 0.19315408170223236  (0.19854492396116258)
     | > align_error: 0.6218556463718414  (0.6053686693310738)

   --> STEP: 21
     | > decoder_loss: 0.44659844040870667  (0.45079074729056584)
     | > postnet_loss: 0.306614488363266  (0.31632532817976816)
     | > stopnet_loss: 0.003912027459591627  (0.006464492729199784)
     | > loss: 0.19221526384353638  (0.19824351157460893)
     | > align_error: 0.5588523745536804  (0.6031536076750074)

   --> STEP: 22
     | > decoder_loss: 0.44879287481307983  (0.4506999349052256)
     | > postnet_loss: 0.3091391324996948  (0.315998682921583)
     | > stopnet_loss: 0.004833661485463381  (0.006390364036302675)
     | > loss: 0.19431667029857635  (0.19806501878933472)
     | > align_error: 0.6247791051864624  (0.604136584834619)

   --> STEP: 23
     | > decoder_loss: 0.4215598702430725  (0.4494329755720885)
     | > postnet_loss: 0.2961927056312561  (0.3151375534741775)
     | > stopnet_loss: 0.004411838483065367  (0.0063043411861619224)
     | > loss: 0.1838499754667282  (0.19744697342748227)
     | > align_error: 0.5660340189933777  (0.6024799515371737)

   --> STEP: 24
     | > decoder_loss: 0.45638591051101685  (0.44972268119454384)
     | > postnet_loss: 0.31212031841278076  (0.3150118353466193)
     | > stopnet_loss: 0.0043803611770272255  (0.006224175352447976)
     | > loss: 0.19650691747665405  (0.1974078044295311)
     | > align_error: 0.578488677740097  (0.6014803151289622)

   --> STEP: 25
     | > decoder_loss: 0.45506078004837036  (0.4499362051486969)
     | > postnet_loss: 0.309506356716156  (0.3147916162014008)
     | > stopnet_loss: 0.0036480482667684555  (0.006121130269020796)
     | > loss: 0.1947898268699646  (0.19730308532714844)
     | > align_error: 0.5567589402198792  (0.5996914601325989)

   --> STEP: 26
     | > decoder_loss: 0.4299792945384979  (0.44916863166368926)
     | > postnet_loss: 0.2984461784362793  (0.31416294551812685)
     | > stopnet_loss: 0.004316231701523066  (0.0060517110933478065)
     | > loss: 0.18642260134220123  (0.19688460517388123)
     | > align_error: 0.545418918132782  (0.5976040546710675)

   --> STEP: 27
     | > decoder_loss: 0.42711541056632996  (0.4483518456971204)
     | > postnet_loss: 0.2929396331310272  (0.31337689691119724)
     | > stopnet_loss: 0.0038716543931514025  (0.005970968252599791)
     | > loss: 0.18388541042804718  (0.19640315351662813)
     | > align_error: 0.5397153794765472  (0.595460029663863)

   --> STEP: 28
     | > decoder_loss: 0.43301162123680115  (0.4478039805378233)
     | > postnet_loss: 0.29815220832824707  (0.31283315803323475)
     | > stopnet_loss: 0.003902935655787587  (0.005897109945570784)
     | > loss: 0.18669390678405762  (0.19605639470475061)
     | > align_error: 0.5652704834938049  (0.5943818315863609)

   --> STEP: 29
     | > decoder_loss: 0.427960067987442  (0.4471197076912584)
     | > postnet_loss: 0.2948229908943176  (0.3122121177870652)
     | > stopnet_loss: 0.0035543846897780895  (0.005816326316060691)
     | > loss: 0.18425016105175018  (0.19564928319947472)
     | > align_error: 0.5392685532569885  (0.5924813737129343)

   --> STEP: 30
     | > decoder_loss: 0.428691029548645  (0.44650541841983793)
     | > postnet_loss: 0.2956191599369049  (0.31165901919205985)
     | > stopnet_loss: 0.0027699267957359552  (0.0057147796653832)
     | > loss: 0.18384747207164764  (0.19525588949521383)
     | > align_error: 0.5322666168212891  (0.5904742151498794)

   --> STEP: 31
     | > decoder_loss: 0.4244343638420105  (0.44579344891732736)
     | > postnet_loss: 0.29350921511650085  (0.31107354164123535)
     | > stopnet_loss: 0.0036554099060595036  (0.005648348382824371)
     | > loss: 0.18314129114151  (0.19486509599993307)
     | > align_error: 0.5540563464164734  (0.5892994451907373)

   --> STEP: 32
     | > decoder_loss: 0.4366551637649536  (0.4455078775063157)
     | > postnet_loss: 0.3001452088356018  (0.3107320312410593)
     | > stopnet_loss: 0.003772895084694028  (0.005589740467257798)
     | > loss: 0.1879729926586151  (0.19464971777051687)
     | > align_error: 0.5296022593975067  (0.5874339081346989)

   --> STEP: 33
     | > decoder_loss: 0.43316450715065  (0.44513383598038647)
     | > postnet_loss: 0.2973458766937256  (0.3103263901941704)
     | > stopnet_loss: 0.003990031313151121  (0.005541264432284868)
     | > loss: 0.18661761283874512  (0.19440632065137228)
     | > align_error: 0.5447789430618286  (0.586141333435521)

   --> STEP: 34
     | > decoder_loss: 0.43882402777671814  (0.4449482533861609)
     | > postnet_loss: 0.2986640930175781  (0.30998338145368237)
     | > stopnet_loss: 0.003232909832149744  (0.005473371649927953)
     | > loss: 0.18760494887828827  (0.1942062803051051)
     | > align_error: 0.5626528561115265  (0.5854504958671682)

   --> STEP: 35
     | > decoder_loss: 0.4358803927898407  (0.44468917165483746)
     | > postnet_loss: 0.2980785071849823  (0.3096432421888624)
     | > stopnet_loss: 0.003497587749734521  (0.005416920681350998)
     | > loss: 0.18698731064796448  (0.19400002402918679)
     | > align_error: 0.5316935479640961  (0.5839145830699376)

   --> STEP: 36
     | > decoder_loss: 0.4424377679824829  (0.44462663266393876)
     | > postnet_loss: 0.3025793731212616  (0.3094470236036513)
     | > stopnet_loss: 0.0036093476228415966  (0.005366710318614625)
     | > loss: 0.1898636370897293  (0.19388512439197964)
     | > align_error: 0.6325690150260925  (0.5852660950687196)

   --> STEP: 37
     | > decoder_loss: 0.4347809851169586  (0.44436053408158793)
     | > postnet_loss: 0.29931434988975525  (0.30917316755732976)
     | > stopnet_loss: 0.003516710828989744  (0.005316710332408547)
     | > loss: 0.1870405375957489  (0.19370013555964907)
     | > align_error: 0.5173527002334595  (0.5834305979110099)

   --> STEP: 38
     | > decoder_loss: 0.4217095971107483  (0.4437644567928816)
     | > postnet_loss: 0.2915005385875702  (0.308708098373915)
     | > stopnet_loss: 0.003117474727332592  (0.005258835711222338)
     | > loss: 0.1814199984073639  (0.19337697405564158)
     | > align_error: 0.550377756357193  (0.5825607862911726)

   --> STEP: 39
     | > decoder_loss: 0.4376654326915741  (0.44360807155951476)
     | > postnet_loss: 0.30264052748680115  (0.3085525196332198)
     | > stopnet_loss: 0.0034352680668234825  (0.005212077566494162)
     | > loss: 0.18851175904273987  (0.19325222495274666)
     | > align_error: 0.5446276068687439  (0.5815881406649565)

   --> STEP: 40
     | > decoder_loss: 0.43502017855644226  (0.4433933742344379)
     | > postnet_loss: 0.3011162579059601  (0.3083666130900383)
     | > stopnet_loss: 0.003003291320055723  (0.005156857910333201)
     | > loss: 0.187037393450737  (0.19309685416519642)
     | > align_error: 0.5824676752090454  (0.5816101290285587)

   --> STEP: 41
     | > decoder_loss: 0.4259374141693115  (0.44296761911089827)
     | > postnet_loss: 0.2935478985309601  (0.30800518102762175)
     | > stopnet_loss: 0.0037175389006733894  (0.005121752568634182)
     | > loss: 0.18358886241912842  (0.19286495192748745)
     | > align_error: 0.5018137395381927  (0.5796638756263547)

   --> STEP: 42
     | > decoder_loss: 0.42979320883750916  (0.4426539426758176)
     | > postnet_loss: 0.2947317361831665  (0.3076891466265633)
     | > stopnet_loss: 0.0032475455664098263  (0.005077128592390744)
     | > loss: 0.18437878787517548  (0.1926629004024324)
     | > align_error: 0.5780693888664246  (0.5796259116558802)

   --> STEP: 43
     | > decoder_loss: 0.4294124245643616  (0.44234600039415584)
     | > postnet_loss: 0.2938390374183655  (0.307367051063582)
     | > stopnet_loss: 0.0029033496975898743  (0.005026575594837236)
     | > loss: 0.18371620774269104  (0.1924548377824384)
     | > align_error: 0.5503178834915161  (0.5789443296055461)

   --> STEP: 44
     | > decoder_loss: 0.4477401077747345  (0.44246859374371444)
     | > postnet_loss: 0.30538442730903625  (0.3073219914327968)
     | > stopnet_loss: 0.002622933592647314  (0.004971947367514737)
     | > loss: 0.19090406596660614  (0.19241959296844222)
     | > align_error: 0.5495163798332214  (0.578275512565266)

   --> STEP: 45
     | > decoder_loss: 0.4407496750354767  (0.44243039555019803)
     | > postnet_loss: 0.3041728436946869  (0.30725201037194994)
     | > stopnet_loss: 0.0032379524782299995  (0.004933414147752855)
     | > loss: 0.18946857750415802  (0.1923540148470137)
     | > align_error: 0.5509447455406189  (0.5776681621869405)

   --> STEP: 46
     | > decoder_loss: 0.43032053112983704  (0.44216713762801624)
     | > postnet_loss: 0.29524675011634827  (0.3069910264533499)
     | > stopnet_loss: 0.00317261996679008  (0.004895136013384099)
     | > loss: 0.18456444144248962  (0.19218467629474142)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.353618860244751 (+0.009044123418403383)
     | > avg_decoder_loss: 0.4379689892133077 (+0.0008536857185941771)
     | > avg_postnet_loss: 0.30394910140471026 (+0.0019127080837885724)
     | > avg_stopnet_loss: 0.004341154454529963 (+1.6531166197226305e-05)
     | > avg_loss: 0.18982067704200745 (+0.0007081311760526732)
     | > avg_align_error: 0.5703867922226589 (-0.0007475853869408633)


 > EPOCH: 158/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 20:29:34)

   --> TIME: 2025-12-28 20:29:58 -- STEP: 17/150 -- GLOBAL_STEP: 23875
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45853957533836365  (0.4613963295431698)
     | > postnet_loss: 0.3866526186466217  (0.39113107323646545)
     | > stopnet_loss: 0.007403374183923006  (0.01077249868060736)
     | > loss: 0.21870142221450806  (0.22390434847158544)
     | > align_error: 0.6917304694652557  (0.6811539004830753)
     | > grad_norm: tensor(0.1576, device='cuda:0')  (tensor(0.3429, device='cuda:0'))
     | > step_time: 0.7303  (0.5787821236778709)
     | > loader_time: 1.1098  (0.7652760673971737)


   --> TIME: 2025-12-28 20:30:46 -- STEP: 42/150 -- GLOBAL_STEP: 23900
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48358574509620667  (0.4696815808614095)
     | > postnet_loss: 0.39730700850486755  (0.3941364323809034)
     | > stopnet_loss: 0.005486576352268457  (0.008031192645874055)
     | > loss: 0.22570976614952087  (0.22398569647754943)
     | > align_error: 0.5993287563323975  (0.651783442213422)
     | > grad_norm: tensor(0.3548, device='cuda:0')  (tensor(0.2827, device='cuda:0'))
     | > step_time: 1.2603  (0.8170692069189889)
     | > loader_time: 1.0422  (0.885091951915196)


   --> TIME: 2025-12-28 20:31:49 -- STEP: 67/150 -- GLOBAL_STEP: 23925
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.4833924174308777  (0.47384556683141793)
     | > postnet_loss: 0.39610859751701355  (0.39446978782539943)
     | > stopnet_loss: 0.004125352017581463  (0.006670552858415602)
     | > loss: 0.22400060296058655  (0.2237493909561812)
     | > align_error: 0.611203134059906  (0.6382428367636099)
     | > grad_norm: tensor(0.1629, device='cuda:0')  (tensor(0.2584, device='cuda:0'))
     | > step_time: 1.4137  (1.0127071088819362)
     | > loader_time: 1.3532  (0.9927011319060823)


   --> TIME: 2025-12-28 20:33:09 -- STEP: 92/150 -- GLOBAL_STEP: 23950
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47613292932510376  (0.47563454735538235)
     | > postnet_loss: 0.3895971477031708  (0.39397602010032406)
     | > stopnet_loss: 0.0038759326562285423  (0.005902428043317859)
     | > loss: 0.22030843794345856  (0.2233050695579985)
     | > align_error: 0.6596639752388  (0.6328105715953788)
     | > grad_norm: tensor(0.1597, device='cuda:0')  (tensor(0.2462, device='cuda:0'))
     | > step_time: 1.6876  (1.1837556206661721)
     | > loader_time: 1.6891  (1.145029176836428)


   --> TIME: 2025-12-28 20:34:36 -- STEP: 117/150 -- GLOBAL_STEP: 23975
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4795176088809967  (0.47692627096787477)
     | > postnet_loss: 0.3899877369403839  (0.39360933171378243)
     | > stopnet_loss: 0.003252919064834714  (0.005376256839173217)
     | > loss: 0.2206292599439621  (0.2230101572906869)
     | > align_error: 0.6223821043968201  (0.6273447410163718)
     | > grad_norm: tensor(0.1447, device='cuda:0')  (tensor(0.2510, device='cuda:0'))
     | > step_time: 1.9943  (1.325457081835494)
     | > loader_time: 1.7351  (1.2504600948757592)


   --> TIME: 2025-12-28 20:36:13 -- STEP: 142/150 -- GLOBAL_STEP: 24000
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4906233847141266  (0.47825167212687747)
     | > postnet_loss: 0.3972454071044922  (0.39342525454474164)
     | > stopnet_loss: 0.00305820070207119  (0.0049772547315281475)
     | > loss: 0.22502538561820984  (0.22289648620595395)
     | > align_error: 0.5898089706897736  (0.6236606464839319)
     | > grad_norm: tensor(0.1593, device='cuda:0')  (tensor(0.2399, device='cuda:0'))
     | > step_time: 2.1826  (1.4600012990790356)
     | > loader_time: 2.0747  (1.34097860060947)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4589451551437378  (0.4589451551437378)
     | > postnet_loss: 0.33473238348960876  (0.33473238348960876)
     | > stopnet_loss: 0.01213410496711731  (0.01213410496711731)
     | > loss: 0.21055349707603455  (0.21055349707603455)
     | > align_error: 0.7184253334999084  (0.7184253334999084)

   --> STEP: 1
     | > decoder_loss: 0.44209471344947815  (0.44209471344947815)
     | > postnet_loss: 0.3246537148952484  (0.3246537148952484)
     | > stopnet_loss: 0.009631379507482052  (0.009631379507482052)
     | > loss: 0.20131848752498627  (0.20131848752498627)
     | > align_error: 0.6585485935211182  (0.6585485935211182)

   --> STEP: 2
     | > decoder_loss: 0.4362294375896454  (0.43916207551956177)
     | > postnet_loss: 0.31356340646743774  (0.3191085606813431)
     | > stopnet_loss: 0.010912392288446426  (0.010271885897964239)
     | > loss: 0.1983605921268463  (0.1998395398259163)
     | > align_error: 0.6547247171401978  (0.656636655330658)

   --> STEP: 3
     | > decoder_loss: 0.43913033604621887  (0.43915149569511414)
     | > postnet_loss: 0.3128584623336792  (0.31702519456545514)
     | > stopnet_loss: 0.008171779103577137  (0.009571850299835205)
     | > loss: 0.19616897404193878  (0.1986160178979238)
     | > align_error: 0.7339450120925903  (0.6824061075846354)

   --> STEP: 4
     | > decoder_loss: 0.4454370439052582  (0.44072288274765015)
     | > postnet_loss: 0.3219054043292999  (0.3182452470064163)
     | > stopnet_loss: 0.00816726591438055  (0.009220704203471541)
     | > loss: 0.20000287890434265  (0.1989627331495285)
     | > align_error: 0.6026140451431274  (0.6624580919742584)

   --> STEP: 5
     | > decoder_loss: 0.42696020007133484  (0.43797034621238706)
     | > postnet_loss: 0.3036659359931946  (0.315329384803772)
     | > stopnet_loss: 0.00808693002909422  (0.008993949368596077)
     | > loss: 0.19074346125125885  (0.19731887876987458)
     | > align_error: 0.6413205564022064  (0.658230584859848)

   --> STEP: 6
     | > decoder_loss: 0.4448472261428833  (0.4391164928674698)
     | > postnet_loss: 0.3164975643157959  (0.3155240813891093)
     | > stopnet_loss: 0.007238227874040604  (0.008701329119503498)
     | > loss: 0.1975744217634201  (0.19736146926879883)
     | > align_error: 0.5930639505386353  (0.6473694791396459)

   --> STEP: 7
     | > decoder_loss: 0.45483019948005676  (0.44136130809783936)
     | > postnet_loss: 0.3152253031730652  (0.3154813987868173)
     | > stopnet_loss: 0.006173735484480858  (0.008340244314500265)
     | > loss: 0.1986876130104065  (0.19755091837474278)
     | > align_error: 0.5781290829181671  (0.6374779939651489)

   --> STEP: 8
     | > decoder_loss: 0.45103293657302856  (0.442570261657238)
     | > postnet_loss: 0.317717969417572  (0.3157609701156616)
     | > stopnet_loss: 0.007222388871014118  (0.008200512384064496)
     | > loss: 0.1994101107120514  (0.19778331741690636)
     | > align_error: 0.5739037990570068  (0.6295312196016312)

   --> STEP: 9
     | > decoder_loss: 0.44744575023651123  (0.44311198261049056)
     | > postnet_loss: 0.3162125051021576  (0.3158111406697167)
     | > stopnet_loss: 0.0065513961017131805  (0.008017277241581015)
     | > loss: 0.19746597111225128  (0.19774805671638912)
     | > align_error: 0.5902919471263885  (0.6251713004377153)

   --> STEP: 10
     | > decoder_loss: 0.47382694482803345  (0.44618347883224485)
     | > postnet_loss: 0.33199751377105713  (0.3174297779798508)
     | > stopnet_loss: 0.005571918096393347  (0.007772741327062249)
     | > loss: 0.20702803134918213  (0.19867605417966844)
     | > align_error: 0.5828712582588196  (0.6209412962198257)

   --> STEP: 11
     | > decoder_loss: 0.4591860771179199  (0.4473655332218517)
     | > postnet_loss: 0.3202713131904602  (0.3176880993626334)
     | > stopnet_loss: 0.005935675464570522  (0.007605735339563002)
     | > loss: 0.20080001652240753  (0.19886914166537198)
     | > align_error: 0.594333678483963  (0.6185224218802019)

   --> STEP: 12
     | > decoder_loss: 0.4566226005554199  (0.44813695549964905)
     | > postnet_loss: 0.31491291522979736  (0.31745683401823044)
     | > stopnet_loss: 0.007847262546420097  (0.007625862606801093)
     | > loss: 0.20073114335536957  (0.19902430847287178)
     | > align_error: 0.5867042541503906  (0.6158709079027176)

   --> STEP: 13
     | > decoder_loss: 0.44491326808929443  (0.4478889795450064)
     | > postnet_loss: 0.31380289793014526  (0.31717576201145464)
     | > stopnet_loss: 0.005284109618514776  (0.007445727761548299)
     | > loss: 0.19496315717697144  (0.19871191221934098)
     | > align_error: 0.5842567682266235  (0.6134390510045565)

   --> STEP: 14
     | > decoder_loss: 0.45870131254196167  (0.4486612890447889)
     | > postnet_loss: 0.3186362683773041  (0.3172800838947296)
     | > stopnet_loss: 0.004907579626888037  (0.007264431466215423)
     | > loss: 0.19924196600914001  (0.19874977320432663)
     | > align_error: 0.5544826686382294  (0.6092278808355331)

   --> STEP: 15
     | > decoder_loss: 0.4525716006755829  (0.44892197648684184)
     | > postnet_loss: 0.3152487277984619  (0.31714466015497844)
     | > stopnet_loss: 0.0050139776431024075  (0.0071144012113412225)
     | > loss: 0.19696906208992004  (0.19863105913003284)
     | > align_error: 0.5879554450511932  (0.6078097184499105)

   --> STEP: 16
     | > decoder_loss: 0.4533069431781769  (0.4491960369050503)
     | > postnet_loss: 0.3095422089099884  (0.31666950695216656)
     | > stopnet_loss: 0.005232865922152996  (0.006996805255766958)
     | > loss: 0.1959451586008072  (0.19846319034695625)
     | > align_error: 0.6052170097827911  (0.6076476741582155)

   --> STEP: 17
     | > decoder_loss: 0.4599774479866028  (0.4498302375569063)
     | > postnet_loss: 0.31762370467185974  (0.31672563622979555)
     | > stopnet_loss: 0.004774857312440872  (0.006866102435571306)
     | > loss: 0.1991751343011856  (0.1985050694030874)
     | > align_error: 0.5577720105648041  (0.6047138115938973)

   --> STEP: 18
     | > decoder_loss: 0.45269709825515747  (0.44998950759569806)
     | > postnet_loss: 0.30922621488571167  (0.31630900171067977)
     | > stopnet_loss: 0.0052353679202497005  (0.0067755060736089945)
     | > loss: 0.19571620225906372  (0.19835013233953053)
     | > align_error: 0.6033339500427246  (0.6046371526188321)

   --> STEP: 19
     | > decoder_loss: 0.45380517840385437  (0.45019033237507466)
     | > postnet_loss: 0.3114953935146332  (0.31605565391088786)
     | > stopnet_loss: 0.004776418209075928  (0.006670290922844096)
     | > loss: 0.19610156118869781  (0.1982317864894867)
     | > align_error: 0.5995215177536011  (0.6043679086785567)

   --> STEP: 20
     | > decoder_loss: 0.4469243884086609  (0.450027035176754)
     | > postnet_loss: 0.30482277274131775  (0.3154940098524094)
     | > stopnet_loss: 0.0044614351354539394  (0.006559848133474588)
     | > loss: 0.19239822030067444  (0.1979401081800461)
     | > align_error: 0.6222702860832214  (0.60526302754879)

   --> STEP: 21
     | > decoder_loss: 0.4455026388168335  (0.4498115877310435)
     | > postnet_loss: 0.30557820200920105  (0.3150218285265423)
     | > stopnet_loss: 0.003953359555453062  (0.006435729629759278)
     | > loss: 0.19172357022762299  (0.19764408256326402)
     | > align_error: 0.5592153668403625  (0.6030702818007696)

   --> STEP: 22
     | > decoder_loss: 0.447253942489624  (0.44969533112916077)
     | > postnet_loss: 0.30777788162231445  (0.31469255821271375)
     | > stopnet_loss: 0.004773701075464487  (0.006360182877291332)
     | > loss: 0.19353166222572327  (0.1974571543661031)
     | > align_error: 0.6248740553855896  (0.6040613624182615)

   --> STEP: 23
     | > decoder_loss: 0.42000097036361694  (0.44840427196544147)
     | > postnet_loss: 0.2948453724384308  (0.3138296370920928)
     | > stopnet_loss: 0.00443232012912631  (0.006276362757805897)
     | > loss: 0.18314391374588013  (0.19683483955652817)
     | > align_error: 0.5663495659828186  (0.6024217190949813)

   --> STEP: 24
     | > decoder_loss: 0.45477280020713806  (0.4486696273088455)
     | > postnet_loss: 0.3106078803539276  (0.31369539722800255)
     | > stopnet_loss: 0.004406766500324011  (0.006198462913744152)
     | > loss: 0.19575193524360657  (0.19678971854348978)
     | > align_error: 0.5788394808769226  (0.6014391258358955)

   --> STEP: 25
     | > decoder_loss: 0.4534759819507599  (0.4488618814945221)
     | > postnet_loss: 0.30791252851486206  (0.31346408247947694)
     | > stopnet_loss: 0.0036967708729207516  (0.006098395232111215)
     | > loss: 0.19404390454292297  (0.1966798859834671)
     | > align_error: 0.5570761859416962  (0.5996646082401276)

   --> STEP: 26
     | > decoder_loss: 0.42897987365722656  (0.44809718888539535)
     | > postnet_loss: 0.2971069812774658  (0.3128349632024765)
     | > stopnet_loss: 0.004293658304959536  (0.0060289822733746124)
     | > loss: 0.18581537902355194  (0.19626202033116266)
     | > align_error: 0.5461243987083435  (0.5976053694119821)

   --> STEP: 27
     | > decoder_loss: 0.42694389820098877  (0.44731373367486177)
     | > postnet_loss: 0.2923497259616852  (0.31207625071207684)
     | > stopnet_loss: 0.003884288715198636  (0.005949549178627354)
     | > loss: 0.18370768427848816  (0.19579704492180436)
     | > align_error: 0.5402640402317047  (0.5954816164793791)

   --> STEP: 28
     | > decoder_loss: 0.4316783547401428  (0.4467553272843361)
     | > postnet_loss: 0.296608030796051  (0.3115238142865045)
     | > stopnet_loss: 0.003910885192453861  (0.00587673975054973)
     | > loss: 0.18598248064517975  (0.19544652476906776)
     | > align_error: 0.5658167600631714  (0.5944221573216575)

   --> STEP: 29
     | > decoder_loss: 0.4272695779800415  (0.44608340489453285)
     | > postnet_loss: 0.2942216098308563  (0.3109271865466545)
     | > stopnet_loss: 0.0035302594769746065  (0.005795826637667829)
     | > loss: 0.1839030683040619  (0.19504847454613652)
     | > align_error: 0.5397253632545471  (0.5925360609745157)

   --> STEP: 30
     | > decoder_loss: 0.42826300859451294  (0.44548939168453217)
     | > postnet_loss: 0.29463687539100647  (0.3103841761747996)
     | > stopnet_loss: 0.002800390124320984  (0.0056959787538896)
     | > loss: 0.18352536857128143  (0.19466437101364137)
     | > align_error: 0.5327630043029785  (0.5905436257521312)

   --> STEP: 31
     | > decoder_loss: 0.42103153467178345  (0.4447004285550887)
     | > postnet_loss: 0.29097774624824524  (0.30975816230620107)
     | > stopnet_loss: 0.003684144699946046  (0.005631080881181744)
     | > loss: 0.18168647587299347  (0.1942457292349108)
     | > align_error: 0.5533521473407745  (0.5893439006420874)

   --> STEP: 32
     | > decoder_loss: 0.4363468289375305  (0.44443937856703997)
     | > postnet_loss: 0.2993300259113312  (0.3094322830438614)
     | > stopnet_loss: 0.0037890917155891657  (0.005573518719756976)
     | > loss: 0.18770831823349  (0.19404143514111638)
     | > align_error: 0.5302044153213501  (0.5874957917258143)

   --> STEP: 33
     | > decoder_loss: 0.431755006313324  (0.4440550036502607)
     | > postnet_loss: 0.29580608010292053  (0.3090193678032268)
     | > stopnet_loss: 0.003997600171715021  (0.005525763612240553)
     | > loss: 0.18588787317276  (0.19379435750571164)
     | > align_error: 0.5449686050415039  (0.5862070890990171)

   --> STEP: 34
     | > decoder_loss: 0.4373152256011963  (0.44385677488411174)
     | > postnet_loss: 0.2971692383289337  (0.30867083458339467)
     | > stopnet_loss: 0.00325695495121181  (0.005459033945739707)
     | > loss: 0.18687807023525238  (0.1935909372918746)
     | > align_error: 0.5628763437271118  (0.5855208907057258)

   --> STEP: 35
     | > decoder_loss: 0.4350208640098572  (0.44360432028770447)
     | > postnet_loss: 0.2969217598438263  (0.3083351467336927)
     | > stopnet_loss: 0.0034747407771646976  (0.005402339855208993)
     | > loss: 0.18646040558815002  (0.19338720781462534)
     | > align_error: 0.5322316884994507  (0.5839983420712608)

   --> STEP: 36
     | > decoder_loss: 0.44065627455711365  (0.4435224301285214)
     | > postnet_loss: 0.3009141683578491  (0.30812900844547486)
     | > stopnet_loss: 0.003621791722252965  (0.005352880184849103)
     | > loss: 0.18901440501213074  (0.19326574107011163)
     | > align_error: 0.6327255368232727  (0.5853518752588167)

   --> STEP: 37
     | > decoder_loss: 0.4333333671092987  (0.4432470500469208)
     | > postnet_loss: 0.2975793778896332  (0.307843883295317)
     | > stopnet_loss: 0.003530095098540187  (0.0053036157230569704)
     | > loss: 0.18625828623771667  (0.19307635039896584)
     | > align_error: 0.5178127288818359  (0.5835264929243037)

   --> STEP: 38
     | > decoder_loss: 0.42070990800857544  (0.44265396736170115)
     | > postnet_loss: 0.2901098132133484  (0.3073771972405283)
     | > stopnet_loss: 0.003116134786978364  (0.005246050435265428)
     | > loss: 0.18082106113433838  (0.1927538427867388)
     | > align_error: 0.5506426095962524  (0.5826611275735655)

   --> STEP: 39
     | > decoder_loss: 0.43676143884658813  (0.44250287688695467)
     | > postnet_loss: 0.30144497752189636  (0.30722508904261464)
     | > stopnet_loss: 0.0034509419929236174  (0.00520002201366692)
     | > loss: 0.1880025416612625  (0.19263201455275222)
     | > align_error: 0.5450647473335266  (0.5816971178238208)

   --> STEP: 40
     | > decoder_loss: 0.43391668796539307  (0.4422882221639156)
     | > postnet_loss: 0.2997628450393677  (0.30703853294253347)
     | > stopnet_loss: 0.0030190907418727875  (0.0051454987318720665)
     | > loss: 0.18643897771835327  (0.19247718863189225)
     | > align_error: 0.5828332901000977  (0.5817255221307278)

   --> STEP: 41
     | > decoder_loss: 0.42492687702178955  (0.44186477472142477)
     | > postnet_loss: 0.29219406843185425  (0.3066764728325169)
     | > stopnet_loss: 0.003712903242558241  (0.005110557378474169)
     | > loss: 0.18299314379692078  (0.19224587046518563)
     | > align_error: 0.5021162629127502  (0.5797838328815088)

   --> STEP: 42
     | > decoder_loss: 0.4303903579711914  (0.44159157432260965)
     | > postnet_loss: 0.29420557618141174  (0.3063795467217763)
     | > stopnet_loss: 0.003259127028286457  (0.005066475703469699)
     | > loss: 0.18440809845924377  (0.19205925684599653)
     | > align_error: 0.5785864591598511  (0.5797553239833741)

   --> STEP: 43
     | > decoder_loss: 0.42815977334976196  (0.44127920685812483)
     | > postnet_loss: 0.29228076338768005  (0.30605166803958805)
     | > stopnet_loss: 0.0029049203731119633  (0.005016206974856729)
     | > loss: 0.18301504850387573  (0.1918489264194356)
     | > align_error: 0.5507764220237732  (0.5790813960308253)

   --> STEP: 44
     | > decoder_loss: 0.44729575514793396  (0.44141594659198413)
     | > postnet_loss: 0.3043474555015564  (0.30601293593645096)
     | > stopnet_loss: 0.0026278395671397448  (0.004961925897408615)
     | > loss: 0.19053862988948822  (0.19181914695284588)
     | > align_error: 0.5499637424945831  (0.5784196311777289)

   --> STEP: 45
     | > decoder_loss: 0.439380019903183  (0.4413707037766775)
     | > postnet_loss: 0.3025968372821808  (0.30593702263302275)
     | > stopnet_loss: 0.003256704658269882  (0.0049240320920944216)
     | > loss: 0.18875092267990112  (0.1917509641912249)
     | > align_error: 0.5514758229255676  (0.5778208798832364)

   --> STEP: 46
     | > decoder_loss: 0.4298350512981415  (0.4411199287227962)
     | > postnet_loss: 0.2941700220108032  (0.3056812182716701)
     | > stopnet_loss: 0.0031755859963595867  (0.004886022394361055)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3477451078819507 (-0.0058737523628003)
     | > avg_decoder_loss: 0.43711567105668964 (-0.0008533181566180437)
     | > avg_postnet_loss: 0.30266482360435243 (-0.001284277800357836)
     | > avg_stopnet_loss: 0.004335720783494639 (-5.433671035323662e-06)
     | > avg_loss: 0.18928084567640768 (-0.0005398313655997633)
     | > avg_align_error: 0.5706121217120778 (+0.00022532948941889064)


 > EPOCH: 159/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 20:38:43)

   --> TIME: 2025-12-28 20:39:04 -- STEP: 16/150 -- GLOBAL_STEP: 24025
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.46665850281715393  (0.460998248308897)
     | > postnet_loss: 0.3934604525566101  (0.39094019308686256)
     | > stopnet_loss: 0.008321758359670639  (0.010871330101508647)
     | > loss: 0.22335150837898254  (0.2238559415563941)
     | > align_error: 0.6762765944004059  (0.6805979963392019)
     | > grad_norm: tensor(0.2380, device='cuda:0')  (tensor(0.3118, device='cuda:0'))
     | > step_time: 0.7666  (0.5792412310838699)
     | > loader_time: 0.7864  (0.6910526603460312)


   --> TIME: 2025-12-28 20:39:54 -- STEP: 41/150 -- GLOBAL_STEP: 24050
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.479793906211853  (0.46933438501706937)
     | > postnet_loss: 0.3990069627761841  (0.39397007517698324)
     | > stopnet_loss: 0.00503906374797225  (0.008048410232110722)
     | > loss: 0.22473928332328796  (0.22387452605294017)
     | > align_error: 0.594776451587677  (0.6534118027221866)
     | > grad_norm: tensor(0.2084, device='cuda:0')  (tensor(0.2837, device='cuda:0'))
     | > step_time: 1.1458  (0.8239062995445438)
     | > loader_time: 1.0629  (0.8741809682148259)


   --> TIME: 2025-12-28 20:40:57 -- STEP: 66/150 -- GLOBAL_STEP: 24075
     | > current_lr: 1e-05  (1.0000000000000014e-05)
     | > decoder_loss: 0.48179465532302856  (0.47351554487690783)
     | > postnet_loss: 0.3941008746623993  (0.3943776560552192)
     | > stopnet_loss: 0.0034972052089869976  (0.006689337992363356)
     | > loss: 0.22247107326984406  (0.22366263830300534)
     | > align_error: 0.6137146055698395  (0.639082156347506)
     | > grad_norm: tensor(0.2100, device='cuda:0')  (tensor(0.2492, device='cuda:0'))
     | > step_time: 1.6853  (1.0283405527924045)
     | > loader_time: 1.2742  (0.9891928398247921)


   --> TIME: 2025-12-28 20:42:13 -- STEP: 91/150 -- GLOBAL_STEP: 24100
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4787274897098541  (0.47534953958385595)
     | > postnet_loss: 0.3909834623336792  (0.39386246558074106)
     | > stopnet_loss: 0.003679310204461217  (0.005914162550182953)
     | > loss: 0.22110703587532043  (0.22321716376713344)
     | > align_error: 0.59517702460289  (0.6326223873830101)
     | > grad_norm: tensor(0.1782, device='cuda:0')  (tensor(0.2316, device='cuda:0'))
     | > step_time: 1.7665  (1.1934046719100448)
     | > loader_time: 1.7546  (1.106937253868187)


   --> TIME: 2025-12-28 20:43:40 -- STEP: 116/150 -- GLOBAL_STEP: 24125
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4761228859424591  (0.47670554266921406)
     | > postnet_loss: 0.3884466290473938  (0.39350598177005497)
     | > stopnet_loss: 0.0030625746585428715  (0.005373210923200282)
     | > loss: 0.21920496225357056  (0.22292609191660223)
     | > align_error: 0.5890527367591858  (0.627376871376202)
     | > grad_norm: tensor(0.1361, device='cuda:0')  (tensor(0.2309, device='cuda:0'))
     | > step_time: 1.9212  (1.3344319791629398)
     | > loader_time: 2.0009  (1.2154836284703228)


   --> TIME: 2025-12-28 20:45:24 -- STEP: 141/150 -- GLOBAL_STEP: 24150
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48495572805404663  (0.4778893247563788)
     | > postnet_loss: 0.3905535638332367  (0.3932193758639883)
     | > stopnet_loss: 0.0029331855475902557  (0.004977294100210705)
     | > loss: 0.2218105047941208  (0.22275446904889235)
     | > align_error: 0.6043917536735535  (0.6239002642902076)
     | > grad_norm: tensor(0.2041, device='cuda:0')  (tensor(0.2238, device='cuda:0'))
     | > step_time: 2.1944  (1.4709013641303312)
     | > loader_time: 2.1633  (1.3624298386539977)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4578035771846771  (0.4578035771846771)
     | > postnet_loss: 0.3325483500957489  (0.3325483500957489)
     | > stopnet_loss: 0.01214681938290596  (0.01214681938290596)
     | > loss: 0.20973479747772217  (0.20973479747772217)
     | > align_error: 0.7181410193443298  (0.7181410193443298)

   --> STEP: 1
     | > decoder_loss: 0.44051533937454224  (0.44051533937454224)
     | > postnet_loss: 0.32104402780532837  (0.32104402780532837)
     | > stopnet_loss: 0.009646013379096985  (0.009646013379096985)
     | > loss: 0.20003585517406464  (0.20003585517406464)
     | > align_error: 0.6585531830787659  (0.6585531830787659)

   --> STEP: 2
     | > decoder_loss: 0.435502290725708  (0.4380088150501251)
     | > postnet_loss: 0.31185635924339294  (0.31645019352436066)
     | > stopnet_loss: 0.010958177037537098  (0.010302095208317041)
     | > loss: 0.19779784977436066  (0.19891685247421265)
     | > align_error: 0.6543254256248474  (0.6564393043518066)

   --> STEP: 3
     | > decoder_loss: 0.4418244957923889  (0.4392807086308797)
     | > postnet_loss: 0.31305399537086487  (0.3153181274731954)
     | > stopnet_loss: 0.008217343129217625  (0.009607177848617235)
     | > loss: 0.1969369798898697  (0.19825689494609833)
     | > align_error: 0.7348785698413849  (0.682585726181666)

   --> STEP: 4
     | > decoder_loss: 0.44357725977897644  (0.4403548464179039)
     | > postnet_loss: 0.3187655508518219  (0.316179983317852)
     | > stopnet_loss: 0.008129989728331566  (0.009237880818545818)
     | > loss: 0.1987156867980957  (0.19837159290909767)
     | > align_error: 0.6022453308105469  (0.6625006273388863)

   --> STEP: 5
     | > decoder_loss: 0.4273073375225067  (0.4377453446388245)
     | > postnet_loss: 0.3023698627948761  (0.3134179592132568)
     | > stopnet_loss: 0.008117053657770157  (0.009013715386390685)
     | > loss: 0.19053635001182556  (0.19680454432964326)
     | > align_error: 0.6412733197212219  (0.6582551658153534)

   --> STEP: 6
     | > decoder_loss: 0.4433612823486328  (0.43868133425712585)
     | > postnet_loss: 0.3136778473854065  (0.3134612739086151)
     | > stopnet_loss: 0.007244977634400129  (0.008718925761058927)
     | > loss: 0.19650475680828094  (0.19675457974274954)
     | > align_error: 0.5924855172634125  (0.6472935577233633)

   --> STEP: 7
     | > decoder_loss: 0.45477548241615295  (0.44098049827984404)
     | > postnet_loss: 0.31373247504234314  (0.3135000169277191)
     | > stopnet_loss: 0.006178857758641243  (0.008356058903570687)
     | > loss: 0.19830584526062012  (0.19697618910244533)
     | > align_error: 0.5777806639671326  (0.637363144329616)

   --> STEP: 8
     | > decoder_loss: 0.45120969414711  (0.44225914776325226)
     | > postnet_loss: 0.3156317472457886  (0.3137664832174778)
     | > stopnet_loss: 0.00728740356862545  (0.008222476986702532)
     | > loss: 0.19899775087833405  (0.19722888432443142)
     | > align_error: 0.5738673508167267  (0.6294261701405048)

   --> STEP: 9
     | > decoder_loss: 0.44757500290870667  (0.4428497983349694)
     | > postnet_loss: 0.3145653307437897  (0.31385524405373466)
     | > stopnet_loss: 0.006629511713981628  (0.008045480845289098)
     | > loss: 0.1971645951271057  (0.19722174108028412)
     | > align_error: 0.5901429951190948  (0.6250613729159037)

   --> STEP: 10
     | > decoder_loss: 0.4708144962787628  (0.44564626812934877)
     | > postnet_loss: 0.3276762366294861  (0.3152373433113098)
     | > stopnet_loss: 0.005579507444053888  (0.007798883505165577)
     | > loss: 0.20520219206809998  (0.1980197861790657)
     | > align_error: 0.5820860862731934  (0.6207638442516327)

   --> STEP: 11
     | > decoder_loss: 0.45847487449645996  (0.4468125050718134)
     | > postnet_loss: 0.3180953562259674  (0.3154971626671878)
     | > stopnet_loss: 0.005948749370872974  (0.007630689492957158)
     | > loss: 0.20009130239486694  (0.19820810583504764)
     | > align_error: 0.5940313637256622  (0.6183336187492717)

   --> STEP: 12
     | > decoder_loss: 0.45514777302742004  (0.4475071107347806)
     | > postnet_loss: 0.312244713306427  (0.31522612522045773)
     | > stopnet_loss: 0.007891586981713772  (0.007652430950353543)
     | > loss: 0.1997397094964981  (0.19833573947350183)
     | > align_error: 0.585988312959671  (0.6156381766001383)

   --> STEP: 13
     | > decoder_loss: 0.44391486048698425  (0.4472307837926425)
     | > postnet_loss: 0.3111564815044403  (0.314913075703841)
     | > stopnet_loss: 0.005287333857268095  (0.007470500404731586)
     | > loss: 0.19405516982078552  (0.19800646488483137)
     | > align_error: 0.583893358707428  (0.6131962675314683)

   --> STEP: 14
     | > decoder_loss: 0.45784687995910645  (0.4479890763759613)
     | > postnet_loss: 0.3163928985595703  (0.3150187773363931)
     | > stopnet_loss: 0.004892634227871895  (0.007286367106384465)
     | > loss: 0.19845257699489594  (0.19803833003555024)
     | > align_error: 0.5540944933891296  (0.608974712235587)

   --> STEP: 15
     | > decoder_loss: 0.45268651843070984  (0.4483022391796112)
     | > postnet_loss: 0.31377148628234863  (0.3149356245994568)
     | > stopnet_loss: 0.00497844023630023  (0.007132505315045516)
     | > loss: 0.19659294188022614  (0.19794197082519532)
     | > align_error: 0.587839663028717  (0.607565708955129)

   --> STEP: 16
     | > decoder_loss: 0.45341435074806213  (0.4486217461526394)
     | > postnet_loss: 0.3083466589450836  (0.31452381424605846)
     | > stopnet_loss: 0.005244156811386347  (0.007014483533566818)
     | > loss: 0.19568440318107605  (0.19780087284743786)
     | > align_error: 0.6046000719070435  (0.6073803566396236)

   --> STEP: 17
     | > decoder_loss: 0.4603734612464905  (0.4493130235111012)
     | > postnet_loss: 0.3166464865207672  (0.31464867732104135)
     | > stopnet_loss: 0.004761201329529285  (0.0068819375215646095)
     | > loss: 0.19901619851589203  (0.19787236259264104)
     | > align_error: 0.5572963356971741  (0.604434237760656)

   --> STEP: 18
     | > decoder_loss: 0.45301294326782227  (0.4495185746086968)
     | > postnet_loss: 0.3080953359603882  (0.31428460280100506)
     | > stopnet_loss: 0.005205480381846428  (0.006788801013802488)
     | > loss: 0.1954825520515442  (0.1977395953403579)
     | > align_error: 0.602971076965332  (0.6043529510498047)

   --> STEP: 19
     | > decoder_loss: 0.4520598351955414  (0.4496523251658992)
     | > postnet_loss: 0.3086068630218506  (0.3139857743915759)
     | > stopnet_loss: 0.004835846368223429  (0.006686013927193065)
     | > loss: 0.19500252604484558  (0.1975955390616467)
     | > align_error: 0.5990045666694641  (0.60407145713505)

   --> STEP: 20
     | > decoder_loss: 0.4471593499183655  (0.4495276764035225)
     | > postnet_loss: 0.3041299283504486  (0.3134929820895195)
     | > stopnet_loss: 0.004462469834834337  (0.006574836722575128)
     | > loss: 0.19228477776050568  (0.19733000099658965)
     | > align_error: 0.6216613054275513  (0.604950949549675)

   --> STEP: 21
     | > decoder_loss: 0.4456285238265991  (0.449342002471288)
     | > postnet_loss: 0.30375683307647705  (0.3130293559460413)
     | > stopnet_loss: 0.0039443885907530785  (0.006449577287726459)
     | > loss: 0.1912907212972641  (0.19704241624900273)
     | > align_error: 0.5585683882236481  (0.6027422561531975)

   --> STEP: 22
     | > decoder_loss: 0.4480665922164917  (0.4492840292778882)
     | > postnet_loss: 0.30677175521850586  (0.31274491954933514)
     | > stopnet_loss: 0.0048858593218028545  (0.006378499198366295)
     | > loss: 0.19359543919563293  (0.19688573547384955)
     | > align_error: 0.624603807926178  (0.6037359630519693)

   --> STEP: 23
     | > decoder_loss: 0.4206005334854126  (0.4480369207651719)
     | > postnet_loss: 0.2938753664493561  (0.3119245041971621)
     | > stopnet_loss: 0.004442972131073475  (0.006294345847614433)
     | > loss: 0.18306194245815277  (0.19628470099490622)
     | > align_error: 0.5658650100231171  (0.6020893998768018)

   --> STEP: 24
     | > decoder_loss: 0.4557041823863983  (0.44835638999938965)
     | > postnet_loss: 0.31035932898521423  (0.31185928856333095)
     | > stopnet_loss: 0.004406138323247433  (0.006215670534099142)
     | > loss: 0.19592201709747314  (0.1962695891658465)
     | > align_error: 0.578409731388092  (0.6011027470231055)

   --> STEP: 25
     | > decoder_loss: 0.45485955476760864  (0.4486165165901184)
     | > postnet_loss: 0.3076193332672119  (0.3116896903514862)
     | > stopnet_loss: 0.0036548373755067587  (0.006113237207755446)
     | > loss: 0.19427455961704254  (0.19618978798389436)
     | > align_error: 0.5567165613174438  (0.599327299594879)

   --> STEP: 26
     | > decoder_loss: 0.42950889468193054  (0.4478816080551881)
     | > postnet_loss: 0.29569119215011597  (0.3110743634975873)
     | > stopnet_loss: 0.004293876700103283  (0.006043261803614979)
     | > loss: 0.1855938881635666  (0.1957822533754202)
     | > align_error: 0.5454146564006805  (0.597253736395102)

   --> STEP: 27
     | > decoder_loss: 0.42665088176727295  (0.4470952848593394)
     | > postnet_loss: 0.2910721004009247  (0.31033353893845167)
     | > stopnet_loss: 0.003868389641866088  (0.005962710982809464)
     | > loss: 0.18329913914203644  (0.1953199158112208)
     | > align_error: 0.5394862294197083  (0.5951141990997171)

   --> STEP: 28
     | > decoder_loss: 0.43275579810142517  (0.446583160332271)
     | > postnet_loss: 0.2960070073604584  (0.3098218770963805)
     | > stopnet_loss: 0.003917587921023369  (0.005889670873459961)
     | > loss: 0.1861082911491394  (0.19499092921614647)
     | > align_error: 0.5651614665985107  (0.5940444586532454)

   --> STEP: 29
     | > decoder_loss: 0.42705774307250977  (0.44590987008193445)
     | > postnet_loss: 0.29222574830055237  (0.3092151140344554)
     | > stopnet_loss: 0.003548814682289958  (0.005808951694454099)
     | > loss: 0.1833696812391281  (0.19459019652728377)
     | > align_error: 0.5391632318496704  (0.5921520025565704)

   --> STEP: 30
     | > decoder_loss: 0.4284506142139435  (0.44532789488633473)
     | > postnet_loss: 0.29332292079925537  (0.30868537425994874)
     | > stopnet_loss: 0.002811098238453269  (0.0057090232459207375)
     | > loss: 0.18325448036193848  (0.19421233932177226)
     | > align_error: 0.5320398807525635  (0.5901482651631035)

   --> STEP: 31
     | > decoder_loss: 0.42457738518714905  (0.44465852360571584)
     | > postnet_loss: 0.2918151915073395  (0.3081411748163162)
     | > stopnet_loss: 0.00367070734500885  (0.00564327112008487)
     | > loss: 0.18276885151863098  (0.19384319455392898)
     | > align_error: 0.5541053414344788  (0.5889855902041156)

   --> STEP: 32
     | > decoder_loss: 0.43607935309410095  (0.4443904245272279)
     | > postnet_loss: 0.29790982604026794  (0.30782144516706467)
     | > stopnet_loss: 0.0037862081080675125  (0.005585237900959328)
     | > loss: 0.1872835010290146  (0.19363820413127542)
     | > align_error: 0.5293115377426147  (0.5871207760646937)

   --> STEP: 33
     | > decoder_loss: 0.43244582414627075  (0.44402846693992615)
     | > postnet_loss: 0.29537612199783325  (0.30744431416193646)
     | > stopnet_loss: 0.003989799413830042  (0.005536891280137228)
     | > loss: 0.1859452873468399  (0.19340508544083798)
     | > align_error: 0.5443781614303589  (0.5858255453181987)

   --> STEP: 34
     | > decoder_loss: 0.4379178583621979  (0.44384874315822825)
     | > postnet_loss: 0.29671087861061096  (0.3071286248810151)
     | > stopnet_loss: 0.0032525346614420414  (0.0054697043207638405)
     | > loss: 0.1869097203016281  (0.19321404528968475)
     | > align_error: 0.5623135268688202  (0.5851340153638053)

   --> STEP: 35
     | > decoder_loss: 0.43532994389533997  (0.4436053488935743)
     | > postnet_loss: 0.2957991361618042  (0.30680492520332336)
     | > stopnet_loss: 0.0034840041771531105  (0.005412970030946391)
     | > loss: 0.18626627326011658  (0.19301553751741138)
     | > align_error: 0.5315631628036499  (0.5836034195763722)

   --> STEP: 36
     | > decoder_loss: 0.441683828830719  (0.4435519733362728)
     | > postnet_loss: 0.3005432188510895  (0.3066309889157613)
     | > stopnet_loss: 0.003598659997805953  (0.005362572530025823)
     | > loss: 0.1891554296016693  (0.19290831229752964)
     | > align_error: 0.6322399377822876  (0.584954433970981)

   --> STEP: 37
     | > decoder_loss: 0.4339340329170227  (0.44329202900061737)
     | > postnet_loss: 0.2967255413532257  (0.3063632741167739)
     | > stopnet_loss: 0.003523971186950803  (0.005312880601834606)
     | > loss: 0.18618887662887573  (0.19272670592810656)
     | > align_error: 0.5170610547065735  (0.5831194777746457)

   --> STEP: 38
     | > decoder_loss: 0.4211840033531189  (0.442710238851999)
     | > postnet_loss: 0.28934937715530396  (0.30591553998620885)
     | > stopnet_loss: 0.00310436449944973  (0.005254761757035004)
     | > loss: 0.18073770403862  (0.19241120587838323)
     | > align_error: 0.5500696301460266  (0.5822497449423135)

   --> STEP: 39
     | > decoder_loss: 0.4369603991508484  (0.44256280706479)
     | > postnet_loss: 0.30015885829925537  (0.3057679327634665)
     | > stopnet_loss: 0.0034294435754418373  (0.005207958726737744)
     | > loss: 0.1877092570066452  (0.19229064308680022)
     | > align_error: 0.5444169044494629  (0.5812796721091635)

   --> STEP: 40
     | > decoder_loss: 0.4340870678424835  (0.44235091358423234)
     | > postnet_loss: 0.2986021935939789  (0.3055887892842293)
     | > stopnet_loss: 0.003001865930855274  (0.005152806406840683)
     | > loss: 0.1861741840839386  (0.19213773161172867)
     | > align_error: 0.5822845101356506  (0.5813047930598257)

   --> STEP: 41
     | > decoder_loss: 0.4250272810459137  (0.44192838596134654)
     | > postnet_loss: 0.29088956117630005  (0.3052302715254993)
     | > stopnet_loss: 0.003708277363330126  (0.005117573991145303)
     | > loss: 0.18268749117851257  (0.19190723794262585)
     | > align_error: 0.5013851523399353  (0.5793555335300723)

   --> STEP: 42
     | > decoder_loss: 0.4300163984298706  (0.4416447672105971)
     | > postnet_loss: 0.29329749941825867  (0.30494615790389834)
     | > stopnet_loss: 0.003245973028242588  (0.005073012063457143)
     | > loss: 0.18407446146011353  (0.19172074326447078)
     | > align_error: 0.5778523683547974  (0.579319743883042)

   --> STEP: 43
     | > decoder_loss: 0.4289936423301697  (0.4413505550040755)
     | > postnet_loss: 0.2919245660305023  (0.3046433301859124)
     | > stopnet_loss: 0.002901052124798298  (0.005022501367209263)
     | > loss: 0.18313059210777283  (0.19152097230733828)
     | > align_error: 0.5502731502056122  (0.578644241704497)

   --> STEP: 44
     | > decoder_loss: 0.44759002327919006  (0.4414923611012372)
     | > postnet_loss: 0.3031570017337799  (0.30460954999381845)
     | > stopnet_loss: 0.0026401595678180456  (0.004968357235404917)
     | > loss: 0.19032691419124603  (0.19149383462288164)
     | > align_error: 0.5491568446159363  (0.577974073588848)

   --> STEP: 45
     | > decoder_loss: 0.4402574598789215  (0.4414649188518524)
     | > postnet_loss: 0.30209702253341675  (0.304553716050254)
     | > stopnet_loss: 0.0032544417772442102  (0.004930270225223569)
     | > loss: 0.18884307146072388  (0.19143492877483367)
     | > align_error: 0.5506719350814819  (0.5773673593997954)

   --> STEP: 46
     | > decoder_loss: 0.4296700060367584  (0.4412085077036982)
     | > postnet_loss: 0.2928451895713806  (0.30429918286593066)
     | > stopnet_loss: 0.0031770996283739805  (0.0048921578209442295)
     | > loss: 0.183805912733078  (0.1912690806000129)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.35762600465254357 (-0.007222894466284491)
     | > avg_decoder_loss: 0.43596469768972107 (-0.0009070792884537937)
     | > avg_postnet_loss: 0.30262288044799457 (-0.0006576979702169194)
     | > avg_stopnet_loss: 0.004327923091213136 (-1.210989218882342e-05)
     | > avg_loss: 0.18897481872276825 (-0.00040330444321490244)
     | > avg_align_error: 0.5710801378344045 (+0.0004346880948906673)


 > EPOCH: 166/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 21:44:05)

   --> TIME: 2025-12-28 21:44:18 -- STEP: 9/150 -- GLOBAL_STEP: 25075
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4581840932369232  (0.45579440063900417)
     | > postnet_loss: 0.38736629486083984  (0.38816969262229073)
     | > stopnet_loss: 0.010788352228701115  (0.012725667717556158)
     | > loss: 0.2221759557723999  (0.22371669113636017)
     | > align_error: 0.6430539488792419  (0.6953279541598426)
     | > grad_norm: tensor(0.3416, device='cuda:0')  (tensor(0.3129, device='cuda:0'))
     | > step_time: 0.6145  (0.5290848149193658)
     | > loader_time: 0.8425  (0.8110956086052789)


   --> TIME: 2025-12-28 21:45:01 -- STEP: 34/150 -- GLOBAL_STEP: 25100
     | > current_lr: 1e-05  (1.000000000000001e-05)
     | > decoder_loss: 0.47039228677749634  (0.46599529771243825)
     | > postnet_loss: 0.3915347158908844  (0.3922905939466813)
     | > stopnet_loss: 0.00556659372523427  (0.008686712874537882)
     | > loss: 0.22104835510253906  (0.22325818810392828)
     | > align_error: 0.6195791363716125  (0.6617938490474925)
     | > grad_norm: tensor(0.3009, device='cuda:0')  (tensor(0.3336, device='cuda:0'))
     | > step_time: 1.076  (0.7483777018154368)
     | > loader_time: 1.0395  (0.8825397281085744)


   --> TIME: 2025-12-28 21:46:01 -- STEP: 59/150 -- GLOBAL_STEP: 25125
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48048296570777893  (0.4716752494795848)
     | > postnet_loss: 0.39427649974823  (0.3935998814590907)
     | > stopnet_loss: 0.004244084469974041  (0.0070799214733859245)
     | > loss: 0.22293394804000854  (0.2233987046500384)
     | > align_error: 0.6037739217281342  (0.6421760573225503)
     | > grad_norm: tensor(0.1983, device='cuda:0')  (tensor(0.3000, device='cuda:0'))
     | > step_time: 1.3151  (0.9531544669199798)
     | > loader_time: 1.2543  (0.9901256682509083)


   --> TIME: 2025-12-28 21:47:12 -- STEP: 84/150 -- GLOBAL_STEP: 25150
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47531265020370483  (0.4740585411588351)
     | > postnet_loss: 0.3882412016391754  (0.393305199132079)
     | > stopnet_loss: 0.003542862134054303  (0.0061481996644510055)
     | > loss: 0.2194313257932663  (0.2229891357322534)
     | > align_error: 0.6685896515846252  (0.6342673621007373)
     | > grad_norm: tensor(0.1787, device='cuda:0')  (tensor(0.2620, device='cuda:0'))
     | > step_time: 1.669  (1.1217261865025476)
     | > loader_time: 1.53  (1.0929962935901822)


   --> TIME: 2025-12-28 21:48:35 -- STEP: 109/150 -- GLOBAL_STEP: 25175
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4741329550743103  (0.4753048162941539)
     | > postnet_loss: 0.3859146535396576  (0.39276638353636495)
     | > stopnet_loss: 0.0034369940403848886  (0.005551667708835199)
     | > loss: 0.21844889223575592  (0.22256946864478086)
     | > align_error: 0.6316795945167542  (0.6282862728342002)
     | > grad_norm: tensor(0.2317, device='cuda:0')  (tensor(0.2452, device='cuda:0'))
     | > step_time: 1.8708  (1.2665208589046373)
     | > loader_time: 1.5524  (1.204304948859259)


   --> TIME: 2025-12-28 21:50:11 -- STEP: 134/150 -- GLOBAL_STEP: 25200
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.47899213433265686  (0.476293304740493)
     | > postnet_loss: 0.3884999752044678  (0.39229534099351104)
     | > stopnet_loss: 0.003201992716640234  (0.005114408762458324)
     | > loss: 0.22007501125335693  (0.22226157095005264)
     | > align_error: 0.6325842142105103  (0.6249458789825438)
     | > grad_norm: tensor(0.1754, device='cuda:0')  (tensor(0.2447, device='cuda:0'))
     | > step_time: 2.1866  (1.4019279355433452)
     | > loader_time: 2.0246  (1.3182864883052774)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4573412537574768  (0.4573412537574768)
     | > postnet_loss: 0.337680459022522  (0.337680459022522)
     | > stopnet_loss: 0.012144219130277634  (0.012144219130277634)
     | > loss: 0.21089965105056763  (0.21089965105056763)
     | > align_error: 0.7189712524414062  (0.7189712524414062)

   --> STEP: 1
     | > decoder_loss: 0.43782106041908264  (0.43782106041908264)
     | > postnet_loss: 0.3264020085334778  (0.3264020085334778)
     | > stopnet_loss: 0.009600690566003323  (0.009600690566003323)
     | > loss: 0.200656458735466  (0.200656458735466)
     | > align_error: 0.6587023138999939  (0.6587023138999939)

   --> STEP: 2
     | > decoder_loss: 0.4352140724658966  (0.4365175664424896)
     | > postnet_loss: 0.3157777786254883  (0.32108989357948303)
     | > stopnet_loss: 0.010897883214056492  (0.010249286890029907)
     | > loss: 0.19864584505558014  (0.19965115189552307)
     | > align_error: 0.6547421514987946  (0.6567222326993942)

   --> STEP: 3
     | > decoder_loss: 0.4395364224910736  (0.43752385179201764)
     | > postnet_loss: 0.3167341649532318  (0.3196379840373993)
     | > stopnet_loss: 0.008181234821677208  (0.009559936200579008)
     | > loss: 0.19724887609481812  (0.19885039329528809)
     | > align_error: 0.7345856130123138  (0.6826766928037008)

   --> STEP: 4
     | > decoder_loss: 0.44112229347229004  (0.4384234622120857)
     | > postnet_loss: 0.32263001799583435  (0.32038599252700806)
     | > stopnet_loss: 0.008133554831147194  (0.009203340858221054)
     | > loss: 0.19907164573669434  (0.19890570640563965)
     | > align_error: 0.6027722358703613  (0.6627005785703659)

   --> STEP: 5
     | > decoder_loss: 0.4256168007850647  (0.4358621299266815)
     | > postnet_loss: 0.30552801489830017  (0.3174143970012665)
     | > stopnet_loss: 0.008063933812081814  (0.008975459448993205)
     | > loss: 0.1908501237630844  (0.1972945898771286)
     | > align_error: 0.6410648226737976  (0.6583734273910522)

   --> STEP: 6
     | > decoder_loss: 0.44247305393218994  (0.43696395059426624)
     | > postnet_loss: 0.3180582523345947  (0.31752170622348785)
     | > stopnet_loss: 0.007232481148093939  (0.008684963065509995)
     | > loss: 0.19736531376838684  (0.19730637719233832)
     | > align_error: 0.5930846333503723  (0.6474919617176056)

   --> STEP: 7
     | > decoder_loss: 0.4526069164276123  (0.43919865999902996)
     | > postnet_loss: 0.3165518343448639  (0.31738315309797016)
     | > stopnet_loss: 0.006171031855046749  (0.008325830035443817)
     | > loss: 0.19846071302890778  (0.19747128231184824)
     | > align_error: 0.5782246887683868  (0.6375966370105743)

   --> STEP: 8
     | > decoder_loss: 0.4495941400527954  (0.44049809500575066)
     | > postnet_loss: 0.31982600688934326  (0.3176885098218918)
     | > stopnet_loss: 0.006983244325965643  (0.008158006821759045)
     | > loss: 0.19933828711509705  (0.19770465791225433)
     | > align_error: 0.573627233505249  (0.6296004615724087)

   --> STEP: 9
     | > decoder_loss: 0.44505634903907776  (0.44100456767612034)
     | > postnet_loss: 0.3173346221446991  (0.3176491889688704)
     | > stopnet_loss: 0.00672880606725812  (0.00799920673792561)
     | > loss: 0.19732655584812164  (0.19766264657179514)
     | > align_error: 0.590475469827652  (0.6252532402674357)

   --> STEP: 10
     | > decoder_loss: 0.47051894664764404  (0.4439560055732727)
     | > postnet_loss: 0.3327005207538605  (0.3191543221473694)
     | > stopnet_loss: 0.005571263842284679  (0.007756412448361516)
     | > loss: 0.2063761204481125  (0.1985339939594269)
     | > align_error: 0.5826980173587799  (0.6209977179765701)

   --> STEP: 11
     | > decoder_loss: 0.45595982670783997  (0.44504726204005157)
     | > postnet_loss: 0.3199002146720886  (0.3192221305587075)
     | > stopnet_loss: 0.005905658472329378  (0.007588162086904049)
     | > loss: 0.19987067580223083  (0.19865551049059088)
     | > align_error: 0.5944373607635498  (0.6185831400481138)

   --> STEP: 12
     | > decoder_loss: 0.45351511240005493  (0.4457529162367185)
     | > postnet_loss: 0.31530869007110596  (0.31889601051807404)
     | > stopnet_loss: 0.007869484834372997  (0.007611605649193128)
     | > loss: 0.2000754326581955  (0.19877383733789125)
     | > align_error: 0.5870773494243622  (0.6159576574961344)

   --> STEP: 13
     | > decoder_loss: 0.44197550415992737  (0.44546234607696533)
     | > postnet_loss: 0.3140811026096344  (0.3185256329866556)
     | > stopnet_loss: 0.0052630663849413395  (0.007430948782712221)
     | > loss: 0.19427721202373505  (0.19842794308295617)
     | > align_error: 0.5840947031974792  (0.6135066610116225)

   --> STEP: 14
     | > decoder_loss: 0.4543919563293457  (0.4461001753807068)
     | > postnet_loss: 0.3179004192352295  (0.31848097486155375)
     | > stopnet_loss: 0.004879744257777929  (0.007248719888074058)
     | > loss: 0.19795283675193787  (0.19839400691645487)
     | > align_error: 0.5541525483131409  (0.6092670815331596)

   --> STEP: 15
     | > decoder_loss: 0.4511633813381195  (0.4464377224445343)
     | > postnet_loss: 0.3153592348098755  (0.3182728588581085)
     | > stopnet_loss: 0.004955066833645105  (0.007095809684445461)
     | > loss: 0.1965857297182083  (0.19827345510323843)
     | > align_error: 0.5881098508834839  (0.6078565994898478)

   --> STEP: 16
     | > decoder_loss: 0.45239296555519104  (0.44680992513895035)
     | > postnet_loss: 0.31045734882354736  (0.31778438948094845)
     | > stopnet_loss: 0.005231602117419243  (0.006979296711506322)
     | > loss: 0.1959441751241684  (0.19812787510454655)
     | > align_error: 0.6050189137458801  (0.6076792441308498)

   --> STEP: 17
     | > decoder_loss: 0.4593927264213562  (0.44755008992026835)
     | > postnet_loss: 0.31861612200737  (0.3178333149236791)
     | > stopnet_loss: 0.004746060352772474  (0.006847929866874919)
     | > loss: 0.199248269200325  (0.19819378063959234)
     | > align_error: 0.5580322742462158  (0.6047588341376361)

   --> STEP: 18
     | > decoder_loss: 0.4520203173160553  (0.44779843588670093)
     | > postnet_loss: 0.31031301617622375  (0.3174155205488205)
     | > stopnet_loss: 0.00518333725631237  (0.006755452499621444)
     | > loss: 0.19576667249202728  (0.19805894129806095)
     | > align_error: 0.6034470200538635  (0.6046859555774264)

   --> STEP: 19
     | > decoder_loss: 0.4484460949897766  (0.44783252320791544)
     | > postnet_loss: 0.30967459082603455  (0.3170081031949897)
     | > stopnet_loss: 0.004673144314438105  (0.006645857331980216)
     | > loss: 0.19420330226421356  (0.19785601292785845)
     | > align_error: 0.5986888706684113  (0.6043703195295835)

   --> STEP: 20
     | > decoder_loss: 0.4457373321056366  (0.44772776365280154)
     | > postnet_loss: 0.3052549958229065  (0.3164204478263855)
     | > stopnet_loss: 0.004490667022764683  (0.006538097816519439)
     | > loss: 0.19223874807357788  (0.19757514968514442)
     | > align_error: 0.6222745180130005  (0.6052655294537544)

   --> STEP: 21
     | > decoder_loss: 0.44365161657333374  (0.4475336614109221)
     | > postnet_loss: 0.3062202036380768  (0.31593472191265654)
     | > stopnet_loss: 0.003942526411265135  (0.006414499178173996)
     | > loss: 0.19141048192977905  (0.19728159407774606)
     | > align_error: 0.5591244697570801  (0.6030683361348652)

   --> STEP: 22
     | > decoder_loss: 0.4463370442390442  (0.44747926972129126)
     | > postnet_loss: 0.30852794647216797  (0.3155980503017253)
     | > stopnet_loss: 0.0048067024908959866  (0.00634141751057045)
     | > loss: 0.19352294504642487  (0.1971107463945042)
     | > align_error: 0.6249175667762756  (0.604061482982202)

   --> STEP: 23
     | > decoder_loss: 0.4195987284183502  (0.44626707227333734)
     | > postnet_loss: 0.2959018051624298  (0.3147416918174081)
     | > stopnet_loss: 0.004448979627341032  (0.006259137602603953)
     | > loss: 0.18332411348819733  (0.19651132757249085)
     | > align_error: 0.5666260123252869  (0.6024338538232057)

   --> STEP: 24
     | > decoder_loss: 0.4540853202342987  (0.44659283260504407)
     | > postnet_loss: 0.3114844262599945  (0.3146059724191825)
     | > stopnet_loss: 0.004391643218696117  (0.006181325336607794)
     | > loss: 0.1957840770483017  (0.1964810254673163)
     | > align_error: 0.579042375087738  (0.6014592088758945)

   --> STEP: 25
     | > decoder_loss: 0.45320191979408264  (0.4468571960926056)
     | > postnet_loss: 0.3090023994445801  (0.3143818295001984)
     | > stopnet_loss: 0.00368017191067338  (0.006081279199570418)
     | > loss: 0.19423124194145203  (0.19639103412628173)
     | > align_error: 0.5575500726699829  (0.5997028434276581)

   --> STEP: 26
     | > decoder_loss: 0.42816439270973206  (0.44613824211634123)
     | > postnet_loss: 0.2982944846153259  (0.3137630854661648)
     | > stopnet_loss: 0.004272184334695339  (0.006011698627844453)
     | > loss: 0.1858869045972824  (0.19598702914439714)
     | > align_error: 0.5462440848350525  (0.5976467373279425)

   --> STEP: 27
     | > decoder_loss: 0.4249447286128998  (0.4453532971717693)
     | > postnet_loss: 0.29223212599754333  (0.31296564252288256)
     | > stopnet_loss: 0.003888580948114395  (0.005933064639706303)
     | > loss: 0.18318279087543488  (0.19551279809739855)
     | > align_error: 0.5403192937374115  (0.5955234986764414)

   --> STEP: 28
     | > decoder_loss: 0.4308635890483856  (0.44483580759593416)
     | > postnet_loss: 0.2977078855037689  (0.3124207226293428)
     | > stopnet_loss: 0.003928410820662975  (0.005861469860454755)
     | > loss: 0.1860712766647339  (0.1951756009033748)
     | > align_error: 0.5657504796981812  (0.5944601765700749)

   --> STEP: 29
     | > decoder_loss: 0.42603546380996704  (0.4441875198791767)
     | > postnet_loss: 0.2947200536727905  (0.31181035473428925)
     | > stopnet_loss: 0.0035430719144642353  (0.005781525103696461)
     | > loss: 0.18373195827007294  (0.19478099253670922)
     | > align_error: 0.5401555001735687  (0.5925876015219195)

   --> STEP: 30
     | > decoder_loss: 0.42684489488601685  (0.4436094323794047)
     | > postnet_loss: 0.29538023471832275  (0.31126268406709034)
     | > stopnet_loss: 0.002791326493024826  (0.005681851816674074)
     | > loss: 0.18334761261940002  (0.19439987987279891)
     | > align_error: 0.5327644944190979  (0.5905934979518255)

   --> STEP: 31
     | > decoder_loss: 0.42056936025619507  (0.44286620424639794)
     | > postnet_loss: 0.2918701171875  (0.3106371173935552)
     | > stopnet_loss: 0.0036530806683003902  (0.005616407586081374)
     | > loss: 0.1817629486322403  (0.19399223692955508)
     | > align_error: 0.5535479187965393  (0.5893984792693969)

   --> STEP: 32
     | > decoder_loss: 0.4347507953643799  (0.4426125977188349)
     | > postnet_loss: 0.29977527260780334  (0.31029768474400043)
     | > stopnet_loss: 0.0037911939434707165  (0.005559369659749791)
     | > loss: 0.1874227076768875  (0.19378693914040923)
     | > align_error: 0.5305516123771667  (0.5875595146790147)

   --> STEP: 33
     | > decoder_loss: 0.4310888946056366  (0.4422633945941925)
     | > postnet_loss: 0.2964332401752472  (0.3098775500600988)
     | > stopnet_loss: 0.00397849828004837  (0.005511464466425506)
     | > loss: 0.18585902452468872  (0.19354669930356921)
     | > align_error: 0.5454385280609131  (0.5862831211451328)

   --> STEP: 34
     | > decoder_loss: 0.4364452362060547  (0.44209227228865905)
     | > postnet_loss: 0.29772505164146423  (0.3095201236360213)
     | > stopnet_loss: 0.0032655049581080675  (0.005445406833827934)
     | > loss: 0.18680807948112488  (0.1933485046029091)
     | > align_error: 0.5629872977733612  (0.5855979498694924)

   --> STEP: 35
     | > decoder_loss: 0.43402326107025146  (0.44186172911099025)
     | > postnet_loss: 0.29770705103874207  (0.3091826072760991)
     | > stopnet_loss: 0.0034663223195821047  (0.005388861561992339)
     | > loss: 0.18639890849590302  (0.1931499447141375)
     | > align_error: 0.5323054194450378  (0.5840753061430795)

   --> STEP: 36
     | > decoder_loss: 0.4405618906021118  (0.44182562248574364)
     | > postnet_loss: 0.30188968777656555  (0.3089800261788898)
     | > stopnet_loss: 0.0036149518564343452  (0.005339586292393506)
     | > loss: 0.18922783434391022  (0.1930409972038534)
     | > align_error: 0.6331449747085571  (0.5854383524921205)

   --> STEP: 37
     | > decoder_loss: 0.43294528126716614  (0.4415856132636199)
     | > postnet_loss: 0.2987721562385559  (0.308704137802124)
     | > stopnet_loss: 0.0035239444114267826  (0.005290514890205216)
     | > loss: 0.18645331263542175  (0.19286295167497686)
     | > align_error: 0.5181969404220581  (0.5836210170307675)

   --> STEP: 38
     | > decoder_loss: 0.4201464056968689  (0.4410214235908107)
     | > postnet_loss: 0.2909732460975647  (0.30823753538884613)
     | > stopnet_loss: 0.003081758739426732  (0.005232389728342624)
     | > loss: 0.1808616667985916  (0.1925471283887562)
     | > align_error: 0.5508645176887512  (0.5827590038901881)

   --> STEP: 39
     | > decoder_loss: 0.4360838532447815  (0.44089481922296375)
     | > postnet_loss: 0.30238351225852966  (0.3080874322316585)
     | > stopnet_loss: 0.0034392771776765585  (0.00518641248345375)
     | > loss: 0.1880561113357544  (0.1924319741053459)
     | > align_error: 0.5451405346393585  (0.5817944277555515)

   --> STEP: 40
     | > decoder_loss: 0.4330563247203827  (0.4406988568603992)
     | > postnet_loss: 0.30057239532470703  (0.3078995563089847)
     | > stopnet_loss: 0.003001236589625478  (0.0051317830861080434)
     | > loss: 0.18640843033790588  (0.1922813855111599)
     | > align_error: 0.5830231606960297  (0.5818251460790634)

   --> STEP: 41
     | > decoder_loss: 0.42425134778022766  (0.44029769810234626)
     | > postnet_loss: 0.29325738549232483  (0.3075424301915052)
     | > stopnet_loss: 0.003717671614140272  (0.005097292562401513)
     | > loss: 0.18309485912322998  (0.1920573238919421)
     | > align_error: 0.5022344589233398  (0.5798839098069726)

   --> STEP: 42
     | > decoder_loss: 0.4286535978317261  (0.4400204576197125)
     | > postnet_loss: 0.2943548560142517  (0.30722844033014196)
     | > stopnet_loss: 0.0032469923608005047  (0.005053237795696728)
     | > loss: 0.18399910628795624  (0.19186546156803766)
     | > align_error: 0.5786862969398499  (0.5798553952148983)

   --> STEP: 43
     | > decoder_loss: 0.42780423164367676  (0.43973635934120003)
     | > postnet_loss: 0.293143630027771  (0.30690088660217985)
     | > stopnet_loss: 0.0029034491162747145  (0.005003242710128774)
     | > loss: 0.18314041197299957  (0.1916625534379205)
     | > align_error: 0.5508675277233124  (0.5791812587616055)

   --> STEP: 44
     | > decoder_loss: 0.44580867886543274  (0.4398743666031144)
     | > postnet_loss: 0.30490413308143616  (0.30685550584034477)
     | > stopnet_loss: 0.002639484591782093  (0.004949520934711804)
     | > loss: 0.19031769037246704  (0.1916319883682511)
     | > align_error: 0.5503128468990326  (0.5785251584920016)

   --> STEP: 45
     | > decoder_loss: 0.43839138746261597  (0.4398414115111033)
     | > postnet_loss: 0.30330196022987366  (0.3067765381601121)
     | > stopnet_loss: 0.0032655447721481323  (0.004912099242210389)
     | > loss: 0.18868888914585114  (0.19156658616330888)
     | > align_error: 0.5514857470989227  (0.5779242826832666)

   --> STEP: 46
     | > decoder_loss: 0.428902804851532  (0.4396036157141561)
     | > postnet_loss: 0.294880747795105  (0.3065179340217424)
     | > stopnet_loss: 0.003188635455444455  (0.00487463263815026)
     | > loss: 0.18413452804088593  (0.19140501968238666)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3550370136896769 (-0.0025889909628666885)
     | > avg_decoder_loss: 0.4357086555524306 (-0.00025604213729046865)
     | > avg_postnet_loss: 0.3035925161657911 (+0.0009696357177965131)
     | > avg_stopnet_loss: 0.004324377983610965 (-3.5451076021708605e-06)
     | > avg_loss: 0.1891496703028679 (+0.00017485158009963864)
     | > avg_align_error: 0.5707556794990192 (-0.00032445833538530255)


 > EPOCH: 167/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 21:53:13)

   --> TIME: 2025-12-28 21:53:16 -- STEP: 8/150 -- GLOBAL_STEP: 25225
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4550575315952301  (0.45543909817934036)
     | > postnet_loss: 0.3852677643299103  (0.3878219611942768)
     | > stopnet_loss: 0.009783281944692135  (0.012541417614556849)
     | > loss: 0.2198646068572998  (0.22335667721927166)
     | > align_error: 0.6866990327835083  (0.7014186792075634)
     | > grad_norm: tensor(0.1975, device='cuda:0')  (tensor(0.2962, device='cuda:0'))
     | > step_time: 0.2913  (0.2454223930835724)
     | > loader_time: 0.1243  (0.11696967482566833)


   --> TIME: 2025-12-28 21:53:59 -- STEP: 33/150 -- GLOBAL_STEP: 25250
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.4747666120529175  (0.46564796205722925)
     | > postnet_loss: 0.3943481147289276  (0.391970005902377)
     | > stopnet_loss: 0.0054939971305429935  (0.008704040961509403)
     | > loss: 0.22277268767356873  (0.22310853320540805)
     | > align_error: 0.6527155041694641  (0.6630551806001952)
     | > grad_norm: tensor(0.3597, device='cuda:0')  (tensor(0.2799, device='cuda:0'))
     | > step_time: 1.0509  (0.6829221248626709)
     | > loader_time: 0.9789  (0.7054718552213727)


   --> TIME: 2025-12-28 21:55:01 -- STEP: 58/150 -- GLOBAL_STEP: 25275
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.48023170232772827  (0.47169428909647054)
     | > postnet_loss: 0.39483165740966797  (0.3935721917399045)
     | > stopnet_loss: 0.004188109189271927  (0.007060115032925689)
     | > loss: 0.2229539453983307  (0.2233767345033843)
     | > align_error: 0.5981969833374023  (0.6428878435800816)
     | > grad_norm: tensor(0.2840, device='cuda:0')  (tensor(0.2684, device='cuda:0'))
     | > step_time: 1.3553  (0.9163316364946037)
     | > loader_time: 1.2597  (0.93931887478664)


   --> TIME: 2025-12-28 21:56:22 -- STEP: 83/150 -- GLOBAL_STEP: 25300
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47342532873153687  (0.4743507982018482)
     | > postnet_loss: 0.3863566517829895  (0.3934777030743749)
     | > stopnet_loss: 0.0036098018754273653  (0.006118925613721454)
     | > loss: 0.2185553014278412  (0.22307605000145464)
     | > align_error: 0.6214583516120911  (0.6337686482682284)
     | > grad_norm: tensor(0.1452, device='cuda:0')  (tensor(0.2482, device='cuda:0'))
     | > step_time: 1.746  (1.1180475734802615)
     | > loader_time: 1.7425  (1.1506110501576619)


   --> TIME: 2025-12-28 21:57:56 -- STEP: 108/150 -- GLOBAL_STEP: 25325
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48086950182914734  (0.47557163845609735)
     | > postnet_loss: 0.39135733246803284  (0.3929488901738768)
     | > stopnet_loss: 0.003220662008970976  (0.0055198187107668726)
     | > loss: 0.2212773710489273  (0.22264995039613159)
     | > align_error: 0.5832787752151489  (0.6280987381383225)
     | > grad_norm: tensor(0.2172, device='cuda:0')  (tensor(0.2332, device='cuda:0'))
     | > step_time: 2.0632  (1.2783701927573592)
     | > loader_time: 1.8858  (1.3327383509388677)


   --> TIME: 2025-12-28 21:59:39 -- STEP: 133/150 -- GLOBAL_STEP: 25350
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48299434781074524  (0.4765259195539288)
     | > postnet_loss: 0.39130663871765137  (0.39243853921280775)
     | > stopnet_loss: 0.0031358145643025637  (0.0050856118349540515)
     | > loss: 0.22171105444431305  (0.22232672594543687)
     | > align_error: 0.5588138103485107  (0.6245941658665363)
     | > grad_norm: tensor(0.1342, device='cuda:0')  (tensor(0.2275, device='cuda:0'))
     | > step_time: 2.2194  (1.418063009591927)
     | > loader_time: 2.0598  (1.475824761211424)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4574575126171112  (0.4574575126171112)
     | > postnet_loss: 0.3348698914051056  (0.3348698914051056)
     | > stopnet_loss: 0.012044914998114109  (0.012044914998114109)
     | > loss: 0.21012677252292633  (0.21012677252292633)
     | > align_error: 0.7187426090240479  (0.7187426090240479)

   --> STEP: 1
     | > decoder_loss: 0.43901970982551575  (0.43901970982551575)
     | > postnet_loss: 0.3232298195362091  (0.3232298195362091)
     | > stopnet_loss: 0.00957726314663887  (0.00957726314663887)
     | > loss: 0.20013964176177979  (0.20013964176177979)
     | > align_error: 0.6587255597114563  (0.6587255597114563)

   --> STEP: 2
     | > decoder_loss: 0.4352632462978363  (0.437141478061676)
     | > postnet_loss: 0.31338781118392944  (0.3183088153600693)
     | > stopnet_loss: 0.010909400880336761  (0.010243332013487816)
     | > loss: 0.1980721652507782  (0.199105903506279)
     | > align_error: 0.6546151041984558  (0.656670331954956)

   --> STEP: 3
     | > decoder_loss: 0.4396306574344635  (0.43797120451927185)
     | > postnet_loss: 0.3141084313392639  (0.31690868735313416)
     | > stopnet_loss: 0.008143987506628036  (0.009543550511201223)
     | > loss: 0.1965787708759308  (0.1982635259628296)
     | > align_error: 0.734365701675415  (0.6825687885284424)

   --> STEP: 4
     | > decoder_loss: 0.44247594475746155  (0.4390973895788193)
     | > postnet_loss: 0.32048892974853516  (0.3178037479519844)
     | > stopnet_loss: 0.008078627288341522  (0.009177319705486298)
     | > loss: 0.1988198459148407  (0.19840260595083237)
     | > align_error: 0.6025605201721191  (0.6625667214393616)

   --> STEP: 5
     | > decoder_loss: 0.4249380826950073  (0.4362655282020569)
     | > postnet_loss: 0.30301111936569214  (0.31484522223472594)
     | > stopnet_loss: 0.008039914071559906  (0.00894983857870102)
     | > loss: 0.19002720713615417  (0.19672752618789674)
     | > align_error: 0.6409468054771423  (0.6582427382469177)

   --> STEP: 6
     | > decoder_loss: 0.44326913356781006  (0.43743279576301575)
     | > postnet_loss: 0.3156656324863434  (0.3149819572766622)
     | > stopnet_loss: 0.00720182666555047  (0.008658503259842595)
     | > loss: 0.1969355046749115  (0.19676218926906586)
     | > align_error: 0.593041181564331  (0.6473758121331533)

   --> STEP: 7
     | > decoder_loss: 0.4539552628993988  (0.43979314821107046)
     | > postnet_loss: 0.3152090013027191  (0.31501439213752747)
     | > stopnet_loss: 0.006119939032942057  (0.008295851227428232)
     | > loss: 0.1984110027551651  (0.19699773405279433)
     | > align_error: 0.5781413614749908  (0.6374851763248444)

   --> STEP: 8
     | > decoder_loss: 0.45090585947036743  (0.4411822371184826)
     | > postnet_loss: 0.3179163932800293  (0.3153771422803402)
     | > stopnet_loss: 0.00706020463258028  (0.008141395403072238)
     | > loss: 0.1992657631635666  (0.19728123769164085)
     | > align_error: 0.5737618803977966  (0.6295197643339634)

   --> STEP: 9
     | > decoder_loss: 0.44520261883735657  (0.44162894619835746)
     | > postnet_loss: 0.3150232136249542  (0.3153378168741862)
     | > stopnet_loss: 0.006631769239902496  (0.007973659162720045)
     | > loss: 0.1966882348060608  (0.19721534848213196)
     | > align_error: 0.5900845527648926  (0.6251380741596222)

   --> STEP: 10
     | > decoder_loss: 0.47256845235824585  (0.4447228968143463)
     | > postnet_loss: 0.3309484124183655  (0.31689887642860415)
     | > stopnet_loss: 0.005530974827706814  (0.007729390729218721)
     | > loss: 0.20641018450260162  (0.19813483208417892)
     | > align_error: 0.5831525325775146  (0.6209395200014114)

   --> STEP: 11
     | > decoder_loss: 0.4575401842594147  (0.445888104763898)
     | > postnet_loss: 0.3190562427043915  (0.3170950006354939)
     | > stopnet_loss: 0.005919358693063259  (0.007564842362295498)
     | > loss: 0.20006845891475677  (0.19831061634150418)
     | > align_error: 0.5941072106361389  (0.6185002191500231)

   --> STEP: 12
     | > decoder_loss: 0.454396516084671  (0.4465971390406291)
     | > postnet_loss: 0.3133227825164795  (0.316780649125576)
     | > stopnet_loss: 0.00787712074816227  (0.007590865561117728)
     | > loss: 0.19980694353580475  (0.19843531027436256)
     | > align_error: 0.5864790976047516  (0.6158317923545837)

   --> STEP: 13
     | > decoder_loss: 0.44271835684776306  (0.4462987711796394)
     | > postnet_loss: 0.3123027980327606  (0.3164361990415133)
     | > stopnet_loss: 0.005267180036753416  (0.0074121205207820125)
     | > loss: 0.19402246177196503  (0.19809586038956276)
     | > align_error: 0.5837370753288269  (0.6133629679679871)

   --> STEP: 14
     | > decoder_loss: 0.4547213613986969  (0.4469003847667149)
     | > postnet_loss: 0.31602388620376587  (0.31640674812453135)
     | > stopnet_loss: 0.004846634808927774  (0.007228871541363853)
     | > loss: 0.19753295183181763  (0.1980556526354381)
     | > align_error: 0.5538729429244995  (0.6091136804648808)

   --> STEP: 15
     | > decoder_loss: 0.45202159881591797  (0.4472417990366618)
     | > postnet_loss: 0.3144497275352478  (0.3162762800852458)
     | > stopnet_loss: 0.004954820033162832  (0.007077268107483784)
     | > loss: 0.19657264649868011  (0.19795678555965424)
     | > align_error: 0.5880943536758423  (0.6077123920122782)

   --> STEP: 16
     | > decoder_loss: 0.45265281200408936  (0.447579987347126)
     | > postnet_loss: 0.30912914872169495  (0.31582958437502384)
     | > stopnet_loss: 0.005230249837040901  (0.006961829465581104)
     | > loss: 0.19567573070526123  (0.19781421963125467)
     | > align_error: 0.6047165095806122  (0.6075251493602991)

   --> STEP: 17
     | > decoder_loss: 0.46029582619667053  (0.44832797786768747)
     | > postnet_loss: 0.31766942143440247  (0.31593781008439903)
     | > stopnet_loss: 0.004746554419398308  (0.006831519168746822)
     | > loss: 0.1992378681898117  (0.19789796366411097)
     | > align_error: 0.5578133165836334  (0.6046009239028481)

   --> STEP: 18
     | > decoder_loss: 0.45199114084243774  (0.44853148692184025)
     | > postnet_loss: 0.3087804317474365  (0.3155401779545678)
     | > stopnet_loss: 0.005200608633458614  (0.006740913027897477)
     | > loss: 0.19539350271224976  (0.19775882694456312)
     | > align_error: 0.6032192707061768  (0.604524165391922)

   --> STEP: 19
     | > decoder_loss: 0.45009884238243103  (0.4486139793145029)
     | > postnet_loss: 0.30881035327911377  (0.3151859766558597)
     | > stopnet_loss: 0.0046796551905572414  (0.006632425773300622)
     | > loss: 0.19440695643424988  (0.19758241270717822)
     | > align_error: 0.5992392301559448  (0.604246010905818)

   --> STEP: 20
     | > decoder_loss: 0.4460946321487427  (0.4484880119562149)
     | > postnet_loss: 0.30422481894493103  (0.3146379187703133)
     | > stopnet_loss: 0.004433642607182264  (0.0065224866149947045)
     | > loss: 0.19201351702213287  (0.19730396792292595)
     | > align_error: 0.6219509541988373  (0.6051312580704689)

   --> STEP: 21
     | > decoder_loss: 0.44401222467422485  (0.44827487922850107)
     | > postnet_loss: 0.30442094802856445  (0.3141513963540395)
     | > stopnet_loss: 0.003935449756681919  (0.006399294383646477)
     | > loss: 0.19104374945163727  (0.19700586228143602)
     | > align_error: 0.5588933527469635  (0.6029294530550638)

   --> STEP: 22
     | > decoder_loss: 0.4466564655303955  (0.4482013149694963)
     | > postnet_loss: 0.30709806084632874  (0.3138307901945981)
     | > stopnet_loss: 0.004786125384271145  (0.0063259685200385074)
     | > loss: 0.1932247430086136  (0.19683399322358044)
     | > align_error: 0.6245033144950867  (0.6039100831205194)

   --> STEP: 23
     | > decoder_loss: 0.41999155282974243  (0.44697480357211566)
     | > postnet_loss: 0.2945597171783447  (0.312992917454761)
     | > stopnet_loss: 0.004443553742021322  (0.006244124399255152)
     | > loss: 0.18308137357234955  (0.19623605323874432)
     | > align_error: 0.5664357244968414  (0.6022807631803595)

   --> STEP: 24
     | > decoder_loss: 0.45364999771118164  (0.44725293666124344)
     | > postnet_loss: 0.3098263740539551  (0.3128609781463941)
     | > stopnet_loss: 0.004394774325191975  (0.006167068146169186)
     | > loss: 0.19526386260986328  (0.19619554529587427)
     | > align_error: 0.5788626670837402  (0.6013050091763337)

   --> STEP: 25
     | > decoder_loss: 0.4528987407684326  (0.447478768825531)
     | > postnet_loss: 0.3076325058937073  (0.31265183925628665)
     | > stopnet_loss: 0.0036498247645795345  (0.006066378410905599)
     | > loss: 0.19378264248371124  (0.19609902918338776)
     | > align_error: 0.557267427444458  (0.5995435059070586)

   --> STEP: 26
     | > decoder_loss: 0.4289175868034363  (0.4467648772092966)
     | > postnet_loss: 0.2968609631061554  (0.31204449786589694)
     | > stopnet_loss: 0.004274649079889059  (0.005997465744328041)
     | > loss: 0.185719296336174  (0.19569980868926415)
     | > align_error: 0.5458149611949921  (0.597477023418133)

   --> STEP: 27
     | > decoder_loss: 0.42511430382728577  (0.445963004121074)
     | > postnet_loss: 0.29102346301078796  (0.31126594101941146)
     | > stopnet_loss: 0.0038780709728598595  (0.005918969641681071)
     | > loss: 0.18291251361370087  (0.195226205167947)
     | > align_error: 0.5399887561798096  (0.5953478283352323)

   --> STEP: 28
     | > decoder_loss: 0.43122923374176025  (0.4454367980360985)
     | > postnet_loss: 0.2963186502456665  (0.3107321092060634)
     | > stopnet_loss: 0.0039058735128492117  (0.005847073351365647)
     | > loss: 0.18579284846782684  (0.19488929957151413)
     | > align_error: 0.5655595064163208  (0.594283959695271)

   --> STEP: 29
     | > decoder_loss: 0.42588070034980774  (0.4447624498400195)
     | > postnet_loss: 0.29297780990600586  (0.31011989198882006)
     | > stopnet_loss: 0.003518338082358241  (0.005766772135192978)
     | > loss: 0.18323296308517456  (0.19448735693405414)
     | > align_error: 0.5397593975067139  (0.5924038023784243)

   --> STEP: 30
     | > decoder_loss: 0.42719513177871704  (0.4441768725713094)
     | > postnet_loss: 0.29390567541122437  (0.3095794181029002)
     | > stopnet_loss: 0.002783599542453885  (0.005667333048768342)
     | > loss: 0.18305879831314087  (0.1941064049800237)
     | > align_error: 0.5324875712394714  (0.5904065946737925)

   --> STEP: 31
     | > decoder_loss: 0.42146843671798706  (0.4434443423824926)
     | > postnet_loss: 0.2909742295742035  (0.30897925073100674)
     | > stopnet_loss: 0.0036407464649528265  (0.005601959288000099)
     | > loss: 0.18175140023231506  (0.19370785643977503)
     | > align_error: 0.5533664226531982  (0.5892117504150637)

   --> STEP: 32
     | > decoder_loss: 0.4353120028972626  (0.4431902067735791)
     | > postnet_loss: 0.2984163761138916  (0.3086491608992219)
     | > stopnet_loss: 0.0037635548505932093  (0.005544509149331134)
     | > loss: 0.18719565868377686  (0.1935043502599001)
     | > align_error: 0.5300124883651733  (0.5873617734760046)

   --> STEP: 33
     | > decoder_loss: 0.4305916428565979  (0.44280843210942816)
     | > postnet_loss: 0.2950093150138855  (0.3082358322360299)
     | > stopnet_loss: 0.003973029553890228  (0.005496888555529894)
     | > loss: 0.18537327647209167  (0.19325795408451196)
     | > align_error: 0.5448927879333496  (0.5860748345201666)

   --> STEP: 34
     | > decoder_loss: 0.43641117215156555  (0.44262027740478516)
     | > postnet_loss: 0.2965383529663086  (0.3078917887280969)
     | > stopnet_loss: 0.0032329873647540808  (0.005430303226389429)
     | > loss: 0.18647035956382751  (0.19305831895155065)
     | > align_error: 0.5625137388706207  (0.5853818611187094)

   --> STEP: 35
     | > decoder_loss: 0.43391653895378113  (0.4423715991633279)
     | > postnet_loss: 0.29620087146759033  (0.30755776252065387)
     | > stopnet_loss: 0.003473726799711585  (0.005374401042770062)
     | > loss: 0.18600308895111084  (0.1928567409515381)
     | > align_error: 0.5318328440189362  (0.5838518892015729)

   --> STEP: 36
     | > decoder_loss: 0.44001299142837524  (0.44230608228180146)
     | > postnet_loss: 0.30032962560653687  (0.30735698093970615)
     | > stopnet_loss: 0.0036001678090542555  (0.005325116786277956)
     | > loss: 0.1886858195066452  (0.19274088202251327)
     | > align_error: 0.6327950954437256  (0.5852114227082994)

   --> STEP: 37
     | > decoder_loss: 0.4330413341522217  (0.4420556836837047)
     | > postnet_loss: 0.29721373319625854  (0.3070828391088022)
     | > stopnet_loss: 0.003510197391733527  (0.005276064910749729)
     | > loss: 0.18607395887374878  (0.19256069491038452)
     | > align_error: 0.5176422595977783  (0.5833852291107178)

   --> STEP: 38
     | > decoder_loss: 0.41997984051704407  (0.44147474044247675)
     | > postnet_loss: 0.28937557339668274  (0.30661685843216746)
     | > stopnet_loss: 0.003089061239734292  (0.005218512182565112)
     | > loss: 0.1804279088973999  (0.19224141106793755)
     | > align_error: 0.5504089593887329  (0.5825174325390866)

   --> STEP: 39
     | > decoder_loss: 0.435612291097641  (0.4413244212285066)
     | > postnet_loss: 0.3004314601421356  (0.30645825847601277)
     | > stopnet_loss: 0.0034297225065529346  (0.005172645780616081)
     | > loss: 0.1874406635761261  (0.19211831497840393)
     | > align_error: 0.5448006093502045  (0.5815503345086024)

   --> STEP: 40
     | > decoder_loss: 0.43295374512672424  (0.44111515432596204)
     | > postnet_loss: 0.29879745841026306  (0.306266738474369)
     | > stopnet_loss: 0.0029937129002064466  (0.005118172458605841)
     | > loss: 0.1859315186738968  (0.19196364507079125)
     | > align_error: 0.5826902389526367  (0.5815788321197032)

   --> STEP: 41
     | > decoder_loss: 0.42379873991012573  (0.4406928027548441)
     | > postnet_loss: 0.2913145422935486  (0.3059020507626417)
     | > stopnet_loss: 0.0037090471014380455  (0.005083803547455407)
     | > loss: 0.1824873685836792  (0.19173251637598362)
     | > align_error: 0.5021544098854065  (0.5796416510895984)

   --> STEP: 42
     | > decoder_loss: 0.428984671831131  (0.4404140377328509)
     | > postnet_loss: 0.2933201789855957  (0.3056024823869978)
     | > stopnet_loss: 0.003262629732489586  (0.005040442266146697)
     | > loss: 0.1838388293981552  (0.1915445714479401)
     | > align_error: 0.5783585011959076  (0.5796110999016534)

   --> STEP: 43
     | > decoder_loss: 0.427634060382843  (0.44011682895726933)
     | > postnet_loss: 0.291821151971817  (0.30528198633083076)
     | > stopnet_loss: 0.0028725501615554094  (0.004990026170691085)
     | > loss: 0.1827363669872284  (0.1913397294837375)
     | > align_error: 0.5506985485553741  (0.5789387149866236)

   --> STEP: 44
     | > decoder_loss: 0.4458252787590027  (0.4402465664527633)
     | > postnet_loss: 0.30324116349220276  (0.30523560399358923)
     | > stopnet_loss: 0.0026220616418868303  (0.004936208795036443)
     | > loss: 0.18988868594169617  (0.19130675122141838)
     | > align_error: 0.5498400032520294  (0.5782773806290192)

   --> STEP: 45
     | > decoder_loss: 0.4383184015750885  (0.4402037183443705)
     | > postnet_loss: 0.301952064037323  (0.30516263643900554)
     | > stopnet_loss: 0.0032643871381878853  (0.0048990572026620305)
     | > loss: 0.18833200633525848  (0.19124064577950373)
     | > align_error: 0.551146924495697  (0.5776744816038343)

   --> STEP: 46
     | > decoder_loss: 0.42858079075813293  (0.43995104600553925)
     | > postnet_loss: 0.2932273745536804  (0.3049031742241072)
     | > stopnet_loss: 0.003177379025146365  (0.004861629416194299)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.38717643781141803 (+0.032139424121741145)
     | > avg_decoder_loss: 0.436110259457068 (+0.00040160390463739315)
     | > avg_postnet_loss: 0.30186753291072266 (-0.001724983255068424)
     | > avg_stopnet_loss: 0.004316098631754743 (-8.279351856222035e-06)
     | > avg_loss: 0.18881054696711627 (-0.0003391233357516177)
     | > avg_align_error: 0.570496188420238 (-0.00025949107878120437)


 > EPOCH: 168/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 22:03:12)

   --> TIME: 2025-12-28 22:03:21 -- STEP: 7/150 -- GLOBAL_STEP: 25375
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4617905020713806  (0.45646082503455027)
     | > postnet_loss: 0.39151379466056824  (0.38890399251665386)
     | > stopnet_loss: 0.010986818000674248  (0.013083470985293388)
     | > loss: 0.224312886595726  (0.22442467297826493)
     | > align_error: 0.6701244115829468  (0.7035918618951525)
     | > grad_norm: tensor(0.2630, device='cuda:0')  (tensor(0.3040, device='cuda:0'))
     | > step_time: 0.5313  (0.4820735113961356)
     | > loader_time: 0.7074  (0.6550170012882778)


   --> TIME: 2025-12-28 22:04:06 -- STEP: 32/150 -- GLOBAL_STEP: 25400
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.47670459747314453  (0.46504328213632107)
     | > postnet_loss: 0.3972611427307129  (0.39172975812107325)
     | > stopnet_loss: 0.005679748952388763  (0.008770280939643271)
     | > loss: 0.22417119145393372  (0.2229635422118008)
     | > align_error: 0.6323245763778687  (0.6636346662417054)
     | > grad_norm: tensor(0.3227, device='cuda:0')  (tensor(0.2840, device='cuda:0'))
     | > step_time: 1.0245  (0.758192852139473)
     | > loader_time: 1.274  (0.9011563137173653)


   --> TIME: 2025-12-28 22:05:09 -- STEP: 57/150 -- GLOBAL_STEP: 25425
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4814188778400421  (0.4708705685640636)
     | > postnet_loss: 0.39537179470062256  (0.39312242520482915)
     | > stopnet_loss: 0.004429674707353115  (0.007058122669134225)
     | > loss: 0.22362732887268066  (0.22305637153617122)
     | > align_error: 0.6572603583335876  (0.6440030001757437)
     | > grad_norm: tensor(0.1856, device='cuda:0')  (tensor(0.2630, device='cuda:0'))
     | > step_time: 1.5658  (0.9933236816473174)
     | > loader_time: 1.2804  (1.0421683788299558)


   --> TIME: 2025-12-28 22:06:28 -- STEP: 82/150 -- GLOBAL_STEP: 25450
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4780549108982086  (0.4739159480100725)
     | > postnet_loss: 0.39081090688705444  (0.393210371819938)
     | > stopnet_loss: 0.0035703089088201523  (0.006109296980245811)
     | > loss: 0.22078676521778107  (0.22289087750562808)
     | > align_error: 0.642272412776947  (0.6340514970261876)
     | > grad_norm: tensor(0.2253, device='cuda:0')  (tensor(0.2427, device='cuda:0'))
     | > step_time: 1.7264  (1.1788786911382907)
     | > loader_time: 1.4858  (1.1908893875959439)


   --> TIME: 2025-12-28 22:07:59 -- STEP: 107/150 -- GLOBAL_STEP: 25475
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48712795972824097  (0.4751839768663745)
     | > postnet_loss: 0.3954649865627289  (0.3926339135548778)
     | > stopnet_loss: 0.003534893970936537  (0.0055086501682542754)
     | > loss: 0.22418312728405  (0.22246312315218916)
     | > align_error: 0.6014998853206635  (0.6286918598914815)
     | > grad_norm: tensor(0.1808, device='cuda:0')  (tensor(0.2337, device='cuda:0'))
     | > step_time: 1.9925  (1.321603991160883)
     | > loader_time: 2.0554  (1.350909119454499)


   --> TIME: 2025-12-28 22:09:44 -- STEP: 132/150 -- GLOBAL_STEP: 25500
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4815455377101898  (0.4761166141340227)
     | > postnet_loss: 0.3896433115005493  (0.39211014455015003)
     | > stopnet_loss: 0.003233878640457988  (0.005076441033672767)
     | > loss: 0.2210310995578766  (0.22213313073822946)
     | > align_error: 0.589909553527832  (0.6253870468248021)
     | > grad_norm: tensor(0.2120, device='cuda:0')  (tensor(0.2263, device='cuda:0'))
     | > step_time: 1.9465  (1.4640588959058125)
     | > loader_time: 2.0154  (1.4980110923449195)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4576762914657593  (0.4576762914657593)
     | > postnet_loss: 0.3358258903026581  (0.3358258903026581)
     | > stopnet_loss: 0.01211574673652649  (0.01211574673652649)
     | > loss: 0.21049129962921143  (0.21049129962921143)
     | > align_error: 0.7186248302459717  (0.7186248302459717)

   --> STEP: 1
     | > decoder_loss: 0.43812793493270874  (0.43812793493270874)
     | > postnet_loss: 0.32356250286102295  (0.32356250286102295)
     | > stopnet_loss: 0.009633542969822884  (0.009633542969822884)
     | > loss: 0.20005615055561066  (0.20005615055561066)
     | > align_error: 0.6587527394294739  (0.6587527394294739)

   --> STEP: 2
     | > decoder_loss: 0.43468573689460754  (0.43640683591365814)
     | > postnet_loss: 0.314005047082901  (0.318783774971962)
     | > stopnet_loss: 0.010882878676056862  (0.010258210822939873)
     | > loss: 0.19805558025836945  (0.19905586540699005)
     | > align_error: 0.6547613739967346  (0.6567570567131042)

   --> STEP: 3
     | > decoder_loss: 0.4396136999130249  (0.4374757905801137)
     | > postnet_loss: 0.31465810537338257  (0.3174085517724355)
     | > stopnet_loss: 0.008182980120182037  (0.009566467255353928)
     | > loss: 0.1967509388923645  (0.19828755656878153)
     | > align_error: 0.7343885600566864  (0.6826342244942983)

   --> STEP: 4
     | > decoder_loss: 0.4422565698623657  (0.4386709854006767)
     | > postnet_loss: 0.3211105167865753  (0.31833404302597046)
     | > stopnet_loss: 0.00816726591438055  (0.009216666920110583)
     | > loss: 0.1990090310573578  (0.1984679251909256)
     | > align_error: 0.6026990413665771  (0.662650428712368)

   --> STEP: 5
     | > decoder_loss: 0.4248737394809723  (0.43591153621673584)
     | > postnet_loss: 0.3037126958370209  (0.31540977358818056)
     | > stopnet_loss: 0.008021125569939613  (0.008977558650076389)
     | > loss: 0.19016773998737335  (0.19680788815021516)
     | > align_error: 0.6410681009292603  (0.6583339631557464)

   --> STEP: 6
     | > decoder_loss: 0.4429473578929901  (0.4370841731627782)
     | > postnet_loss: 0.31632155179977417  (0.31556173662344617)
     | > stopnet_loss: 0.007224180269986391  (0.008685328920061389)
     | > loss: 0.19704140722751617  (0.19684680799643198)
     | > align_error: 0.5931759774684906  (0.6474742988745371)

   --> STEP: 7
     | > decoder_loss: 0.4529957175254822  (0.4393572509288788)
     | > postnet_loss: 0.3151094615459442  (0.3154971258980887)
     | > stopnet_loss: 0.0061397734098136425  (0.00832167813288314)
     | > loss: 0.19816605746746063  (0.19703527220657893)
     | > align_error: 0.5781398415565491  (0.6375693764005389)

   --> STEP: 8
     | > decoder_loss: 0.44907912611961365  (0.44057248532772064)
     | > postnet_loss: 0.3174313008785248  (0.31573889777064323)
     | > stopnet_loss: 0.007059802301228046  (0.008163943653926253)
     | > loss: 0.19868740439414978  (0.1972417887300253)
     | > align_error: 0.5738987326622009  (0.6296105459332466)

   --> STEP: 9
     | > decoder_loss: 0.4445851445198059  (0.44101833634906346)
     | > postnet_loss: 0.31495970487594604  (0.31565232078234357)
     | > stopnet_loss: 0.006631741765886545  (0.007993698999699619)
     | > loss: 0.1965179592370987  (0.19716136323081124)
     | > align_error: 0.5901351571083069  (0.6252243916193644)

   --> STEP: 10
     | > decoder_loss: 0.4705180525779724  (0.44396830797195436)
     | > postnet_loss: 0.33043378591537476  (0.31713046729564665)
     | > stopnet_loss: 0.005551785230636597  (0.007749507622793317)
     | > loss: 0.2057897448539734  (0.19802420139312743)
     | > align_error: 0.5830175280570984  (0.6210037052631379)

   --> STEP: 11
     | > decoder_loss: 0.45589855313301086  (0.4450528757138686)
     | > postnet_loss: 0.31844329833984375  (0.31724981557239185)
     | > stopnet_loss: 0.005926769692450762  (0.0075838041745803575)
     | > loss: 0.19951222836971283  (0.19815947657281702)
     | > align_error: 0.5943587124347687  (0.6185814331878315)

   --> STEP: 12
     | > decoder_loss: 0.45289063453674316  (0.44570602228244144)
     | > postnet_loss: 0.31302493810653687  (0.3168977424502373)
     | > stopnet_loss: 0.007863014936447144  (0.007607071738069256)
     | > loss: 0.19934190809726715  (0.19825801253318787)
     | > align_error: 0.5869330167770386  (0.6159440651535988)

   --> STEP: 13
     | > decoder_loss: 0.44203856587409973  (0.44542391025103056)
     | > postnet_loss: 0.31221267580986023  (0.3165373527086698)
     | > stopnet_loss: 0.005266802851110697  (0.007427051054457059)
     | > loss: 0.19382961094379425  (0.19791736625708067)
     | > align_error: 0.5842898190021515  (0.6135091231419489)

   --> STEP: 14
     | > decoder_loss: 0.4539235532283783  (0.4460310276065554)
     | > postnet_loss: 0.3162840008735657  (0.3165192561490195)
     | > stopnet_loss: 0.004892393015325069  (0.007246004051661917)
     | > loss: 0.19744427502155304  (0.19788357402597154)
     | > align_error: 0.5543097853660583  (0.6092805990150997)

   --> STEP: 15
     | > decoder_loss: 0.452362984418869  (0.4464531580607096)
     | > postnet_loss: 0.3152761459350586  (0.31643638213475545)
     | > stopnet_loss: 0.004965036176145077  (0.007093939526627461)
     | > loss: 0.19687482714653015  (0.1978163242340088)
     | > align_error: 0.588298112154007  (0.6078817665576934)

   --> STEP: 16
     | > decoder_loss: 0.45270997285842896  (0.4468442089855671)
     | > postnet_loss: 0.3095836043357849  (0.3160080835223198)
     | > stopnet_loss: 0.0052337646484375  (0.0069776785967405885)
     | > loss: 0.19580715894699097  (0.19769075140357018)
     | > align_error: 0.6051096320152283  (0.6077085081487894)

   --> STEP: 17
     | > decoder_loss: 0.4589950442314148  (0.4475589640000287)
     | > postnet_loss: 0.317298948764801  (0.31608401677187753)
     | > stopnet_loss: 0.0047597805969417095  (0.006847214008517125)
     | > loss: 0.19883327186107635  (0.19775795848930583)
     | > align_error: 0.5582888424396515  (0.6048014689894283)

   --> STEP: 18
     | > decoder_loss: 0.4520324766635895  (0.44780749248133767)
     | > postnet_loss: 0.3092767298221588  (0.3157058341635598)
     | > stopnet_loss: 0.005166506860405207  (0.006753841389177574)
     | > loss: 0.19549380242824554  (0.19763217204146916)
     | > align_error: 0.6037827730178833  (0.6047448747687869)

   --> STEP: 19
     | > decoder_loss: 0.4477498531341553  (0.44780445883148595)
     | > postnet_loss: 0.3080689311027527  (0.31530389189720154)
     | > stopnet_loss: 0.004681054037064314  (0.006644747318013718)
     | > loss: 0.1936357468366623  (0.1974218338727951)
     | > align_error: 0.5987976491451263  (0.6044318628938574)

   --> STEP: 20
     | > decoder_loss: 0.4458293914794922  (0.44770570546388627)
     | > postnet_loss: 0.30491557717323303  (0.31478447616100313)
     | > stopnet_loss: 0.004439018666744232  (0.006534460885450244)
     | > loss: 0.19212526082992554  (0.19715700522065163)
     | > align_error: 0.6225039958953857  (0.6053354695439339)

   --> STEP: 21
     | > decoder_loss: 0.4433739483356476  (0.44749943131492254)
     | > postnet_loss: 0.3047213554382324  (0.3143052799361093)
     | > stopnet_loss: 0.003927166108042002  (0.006410303991287947)
     | > loss: 0.19095098972320557  (0.1968614806731542)
     | > align_error: 0.5594542026519775  (0.6031506473109836)

   --> STEP: 22
     | > decoder_loss: 0.4470673203468323  (0.44747978990728204)
     | > postnet_loss: 0.3080567419528961  (0.3140212554823269)
     | > stopnet_loss: 0.004772914107888937  (0.006335877178406174)
     | > loss: 0.19355393946170807  (0.19671113789081573)
     | > align_error: 0.6250003576278687  (0.604143815961751)

   --> STEP: 23
     | > decoder_loss: 0.4195474684238434  (0.44626534114713257)
     | > postnet_loss: 0.29502707719802856  (0.31319542164387915)
     | > stopnet_loss: 0.004442760720849037  (0.006253567767208037)
     | > loss: 0.18308641016483307  (0.19611875842446866)
     | > align_error: 0.5668796896934509  (0.6025236365587815)

   --> STEP: 24
     | > decoder_loss: 0.45430833101272583  (0.4466004657248656)
     | > postnet_loss: 0.31105947494506836  (0.313106423864762)
     | > stopnet_loss: 0.0043755341321229935  (0.00617531636574616)
     | > loss: 0.1957174837589264  (0.19610203864673773)
     | > align_error: 0.5792457163333893  (0.6015537232160568)

   --> STEP: 25
     | > decoder_loss: 0.4534805119037628  (0.44687566757202146)
     | > postnet_loss: 0.3084729313850403  (0.3129210841655731)
     | > stopnet_loss: 0.0036585850175470114  (0.006074647111818194)
     | > loss: 0.19414694607257843  (0.19602383494377137)
     | > align_error: 0.5580671727657318  (0.5998142611980438)

   --> STEP: 26
     | > decoder_loss: 0.428232878446579  (0.44615863722104293)
     | > postnet_loss: 0.2972220480442047  (0.31231727508398205)
     | > stopnet_loss: 0.004262922331690788  (0.0060049653895056015)
     | > loss: 0.18562665581703186  (0.19562394343889677)
     | > align_error: 0.546474277973175  (0.5977627233817027)

   --> STEP: 27
     | > decoder_loss: 0.42508476972579956  (0.445378123610108)
     | > postnet_loss: 0.2915448546409607  (0.31154792617868493)
     | > stopnet_loss: 0.0038579104002565145  (0.005925444834348228)
     | > loss: 0.18301531672477722  (0.19515695726429974)
     | > align_error: 0.5405538976192474  (0.5956438779830933)

   --> STEP: 28
     | > decoder_loss: 0.4308868944644928  (0.4448605797120503)
     | > postnet_loss: 0.2969150245189667  (0.3110253225479807)
     | > stopnet_loss: 0.003914297558367252  (0.005853618145920336)
     | > loss: 0.18586477637290955  (0.19482509366103581)
     | > align_error: 0.5660866498947144  (0.5945882626942226)

   --> STEP: 29
     | > decoder_loss: 0.42561060190200806  (0.444196787373773)
     | > postnet_loss: 0.2935173511505127  (0.3104215993963439)
     | > stopnet_loss: 0.003514273790642619  (0.005772951099186622)
     | > loss: 0.18329626321792603  (0.1944275477836872)
     | > align_error: 0.5403571128845215  (0.5927182230456122)

   --> STEP: 30
     | > decoder_loss: 0.42662039399147034  (0.4436109075943629)
     | > postnet_loss: 0.2943262755870819  (0.3098850886027018)
     | > stopnet_loss: 0.002761227311566472  (0.00567256030626595)
     | > loss: 0.1829978972673416  (0.19404655943314233)
     | > align_error: 0.5330084562301636  (0.5907278974850972)

   --> STEP: 31
     | > decoder_loss: 0.42090728878974915  (0.4428785327942141)
     | > postnet_loss: 0.291324257850647  (0.3092863521268291)
     | > stopnet_loss: 0.0036416768562048674  (0.005607047936909141)
     | > loss: 0.18169955909252167  (0.19364826909957394)
     | > align_error: 0.5537909269332886  (0.5895363823060067)

   --> STEP: 32
     | > decoder_loss: 0.43527790904045105  (0.44264101330190897)
     | > postnet_loss: 0.2991948425769806  (0.3089709924533963)
     | > stopnet_loss: 0.0037763717118650675  (0.005549839304876514)
     | > loss: 0.18739455938339233  (0.19345284067094326)
     | > align_error: 0.5310081243515015  (0.5877073742449284)

   --> STEP: 33
     | > decoder_loss: 0.4310188591480255  (0.44228882681239734)
     | > postnet_loss: 0.2958139479160309  (0.3085722941340822)
     | > stopnet_loss: 0.003973252139985561  (0.005502063936243455)
     | > loss: 0.18568144738674164  (0.19321734390475534)
     | > align_error: 0.5456603467464447  (0.5864332218964895)

   --> STEP: 34
     | > decoder_loss: 0.43721145391464233  (0.44213949231540456)
     | > postnet_loss: 0.29775765538215637  (0.3082542165237315)
     | > stopnet_loss: 0.0032398176845163107  (0.005435527281780892)
     | > loss: 0.18698209524154663  (0.19303395423819036)
     | > align_error: 0.5633189082145691  (0.5857533891411388)

   --> STEP: 35
     | > decoder_loss: 0.43434956669807434  (0.44191692301205227)
     | > postnet_loss: 0.29705342650413513  (0.307934193951743)
     | > stopnet_loss: 0.003481185296550393  (0.0053796889393457345)
     | > loss: 0.18633192777633667  (0.1928424677678517)
     | > align_error: 0.5325859189033508  (0.5842343185629163)

   --> STEP: 36
     | > decoder_loss: 0.44060012698173523  (0.44188034534454346)
     | > postnet_loss: 0.3011925518512726  (0.3077469261156188)
     | > stopnet_loss: 0.003588654100894928  (0.0053299379716109895)
     | > loss: 0.18903681635856628  (0.19273675522870487)
     | > align_error: 0.6333158612251282  (0.5855976947479777)

   --> STEP: 37
     | > decoder_loss: 0.43265968561172485  (0.44163113832473755)
     | > postnet_loss: 0.2977999448776245  (0.3074780887848622)
     | > stopnet_loss: 0.003505121450871229  (0.005280618606185591)
     | > loss: 0.18612003326416016  (0.1925579249053388)
     | > align_error: 0.5182732939720154  (0.5837781163486274)

   --> STEP: 38
     | > decoder_loss: 0.4197111129760742  (0.44105429555240433)
     | > postnet_loss: 0.2900049686431885  (0.3070182698337655)
     | > stopnet_loss: 0.003079858375713229  (0.005222703863278423)
     | > loss: 0.18050888180732727  (0.19224084482381218)
     | > align_error: 0.5512354969978333  (0.5829217316288697)

   --> STEP: 39
     | > decoder_loss: 0.436100035905838  (0.4409272632537744)
     | > postnet_loss: 0.3013112545013428  (0.30687193610729313)
     | > stopnet_loss: 0.0034232514444738626  (0.00517656405766805)
     | > loss: 0.18777607381343842  (0.19212636351585388)
     | > align_error: 0.5455871522426605  (0.581964434721531)

   --> STEP: 40
     | > decoder_loss: 0.4328940808773041  (0.44072643369436265)
     | > postnet_loss: 0.29958146810531616  (0.3066896744072437)
     | > stopnet_loss: 0.0029893063474446535  (0.005121882614912465)
     | > loss: 0.18610818684101105  (0.19197590909898282)
     | > align_error: 0.5833783745765686  (0.5819997832179069)

   --> STEP: 41
     | > decoder_loss: 0.4237302243709564  (0.44031189200354787)
     | > postnet_loss: 0.29211100935935974  (0.3063340972109539)
     | > stopnet_loss: 0.0037056333385407925  (0.005087339949635107)
     | > loss: 0.18266594409942627  (0.19174883678192045)
     | > align_error: 0.5028536915779114  (0.5800693907388826)

   --> STEP: 42
     | > decoder_loss: 0.42931264638900757  (0.44005000520320164)
     | > postnet_loss: 0.29422739148139954  (0.30604584231263116)
     | > stopnet_loss: 0.0032478151842951775  (0.005043541740936537)
     | > loss: 0.18413282930850983  (0.19156750327064878)
     | > align_error: 0.5789834260940552  (0.5800435344378153)

   --> STEP: 43
     | > decoder_loss: 0.42780187726020813  (0.4397651650184809)
     | > postnet_loss: 0.2927185297012329  (0.3057359048100405)
     | > stopnet_loss: 0.0028866787906736135  (0.004993382137442051)
     | > loss: 0.18301677703857422  (0.19136864917222843)
     | > align_error: 0.5511853098869324  (0.579372412936632)

   --> STEP: 44
     | > decoder_loss: 0.44597285985946655  (0.43990624899213965)
     | > postnet_loss: 0.30412745475769043  (0.30569934912703256)
     | > stopnet_loss: 0.0026326419319957495  (0.004939728950954635)
     | > loss: 0.1901577264070511  (0.1913411282002926)
     | > align_error: 0.5504060089588165  (0.5787140855734999)

   --> STEP: 45
     | > decoder_loss: 0.43875545263290405  (0.4398806757397122)
     | > postnet_loss: 0.3029155135154724  (0.3056374861134423)
     | > stopnet_loss: 0.0032456605695188046  (0.004902082986922728)
     | > loss: 0.18866340816020966  (0.19128162331051296)
     | > align_error: 0.5517987012863159  (0.5781159659226737)

   --> STEP: 46
     | > decoder_loss: 0.4291653037071228  (0.4396477328694385)
     | > postnet_loss: 0.2942711412906647  (0.30539039166077325)
     | > stopnet_loss: 0.0031659635715186596  (0.0048643412605009)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.4231570814595078 (+0.03598064364808978)
     | > avg_decoder_loss: 0.4358050985769792 (-0.00030516088008880615)
     | > avg_postnet_loss: 0.30244778683691315 (+0.0005802539261904882)
     | > avg_stopnet_loss: 0.004316001724818665 (-9.690693607809775e-08)
     | > avg_loss: 0.18887922325820633 (+6.867629109005846e-05)
     | > avg_align_error: 0.5710141193686111 (+0.0005179309483731576)


 > EPOCH: 169/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 22:13:16)

   --> TIME: 2025-12-28 22:13:24 -- STEP: 6/150 -- GLOBAL_STEP: 25525
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.44948241114616394  (0.45479874312877655)
     | > postnet_loss: 0.38205036520957947  (0.3880437761545181)
     | > stopnet_loss: 0.011705279350280762  (0.013592491547266642)
     | > loss: 0.2195884734392166  (0.22430311888456345)
     | > align_error: 0.7016644477844238  (0.7094679971536001)
     | > grad_norm: tensor(0.1825, device='cuda:0')  (tensor(0.2885, device='cuda:0'))
     | > step_time: 0.491  (0.4449574152628581)
     | > loader_time: 0.8743  (0.5866348346074423)


   --> TIME: 2025-12-28 22:14:06 -- STEP: 31/150 -- GLOBAL_STEP: 25550
     | > current_lr: 1e-05  (1.0000000000000008e-05)
     | > decoder_loss: 0.47254320979118347  (0.4647431479346368)
     | > postnet_loss: 0.39357081055641174  (0.39130701653419003)
     | > stopnet_loss: 0.006175524555146694  (0.008967342786490917)
     | > loss: 0.22270402312278748  (0.22297988255177775)
     | > align_error: 0.6447383463382721  (0.6645204030698345)
     | > grad_norm: tensor(0.1429, device='cuda:0')  (tensor(0.2908, device='cuda:0'))
     | > step_time: 1.0206  (0.7020003487986903)
     | > loader_time: 1.3953  (0.8754796674174647)


   --> TIME: 2025-12-28 22:15:14 -- STEP: 56/150 -- GLOBAL_STEP: 25575
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4741628170013428  (0.4706644059291908)
     | > postnet_loss: 0.38988643884658813  (0.39281892137868063)
     | > stopnet_loss: 0.004490749444812536  (0.007187991278312568)
     | > loss: 0.2205030620098114  (0.22305882136736596)
     | > align_error: 0.6148146092891693  (0.6435620710253718)
     | > grad_norm: tensor(0.1932, device='cuda:0')  (tensor(0.2789, device='cuda:0'))
     | > step_time: 1.2841  (0.9422061273029874)
     | > loader_time: 1.3227  (1.1299200057983396)


   --> TIME: 2025-12-28 22:16:26 -- STEP: 81/150 -- GLOBAL_STEP: 25600
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4836508631706238  (0.47333317112039636)
     | > postnet_loss: 0.39385250210762024  (0.39274593966978566)
     | > stopnet_loss: 0.0036578732542693615  (0.006223935654018948)
     | > loss: 0.22303372621536255  (0.2227437122736448)
     | > align_error: 0.6919490694999695  (0.6340003767867148)
     | > grad_norm: tensor(0.2088, device='cuda:0')  (tensor(0.2553, device='cuda:0'))
     | > step_time: 1.7028  (1.124178127006248)
     | > loader_time: 1.5549  (1.2053281230691038)


   --> TIME: 2025-12-28 22:17:49 -- STEP: 106/150 -- GLOBAL_STEP: 25625
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47823673486709595  (0.4747865737046836)
     | > postnet_loss: 0.3897324502468109  (0.39233583549283585)
     | > stopnet_loss: 0.003296194365248084  (0.005596810523508433)
     | > loss: 0.22028848528862  (0.22237741202116013)
     | > align_error: 0.6248638927936554  (0.629170517033001)
     | > grad_norm: tensor(0.2605, device='cuda:0')  (tensor(0.2452, device='cuda:0'))
     | > step_time: 1.9626  (1.2601077264209968)
     | > loader_time: 1.6203  (1.304109199991766)


   --> TIME: 2025-12-28 22:19:27 -- STEP: 131/150 -- GLOBAL_STEP: 25650
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48244792222976685  (0.47571577211372723)
     | > postnet_loss: 0.390279620885849  (0.39183069208196103)
     | > stopnet_loss: 0.003031311556696892  (0.005143106040608792)
     | > loss: 0.2212131917476654  (0.22202972123641093)
     | > align_error: 0.5906689763069153  (0.6257212564690421)
     | > grad_norm: tensor(0.1179, device='cuda:0')  (tensor(0.2419, device='cuda:0'))
     | > step_time: 2.1102  (1.3961529149353964)
     | > loader_time: 1.7329  (1.420482710117602)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4555094540119171  (0.4555094540119171)
     | > postnet_loss: 0.3336065113544464  (0.3336065113544464)
     | > stopnet_loss: 0.012152060866355896  (0.012152060866355896)
     | > loss: 0.20943105220794678  (0.20943105220794678)
     | > align_error: 0.7183800339698792  (0.7183800339698792)

   --> STEP: 1
     | > decoder_loss: 0.4379248023033142  (0.4379248023033142)
     | > postnet_loss: 0.32240670919418335  (0.32240670919418335)
     | > stopnet_loss: 0.009625593200325966  (0.009625593200325966)
     | > loss: 0.1997084766626358  (0.1997084766626358)
     | > align_error: 0.6586010456085205  (0.6586010456085205)

   --> STEP: 2
     | > decoder_loss: 0.4330143928527832  (0.4354695975780487)
     | > postnet_loss: 0.31193166971206665  (0.317169189453125)
     | > stopnet_loss: 0.01090939436107874  (0.010267493780702353)
     | > loss: 0.19714590907096863  (0.19842719286680222)
     | > align_error: 0.6543624401092529  (0.6564817428588867)

   --> STEP: 3
     | > decoder_loss: 0.43730294704437256  (0.4360807140668233)
     | > postnet_loss: 0.312277227640152  (0.31553853551546734)
     | > stopnet_loss: 0.008040467277169228  (0.009525151612857977)
     | > loss: 0.1954355090856552  (0.1974299649397532)
     | > align_error: 0.7335504591464996  (0.6821713149547577)

   --> STEP: 4
     | > decoder_loss: 0.44059982895851135  (0.43721049278974533)
     | > postnet_loss: 0.31942230463027954  (0.3165094777941704)
     | > stopnet_loss: 0.008133530616760254  (0.009177246363833547)
     | > loss: 0.19813907146453857  (0.19760724157094955)
     | > align_error: 0.6022096872329712  (0.6621809080243111)

   --> STEP: 5
     | > decoder_loss: 0.4238048791885376  (0.43452937006950376)
     | > postnet_loss: 0.3021811544895172  (0.31364381313323975)
     | > stopnet_loss: 0.00800337828695774  (0.008942472748458385)
     | > loss: 0.1894998848438263  (0.1959857702255249)
     | > align_error: 0.640471339225769  (0.6578389942646027)

   --> STEP: 6
     | > decoder_loss: 0.44083282351493835  (0.43557994564374286)
     | > postnet_loss: 0.31434229016304016  (0.3137602259715398)
     | > stopnet_loss: 0.007236415520310402  (0.008658129877100388)
     | > loss: 0.19603019952774048  (0.1959931751092275)
     | > align_error: 0.5926080346107483  (0.6469671676556269)

   --> STEP: 7
     | > decoder_loss: 0.4530273973941803  (0.4380724387509482)
     | > postnet_loss: 0.3145638108253479  (0.31387502380779814)
     | > stopnet_loss: 0.006133353803306818  (0.008297447580844164)
     | > loss: 0.19803115725517273  (0.1962843154157911)
     | > align_error: 0.5779709219932556  (0.637110561132431)

   --> STEP: 8
     | > decoder_loss: 0.4451334476470947  (0.43895506486296654)
     | > postnet_loss: 0.3142480254173279  (0.31392164900898933)
     | > stopnet_loss: 0.007021021563559771  (0.008137894328683615)
     | > loss: 0.19686639308929443  (0.19635707512497902)
     | > align_error: 0.572502851486206  (0.6290345974266529)

   --> STEP: 9
     | > decoder_loss: 0.444320410490036  (0.4395512143770854)
     | > postnet_loss: 0.3145367205142975  (0.3139899902873569)
     | > stopnet_loss: 0.006646109279245138  (0.007972140434301563)
     | > loss: 0.19636039435863495  (0.19635744392871857)
     | > align_error: 0.5898533165454865  (0.62468112177319)

   --> STEP: 10
     | > decoder_loss: 0.469589501619339  (0.4425550431013107)
     | > postnet_loss: 0.32916247844696045  (0.31550723910331724)
     | > stopnet_loss: 0.0055961306206882  (0.007734539452940226)
     | > loss: 0.20528411865234375  (0.1972501114010811)
     | > align_error: 0.5817438364028931  (0.6203873932361603)

   --> STEP: 11
     | > decoder_loss: 0.4553569257259369  (0.4437188506126404)
     | > postnet_loss: 0.31800419092178345  (0.3157342347231778)
     | > stopnet_loss: 0.005899250041693449  (0.0075676949610087)
     | > loss: 0.19923952221870422  (0.1974309669299559)
     | > align_error: 0.5939608812332153  (0.6179849830540743)

   --> STEP: 12
     | > decoder_loss: 0.45124274492263794  (0.4443458418051402)
     | > postnet_loss: 0.3115878403186798  (0.31538870185613627)
     | > stopnet_loss: 0.007789573632180691  (0.007586184850273033)
     | > loss: 0.1984972208738327  (0.197519821425279)
     | > align_error: 0.5865339934825897  (0.6153640672564507)

   --> STEP: 13
     | > decoder_loss: 0.44062530994415283  (0.44405964704660267)
     | > postnet_loss: 0.31118741631507874  (0.31506552604528565)
     | > stopnet_loss: 0.005269953049719334  (0.007408013173307364)
     | > loss: 0.19322313368320465  (0.19718930698358095)
     | > align_error: 0.5840718448162079  (0.6129569732225858)

   --> STEP: 14
     | > decoder_loss: 0.4532405436038971  (0.4447154253721237)
     | > postnet_loss: 0.31528931856155396  (0.3150815112250191)
     | > stopnet_loss: 0.004874733276665211  (0.0072270646092614955)
     | > loss: 0.1970072090625763  (0.19717629998922348)
     | > align_error: 0.553681343793869  (0.6087229996919632)

   --> STEP: 15
     | > decoder_loss: 0.4495282471179962  (0.4450362801551819)
     | > postnet_loss: 0.313398152589798  (0.3149692873160044)
     | > stopnet_loss: 0.004953492898494005  (0.007075493161876997)
     | > loss: 0.19568508863449097  (0.19707688589890798)
     | > align_error: 0.5876878499984741  (0.607320656379064)

   --> STEP: 16
     | > decoder_loss: 0.4509856104850769  (0.4454081133008003)
     | > postnet_loss: 0.3080044090747833  (0.31453398242592806)
     | > stopnet_loss: 0.005236497614532709  (0.006960555940167978)
     | > loss: 0.19498400390148163  (0.19694608077406883)
     | > align_error: 0.6046222448348999  (0.6071520056575537)

   --> STEP: 17
     | > decoder_loss: 0.4582534432411194  (0.44616372094434853)
     | > postnet_loss: 0.3167431056499481  (0.3146639308508704)
     | > stopnet_loss: 0.004753393121063709  (0.006830722833161845)
     | > loss: 0.1985025256872177  (0.19703763635719523)
     | > align_error: 0.5579113960266113  (0.6042554992086747)

   --> STEP: 18
     | > decoder_loss: 0.4512215256690979  (0.44644471009572345)
     | > postnet_loss: 0.3081330955028534  (0.3143011066648695)
     | > stopnet_loss: 0.005170467775315046  (0.006738486441059245)
     | > loss: 0.19500911235809326  (0.19692494057946736)
     | > align_error: 0.6036638617515564  (0.6042226304610571)

   --> STEP: 19
     | > decoder_loss: 0.4466448128223419  (0.4464552418181771)
     | > postnet_loss: 0.3067406117916107  (0.3139031858820664)
     | > stopnet_loss: 0.004670519847422838  (0.00662964609402575)
     | > loss: 0.1930168718099594  (0.19671925274949326)
     | > align_error: 0.598271369934082  (0.6039094062227952)

   --> STEP: 20
     | > decoder_loss: 0.44502073526382446  (0.44638351649045943)
     | > postnet_loss: 0.30361810326576233  (0.31338893175125115)
     | > stopnet_loss: 0.00442888168618083  (0.006519607873633504)
     | > loss: 0.1915885955095291  (0.19646271988749503)
     | > align_error: 0.6224704384803772  (0.6048374578356743)

   --> STEP: 21
     | > decoder_loss: 0.44362565875053406  (0.44625218993141536)
     | > postnet_loss: 0.3041665852069855  (0.3129497723920004)
     | > stopnet_loss: 0.003925594035536051  (0.006396083405152673)
     | > loss: 0.1908736526966095  (0.1961965738307862)
     | > align_error: 0.5591511726379395  (0.602661920445306)

   --> STEP: 22
     | > decoder_loss: 0.4456648826599121  (0.44622549414634705)
     | > postnet_loss: 0.30630776286125183  (0.31264786286787544)
     | > stopnet_loss: 0.0047812266275286674  (0.006322680824351582)
     | > loss: 0.19277440011501312  (0.19604102048006924)
     | > align_error: 0.6249009668827057  (0.6036727861924605)

   --> STEP: 23
     | > decoder_loss: 0.4189958870410919  (0.445041598185249)
     | > postnet_loss: 0.29386186599731445  (0.3118310803952424)
     | > stopnet_loss: 0.004451224580407143  (0.006241313161571388)
     | > loss: 0.1826656609773636  (0.19545948311038638)
     | > align_error: 0.5667551159858704  (0.6020676700965218)

   --> STEP: 24
     | > decoder_loss: 0.4527111053466797  (0.4453611609836419)
     | > postnet_loss: 0.30924513936042786  (0.3117233328521251)
     | > stopnet_loss: 0.004364160820841789  (0.006163098480707656)
     | > loss: 0.19485321640968323  (0.1954342219978571)
     | > align_error: 0.579092413187027  (0.6011103677252929)

   --> STEP: 25
     | > decoder_loss: 0.45202699303627014  (0.44562779426574706)
     | > postnet_loss: 0.30672088265419006  (0.3115232348442077)
     | > stopnet_loss: 0.003657880239188671  (0.006062889751046896)
     | > loss: 0.193344846367836  (0.19535064697265625)
     | > align_error: 0.5574697256088257  (0.5993647420406343)

   --> STEP: 26
     | > decoder_loss: 0.4273883104324341  (0.4449262756567735)
     | > postnet_loss: 0.2957410514354706  (0.3109162277900255)
     | > stopnet_loss: 0.004292887635529041  (0.0059948127466039015)
     | > loss: 0.18507523834705353  (0.1949554389485946)
     | > align_error: 0.5462263822555542  (0.5973209589719773)

   --> STEP: 27
     | > decoder_loss: 0.4235883951187134  (0.44413598378499347)
     | > postnet_loss: 0.2900227904319763  (0.3101423967767644)
     | > stopnet_loss: 0.0035862871445715427  (0.005905608094676777)
     | > loss: 0.18198908865451813  (0.1944752037525177)
     | > align_error: 0.5396181643009186  (0.5951838184286048)

   --> STEP: 28
     | > decoder_loss: 0.42990899085998535  (0.44362787689481464)
     | > postnet_loss: 0.29523974657058716  (0.30961015926940094)
     | > stopnet_loss: 0.0039039934054017067  (0.005834121855774096)
     | > loss: 0.18519118428230286  (0.19414363162858145)
     | > align_error: 0.5660692751407623  (0.5941440133111818)

   --> STEP: 29
     | > decoder_loss: 0.4251033663749695  (0.44298910066999236)
     | > postnet_loss: 0.29205548763275146  (0.3090048257646889)
     | > stopnet_loss: 0.0035210063215345144  (0.005754359251145145)
     | > loss: 0.1828107237815857  (0.19375284170282298)
     | > align_error: 0.5402576327323914  (0.5922858622567408)

   --> STEP: 30
     | > decoder_loss: 0.42575591802597046  (0.44241466124852497)
     | > postnet_loss: 0.29286712408065796  (0.3084669023752212)
     | > stopnet_loss: 0.0027587879449129105  (0.0056545068742707375)
     | > loss: 0.18241454660892487  (0.1933748985330264)
     | > align_error: 0.533030241727829  (0.590310674905777)

   --> STEP: 31
     | > decoder_loss: 0.4204255938529968  (0.44170533649383054)
     | > postnet_loss: 0.29017916321754456  (0.3078769753056187)
     | > stopnet_loss: 0.0036377718206495047  (0.005589450904799085)
     | > loss: 0.1812889724969864  (0.19298502995121863)
     | > align_error: 0.5536743998527527  (0.589128859581486)

   --> STEP: 32
     | > decoder_loss: 0.4337332844734192  (0.4414562098681927)
     | > postnet_loss: 0.2972826361656189  (0.3075459022074937)
     | > stopnet_loss: 0.003774312324821949  (0.005532727824174799)
     | > loss: 0.1865282952785492  (0.19278325699269772)
     | > align_error: 0.5307285487651825  (0.5873038498684765)

   --> STEP: 33
     | > decoder_loss: 0.43073347210884094  (0.4411312784209396)
     | > postnet_loss: 0.294773668050766  (0.307158864808805)
     | > stopnet_loss: 0.0039686099626123905  (0.005485330313218363)
     | > loss: 0.18534539639949799  (0.19255786727775226)
     | > align_error: 0.5458420217037201  (0.5860474308331809)

   --> STEP: 34
     | > decoder_loss: 0.43616679310798645  (0.4409852641470292)
     | > postnet_loss: 0.29615697264671326  (0.3068352797452141)
     | > stopnet_loss: 0.00323407631367445  (0.0054191169602906)
     | > loss: 0.18631501495838165  (0.19237425397424138)
     | > align_error: 0.5634593367576599  (0.5853830751250773)

   --> STEP: 35
     | > decoder_loss: 0.4338425397872925  (0.4407811863081796)
     | > postnet_loss: 0.29569578170776367  (0.3065170083727155)
     | > stopnet_loss: 0.0034753738436847925  (0.005363581442673291)
     | > loss: 0.18585994839668274  (0.1921881309577397)
     | > align_error: 0.5325740575790405  (0.5838742460523334)

   --> STEP: 36
     | > decoder_loss: 0.43956440687179565  (0.44074738687939113)
     | > postnet_loss: 0.2998003661632538  (0.3063304349780082)
     | > stopnet_loss: 0.0035910930018872023  (0.005314345652651455)
     | > loss: 0.18843227624893188  (0.1920838016602728)
     | > align_error: 0.633276104927063  (0.5852465199099648)

   --> STEP: 37
     | > decoder_loss: 0.4320372939109802  (0.440511978961326)
     | > postnet_loss: 0.2963792085647583  (0.30606148291278523)
     | > stopnet_loss: 0.0035122032277286053  (0.005265639100626514)
     | > loss: 0.18561632931232452  (0.19190900511032827)
     | > align_error: 0.5185030400753021  (0.5834426420765955)

   --> STEP: 38
     | > decoder_loss: 0.4192269742488861  (0.43995184725836706)
     | > postnet_loss: 0.28885823488235474  (0.30560876585935287)
     | > stopnet_loss: 0.0030925374012440443  (0.005208452213800659)
     | > loss: 0.18011383712291718  (0.19159860595276482)
     | > align_error: 0.5514459013938904  (0.5826006225849454)

   --> STEP: 39
     | > decoder_loss: 0.4360590875148773  (0.43985203290596986)
     | > postnet_loss: 0.3002749979496002  (0.3054720025796156)
     | > stopnet_loss: 0.0034244852140545845  (0.005162709470217426)
     | > loss: 0.1875080019235611  (0.19149371866996473)
     | > align_error: 0.5455756187438965  (0.581651263512098)

   --> STEP: 40
     | > decoder_loss: 0.43277305364608765  (0.4396750584244728)
     | > postnet_loss: 0.2983725368976593  (0.3052945159375667)
     | > stopnet_loss: 0.0029777013696730137  (0.005108084267703816)
     | > loss: 0.1857641041278839  (0.19135047830641272)
     | > align_error: 0.5833294987678528  (0.5816932193934918)

   --> STEP: 41
     | > decoder_loss: 0.4226221740245819  (0.43925913441471937)
     | > postnet_loss: 0.2903742492198944  (0.3049306069932332)
     | > stopnet_loss: 0.0036891421768814325  (0.005073475924025222)
     | > loss: 0.18193824589252472  (0.19112091166217154)
     | > align_error: 0.5025565326213837  (0.5797630563014892)

   --> STEP: 42
     | > decoder_loss: 0.4290553033351898  (0.43901618605568293)
     | > postnet_loss: 0.29310372471809387  (0.30464901455811083)
     | > stopnet_loss: 0.003240198828279972  (0.00502982646936462)
     | > loss: 0.18377995491027832  (0.19094612697760263)
     | > align_error: 0.5792159736156464  (0.5797500305232548)

   --> STEP: 43
     | > decoder_loss: 0.4271591901779175  (0.4387404419655024)
     | > postnet_loss: 0.29118528962135315  (0.30433590467586064)
     | > stopnet_loss: 0.0028862603940069675  (0.004979976095519093)
     | > loss: 0.1824723780155182  (0.19074906304825184)
     | > align_error: 0.5513789057731628  (0.5790902369244154)

   --> STEP: 44
     | > decoder_loss: 0.4453173577785492  (0.4388899173248898)
     | > postnet_loss: 0.3025912642478943  (0.3042962537570432)
     | > stopnet_loss: 0.002623348729684949  (0.004926416382659226)
     | > loss: 0.18960049748420715  (0.19072295928543265)
     | > align_error: 0.5507901906967163  (0.578447054055604)

   --> STEP: 45
     | > decoder_loss: 0.4383085370063782  (0.4388769977622562)
     | > postnet_loss: 0.3015941083431244  (0.30423620608117835)
     | > stopnet_loss: 0.003252150723710656  (0.0048892104791270355)
     | > loss: 0.1882278025150299  (0.19066751135720147)
     | > align_error: 0.552170991897583  (0.5778631415632036)

   --> STEP: 46
     | > decoder_loss: 0.4280756413936615  (0.43864218566728674)
     | > postnet_loss: 0.2924976348876953  (0.3039810197508852)
     | > stopnet_loss: 0.003154575591906905  (0.004851501025057033)
     | > loss: 0.18329790234565735  (0.19050730246564615)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.4003614729101008 (-0.022795608549406987)
     | > avg_decoder_loss: 0.4349437699173436 (-0.0008613286596355629)
     | > avg_postnet_loss: 0.30089123908317433 (-0.0015565477537388128)
     | > avg_stopnet_loss: 0.004305615544911812 (-1.0386179906852686e-05)
     | > avg_loss: 0.18826436860994858 (-0.000614854648257751)
     | > avg_align_error: 0.5708753344687548 (-0.0001387848998563035)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_25670.pth

 > EPOCH: 170/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 22:22:54)

   --> TIME: 2025-12-28 22:23:02 -- STEP: 5/150 -- GLOBAL_STEP: 25675
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4559091329574585  (0.4542107224464417)
     | > postnet_loss: 0.3861575424671173  (0.38768559098243716)
     | > stopnet_loss: 0.011709711514413357  (0.013549624383449555)
     | > loss: 0.2222263664007187  (0.22402369678020478)
     | > align_error: 0.7246140539646149  (0.7110026597976684)
     | > grad_norm: tensor(0.2860, device='cuda:0')  (tensor(0.2702, device='cuda:0'))
     | > step_time: 0.5426  (0.47068066596984864)
     | > loader_time: 0.7959  (0.7308239459991455)


   --> TIME: 2025-12-28 22:23:44 -- STEP: 30/150 -- GLOBAL_STEP: 25700
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.47316986322402954  (0.46336472034454346)
     | > postnet_loss: 0.39184218645095825  (0.3903894633054733)
     | > stopnet_loss: 0.005781813990324736  (0.008899221926306685)
     | > loss: 0.22203482687473297  (0.22233776648839315)
     | > align_error: 0.6095336079597473  (0.6647469212611516)
     | > grad_norm: tensor(0.3936, device='cuda:0')  (tensor(0.3080, device='cuda:0'))
     | > step_time: 0.8274  (0.710224469502767)
     | > loader_time: 1.2705  (0.889569894472758)


   --> TIME: 2025-12-28 22:24:42 -- STEP: 55/150 -- GLOBAL_STEP: 25725
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.47697240114212036  (0.47005733197385613)
     | > postnet_loss: 0.39103269577026367  (0.39250241897322913)
     | > stopnet_loss: 0.004317274317145348  (0.007143346321853725)
     | > loss: 0.2213185429573059  (0.22278328267010775)
     | > align_error: 0.6479743123054504  (0.6439998296174136)
     | > grad_norm: tensor(0.1548, device='cuda:0')  (tensor(0.2782, device='cuda:0'))
     | > step_time: 1.2886  (0.9208765073256059)
     | > loader_time: 1.2331  (0.9985862471840599)


   --> TIME: 2025-12-28 22:25:53 -- STEP: 80/150 -- GLOBAL_STEP: 25750
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47501140832901  (0.47319507114589215)
     | > postnet_loss: 0.3881252110004425  (0.3926757667213679)
     | > stopnet_loss: 0.004206768237054348  (0.0061618075415026405)
     | > loss: 0.21999092400074005  (0.22262951582670212)
     | > align_error: 0.5864400565624237  (0.6336393162608148)
     | > grad_norm: tensor(0.1501, device='cuda:0')  (tensor(0.2576, device='cuda:0'))
     | > step_time: 1.6251  (1.0925935953855517)
     | > loader_time: 1.6111  (1.11560035943985)


   --> TIME: 2025-12-28 22:27:21 -- STEP: 105/150 -- GLOBAL_STEP: 25775
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4800683259963989  (0.4745922392322904)
     | > postnet_loss: 0.3909240663051605  (0.3922225106330145)
     | > stopnet_loss: 0.0035509238950908184  (0.005548053487603154)
     | > loss: 0.22129902243614197  (0.22225173995608374)
     | > align_error: 0.6093242764472961  (0.6294490203970956)
     | > grad_norm: tensor(0.1391, device='cuda:0')  (tensor(0.2408, device='cuda:0'))
     | > step_time: 1.9937  (1.2577877657754084)
     | > loader_time: 1.8167  (1.266263925461542)


   --> TIME: 2025-12-28 22:28:55 -- STEP: 130/150 -- GLOBAL_STEP: 25800
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.480099618434906  (0.4755376515480188)
     | > postnet_loss: 0.38966360688209534  (0.39171192668951477)
     | > stopnet_loss: 0.0030009488109499216  (0.005107159407522816)
     | > loss: 0.2204417586326599  (0.22191955286722917)
     | > align_error: 0.5966363549232483  (0.6259823510280024)
     | > grad_norm: tensor(0.2233, device='cuda:0')  (tensor(0.2275, device='cuda:0'))
     | > step_time: 2.0279  (1.4014796477097733)
     | > loader_time: 1.8773  (1.3597245491467989)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45688366889953613  (0.45688366889953613)
     | > postnet_loss: 0.3343288004398346  (0.3343288004398346)
     | > stopnet_loss: 0.012074063532054424  (0.012074063532054424)
     | > loss: 0.20987717807292938  (0.20987717807292938)
     | > align_error: 0.7186425030231476  (0.7186425030231476)

   --> STEP: 1
     | > decoder_loss: 0.4383513927459717  (0.4383513927459717)
     | > postnet_loss: 0.32247450947761536  (0.32247450947761536)
     | > stopnet_loss: 0.009601430036127567  (0.009601430036127567)
     | > loss: 0.19980789721012115  (0.19980789721012115)
     | > align_error: 0.6590205132961273  (0.6590205132961273)

   --> STEP: 2
     | > decoder_loss: 0.4342574179172516  (0.43630440533161163)
     | > postnet_loss: 0.3123914301395416  (0.3174329698085785)
     | > stopnet_loss: 0.010830942541360855  (0.010216186288744211)
     | > loss: 0.19749315083026886  (0.198650524020195)
     | > align_error: 0.6547702848911285  (0.6568953990936279)

   --> STEP: 3
     | > decoder_loss: 0.4383125305175781  (0.43697378039360046)
     | > postnet_loss: 0.31286948919296265  (0.31591180960337323)
     | > stopnet_loss: 0.008129922673106194  (0.009520765083531538)
     | > loss: 0.19592542946338654  (0.1977421591679255)
     | > align_error: 0.7340860068798065  (0.6826256016890208)

   --> STEP: 4
     | > decoder_loss: 0.4421173930168152  (0.43825968354940414)
     | > postnet_loss: 0.3197568655014038  (0.31687307357788086)
     | > stopnet_loss: 0.008105677552521229  (0.009166993200778961)
     | > loss: 0.1985742449760437  (0.19795018061995506)
     | > align_error: 0.6028124094009399  (0.6626723036170006)

   --> STEP: 5
     | > decoder_loss: 0.42409199476242065  (0.43542614579200745)
     | > postnet_loss: 0.30206096172332764  (0.3139106512069702)
     | > stopnet_loss: 0.008022911846637726  (0.008938176929950714)
     | > loss: 0.1895611584186554  (0.19627237617969512)
     | > align_error: 0.6410203874111176  (0.658341920375824)

   --> STEP: 6
     | > decoder_loss: 0.4426408112049103  (0.43662859002749127)
     | > postnet_loss: 0.31478044390678406  (0.3140556166569392)
     | > stopnet_loss: 0.0072482856921851635  (0.008656528390323123)
     | > loss: 0.19660359621047974  (0.19632757951815924)
     | > align_error: 0.5931921005249023  (0.647483617067337)

   --> STEP: 7
     | > decoder_loss: 0.45248472690582275  (0.43889375243868145)
     | > postnet_loss: 0.31381943821907043  (0.3140218768801008)
     | > stopnet_loss: 0.006108791567385197  (0.008292565987046276)
     | > loss: 0.19768482446670532  (0.19652147165366582)
     | > align_error: 0.578145444393158  (0.6375781638281686)

   --> STEP: 8
     | > decoder_loss: 0.4485449492931366  (0.44010015204548836)
     | > postnet_loss: 0.31572017073631287  (0.3142341636121273)
     | > stopnet_loss: 0.00694649014621973  (0.008124306506942958)
     | > loss: 0.19801276922225952  (0.19670788384974003)
     | > align_error: 0.5731388926506042  (0.629523254930973)

   --> STEP: 9
     | > decoder_loss: 0.44457244873046875  (0.4405970738993751)
     | > postnet_loss: 0.3137504458427429  (0.3141804171933068)
     | > stopnet_loss: 0.0066943541169166565  (0.007965422908051146)
     | > loss: 0.19627508521080017  (0.19665979511208004)
     | > align_error: 0.5903353095054626  (0.625169038772583)

   --> STEP: 10
     | > decoder_loss: 0.4707046449184418  (0.44360783100128176)
     | > postnet_loss: 0.32896068692207336  (0.3156584441661835)
     | > stopnet_loss: 0.005565263330936432  (0.007725406950339675)
     | > loss: 0.20548158884048462  (0.1975419744849205)
     | > align_error: 0.5824483931064606  (0.6208969742059708)

   --> STEP: 11
     | > decoder_loss: 0.45576122403144836  (0.44471268491311505)
     | > postnet_loss: 0.31749823689460754  (0.31582569805058563)
     | > stopnet_loss: 0.005892585497349501  (0.0075587868182496595)
     | > loss: 0.19920745491981506  (0.19769338179718365)
     | > align_error: 0.594112753868103  (0.6184620450843464)

   --> STEP: 12
     | > decoder_loss: 0.4523369371891022  (0.4453480392694473)
     | > postnet_loss: 0.3113905191421509  (0.31545609980821604)
     | > stopnet_loss: 0.007852193899452686  (0.007583237408349912)
     | > loss: 0.19878405332565308  (0.19778427109122276)
     | > align_error: 0.5869418680667877  (0.6158353636662165)

   --> STEP: 13
     | > decoder_loss: 0.4420302212238312  (0.4450928224967076)
     | > postnet_loss: 0.31108129024505615  (0.31511957599566526)
     | > stopnet_loss: 0.005258707329630852  (0.007404427402294599)
     | > loss: 0.19353657960891724  (0.19745752559258387)
     | > align_error: 0.5840355157852173  (0.6133892215215243)

   --> STEP: 14
     | > decoder_loss: 0.45742174983024597  (0.44597346016338896)
     | > postnet_loss: 0.3174630105495453  (0.31528696417808527)
     | > stopnet_loss: 0.004839904140681028  (0.007221247169322201)
     | > loss: 0.19856108725070953  (0.19753635142530715)
     | > align_error: 0.5545467734336853  (0.60918618951525)

   --> STEP: 15
     | > decoder_loss: 0.45044204592704773  (0.44627136588096616)
     | > postnet_loss: 0.3131444752216339  (0.31514413158098853)
     | > stopnet_loss: 0.0049706497229635715  (0.007071207339564959)
     | > loss: 0.19586728513240814  (0.19742508033911388)
     | > align_error: 0.5879436731338501  (0.6077700217564901)

   --> STEP: 16
     | > decoder_loss: 0.4519343078136444  (0.4466252997517586)
     | > postnet_loss: 0.3079226315021515  (0.3146927878260612)
     | > stopnet_loss: 0.005213801749050617  (0.006955119490157813)
     | > loss: 0.19517803192138672  (0.19728463981300592)
     | > align_error: 0.6047996878623962  (0.6075843758881092)

   --> STEP: 17
     | > decoder_loss: 0.4581168591976166  (0.44730127383680907)
     | > postnet_loss: 0.3158302307128906  (0.3147596962311688)
     | > stopnet_loss: 0.004736182279884815  (0.00682459377190646)
     | > loss: 0.19822296500205994  (0.19733983541236205)
     | > align_error: 0.5579532980918884  (0.6046649007236257)

   --> STEP: 18
     | > decoder_loss: 0.451490193605423  (0.447533991601732)
     | > postnet_loss: 0.3076314330101013  (0.31436368160777617)
     | > stopnet_loss: 0.005179242230951786  (0.0067331853529645335)
     | > loss: 0.19495965540409088  (0.1972076031896803)
     | > align_error: 0.6034792065620422  (0.6045990288257599)

   --> STEP: 19
     | > decoder_loss: 0.4474238157272339  (0.4475281928714953)
     | > postnet_loss: 0.30657169222831726  (0.3139535769035941)
     | > stopnet_loss: 0.00465392554178834  (0.006623750626060523)
     | > loss: 0.19315281510353088  (0.1969941932904093)
     | > align_error: 0.5987175107002258  (0.6042894752402055)

   --> STEP: 20
     | > decoder_loss: 0.4457283914089203  (0.44743820279836655)
     | > postnet_loss: 0.30358627438545227  (0.313435211777687)
     | > stopnet_loss: 0.00441224267706275  (0.006513175228610635)
     | > loss: 0.19174091517925262  (0.19673152938485144)
     | > align_error: 0.6225017309188843  (0.6052000880241394)

   --> STEP: 21
     | > decoder_loss: 0.4439762830734253  (0.44727334947813124)
     | > postnet_loss: 0.30366942286491394  (0.3129701742104121)
     | > stopnet_loss: 0.0039037715177983046  (0.006388917909048143)
     | > loss: 0.19081521034240723  (0.19644979990663983)
     | > align_error: 0.5589737296104431  (0.6029988328615824)

   --> STEP: 22
     | > decoder_loss: 0.4454292356967926  (0.447189526124434)
     | > postnet_loss: 0.30555444955825806  (0.3126330958171324)
     | > stopnet_loss: 0.004869459196925163  (0.0063198516039516435)
     | > loss: 0.19261538982391357  (0.19627550853924317)
     | > align_error: 0.6247825026512146  (0.603988999670202)

   --> STEP: 23
     | > decoder_loss: 0.41900867223739624  (0.4459642716076063)
     | > postnet_loss: 0.29346102476119995  (0.3117995275103527)
     | > stopnet_loss: 0.004442211240530014  (0.006238215066411573)
     | > loss: 0.18255963921546936  (0.19567916639473126)
     | > align_error: 0.5664202570915222  (0.6023555760798246)

   --> STEP: 24
     | > decoder_loss: 0.45336684584617615  (0.44627271220088005)
     | > postnet_loss: 0.30927789211273193  (0.3116944593687852)
     | > stopnet_loss: 0.0043843574821949005  (0.006160971000402545)
     | > loss: 0.19504554569721222  (0.19565276553233465)
     | > align_error: 0.5789200961589813  (0.6013790977497895)

   --> STEP: 25
     | > decoder_loss: 0.45239898562431335  (0.4465177631378174)
     | > postnet_loss: 0.3065508306026459  (0.3114887142181397)
     | > stopnet_loss: 0.0036556886043399572  (0.006060759704560041)
     | > loss: 0.19339314103126526  (0.19556238055229186)
     | > align_error: 0.5572373270988464  (0.5996134269237517)

   --> STEP: 26
     | > decoder_loss: 0.4275864064693451  (0.44578963403518385)
     | > postnet_loss: 0.2952324450016022  (0.3108634730944267)
     | > stopnet_loss: 0.00427321158349514  (0.005992007853749853)
     | > loss: 0.1849779188632965  (0.1951552858719459)
     | > align_error: 0.5461185574531555  (0.5975559319441135)

   --> STEP: 27
     | > decoder_loss: 0.42482268810272217  (0.4450130804821297)
     | > postnet_loss: 0.290213018655777  (0.31009864144855076)
     | > stopnet_loss: 0.0038528884761035442  (0.005912781210133323)
     | > loss: 0.18261180818080902  (0.19469071262412602)
     | > align_error: 0.540142148733139  (0.5954294955288922)

   --> STEP: 28
     | > decoder_loss: 0.4302336275577545  (0.4444852428776877)
     | > postnet_loss: 0.2950398921966553  (0.30956082897526876)
     | > stopnet_loss: 0.003908192273229361  (0.005841188748101038)
     | > loss: 0.18522655963897705  (0.1943527071603707)
     | > align_error: 0.565674901008606  (0.594366831438882)

   --> STEP: 29
     | > decoder_loss: 0.42561447620391846  (0.4438345267854888)
     | > postnet_loss: 0.2918948829174042  (0.3089516584215493)
     | > stopnet_loss: 0.0035105054266750813  (0.00576082035770704)
     | > loss: 0.18288785219192505  (0.19395736733387256)
     | > align_error: 0.5399265885353088  (0.5924895816835863)

   --> STEP: 30
     | > decoder_loss: 0.42694929242134094  (0.4432716856400172)
     | > postnet_loss: 0.293011337518692  (0.30842031439145406)
     | > stopnet_loss: 0.002755167428404093  (0.005660631926730275)
     | > loss: 0.1827453225851059  (0.19358363250891367)
     | > align_error: 0.5328699946403503  (0.5905022621154785)

   --> STEP: 31
     | > decoder_loss: 0.4199250638484955  (0.44251856880803264)
     | > postnet_loss: 0.2894730865955353  (0.3078091134948115)
     | > stopnet_loss: 0.003660478862002492  (0.005596110860126153)
     | > loss: 0.18101002275943756  (0.19317803219441446)
     | > align_error: 0.5533325374126434  (0.5893032387379677)

   --> STEP: 32
     | > decoder_loss: 0.43442580103874207  (0.4422656698152423)
     | > postnet_loss: 0.29721662402153015  (0.3074780981987715)
     | > stopnet_loss: 0.003772175405174494  (0.005539112877158914)
     | > loss: 0.1866827756166458  (0.19297505542635918)
     | > align_error: 0.5299280285835266  (0.5874477634206414)

   --> STEP: 33
     | > decoder_loss: 0.43032410740852356  (0.441903804287766)
     | > postnet_loss: 0.29418882727622986  (0.30707539301930054)
     | > stopnet_loss: 0.003959641791880131  (0.005491250116998951)
     | > loss: 0.1850878745317459  (0.19273604994470422)
     | > align_error: 0.5451532006263733  (0.5861661100026333)

   --> STEP: 34
     | > decoder_loss: 0.43609166145324707  (0.44173285891028014)
     | > postnet_loss: 0.2957797646522522  (0.3067431686555638)
     | > stopnet_loss: 0.003216925309970975  (0.005424358210909893)
     | > loss: 0.18618477880954742  (0.19254336549955256)
     | > align_error: 0.5628373622894287  (0.5854799703640097)

   --> STEP: 35
     | > decoder_loss: 0.4335756301879883  (0.4414997952325003)
     | > postnet_loss: 0.29511281847953796  (0.3064108729362488)
     | > stopnet_loss: 0.0034765738528221846  (0.005368707229250244)
     | > loss: 0.18564869463443756  (0.19234637490340642)
     | > align_error: 0.5320166647434235  (0.5839524473462786)

   --> STEP: 36
     | > decoder_loss: 0.4394846558570862  (0.44144381913873887)
     | > postnet_loss: 0.2992830276489258  (0.3062128772338231)
     | > stopnet_loss: 0.0035994292702525854  (0.005319560619278086)
     | > loss: 0.18829135596752167  (0.19223373548852074)
     | > align_error: 0.632863849401474  (0.5853110974033674)

   --> STEP: 37
     | > decoder_loss: 0.4322432279586792  (0.4411951545122507)
     | > postnet_loss: 0.2960071265697479  (0.30593704613479406)
     | > stopnet_loss: 0.003529851557686925  (0.005271190104099947)
     | > loss: 0.1855924427509308  (0.1920542410902075)
     | > align_error: 0.5177372097969055  (0.5834847761167062)

   --> STEP: 38
     | > decoder_loss: 0.4193110167980194  (0.44061925615134995)
     | > postnet_loss: 0.2883504033088684  (0.3054742397446381)
     | > stopnet_loss: 0.003072999184951186  (0.005213342974648664)
     | > loss: 0.1799883395433426  (0.19173671736529)
     | > align_error: 0.5507507920265198  (0.5826233554827539)

   --> STEP: 39
     | > decoder_loss: 0.4360625147819519  (0.44050241662905765)
     | > postnet_loss: 0.29978081583976746  (0.3053282545163081)
     | > stopnet_loss: 0.0034166413825005293  (0.005167273703055122)
     | > loss: 0.187377467751503  (0.19162494173416725)
     | > align_error: 0.5451022386550903  (0.5816612755640959)

   --> STEP: 40
     | > decoder_loss: 0.43276411294937134  (0.4403089590370655)
     | > postnet_loss: 0.29779329895973206  (0.30513988062739367)
     | > stopnet_loss: 0.002974804025143385  (0.005112461961107329)
     | > loss: 0.18561416864395142  (0.19147467240691185)
     | > align_error: 0.5827785730361938  (0.5816892080008983)

   --> STEP: 41
     | > decoder_loss: 0.42398107051849365  (0.4399107178536857)
     | > postnet_loss: 0.29072871804237366  (0.30478838885702736)
     | > stopnet_loss: 0.0037021436728537083  (0.005078063954076752)
     | > loss: 0.1823795884847641  (0.1912528410917375)
     | > align_error: 0.5018571019172668  (0.5797420834622731)

   --> STEP: 42
     | > decoder_loss: 0.4289865493774414  (0.4396506186042513)
     | > postnet_loss: 0.29258453845977783  (0.3044978209904262)
     | > stopnet_loss: 0.0032377587631344795  (0.005034247163816222)
     | > loss: 0.18363052606582642  (0.1910713574006444)
     | > align_error: 0.5784537196159363  (0.5797114081325984)

   --> STEP: 43
     | > decoder_loss: 0.4275735318660736  (0.4393697561219681)
     | > postnet_loss: 0.2908858358860016  (0.30418126319730004)
     | > stopnet_loss: 0.00289513124153018  (0.0049845002819025935)
     | > loss: 0.18250997364521027  (0.1908722554528436)
     | > align_error: 0.550707995891571  (0.5790369101735047)

   --> STEP: 44
     | > decoder_loss: 0.4457702934741974  (0.4395152228799733)
     | > postnet_loss: 0.3025065064430237  (0.3041432005437938)
     | > stopnet_loss: 0.002619758015498519  (0.004930756139484319)
     | > loss: 0.18968896567821503  (0.1908453625034202)
     | > align_error: 0.5500624179840088  (0.5783783989873797)

   --> STEP: 45
     | > decoder_loss: 0.43858110904693604  (0.4394944647947947)
     | > postnet_loss: 0.30126166343688965  (0.3040791663858626)
     | > stopnet_loss: 0.0032493597827851772  (0.004893391776002115)
     | > loss: 0.18821005523204803  (0.19078680011961197)
     | > align_error: 0.5514392256736755  (0.5777797506915197)

   --> STEP: 46
     | > decoder_loss: 0.42831236124038696  (0.4392513755870902)
     | > postnet_loss: 0.2921660244464874  (0.30382018503935443)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.34715733744881366 (-0.05320413546128716)
     | > avg_decoder_loss: 0.435516407995513 (+0.0005726380781693741)
     | > avg_postnet_loss: 0.3006690383860559 (-0.00022220069711842427)
     | > avg_stopnet_loss: 0.004308507985886977 (+2.892440975164369e-06)
     | > avg_loss: 0.18835486990935874 (+9.050129941015617e-05)
     | > avg_align_error: 0.5705896801117694 (-0.00028565435698546526)


 > EPOCH: 171/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 22:32:19)

   --> TIME: 2025-12-28 22:32:24 -- STEP: 4/150 -- GLOBAL_STEP: 25825
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45586615800857544  (0.454780638217926)
     | > postnet_loss: 0.3889857828617096  (0.38944483548402786)
     | > stopnet_loss: 0.013263631612062454  (0.014303954783827066)
     | > loss: 0.224476620554924  (0.22536032646894455)
     | > align_error: 0.687728762626648  (0.7074994072318077)
     | > grad_norm: tensor(0.3719, device='cuda:0')  (tensor(0.3069, device='cuda:0'))
     | > step_time: 0.5236  (0.4408046007156372)
     | > loader_time: 0.5269  (0.5659374594688416)


   --> TIME: 2025-12-28 22:33:05 -- STEP: 29/150 -- GLOBAL_STEP: 25850
     | > current_lr: 1e-05  (1.0000000000000006e-05)
     | > decoder_loss: 0.4766528308391571  (0.46431888691310225)
     | > postnet_loss: 0.3970671594142914  (0.3911736771978181)
     | > stopnet_loss: 0.006779901683330536  (0.00920175703178192)
     | > loss: 0.22520989179611206  (0.22307489915140744)
     | > align_error: 0.6731179356575012  (0.6662680116193048)
     | > grad_norm: tensor(0.3528, device='cuda:0')  (tensor(0.3097, device='cuda:0'))
     | > step_time: 0.9784  (0.7118112794284163)
     | > loader_time: 1.0218  (0.8490280858401594)


   --> TIME: 2025-12-28 22:34:03 -- STEP: 54/150 -- GLOBAL_STEP: 25875
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4779279828071594  (0.47056348621845245)
     | > postnet_loss: 0.3915315270423889  (0.39298579979825904)
     | > stopnet_loss: 0.005211327224969864  (0.007284582954727942)
     | > loss: 0.22257620096206665  (0.2231719046831131)
     | > align_error: 0.5751147270202637  (0.6434683065723492)
     | > grad_norm: tensor(0.2361, device='cuda:0')  (tensor(0.2809, device='cuda:0'))
     | > step_time: 1.2853  (0.9213100362707067)
     | > loader_time: 1.2226  (0.9859180008923566)


   --> TIME: 2025-12-28 22:35:12 -- STEP: 79/150 -- GLOBAL_STEP: 25900
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4793413281440735  (0.4733911413180677)
     | > postnet_loss: 0.3914456367492676  (0.3928829767281496)
     | > stopnet_loss: 0.004323779139667749  (0.006257767780224167)
     | > loss: 0.22202052175998688  (0.22282629677011997)
     | > align_error: 0.5921832919120789  (0.6332502436788778)
     | > grad_norm: tensor(0.2284, device='cuda:0')  (tensor(0.2593, device='cuda:0'))
     | > step_time: 1.5056  (1.0906343128107765)
     | > loader_time: 1.5142  (1.0895135704475112)


   --> TIME: 2025-12-28 22:36:35 -- STEP: 104/150 -- GLOBAL_STEP: 25925
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48402348160743713  (0.47457171317476493)
     | > postnet_loss: 0.39470231533050537  (0.3922485342392555)
     | > stopnet_loss: 0.003029988147318363  (0.005613004499956822)
     | > loss: 0.22271142899990082  (0.22231806628406048)
     | > align_error: 0.6154885292053223  (0.6288585949402589)
     | > grad_norm: tensor(0.1343, device='cuda:0')  (tensor(0.2396, device='cuda:0'))
     | > step_time: 1.8973  (1.2460646170836223)
     | > loader_time: 1.7046  (1.2020489481779246)


   --> TIME: 2025-12-28 22:38:09 -- STEP: 129/150 -- GLOBAL_STEP: 25950
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.47880521416664124  (0.47554536360178806)
     | > postnet_loss: 0.38816335797309875  (0.39176378416460617)
     | > stopnet_loss: 0.003089099656790495  (0.005153798691336383)
     | > loss: 0.21983124315738678  (0.22198108566361804)
     | > align_error: 0.660694807767868  (0.6258742395759553)
     | > grad_norm: tensor(0.1425, device='cuda:0')  (tensor(0.2333, device='cuda:0'))
     | > step_time: 2.1092  (1.387570135353147)
     | > loader_time: 2.1021  (1.3141881199770198)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4568018615245819  (0.4568018615245819)
     | > postnet_loss: 0.33197757601737976  (0.33197757601737976)
     | > stopnet_loss: 0.012100285850465298  (0.012100285850465298)
     | > loss: 0.2092951387166977  (0.2092951387166977)
     | > align_error: 0.7186580896377563  (0.7186580896377563)

   --> STEP: 1
     | > decoder_loss: 0.4372006952762604  (0.4372006952762604)
     | > postnet_loss: 0.3187578022480011  (0.3187578022480011)
     | > stopnet_loss: 0.009582428261637688  (0.009582428261637688)
     | > loss: 0.1985720545053482  (0.1985720545053482)
     | > align_error: 0.6590317487716675  (0.6590317487716675)

   --> STEP: 2
     | > decoder_loss: 0.4344649314880371  (0.43583281338214874)
     | > postnet_loss: 0.31123626232147217  (0.31499703228473663)
     | > stopnet_loss: 0.01092139258980751  (0.010251910425722599)
     | > loss: 0.19734668731689453  (0.19795937091112137)
     | > align_error: 0.6547438502311707  (0.6568877995014191)

   --> STEP: 3
     | > decoder_loss: 0.4410504996776581  (0.43757204214731854)
     | > postnet_loss: 0.31202611327171326  (0.3140067259470622)
     | > stopnet_loss: 0.00805977825075388  (0.009521199700733026)
     | > loss: 0.19632893800735474  (0.1974158932765325)
     | > align_error: 0.7347223460674286  (0.6828326483567556)

   --> STEP: 4
     | > decoder_loss: 0.4414423108100891  (0.43853960931301117)
     | > postnet_loss: 0.3171038329601288  (0.3147810027003288)
     | > stopnet_loss: 0.008149053901433945  (0.009178163250908256)
     | > loss: 0.19778558611869812  (0.1975083164870739)
     | > align_error: 0.6027300953865051  (0.662807010114193)

   --> STEP: 5
     | > decoder_loss: 0.4251801669597626  (0.4358677208423615)
     | > postnet_loss: 0.301173597574234  (0.31205952167510986)
     | > stopnet_loss: 0.008029756136238575  (0.008948481827974319)
     | > loss: 0.18961820006370544  (0.1959302932024002)
     | > align_error: 0.6410470902919769  (0.6584550261497497)

   --> STEP: 6
     | > decoder_loss: 0.4425073564052582  (0.4369743267695109)
     | > postnet_loss: 0.3126858174800873  (0.31216390430927277)
     | > stopnet_loss: 0.007274777162820101  (0.008669531050448617)
     | > loss: 0.19607307016849518  (0.19595408936341605)
     | > align_error: 0.5934144854545593  (0.6476149360338846)

   --> STEP: 7
     | > decoder_loss: 0.4545165002346039  (0.43948035155023846)
     | > postnet_loss: 0.31368809938430786  (0.3123816464628492)
     | > stopnet_loss: 0.00613938644528389  (0.00830808182113937)
     | > loss: 0.19819052517414093  (0.1962735801935196)
     | > align_error: 0.5781295001506805  (0.6376884451934269)

   --> STEP: 8
     | > decoder_loss: 0.44512900710105896  (0.44018643349409103)
     | > postnet_loss: 0.3116387128829956  (0.3122887797653675)
     | > stopnet_loss: 0.00696236826479435  (0.008139867626596242)
     | > loss: 0.19615431129932404  (0.19625867158174515)
     | > align_error: 0.5735766887664795  (0.6296744756400585)

   --> STEP: 9
     | > decoder_loss: 0.4443121552467346  (0.44064484702216256)
     | > postnet_loss: 0.31238871812820435  (0.31229988402790493)
     | > stopnet_loss: 0.0065840501338243484  (0.007966999016288254)
     | > loss: 0.19575926661491394  (0.19620318214098612)
     | > align_error: 0.5902648270130157  (0.6252956257926093)

   --> STEP: 10
     | > decoder_loss: 0.47035840153694153  (0.4436162024736404)
     | > postnet_loss: 0.326966792345047  (0.3137665748596191)
     | > stopnet_loss: 0.005580614786595106  (0.007728360593318939)
     | > loss: 0.20491191744804382  (0.1970740556716919)
     | > align_error: 0.5830063819885254  (0.6210667014122009)

   --> STEP: 11
     | > decoder_loss: 0.4562109708786011  (0.44476118141954596)
     | > postnet_loss: 0.31663981080055237  (0.3140277781269767)
     | > stopnet_loss: 0.005919701885432005  (0.007563937074420127)
     | > loss: 0.19913238286972046  (0.19726117632605814)
     | > align_error: 0.5943335890769958  (0.6186364184726368)

   --> STEP: 12
     | > decoder_loss: 0.4540189206600189  (0.4455326596895854)
     | > postnet_loss: 0.311204195022583  (0.3137924795349439)
     | > stopnet_loss: 0.007812801748514175  (0.007584675797261298)
     | > loss: 0.19911858439445496  (0.19741596033175787)
     | > align_error: 0.5867772102355957  (0.6159814844528834)

   --> STEP: 13
     | > decoder_loss: 0.4419209957122803  (0.4452548393836388)
     | > postnet_loss: 0.3099138140678406  (0.31349412065285903)
     | > stopnet_loss: 0.005254213698208332  (0.0074054094819495314)
     | > loss: 0.19321291148662567  (0.19709264888213232)
     | > align_error: 0.5840432941913605  (0.6135247005866125)

   --> STEP: 14
     | > decoder_loss: 0.45455873012542725  (0.4459194030080523)
     | > postnet_loss: 0.31444549560546875  (0.31356207600661684)
     | > stopnet_loss: 0.004862556234002113  (0.007223777107096144)
     | > loss: 0.19711361825466156  (0.19709414669445582)
     | > align_error: 0.5543921887874603  (0.6093009497438159)

   --> STEP: 15
     | > decoder_loss: 0.4522390365600586  (0.44634071191151936)
     | > postnet_loss: 0.3136850595474243  (0.31357027490933737)
     | > stopnet_loss: 0.00496712839230895  (0.007073333859443665)
     | > loss: 0.19644814729690552  (0.19705108006795247)
     | > align_error: 0.5881953835487366  (0.6078939119974772)

   --> STEP: 16
     | > decoder_loss: 0.4534834027290344  (0.44678713008761406)
     | > postnet_loss: 0.3084903359413147  (0.31325277872383595)
     | > stopnet_loss: 0.005239088553935289  (0.006958693527849391)
     | > loss: 0.19573251903057098  (0.19696867000311613)
     | > align_error: 0.6049355566501617  (0.60770901478827)

   --> STEP: 17
     | > decoder_loss: 0.4574130177497864  (0.447412182303036)
     | > postnet_loss: 0.31504735350608826  (0.3133583419463214)
     | > stopnet_loss: 0.004743930883705616  (0.006828413372311522)
     | > loss: 0.1978590190410614  (0.19702104347593644)
     | > align_error: 0.557939738035202  (0.6047814102733836)

   --> STEP: 18
     | > decoder_loss: 0.4526601731777191  (0.4477037373516295)
     | > postnet_loss: 0.3079318702220917  (0.3130568712949753)
     | > stopnet_loss: 0.005166602320969105  (0.006736090536125832)
     | > loss: 0.19531461596488953  (0.19692624194754493)
     | > align_error: 0.6035606861114502  (0.6047135922643874)

   --> STEP: 19
     | > decoder_loss: 0.4502812623977661  (0.44783939656458405)
     | > postnet_loss: 0.30750253796577454  (0.31276453796185943)
     | > stopnet_loss: 0.0047148969024419785  (0.006629711923826682)
     | > loss: 0.1941608339548111  (0.1967806941584537)
     | > align_error: 0.5995531678199768  (0.6044419909778395)

   --> STEP: 20
     | > decoder_loss: 0.44690123200416565  (0.4477924883365631)
     | > postnet_loss: 0.30430713295936584  (0.31234166771173477)
     | > stopnet_loss: 0.004435333888977766  (0.006519993022084236)
     | > loss: 0.19223742187023163  (0.1965535305440426)
     | > align_error: 0.62241992354393  (0.6053408876061439)

   --> STEP: 21
     | > decoder_loss: 0.4444049596786499  (0.44763117744809106)
     | > postnet_loss: 0.3031918704509735  (0.31190596308026997)
     | > stopnet_loss: 0.0039067924953997135  (0.006395554901765925)
     | > loss: 0.19080600142478943  (0.196279838681221)
     | > align_error: 0.5591748952865601  (0.6031425070194971)

   --> STEP: 22
     | > decoder_loss: 0.4458727240562439  (0.4475512477484616)
     | > postnet_loss: 0.30556994676589966  (0.31161796233870764)
     | > stopnet_loss: 0.004531605634838343  (0.0063108299350873994)
     | > loss: 0.1923922747373581  (0.19610313122922723)
     | > align_error: 0.6247289776802063  (0.6041237102313475)

   --> STEP: 23
     | > decoder_loss: 0.419818639755249  (0.44634548218353937)
     | > postnet_loss: 0.2934175431728363  (0.3108266397662785)
     | > stopnet_loss: 0.004460729658603668  (0.006230390792631585)
     | > loss: 0.182769775390625  (0.19552342010580975)
     | > align_error: 0.5665836334228516  (0.6024915329788042)

   --> STEP: 24
     | > decoder_loss: 0.45472726225852966  (0.4466947230199973)
     | > postnet_loss: 0.3101229667663574  (0.31079732005794847)
     | > stopnet_loss: 0.004389404319226742  (0.006153683022906383)
     | > loss: 0.19560196995735168  (0.19552669301629066)
     | > align_error: 0.5789017975330353  (0.6015086273352305)

   --> STEP: 25
     | > decoder_loss: 0.45368966460227966  (0.4469745206832886)
     | > postnet_loss: 0.30695199966430664  (0.3106435072422028)
     | > stopnet_loss: 0.0036602343898266554  (0.006053945077583194)
     | > loss: 0.19382065534591675  (0.19545845150947572)
     | > align_error: 0.5576784610748291  (0.5997554206848145)

   --> STEP: 26
     | > decoder_loss: 0.4279119372367859  (0.4462413443968846)
     | > postnet_loss: 0.2949647903442383  (0.3100404796692041)
     | > stopnet_loss: 0.004276860039681196  (0.005985595653048501)
     | > loss: 0.18499603867530823  (0.19505605101585388)
     | > align_error: 0.5461621880531311  (0.5976941425066727)

   --> STEP: 27
     | > decoder_loss: 0.4257062077522278  (0.44548078378041583)
     | > postnet_loss: 0.2906396687030792  (0.3093219311149032)
     | > stopnet_loss: 0.0038669458590447903  (0.005907127142159475)
     | > loss: 0.18295341730117798  (0.19460780532271774)
     | > align_error: 0.5402560532093048  (0.5955668058660295)

   --> STEP: 28
     | > decoder_loss: 0.4311832785606384  (0.44497015859399525)
     | > postnet_loss: 0.29521486163139343  (0.30881810720477787)
     | > stopnet_loss: 0.003912689629942179  (0.0058358972310088575)
     | > loss: 0.1855122148990631  (0.19428296280758722)
     | > align_error: 0.5659899115562439  (0.5945104882121086)

   --> STEP: 29
     | > decoder_loss: 0.4269051253795624  (0.4443472264141872)
     | > postnet_loss: 0.29201433062553406  (0.3082386666330798)
     | > stopnet_loss: 0.003527495078742504  (0.005756297156792776)
     | > loss: 0.1832573562860489  (0.1939027694792583)
     | > align_error: 0.5400263667106628  (0.5926317254017139)

   --> STEP: 30
     | > decoder_loss: 0.4267496168613434  (0.4437606394290924)
     | > postnet_loss: 0.2924026846885681  (0.3077108005682627)
     | > stopnet_loss: 0.0027509781066328287  (0.005656119855120778)
     | > loss: 0.18253906071186066  (0.19352397918701172)
     | > align_error: 0.5329277813434601  (0.5906415939331054)

   --> STEP: 31
     | > decoder_loss: 0.4224609434604645  (0.44307355246236246)
     | > postnet_loss: 0.2906656861305237  (0.30716095816704536)
     | > stopnet_loss: 0.0036518960259854794  (0.005591467473535768)
     | > loss: 0.18193356692790985  (0.19315009492058907)
     | > align_error: 0.5537574589252472  (0.5894517831264003)

   --> STEP: 32
     | > decoder_loss: 0.43552151322364807  (0.44283755123615265)
     | > postnet_loss: 0.29745280742645264  (0.3068575784564018)
     | > stopnet_loss: 0.0037736587692052126  (0.005534660951525439)
     | > loss: 0.18701723217964172  (0.19295844295993447)
     | > align_error: 0.5303699374198914  (0.587605475448072)

   --> STEP: 33
     | > decoder_loss: 0.43192437291145325  (0.4425068488626769)
     | > postnet_loss: 0.2951715588569641  (0.3065034566503583)
     | > stopnet_loss: 0.003990924451500177  (0.0054878810575852794)
     | > loss: 0.18576490879058838  (0.1927404570760149)
     | > align_error: 0.5453816652297974  (0.5863259660475182)

   --> STEP: 34
     | > decoder_loss: 0.4378848671913147  (0.4423709082252839)
     | > postnet_loss: 0.29674652218818665  (0.30621648798970613)
     | > stopnet_loss: 0.0032213206868618727  (0.005421217517269885)
     | > loss: 0.18687917292118073  (0.1925680663655786)
     | > align_error: 0.5632254481315613  (0.5856465390499901)

   --> STEP: 35
     | > decoder_loss: 0.43473896384239197  (0.442152852671487)
     | > postnet_loss: 0.2954036295413971  (0.30590754917689733)
     | > stopnet_loss: 0.003473868826404214  (0.005365578983245151)
     | > loss: 0.1860095113515854  (0.19238067907946452)
     | > align_error: 0.532122790813446  (0.5841172891003745)

   --> STEP: 36
     | > decoder_loss: 0.4411577582359314  (0.4421252111593883)
     | > postnet_loss: 0.3003515899181366  (0.3057532169752651)
     | > stopnet_loss: 0.0035939463414251804  (0.005316366965416819)
     | > loss: 0.18897128105163574  (0.1922859735786915)
     | > align_error: 0.6329397559165955  (0.5854734687341584)

   --> STEP: 37
     | > decoder_loss: 0.4335440695285797  (0.4418932884126097)
     | > postnet_loss: 0.2964552640914917  (0.3055019209513793)
     | > stopnet_loss: 0.00351761095225811  (0.005267751938034151)
     | > loss: 0.18601743876934052  (0.19211655371897932)
     | > align_error: 0.5180749297142029  (0.5836518865984839)

   --> STEP: 38
     | > decoder_loss: 0.42037448287010193  (0.44132700405622793)
     | > postnet_loss: 0.2887410819530487  (0.3050608462408969)
     | > stopnet_loss: 0.0030961832962930202  (0.005210605394830437)
     | > loss: 0.18037506937980652  (0.19180756728900109)
     | > align_error: 0.5509368777275085  (0.5827909653124056)

   --> STEP: 39
     | > decoder_loss: 0.43699580430984497  (0.4412159476524745)
     | > postnet_loss: 0.30003032088279724  (0.3049318584112021)
     | > stopnet_loss: 0.003433551639318466  (0.005165039913919873)
     | > loss: 0.18769007921218872  (0.19170199067164692)
     | > align_error: 0.5452696084976196  (0.5818288792402316)

   --> STEP: 40
     | > decoder_loss: 0.43396541476249695  (0.4410346843302251)
     | > postnet_loss: 0.298344224691391  (0.30476716756820676)
     | > stopnet_loss: 0.0029957988299429417  (0.00511080888682045)
     | > loss: 0.1860732138156891  (0.19156127125024797)
     | > align_error: 0.5829196274280548  (0.5818561479449272)

   --> STEP: 41
     | > decoder_loss: 0.42418545484542847  (0.44062372751352274)
     | > postnet_loss: 0.2906785011291504  (0.30442354155749807)
     | > stopnet_loss: 0.003704923205077648  (0.005076518992143796)
     | > loss: 0.18242090940475464  (0.19133833559547983)
     | > align_error: 0.5025054514408112  (0.5799207651033634)

   --> STEP: 42
     | > decoder_loss: 0.42894548177719116  (0.4403456740436101)
     | > postnet_loss: 0.2925977408885956  (0.30414197487490513)
     | > stopnet_loss: 0.003255895571783185  (0.005033170815468543)
     | > loss: 0.1836416870355606  (0.1911550820583389)
     | > align_error: 0.578676700592041  (0.5798911445197605)

   --> STEP: 43
     | > decoder_loss: 0.4289294183254242  (0.44008017972458247)
     | > postnet_loss: 0.29187852144241333  (0.3038567782834518)
     | > stopnet_loss: 0.0029123604763299227  (0.004983849644790901)
     | > loss: 0.18311433494091034  (0.19096808793932893)
     | > align_error: 0.5509804487228394  (0.5792188027570414)

   --> STEP: 44
     | > decoder_loss: 0.4464230239391327  (0.44022433527491317)
     | > postnet_loss: 0.3025537133216858  (0.30382716317068437)
     | > stopnet_loss: 0.002632260788232088  (0.004930404443505473)
     | > loss: 0.18987643718719482  (0.19094327769496225)
     | > align_error: 0.5502367615699768  (0.5785601200027899)

   --> STEP: 45
     | > decoder_loss: 0.43882277607917786  (0.44019318951500797)
     | > postnet_loss: 0.30147528648376465  (0.3037748992443084)
     | > stopnet_loss: 0.003248966997489333  (0.004893039166927337)
     | > loss: 0.1883234679698944  (0.19088505970107184)
     | > align_error: 0.5516640841960907  (0.5779624303181966)

   --> STEP: 46
     | > decoder_loss: 0.42978593707084656  (0.4399669448966566)
     | > postnet_loss: 0.292915403842926  (0.30353882325732184)
     | > stopnet_loss: 0.003154997481033206  (0.0048552556520165945)
     | > loss: 0.18383032083511353  (0.19073169581268146)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.3474706700353911 (+0.0003133325865774528)
     | > avg_decoder_loss: 0.4362435738245647 (+0.0007271658290516902)
     | > avg_postnet_loss: 0.30047505552118475 (-0.00019398286487115612)
     | > avg_stopnet_loss: 0.004309417496463564 (+9.09510576587412e-07)
     | > avg_loss: 0.1884890738310236 (+0.00013420392166485495)
     | > avg_align_error: 0.5708002163605255 (+0.0002105362487561102)


 > EPOCH: 172/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 22:41:40)

   --> TIME: 2025-12-28 22:41:44 -- STEP: 3/150 -- GLOBAL_STEP: 25975
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.45045986771583557  (0.45298468073209125)
     | > postnet_loss: 0.3865707218647003  (0.3886370261510213)
     | > stopnet_loss: 0.01292723510414362  (0.014148592638472715)
     | > loss: 0.22218488156795502  (0.22455401718616486)
     | > align_error: 0.6983516216278076  (0.7140075465043386)
     | > grad_norm: tensor(0.3143, device='cuda:0')  (tensor(0.3041, device='cuda:0'))
     | > step_time: 0.4554  (0.4699876308441162)
     | > loader_time: 0.4998  (0.6272234121958414)


   --> TIME: 2025-12-28 22:42:24 -- STEP: 28/150 -- GLOBAL_STEP: 26000
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.4738861620426178  (0.46414780403886524)
     | > postnet_loss: 0.39380908012390137  (0.3911981391055243)
     | > stopnet_loss: 0.0057719252072274685  (0.00918306109295892)
     | > loss: 0.2226957231760025  (0.22301954669611795)
     | > align_error: 0.6456875503063202  (0.6667434381587165)
     | > grad_norm: tensor(0.2435, device='cuda:0')  (tensor(0.2612, device='cuda:0'))
     | > step_time: 0.8347  (0.6905429533549717)
     | > loader_time: 0.9399  (0.8623486586979457)


   --> TIME: 2025-12-28 22:43:19 -- STEP: 53/150 -- GLOBAL_STEP: 26025
     | > current_lr: 1e-05  (1.0000000000000013e-05)
     | > decoder_loss: 0.4767724871635437  (0.47013077758393196)
     | > postnet_loss: 0.3922650218009949  (0.3927877129248853)
     | > stopnet_loss: 0.004347143229097128  (0.007255151077120934)
     | > loss: 0.2216065227985382  (0.22298477477622483)
     | > align_error: 0.5791162252426147  (0.6453342702028886)
     | > grad_norm: tensor(0.3450, device='cuda:0')  (tensor(0.2605, device='cuda:0'))
     | > step_time: 1.4139  (0.9003552220902353)
     | > loader_time: 1.208  (0.950726108730964)


   --> TIME: 2025-12-28 22:44:29 -- STEP: 78/150 -- GLOBAL_STEP: 26050
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47943761944770813  (0.4731275668511024)
     | > postnet_loss: 0.39251452684402466  (0.39279673114801067)
     | > stopnet_loss: 0.004183096345514059  (0.006227559857786848)
     | > loss: 0.2221711426973343  (0.22270863503217697)
     | > align_error: 0.6152567863464355  (0.6344700761330433)
     | > grad_norm: tensor(0.2625, device='cuda:0')  (tensor(0.2525, device='cuda:0'))
     | > step_time: 1.6106  (1.0844817681190295)
     | > loader_time: 1.781  (1.0648509661356607)


   --> TIME: 2025-12-28 22:45:54 -- STEP: 103/150 -- GLOBAL_STEP: 26075
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4842388927936554  (0.47450024294621734)
     | > postnet_loss: 0.3935001790523529  (0.39220029376085525)
     | > stopnet_loss: 0.0035141357220709324  (0.005592086058544013)
     | > loss: 0.22294890880584717  (0.2222672200318679)
     | > align_error: 0.5945717692375183  (0.6297565577099627)
     | > grad_norm: tensor(0.2113, device='cuda:0')  (tensor(0.2335, device='cuda:0'))
     | > step_time: 1.9092  (1.2446709142147911)
     | > loader_time: 1.4443  (1.2122239256368097)


   --> TIME: 2025-12-28 22:47:26 -- STEP: 128/150 -- GLOBAL_STEP: 26100
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4806255102157593  (0.47562684095464647)
     | > postnet_loss: 0.38927680253982544  (0.3918015907984227)
     | > stopnet_loss: 0.003415995743125677  (0.005139542487086146)
     | > loss: 0.2208915799856186  (0.22199665056541562)
     | > align_error: 0.6168934106826782  (0.6261290314141663)
     | > grad_norm: tensor(0.2114, device='cuda:0')  (tensor(0.2337, device='cuda:0'))
     | > step_time: 2.0564  (1.3870965577661987)
     | > loader_time: 2.0076  (1.3022720981389284)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4560873210430145  (0.4560873210430145)
     | > postnet_loss: 0.33258527517318726  (0.33258527517318726)
     | > stopnet_loss: 0.01206067856401205  (0.01206067856401205)
     | > loss: 0.20922881364822388  (0.20922881364822388)
     | > align_error: 0.7192457318305969  (0.7192457318305969)

   --> STEP: 1
     | > decoder_loss: 0.4361916482448578  (0.4361916482448578)
     | > postnet_loss: 0.3193055987358093  (0.3193055987358093)
     | > stopnet_loss: 0.00967160239815712  (0.00967160239815712)
     | > loss: 0.198545902967453  (0.198545902967453)
     | > align_error: 0.6598230302333832  (0.6598230302333832)

   --> STEP: 2
     | > decoder_loss: 0.432953804731369  (0.4345727264881134)
     | > postnet_loss: 0.31077587604522705  (0.3150407373905182)
     | > stopnet_loss: 0.010916542261838913  (0.010294072329998016)
     | > loss: 0.19684897363185883  (0.19769743829965591)
     | > align_error: 0.6548829078674316  (0.6573529690504074)

   --> STEP: 3
     | > decoder_loss: 0.4387925863265991  (0.4359793464342753)
     | > postnet_loss: 0.3116161823272705  (0.3138992190361023)
     | > stopnet_loss: 0.008066488429903984  (0.009551544363300005)
     | > loss: 0.19566868245601654  (0.19702118635177612)
     | > align_error: 0.7351437509059906  (0.6832832296689352)

   --> STEP: 4
     | > decoder_loss: 0.4400419294834137  (0.4369949921965599)
     | > postnet_loss: 0.3170538544654846  (0.3146878778934479)
     | > stopnet_loss: 0.008186652325093746  (0.00921032135374844)
     | > loss: 0.1974606066942215  (0.19713104143738747)
     | > align_error: 0.6032335162162781  (0.6632708013057709)

   --> STEP: 5
     | > decoder_loss: 0.4237646162509918  (0.43434891700744627)
     | > postnet_loss: 0.3008514940738678  (0.31192060112953185)
     | > stopnet_loss: 0.007985084317624569  (0.008965273946523666)
     | > loss: 0.18913911283016205  (0.1955326557159424)
     | > align_error: 0.6415315866470337  (0.6589229583740235)

   --> STEP: 6
     | > decoder_loss: 0.4402425289154053  (0.43533118565877277)
     | > postnet_loss: 0.31231093406677246  (0.31198565661907196)
     | > stopnet_loss: 0.0071905250661075115  (0.008669482466454307)
     | > loss: 0.19532889127731323  (0.19549869497617087)
     | > align_error: 0.5939874053001404  (0.648100366195043)

   --> STEP: 7
     | > decoder_loss: 0.4518965184688568  (0.4376976617744991)
     | > postnet_loss: 0.3125867545604706  (0.31207152775355745)
     | > stopnet_loss: 0.0060721030458807945  (0.008298428263515234)
     | > loss: 0.19719292223453522  (0.19574072744165147)
     | > align_error: 0.578737735748291  (0.6381914189883641)

   --> STEP: 8
     | > decoder_loss: 0.44563090801239014  (0.43868931755423546)
     | > postnet_loss: 0.3128657341003418  (0.3121708035469055)
     | > stopnet_loss: 0.006963852792978287  (0.008131606329698116)
     | > loss: 0.19658800959587097  (0.19584663771092892)
     | > align_error: 0.5729524791240692  (0.6300365515053272)

   --> STEP: 9
     | > decoder_loss: 0.44391924142837524  (0.43927042020691764)
     | > postnet_loss: 0.31281742453575134  (0.31224265032344395)
     | > stopnet_loss: 0.006666070315986872  (0.007968768994841311)
     | > loss: 0.1958502233028412  (0.1958470361100303)
     | > align_error: 0.5909744799137115  (0.6256963213284811)

   --> STEP: 10
     | > decoder_loss: 0.4688459634780884  (0.44222797453403473)
     | > postnet_loss: 0.3268893361091614  (0.3137073189020157)
     | > stopnet_loss: 0.005598871503025293  (0.007731779245659709)
     | > loss: 0.2045326977968216  (0.1967156022787094)
     | > align_error: 0.5829606056213379  (0.6214227497577667)

   --> STEP: 11
     | > decoder_loss: 0.4558364748954773  (0.4434651109305295)
     | > postnet_loss: 0.3168465793132782  (0.31399270621213043)
     | > stopnet_loss: 0.005899863783270121  (0.007565241476351564)
     | > loss: 0.19907061755657196  (0.19692969457669693)
     | > align_error: 0.5950257778167725  (0.6190230250358582)

   --> STEP: 12
     | > decoder_loss: 0.45234283804893494  (0.44420492152373)
     | > postnet_loss: 0.31082847714424133  (0.313729020456473)
     | > stopnet_loss: 0.007830080576241016  (0.007587311401342352)
     | > loss: 0.1986229121685028  (0.19707079604268074)
     | > align_error: 0.587506115436554  (0.6163966159025828)

   --> STEP: 13
     | > decoder_loss: 0.4410412907600403  (0.44396156531113845)
     | > postnet_loss: 0.3099673092365265  (0.3134396580549387)
     | > stopnet_loss: 0.005254257470369339  (0.007407845714344428)
     | > loss: 0.19300641119480133  (0.19675815105438232)
     | > align_error: 0.5850238800048828  (0.6139833285258367)

   --> STEP: 14
     | > decoder_loss: 0.4535142481327057  (0.44464389979839325)
     | > postnet_loss: 0.3143537640571594  (0.3135049513408116)
     | > stopnet_loss: 0.0048541110008955  (0.007225436091955219)
     | > loss: 0.19682112336158752  (0.19676264907632554)
     | > align_error: 0.5549027621746063  (0.6097632880721774)

   --> STEP: 15
     | > decoder_loss: 0.45138025283813477  (0.4450929900010427)
     | > postnet_loss: 0.3136693835258484  (0.3135159134864807)
     | > stopnet_loss: 0.004966322332620621  (0.007074828507999579)
     | > loss: 0.1962287276983261  (0.19672705431779225)
     | > align_error: 0.5886883735656738  (0.6083582937717438)

   --> STEP: 16
     | > decoder_loss: 0.45184990763664246  (0.44551529735326767)
     | > postnet_loss: 0.30792519450187683  (0.31316649354994297)
     | > stopnet_loss: 0.005258472170680761  (0.006961306236917153)
     | > loss: 0.19520224630832672  (0.19663175381720066)
     | > align_error: 0.6055897176265717  (0.6081852577626705)

   --> STEP: 17
     | > decoder_loss: 0.45744380354881287  (0.44621697418829975)
     | > postnet_loss: 0.3154160976409912  (0.3132988232023576)
     | > stopnet_loss: 0.004743294324725866  (0.006830834947964724)
     | > loss: 0.19795827567577362  (0.19670978451476379)
     | > align_error: 0.5590039491653442  (0.6052922396098867)

   --> STEP: 18
     | > decoder_loss: 0.45191481709480286  (0.4465335210164388)
     | > postnet_loss: 0.307961106300354  (0.3130022833744685)
     | > stopnet_loss: 0.005167869850993156  (0.00673844799813297)
     | > loss: 0.19513684511184692  (0.19662239899237952)
     | > align_error: 0.6043650805950165  (0.6052407307757272)

   --> STEP: 19
     | > decoder_loss: 0.44745171070098877  (0.44658184678930984)
     | > postnet_loss: 0.3063933253288269  (0.31265444347732946)
     | > stopnet_loss: 0.0046614245511591434  (0.006629130974608033)
     | > loss: 0.19312268495559692  (0.19643820351675936)
     | > align_error: 0.5995749533176422  (0.6049425319621438)

   --> STEP: 20
     | > decoder_loss: 0.44663307070732117  (0.44658440798521043)
     | > postnet_loss: 0.30427566170692444  (0.3122355043888092)
     | > stopnet_loss: 0.004421077203005552  (0.0065187282860279085)
     | > loss: 0.19214825332164764  (0.19622370600700378)
     | > align_error: 0.6231711506843567  (0.6058539628982544)

   --> STEP: 21
     | > decoder_loss: 0.44348758459091187  (0.4464369402045295)
     | > postnet_loss: 0.30314207077026367  (0.31180248374030706)
     | > stopnet_loss: 0.00391179695725441  (0.006394588698943456)
     | > loss: 0.190569207072258  (0.19595444415296828)
     | > align_error: 0.5601316094398499  (0.6036767079716637)

   --> STEP: 22
     | > decoder_loss: 0.4441221356391907  (0.4463317218151959)
     | > postnet_loss: 0.3050955832004547  (0.3114976246248592)
     | > stopnet_loss: 0.00447155861184001  (0.006307178240438754)
     | > loss: 0.19177599251270294  (0.1957645145329562)
     | > align_error: 0.6252793669700623  (0.6046586470170454)

   --> STEP: 23
     | > decoder_loss: 0.4197036623954773  (0.44517398010129516)
     | > postnet_loss: 0.2938196361064911  (0.3107290164284084)
     | > stopnet_loss: 0.004428177140653133  (0.006225482540448074)
     | > loss: 0.1828089952468872  (0.1952012310857358)
     | > align_error: 0.5674054026603699  (0.6030389407406682)

   --> STEP: 24
     | > decoder_loss: 0.45401087403297424  (0.4455421840151151)
     | > postnet_loss: 0.30992886424064636  (0.3106956767539183)
     | > stopnet_loss: 0.004368968307971954  (0.00614812778076157)
     | > loss: 0.1953538954257965  (0.19520759209990501)
     | > align_error: 0.5799786746501923  (0.6020780963202318)

   --> STEP: 25
     | > decoder_loss: 0.4527987539768219  (0.44583244681358336)
     | > postnet_loss: 0.30698084831237793  (0.31054708361625666)
     | > stopnet_loss: 0.0036372910253703594  (0.006047694310545922)
     | > loss: 0.1935821771621704  (0.19514257550239564)
     | > align_error: 0.5582836270332336  (0.6003263175487519)

   --> STEP: 26
     | > decoder_loss: 0.4274338185787201  (0.4451248072660886)
     | > postnet_loss: 0.2954285144805908  (0.3099656001879618)
     | > stopnet_loss: 0.004289540927857161  (0.005980073026596353)
     | > loss: 0.18500512838363647  (0.19475267369013566)
     | > align_error: 0.5470667481422424  (0.5982778725715785)

   --> STEP: 27
     | > decoder_loss: 0.42454394698143005  (0.44436255318147166)
     | > postnet_loss: 0.2904118597507477  (0.3092413875791761)
     | > stopnet_loss: 0.003835573559626937  (0.005900647120412301)
     | > loss: 0.18257452547550201  (0.19430163116366775)
     | > align_error: 0.540939211845398  (0.5961542184706089)

   --> STEP: 28
     | > decoder_loss: 0.4309186339378357  (0.44388241320848465)
     | > postnet_loss: 0.29553335905075073  (0.30875181513173233)
     | > stopnet_loss: 0.003907633014023304  (0.005829468045184123)
     | > loss: 0.18552063405513763  (0.1939880241240774)
     | > align_error: 0.5670162439346313  (0.5951135765228954)

   --> STEP: 29
     | > decoder_loss: 0.4258230924606323  (0.4432596780102828)
     | > postnet_loss: 0.29207801818847656  (0.30817685661644767)
     | > stopnet_loss: 0.0035396392922848463  (0.005750508433015182)
     | > loss: 0.183014914393425  (0.19360964102991696)
     | > align_error: 0.5410960018634796  (0.5932509015346397)

   --> STEP: 30
     | > decoder_loss: 0.426662415266037  (0.442706435918808)
     | > postnet_loss: 0.29297155141830444  (0.3076700131098429)
     | > stopnet_loss: 0.002738435985520482  (0.005650106018098692)
     | > loss: 0.18264691531658173  (0.19324421683947246)
     | > align_error: 0.5338769853115082  (0.5912717709938686)

   --> STEP: 31
     | > decoder_loss: 0.42104372382164  (0.4420076387543832)
     | > postnet_loss: 0.2904464900493622  (0.30711441559176283)
     | > stopnet_loss: 0.0036305843386799097  (0.00558496015747228)
     | > loss: 0.18150313198566437  (0.19286547216676897)
     | > align_error: 0.5544094443321228  (0.5900826636821994)

   --> STEP: 32
     | > decoder_loss: 0.43451958894729614  (0.44177363719791174)
     | > postnet_loss: 0.2975415587425232  (0.3068152638152241)
     | > stopnet_loss: 0.0037705451250076294  (0.0055282596877077594)
     | > loss: 0.18678583204746246  (0.19267548341304064)
     | > align_error: 0.5315706431865692  (0.588254163041711)

   --> STEP: 33
     | > decoder_loss: 0.43115517497062683  (0.4414518656152667)
     | > postnet_loss: 0.29500994086265564  (0.30645752675605537)
     | > stopnet_loss: 0.003985756076872349  (0.0054815171540460806)
     | > loss: 0.185527041554451  (0.19245886396278034)
     | > align_error: 0.5468101501464844  (0.5869982838630677)

   --> STEP: 34
     | > decoder_loss: 0.4366191327571869  (0.44130972641355853)
     | > postnet_loss: 0.296432226896286  (0.3061626649954739)
     | > stopnet_loss: 0.0032145415898412466  (0.005414841402157703)
     | > loss: 0.18647737801074982  (0.19228293790536768)
     | > align_error: 0.5642636716365814  (0.5863296187975828)

   --> STEP: 35
     | > decoder_loss: 0.43419480323791504  (0.44110644289425444)
     | > postnet_loss: 0.2957429885864258  (0.3058649599552154)
     | > stopnet_loss: 0.0034877604339271784  (0.005359781945922545)
     | > loss: 0.1859722137451172  (0.1921026315007891)
     | > align_error: 0.5333176851272583  (0.5848149921212878)

   --> STEP: 36
     | > decoder_loss: 0.4400368928909302  (0.44107673317193985)
     | > postnet_loss: 0.3000239431858063  (0.3057027094893985)
     | > stopnet_loss: 0.003590333741158247  (0.005310630606901314)
     | > loss: 0.18860553205013275  (0.19200548984938198)
     | > align_error: 0.63406702876091  (0.5861831042501663)

   --> STEP: 37
     | > decoder_loss: 0.4333333969116211  (0.44086745381355286)
     | > postnet_loss: 0.2968641519546509  (0.3054638295560269)
     | > stopnet_loss: 0.0035253004170954227  (0.005262378439609264)
     | > loss: 0.18607468903064728  (0.19184519793536212)
     | > align_error: 0.5190896391868591  (0.5843697673565633)

   --> STEP: 38
     | > decoder_loss: 0.420005202293396  (0.44031844719460134)
     | > postnet_loss: 0.28913816809654236  (0.3050342068860405)
     | > stopnet_loss: 0.0030816076323390007  (0.005204989734154783)
     | > loss: 0.18036745488643646  (0.19154315206565356)
     | > align_error: 0.5524027049541473  (0.5835285288722892)

   --> STEP: 39
     | > decoder_loss: 0.4360339343547821  (0.44020858789101625)
     | > postnet_loss: 0.2999520003795624  (0.3049038938986949)
     | > stopnet_loss: 0.0034150101710110903  (0.005159092822279303)
     | > loss: 0.18741148710250854  (0.19143721193839341)
     | > align_error: 0.5463593900203705  (0.5825754740299324)

   --> STEP: 40
     | > decoder_loss: 0.4334399998188019  (0.4400393731892109)
     | > postnet_loss: 0.29859501123428345  (0.30474617183208463)
     | > stopnet_loss: 0.00296952435746789  (0.005104353610659018)
     | > loss: 0.18597827851772308  (0.19130073860287666)
     | > align_error: 0.5841249823570251  (0.5826142117381097)

   --> STEP: 41
     | > decoder_loss: 0.4240308403968811  (0.4396489211698858)
     | > postnet_loss: 0.29083776473999023  (0.30440694239081406)
     | > stopnet_loss: 0.0036836694926023483  (0.005069702778511294)
     | > loss: 0.18240082263946533  (0.19108366748181785)
     | > align_error: 0.5035091042518616  (0.5806848188725914)

   --> STEP: 42
     | > decoder_loss: 0.4278726875782013  (0.43936853465579806)
     | > postnet_loss: 0.29235708713531494  (0.30412004107520696)
     | > stopnet_loss: 0.00325184129178524  (0.005026420362160674)
     | > loss: 0.18330927193164825  (0.19089856282586143)
     | > align_error: 0.5799534320831299  (0.5806674049014137)

   --> STEP: 43
     | > decoder_loss: 0.4277373254299164  (0.43909804141798686)
     | > postnet_loss: 0.2917011082172394  (0.3038312286831612)
     | > stopnet_loss: 0.0028861998580396175  (0.004976647792297394)
     | > loss: 0.1827458143234253  (0.1907089640234792)
     | > align_error: 0.5522884726524353  (0.5800074297328328)

   --> STEP: 44
     | > decoder_loss: 0.4456295669078827  (0.43924648517912085)
     | > postnet_loss: 0.3026810884475708  (0.3038050891323523)
     | > stopnet_loss: 0.0026233557146042585  (0.004923163881440732)
     | > loss: 0.18970102071762085  (0.19068605622107332)
     | > align_error: 0.5516145825386047  (0.5793621377511458)

   --> STEP: 45
     | > decoder_loss: 0.4385368824005127  (0.4392307162284851)
     | > postnet_loss: 0.3016757071018219  (0.3037577695316739)
     | > stopnet_loss: 0.003250068286433816  (0.004885983979329467)
     | > loss: 0.18830320239067078  (0.19063310391373103)
     | > align_error: 0.5529199838638306  (0.5787745343314277)

   --> STEP: 46
     | > decoder_loss: 0.43009981513023376  (0.43903221837852313)
     | > postnet_loss: 0.293367862701416  (0.3035319019918857)
     | > stopnet_loss: 0.0031327682081609964  (0.004847870592999718)
     | > loss: 0.183999702334404  (0.19048889953157175)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.2694864814931696 (-0.0779841885422215)
     | > avg_decoder_loss: 0.43546710366552527 (-0.0007764701590394218)
     | > avg_postnet_loss: 0.300639825336861 (+0.00016476981567625781)
     | > avg_stopnet_loss: 0.004302925073936809 (-6.492422526755207e-06)
     | > avg_loss: 0.18832965624151807 (-0.00015941758950552276)
     | > avg_align_error: 0.5717918412251906 (+0.000991624864665086)


 > EPOCH: 173/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 22:50:42)

   --> TIME: 2025-12-28 22:50:45 -- STEP: 2/150 -- GLOBAL_STEP: 26125
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.44308045506477356  (0.44982099533081055)
     | > postnet_loss: 0.3820793032646179  (0.38689084351062775)
     | > stopnet_loss: 0.014646647498011589  (0.014237707480788231)
     | > loss: 0.2209365963935852  (0.22341567277908325)
     | > align_error: 0.7321706116199493  (0.7229353338479996)
     | > grad_norm: tensor(0.2399, device='cuda:0')  (tensor(0.2646, device='cuda:0'))
     | > step_time: 0.4769  (0.4132117033004761)
     | > loader_time: 0.5687  (0.5526883602142334)


   --> TIME: 2025-12-28 22:51:24 -- STEP: 27/150 -- GLOBAL_STEP: 26150
     | > current_lr: 1e-05  (1.0000000000000004e-05)
     | > decoder_loss: 0.47369617223739624  (0.462840563721127)
     | > postnet_loss: 0.39328500628471375  (0.3906297772018998)
     | > stopnet_loss: 0.005901006516069174  (0.0091986821067554)
     | > loss: 0.2226462960243225  (0.22256626906218352)
     | > align_error: 0.6591227650642395  (0.6684942830491949)
     | > grad_norm: tensor(0.1865, device='cuda:0')  (tensor(0.2785, device='cuda:0'))
     | > step_time: 0.9415  (0.665506159817731)
     | > loader_time: 1.1058  (0.8521669617405644)


   --> TIME: 2025-12-28 22:52:20 -- STEP: 52/150 -- GLOBAL_STEP: 26175
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.477568119764328  (0.46977861110980695)
     | > postnet_loss: 0.3932007849216461  (0.3927693200799135)
     | > stopnet_loss: 0.004551142919808626  (0.007324314291159119)
     | > loss: 0.22224336862564087  (0.2229612968288935)
     | > align_error: 0.6591786742210388  (0.646812644142371)
     | > grad_norm: tensor(0.3126, device='cuda:0')  (tensor(0.2720, device='cuda:0'))
     | > step_time: 1.368  (0.8951180118780869)
     | > loader_time: 1.1973  (0.9707255271764902)


   --> TIME: 2025-12-28 22:53:29 -- STEP: 77/150 -- GLOBAL_STEP: 26200
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4813064932823181  (0.47285263956367196)
     | > postnet_loss: 0.3938813805580139  (0.3927460599255252)
     | > stopnet_loss: 0.00435602618381381  (0.006270371459110022)
     | > loss: 0.2231529951095581  (0.22267004615300662)
     | > align_error: 0.6114784479141235  (0.6348101539271219)
     | > grad_norm: tensor(0.1759, device='cuda:0')  (tensor(0.2617, device='cuda:0'))
     | > step_time: 1.5185  (1.0872749322420594)
     | > loader_time: 1.436  (1.0738318647657115)


   --> TIME: 2025-12-28 22:54:49 -- STEP: 102/150 -- GLOBAL_STEP: 26225
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4805419147014618  (0.4741954914495057)
     | > postnet_loss: 0.39082151651382446  (0.392152391520201)
     | > stopnet_loss: 0.003197404555976391  (0.005620152481795086)
     | > loss: 0.22103825211524963  (0.22220712345020444)
     | > align_error: 0.6061980426311493  (0.630044684982767)
     | > grad_norm: tensor(0.1167, device='cuda:0')  (tensor(0.2569, device='cuda:0'))
     | > step_time: 1.7906  (1.231473873643314)
     | > loader_time: 1.6731  (1.180626913612964)


   --> TIME: 2025-12-28 22:56:26 -- STEP: 127/150 -- GLOBAL_STEP: 26250
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48045167326927185  (0.47530335000180823)
     | > postnet_loss: 0.3898601830005646  (0.3916913918622835)
     | > stopnet_loss: 0.0029381108470261097  (0.005153538193553685)
     | > loss: 0.22051607072353363  (0.2219022241399044)
     | > align_error: 0.598707914352417  (0.626290642605053)
     | > grad_norm: tensor(0.1582, device='cuda:0')  (tensor(0.2486, device='cuda:0'))
     | > step_time: 2.0057  (1.366448201532439)
     | > loader_time: 2.4898  (1.3298506868167184)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.457144170999527  (0.457144170999527)
     | > postnet_loss: 0.33465367555618286  (0.33465367555618286)
     | > stopnet_loss: 0.012057987973093987  (0.012057987973093987)
     | > loss: 0.2100074589252472  (0.2100074589252472)
     | > align_error: 0.7183514833450317  (0.7183514833450317)

   --> STEP: 1
     | > decoder_loss: 0.43693605065345764  (0.43693605065345764)
     | > postnet_loss: 0.32197442650794983  (0.32197442650794983)
     | > stopnet_loss: 0.009550758637487888  (0.009550758637487888)
     | > loss: 0.19927838444709778  (0.19927838444709778)
     | > align_error: 0.6585480868816376  (0.6585480868816376)

   --> STEP: 2
     | > decoder_loss: 0.4345566928386688  (0.43574637174606323)
     | > postnet_loss: 0.312831312417984  (0.3174028694629669)
     | > stopnet_loss: 0.010857927612960339  (0.010204343125224113)
     | > loss: 0.19770492613315582  (0.1984916552901268)
     | > align_error: 0.6543729305267334  (0.6564605087041855)

   --> STEP: 3
     | > decoder_loss: 0.4381978213787079  (0.43656352162361145)
     | > postnet_loss: 0.3131074011325836  (0.3159710466861725)
     | > stopnet_loss: 0.007965460419654846  (0.009458048890034357)
     | > loss: 0.19579176604747772  (0.19759169220924377)
     | > align_error: 0.734011322259903  (0.6823107798894247)

   --> STEP: 4
     | > decoder_loss: 0.44077980518341064  (0.43761759251356125)
     | > postnet_loss: 0.319092720746994  (0.31675146520137787)
     | > stopnet_loss: 0.008150395005941391  (0.009131135419011116)
     | > loss: 0.19811853766441345  (0.1977234035730362)
     | > align_error: 0.6020877957344055  (0.6622550338506699)

   --> STEP: 5
     | > decoder_loss: 0.4250486195087433  (0.4351037979125977)
     | > postnet_loss: 0.30305320024490356  (0.314011812210083)
     | > stopnet_loss: 0.007985837757587433  (0.008902075886726379)
     | > loss: 0.19001129269599915  (0.1961809813976288)
     | > align_error: 0.6405869424343109  (0.657921415567398)

   --> STEP: 6
     | > decoder_loss: 0.44155654311180115  (0.4361792554457982)
     | > postnet_loss: 0.3146607279777527  (0.31411996483802795)
     | > stopnet_loss: 0.0072128381580114365  (0.00862053626527389)
     | > loss: 0.19626714289188385  (0.1961953416466713)
     | > align_error: 0.592654287815094  (0.6470435609420141)

   --> STEP: 7
     | > decoder_loss: 0.45159462094306946  (0.43838145051683697)
     | > postnet_loss: 0.31354671716690063  (0.3140380723135812)
     | > stopnet_loss: 0.0060899225063622  (0.00825902001400079)
     | > loss: 0.19737526774406433  (0.19636390251772745)
     | > align_error: 0.577656090259552  (0.6371310651302338)

   --> STEP: 8
     | > decoder_loss: 0.4468230605125427  (0.4394366517663002)
     | > postnet_loss: 0.3153083622455597  (0.3141968585550785)
     | > stopnet_loss: 0.006971051916480064  (0.0080980240018107)
     | > loss: 0.19750390946865082  (0.19650640338659286)
     | > align_error: 0.5727015733718872  (0.6290773786604404)

   --> STEP: 9
     | > decoder_loss: 0.444943368434906  (0.4400485091739231)
     | > postnet_loss: 0.31460246443748474  (0.3142419258753459)
     | > stopnet_loss: 0.0065651400946080685  (0.007927703567677073)
     | > loss: 0.1964515894651413  (0.19650031295087603)
     | > align_error: 0.5896707773208618  (0.6246988674004873)

   --> STEP: 10
     | > decoder_loss: 0.4688872992992401  (0.44293238818645475)
     | > postnet_loss: 0.32888832688331604  (0.3157065659761429)
     | > stopnet_loss: 0.005569618660956621  (0.007691895077005029)
     | > loss: 0.20501352846622467  (0.1973516345024109)
     | > align_error: 0.5816062688827515  (0.6203896075487136)

   --> STEP: 11
     | > decoder_loss: 0.4546751379966736  (0.44399991089647467)
     | > postnet_loss: 0.31738346815109253  (0.315859011628411)
     | > stopnet_loss: 0.005902365315705538  (0.007529210553250529)
     | > loss: 0.19891701638698578  (0.19749394194646316)
     | > align_error: 0.5938268899917603  (0.6179748150435361)

   --> STEP: 12
     | > decoder_loss: 0.4528590738773346  (0.444738174478213)
     | > postnet_loss: 0.312304824590683  (0.31556282937526703)
     | > stopnet_loss: 0.00782306119799614  (0.00755369810697933)
     | > loss: 0.19911403954029083  (0.19762895007928213)
     | > align_error: 0.5868104100227356  (0.6153777812918028)

   --> STEP: 13
     | > decoder_loss: 0.4413106143474579  (0.44447451600661647)
     | > postnet_loss: 0.31145137548446655  (0.3152465636913593)
     | > stopnet_loss: 0.00522440392524004  (0.007374521631460924)
     | > loss: 0.19341489672660828  (0.19730479212907645)
     | > align_error: 0.5837787389755249  (0.6129470857290121)

   --> STEP: 14
     | > decoder_loss: 0.4549805521965027  (0.4452249471630369)
     | > postnet_loss: 0.31666064262390137  (0.315347569329398)
     | > stopnet_loss: 0.004899418447166681  (0.007197728546868477)
     | > loss: 0.19780971109867096  (0.19734085776976176)
     | > align_error: 0.5535483062267303  (0.6087043157645634)

   --> STEP: 15
     | > decoder_loss: 0.45014578104019165  (0.4455530027548472)
     | > postnet_loss: 0.31383395195007324  (0.3152466615041097)
     | > stopnet_loss: 0.0049524446949362755  (0.007048042956739664)
     | > loss: 0.19594737887382507  (0.19724795917669932)
     | > align_error: 0.5874195694923401  (0.6072853326797485)

   --> STEP: 16
     | > decoder_loss: 0.45118480920791626  (0.445904990658164)
     | > postnet_loss: 0.30860862135887146  (0.3148317839950323)
     | > stopnet_loss: 0.005226269830018282  (0.006934182136319578)
     | > loss: 0.19517461955547333  (0.1971183754503727)
     | > align_error: 0.604222297668457  (0.6070938929915428)

   --> STEP: 17
     | > decoder_loss: 0.45723310112953186  (0.44657135009765625)
     | > postnet_loss: 0.31623736023902893  (0.3149144649505615)
     | > stopnet_loss: 0.00474508898332715  (0.006805411950849435)
     | > loss: 0.19811271131038666  (0.1971768657950794)
     | > align_error: 0.5576575994491577  (0.6041858757243437)

   --> STEP: 18
     | > decoder_loss: 0.4504922032356262  (0.4467891752719879)
     | > postnet_loss: 0.30824124813079834  (0.3145437306827969)
     | > stopnet_loss: 0.005170784424990416  (0.006714599310523934)
     | > loss: 0.19485414028167725  (0.19704782548877928)
     | > align_error: 0.6033609509468079  (0.6041400465700362)

   --> STEP: 19
     | > decoder_loss: 0.4465363621711731  (0.44677586931931346)
     | > postnet_loss: 0.30761218070983887  (0.3141789122631675)
     | > stopnet_loss: 0.004667582456022501  (0.006606861581339648)
     | > loss: 0.19320471584796906  (0.19684555656031558)
     | > align_error: 0.5974888205528259  (0.6037899820428145)

   --> STEP: 20
     | > decoder_loss: 0.44495895504951477  (0.4466850236058235)
     | > postnet_loss: 0.30432456731796265  (0.3136861950159073)
     | > stopnet_loss: 0.004399555269628763  (0.006496496265754104)
     | > loss: 0.19172044098377228  (0.19658930078148842)
     | > align_error: 0.622382402420044  (0.604719603061676)

   --> STEP: 21
     | > decoder_loss: 0.44320860505104065  (0.4465194798651196)
     | > postnet_loss: 0.3047628402709961  (0.3132612733613877)
     | > stopnet_loss: 0.0038961407262831926  (0.006372669811493584)
     | > loss: 0.19088900089263916  (0.19631785792963846)
     | > align_error: 0.5587038397789001  (0.6025283762386867)

   --> STEP: 22
     | > decoder_loss: 0.4435825049877167  (0.4463859810070558)
     | > postnet_loss: 0.30607515573501587  (0.3129346316510981)
     | > stopnet_loss: 0.004445768427103758  (0.00628508338493041)
     | > loss: 0.191860169172287  (0.1961152357133952)
     | > align_error: 0.6237226128578186  (0.6034917506304655)

   --> STEP: 23
     | > decoder_loss: 0.4185000956058502  (0.44517355120700336)
     | > postnet_loss: 0.29447343945503235  (0.31213197112083435)
     | > stopnet_loss: 0.004447759594768286  (0.006205199741879883)
     | > loss: 0.18269114196300507  (0.19553157946337824)
     | > align_error: 0.5660300254821777  (0.6018629799718442)

   --> STEP: 24
     | > decoder_loss: 0.4521295726299286  (0.4454633854329586)
     | > postnet_loss: 0.30988261103630066  (0.31203824778397876)
     | > stopnet_loss: 0.0043686567805707455  (0.006128677118492003)
     | > loss: 0.1948717087507248  (0.195504084850351)
     | > align_error: 0.5786763727664948  (0.600896871338288)

   --> STEP: 25
     | > decoder_loss: 0.45112863183021545  (0.4456899952888489)
     | > postnet_loss: 0.30736663937568665  (0.31185138344764707)
     | > stopnet_loss: 0.003640882670879364  (0.006029165340587497)
     | > loss: 0.1932646930217743  (0.19541450917720796)
     | > align_error: 0.5568106174468994  (0.5991334211826325)

   --> STEP: 26
     | > decoder_loss: 0.42722561955451965  (0.44497982699137467)
     | > postnet_loss: 0.2967565655708313  (0.311270813529308)
     | > stopnet_loss: 0.0042669023387134075  (0.00596138599436157)
     | > loss: 0.18526245653629303  (0.19502404561409584)
     | > align_error: 0.5458119511604309  (0.5970825954125478)

   --> STEP: 27
     | > decoder_loss: 0.4231281280517578  (0.4441705048084259)
     | > postnet_loss: 0.2906912565231323  (0.3105086077142645)
     | > stopnet_loss: 0.003579329000785947  (0.005873161661266176)
     | > loss: 0.1820341795682907  (0.1945429394642512)
     | > align_error: 0.5394113063812256  (0.594946621744721)

   --> STEP: 28
     | > decoder_loss: 0.4296780824661255  (0.4436529182962009)
     | > postnet_loss: 0.29619812965393066  (0.3099975192121097)
     | > stopnet_loss: 0.0038765480276197195  (0.005801854031493089)
     | > loss: 0.1853456050157547  (0.19421446323394775)
     | > align_error: 0.5658042132854462  (0.5939058214426041)

   --> STEP: 29
     | > decoder_loss: 0.4250268042087555  (0.4430106385000821)
     | > postnet_loss: 0.2933397889137268  (0.30942311471906203)
     | > stopnet_loss: 0.003494720906019211  (0.005722297716821576)
     | > loss: 0.18308638036251068  (0.19383073623838096)
     | > align_error: 0.5397869348526001  (0.5920396529395004)

   --> STEP: 30
     | > decoder_loss: 0.42632928490638733  (0.44245459338029225)
     | > postnet_loss: 0.2944765090942383  (0.3089248945315679)
     | > stopnet_loss: 0.0027114232070744038  (0.0056219352331633365)
     | > loss: 0.18291287124156952  (0.1934668074051539)
     | > align_error: 0.5324940383434296  (0.5900547991196314)

   --> STEP: 31
     | > decoder_loss: 0.4194051921367645  (0.4417110643079204)
     | > postnet_loss: 0.29075348377227783  (0.30833871999094564)
     | > stopnet_loss: 0.0036261712666600943  (0.00555755575037291)
     | > loss: 0.18116584420204163  (0.19307000214053738)
     | > align_error: 0.5531382858753204  (0.5888639438536859)

   --> STEP: 32
     | > decoder_loss: 0.4339616298675537  (0.44146889448165894)
     | > postnet_loss: 0.29857057332992554  (0.30803346540778875)
     | > stopnet_loss: 0.0037600297946482897  (0.005501383064256515)
     | > loss: 0.18689307570457458  (0.19287697318941355)
     | > align_error: 0.5303986668586731  (0.5870369039475918)

   --> STEP: 33
     | > decoder_loss: 0.4298889935016632  (0.441117988391356)
     | > postnet_loss: 0.2955118417739868  (0.3076540222673705)
     | > stopnet_loss: 0.003976458217948675  (0.005455173220429005)
     | > loss: 0.18532666563987732  (0.19264817599094275)
     | > align_error: 0.5455405116081238  (0.5857794375130625)

   --> STEP: 34
     | > decoder_loss: 0.4360189735889435  (0.44096801736775565)
     | > postnet_loss: 0.2971653342247009  (0.30734553144258614)
     | > stopnet_loss: 0.0032075310591608286  (0.005389066098038764)
     | > loss: 0.18650361895561218  (0.19246745372519775)
     | > align_error: 0.5632010102272034  (0.5851153661223019)

   --> STEP: 35
     | > decoder_loss: 0.43345844745635986  (0.44075345822743006)
     | > postnet_loss: 0.29671916365623474  (0.30704192093440463)
     | > stopnet_loss: 0.0034517247695475817  (0.005333713488653302)
     | > loss: 0.1859961301088333  (0.1922825587647302)
     | > align_error: 0.532111793756485  (0.5836009783404214)

   --> STEP: 36
     | > decoder_loss: 0.4384761154651642  (0.44069019870625603)
     | > postnet_loss: 0.3002384305000305  (0.30685293508900535)
     | > stopnet_loss: 0.003582384204491973  (0.005285065452982154)
     | > loss: 0.1882610321044922  (0.19217084969083467)
     | > align_error: 0.6329537630081177  (0.5849718890256351)

   --> STEP: 37
     | > decoder_loss: 0.43252745270729065  (0.44046958394952723)
     | > postnet_loss: 0.2978380024433136  (0.3066092882607434)
     | > stopnet_loss: 0.003491058014333248  (0.005236578765451102)
     | > loss: 0.18608242273330688  (0.1920062976109015)
     | > align_error: 0.518082320690155  (0.5831640628544059)

   --> STEP: 38
     | > decoder_loss: 0.41915446519851685  (0.43990865977186905)
     | > postnet_loss: 0.2899368405342102  (0.306170539636361)
     | > stopnet_loss: 0.0030746362172067165  (0.005179685540497302)
     | > loss: 0.18034745752811432  (0.19169948602977552)
     | > align_error: 0.55122110247612  (0.5823234586339247)

   --> STEP: 39
     | > decoder_loss: 0.4363432228565216  (0.4398172383125012)
     | > postnet_loss: 0.30172377824783325  (0.3060565201135782)
     | > stopnet_loss: 0.0033912749495357275  (0.005133828858677775)
     | > loss: 0.18790803849697113  (0.1916022694263703)
     | > align_error: 0.5450130701065063  (0.5813667820050166)

   --> STEP: 40
     | > decoder_loss: 0.4329182207584381  (0.4396447628736496)
     | > postnet_loss: 0.29980161786079407  (0.3059001475572586)
     | > stopnet_loss: 0.002978290431201458  (0.005079940397990867)
     | > loss: 0.18615825474262238  (0.1914661690592766)
     | > align_error: 0.5827809870243073  (0.5814021371304988)

   --> STEP: 41
     | > decoder_loss: 0.42365413904190063  (0.4392547476582411)
     | > postnet_loss: 0.2920823395252228  (0.3055631278491602)
     | > stopnet_loss: 0.003683083225041628  (0.005045870710845763)
     | > loss: 0.1826172173023224  (0.19125034096764357)
     | > align_error: 0.5020904541015625  (0.5794677058371102)

   --> STEP: 42
     | > decoder_loss: 0.42905884981155396  (0.4390119881857009)
     | > postnet_loss: 0.2943153977394104  (0.305295324751309)
     | > stopnet_loss: 0.0032395548187196255  (0.005002863189604665)
     | > loss: 0.18408311903476715  (0.1910796928263846)
     | > align_error: 0.57863849401474  (0.5794479626984823)

   --> STEP: 43
     | > decoder_loss: 0.42662593722343445  (0.438723940488904)
     | > postnet_loss: 0.29212766885757446  (0.30498910019564074)
     | > stopnet_loss: 0.002870106603950262  (0.004953264199240609)
     | > loss: 0.18255850672721863  (0.19088152570779934)
     | > align_error: 0.5507695376873016  (0.5787810225819432)

   --> STEP: 44
     | > decoder_loss: 0.4451078474521637  (0.43886902928352356)
     | > postnet_loss: 0.3039487898349762  (0.3049654567783529)
     | > stopnet_loss: 0.00260348804295063  (0.004899860195688564)
     | > loss: 0.18986764550209045  (0.1908584829758514)
     | > align_error: 0.550478458404541  (0.5781377824870022)

   --> STEP: 45
     | > decoder_loss: 0.4384050965309143  (0.4388587196667989)
     | > postnet_loss: 0.3029725253582001  (0.30492116941346065)
     | > stopnet_loss: 0.003225846914574504  (0.004862659900552696)
     | > loss: 0.18857024610042572  (0.1908076332675086)
     | > align_error: 0.5516995489597321  (0.5775502661863962)

   --> STEP: 46
     | > decoder_loss: 0.4295523166656494  (0.43865640655807825)
     | > postnet_loss: 0.29460710287094116  (0.30469695057557983)
     | > stopnet_loss: 0.0031221439130604267  (0.004824822596476777)
     | > loss: 0.18416200578212738  (0.19066316310478293)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.39437573606317694 (+0.12488925457000732)
     | > avg_decoder_loss: 0.435101435491533 (-0.0003656681739922507)
     | > avg_postnet_loss: 0.3020328472961079 (+0.0013930219592468984)
     | > avg_stopnet_loss: 0.004283162101990346 (-1.9762971946462975e-05)
     | > avg_loss: 0.18856673371611218 (+0.0002370774745941162)
     | > avg_align_error: 0.5705416757952082 (-0.0012501654299823528)


 > EPOCH: 174/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 23:00:21)

   --> TIME: 2025-12-28 23:00:23 -- STEP: 1/150 -- GLOBAL_STEP: 26275
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4561575949192047  (0.4561575949192047)
     | > postnet_loss: 0.3921721279621124  (0.3921721279621124)
     | > stopnet_loss: 0.014787222258746624  (0.014787222258746624)
     | > loss: 0.22686965763568878  (0.22686965763568878)
     | > align_error: 0.713146299123764  (0.713146299123764)
     | > grad_norm: tensor(0.3700, device='cuda:0')  (tensor(0.3700, device='cuda:0'))
     | > step_time: 0.3971  (0.3970959186553955)
     | > loader_time: 0.5782  (0.5782127380371094)


   --> TIME: 2025-12-28 23:01:02 -- STEP: 26/150 -- GLOBAL_STEP: 26300
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.47523027658462524  (0.4619690156899966)
     | > postnet_loss: 0.3959192931652069  (0.38994566752360416)
     | > stopnet_loss: 0.006878691725432873  (0.00960256918691672)
     | > loss: 0.2246660739183426  (0.22258123927391493)
     | > align_error: 0.6200990378856659  (0.6670968509637393)
     | > grad_norm: tensor(0.2291, device='cuda:0')  (tensor(0.2770, device='cuda:0'))
     | > step_time: 0.8963  (0.675137739915114)
     | > loader_time: 0.9865  (0.8898453712463379)


   --> TIME: 2025-12-28 23:01:58 -- STEP: 51/150 -- GLOBAL_STEP: 26325
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.47735002636909485  (0.46924224028400346)
     | > postnet_loss: 0.39330819249153137  (0.3923367238512226)
     | > stopnet_loss: 0.0044711921364068985  (0.007488318956365774)
     | > loss: 0.2221357524394989  (0.2228830599901723)
     | > align_error: 0.61053067445755  (0.6460685338459762)
     | > grad_norm: tensor(0.1593, device='cuda:0')  (tensor(0.2590, device='cuda:0'))
     | > step_time: 1.3328  (0.89910608179429)
     | > loader_time: 1.216  (0.9902821288389319)


   --> TIME: 2025-12-28 23:03:11 -- STEP: 76/150 -- GLOBAL_STEP: 26350
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4834718704223633  (0.4724038435440314)
     | > postnet_loss: 0.39452269673347473  (0.392392843177444)
     | > stopnet_loss: 0.003646053373813629  (0.006378394723134606)
     | > loss: 0.22314468026161194  (0.22257756539865545)
     | > align_error: 0.6029759347438812  (0.6346137370718151)
     | > grad_norm: tensor(0.2337, device='cuda:0')  (tensor(0.2344, device='cuda:0'))
     | > step_time: 1.5833  (1.0826760154021413)
     | > loader_time: 2.0284  (1.140367900070391)


   --> TIME: 2025-12-28 23:04:32 -- STEP: 101/150 -- GLOBAL_STEP: 26375
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4798740744590759  (0.47381729064601485)
     | > postnet_loss: 0.3918035924434662  (0.39183318526437966)
     | > stopnet_loss: 0.0036705515813082457  (0.00572000428951244)
     | > loss: 0.22158996760845184  (0.22213262231043068)
     | > align_error: 0.6046089828014374  (0.6297523429488191)
     | > grad_norm: tensor(0.1436, device='cuda:0')  (tensor(0.2207, device='cuda:0'))
     | > step_time: 1.2299  (1.2366910075197128)
     | > loader_time: 0.4172  (1.2436048181930388)


   --> TIME: 2025-12-28 23:06:05 -- STEP: 126/150 -- GLOBAL_STEP: 26400
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.479692280292511  (0.47502199643188053)
     | > postnet_loss: 0.388264924287796  (0.39144934430008843)
     | > stopnet_loss: 0.0028558382764458656  (0.005231450714673552)
     | > loss: 0.21984514594078064  (0.22184928506612778)
     | > align_error: 0.6083078384399414  (0.6259830735978626)
     | > grad_norm: tensor(0.1247, device='cuda:0')  (tensor(0.2127, device='cuda:0'))
     | > step_time: 2.0051  (1.3747114662140139)
     | > loader_time: 1.8971  (1.3494182124970446)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.455332487821579  (0.455332487821579)
     | > postnet_loss: 0.3326109051704407  (0.3326109051704407)
     | > stopnet_loss: 0.012159102596342564  (0.012159102596342564)
     | > loss: 0.2091449499130249  (0.2091449499130249)
     | > align_error: 0.7184906601905823  (0.7184906601905823)

   --> STEP: 1
     | > decoder_loss: 0.43676140904426575  (0.43676140904426575)
     | > postnet_loss: 0.3208482563495636  (0.3208482563495636)
     | > stopnet_loss: 0.00959008652716875  (0.00959008652716875)
     | > loss: 0.1989925056695938  (0.1989925056695938)
     | > align_error: 0.6587570309638977  (0.6587570309638977)

   --> STEP: 2
     | > decoder_loss: 0.4328969120979309  (0.4348291605710983)
     | > postnet_loss: 0.31118759512901306  (0.31601792573928833)
     | > stopnet_loss: 0.010923916473984718  (0.010257001500576735)
     | > loss: 0.19694504141807556  (0.1979687735438347)
     | > align_error: 0.6542561054229736  (0.6565065681934357)

   --> STEP: 3
     | > decoder_loss: 0.4361245930194855  (0.43526097138722736)
     | > postnet_loss: 0.310931921005249  (0.3143225908279419)
     | > stopnet_loss: 0.008095698431134224  (0.009536567144095898)
     | > loss: 0.1948598176240921  (0.1969324549039205)
     | > align_error: 0.733915388584137  (0.6823095083236694)

   --> STEP: 4
     | > decoder_loss: 0.43826574087142944  (0.4360121637582779)
     | > postnet_loss: 0.3170509934425354  (0.31500469148159027)
     | > stopnet_loss: 0.008177599869668484  (0.009196825325489044)
     | > loss: 0.19700677692890167  (0.1969510354101658)
     | > align_error: 0.6021471619606018  (0.6622689217329025)

   --> STEP: 5
     | > decoder_loss: 0.4221494495868683  (0.433239620923996)
     | > postnet_loss: 0.3007979393005371  (0.3121633410453796)
     | > stopnet_loss: 0.008052637800574303  (0.008967987820506096)
     | > loss: 0.1887894719839096  (0.19531872272491455)
     | > align_error: 0.6405433118343353  (0.657923799753189)

   --> STEP: 6
     | > decoder_loss: 0.4405674636363983  (0.4344609280427297)
     | > postnet_loss: 0.3136630654335022  (0.3124132951100667)
     | > stopnet_loss: 0.0072972518391907215  (0.0086895318236202)
     | > loss: 0.19585487246513367  (0.19540808101495108)
     | > align_error: 0.5929181575775146  (0.6470895260572433)

   --> STEP: 7
     | > decoder_loss: 0.45015189051628113  (0.4367024941103799)
     | > postnet_loss: 0.31271517276763916  (0.31245642048971994)
     | > stopnet_loss: 0.006126968190073967  (0.008323451304542167)
     | > loss: 0.19684374332427979  (0.19561317563056946)
     | > align_error: 0.578126847743988  (0.6372377148696354)

   --> STEP: 8
     | > decoder_loss: 0.4444361627101898  (0.43766920268535614)
     | > postnet_loss: 0.31328511238098145  (0.3125600069761276)
     | > stopnet_loss: 0.007045642472803593  (0.008163725200574845)
     | > loss: 0.19647596776485443  (0.19572102464735508)
     | > align_error: 0.5730552673339844  (0.6292149089276791)

   --> STEP: 9
     | > decoder_loss: 0.44438183307647705  (0.4384150505065918)
     | > postnet_loss: 0.3143244683742523  (0.3127560582425859)
     | > stopnet_loss: 0.006554910913109779  (0.00798496805752317)
     | > loss: 0.19623149931430817  (0.1957777440547943)
     | > align_error: 0.5896270573139191  (0.6248162587483724)

   --> STEP: 10
     | > decoder_loss: 0.4682867228984833  (0.4414022177457809)
     | > postnet_loss: 0.3279532790184021  (0.31427578032016756)
     | > stopnet_loss: 0.005543557461351156  (0.00774082699790597)
     | > loss: 0.20460355281829834  (0.19666032493114471)
     | > align_error: 0.5817962288856506  (0.6205142557621002)

   --> STEP: 11
     | > decoder_loss: 0.4543784558773041  (0.4425818757577376)
     | > postnet_loss: 0.3170529901981354  (0.3145282539454373)
     | > stopnet_loss: 0.005918942391872406  (0.007575201124630191)
     | > loss: 0.19877681136131287  (0.19685273278843274)
     | > align_error: 0.594022810459137  (0.6181059425527399)

   --> STEP: 12
     | > decoder_loss: 0.4520014226436615  (0.44336683799823123)
     | > postnet_loss: 0.3118477463722229  (0.3143048783143361)
     | > stopnet_loss: 0.007797983940690756  (0.007593766359301905)
     | > loss: 0.1987602710723877  (0.19701169431209564)
     | > align_error: 0.5871729850769043  (0.6155281960964202)

   --> STEP: 13
     | > decoder_loss: 0.44045117497444153  (0.4431425562271705)
     | > postnet_loss: 0.3107631206512451  (0.3140324354171753)
     | > stopnet_loss: 0.005264371633529663  (0.007414582149627117)
     | > loss: 0.19306793808937073  (0.19670832844880912)
     | > align_error: 0.5839628279209137  (0.6131000908521504)

   --> STEP: 14
     | > decoder_loss: 0.4542385935783386  (0.44393513032368254)
     | > postnet_loss: 0.31565433740615845  (0.3141482855592455)
     | > stopnet_loss: 0.004905723966658115  (0.00723537799370076)
     | > loss: 0.1973789632320404  (0.19675623093332564)
     | > align_error: 0.5537963211536407  (0.6088641073022568)

   --> STEP: 15
     | > decoder_loss: 0.44870129227638245  (0.4442528744538625)
     | > postnet_loss: 0.31282833218574524  (0.3140602886676788)
     | > stopnet_loss: 0.004922067746520042  (0.0070811573105553785)
     | > loss: 0.19530446827411652  (0.19665944675604502)
     | > align_error: 0.5874631404876709  (0.6074373761812845)

   --> STEP: 16
     | > decoder_loss: 0.4500978887081146  (0.44461818784475327)
     | > postnet_loss: 0.3076086938381195  (0.3136570639908314)
     | > stopnet_loss: 0.0052500031888484955  (0.006966710177948698)
     | > loss: 0.19467665255069733  (0.1965355221182108)
     | > align_error: 0.60471510887146  (0.6072672344744204)

   --> STEP: 17
     | > decoder_loss: 0.45801782608032227  (0.44540640185861025)
     | > postnet_loss: 0.3167669475078583  (0.31383999831536236)
     | > stopnet_loss: 0.004753082524985075  (0.006836496786597897)
     | > loss: 0.1984492838382721  (0.19664809633703792)
     | > align_error: 0.5579772591590881  (0.6043678241617538)

   --> STEP: 18
     | > decoder_loss: 0.44949230551719666  (0.4456333965063095)
     | > postnet_loss: 0.307229220867157  (0.3134727329015732)
     | > stopnet_loss: 0.005196524318307638  (0.006745387205026216)
     | > loss: 0.1943769007921219  (0.1965219188067648)
     | > align_error: 0.6036841571331024  (0.6043298426601621)

   --> STEP: 19
     | > decoder_loss: 0.4457579553127289  (0.44563995223296315)
     | > postnet_loss: 0.30664631724357605  (0.31311344786694173)
     | > stopnet_loss: 0.00468479236587882  (0.00663693484507109)
     | > loss: 0.1927858591079712  (0.19632528408577568)
     | > align_error: 0.5975849032402039  (0.6039748458485853)

   --> STEP: 20
     | > decoder_loss: 0.44387179613113403  (0.4455515444278717)
     | > postnet_loss: 0.30321621894836426  (0.31261858642101287)
     | > stopnet_loss: 0.004436018411070108  (0.0065268890233710405)
     | > loss: 0.19120801985263824  (0.1960694208741188)
     | > align_error: 0.6225569546222687  (0.6049039512872695)

   --> STEP: 21
     | > decoder_loss: 0.44237908720970154  (0.44540047503653024)
     | > postnet_loss: 0.30372339487075806  (0.31219500587100074)
     | > stopnet_loss: 0.003937160596251488  (0.006403568622079634)
     | > loss: 0.19046276807785034  (0.19580243740762984)
     | > align_error: 0.5592671632766724  (0.6027307709058125)

   --> STEP: 22
     | > decoder_loss: 0.4425677955150604  (0.44527171687646344)
     | > postnet_loss: 0.3047580420970917  (0.31185696206309577)
     | > stopnet_loss: 0.004489804618060589  (0.006316579349169677)
     | > loss: 0.1913212686777115  (0.19559874791990628)
     | > align_error: 0.6243575811386108  (0.6037138077345761)

   --> STEP: 23
     | > decoder_loss: 0.41762596368789673  (0.4440697276073953)
     | > postnet_loss: 0.29327061772346497  (0.31104886013528577)
     | > stopnet_loss: 0.004430388566106558  (0.006234571054253889)
     | > loss: 0.18215453624725342  (0.195014216977617)
     | > align_error: 0.566667914390564  (0.602103116719619)

   --> STEP: 24
     | > decoder_loss: 0.4508620798587799  (0.44435274228453636)
     | > postnet_loss: 0.30843406915664673  (0.3109399105111758)
     | > stopnet_loss: 0.004364511929452419  (0.006156651924053828)
     | > loss: 0.19418855011463165  (0.1949798141916593)
     | > align_error: 0.5791963636875153  (0.6011486686766147)

   --> STEP: 25
     | > decoder_loss: 0.450304239988327  (0.444590802192688)
     | > postnet_loss: 0.3061855733394623  (0.31074973702430725)
     | > stopnet_loss: 0.003675767220556736  (0.006057416535913945)
     | > loss: 0.19279822707176208  (0.1948925507068634)
     | > align_error: 0.557173490524292  (0.5993896615505218)

   --> STEP: 26
     | > decoder_loss: 0.42536142468452454  (0.44385121075006634)
     | > postnet_loss: 0.29483088850975037  (0.31013747361990124)
     | > stopnet_loss: 0.004275031387805939  (0.005988863260986714)
     | > loss: 0.18432310223579407  (0.19448603345797613)
     | > align_error: 0.5460807681083679  (0.5973393194950544)

   --> STEP: 27
     | > decoder_loss: 0.4230538010597229  (0.4430809363170906)
     | > postnet_loss: 0.289976567029953  (0.30939077337582904)
     | > stopnet_loss: 0.0035763767082244158  (0.005899511907180703)
     | > loss: 0.18183396756649017  (0.1940174384249581)
     | > align_error: 0.5396164059638977  (0.5952014338087153)

   --> STEP: 28
     | > decoder_loss: 0.4290730059146881  (0.4425806530884334)
     | > postnet_loss: 0.29505857825279236  (0.308878909264292)
     | > stopnet_loss: 0.003904384560883045  (0.005828257359098643)
     | > loss: 0.1849372833967209  (0.19369314717394964)
     | > align_error: 0.5663230419158936  (0.5941700626696859)

   --> STEP: 29
     | > decoder_loss: 0.4242500066757202  (0.4419485618328226)
     | > postnet_loss: 0.29190126061439514  (0.3082934731039508)
     | > stopnet_loss: 0.003491327865049243  (0.005747673583441767)
     | > loss: 0.18252913653850555  (0.19330818128996882)
     | > align_error: 0.5400550365447998  (0.5923040272860691)

   --> STEP: 30
     | > decoder_loss: 0.42518559098243713  (0.44138979613780976)
     | > postnet_loss: 0.2926821708679199  (0.30777309636274974)
     | > stopnet_loss: 0.0027472928632050753  (0.0056476608927672105)
     | > loss: 0.18221423029899597  (0.19293838292360305)
     | > align_error: 0.5327783823013306  (0.5903198391199111)

   --> STEP: 31
     | > decoder_loss: 0.41898027062416077  (0.44066690821801463)
     | > postnet_loss: 0.28945207595825195  (0.30718209570454014)
     | > stopnet_loss: 0.0036357559729367495  (0.005582760734063002)
     | > loss: 0.18074382841587067  (0.19254501019754716)
     | > align_error: 0.5538779199123383  (0.5891442933390217)

   --> STEP: 32
     | > decoder_loss: 0.4318595230579376  (0.4403916774317622)
     | > postnet_loss: 0.2963851988315582  (0.30684469267725945)
     | > stopnet_loss: 0.0037550043780356646  (0.005525643347937148)
     | > loss: 0.1858161836862564  (0.19233473436906934)
     | > align_error: 0.5303699374198914  (0.5873075947165489)

   --> STEP: 33
     | > decoder_loss: 0.4284866452217102  (0.44003091887994245)
     | > postnet_loss: 0.2938317060470581  (0.30645035974907153)
     | > stopnet_loss: 0.003987593576312065  (0.005479035779100024)
     | > loss: 0.1845671832561493  (0.19209935403231418)
     | > align_error: 0.546111524105072  (0.5860592289404436)

   --> STEP: 34
     | > decoder_loss: 0.43435102701187134  (0.4398638632367639)
     | > postnet_loss: 0.29537391662597656  (0.30612458201015696)
     | > stopnet_loss: 0.003208855865523219  (0.005412265781641883)
     | > loss: 0.1856400966644287  (0.1919093758744352)
     | > align_error: 0.5639064311981201  (0.5854076760656693)

   --> STEP: 35
     | > decoder_loss: 0.4331763684749603  (0.43967279195785525)
     | > postnet_loss: 0.2955428659915924  (0.30582224726676943)
     | > stopnet_loss: 0.0034729191102087498  (0.005356855876743794)
     | > loss: 0.1856527328491211  (0.19173061464514052)
     | > align_error: 0.5329675078392029  (0.5839093855449131)

   --> STEP: 36
     | > decoder_loss: 0.43808138370513916  (0.43962858617305756)
     | > postnet_loss: 0.29922378063201904  (0.30563895652691525)
     | > stopnet_loss: 0.0035994923673570156  (0.005308040223705272)
     | > loss: 0.187925785779953  (0.19162492495444086)
     | > align_error: 0.6334560215473175  (0.5852856809894244)

   --> STEP: 37
     | > decoder_loss: 0.43115371465682983  (0.4393995355915379)
     | > postnet_loss: 0.296004056930542  (0.30537855383512136)
     | > stopnet_loss: 0.0035000964999198914  (0.00525917687981918)
     | > loss: 0.18528953194618225  (0.19145369811637983)
     | > align_error: 0.5189107358455658  (0.5834917635531038)

   --> STEP: 38
     | > decoder_loss: 0.41811415553092957  (0.4388393940109956)
     | > postnet_loss: 0.28837236762046814  (0.3049310226189463)
     | > stopnet_loss: 0.0030839114915579557  (0.005201933053812306)
     | > loss: 0.17970554530620575  (0.19114453620032262)
     | > align_error: 0.5518505573272705  (0.5826591002313715)

   --> STEP: 39
     | > decoder_loss: 0.43521952629089355  (0.4387465768899673)
     | > postnet_loss: 0.2999129891395569  (0.30480235509383374)
     | > stopnet_loss: 0.0034004217013716698  (0.005155740455031777)
     | > loss: 0.18718354403972626  (0.19104297229876888)
     | > align_error: 0.5457247793674469  (0.5817120663630657)

   --> STEP: 40
     | > decoder_loss: 0.43218332529067993  (0.43858249559998513)
     | > postnet_loss: 0.2980709373950958  (0.3046340696513653)
     | > stopnet_loss: 0.002983092563226819  (0.0051014242577366534)
     | > loss: 0.1855466663837433  (0.19090556465089323)
     | > align_error: 0.5835241675376892  (0.5817573688924312)

   --> STEP: 41
     | > decoder_loss: 0.4209616482257843  (0.4381527188347607)
     | > postnet_loss: 0.28951844573020935  (0.30426539589719076)
     | > stopnet_loss: 0.003687389427796006  (0.005066935603347857)
     | > loss: 0.18130742013454437  (0.19067146356512862)
     | > align_error: 0.5021329820156097  (0.5798153106759234)

   --> STEP: 42
     | > decoder_loss: 0.42778515815734863  (0.4379058721519652)
     | > postnet_loss: 0.2926657199859619  (0.30398921313739957)
     | > stopnet_loss: 0.0032399387564510107  (0.005023435678421741)
     | > loss: 0.18335266411304474  (0.1904972064353171)
     | > align_error: 0.579338550567627  (0.5798039592447735)

   --> STEP: 43
     | > decoder_loss: 0.4260809123516083  (0.4376308730868406)
     | > postnet_loss: 0.29089295864105225  (0.303684649079345)
     | > stopnet_loss: 0.0028820126317441463  (0.004973635142452495)
     | > loss: 0.1821254938840866  (0.19030251544575358)
     | > align_error: 0.5512378215789795  (0.579139630461848)

   --> STEP: 44
     | > decoder_loss: 0.4444081783294678  (0.43778490275144577)
     | > postnet_loss: 0.30227914452552795  (0.303652705794031)
     | > stopnet_loss: 0.0026081602554768324  (0.004919874349566685)
     | > loss: 0.18927998840808868  (0.19027927619489757)
     | > align_error: 0.5511888265609741  (0.5785043849186464)

   --> STEP: 45
     | > decoder_loss: 0.43738505244255066  (0.43777601718902587)
     | > postnet_loss: 0.3012355864048004  (0.3035989920298258)
     | > stopnet_loss: 0.0032366164959967136  (0.004882468619487352)
     | > loss: 0.18789178133010864  (0.1902262207534578)
     | > align_error: 0.5522908866405487  (0.5779218627346887)

   --> STEP: 46
     | > decoder_loss: 0.4290374517440796  (0.4375860483750053)
     | > postnet_loss: 0.2931220233440399  (0.3033712318410044)
     | > stopnet_loss: 0.0031256128568202257  (0.004844276102907632)
     | > loss: 0.18366548418998718  (0.19008359604555627)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.4167059840578021 (+0.022330247994625185)
     | > avg_decoder_loss: 0.43409678520578326 (-0.001004650285749753)
     | > avg_postnet_loss: 0.3004055352825107 (-0.0016273120135972263)
     | > avg_stopnet_loss: 0.00429745694749396 (+1.4294845503613936e-05)
     | > avg_loss: 0.18792303741881342 (-0.0006436962972987681)
     | > avg_align_error: 0.5709911928032384 (+0.000449517008030198)

 > BEST MODEL : train_data\run-December-27-2025_08+25PM-0000000\best_model_26425.pth

 > EPOCH: 175/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 23:10:06)

   --> TIME: 2025-12-28 23:10:07 -- STEP: 0/150 -- GLOBAL_STEP: 26425
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4441450536251068  (0.4441450536251068)
     | > postnet_loss: 0.3824188709259033  (0.3824188709259033)
     | > stopnet_loss: 0.018924783915281296  (0.018924783915281296)
     | > loss: 0.22556577622890472  (0.22556577622890472)
     | > align_error: 0.7501164674758911  (0.7501164674758911)
     | > grad_norm: tensor(0.4191, device='cuda:0')  (tensor(0.4191, device='cuda:0'))
     | > step_time: 0.481  (0.48104238510131836)
     | > loader_time: 0.4016  (0.4016261100769043)


   --> TIME: 2025-12-28 23:10:45 -- STEP: 25/150 -- GLOBAL_STEP: 26450
     | > current_lr: 1e-05  (1.0000000000000003e-05)
     | > decoder_loss: 0.46898147463798523  (0.4620788872241974)
     | > postnet_loss: 0.3930566906929016  (0.39004859447479245)
     | > stopnet_loss: 0.006202287506312132  (0.009610285442322493)
     | > loss: 0.22171181440353394  (0.2226421570777893)
     | > align_error: 0.6173018515110016  (0.6703208494186401)
     | > grad_norm: tensor(0.3165, device='cuda:0')  (tensor(0.2883, device='cuda:0'))
     | > step_time: 0.936  (0.6692223167419433)
     | > loader_time: 0.9476  (0.8436071968078613)


   --> TIME: 2025-12-28 23:11:41 -- STEP: 50/150 -- GLOBAL_STEP: 26475
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.48458343744277954  (0.46921772658824923)
     | > postnet_loss: 0.3991369605064392  (0.392394580245018)
     | > stopnet_loss: 0.004207835532724857  (0.007484368709847334)
     | > loss: 0.22513793408870697  (0.22288744390010834)
     | > align_error: 0.632987380027771  (0.6473749041557313)
     | > grad_norm: tensor(0.1649, device='cuda:0')  (tensor(0.2525, device='cuda:0'))
     | > step_time: 1.2954  (0.8974874305725098)
     | > loader_time: 1.2408  (0.9687948894500732)


   --> TIME: 2025-12-28 23:12:54 -- STEP: 75/150 -- GLOBAL_STEP: 26500
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4745440185070038  (0.47242751200993854)
     | > postnet_loss: 0.38849911093711853  (0.3924237803618113)
     | > stopnet_loss: 0.0033000544644892216  (0.00636734739256402)
     | > loss: 0.21906083822250366  (0.22258017003536223)
     | > align_error: 0.6111560761928558  (0.6355720969041191)
     | > grad_norm: tensor(0.1361, device='cuda:0')  (tensor(0.2350, device='cuda:0'))
     | > step_time: 1.611  (1.1115583356221517)
     | > loader_time: 1.4128  (1.1059400463104248)


   --> TIME: 2025-12-28 23:14:23 -- STEP: 100/150 -- GLOBAL_STEP: 26525
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4721260070800781  (0.4737498036026955)
     | > postnet_loss: 0.3852507472038269  (0.3918072757124901)
     | > stopnet_loss: 0.003243742510676384  (0.005685652382671833)
     | > loss: 0.2175879329442978  (0.22207492142915725)
     | > align_error: 0.5826748609542847  (0.6302961942553522)
     | > grad_norm: tensor(0.2047, device='cuda:0')  (tensor(0.2215, device='cuda:0'))
     | > step_time: 1.8579  (1.2608560681343075)
     | > loader_time: 1.7755  (1.2911553049087525)


   --> TIME: 2025-12-28 23:15:59 -- STEP: 125/150 -- GLOBAL_STEP: 26550
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.47496363520622253  (0.4750427565574646)
     | > postnet_loss: 0.3849163055419922  (0.39151763010025026)
     | > stopnet_loss: 0.0031196619383990765  (0.005213985191658139)
     | > loss: 0.21808965504169464  (0.2218540815114975)
     | > align_error: 0.5897180438041687  (0.6263049862384799)
     | > grad_norm: tensor(0.2276, device='cuda:0')  (tensor(0.2270, device='cuda:0'))
     | > step_time: 2.0531  (1.3922464389801026)
     | > loader_time: 2.1196  (1.4204285430908203)


   --> TIME: 2025-12-28 23:18:01 -- STEP: 150/150 -- GLOBAL_STEP: 26575
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.48694896697998047  (0.47671076873938245)
     | > postnet_loss: 0.3945578932762146  (0.39159387528896333)
     | > stopnet_loss: 0.002428242703899741  (0.0048368288033331435)
     | > loss: 0.2228049635887146  (0.22191298971573512)
     | > align_error: 0.5852944254875183  (0.6229160320758823)
     | > grad_norm: tensor(0.4604, device='cuda:0')  (tensor(0.2240, device='cuda:0'))
     | > step_time: 7.7033  (1.6249392461776733)
     | > loader_time: 0.823  (1.5285456387201946)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45734381675720215  (0.45734381675720215)
     | > postnet_loss: 0.3345126509666443  (0.3345126509666443)
     | > stopnet_loss: 0.012137973681092262  (0.012137973681092262)
     | > loss: 0.21010209619998932  (0.21010209619998932)
     | > align_error: 0.7187089920043945  (0.7187089920043945)

   --> STEP: 1
     | > decoder_loss: 0.43883001804351807  (0.43883001804351807)
     | > postnet_loss: 0.3225964307785034  (0.3225964307785034)
     | > stopnet_loss: 0.009598644450306892  (0.009598644450306892)
     | > loss: 0.19995525479316711  (0.19995525479316711)
     | > align_error: 0.6589880585670471  (0.6589880585670471)

   --> STEP: 2
     | > decoder_loss: 0.43579524755477905  (0.43731263279914856)
     | > postnet_loss: 0.31324657797813416  (0.3179215043783188)
     | > stopnet_loss: 0.010885952971875668  (0.01024229871109128)
     | > loss: 0.19814640283584595  (0.19905082881450653)
     | > align_error: 0.6546849310398102  (0.6568364948034286)

   --> STEP: 3
     | > decoder_loss: 0.4402990937232971  (0.43830811977386475)
     | > postnet_loss: 0.3139345943927765  (0.316592534383138)
     | > stopnet_loss: 0.008149704895913601  (0.009544767439365387)
     | > loss: 0.19670812785625458  (0.1982699284950892)
     | > align_error: 0.7343133091926575  (0.6826620995998383)

   --> STEP: 4
     | > decoder_loss: 0.4411851465702057  (0.43902737647295)
     | > postnet_loss: 0.31918251514434814  (0.31724002957344055)
     | > stopnet_loss: 0.008198260329663754  (0.009208140661939979)
     | > loss: 0.1982901692390442  (0.19827498868107796)
     | > align_error: 0.6026023328304291  (0.662647157907486)

   --> STEP: 5
     | > decoder_loss: 0.42434602975845337  (0.43609110713005067)
     | > postnet_loss: 0.3022902011871338  (0.3142500638961792)
     | > stopnet_loss: 0.008066304959356785  (0.00897977352142334)
     | > loss: 0.1897253692150116  (0.19656506478786467)
     | > align_error: 0.6408736109733582  (0.6582924485206604)

   --> STEP: 6
     | > decoder_loss: 0.44278568029403687  (0.43720686932404834)
     | > postnet_loss: 0.3151003420352936  (0.31439177691936493)
     | > stopnet_loss: 0.007262287195771933  (0.008693525800481439)
     | > loss: 0.19673380255699158  (0.19659318774938583)
     | > align_error: 0.5931978225708008  (0.6474433441956838)

   --> STEP: 7
     | > decoder_loss: 0.45499274134635925  (0.43974770818437847)
     | > postnet_loss: 0.3152020275592804  (0.31450752701078144)
     | > stopnet_loss: 0.0061670709401369095  (0.008332603677575077)
     | > loss: 0.19871576130390167  (0.1968964125428881)
     | > align_error: 0.5781400203704834  (0.6375428693635123)

   --> STEP: 8
     | > decoder_loss: 0.4486168920993805  (0.44085635617375374)
     | > postnet_loss: 0.31581810116767883  (0.3146713487803936)
     | > stopnet_loss: 0.00724042858928442  (0.008196081791538745)
     | > loss: 0.19834917783737183  (0.19707800820469856)
     | > align_error: 0.5740926265716553  (0.6296115890145302)

   --> STEP: 9
     | > decoder_loss: 0.4471611976623535  (0.4415568941169315)
     | > postnet_loss: 0.31582334637641907  (0.31479934851328534)
     | > stopnet_loss: 0.006583208218216896  (0.008016873616725206)
     | > loss: 0.1973293423652649  (0.19710593422253928)
     | > align_error: 0.5904792547225952  (0.6252635518709818)

   --> STEP: 10
     | > decoder_loss: 0.46985355019569397  (0.44438655972480773)
     | > postnet_loss: 0.32896625995635986  (0.31621603965759276)
     | > stopnet_loss: 0.00560049619525671  (0.007775235874578357)
     | > loss: 0.20530544221401215  (0.19792588502168657)
     | > align_error: 0.5822019577026367  (0.6209573924541474)

   --> STEP: 11
     | > decoder_loss: 0.4561398923397064  (0.44545504450798035)
     | > postnet_loss: 0.31784307956695557  (0.31636395237662573)
     | > stopnet_loss: 0.0059323180466890335  (0.007607697890224782)
     | > loss: 0.19942806661128998  (0.19806244698437778)
     | > align_error: 0.5943782329559326  (0.6185411052270369)

   --> STEP: 12
     | > decoder_loss: 0.45452433824539185  (0.446210818986098)
     | > postnet_loss: 0.3129018545150757  (0.3160754442214966)
     | > stopnet_loss: 0.007834553718566895  (0.007626602542586625)
     | > loss: 0.19969110190868378  (0.19819816822806993)
     | > align_error: 0.5873102843761444  (0.6159385368227959)

   --> STEP: 13
     | > decoder_loss: 0.442227840423584  (0.4459044360197507)
     | > postnet_loss: 0.3116072118282318  (0.3157317340373993)
     | > stopnet_loss: 0.005275405943393707  (0.007445741265725631)
     | > loss: 0.19373416900634766  (0.19785478367255285)
     | > align_error: 0.5839245319366455  (0.6134759210623227)

   --> STEP: 14
     | > decoder_loss: 0.45711806416511536  (0.44670540945870535)
     | > postnet_loss: 0.3172447681427002  (0.3158398079020636)
     | > stopnet_loss: 0.00489926990121603  (0.007263850453974945)
     | > loss: 0.1984899640083313  (0.19790015369653702)
     | > align_error: 0.5543714761734009  (0.6092541749988284)

   --> STEP: 15
     | > decoder_loss: 0.45081356167793274  (0.4469792862733205)
     | > postnet_loss: 0.31342843174934387  (0.3156790494918823)
     | > stopnet_loss: 0.004934386815875769  (0.007108552878101667)
     | > loss: 0.19599488377571106  (0.1977731357018153)
     | > align_error: 0.5876039862632751  (0.6078108290831248)

   --> STEP: 16
     | > decoder_loss: 0.4521845281124115  (0.4473046138882637)
     | > postnet_loss: 0.30830132961273193  (0.3152179419994354)
     | > stopnet_loss: 0.005260300822556019  (0.006993037124630064)
     | > loss: 0.1953817754983902  (0.19762367568910122)
     | > align_error: 0.6052639484405518  (0.607651649042964)

   --> STEP: 17
     | > decoder_loss: 0.46015140414237976  (0.4480603074326235)
     | > postnet_loss: 0.3173865079879761  (0.3153455047046437)
     | > stopnet_loss: 0.00476703979074955  (0.006862096104990034)
     | > loss: 0.19915153086185455  (0.1977135495227926)
     | > align_error: 0.5579642057418823  (0.6047288582605475)

   --> STEP: 18
     | > decoder_loss: 0.45165181159973145  (0.44825983544190723)
     | > postnet_loss: 0.3079241216182709  (0.31493320564428967)
     | > stopnet_loss: 0.005183289293199778  (0.006768829059890575)
     | > loss: 0.19507728517055511  (0.19756709039211273)
     | > align_error: 0.6035299897193909  (0.6046622544527054)

   --> STEP: 19
     | > decoder_loss: 0.4482506811618805  (0.4482593536376953)
     | > postnet_loss: 0.30739179253578186  (0.3145362891648945)
     | > stopnet_loss: 0.004680110607296228  (0.006658896509754031)
     | > loss: 0.19359073042869568  (0.197357808288775)
     | > align_error: 0.5985583961009979  (0.6043409987499839)

   --> STEP: 20
     | > decoder_loss: 0.4460970461368561  (0.44815123826265335)
     | > postnet_loss: 0.3038174510002136  (0.3140003472566605)
     | > stopnet_loss: 0.004479205701500177  (0.0065499119693413375)
     | > loss: 0.19195783138275146  (0.19708780944347382)
     | > align_error: 0.6224155426025391  (0.6052447259426117)

   --> STEP: 21
     | > decoder_loss: 0.4437143802642822  (0.44793995931034997)
     | > postnet_loss: 0.3036055564880371  (0.31350535722005934)
     | > stopnet_loss: 0.003917875699698925  (0.006424576908882175)
     | > loss: 0.19074785709381104  (0.19678590695063272)
     | > align_error: 0.5589390397071838  (0.6030396932647342)

   --> STEP: 22
     | > decoder_loss: 0.44615116715431213  (0.4478586505759846)
     | > postnet_loss: 0.3059919476509094  (0.3131638386032798)
     | > stopnet_loss: 0.004771792329847813  (0.006349450337107886)
     | > loss: 0.19280758500099182  (0.19660507413473996)
     | > align_error: 0.6247096061706543  (0.6040246893059124)

   --> STEP: 23
     | > decoder_loss: 0.4196297824382782  (0.44663130848304083)
     | > postnet_loss: 0.29371991753578186  (0.3123184507307799)
     | > stopnet_loss: 0.004451235290616751  (0.006266919248130011)
     | > loss: 0.1827886551618576  (0.19600436026635376)
     | > align_error: 0.5665193200111389  (0.6023940210757048)

   --> STEP: 24
     | > decoder_loss: 0.4529934823513031  (0.44689639906088513)
     | > postnet_loss: 0.30905741453170776  (0.31218257422248524)
     | > stopnet_loss: 0.004368561320006847  (0.0061878210011248784)
     | > loss: 0.19488127529621124  (0.1959575650592645)
     | > align_error: 0.5789215862751007  (0.601416002959013)

   --> STEP: 25
     | > decoder_loss: 0.45201435685157776  (0.4471011173725128)
     | > postnet_loss: 0.3063078224658966  (0.3119475841522217)
     | > stopnet_loss: 0.003684644354507327  (0.0060876939352601765)
     | > loss: 0.1932651847600937  (0.19584986984729766)
     | > align_error: 0.5570096671581268  (0.5996397495269775)

   --> STEP: 26
     | > decoder_loss: 0.42759883403778076  (0.4463510295519462)
     | > postnet_loss: 0.2954607307910919  (0.31131347440756285)
     | > stopnet_loss: 0.0042914641089737415  (0.006018608172710698)
     | > loss: 0.18505634367465973  (0.19543473422527313)
     | > align_error: 0.5459859371185303  (0.5975761413574219)

   --> STEP: 27
     | > decoder_loss: 0.42433807253837585  (0.4455357348477399)
     | > postnet_loss: 0.2900289297103882  (0.3105251579372971)
     | > stopnet_loss: 0.003591480664908886  (0.0059287145613106315)
     | > loss: 0.18218323588371277  (0.19494393799040052)
     | > align_error: 0.5391231775283813  (0.5954112167711612)

   --> STEP: 28
     | > decoder_loss: 0.43008601665496826  (0.44498395919799805)
     | > postnet_loss: 0.29494211077690125  (0.30996862053871155)
     | > stopnet_loss: 0.003924093209207058  (0.005857120941592646)
     | > loss: 0.185181125998497  (0.19459526613354683)
     | > align_error: 0.5657334923744202  (0.594351298042706)

   --> STEP: 29
     | > decoder_loss: 0.42576339840888977  (0.44432118123975295)
     | > postnet_loss: 0.2919662892818451  (0.30934785049537133)
     | > stopnet_loss: 0.0035271572414785624  (0.005776777365726644)
     | > loss: 0.18295958638191223  (0.19419403579728356)
     | > align_error: 0.5397520661354065  (0.5924685659079716)

   --> STEP: 30
     | > decoder_loss: 0.42569559812545776  (0.44370032846927643)
     | > postnet_loss: 0.2923327088356018  (0.30878067910671236)
     | > stopnet_loss: 0.0027493813540786505  (0.005675864165338377)
     | > loss: 0.18225646018981934  (0.19379611661036808)
     | > align_error: 0.5324549674987793  (0.5904681126276652)

   --> STEP: 31
     | > decoder_loss: 0.41990214586257935  (0.44293264515938296)
     | > postnet_loss: 0.28941741585731506  (0.3081560577115705)
     | > stopnet_loss: 0.00366018433123827  (0.0056108422352061154)
     | > loss: 0.1809900850057602  (0.19338301881667105)
     | > align_error: 0.5533129572868347  (0.5892695592295739)

   --> STEP: 32
     | > decoder_loss: 0.43554964661598206  (0.4427019264549017)
     | > postnet_loss: 0.29800745844841003  (0.30783891398459673)
     | > stopnet_loss: 0.0037794297095388174  (0.0055536105937790126)
     | > loss: 0.18716870248317719  (0.19318882143124938)
     | > align_error: 0.5304455757141113  (0.5874313097447157)

   --> STEP: 33
     | > decoder_loss: 0.4306979477405548  (0.44233816952416394)
     | > postnet_loss: 0.29438701272010803  (0.30743128061294556)
     | > stopnet_loss: 0.003990176599472761  (0.0055062338060727625)
     | > loss: 0.18526141345500946  (0.1929485969471209)
     | > align_error: 0.5453813076019287  (0.5861570672555403)

   --> STEP: 34
     | > decoder_loss: 0.4363766610622406  (0.4421628310399897)
     | > postnet_loss: 0.29589173197746277  (0.30709188212366667)
     | > stopnet_loss: 0.0032515423372387886  (0.005439919351107057)
     | > loss: 0.18631863594055176  (0.1927535980939865)
     | > align_error: 0.5631749629974365  (0.5854811230126549)

   --> STEP: 35
     | > decoder_loss: 0.43373769521713257  (0.4419221128736224)
     | > postnet_loss: 0.2953176498413086  (0.30675547548702786)
     | > stopnet_loss: 0.003477586666122079  (0.00538385270296463)
     | > loss: 0.18574142456054688  (0.19255325027874537)
     | > align_error: 0.532203733921051  (0.583958911895752)

   --> STEP: 36
     | > decoder_loss: 0.4400501549243927  (0.4418701140416993)
     | > postnet_loss: 0.2996605932712555  (0.30655839542547864)
     | > stopnet_loss: 0.003610646352171898  (0.005334596970998164)
     | > loss: 0.1885383278131485  (0.19244172465470102)
     | > align_error: 0.6329284310340881  (0.5853191763162613)

   --> STEP: 37
     | > decoder_loss: 0.4325869381427765  (0.44161921739578247)
     | > postnet_loss: 0.29611527919769287  (0.30627614904094386)
     | > stopnet_loss: 0.0035029978025704622  (0.005285094290770389)
     | > loss: 0.18567854166030884  (0.19225893592512286)
     | > align_error: 0.5181630253791809  (0.5835041452098537)

   --> STEP: 38
     | > decoder_loss: 0.41942235827445984  (0.4410350895241687)
     | > postnet_loss: 0.2883634567260742  (0.3058047624010789)
     | > stopnet_loss: 0.003092730650678277  (0.005227400510767965)
     | > loss: 0.1800391972064972  (0.19193736385358007)
     | > align_error: 0.5507936477661133  (0.5826433426455447)

   --> STEP: 39
     | > decoder_loss: 0.43599408864974976  (0.4409058330914913)
     | > postnet_loss: 0.2999410629272461  (0.30565441113251907)
     | > stopnet_loss: 0.003420711262151599  (0.005181075145418828)
     | > loss: 0.18740449845790863  (0.19182113653574234)
     | > align_error: 0.5451341867446899  (0.5816815694173177)

   --> STEP: 40
     | > decoder_loss: 0.43243247270584106  (0.44069399908185003)
     | > postnet_loss: 0.29771900177001953  (0.30545602589845655)
     | > stopnet_loss: 0.0029974894132465124  (0.00512648550211452)
     | > loss: 0.18553535640239716  (0.19166399203240872)
     | > align_error: 0.5827683508396149  (0.5817087389528751)

   --> STEP: 41
     | > decoder_loss: 0.4226419925689697  (0.4402537062400725)
     | > postnet_loss: 0.2900312542915344  (0.3050798119568243)
     | > stopnet_loss: 0.0036915938835591078  (0.005091488145564389)
     | > loss: 0.18185991048812866  (0.19142486809230433)
     | > align_error: 0.5015427470207214  (0.5797534708569689)

   --> STEP: 42
     | > decoder_loss: 0.42901378870010376  (0.4399860891557875)
     | > postnet_loss: 0.2926994860172272  (0.3047850422915958)
     | > stopnet_loss: 0.0032251793891191483  (0.005047052222791883)
     | > loss: 0.18365350365638733  (0.19123983560573488)
     | > align_error: 0.5785356163978577  (0.5797244743222282)

   --> STEP: 43
     | > decoder_loss: 0.42691442370414734  (0.4396820969359819)
     | > postnet_loss: 0.2906607389450073  (0.30445657012074495)
     | > stopnet_loss: 0.0029101124964654446  (0.004997355950086617)
     | > loss: 0.18230390548706055  (0.1910320232773936)
     | > align_error: 0.550574779510498  (0.5790465744428857)

   --> STEP: 44
     | > decoder_loss: 0.44527384638786316  (0.4398091821507974)
     | > postnet_loss: 0.3021499514579773  (0.30440414696931845)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.38706069281606964 (-0.029645291241732485)
     | > avg_decoder_loss: 0.4355922237490163 (+0.0014954385432330297)
     | > avg_postnet_loss: 0.3008454961307121 (+0.000439960848201415)
     | > avg_stopnet_loss: 0.0043205942104881006 (+2.3137262994140685e-05)
     | > avg_loss: 0.1884300232385144 (+0.0005069858197009891)
     | > avg_align_error: 0.5706505314870314 (-0.0003406613162070249)


 > EPOCH: 176/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 23:19:47)

   --> TIME: 2025-12-28 23:20:20 -- STEP: 24/150 -- GLOBAL_STEP: 26600
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.471405953168869  (0.46104441583156586)
     | > postnet_loss: 0.395737886428833  (0.3895092122256756)
     | > stopnet_loss: 0.006128084380179644  (0.009790782545072338)
     | > loss: 0.22291405498981476  (0.22242918921013674)
     | > align_error: 0.6912891864776611  (0.6709716046849886)
     | > grad_norm: tensor(0.4367, device='cuda:0')  (tensor(0.2847, device='cuda:0'))
     | > step_time: 0.9476  (0.6116109291712444)
     | > loader_time: 1.067  (0.7373664180437723)


   --> TIME: 2025-12-28 23:21:18 -- STEP: 49/150 -- GLOBAL_STEP: 26625
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.4761362671852112  (0.4683884655942722)
     | > postnet_loss: 0.3918132185935974  (0.3919835212279339)
     | > stopnet_loss: 0.00456616934388876  (0.007579642519050712)
     | > loss: 0.22155353426933289  (0.22267263945268126)
     | > align_error: 0.5812546014785767  (0.6464275942773237)
     | > grad_norm: tensor(0.1475, device='cuda:0')  (tensor(0.2660, device='cuda:0'))
     | > step_time: 1.3483  (0.862602559887633)
     | > loader_time: 1.5849  (0.9683700580986179)


   --> TIME: 2025-12-28 23:22:32 -- STEP: 74/150 -- GLOBAL_STEP: 26650
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.47922173142433167  (0.47194050051070546)
     | > postnet_loss: 0.39113664627075195  (0.39215955379846934)
     | > stopnet_loss: 0.0036999108269810677  (0.006420501794137462)
     | > loss: 0.2212895005941391  (0.22244551455652392)
     | > align_error: 0.6008733510971069  (0.6349908496076997)
     | > grad_norm: tensor(0.1763, device='cuda:0')  (tensor(0.2400, device='cuda:0'))
     | > step_time: 1.5468  (1.0538149621035602)
     | > loader_time: 1.6479  (1.1628085374832156)


   --> TIME: 2025-12-28 23:23:59 -- STEP: 99/150 -- GLOBAL_STEP: 26675
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.48360729217529297  (0.47351770599683124)
     | > postnet_loss: 0.3925378620624542  (0.39168711623760183)
     | > stopnet_loss: 0.003338201902806759  (0.0057264928461400535)
     | > loss: 0.22237448394298553  (0.22202769734642722)
     | > align_error: 0.6016297936439514  (0.6300835603415366)
     | > grad_norm: tensor(0.1938, device='cuda:0')  (tensor(0.2341, device='cuda:0'))
     | > step_time: 1.678  (1.208443694644504)
     | > loader_time: 1.5844  (1.3241434723439842)


   --> TIME: 2025-12-28 23:25:38 -- STEP: 124/150 -- GLOBAL_STEP: 26700
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.4768446981906891  (0.47468238299892795)
     | > postnet_loss: 0.38738182187080383  (0.39130651494187696)
     | > stopnet_loss: 0.0034034892451018095  (0.005243044772801259)
     | > loss: 0.2194601148366928  (0.22174026853134554)
     | > align_error: 0.6130103468894958  (0.6260460257049529)
     | > grad_norm: tensor(0.2103, device='cuda:0')  (tensor(0.2363, device='cuda:0'))
     | > step_time: 2.1026  (1.367900671497468)
     | > loader_time: 1.6689  (1.447369231331733)


   --> TIME: 2025-12-28 23:27:40 -- STEP: 149/150 -- GLOBAL_STEP: 26725
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.5079638957977295  (0.47628605225742265)
     | > postnet_loss: 0.4070979654788971  (0.3912977888280113)
     | > stopnet_loss: 0.002521247137337923  (0.004869253338695872)
     | > loss: 0.23128670454025269  (0.22176521296469157)
     | > align_error: 0.6240364909172058  (0.6227609511189813)
     | > grad_norm: tensor(0.2214, device='cuda:0')  (tensor(0.2289, device='cuda:0'))
     | > step_time: 10.6992  (1.5806019130169144)
     | > loader_time: 2.456  (1.5866716452092933)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.45612818002700806  (0.45612818002700806)
     | > postnet_loss: 0.33174121379852295  (0.33174121379852295)
     | > stopnet_loss: 0.012073787860572338  (0.012073787860572338)
     | > loss: 0.20904113352298737  (0.20904113352298737)
     | > align_error: 0.7189884185791016  (0.7189884185791016)

   --> STEP: 1
     | > decoder_loss: 0.4375850558280945  (0.4375850558280945)
     | > postnet_loss: 0.31951239705085754  (0.31951239705085754)
     | > stopnet_loss: 0.009626038372516632  (0.009626038372516632)
     | > loss: 0.19890040159225464  (0.19890040159225464)
     | > align_error: 0.6589670181274414  (0.6589670181274414)

   --> STEP: 2
     | > decoder_loss: 0.43441683053970337  (0.4360009431838989)
     | > postnet_loss: 0.3109133839607239  (0.3152128905057907)
     | > stopnet_loss: 0.010937809012830257  (0.010281923692673445)
     | > loss: 0.19727036356925964  (0.19808538258075714)
     | > align_error: 0.6548091769218445  (0.6568880975246429)

   --> STEP: 3
     | > decoder_loss: 0.4396456778049469  (0.43721585472424823)
     | > postnet_loss: 0.31139877438545227  (0.3139415184656779)
     | > stopnet_loss: 0.008121156133711338  (0.009561667839686075)
     | > loss: 0.19588227570056915  (0.1973510136206945)
     | > align_error: 0.7343807816505432  (0.6827189922332764)

   --> STEP: 4
     | > decoder_loss: 0.44103339314460754  (0.4381702393293381)
     | > postnet_loss: 0.31717056035995483  (0.31474877893924713)
     | > stopnet_loss: 0.008183632045984268  (0.009217158891260624)
     | > loss: 0.19773462414741516  (0.19744691625237465)
     | > align_error: 0.6027825176715851  (0.6627348735928535)

   --> STEP: 5
     | > decoder_loss: 0.42323535680770874  (0.4351832628250122)
     | > postnet_loss: 0.29987627267837524  (0.3117742776870728)
     | > stopnet_loss: 0.008031949400901794  (0.008980116993188857)
     | > loss: 0.1888098567724228  (0.19571950435638427)
     | > align_error: 0.6409653127193451  (0.6583809614181518)

   --> STEP: 6
     | > decoder_loss: 0.4423462450504303  (0.4363770931959152)
     | > postnet_loss: 0.31267842650413513  (0.31192496915658313)
     | > stopnet_loss: 0.007239379920065403  (0.008689994147668282)
     | > loss: 0.19599555432796478  (0.19576551268498102)
     | > align_error: 0.593093752861023  (0.6474997599919637)

   --> STEP: 7
     | > decoder_loss: 0.45450490713119507  (0.4389667809009552)
     | > postnet_loss: 0.3135376572608948  (0.3121553531714848)
     | > stopnet_loss: 0.0061153206042945385  (0.008322183641472034)
     | > loss: 0.198125958442688  (0.1961027192217963)
     | > align_error: 0.5782419443130493  (0.6376057863235474)

   --> STEP: 8
     | > decoder_loss: 0.4499613642692566  (0.4403411038219929)
     | > postnet_loss: 0.31486400961875916  (0.3124939352273941)
     | > stopnet_loss: 0.007488430943340063  (0.008217964554205537)
     | > loss: 0.19869476556777954  (0.1964267250150442)
     | > align_error: 0.5747777819633484  (0.6297522857785225)

   --> STEP: 9
     | > decoder_loss: 0.44599127769470215  (0.44096890091896057)
     | > postnet_loss: 0.3135899305343628  (0.31261571248372394)
     | > stopnet_loss: 0.00662419805303216  (0.008040879387408495)
     | > loss: 0.19651949405670166  (0.1964370326863395)
     | > align_error: 0.5903252363204956  (0.6253715025054084)

   --> STEP: 10
     | > decoder_loss: 0.4690166711807251  (0.443773677945137)
     | > postnet_loss: 0.32639893889427185  (0.31399403512477875)
     | > stopnet_loss: 0.00555693544447422  (0.007792484993115067)
     | > loss: 0.2044108510017395  (0.19723441451787949)
     | > align_error: 0.5827621817588806  (0.6211105704307556)

   --> STEP: 11
     | > decoder_loss: 0.45556387305259705  (0.444845513863997)
     | > postnet_loss: 0.31618377566337585  (0.3141931024464694)
     | > stopnet_loss: 0.0059194802306592464  (0.007622211832891811)
     | > loss: 0.1988563984632492  (0.19738186760382218)
     | > align_error: 0.5944831371307373  (0.6186898946762085)

   --> STEP: 12
     | > decoder_loss: 0.45196887850761414  (0.44543912758429843)
     | > postnet_loss: 0.3098706007003784  (0.31383289396762853)
     | > stopnet_loss: 0.007836764678359032  (0.007640091236680746)
     | > loss: 0.19829663634300232  (0.1974580983320872)
     | > align_error: 0.586762398481369  (0.6160292699933052)

   --> STEP: 13
     | > decoder_loss: 0.4421536326408386  (0.4451863972040323)
     | > postnet_loss: 0.3098798096179962  (0.31352881055611836)
     | > stopnet_loss: 0.005244147498160601  (0.007455787872179196)
     | > loss: 0.19325251877307892  (0.19713459221216348)
     | > align_error: 0.5838998258113861  (0.6135577742870038)

   --> STEP: 14
     | > decoder_loss: 0.4575527608394623  (0.4460697088922773)
     | > postnet_loss: 0.316285103559494  (0.31372568862778805)
     | > stopnet_loss: 0.004883532412350178  (0.007272055339334267)
     | > loss: 0.19834299385547638  (0.19722090661525726)
     | > align_error: 0.5540654063224792  (0.6093083194323948)

   --> STEP: 15
     | > decoder_loss: 0.4511646628379822  (0.44640937248865764)
     | > postnet_loss: 0.31258708238601685  (0.31364978154500334)
     | > stopnet_loss: 0.004956139717251062  (0.0071176609645287195)
     | > loss: 0.19589407742023468  (0.1971324513355891)
     | > align_error: 0.5878866016864777  (0.6078802049160004)

   --> STEP: 16
     | > decoder_loss: 0.45203474164009094  (0.4467609580606222)
     | > postnet_loss: 0.3070293068885803  (0.3132360018789769)
     | > stopnet_loss: 0.005250987131148577  (0.007000993849942461)
     | > loss: 0.195017009973526  (0.19700023625046015)
     | > align_error: 0.6050775051116943  (0.6077050361782312)

   --> STEP: 17
     | > decoder_loss: 0.45928695797920227  (0.44749778158524456)
     | > postnet_loss: 0.3160640597343445  (0.3134023582234103)
     | > stopnet_loss: 0.004753285087645054  (0.006868775687454378)
     | > loss: 0.19859105348587036  (0.19709381373489604)
     | > align_error: 0.5579537451267242  (0.6047784896457896)

   --> STEP: 18
     | > decoder_loss: 0.4511588215827942  (0.44770117269621956)
     | > postnet_loss: 0.30668899416923523  (0.3130293935537339)
     | > stopnet_loss: 0.005196518264710903  (0.006775872497301962)
     | > loss: 0.19465845823287964  (0.19695851620700625)
     | > align_error: 0.6035606265068054  (0.6047108305825127)

   --> STEP: 19
     | > decoder_loss: 0.4468638300895691  (0.44765710203271164)
     | > postnet_loss: 0.30555620789527893  (0.31263606799276256)
     | > stopnet_loss: 0.004682398866862059  (0.006665689674647231)
     | > loss: 0.19278740882873535  (0.19673898423972883)
     | > align_error: 0.5983124077320099  (0.6043740714851179)

   --> STEP: 20
     | > decoder_loss: 0.44570642709732056  (0.44755956828594207)
     | > postnet_loss: 0.3030519187450409  (0.3121568605303765)
     | > stopnet_loss: 0.004434239584952593  (0.006554117170162499)
     | > loss: 0.19162382185459137  (0.19648322612047195)
     | > align_error: 0.6224628686904907  (0.6052785113453865)

   --> STEP: 21
     | > decoder_loss: 0.4428291320800781  (0.44733430941899616)
     | > postnet_loss: 0.30204862356185913  (0.31167551591282805)
     | > stopnet_loss: 0.0038979065138846636  (0.006427630948434983)
     | > loss: 0.19011734426021576  (0.19618008888903118)
     | > align_error: 0.5589934289455414  (0.6030744598025367)

   --> STEP: 22
     | > decoder_loss: 0.4458858072757721  (0.44726846841248596)
     | > postnet_loss: 0.3050326406955719  (0.3113735670393164)
     | > stopnet_loss: 0.00481619406491518  (0.006354383817365901)
     | > loss: 0.1925458014011383  (0.19601489400321787)
     | > align_error: 0.6248836815357208  (0.604065788063136)

   --> STEP: 23
     | > decoder_loss: 0.4189454913139343  (0.44603703462559247)
     | > postnet_loss: 0.2925835847854614  (0.3105566112891488)
     | > stopnet_loss: 0.004452136345207691  (0.006271677405532935)
     | > loss: 0.18233440816402435  (0.195420090271079)
     | > align_error: 0.5666038990020752  (0.6024370102778726)

   --> STEP: 24
     | > decoder_loss: 0.45310407876968384  (0.4463314947982629)
     | > postnet_loss: 0.30851688981056213  (0.31047162289420766)
     | > stopnet_loss: 0.004374786280095577  (0.0061926402753063785)
     | > loss: 0.19478003680706024  (0.1953934213767449)
     | > align_error: 0.5790242552757263  (0.6014614788194498)

   --> STEP: 25
     | > decoder_loss: 0.4518420696258545  (0.4465519177913666)
     | > postnet_loss: 0.30539631843566895  (0.3102686107158661)
     | > stopnet_loss: 0.003676486434414983  (0.006091994121670723)
     | > loss: 0.19298608601093292  (0.19529712796211243)
     | > align_error: 0.5571622252464294  (0.5996895086765289)

   --> STEP: 26
     | > decoder_loss: 0.4268438518047333  (0.44579391525341916)
     | > postnet_loss: 0.29417431354522705  (0.30964959928622615)
     | > stopnet_loss: 0.004265362862497568  (0.006021739073240986)
     | > loss: 0.1845199167728424  (0.19488261983944818)
     | > align_error: 0.5460638999938965  (0.5976269852656585)

   --> STEP: 27
     | > decoder_loss: 0.4243497848510742  (0.44499968820148045)
     | > postnet_loss: 0.2893233299255371  (0.3088967744950895)
     | > stopnet_loss: 0.0038819615729153156  (0.005942488054710406)
     | > loss: 0.18230023980140686  (0.1944166057639652)
     | > align_error: 0.5402629375457764  (0.5955023909056628)

   --> STEP: 28
     | > decoder_loss: 0.429828405380249  (0.44445785667215076)
     | > postnet_loss: 0.29412195086479187  (0.30836910222257885)
     | > stopnet_loss: 0.003918651957064867  (0.005870208194080208)
     | > loss: 0.1849062442779541  (0.19407694999660766)
     | > align_error: 0.5657533407211304  (0.5944399248276439)

   --> STEP: 29
     | > decoder_loss: 0.42537418007850647  (0.4437997988585768)
     | > postnet_loss: 0.29086530208587646  (0.3077655229075202)
     | > stopnet_loss: 0.0035309181548655033  (0.005789543020314184)
     | > loss: 0.1825907826423645  (0.19368087526025443)
     | > align_error: 0.540009617805481  (0.5925630176889485)

   --> STEP: 30
     | > decoder_loss: 0.42582908272743225  (0.4432007749875387)
     | > postnet_loss: 0.29172617197036743  (0.3072308778762817)
     | > stopnet_loss: 0.002761316951364279  (0.005688602151349187)
     | > loss: 0.18215014040470123  (0.19329651743173598)
     | > align_error: 0.5327647030353546  (0.5905697405338287)

   --> STEP: 31
     | > decoder_loss: 0.42050400376319885  (0.4424686210770761)
     | > postnet_loss: 0.28907397389411926  (0.306645171296212)
     | > stopnet_loss: 0.003657102584838867  (0.005623069907268209)
     | > loss: 0.1810515969991684  (0.19290151999842736)
     | > align_error: 0.5539111196994781  (0.589387204377882)

   --> STEP: 32
     | > decoder_loss: 0.4353543221950531  (0.44224629923701286)
     | > postnet_loss: 0.2970901131629944  (0.30634657572954893)
     | > stopnet_loss: 0.0037779000122100115  (0.00556540834804764)
     | > loss: 0.18688900768756866  (0.19271362898871303)
     | > align_error: 0.5302154719829559  (0.5875380877405405)

   --> STEP: 33
     | > decoder_loss: 0.4302137792110443  (0.4418816774180441)
     | > postnet_loss: 0.2937149405479431  (0.3059637989058639)
     | > stopnet_loss: 0.0039826929569244385  (0.005517447275589361)
     | > loss: 0.1849648654460907  (0.19247881797226993)
     | > align_error: 0.545314371585846  (0.5862585811903982)

   --> STEP: 34
     | > decoder_loss: 0.4360494911670685  (0.44171014252830954)
     | > postnet_loss: 0.29517242312431335  (0.3056464055005242)
     | > stopnet_loss: 0.0032398169860243797  (0.005450458149425685)
     | > loss: 0.18604528903961182  (0.1922895965330741)
     | > align_error: 0.5631138682365417  (0.5855778543388143)

   --> STEP: 35
     | > decoder_loss: 0.43339911103248596  (0.4414726844855717)
     | > postnet_loss: 0.29438018798828125  (0.30532451357160295)
     | > stopnet_loss: 0.003474504454061389  (0.005394002329558134)
     | > loss: 0.18541932106018066  (0.1920933029481343)
     | > align_error: 0.5322426557540894  (0.5840539915221078)

   --> STEP: 36
     | > decoder_loss: 0.439668208360672  (0.4414225601487689)
     | > postnet_loss: 0.29891982674598694  (0.30514660560422474)
     | > stopnet_loss: 0.0036155858542770147  (0.005344601871911436)
     | > loss: 0.18826259672641754  (0.19198689444197548)
     | > align_error: 0.6330326199531555  (0.5854145089785258)

   --> STEP: 37
     | > decoder_loss: 0.4320521950721741  (0.4411693070385907)
     | > postnet_loss: 0.2951769232749939  (0.30487715473046173)
     | > stopnet_loss: 0.003508510999381542  (0.005294977794275494)
     | > loss: 0.1853157877922058  (0.191806594262252)
     | > align_error: 0.5180577039718628  (0.5835940547891565)

   --> STEP: 38
     | > decoder_loss: 0.4188162684440613  (0.44058106918083995)
     | > postnet_loss: 0.28742119669914246  (0.30441778741384806)
     | > stopnet_loss: 0.0030944389291107655  (0.005237068876771159)
     | > loss: 0.17965379357337952  (0.19148678371780797)
     | > align_error: 0.550889790058136  (0.5827334162436033)

   --> STEP: 39
     | > decoder_loss: 0.4359588027000427  (0.44046254952748615)
     | > postnet_loss: 0.29906609654426575  (0.30428056457103825)
     | > stopnet_loss: 0.0034249299205839634  (0.0051906037753304615)
     | > loss: 0.18718115985393524  (0.1913763831059138)
     | > align_error: 0.5451719760894775  (0.5817703023934976)

   --> STEP: 40
     | > decoder_loss: 0.4318925440311432  (0.4402482993900776)
     | > postnet_loss: 0.29663941264152527  (0.30408953577280046)
     | > stopnet_loss: 0.0029840138740837574  (0.0051354390277992944)
     | > loss: 0.18511700630187988  (0.19121989868581296)
     | > align_error: 0.5828604996204376  (0.581797557324171)

   --> STEP: 41
     | > decoder_loss: 0.4223254919052124  (0.4398111577441053)
     | > postnet_loss: 0.28907036781311035  (0.3037232146030519)
     | > stopnet_loss: 0.0036988696083426476  (0.005100400749275962)
     | > loss: 0.1815478354692459  (0.19098399470492108)
     | > align_error: 0.5017291307449341  (0.5798446688710189)

   --> STEP: 42
     | > decoder_loss: 0.4293823540210724  (0.43956285289355684)
     | > postnet_loss: 0.2924492359161377  (0.30345478653907776)
     | > stopnet_loss: 0.0032440009526908398  (0.005056200754119174)
     | > loss: 0.18370188772678375  (0.1908106112054416)
     | > align_error: 0.5784926414489746  (0.5798124777419227)

   --> STEP: 43
     | > decoder_loss: 0.4265718460083008  (0.43926073645436486)
     | > postnet_loss: 0.29006946086883545  (0.30314349989558376)
     | > stopnet_loss: 0.002881963038817048  (0.005005637086321449)
     | > loss: 0.18204228579998016  (0.19060669666112856)
     | > align_error: 0.5507981777191162  (0.5791377265786015)

   --> STEP: 44
     | > decoder_loss: 0.44474098086357117  (0.439385287463665)
     | > postnet_loss: 0.3012855350971222  (0.30310127342289145)
     | > stopnet_loss: 0.002618045313283801  (0.00495137363693423)
     | > loss: 0.1891246736049652  (0.19057301431894302)
     | > align_error: 0.5501115620136261  (0.5784780410203066)

   --> STEP: 45
     | > decoder_loss: 0.4385804235935211  (0.439367401599884)
     | > postnet_loss: 0.3007655143737793  (0.3030493676662445)
     | > stopnet_loss: 0.0032581291161477566  (0.004913745980916753)
     | > loss: 0.1880946010351181  (0.19051793846819137)
     | > align_error: 0.5514748096466064  (0.5778779692120022)

   --> STEP: 46
     | > decoder_loss: 0.4287770986557007  (0.43913717762283655)
     | > postnet_loss: 0.2918964624404907  (0.30280691320481506)
     | > stopnet_loss: 0.0031545942183583975  (0.004875503551295919)

warning: audio amplitude out of range, auto clipped.
warning: audio amplitude out of range, auto clipped.

  --> EVAL PERFORMANCE
     | > avg_loader_time: 0.37994635105133057 (-0.007114341764739074)
     | > avg_decoder_loss: 0.43524411636771576 (-0.0003481073813005331)
     | > avg_postnet_loss: 0.2996396314014089 (-0.0012058647293031743)
     | > avg_stopnet_loss: 0.004325590710240332 (+4.9964997522310844e-06)
     | > avg_loss: 0.1880465274055799 (-0.0003834958329345106)
     | > avg_align_error: 0.5707409806323774 (+9.044914534606097e-05)


 > EPOCH: 177/999
 --> train_data\run-December-27-2025_08+25PM-0000000

 > TRAINING (2025-12-28 23:29:40)

   --> TIME: 2025-12-28 23:30:13 -- STEP: 23/150 -- GLOBAL_STEP: 26750
     | > current_lr: 1e-05  (1e-05)
     | > decoder_loss: 0.4674304127693176  (0.4604331617769988)
     | > postnet_loss: 0.3927381932735443  (0.38899026357609295)
     | > stopnet_loss: 0.006720614619553089  (0.00976475605579174)
     | > loss: 0.2217627614736557  (0.22212061350760254)
     | > align_error: 0.637677013874054  (0.6713669416697128)
     | > grad_norm: tensor(0.2155, device='cuda:0')  (tensor(0.2753, device='cuda:0'))
     | > step_time: 0.788  (0.61609002818232)
     | > loader_time: 1.0508  (0.7947673382966415)


   --> TIME: 2025-12-28 23:31:07 -- STEP: 48/150 -- GLOBAL_STEP: 26775
     | > current_lr: 1e-05  (1.0000000000000011e-05)
     | > decoder_loss: 0.47272789478302  (0.4685389207055171)
     | > postnet_loss: 0.3909240663051605  (0.3919524612526099)
     | > stopnet_loss: 0.004440500866621733  (0.00758109035086818)
     | > loss: 0.22035349905490875  (0.2227039374411106)
     | > align_error: 0.6240514516830444  (0.6490913809587558)
     | > grad_norm: tensor(0.4900, device='cuda:0')  (tensor(0.3442, device='cuda:0'))
     | > step_time: 1.1791  (0.8315410713354746)
     | > loader_time: 1.2574  (0.9714942077795664)


   --> TIME: 2025-12-28 23:32:17 -- STEP: 73/150 -- GLOBAL_STEP: 26800
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4771564304828644  (0.4720360742856378)
     | > postnet_loss: 0.3899543583393097  (0.39221900905648316)
     | > stopnet_loss: 0.0037503859493881464  (0.006416974078914891)
     | > loss: 0.22052808105945587  (0.22248074616471383)
     | > align_error: 0.6474441587924957  (0.6368522991056311)
     | > grad_norm: tensor(0.1443, device='cuda:0')  (tensor(0.3079, device='cuda:0'))
     | > step_time: 1.5094  (1.0181828655608713)
     | > loader_time: 1.6405  (1.1231812157043042)


   --> TIME: 2025-12-28 23:33:48 -- STEP: 98/150 -- GLOBAL_STEP: 26825
     | > current_lr: 1e-05  (1.0000000000000018e-05)
     | > decoder_loss: 0.4837760627269745  (0.473546668583033)
     | > postnet_loss: 0.39373335242271423  (0.39168411919048857)
     | > stopnet_loss: 0.003886578371748328  (0.005725414608605206)
     | > loss: 0.2232639342546463  (0.22203311263298503)
     | > align_error: 0.6087539494037628  (0.6317653890166965)
     | > grad_norm: tensor(0.2214, device='cuda:0')  (tensor(0.2847, device='cuda:0'))
     | > step_time: 1.7525  (1.1874015988135824)
     | > loader_time: 2.2282  (1.3372483521091698)


   --> TIME: 2025-12-28 23:35:20 -- STEP: 123/150 -- GLOBAL_STEP: 26850
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.47679972648620605  (0.4747619922083568)
     | > postnet_loss: 0.3868982791900635  (0.39130450676127176)
     | > stopnet_loss: 0.003240973921492696  (0.005234585893226833)
     | > loss: 0.21916547417640686  (0.2217512117411063)
     | > align_error: 0.6006975769996643  (0.6271822534925572)
     | > grad_norm: tensor(0.1545, device='cuda:0')  (tensor(0.2693, device='cuda:0'))
     | > step_time: 2.0049  (1.321541460548959)
     | > loader_time: 1.882  (1.4353865200911113)


   --> TIME: 2025-12-28 23:37:07 -- STEP: 148/150 -- GLOBAL_STEP: 26875
     | > current_lr: 1e-05  (1.000000000000002e-05)
     | > decoder_loss: 0.49173930287361145  (0.47617242163097534)
     | > postnet_loss: 0.39573022723197937  (0.3911653686616873)
     | > stopnet_loss: 0.0026210970245301723  (0.00486133259412757)
     | > loss: 0.22448848187923431  (0.22169578075408936)
     | > align_error: 0.6111819744110107  (0.6235383527504431)
     | > grad_norm: tensor(0.1497, device='cuda:0')  (tensor(0.2565, device='cuda:0'))
     | > step_time: 2.9233  (1.4769527235546627)
     | > loader_time: 2.6503  (1.5375197851980058)


 > EVALUATION

   --> STEP: 0
     | > decoder_loss: 0.4555041790008545  (0.4555041790008545)
     | > postnet_loss: 0.331533282995224  (0.331533282995224)
     | > stopnet_loss: 0.0120414849370718  (0.0120414849370718)
     | > loss: 0.20880085229873657  (0.20880085229873657)
     | > align_error: 0.718720018863678  (0.718720018863678)

   --> STEP: 1
     | > decoder_loss: 0.43696343898773193  (0.43696343898773193)
     | > postnet_loss: 0.3190098702907562  (0.3190098702907562)
     | > stopnet_loss: 0.00961808767169714  (0.00961808767169714)
     | > loss: 0.19861142337322235  (0.19861142337322235)
     | > align_error: 0.6585479378700256  (0.6585479378700256)

   --> STEP: 2
     | > decoder_loss: 0.4347834289073944  (0.43587343394756317)
     | > postnet_loss: 0.3114264905452728  (0.3152181804180145)
     | > stopnet_loss: 0.01101071946322918  (0.01031440356746316)
     | > loss: 0.19756320118904114  (0.19808731228113174)
     | > align_error: 0.6543727219104767  (0.6564603298902512)

   --> STEP: 3
     | > decoder_loss: 0.43723392486572266  (0.436326930920283)
     | > postnet_loss: 0.31023237109184265  (0.3135562439759572)
     | > stopnet_loss: 0.008031822741031647  (0.009553543291985989)
     | > loss: 0.19489839673042297  (0.19702434043089548)
     | > align_error: 0.7339235842227936  (0.6822814146677653)

   --> STEP: 4
     | > decoder_loss: 0.4416689872741699  (0.43766244500875473)
     | > postnet_loss: 0.3177734911441803  (0.314610555768013)
     | > stopnet_loss: 0.008170420303940773  (0.009207762544974685)
     | > loss: 0.19803103804588318  (0.1972760148346424)
     | > align_error: 0.6022282838821411  (0.6622681319713593)

   --> STEP: 5
     | > decoder_loss: 0.4230964779853821  (0.4347492516040802)
     | > postnet_loss: 0.3001072108745575  (0.3117098867893219)
     | > stopnet_loss: 0.00796513631939888  (0.008959237299859524)
     | > loss: 0.18876604735851288  (0.1955740213394165)
     | > align_error: 0.6404746174812317  (0.6579094290733337)

   --> STEP: 6
     | > decoder_loss: 0.4417153596878052  (0.43591026961803436)
     | > postnet_loss: 0.31245356798171997  (0.31183383365472156)
     | > stopnet_loss: 0.007183357607573271  (0.008663257351145148)
     | > loss: 0.19572558999061584  (0.19559928278128305)
     | > align_error: 0.5925092101097107  (0.6470093925793966)

   --> STEP: 7
     | > decoder_loss: 0.4540301263332367  (0.43849882057734896)
     | > postnet_loss: 0.3134984076023102  (0.3120716299329485)
     | > stopnet_loss: 0.006075466517359018  (0.008293572946318559)
     | > loss: 0.1979576051235199  (0.19593618597303117)
     | > align_error: 0.5779826045036316  (0.6371484228542873)

   --> STEP: 8
     | > decoder_loss: 0.4476526975631714  (0.4396430552005768)
     | > postnet_loss: 0.3135039806365967  (0.31225067377090454)
     | > stopnet_loss: 0.0070449975319206715  (0.008137501019518822)
     | > loss: 0.1973341703414917  (0.19611093401908875)
     | > align_error: 0.5738270878791809  (0.629233255982399)

   --> STEP: 9
     | > decoder_loss: 0.44472476840019226  (0.44020769000053406)
     | > postnet_loss: 0.31287744641304016  (0.3123203151755863)
     | > stopnet_loss: 0.0065576317720115185  (0.00796195999201801)
     | > loss: 0.1959581822156906  (0.19609396159648895)
     | > align_error: 0.5895934104919434  (0.6248288287056817)

   --> STEP: 10
     | > decoder_loss: 0.468871146440506  (0.44307403564453124)
     | > postnet_loss: 0.32645002007484436  (0.31373328566551206)
     | > stopnet_loss: 0.00553104979917407  (0.007718868972733617)
     | > loss: 0.20436133444309235  (0.1969206988811493)
     | > align_error: 0.5823639631271362  (0.6205823421478271)

   --> STEP: 11
     | > decoder_loss: 0.4556357264518738  (0.44421600753610785)
     | > postnet_loss: 0.3164440393447876  (0.3139797178181735)
     | > stopnet_loss: 0.005921622738242149  (0.007555482951416211)
     | > loss: 0.19894155859947205  (0.19710441340099683)
     | > align_error: 0.5938394367694855  (0.6181511689316143)

   --> STEP: 12
     | > decoder_loss: 0.4525427222251892  (0.4449099004268646)
     | > postnet_loss: 0.3105911910533905  (0.31369734058777493)
     | > stopnet_loss: 0.007833847776055336  (0.0075786800201361375)
     | > loss: 0.19861732423305511  (0.19723048930366835)
     | > align_error: 0.586386501789093  (0.6155041133364042)

   --> STEP: 13
     | > decoder_loss: 0.44225382804870605  (0.44470558716700626)
     | > postnet_loss: 0.3101767599582672  (0.31342652669319737)
     | > stopnet_loss: 0.005531053524464369  (0.007421170289699848)
     | > loss: 0.19363869726657867  (0.1969541976085076)
     | > align_error: 0.584227979183197  (0.6130982568630805)

   --> STEP: 14
     | > decoder_loss: 0.45859071612358093  (0.4456973820924759)
     | > postnet_loss: 0.31730449199676514  (0.3137035242148808)
     | > stopnet_loss: 0.004851433448493481  (0.007237617658185107)
     | > loss: 0.19882524013519287  (0.19708784350327083)
     | > align_error: 0.5537716150283813  (0.6088606395891735)

   --> STEP: 15
     | > decoder_loss: 0.45141318440437317  (0.4460784355799357)
     | > postnet_loss: 0.3130338788032532  (0.31365888118743895)
     | > stopnet_loss: 0.004946073051542044  (0.007084848017742237)
     | > loss: 0.19605784118175507  (0.19701917668183644)
     | > align_error: 0.5874737501144409  (0.6074348469575246)

   --> STEP: 16
     | > decoder_loss: 0.45255225896835327  (0.4464830495417118)
     | > postnet_loss: 0.3077771067619324  (0.3132912702858448)
     | > stopnet_loss: 0.005250954534858465  (0.006970229675062001)
     | > loss: 0.1953333020210266  (0.19691380951553583)
     | > align_error: 0.6046715974807739  (0.6072621438652277)

   --> STEP: 17
     | > decoder_loss: 0.45878493785858154  (0.44720669003093944)
     | > postnet_loss: 0.31618979573249817  (0.3134617717827068)
     | > stopnet_loss: 0.004737769719213247  (0.006838908501188545)
     | > loss: 0.19848144054412842  (0.19700602310545304)
     | > align_error: 0.5576420724391937  (0.6043433161342845)

   --> STEP: 18
     | > decoder_loss: 0.45220333337783813  (0.44748428132798934)
     | > postnet_loss: 0.3074626624584198  (0.3131284879313575)
     | > stopnet_loss: 0.005191992502659559  (0.006747413167936934)
     | > loss: 0.19510848820209503  (0.19690060449971092)
     | > align_error: 0.6030635237693787  (0.6042722165584564)

   --> STEP: 19
     | > decoder_loss: 0.44737598299980164  (0.44747858141597946)
     | > postnet_loss: 0.30607569217681885  (0.3127572881548028)
     | > stopnet_loss: 0.004666790831834078  (0.0066379067291946784)
     | > loss: 0.1930297166109085  (0.196696873558195)
     | > align_error: 0.5979107022285461  (0.6039374000147769)

   --> STEP: 20
     | > decoder_loss: 0.4461645185947418  (0.4474128782749176)
     | > postnet_loss: 0.30368325114250183  (0.31230358630418775)
     | > stopnet_loss: 0.004418055061250925  (0.006526914145797491)
     | > loss: 0.191880002617836  (0.19645603001117706)
     | > align_error: 0.6221844255924225  (0.6048497512936593)

   --> STEP: 21
     | > decoder_loss: 0.44426363706588745  (0.44726291440782096)
     | > postnet_loss: 0.302995890378952  (0.3118603626887004)
     | > stopnet_loss: 0.003913224209100008  (0.006402452720240468)
     | > loss: 0.190728098154068  (0.19618327135131472)
     | > align_error: 0.5587114691734314  (0.602652690240315)

   --> STEP: 22
     | > decoder_loss: 0.4447617530822754  (0.4471492252566598)
     | > postnet_loss: 0.3047291338443756  (0.31153621592304925)
     | > stopnet_loss: 0.00453157676383853  (0.0063174129040403796)
     | > loss: 0.19190429151058197  (0.19598877226764505)
     | > align_error: 0.6241322159767151  (0.6036290323192423)

   --> STEP: 23
     | > decoder_loss: 0.41992589831352234  (0.44596560234608856)
     | > postnet_loss: 0.29342228174209595  (0.3107486535673556)
     | > stopnet_loss: 0.004437548108398914  (0.006235679652055968)
     | > loss: 0.1827745884656906  (0.1954142425371253)
     | > align_error: 0.5662282109260559  (0.6020029096499733)

   --> STEP: 24
     | > decoder_loss: 0.45372122526168823  (0.4462887533009052)
     | > postnet_loss: 0.3092058002948761  (0.31068436801433563)
     | > stopnet_loss: 0.00439582159742713  (0.006159018899779767)
     | > loss: 0.19512759149074554  (0.19540229874352613)
     | > align_error: 0.5784313678741455  (0.6010207620759804)

   --> STEP: 25
     | > decoder_loss: 0.45284464955329895  (0.446550989151001)
     | > postnet_loss: 0.3063015937805176  (0.3105090570449829)
     | > stopnet_loss: 0.0036478471010923386  (0.006058572027832269)
     | > loss: 0.19343440234661102  (0.19532358288764953)
     | > align_error: 0.556875616312027  (0.5992549562454222)

   --> STEP: 26
     | > decoder_loss: 0.428180456161499  (0.4458444301898663)
     | > postnet_loss: 0.2951807975769043  (0.30991950860390294)
     | > stopnet_loss: 0.004279548302292824  (0.005990148038388445)
     | > loss: 0.1851198673248291  (0.19493113228907952)
     | > align_error: 0.5458059310913086  (0.5971992245087255)

   --> STEP: 27
     | > decoder_loss: 0.42573055624961853  (0.445099471895783)
     | > postnet_loss: 0.2905690371990204  (0.3092028244777962)
     | > stopnet_loss: 0.003874376183375716  (0.005911786117832418)
     | > loss: 0.1829492747783661  (0.19448735978868273)
     | > align_error: 0.5399898290634155  (0.5950803580107511)

   --> STEP: 28
     | > decoder_loss: 0.43044134974479675  (0.4445759675332478)
     | > postnet_loss: 0.2946629524230957  (0.3086835433329855)
     | > stopnet_loss: 0.0038915511686354876  (0.0058396348696468136)
     | > loss: 0.18516764044761658  (0.19415451266935893)
     | > align_error: 0.5654306709766388  (0.5940214406166756)

   --> STEP: 29
     | > decoder_loss: 0.42569682002067566  (0.4439249624466074)
     | > postnet_loss: 0.29131072759628296  (0.30808448072137506)
     | > stopnet_loss: 0.0035209639463573694  (0.0057596806998782115)
     | > loss: 0.18277284502983093  (0.19376204137144418)
     | > align_error: 0.5395496189594269  (0.5921431019388395)

   --> STEP: 30
     | > decoder_loss: 0.4276406764984131  (0.44338215291500094)
     | > postnet_loss: 0.29290708899497986  (0.3075785676638285)
     | > stopnet_loss: 0.002820363035425544  (0.005661703444396456)
     | > loss: 0.18295730650424957  (0.19340188354253768)
     | > align_error: 0.5328541994094849  (0.590166805187861)

   --> STEP: 31
     | > decoder_loss: 0.42230328917503357  (0.44270218956855034)
     | > postnet_loss: 0.29030513763427734  (0.30702136024352045)
     | > stopnet_loss: 0.0036369548179209232  (0.005596388972574665)
     | > loss: 0.1817890703678131  (0.19302727666593367)
     | > align_error: 0.5543322861194611  (0.5890108529598481)

   --> STEP: 32
     | > decoder_loss: 0.4363372325897217  (0.44250328466296196)
     | > postnet_loss: 0.2980196475982666  (0.30674005672335625)
     | > stopnet_loss: 0.003766021691262722  (0.0055391899950336665)
     | > loss: 0.18735523521900177  (0.19285002537071705)
     | > align_error: 0.5296905636787415  (0.5871570939198135)

   --> STEP: 33
     | > decoder_loss: 0.4314930737018585  (0.4421696419065649)
     | > postnet_loss: 0.2946406304836273  (0.30637340744336444)
     | > stopnet_loss: 0.003989566117525101  (0.005492231695715225)
     | > loss: 0.18552298843860626  (0.19262799394853186)
     | > align_error: 0.5450994074344635  (0.5858826185717726)

   --> STEP: 34
     | > decoder_loss: 0.43664315342903137  (0.4420070981278139)
     | > postnet_loss: 0.2959282100200653  (0.3060661957544439)
     | > stopnet_loss: 0.0032131520565599203  (0.005425199941622422)
     | > loss: 0.18635599315166473  (0.19244352333685932)
     | > align_error: 0.5628983378410339  (0.5852066103149862)

   --> STEP: 35
     | > decoder_loss: 0.4343237578868866  (0.4417875741209303)
     | > postnet_loss: 0.29495561122894287  (0.3057487504822867)
     | > stopnet_loss: 0.0034405887126922607  (0.0053684967636529884)
     | > loss: 0.18576043844223022  (0.19225257805415563)
     | > align_error: 0.531984955072403  (0.5836859915937695)

   --> STEP: 36
     | > decoder_loss: 0.4401416480541229  (0.44174185395240784)
     | > postnet_loss: 0.29945242404937744  (0.30557385252581704)
     | > stopnet_loss: 0.003592726308852434  (0.005319169806575196)
     | > loss: 0.18849125504493713  (0.1921480968594551)
     | > align_error: 0.6327694356441498  (0.585049420595169)

   --> STEP: 37
     | > decoder_loss: 0.4331750273704529  (0.4415103180988415)
     | > postnet_loss: 0.2960461676120758  (0.30531634752814835)
     | > stopnet_loss: 0.0034769317135214806  (0.005269379587844014)
     | > loss: 0.18578223884105682  (0.19197604664274165)
     | > align_error: 0.5178088545799255  (0.5832321080001623)

   --> STEP: 38
     | > decoder_loss: 0.4201350510120392  (0.44094781107024145)
     | > postnet_loss: 0.2884904444217682  (0.3048735606042962)
     | > stopnet_loss: 0.003111551282927394  (0.0052125946324514715)
     | > loss: 0.18026793003082275  (0.19166793831084905)
     | > align_error: 0.5508396029472351  (0.5823796736566642)

   --> STEP: 39
     | > decoder_loss: 0.4365159869194031  (0.4408341745535533)
     | > postnet_loss: 0.2996504008769989  (0.30473963343180144)
     | > stopnet_loss: 0.0034014780540019274  (0.0051661557458245605)
     | > loss: 0.1874430626630783  (0.1915596081660344)
     | > align_error: 0.5449427962303162  (0.5814197537226553)

   --> STEP: 40
     | > decoder_loss: 0.43332016468048096  (0.44064632430672646)
     | > postnet_loss: 0.2978785037994385  (0.30456810519099237)
     | > stopnet_loss: 0.002985662082210183  (0.005111643404234201)
     | > loss: 0.18578532338142395  (0.19141525104641915)
     | > align_error: 0.5826427638530731  (0.5814503289759158)

   --> STEP: 41
     | > decoder_loss: 0.42377880215644836  (0.4402349213274514)
     | > postnet_loss: 0.2901473343372345  (0.304216379072608)
     | > stopnet_loss: 0.0036896774545311928  (0.005076961307899981)
     | > loss: 0.18217121064662933  (0.19118978664642428)
     | > align_error: 0.5017551481723785  (0.5795065440782685)

   --> STEP: 42
     | > decoder_loss: 0.42923274636268616  (0.43997296478067127)
     | > postnet_loss: 0.29254838824272156  (0.3039385697671345)
     | > stopnet_loss: 0.0032487993594259024  (0.005033433642460122)
     | > loss: 0.18369407951831818  (0.19101131742908842)
     | > align_error: 0.5783993601799011  (0.5794801825568788)

   --> STEP: 43
     | > decoder_loss: 0.4273931086063385  (0.43968040998591934)
     | > postnet_loss: 0.29089945554733276  (0.3036353345527205)
     | > stopnet_loss: 0.002869445364922285  (0.004983108333680172)
     | > loss: 0.1824425905942917  (0.1908120447120001)
     | > align_error: 0.5507237315177917  (0.5788114278815513)

   --> STEP: 44
     | > decoder_loss: 0.4455253481864929  (0.43981324949047784)
     | > postnet_loss: 0.30189454555511475  (0.3035957711664113)
     | > stopnet_loss: 0.0026008784770965576  (0.0049289667460305445)
     | > loss: 0.18945585191249847  (0.1907812221483751)
     | > align_error: 0.5497948229312897  (0.5781519595872271)

   --> STEP: 45
     | > decoder_loss: 0.43941551446914673  (0.4398044109344482)
     | > postnet_loss: 0.3016175925731659  (0.3035518116421169)
     | > stopnet_loss: 0.0032678234856575727  (0.00489205245135559)
     | > loss: 0.18852609395980835  (0.19073110818862915)
     | > align_error: 0.5512584745883942  (0.577554326587253)

   --> STEP: 46
     | > decoder_loss: 0.42897337675094604  (0.4395689536695895)
     | > postnet_loss: 0.2922857999801636  (0.3033068983451179)
     | > stopnet_loss: 0.003145578783005476  (0.0048540856324784136)
     | > loss: 0.18346036970615387  (0.19057304865640143)

warning: audio amplitude out of range, auto clipped.